Use make docker image
cilium/cilium pull request #1000
Opened 2017-06-19 23:42 UTC by aanm

2017-06-22 04:33 UTC, ianvernon approved these changes

2017-06-22 16:24 UTC, tgraf requested changes

2017-06-22 16:24 UTC, tgraf commented on contrib/packaging/docker/Makefile
> +	docker build -t "cilium:local_build" $(BUILDDIR)
Let's make this an environment variable which defaults to `"latest"` instead. The relevant build script can then set that to `"local_build"`. This way the Makefile can be used outside of the automated build system as well.

2017-06-27 04:12 UTC, tgraf approved these changes
Awesome work! 💯

2017-06-27 04:12 UTC, merged