bpf: add missing '__inline__' flag for a few functions
cilium/cilium pull request #10017
Opened 2020-02-01 15:23 UTC by zhiyuan0x

Signed-off-by: Zhiyuan Hou <zhiyuan2048@linux.alibaba.com>

2020-02-02 19:17 UTC, vadorovsky requested changes
Hi @zhiyuan0x! Thanks for you contribution. I grepped the code and I see that there are more `__inline__` flags missing. Would you mind add them as well?

```
 mrostecki   master  …  github.com  cilium  cilium  git grep -n "static inline" | grep -v __inline__ | grep -v vendor | grep -v Documentation
bpf/bpf_lxc.c:61:static inline bool redirect_to_proxy(int verdict, __u8 dir)
bpf/bpf_lxc.c:69:static inline int ipv6_l3_from_lxc(struct __sk_buff *skb,
bpf/bpf_lxc.c:419:static inline int handle_ipv4_from_lxc(struct __sk_buff *skb, __u32 *dstID)
bpf/bpf_netdev.c:55:static inline int rewrite_dmac_to_host(struct __sk_buff *skb, __u32 src_identity)
bpf/bpf_netdev.c:71:static inline __u32 finalize_sec_ctx(__u32 secctx, __u32 src_identity)
bpf/bpf_netdev.c:86:static inline __u32 derive_sec_ctx(struct __sk_buff *skb, const union v6addr *node_ip,
bpf/bpf_netdev.c:111:static inline int handle_ipv6(struct __sk_buff *skb, __u32 src_identity)
bpf/bpf_netdev.c:276:static inline __u32 derive_ipv4_sec_ctx(struct __sk_buff *skb, struct iphdr *ip4)
bpf/bpf_netdev.c:285:static inline int handle_ipv4(struct __sk_buff *skb, __u32 src_identity)
bpf/bpf_network.c:39:static inline int handle_ipv6(struct __sk_buff *skb)
bpf/bpf_network.c:77:static inline int handle_ipv4(struct __sk_buff *skb)
bpf/bpf_overlay.c:42:static inline int handle_ipv6(struct __sk_buff *skb, __u32 *identity)
bpf/bpf_overlay.c:162:static inline int handle_ipv4(struct __sk_buff *skb, __u32 *identity)
bpf/cilium-map-migrate.c:117:static inline __u64 bpf_ptr_to_u64(const void *ptr)
bpf/lib/arp.h:35:static inline int arp_check(struct ethhdr *eth, struct arphdr *arp,
bpf/lib/arp.h:45:static inline int arp_prepare_response(struct __sk_buff *skb, struct ethhdr *eth,
bpf/lib/arp.h:65:static inline int arp_respond(struct __sk_buff *skb, union macaddr *mac, int direction)
bpf/lib/common.h:112:static inline bool validate_ethertype(struct __sk_buff *skb, __u16 *proto)
bpf/lib/common.h:129:static inline bool __revalidate_data(struct __sk_buff *skb, void **data_,
bpf/lib/common.h:674:static inline void relax_verifier(void)
bpf/lib/common.h:680:static inline int redirect_self(struct __sk_buff *skb)
bpf/lib/common.h:695:static inline int redirect_peer(int ifindex, uint32_t flags)
bpf/lib/conntrack.h:47:static inline bool conn_is_dns(__u16 dport)
bpf/lib/conntrack.h:193:static inline bool __ct_entry_keep_alive(void *map, void *tuple)
bpf/lib/conntrack.h:485:static inline void ct4_cilium_dbg_tuple(struct __sk_buff *skb, __u8 type,
bpf/lib/conntrack_map.h:54:static inline struct bpf_elf_map *
bpf/lib/conntrack_map.h:87:static inline struct bpf_elf_map *
bpf/lib/csum.h:45:static inline void csum_l4_offset_and_flags(__u8 nexthdr, struct csum_offset *off)
bpf/lib/csum.h:75:static inline int csum_l4_replace(struct __sk_buff *skb, int l4_off, struct csum_offset *csum,
bpf/lib/dbg.h:162:static inline void cilium_dbg(struct __sk_buff *skb, __u8 type, __u32 arg1, __u32 arg2)
bpf/lib/dbg.h:177:static inline void cilium_dbg3(struct __sk_buff *skb, __u8 type, __u32 arg1,
bpf/lib/dbg.h:200:static inline void cilium_dbg_capture2(struct __sk_buff *skb, __u8 type, __u32 arg1, __u32 arg2)
bpf/lib/dbg.h:221:static inline void cilium_dbg_capture(struct __sk_buff *skb, __u8 type, __u32 arg1)
bpf/lib/dbg.h:231:static inline void cilium_dbg(struct __sk_buff *skb, __u8 type, __u32 arg1, __u32 arg2)
bpf/lib/dbg.h:235:static inline void cilium_dbg3(struct __sk_buff *skb, __u8 type, __u32 arg1,
bpf/lib/dbg.h:240:static inline void cilium_dbg_capture(struct __sk_buff *skb, __u8 type, __u32 arg1)
bpf/lib/dbg.h:244:static inline void cilium_dbg_capture2(struct __sk_buff *skb, __u8 type, __u32 arg1, __u32 arg2)
bpf/lib/drop.h:91:static inline int send_drop_notify(struct __sk_buff *skb, __u32 src, __u32 dst,
bpf/lib/drop.h:109:static inline int send_drop_notify(struct __sk_buff *skb, __u32 src, __u32 dst,
bpf/lib/drop.h:118:static inline int send_drop_notify_error(struct __sk_buff *skb, __u32 src, int error,
bpf/lib/eth.h:39:static inline int eth_addrcmp(const union macaddr *a, const union macaddr *b)
bpf/lib/eth.h:50:static inline int eth_is_bcast(const union macaddr *a)
bpf/lib/eth.h:63:static inline int eth_load_saddr(struct __sk_buff *skb, __u8 *mac, int off)
bpf/lib/eth.h:68:static inline int eth_store_saddr(struct __sk_buff *skb, __u8 *mac, int off)
bpf/lib/eth.h:73:static inline int eth_load_daddr(struct __sk_buff *skb, __u8 *mac, int off)
bpf/lib/eth.h:78:static inline int eth_store_daddr(struct __sk_buff *skb, __u8 *mac, int off)
bpf/lib/icmp6.h:38:static inline __u8 icmp6_load_type(struct __sk_buff *skb, int nh_off)
bpf/lib/icmp6.h:87:static inline int __icmp6_send_echo_reply(struct __sk_buff *skb, int nh_off)
bpf/lib/icmp6.h:143:static inline int icmp6_send_echo_reply(struct __sk_buff *skb, int nh_off,
bpf/lib/icmp6.h:153:static inline int send_icmp6_ndisc_adv(struct __sk_buff *skb, int nh_off,
bpf/lib/icmp6.h:208:static inline __be32 compute_icmp6_csum(char data[80], __u16 payload_len,
bpf/lib/icmp6.h:224:static inline int __icmp6_send_time_exceeded(struct __sk_buff *skb, int nh_off)
bpf/lib/icmp6.h:332:static inline int icmp6_send_time_exceeded(struct __sk_buff *skb, int nh_off, __u8 direction)
bpf/lib/icmp6.h:342:static inline int __icmp6_handle_ns(struct __sk_buff *skb, int nh_off)
bpf/lib/icmp6.h:386:static inline int icmp6_handle_ns(struct __sk_buff *skb, int nh_off, __u8 direction)
bpf/lib/icmp6.h:396:static inline int icmp6_handle(struct __sk_buff *skb, int nh_off,
bpf/lib/identity.h:41:static inline bool identity_is_reserved(__u32 identity)
bpf/lib/ipv4.h:25:static inline int ipv4_load_daddr(struct __sk_buff *skb, int off, __u32 *dst)
bpf/lib/ipv4.h:30:static inline int ipv4_dec_ttl(struct __sk_buff *skb, int off, struct iphdr *ip4)
bpf/lib/ipv4.h:45:static inline int ipv4_hdrlen(struct iphdr *ip4)
bpf/lib/ipv4.h:50:static inline bool ipv4_is_fragment(struct iphdr *ip4)
bpf/lib/ipv6.h:51:static inline int ipv6_optlen(struct ipv6_opt_hdr *opthdr)
bpf/lib/ipv6.h:56:static inline int ipv6_authlen(struct ipv6_opt_hdr *opthdr)
bpf/lib/ipv6.h:100:static inline void ipv6_addr_copy(union v6addr *dst, union v6addr *src)
bpf/lib/ipv6.h:106:static inline __u64 ipv6_addrcmp(union v6addr *a, union v6addr *b)
bpf/lib/ipv6.h:117:static inline int ipv6_addr_in_net(union v6addr *addr, union v6addr *net, union v6addr *mask)
bpf/lib/ipv6.h:131:static inline void ipv6_addr_clear_suffix(union v6addr *addr, int prefix)
bpf/lib/ipv6.h:143:static inline int ipv6_match_prefix_64(const union v6addr *addr, const union v6addr *prefix)
bpf/lib/ipv6.h:154:static inline int ipv6_dec_hoplimit(struct __sk_buff *skb, int off)
bpf/lib/ipv6.h:169:static inline int ipv6_load_saddr(struct __sk_buff *skb, int off, union v6addr *dst)
bpf/lib/ipv6.h:176:static inline int ipv6_store_saddr(struct __sk_buff *skb, __u8 *addr, int off)
bpf/lib/ipv6.h:181:static inline int ipv6_load_daddr(struct __sk_buff *skb, int off, union v6addr *dst)
bpf/lib/ipv6.h:188:static inline int ipv6_store_daddr(struct __sk_buff *skb, __u8 *addr, int off)
bpf/lib/ipv6.h:193:static inline int ipv6_load_nexthdr(struct __sk_buff *skb, int off, __u8 *nexthdr)
bpf/lib/ipv6.h:200:static inline int ipv6_store_nexthdr(struct __sk_buff *skb, __u8 *nexthdr, int off)
bpf/lib/ipv6.h:206:static inline int ipv6_load_paylen(struct __sk_buff *skb, int off, __be16 *len)
bpf/lib/ipv6.h:213:static inline int ipv6_store_paylen(struct __sk_buff *skb, int off, __be16 *len)
bpf/lib/ipv6.h:219:static inline int ipv6_store_flowlabel(struct __sk_buff *skb, int off, __be32 label)
bpf/lib/ipv6.h:236:static inline __be32 ipv6_pseudohdr_checksum(struct ipv6hdr *hdr,
bpf/lib/ipv6.h:253:static inline int ipv6_addr_is_mapped(union v6addr *addr)
bpf/lib/l3.h:74:static inline int ipv6_local_delivery(struct __sk_buff *skb, int l3_off, int l4_off,
bpf/lib/l4.h:50:static inline int l4_modify_port(struct __sk_buff *skb, int l4_off, int off,
bpf/lib/l4.h:62:static inline int l4_load_port(struct __sk_buff *skb, int off, __be16 *por [...]

2020-02-03 02:32 UTC, zhiyuan0x commented
> Hi @zhiyuan0x! Thanks for you contribution. I grepped the code and I see that there are more `__inline__` flags missing. Would you mind add them as well?
> 
> ```
>  mrostecki   master  …  github.com  cilium  cilium  git grep -n "static inline" | grep -v __inline__ | grep -v vendor | grep -v Documentation
> bpf/bpf_lxc.c:61:static inline bool redirect_to_proxy(int verdict, __u8 dir)
> bpf/bpf_lxc.c:69:static inline int ipv6_l3_from_lxc(struct __sk_buff *skb,
> bpf/bpf_lxc.c:419:static inline int handle_ipv4_from_lxc(struct __sk_buff *skb, __u32 *dstID)
> bpf/bpf_netdev.c:55:static inline int rewrite_dmac_to_host(struct __sk_buff *skb, __u32 src_identity)
> bpf/bpf_netdev.c:71:static inline __u32 finalize_sec_ctx(__u32 secctx, __u32 src_identity)
> bpf/bpf_netdev.c:86:static inline __u32 derive_sec_ctx(struct __sk_buff *skb, const union v6addr *node_ip,
> bpf/bpf_netdev.c:111:static inline int handle_ipv6(struct __sk_buff *skb, __u32 src_identity)
> bpf/bpf_netdev.c:276:static inline __u32 derive_ipv4_sec_ctx(struct __sk_buff *skb, struct iphdr *ip4)
> bpf/bpf_netdev.c:285:static inline int handle_ipv4(struct __sk_buff *skb, __u32 src_identity)
> bpf/bpf_network.c:39:static inline int handle_ipv6(struct __sk_buff *skb)
> bpf/bpf_network.c:77:static inline int handle_ipv4(struct __sk_buff *skb)
> bpf/bpf_overlay.c:42:static inline int handle_ipv6(struct __sk_buff *skb, __u32 *identity)
> bpf/bpf_overlay.c:162:static inline int handle_ipv4(struct __sk_buff *skb, __u32 *identity)
> bpf/cilium-map-migrate.c:117:static inline __u64 bpf_ptr_to_u64(const void *ptr)
> bpf/lib/arp.h:35:static inline int arp_check(struct ethhdr *eth, struct arphdr *arp,
> bpf/lib/arp.h:45:static inline int arp_prepare_response(struct __sk_buff *skb, struct ethhdr *eth,
> bpf/lib/arp.h:65:static inline int arp_respond(struct __sk_buff *skb, union macaddr *mac, int direction)
> bpf/lib/common.h:112:static inline bool validate_ethertype(struct __sk_buff *skb, __u16 *proto)
> bpf/lib/common.h:129:static inline bool __revalidate_data(struct __sk_buff *skb, void **data_,
> bpf/lib/common.h:674:static inline void relax_verifier(void)
> bpf/lib/common.h:680:static inline int redirect_self(struct __sk_buff *skb)
> bpf/lib/common.h:695:static inline int redirect_peer(int ifindex, uint32_t flags)
> bpf/lib/conntrack.h:47:static inline bool conn_is_dns(__u16 dport)
> bpf/lib/conntrack.h:193:static inline bool __ct_entry_keep_alive(void *map, void *tuple)
> bpf/lib/conntrack.h:485:static inline void ct4_cilium_dbg_tuple(struct __sk_buff *skb, __u8 type,
> bpf/lib/conntrack_map.h:54:static inline struct bpf_elf_map *
> bpf/lib/conntrack_map.h:87:static inline struct bpf_elf_map *
> bpf/lib/csum.h:45:static inline void csum_l4_offset_and_flags(__u8 nexthdr, struct csum_offset *off)
> bpf/lib/csum.h:75:static inline int csum_l4_replace(struct __sk_buff *skb, int l4_off, struct csum_offset *csum,
> bpf/lib/dbg.h:162:static inline void cilium_dbg(struct __sk_buff *skb, __u8 type, __u32 arg1, __u32 arg2)
> bpf/lib/dbg.h:177:static inline void cilium_dbg3(struct __sk_buff *skb, __u8 type, __u32 arg1,
> bpf/lib/dbg.h:200:static inline void cilium_dbg_capture2(struct __sk_buff *skb, __u8 type, __u32 arg1, __u32 arg2)
> bpf/lib/dbg.h:221:static inline void cilium_dbg_capture(struct __sk_buff *skb, __u8 type, __u32 arg1)
> bpf/lib/dbg.h:231:static inline void cilium_dbg(struct __sk_buff *skb, __u8 type, __u32 arg1, __u32 arg2)
> bpf/lib/dbg.h:235:static inline void cilium_dbg3(struct __sk_buff *skb, __u8 type, __u32 arg1,
> bpf/lib/dbg.h:240:static inline void cilium_dbg_capture(struct __sk_buff *skb, __u8 type, __u32 arg1)
> bpf/lib/dbg.h:244:static inline void cilium_dbg_capture2(struct __sk_buff *skb, __u8 type, __u32 arg1, __u32 arg2)
> bpf/lib/drop.h:91:static inline int send_drop_notify(struct __sk_buff *skb, __u32 src, __u32 dst,
> bpf/lib/drop.h:109:static inline int send_drop_notify(struct __sk_buff *skb, __u32 src, __u32 dst,
> bpf/lib/drop.h:118:static inline int send_drop_notify_error(struct __sk_buff *skb, __u32 src, int error,
> bpf/lib/eth.h:39:static inline int eth_addrcmp(const union macaddr *a, const union macaddr *b)
> bpf/lib/eth.h:50:static inline int eth_is_bcast(const union macaddr *a)
> bpf/lib/eth.h:63:static inline int eth_load_saddr(struct __sk_buff *skb, __u8 *mac, int off)
> bpf/lib/eth.h:68:static inline int eth_store_saddr(struct __sk_buff *skb, __u8 *mac, int off)
> bpf/lib/eth.h:73:static inline int eth_load_daddr(struct __sk_buff *skb, __u8 *mac, int off)
> bpf/lib/eth.h:78:static inline int eth_store_daddr(struct __sk_buff *skb, __u8 *mac, int off)
> bpf/lib/icmp6.h:38:static inline __u8 icmp6_load_type(struct __sk_buff *skb, int nh_off)
> bpf/lib/icmp6.h:87:static inline int __icmp6_send_echo_reply(struct __sk_buff *skb, int nh_off)
> bpf/lib/icmp6.h:143:static inline int icmp6_send_echo_reply(struct __sk_buff *skb, int nh_off,
> bpf/lib/icmp6.h:153:static inline int send_icmp6_ndisc_adv(struct __sk_buff *skb, int nh_off,
> bpf/lib/icmp6.h:208:static inline __be32 compute_icmp6_csum(char data[80], __u16 payload_len,
> bpf/lib/icmp6.h:224:static inline int __icmp6_send_time_exceeded(struct __sk_buff *skb, int nh_off)
> bpf/lib/icmp6.h:332:static inline int icmp6_send_time_exceeded(struct __sk_buff *skb, int nh_off, __u8 direction)
> bpf/lib/icmp6.h:342:static inline int __icmp6_handle_ns(struct __sk_buff *skb, int nh_off)
> bpf/lib/icmp6.h:386:static inline int icmp6_handle_ns(struct __sk_buff *skb, int nh_off, __u8 direction)
> bpf/lib/icmp6.h:396:static inline int icmp6_handle(struct __sk_buff *skb, int nh_off,
> bpf/lib/identity.h:41:static inline bool identity_is_reserved(__u32 identity)
> bpf/lib/ipv4.h:25:static inline int ipv4_load_daddr(struct __sk_buff *skb, int off, __u32 *dst)
> bpf/lib/ipv4.h:30:static inline int ipv4_dec_ttl(struct __sk_buff *skb, int off, struct iphdr *ip4)
> bpf/lib/ipv4.h:45:static inline int ipv4_hdrlen(struct iphdr *ip4)
> bpf/lib/ipv4.h:50:static inline bool ipv4_is_fragment(struct iphdr *ip4)
> bpf/lib/ipv6.h:51:static inline int ipv6_optlen(struct ipv6_opt_hdr *opthdr)
> bpf/lib/ipv6.h:56:static inline int ipv6_authlen(struct ipv6_opt_hdr *opthdr)
> bpf/lib/ipv6.h:100:static inline void ipv6_addr_copy(union v6addr *dst, union v6addr *src)
> bpf/lib/ipv6.h:106:static inline __u64 ipv6_addrcmp(union v6addr *a, union v6addr *b)
> bpf/lib/ipv6.h:117:static inline int ipv6_addr_in_net(union v6addr *addr, union v6addr *net, union v6addr *mask)
> bpf/lib/ipv6.h:131:static inline void ipv6_addr_clear_suffix(union v6addr *addr, int prefix)
> bpf/lib/ipv6.h:143:static inline int ipv6_match_prefix_64(const union v6addr *addr, const union v6addr *prefix)
> bpf/lib/ipv6.h:154:static inline int ipv6_dec_hoplimit(struct __sk_buff *skb, int off)
> bpf/lib/ipv6.h:169:static inline int ipv6_load_saddr(struct __sk_buff *skb, int off, union v6addr *dst)
> bpf/lib/ipv6.h:176:static inline int ipv6_store_saddr(struct __sk_buff *skb, __u8 *addr, int off)
> bpf/lib/ipv6.h:181:static inline int ipv6_load_daddr(struct __sk_buff *skb, int off, union v6addr *dst)
> bpf/lib/ipv6.h:188:static inline int ipv6_store_daddr(struct __sk_buff *skb, __u8 *addr, int off)
> bpf/lib/ipv6.h:193:static inline int ipv6_load_nexthdr(struct __sk_buff *skb, int off, __u8 *nexthdr)
> bpf/lib/ipv6.h:200:static inline int ipv6_store_nexthdr(struct __sk_buff *skb, __u8 *nexthdr, int off)
> bpf/lib/ipv6.h:206:static inline int ipv6_load_paylen(struct __sk_buff *skb, int off, __be16 *len)
> bpf/lib/ipv6.h:213:static inline int ipv6_store_paylen(struct __sk_buff *skb, int off, __be16 *len)
> bpf/lib/ipv6.h:219:static inline int ipv6_store_flowlabel(struct __sk_buff *skb, int off, __be32 label)
> bpf/lib/ipv6.h:236:static inline __be32 ipv6_pseudohdr_checksum(struct ipv6hdr *hdr,
> bpf/lib/ipv6.h:253:static inline int ipv6_addr_is_mapped(union v6addr *addr)
> bpf/lib/l3.h:74:static inline int ipv6_local_delivery(struct __sk_buff *skb, int l3_off, int l4_off,
> bpf/lib/l4. [...]

2020-02-03 16:25 UTC, zhiyuan0x commented
Hi @mrostecki , missing flag has been added. Please conduct a review, thanks.

2020-02-03 16:28 UTC, zhiyuan0x commented
Hi @mrostecki ,  missing flag has been added.

2020-02-03 18:44 UTC, vadorovsky requested changes
@zhiyuan0x Thanks a lot!

Now I noticed that we have inconsistency in the code. Sometimes we do:

```
static inline bool __inline__ foo() {
```

Sometimes we do:

```
static __always_inline bool foo() {
```

Ideally I think we should have just one macro (one way of enforcing inline) used everywhere. Would you mind to switch all functions either to `__always_inline` or to `__inline__`? Sorry for making your first contribution harder.

The other thing - you need to rebase your branch and solve the conflict in `daemon/bpf.sha`. ;)

/cc @borkmann @joestringer

2020-02-04 16:05 UTC, zhiyuan0x commented
> Ideally I think we should have just one macro (one way of enforcing inline) used everywhere. Would you mind to switch all functions either to `__always_inline` or to `__inline__`? 

Yeah. But these two macros are defined in different files. '\_\_inline\_\_' is in bpf/api.h and '__always_inline' is in lib/common.h. 

bpf/api.h
```c
#ifndef __inline__
# define __inline__		__attribute__((always_inline))
#endif
```

lib/common.h
```c
#ifndef __always_inline
#define __always_inline inline __inline__
#endif
```

In order not to change '#include' statements, I used following policy.
```
IF include 'lib/common.h' THEN
  use '__always_inline'
ELSE IF include 'bpf/api.h' THEN
  use '__inline__'
ELSE
  add '#include <bpf/api.h>'
  use '__inline__' 
END
```

If we want one 'enforcing inline' macro,  I think we can add  '__always_inline' definition to 'bpf/api.h' and use it for functions that miss 'enforcing inline' flags. What's your opinion？

>Sorry for making your first contribution harder.

It doesn't matter ^_^

> The other thing - you need to rebase your branch and solve the conflict in `daemon/bpf.sha`. ;)

Ok, I will do it in next commit.

2020-02-07 17:20 UTC, zhiyuan0x commented
Hi @mrostecki , I recommit this patch and  uses one macro '__always_inline' for all functions that miss 'always inline' flag. Can you conduct a review? Thanks.

2020-02-11 22:46 UTC, vadorovsky approved these changes
Looks good. Thanks! After rebasing I think it can be accepted and merged, since we already have a branch for 1.7.

2020-02-11 22:47 UTC, mrostecki commented
I will run tests after rebasing.

2020-02-11 22:56 UTC, joestringer commented
@mrostecki Just FYI we've been holding off particularly on merging PRs that make changes to `daemon/bpf.sha` until the full 1.7 release just to try to ease backports of any remaining fixes to the 1.7 branch, avoiding needing to fix up the bpf.sha. 

In the v1.8 cycle we'll remove the need for this `bpf.sha` and make this aspect of development easier for everyone.

2020-02-11 22:58 UTC, mrostecki commented
@joestringer 
> In the v1.8 cycle we'll remove the need for this `bpf.sha` and make this aspect of development easier for everyone.

Good to hear that. Are we going to drop usage of go-bindata or what's the idea?

2020-02-11 23:02 UTC, joestringer commented
@mrostecki See https://github.com/cilium/cilium/issues/10075 for more details.

2020-02-15 17:56 UTC, zhiyuan0x commented
Hi @mrostecki 

> I will run tests after rebasing.

I have rebased the branch, Thanks.

2020-02-15 19:38 UTC, joestringer commented
test-me-please

2020-02-18 23:45 UTC, aanm commented
We have lifted the code-freeze since v1.7.0 was released. However @zhiyuan0x this requires rebase against master

2020-02-19 05:13 UTC, zhiyuan0x commented
Hi @aanm , I have rebased the commit.

2020-02-19 06:39 UTC, aanm commented
test-me-please

2020-02-19 08:04 UTC, aanm commented
test-me-please

2020-02-20 08:00 UTC, zhiyuan0x commented
Hi @aanm , I noticed that go-bindata has been removed on latest updates. So I deleted file 'daemon/bpf.sha' and recommitted the patch.

2020-02-20 23:25 UTC, joestringer commented
test-me-please

2020-02-21 12:44 UTC, aanm commented
test-me-please

2020-02-21 23:45 UTC, joestringer commented
Hit known master flakes #10274 , #10276

2020-02-24 08:13 UTC, borkmann commented
@zhiyuan0x Could you rebase your change, there are two conflicts with master. Thanks a lot.

2020-02-24 11:29 UTC, zhiyuan0x commented
> @zhiyuan0x Could you rebase your change, there are two conflicts with master. Thanks a lot.

@borkmann Of course。 I have done.

2020-02-24 11:46 UTC, aanm commented
test-me-please

2020-02-24 21:53 UTC, joestringer commented
There were several build failures for `make -C bpf all BUILD_PERMUTATIONS=1`:

```
04:20:55  In file included from bpf_lxc.c:30:
04:20:55  /go/src/github.com/cilium/cilium/bpf/lib/common.h:683:28: error: unused function 'redirect_self' [-Werror,-Wunused-function]
04:20:55  static __always_inline int redirect_self(struct __sk_buff *skb)
04:20:55                             ^
04:20:55  /go/src/github.com/cilium/cilium/bpf/lib/common.h:698:28: error: unused function 'redirect_peer' [-Werror,-Wunused-function]
04:20:55  static __always_inline int redirect_peer(int ifindex, __u32 flags)
04:20:55                             ^
04:20:55  In file included from bpf_lxc.c:32:
04:20:55  In file included from /go/src/github.com/cilium/cilium/bpf/lib/maps.h:22:
04:20:55  /go/src/github.com/cilium/cilium/bpf/lib/ipv6.h:108:30: error: unused function 'ipv6_addrcmp' [-Werror,-Wunused-function]
04:20:55  static __always_inline __u64 ipv6_addrcmp(union v6addr *a, union v6addr *b)
04:20:55                               ^
04:20:55  /go/src/github.com/cilium/cilium/bpf/lib/ipv6.h:119:28: error: unused function 'ipv6_addr_in_net' [-Werror,-Wunused-function]
04:20:55  static __always_inline int ipv6_addr_in_net(union v6addr *addr, union v6addr *net, union v6addr *mask)
04:20:55                             ^
04:20:55  /go/src/github.com/cilium/cilium/bpf/lib/ipv6.h:145:28: error: unused function 'ipv6_match_prefix_64' [-Werror,-Wunused-function]
04:20:55  static __always_inline int ipv6_match_prefix_64(const union v6addr *addr, const union v6addr *prefix)
04:20:55                             ^
04:20:55  /go/src/github.com/cilium/cilium/bpf/lib/ipv6.h:156:28: error: unused function 'ipv6_dec_hoplimit' [-Werror,-Wunused-function]
04:20:55  static __always_inline int ipv6_dec_hoplimit(struct __sk_buff *skb, int off)
04:20:55                             ^
04:20:55  /go/src/github.com/cilium/cilium/bpf/lib/ipv6.h:171:28: error: unused function 'ipv6_load_saddr' [-Werror,-Wunused-function]
04:20:55  static __always_inline int ipv6_load_saddr(struct __sk_buff *skb, int off, union v6addr *dst)
04:20:55                             ^
04:20:55  /go/src/github.com/cilium/cilium/bpf/lib/ipv6.h:178:28: error: unused function 'ipv6_store_saddr' [-Werror,-Wunused-function]
04:20:55  static __always_inline int ipv6_store_saddr(struct __sk_buff *skb, __u8 *addr, int off)
04:20:55                             ^
04:20:55  /go/src/github.com/cilium/cilium/bpf/lib/ipv6.h:183:28: error: unused function 'ipv6_load_daddr' [-Werror,-Wunused-function]
04:20:55  static __always_inline int ipv6_load_daddr(struct __sk_buff *skb, int off, union v6addr *dst)
04:20:55                             ^
04:20:55  /go/src/github.com/cilium/cilium/bpf/lib/ipv6.h:190:28: error: unused function 'ipv6_store_daddr' [-Werror,-Wunused-function]
04:20:55  static __always_inline int ipv6_store_daddr(struct __sk_buff *skb, __u8 *addr, int off)
04:20:55                             ^
04:20:55  /go/src/github.com/cilium/cilium/bpf/lib/ipv6.h:195:28: error: unused function 'ipv6_load_nexthdr' [-Werror,-Wunused-function]
04:20:55  static __always_inline int ipv6_load_nexthdr(struct __sk_buff *skb, int off, __u8 *nexthdr)
04:20:55                             ^
04:20:55  /go/src/github.com/cilium/cilium/bpf/lib/ipv6.h:202:28: error: unused function 'ipv6_store_nexthdr' [-Werror,-Wunused-function]
04:20:55  static __always_inline int ipv6_store_nexthdr(struct __sk_buff *skb, __u8 *nexthdr, int off)
04:20:55                             ^
04:20:55  /go/src/github.com/cilium/cilium/bpf/lib/ipv6.h:208:28: error: unused function 'ipv6_load_paylen' [-Werror,-Wunused-function]
04:20:55  static __always_inline int ipv6_load_paylen(struct __sk_buff *skb, int off, __be16 *len)
04:20:55                             ^
04:20:55  /go/src/github.com/cilium/cilium/bpf/lib/ipv6.h:215:28: error: unused function 'ipv6_store_paylen' [-Werror,-Wunused-function]
04:20:55  static __always_inline int ipv6_store_paylen(struct __sk_buff *skb, int off, __be16 *len)
04:20:55                             ^
04:20:55  /go/src/github.com/cilium/cilium/bpf/lib/ipv6.h:221:28: error: unused function 'ipv6_store_flowlabel' [-Werror,-Wunused-function]
04:20:55  static __always_inline int ipv6_store_flowlabel(struct __sk_buff *skb, int off, __be32 label)
04:20:55                             ^
04:20:55  /go/src/github.com/cilium/cilium/bpf/lib/ipv6.h:255:28: error: unused function 'ipv6_addr_is_mapped' [-Werror,-Wunused-function]
04:20:55  static __always_inline int ipv6_addr_is_mapped(union v6addr *addr)
04:20:55                             ^
04:20:55  In file included from bpf_lxc.c:33:
04:20:55  In file included from /go/src/github.com/cilium/cilium/bpf/lib/arp.h:25:
04:20:55  /go/src/github.com/cilium/cilium/bpf/lib/eth.h:65:28: error: unused function 'eth_load_saddr' [-Werror,-Wunused-function]
04:20:55  static __always_inline int eth_load_saddr(struct __sk_buff *skb, __u8 *mac, int off)
04:20:55                             ^
04:20:55  /go/src/github.com/cilium/cilium/bpf/lib/eth.h:75:28: error: unused function 'eth_load_daddr' [-Werror,-Wunused-function]
04:20:55  static __always_inline int eth_load_daddr(struct __sk_buff *skb, __u8 *mac, int off)
04:20:55                             ^
04:20:55  In file included from bpf_lxc.c:33:
04:20:55  /go/src/github.com/cilium/cilium/bpf/lib/arp.h:67:28: error: unused function 'arp_respond' [-Werror,-Wunused-function]
04:20:55  static __always_inline int arp_respond(struct __sk_buff *skb, union macaddr *mac, int direction)
04:20:55                             ^
04:20:55  fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

2020-02-25 08:39 UTC, zhiyuan0x commented
> Also, Jenkins reports that there were several build failures for make -C bpf all BUILD_PERMUTATIONS=1

I found that some unused functions cause the build to fail after changing "inline" to "always_inline".  I added another '__maybe_unused' flag for these functions. 

Thanks.

2020-02-25 09:29 UTC, borkmann commented
test-me-please

2020-02-26 16:23 UTC, borkmann commented
Merged via #10344, thanks!

2020-02-26 16:23 UTC, closed without merging