linux: check policy routing of running kernel
cilium/cilium pull request #10068
Opened 2020-02-05 15:38 UTC by iecedge

Check the payload of the NLMSG_DONE type netlink
message for possible error, then determine whether
CONFIG_IP_MULTIPLE_TABLES is enabled.

Signed-off-by: Jianlin Lv <Jianlin.Lv@arm.com>

Fixes: #9834

2020-02-05 17:19 UTC, joestringer approved these changes
This looks nice and tidy!

Did you already submit the vendor change to the upstream library? If not, please do. We can rebase the netlink dependency on top when the upstream change is merged.

2020-02-05 17:21 UTC, joestringer commented
test-me-please

2020-02-06 00:41 UTC, Jianlin-lv commented
> This looks nice and tidy!
> 
> Did you already submit the vendor change to the upstream library? If not, please do. We can rebase the netlink dependency on top when the upstream change is merged.

The change is already upstream, https://github.com/vishvananda/netlink/pull/520

2020-02-06 18:09 UTC, joestringer commented
> The change is already upstream, vishvananda/netlink#520

Thanks. When the above is merged, please update this PR to the new version of the library using these instructions:

http://docs.cilium.io/en/latest/contributing/development/dev_setup/#add-update-a-golang-dependency

2020-02-10 09:56 UTC, Jianlin-lv commented
> > The change is already upstream, [vishvananda/netlink#520](https://github.com/vishvananda/netlink/pull/520)
> 
> Thanks. When the above is merged, please update this PR to the new version of the library using these instructions:
> 
> http://docs.cilium.io/en/latest/contributing/development/dev_setup/#add-update-a-golang-dependency

@joestringer, vishvananda/netlink#520 have been merged,
When locally update github.com/vishvananda/netlink to latest and recompiling, 
I encountered one issue that
"# Github.com/vishvananda/netlink/nl
../../vendor/github.com/vishvananda/netlink/nl/addr_linux.go:58:2: undefined: unix.IfaCacheinfo
"
This issue needs to be resolved by upgrading golang.org/x/sys/unix， Refer：https://github.com/vishvananda/netlink/pull/514

I see "pinned to release-branch.go1.13" in the go.mod about sys/unix
Could I upgrade golang.org/x/sys/unix to latest?

2020-02-10 16:37 UTC, joestringer commented
I think that makes sense, unfortunate it's relying on such a new implementation. /cc @aanm who will review such changes.

2020-02-10 21:42 UTC, aanm commented
@Jianlin-lv it is be fine to pin the sys/unix to latest because Go 1.14 will be released during the Cilium 1.8 dev cycle.

2020-02-18 23:58 UTC, aanm requested changes
Please run `./contrib/go-mod/update-vendor.sh` for each commit as there are files being added in the vendor directory that are not required.

2020-02-18 23:58 UTC, aanm commented
@iecedge ^^^

2020-02-19 08:55 UTC, iecedge commented
> Please run `./contrib/go-mod/update-vendor.sh` for each commit as there are files being added in the vendor directory that are not required.

vendor have been update by https://github.com/cilium/cilium/pull/10138 
This PR only keep code of checking policy routing

2020-02-19 08:55 UTC, aanm commented
test-me-please

2020-02-19 08:56 UTC, aanm approved these changes

2020-02-21 12:29 UTC, merged