kubernetes: Updated connectivity check
cilium/cilium pull request #10104
Opened 2020-02-09 22:10 UTC by tgraf

Improved connectivity check with the ability to test various connectivity and
policy variations.

2020-02-10 07:47 UTC, aanm requested changes

2020-02-10 07:47 UTC, aanm commented on examples/kubernetes/connectivity-check/pod-to-external-fqdn-allow-google.yaml
> +        image: docker.io/cilium/json-mock
set image tag

2020-02-10 07:47 UTC, aanm commented on examples/kubernetes/connectivity-check/pod-to-external-1111.yaml
> +        image: docker.io/cilium/json-mock
set image tag

2020-02-10 07:47 UTC, aanm commented on examples/kubernetes/connectivity-check/pod-to-b-multi-node.yaml
> +        image: docker.io/cilium/json-mock
set image tag

2020-02-10 07:47 UTC, aanm commented on examples/kubernetes/connectivity-check/pod-to-b-intra-node.yaml
> +        image: docker.io/cilium/json-mock
set image tag

2020-02-10 07:47 UTC, aanm commented on examples/kubernetes/connectivity-check/pod-to-a.yaml
> +        image: docker.io/cilium/json-mock
set image tag

2020-02-10 07:47 UTC, aanm commented on examples/kubernetes/connectivity-check/pod-to-a-denied.yaml
> +        image: docker.io/cilium/json-mock
set image tag

2020-02-10 07:47 UTC, aanm commented on examples/kubernetes/connectivity-check/pod-to-a-allowed.yaml
> +        image: docker.io/cilium/json-mock
set image tag

2020-02-10 07:47 UTC, aanm commented on examples/kubernetes/connectivity-check/echo-b.yaml
> +        image: docker.io/cilium/json-mock
set image tag

2020-02-10 07:47 UTC, aanm commented on examples/kubernetes/connectivity-check/echo-a.yaml
> +        image: docker.io/cilium/json-mock
set image tag

2020-02-10 19:31 UTC, joestringer approved these changes

2020-02-10 22:31 UTC, aanm approved these changes

2020-02-10 22:32 UTC, aanm commented
test-me-please

2020-02-11 10:02 UTC, merged

2020-02-11 13:48 UTC, Rolinh commented
The doc still references the file `connectivity-check.yaml` in 3 places which breaks the instructions with `kubectl apply`:
```
$ ag 'connectivity-check.yaml' Documentation
Documentation/gettingstarted/k8s-install-validate.rst
31:    kubectl apply -f \ |SCM_WEB|\/examples/kubernetes/connectivity-check/connectivity-check.yaml

Documentation/gettingstarted/k8s-install-azure-cni-validate.rst
27:    kubectl apply -f \ |SCM_WEB|\/examples/kubernetes/connectivity-check/connectivity-check.yaml

Documentation/gettingstarted/kube-router.rst
147:    $ kubectl create -f \ |SCM_WEB|\/examples/kubernetes/connectivity-check/connectivity-check.yaml
```
What should this point to now?