test: Add Kubernetes Service CI tests for IPv6
cilium/cilium pull request #10115
Opened 2020-02-10 14:19 UTC by gandro

2020-02-10 14:20 UTC, gandro commented
test-focus K8sService*

2020-02-10 15:19 UTC, gandro commented
test-focus K8sService*

2020-02-10 15:57 UTC, gandro commented
test-focus K8sService*

2020-02-10 17:46 UTC, gandro commented
test-focus K8sService*

2020-02-11 11:18 UTC, gandro commented
test-focus K8sService*

2020-02-11 12:11 UTC, gandro commented
test-focus K8sService*

2020-02-11 16:06 UTC, gandro commented
test-me-please

2020-02-11 17:16 UTC, brb requested changes
LGTM, just one nit.

2020-02-11 17:16 UTC, brb commented on test/k8sT/Services.go
> +			_ = kubectl.CiliumServiceDel(pod, 1001)
s/1001/id/?

2020-02-11 18:00 UTC, gandro commented on test/k8sT/Services.go
> +			_ = kubectl.CiliumServiceDel(pod, 1001)
:scream: Thanks, good catch!

2020-02-11 18:29 UTC, gandro commented
test-me-please

2020-02-11 19:46 UTC, brb approved these changes

2020-02-11 21:32 UTC, merged