[WIP DO NOT MERGE / REVIEW] gather /var/run/cilium, /var/lib/cilium as part of Jenkins builds
cilium/cilium pull request #1017
Opened 2017-06-21 23:28 UTC by ianvernon

2017-06-23 00:13 UTC, ianvernon commented
Logs / contents of /var/run/cilium, /var/lib/cilium are packaged up now in a tar.gz as part of the build. [Example](https://jenkins.cilium.io/job/cilium/job/cilium/job/PR-1017/33/).

2017-06-23 00:17 UTC, aanm commented
Small thing can you remove one of the timestamps from the log?

2017-06-23 03:59 UTC, tgraf approved these changes

2017-06-23 04:13 UTC, aanm requested changes
Ping me once the duplicate timestamps are removed

2017-06-23 08:28 UTC, aalemayhu requested changes
Can you change `/home/vagrant/go/` to `$GOPATH`? This will make the script useable outside of vagrant environments.

2017-06-23 08:31 UTC, scanf commented on tests/helpers.bash
> +    CILIUM_DIR="/home/vagrant/go/src/github.com/cilium/cilium/tests/cilium-files/$1"
`TEST_NAME` is unused.

2017-06-23 08:36 UTC, scanf commented on Jenkinsfile
>              sh 'vagrant destroy -f'
Nice, this makes the artefact available for download from Jenkins

https://jenkins.cilium.io/job/cilium/job/cilium/job/PR-1017/35/artifact/cilium-files.tar.gz

2017-06-23 20:55 UTC, ianvernon commented
@aanm given that the formatting of the logs was removed by another commit which is unrelated to the goal of this ticket, 41786b1ef , I'd prefer to file another ticket and deal with it separately. I'll happily take on that ticket as well. Is that OK with you?

2017-06-24 00:09 UTC, aalemayhu approved these changes
Other than the newlines in `run-tests`. This looks great!

2017-06-25 19:46 UTC, aanm commented
>@aanm given that the formatting of the logs was removed by another commit which is unrelated to the goal of this ticket, 41786b1 , I'd prefer to file another ticket and deal with it separately. I'll happily take on that ticket as well. Is that OK with you?

Sounds good!

2017-06-25 19:46 UTC, aanm approved these changes

2017-06-25 19:56 UTC, ianvernon commented
Logging issues will be taken care of separately: https://github.com/cilium/cilium/issues/1029

2017-06-26 16:02 UTC, merged