cli: Do not panic if BPF map does not exist
cilium/cilium pull request #10193
Opened 2020-02-14 15:22 UTC by brb

This commit changes the behavior of the following cmds:

- `cilium bpf ct flush`
- `cilium bpf ct list`
- `cilium bpf nat list`
- `cilium bpf nat flush`

The change makes the cmds not to fail if a map does not exist, and
instead to continue processing a next map.

This was observed when a user was running in the ipv6-only mode, and
the listed cmds failed to process ipv6 maps due to missing ipv4 maps.

Fixes: #10191

2020-02-14 15:27 UTC, brb commented
test-me-please

2020-02-14 17:27 UTC, joestringer approved these changes

2020-02-14 17:31 UTC, aanm requested changes
I don't think this be enough, the error is not os.ErrNotExist:

`Error: Unable to open /sys/fs/bpf/tc/globals/cilium_ct4_global: Unable to get object /sys/fs/bpf/tc/globals/cilium_ct4_global: no such file or directory, *os.PathError`

2020-02-17 10:53 UTC, brb commented
test-me-please

2020-02-18 00:33 UTC, aanm requested changes
@brb an error can also be `*os.PathError` besides `os.ErrNotExist `. Maybe we should never fatal in any error condition.

2020-02-18 07:47 UTC, brb commented
> an error can also be *os.PathError besides os.ErrNotExist 
@aanm How did you trigger the path error?

2020-02-18 08:57 UTC, aanm commented
> > an error can also be *os.PathError besides os.ErrNotExist
> 
> @aanm How did you trigger the path error?

@brb I had it running on my machine with `enable-ipv4=false`. Once I got that error I added a `reflect.Type` to the cli to discover which error was it.

2020-02-18 09:41 UTC, brb commented
@aanm Anyway, from your output above, I see that `os.PathError` wrapped `ErrNotExist`, so `os.IsNotExist` should catch it.

2020-02-18 09:41 UTC, brb commented
CI provisioning failed. Re-running.

2020-02-18 09:41 UTC, brb commented
test-me-please

2020-02-18 10:16 UTC, aanm approved these changes

2020-02-18 23:15 UTC, merged