docs: Mention that a kv-store is optional with k8s.
cilium/cilium pull request #10321
Opened 2020-02-24 19:51 UTC by jrajahalme

2020-02-24 19:51 UTC, jrajahalme commented
test-docs-please

2020-02-24 20:59 UTC, joestringer requested changes
Minor nits, it's not just identity management that is done via CRD and the sentence wasn't complete.

2020-02-24 20:59 UTC, joestringer commented on Documentation/install/system_requirements.rst
> +for more.
```suggestion
for more details.
```

2020-02-24 20:59 UTC, joestringer commented on Documentation/install/system_requirements.rst
> +Cilium can be used without a Key-Value store when CRD-based identity
```suggestion
Cilium can be used without a Key-Value store when CRD-based state
```

2020-02-26 20:49 UTC, jrajahalme commented on Documentation/install/system_requirements.rst
> +for more.
Done

2020-02-26 20:50 UTC, jrajahalme commented on Documentation/install/system_requirements.rst
> +Cilium can be used without a Key-Value store when CRD-based identity
Done.

2020-02-26 20:51 UTC, jrajahalme commented
test-docs-please

2020-02-26 23:12 UTC, joestringer approved these changes

2020-02-26 23:12 UTC, merged