Fix eks restart pods helm
cilium/cilium pull request #10351
Opened 2020-02-26 19:24 UTC by tom-hadlaw-hs

Signed-off-by: Tom Hadlaw <thomas.hadlaw@hootsuite.com>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Follow up bugfix's for my previous pull request. One problem is that helm actually breaks the docker `--format` argument value as it considers it a template value. This causes the conditional to always be false and for the container restart to never happen on EKS nodes.
Secondly, upon further testing, it seems like kubelet can fail due if the container is removed: (`rpc error: code = Unknown desc = unable to inspect docker image ...`).

I'm not exactly sure why this didn't happen during my first round of testing but I propose to just kill the container and let Kubelet manage the remaining container state (docker kill just sends sigkill to the container process, wheraes rm removes all the container state as well). The container does get cleaned up afterwards.

2020-02-26 23:39 UTC, jrajahalme requested changes
Looks good, but please add "Fixes: #<your previous PR number>" to the commit message so that we can track backports effectively.

2020-02-26 23:41 UTC, jrajahalme commented
Also add the description to the commit message, thanks!

2020-02-27 10:20 UTC, aanm requested changes
it seems `cilium.yaml` was added by accident

2020-02-27 18:26 UTC, tom-hadlaw-hs commented
@jrajahalme I added the original issue from the first pull request

2020-03-04 09:32 UTC, aanm approved these changes

2020-03-04 09:32 UTC, aanm commented
test-me-please

2020-03-05 17:49 UTC, joestringer commented
test-me-please

2020-03-05 20:14 UTC, tgraf approved these changes

2020-03-05 20:14 UTC, merged