[v1.6] operator: stop listening on all interfaces for api-server-port
cilium/cilium pull request #10369
Opened 2020-02-27 19:17 UTC by aanm

We should not open this port on all interfaces since cilium-operator is
running in the host network.

For now we will open on both IPv4 and IPv6 localhost addresses since the
user might run the operator on IPv6-only clusters, or vice-versa, we
don't want the operator to not being able from listening on a port on
the IP version not available on the cluster.

Signed-off-by: André Martins <andre@cilium.io>

```release-note
Do not listen on any port by default for cilium-operator
```

backport of https://github.com/cilium/cilium/pull/10368

2020-02-27 19:17 UTC, aanm commented
never-tell-me-the-odds

2020-02-28 13:45 UTC, raybejjani requested changes

2020-02-28 13:45 UTC, raybejjani commented on operator/api.go
> +	for err := range errs {
Similar question as https://github.com/cilium/cilium/pull/10370#discussion_r385700594 (and I think whatever we do there will also work here).

2020-02-28 14:10 UTC, raybejjani approved these changes

2020-02-28 14:10 UTC, merged