operator: populate CLI flags from cilium-operator
cilium/cilium pull request #10372
Opened 2020-02-27 20:20 UTC by aanm

This commit fixes the ability to read the CLI flags by the operator.

Fixes: 67b147c3f273 ("operator: add ability to ready options from a config directory")
Signed-off-by: André Martins <andre@cilium.io>

2020-02-27 20:23 UTC, aanm commented
test-me-please

2020-02-28 08:30 UTC, aanm commented
test-me-please

2020-02-28 14:32 UTC, aanm commented
test-me-please

2020-02-28 20:45 UTC, tgraf requested changes

2020-02-28 20:45 UTC, tgraf commented on operator/main.go
> +	logging.SetupLogging(option.Config.LogDriver, option.Config.LogOpt, "cilium-agent", option.Config.Debug)
Should this be `"cilium-operator"`?

2020-03-02 08:50 UTC, aanm commented
test-me-please

2020-03-02 12:10 UTC, merged