Enhanced daemons flags
cilium/cilium pull request #1037
Opened 2017-06-27 06:59 UTC by aanm

Reordered daemons flags in `daemon/main.go` and rewrite some of the flags descriptions that could cause some misinterpretation.

Also add the bindata.go to the list of ignored git files.

```
cilium-agent --help
Run cilium daemon

Usage:
  daemon [flags]

Flags:
      --access-log string             Path to access log of all HTTP requests observed
      --agent-labels stringSlice      Additional labels to identify this agent
      --allow-localhost string        Policy when to allow local stack to reach local endpoints { auto | always | policy }  (default "auto")
      --bpf-root string               BPF mount path filesystem
      --config string                 Configuration file (default "$HOME/ciliumd.yaml")
  -D, --debug                         Enable debug messages
  -d, --device string                 Device to snoop on (default "undefined")
      --disable-conntrack             Disable connection tracking
      --disable-ipv4                  Disable IPv4 mode
  -e, --docker string                 Register a listener for docker events on the given endpoint (default "unix:///var/run/docker.sock")
      --enable-policy string          Enable policy enforcement (default "default")
      --enable-tracing                Enable tracing while determining policy
      --ipv4-range string             IPv4 prefix for endpoints, must be in correct format (10.N.0.1/16)
      --k8s-api-server string         Kubernetes api address server (for https use kubeconfig instead)
      --k8s-kubeconfig-path string    Absolute path of the kubernetes kubeconfig file
      --keep-config                   When restoring state, keeps containers' configuration in place
      --keep-templates                Do not restore BPF template files from binary
      --kvstore string                Key-value store type
      --kvstore-opt map               Key-value store options (default map[])
      --label-prefix-file string      Valid label prefixes file path
      --labels stringSlice            List of label prefixes used to determine identity of an endpoint
      --lb string                     Enables load balancer mode where load balancer bpf program is attached to the given interface
      --lib-dir string                Directory path to store runtime build environment (default "/var/lib/cilium")
      --log-driver stringSlice        Logging endpoints to use for example systemd, fluentd
      --log-opt map                   Log driver options for cilium (default map[])
      --logstash                      Enable logstash integration
      --logstash-agent string         Logstash agent address (default "127.0.0.1:8080")
      --logstash-probe-timer uint32   Logstash probe timer (seconds) (default 10)
      --nat46-range string            IPv6 prefix to map IPv4 addresses to (default "0:0:0:0:0:FFFF::/96")
  -n, --node-address string           IPv6 address of node, must be in correct format (XXXX:XXXX:XXXX:XXXX:XXXX:XXXX::/112)
      --restore                       Restores state, if possible, from previous daemon
      --socket-path string            Sets daemon's socket path to listen for connections (default "/var/run/cilium/cilium.sock")
      --state-dir string              Directory path to store runtime state (default "/var/run/cilium")
  -t, --tunnel string                 Tunnel mode VXLAN or GENEVE (default "vxlan")
      --version                       Print version information
```

2017-06-27 08:32 UTC, aalemayhu approved these changes

2017-06-27 08:39 UTC, borkmann commented on daemon/main.go
> +		"tunnel", "t", "vxlan", "Tunnel mode VXLAN or GENEVE")
This one also has other mode options like "direct" etc, no?

2017-06-27 19:24 UTC, ianvernon commented on daemon/main.go
> +		"log-driver", []string{}, "Logging endpoints to use for example systemd, fluentd")
systemd -> syslog

2017-06-27 19:24 UTC, ianvernon commented on daemon/main.go
> +		"k8s-api-server", "", "Kubernetes api address server (for https use kubeconfig instead)")
I'd change kubeconfig --> "k8s-kubeconfig-path" so that it corresponds to the flag the user should provide.

2017-06-27 19:41 UTC, aanm commented on daemon/main.go
> +		"k8s-api-server", "", "Kubernetes api address server (for https use kubeconfig instead)")
cool I like it! fixed

2017-06-27 19:41 UTC, aanm commented on daemon/main.go
> +		"log-driver", []string{}, "Logging endpoints to use for example systemd, fluentd")
for some reason I read systemd, fixed

2017-06-27 19:46 UTC, aanm commented on daemon/main.go
> +		"tunnel", "t", "vxlan", "Tunnel mode VXLAN or GENEVE")
I believe "direct" mode is only set if the `snoop-device != "undefined"`.
For example, if you set `snoop-device="eth0"` and `-t vxlan` the `"vxlan"` is ignored.
The code is this one: https://github.com/cilium/cilium/blob/9c6885a3a4b81c2355c6981b4126f3a58c3eae1d/daemon/daemon.go#L315

2017-06-27 20:50 UTC, ianvernon approved these changes

2017-06-27 21:14 UTC, tgraf requested changes
Some more suggestions

2017-06-27 21:14 UTC, tgraf commented on daemon/main.go
> +		"bpf-root", "", "BPF mount path filesystem")
`"Path to BPF filesystem"`

2017-06-27 21:14 UTC, tgraf commented on daemon/main.go
> +		"debug", "D", false, "Enable debug messages")
`"Enable debugging mode"`

2017-06-27 21:14 UTC, tgraf commented on daemon/main.go
> +		"device", "d", "undefined", "Device to snoop on")
`"Device facing cluster/external network for direct L3 (non-overlay mode)"`

2017-06-27 21:14 UTC, tgraf commented on daemon/main.go
> +		"docker", "e", "unix:///var/run/docker.sock", "Register a listener for docker events on the given endpoint")
`"Path to docker runtime socket"`

2017-06-27 21:14 UTC, tgraf commented on daemon/main.go
> +		"enable-tracing", false, "Enable tracing while determining policy")
`"Enable tracing while determining policy (debugging)"`

2017-06-27 21:14 UTC, tgraf commented on daemon/main.go
> +		"ipv4-range", "", "IPv4 prefix for endpoints, must be in correct format (10.N.0.1/16)")
`"IPv4 allocation range for local endpoints"`

2017-06-27 21:14 UTC, tgraf commented on daemon/main.go
> +		"keep-templates", false, "Do not restore BPF template files from binary")
We should rename this option to `--keep-bpf-templates`

2017-06-28 04:35 UTC, aanm commented on daemon/main.go
> +		"bpf-root", "", "BPF mount path filesystem")
Wouldn't this be clear if it says the word "mounted", like "... mounted filesystem"?

2017-06-28 04:38 UTC, aanm commented on daemon/main.go
> +		"keep-templates", false, "Do not restore BPF template files from binary")
Should I create a new flag `--keep-bpf-templates` and leave the `--keep-templates` one for 2 versions with `(deprecated)` written in the description?

2017-06-28 05:07 UTC, tgraf commented on daemon/main.go
> +		"keep-templates", false, "Do not restore BPF template files from binary")
Just renamed it. If somebody complains we can add a deprecated version. We haven't declared our CLI stable yet.

2017-06-28 05:08 UTC, tgraf commented on daemon/main.go
> +		"bpf-root", "", "BPF mount path filesystem")
It's not necessarily mounted yet. We will mount the bpf filesystem.

2017-06-28 05:13 UTC, aanm commented on daemon/main.go
> +		"bpf-root", "", "BPF mount path filesystem")
Ah that's right!

2017-06-28 05:20 UTC, tgraf approved these changes

2017-06-28 05:44 UTC, merged