proxy: Remove accesslog option
cilium/cilium pull request #10393
Opened 2020-02-29 12:46 UTC by tgraf

L7 flow logging has been supported via Hubble for a while. The file logging is
no longer required.

2020-02-29 13:59 UTC, tgraf commented
test-me-please

2020-03-01 08:26 UTC, tgraf commented
test-me-please

2020-03-02 09:38 UTC, aanm approved these changes
LGTM besides the requested changes, doesn't require 2nd review

2020-03-02 09:38 UTC, aanm commented on Documentation/install/upgrade.rst
> +* ``accesslog``: L7 access logs have been available since Cilium 1.6. The
`s/accesslog/access-log`

2020-03-02 09:38 UTC, aanm commented on Documentation/install/upgrade.rst
> +  ``accesslog`` option to log to a file has been removed.
`s/accesslog/access-log`

2020-03-02 12:25 UTC, tgraf commented
test-me-please

2020-03-03 11:26 UTC, qmonnet requested changes
The option is also used in `contrib/vagrant/start.sh` and mentioned in `Documentation/envoy/extensions.rst`, could you please also update those files?

2020-03-03 14:17 UTC, tgraf commented
test-me-please

2020-03-03 16:18 UTC, qmonnet approved these changes

2020-03-04 09:24 UTC, merged