daemon: returning clearer k8s error messages
cilium/cilium pull request #1048
Opened 2017-06-29 13:27 UTC by aanm

Some users were getting an error messages like:
`Error while creating daemon: an error on the server (\"\") has prevented the request from succeeding (get nodes 192.168.0.1)`

By enhancing the error messages where they were originated from, hopefully this gives a clearer information to the user.

2017-06-29 14:23 UTC, tgraf requested changes

2017-06-29 14:23 UTC, tgraf commented on daemon/daemon.go
> +			return nil, fmt.Errorf("k8s create client: %s", err)
I think this is still cryptic, let's be obvious: `"Unable to create k8s client: %s", err`

2017-06-29 14:23 UTC, tgraf commented on daemon/daemon.go
> +				return nil, fmt.Errorf("k8s use node CIDR: %s", err)
Let's fail inside of `useK8sNodeCIDR` and improve the error messages there. We can even `log.Fatalf` in the function directly.

2017-06-30 06:38 UTC, aanm commented on daemon/daemon.go
> +			return nil, fmt.Errorf("k8s create client: %s", err)
Fixed!

2017-06-30 06:39 UTC, aanm commented on daemon/daemon.go
> +				return nil, fmt.Errorf("k8s use node CIDR: %s", err)
If we use `log.Fatalf` we can't unit test that function in #1039 . I've changed this error to `return nil, fmt.Errorf("unable to retrieve node CIDR: %s", err)`

2017-06-30 17:43 UTC, tgraf approved these changes

2017-06-30 17:43 UTC, merged