operator: read options from config-map
cilium/cilium pull request #10520
Opened 2020-03-09 22:40 UTC by aanm

cobra.OnInitialize should be called directly in the init function.

Fixes: 67b147c3f273 ("operator: add ability to ready options from a config directory")
Signed-off-by: André Martins <andre@cilium.io>

2020-03-09 23:16 UTC, aanm commented
test-me-please

2020-03-09 23:30 UTC, aanm commented
test-me-please

2020-03-10 09:31 UTC, aanm commented
test-me-please

2020-03-10 11:10 UTC, aanm commented
test-me-please

2020-03-10 12:45 UTC, aanm commented
test-me-please

2020-03-10 22:54 UTC, aanm commented
test-me-please

2020-03-11 00:56 UTC, aanm commented
test-me-please

2020-03-11 10:13 UTC, aanm commented
test-me-please

2020-03-11 14:47 UTC, tklauser reviewed
LGTM in general.

Noticed that `operator` now has two `init` functions one of which (in `operator/flags.go) calls `cobra.OnInitialize(option.InitConfig...)` hooking up the handling of `--version` and the other (in `operator/main.go`) handles `--version` by itself. Would it be possible to somehow merge the two so we can a centralized handling of `--version` in `InitConfig`?

2020-03-12 02:13 UTC, aanm commented
test-me-please

2020-03-12 10:08 UTC, tklauser commented
test-me-please

2020-03-12 10:09 UTC, tklauser approved these changes

2020-03-12 11:36 UTC, aanm commented
test-me-please

2020-03-12 12:05 UTC, nebril requested changes
One small comment, lgtm otherwise

2020-03-12 12:05 UTC, nebril commented on test/helpers/kubectl.go
> +			return fmt.Errorf("timed out waiting to delete Cilium Operator: pods still remaining: %s", pods)
`pods` will be uninitialized here on first run, probably won't ever happen, but can we move whole `select` to the end of the loop body? I assume we want to run through the loop body at least once.

2020-03-12 14:37 UTC, aanm commented on test/helpers/kubectl.go
> +			return fmt.Errorf("timed out waiting to delete Cilium Operator: pods still remaining: %s", pods)
@nebril I'm going to fix this in another PR as this PR is blocking some of my work.

2020-03-12 15:23 UTC, merged