v1.6 backports 2020-03-10
cilium/cilium pull request #10532
Opened 2020-03-10 15:17 UTC by jrajahalme

* #10501 -- policy: Keep NameManager locked during SelectorCache operations (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 10501; do contrib/backporting/set-labels.py $pr done 1.6; done
```

2020-03-10 15:18 UTC, jrajahalme commented
test-me-please

2020-03-10 17:32 UTC, joestringer commented
Provisioning failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/17835/

2020-03-10 17:32 UTC, joestringer commented
test-me-please

2020-03-10 18:13 UTC, joestringer commented
@jrajahalme I noticed that this hunk was dropped from the backport, was this intentional?

```
diff --git a/pkg/ipcache/cidr.go b/pkg/ipcache/cidr.go
index 995b2497c19c..feea372140e7 100644
--- a/pkg/ipcache/cidr.go
+++ b/pkg/ipcache/cidr.go
@@ -71,6 +71,9 @@ func allocateCIDRs(prefixes []*net.IPNet) ([]*identity.Identity, error) {
                allocateCtx, cancel := context.WithTimeout(context.Background(), option.Config.IPAllocationTimeout)
                defer cancel()

+               if IdentityAllocator == nil {
+                       return nil, fmt.Errorf("IdentityAllocator not initialized!")
+               }
                id, isNew, err := IdentityAllocator.AllocateIdentity(allocateCtx, cidr.GetCIDRLabels(prefix), false)
                if err != nil {
                        IdentityAllocator.ReleaseSlice(context.Background(), nil, usedIdentities)
```

2020-03-10 21:13 UTC, joestringer commented
Hit known flake #10278 :
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/17842/

2020-03-10 21:13 UTC, joestringer commented
test-me-please

2020-03-11 04:12 UTC, joestringer commented
test-me-please

2020-03-12 01:41 UTC, joestringer requested changes
Awaiting confirmation whether the omitted hunk is deliberate or not:

https://github.com/cilium/cilium/pull/10532#issuecomment-597235675

2020-03-13 21:30 UTC, jrajahalme commented
@joestringer v1.6 `pkg/ipcache` calls directly to the `cache` package, so there is no chance of nil pointer dereference through (the nonexistent) `ipcache.IdentityAllocator`. `AllocateIdentity()` in `pkg/identity/cache` already has the `nil` test for it's internal `IdentityAllocator`.

2020-03-13 21:38 UTC, joestringer approved these changes

2020-03-13 21:38 UTC, merged