test: merge waitToDelete* functions
cilium/cilium pull request #10559
Opened 2020-03-12 15:23 UTC by aanm

Follow up of https://github.com/cilium/cilium/pull/10520#discussion_r391665734

2020-03-12 15:23 UTC, aanm commented
test-me-please

2020-03-12 21:29 UTC, aanm commented
test-me-please

2020-03-13 09:06 UTC, brb requested changes

2020-03-13 09:06 UTC, brb commented on test/helpers/kubectl.go
>  		default:
At the line 1518 (GH does not allow me to comment it), you probably want to replace `"Cilium Operator"` with `name`.

2020-03-13 09:06 UTC, brb commented on test/helpers/kubectl.go
> +	return kub.waitToDelete("Cilium Operator", "io.cilium/app=cilium")
Can we have consts for `CiliumOperatorLabal` and `CiliumAgentLabel`?

2020-03-17 11:12 UTC, aanm commented
test-me-please

2020-03-17 15:13 UTC, aanm commented
test-me-please

2020-03-18 10:09 UTC, brb approved these changes

2020-03-18 10:17 UTC, merged