WIP - adding list of rules in ciliumspec
cilium/cilium pull request #1055
Opened 2017-06-30 07:10 UTC by aanm

Fixes https://github.com/cilium/cilium/issues/900
Signed-off-by: André Martins <andre@cilium.io>

2017-07-07 21:55 UTC, tgraf commented
What are we missing here before this can get merged?

2017-07-07 22:28 UTC, aanm commented
@tgraf I'm currently writing runtime tests. If you want we can merge and I'll push the tests later

2017-07-07 23:25 UTC, tgraf commented
> @tgraf I'm currently writing runtime tests. If you want we can merge and I'll push the tests later

I'm fine with waiting until the runtime tests are done. I was just wondering if this needed more review first.

2017-07-10 17:49 UTC, aanm commented
@tgraf I forgot to ask you in the meeting, on a cilium multi rule policy, which labels should I assign to each policy imported to cilium? Can we have 2+ policies with the same labels?

2017-07-10 17:56 UTC, aanm commented on tests/k8s/multi-node/tests/02-cnp-specs.sh
> +# FIXME we have 2 policies with the same labels, figure it out how to deal
@tgraf ^^

2017-07-10 19:39 UTC, tgraf requested changes

2017-07-10 19:39 UTC, tgraf commented on daemon/k8s_watcher.go
> -	// Delete an eventual existing rule with matching label
Why are you removing this?

2017-07-10 19:39 UTC, tgraf commented on tests/k8s/multi-node/tests/02-cnp-specs.sh
> +# FIXME we have 2 policies with the same labels, figure it out how to deal
The default behavior on matching labels is to replace. So we will never have multiple rules with identical labels.
We could also enforce this in `Parse()` and search if multiple rules have identical labels and error out. Both is fine I think.

2017-07-10 20:22 UTC, michi-covalent approved these changes
will i be able to replace existing rules with the same name with this patch, or do i need to delete the existing rules first and then create new rules with the same name?

2017-07-10 20:34 UTC, aanm commented on daemon/k8s_watcher.go
> -	// Delete an eventual existing rule with matching label
I thought it was a leftover, do we need it? If yes, doesn't the `opts := AddOptions{Replace: true}` do the same?

2017-07-10 21:48 UTC, tgraf commented on daemon/k8s_watcher.go
> -	// Delete an eventual existing rule with matching label
It indeed looks like a leftover. Removing this is correct.

2017-07-10 21:49 UTC, tgraf commented
> will i be able to replace existing rules with the same name with this patch, or do i need to delete the existing rules first and then create new rules with the same name?

Each rule has a set of labels and will overwrite *all* rules with the same set of labels. If adding fails, *all* old rules will be put back in place.

2017-07-10 21:51 UTC, tgraf commented
> @tgraf I forgot to ask you in the meeting, on a cilium multi rule policy, which labels should I assign to each policy imported to cilium? Can we have 2+ policies with the same labels?

2017-07-11 21:35 UTC, michi-covalent commented
> Each rule has a set of labels and will overwrite all rules with the same set of labels. If adding fails, all old rules will be put back in place.

What happens if do something like this? First, create a policy with two rules:
```
apiVersion: "cilium.io/v1"
kind: CiliumNetworkPolicy
description: "Policy to test multiple rules in a single file"
metadata:
  name: "multi-rules"
specs:
  - endpointSelector:
      matchLabels:
        app: ratings
    ingress:
    - fromEndpoints:
      - matchLabels:
          app: reviews
  - endpointSelector:
      matchLabels:
        app: details
    ingress:
    - fromEndpoints:
      - matchLabels:
          app: productpage
```
Then, remove one rule from the YAML file and apply it again:
```
apiVersion: "cilium.io/v1"
kind: CiliumNetworkPolicy
description: "Policy to test multiple rules in a single file"
metadata:
  name: "multi-rules"
specs:
  - endpointSelector:
      matchLabels:
        app: ratings
    ingress:
    - fromEndpoints:
      - matchLabels:
          app: reviews
```
Will this remove the ingress rule from productpage to details?

2017-07-11 21:43 UTC, tgraf commented
> Will this remove the ingress rule from productpage to details?

Yes. Identification of rules is based on the metadata and not on the rules themselves. Your example does not contain any labels in the rules themselves which means that the only label attached to the rules is the one which is generated from the policy name. Your delete request will thus delete both rules.

2017-07-11 21:53 UTC, michi-covalent commented
Cool thanks @tgraf. One more follow up question. Say I created a policy with metadata like this:

```
metadata:
  name: my-policy-with-a-bunch-of-rules
  namespace: default
  labels:
    policy-version: v1
```
and later on I want to replace it with a new version of the policy:
```
metadata:
  name: my-policy-with-a-bunch-of-rules
  namespace: default
  labels:
    policy-version: v2
```
but I guess this won't match the existing policy because policy-version is different?

2017-07-12 12:56 UTC, aanm commented
@tgraf I add a new commit as a workaround, it should be reverted once the l7 multinode bug is fixed.

2017-07-13 19:57 UTC, tgraf approved these changes

2017-07-13 19:58 UTC, merged