[BPF/probes]: Added kernel checks Fixes: #891
cilium/cilium pull request #1065
Opened 2017-07-02 08:51 UTC by eloycoto

Hello!

This PR check the kernel config and validate that the minimum kernel params are satisfied. 

CoreOS uses /proc/config, but the other distros are using "/boot-config-${kernel-release}". I tested with major distributions and should work ok in all of them. 

On the other hand, maybe some modules should be checked too, like "algif_hash" but I was not entirely sure, and I didn't add it. If you want to add, I'll do. 

Thanks!

2017-07-02 19:40 UTC, aalemayhu requested changes
A part from nitpicks, looks good.

2017-07-02 19:40 UTC, scanf commented on bpf/run_probes.sh
> +    fi
Is this return needed?

2017-07-02 19:40 UTC, scanf commented on bpf/run_probes.sh
>  }
If there is no reason to change the indentation, please leave as is.

2017-07-03 10:18 UTC, tgraf requested changes

2017-07-03 10:18 UTC, tgraf commented on bpf/run_probes.sh
> +        "CONFIG_BPF_EVENTS=y" "CONFIG_TEST_BPF=m")
Several of these can be configured as both a module or builtin. I think these must be regular expressions which we pass into `zgrep -E` or something similar.

2017-07-04 12:42 UTC, tklauser commented on bpf/run_probes.sh
> +        echo "Error: BPF/probes: No valid kernerl configuration" >> $WARNING_FILE
Typo: should be _kernel_ instead of _kernerl_

2017-07-12 09:12 UTC, aalemayhu approved these changes
Requires re-base, but otherwise looks good.

2017-07-13 12:50 UTC, tgraf approved these changes

2017-07-13 12:50 UTC, merged