Improve k8s client heartbeat capability
cilium/cilium pull request #10673
Opened 2020-03-23 22:59 UTC by aanm

Switched the heartbeat to be done on `/healthz` instead of doing a get
on kube-system namespace which has higher overhead than `/heatlhz`.

If Cilium has interactions with k8s, Cilium does not need to
perform heatbeats to the kube-apiserver. Unless those interactions
result in an error for which we should perform a heartbeat to
kube-apiserver to check if the connection is still alive. In case the
response from kube-apiserver is an error Cilium should then close all
connections with the kube-apiserver.

Read per commit for more details

2020-03-23 23:00 UTC, aanm commented
test-me-please

2020-03-24 11:21 UTC, tgraf requested changes

2020-03-24 11:21 UTC, tgraf commented on pkg/k8s/init.go
> +	go wait.Until(func() {
Why are we using this custom code instead of `pkg/controller`? Having the controller would give us visibility into what is happening.

2020-03-24 11:21 UTC, tgraf commented on pkg/k8s/client.go
> +		// 'timeout' duration then we should close all connections!
The comment seems wrong. It's not what the code does. The comment should say:
```
// Skip the heartbeat if we have received an event within the heartbeat timeout interval and not error has been received from the apiserver.
```

That said, is the error condition really useful. We are likely to receive quite a few errors while attempting to update outdated resources. Would they all skip the heartbeat ping?

2020-03-24 12:51 UTC, aanm commented
test-me-please

2020-03-24 14:08 UTC, aanm commented
test-me-please

2020-03-24 14:13 UTC, tgraf approved these changes
Awesome

2020-03-24 16:51 UTC, aanm commented
hit https://github.com/cilium/cilium/issues/10118

2020-03-24 16:51 UTC, merged