contrib: Add script to bump stable releases
cilium/cilium pull request #10711
Opened 2020-03-25 23:42 UTC by joestringer

Add a script to create a new commit bumping the README and github
actions for newly released versions.

Usage:

$ git fetch origin
$ git checkout -b pr/bump-readme-$(date --rfc-3339=date) origin/master
$ ./contrib/release/bump-readme
$ git push
<open PR>

Used to create #10710.

2020-03-26 01:30 UTC, christarazi reviewed
I usually like to add `set -euo pipefail` for bash scripts. It would be great if we can add this to the docs as well. Otherwise, nice!

2020-03-26 01:39 UTC, joestringer commented
Ah, good point, I was assuming that these are set in the included common/lib scripts and that those settings would propagate out to this script, which I *think* is true but worth double-checking.

Agree on the docs, question will be whether we move towards retiring the docs for generating releases and roll this into the github issue template for releases.

Or for that matter if we just avoid using this script manually and script up a github action to invoke it automatically..

2020-03-26 05:57 UTC, christarazi commented
I quickly glanced at the "usage" section of the script and thought that could go in the docs. But it seems simple enough after a second look, so probably not worth doing. Eventually a GitHub action is probably the most fitting for this kind of thing. :+1:

2020-04-01 07:48 UTC, aanm requested changes
@christarazi @joestringer is this good to be merged besides my nits?

2020-04-01 07:48 UTC, aanm commented on contrib/release/bump-readme
> +#!/bin/bash
maybe rename the filename to `bump-readme.sh`?

2020-04-01 16:48 UTC, christarazi commented
@aanm Good to go for me.

2020-04-01 17:45 UTC, joestringer commented
Moved, and updated the issue template for releases.

2020-04-01 17:46 UTC, merged