Dockerfiles: Add git log when checking out from git
cilium/cilium pull request #10819
Opened 2020-04-02 00:13 UTC by joestringer

For all of the commands we run in dockerfiles where we check out code
from git, we should run `git log -1` so that in the logs of the docker
generation we can tell exactly which commit is checked out and in use
for that particular docker image, using only the docker build logs.

2020-04-02 00:13 UTC, joestringer commented
test-me-please

2020-04-02 12:01 UTC, aanm requested changes
This requires an update of the runtime and builder image tags in quay.io; update these new tags in this PR; finally run the CI with these new tags.

2020-04-02 12:21 UTC, errordeveloper commented on Dockerfile.builder
> +        git log -1 && \
perhaps `git --no-pager log -1` or does it auto-detect as there is no tty?

2020-04-02 22:59 UTC, joestringer commented
Waiting on this build to tag: https://quay.io/repository/cilium/cilium-runtime/build/53f65119-ea0c-4326-b8de-e26117694865

2020-04-03 07:27 UTC, joestringer commented
test-me-please

2020-04-06 21:14 UTC, joestringer commented
restart-ginkgo

2020-04-07 21:13 UTC, joestringer commented
Hit #10882 which seems like a flake, unless the cilium-runtime image here is somehow pulling in something else that was merged but not yet part of the image. Will re-run ginkgo.

2020-04-07 21:13 UTC, joestringer commented
restart-ginkgo

2020-04-09 06:38 UTC, joestringer commented
restart-ginkgo

2020-04-09 16:04 UTC, joestringer commented
Vagrant index problem:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/18622/execution/node/70/log/

2020-04-09 16:04 UTC, joestringer commented
test-ginkgo

2020-04-09 16:04 UTC, joestringer commented
restart-ginkgo

2020-04-09 19:25 UTC, aanm commented
This PR conflicts with open PR #10912 in case one is merged the other needs to be rebased

2020-04-09 20:43 UTC, joestringer commented
Hit #10882 on k8s-1.11 / net-next run again. Doesn't seem related to the changes made in this PR, so it seems like master is already broken :( More investigation necessary....

2020-04-13 23:56 UTC, joestringer commented
restart-ginkgo

2020-04-23 06:04 UTC, joestringer commented
test-me-please

2020-04-24 10:59 UTC, aanm approved these changes

2020-04-24 10:59 UTC, merged