monitor: Support more verbosity levels
cilium/cilium pull request #10820
Opened 2020-04-02 00:13 UTC by joestringer

Make the default verbosity with `cilium monitor -v` print the CAPTURE /
DROP messages in the same format as without `-v` flag, along with DEBUG
messages. This avoids expanding / dissecting CAPTURE messages and
formatting them across multiple lines which can be harder to read.

Move the packet dissection into a new `cilium monitor -v -v` command
instead.

2020-04-02 00:13 UTC, joestringer commented
test-me-please

2020-04-03 07:00 UTC, joestringer commented
test-me-please

2020-04-03 16:13 UTC, joestringer commented
Hit known flake #10821 in the kernel test, can ignore

2020-04-06 06:44 UTC, pchaigno approved these changes
Tested, looks a lot better! If I was running it for the first time, I think I would know where to look this time :-)

One nit below maybe.

2020-04-06 06:44 UTC, pchaigno commented on Documentation/cmdref/cilium_monitor.md
> +  -v, --verbose bools[=false]   Enable verbose output (-v, -vv) (default [])
Is the 's' in "bools" a mistake?

2020-04-06 08:30 UTC, tklauser approved these changes

2020-04-06 08:32 UTC, tklauser commented on Documentation/cmdref/cilium_monitor.md
> +  -v, --verbose bools[=false]   Enable verbose output (-v, -vv) (default [])
I think instead of `-vv` you could also say `-v=true,true` so technically `bools` is correct.

2020-04-06 08:35 UTC, pchaigno commented on Documentation/cmdref/cilium_monitor.md
> +  -v, --verbose bools[=false]   Enable verbose output (-v, -vv) (default [])
Hm, I was expecting `[]bool` as with the other options.

2020-04-06 08:44 UTC, tklauser commented on Documentation/cmdref/cilium_monitor.md
> +  -v, --verbose bools[=false]   Enable verbose output (-v, -vv) (default [])
Ah, right. Didn't notice the use of `[]bools` in other places. I guess it'd make sense to be consistent :+1:

2020-04-06 13:34 UTC, qmonnet requested changes
Looks good, thanks for that! But I would also suggest running a `git grep 'cilium monitor' Documentation/`, I think that at least `Documentation/cheatsheet.rst` and `Documentation/contributing/development/dev_setup.rst` should be updated.

2020-04-06 18:27 UTC, joestringer commented on Documentation/cmdref/cilium_monitor.md
> +  -v, --verbose bools[=false]   Enable verbose output (-v, -vv) (default [])
`bools` is autogenerated by the CLI library.

2020-04-06 18:29 UTC, joestringer commented on Documentation/cmdref/cilium_monitor.md
> +  -v, --verbose bools[=false]   Enable verbose output (-v, -vv) (default [])
I could say `-v=true,true`, but I don't expect anyone to bother typing all of that out. Having `(-v, -vv)` in the example works in practice, and communicates to the user that they can specify additional `v`s to get different output.

2020-04-07 00:04 UTC, joestringer commented
@qmonnet only the ones you mentioned used `-v`, so I've updated those examples. Good spotting.

2020-04-07 03:00 UTC, joestringer commented
test-me-please

2020-04-07 06:02 UTC, pchaigno commented on Documentation/cmdref/cilium_monitor.md
> +  -v, --verbose bools[=false]   Enable verbose output (-v, -vv) (default [])
Ah, didn't realize this was in the generated files :+1:

2020-04-07 06:08 UTC, pchaigno commented
test-with-kernel

2020-04-07 08:25 UTC, qmonnet approved these changes
Looks good, thanks!

2020-04-07 14:12 UTC, merged