bpf: Remove duplicate code in bpf_sock.c
cilium/cilium pull request #10862
Opened 2020-04-06 13:48 UTC by brb

This commit refactors `__sock{4,6}_xlate()` functions in a way that they can be used to replace `__sock{4,6}_snd_xlate()`.

The refactoring also allows us to get rid of the `sock6_xlate_snd_v4_in_v6()` function.

2020-04-06 13:48 UTC, brb commented
test-me-please

2020-04-06 13:53 UTC, tklauser requested changes
Would it make sense to add `-DHOOK_CONNECT` to `LB_OPTIONS` in `bpf/Makefile` so it gets compile-tested too in various option combinations?

2020-04-06 14:03 UTC, borkmann requested changes
Makes sense, but why do we need even more ifdef wrt `HOOK_CONNECT` at all? Either we could leave the sanity check in place (which doesn't hurt much either) or if we really want to remove it then via `const bool` so compiler optimizes it out. I'd probably do the former so `__sock4_xlate()` could stay unchanged, for example.

2020-04-06 15:09 UTC, brb commented
> Makes sense, but why do we need even more ifdef wrt HOOK_CONNECT at all

@borkmann It was just to save a few CPU cycles considering that the unnecessary checks would be in the fastpath in the case of UDP. If you think that's not worth doing, then I can remove the ifdefs from the checks.

2020-04-06 15:19 UTC, borkmann commented
> > Makes sense, but why do we need even more ifdef wrt HOOK_CONNECT at all
> 
> @borkmann It was just to save a few CPU cycles considering that the unnecessary checks would be in the fastpath in the case of UDP. If you think that's not worth doing, then I can remove the ifdefs from the checks.

But in such case I'd just go for `const bool udp_only` or such, so we have less ifdef in the code and compiler can optimize it out.

2020-04-06 15:53 UTC, brb commented
test-me-please

2020-04-06 15:59 UTC, brb commented
@tklauser `HOOK_CONNECT` has been removed.

2020-04-06 18:37 UTC, tklauser approved these changes
Even nicer without the `HOOK_CONNECT` define! Two small nits/questions inline. Otherwise LGTM.

2020-04-06 18:37 UTC, tklauser commented on bpf/bpf_sock.c
> +update_dst: __maybe_unused
Why is it needed to mark this as `__maybe_unused`? It seems it's always used.

2020-04-06 18:37 UTC, tklauser commented on bpf/bpf_sock.c
> +		goto update_dst;
Same comment as for `__sock4_xlate` applies here regarding `goto` and `update_dst` jump label with `__maybe_unused`.

2020-04-06 18:38 UTC, brb commented
test-me-please

2020-04-06 19:47 UTC, brb commented
test-me-please

2020-04-07 06:40 UTC, brb commented
test-me-please

2020-04-07 08:37 UTC, borkmann approved these changes

2020-04-07 12:02 UTC, brb commented
test-me-please

2020-04-07 13:16 UTC, brb commented
CI hit the flake #10669. As my code changes are tested by the flaking test, re-running the CI.

2020-04-08 08:06 UTC, brb commented
test-me-please

2020-04-08 12:25 UTC, brb commented
test-me-please

2020-04-08 18:10 UTC, brb commented
test-me-please

2020-04-08 20:47 UTC, merged