test: Pass KERNEL env param in ginkgo-kernel job
cilium/cilium pull request #10874
Opened 2020-04-07 13:39 UTC by brb

Otherwise, the RunsOnNetNextOr419Kernel() returns false on the 4.19 build, which makes to skip some kube-proxy replacement related tests.

Fixes: 72fe87afb80a ("test: Extend RunsOnNetNext helper family")

2020-04-07 13:40 UTC, brb commented
test-with-kernel

2020-04-07 14:17 UTC, brb commented
test-with-kernel

2020-04-07 14:29 UTC, brb commented
test-with-kernel

2020-04-07 14:34 UTC, brb commented
test-with-kernel

2020-04-07 14:47 UTC, brb commented
test-me-please

2020-04-08 08:15 UTC, brb commented
test-with-kernel

2020-04-08 09:31 UTC, brb commented
test-with-kernel

2020-04-08 09:43 UTC, brb commented
test-with-kernel

2020-04-08 12:24 UTC, brb commented
test-with-kernel

2020-04-08 12:35 UTC, brb commented
test-with-kernel

2020-04-10 14:49 UTC, nebril requested changes

2020-04-10 14:49 UTC, nebril commented on jenkinsfiles/ginkgo-kernel.Jenkinsfile
> +    dir("${TESTDIR}") {
Seems like this line causes the problem in CI.

2020-04-10 14:49 UTC, nebril commented on jenkinsfiles/ginkgo-kernel.Jenkinsfile
> +        KERNEL = get_kernel("${DEFAULT_KERNEL}")
If you set `KERNEL` here in a manner similar to https://github.com/cilium/cilium/blob/master/jenkinsfiles/ginkgo-gke.Jenkinsfile#L128 , it should be available as an env var in all children pipeline steps.

2020-04-14 07:42 UTC, brb commented
test-with-kernel

2020-04-14 08:38 UTC, brb commented
test-with-kernel

2020-04-14 12:27 UTC, brb commented
test-with-kernel

2020-04-15 08:41 UTC, borkmann commented
test-with-kernel

2020-04-17 20:27 UTC, brb commented
test-with-kernel

2020-04-20 05:30 UTC, brb commented
test-with-kernel

2020-04-20 14:49 UTC, brb commented
test-with-kernel

2020-04-20 20:24 UTC, brb commented
test-with-kernel

2020-06-09 11:29 UTC, brb commented
Closing in favor of https://github.com/cilium/cilium/pull/11915 and https://github.com/cilium/cilium/pull/11894.

2020-06-09 11:29 UTC, closed without merging