Configure context to prevent a hanging call
cilium/cilium pull request #10986
Opened 2020-04-15 10:02 UTC by manuelbuil

When using interfaces with MTU=9000, we sometimes see how cilium-agent
gets stuck when doing this Rest call. Eventually it gets killed by
Kubernetes because it exceeds the liveness probe and as a result there
are no useful logs.

This patch uses contexts to provide a timeout to the call. The 120s are
used since this number is defined in one of the examples for the
livenessProbe.initialDelaySeconds

https://github.com/cilium/cilium/blob/master/install/kubernetes/quick-install.yaml#L364

We can discuss if perhaps makes sense to generalize all calls to include
such a timeout with a globally defined timeout variable

Fixes: #10506

Signed-off-by: Manuel Buil <mbuil@suse.com>

Please ensure your pull request adheres to the following guidelines:

- [X] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [X] All code is covered by unit and/or runtime tests where feasible.
- [X] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [X] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [X] Provide a title or release-note blurb suitable for the release notes.
- [X] Thanks for contributing!

Fixes: #10506

```release-note

```

2020-04-15 10:54 UTC, vadorovsky requested changes
I would prefer to have a more generic solution. For example, using `context.WithTimeout` to all client calls (should be possible, since we already wrap the client in `pkg/k8s`). Or at least using `context.WithTimeout` in all calls which are done during daemon launch. I don't have a clear idea how to do that though, I will think about it.

2020-04-15 10:54 UTC, mrostecki commented on pkg/k8s/node.go
> +	ctx, cancel := context.WithTimeout(context.TODO(), 120*time.Second)
https://github.com/cilium/cilium/blob/master/pkg/defaults/defaults.go is a good place to store timeout values

2020-04-16 09:42 UTC, aanm requested changes
>When using interfaces with MTU=9000, we sometimes see how cilium-agent
gets stuck when doing this Rest call.

Can you provide more context why is this happening?

2020-04-16 09:42 UTC, aanm commented on pkg/k8s/node.go
> +        }
Why the use of channels? the context itself should be enough to timeout this request.

2020-04-21 10:46 UTC, manuelbuil commented
I can't reproduce the issue anymore. I suspect it got fixed with the client-go update. Therefore, I close this

2020-04-21 10:46 UTC, closed without merging