Handle audit mode in cilium endpoint list and kubectl get cep
cilium/cilium pull request #11011
Opened 2020-04-16 02:10 UTC by ap4y

This patch improve enforcement status reporting for
'cilium endpoint list' and 'kubectl get cep'. Former will have a new
audit status and later will show Enforcing=false when policy audit
mode is enabled.

2020-04-16 10:26 UTC, aanm reviewed
Can you clarify the PR description a little bit? You're saying the if `audit` mode is set the `cilium endpoint list` will show Ingress/Egress policy as "Disabled"?

2020-04-16 10:26 UTC, aanm commented
test-me-please

2020-04-16 22:22 UTC, ap4y commented
@aanm I have updated description with examples of both commands to make it more clear.

2020-04-16 22:34 UTC, joestringer approved these changes
CLI LGTM.

2020-04-20 18:02 UTC, aanm requested changes
From a usability PoV it is not clear to me what "Audit" means, it's not clear if a policy is being enforced or not. I would prefer to see "Disabled (audit)"

2020-04-21 03:16 UTC, ap4y commented
Updated state label from `Audit` to `Disabled (Audit)`.

2020-04-21 19:05 UTC, aanm approved these changes

2020-04-21 19:05 UTC, aanm commented
test-me-please

2020-04-22 01:14 UTC, joestringer approved these changes

2020-04-22 01:16 UTC, joestringer commented
CI (Ginkgo) failure seems related to the latest change, GKE looks more like a flake. PTAL.

2020-04-22 02:31 UTC, ap4y commented
@joestringer Fixed regex escaping in the Gingko spec

2020-04-22 08:12 UTC, aanm commented
test-me-please

2020-04-24 10:27 UTC, merged

2020-07-24 14:31 UTC, tklauser commented on api/v1/models/endpoint_policy_enabled.go
> +	EndpointPolicyEnabledAuditBoth EndpointPolicyEnabled = "audit-both"
It looks like this PR didn't include the corresponding changes made to `api/v1/openapi.yaml` from which these consts were generated using `make generate-api`. When I rerun `make generate-api`, these consts are gone :( Same for the hunk below.

2020-07-24 14:39 UTC, tklauser commented on api/v1/models/endpoint_policy_enabled.go
> +	EndpointPolicyEnabledAuditBoth EndpointPolicyEnabled = "audit-both"
Adressed in #12652. I'll also make a PR adding a GitHub action to check the generated API (similar to what we already do for the k8s APIs).