Improve tunnel identity notifications
cilium/cilium pull request #11027
Opened 2020-04-17 05:38 UTC by joestringer

These two improvements were previously part of #10951 for visibility and debugging, but a different approach to the bugfix was taken. This PR just splits out the notifications changes.

/cc @jrfastab already reviewed these and gave thumbs up.

2020-04-17 05:38 UTC, joestringer commented
test-me-please

2020-04-17 20:43 UTC, joestringer commented
Hit #11029

2020-04-20 11:01 UTC, qmonnet requested changes

2020-04-20 11:01 UTC, qmonnet commented on bpf/bpf_overlay.c
> +		*identity = get_identity(ctx);
Is this line necessary at all with the change above? If I understand correctly we have:
``` c
if (decrypted) {
	*identity = key.tunnel_id = get_identity(ctx);
} else { ... }

cilium_dbg(...);

// No change to *identity, or decrypted, or ctx->mark

if (!decrypted) { ... }
else { // if (decrypted)
	*identity = get_identity(ctx);
}
```
So `*identity` is set twice to the same value?

2020-04-20 11:01 UTC, qmonnet commented on bpf/bpf_overlay.c
> +		*identity = get_identity(ctx);
Same remark.

2020-04-21 01:56 UTC, joestringer commented on bpf/bpf_overlay.c
> +		*identity = get_identity(ctx);
Perhaps not. IMO it's a little easier to read if the `if/else` conditions initialize the `*identity` in the same spot. I can take a look whether that's possible to do.

2020-04-21 09:26 UTC, qmonnet commented on bpf/bpf_overlay.c
> +		*identity = get_identity(ctx);
Not sure if you understand each other. The two `if` are consecutive, and I meant that if `decrypted` is `true`, we execute twice `*identity = get_identity(ctx);` successively, with no change to `*identity` or to the result from `get_identity(ctx);` in the meantime. Isn't the second assignment identical to the first, and thus useless?

2020-04-22 01:20 UTC, joestringer commented on bpf/bpf_overlay.c
> +		*identity = get_identity(ctx);
I got half way through my reply to this in the morning before github broke..

Summary, you're right, I read the code wrong when I first saw your review. Fixed it up now. Thanks for the review and the patience :-)

2020-04-22 01:20 UTC, joestringer commented
test-me-please

2020-04-22 09:04 UTC, qmonnet commented on bpf/bpf_overlay.c
> +		*identity = get_identity(ctx);
Sure, no problem :)

2020-04-22 09:05 UTC, qmonnet approved these changes

2020-04-22 09:14 UTC, qmonnet commented
test-gke

2020-04-24 02:33 UTC, merged