Fix BPF map data race conditions
cilium/cilium pull request #11050
Opened 2020-04-19 15:09 UTC by tgraf

2020-04-20 07:29 UTC, tgraf commented
test-me-please

2020-04-20 13:45 UTC, tgraf commented
test-me-please

2020-04-20 23:37 UTC, tgraf commented
restart-gke

2020-04-21 00:07 UTC, tgraf commented
test-gke

2020-04-21 00:44 UTC, joestringer requested changes
Looks like a couple of `m.cache` usages without holding the lock were missed, PTAL.

2020-04-21 00:44 UTC, joestringer commented on pkg/bpf/map_linux.go
> +	return
ICYMI, the approach below is now optimized by the Go compiler to "do the right thing" (efficiently):

```
m.RLock()
defer m.RUnlock()
return m.fd
```

(I don't care that much if it's used here or not so feel free to disregard this comment)

2020-04-21 00:44 UTC, joestringer commented on pkg/bpf/map_linux.go
> +	if err = m.openAndLock(); err != nil {
In this error condition, we will not have the lock and we will still perform the defer() immediately above, including the potential modification of `m.cache`.

2020-04-21 00:44 UTC, joestringer commented on pkg/bpf/map_linux.go
> +	if err = m.openAndLock(); err != nil {
Similar usage of `m.cache` as the above comment, via `m.deleteCacheEntry()`.

2020-04-21 00:44 UTC, joestringer commented on pkg/bpf/map_linux.go
> +	if err := m.openAndLock(); err != nil {
TIL open / close don't need to be balanced; maps can be opened any number of times but should be closed once.

LGTM.

2020-04-21 08:42 UTC, tgraf commented
test-me-please

2020-04-21 19:07 UTC, aanm commented
The GKE test failures seem to be related as they are touching bpf maps? `bpf-map-sync-cilium_ipcache           never          4s ago       9       4 map sync errors`

2020-04-21 21:07 UTC, aanm requested changes
Also there's potential deadlock for the `m.Flush()` call.

```
POTENTIAL DEADLOCK: Recursive locking:
current goroutine 24 lock 0xc00026e078
../../lock/lock_debug.go:62 lock.(*internalRWMutex).Lock { i.RWMutex.Lock() } <<<<<
../../bpf/map_linux.go:930 bpf.(*Map).Delete { m.lock.Lock() }
ctmap.go:377 ctmap.purgeCtEntry4 { err := m.Delete(key) }
ctmap.go:414 ctmap.doGC4.func1 { err := purgeCtEntry4(m, currentKey4Global, natMap) }
../../bpf/map_linux.go:791 bpf.(*Map).DumpReliablyWithCallback { cb(mk, mv) }
ctmap.go:451 ctmap.doGC4 { stats.dumpError = m.DumpReliablyWithCallback(filterCallback, stats.DumpStats) }
ctmap.go:488 ctmap.doGC { return int(doGC4(m, filter).deleted) }
ctmap.go:509 ctmap.(*Map).Flush { return doGC(m, &GCFilter{ }
ctmap.go:509 ctmap.(*Map).Flush { return doGC(m, &GCFilter{ }
/usr/local/go/src/reflect/value.go:460 reflect.Value.call { call(frametype, fn, args, uint32(frametype.size), uint32(retOffset)) }
/usr/local/go/src/reflect/value.go:321 reflect.Value.Call { return v.call("Call", in) }
../../../vendor/gopkg.in/check.v1/check.go:792 check%2ev1.(*suiteRunner).forkTest.func1 { c.method.Call([]reflect.Value{reflect.ValueOf(c)}) }
../../../vendor/gopkg.in/check.v1/check.go:675 check%2ev1.(*suiteRunner).forkCall.func1 { dispatcher(c) }

Previous place where the lock was grabbed (same goroutine)
../../lock/lock_debug.go:78 bpf.(*Map).openAndRLock { i.RWMutex.RLock() } <<<<<
../../bpf/map_linux.go:503 bpf.(*Map).openAndRLock { m.lock.RLock() }
../../bpf/map_linux.go:694 bpf.(*Map).DumpReliablyWithCallback { if err := m.openAndRLock(); err != nil { }
ctmap.go:451 ctmap.doGC4 { stats.dumpError = m.DumpReliablyWithCallback(filterCallback, stats.DumpStats) }
ctmap.go:488 ctmap.doGC { return int(doGC4(m, filter).deleted) }
ctmap.go:509 ctmap.(*Map).Flush { return doGC(m, &GCFilter{ }
ctmap.go:509 ctmap.(*Map).Flush { return doGC(m, &GCFilter{ }
/usr/local/go/src/reflect/value.go:460 reflect.Value.call { call(frametype, fn, args, uint32(frametype.size), uint32(retOffset)) }
/usr/local/go/src/reflect/value.go:321 reflect.Value.Call { return v.call("Call", in) }
../../../vendor/gopkg.in/check.v1/check.go:792 check%2ev1.(*suiteRunner).forkTest.func1 { c.method.Call([]reflect.Value{reflect.ValueOf(c)}) }
../../../vendor/gopkg.in/check.v1/check.go:675 check%2ev1.(*suiteRunner).forkCall.func1 { dispatcher(c) }

Other goroutines holding locks:
goroutine 24 lock 0x12a4340
../../lock/lock_debug.go:91 lock.(*internalMutex).Lock { i.Mutex.Lock() } <<<<<
ctmap.go:450 ctmap.doGC4 { globalDeleteLock[m.mapType].Lock() }
ctmap.go:488 ctmap.doGC { return int(doGC4(m, filter).deleted) }
ctmap.go:509 ctmap.(*Map).Flush { return doGC(m, &GCFilter{ }
ctmap.go:509 ctmap.(*Map).Flush { return doGC(m, &GCFilter{ }
/usr/local/go/src/reflect/value.go:460 reflect.Value.call { call(frametype, fn, args, uint32(frametype.size), uint32(retOffset)) }
/usr/local/go/src/reflect/value.go:321 reflect.Value.Call { return v.call("Call", in) }
../../../vendor/gopkg.in/check.v1/check.go:792 check%2ev1.(*suiteRunner).forkTest.func1 { c.method.Call([]reflect.Value{reflect.ValueOf(c)}) }
../../../vendor/gopkg.in/check.v1/check.go:675 check%2ev1.(*suiteRunner).forkCall.func1 { dispatcher(c) }
```

2020-04-21 21:07 UTC, aanm commented on pkg/bpf/map_linux.go
> +	// all Open() variants
Conventionally, a lock is on top of all fields that it protects so this should be on line 97 to be more explicit.

2020-04-21 21:07 UTC, aanm commented on pkg/bpf/map_linux.go
> +	// when the function exits
Looking at the previous code it seems to me that some call backs were only called after `DumpWithCallback` was returned? Is my assessment correct?

2020-04-29 00:49 UTC, joestringer commented
We discussed offline scoping this out of the next v1.7 release, so moving to prio/high.

2020-06-02 09:13 UTC, tgraf commented
Closed in favor of #11812

2020-06-02 09:13 UTC, closed without merging