Remove deprecated --container-runtime{,-endpoint} options
cilium/cilium pull request #11060
Opened 2020-04-20 12:11 UTC by tklauser

These no longer have any effect, were deprecated in 1.7 and announced to
be removed in the upcoming 1.8.

Also remove remains of the --docker command line option which is no
longer supported since commit 532ad9d44a6f ("rm pkg/workloads")

2020-04-20 12:11 UTC, tklauser commented
test-me-please

2020-04-20 12:12 UTC, aanm requested changes

2020-04-20 12:12 UTC, aanm commented on Documentation/install/upgrade.rst
> +  were deprecated in Cilium 1.7 and are now removed.
typo. `did not were`?

2020-04-20 12:13 UTC, tklauser commented on Documentation/install/upgrade.rst
> +  were deprecated in Cilium 1.7 and are now removed.
Oops, yes. Fixed.

2020-04-20 15:16 UTC, tklauser commented
test-me-please

2020-04-20 16:30 UTC, aanm approved these changes

2020-04-20 19:02 UTC, tklauser commented
test-gke

2020-04-21 04:25 UTC, soumynathan reviewed
LGTM

2020-04-21 08:03 UTC, pchaigno commented
test-gke

2020-04-21 12:58 UTC, pchaigno approved these changes

2020-04-21 20:16 UTC, merged