CI: Istio debugging
cilium/cilium pull request #11072
Opened 2020-04-20 16:38 UTC by jrajahalme

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

2020-04-20 16:38 UTC, jrajahalme commented
test-missed-k8s

2020-04-20 16:44 UTC, jrajahalme commented
test-missed-k8s

2020-04-20 16:46 UTC, jrajahalme commented
test-missed-k8s

2020-04-23 10:12 UTC, aanm commented
this PR has been marked as a draft PR since it had a WIP label. Please click in "Ready for review" [below vvv ] once the PR is ready to be reviewed. CI will still run for draft PRs.

2020-04-23 16:58 UTC, jrajahalme commented
@aanm istioctl failing with K8s 1.14 and 1.15 may be due to the installed kubectl being version 1.18. When testing locally on Mac I had to downgrade kubectl to match the server version to make it work. Do you know how I could downgrade kubectl, or maybe we should do it universally for older k8s versions?

Ref:
> kubectl
> kubectl is supported within one minor version (older or newer) of kube-apiserver.
>
> Example:
>
> kube-apiserver is at 1.18
> kubectl is supported at 1.19, 1.18, and 1.17

2020-04-23 17:09 UTC, aanm commented
> @aanm istioctl failing with K8s 1.14 and 1.15 may be due to the installed kubectl being version 1.18. When testing locally on Mac I had to downgrade kubectl to match the server version to make it work. Do you know how I could downgrade kubectl, or maybe we should do it universally for older k8s versions?
> 
> Ref:
> 
> > kubectl
> > kubectl is supported within one minor version (older or newer) of kube-apiserver.
> > Example:
> > kube-apiserver is at 1.18
> > kubectl is supported at 1.19, 1.18, and 1.17

Downgrade `kubectl` where? in istioctl?

2020-04-23 17:16 UTC, jrajahalme commented
istioctl is complaining that it can't find kubectl in $PATH. My hunch is that the installed kubectl version (1.18) is found, but then fails due to some compatibility reason. I'm assuming istioctl is trying to invoke kubectl from the $PATH, but the installed kubectl version (at /usr/local/bin/kubectl) is version 1.18, even though the VM is booted with K8S_VERSION=1.1[45].

This is the output of the commands I added in this PR for debugging purposes:
```
time="2020-04-20T19:07:53Z" level=debug msg="running command: which kubectl"
cmd: "which kubectl" exitCode: 0 duration: 1.683695ms stdout:
/usr/local/bin/kubectl

time="2020-04-20T19:07:53Z" level=debug msg="running command: echo $PATH"
cmd: "echo $PATH" exitCode: 0 duration: 892.9µs stdout:
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

time="2020-04-20T19:07:53Z" level=debug msg="running command: `which kubectl` version"
cmd: "`which kubectl` version" exitCode: 0 duration: 51.389712ms stdout:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:32:32Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

2020-04-23 17:17 UTC, jrajahalme commented
@aanm Do you know why the kubectl reports client version 1.18 on a test VM with `K8S_VERSION=1.14`??

2020-04-23 17:22 UTC, jrajahalme commented
VM start scripts shows:
```
11:58:16      k8s1-1.14: Setting up kubectl (1.14.10-00) ...
```
But then when running tests `kubectl version` reports client version 1.18???

2020-04-23 17:50 UTC, aanm commented
> VM start scripts shows:
> 
> ```
> 11:58:16      k8s1-1.14: Setting up kubectl (1.14.10-00) ...
> ```
> 
> But then when running tests `kubectl version` reports client version 1.18???

IIRC @jrajahalme that is the version of the `kubectl` installed in the nodes (not VMs)

2020-04-23 18:45 UTC, jrajahalme commented
@aanm Exactly, istioctl is run in the host, just like any kubectl command run in the test?

2020-04-23 18:46 UTC, jrajahalme commented
So I conflated the VM k8s install to the host kubectl above, sorry.

2020-04-23 18:59 UTC, jrajahalme commented
This PR adds:
```
		res = kubectl.ExecShort("`which kubectl` version")
```
Which reports client version 1.18. It would make sense that this is coming from the host, but `kubectl` is initialized as:
```
		kubectl = helpers.CreateKubectl(helpers.K8s1VMName(), logger)
```

2020-04-23 19:11 UTC, aanm commented
> This PR adds:
> 
> ```
> 		res = kubectl.ExecShort("`which kubectl` version")
> ```
> 
> Which reports client version 1.18. It would make sense that this is coming from the host, but `kubectl` is initialized as:
> 
> ```
> 		kubectl = helpers.CreateKubectl(helpers.K8s1VMName(), logger)
> ```

@jrajahalme and isn't that VM running k8s 1.18?

2020-04-23 19:14 UTC, jrajahalme commented
@aanm I don't know, is it different from the ones started under `K8S_VERSION=1.;14`? If so, is there a way to start K8s1VM with K8s 1.14 instead?

2020-04-23 19:17 UTC, jrajahalme commented
And why would we configure `k8s1` and `k8s2` with different versions of Kubernetes?

2020-04-23 23:21 UTC, jrajahalme commented
test-missed-k8s

2020-04-23 23:41 UTC, jrajahalme commented
test-missed-k8s

2020-04-24 00:15 UTC, jrajahalme commented
test-missed-k8s

2020-04-24 00:39 UTC, jrajahalme commented
test-missed-k8s

2020-04-24 01:01 UTC, jrajahalme commented
test-missed-k8s

2020-04-24 01:35 UTC, jrajahalme commented
test-missed-k8s

2020-04-24 02:14 UTC, jrajahalme commented
test-missed-k8s

2020-04-24 02:34 UTC, jrajahalme commented
test-missed-k8s

2020-04-24 06:05 UTC, jrajahalme commented
test-me-please

2020-04-24 06:05 UTC, jrajahalme commented
never-tell-me-the-odds

2020-04-24 12:49 UTC, nebril requested changes
Great job with finding the root cause of the issue!

While this change fixes the problem, I believe that going back to "the old way" of running kubectl via SSH in isn't the way to go.

SSH-specific execution code is left in the test framework exclusively to support Runtime tests. Historically, SSH to vagrant VM was unreliable and made debugging harder. As we retire Runtime tests, we should be able to delete this code with minimal pain.

I would strongly prefer fixing this by adding multiple versions of kubectl binaries on CI nodes and manipulating PATH. I can add downloading of all needed kubectl binaries into node provisioning scripts, after that this change would just need symlinking to them appropriately and setting the PATH.

Also, thanks for fixing print-node-ip bugs, I am not sure how these could have persisted for so long

2020-04-24 16:48 UTC, jrajahalme commented
test-me-please

2020-04-24 17:17 UTC, jrajahalme commented
@nebril Running K8s CI tests locally on a Mac host without Jenkins, when started with `test/vagrant-local-start.sh` depends on running the Ginkgo Execs in via SSH. I'd like to keep this functionality if possible.

I'll revise this PR after you have made the old kubectl versions available. We probably should use an old version for the k8s 1.11 tests in the regular ginkgo k8s test suite as well.

2020-04-24 20:41 UTC, christarazi approved these changes
Good find!

2020-04-27 14:33 UTC, nebril commented
after discussing offline let's merge this as an immediate mitigation

2020-04-27 14:34 UTC, merged