vendor: update github.com/sirupsen/logrus to v1.5.0
cilium/cilium pull request #11149
Opened 2020-04-24 20:16 UTC by waynr

I have recently encountered an instance of the following issues running in Cilium v1.6.4 running in a customer's cluster:

* https://github.com/sirupsen/logrus/issues/1003
* https://github.com/cilium/cilium/issues/8816

```
2020-04-24T16:30:10.38634175Z  panic: runtime error: invalid memory address or nil pointer dereference
2020-04-24T16:30:10.386806335Z  [signal SIGSEGV: segmentation violation code=0x1 addr=0x6 pc=0x1436b7e]
2020-04-24T16:30:10.386841802Z
2020-04-24T16:30:10.386865795Z  goroutine 130 [running]:
2020-04-24T16:30:10.386884479Z  github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*TextFormatter).needsQuoting(0xc0000d6780, 0x6, 0x1a4, 0x1c)
2020-04-24T16:30:10.386891262Z  	/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/text_formatter.go:268 +0x4e
2020-04-24T16:30:10.386898206Z  github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*TextFormatter).appendValue(0xc0000d6780, 0xc00041ba10, 0x2faa800, 0xc000ee4070)
2020-04-24T16:30:10.38690452Z  	/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/text_formatter.go:294 +0x6d
2020-04-24T16:30:10.386910689Z  github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*TextFormatter).appendKeyValue(0xc0000d6780, 0xc00041ba10, 0x33ff9a0, 0x6, 0x2faa800, 0xc000ee4070)
2020-04-24T16:30:10.386917674Z  	/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/text_formatter.go:285 +0x90
2020-04-24T16:30:10.386923862Z  github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*TextFormatter).Format(0xc0000d6780, 0xc00014c230, 0xc0000d24b0, 0xc001b87b18, 0x1359306, 0x33842c0, 0xc001b87b18)
2020-04-24T16:30:10.387469817Z  	/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/text_formatter.go:202 +0xa52
2020-04-24T16:30:10.413555308Z  github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*Entry).write(0xc00014c230)
2020-04-24T16:30:10.413637785Z  	/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/entry.go:255 +0x81
2020-04-24T16:30:10.41364715Z  github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.Entry.log(0xc0000d2480, 0xc00041b980, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2020-04-24T16:30:10.413674162Z  	/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/entry.go:231 +0x193
2020-04-24T16:30:10.413681447Z  github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*Entry).Log(0xc00014c1c0, 0xc000000004, 0xc001b87ce0, 0x1, 0x1)
2020-04-24T16:30:10.413688708Z  	/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/entry.go:268 +0xed
2020-04-24T16:30:10.413715173Z  github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*Entry).Info(...)
2020-04-24T16:30:10.414225404Z  	/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/entry.go:285
2020-04-24T16:30:10.414277925Z  github.com/cilium/cilium/pkg/endpointmanager.RegenerateAllEndpoints(0xc00041b7d0, 0xc00041b7d0)
2020-04-24T16:30:10.414290567Z  	/go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:466 +0x1c1
2020-04-24T16:30:10.414296495Z  main.(*Daemon).policyUpdateTrigger(0xc0003a45a0, 0xc000ee4060, 0x1, 0x1)
2020-04-24T16:30:10.414302346Z  	/go/src/github.com/cilium/cilium/daemon/policy.go:74 +0xe3
2020-04-24T16:30:10.414307707Z  github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter(0xc0006a3860)
2020-04-24T16:30:10.414313525Z  	/go/src/github.com/cilium/cilium/pkg/trigger/trigger.go:210 +0x2d7
2020-04-24T16:30:10.414319442Z  created by github.com/cilium/cilium/pkg/trigger.NewTrigger
2020-04-24T16:30:10.414325351Z  	/go/src/github.com/cilium/cilium/pkg/trigger/trigger.go:133 +0x130
```

After spending a bit of time digging in, I am pretty confused as to what field might be nil during the call to `Entry.Info()` because the value being explicitly set as a field in `RegenerateAllEndpoints` is a string, which to my admittedly dim understanding, cannot take a nil value.

So in the hopes of maybe doing some good I am proposing that the `logrus` dependency be updated to the latest `v1.5.0` which includes [this data race fix to `Entry.WithFields`](https://github.com/sirupsen/logrus/commit/c7278b2d7a38c9dae5bf70203d64696be84f6755) and [this "data bleed" in withContext](https://github.com/sirupsen/logrus/commit/bcc146f96bac06492f800415b0ad6bd2ad1ff4fe). I've spent a little bit of time trying to wrap my puny mind around how either of these could lead to the nil pointer dereference above to little avail.

I also found https://github.com/cilium/cilium/commit/78edf46edb3789714f6b0df7d6b41456bb9868c0 in this repository's history and I'm wondering if any Cilium maintainers can speak to whether or not this could prevent the kind of nil pointer dereference shown above (or for that matter if either of the logrus commits I reference above and am hoping to pull in with logrus `v1.5.0` could do the trick). Thanks for your consideration!

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note

```

2020-04-24 21:18 UTC, christarazi reviewed
Thanks for the PR!

2020-04-24 21:18 UTC, christarazi commented
test-me-please

2020-04-24 22:06 UTC, aanm requested changes
Thank you for your PR and the the investigation that you have done.

Although https://github.com/sirupsen/logrus/pull/1047 and https://github.com/sirupsen/logrus/commit/bcc146f96bac06492f800415b0ad6bd2ad1ff4fe are included in v1.5.0, which seem to help fixing this issue they also seem to have introduced regressions in v1.5.0 and https://github.com/sirupsen/logrus/pull/1047 was reverted https://github.com/sirupsen/logrus/issues/1046#issuecomment-614719354.

Since v1.5.0 has these regressions, which might affect Cilium stability we can't accept these proposed changes, not until those regressions are fixed.

We have never seen this bug coming back again since we have merged these PRs https://github.com/cilium/cilium/pull/10168 and https://github.com/cilium/cilium/pull/10192 (which are backported and available since 1.6.7). Please upgrade your Cilium version to a release newer or equal than 1.6.7 to see if you can hit the issue again.

2020-04-28 14:04 UTC, waynr commented
> We have never seen this bug coming back again since we have merged these PRs #10168 and #10192 (which are backported and available since 1.6.7). Please upgrade your Cilium version to a release newer or equal than 1.6.7 to see if you can hit the issue again.

Thanks for the info @aanm! We have work in progress to upgrade all our clusters to 1.7.2 so it sounds like we should be good. I'll be sure to report back with an issue if we do happen to see a recurrence after upgrading.

2020-06-11 17:46 UTC, closed without merging