bpf: xdp asm volatile fix in relation to reg spill
cilium/cilium pull request #11152
Opened 2020-04-25 00:43 UTC by borkmann

See commit msg.

2020-04-25 00:46 UTC, borkmann commented
test-me-please

2020-04-25 00:48 UTC, jrfastab approved these changes

2020-04-25 01:27 UTC, joestringer approved these changes

2020-04-25 08:17 UTC, borkmann commented
test-focus K8sService.*

2020-04-25 08:17 UTC, borkmann commented
restart-ginkgo

2020-04-25 08:17 UTC, borkmann commented
restart-gke

2020-04-25 12:32 UTC, pchaigno approved these changes

2020-04-27 10:35 UTC, qmonnet approved these changes

2020-04-27 10:35 UTC, qmonnet commented
test-focus K8sService.*

2020-04-27 10:35 UTC, qmonnet commented
restart-gke

2020-04-27 10:36 UTC, qmonnet commented
test-gke

2020-04-27 12:23 UTC, aanm requested changes

2020-04-27 12:23 UTC, aanm commented on daemon/cmd/daemon_main.go
> +			log.Fatal("Cannot use NodePort acceleration with tunneling. Only direct routing mode supported at this point.")
To make it clear for users how they can fix this we should probably end this error message with `supported at this point. Either run cilium-agent with '--%s=%s' or '--%s=%s'", option.NodePortRange, option.NodePortAccelerationNone, option.TunnelName, option.TunnelDisabled)`

2020-04-28 08:52 UTC, borkmann commented
test-me-please

2020-04-28 11:30 UTC, merged