Move labels to ep
cilium/cilium pull request #1116
Opened 2017-07-13 16:22 UTC by amreshakim

Decouple labels from containers and store them in endpoints.

- change api to allow passing labels during endpoint creation
- regenerate swagger API
- remove labels from containers
- store labels in endpoints

https://github.com/cilium/cilium/issues/1041

2017-07-14 13:42 UTC, aanm requested changes
`CreateOrUpdateIdentity` is an important function and should have got a description on top (mea culpa).

The `epid` on that function needs to be a cluster wide ID (`s/epid/clusterWideEPID/g`). This is currently achieved (of course not with 100% certain) with docker ID. By using the local endpoint ID, which only goes from 1-65535, we can't make sure how many containers / endpoints are associated with a particular set of labels.

2017-07-14 13:42 UTC, aanm commented on daemon/docker_watcher.go
> -		if ok && !orchLabelsModified {
If the labels weren't changed we can safely stop here as before, no?

2017-07-14 13:42 UTC, aanm commented on daemon/docker_watcher.go
> -func updateOrchLabels(c *container.Container, l labels.Labels) bool {
Suggestion: Create a commit and move this function to the `endpoint.go` where the endpoint is the receiver.

2017-07-14 13:42 UTC, aanm commented on daemon/endpoint.go
> +			return errLabelsAdd
Small nit: why not return the error?
`return fmt.Errorf("Could not add labels %v while creating an ep %s: %s", add, params.ID, err)`

2017-07-14 13:42 UTC, aanm commented on daemon/endpoint.go
> +		log.Infof("NewPutEndpointIDLabelsNotFound %v %v container not found", id, ep)
`log.Infof` with endpoint's `%v` result on an ultra verbose output. Use the relevant endpoint's data or simply the endpoint ID.

If the container was not found shouldn't we `return NewPutEndpointIDLabelsNotFound` like before?

2017-07-14 13:42 UTC, aanm commented on pkg/endpoint/endpoint.go
> +	defer e.Mutex.Unlock()
`defer` adds a small overhead, leave it as before. For small functions doesn't make sense to use `defer` (IMHO)

2017-07-14 15:58 UTC, amreshakim commented on daemon/docker_watcher.go
> -		if ok && !orchLabelsModified {
I was hoping you could help me out with this. If you look at the original code, it executes this if statement only if the container already exists. I have removed it initially thinking exactly the same but after many changes I revert to the original logic.

2017-07-14 15:59 UTC, amreshakim commented on daemon/endpoint.go
> +			return errLabelsAdd
good point!

2017-07-14 15:59 UTC, amreshakim commented on daemon/endpoint.go
> +		log.Infof("NewPutEndpointIDLabelsNotFound %v %v container not found", id, ep)
agreed, it is an artifact of my debugging.

2017-07-14 16:02 UTC, amreshakim commented on pkg/endpoint/endpoint.go
> +	defer e.Mutex.Unlock()
That is also an artifact of the debugging but my thought was if e.removeDirectory() panics, is there a possibility to leak the lock?

2017-07-14 16:02 UTC, amreshakim commented on daemon/docker_watcher.go
> -func updateOrchLabels(c *container.Container, l labels.Labels) bool {
will do

2017-07-14 16:07 UTC, tgraf commented
> CreateOrUpdateIdentity is an important function and should have got a description on top (mea culpa).
> 
> The epid on that function needs to be a cluster wide ID (s/epid/clusterWideEPID/g). This is currently achieved (of course not with 100% certain) with docker ID. By using the local endpoint ID, which only goes from 1-65535, we can't make sure how many containers / endpoints are associated with a particular set of labels.

I suggest we keep this as-is. I have a large change queued up which will completely rework the reference counting on identities. It will count the references on agent level instead of endpoint level. Each agent can internally do reference counting and figure out once an identity is no longer in use by the local agent. This will remove number of kvstore operations and thus improves scale.

2017-07-14 16:09 UTC, amreshakim commented
Thanks Andre!

2017-07-14 16:23 UTC, amreshakim commented on daemon/endpoint.go
> +			return errLabelsAdd
actually, it has to be middleware.Responder type so I will leave it as is.

2017-07-14 16:26 UTC, amreshakim commented on daemon/endpoint.go
> +		log.Infof("NewPutEndpointIDLabelsNotFound %v %v container not found", id, ep)
and to answer the second part of the question, we do not exit now since it is the exact case for mesos.

2017-07-14 17:33 UTC, aanm commented on pkg/endpoint/endpoint.go
> +	defer e.Mutex.Unlock()
In case of panic cilium crashes :) but yeah, your case makes sense

2017-07-14 19:51 UTC, amreshakim commented on daemon/docker_watcher.go
> -			if orchLabelsModified = updateOrchLabels(cont, lbls); !orchLabelsModified {
@aanm this is what I referred to as the original logic for skipping if labels modified. To skip is should satisfy both ok on line 265 and ! orchLabelsModified.

2017-07-14 20:17 UTC, ianvernon commented on pkg/endpoint/endpoint.go
>  // the endpoint's mutex locked.
We do not need to lock the mutex anymore with this function so this can be removed

2017-07-14 20:30 UTC, ianvernon approved these changes
Looks great.

2017-07-14 21:33 UTC, aanm commented on daemon/docker_watcher.go
> -			if orchLabelsModified = updateOrchLabels(cont, lbls); !orchLabelsModified {
Ah right

2017-07-14 21:35 UTC, aanm commented on daemon/docker_watcher.go
> +	if _, ok := d.containers[dockerID]; ok {
Redundant, you can remove this line as well and simply write `delete(d.containers. dockerID)`

2017-07-14 21:38 UTC, aanm commented on daemon/labels.go
> -	identity, _, err := d.CreateOrUpdateIdentity(lbls, contID)
This needs to be the `contID` as discussed before.

2017-07-14 21:38 UTC, aanm commented on daemon/labels.go
> -		if err := d.DeleteIdentityBySHA256(oldLabelsHash, contID); err != nil {
same here

2017-07-14 21:39 UTC, aanm requested changes

2017-07-14 21:39 UTC, aanm commented on daemon/state.go
> -		l, _, err := d.CreateOrUpdateIdentity(ep.SecLabel.Labels, ep.DockerID)
should be DockerID

2017-07-14 21:43 UTC, amreshakim commented on daemon/labels.go
> -	identity, _, err := d.CreateOrUpdateIdentity(lbls, contID)
this won't work for mesos though. We create the endpoint in CNI plugin before we receive a create-container event. OK, I might have misunderstood @tgraf's comment. Leaving it "as is" should be read as is in my PR or as it was before?

2017-07-14 21:43 UTC, amreshakim commented on daemon/labels.go
> -		if err := d.DeleteIdentityBySHA256(oldLabelsHash, contID); err != nil {
see above

2017-07-14 21:44 UTC, amreshakim commented on daemon/state.go
> -		l, _, err := d.CreateOrUpdateIdentity(ep.SecLabel.Labels, ep.DockerID)
we'd have to mix docker-id and cluster-wide-ep-id then

2017-07-14 22:57 UTC, tgraf commented on daemon/labels.go
> -	identity, _, err := d.CreateOrUpdateIdentity(lbls, contID)
I will remove this anyway so whatever works with minimal effort.

2017-07-14 22:59 UTC, amreshakim commented on daemon/labels.go
> -	identity, _, err := d.CreateOrUpdateIdentity(lbls, contID)
Awesome! Thanks Thomas!

2017-07-16 19:37 UTC, amreshakim commented
merged as apart of https://github.com/cilium/cilium/pull/1126

2017-07-16 19:37 UTC, closed without merging