Improve CI test bootstrapping
cilium/cilium pull request #11167
Opened 2020-04-27 10:15 UTC by tgraf

* This deletes all non-essential namespaces before the first test
* Decouples node-labeling from node naming

2020-04-27 10:17 UTC, tgraf commented
test-me-please

2020-04-27 11:22 UTC, tgraf commented
test-me-please

2020-04-27 23:30 UTC, tgraf commented
test-me-please

2020-04-28 07:07 UTC, tgraf commented
restart-ginkgo

2020-04-28 17:20 UTC, nebril requested changes

2020-04-28 17:20 UTC, nebril commented on test/helpers/kubectl.go
> +// labelNodes labels nodes in vagrant env. If you are running tests on
This comment seems to be deprecated by now.

2020-04-29 08:17 UTC, merged