helm: Update hubble-ui chart
cilium/cilium pull request #11273
Opened 2020-04-30 23:12 UTC by michi-covalent

- Use v0.5.0 tag by default instead of latest.
- Rely on requirements.yaml to enable the chart instead of guarding
  individual templates.

Ref: https://github.com/cilium/hubble-ui/releases

Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

2020-05-01 12:46 UTC, gandro approved these changes
Awesome, thanks for taking care of this!

2020-05-01 12:46 UTC, gandro commented on install/kubernetes/cilium/charts/hubble-ui/values.yaml
>    pullPolicy: Always
nit: Maybe we should default to `IfNotPresent` now that we have a proper tag?

2020-05-01 12:46 UTC, gandro commented
test-me-please

2020-05-01 15:05 UTC, aanm approved these changes

2020-05-01 15:06 UTC, aanm requested changes

2020-05-01 15:06 UTC, aanm commented on install/kubernetes/cilium/charts/hubble-ui/values.yaml
>    pullPolicy: Always
Yes, please change to IfNotPresent

2020-05-01 16:11 UTC, michi-covalent commented on install/kubernetes/cilium/charts/hubble-ui/values.yaml
>    pullPolicy: Always
yes, of course

2020-05-01 16:15 UTC, michi-covalent commented
change the default image pull policy to IfNotPresent.

2020-05-01 16:59 UTC, aanm approved these changes

2020-05-01 22:27 UTC, michi-covalent commented
test-me-please

2020-05-04 10:24 UTC, gandro commented
test-me-please

2020-05-04 11:29 UTC, tgraf commented
Unit tests hit: https://github.com/cilium/cilium/issues/11289

Restarting

2020-05-04 16:03 UTC, michi-covalent commented
test-me-please

2020-05-06 13:21 UTC, gandro commented
test-me-please

2020-05-06 22:16 UTC, joestringer approved these changes

2020-05-06 22:16 UTC, merged