CI: Improve bootstraping before each test
cilium/cilium pull request #11287
Opened 2020-05-01 14:23 UTC by tgraf

See individual commits

2020-05-01 14:39 UTC, tgraf commented
test-me-please

2020-05-04 10:28 UTC, tgraf commented
test-gke

2020-05-05 11:02 UTC, tklauser requested changes
Nice improvements! Two small nits about functions that are no longer used after this PR and could be removed.

2020-05-05 11:02 UTC, tklauser commented on test/helpers/kubectl.go
> -	if err := kub.DeleteCiliumDS(); err != nil {
Looks like this was the only place where `DeleteCiliumDS` is called. Should its implementation be removed as well?

2020-05-05 11:02 UTC, tklauser commented on test/helpers/kubectl.go
> -	if err := kub.DeleteCiliumOperator(); err != nil {
Same here. Looks like this was the only place where `DeleteCiliumOperator` is called. Remove its implementation?

2020-05-05 11:53 UTC, nebril requested changes
One comment inline, agreed with tklauser comments. Otherwise looks good!

2020-05-05 11:53 UTC, nebril commented on test/helpers/kubectl.go
> +			_ = kub.DeleteResource(resourceType, "-n "+GetCiliumNamespace(GetCurrentIntegration())+" "+resource)
I think you can use `CiliumNamespace` instead of `GetCiliumNamespace` here, just to be consistent.

2020-05-05 14:15 UTC, tgraf commented on test/helpers/kubectl.go
> -	if err := kub.DeleteCiliumDS(); err != nil {
I'm still seeing many uses:
```
test/helpers/kubectl.go:func (kub *Kubectl) DeleteCiliumDS() error {
test/k8sT/Chaos.go:             kubectl.DeleteCiliumDS()
test/k8sT/Conformance.go:               kubectl.DeleteCiliumDS()
test/k8sT/Health.go:            kubectl.DeleteCiliumDS()
test/k8sT/KafkaPolicies.go:             kubectl.DeleteCiliumDS()
test/k8sT/Nightly.go:           kubectl.DeleteCiliumDS()
test/k8sT/Policies.go:          kubectl.DeleteCiliumDS()
test/k8sT/PoliciesNightly.go:           kubectl.DeleteCiliumDS()
test/k8sT/Services.go:          kubectl.DeleteCiliumDS()
test/k8sT/Services.go:                                  kubectl.DeleteCiliumDS()
test/k8sT/demos.go:             kubectl.DeleteCiliumDS()
test/k8sT/external_ips.go:              kubectl.DeleteCiliumDS()
test/k8sT/fqdn.go:              kubectl.DeleteCiliumDS()
test/k8sT/istio.go:             kubectl.DeleteCiliumDS()
```

Are you talking about a different function?

2020-05-05 14:24 UTC, tgraf commented
test-me-please

2020-05-05 14:27 UTC, tklauser commented on test/helpers/kubectl.go
> -	if err := kub.DeleteCiliumDS(); err != nil {
Grepped for the wrong function, sorry.

2020-05-05 14:27 UTC, tklauser approved these changes

2020-05-05 17:28 UTC, nebril approved these changes

2020-05-05 20:20 UTC, merged