test: Add direct-routing + L7 test
cilium/cilium pull request #11440
Opened 2020-05-08 23:12 UTC by joestringer

2020-05-08 23:12 UTC, joestringer commented
test-focus with L7 policy

2020-05-08 23:14 UTC, joestringer commented
test-focus K8s.*with L7 policy.*

2020-05-11 04:05 UTC, joestringer commented
test-me-please

2020-05-11 07:44 UTC, brb requested changes

2020-05-11 07:44 UTC, brb commented on test/k8sT/DatapathConfiguration.go
> +			It("with L7 policy", func() {
`s/It/Context/`, as AFAIK `It` doesn't allow its body to contain setup routines. From the CI run of this PR:

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:471
You may only call It from within a Describe, Context or When
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:471
```

2020-05-11 20:28 UTC, joestringer commented
test-focus K8s.*with L7 policy.*

2020-05-12 03:12 UTC, joestringer commented
test-me-please

2020-05-12 06:20 UTC, joestringer commented
Hit #11457 in K8s-1.17-Kernel-4.19 run.

2020-05-12 19:29 UTC, joestringer commented
Hit #11442 in K8s-1.11-Kernel-netnext run.

2020-05-19 09:30 UTC, brb approved these changes

2020-05-19 09:54 UTC, pchaigno approved these changes

2020-05-20 22:11 UTC, joestringer commented
I finally fixed my local testing environment and was unable to verify that L7 traffic was actually observed in this test as of the code today. #11625 will mainline the testing changes necessary to validate locally, and I'll need to respin this test to validate it actually works and tests L7 visibility.

2020-08-03 11:14 UTC, closed without merging