cilium: rename aws/eni/routing to pkg/datapath/linux/routing
cilium/cilium pull request #11452
Opened 2020-05-10 21:57 UTC by bpineau

Per discussion in #11268 : the routing rules we use here are in
no way specific to AWS ENI; they are for also used to setup
Azure IPAM routes.

While at it, also garbage collect routes on endpoint deletion
when running Azure IPAM mode.

Signed-off-by: Benjamin Pineau <benjamin.pineau@datadoghq.com>

```release-note
Also garbage collect Azure IPAM routes on endpoint removal
```

2020-05-10 23:10 UTC, christarazi requested changes
Thanks for following up! A few small comments to address for me. Also https://github.com/cilium/cilium/pull/11328 is pending, but should be merged soon which I'd like to get in before this one.

2020-05-10 23:10 UTC, christarazi commented on daemon/cmd/daemon.go
>  	// endpoint's routing in ENI mode
We should update this comment

2020-05-10 23:10 UTC, christarazi commented on pkg/datapath/linux/routing/routing_test.go
> +				// are setting the Src because interfacesingress rules don't have
```suggestion
				// are setting the Src because ingress rules don't have
```

Nit

2020-05-10 23:10 UTC, christarazi commented on pkg/endpoint/endpoint.go
> +		}).Debug("Deleting endpoint interface rules")
```suggestion
		}).Debug("Deleting endpoint routing rules")
```
I like "routing" better here as "interface rules" isn't very informative

2020-05-10 23:10 UTC, christarazi commented on pkg/endpoint/endpoint.go
> +			errs = append(errs, fmt.Errorf("unable to delete endpoint interface rules: %s", err))
```suggestion
			errs = append(errs, fmt.Errorf("unable to delete endpoint routing rules: %s", err))
```

2020-05-10 23:15 UTC, christarazi commented
Added backport label as I'd like to backport this to 1.7 since it'll be a branch we support for a while and this PR has changed code which was recently backported, so it'll be good to keep the divergence to a minimum.

2020-05-11 12:33 UTC, tklauser commented
This needs a rebase now that #11328 is merged.

2020-05-11 15:12 UTC, aanm approved these changes

2020-05-11 15:43 UTC, christarazi approved these changes
Awesome!

2020-05-12 03:06 UTC, joestringer requested changes
Thanks for following up on this.

> Per discussion in #11268 : the routing rules we use here are in
no way specific to AWS ENI; they are for also used to setup
Azure IPAM routes.

> While at it, also garbage collect routes on endpoint deletion
when running Azure IPAM mode.

I was surprised that the PR named "rename ..." made functional changes, same with the commit naming. Please consider using the biggest change as the title for the PR and commit to make it more clear for anyone searching through the PRs or commits later.

In a similar vein, in future please consider splitting functional changes into a separate commit from the refactoring changes. If we end up wanting to trace back and git-bisect the tree, it's easier to understand what changed when commits are smaller and when the changes are incremental with either functional or cosmetic changes. As is, when I glance through `git log`, I would have a tendency to skip over this commit because it sounds like it doesn't make any functional changes. Commits like this break this assumption which can be painful when attempting to find the cause of an issue later on via git logs. 

The changes themselves look fine. Given that you'll need to do a rebase anyway, do you mind fixing up the commit title?

2020-05-13 07:22 UTC, bpineau commented
@joestringer duly noted. I rebased and updated commit title as suggested.

2020-05-14 00:00 UTC, joestringer approved these changes

2020-05-14 02:57 UTC, christarazi commented
test-me-please

2020-05-14 02:58 UTC, christarazi approved these changes

2020-05-14 11:28 UTC, gandro commented
retest-runtime

2020-05-14 11:29 UTC, gandro commented
retest-net-next

2020-05-14 23:10 UTC, joestringer commented
test-me-please

2020-05-15 09:00 UTC, merged