helm: set hubble-ui securityContext
cilium/cilium pull request #11475
Opened 2020-05-11 17:32 UTC by alex1989hu

The image hubble-ui no longer needs run as root user

**Special notes for your reviewer**:
Do not merge it until new hubble-ui image is released, see corresponding pull request: [cilium/hubble-ui#31](https://github.com/cilium/hubble-ui/pull/31). Tested on k8s (`v1.18`) with enforced  [restricted PSP](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#example-policies).

Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>

Please ensure your pull request adheres to the following guidelines:

- [X] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [X] All code is covered by unit and/or runtime tests where feasible.
- [X] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [X] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [X] Provide a title or release-note blurb suitable for the release notes.
- [X] Thanks for contributing!

Fixes:
N/A

```release-note
use non-root image for hubble-ui
```

2020-05-11 17:38 UTC, alex1989hu commented
/cc @gandro  - I don't know what is wrong with the label: 1st: filled release not 2nd: removed section => same result.

2020-05-11 17:54 UTC, gandro requested changes
Thanks a lot for the PR! As discussed on Slack, I believe the `securityContext` should be opt-in (via Helm values), to allow the chart to function with the existing `v0.5` hubble-ui image.

I propose we add the following to the [values.yaml](https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/charts/hubble-ui/values.yaml) of hubble-ui.
```yaml
securityContext:
  enabled: false
  runAsUser: 1001
```

Once we have a new release of the hubble-ui container and we bump the default image tag, we can then update the `securityContext.enabled=true` by default to make it opt-out.

2020-05-11 18:19 UTC, gandro approved these changes

2020-05-11 18:19 UTC, gandro commented
test-me-please

2020-05-12 07:49 UTC, gandro commented
test-me-please

2020-05-12 20:22 UTC, gandro commented
retest-net-next

2020-05-12 20:24 UTC, aanm approved these changes

2020-05-13 08:18 UTC, merged