helm: add bpf-policy-map-max option
cilium/cilium pull request #11478
Opened 2020-05-11 19:09 UTC by alex1989hu

The source of the default value origin is: v1.7/cmdref/cilium-agent

I faced an issue today which solution and problem statement is described here https://github.com/cilium/cilium/issues/9117

This PR adds an option to let users override the default value `16384`.

**Special notes for your reviewer**:
Please backport to `v1.7` release

Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>

Please ensure your pull request adheres to the following guidelines:

- [X] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [X] All code is covered by unit and/or runtime tests where feasible.
- [X] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [X] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [X] Provide a title or release-note blurb suitable for the release notes.
- [X] Thanks for contributing!

Fixes:
N/A

2020-05-11 19:12 UTC, joestringer requested changes
Thanks for the submisson!

The helm lint check failed:
https://github.com/cilium/cilium/pull/11478/checks?check_run_id=664504076

I believe you will need to run `make -C install/kubernetes/` and commit the results.

2020-05-11 19:46 UTC, joestringer commented
test-me-please

2020-05-11 19:47 UTC, joestringer approved these changes

2020-05-12 09:42 UTC, gandro commented
test-me-please

2020-05-12 09:52 UTC, aanm approved these changes

2020-05-12 17:39 UTC, joestringer commented
K8s-1.11-Kernel-netnext CI run hit known flake #11442 .
Runtime-4.9 CI run failed in `sudo make privileged-tests` and I see the same failure in the master pipeline so this PR is not changing anything here. There are no other failures in that test job.

I'm happy to override and mark this as ready-to-merge based upon the above findings.

2020-05-12 18:27 UTC, merged