test: Aid flake debugging
cilium/cilium pull request #11520
Opened 2020-05-13 14:19 UTC by errordeveloper

Just a few simple changes that add some useful output for debugging our flakes when pod waiters fail and Cilium daemonset deletion races (#11497).

2020-05-14 13:49 UTC, errordeveloper commented
test-me-please

2020-05-18 13:42 UTC, nebril requested changes
This will add a lot of verbosity to our test output, but I don't think that's necessarily a bad thing. Several requests for changes inline.

2020-05-18 13:42 UTC, nebril commented on test/helpers/kubectl.go
> +		ginkgoext.By("kubectl describe pods -n %s %s:\n=== STDOUT ===\n%s\n=== STDERR ===\n%s\n===\n",
Unless you are attached to formatting, please consider using `desc.GetDebugMessage`

2020-05-18 13:42 UTC, nebril commented on test/helpers/kubectl.go
> +		ginkgoext.By("kubectl describe pods -n %s %s:\n=== STDOUT ===\n%s\n=== STDERR ===\n%s\n===\n",
same as above

2020-05-18 13:42 UTC, nebril commented on test/helpers/kubectl.go
> +		ginkgoext.By("kubectl describe pods -n %s %s:\n=== STDOUT ===\n%s\n=== STDERR ===\n%s\n===\n",
same as above

2020-05-18 13:42 UTC, nebril commented on test/helpers/kubectl.go
> +	ns := GetCiliumNamespace(GetCurrentIntegration())
As you are changing this, please drop the `ns` var and use `CiliumNamespace` from `cons.go`. (Same package)

2020-05-18 14:08 UTC, errordeveloper commented
> This will add a lot of verbosity to our test output, but I don't think that's necessarily a bad thing. Several requests for changes inline.

Yes, but at the moment there are `kubectl get pods --all-namespaces`  that are not very useful at all. There is very little one can tell from pod statuses alone, and that's only done on test failure. Waiter failures go uncaptured most of the time. From my perspective this just adds a bit to what is already very verbose output, but I hope these additions are actually more useful.
If the implementation used the API directly, I think we could do with much less of guess work when trying to add troubleshooting info.

2020-05-20 17:25 UTC, nebril approved these changes

2020-05-21 14:44 UTC, errordeveloper commented
test-kernel-4.19

2020-05-21 14:45 UTC, errordeveloper commented
test-4.19

2020-05-21 18:06 UTC, errordeveloper commented
In CI this hits #11582.

2020-05-22 12:15 UTC, errordeveloper commented
@nebril do you think we can merge this? I believe it should be very helpful to detect pod readiness flakes! :)

2020-05-22 14:03 UTC, merged