CI: integrate hubble-relay and add initial hubble-relay tests
cilium/cilium pull request #11549
Opened 2020-05-15 13:08 UTC by Rolinh

This PR integrates hubble-relay into the CI and adds basic tests for hubble-relay. 

Ref: #11425

2020-05-15 13:24 UTC, Rolinh commented
test-me-please

2020-05-15 17:13 UTC, michi-covalent approved these changes
amazing test coverage

2020-05-16 09:08 UTC, gandro approved these changes
Not super familiar with the provisioning scripts, but the CI tests themselves look fine.

2020-05-16 09:09 UTC, gandro commented
test-me-please

2020-05-16 20:01 UTC, gandro commented
retest-runtime

2020-05-18 15:05 UTC, nebril requested changes
Good changes! I have one small request - please add 
```
--build-arg CILIUM_SHA=$(firstword $(GIT_VERSION))
```
 to `docker build` call in hubble-relay build step in Makefile and 
```
ARG CILIUM_SHA=""
LABEL cilium-sha=${CILIUM_SHA}
```
in hubble-relay dockerfile for all intermediate images as well as the final images to ensure that these get cleaned in GKE builds.

2020-05-18 15:59 UTC, nebril requested changes

2020-05-18 15:59 UTC, nebril commented on hubble-relay.Dockerfile
> +ARG CILIUM_SHA=""
Please add these also to every intermediate image we are using (every `FROM` Dockerfile command creates a new image), so they need to be added on current lines 2, 8 and 11.

2020-05-19 06:26 UTC, Rolinh commented
test-me-please

2020-05-20 08:05 UTC, Rolinh commented
test-me-please

2020-05-20 13:56 UTC, Rolinh commented
retest-runtime

2020-05-20 13:57 UTC, Rolinh commented
retest-4.9

2020-05-20 13:59 UTC, gandro approved these changes

2020-05-20 14:01 UTC, nebril approved these changes

2020-05-20 15:36 UTC, tklauser commented
Runtime tests failed on known flake #11512 (https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/295/), thus merging.

2020-05-20 15:37 UTC, merged