test: paralellize testNodePort
cilium/cilium pull request #11550
Opened 2020-05-15 14:16 UTC by brb

2020-05-15 14:16 UTC, brb commented
retest-net-next

2020-05-15 14:56 UTC, brb commented
test-focus K8sService*

2020-05-15 16:22 UTC, brb commented
test-focus K8sService*

2020-05-15 17:08 UTC, brb commented
retest-net-next

2020-05-15 20:18 UTC, brb commented
retest-net-next

2020-05-17 07:28 UTC, brb commented
retest-net-next

2020-05-18 05:19 UTC, brb commented
retest-net-next

2020-05-18 08:31 UTC, brb commented
test-me-please

2020-05-18 08:51 UTC, brb commented
retest-gke

2020-05-18 09:07 UTC, brb commented
test-me-please

2020-05-18 09:28 UTC, brb commented
retest-gke

2020-05-18 10:39 UTC, brb commented
retest-4.9

2020-05-18 10:39 UTC, brb commented
retest-4.19

2020-05-18 14:16 UTC, brb commented
test-me-please

2020-05-18 18:33 UTC, brb commented
retest-4.19

2020-05-18 18:33 UTC, brb commented
retest-runtime

2020-05-18 21:39 UTC, pchaigno approved these changes
Can't wait to see the results in our amazing CI dashboard :tada:

2020-05-19 07:33 UTC, brb commented
test-me-please

2020-05-19 10:02 UTC, brb commented
retest-net-next

2020-05-19 12:26 UTC, brb commented
retest-net-next

2020-05-19 13:18 UTC, brb commented
retest-net-next

2020-05-19 16:16 UTC, nebril requested changes
Thanks for this change, couple comments inline, can't wait to merge it!

2020-05-19 16:16 UTC, nebril commented on test/k8sT/Services.go
> +					testCurlRequest(testDSClient, url)
I think you will need to increment `ExpectWithOffset` offset (first argument) in each helper test function called in goroutines so we get better context information about error if assertion fails.

2020-05-19 16:16 UTC, nebril commented on test/k8sT/Services.go
> +				go func(url string) {
Same as above

2020-05-19 16:16 UTC, nebril commented on test/k8sT/Services.go
> +					defer wg.Done()
ditto

2020-05-19 16:16 UTC, nebril commented on test/k8sT/Services.go
> +			cmd := fmt.Sprintf(`/bin/sh -c 'for i in $(seq 1 %d); do %s; done'`, count,
Holy mother of nesting. But I guess there is no way around this (unless we want to also parallelize curl calls?).

2020-05-19 16:16 UTC, nebril commented on test/k8sT/Services.go
> +			Expect(err).Should(BeNil(), "Can not retrieve service")
I think we should use `ExpectWithOffset(1, ...)` here, as we are moving these Expects one level into call stack.

2020-05-19 16:23 UTC, brb commented
retest-net-next

2020-05-19 17:02 UTC, brb commented
retest-4.9

2020-05-19 18:10 UTC, brb commented
retest-4.9

2020-05-19 18:11 UTC, brb commented
retest-4.19

2020-05-19 19:48 UTC, brb commented
retest-net-next

2020-05-20 06:21 UTC, brb commented
retest-net-next

2020-05-20 12:06 UTC, brb commented
retest-net-next

2020-05-20 15:11 UTC, brb commented
retest-4.9

2020-05-20 15:11 UTC, brb commented
retest-4.19

2020-05-20 15:11 UTC, brb commented
test-runtime

2020-05-20 17:09 UTC, brb commented
@nebril Thanks for the review! Considering that all the tests have passed, can we merge this, and then I will address your comments in a follow-up PR?

2020-05-20 17:19 UTC, nebril commented
Let's merge, @brb will make a followup PR with QoL fixes.

2020-05-20 17:20 UTC, merged