cilium: Add CLI to introspect IPIdentityCache
cilium/cilium pull request #11566
Opened 2020-05-16 00:51 UTC by joestringer

The flow of IP <-> Identity mappings into the IPIdentityCache follow the
path of:

1) K8s watch / local poll / generation of the mapping
2) pkg/ipcache:IPIdentityCache
3) pkg/bpf/map userspace cache of map entries being pushed into BPF map
4) Actual BPF map

We can currently introspect some of (1) depending on the source; (3)
always; and (4) depending on the kernel version in use. (2) cannot be
introspected.

This commit adds support for introspecting (2) to assist in
troubleshooting issues related to the propagation of IP to Identity
mappings.

2020-05-19 00:47 UTC, joestringer commented
test-me-please

2020-05-19 00:55 UTC, joestringer commented on bugtool/cmd/configuration.go
> +		"cilium ip list",
nit: We could probably do `cilium ip list --verbose` and/or `cilium ip list -o json` here for more info.

2020-05-19 01:27 UTC, christarazi approved these changes
Nice! LGTM

2020-05-19 03:32 UTC, joestringer commented
test-me-please

2020-05-19 07:29 UTC, tklauser commented
test-me-please

2020-05-19 07:30 UTC, tgraf approved these changes

2020-05-19 07:32 UTC, tklauser approved these changes

2020-05-19 10:26 UTC, tklauser commented
test-me-please

2020-05-19 11:41 UTC, tklauser commented
test-me-please

2020-05-19 12:26 UTC, pchaigno approved these changes

2020-05-19 12:34 UTC, pchaigno requested changes
Actually, aren't the two generated files `Documentation/cmdref/cilium_ip.md` and `Documentation/cmdref/cilium_ip_list.md` missing from this PR?

2020-05-19 14:21 UTC, tklauser commented
test-me-please

2020-05-19 17:21 UTC, joestringer commented
> Actually, aren't the two generated files Documentation/cmdref/cilium_ip.md and Documentation/cmdref/cilium_ip_list.md missing from this PR?

Good catch.

2020-05-19 17:22 UTC, joestringer commented
test-me-please

2020-05-19 17:24 UTC, pchaigno approved these changes

2020-05-19 17:49 UTC, tklauser approved these changes

2020-05-19 17:52 UTC, pchaigno commented
> > Actually, aren't the two generated files Documentation/cmdref/cilium_ip.md and Documentation/cmdref/cilium_ip_list.md missing from this PR?
> 
> Good catch. I fixed this up.

It's kinda of weird that the documentation tests didn't catch this. @errordeveloper Is that expected?

2020-05-19 17:54 UTC, joestringer commented
test-me-please

2020-05-19 17:56 UTC, joestringer commented
> It's kinda of weird that the documentation tests didn't catch this. @errordeveloper Is that expected?

I agree. Note that the build *did* complain about cmdref, but when I responded, I regenerated the cmdref and only added the diff into my commit. This type of failure is easy to miss in local testing since the file is still there, but I'd expect the CI side to pick up that there's a missing file or unclean git or broken links and complain there.

2020-05-19 21:01 UTC, joestringer commented
Nominating for v1.7 backport to aid debugging.

2020-05-20 06:22 UTC, joestringer commented
test-me-please

2020-05-20 07:56 UTC, tklauser commented
Looks like the runtime tests failed because the `verbose` flag is not in the cmdref docs:

```
09:39:21      runtime: diff --git a/Documentation/cmdref/cilium_ip_list.md b/Documentation/cmdref/cilium_ip_list.md
09:39:21      runtime: index 45b1652d7..ab2934016 100644
09:39:21      runtime: --- a/Documentation/cmdref/cilium_ip_list.md
09:39:21      runtime: +++ b/Documentation/cmdref/cilium_ip_list.md
09:39:21      runtime: @@ -17,6 +17,7 @@ cilium ip list [flags]
09:39:21      runtime:  ```
09:39:21      runtime:    -h, --help            help for list
09:39:21      runtime:    -o, --output string   json| jsonpath='{}'
09:39:21      runtime: +  -v, --verbose         Print all fields of ipcache
09:39:21      runtime:  ```
09:39:21      runtime:  
09:39:21      runtime:  ### Options inherited from parent commands
09:39:21      runtime: HINT: to fix this, run 'make -C Documentation update-cmdref ; git commit Documentation/cmdref --message "docs: Update cmdref"'
```

2020-05-20 17:29 UTC, joestringer commented
test-me-please

2020-05-20 18:15 UTC, errordeveloper commented
I've opened an issue #11619 regarding CI checks.

2020-05-20 20:44 UTC, merged