bpf: getpeername hook implementation for socket lb
cilium/cilium pull request #11617
Opened 2020-05-20 15:00 UTC by borkmann

See commit msgs.

2020-05-20 19:53 UTC, brb commented on vagrant_box_defaults.rb
> +$NETNEXT_SERVER_VERSION= "55"
AFAIK we need to bump it from a separate PR which branch has a special name (to populate VM cache).

2020-05-21 09:09 UTC, pchaigno requested changes
Except for Martynas's comment and one missing test case, LGTM!

2020-05-21 09:09 UTC, pchaigno commented on bpf/include/bpf/builtins.h
> +}
This builtin is missing a corresponding test case.

2020-05-22 08:20 UTC, borkmann commented on bpf/include/bpf/builtins.h
> +}
Agree, will add. Thanks for the review!

2020-05-22 14:03 UTC, pchaigno commented
Does commit `bpf: properly reverse xlate svc:port tuple from wildcarded lookups` require a backport?

2020-05-22 14:03 UTC, pchaigno approved these changes
LGTM!

2020-05-22 14:12 UTC, borkmann commented
> Does commit `bpf: properly reverse xlate svc:port tuple from wildcarded lookups` require a backport?

Yeah, I'll take care of it for 1.7.

2020-05-22 16:27 UTC, borkmann commented
test-docs-please

2020-05-22 16:36 UTC, pchaigno commented
> test-docs-please (green)

@borkmann I don't think that's required anymore since the doc tests run in GitHub Action.

2020-05-22 21:04 UTC, borkmann commented
test-me-please

2020-05-22 22:00 UTC, borkmann commented
retest-4.19

2020-05-22 23:15 UTC, borkmann commented
test-me-please

2020-05-22 23:39 UTC, borkmann commented
restest-4.9

2020-05-23 00:21 UTC, borkmann commented
test-me-please

2020-05-23 07:45 UTC, borkmann commented
retest-net-next

2020-05-23 07:45 UTC, borkmann commented
retest-runtime

2020-05-23 10:22 UTC, borkmann commented
retest-net-next

2020-05-23 11:05 UTC, borkmann commented
vbox error:
```
10:59:40  Progress state: VBOX_E_OBJECT_IN_USE
10:59:40  VBoxManage: error: Machine delete failed
10:59:40  VBoxManage: error: Cannot close medium '/root/VirtualBox VMs/ubuntu-18.04.4-amd64-55_1590229760245_39345/ubuntu-18.04.4-amd64-55-disk001.vmdk' because it has 2 child media
10:59:40  VBoxManage: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component MediumWrap, interface IMedium
10:59:40  VBoxManage: error: Context: "RTEXITCODE handleUnregisterVM(HandlerArg*)" at line 162 of file VBoxManageMisc.cpp
10:59:40  VBoxManage: error: Machine 'dc5268d5-da68-4fc4-9b13-921a35692493' is not currently running
10:59:40  0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
10:59:40  VBoxManage: error: Machine '3c6abf7b-0259-4188-973c-e78ed91e0dac' is not currently running
10:59:42  0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
```

2020-05-23 11:05 UTC, borkmann commented
retest-net-next

2020-05-23 12:25 UTC, borkmann commented
retest-net-next

2020-05-23 14:39 UTC, borkmann commented
retest-net-next

2020-05-23 18:12 UTC, merged