build: Show privileged test output
cilium/cilium pull request #11644
Opened 2020-05-21 19:22 UTC by jrajahalme

Show privileged test output in hopes this helps figuring out why they fail.

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

2020-05-21 19:23 UTC, jrajahalme commented
retest runtime

2020-05-21 19:24 UTC, jrajahalme commented
retest-runtime

2020-05-21 19:28 UTC, michi-covalent approved these changes

2020-05-21 19:42 UTC, joestringer approved these changes

2020-05-21 20:45 UTC, pchaigno commented
The test failed but the more verbose output doesn't seem to have any more indication as to what failed exactly :/

2020-05-21 21:18 UTC, christarazi commented
Did this test run include https://github.com/cilium/cilium/pull/11620?

2020-05-21 22:17 UTC, jrajahalme commented
retest-runtime

2020-05-21 23:14 UTC, jrajahalme commented
@christarazi Yes, but unfortunately this does not give any better results, I thought `exit 1` might be hiding something, but alas, no. Still failing every time, now right after completing `github.com/cilium/cilium/pkg/datapath/linux/ipsec`, but before there is any output from the next iteration (`github.com/cilium/cilium/pkg/datapath/linux/probes`).

I tried running this locally by spinning up the `runtime` VM at `test` via `vagrant up runtime --provision` and then running `ginkgo --focus="Runtime.*ivileged.*" -v -- -cilium.provision=false` but locally it succeeds. Same result if I `ssh runtime` and `sudo make -C /home/vagrant/go/src/github.com/cilium/cilium/ tests-privileged`, success.

2020-05-21 23:18 UTC, jrajahalme commented
retest-runtime (added more printing...)

2020-05-21 23:19 UTC, jrajahalme commented
retest-runtime

2020-05-21 23:21 UTC, jrajahalme commented
retest-runtime

2020-05-22 00:56 UTC, jrajahalme commented
Now it fails on go test for `github.com/cilium/cilium/pkg/datapath/linux/ipsec` (I added some echoes to see bit more what is happening):
```
[2020-05-22T00:52:54.971Z]   	 Starting test in github.com/cilium/cilium/pkg/datapath/linux/ipsec...
```

2020-05-22 14:55 UTC, pchaigno commented
It looks like the only way to reproduce is to run `retest-runtime`. [`test-focus` doesn't seem to have the same flake](https://github.com/cilium/cilium/pull/11636#issuecomment-632615323). Local testing doesn't either (I tried running the whole `Runtime*` test suite 6 times locally, all succeeding).

@nebril Is there anything specific about the `Runtime-4.9` VM that we may have missed?

2020-05-22 17:39 UTC, jrajahalme commented
retest-runtime

2020-05-22 17:39 UTC, jrajahalme commented
@pchaigno Trying again with `ginkgo -seed=1590090144` which runs the privileged tests within minutes from starting and failed in the past.

2020-05-25 11:09 UTC, aanm requested changes

2020-05-25 11:09 UTC, aanm commented on jenkinsfiles/ginkgo-runtime-kernel.Jenkinsfile
> +                sh 'cd ${TESTDIR}; ginkgo -seed=1590090144 --focus="$(python get-gh-comment-info.py "${ghprbCommentBody}" | sed "s/^$/Runtime.*/" | sed "s/K8s.*/NoTests/")" -v --failFast=true -- -cil
I assume this is unintended?

2020-05-25 20:23 UTC, pchaigno commented
This can probably be closed now that #11677 is merged.

2020-06-08 19:07 UTC, closed without merging