Fix various data races in pkg/aws/eni and pkg/ipam
cilium/cilium pull request #11685
Opened 2020-05-26 07:10 UTC by christarazi

This PR also contains a potential fix for the flakiness seen in
https://github.com/cilium/cilium/issues/11560. The commit for the fix adds a
setup and cleanup method for a metrics mock implementation used in the
ENISuite.

See commit msgs.

Related https://github.com/cilium/cilium/issues/11560
Related https://github.com/cilium/cilium/issues/10677

2020-05-26 07:11 UTC, christarazi commented
test-me-please

2020-05-26 16:44 UTC, christarazi commented
retest-4.9

2020-05-26 16:45 UTC, christarazi commented
retest-4.19

2020-05-26 21:37 UTC, christarazi commented
Travis has passed thrice so far...

2020-05-27 13:19 UTC, aanm requested changes

2020-05-27 13:19 UTC, aanm commented on pkg/aws/eni/node.go
>  func (n *Node) findNextIndex(index int64) int64 {
It's odd seeing a private method getting a mutext. Please add a comment in the function stating `n.mutex` must NOT be held.

2020-05-27 13:19 UTC, aanm commented on pkg/aws/eni/instances.go
> +	m.mutex.RUnlock()
please use a defer
```
	m.mutex.RLock()
        defer m.mutex.RUnlock()
	m.instances.ForeachInterface(instanceID, fn)
```

2020-05-27 13:20 UTC, aanm commented
@christarazi my requested changes won't require the CI to re-run again. Ping me once they are addressed so we can merge the PR without running the CI.

2020-05-27 16:34 UTC, christarazi commented
@aanm Made the requested modifications.

2020-05-27 17:06 UTC, aanm approved these changes

2020-05-27 17:07 UTC, merged