test: Wrap helm inside Eventually clauses
cilium/cilium pull request #11762
Opened 2020-05-28 20:31 UTC by christarazi

This commit is an attempt to add retry logic to Helm operations in the
Kubernetes test suite. This should help reduce flakes in the case of network
errors such as timeouts.

2020-05-28 20:31 UTC, christarazi commented
test-me-please

2020-05-28 22:14 UTC, christarazi commented
This change affects K8s CI tests and they have passed

2020-05-28 22:18 UTC, christarazi commented
test-me-please

2020-05-28 22:50 UTC, christarazi commented
test-me-please

2020-05-29 05:12 UTC, christarazi commented
retest-runtime

2020-05-29 10:38 UTC, pchaigno requested changes
I couldn't find if Helm has a retry mechanism builtin, so :+1: on first commit. `docker pull` does retry on connection breakages though (tried locally by blocking outgoing connection for a couple minutes). I don't think the second commit is worth it; it's just likely to take more time whenever the connection is persistently down.

2020-06-01 05:01 UTC, christarazi commented
test-me-please

2020-06-01 05:31 UTC, christarazi commented
retest-net-next

2020-06-01 09:19 UTC, errordeveloper commented
Just for the record, can we clarify - is this most of the time due to chart repo availability? I've seen  500s occasionally.

2020-06-01 15:45 UTC, christarazi commented
retest-net-next

2020-06-01 15:47 UTC, christarazi commented
> Just for the record, can we clarify - is this most of the time due to chart repo availability? I've seen 500s occasionally.

I have not personally seen these failures, but I was asked to help with this. If you have seen them and they manifest themselves as 500s, I'd be happy to clarify the PR or the commit.

2020-06-01 15:59 UTC, christarazi commented
retest-4.19

2020-06-01 16:11 UTC, errordeveloper commented
@christarazi I've not seen issues in CI context actually, I just recall seeing occasional 500s when running `helm repo add`, and I know that GitHub pages can be a little unreliable at times.

2020-06-01 16:54 UTC, b3a-dev commented
@errordeveloper , @christarazi an example of this in CI context: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-k8s1.11-Pipeline/453/testReport/junit/Suite-k8s-1/11/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/

`Stderr:
 	 Error: looks like "https://helm.cilium.io" is not a valid chart repository or cannot be reached: Get https://helm.cilium.io/index.yaml: dial tcp: lookup helm.cilium.io on 147.75.207.208:53: read udp 147.75.69.147:52976->147.75.207.208:53: i/o timeout
`

2020-06-01 17:08 UTC, errordeveloper commented
@b3a-dev that is a DNS issue actually, if that is what is we are seeing, there is bigger fish to fry (which is not really news to me)...

2020-06-01 17:19 UTC, pchaigno commented
> @b3a-dev that is a DNS issue actually, if that is what is we are seeing, there is bigger fish to fry (which is not really news to me)...

@errordeveloper Could you elaborate? That looks like a connectivity blip with the DNS lookup first hitting it. The retry doesn't seem like such a bad idea to handle that case.

2020-06-01 17:30 UTC, errordeveloper commented
> @errordeveloper Could you elaborate? That looks like a connectivity blip with the DNS lookup first hitting it. The retry doesn't seem like such a bad idea to handle that case.

For sure, retrying is a good fix in any case! I just mean that we should also stop using unriliable DNS providers, we should use either 1.1.1.1 or Google DNS.

2020-06-01 17:44 UTC, pchaigno commented
> I just mean that we should also stop using unriliable DNS providers, we should use either 1.1.1.1 or Google DNS.

Yeah, sure. I don't know what we currently use in VMs and on the hosts, but if it's something flaky, let's switch!

2020-06-01 17:45 UTC, christarazi commented
I believe we use 8.8.8.8 (Google DNS)

2020-06-01 17:47 UTC, christarazi commented
Also, CI has flaked many times on the Policy tests, and the failures are unrelated to this PR. So this is ready to merge, pending if we'd want to reword the commit or etc.

2020-06-01 17:48 UTC, pchaigno approved these changes

2020-06-02 09:14 UTC, nebril approved these changes
LGTM, thanks!

2020-06-02 09:15 UTC, merged

2020-06-08 21:22 UTC, christarazi commented
Failure in v1.7 backports due to this issue this PR fixes: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/19728/testReport/junit/Suite-k8s-1/17/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/

https://github.com/cilium/cilium/pull/11906

Marking as backport to v1.7