pkg/k8s: decrease CEP status initialization
cilium/cilium pull request #11829
Opened 2020-06-02 16:13 UTC by aanm

When an endpoint is created, its status is only created 10 seconds
after. This happens because Kubernetes ignores the status field of a CRD
object on its initialization and Cilium has a controller running every
10 seconds.

In order to have a shorter CEP update window, Cilium can create the
status field immediately after the creation of the CEP without waiting
for the next execution of the CEP controller to be executed.

Signed-off-by: André Martins <andre@cilium.io>

Fixes https://github.com/cilium/cilium/issues/11751

2020-06-02 16:15 UTC, aanm commented
test-me-please

2020-06-02 16:53 UTC, nebril approved these changes

2020-06-02 17:26 UTC, brb requested changes
Can you revert https://github.com/cilium/cilium/pull/11771 as the part of this PR, and see whether we don't hit the flake anymore?

2020-06-02 18:22 UTC, aanm commented
test-focus K8sServicesTest.*

2020-06-02 18:22 UTC, aanm commented
test-me-please

2020-06-03 07:16 UTC, brb commented
test-focus K8sServicesTest.*

2020-06-03 07:22 UTC, brb approved these changes

2020-06-03 07:45 UTC, tgraf approved these changes

2020-06-03 09:43 UTC, aanm commented
hit #8945

2020-06-03 09:43 UTC, aanm commented
test-focus K8sServicesTest.*

2020-06-03 13:23 UTC, aanm commented
test-focus K8sServicesTest.*

2020-06-03 14:37 UTC, aanm commented
test-focus K8sServicesTest.*

2020-06-03 17:43 UTC, aanm commented
retest-net-next

2020-06-04 07:30 UTC, aanm commented
retest-net-next

2020-06-04 09:39 UTC, merged