helm: updated default values.yml to advise about config.ipam=eni
cilium/cilium pull request #11859
Opened 2020-06-03 12:32 UTC by mvisonneau

Following the upgrade from `1.7.4` to `1.8.0-rc1`, I experienced a small issue regarding the existing IPAM configuration:

<img width="715" alt="image" src="https://user-images.githubusercontent.com/1761583/83636753-c797f400-a5a6-11ea-9516-e81014a76496.png">

We now have to set : `config.ipam: eni` in order to keep an existing/working configuration in place. I added a few indications in the default values of the chart to make it more obvious.

2020-06-03 16:59 UTC, aanm requested changes
I'm not sure if this is the right fix. I've opened https://github.com/cilium/cilium/issues/11868 to understand what the issue is.

2020-06-03 17:00 UTC, mvisonneau commented
sounds good thanks @aanm! 👍

2020-06-04 09:20 UTC, mvisonneau commented
closing in favour of #11868

2020-06-04 09:20 UTC, closed without merging

2020-06-04 13:06 UTC, tgraf commented
Fix will be in this PR:
https://github.com/cilium/cilium/pull/11892