option: Do not permit setting kvstore type in CRD allocation mode
cilium/cilium pull request #11857
Opened 2020-06-03 11:54 UTC by mrostecki

CRD allocation mode should mean that kvstore is not used. Before this
change, user could set identity-allocation-mode=crd and kvstore options,
which resulted in trigerring the deamon to initialize a kvstore while
using CRD as the store, which resulted in a deadlock (#11690).

Fixes: 8822c1d650f0 ("k8s: Add CRD Identities as an identity allocator backend")
Fixes: #11820
Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>

2020-06-03 11:54 UTC, mrostecki commented
test-me-please

2020-06-03 13:40 UTC, mrostecki commented
test-me-please

2020-06-04 04:19 UTC, joestringer requested changes
Couple of minor nits in the testsuite side.

I raised some question in the main logic but it LGTM.

2020-06-04 04:19 UTC, joestringer commented on pkg/option/config.go
> +	c.DisableCiliumEndpointCRD = viper.GetBool(DisableCiliumEndpointCRDName)
How does CiliumEndpoint CRD relate to identities? ciliumidentities sure, but ciliumendpoint I'm not sure.

2020-06-04 04:19 UTC, joestringer commented on pkg/option/config_test.go
> +			name: "crd mode provided, endpoint crd enabled, should enable endpoint crd",
nit:

```suggestion
			name: "crd mode provided, endpoint crd disabled, should enable endpoint crd",
```

2020-06-04 04:19 UTC, joestringer commented on pkg/option/config_test.go
> +			},
Hmm, I kinda wonder if someone explicitly passes kvstore mode but fails to properly configure it whether it should actually error out..?

2020-06-04 04:19 UTC, joestringer commented on pkg/option/config.go
> +		}
@aanm do you know if this is still true? We have ciliumidentities CRD now, is this left over or we still have a dependency on ciliumendpoint CRD as well?

2020-06-11 16:29 UTC, mrostecki commented
I'm closing this PR, since my assumption about kvstore and CRD being mutually exclusive was wrong. Sorry!

2020-06-11 16:29 UTC, closed without merging