1.8 Documentation updates
cilium/cilium pull request #11892
Opened 2020-06-04 13:05 UTC by tgraf

2020-06-04 15:43 UTC, joestringer requested changes
LGTM, one minor comment below.

Would be nice to get a second view from someone like @seanmwinn  / @jedsalazar .

2020-06-04 15:43 UTC, joestringer commented on Documentation/concepts/networking.rst
> +  option ``egress-masquerade-interfaces: eth+`` can be used.
maybe worth noting here what the `eth+` actually means, and that the user should specify a prefix pattern that matches the devices they care about.

I don't know if many modern Linux distributions still name devices as `ethN` by default these days.

2020-06-04 15:43 UTC, joestringer commented on Documentation/concepts/networking.rst
> +  option ``egress-masquerade-interfaces: eth+`` can be used.
(I'm also not sure if we're respecting this option for bpf masquerade /cc @brb )

2020-06-04 15:54 UTC, jedsalazar commented on Documentation/concepts/networking.rst
> +As the IPv4 addresses used for pods are typically allocated from RFC1918
I think it reads cleaner if we remove the condition in the beginning of the statement 
s/As the//

2020-06-04 16:07 UTC, jedsalazar commented on Documentation/concepts/networking.rst
> +  option ``egress-masquerade-interfaces: eth+`` can be used.
systemd-based distros have eliminated the eth naming scheme and replaced it with the systemd.net-naming-scheme (`enN`-based naming). that's not very intuitive so agreed that we note what `eth+` references

2020-06-04 16:24 UTC, christarazi reviewed
LGTM, when I looked at https://github.com/cilium/cilium/issues/11868 yesterday, I noticed that we have two of the same Helm deploy instructions for AWS / EKS / ENI. See [EKS guide](https://docs.cilium.io/en/latest/gettingstarted/k8s-install-eks/?highlight=config.ipam#deploy-cilium) and [ENI guide](https://docs.cilium.io/en/latest/gettingstarted/aws-eni/#deploy-cilium). It'd be nice if we can consolidate these two Helm instruction sections into one, by putting the shared info into a separate file and referencing it in the two sections. This would help avoid an inconsistency cropping up like the above issue.

2020-06-04 16:35 UTC, brb commented on Documentation/concepts/networking.rst
> +  The eBPF-based implementation is the most efficient
Once this PR is emerged, I will extend this section to add more info about device selection.

2020-06-05 09:18 UTC, tklauser commented on Documentation/install/upgrade.rst
> +    and set it to the CIDR for which masquerading should be omitted for. This is
Nit:
```suggestion
    and set it to the CIDR for which masquerading should be omitted. This is
```

2020-06-05 16:05 UTC, merged