Properly cancel endpoint creations as they become obsolete
cilium/cilium pull request #11920
Opened 2020-06-05 11:29 UTC by tgraf

So far, the endpoint create request has relied on timing out eventually
and checking liveness of the endpoint in various spots to then abort the
creation.

This has the disadvantage that if a blocking operation such as etcd
interactions are delayed for a long time, kubelet may schedule a new pod
creation attempt while the old endpoint is still being created, leading
to parallel endpoint create events for the same pod.

Establish a new map which keeps track of all endpoint create requests
and:
* Cancel any endpoint create request if an endpoint delete request for
the same endpoint is being received.
* Cancel any endpoint create request if a new endpoint create request
for the same pod is being received. The new request will continue.

In order to assist in troubleshooting of create endpoint related issues,
the list of ongoing endpoint creations is printed in the debuginfo
output.

2020-06-05 11:35 UTC, tgraf commented
test-me-please

2020-06-05 12:01 UTC, aanm requested changes

2020-06-05 12:01 UTC, aanm commented on daemon/cmd/endpoint.go
> +	log.WithField("id", id).Info("Delete endpoint request")
We have https://github.com/cilium/cilium/blob/05163ed608e54b2ca095cfa0ef849f57d8a94f91/pkg/endpoint/endpoint.go#L1074

2020-06-05 12:01 UTC, aanm commented on daemon/cmd/endpoint.go
> +	}).Info("Create endpoint request")
This is a lot of verbosity IMO. We already have https://github.com/cilium/cilium/blob/05163ed608e54b2ca095cfa0ef849f57d8a94f91/pkg/endpoint/manager.go#L67 https://github.com/cilium/cilium/blob/3123abd45a709a73c406bd342e625a939e9d4d46/pkg/endpoint/bpf.go#L658 and https://github.com/cilium/cilium/blob/89654fd6400e77b97eac4738f42cad662a1f10b1/daemon/cmd/endpoint.go#L396

2020-06-05 12:01 UTC, aanm commented on daemon/cmd/endpoint.go
> +	// create
description doesn't match field

2020-06-05 12:01 UTC, aanm commented on daemon/cmd/endpoint.go
> +	}
Please add comment to why this only matters in k8s.

2020-06-05 15:44 UTC, tgraf commented on daemon/cmd/endpoint.go
> +	log.WithField("id", id).Info("Delete endpoint request")
That's at the very end and only printed when deletion has been successful. The new log message gives visibility into every CNI DEL.

2020-06-05 15:45 UTC, tgraf commented on daemon/cmd/endpoint.go
> +	}).Info("Create endpoint request")
It was clearly not enough to debug this issue. Most of them are also after several potentially blocking operations which means there is no visibility when a new add has occurred.

2020-06-05 17:03 UTC, christarazi approved these changes
:tada:

2020-06-05 17:30 UTC, tgraf commented
test-me-please

2020-06-05 19:08 UTC, joestringer requested changes
One comment below, basically goes to the heart of an assumption made here which if fine is all good (though might be nice to warn on unexpected condition), if not fine then we need to adjust the keying of this map.

The assumption being that a pod must have a unique "namespace/name".

2020-06-05 19:08 UTC, joestringer commented on daemon/cmd/endpoint.go
> +		if req.endpoint == ep {
In the "else" case of this condition, what do we expect? Is that a bug? Should we warn? That'd basically be a duplicate pod namespace+name currently being created which the rest of this PR seems to assume is not possible AFAICT.

2020-06-06 01:44 UTC, joestringer commented on daemon/cmd/endpoint.go
> +		if req.endpoint == ep {
Names have to be unique, can disregard: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/

2020-06-06 01:44 UTC, joestringer approved these changes

2020-06-07 07:06 UTC, merged