cni: Only require ipam.Cidrs when masquerade is enabled
cilium/cilium pull request #11978
Opened 2020-06-09 09:53 UTC by bpineau

Since recently, allocations results returned without CIDRs became fatal
for CNI (CNI cmdAdd() would fail due to interfaceAdd() failing, due to
RoutingInfo.parse() bailing out on `len(cidrs) == 0`).

That (now mandatory) `IPv4CIDRs` is used when masquerading is enabled,
to source-route traffic from the pods to its attached VPC CIDRs through
a dedicated local table (that I assume is exempt from masquerade).

But on Azure we don't collect and dont't propagate subnets CIDRs, and
that bit of information is missing from ciliumnodes azure crd/ipam.

Adding masquerade support to Azure CNI (therefore, collecting and bubbling
down per-address CIDRs) would be a nice feature to have in the longer term.
But we might be late in the feature freeze to implement that on time to
unbreak Azure CNI before 1.8 release; and there's no reason to insist on
having CIDRs when masquerade is disabled anyway.

Please ensure your pull request adheres to the following guidelines:

```release-note
Don't require (not supported on Azure) ipam.Cidrs when masquerade is disabled
```

2020-06-09 16:44 UTC, christarazi requested changes
Changes look good, just a small comment. 

If I understand you correctly, this is a temporary Azure fix until we support masquerading on Azure? If that's the case, happy to merge this in as a 1.8 backport.

2020-06-09 16:44 UTC, christarazi commented on pkg/datapath/linux/routing/info_test.go
> +		rInfo, err := NewRoutingInfo(tt.gateway, tt.cidrs, tt.macAddr, true)
Could you add test cases for `masquerade` as it's now an extra variable?

2020-06-09 16:45 UTC, christarazi commented on pkg/datapath/linux/routing/info.go
> +func NewRoutingInfo(gateway string, cidrs []string, mac string, masquerade bool) (*RoutingInfo, error) {
Could you also update the comment of this function to state the intent of `masquerade` and why it's not part of the struct like all the other parameters?

2020-06-10 07:42 UTC, bpineau commented
@christarazi thanks for the review, PR updated.

You understood correctly. I don't know if anyone is actively working on masquerade support for Azure at the moment (I'd like to give a stab at it, but can't promise).

Yes it would be great to backport to 1.8, so Azure CNI would work when released (albeit not supporting all features AWS does).

2020-06-10 15:56 UTC, nebril approved these changes

2020-06-11 05:32 UTC, christarazi approved these changes
Looks great, thanks for the PR!

2020-06-11 05:32 UTC, christarazi commented
test-me-please

2020-06-11 15:09 UTC, aanm commented
test-me-please

2020-06-15 09:31 UTC, merged