docs: clarify janitor duty for backport PRs
cilium/cilium pull request #11988
Opened 2020-06-09 14:37 UTC by aanm

Signed-off-by: André Martins <andre@cilium.io>

2020-06-09 14:41 UTC, pchaigno approved these changes

2020-06-10 20:47 UTC, joestringer requested changes

2020-06-10 20:47 UTC, joestringer commented on Documentation/contributing/development/contributing_guide.rst
> +   PRs that were upstreamed from an external contributor.
Please use the imperative form, this brings more clarity to exactly what is expected.

Possible alternative text:

```suggestion
   If this PR is a backport PR (e.g. with the label ``kind/backport``) and
   no-one else has reviewed the PR, review the changes as a sanity check.
   If any individual commits deviate from the original patch, request review from
   the original author to validate that the backport was correctly applied.
```

(I didn't include the bit about external contributors but the backports review is more about a sanity check than actual involved review because we should have caught most things already when the original PR was introduced).

2020-06-11 15:21 UTC, joestringer approved these changes

2020-06-11 19:11 UTC, merged