grafana: Add Hubble dashboard
cilium/cilium pull request #12004
Opened 2020-06-10 13:43 UTC by gandro

This adds the Grafana dashboard for Hubble to our Grafana example chart.
Because `kubectl apply` has a limitation of 256KB per ConfigMap, the
chart is modified to create one ConfigMap per dashboard.

The "Running Prometheus & Grafana" getting started guide is updated
with information on how to enable metrics for Hubble and Cilium Operator.

In addition, the images from the Hubble metrics documentation are
copied over into the "Examples" section.

2020-06-10 16:40 UTC, nebril approved these changes

2020-06-11 13:44 UTC, aanm requested changes
needs docs changes to inform users that `__meta_kubernetes_service_annotation_prometheus_io_scrape` needs to be set in prometheus. Can be addressed as a follow up if you prefer

2020-06-11 13:44 UTC, aanm commented on examples/kubernetes/addons/prometheus/files/grafana-dashboards/hubble-dashboard.json
> +  "refresh": "5s",
30s instead of 5s

2020-06-11 14:21 UTC, rolinh approved these changes

2020-06-11 15:17 UTC, gandro commented
> needs docs changes to inform users that `__meta_kubernetes_service_annotation_prometheus_io_scrape` needs to be set in prometheus. Can be addressed as a follow up if you prefer

I have added it to this PR. Plus some other minor cosmetic fixes (such as making the links clickable).

2020-06-11 15:19 UTC, gandro commented
test-me-please

2020-06-11 17:38 UTC, gandro commented
retest-4.19

2020-06-11 17:40 UTC, michi-covalent commented
for my own reference, the updated metrics page: https://deploy-preview-12004--cilium-docs.netlify.app/configuration/metrics.html

2020-06-11 17:44 UTC, michi-covalent approved these changes
@gandro thank you for taking care of this!

2020-06-11 19:14 UTC, gandro commented
retest-4.19

2020-06-12 08:05 UTC, aanm approved these changes

2020-06-12 08:05 UTC, merged