Fix setting monitorAggregationLevel to max reflects via CLI
cilium/cilium pull request #12014
Opened 2020-06-10 20:18 UTC by soumynathan

This PR fixes setting MonitorAggregationLevel to max to correctly
reflect through CLI.

Fixes: #12000
Signed-off-by: Swaminathan Vasudevan <svasudevan@suse.com>

2020-06-11 14:56 UTC, aanm requested changes

2020-06-11 14:56 UTC, aanm commented on pkg/option/monitor.go
> +	MonitorAggregationLevelMax = 4
`MonitorAggregationLevelMax OptionSetting = 4`

2020-06-11 17:41 UTC, soumynathan commented on pkg/option/monitor.go
> +	MonitorAggregationLevelMax = 4
Done.

2020-06-12 09:28 UTC, aanm approved these changes

2020-06-12 09:32 UTC, tklauser approved these changes
Unrelated to this PR: I think we could simplify the definition of the `MonitorAggregationLevel*` consts a bit by using `iota`.

2020-06-12 09:34 UTC, tklauser commented
Marking as `needs-backport/1.7` since this was reported against 1.7.4 in #12000

2020-06-12 09:35 UTC, tklauser commented
test-me-please

2020-06-12 09:37 UTC, aanm requested changes
I gave it a little mor thought on this PR, I'm not sure if setting the maximum aggregation level to 4 is the correct approach here since we only support at maximum 3, not 4 levels of aggregation. cc @joestringer are there any implications in regarding the datapath implementation i.e., user setting it to 4 while the datapath only supports 3 aggregation levels?

2020-06-12 17:08 UTC, christarazi commented
I think the core of the issue here is that previously the `format` function for MonitorAggregationLevel didn't have a field for `max`. @soumynathan correctly fixes this. IMO, I don't think it matters whether we create a new level (in this case it is a `4`) to fix this bug, of course assuming no datapath implications. Only the formatting is affected as it seems to be a cosmetic bug, *I believe*.

Now what we are dealing with is whether we want to allow the user to specify `max` and if we should spit a warning msg to inform them that max aggregation hasn't been implemented (or similar). When I briefly synced with @joestringer on this, currently `max` is just a placeholder until we actually implement it.

2020-06-12 18:06 UTC, joestringer commented
There's clearly a bit of confusion around what these settings are and what they mean, and that's partly on me for not documenting; Furthermore I fully anticipate that 99% of users will use whatever is the default so I haven't seen it as a tweak that's worth documenting fully at this point.

Here's the code:

https://github.com/cilium/cilium/blob/a8066cec55fca1a898db1a8d5062af6e0ce12e36/bpf/lib/trace.h#L46-L51

"NONE" on the datapath maps to the none on the daemon, that means send all datapath notifications for receive/transmit packets.
"AGGREGATE_RX" is equivalent to "low" in the daemon. That means stop sending datapath notifications for received packets. All transmitted packets should still cause a notification to be sent.
"ACTIVE_CT" (note ==`3`) adds connection aggregation which by default limits trigger notifications to once per 5 seconds per connection (unless there's new information like new TCP flags). All dropped packets still trigger notifications.

If someone is particularly careful about the semantics they need from the notifications mechanism, they can lock the value to one of the specific levels to get those semantics.

There is no "maximum" in the datapath, maximum in the daemon is a concept that says "I don't care, give me whatever notifications that the Cilium maintainers think is a reasonable level of filtering". This is part of why there's this "UI bug" right now, because "maximum" isn't a distinct value or setting with its own semantics. Its semantics *will change* if we introduce additional levels of aggregation (such as sending fewer notifications for dropped packets).

> are there any implications in regarding the datapath implementation[...]?

No, the datapath checks against ">=" specific values of aggregation:

https://github.com/cilium/cilium/blob/a8066cec55fca1a898db1a8d5062af6e0ce12e36/bpf/lib/trace.h#L121-L140

In summary, setting to 4 should have no behaviour difference and will retain the semantics we expect. We may need to bump it again in future when adding additional levels, but we can address that if/when we come to that.

2020-06-12 19:22 UTC, joestringer approved these changes

2020-06-12 19:25 UTC, joestringer commented
I don't really consider this worth backporting since it's been there since Cilium v1.2 and it took until v1.8 (1.5 years+) for anyone to notice.

2020-06-12 19:28 UTC, merged