Implement per-provider operator deployments in Helm
cilium/cilium pull request #12029
Opened 2020-06-11 18:11 UTC by joestringer

Update the helm charts for for generic, aws and azure operator images.

Fixes: #11800

This is a simplification of the minimal required changes from #11837  for the v1.8.0 release.

2020-06-11 18:11 UTC, joestringer commented
test-focus K8sUpdates

2020-06-11 18:20 UTC, joestringer commented
test-focus K8sUpdates

2020-06-11 18:37 UTC, aanm approved these changes

2020-06-11 18:39 UTC, joestringer commented
test-me-please

2020-06-11 19:35 UTC, tgraf approved these changes

2020-06-11 19:57 UTC, tgraf requested changes
The following needs to be changed as well:
```
docker tag "cilium/cilium:$2" "$1/cilium/cilium:$2"
docker tag "cilium/cilium:$2" "$1/cilium/cilium-dev:$2"
docker tag "cilium/operator:$2" "$1/cilium/operator:$2"
docker tag "cilium/hubble-relay:$2" "$1/cilium/hubble-relay:$2"
```

2020-06-11 20:27 UTC, tgraf commented
test-focus K8sUpdates

2020-06-11 21:55 UTC, tgraf commented
test-focus K8sUpdates

2020-06-11 21:58 UTC, joestringer commented on Makefile.docker
> +	$(MAKE) docker-operator-generic-image-unstripped
:) would've expected these to be largely equivalent. "If you didn't know, now you know"

:+1:

2020-06-11 23:23 UTC, joestringer commented
Focus passed :tada:

2020-06-11 23:23 UTC, joestringer commented
test-me-please

2020-06-11 23:36 UTC, tgraf commented
This PR currently uses the brute-force method to resolve this. We should avoid building all operator images in the CI in a follow-up PR.

2020-06-11 23:36 UTC, tgraf approved these changes

2020-06-12 01:08 UTC, joestringer commented
Hit known flake https://github.com/cilium/cilium/issues/10929

2020-06-12 02:23 UTC, joestringer commented
The rest is green, merging.

2020-06-12 02:23 UTC, merged