helm: Clean up the hubble-relay DNS name in the UI chart
cilium/cilium pull request #12033
Opened 2020-06-11 23:53 UTC by michi-covalent

Specifying the service name by itself as the DNS is sufficient since
hubble-relay and hubble-ui get deployed to the same namespace.

Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

2020-06-12 08:23 UTC, rolinh approved these changes

2020-06-12 17:11 UTC, christarazi approved these changes
:ship:

2020-06-15 09:08 UTC, gandro commented
test-me-please

2020-06-15 09:09 UTC, gandro approved these changes

2020-06-15 09:10 UTC, gandro requested changes
I approved a bit too early, can you also remove the corresponding value, since it is now unused?

https://github.com/cilium/cilium/blob/a1ccadba8cc64e76329d5ea35759f85800c044b5/install/kubernetes/cilium/charts/hubble-ui/values.yaml#L11

2020-06-15 12:43 UTC, nebril reviewed
Same comment as Sebastian, LGTM otherwise.

2020-06-17 11:43 UTC, aanm reviewed
If we are going to backport this to 1.8 then it does not need to wait for the 1.8.0 release.

2020-06-17 11:44 UTC, aanm commented
test-me-please

2020-06-17 14:33 UTC, gandro approved these changes

2020-06-18 10:18 UTC, merged