daemon: added KeepConfig option
cilium/cilium pull request #121
Opened 2016-09-14 17:25 UTC by aanm

KeepConfig allows users to specify if they want to keep the container
configuration or not when the daemon is set to restore state. The option
is set by default. If user sepcify unsets it, the daemon configuration
will be used instead.

Fixes #48 

Signed-off-by: André Martins <andre@cilium.io>

2016-09-14 17:26 UTC, aanm commented on common/types/option.go
> +	o.Set(key, parent.IsEnabled(key))
@tgraf special attention to here

2016-09-14 17:28 UTC, aanm commented on common/types/option.go
> -				delete(o.Opts, k)
@tgraf special attention to here as well

2016-09-15 07:40 UTC, tgraf commented on common/types/option.go
> +	o.Set(key, parent.IsEnabled(key))
We can get rid of `InheritDefault` alltogether and just call `Set()` in `SetDefaultOpts()`

2016-09-15 07:42 UTC, tgraf commented on common/types/option.go
> -				delete(o.Opts, k)
ACK, maybe just do `o.Opts[k] = false` to make it even clearer.

2016-09-15 07:43 UTC, tgraf commented on daemon/daemon/daemon_config.go
> +	KeepConfig   bool // When RestoreState is set, it keeps endpoints' configuration.
Reword this comment to something like "Keep configuration of existing endpoints when starting up"

2016-09-15 07:44 UTC, tgraf commented on daemon/main.go
> +						Usage:       "When restoring state, keeps containers' configuration in place",
Same here, make it easier to understand. "Restoring state" is an internal term.

2016-09-15 07:44 UTC, tgraf requested changes

2016-09-15 14:03 UTC, aanm commented on daemon/main.go
> +						Usage:       "When restoring state, keeps containers' configuration in place",
No, restoring state is a public term. It's set by default

```

					cli.BoolTFlag{
						Destination: &config.RestoreState,
						Name:        "restore-state",
						Usage:       "Restore state from previous daemon",
					},
```

2016-09-15 18:38 UTC, tgraf commented on daemon/main.go
> +						Usage:       "When restoring state, keeps containers' configuration in place",
I think state is  misleading wording for this in general. We should rename that option as well and simply call it `--restore`.

2016-09-15 22:59 UTC, aanm commented on daemon/main.go
> +						Usage:       "When restoring state, keeps containers' configuration in place",
Change it to `--restore`. All good?

2016-09-16 07:25 UTC, tgraf approved these changes

2016-09-16 14:11 UTC, merged

2025-03-15 18:22 UTC, dswaffordcw commented
@tgraf Is this still a relevant option?

I came across it recently while investigating the various flags for Cilium agent persistence across restarts:
```
--keep-config
--restore
--clean-cilium-state
--clean-cilium-bpf-state
```

I ask, because I don't see a Helm variant of `--keep-config`?  If it's no longer needed, I'd like to remove it to reduce confusion.

2025-03-18 10:02 UTC, aanm commented
> @aanm @tgraf Is this still a relevant option?
> 
> I came across it recently while investigating the various flags for Cilium agent persistence across restarts:
> 
> ```
> --keep-config
> --restore
> --clean-cilium-state
> --clean-cilium-bpf-state
> ```
> 
> I ask, because I don't see a Helm variant of `--keep-config`? If it's no longer needed, I'd like to remove it to reduce confusion.

We can always deprecate the option. However, users are free to extend any flags using helm.