doc: Update AUTHORS file
cilium/cilium pull request #12142
Opened 2020-06-17 14:44 UTC by tgraf

2020-06-18 00:05 UTC, joestringer requested changes
~I suspect we've resolved several of these in Cilium 1.7 branch, maybe we need to forward-port the `.mailmap` file and amend it.~

(I checked; we haven't. Must just be the new authors this round.)

2020-06-18 00:05 UTC, joestringer commented on AUTHORS
> +Weilong Cui                             cuiwl@google.com
Looks like we need to extend `.mailmap`.

2020-06-18 00:05 UTC, joestringer commented on AUTHORS
> +ArthurChiao                             arthurchiao@hotmail.com
```suggestion
Arthur Chiao                             arthurchiao@hotmail.com
```

2020-06-18 00:05 UTC, joestringer commented on AUTHORS
> +CybrPunk                                seanmwinn@hotmail.com
One more for `.mailmap`

2020-06-18 00:05 UTC, joestringer commented on AUTHORS
> +Jonathan Davies                         jpds@protonmail.com
One more for `.mailmap`

2020-06-18 00:05 UTC, joestringer commented on AUTHORS
> +Joshua Roppo                            joshroppo@gmail.com
One more for `.mailmap`

2020-06-18 00:05 UTC, joestringer commented on AUTHORS
> +Tony Lu                                 tonylu@linux.alibaba.com
doubled up here

2020-07-03 12:50 UTC, aanm approved these changes

2020-07-06 12:51 UTC, merged