cilium: split off handling of lb svc type in datapath
cilium/cilium pull request #12234
Opened 2020-06-23 14:21 UTC by borkmann

See commit msgs.

2020-06-23 15:01 UTC, tklauser approved these changes
LGTM. Two small remarks regarding extending the unit tests. Probably not worth respinning just for these.

2020-06-23 15:01 UTC, tklauser commented on pkg/loadbalancer/loadbalancer.go
> +		case SVCTypeLoadBalancer:
Might be worth to expand `TestCreateSvcFlag` to cover `SVCTypeLoadBalancer`?

2020-06-23 15:01 UTC, tklauser commented on pkg/loadbalancer/loadbalancer.go
> +	sType := s & (serviceFlagExternalIPs | serviceFlagHostPort | serviceFlagNodePort | serviceFlagLoadBalancer)
Same here, maybe extend `TestServiceFlags_String` to cover `SVCTypeLoadBalancer`?

2020-06-23 15:14 UTC, aanm requested changes
LGTM but needs e2e that we can run on GKE since it offers a LB

2020-06-23 20:19 UTC, borkmann commented
test-me-please

2020-06-24 08:03 UTC, borkmann commented
(all tests green)

2020-06-24 09:52 UTC, borkmann commented
test-me-please

2020-06-24 09:52 UTC, borkmann commented
test-gke

2020-06-24 09:53 UTC, borkmann commented
test-focus K8sService*

2020-06-24 11:32 UTC, nebril approved these changes

2020-06-24 12:22 UTC, borkmann commented
(2 GKE test flakes, unrelated: https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/1717/)

2020-06-24 13:22 UTC, aanm approved these changes

2020-06-24 13:23 UTC, merged