Add Kubernetes the Hard Way Install File
cilium/cilium pull request #12242
Opened 2020-06-23 18:12 UTC by nathanjsweet

Signed-off-by: Nate Sweet <nathanjsweet@pm.me>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Given a Cilium-specific "Kubernetes The Hard Way" install guide, we need a file that works with that specific installation guide to make it easy to use.

2020-06-23 19:16 UTC, joestringer commented
Quick question, how do we intend to keep this up-to-date?

This seems like something we should be able to generate from Helm in a similar way to the `quick-install.yaml`. That way, `make -C install/kubernetes` would update it so it wouldn't rot.

2020-06-23 21:00 UTC, michi-covalent commented
agree with @joestringer it would be good to add a make target like {quick,experimental}_install.yaml.

also, could you also point me to the "Kubernetes The Hard Way" install guide?

2020-06-24 10:14 UTC, aanm requested changes
Ideally this file should be created automatically in a similar way we are doing with the `install/kubernetes/experimental-install.yaml`

2020-06-24 10:14 UTC, aanm commented on install/kubernetes/kubernetes-the-hard-way-install.yaml
> +        name: cilium-etc
Why is this required? All necessary configuration to access the cluster should be installed in the pods automatically by kubelet.

2020-07-09 23:08 UTC, joestringer commented
Converting to draft so it doesn't show up in people's review queues. When the feedback has been addressed, please mark `Ready for review` using the button near the bottom of the page.

2020-08-22 23:41 UTC, closed without merging