ci: Check for gke nodepool before locking cluster
cilium/cilium pull request #12301
Opened 2020-06-26 11:54 UTC by nebril

If the cluster has just been recreated, it can have no nodepool yet.
Don't choose such clusters because scaling it will fail.

2020-06-26 11:54 UTC, nebril commented
test-gke K8sDemos

2020-06-26 12:18 UTC, nebril commented
test-gke K8sDemos

2020-06-26 16:51 UTC, nebril commented
test-gke K8sDemos

2020-06-29 08:59 UTC, aanm commented
The error looks odd:
```
16:55:07  #18 DONE 0.3s
16:55:07  docker tag cilium/hubble-relay:5d82d5084a83d2bbe06c7cc87eacd9fb7c7c90f8 cilium/hubble-relay:5d82d5084a83d2bbe06c7cc87eacd9fb7c7c90f8-amd64
16:55:07  Push like this when ready:
16:55:07  docker push cilium/hubble-relay:5d82d5084a83d2bbe06c7cc87eacd9fb7c7c90f8-amd64
16:55:07  make docker-operator-image
16:55:07  make[1]: Entering directory '/home/jenkins/workspace/Cilium-PR-K8s-GKE@2/src/github.com/cilium/cilium'
16:55:07  HEAD detached at 5d82d5084a
16:55:07  Untracked files:
16:55:07    (use "git add <file>..." to include in what will be committed)
16:55:07  
16:55:07  	test/gke/registry-adder.yaml
16:55:07  
16:55:07  nothing added to commit but untracked files present (use "git add" to track)
16:55:07  These changes will not be included in build, aborting. Define IGNORE_GIT_STATUS to build anyway.
16:55:07  Makefile.buildkit:73: recipe for target 'check-status' failed
16:55:07  make[1]: *** [check-status] Error 1
16:55:07  make[1]: Leaving directory '/home/jenkins/workspace/Cilium-PR-K8s-GKE@2/src/github.com/cilium/cilium'
16:55:07  Makefile.docker:16: recipe for target 'docker-image' failed
16:55:07  make: *** [docker-image] Error 2
```

2020-06-30 14:14 UTC, nebril commented
test-gke K8sDemos

2020-06-30 14:36 UTC, nebril commented
Seems like this is caused by setting DOCKER_BUILDKIT to 1

2020-06-30 14:40 UTC, nebril commented
test-gke K8sDemos

2020-07-01 08:06 UTC, nebril commented
test-4.9

2020-07-01 08:07 UTC, nebril commented
gke error happens after what this PR fixes, so all good from this side. running 4.9 build to make sure nothing else break, after that it's good to merge

2020-07-01 08:09 UTC, jrajahalme commented
On GKE test cilium-node-init is in ImagePullBackOff because startup-script is not available from the same hub as the cilium itself:
```
07:51:38  	 cilium              cilium-node-init-hmn5w                                      0/1     ImagePullBackOff   0          5m30s   10.128.0.10   gke-cilium-ci-16-cilium-ci-16-f02f6524-xqsp   <none>           <none>
```
This error is unrelated to this PR.

2020-07-01 08:10 UTC, jrajahalme approved these changes
GKE test successfully passed cluster selection, so this is good to merge.

2020-07-01 08:12 UTC, jrajahalme requested changes

2020-07-01 08:12 UTC, jrajahalme commented on test/make-images-push-to-local-registry.sh
> +IGNORE_GIT_STATUS=1 DOCKER_BUILDKIT=1 make docker-image DOCKER_IMAGE_TAG="$2"
But this should not be there. Rather add any offending temp files to `.gitignore`.

2020-07-01 08:26 UTC, nebril commented
test-gke K8sDemos

2020-07-01 08:27 UTC, jrajahalme approved these changes

2020-07-01 08:48 UTC, merged