fix(9966): fix creation of multiple KVStore watchers for CNPs and CCNPs
cilium/cilium pull request #12323
Opened 2020-06-29 15:07 UTC by fristonio

* Fixes #9966
* Implement Observer for CNPStatusEventHandler to remove the need of extra
  KVstore watcher.

2020-06-29 15:46 UTC, fristonio commented
test-me-please

2020-06-29 17:49 UTC, aanm requested changes

2020-06-29 17:49 UTC, aanm commented on operator/ccnp_event.go
>  		ccnpSharedStore, err := store.JoinSharedStore(store.Configuration{
Why doesn't this `ccnpSharedStore` have  observer?

2020-06-29 17:49 UTC, aanm commented on pkg/k8s/ccnpstatus.go
> -
On line 42, `func NewCCNPStatusEventHandler` no longer uses `cnpStore` so we can remove it from the function arguments.

2020-06-29 17:49 UTC, aanm commented on operator/cnp_event.go
> +		cnpStatusMgr.UpdateCNPStore(cnpSharedStore)
Please add a comment that is safe to update the store here given that the store will only be used by the `StartStatusHandler` function. (Same for the CCNP similar code)

2020-06-30 04:40 UTC, fristonio commented
test-me-please

2020-06-30 14:45 UTC, aanm approved these changes

2020-06-30 14:55 UTC, merged