v1.6 backports 2020-06-30
cilium/cilium pull request #12346
Opened 2020-06-30 21:05 UTC by aanm

* #12106 -- Use right CCNP validation (@aanm)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 12106 1; do contrib/backporting/set-labels.py $pr done 1.6; done
```

2020-06-30 21:06 UTC, aanm commented
test-backport-1.6

2020-06-30 22:32 UTC, joestringer requested changes

2020-06-30 22:32 UTC, joestringer commented on cilium/cmd/preflight_k8s_valid_cnp.go
> +		return fmt.Errorf("Unable to create API extensions clientset for k8s CRD: %w", err)
Travis reports:

```
cilium/cmd/preflight_k8s_valid_cnp.go:76:10: Errorf format %w has unknown verb w

cilium/cmd/preflight_k8s_valid_cnp.go:80:10: Errorf format %w has unknown verb w
```

This seems to be due to `%w` being a Go 1.13 feature. I think we just need to do:

```suggestion
		return fmt.Errorf("Unable to create rest configuration for k8s CRD: %s", err)
	}
	apiExtensionsClient, err := apiextensionsclient.NewForConfig(restConfig)
	if err != nil {
		return fmt.Errorf("Unable to create API extensions clientset for k8s CRD: %s", err)
```

2020-07-01 00:52 UTC, joestringer commented
Looks like the only failures were the unit tests, so I fixed it up & will re-push.

2020-07-01 00:56 UTC, joestringer commented
test-backport-1.6

2020-07-01 01:01 UTC, joestringer approved these changes

2020-07-01 07:05 UTC, merged

2020-07-01 18:18 UTC, joestringer commented
@pchaigno quick reminder to run the command in the commit message to update labels after merging :-) I did it this time.

2020-07-02 10:38 UTC, pchaigno commented
Ah, I thought the backporter was in charge of that. But yeah makes sense, since backporter could be offline and we want to do that as quickly as possible.