build: Fix shellcheck errors
cilium/cilium pull request #12407
Opened 2020-07-03 18:15 UTC by errordeveloper

- specify the path to cni-version.sh
- only lint executable shell scripts
- remove unused variable

2020-07-03 18:20 UTC, errordeveloper commented
This is a follow-up to https://github.com/cilium/cilium/pull/12013, as I forgot to run linter on the latest iteration of the code.

2020-07-03 19:19 UTC, tklauser approved these changes

2020-07-04 08:08 UTC, nebril approved these changes

2020-07-04 17:20 UTC, aanm requested changes
Please add a `Fixes: <12 first characters of commit sha>` for the commit these changes are fixing.

Item number 5 from https://docs.cilium.io/en/latest/contributing/development/contributing_guide/#submitting-a-pull-request

2020-07-06 10:07 UTC, errordeveloper commented
@aanm thanks, I've update the commit message.

2020-07-06 13:21 UTC, aanm approved these changes

2020-07-06 13:21 UTC, merged