Revisited endpoint state restore
cilium/cilium pull request #1242
Opened 2017-08-01 01:18 UTC by aanm

There's still some tests to be made but works with docker and kubernetes.

2017-08-01 01:36 UTC, ianvernon commented on daemon/state.go
> +// cleanUpDockerDandlingEndpoints cleans all endpoints that are dandling by
Nit: Dandling --> Dangling

2017-08-01 02:20 UTC, aanm commented on daemon/state.go
> +// cleanUpDockerDandlingEndpoints cleans all endpoints that are dandling by
Fixed!

2017-08-01 08:57 UTC, tgraf requested changes

2017-08-01 08:57 UTC, tgraf commented on daemon/state.go
>  	log.Infof("Restored %d endpoints", restored)
This number of restored endpoints seems premature as it may fail later. I suggest we remove it.

2017-08-01 08:57 UTC, tgraf commented on daemon/state.go
> +				log.Errorf("Failed while reallocating ep %d's IP addresses: %s. Endpoint won't be restored", ep.ID, err)
Let's be consistent and call it endpoint in all info messages
`"Failed to re-allocate IP of endpoint %d. Not restoring endpoint."`

2017-08-01 08:57 UTC, tgraf commented on daemon/state.go
> +			log.Infof("EP %d's IP addresses successfully reallocated", ep.ID)
This info message seems useless as it again may fail afterwards.

2017-08-01 08:57 UTC, tgraf commented on daemon/state.go
> +			log.Infof("Restored endpoint %d", epID)
This is the most important info message, we may want to report the IP addresses as well.

2017-08-01 08:57 UTC, tgraf commented on daemon/state.go
> +
`"Restored %d endpoints"`

2017-08-01 08:57 UTC, tgraf commented on daemon/docker_watcher.go
> +		d.SyncDocker()
Typo in commit title. "Spawning"

2017-08-03 05:21 UTC, aanm commented on daemon/state.go
> +
Change it a little bit, better?

2017-08-03 12:51 UTC, tgraf commented on daemon/state.go
> +
nit: `.. of which 3 were restored`

2017-08-03 12:51 UTC, tgraf commented on daemon/state.go
> +
Otherwise looks great now!

2017-08-03 12:53 UTC, tgraf requested changes
Only a small nit left

2017-08-03 13:13 UTC, aanm commented on daemon/state.go
> +
Fixed

2017-08-04 15:13 UTC, aanm commented
@tgraf the tests (k8s, docker and unit tests) have passed. I've changed the flag restore functionality to be `true` as default.

2017-08-05 19:39 UTC, tgraf approved these changes

2017-08-05 19:40 UTC, merged