Documentation: Rework architecture guide (endpoints & multi node networking)
cilium/cilium pull request #1244
Opened 2017-08-01 14:30 UTC by tgraf

Also removes some outdated documentation around policy

2017-08-01 15:39 UTC, ianvernon commented on Documentation/architecture.rst
> +container running on the same cluster node to all bind to well known ports such
multiple application containers

2017-08-01 15:40 UTC, ianvernon commented on Documentation/architecture.rst
> +IP addresses. Multiple application containers can share the same IP address, a
same IP address; a typical example...

2017-08-01 15:40 UTC, ianvernon commented on Documentation/architecture.rst
> +IPv4 or IPv6 address. If both an IPv6 and IPv4 address are assigned, either
would be helpful to link to a section in the Docs that describes such configuration

2017-08-01 15:41 UTC, ianvernon commented on Documentation/architecture.rst
> +For identification purposes, Cilium assign an *endpoint id* to all endpoints on
assigns

2017-08-01 15:43 UTC, ianvernon commented on Documentation/architecture.rst
> +    62006      Disabled      257        container:app=netperf         f00d::a00:20f:0:f236   10.15.116.202   ready
Shouldn't the label be "container:app=benchmark"?

2017-08-01 15:43 UTC, ianvernon commented on Documentation/architecture.rst
> +Key-Value store or with packet metdata.
metadata

2017-08-01 15:45 UTC, ianvernon commented on Documentation/architecture.rst
> +This simplifies address handling and allows to make a fundamental assumption:
allows one to make

2017-08-01 15:47 UTC, ianvernon commented on Documentation/architecture.rst
> +transmit the security context of where the packet origins from which allows
where the packet originates, which allows...

2017-08-01 15:48 UTC, ianvernon commented on Documentation/architecture.rst
>  underlying network it runs on, it only contains a default route which points to
it runs on; it only...

2017-08-01 15:48 UTC, ianvernon commented on Documentation/architecture.rst
> +the IP address of the cluster node Given the removal of the routing cache in
cluster node.

2017-08-01 15:49 UTC, ianvernon commented on Documentation/architecture.rst
>  the Linux kernel, this reduces the amount of state to keep to the per
amount of state to keep in the per-connection flow cache, which allows for the termination of millions of connection in each container.

2017-08-01 15:50 UTC, ianvernon commented on Documentation/architecture.rst
> +encapsulation protocols VXLAN_ or Geneve_. All container to container network
container-to-container

2017-08-01 15:50 UTC, ianvernon commented on Documentation/architecture.rst
> +traffic is routed through these tunnels. This mode several major advantages:
... mode has ...

2017-08-01 15:51 UTC, ianvernon commented on Documentation/architecture.rst
> +- **Identity transfer:** Encapsulation protocols allow to carry arbitrary
allow for the carrying of arbitrary

2017-08-01 15:53 UTC, ianvernon commented on Documentation/architecture.rst
> +means that the packet will be routed just as if a local process would emit the
will be routed as if a local process had emitted the packet

2017-08-01 16:58 UTC, ianvernon requested changes
Great explanations! Just a few typos / grammatical mistakes that need to be fixed.

2017-08-01 16:58 UTC, ianvernon commented on Documentation/architecture.rst
> +          stored in the flowlabel. IPv4 is currently ot supported and thus
currently not supported

2017-08-01 16:58 UTC, ianvernon commented on Documentation/architecture.rst
> +If the destination of a packet relies outside of the cluster. Cilium will
lies outside of the cluster, Cilium will delegate...

2017-08-01 16:58 UTC, ianvernon commented on Documentation/architecture.rst
> +from RFC1918 private address blocks and not publicly routeable. Cilium will
...are not publicly routable

2017-08-01 16:58 UTC, ianvernon commented on Documentation/architecture.rst
> +In direct routing mode, endpoint IPs can be publicly routeable IPs and no
endpoint is referenced as \*endpoint\* elsewhere in the guide - should it be done so here as well for consistency?

2017-08-01 16:58 UTC, ianvernon commented on Documentation/architecture.rst
> +In overlay mode, endpoints accepting inbound connections, such services are
Same as above.

2017-08-01 16:58 UTC, ianvernon commented on Documentation/architecture.rst
> +In overlay mode, endpoints accepting inbound connections, such services are
In overlay mode, endpoints that are accepting inbound connections are likely exposed via some kind of load-balancing layer...

2017-08-01 17:31 UTC, aalemayhu requested changes

2017-08-01 17:31 UTC, scanf commented on Documentation/architecture.rst
> +- `Direct / Native Routing Mode`_
The overlay link does not render properly.

2017-08-02 07:32 UTC, tgraf commented on Documentation/architecture.rst
> +    62006      Disabled      257        container:app=netperf         f00d::a00:20f:0:f236   10.15.116.202   ready
Yes,fixed

2017-08-02 13:48 UTC, merged