test: Use updated smaller docker images
cilium/cilium pull request #12583
Opened 2020-07-20 10:43 UTC by pchaigno

The `dnssec-client` and `python-bmemcached` images have been updated as shown in cilium/dnssec-client#1 and cilium/python-bmemcached#1 respectively. The `cc-grpc-demo` image has been updated as per the first commit in this PR.

Updates: cilium/packer-ci-build#227

2020-07-20 10:56 UTC, pchaigno commented
test-me-please

2020-07-20 13:34 UTC, pchaigno commented
retest-net-next

2020-07-21 09:59 UTC, aanm requested changes

2020-07-21 09:59 UTC, aanm commented on examples/kubernetes-memcached/memcd-sw-app.yaml
> +        image: cilium/python-bmemcached:v0.0.2
can you add `docker.io/`

2020-07-21 09:59 UTC, aanm requested changes

2020-07-21 09:59 UTC, aanm commented on examples/kubernetes-grpc/Dockerfile
> +FROM ubuntu:20.04 as builder
and here `docker.io/library/ubuntu:20.04`

2020-07-21 09:59 UTC, aanm commented on examples/kubernetes-grpc/Dockerfile
> +FROM ubuntu:20.04
and here `docker.io/library/ubuntu:20.04`

2020-07-21 10:05 UTC, pchaigno commented
test-me-please

2020-07-21 10:12 UTC, qmonnet approved these changes

2020-07-21 10:32 UTC, pchaigno commented
test-me-please

2020-07-21 11:40 UTC, aanm approved these changes

2020-07-21 12:10 UTC, rolinh approved these changes

2020-07-21 13:59 UTC, pchaigno commented
cilium/dnssec-client#1 and cilium/python-bmemcached#1 are merged, so this should be ready once it gets some @cilium/ci reviews.

2020-07-23 08:18 UTC, nebril approved these changes

2020-07-23 08:18 UTC, merged