v1.8: Update Go to 1.14.6
cilium/cilium pull request #12584
Opened 2020-07-20 10:53 UTC by tklauser

2020-07-20 11:17 UTC, tklauser commented
test-backport-1.8

2020-07-21 00:33 UTC, christarazi approved these changes

2020-07-21 08:53 UTC, aanm requested changes

2020-07-21 08:53 UTC, aanm commented on Dockerfile.builder
> +FROM quay.io/cilium/cilium-runtime:2020-07-20@sha256:919b0084a343431d695e8f1f6abebb6040f620c28d7a9982bc5b653ccaadf67e
`s+FROM quay.io/cilium/cilium-runtime:2020-07-20+quay.io/cilium/cilium-runtime:2020-07-20-v1.8`

2020-07-21 09:05 UTC, aanm approved these changes
Doesn't need a 2nd CI run since this the requested change were only typos

2020-07-21 09:05 UTC, merged