Cleanup unused methods and fields in pkg/policy
cilium/cilium pull request #12688
Opened 2020-07-27 17:59 UTC by aanm

Read per commit

2020-07-27 18:01 UTC, christarazi approved these changes
Nice. I thought `golangci-lint` would have caught these things?

2020-07-27 18:02 UTC, aanm commented
test-me-please

2020-07-27 18:53 UTC, aditighag requested changes

2020-07-27 18:53 UTC, aditighag commented on pkg/policy/distillery.go
>  // and whether policy has been computed for this identity.
Update the description for returned fields.

2020-07-27 18:53 UTC, aditighag commented on pkg/policy/distillery.go
>  // and whether policy has been computed for this identity.
Same as above.

2020-07-27 19:05 UTC, aanm commented
test-me-please

2020-07-27 19:23 UTC, aditighag approved these changes

2020-07-27 23:14 UTC, joestringer approved these changes

2020-07-27 23:53 UTC, sayboras commented
> Nice. I thought `golangci-lint` would have caught these things?

I think golangci-lint is only able to catch un-used private methods/variables, it's hard to catch public ones in `pkg/` , as these can be used as depedency.

2020-07-28 01:16 UTC, aanm commented
retest-netnext

2020-07-28 01:17 UTC, aanm commented
retest-net-next

2020-07-28 08:30 UTC, merged

2020-08-07 13:55 UTC, jrajahalme commented
Other backports depended on these so backported to v1.8.