pkg/envoy: Fix Envoy MySQL test
cilium/cilium pull request #12790
Opened 2020-08-05 22:07 UTC by christarazi

After https://github.com/cilium/cilium/pull/12567 was merged, a
potential bad rebase missed updating the `getNetworkPolicy` function
signature in the MySQL tests (introduduced in
https://github.com/cilium/cilium/pull/12500).

Fixes: 7857a628 ("envoy: Experimental support for MongoDB and MySQL enforcement")
Fixes: 13f22dc3 ("ipcache: Maintain named ports on demand")

2020-08-05 22:08 UTC, christarazi commented
Only a Travis run is necessary to unblock master branch.

2020-08-05 22:10 UTC, joestringer approved these changes

2020-08-05 22:12 UTC, aanm approved these changes

2020-08-05 22:14 UTC, aanm requested changes
The commit SHA that this one is fixing don't exist.

It should be:
040e88d71c50ea8e425534d590d3ba0ada1a6c0d - envoy: Experimental support for MongoDB and MySQL enforcement
fbd904915d53b5f1efdc47c4f4a106f12d21a07e - ipcache: Maintain named ports on demand

2020-08-05 22:15 UTC, christarazi commented
> [fbd9049](https://github.com/cilium/cilium/commit/fbd904915d53b5f1efdc47c4f4a106f12d21a07e)

Fixed. Not sure how I messed that up.

2020-08-05 22:18 UTC, aditighag approved these changes

2020-08-05 22:28 UTC, aanm approved these changes

2020-08-05 22:47 UTC, aanm commented
It was green https://travis-ci.com/github/cilium/cilium/jobs/369152358

2020-08-05 22:47 UTC, merged

2020-08-06 06:19 UTC, jrajahalme commented
Thanks for fixing this :-)