test: fixed failing missed k8s tests
cilium/cilium pull request #12887
Opened 2020-08-14 09:36 UTC by fristonio

2020-08-14 09:39 UTC, fristonio commented
test-me-please

2020-08-14 10:10 UTC, aanm requested changes
Small nit

2020-08-14 10:10 UTC, aanm commented on install/kubernetes/cilium/charts/preflight/templates/clusterrolebinding.yaml
> +  name: cilium-pre-flight
Please add in the commit message the "Why?" we need this change.

2020-08-14 12:18 UTC, fristonio commented
test-focus K8sUpdates

2020-08-14 12:32 UTC, fristonio commented
test-missed-k8s

2020-08-14 14:08 UTC, fristonio commented
test-focus K8sServicesTest

2020-08-14 17:48 UTC, christarazi approved these changes
LGTM, there's a typo in one of serviceAccount commit: `serviceAccnout`

2020-08-15 06:11 UTC, fristonio commented
test-focus K8sServicesTest

2020-08-16 12:42 UTC, fristonio commented
test-me-please

2020-08-16 14:34 UTC, sayboras approved these changes
LGTM and thanks.

I can re-run gingko test with `--cilium.provision=false` now :man_dancing:

2020-08-16 15:39 UTC, fristonio commented
test-missed-k8s

2020-08-16 19:27 UTC, fristonio commented
test-missed-k8s

2020-08-16 19:28 UTC, fristonio commented
test-me-please

2020-08-17 03:55 UTC, fristonio commented
test-focus K8sServicesTest

2020-08-17 09:51 UTC, aanm requested changes

2020-08-17 09:51 UTC, aanm commented on test/helpers/kubectl.go
>  		"kubectl get replicationcontroller --all-namespaces -o json":         "replicationcontroller.txt",
In the commit message, it should be:
```
Fixes: aeefd5862ae4 ("test/helpers: dump rbac information on k8s test failure")
Signed-off-by: Deepesh Pathak <deepshpathak@gmail.com>
```

2020-08-17 17:08 UTC, fristonio commented
test-focus K8sUpdates

2020-08-18 09:16 UTC, aanm approved these changes

2020-08-18 09:56 UTC, fristonio commented
test-focus K8sServicesTest

2020-08-18 10:01 UTC, fristonio commented
test-focus K8sUpdates

2020-08-18 10:59 UTC, fristonio commented
test-missed-k8s

2020-08-18 11:51 UTC, tklauser approved these changes

2020-08-20 06:01 UTC, fristonio commented
test-me-please

2020-08-20 09:40 UTC, fristonio commented
retest-net-next

2020-08-20 11:47 UTC, fristonio commented
test-focus K8sServicesTest

2020-08-20 16:41 UTC, aanm approved these changes

2020-08-21 06:05 UTC, fristonio commented
test-focus K8sServicesTest

2020-08-25 13:26 UTC, merged