Add a `node` label to agent metrics.
cilium/cilium pull request #12965
Opened 2020-08-25 12:32 UTC by diversario

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

Exposing node name allows correlating Cilium metrics to node metrics for
more advanced recording rules/alerts, for example: ignore endpoint
health on nodes aged less than 2 minutes.

```release-note

```

2020-08-26 15:01 UTC, sayboras reviewed
Maybe a question to you and others :)  

Do we need to add for other ServiceMonitor as well or will it be case by case? The best case that I have in mind is to expose `relabel configs` in values.yaml, so that users can just adjust values based on their needs, I don't know how to achieve it in concise way now though.

[1] https://prometheus.io/docs/prometheus/latest/configuration/configuration/

2020-08-26 15:01 UTC, sayboras commented on install/kubernetes/cilium/charts/agent/templates/servicemonitor.yaml
> +    - replacement: ${1}
nit: this is default value, which can be removed. Feel free to ignore.

2020-09-02 20:27 UTC, joestringer commented on install/kubernetes/cilium/charts/agent/templates/servicemonitor.yaml
> +    - replacement: ${1}
@sayboras do you want @diversario to remove this line or not? If we think it should be here, then I think we can resolve this point. If this line should not be there, please use the "request changes" approach to make it clear that the contributor will need to address this prior to accepting this patch.

2020-09-02 20:29 UTC, joestringer requested changes
Please either write a release note in the section of the description with the following text, or remove that section:

```
<!-- Enter the release note text here if needed or remove this section! -->
```

This will ensure that the release notes will mention your PR submission with a clear description.

Other than this, if it's passing CI and helps solve what you're trying to do then I think this makes sense to merge :+1:

2020-09-06 21:04 UTC, diversario commented on install/kubernetes/cilium/charts/agent/templates/servicemonitor.yaml
> +    - replacement: ${1}
Sorry about lack of response!

Re this line: I understand it's redundant but IMO it's ok to keep as it for people who're reading this and trying to understand how things work (definitely helped me).

2020-09-08 01:33 UTC, sayboras approved these changes
LGTM :100:

2020-09-15 21:37 UTC, joestringer approved these changes

2020-09-15 21:37 UTC, merged