docs: Script more of the bandwidth manager GSG
cilium/cilium pull request #12976
Opened 2020-08-26 15:39 UTC by pchaigno

This commit attempts to turn the bandwidth manager getting started guide into a simple workflow of copy/pastes for users. That is, it scripts commands so that they can be executed without needing to look for the right pod or node name.

To make this easier, a second netperf pod is started on a separate node from the netperf server (via an antiAffinity rule). That second pod is used to run the netperf client.

- If anyone has ideas to make the deployments shorter, please suggest. I'm not very familiar with those.
- The downside of scripting more of the guide through use of `jq` is that it may be a bit less easier for the users to see what they are doing. The variable names attempt to clarify that but there might be room for improvement.

2020-08-26 18:40 UTC, borkmann reviewed
I would love for the very initial first user howto to have some simple step by step items. My concern if we place the more complex setup there right away would be that users potentially find it too complex. I do like that for the kube-proxy free guide we have an easy super quick intro and all the advanced stuff marked as such under `advanced configuration`. Maybe here it makes sense to add a `Advanced testing` section and place these there, e.g. having to or more parallel flows to the same pod and showing that the max rate is still the one configured for the Pod overall.

2020-08-27 05:57 UTC, pchaigno commented
@borkmann The general idea of having an advanced section sounds good to me. I'm not sure I understand what changes you'd expect w.r.t. to the current PR though. Are there parts of the current guide you think we should move to an advanced section? Are there other aspects you think we should cover (in an advanced section)?

> e.g. having to or more parallel flows to the same pod and showing that the max rate is still the one configured for the Pod overall

For that specific example, I wouldn't expect to see that in a GSG. I'd expect the (advanced) guide to cover situations users may run into (for troubleshooting, corner cases, etc.). This one sounds more like a specific situation the implementation handles that doesn't require any additional step from users, like you'd find in a demo.

2020-08-27 08:55 UTC, borkmann commented
> @borkmann The general idea of having an advanced section sounds good to me. I'm not sure I understand what changes you'd expect w.r.t. to the current PR though. Are there parts of the current guide you think we should move to an advanced section? Are there other aspects you think we should cover (in an advanced section)?

Ok, for the current PR, my main concern is that the scripting bits while useful for us might scare away some users if they see it in the GSG. So I think we should keep it as simple & straight forward as possible w/o much additional complexity for the main part. I'm also thinking to move the ifb explanation out (https://github.com/cilium/cilium/pull/12976) from there since it's unnecessary detail.

I think it would be nice if you could add a similar structure as in https://docs.cilium.io/en/latest/gettingstarted/kubeproxy-free/ that is, subsections for `Quick-Start`, `Validate the Setup`, `Limitations`, and for the setup validation we could cover the two cases e.g. host->pod and pod->pod, maybe one example with direct routing and another one with tunneling enabled or such.

> > e.g. having to or more parallel flows to the same pod and showing that the max rate is still the one configured for the Pod overall
> 
> For that specific example, I wouldn't expect to see that in a GSG. I'd expect the (advanced) guide to cover situations users may run into (for troubleshooting, corner cases, etc.). This one sounds more like a specific situation the implementation handles that doesn't require any additional step from users, like you'd find in a demo.

Yeah agree, that goes beyond what is needed.

2020-09-02 20:01 UTC, joestringer requested changes
Couple of minor nits but looks OK to me. I did not try out the instructions.

2020-09-02 20:01 UTC, joestringer commented on Documentation/gettingstarted/bandwidth-manager.rst
> +.. code:: bash
nit, FYI these should be `shell-session` not `bash` as the highlighting is different and this is a shell session example, not a bash script.
```suggestion
.. code:: shell-session
```

2020-09-02 20:01 UTC, joestringer commented on Documentation/gettingstarted/bandwidth-manager.rst
> +    $ cat <<EOF | kubectl apply -f -
It makes sense to have these examples in the tree under `examples/` and to `kubectl apply -f |SCM_WEB| ...` (using `.. parsed-literal::`) so it's easy to pull & apply such examples. This can then be `literalinclude` of the file. One step beyond that is to then also take this GSG example into CI testing so we validate the guides as part of automated testing.

2020-11-23 14:17 UTC, closed without merging