cleanup/ipam: Remove hostscope-legacy IPAM option
cilium/cilium pull request #12984
Opened 2020-08-27 10:35 UTC by sayboras

To remove hostscope-legacy IPAM option

Fixes: #12974

Signed-off-by: Tam Mach <sayboras@yahoo.com>

```release-note
cleanup/ipam: Remove hostscope-legacy IPAM option
```

2020-08-28 06:00 UTC, sayboras commented
test-me-please

2020-08-28 12:13 UTC, sayboras commented
test-me-please

2020-09-01 13:36 UTC, sayboras commented
test-me-please

2020-09-02 23:29 UTC, joestringer requested changes
Minor docs typos/nits, otherwise LGTM

2020-09-02 23:29 UTC, joestringer commented on Documentation/install/upgrade.rst
> +* The ``hostscope-legacy`` option value for ``ipam`` is not removed. Defaults to
```suggestion
* The ``hostscope-legacy`` option value for ``ipam`` is now removed. Defaults to
```

2020-09-02 23:29 UTC, joestringer commented on Documentation/install/upgrade.rst
> +* The ``hostscope-legacy`` option value for ``ipam`` is not removed.
```suggestion
* The ``hostscope-legacy`` option value for ``ipam`` is now removed.
```

2020-09-02 23:29 UTC, joestringer commented on Documentation/install/upgrade.rst
> +* The ``hostscope-legacy`` option value for ``ipam`` is not removed. Defaults to
Also maybe to be a bit more clear?
````
The ``ipam`` option now defaults to ``cluster-pool``
````

2020-09-03 02:46 UTC, sayboras commented
Jenkins jobs are completed successfully, force push to address review comments related to docs.

2020-09-03 08:02 UTC, aanm approved these changes

2020-09-03 08:03 UTC, aanm commented
test-me-please

2020-09-03 12:18 UTC, sayboras commented
Failure seems related to https://github.com/cilium/cilium/issues/13056

```
20:17:43  Summarizing 1 Failure:
20:17:43  
20:17:43  [Fail] K8sBandwidthTest Checks Bandwidth Rate-Limiting [It] Checks Pod to Pod bandwidth, geneve tunneling 
20:17:43  /home/jenkins/workspace/Cilium-PR-K8s-1.12-net-next/src/github.com/cilium/cilium/test/k8sT/Bandwidth.go:142
```

2020-09-03 12:44 UTC, fristonio requested changes
The changes in the PR looks good to me. But I wonder with the changes in the PR we don't need any documentation related to `hostscope` IPAM as well?
Like removing - https://github.com/cilium/cilium/blob/master/Documentation/concepts/networking/ipam/hostscope.rst

2020-09-03 19:13 UTC, christarazi approved these changes
LGTM assuming everyone else's comments have been addressed.

2020-09-03 22:12 UTC, sayboras commented
> The changes in the PR looks good to me. But I wonder with the changes in the PR we don't need any documentation related to `hostscope` IPAM as well?
> Like removing - https://github.com/cilium/cilium/blob/master/Documentation/concepts/networking/ipam/hostscope.rst

Good catch, thanks a lot. Let me scan the docs one more time :monocle_face:

2020-09-04 10:43 UTC, sayboras commented
Force pull for docs update, full CI is not required

<details>
<summary>git diff</summary>

```
        deleted:    concepts/networking/ipam/hostscope.rst
        modified:   concepts/networking/ipam/index.rst

diff --git a/Documentation/concepts/networking/ipam/index.rst b/Documentation/concepts/networking/ipam/index.rst
index 32d770231..4bb72e55a 100644
--- a/Documentation/concepts/networking/ipam/index.rst
+++ b/Documentation/concepts/networking/ipam/index.rst
@@ -24,5 +24,4 @@ Cilium. Various IPAM modes are supported to meet the needs of different users:
    eni
    gke
    crd
-   hostscope
    deep_dive
```

</details>

2020-09-04 11:05 UTC, fristonio approved these changes
LGTM :100:

2020-09-05 14:21 UTC, sayboras commented
test-me-please

2020-09-07 09:20 UTC, merged