Initial Text for the Mesos GSG
cilium/cilium pull request #1301
Opened 2017-08-12 01:30 UTC by techcet

2017-08-12 09:13 UTC, tgraf requested changes
Looks great, a couple of comments inline

2017-08-12 09:13 UTC, tgraf commented on Documentation/gettingstarted.rst
> +Download the latest Cilium `source code <https://github.com/cilium/cilium/archive/master.zip>`_
We should fix all guides to not point to the master release as it is a nightly generated tarball of the latest development snapshot. I'll create a separate issue to track this. Unfortunately, GitHub does not make it simple to link to the latest stable release so we'll have to maintain a stable URL ourselves.

2017-08-12 09:13 UTC, tgraf commented on Documentation/gettingstarted.rst
> +Start Marathon inside of the vbox:
The reset of the guides refers to *Vagrant VM* instead of box

2017-08-12 09:13 UTC, tgraf commented on Documentation/gettingstarted.rst
> +The web-server simply responds to requests on a particular port. Use the ``curl`` command below to launch it.
This needs a short explanation that curl is used to talk to the Marathon API to schedule a task

2017-08-12 09:13 UTC, tgraf commented on Documentation/gettingstarted.rst
> +
I would add a note that the output should be:
```
HTTP/1.1 201 Created
[...]
```
As the extensive response from Marathon looks a bit like something went wrong.

2017-08-12 09:13 UTC, tgraf commented on Documentation/gettingstarted.rst
> +    $ cilium endpoint list
People also read through guides without running them. Listing the output of commands is thus helpful:
```
ENDPOINT   POLICY        IDENTITY   LABELS (source:key[=value])   IPv6                   IPv4           STATUS
           ENFORCEMENT
29898      Disabled      256        mesos:id=web-server           f00d::a00:20f:0:74ca   10.15.242.54   ready
```

2017-08-12 09:13 UTC, tgraf commented on Documentation/gettingstarted.rst
> +There is no easy way to retrieve the logs of the client, so use the following script:
I would rephrase this so it doesn't sound like Cilium is at fault for not providing easier log access. I would write something like this:

Marathon runs all tasks as batch jobs and makes the stdout output available via a log file in `/var/lib/mesos`. The `tail_client.sh` script will identify the log file and then run `tail` on it.

2017-08-14 15:18 UTC, ianvernon approved these changes

2017-08-14 17:26 UTC, techcet commented on Documentation/gettingstarted.rst
> +    $ cilium endpoint list
Agreed- done.

2017-08-14 17:26 UTC, techcet commented on Documentation/gettingstarted.rst
> +
Agreed- done.

2017-08-14 17:26 UTC, techcet commented on Documentation/gettingstarted.rst
> +Start Marathon inside of the vbox:
Done.

2017-08-16 21:10 UTC, tgraf approved these changes

2017-08-16 21:20 UTC, amreshakim approved these changes
Looks awesome! Thanks for doing this.

2017-08-16 21:24 UTC, merged