contrib: Add release helper scripts for preparing micro releases
cilium/cilium pull request #13044
Opened 2020-09-02 03:42 UTC by joestringer

Automate the preparation of micro releases via a set of scripts. Steps in this PR:

* Run `start-release.sh` to generate helm charts, authors, changelogs, etc. Provide target release version and GH project number for N+1 version.
* Inspect changes and create commit with name "Prepare for release vX.Y.Z".
* Run `submit-release.sh` to send PR for this commit
* Manually close the old GH project
* Review & merge PR
* Pull release branch for true version of release commit
* `tag-release.sh` to tag current release & push releases (requires GPG key)
* Continue other steps from templates

2020-09-03 07:28 UTC, aanm requested changes
LGTM, only a small thing missing.

2020-09-03 07:28 UTC, aanm commented on .github/ISSUE_TEMPLATE/release_template.md
> -  - [ ] Point `.github/cilium-actions.yml` to the newly created project
We need to change the upgrade guide as well to reflect these changes.

2020-09-03 20:12 UTC, christarazi requested changes
Thanks for PRing these! A few minor comments below. Do you intend to merge this when ready or wait to give them a whirl on the next release, then merge?

2020-09-03 20:12 UTC, christarazi commented on contrib/release/prep-changelog.sh
> +    logecho "OLD-VERSION    Previuos release version for comparison"
```suggestion
    logecho "OLD-VERSION    Previous release version for comparison"
```

2020-09-03 20:12 UTC, christarazi commented on contrib/release/tag-release.sh
> +        git tag | tail -n 1
If we hit this case, what happens? Would it just generate release notes from a different tag, causing the release-notes to be shorter than they should be?

2020-09-03 22:10 UTC, joestringer commented on contrib/release/tag-release.sh
> +        git tag | tail -n 1
Good question, now I'm reading through this script again I don't remember why it's necessary to have any of this changelog generation code in `tag-release.sh`. The previous scripts should have properly generated it and if not, we should just exit out and have the release manager run the right scripts to generate it.

I'll rework this script to drop the extra complexity.

2020-09-03 22:12 UTC, joestringer commented
> Do you intend to merge this when ready or wait to give them a whirl on the next release, then merge?

I'm fine to go either way. No specific rush for this PR but if it's easier to iterate on the scripts in-tree then we can do so. I guess for ease of use we should also backport them to each branch so they're available locally (for those who don't have a separate Cilium git tree for each release).

2020-09-15 23:16 UTC, christarazi approved these changes

2020-09-16 09:00 UTC, aanm approved these changes
I didn't look at the scripts. I'll try them out in the next release and see how they go :tada:

2020-09-16 09:00 UTC, merged