connectivity-check: Check cue file formatting
cilium/cilium pull request #13088
Opened 2020-09-04 13:07 UTC by sayboras

This PR is to add one simple make target `make fmt` to auto-format cue
files, and run this check in related Github Action step as well

Related to https://github.com/cilium/cilium/pull/13067#discussion_r482930334

```release-note
connectivity-check: Check cue file formatting
```

2020-09-04 13:51 UTC, fristonio requested changes

2020-09-04 13:51 UTC, fristonio commented on examples/kubernetes/connectivity-check/Makefile
> +	$(QUIET)$(CUE) fmt
If I am not wrong then this only formats the cue templates and not check for formatting errors, right?

2020-09-04 16:59 UTC, christarazi approved these changes

2020-09-04 22:46 UTC, sayboras commented on examples/kubernetes/connectivity-check/Makefile
> +	$(QUIET)$(CUE) fmt
it's similar to gofmt as per my understanding (except that cue fmt returns zero exit code if there are some changes). In GA, _git diff_ is used to failed the build.

<details>
<summary>cue fmt exit code is always 0</summary>
```
$ git status           
On branch dummy
nothing to commit, working tree clean

$ cue fmt   
$ echo $?
0

$ gst       
On branch dummy
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   main_tool.cue

no changes added to commit (use "git add" and/or "git commit -a")
```

</details>

2020-09-08 16:28 UTC, fristonio approved these changes

2020-09-08 16:28 UTC, fristonio commented on examples/kubernetes/connectivity-check/Makefile
> +	$(QUIET)$(CUE) fmt
Ah, I missed the `git diff` part. Sorry
Looks good.

2020-09-08 16:41 UTC, joestringer approved these changes

2020-09-09 00:26 UTC, merged