k8s: Fix missing status subresource on CiliumNode
cilium/cilium pull request #13195
Opened 2020-09-17 04:41 UTC by christarazi

This fixes the issue where we fail to update the status of the
CiliumNode resource, leading to failures in surfacing ENI or Azure IPAM
information.

Fixes: https://github.com/cilium/cilium/issues/13193

2020-09-17 04:42 UTC, christarazi commented
test-me-please

2020-09-17 05:55 UTC, sayboras approved these changes
LGTM

2020-09-17 05:55 UTC, sayboras commented on pkg/k8s/apis/cilium.io/v2/types.go
> +// +kubebuilder:subresource:status
I believe that you already scanned once to make sure this is only resource missing `subresource:status` :)

2020-09-17 06:03 UTC, aanm requested changes
Please write a good release note for our users.

2020-09-17 08:35 UTC, qmonnet approved these changes
Thanks a lot for tracking this down!

2020-09-17 16:14 UTC, aditighag approved these changes

2020-09-17 17:43 UTC, joestringer commented
> Please write a good release note for our users.

This is good practice in general, although it's more important if it actually affects an existing release. If I follow correctly, this is only affecting the master branch right now. @christarazi is that correct?

For the release note, I think the current PR title is fairly close, but it does not make it clear for instance what the observed error is (eg in Cilium logs) or the potential consequence. These would be helpful to assist users hitting an issue to suggest whether this bugfix is relevant to them or not.

2020-09-17 18:18 UTC, christarazi commented
> > Please write a good release note for our users.
> 
> This is good practice in general, although it's more important if it actually affects an existing release. If I follow correctly, this is only affecting the master branch right now. @christarazi is that correct?
> 
> For the release note, I think the current PR title is fairly close, but it does not make it clear for instance what the observed error is (eg in Cilium logs) or the potential consequence. These would be helpful to assist users hitting an issue to suggest whether this bugfix is relevant to them or not. Feel free to ping me if you want to iterate on this and clarify the level of detail we would typically expect in a release note.

Yes that's correct. This is a regression on `master`. Will update the release note.

2020-09-17 18:21 UTC, christarazi commented
test-me-please

2020-09-18 00:52 UTC, christarazi commented
CI was failing because we needed 851a9ab. Unsure why we didn't see this behavior before with the missing status subresource.

2020-09-18 00:52 UTC, christarazi commented
test-me-please

2020-09-18 09:26 UTC, aanm approved these changes

2020-09-18 09:26 UTC, merged