v1.6 backports 2020-09-22
cilium/cilium pull request #13250
Opened 2020-09-22 15:32 UTC by mrostecki

* #13044 -- contrib: Add release helper scripts for preparing micro releases (@joestringer)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 13044; do contrib/backporting/set-labels.py $pr done 1.6; done
```

2020-09-22 15:36 UTC, mrostecki commented
This PR has changes only in docs and ´contrib` dir, so I guess that we don't have to run the whole test suite.

2020-09-22 15:59 UTC, qmonnet commented
test-docs-please

2020-09-22 16:08 UTC, qmonnet requested changes
We still have a test to build the doc in v1.6 so I ran it.

2020-09-22 16:08 UTC, qmonnet commented on Documentation/contributing/release.rst
> +#. Wait for DockerHub to prepare all docker images.
I think the double-colon kept above this line expects a “liteal block”, but none is found. This is what CI seems to complain about. Please address :)

2020-09-22 17:06 UTC, joestringer reviewed
FWIW I think it's also fine to just drop the issue template / docs changes changes to simplify the backport. My aim in making it available for backport is mainly to make the scripts available for anyone preparing a release on older branches. They should be able to refer to the `latest` version of the docs but change the local git branch to an older branch and use the scripts.

2020-09-23 13:08 UTC, qmonnet commented
test-docs-please

2020-09-23 14:12 UTC, merged