v1.8 backports 2020-09-25
cilium/cilium pull request #13289
Opened 2020-09-25 10:28 UTC by mrostecki

* #13241 -- cilium: encrypt-node creates two IPsec tunnels but only uses one (@jrfastab)
 * #13228 -- identity: Avoid kvstore lookup for local identities (@gandro)
 * #13248 -- hubble: Fix filter by reply reporting flows with unknown reply state  (@gandro)
 * #13187 -- docs: backport documentation additions (@kkourt)
 * #13234 -- EKS: improve rules for asymmetric routing (multi-node NodePort) (@qmonnet)
 * #13162 -- bpf: fix nodeport ipv6 services (@fristonio)
 * #13272 -- k8s: Remove CRD deleting functionality (@christarazi)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 13241 13228 13248 13187 13234 13162 13272; do contrib/backporting/set-labels.py $pr done 1.8; done
```

2020-09-25 10:28 UTC, mrostecki commented
test-backport-1.8

2020-09-25 10:31 UTC, mrostecki commented
@christarazi I'm a bit unsure if I backported your PR properly. I had a conflict with https://github.com/christarazi/cilium/commit/c2ca49c4c1704ca7531deb331b1ae2af8c33b926.

2020-09-25 10:33 UTC, qmonnet approved these changes
> * #13234 -- EKS: improve rules for asymmetric routing (multi-node NodePort) (@qmonnet)

Looks good to me, thank you!

2020-09-25 11:53 UTC, aanm commented
@mrostecki the code is failing:
```
13:00:33  
13:00:33  # github.com/cilium/cilium/test/k8sT
13:00:33  k8sT/Services.go:130:47: not enough arguments in call to kubectl.GetCiliumPodOnNode
13:00:33  	have (string)
13:00:33  	want (string, string)
13:00:33  
13:00:33  Ginkgo ran 1 suite in 18.309450923s
13:00:33  Test Suite Failed
```

2020-09-25 14:02 UTC, mrostecki commented
test-backport-1.8

2020-09-25 20:33 UTC, christarazi requested changes

2020-09-25 20:33 UTC, christarazi commented on pkg/k8s/apis/cilium.io/v2/client/register.go
> +		return fmt.Errorf("error occurred waiting for CRD: %w", err)
This is correct. 

What's missing is the removal of the code in `operator/crd_test.go` as seen in the upstream commit.

2020-09-25 20:36 UTC, christarazi approved these changes
Disregard my previous comments, I realized that `operator/crd_test.go` doesn't have any logic related to deleting CRDs. This is good to go for me!

2020-09-26 07:32 UTC, fristonio approved these changes
Looks Good for my changes. Thanks :rocket:

2020-09-28 09:02 UTC, mrostecki commented
Failure is legit, let me fix it.

2020-09-28 15:16 UTC, mrostecki commented
test-backport-1.8

2020-09-28 20:12 UTC, aanm commented
@mrostecki I would suggest to drop the faulty commits so we can merge the other changes.

2020-09-28 20:28 UTC, mrostecki commented
@aanm OK, let's try without #13228.

2020-09-28 20:28 UTC, mrostecki commented
test-backport-1.8

2020-09-28 23:54 UTC, mrostecki commented
test-backport-1.8

2020-09-29 09:21 UTC, mrostecki commented
test-backport-1.8

2020-09-29 10:30 UTC, mrostecki commented
https://jenkins.cilium.io/job/Cilium-PR-Kubernetes-Upstream/2541/console - VM provisioning failed

2020-09-29 10:30 UTC, mrostecki commented
test-backport-1.8

2020-09-29 16:28 UTC, merged