contrib: Automate stable docker image tag updates
cilium/cilium pull request #13364
Opened 2020-10-01 03:15 UTC by joestringer

2020-10-01 07:54 UTC, tklauser approved these changes

2020-10-01 07:56 UTC, Rolinh approved these changes

2020-10-01 07:56 UTC, Rolinh commented on contrib/release/bump-docker-stable.sh
> +    local ersion="$(echo $1 | sed 's/^v//')"
:joy:

2020-10-01 09:37 UTC, aanm requested changes
@joestringer I usually change the build setup on docker hub to build the stable tag the same time we are building a "normal" tag. Isn't that enough?

2020-10-01 17:14 UTC, joestringer commented
@aanm I didn't want to click all the buttons to make that happen :joy: Did we ever figure out a way to automate all the dockerhub UI interactions?

2020-10-01 19:16 UTC, aanm commented
> @aanm I didn't want to click all the buttons to make that happen  Did we ever figure out a way to automate all the dockerhub UI interactions?

Yes, once GH actions are done for `cilium/cilium` we should be good for >=1.9

2020-10-01 20:18 UTC, joestringer commented
@aanm is that tracked somewhere specifically and is it planning to address both the v1.X.Y release image building / triggering as well as updating the `stable` tags? 

If the `stable` tag update will be handled by some other logic for v1.9 then I'll drop this PR.

2020-10-01 20:51 UTC, aanm commented
> @aanm is that tracked somewhere specifically and is it planning to address both the v1.X.Y release image building / triggering as well as updating the `stable` tags?
> 
> If the `stable` tag update will be handled by some other logic for v1.9 then I'll drop this PR.

We'll have to double check this once we have it running

2020-10-23 00:23 UTC, joestringer commented
@aanm oh, I guess there was a disconnect here. I marked this as draft under the assumption it's not necessary at this point. But it also has `priority/release-blocker`. Maybe I'll revert from draft again and we can evaluate whether to accept or just close it out.

2020-10-23 08:49 UTC, aanm commented
@joestringer I might have marked this PR as release-blocker by accident

2020-11-17 19:47 UTC, joestringer commented
@aanm given that we didn't address this for 1.9, would it be worthwhile for me to re-spin this PR to merge? There's now eight different images to configure the build targets on dockerhub each time.

2020-11-18 09:23 UTC, aanm commented
> @aanm given that we didn't address this for 1.9, would it be worthwhile for me to re-spin this PR to merge? There's now eight different images to configure the build targets on dockerhub each time we do a 1.9.x release.

@joestringer it depends, as soon we have the GH actions builds done, we don't need to configure anything on docker hub anymore.

2020-11-18 18:48 UTC, joestringer commented
@aanm that answer has not changed for the last six weeks. Do we have concrete expectations that those steps will occur in the short term? If not, I suggest we merge this as-is and revert whenever that system is fully set up.

2020-11-18 21:51 UTC, aanm commented
> @aanm that answer has not changed for the last six weeks. Do we have concrete expectations that those steps will occur in the short term? If not, I suggest we merge this as-is and revert whenever that system is fully set up.

@joestringer I thought you had to make further changes to this PR if that's not the case I'm fine to merge it as is

2020-11-18 22:32 UTC, joestringer commented
:+1: Just needed a rebase, already done.

2020-11-18 22:33 UTC, merged