bpf: fix typo in IPV4_FRAGMENTS constant
cilium/cilium pull request #13414
Opened 2020-10-05 19:40 UTC by jibi

The IPV4_FRAGMENTS constant should be named ENABLE_IPV4_FRAGMENTS.

Signed-off-by: Gilberto Bertin <gilberto@isovalent.com>

2020-10-05 19:47 UTC, pchaigno requested changes
Thanks for fixing this!

Could you update the title, which will be used in release notes, to clarify the bug that is fixed (i.e., the consequence)?

2020-10-05 20:00 UTC, pchaigno commented
test-me-please

2020-10-06 11:29 UTC, jibi commented
> Thanks for fixing this!
> 
> Could you update the PR title, which will be used in release notes, to clarify the bug that is fixed (i.e., the consequence)?

@pchaigno updated :+1:

2020-10-06 11:46 UTC, pchaigno approved these changes

2020-10-06 20:18 UTC, mrostecki approved these changes

2020-10-06 21:17 UTC, joestringer approved these changes
Nice catch!

2020-10-06 21:17 UTC, merged