helm: renamed podsAnnotations variable into podAnnotations
cilium/cilium pull request #13458
Opened 2020-10-08 10:24 UTC by mvisonneau

This change follows-up onto https://github.com/cilium/cilium/pull/12189#issuecomment-705226944
It concerns the agent and operator charts

2020-10-08 10:38 UTC, sayboras commented
@mvisonneau thanks, seems like this one is coverred in #13259 as well. If it is already, I think we can wait for a little, as #13259 seems pretty closed from my understanding :)

2020-10-08 11:52 UTC, mvisonneau commented
oh cool, sure feel free to do whatever you want with this PR then! :)

2020-10-08 18:17 UTC, dominik318 commented
@sayboras this PR is required for Cilium DataDog integration which is somewhat urgent for many people. It would be fantastic if we could back-port this to 1.8. This PR is fully backwards compatible.

2020-10-08 21:28 UTC, sayboras commented
> this PR is required for Cilium DataDog integration which is somewhat urgent for many people. It would be fantastic if we could back-port this to 1.8. This PR is fully backwards compatible.

Thanks for clarification, I am big fan of of datadog :1st_place_medal:

2020-10-08 21:32 UTC, sayboras commented on install/kubernetes/cilium/charts/agent/templates/daemonset.yaml
> +{{- with .Values.podAnnotations }}{{- toYaml . | nindent 8 }}{{- end }}
Need other to weigh in, as I am not sure how we capture note for upgrad for this changes. Using `--reuse-values` during upgrade might remove existing pod annotations if this field is not explicitly set in `helm upgrade`

2020-10-08 21:55 UTC, christarazi approved these changes
Thanks! We'll need to wait until the big Helm refactor is merged.

@sayboras I think because the original change never made it into a release, we could probably skip mentioning it. It seems like this PR is just amending the previous change. (Unless I've missed something.)

2020-10-08 23:42 UTC, sayboras commented on install/kubernetes/cilium/charts/agent/templates/daemonset.yaml
> +{{- with .Values.podAnnotations }}{{- toYaml . | nindent 8 }}{{- end }}
the above is answered by Chris :)

2020-10-08 23:42 UTC, sayboras approved these changes
LGTM 💯

2020-10-09 12:43 UTC, kAworu requested changes
Here is my understanding:

https://github.com/cilium/cilium/pull/13259 does include this fix, so the issue will be solved as soon as #13259 is merged into master.

There is a need to have this fix in v1.8. Since this PR won't be merged into master, it could be re-targeted to be merged into the v1.8 branch. Alternatively, this PR could be closed and another PR could be opened against v1.8.

2020-10-09 17:16 UTC, joestringer commented
Thanks for clarifying @kAworu , confirmed. @mvisonneau would you mind retargeting these changes for the v1.8 branch?

2020-10-10 21:13 UTC, mvisonneau commented
there you go @joestringer! 🙇

2020-10-12 09:46 UTC, kAworu approved these changes
LGTM, thanks!

2020-10-12 09:47 UTC, Rolinh approved these changes

2020-10-12 10:02 UTC, kAworu commented
test-me-please

2020-10-12 10:58 UTC, gandro approved these changes

2020-10-12 10:59 UTC, gandro commented
test-backport-1.8

2020-10-13 08:52 UTC, merged