Cilium k8s proxy performance
cilium/cilium pull request #135
Opened 2016-09-22 23:25 UTC by aanm

2016-09-23 22:24 UTC, tgraf approved these changes

2016-09-23 22:25 UTC, tgraf commented on daemon/daemon/k8s_watcher.go
> +		if isSvcIPv4 {
You can have a single isSvcIPv4 branch and do the !d.conf.IPv4Enabled check from within

2016-09-23 22:26 UTC, tgraf commented on daemon/daemon/k8s_watcher.go
> +			for epIP := range se.IPs {
You can move this into a function and use it from both branches

2016-09-23 22:27 UTC, tgraf requested changes

2016-09-23 23:40 UTC, aanm commented on daemon/daemon/k8s_watcher.go
> +			for epIP := range se.IPs {
Sorry, that code changed in the last commit. But still applies and I've change it under `areIPsConsistent` function

2016-09-27 07:52 UTC, tgraf approved these changes

2016-09-27 18:10 UTC, merged