pkg/k8s: waiting for k8s to be ready on create
cilium/cilium pull request #1350
Opened 2017-08-23 00:35 UTC by aanm

Signed-off-by: André Martins <andre@cilium.io>

2017-08-23 01:46 UTC, ianvernon approved these changes

2017-08-23 02:11 UTC, tgraf requested changes

2017-08-23 02:11 UTC, tgraf commented on pkg/k8s/client.go
> +func IsReady(c *kubernetes.Clientset) error {
Does this function need to be exported?

2017-08-24 15:05 UTC, aanm commented on pkg/k8s/client.go
> +func IsReady(c *kubernetes.Clientset) error {
No, fixed

2017-08-24 15:24 UTC, tgraf approved these changes

2017-08-24 18:19 UTC, merged