identity: Fix nil pointer panic in LookupIdentityByID
cilium/cilium pull request #13514
Opened 2020-10-12 16:20 UTC by gandro

Because the identity allocator is initialized asynchronously via
`InitIdentityAllocator`, its internal local identitiy allocator might
not have been initialized yet when the lookup functions are called.
This can cause nil pointer panics, as observed in #13479.

Before b194612c004c3e69289286e9a35d337b2645fc50, this nil pointer panic could not occur in
`LookupIdentityByID` as the function checked for `m.IdentityAllocator != nil`
which also implies `m.localIdentities != nil`.
This commit adds an explict check for `m.localIdentities`.

Fixes: #13479
Fixes: b194612c004c ("identity: Avoid kvstore lookup for local identities")

Signed-off-by: Sebastian Wicki <sebastian@isovalent.com>

---

Note: While the backported version of b194612c004c in v1.7 and v1.8 does not suffer from the nil pointer panic due to an early check fo `m.IdentityAllocator != nil` , I think we should still back-port this to fix the potential nil-pointer panic in `LookupIdentity` which is also fixed by this commit.

2020-10-12 16:20 UTC, gandro commented
test-me-please

2020-10-12 16:26 UTC, aanm requested changes
@gandro why don't we need to wait before the variable is assigned with the `<-m.localIdentityAllocatorInitialized`?

2020-10-12 16:47 UTC, gandro commented
> @gandro why don't we need to wait before the variable is assigned with the `<-m.localIdentityAllocatorInitialized`?

Fair point. My thinking was that I would restore the behavior present in 1.7/1.8. But assuming there are no issues with deadlocks, I guess we could rely on `m.localIdentityAllocatorInitialized` instead. I'll update the PR.

2020-10-12 19:29 UTC, aanm commented
> > @gandro why don't we need to wait before the variable is assigned with the `<-m.localIdentityAllocatorInitialized`?
> 
> Fair point. My thinking was that I would restore the behavior present in 1.7/1.8. But assuming there are no issues with deadlocks, I guess we could rely on `m.localIdentityAllocatorInitialized` instead. I'll update the PR.
> 
> Edit: Overall, I don't think waiting on `m.localIdentityAllocatorInitialized` will change anything however. Once it becomes ready, the local identity cache will be empty, so it will also return simply nil.

@gandro the race detector will complain that we are accessing the variable concurrently :smile:

2020-10-13 14:39 UTC, gandro commented
@aanm PTAL again. After looking a bit more closely at initialization, I decided to do a non-blocking check on the channel. This ensures that we have proper synchronization point to avoid data races. In the process, I found some additional potential data races and nil pointer panics that I fixed.

I decided to fail the lookup instead of waiting for the caches to be initialized. If we wait for full initialization including synchronization, then both the DNS Proxy ([call site](https://github.com/cilium/cilium/blob/5590bf464ab45fc395c9a8c65ca51f7ce58787e9/daemon/cmd/fqdn.go#L471)) and Hubble ([call site](https://github.com/cilium/cilium/blob/8a1d6d09937bdc2edd76771ffce73f59fdaa316c/daemon/cmd/hubble.go#L224)) would not be operational until we have synchronized the identity cache. I don't think we want that.

If callers need to perform a lookup on a synchronized cache, they should call `WaitForInitialGlobalIdentities` first.

2020-10-13 14:41 UTC, gandro commented
test-me-please

2020-10-14 08:26 UTC, gandro commented
GKE hit a flake `"could not get service LoadBalancer IP addr: 30s timeout expired"` https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/2802/

This does not seem related

2020-10-14 08:26 UTC, gandro commented
test-gke

2020-10-14 10:42 UTC, gandro commented
Hit #13554 twice

2020-10-15 08:33 UTC, gandro commented
Rebased to pick up the fix the the GKE flake this observed. Rerunning CI

2020-10-15 08:33 UTC, gandro commented
test-me-please

2020-10-15 11:20 UTC, gandro commented
netnext hit #13261

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/866/testReport/junit/Suite-k8s-1/12/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_NodePort_with_Maglev_Tests_NodePort/

2020-10-15 11:20 UTC, gandro commented
retest-net-next

2020-10-15 13:02 UTC, aanm approved these changes

2020-10-15 14:44 UTC, gandro commented
Potentially new net-next flake? https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/872/testReport/junit/Suite-k8s-1/12/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_NodePort_with_Maglev_Tests_NodePort/

2020-10-15 14:44 UTC, gandro commented
retest-net-next

2020-10-15 17:26 UTC, merged