k8s/watches: fix data race in (*K8sWatcher).addK8sServiceV1
cilium/cilium pull request #13604
Opened 2020-10-16 14:40 UTC by tklauser

Access to k.podStore must be protected by k.podStoreMU.

Closes #13603

Fixes: e7bb8a7eadb5 ("k8s/cilium Event handlers and processing logic for LRPs")

2020-10-16 14:44 UTC, tklauser commented
test-me-please

2020-10-16 14:52 UTC, tklauser commented
test-race-4.9

2020-10-16 15:00 UTC, aanm requested changes
@tklauser I'm fine with the changes but this should not be the real fix. This code architecture should be done differently as well.

@aditighag `k.podStore` should to be passed for every k8s service add, we should register a store in https://github.com/cilium/cilium/blob/e91f803c360484dc109eb0d18badc1afa92d457f/daemon/cmd/daemon.go#L367 and use it as follow. 

```patch
diff --git a/daemon/cmd/daemon.go b/daemon/cmd/daemon.go
index 8c334acaa..faae4336b 100644
--- a/daemon/cmd/daemon.go
+++ b/daemon/cmd/daemon.go
@@ -365,6 +365,7 @@ func NewDaemon(ctx context.Context, epMgr *endpointmanager.EndpointManager, dp d
        )
 
        d.redirectPolicyManager.RegisterSvcCache(&d.k8sWatcher.K8sSvcCache)
+       d.redirectPolicyManager.RegisterGetStores(&d.k8sWatcher)
 
        bootstrapStats.daemonInit.End(true)
 
diff --git a/pkg/redirectpolicy/manager.go b/pkg/redirectpolicy/manager.go
index 5213fcb30..bfce4b013 100644
--- a/pkg/redirectpolicy/manager.go
+++ b/pkg/redirectpolicy/manager.go
@@ -65,6 +65,8 @@ type Manager struct {
 
        svcCache svcCache
 
+       storeGetter StoreGetter
+
        // Mutex to protect against concurrent access to the maps
        mutex lock.Mutex
 
@@ -95,6 +97,14 @@ func (rpm *Manager) RegisterSvcCache(cache svcCache) {
        rpm.svcCache = cache
 }
 
+type StoreGetter interface {
+       GetStore(name string) cache.Store
+}
+
+func (rpm *Manager) RegisterGetStores(sg StoreGetter) {
+       rpm.storeGetter = sg
+}
+
 // Event handlers
 
 // AddRedirectPolicy parses the given local redirect policy config, and updates
@@ -503,12 +513,13 @@ func (rpm *Manager) upsertService(config *LRPConfig, frontendMapping *feMapping)
 }
 
 // Returns a slice of endpoint pods metadata that are selected by the given policy config.
-func (rpm *Manager) getLocalPodsForPolicy(config *LRPConfig, podStore cache.Store) []*podMetadata {
+func (rpm *Manager) getLocalPodsForPolicy(config *LRPConfig) []*podMetadata {
        var (
                retPods []*podMetadata
                podData *podMetadata
        )
 
+       podStore := rpm.storeGetter.GetStore("pod")
        for _, podItem := range podStore.List() {
                pod, ok := podItem.(*slimcorev1.Pod)
                if !ok || !config.checkNamespace(pod.GetNamespace()) {

```

2020-10-19 09:49 UTC, tklauser commented
test-me-please

2020-10-19 09:50 UTC, tklauser commented
Updated as per @aanm's suggestion (https://github.com/cilium/cilium/pull/13604#pullrequestreview-510554177), see commit ea208e7d1796c38163de1ae35c488b1f08967878

2020-10-19 16:03 UTC, christarazi approved these changes
Minor nit

2020-10-19 16:03 UTC, christarazi commented on pkg/redirectpolicy/manager_test.go
> +	"k8s.io/client-go/tools/cache"
Nit: import ordering

2020-10-19 16:36 UTC, aanm approved these changes

2020-10-19 16:36 UTC, aanm commented
test-me-please

2020-10-20 09:10 UTC, merged

2020-10-20 16:10 UTC, aditighag commented
Thanks for fixing this, @tklauser and @aanm.