Pr/v1.7 backport 2020-10-20
cilium/cilium pull request #13656
Opened 2020-10-21 00:54 UTC by nathanjsweet

v1.7 backports 2020-10-20

 * #13295 -- test: Debug RuntimeConntrackInVethModeTest flake (@pchaigno)
 * #13640 -- docs: Document some caveats of kube-proxy replacement (@brb)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 13295 13640; do contrib/backporting/set-labels.py $pr done 1.7; done
```

2020-10-21 00:55 UTC, nathanjsweet commented
test-backport-1-7

2020-10-21 00:56 UTC, nathanjsweet commented
I initiated the tests, because I want to see if we can catch the [conntrack test bug](https://github.com/cilium/cilium/issues/12891)

2020-10-21 03:10 UTC, joestringer commented
test-backport-1.7

2020-10-21 07:09 UTC, pchaigno requested changes

2020-10-21 07:09 UTC, pchaigno commented on Documentation/gettingstarted/kubeproxy-free.rst
> +    * "eBPF as a revolutionary technology for the container landscape" (Fosdem 2020, `slides
The builds are failing because you'll need to run `Documentation/update-spelling_wordlist.sh DSR Fosdem` for these doc changes.

2020-10-21 07:09 UTC, pchaigno commented on Documentation/gettingstarted/kubeproxy-free.rst
> +************************
This doesn't look right. See https://docs.cilium.io/en/latest/gettingstarted/kubeproxy-free/#hybrid-mode.

2020-10-21 13:35 UTC, brb reviewed
Let's drop #13640, as it is causing too many changes being pulled in. The doc change will be available for the v1.8 and v1.9 pages anyway.

2020-10-21 17:10 UTC, pchaigno approved these changes
LGTM! Thanks @nathanjsweet!

2020-10-21 17:10 UTC, pchaigno commented
test-backport-1.7

2020-10-22 17:31 UTC, nathanjsweet commented
test-backport-1.7

2020-10-22 22:03 UTC, joestringer commented
Cluster setup for upstream tests seems to have failed:

https://jenkins.cilium.io/job/Cilium-PR-Kubernetes-Upstream/2612/execution/node/46/log/

will re-kick.

2020-10-22 22:03 UTC, joestringer commented
test-upstream-k8s

2020-10-22 23:23 UTC, merged