Fix logging bug
cilium/cilium pull request #13754
Opened 2020-10-26 14:17 UTC by manuelbuil

Signed-off-by: Manuel Buil <mbuil@suse.com>

Please ensure your pull request adheres to the following guidelines:

- [X] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [X] All code is covered by unit and/or runtime tests where feasible.
- [X] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [X] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [X] Provide a title or release-note blurb suitable for the release notes.
- [X] Thanks for contributing!

When executing ginkgo according to the instructions: https://docs.cilium.io/en/v1.9.0-rc2/contributing/testing/e2e/#running-end-to-end-tests-in-other-environments-via-ssh, something was not working and the only output I was getting was:

`FAIL: Cannot connect to vmName  'k8s1-1.18'`

After changing the logs using this patch, I could see that the real error was:

`cat: ssh-config: No such file or directory`

It seems that `fmt.Fprintf(&logger.TestLogWriter...` function does not print the logs anywhere as I could not see that message in the output

2020-10-26 16:53 UTC, christarazi requested changes
Thanks for the PR! Could you add the context in the commit itself?

2020-10-29 09:30 UTC, aanm commented
ping @manuelbuil

2020-10-29 12:00 UTC, manuelbuil commented
> Thanks for the PR! Could you add the context in the commit itself?

I was executing things by following this ==> https://docs.cilium.io/en/v1.8/contributing/testing/e2e/#running-end-to-end-tests-in-other-environments-via-ssh because I already had VMs in place. I am using cilium/master

I asked in Slack and I was told that ginkgo is supposed to be used in CI and possibly this "running-end-to-end-tests-in-other-environments-via-ssh" is not really supported. If I wanted to test my env, I should use: https://docs.cilium.io/en/latest/gettingstarted/k8s-install-connectivity-test/. If that is the case maybe I should close this PR, can you confirm that?

If not, any more context information you might need? Thanks!

2020-10-29 20:32 UTC, christarazi commented
> > Thanks for the PR! Could you add the context in the commit itself?
> 
> I was executing things by following this ==> https://docs.cilium.io/en/v1.8/contributing/testing/e2e/#running-end-to-end-tests-in-other-environments-via-ssh because I already had VMs in place. I am using cilium/master
> 
> I asked in Slack and I was told that ginkgo is supposed to be used in CI and possibly this "running-end-to-end-tests-in-other-environments-via-ssh" is not really supported. If I wanted to test my env, I should use: https://docs.cilium.io/en/latest/gettingstarted/k8s-install-connectivity-test/. If that is the case maybe I should close this PR, can you confirm that?
> 
> If not, any more context information you might need? Thanks!

Ah, sorry. I meant, to request adding the context that you provided in the PR description in the commit body itself. The reason is because the commit title `Fix logging bug` doesn't provide enough context as to what was wrong and why the commit is needed, but your PR description does.

2020-10-30 15:02 UTC, mrostecki requested changes
@manuelbuil I think putting pretty much what you have in the PR description into the commit message (while wrapping it to 72 chars per line and use the 3rd person neutral pronouns instead of the 1st person pronouns) and changing the title to more descriptive (and including the subsystem in it) would be enough. Like, for example:


```
test: Switch from Cilium test logger to Ginkgo logger

When executing ginkgo according to the instructions[0], the only error
output was:

  FAIL: Cannot connect to vmName 'k8s1-1.18'

After this change, the logs show the underlying error:

  cat: ssh-config: No such file or directory

[0] https://docs.cilium.io/en/v1.8/contributing/testing/e2e/#running-end-to-end-tests-in-other-environments-via-ssh

Signed-off-by: Manuel Buil <mbuil@suse.com>
```

Or maybe even without the link.

2020-11-06 22:15 UTC, christarazi approved these changes

2020-11-08 14:44 UTC, mrostecki approved these changes

2020-11-09 09:02 UTC, aanm commented
test-me-please

2020-11-11 10:07 UTC, merged