cilium/cmd: Replace exit code -1 with exit code 1
cilium/cilium pull request #13761
Opened 2020-10-26 15:32 UTC by twpayne

In two cases, cilium could exit with code -1, which gets converted to
255. Instead, always exit with code 1 in the event of failure. Also,
remove an unnecessary os.Exit(0).

2020-10-26 18:33 UTC, christarazi approved these changes

2020-10-27 07:20 UTC, fristonio approved these changes
LGTM, thanks :rocket:

2020-10-27 07:37 UTC, sayboras reviewed
Maybe for a few more cases if you want, a quick ripgrep shows below output.

```shell script
$ rg "os.Exit\(-1\)"
operator/main.go
75:                             os.Exit(-1)
160:            os.Exit(-1)

cilium-health/cmd/root.go
54:     os.Exit(-1)
62:             os.Exit(-1)

cilium-health/responder/main.go
65:                     os.Exit(-1)

daemon/cmd/daemon_main.go
118:                            os.Exit(-1)
151:            os.Exit(-1)

plugins/cilium-docker/main.go
72:             os.Exit(-1)

test/test_suite_test.go
52:             os.Exit(-1)
```

2020-10-29 09:36 UTC, aanm commented
test-me-please

2020-11-09 11:10 UTC, kAworu requested changes
LGTM once the instances found by @sayboras get fixed as well for consistency's sake

2020-11-09 12:57 UTC, twpayne commented
> LGTM once the instances found by @sayboras get fixed as well for consistency's sake

This is done in #13798.

2020-11-10 09:59 UTC, kAworu approved these changes

2020-11-10 10:03 UTC, kAworu commented
let's wait on the next release (see https://github.com/cilium/cilium/pull/13798#issuecomment-718557055) before merging this.

2020-11-11 09:57 UTC, merged