k8s: clarify CRD schema versioning and its update process
cilium/cilium pull request #13811
Opened 2020-10-29 21:45 UTC by aanm

Add steps on and when the CRD validation version should be updated.

Signed-off-by: André Martins <andre@cilium.io>

Related with https://github.com/cilium/cilium/issues/12737

2020-10-30 09:20 UTC, kkourt approved these changes
LGTM.

2020-10-30 09:20 UTC, kkourt commented on Documentation/concepts/kubernetes/compatibility.rst
> +The following table lists all Cilium Versions and their expected schema
nit: s/Versions/versions/

2020-10-30 09:20 UTC, kkourt commented on Documentation/check-compat-table.sh
> +#!/usr/bin/env bash
Renaming this to `check-crd-compat-table.sh` might make it's function more clear. Not a big issue, though, since the script is documented elsewhere.

2020-10-30 14:56 UTC, ti-mo approved these changes

2020-10-30 18:01 UTC, christarazi requested changes
I tried it out and the script seems to work. Will the script detect if there's changes to the CRD and suggest bumping the version? Or, is it more like if we've made a change to the CRD schema, then we add an entry to the table, _then_ at release time, the process would be to run the script to see if the schema version bump matches with the expected value in the table?

A few comments below to help clarity.

2020-10-30 18:01 UTC, christarazi commented on Documentation/contributing/release/feature.rst
> +   the ``pkg/k8s/client`` by following these instructions:
I think you mean to say to check the `CustomResourceDefinitionSchemaVersion` inside `pkg/k8s/apis/cilium.io/v2/register.go`, correct? There's no reference to the schema version inside `pkg/k8s/client.go`.

2020-10-30 18:01 UTC, christarazi commented on Documentation/contributing/release/rc.rst
> +   If you are doing the first RC for a new minor version the validation schema
```suggestion
   If you are doing the first RC for a new minor version, the validation schema
```

2020-10-30 18:01 UTC, christarazi commented on Documentation/contributing/release/rc.rst
> +   ``CustomResourceDefinitionSchemaVersion``.
I am confused by this. My reading is if we are about to create a new RC, for ex. 1.10-rc1, then the validation schema version should be `v1.10.1`?  Surely, that's not what you meant, but that's how it reads. I assume you mean the schema version minor should be incremented and the patch version should be `1`.

I think in general giving an example of what you mean here will greatly clarify things.

2020-10-30 18:01 UTC, christarazi commented on Documentation/contributing/release/rc.rst
> +   maximum of +1 patch versions in case there were CRD changes.
This is slightly confusing to me too. I think you mean this and correct me if I'm wrong:

```suggestion
   If a branch for ``vX.Y`` doesn't exist yet, then ensure the CRD schema version has not been incremented in the case there were no changes. If there were changes to the CRD, then ensure it is incremented at most by 1 patch version.
```

2020-10-30 18:01 UTC, christarazi commented on Documentation/check-crd-compat-table.sh
> +    echo "Run the following command to fix it:"
```suggestion
    echo "Current version for branch ${release_version} should be ${expected_version}, not ${current_release_version}, please run the following command to fix it:"
```

2020-11-02 09:14 UTC, aanm commented on Documentation/contributing/release/feature.rst
> +   the ``pkg/k8s/client`` by following these instructions:
Actually it was suppose to be `pkg/k8s/...` since we have moved the file around in different Cilium versions.

2020-11-02 09:16 UTC, aanm commented
@christarazi 

> I tried it out and the script seems to work. Will the script detect if there's changes to the CRD and suggest bumping the version? 

No, the script will detect if there are changes to the CRD schema version and suggest to increment at maximum of 1 patch version per Cilium patch version released.

>Or, is it more like if we've made a change to the CRD schema, then we add an entry to the table, _then_ at release time, the process would be to run the script to see if the schema version bump matches with the expected value in the table?

Correct.

2020-11-02 18:32 UTC, christarazi commented on Documentation/contributing/release/feature.rst
> +   the ``pkg/k8s/client`` by following these instructions:
Makes sense. I don't see the change made. Maybe you forgot to change it to `pkg/k8s/...`?

2020-11-02 18:32 UTC, christarazi approved these changes
LGTM pending https://github.com/cilium/cilium/pull/13811#discussion_r516176561

2020-11-02 19:58 UTC, aanm commented on Documentation/contributing/release/feature.rst
> +   the ``pkg/k8s/client`` by following these instructions:
@christarazi GH doesn't update this section. You need to check the file again. (it is already changed)

2020-11-02 21:01 UTC, joestringer approved these changes
I'm going to want to automate this so it's not an extra manual step, but this is good for now.

2020-11-02 21:01 UTC, merged