operator: wait for endpoints to sync to use cache
cilium/cilium pull request #13823
Opened 2020-10-30 23:02 UTC by dctrwatson

Wait for endpoints to sync before marking the k8s service cache as synced.

Otherwise the custom dialer for etcd may hit its deadline while waiting to take a RLock on the global service cache because endpoints are still being updated.

Fixes: #13454

2020-10-30 23:03 UTC, dctrwatson commented
This works for both v1.7.11 and v1.8.5

2020-11-02 09:44 UTC, aanm requested changes
I can't understand how the code change helps to fix the issue. Did you add log messages before and after acquiring the `s.mutex` in the `GetServiceIP` function? How many k8s endpoints do you have in total?

The `s.mutex` is acquired for each new k8s endpoint event received so the `GetServiceIP` would have the opportunity to get a `RLock` of that mutex

2020-11-02 18:17 UTC, dctrwatson commented
> I can't understand how the code change helps to fix the issue. Did you add log messages before and after acquiring the `s.mutex` in the `GetServiceIP` function? How many k8s endpoints do you have in total?

Yeah, I went with the quick route of adding log messages everywhere. And yeah, GetServiceIP would just get stuck at trying to acquire the lock which is could never do before the grpc deadline.

Not _that_ many endpoints, 145 in the cluster that's constantly exhibiting this behavior. Unfortunately, it's EKS so the apiserver is a bit of blackbox.

> The `s.mutex` is acquired for each new k8s endpoint event received so the `GetServiceIP` would have the opportunity to get a `RLock` of that mutex

Yeah, that was my intuition too, so it was the last thing I was going to look at just using log messages, heh

2020-11-03 09:44 UTC, aanm commented
@dctrwatson was the code blocked here? https://github.com/cilium/cilium/blob/71b4fb5616248ebdac58a9856b5cab381b15e517/pkg/k8s/service_cache.go#L114

Can you take a `gops stack <cilium-operator-pid>`?

2020-11-09 10:53 UTC, aanm commented
@dctrwatson any update?

2020-11-09 19:10 UTC, dctrwatson commented
> @dctrwatson any update?

Sorry, I got side-tracked last week. I'll get a stack today

2020-11-10 07:51 UTC, dctrwatson commented
Well this is disappointing...

Nothing has changed but it's no longer exhibiting this behavior with 1.7.11 or 1.8.5

Since this is in EKS, I can't for sure nothing has changed in etcd/apiserver

2020-11-18 23:07 UTC, dctrwatson commented
The issue is no longer occurring so this wasn't necessary anyway

2020-11-18 23:07 UTC, closed without merging