docs: add info about tailcalls in bpf subprograms
cilium/cilium pull request #13888
Opened 2020-11-04 02:03 UTC by mfijalko

Here is an update to Cilium's documentation in order to reflect the current state of relationship between bpf2bpf calls and tail calls.
I tried to mimic as much as I could the style of provided image so that it follows all of the existing images.

Thanks!

2020-11-04 07:55 UTC, borkmann commented on Documentation/bpf.rst
> +programs that utilized tail calls couldn't take the benefit of shrinked program
nit: `benefit of shrinked program` -> `benefit of reducing program image size`

2020-11-04 07:57 UTC, borkmann commented on Documentation/bpf.rst
> +programs that utilized tail calls couldn't take the benefit of shrinked program
Please also run `./Documentation/update-spelling_wordlist.sh func unwinded` so the latter two get added to the word list and don't cause doc CI failure. Thanks for extending the doc!

2020-11-04 11:09 UTC, fristonio requested changes
Thanks for the PR :rocket: 
Some minor improvements.

2020-11-04 11:09 UTC, fristonio commented on Documentation/bpf.rst
> +calls.
```suggestion
images and faster load times. Linux kernel 5.10 finally allows users to bring the best of two worlds and adds the ability to combine the BPF subprograms with tail calls.
```

2020-11-04 11:09 UTC, fristonio commented on Documentation/bpf.rst
> +could cause kernel stack overflow. To get an idea of what might happen, see the
```suggestion
This improvement comes with some restrictions, though. Mixing these two features
can cause a kernel stack overflow. To get an idea of what might happen, see the
```

2020-11-04 11:09 UTC, fristonio commented on Documentation/bpf.rst
> +control will get back to the caller of BPF program.
```suggestion
Tail calls, before the actual jump to the target program, will unwind only its
current stack frame. As we can see in the example above, if a tail call occurs
from within the sub-function, the functions' (func1) stack frame will be
present on the stack when program execution is at func2. Once the final function(func3)
terminates, all the previous stack frames will be unwinded, and
control will get back to the BPF program caller.
```

2020-11-04 11:09 UTC, fristonio commented on Documentation/bpf.rst
> +supported only on x86-64 architecture.
How about rewording this to something like?
```
The kernel introduced additional logic for detecting this feature combination.
There is a limit on the stack size throughout the whole call chain down to 256 bytes
per subprogram (note that if the verifier detects the bpf2bpf call, then the main
function is treated as a sub-function as well). In total, with this restriction,
the BPF program's call chain can consume at most 8KB of stack space.
This limit comes from the 256 bytes per stack frame multiplied by the tail call count limit(32).
Without this, the BPF programs will operate on 512-byte stack size, yielding the
16KB size in total for the maximum count of tail calls that would overflow the
stack on some architectures.
One more thing to mention is that this feature combination is currently supported only on the x86-64 architecture.
```

2020-12-10 19:55 UTC, joestringer commented
@mfijalko thanks again for the submission :-) I've converted the PR to draft status for now. When you get a chance to address the review feedback, then please force-push the updated branch back here and mark the PR as "Ready for review" using the button at the bottom of the page.

2020-12-10 22:43 UTC, mfijalko commented
> @mfijalko thanks again for the submission :-) I've converted the PR to draft status for now. When you get a chance to address the review feedback, then please force-push the updated branch back here and mark the PR as "Ready for review" using the button at the bottom of the page.

Ugh, sorry, that's embarrassing. Shortly after initial pull request submission I caught covid and totally forgot about that. Thanks for review, I'll try address comments in a day or two.

2020-12-10 23:24 UTC, joestringer commented
@mfijalko No worries at all. I hope you're feeling better now :slightly_smiling_face:

2020-12-17 11:37 UTC, mfijalko commented
Not sure if it's my fault that conformance test failed, but anyway I tried to address all of the review comments. Not sure where should I place versioning in github flow, commit message?

Anyway, hitting the 'ready for review' button.

2020-12-17 14:00 UTC, borkmann approved these changes

2020-12-17 16:01 UTC, fristonio approved these changes
LGTM :rocket: 
Thanks for sending out the PR.

2020-12-17 16:18 UTC, merged