helm/hubble-relay: fixed indentation error
cilium/cilium pull request #14029
Opened 2020-11-14 05:54 UTC by PranaviRoy

Signed-off-by: Pranavi Roy <pranvyr@gmail.com>

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

Previously, customizing resources for hubble-relay-deployment via helm produced validation errors due to smaller indentation width. This PR increases the indentation width by 2, so as to not write the resource requests on the same level as 'resources'.

Also, couldn't find similar instance anywhere else XD

Fixes: #14000

2020-11-14 06:04 UTC, michi-covalent approved these changes

2020-11-14 06:47 UTC, sayboras approved these changes
LGTM :100:

2020-11-14 07:17 UTC, sayboras commented
I don't think full CI will be required, otherwise this issue would have caught before.

2020-11-16 09:41 UTC, kAworu requested changes
Hey @PranaviRoy, nice catch thanks for the contribution! The diff looks good, but I have a request:

On your way, could you fix `hubble.relay.resources` in the _value.yaml_ file please? It is currently duplicated, see [here](https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/values.yaml#L540-L541) and [here](https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/values.yaml#L554-L562). In my opinion we can simply remove the latter as it seems to be a copy of the hubble-ui section.

2020-11-16 10:36 UTC, PranaviRoy commented
Hi @kAworu, sure!

2020-11-16 11:06 UTC, PranaviRoy commented
@kAworu, should I uncomment this line ??https://github.com/cilium/cilium/blob/c158fb169742923d7e97b52fde98388198be8ada/install/kubernetes/cilium/values.yaml#L541

2020-11-16 11:30 UTC, kAworu commented
> @kAworu, should I uncomment this line ??
> 
> https://github.com/cilium/cilium/blob/c158fb169742923d7e97b52fde98388198be8ada/install/kubernetes/cilium/values.yaml#L541

Yes please. Both cases yield the same helm output, but uncommenting it would make it consistent with the others `resources` we have in _values.yml_ (top-level, hubble-ui, and so on).

2020-11-16 12:27 UTC, kAworu approved these changes
Patch LGTM thanks! If you could squash the commits it would be great, not critical though.

2020-11-17 20:36 UTC, merged