helm: 'bpf.ctTcpMax' and 'bpf.ctAnyMax' need to be strings, not integers
cilium/cilium pull request #14021
Opened 2020-11-13 12:10 UTC by mvisonneau

Make it more evident for end users by amending the comment regarding how to configure `bpf.ctTcpMax` and `bpf.ctAnyMax`

Helm release would succeed if integers are provided but the Cilium agents would then crash.

2020-11-13 12:53 UTC, aanm requested changes
Can you clarify why `lbMapMax` does not require the integer to be quoted for example?

2020-11-13 14:26 UTC, mvisonneau commented
> Can you clarify why `lbMapMax` does not require the integer to be quoted for example?

actually it could be related to using `| quote` [ctAnyMax](https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/templates/cilium-configmap.yaml#L250) vs `{{ }}` [lbMapMax](https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/templates/cilium-configmap.yaml#L271)

I will give it a try

2020-11-13 14:28 UTC, mvisonneau commented
indeed:

```
-   bpf-ct-global-tcp-max: "2097152"
-   bpf-ct-global-any-max: "1048576"
+   bpf-ct-global-tcp-max: "2.097152e+06"
+   bpf-ct-global-any-max: "1.048576e+06"
```

I assume that the agent is not happy about the scientific syntax.

2020-11-16 12:01 UTC, aanm requested changes
So for consistency we should quote all numbers? @mvisonneau

2020-11-16 13:09 UTC, mvisonneau commented
I tried to find a way to update the chart templating logic to be able to leverage numbers but I did not manage to get it to work yet. I believe that it would be interesting to stick to the actually expected type by default but at the same time, current implementation prevents it. Lets perhaps merge this one and create a follow-up issue to figure out what to do with this problem 🤔

2020-12-10 19:57 UTC, joestringer commented
@aanm what do you think of @mvisonneau 's proposal above? If we're fine to merge this as-is, it will need a rebase.

2020-12-10 20:21 UTC, aanm approved these changes
@joestringer LGTM

2020-12-10 20:30 UTC, joestringer approved these changes
:+1: just needs to be rebased.

2020-12-11 06:10 UTC, christarazi approved these changes

2020-12-11 17:27 UTC, mvisonneau commented
rebased! 👍

2020-12-14 08:18 UTC, kAworu requested changes
Helm doc failure from the CI pipeline is legit, @mvisonneau please run `make -C install/kubernetes docs`.

2020-12-15 10:59 UTC, mvisonneau commented
ah right! I rebased again and ran the formatting command 👍, sorry about that

2020-12-15 12:34 UTC, kAworu requested changes
@mvisonneau Thanks! Marking this as `ready-to-merge` as it doesn't warrant a full CI run.

2020-12-15 12:34 UTC, kAworu approved these changes
@mvisonneau Thanks! Marking this as `ready-to-merge` as it doesn't warrant a full CI run.

2020-12-15 22:36 UTC, merged