cocinelle: add git and golang to Dockerfile
cilium/cilium pull request #14039
Opened 2020-11-16 11:20 UTC by kAworu

_bpf/Makefile_ include _Makefile.defs_ which call both go and git. Before this patch in the `coccicheck` GitHub action we have:

    make: Entering directory '/github/workspace/bpf'
    /bin/bash: git: command not found
    /bin/bash: go: command not found
    expr: syntax error

Update to alpine-3.12 and Python 3 on the way.

2020-11-16 11:25 UTC, kAworu commented
Question: should we switch the `cilium/coccicheck` image to quay.io on the way?

2020-11-16 11:53 UTC, aanm commented
> Question: should we switch the `cilium/coccicheck` image to quay.io on the way in order to avoid the rate-limit issue we have with docker.io?

@kAworu The rate limit should be solved now since we have added, 1 hour ago, an account to our docker team to avoid us being rate limited.

2020-11-16 12:09 UTC, pchaigno requested changes
To use this, we will need to push the new image (`cilium/coccicheck:v2.0`?) and update the corresponding GitHub action.

That said, I'm not sure this is the best way to proceed. The errors you noted are actually just warnings and don't prevent the check from running. IIRC, we get those warnings because of how our Makefiles are defined. We should probably find a way to remove those warnings rather than using a bigger image.

2021-01-05 11:33 UTC, kaworu commented
Discussed with @pchaigno offline; abandonning this PR and will create a new one with only the python and alpine update.

2021-01-05 11:33 UTC, closed without merging