pkg/logging: Init klog with flag set name
cilium/cilium pull request #14346
Opened 2020-12-10 07:51 UTC by fafucoder

Previously, klog init flag with nil by using default flag commandline, if other operator
init flag by nil will result in flag log_dir redefined errors.

This commit resolved the log_dir flag redefined problem by instantiating flag.NewFlagSet

Fixes: #14317
Signed-off-by: André Martins <andre@cilium.io>

2020-12-10 09:13 UTC, tklauser commented
> Signed-off-by: André Martins [andre@cilium.io](mailto:andre@cilium.io)

@fafucoder: Thanks for sending the PR. One remark regarding the `Signed-off-by` line: this should have your name and e-mail (also in the commit message), not the one from André. See https://docs.cilium.io/en/v1.9/contributing/development/contributing_guide/#dev-coo for more information.

2020-12-10 09:21 UTC, aanm requested changes
LGTM besides the sign-off email

2020-12-11 01:37 UTC, fafucoder commented
@tklauser Thanks for reminding

2020-12-11 10:13 UTC, twpayne approved these changes
LGTM

2020-12-11 10:17 UTC, tklauser approved these changes
Thanks @fafucoder

2020-12-11 10:18 UTC, tklauser commented
test-me-please

2020-12-11 18:25 UTC, aanm approved these changes

2020-12-11 18:25 UTC, aanm commented
retest-gke

2020-12-11 18:25 UTC, aanm commented
retest-4.9

2020-12-11 18:25 UTC, aanm commented
retest-runtime

2020-12-17 11:57 UTC, merged