pkg/node: only require external IPv4 address if ipv4 mode is enabled
cilium/cilium pull request #14385
Opened 2020-12-12 17:26 UTC by aanm

The external IPv4 node address is not required in IPv6 since we don't have
tunneling for IPv6 mode.

Fixes: 0c22956df3f1 ("node: Only require external IPv4 node address when IPv4 or encapsulation is enabled")
Signed-off-by: André Martins <andre@cilium.io>

```release-note
Allow execution of Cilium in IPv6 only mode regardless of the tunneling mode set
```

2020-12-12 17:26 UTC, aanm commented
test-me-please

2020-12-14 14:11 UTC, aanm commented
retest-gke

2020-12-14 14:27 UTC, tgraf approved these changes

2020-12-14 14:29 UTC, tgraf requested changes
I think the condition is correct.

When running with IPv6 + Encap, the other header is IPv4. So we can only skip this check if:

```
if !(option.Config.EnableIPv6 && option.Config.Tunnel == option.TunnelDisabled))
```

The current code is just a different version of that

2020-12-14 16:45 UTC, aanm commented
The code is behaving correctly. In IPv6-only mode, the user can still have tunneling if the underlay has IPv4. If the user has a IPv6-only cluster he needs to set `--tunnel=disabled`.

2020-12-14 16:45 UTC, closed without merging