Synchronize compilation of base, endpoint programs
cilium/cilium pull request #1440
Opened 2017-08-30 15:27 UTC by ianvernon

Add a new mutex for the daemon, compilationMU, which is Locked when the
daemon's base programs are being compiled. This mutex is RLocked when
endpoints are having their BPF programs generated.

Signed-off by: Ian Vernon <ian@covalent.io>

2017-08-30 16:11 UTC, tgraf requested changes

2017-08-30 16:11 UTC, tgraf commented on daemon/daemon.go
> +	compilationMU *sync.RWMutex
I don't like this `MU` notion. Can we just call it `compilationMutex`.

2017-08-30 16:24 UTC, aanm approved these changes

2017-08-30 18:13 UTC, tgraf approved these changes

2017-08-30 22:22 UTC, tgraf requested changes
Revoking approval until real CI failure is fixed

2017-08-31 14:11 UTC, ianvernon commented
@tgraf sorry about that. CI is passing now.

2017-08-31 14:34 UTC, tgraf approved these changes

2017-08-31 14:34 UTC, merged