v1.9 backport: node: Remove check whether nextHop is in same L2
cilium/cilium pull request #14453
Opened 2020-12-18 17:06 UTC by brb

This is a backport of #14354 for v1.9.

2020-12-18 17:25 UTC, brb commented
test-backport-1.9

2020-12-21 12:37 UTC, aanm approved these changes

2020-12-21 12:40 UTC, aanm requested changes

2020-12-21 12:40 UTC, aanm commented on pkg/datapath/linux/node.go
> +			copy(srcIP, route.Src)
We don't know if `route.Src` as size 4. We need to either make `srcIP` with size `net.IPv6Len` or do:
```
routeSrcIPv4 := route.Src.To4()
```

2020-12-21 12:40 UTC, aanm commented on pkg/datapath/linux/node.go
> +	srcIP := make(net.IP, 4)
```
srcIP := make(net.IP, net.IPv4len)
```

2020-12-22 10:35 UTC, aanm requested changes

2020-12-22 10:35 UTC, aanm commented on pkg/datapath/linux/node.go
>  			copy(nextHopIPv4, route.Gw)
same here for the `To4()`, no?

2021-01-04 09:05 UTC, brb commented
test-backport-1.9

2021-01-04 09:17 UTC, aanm approved these changes

2021-01-05 05:57 UTC, brb commented
retest-net-next

2021-01-05 05:57 UTC, brb commented
retest-runtime

2021-01-06 07:42 UTC, brb commented
CI net-next failed with:
```
/home/jenkins/workspace/Cilium-PR-K8s-1.13-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
Can not connect to service "http://192.168.36.11:31362" from outside cluster
Expected command: kubectl exec -n kube-system log-gatherer-784hz -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://192.168.36.11:31362 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 error: unable to upgrade connection: Authorization error (user=kube-apiserver-kubelet-client, verb=create, resource=nodes, subresource=proxy)
```

2021-01-06 07:42 UTC, brb commented
retest-net-next

2021-01-06 14:56 UTC, pchaigno approved these changes
The two backported commits are missing references to the upstream commits. Those references are automatically added when using our cherry-pick script.

@brb If you want to fix that, I can merge without rerunning the whole tests after the update. Otherwise, I'll merge before end of day.

2021-01-06 15:34 UTC, brb commented
> The two backported commits are missing references to the upstream commits. Those references are automatically added when using our cherry-pick script.

There are no upstream commits. The commits in this PR are only for v1.9.

2021-01-06 15:36 UTC, pchaigno commented
> > The two backported commits are missing references to the upstream commits. Those references are automatically added when using our cherry-pick script.
> 
> There are no upstream commits. The commits in this PR are only for v1.9.

Oh, I missed that the "upstream" PR was closed and I had completely forgot our discussion. Merging both backport PRs :ship:

2021-01-06 15:36 UTC, merged