v1.8 backport: node: Remove check whether nextHop is in same L2
cilium/cilium pull request #14455
Opened 2020-12-18 17:22 UTC by brb

This is a backport of #14354 for v1.8.

2020-12-19 09:06 UTC, brb commented
test-backport-1.8

2020-12-21 10:41 UTC, brb commented
test-backport-1.8

2020-12-21 12:36 UTC, aanm approved these changes

2020-12-21 12:40 UTC, aanm requested changes

2020-12-21 12:40 UTC, aanm commented on pkg/datapath/linux/node.go
> +	srcIP := make(net.IP, 4)
```
srcIP := make(net.IP, net.IPv4len)
```

2020-12-21 12:40 UTC, aanm commented on pkg/datapath/linux/node.go
> +			copy(srcIP, route.Src)
We don't know if `route.Src` as size 4. We need to either make `srcIP` with size `net.IPv6Len` or do:
```
routeSrcIPv4 := route.Src.To4()
```

2020-12-22 10:36 UTC, aanm requested changes

2020-12-22 10:36 UTC, aanm commented on pkg/datapath/linux/node.go
>  			copy(nextHopIPv4, route.Gw)
`route.Gw.To4()`?

2021-01-04 09:05 UTC, brb commented
test-backport-1.8

2021-01-04 09:17 UTC, aanm approved these changes

2021-01-05 05:57 UTC, brb commented
test-backport-1.8

2021-01-05 14:37 UTC, brb commented
test-backport-1.8

2021-01-06 15:23 UTC, pchaigno commented
Travis CI is currently failing on v1.8; #14531 should fix it. In the meantime, I've manually run the unit tests.

2021-01-06 15:25 UTC, pchaigno approved these changes
As in the v1.9 backport PR, the backported commits are missing references to the upstream commits. You can update and I'll merge without re-running e2e tests, or I'll merge before end of day otherwise.

2021-01-06 15:37 UTC, merged