Makefile: format all packages in GOFILES
cilium/cilium pull request #1446
Opened 2017-08-30 21:46 UTC by scanf

Closes: #1445 (Run gofmt as part of the regular build)
Signed-off-by: Alexander Alemayhu <alexander@alemayhu.com>

2017-08-30 21:50 UTC, aanm requested changes

2017-08-30 21:50 UTC, aanm commented on Makefile
> +	for pkg in $(GOFILES); do go fmt $$pkg; done
I think you meant `gofmt -w $$pkg`

2017-08-30 22:19 UTC, scanf commented on Makefile
> +	for pkg in $(GOFILES); do go fmt $$pkg; done
No, see help page
```
go help fmt
usage: go fmt [-n] [-x] [packages]

Fmt runs the command 'gofmt -l -w' on the packages named
by the import paths.  It prints the names of the files that are modified.
```

2017-08-30 22:47 UTC, tgraf commented
Can you provide an example output of how it looks like if there is a formatting error?

2017-08-30 22:49 UTC, aanm approved these changes

2017-08-31 09:02 UTC, scanf commented
@tgraf If there is a formatting error you won't see any output.  It would just be reformatted. Considering that this is running right after building where it should not reach reformatting if there is a build error. So seems safe to assume the tooling can reformat in place. Let me know what you think, alternative we can change it if you don't like this.

@aanm Thanks for approving.

2017-08-31 14:25 UTC, ianvernon commented
Say someone runs a build with unformatted Go code - this will run `go fmt` on the build slaves, but is it possible that the unformatted code gets merged? I.e., are the changes made in the workspace in Jenkins made reflected in master after a merge is done?

2017-08-31 14:42 UTC, tgraf commented
> @tgraf If there is a formatting error you won't see any output. It would just be reformatted. Considering that this is running right after building where it should not reach reformatting if there is a build error. So seems safe to assume the tooling can reformat in place. Let me know what you think, alternative we can change it if you don't like this.

I think failing with the diff will be better. Replacing requires the editor to reload the files. Some editors will do this automatically, most won't.

2017-09-01 22:49 UTC, tgraf requested changes
The output is great otherwise:
```
make[1]: Leaving directory '/home/tgraf/dev/go/src/github.com/cilium/cilium/monitor'
tests/00-fmt.sh
Unformatted Go source code:
./daemon/daemon.go
diff ./daemon/daemon.go gofmt/./daemon/daemon.go
--- /tmp/gofmt043574680	2017-08-30 03:20:01.370900674 +0200
+++ /tmp/gofmt253938199	2017-08-30 03:20:01.370900674 +0200
@@ -83,7 +83,7 @@
 	initArgLib int = iota
 	initArgRundir
 	initArgIPv6Router
-	   initArgIPv4NodeIP
+	initArgIPv4NodeIP
 	initArgIPv6NodeIP
 	initArgIPv4Range
 	initArgIPv6Range
Makefile:10: recipe for target 'all' failed
make: [all] Error 1 (ignored)
```

2017-09-01 22:49 UTC, tgraf commented on Makefile
> +	-tests/00-fmt.sh
We should run `gofmt` before we compile. Otherwise we have to wait for the compile to be complete every time.

2017-09-01 23:54 UTC, tgraf approved these changes

2017-09-02 17:20 UTC, merged