Bump aws-go-sdk-v2 to v0.30.0
cilium/cilium pull request #14460
Opened 2020-12-20 20:50 UTC by ungureanuvladvictor

2020-12-21 01:07 UTC, ungureanuvladvictor commented
test-me-please

2020-12-21 09:19 UTC, tklauser commented
retest-gke

2020-12-21 09:24 UTC, tklauser commented
retest-runtime

2020-12-21 09:34 UTC, tklauser approved these changes

2020-12-21 11:46 UTC, tklauser commented
retest-runtime

2020-12-21 12:34 UTC, aanm requested changes
LGTM, only a minor nit :smile:

2020-12-21 12:34 UTC, aanm commented on pkg/policy/groups/aws/aws.go
> +func extraxctIPs(req *ec2.DescribeInstancesOutput) []net.IP {
`s/extraxctIPs/extractIPs`

2020-12-21 12:34 UTC, aanm commented on pkg/policy/groups/aws/aws.go
> +	return extraxctIPs(result), nil
`s/extraxctIPs/extractIPs`

2020-12-21 18:23 UTC, ungureanuvladvictor commented on pkg/policy/groups/aws/aws.go
> +func extraxctIPs(req *ec2.DescribeInstancesOutput) []net.IP {
Updated!

2020-12-21 18:23 UTC, ungureanuvladvictor commented on pkg/policy/groups/aws/aws.go
> +	return extraxctIPs(result), nil
Updated!

2020-12-21 19:01 UTC, ungureanuvladvictor commented
test-me-please

2020-12-21 19:06 UTC, christarazi approved these changes

2020-12-21 22:08 UTC, aanm approved these changes

2020-12-21 22:09 UTC, aanm commented
retest-gke

2020-12-22 10:16 UTC, tklauser commented
retest-runtime

2020-12-22 10:17 UTC, tklauser commented
retest-gke

2020-12-22 16:41 UTC, merged