preflight: Ignore managed fields in policy validator
cilium/cilium pull request #14528
Opened 2021-01-05 18:16 UTC by christarazi

Fixes: 5aa807c348 ("preflight: Add unknown fields check for validation")
Fixes: https://github.com/cilium/cilium/issues/14526

Reported-by: Robert Stam

2021-01-05 18:17 UTC, christarazi commented
test-me-please

2021-01-06 10:35 UTC, aanm requested changes
Can you add more information on why `metadata.manageFields` is considered a unknown field? AFAIK the `managedFields` exist in the `metadata` structure, so why was it considered unknown?

2021-01-07 00:17 UTC, christarazi commented
@aanm I tried to do a simple repro, but I wasn't able to:

```sh
❯ k get cnp l3-l4-policy -o yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cilium.io/v2","kind":"CiliumNetworkPolicy","metadata":{"annotations":{},"name":"l3-l4-policy","namespace":"default"},"spec":{"description":"L3-L4 policy","endpointSelector":{"matchLabels":{"id":"app1"}},"ingress":[{"fromEndpoints":[{"matchLabels":{"id":"app2"}}],"toPorts":[{"ports":[{"port":"80","protocol":"TCP"}]}]}]}}
  creationTimestamp: "2021-01-07T00:12:25Z"
  generation: 1
  managedFields:
  - apiVersion: cilium.io/v2
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:description: {}
        f:endpointSelector:
          .: {}
          f:matchLabels:
            .: {}
            f:id: {}
        f:ingress: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-01-07T00:12:25Z"
  name: l3-l4-policy
  namespace: default
  resourceVersion: "2440"
  selfLink: /apis/cilium.io/v2/namespaces/default/ciliumnetworkpolicies/l3-l4-policy
  uid: 0e1a0b6d-8ecf-4e2f-aedf-569f434dfe10
spec:
  description: L3-L4 policy
  endpointSelector:
    matchLabels:
      id: app1
  ingress:
  - fromEndpoints:
    - matchLabels:
        id: app2
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP

~/code/cilium/cilium master*
❯ kc exec -it cilium-vqcdc -- cilium preflight validate-cnp
INFO[0000] Setting up Kubernetes client
INFO[0000] Establishing connection to apiserver          host="https://10.47.240.1:443" subsys=k8s
INFO[0000] Connected to apiserver                        subsys=k8s
INFO[0000] Validation OK!                                CiliumNetworkPolicy=default/l3-l4-policy
INFO[0000] All CCNPs and CNPs valid!
```

I'm not sure how the user who reported the issue got into this situation.

2021-01-08 02:31 UTC, christarazi commented
Superseded by https://github.com/cilium/cilium/pull/14557.

2021-01-08 02:31 UTC, closed without merging