k8s: Decouple CNP embedding inside CCNP
cilium/cilium pull request #14557
Opened 2021-01-07 20:52 UTC by christarazi

See commit msgs.

```release-note
Fix bug where CCNPs are not validated properly in preflight
```

2021-01-07 20:53 UTC, christarazi commented
test-me-please

2021-01-08 01:26 UTC, christarazi commented
test-me-please

2021-01-08 08:51 UTC, aanm approved these changes

2021-01-08 08:51 UTC, aanm commented on pkg/k8s/apis/cilium.io/v2/cnp_types.go
> +func sharedCNPDeepEqual(in, other metav1.ObjectMeta) bool {
non blocking nit, this function name could be `objectMetaDeepEqual`

2021-01-08 09:07 UTC, fristonio requested changes
The changes looks good to me. Thanks for the Pull Request :pray:  :rocket: 
There is some documentation around `ClusterwideNetworkPolicies` that needs an update. For example here - https://github.com/cilium/cilium/blob/master/Documentation/concepts/kubernetes/policy.rst#ciliumclusterwidenetworkpolicy

2021-01-08 19:05 UTC, fristonio approved these changes
LGTM :rocket: :100:

2021-01-08 22:17 UTC, christarazi commented
test-me-please

2021-01-11 11:44 UTC, qmonnet approved these changes
Looks good as far as I can tell.

2021-01-11 11:44 UTC, qmonnet commented on Documentation/concepts/kubernetes/policy.rst
> +                // The reason this field exists in this structure is due a bug in the k8s
```suggestion
                // The reason this field exists in this structure is due to a bug in the k8s
```

2021-01-11 11:46 UTC, qmonnet commented
test-gke

2021-01-14 08:06 UTC, merged