Fix clustermesh-apiserver dependencies on pkg/option
cilium/cilium pull request #14577
Opened 2021-01-11 12:51 UTC by tgraf

The clustermesh-apiserver code indirectly used `pkg/option` without initializing it properly. Instead of fixing the initialization, refactor the dependency code to no longer use `pkg/option` but offer interfaces to pass in the required configuration.

2021-01-11 13:05 UTC, nebril approved these changes

2021-01-11 13:07 UTC, tklauser approved these changes

2021-01-11 13:38 UTC, borkmann approved these changes

2021-01-11 14:23 UTC, tgraf commented
test-me-please

2021-01-11 17:16 UTC, gandro approved these changes

2021-01-11 19:15 UTC, aanm requested changes
Can you add more information in the 2nd commit why is it needed? it's not clear to me.

2021-01-11 19:24 UTC, christarazi requested changes
One comment on adding a field to an existing struct instead of expanding the set of parameters passed into functions and another small nit

2021-01-11 19:24 UTC, christarazi commented on pkg/k8s/watchers/watcher.go
> +func (k *K8sWatcher) InitK8sSubsystem(ctx context.Context, cfg WatcherConfiguration) <-chan struct{} {
Instead of passing in `cfg` to each function that may use it, we could add it as a field to the `K8sWatcher`

2021-01-11 19:24 UTC, christarazi commented on operator/watchers/k8s_service_sync.go
> +	// LocalClusterName must return the local cluster name`
Nit: extra backtick at the end of the godoc

2021-01-12 15:22 UTC, tgraf commented
test-me-please

2021-01-12 16:14 UTC, aanm approved these changes

2021-01-12 17:31 UTC, christarazi approved these changes

2021-01-12 18:40 UTC, merged