Documentation: Update list of Jenkins jobs
cilium/cilium pull request #14592
Opened 2021-01-12 15:51 UTC by twpayne

This updates the list of Jenkins jobs that can be triggered with trigger phrases in the documentation to more closely match the jobs currently running in Jenkins.

I'm not sure if the trigger phrases are correct.

2021-01-13 09:29 UTC, qmonnet approved these changes

2021-01-14 09:43 UTC, aanm requested changes

2021-01-14 09:43 UTC, aanm commented on Documentation/contributing/testing/ci.rst
> +| `Ginkgo-CI-Tests-k8s1.20-Pipeline <https://jenkins.cilium.io/job/Ginkgo-CI-Tests-k8s1.20-Pipeline/>`_          | test-missed-k8s   | Yes                |
this doesn't look right... `test-missed-k8s` runs k8s versions from 1.14-1.19

2021-01-14 09:43 UTC, aanm commented on Documentation/contributing/testing/ci.rst
> +| `Cilium-PR-K8s-1.19-kernel-4.9 <https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-4.9/>`_                | test-me-please,   | Yes                |
This doesn't look right as well, `test-me-please` runs k8s 1.20 + kernel 4.9, k8s 1.19 + kernel 4.19 and k8s 1.13 + kernel net-next

2021-01-14 12:55 UTC, nebril approved these changes

2021-01-15 13:12 UTC, twpayne commented
This should now be correct with respect to the trigger phrases too. I've removed the pipeline jobs from the list as they are run periodically rather than being triggered by PRs.

2021-01-18 11:00 UTC, pchaigno approved these changes

2021-01-18 11:55 UTC, aanm approved these changes

2021-01-18 12:41 UTC, merged