arp: Add retries to arping
cilium/cilium pull request #14601
Opened 2021-01-13 15:07 UTC by brb

It has been observed that sometimes arping fails with "i/o timeout".
Further investigation \[1\] has shown that this happen due to the kernel
not sending packets. Therefore, to mitigate the issue, try multiple times
to send the request if the timeout error is encountered.

\[1\]: https://github.com/cilium/cilium/issues/14125#issuecomment-748499731

---

Currently, I'm not labeling it for backporting to v1.{8,9}, as I've opened a discussion whether we could backport the arp library too which would significantly reduce complexity of arping-related backports.

2021-01-13 15:41 UTC, brb commented
test-me-please

2021-01-14 05:36 UTC, brb commented
retest-4.19

2021-01-14 09:29 UTC, aanm requested changes
After fixing the requested changes I would suggest to just run 1 more time the runtime CI since the test was faulty in there.

2021-01-14 09:29 UTC, aanm commented on pkg/datapath/linux/node_linux_test.go
>  	// just created.
at least I know I'm not the only one that doesn't read comments... You forgot to remove these 2 lines as well.

2021-01-14 11:49 UTC, fristonio approved these changes

2021-01-14 14:48 UTC, brb commented
Previously all tests were green. Pushed only a comment change. Retrying the runtime suite to see whether the flake is not reintroduced.

2021-01-14 14:48 UTC, brb commented
test-runtime

2021-01-17 14:36 UTC, brb commented
test-runtime

2021-01-18 09:00 UTC, aanm approved these changes

2021-01-18 09:00 UTC, merged

2021-01-18 09:49 UTC, brb commented
Once https://github.com/cilium/arping/pull/6 has been merged, I will manually backport to v1.8 and v1.9.