v1.7 backports 2021-01-20
cilium/cilium pull request #14669
Opened 2021-01-20 14:54 UTC by mrostecki

* #14565 -- clustermesh: Ignore symlink files on fsnotify events (@tgraf)
 * #14516 -- Fix CIDR coalescing issue in ExceptCIDR rule expressions (@jrajahalme)
 * #14645 -- cilium-cni: Fix error handling for bad netns (@joestringer)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14565 14516 14645; do contrib/backporting/set-labels.py $pr done 1.7; done
```

2021-01-20 14:55 UTC, mrostecki commented
test-backport-1.7

2021-01-20 15:15 UTC, Rolinh approved these changes

2021-01-20 18:49 UTC, joestringer approved these changes

2021-01-20 20:06 UTC, aanm requested changes
@mrostecki PR #14516 only needs the first commit to be backported.

2021-01-21 11:59 UTC, mrostecki commented
test-backport-1.7

2021-01-21 20:52 UTC, joestringer commented
Hmm. CI hit known flake #10442 (which caused `BeforeAll` to fail for 3 subsequent tests):
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/20062/testReport/junit/Suite-k8s-1/17/K8sServicesTest_External_services_To_Services_first_endpoint_creation/

I was hoping that #14645 fixes this issue, but this confirms that it does not. Since it's a known flake, this is not a regression so we're good to merge this PR; the rest of CI passed.

2021-01-21 20:53 UTC, merged