added flag for proxy.prometheus.enabled in helm chart
cilium/cilium pull request #14688
Opened 2021-01-21 17:22 UTC by yuriydzobak

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

By default the service is crated and has annotation of scrape metrics, I don't use envoy, Istio and I have auto discovery for all annotation about prometheus. The endpoint is created in promehtues and spam alerts about it. I want have ability to disable the service. I have set value `true` because it was enabled by default, any users are not effected who wants to disable they should change the flag to `false`

```release-note
Added flag `proxy.promtheus.enabled` to helm chart for disabling service 
```

2021-01-22 10:38 UTC, kaworu commented
Hello @yuriydzobak and thank you for the PR!

I'll defer to @errordeveloper and @seanmwinn here as I lack context about prometheus.

2021-01-25 09:20 UTC, aanm approved these changes
Changes LGTM, please remove the new lines added.

2021-01-25 09:20 UTC, aanm commented on install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml
> +
Nit: remove this line

2021-01-25 09:20 UTC, aanm commented on install/kubernetes/cilium/templates/cilium-configmap.yaml
> +
nit: remove this line

2021-01-25 09:21 UTC, aanm commented
@jrajahalme can you take a look as well?

2021-01-25 09:40 UTC, yuriydzobak commented on install/kubernetes/cilium/templates/cilium-configmap.yaml
> +
done

2021-01-25 09:40 UTC, yuriydzobak commented on install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml
> +
done

2021-01-27 11:38 UTC, nebril approved these changes

2021-01-27 22:46 UTC, christarazi requested changes
Please squash all commits into the first

2021-01-28 07:36 UTC, yuriydzobak commented
> Please squash all commits into the first

Done

2021-01-30 15:05 UTC, aanm commented
test-me-please

2021-01-31 11:39 UTC, fristonio approved these changes
LGTM Thanks :100:

2021-02-01 09:19 UTC, aanm commented
retest-gke

2021-02-01 19:31 UTC, christarazi approved these changes

2021-02-02 09:25 UTC, merged