contrib: Add script to fetch docker manifests
cilium/cilium pull request #14707
Opened 2021-01-22 22:14 UTC by joestringer

This script pulls all of the tagged cilium images from docker.io and
quay.io and fetches the official manifests from the images, and
generates text output for adding to the github release announcement to
allow users to use and/or audit the docker digests that are deployed in
the cluster.

2021-01-22 22:48 UTC, joestringer commented
I didn't bother to extend the release issue templates / process at this point since @aanm mentioned he would be looking into how to build the SHAs into the helm charts. Happy to revisit whether we should add steps particularly for v1.7 and v1.8 once we figure out the right long-term approach.

2021-01-25 09:29 UTC, aanm requested changes
We might need to add to run this script as part of the release process otherwise we will forget the script exists :sweat_smile:

2021-01-28 18:51 UTC, joestringer commented
@aanm done, PTAL

2021-01-28 19:13 UTC, aanm approved these changes

2021-01-28 19:15 UTC, joestringer commented on contrib/release/pull-docker-manifests.sh
> +            >&2 $CONTAINER_ENGINE pull $registry/cilium/$image:$version
This does basically `docker pull` which can take quite some time.

We might be able to instead ping some API that will tell us the digest? Somewhere under here?

```
https://index.docker.io/v1/repositories/${repo}/tags/${tag}"
```

2021-01-28 19:21 UTC, joestringer commented on contrib/release/pull-docker-manifests.sh
> +            >&2 $CONTAINER_ENGINE pull $registry/cilium/$image:$version
Looks like it, will iterate on this:

```
$ curl --silent -f -lSL "https://hub.docker.com/v2/repositories/cilium/cilium/tags/v1.7.13" | jq -r '.images[] as $i | "docker.io/cilium/cilium:\($i.digest)"'
docker.io/cilium/cilium:sha256:ce1254db59d1113e80ca13748ec54204183e15996efdef0dee915eb69e0b3920
```

2021-01-28 19:59 UTC, joestringer commented on contrib/release/pull-docker-manifests.sh
> +            >&2 $CONTAINER_ENGINE pull $registry/cilium/$image:$version
Eh, I can't seem to figure out a convenient way to pull this from quay.io by tag so I'll just defer for now.

2021-01-28 20:02 UTC, merged

2021-01-28 20:23 UTC, joestringer commented on contrib/release/pull-docker-manifests.sh
> +IMAGES=(cilium clustermesh-apiserver docker-plugin hubble-relay operator operator-generic operator-aws operator-azure)
Backporters, For backports to v1.7/v1.8, we need to trim back these image lists. See the `.github/ISSUE_TEMPLATE/release_template.md` for a list of images per branch version.