operator: added --pprof flag/endpoint
cilium/cilium pull request #14903
Opened 2021-02-09 10:13 UTC by mvisonneau

I believe it could be useful to have it for the operator as well as I was looking to troubleshoot some goroutines.

```release-note
operator: added --pprof flag/endpoint
```

2021-02-09 13:44 UTC, nebril approved these changes

2021-02-09 13:47 UTC, nebril requested changes
Code looks good, but this needs another commit with docs changes:

Run `make -C Documentation update-cmdref` and commit doc changes made by this script.

2021-02-09 13:57 UTC, mvisonneau commented
oh right, thanks @nebril, I got the following error when I ran the command though:
```
~$ make -C Documentation update-cmdref
[..]
Successfully tagged cilium/docs-builder:latest
rm -rf cmdref/cilium*.md
docker container run --rm --workdir /src/Documentation --volume /Users/max/Projects/os/cilium/Documentation/..:/src --env READTHEDOCS_VERSION= --env SKIP_LINT= --user "501:20" cilium/docs-builder ./update-cmdref.sh
./update-cmdref.sh: line 23: /src/bugtool/cilium-bugtool: No such file or directory
make: *** [update-cmdref] Error 127
```

do you know if I need specific tooling installed beforehand? 🤔

2021-02-10 13:02 UTC, nebril commented
@mvisonneau you need to build Cilium binaries before running this, sorry for not mentioning that this was also unclear for me. Run 
`make daemon bugtool operator cilium cilium-health` in root of the repo before running `make -C Documentation update-cmdref`, this will build required binaries. Will make sure that this is better documented too.

2021-02-10 16:42 UTC, mvisonneau commented
awesome, thanks for the guidance 🙇! I also had to `make operator` as well and managed to get it done afterwards 👌

2021-02-11 13:50 UTC, aanm approved these changes

2021-02-12 12:14 UTC, nebril approved these changes

2021-02-12 12:14 UTC, nebril commented
test-gke

2021-02-14 12:39 UTC, merged