helm: Fix and add missing podLabels
cilium/cilium pull request #14943
Opened 2021-02-11 21:49 UTC by Subreptivus

- Pod Labels defined in `values` file were not propagated to actual manifests
- Some of the Pods were missing `podLabels` definition in `values` file and in actual manifests (i.e. certgen jobs Pods)

2021-02-11 22:34 UTC, nathanjsweet commented
@Subreptivus can you run the command `make -C install/kubernetes docs` and commit the changes. We'll have test failures until you update the `quick-install.yaml` file. Thanks!

2021-02-12 11:37 UTC, qmonnet requested changes
Thank you! Can we get rid of the third commit (the merge, I suspect it was created because you tried to update the branch automatically in GitHub)? No need to update unless there are conflicts to solve, in which case it looks cleaner to rebase the PR on top on the current master.

2021-02-12 11:37 UTC, qmonnet commented on install/kubernetes/cilium/values.yaml
> +    #
Nit: We can probably remove this empty comment line

2021-02-12 11:37 UTC, qmonnet commented on install/kubernetes/cilium/values.yaml
> +    #
And here.

2021-02-15 10:54 UTC, Subreptivus commented
@qmonnet Done, now it should be allright.
As for empty lines, I was just used few lines up to be consistent with a config that was there before (sometimes there were empty lines, sometimes not). So I've removed all empty lines. Hope you're happy now.

2021-02-15 13:49 UTC, Skymirrh approved these changes

2021-02-15 14:44 UTC, qmonnet approved these changes
I'm happy now :). Thank you

2021-02-15 14:44 UTC, qmonnet commented
test-me-please

2021-02-16 13:06 UTC, nebril approved these changes

2021-02-22 12:17 UTC, errordeveloper approved these changes

2021-02-23 14:01 UTC, merged