Helm: add eni option to use iam-role
cilium/cilium pull request #14970
Opened 2021-02-13 17:57 UTC by bluestealth

Prevents helm from adding secret env in particular `AWS_DEFAULT_REGION` for AWS pod identity if using an iam-role.

It seems that this prevents the [eks-pod-identity-webhook](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/599cfe7cfc8c72d48a8870e675e19a8169b3dafe/pkg/handler/handler.go#L212-L224) from adding the entry if missing.
```
level=warning msg="Unable to synchronize EC2 VPC list" error="operation error EC2: DescribeVpcs, failed to sign request: failed to retrieve credentials: failed to retrieve credentials, operation error STS: AssumeRoleWithWebIdentity, failed to resolve service endpoint, an AWS region is required, but was not found" subsys=eni
level=fatal msg="Unable to start eni allocator" error="Initial synchronization with instances API failed" subsys=cilium-operator-aws
```

Fixes: #13270 

```release-note
Add iam-role option to eni to Helm chart to allow using EKS pod identity for AWS identity
```

2021-02-15 15:06 UTC, qmonnet approved these changes
Looks good, although my knowledge of AWS is too limited to provide a correct review on the content.

2021-02-16 03:09 UTC, christarazi requested changes
LGTM, I think the second commit can be squashed with the first

2021-02-16 05:38 UTC, bluestealth commented
@christarazi done

2021-02-16 05:52 UTC, christarazi approved these changes

2021-02-16 07:14 UTC, kkourt approved these changes
Same as Quentin.

2021-02-22 12:21 UTC, errordeveloper approved these changes

2021-02-26 13:55 UTC, qmonnet commented
test-me-please

2021-02-26 17:53 UTC, qmonnet commented
test-1.19-4.19

2021-02-26 18:16 UTC, qmonnet commented
test-1.20-4.9

2021-03-01 10:04 UTC, merged