Move Azure IPAM out of beta
cilium/cilium pull request #14993
Opened 2021-02-16 10:45 UTC by tgraf

2021-02-16 11:21 UTC, twpayne approved these changes
LGTM, two minor comments - feel free to ignore them.

2021-02-16 11:21 UTC, twpayne commented on Documentation/gettingstarted/k8s-install-azure.rst
> +   export LOCATION=westeurope
Tiny nit: the previous command uses location `westus` but this command uses `westeurope`.

2021-02-16 11:21 UTC, twpayne commented on Documentation/gettingstarted/cni-chaining-azure-cni.rst
> +desired CNI chaining configuration:
Is it worth adding a sentence or two describing what `chaining.yaml` does? For example, the need for the `azure-vnet` and `ciluim` plugins is clear, but why is the `portmap` plugin needed?

2021-02-16 11:32 UTC, qmonnet requested changes
It looks like the following links will break, can you please update them?
```
$ grep k8s-install-aks install | sed 's/:.*\[/: [/'     
install/kubernetes/cilium/README.md.gotmpl: [Microsoft AKS](https://raw.githubusercontent.com/cilium/charts/master/images/azure.svg)](https://cilium.readthedocs.io/en/stable/gettingstarted/k8s-install-aks/) |
install/kubernetes/cilium/README.md: [Microsoft AKS](https://raw.githubusercontent.com/cilium/charts/master/images/azure.svg)](https://cilium.readthedocs.io/en/stable/gettingstarted/k8s-install-aks/) |
```

Looks good to me otherwise.

2021-02-17 08:26 UTC, tgraf commented
test-docs

2021-02-17 08:49 UTC, jibi approved these changes

2021-02-17 09:37 UTC, qmonnet approved these changes

2021-02-17 09:41 UTC, ti-mo requested changes
Looks good! I left another mention of Azure IPAM being beta in `gettingstarted/kubeproxy-free.rst` at the time, which probably needs to be removed:

> Deploying Cilium with `azure.enabled=true` will disconnect all running Pods in the cluster that were scheduled using the default azure-vnet CNI plugin. We aim to remove this limitation before moving Azure IPAM out of Beta.

(:point_up: Reading this again, it's not 100% accurate anyway, as this only manifests on legacy nodepools configured in bridge mode.)

There's also a `helm install` example using Azure IPAM in `kubeproxy-free.rst` that might need to be replaced with a link to the AKS install guide or an rst include to prevent it from going stale.

2021-02-22 12:20 UTC, errordeveloper approved these changes

2021-02-22 12:47 UTC, ti-mo approved these changes
Looks good!

2021-02-22 13:04 UTC, jibi commented
I'm marking this as ready-to-merge without full CI tests as the PR is only touching documentation

2021-02-22 13:04 UTC, merged