Pr/v1.8 backport 2021 02 19
cilium/cilium pull request #15038
Opened 2021-02-19 17:00 UTC by nathanjsweet

Please ensure your pull request adheres to the following guidelines:

v1.8 backports 2021-02-19

 * #15008 -- backporting: Add support for forked cilium repositories  (@gandro)
 * #14902 -- datapath: Do not log when kernel config not found (@brb)
 * #15012 -- Avoid an empty instanceID on EC2 (@kkourt)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 15008 14902 15012; do contrib/backporting/set-labels.py $pr done 1.8; done
```

2021-02-19 23:30 UTC, tgraf approved these changes

2021-02-20 14:58 UTC, gandro requested changes

2021-02-20 14:58 UTC, gandro commented on contrib/backporting/submit-backport
> +require_linux
Seems like the merge conflict resolution pulled in this line here accidentally. It should be removed, as the `require_linux` function has not been backported to 1.8

2021-02-22 08:01 UTC, brb approved these changes
:+1: for my changes, thanks.

2021-02-22 08:14 UTC, kkourt approved these changes
:+1: for my PR

2021-02-22 09:46 UTC, aanm commented
@nathanjsweet Please rebase against v1.8 before retesting.

2021-02-22 10:01 UTC, gandro commented on contrib/backporting/submit-backport
> +require_linux
@nathanjsweet I think it's probably the easiest if you backported commit https://github.com/cilium/cilium/commit/05eabc71a8525fffba8977eabdfd6e763dcd08c7 as well (not the full PR, just the commit). 

I'll do the same for the v1.7 and v1.9 branch.

2021-02-22 16:09 UTC, gandro approved these changes

2021-02-22 18:10 UTC, christarazi commented
test-backport-1.8

2021-02-22 21:17 UTC, christarazi commented
retest-1.18-4.9

2021-02-22 23:05 UTC, merged