jenkinsfiles: remove unused environment variables
cilium/cilium pull request #15125
Opened 2021-02-26 12:01 UTC by aanm

As we are no longer building images in ginkgo, we can remove these
environment variables.

Signed-off-by: André Martins <andre@cilium.io>

2021-02-26 13:57 UTC, aanm commented
test-me-please

2021-03-01 11:21 UTC, aanm commented
hit https://github.com/cilium/cilium/issues/15141

2021-03-01 11:42 UTC, nebril requested changes
Thanks for taking a stab at this! There are some issues with this change, let me know if any of my comments is unclear.

2021-03-01 11:42 UTC, nebril commented on jenkinsfiles/ginkgo-gke.Jenkinsfile
>                      if (env.RACE?.trim()) {
`s/env.RACE?.trim()/env.run_with_race_detection?.trim()` , `RACE` was set at line 23

2021-03-01 11:42 UTC, nebril commented on jenkinsfiles/ginkgo-kernel.Jenkinsfile
>                      if (env.RACE?.trim()) {
same as gke jenkinsfile

2021-03-01 11:42 UTC, nebril commented on jenkinsfiles/ginkgo-gke.Jenkinsfile
> +                        env.RACE = "true"
This doesn't do anything, let's get rid of `RACE` env var in all jenkinsfiles.

2021-03-01 11:42 UTC, nebril commented on jenkinsfiles/ginkgo-kernel.Jenkinsfile
> +                        env.RACE = "true"
same as gke jenkinsfile

2021-03-01 11:42 UTC, nebril commented on jenkinsfiles/ginkgo-runtime-kernel.Jenkinsfile
> -        LOCKDEBUG="""${sh(
I think we want these env vars to be set, as they are passed to runtime VM which causes them to be passed to `make` targets run inside the vm which build the binaries.

2021-03-01 11:42 UTC, nebril commented on jenkinsfiles/ginkgo-runtime-kernel.Jenkinsfile
> -        BASE_IMAGE="""${sh(
ditto

2021-03-01 11:42 UTC, nebril commented on jenkinsfiles/kubernetes-upstream.Jenkinsfile
> +                        env.RACE = "true"
This is a no-op, we need a second if in this block: 

```
if (env.run_with_race_detection?.trim()) {
  env.DOCKER_TAG = env.DOCKER_TAG + "-race"
}
```

2021-03-01 12:24 UTC, nebril approved these changes

2021-03-01 12:25 UTC, aanm commented
test-me-please

2021-03-03 09:32 UTC, aanm commented
merging since this is only modifying jenkinsfiles.

2021-03-03 09:32 UTC, merged