Docs: adds a getting started guide for Rancher 2.x
cilium/cilium pull request #15179
Opened 2021-03-02 23:06 UTC by seanmwinn

Signed-off-by: Sean Winn <sean@isovalent.com>

Adds a getting started guide for Rancher 2.x using Existing Nodes

```release-note
Adds a Getting Started Guide for Rancher 2.x using Existing Nodes
```

2021-03-03 10:54 UTC, qmonnet requested changes
Thanks Sean, the guide looks nice (although I haven't checked the pictures yet)! But the formatting is not good. You need to address it, Markdown syntax is not valid. See the suggestions inline.

In addition to the use of single backquotes, the CI complains because your document is not included anywhere in the doc, it is an orphan page not linked from any other. You need to reference it, most likely in `Documentation/gettingstarted/index.rst`.

Note that you should be able to compile and preview the documentation locally with:

    make -C Documentation live-preview

The content looks good, should we also include the instructions to run the connectivity tests, to make sure that Cilium is running as expected?

2021-03-03 10:54 UTC, qmonnet commented on Documentation/gettingstarted/rancher.rst
> +=====================
```suggestion
Create a New Cluster
====================
```

2021-03-03 10:54 UTC, qmonnet commented on Documentation/gettingstarted/rancher.rst
> +`Add Cluster` box to create a new cluster.
This is RST, not markdown. The simple backquotes in RST are for “[interpreted text](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#interpreted-text)”, text interpreted in a specific context. Instead, you want inline litterals, with double-backquotes.
```suggestion
``Add Cluster`` box to create a new cluster.
```
Here and at other locations in the document. This should fix most of the complaints from the CI action.

2021-03-03 10:54 UTC, qmonnet commented on Documentation/gettingstarted/rancher.rst
> +```
This is Markdown. RST:
```suggestion
.. code-block:: shell-session

    $ sudo mount bpffs -t bpf /sys/fs/bpf
    $ sudo bash -c 'cat <<EOF >> /etc/fstab
    none /sys/fs/bpf bpf rw,relatime 0 0
    EOF'
```

Can't the second command be simplified into something like `sudo echo 'none /sys/fs/bpf bpf rw,relatime 0 0' >> /etc/fstab`?

2021-03-03 10:54 UTC, qmonnet commented on Documentation/gettingstarted/rancher.rst
> +Before adding nodes to the cluster, ensure the BPF filesystem  is mounted.
```suggestion
Before adding nodes to the cluster, ensure the BPF filesystem is mounted.
```

2021-03-03 10:54 UTC, qmonnet commented on Documentation/gettingstarted/rancher.rst
> +This error is expected. - [ ] The Kubernetes components are not able to fully
Leftover from copy-paste?
```suggestion
This error is expected. The Kubernetes components are not able to fully
```

2021-03-03 10:54 UTC, qmonnet commented on Documentation/gettingstarted/rancher.rst
> +One added, you should see the Cilium repository in the catalog list:
```suggestion
Once added, you should see the Cilium repository in the catalog list:
```

2021-03-09 12:18 UTC, qmonnet requested changes
Two more observations, one is my fault - Sorry!

2021-03-09 12:18 UTC, qmonnet commented on Documentation/gettingstarted/k8s-install-rancher-existing-nodes.rst
> +***********************
This time, the GitHub action complains about the following:

```suggestion
**************************
Installation using Rancher
**************************
```

2021-03-09 12:18 UTC, qmonnet commented on Documentation/gettingstarted/k8s-install-rancher-existing-nodes.rst
> +  sudo echo 'none /sys/fs/bpf bpf rw,relatime 0 0' >> /etc/fstab
I'm terribly sorry, on re-reading this, I was mistaken. The redirection itself needs to be performed as root, and the `bash -c` you had was the correct thing. Apologies for that!
```suggestion
  sudo bash -c "echo 'none /sys/fs/bpf bpf rw,relatime 0 0' >> /etc/fstab"
```

2021-03-09 17:29 UTC, qmonnet requested changes
You're welcome!
A last few comments. While looking at other guides I realised we're missing the disclaimer at the top of the file, see my comment below. There's also a typo on the bash option (should be lowercase `-c`, see below).

After that, it should be all from my side. I built the doc locally and tested that everything works as expected. The doc build fine and is linked from the list of GSG, and the links to the pictures are correct and consistent with the walk-through, all good on that side :)

2021-03-09 17:29 UTC, qmonnet commented on Documentation/gettingstarted/k8s-install-rancher-existing-nodes.rst
> +**************************
We forgot the disclaimer at the top of the file:
```suggestion
.. only:: not (epub or latex or html)

    WARNING: You are looking at unreleased Cilium documentation.
    Please use the official rendered version released here:
    https://docs.cilium.io

**************************
```

2021-03-09 17:29 UTC, qmonnet commented on Documentation/gettingstarted/k8s-install-rancher-existing-nodes.rst
> +  sudo bash -C "echo 'none /sys/fs/bpf bpf rw,relatime 0 0' >> /etc/fstab"
This should be a lower case `-c`.

```suggestion
  sudo bash -c "echo 'none /sys/fs/bpf bpf rw,relatime 0 0' >> /etc/fstab"
```

2021-03-09 23:49 UTC, qmonnet approved these changes
Looks good to me now, thanks a lot! Could you please squash your two commits into a single one?

2021-03-10 01:07 UTC, seanmwinn commented
@qmonnet all squashed and ready, thanks again

2021-03-10 08:45 UTC, merged