docs: update k3s installation instructions
cilium/cilium pull request #15191
Opened 2021-03-03 17:57 UTC by oskapt

I work for Rancher. This commit fixes the K3s installation instructions, removing the deprecated `--no-flannel` option and removing the unrecognized flags being passed to the agent. The installation instructions will now result in a successful installation.

2021-03-03 18:04 UTC, oskapt commented
For what it's worth, if you're going to add all these PR restrictions that aren't visible until _after_ someone clicks "Edit on GitHub" on your docs and makes a commit they can't amend, the actual result is that people will delete their commits instead of going through the trouble of redoing them. Signing off by writing "Signed-off-by" in the commit proves nothing, and there's no "sign off" option when commiting in the Web UI. 

I like you guys, but it took me 2 minutes to make the original change and then 15 minutes to try and fix it, clone the repo, try to find the patch branch, give up, delete it, redo it, and resubmit it with the magic line. Signing off accomplishes nothing except that next time I find a mistake in your docs, I'm a thousand times less likely to contribute because the experience sucked.

Furthermore, I want to thank you for forcing me to put my email address in a public commit message for spammers to harvest. 👍 

Signed-off-by: Security Theater <handwavey@makes.us.look.important.com>

2021-03-15 16:37 UTC, jrajahalme requested changes
Thanks for the fix! Looks good but this should apply against master rather than a release branch, and mark it to 1.9 backport from there. Doing this requires a new PR to be opened against master and this one closed.

2021-03-15 16:45 UTC, jrajahalme commented
> For what it's worth, if you're going to add all these PR restrictions that aren't visible until _after_ someone clicks "Edit on GitHub" on your docs and makes a commit they can't amend, the actual result is that people will delete their commits instead of going through the trouble of redoing them. Signing off by writing "Signed-off-by" in the commit proves nothing, and there's no "sign off" option when commiting in the Web UI.
> 
> I like you guys, but it took me 2 minutes to make the original change and then 15 minutes to try and fix it, clone the repo, try to find the patch branch, give up, delete it, redo it, and resubmit it with the magic line. Signing off accomplishes nothing except that next time I find a mistake in your docs, I'm a thousand times less likely to contribute because the experience sucked.
> 
> Furthermore, I want to thank you for forcing me to put my email address in a public commit message for spammers to harvest. 👍
> 
> Signed-off-by: Security Theater [handwavey@makes.us.look.important.com](mailto:handwavey@makes.us.look.important.com)

@aanm Is there a way to disable the "Edit on GitHub" functionality as it is not really supported?

On the PR process, hopefully you'll open a GH issue instead of giving up. GH issue process is trivial and gives a chance for someone else to go through the PR process in the case you don't have the time.

2021-03-15 20:02 UTC, oskapt commented
Hmm...so, you're asking me to:

1. Find an error in the docs that's easy for me to fix
2. Open an issue and tell you about it instead of fixing it
3. Wait for someone else to fix it

I'd love to help you, but if you make it onerous and painful for me to do so, I'm just not going to do it. 

The docs still have incorrect k3s instructions. The fix is in my PR - you're welcome to apply it if you'd like your docs to be accurate.

2021-03-15 20:02 UTC, closed without merging

2021-03-29 23:12 UTC, aanm commented
Hi @oskapt, the PR is opened here https://github.com/cilium/cilium/pull/15503

Thanks for the changes

2021-04-06 18:23 UTC, joestringer commented
> @aanm Is there a way to disable the "Edit on GitHub" functionality as it is not really supported?

I've opened this PR to disable the option since it's so confusing. https://github.com/cilium/cilium/pull/15579