Use vishvananda/netlink instead of net.Interface*
cilium/cilium pull request #15296
Opened 2021-03-10 06:37 UTC by anfernee

This will allow us to avoid deadlocks when retrieving iface by name
described in cilium/cilium#15051.

2021-03-10 16:08 UTC, anfernee commented
test-me-please

2021-03-10 17:53 UTC, brb requested changes
Thanks! Just one nit.

2021-03-10 17:53 UTC, brb commented on pkg/multicast/multicast.go
> +func interfaceByName(name string) (*net.Interface, error) {
Maybe a small comment explaining the conversion would be useful.

2021-03-10 20:00 UTC, brb commented
test-me-please

2021-03-10 20:00 UTC, brb approved these changes
Thanks! Could you set the release note label?

2021-03-11 09:55 UTC, aanm commented
Changed release note to `misc` as it's not a user-facing change.

2021-03-11 09:55 UTC, merged