doc: Use Cilium CLI for Cluster Mesh documentation
cilium/cilium pull request #15359
Opened 2021-03-16 11:06 UTC by tgraf

* Use of the Cilium CLI for Cluster Mesh installation massively
  simplifies the installation.
* Installation, service discovery, and network policy are split it into
  individual guides.
* Cluster Mesh is moved to a top level entry under "Getting Started"
  instead of hiding it in "Advanced Networking".
* The extended troubleshooting is moved to a the Troubleshooting
  section.

Related: #14205

2021-03-16 18:19 UTC, qmonnet requested changes
Looks great, the CLI really makes things simpler.

I spotted a few typos, please see below.

I also suggested fixes for title case, and for code block formatting. My understanding is that `.. code-block::` is more flexible than `.. code::`, even though there's probably no difference with our current usage of the directive. Language `shell-session` is more suitable for command-line command/output sessions, `bash` is for bash scripts. We have no consensus on prepending the `$` at the beginning of the commands, so that one is optional to fix.

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/clustermesh.rst
> +connecting them together, enabling pod-to-pod connectivity across all clusters,
```suggestion
connecting them together, enable pod-to-pod connectivity across all clusters,
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/clustermesh.rst
> +Prepare the clusters
```suggestion
Prepare the Clusters
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/clustermesh.rst
> +as you typically pass to ``kubectl --context``.
Missing a word between the two lines.

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/clustermesh.rst
> +Specify the cluster name and ID
```suggestion
Specify the Cluster Name and ID
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/clustermesh.rst
> +   cilium install --context $CLUSTER2 [...] --inherit-ca $CLUSTER1
```suggestion
.. code-block:: shell-session

   $ cilium install --context $CLUSTER2 [...] --inherit-ca $CLUSTER1
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/clustermesh.rst
> +   cilium clustermesh enable --context $CLUSTER2
```suggestion
.. code-block:: shell-session

   $ cilium clustermesh enable --context $CLUSTER1
   $ cilium clustermesh enable --context $CLUSTER2
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/clustermesh.rst
> +.. code::
```suggestion
.. code-block::
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/clustermesh.rst
> +   cilium clustermesh status --context $CLUSTER2 --wait
```suggestion
.. code-block:: shell-session

   $ cilium clustermesh status --context $CLUSTER1 --wait
   $ cilium clustermesh status --context $CLUSTER2 --wait
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/clustermesh.rst
> +.. code::
```suggestion
.. code-block::
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/clustermesh.rst
> +    cilium clustermesh connect --context $CLUSTER1 --destination-context $CLUSTER2
```suggestion
.. code-block:: shell-session

    $ cilium clustermesh connect --context $CLUSTER1 --destination-context $CLUSTER2
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/clustermesh.rst
> +.. code::
```suggestion
.. code-block::
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/clustermesh.rst
> +   cilium clustermesh status --context $CLUSTER1 --wait
```suggestion
.. code-block:: shell-session

   $ cilium clustermesh status --context $CLUSTER1 --wait
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/clustermesh.rst
> +.. code::
```suggestion
.. code-block::
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/clustermesh.rst
> +Test pod connectivity between clusters
```suggestion
Test Pod Connectivity Between Clusters
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/clustermesh.rst
> +   cilium connectivity test --context $CLUSTER1 --multi-cluster $CLUSTER2
```suggestion
.. code-block::

   $ cilium connectivity test --context $CLUSTER1 --multi-cluster $CLUSTER2
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/clustermesh.rst
> +       cilium status --context $CLUSTER2
```suggestion
    .. code-block:: shell-session

       $ cilium status --context $CLUSTER1
       $ cilium status --context $CLUSTER2
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/clustermesh.rst
> +       cilium clustermesh status --context $CLUSTER2
```suggestion
    .. code-block:: shell-session

       $ cilium clustermesh status --context $CLUSTER1
       $ cilium clustermesh status --context $CLUSTER2
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/policy.rst
> +You need to have a functioning Cluster Mesh setup, please following the guide
```suggestion
You need to have a functioning Cluster Mesh setup, please follow the guide
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/policy.rst
> +As addressing and network security is decoupled, network security enforcement
```suggestion
As addressing and network security are decoupled, network security enforcement
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/policy.rst
> +Allowing specific communication between clusters
```suggestion
Allowing Specific Communication Between Clusters
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/policy.rst
> +The following policy illustrates how to allow particular pods to allow
```suggestion
The following policy illustrates how to allow particular pods to
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/policy.rst
> +   ``--auto-direct-node-routes`` but won't work automatically when using
```suggestion
   is obtained when running in direct routing mode by running a routing daemon or
   ``--auto-direct-node-routes``, but it won't work automatically when using
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/services.rst
> +This tutorial will guide you how to perform load-balancing and service
```suggestion
This tutorial will guide you to perform load-balancing and service
```
(Or is it `guide you on how to perfom`? Not sure what's best here)

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/policy.rst
> +This tutorial will guide you how to define NetworkPolicies affecting multiple
```suggestion
This tutorial will guide you to define NetworkPolicies affecting multiple
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/services.rst
> +You need to have a functioning Cluster Mesh setup, please following the guide
```suggestion
You need to have a functioning Cluster Mesh setup, please follow the guide
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/services.rst
> +the annotation ``io.cilium/global-service: "true"``` to declare it global.
```suggestion
the annotation ``io.cilium/global-service: "true"`` to declare it global.
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/services.rst
> +Load-balancing only to a remote cluster
```suggestion
Load-balancing Only to a Remote Cluster
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/services.rst
> +Deploying a simple example service
```suggestion
Deploying a Simple Example Service
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/clustermesh/services.rst
> +      kubectl exec -ti xwing-xxx -- curl rebel-base
```suggestion
   .. code-block:: shell-session

      $ kubectl exec -ti xwing-xxx -- curl rebel-base
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/gettingstarted/install-cli.rst
> +      rm cilium-darwin-amd64.tar.gz
```suggestion
    .. code-block:: shell-session

      $ curl -LO https://github.com/cilium/cilium-cli/releases/latest/download/cilium-darwin-amd64.tar.gz
      $ sudo tar xzvfC cilium-darwin-amd64.tar.gz /usr/local/bin
      $ rm cilium-darwin-amd64.tar.gz
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/operations/troubleshooting.rst
> +       cilium status
```suggestion
    .. code-block:: shell-session

       $ cilium status
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/operations/troubleshooting.rst
> +       cilium clustermesh status
```suggestion
    .. code-block:: shell-session

       $ cilium clustermesh status
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/operations/troubleshooting.rst
> +    .. code:: bash
```suggestion
    .. code-block::
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/operations/troubleshooting.rst
> +    If the configuration is now found, check the following:
```suggestion
    If the configuration is not found, check the following:
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/operations/troubleshooting.rst
> +    .. code:: bash
```suggestion
    .. code-block::
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/operations/troubleshooting.rst
> +    .. code:: bash
```suggestion
    .. code-block::
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/operations/troubleshooting.rst
> +    If the connection fails, the cause can be one of the following:
```suggestion
    If the connection failed, check the following:
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/operations/troubleshooting.rst
> +      .. code:: yaml
```suggestion
      .. code-block:: yaml
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/operations/troubleshooting.rst
> +          cilium kvstore get --recursive cilium/state/nodes/v1/
```suggestion
      .. code-block:: shell-session

          $ cilium kvstore get --recursive cilium/state/nodes/v1/
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/operations/troubleshooting.rst
> +    * Run ``cilium debuginfo`` and look for the section "k8s-service-cache". In
```suggestion
    * Run ``cilium debuginfo`` and look for the section ``k8s-service-cache``. In
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/operations/troubleshooting.rst
> +      cache.  it will list the Kubernetes services and endpoints of the local
```suggestion
      cache.  It will list the Kubernetes services and endpoints of the local
```

2021-03-16 18:19 UTC, qmonnet commented on Documentation/operations/troubleshooting.rst
> +      .. code::
```suggestion
      .. code-block::
```

2021-03-16 23:45 UTC, tgraf commented
``code-block::`` without a language doesn't render correctly for me so I've put in `shell-session`

2021-03-17 10:27 UTC, qmonnet requested changes
> `code-block::` without a language doesn't render correctly for me so I've put in `shell-session`

Sounds good, thanks a lot for all the fixes.
A few colons got lost (see below), can you please address it? Looks all good otherwise.

2021-03-17 10:27 UTC, qmonnet commented on Documentation/operations/troubleshooting.rst
> +    .. code-block: shell-session
Missing a colon, this is treated as a comment.
```suggestion
    .. code-block:: shell-session
```

2021-03-17 10:27 UTC, qmonnet commented on Documentation/operations/troubleshooting.rst
> +    .. code-block: shell-session
```suggestion
    .. code-block:: shell-session
```

2021-03-17 10:27 UTC, qmonnet commented on Documentation/operations/troubleshooting.rst
> +      .. code-block: shell-session
```suggestion
      .. code-block:: shell-session
```

2021-03-17 14:55 UTC, qmonnet approved these changes

2021-03-17 15:42 UTC, qmonnet commented
Not sure why nobody from the K8s team has been assigned, picking someone at `$RANDOM`. Maciej, you're the lucky one :+1:.

2021-03-18 20:57 UTC, christarazi approved these changes

2021-03-19 17:21 UTC, joestringer commented
Couple of questions, 
1. Do we want to consider backporting these instructions to v1.9 branch so that the docs become more widely available ~now rather than when we end up releasing v1.10?
1. If yes, have we had someone other than @tgraf go through the new instructions and have success with them or was the review purely just reading docs / formatting / etc.?

Non-blocking questions to merge but I think we should be able to answer the (2) with "yes" before publishing the docs for wider consumption (whether as part of v1.10 or backported into v1.9).

2021-03-19 17:21 UTC, merged