bpf: ignore errno 2 when deleting non-existing entry
cilium/cilium pull request #15390
Opened 2021-03-18 18:38 UTC by jxiaobin

Note: errno 2 is "no such file or directory".

Previously if an entry doesn't exist in underlying map, an error will be returned
directly and the cache entry will be left there. This fix logs such event and
ignores the error so that cache deletion will go through.

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
Fix bug when deleting an non-existing entry
```

2021-03-18 20:46 UTC, christarazi reviewed
Overall looks good, just minor suggestions.

2021-03-18 20:46 UTC, christarazi commented on pkg/bpf/map_linux.go
> +		if errno == 2 {
```suggestion
		if errno == unix.ENOENT {
```

2021-03-18 20:46 UTC, christarazi commented on pkg/bpf/map_linux.go
> +			m.scopedLogger().WithField("element", key).WithField("map", m.name).Warn("element not found")
```suggestion
			m.scopedLogger().WithFields(logrus.LogFields{
			    "key": key,
			    "map": m.name,
			}).Warn("element not found")
```

It's worth seeing if we already having `logfields` for each field in the above entry, i.e. `logfields.MapKey`, `logfield.MapName`, etc.

2021-03-18 21:05 UTC, brb requested changes
Thanks.

I'd rather keep the error, as there might be the API consumers which are interested in ENOENT when removing an entry. Instead, let's better figure out why `pkg/service` is trying to delete a non-existing entry. It should have an up to date view of the relevant BPF maps content.

2021-03-25 10:51 UTC, pchaigno commented
@jxiaobin I've converted the pull request to draft. If you're still working on this, don't hesitate to move out of draft once it's ready for a new round of reviews. (Although, looking at Martynas's review, it seems we should debug the error rather than hide it.)

2021-06-20 13:12 UTC, closed without merging