e2e test for egress
cilium/cilium pull request #15444
Opened 2021-03-24 05:18 UTC by anfernee

Still a draft. 

This is built on top of ##14830 and #15134 and it has passed.

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note

```

2021-05-21 20:40 UTC, pchaigno commented
@anfernee Are you planning to revive this pull request? It would really help to catch bugs and regressions in the egress gateway. Right now, we have zero end-to-end tests :-/

2021-05-22 00:33 UTC, anfernee commented
Right on the top of my list. I'll look at this one this weekend (most effective time for me). Sorry for the delay..

2021-05-24 07:54 UTC, anfernee commented
There is still an issue I don't exactly know what is the root cause yet. Some times agent failed to start, which caused the cilium pre-flight checks failed: 

```
 	 Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
	 Error: Cannot get status/probe: Put "http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe": context deadline exceeded
	 
	 command terminated with exit code 1
```

2021-05-26 22:06 UTC, pchaigno requested changes
Lots of small comments but nothing really blocking. It looks good overall!

I think we should also cover endpoint routes enabled vs. disabled.

2021-05-26 22:06 UTC, pchaigno commented on install/kubernetes/cilium/templates/cilium-operator-clusterrole.yaml
> +  - ciliumegressnatpolicies
Was this included by mistake?

2021-05-26 22:06 UTC, pchaigno commented on test/helpers/kubectl.go
> +	return kub.ExecShort(fmt.Sprintf("%s label namespace %s %s", KubectlCmd, name, NamespaceSelector))
This helper function is used in all sorts of end-to-end tests, with different namespaces. So I'd prefer if we did not indiscriminately add the label to all namespaces we create. Maybe it's enough to set the label at the beginning of the egress IP gateway tests?

2021-05-26 22:06 UTC, pchaigno commented on test/helpers/kubectl.go
> +	replaced = strings.Replace(replaced, "-", "", -1)
Why is `-` not supported?

2021-05-26 22:06 UTC, pchaigno commented on test/k8sT/manifests/egress-ip-deployment.yaml
> +              - "for i in $EGRESS_IPS; do ip address del $i dev enp0s8; done"
Nit: Missing newline. Same in the file below.

2021-05-26 22:06 UTC, pchaigno commented on test/k8sT/Egress.go
> +			helpers.HelperTimeout)).Should(BeNil())
It looks like this was copied from test `Check BPF masquerading with ip-masq-agent`. Maybe we could introduce a function in `test/helpers/` to implement this?

2021-05-26 22:06 UTC, pchaigno commented on test/k8sT/Egress.go
> +		if !helpers.ExistNodeWithoutCilium() {
We also need to skip the test if we're not running with the kube-proxy replacement (`DoesNotRunWithKubeProxyReplacement`).

We can include these conditions directly at the level of the `Describe` with `SkipDescribeIf(conditions, ...)`.

2021-05-26 22:06 UTC, pchaigno commented on test/k8sT/Egress.go
> +}
Why isn't this function declared next to `runEchoServer` and `assignEgressIP`?

2021-05-26 22:06 UTC, pchaigno commented on test/k8sT/manifests/egress-policy-demo.yaml
> +apiVersion: cilium.io/v2alpha1
Could we rename this file to something like `egress-nat-policy.yaml` to clarify it's not an egress network policy. It may not be obvious from context since files in this directory can be anything.

2021-05-26 22:06 UTC, pchaigno commented on test/k8sT/Egress.go
> +			})
I think we should also test with endpoint routes enabled and disabled. We already have one potential bug that is related to that and in general endpoint routes have a big impact on the BPF datapath's logic.

2021-05-26 22:06 UTC, pchaigno commented on test/k8sT/Egress.go
> +			time.Sleep(time.Second)
Could we check the BPF map content? It's clearly not ideal, but I'm worried a sleep in the code will cause a lot of flakes.

2021-06-08 07:01 UTC, pchaigno commented
Going back to draft to avoid having it show up in review queues.

2021-06-14 04:10 UTC, anfernee commented
Fixed the comments and this change is moved to #16447 so the fix and e2e test can be merged together.

2021-06-14 04:11 UTC, anfernee commented on test/helpers/kubectl.go
> +	replaced = strings.Replace(replaced, "-", "", -1)
I remember seeing `-` trailing in a namespace, which k8s doesn't like.

2021-06-14 04:11 UTC, anfernee commented on test/k8sT/Egress.go
> +		if !helpers.ExistNodeWithoutCilium() {
ack.

2021-06-14 04:11 UTC, anfernee commented on test/k8sT/Egress.go
> +			})
ack.

2021-06-14 04:11 UTC, anfernee commented on test/k8sT/manifests/egress-ip-deployment.yaml
> +              - "for i in $EGRESS_IPS; do ip address del $i dev enp0s8; done"
ack.

2021-06-14 04:11 UTC, anfernee commented on test/k8sT/manifests/egress-policy-demo.yaml
> +apiVersion: cilium.io/v2alpha1
ack.

2021-06-14 04:11 UTC, anfernee commented on install/kubernetes/cilium/templates/cilium-operator-clusterrole.yaml
> +  - ciliumegressnatpolicies
ack

2021-06-14 04:11 UTC, anfernee commented on test/k8sT/Egress.go
> +			helpers.HelperTimeout)).Should(BeNil())
It couldn't be easily extracted now, because it's a closure that depends on an external variable `echoPodYAML`, which will be used in `AfterAll` to cleanup. I'll add an comment here to remind myself.

2021-06-14 04:11 UTC, anfernee commented on test/k8sT/Egress.go
> +			time.Sleep(time.Second)
ack.

2021-07-30 02:25 UTC, joestringer commented
Hi @anfernee , were you expecting review on this? It's still marked as draft. If you'd like fresh review, please rebase again (just to make sure you pick up the latest core CI changes) and mark the PR as "Ready for review" using the button at the bottom of the page.

2021-07-30 16:57 UTC, anfernee commented
No, this has been moved to #16447 let me close this PR.

2021-07-30 16:57 UTC, closed without merging