doc: Deprecate managed etcd mode
cilium/cilium pull request #15464
Opened 2021-03-25 11:16 UTC by tgraf

With ClusterMesh no longer requiring Cilium to run in etcd mode and CRD
being the default for many releases, there is no longer any value in
maintaining the complexity for managed etcd. Mark it for deprecation.

The guides for new cluster installation are removed immediately. The
helm options will remain until 1.11.

Fixes: #14205

2021-03-25 11:21 UTC, kaworu requested changes
Needs `make -C install/kubernetes` to update `install/kubernetes/cilium/README.md`, other than that LGTM.

2021-03-25 11:56 UTC, nebril approved these changes

2021-03-25 12:27 UTC, qmonnet approved these changes

2021-03-25 12:29 UTC, qmonnet requested changes
Documentation/gettingstarted/k8s-install-managed.rst needs to be updated too, the GH complains about a broken reference in that file.

2021-03-25 12:31 UTC, qmonnet approved these changes

2021-03-26 07:36 UTC, kaworu approved these changes

2021-03-26 12:34 UTC, merged