ci: add EKS workflow
cilium/cilium pull request #15465
Opened 2021-03-25 13:10 UTC by nbusseneau

This workflow has been migrated and adapted from https://github.com/cilium/cilium-cli/ as part of the CI 3.0 initiative.

2021-03-25 14:32 UTC, nbusseneau commented
Testing via #15468.

2021-03-26 18:54 UTC, nbusseneau commented
Working run with latest version here: https://github.com/cilium/cilium/actions/runs/690892438

2021-03-30 17:29 UTC, aanm requested changes
Needs the GH actions pinned with a particular SHA

2021-04-02 12:49 UTC, nbusseneau commented
Waiting for #15482 to be merged before removing draft status.

2021-04-06 17:07 UTC, nbusseneau commented
Link to test run for this version of the workflow, from #15468 : https://github.com/cilium/cilium/actions/runs/723299009

2021-04-07 09:27 UTC, nebril approved these changes

2021-04-07 11:02 UTC, aanm approved these changes

2021-04-07 11:07 UTC, merged