ansible provisioner scripts for cilium.
cilium/cilium pull request #155
Opened 2016-10-03 08:11 UTC by mchalla

I separated them into roles so it easily allows running a single task. Still working on the cilium install scripts, will add them tomorrow.

2016-10-03 08:32 UTC, aanm approved these changes

2016-10-03 08:33 UTC, aanm commented
LGTM, waiting for @tgraf 's feedback

2016-10-04 00:57 UTC, tgraf requested changes
LGTM in general. Please make the destination directory configurable

2016-10-04 00:57 UTC, tgraf commented on contrib/ansible/roles/kernel/tasks/kernel_clean.yml
> +  shell: \rm -Rf /home/vagrant/net-next
This path must be made configurable somehow

2016-10-04 00:57 UTC, tgraf commented on contrib/ansible/roles/iproute2/tasks/iproute2_build.yml
> +  command: "{{ item }} chdir=/home/vagrant/iproute2"
This path must be made configurable

2016-10-04 00:57 UTC, tgraf commented on contrib/ansible/roles/iproute2/tasks/iproute2_clean.yml
> +  shell: \rm -Rf /home/vagrant/iproute2
This path must be made configurable

2016-10-04 00:57 UTC, tgraf commented on contrib/ansible/roles/iproute2/tasks/iproute2_fetch.yml
> +       dest=/home/vagrant/iproute2
This path must be made configurable

2016-10-04 00:57 UTC, tgraf commented on contrib/ansible/roles/iproute2/tasks/iproute2_install.yml
> +  shell: make install chdir=/home/vagrant/iproute2
This path must be made configurable

2016-10-04 00:57 UTC, tgraf commented on contrib/ansible/roles/kernel/tasks/kernel_build.yml
> +  command: "{{ item }} chdir=/home/vagrant/net-next"
This path must be made configurable

2016-10-04 00:57 UTC, tgraf commented on contrib/ansible/roles/kernel/tasks/kernel_fetch.yml
> +       dest=/home/vagrant/net-next
This path must be made configurable

2016-10-04 00:57 UTC, tgraf commented on contrib/ansible/roles/kernel/tasks/kernel_install.yml
> +  command: "{{ item }} chdir=/home/vagrant/net-next"
This path must be made configurable

2016-10-04 01:00 UTC, mchalla commented on contrib/ansible/roles/kernel/tasks/kernel_clean.yml
> +  shell: \rm -Rf /home/vagrant/net-next
Ok i will see how I can make /home/vagrant configurable. Everything else is relative to it.

2016-10-06 06:43 UTC, tgraf commented
Looks good, please rebase and clash both commits.

2016-10-06 06:44 UTC, tgraf approved these changes

2016-10-06 14:30 UTC, merged