cni-install: Add portmap binary if needed
cilium/cilium pull request #15508
Opened 2021-03-30 12:14 UTC by ChangyuWang

Add portmap binary when install cni

2021-03-30 20:43 UTC, joestringer requested changes
Thanks for the contribution! Looks mostly good to me, though the install section looks maybe a little more complicated than necessary. Would you mind making it more in line with the loopback CNI handling?

2021-03-30 20:43 UTC, joestringer commented on plugins/cilium-cni/cni-install.sh
> +fi
Is there any particular reason to add all of the extra conditions for cni chaining modes? Ideally we would have one variable for "User intends to use portmap", but given that it could be chained at any point I'm not sure that `${CILIUM_CNI_CHAINING_MODE}` will reliably tell us this.

The consequences of creating this binary if it's not needed seem very low to me, I think this could be treated almost exactly the same as the loopback case earlier on lines 65-71. Then we don't need to individually handle each possible chaining mode, we can just rely on it when necessary.

2021-03-30 23:33 UTC, aanm requested changes
As documented https://docs.cilium.io/en/v1.9/gettingstarted/cni-chaining-portmap/ Cilium has support for portmap in eBPF since Cilium 1.8. What is the motivation for adding this CNI plugin as part of the Cilium installation? With these changes we are increasing the artifacts Cilium is installing unnecessary.

2021-03-31 03:48 UTC, ChangyuWang commented
@aanm As a alternative choice if not support for portmap in eBPF.  So portmap plugin should be added when setting cni.chainingMode=portmap

2021-03-31 04:28 UTC, ChangyuWang commented on plugins/cilium-cni/cni-install.sh
> +fi
done

2021-04-01 17:46 UTC, joestringer commented
I think @aanm raises an interesting question. Cilium is a CNI, is it really Cilium's responsibility to provide other CNI binaries as part of a chaining configuration? This is suboptimal because if you need to update the other CNI, then Cilium has to be updated first. If Cilium does not deploy the portmap CNI, then you can separately version & update it.

We special-case the `loopback` binary because I guess that's fundamentally required for all CNIs to work correctly. But for all of the other CNIs we chain with (flannel, aws-cni, ...), Cilium assumes that you have already deployed the other CNI plugins which you intend to chain with. Following the same logic, we would assume that the user must install portmap CNI from the original distributor (https://github.com/containernetworking/plugins).

^ If this is the case, then the best option would be to make this clear in the documentation page (https://docs.cilium.io/en/stable/gettingstarted/cni-chaining-portmap/) that the portmap CNI is expected to be already deployed.

2021-04-14 11:06 UTC, errordeveloper reviewed
I second what @aanm said

2021-04-20 10:19 UTC, nbusseneau commented
I am converting this to draft until we resolve the discussions above (and should note that I share André's opinion as well).

2021-04-20 14:56 UTC, borkmann commented
Ack on what @joestringer & @aanm says, otherwise also the same case would have to be made for bandwidth plugin, etc. I don't think it would be suitable to maintain these via Cilium container since i) it's not a hard requirement for Cilium (and we'd like to keep the runtime to a bare minimum), and ii) Cilium implements these natively via eBPF. If there is anything missing from portmap or others, then we should fix it instead.

2021-06-20 13:12 UTC, closed without merging