daemon: add new option --allocator-list-timeout
cilium/cilium pull request #15538
Opened 2021-04-01 13:11 UTC by ArthurChiao

This enables user to configure how long they would like to wait before
successfully listed objects from kvstore. Especially, this determines the
agent restart frequency when clustermesh is enabled and remote kvstore
has connection problems: too many restarts in really large clusters pose
significant pressures on both k8s apiserver, local and remote kvstores.

Signed-off-by: ArthurChiao <arthurchiao@hotmail.com>

2021-04-01 13:13 UTC, ArthurChiao commented
Hi there, please see the commit message for the purpose of this patch.

Any comments welcomed.

2021-04-05 19:49 UTC, jibi requested changes
Thanks for the PR! Could you update the documentation with the new option please? Should be just a matter of running `make  -C Documentation update-cmdref check` and mentioning it in the [upgrade document](https://github.com/cilium/cilium/blob/master/Documentation/operations/upgrade.rst#new-options).

2021-04-06 06:48 UTC, ArthurChiao commented
Documentation updated, thanks! @jibi

2021-04-06 07:51 UTC, jibi approved these changes

2021-04-06 07:54 UTC, jibi commented
test-me-please

2021-04-06 08:51 UTC, jibi commented
test-me-please

2021-04-06 09:24 UTC, jibi commented
test-me-please

2021-04-06 09:32 UTC, qmonnet approved these changes
Looks good, thank you!

2021-04-06 09:33 UTC, jibi commented
@ArthurChiao there seems to be some issues with the CI, could you rebase your PR on top of master?

2021-04-06 09:34 UTC, qmonnet commented
The Travis error seems related?
> _level=fatal msg="Timeout while waiting for initial allocator state" subsys=allocator_

2021-04-06 09:47 UTC, ArthurChiao commented
I'll take a look, thank you!

2021-04-06 10:30 UTC, twpayne approved these changes

2021-04-06 12:00 UTC, jibi commented
test-me-please

2021-04-06 14:19 UTC, ArthurChiao commented
> The Travis error seems related?
>
> > level=fatal msg="Timeout while waiting for initial allocator state" subsys=allocator

Yes, unittests skipped the `option.Populate()` method, which leaved  the `option.Config.AllocatorListTimeout` un-initialized. Fixed it by initializing the field when creating `option.Config` object.

2021-04-06 14:24 UTC, jibi commented
test-me-please

2021-04-07 01:01 UTC, aanm requested changes
I thought I had reviewed this PR but I guess not... @ArthurChiao the `clustermesh-apiserver/main.go` likely needs this flag as well since it also uses the `pkg/allocator/allocator.go` cc @jrajahalme

2021-04-07 09:00 UTC, ArthurChiao commented
I'll take a look, thanks! @aanm

2021-04-07 12:08 UTC, ArthurChiao commented
Checked that the calling stack is: `NewVMManager() -> m.identityAllocator.InitIdentityAllocator() -> allocator.NewAllocator()`.

Code updated, please have a review, thanks! @aanm

2021-04-07 15:20 UTC, aanm approved these changes

2021-04-07 15:43 UTC, pchaigno commented
test-me-please

2021-04-07 15:43 UTC, pchaigno approved these changes

2021-04-07 23:57 UTC, merged