Kata: Mention incompatibility with host-reachable services or strict KPR in documentation
cilium/cilium pull request #15589
Opened 2021-04-07 14:42 UTC by qmonnet

Host-reachable services are not supported with Kata containers at this time. This is because they use socket-based load-balancing which requires hooking in the kernel at the socket level in the pods, but Kata containers are VMs with their own kernels, making it impossible.

Kube-proxy replacement in strict mode implies host-reachable services, and is therefore not supported either.

Update the documentation accordingly, to avoid users stumbling on it.

Preview:
![warning](https://user-images.githubusercontent.com/17001771/113882817-891a2980-97b5-11eb-855e-a6e7121d195b.png)

2021-04-07 14:46 UTC, borkmann approved these changes

2021-04-07 17:49 UTC, joestringer approved these changes
Thanks for documenting this. Couple of minor nits.

2021-04-07 17:49 UTC, joestringer commented on Documentation/gettingstarted/kata.rst
> +    Kata containers are virtual machines running with their own kernel.
nit, in general I believe that the indentation here should match the first character of `warning` (ie 3 spaces). In this case I don't think it has an impact but when you get multiple levels of indentation, it can start to be the difference between whether the indentation is rendered correctly or not.

2021-04-07 17:49 UTC, joestringer commented on Documentation/gettingstarted/kata.rst
> +
We could also add a reference here to https://github.com/cilium/cilium/issues/15437 to say something like `GitHub Issue 15437 tracks this limitation.` so users have a way to see whether the limitation is still live (+ interact on the issue), and we can also refer back later to see whether this warning is up to date.

2021-04-07 17:49 UTC, joestringer requested changes
I meant to request changes, but with those small fixups sorted we can merge this.

2021-04-08 09:47 UTC, pchaigno commented
Switching back to draft while @qmonnet is out.

2021-04-12 10:19 UTC, qmonnet commented
Thanks Joe for your feedback, I addressed the two points. New preview:
![warning](https://user-images.githubusercontent.com/17001771/114379508-cea57080-9b80-11eb-825c-992aaee5bc39.png)

<details><summary>Incremental diff</summary>

``` diff
diff --git a/Documentation/gettingstarted/kata.rst b/Documentation/gettingstarted/kata.rst
index 46120ad5ea5a..ac760892c8ae 100644
--- a/Documentation/gettingstarted/kata.rst
+++ b/Documentation/gettingstarted/kata.rst
@@ -77,13 +77,15 @@ Deploy Cilium release via Helm:
 
 .. warning::
 
-    Kata containers do not work with :ref:`host-services`, or with
-    :ref:`kube-proxy replacement <kubeproxy-free>` in strict mode. They should
-    be disabled with ``--set hostServices.enabled=false`` (default) and
-    ``--set kubeProxyReplacement=disabled`` (or ``partial``)
+   Kata containers do not work with :ref:`host-services`, or with
+   :ref:`kube-proxy replacement <kubeproxy-free>` in strict mode. These
+   features should be disabled with ``--set hostServices.enabled=false``
+   (default) and ``--set kubeProxyReplacement=disabled`` (or ``partial``).
 
-    Both rely on socket-based load-balancing, which is not possible given that
-    Kata containers are virtual machines running with their own kernel.
+   Both features rely on socket-based load-balancing, which is not possible
+   given that Kata containers are virtual machines running with their own
+   kernel. For kube-proxy replacement, this limitation is tracked with
+   `GitHub issue 15437 <https://github.com/cilium/cilium/issues/15437>`_.
 
 .. include:: k8s-install-validate.rst
 
```
</details>

2021-04-12 18:50 UTC, joestringer approved these changes

2021-04-12 21:53 UTC, merged