maps: Do not create cache for SNAT BPF maps
cilium/cilium pull request #15644
Opened 2021-04-12 07:59 UTC by brb

There is no need to create the user-space cache for the SNAT BPF maps, as they can be dumped with the `cilium bpf nat list` cli cmd.

(Discovered while taking a look into https://github.com/cilium/cilium/pull/15590).

2021-04-12 08:59 UTC, brb commented
test-me-please

2021-04-12 10:56 UTC, aanm requested changes
This will disable userspace sync with the datapath. i.e., if anything deletes an entry from the map the agent is not able to re-populate that entry.

2021-04-12 11:47 UTC, brb commented
> This will disable userspace sync with the datapath. i.e., if anything deletes an entry from the map the agent is not able to re-populate that entry.

@aanm Why does the agent need to repopulate an entry?

2021-04-12 11:51 UTC, aanm commented
> > This will disable userspace sync with the datapath. i.e., if anything deletes an entry from the map the agent is not able to re-populate that entry.
> 
> @aanm Why does the agent need to repopulate an entry?

 if anything deletes an entry from the bpf map, the agent will repopulate the entry automatically.

2021-04-12 12:33 UTC, brb commented
> if anything deletes an entry from the bpf map, the agent will repopulate the entry automatically.

In the agent we don't insert any SNAT entries. Only from the datapath. The agent only removes entries as a part of the CT GC.

2021-04-12 13:14 UTC, brb commented
net-next CI hit https://github.com/cilium/cilium/issues/15455.

2021-04-13 02:56 UTC, aanm commented
> > if anything deletes an entry from the bpf map, the agent will repopulate the entry automatically.
> 
> In the agent we don't insert any SNAT entries. Only from the datapath. The agent only removes entries as a part of the CT GC.

@brb oh I didn't know that, then please add this information in a comment in the code, (where the WithCache was) and in the commit description.

2021-04-13 16:34 UTC, brb commented
>  if anything deletes an entry from the bpf map, the agent will repopulate the entry automatically.

@aanm I'm still puzzled with your comment. Could you elaborate more?

2021-04-21 13:11 UTC, pchaigno approved these changes

2021-04-21 13:46 UTC, brb commented
Marking it as a draft until we have made a decision on how likely it's to have an error when deleting an SNAT mapping which could be resolved later by the cache resolver in the agent.

2022-07-11 07:46 UTC, brb commented
I think we cannot completely get rid of the SNAT BPF map cache in the agent, as the agent GCs SNAT entries, and if any of delete ops fail, w/o the cache it won't be able to retry the removal.

2022-07-11 07:46 UTC, closed without merging