option: auto enable K8sRequireIPv4PodCIDR in hostscope-legacy mode
cilium/cilium pull request #15732
Opened 2021-04-15 23:26 UTC by ArthurChiao

Fix: #15345

With `hostscope-legacy` mode IPAM and a flapping k8s apiserver, there are
possibilities that the PodCIDR the node is using will be overridden by an
auto-generated one from cilium-agent, resulting in interrupted pod traffic.
Refer to #15345 for more details.

This patch fixed the problem by auto enabling `K8sRequireIPv4PodCIDR` in
this mode, just like what we do in `kubernetes` mode and `cluster-pool` mode.

Signed-off-by: ArthurChiao <arthurchiao@hotmail.com>

2021-04-16 09:22 UTC, pchaigno commented
Asked for a review from @cilium/ipam folks.

2021-04-16 09:23 UTC, qmonnet commented
test-backport-1.8

2021-04-16 23:11 UTC, aanm requested changes
I'm not so sure about these changes. The `hostscope-legacy` mode was created to not depend on kubernetes, that is why we have the `kubernetes` IPAM mode, which should be used instead. Unless I am missing something, using `kubernetes` IPAM mode would likely fix https://github.com/cilium/cilium/issues/15345.

2021-04-17 05:26 UTC, ArthurChiao commented
> Unless I am missing something, using kubernetes IPAM mode would likely fix #15345.

Hi @aanm, you are right, using `kubernetes` IPAM could fix this problem.

>  The hostscope-legacy mode was created to not depend on kubernetes, that is why we have the kubernetes IPAM mode.

Sorry, **I didn't have this knowledge before**. Actually I could not clearly tell the difference between `hostscope-legacy` and `kubernetes` (I thought it's just a renaming). If I did, I will not open the issue and this PR.

Feel free to close this PR (and the issue) if you're done.

2021-04-17 18:05 UTC, aanm commented
> > Unless I am missing something, using kubernetes IPAM mode would likely fix #15345.
> 
> Hi @aanm, you are right, using `kubernetes` IPAM could fix this problem.
> 
> > The hostscope-legacy mode was created to not depend on kubernetes, that is why we have the kubernetes IPAM mode.
> 
> Sorry, **I didn't have this knowledge before** (I thought it's just a renaming). If I did, I would not open the issue and this PR.
> 
> Actually I'm still not clear about the difference between `hostscope-legacy` and `kubernetes`, as **in hostscope-legacy mode, agents also retrieve PodCIDRs from k8s annotations**, and fatal immediately if the retrieving failed.

@ArthurChiao that is correct, but those PodCIDRs annotations were previously set by Cilium. And the hostscope-legacy mode is either derived from the CIDR available in the k8s node or automatically generated from the local address, as you probably have seen from the described behavior in #15345
> 
> Feel free to close this PR (and the issue) if you're done.

2021-04-19 01:55 UTC, ArthurChiao commented
Make sense to me. Thanks! I'm closing this. @aanm

2021-04-19 01:55 UTC, closed without merging