issue_14922: Fixed the 429 response code handling
cilium/cilium pull request #15760
Opened 2021-04-18 16:41 UTC by Maddy007-maha

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well-written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

We have introduced a change for the support of handling 429 response code in the openapi.yaml.

Fixes: #14922

2021-04-19 08:13 UTC, Maddy007-maha commented
Signed-off-by: Maddy007-maha <mahadev.panchal@accuknox.com>

2021-04-19 21:06 UTC, christarazi reviewed
LGTM. A couple points:

1) Typically commit msgs should contain the subsystem that they are changing, in this case, it would be `api: Improve API ratelimit error messages`
2) I wonder if it would be useful to mention rate-limiting in the error msgs somehow just so we're more explicit. Rate-limiting is the only reason we'd return this error code, so no need to keep it ambiguous.

2021-04-20 13:23 UTC, Maddy007-maha commented
Thanks for your valuable comments
We have incorporated the review comments.

2021-04-20 16:40 UTC, christarazi approved these changes

2021-04-20 20:06 UTC, aanm approved these changes

2021-04-20 20:07 UTC, aanm commented
@Maddy007-maha can you run `make  generate-api` and submit the changes within the same commit? Thank you!

2021-04-21 11:35 UTC, Maddy007-maha commented
> @Maddy007-maha can you run `make generate-api` and submit the changes within the same commit? Thank you!

Hi @aanm Have incorporated your comments, kindly review

2021-04-21 14:35 UTC, aanm commented
test-me-please

2021-04-22 06:56 UTC, Maddy007-maha commented
> test-me-please

I have tested and verified these changes -> is this what you are asking

@aanm Can you bit elaborate more on your comment
Is anything pending?

Thanks

2021-04-22 12:50 UTC, aanm commented
> > test-me-please
> 
> I have tested and verified these changes -> is this what you are asking
> 
> @aanm Can you bit elaborate more on your comment
> Is anything pending?
> 
> Thanks

This is our trigger message that we have for jenkins to test the PR, it was not directed to you :-)

2021-04-22 12:50 UTC, aanm commented
test-1.16-netnext

2021-04-22 16:14 UTC, aanm commented
test-1.16-netnext

2021-04-24 01:42 UTC, aanm commented
@pchaigno it's the 2nd time in a row that this test fails. Care to take a look? :pray:

2021-04-24 11:18 UTC, pchaigno commented
> @pchaigno it's the 2nd time in a row that this test fails. Care to take a look? pray

@aanm I suspect it's just because this pull request isn't rebased against latest master, so Jenkins runs with https://github.com/cilium/cilium/pull/15714 but not https://github.com/cilium/cilium/pull/15780. I.e., another case of https://github.com/cilium/cilium/issues/15474.

@Maddy007-maha Could you rebase your branch against latest master?

2021-04-24 14:20 UTC, Maddy007-maha commented
> > @pchaigno it's the 2nd time in a row that this test fails. Care to take a look? pray
> 
> @aanm I suspect it's just because this pull request isn't rebased against latest master, so Jenkins runs with #15714 but not #15780. I.e., another case of #15474.
> 
> @Maddy007-maha Could you rebase your branch against latest master?

It was already rebased with the master, don't know why it got failed? Anyways I have rebased with Master now.

2021-04-24 14:23 UTC, pchaigno commented
test-me-please

2021-04-24 15:12 UTC, Maddy007-maha commented
> test-me-pleas

2021-04-24 16:41 UTC, Maddy007-maha commented
Is All OK? @pchaigno

2021-04-24 17:29 UTC, aanm commented
@Maddy007-maha please perform the rebased manually using git, and not the GitHub web UI. If you need help ping me on cilium slack

2021-04-25 08:28 UTC, Maddy007-maha commented
> @Maddy007-maha please perform the rebased manually using git, and not the GitHub web UI. If you need help ping me on cilium slack

Yeah I have rebased manually, not via GitHub GUI.

-Thank you

2021-04-26 06:08 UTC, Maddy007-maha commented
Is this pull request properly met the build requirements or any issues?

Do we need one more approval or build is failing?

As am new to this process could you please help us progressing on this PR.

-Thank you

2021-04-26 07:34 UTC, pchaigno requested changes
Please squash your commits and remove the merge commit. Once that is done, we will start the end-to-end tests.

2021-04-26 07:54 UTC, Maddy007-maha commented
> Please squash your commits and remove the merge commit. Once that is done, we will start the end-to-end tests.
> 
> EDIT: You'll also need to sign off as per [#15760 (comment)](https://github.com/cilium/cilium/pull/15760#issuecomment-826114591).

Thanks for the reply, I have done what you are requested  => by removing the last merge commit (which also resolves the signed off)

2021-04-26 08:31 UTC, pchaigno commented
test-me-please

2021-04-26 12:10 UTC, Maddy007-maha commented
> test-me-please

Out of all only 3 got failed while testing is there is an issue?

2021-04-27 14:12 UTC, Maddy007-maha commented
Is there any issue with 3 failures?

2021-04-27 16:15 UTC, aanm commented
test-1.16-netnext

2021-04-28 05:49 UTC, Maddy007-maha commented
> test-1.16-netnext (previous failure https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/371/)

Looks like it's a firewall issue?

Or is that an issue related to test-suite?

2021-04-28 06:57 UTC, pchaigno commented
test-gke

2021-04-28 17:30 UTC, aanm commented
@Maddy007-maha thanks for the changes!

2021-04-28 17:30 UTC, merged