doc: New performance benchmarks and tuning guide
cilium/cilium pull request #15907
Opened 2021-04-28 09:43 UTC by tgraf

Updated performance benchmark section and a brand new tuning guide
explaining how to achieve these results.

2021-04-28 10:46 UTC, qmonnet requested changes
A few typos & minor suggestions.

2021-04-28 10:46 UTC, qmonnet commented on Documentation/operations/performance/benchmark.rst
> +The following section contain performance benchmark numbers of various
```suggestion
The following section contains performance benchmark numbers of various
```

2021-04-28 10:46 UTC, qmonnet commented on Documentation/operations/performance/benchmark.rst
> +Cilium can outperform even the node to node baseline even though it is
```suggestion
Cilium can outperform even the node-to-node baseline even though it is
```

2021-04-28 10:46 UTC, qmonnet commented on Documentation/operations/performance/benchmark.rst
> +node which is still traversed for node to node baseline.
```suggestion
node which is still traversed for node-to-node baseline.
```

2021-04-28 10:46 UTC, qmonnet commented on Documentation/operations/performance/benchmark.rst
> +Considerable more CPU is spent in total. This is because more processes are
> Considerable more CPU is spent in total.

I would make explicit more than _what_.

2021-04-28 10:46 UTC, qmonnet commented on Documentation/operations/performance/benchmark.rst
> +The request/reply rate primarily measures the latency and efficient to handle
```suggestion
The request/reply rate primarily measures the latency and efficiency to handle
```

2021-04-28 10:46 UTC, qmonnet commented on Documentation/operations/performance/benchmark.rst
> +will handling situation with overwhelming connection rates better, leaving more
```suggestion
will handle situation with overwhelming connection rates better, leaving more
```

2021-04-28 10:46 UTC, qmonnet commented on Documentation/operations/performance/benchmark.rst
> +in particular illustrates the overall cost of iptables which is optimized to
```suggestion
This benchmark outlines major differences between the tested configurations. In
particular, it illustrates the overall cost of iptables which is optimized to
```

2021-04-28 10:46 UTC, qmonnet commented on Documentation/operations/performance/benchmark.rst
> +nodes connected by a 100Gbit network interface.
```suggestion
nodes connected by a 100Gbit/s network interface.
```

2021-04-28 10:46 UTC, qmonnet commented on Documentation/operations/performance/benchmark.rst
> +will handling situation with overwhelming connection rates much better, leaving
```suggestion
will handle situation with overwhelming connection rates much better, leaving
```

2021-04-28 10:46 UTC, qmonnet commented on Documentation/operations/performance/tuning.rst
> +jumbo frames then Cilium will automatically make us of it.
```suggestion
jumbo frames then Cilium will automatically make use of it. 
```

2021-04-28 10:46 UTC, qmonnet commented on Documentation/operations/performance/tuning.rst
> +performance:
```suggestion
performance.
```

Would be interesting for users, I think, to have a one-line description of what each optimisation does.

2021-04-28 10:46 UTC, qmonnet commented on Documentation/operations/performance/benchmark.rst
> +The following section contain performance benchmark numbers of various
Sorry about that - I thought this comment had been automatically removed when I refreshed the page on the latest commit :/.

2021-04-28 15:34 UTC, lizrice commented on Documentation/operations/performance/benchmark.rst
> +achieved with a particular configuration. All or most configuration will be
```suggestion
achieved with a particular configuration. All or most configurations will be
```

2021-04-28 17:25 UTC, aanm approved these changes
Just one small nit. LGTM

2021-04-28 17:25 UTC, aanm commented on Documentation/operations/performance/benchmark.rst
> +found in https://github.com/cilium/perfeval. All scripts in this document refer
can be found in https://github.com/cilium/cilium-perf-networking

2021-04-28 22:55 UTC, ianvernon reviewed
Nice work! Just one small grammatical nit

2021-04-28 22:55 UTC, ianvernon commented on Documentation/operations/performance/benchmark.rst
> +In this test, 32 processes are opening 32 parallel TCP connection. Each process
connection --> connections

2021-04-29 09:09 UTC, borkmann commented
@ianvernon @aanm @lizrice Note that this PR still needs to switch its base to https://github.com/cilium/cilium/commits/pr/tgraf/performance-docs given we've pushed various improvements on top which should at least address some of your feedback.

2021-04-29 19:45 UTC, tgraf commented
Superseded by #15943

2021-04-29 19:45 UTC, closed without merging