.github: Don't persist credentials in repository
cilium/cilium pull request #16052
Opened 2021-05-07 19:54 UTC by pchaigno

When using actions/checkout, the default behavior [1] is to persist git credentials in the checked out code. This is ill-advised, so let's disable with `persist-credentials`.

1 - https://github.com/actions/checkout#usage
2 - https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

2021-05-07 20:43 UTC, joestringer approved these changes
SGTM. Do we need to test these before we merge them to make sure we're not relying on them?

2021-05-07 21:05 UTC, pchaigno commented
> Do we need to test these before we merge them to make sure we're not relying on them?

I'd prefer if we can, yes. But it seems GitHub workflows are on strike in this PR...

2021-05-10 09:30 UTC, nbusseneau requested changes

2021-05-10 09:30 UTC, nbusseneau commented on .github/workflows/bpf-checks.yaml
> +        persist-credentials: false
`persist-credentials` should be within the `with` block with the other arguments ;)

2021-05-10 09:31 UTC, nbusseneau commented
> I'd prefer if we can, yes. But it seems GitHub workflows are on strike in this PR...

This is because of the syntax error outlined above: https://github.com/cilium/cilium/actions/runs/821429393

2021-05-10 09:55 UTC, pchaigno commented on .github/workflows/bpf-checks.yaml
> +        persist-credentials: false
:facepalm:

2021-05-10 10:04 UTC, nbusseneau requested changes

2021-05-10 10:04 UTC, nbusseneau commented on .github/workflows/codeql-analysis.yml
> +      persist-credentials: false
Missed this one :D

2021-05-10 10:05 UTC, nbusseneau approved these changes
Otherwise LGTM.

2021-05-10 12:57 UTC, pchaigno commented
Team reviews are in and all GitHub workflows are passing. Marking as ready to merge.

2021-05-10 13:58 UTC, merged