bpf_host: emit '-> network' traces for egress packets
cilium/cilium pull request #16082
Opened 2021-05-11 12:56 UTC by navarrothiago

bpf_host: emit '-> network' traces for egress packets

See the issue below for the full context. The caveat is, this program is only attached to the native device egress if the host firewall is enabled, so there still won't be any TRACE_TO_NETWORK visibility if that's not the case.

I've also added handle_to_netdev_ipv4() to clean up to_netdev() a bit, to bring it on par with the ipv6 handling.

bpf_host: emit '-> network' traces for packets leaving the node when Host Firewall are enabled

Based on: #13485
Fixes: #12561

Co-authored-by: Thiago Navarro <navarro@accuknox.com>
Signed-off-by: Timo Beckers <timo@isovalent.com>
Signed-off-by: Thiago Navarro <navarro@accuknox.com>

2021-05-21 15:15 UTC, pchaigno reviewed
This is a bit hard to review as is. Could you separate in multiple logical commits? For example, the changes to take monitor into account in existing traces (what #12561 is about) could be one commit, new traces would be another commit, and general cleanups (e.g., new comments) would be a last commit.

2021-05-21 15:15 UTC, pchaigno commented on bpf/lib/common.h
> +#define	CB_CT_MONITOR		CB_CT_STATE
What happened in this file?

2021-05-21 15:15 UTC, pchaigno commented on bpf/lib/trace.h
> +	 */
This sort of cleanup should be in a separate commit.

2021-05-24 20:57 UTC, navarrothiago commented
> new traces would be another commit

Thank you for you comments. Sorry, but I did not understand. What do you mean by new traces? AFAIU, the issue is related to this [comment](https://github.com/cilium/cilium/issues/12561#issuecomment-705089371), right? So, `new trace` would be the `issue`. Let me know if I got your point.

2021-05-26 12:49 UTC, pchaigno requested changes
I think we should exclude the second commit for now. The other two commits look :+1: to me.

Please don't forget to add Timo has a coauthor of the last commit (via `Signed-off-by`, `Co-authored-by`, or both).

2021-05-26 12:49 UTC, pchaigno commented on bpf/lib/nodeport.h
> +	send_trace_notify(ctx, TRACE_TO_NETWORK, 0, 0, 0, 0, ret, monitor);
I think we should skip the commit that adds `TRACE_TO_NETWORK` traces for now. See the discussion at https://github.com/cilium/cilium/pull/14696. These additional traces will get very noisy quickly so there's a bit more work needed before we can introduce them.

2021-05-26 13:15 UTC, pchaigno commented
@navarrothiago Could you also fix the second commit's title? Right now, I doesn't provide any useful/actionable information.

2021-05-26 14:49 UTC, pchaigno approved these changes

2021-05-26 19:32 UTC, pchaigno commented
test-me-please

2021-05-27 12:43 UTC, navarrothiago commented
@pchaigno, should we re-trigger the jobs?

2021-05-27 13:33 UTC, pchaigno commented
test-runtime

2021-05-27 17:15 UTC, pchaigno commented
Team reviews are covered and tests are passing. Marking as ready to merge.

2021-05-28 22:15 UTC, merged