Adding error checks for ctx_load_bytes.
cilium/cilium pull request #16138
Opened 2021-05-13 12:44 UTC by trvll

The function ctx_load_bytes() was being called without checking for return errors.
This could let to a possible evaluation of an uninitialized variable.

Added a verification to drop packets when ctx_load_bytes() returns error.

Signed-off-by: Thales Paiva thales@accuknox.com

Fixes: #16076

2021-05-21 15:05 UTC, pchaigno requested changes
Couple styling problems.

2021-05-21 15:05 UTC, pchaigno commented on bpf/lib/ipv6.h
> +	    return DROP_INVALID;
Indentation is broken here.

2021-05-21 15:05 UTC, pchaigno commented on bpf/lib/ipv6.h
> +	if(ctx_load_bytes(ctx, off + offsetof(struct ipv6hdr, hop_limit), &hl, sizeof(hl)) < 0)
Needs a space after `if`.

2021-05-27 21:21 UTC, pchaigno approved these changes

2021-05-27 21:21 UTC, pchaigno commented
test-me-please

2021-06-02 19:18 UTC, nathanjsweet commented
k8s-1.21-kernel-4.9 is running into #13011.
Marking as ready-to-merge. I'll merge tomorrow if there are no intervening objections.

2021-06-03 14:46 UTC, merged