.github: Set commit status to error when workflow are cancelled
cilium/cilium pull request #16155
Opened 2021-05-14 15:23 UTC by pchaigno

I believe commit status 'error' is more appropriate than 'pending' when a workflow was cancelled.

Cancellation of a workflow might happen after manual action by a contributor (in which case 'pending' might be fine), but it can also happen for other automatic reasons (not yet determined). In any case, having the state appear as an error clarifies that the author, janitor, and reviewers should take notice of that workflow's result.

2021-05-14 15:31 UTC, aanm approved these changes

2021-05-14 20:05 UTC, nbusseneau requested changes
> it can also happen for other automatic reasons (not yet determined)

Did you see this happen? The only case I've seen workflows get cancelled is when they hit the timeout, which is expected.

I personally still think both user cancellation and timeout cancellation resulting in `pending` is better than marking the job as failed, because when a job is cancelled it should simply be retriggered. Keeping it marked as pending makes it clearer IMO.

In any case, if we do want to move forward with marking jobs as failure, then I would recommend we instead just refactor both in the existing failure state by replacing:

```yaml
- name: Set commit status to failure
   if: ${{ failure() }}
```

with

```yaml
- name: Set commit status to failure
   if: ${{ !success() }}
```

(or `failure() || cancelled()`)

2021-05-14 20:29 UTC, pchaigno commented
> Did you see this happen? The only case I've seen workflows get cancelled is when they hit the timeout, which is expected.

I've seen this is https://github.com/cilium/cilium/actions/runs/836840304, and it is indeed because of the 30 minutes timeout. I was not aware that was a potential reason for cancellation.

> I personally still think both user cancellation and timeout cancellation resulting in `pending` is better than marking the job as failed, because when a job is cancelled it should simply be retriggered. Keeping it marked as pending makes it clearer IMO.

Ideally, we'd have a `cancelled` status, but we don't :'-(. Marking timeouts as pending is very weird to me: it's a failure case and whoever is responsible for the PR should check it to see what happened. They should not just retry blindly. It's also a behavior that differs from what Jenkins does (and maybe from what GitHub itself does in `pull_request` events). In particular, for non-required GitHub checks, if I'm a janitor and I see them as `pending`, I'm likely to think the PR author just didn't trigger them because it was unnecessary.

We can raise this on Monday to get the opinion of more folks.

> In any case, if we do want to move forward with marking jobs as failure, then I would recommend we instead just refactor both in the existing failure state by replacing:

:+1: I'll make the change.

2021-06-28 16:31 UTC, nbusseneau approved these changes

2021-06-28 23:06 UTC, merged