docs: gsg/operations - use parsed-literal for all blocks referring SCM_WEB
cilium/cilium pull request #16173
Opened 2021-05-17 12:07 UTC by bmcustodio

2021-05-17 12:08 UTC, rolinh approved these changes

2021-05-17 12:10 UTC, qmonnet requested changes
I'd recommend going through the backport process explained in the docs. You need a couple of things on this PR, including
- prefixing the title to make it clear it's for 1.9
- formatting the commit log adequately so it contains the upstream SHA, and your own SOB tag in addition to Timo's
- adding to PR's description the command for easily labelling the initial PR as backported, once this one is merged.

2021-05-17 13:02 UTC, qmonnet approved these changes

2021-05-17 13:41 UTC, tklauser approved these changes

2021-05-17 13:42 UTC, tklauser commented
Docs changes only and the respective GH action passed, no need to run full CI. And all reviews are in - merging.

2021-05-17 13:42 UTC, merged

2021-05-19 20:02 UTC, ti-mo commented
Thanks! :+1: