Invalid helm value in the documentation (bgp)
cilium/cilium pull request #16263
Opened 2021-05-21 13:52 UTC by xentobias

Helm value "bgp.announce.lbIP" is invalid, it should be "bgp.announce.loadbalancerIP".
(Source: https://github.com/cilium/cilium/tree/v1.10.0/install/kubernetes/cilium#values)

2021-05-21 13:58 UTC, qmonnet approved these changes
Thanks!
(Please make sure to sign-off your commit as explained at the link above.)

2021-05-21 18:53 UTC, christarazi approved these changes

2021-05-21 18:55 UTC, christarazi requested changes
Please state what the commit is changing. So a commit title such as "docs: Fix Helm instructions for BGP" can work and please make sure the commit is signed off as Quentin mentioned

2021-05-21 23:22 UTC, christarazi commented
The sign off I think needs to have the email within angle brackets, `<address@email.com>`

2021-05-22 05:45 UTC, christarazi approved these changes
Thanks for the PR!

2021-05-25 08:50 UTC, merged