Fix overwriting iptables for kube-proxy free installation
cilium/cilium pull request #16264
Opened 2021-05-21 14:26 UTC by Stijn98s

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Updated the restore iptables command because this command wasn't working on Ubuntu 20.10 arm64.

2021-05-21 14:37 UTC, qmonnet reviewed
Thanks! The change looks good, but I would be curious to understand why the previous command wouldn't work. What error did you get?

2021-05-21 14:49 UTC, Stijn98s commented
Didn't get a clear error. The changes didn't got applied. These errors occured.

`Can't open /dev/fd/63: No such file or directory`
and
`Warning: iptables-legacy tables present, use iptables-legacy-save to see them`

2021-05-21 15:08 UTC, qmonnet approved these changes
Ah, did you run the command with `sudo`? [Process substitution](https://unix.stackexchange.com/a/279889/70764) might be at play here.

If so, let's update the command indeed to avoid other people to hit the same issue.

2021-05-21 15:20 UTC, Stijn98s commented
Yea, added `sudo` to both commands. Still didn't work

2021-05-21 15:24 UTC, pchaigno approved these changes

2021-05-21 15:24 UTC, qmonnet commented
Yes, I suppose this is _because_ of the `sudo` that the `<(...)` syntax didn't work. See the answers I linked if you want the details. All good for me!

2021-05-21 15:34 UTC, aanm reviewed
@qmonnet but wouldn't we need something like `sudo iptables-save | grep -v KUBE | sudo iptables-restore`? at the very least: `sudo su -c "iptables-save | grep -v KUBE | iptables-restore"`?

2021-05-21 15:45 UTC, qmonnet commented
True, we can also add the `sudo` everywhere. This would require updating the other `iptables-save` commands in the document, though.

(At least with the new form in this commit, a missing `sudo` will fail with `Fatal: can't open lock file /run/xtables.lock: Permission denied`, which is a better indication than what we had previously.)

2021-05-25 14:09 UTC, brb commented
@Stijn98s Can you try running the previous cmd after entering the root with `sudo -s`?

2021-05-25 18:44 UTC, aanm requested changes
We would at least need the following changes

2021-05-25 18:44 UTC, aanm commented on Documentation/gettingstarted/kubeproxy-free.rst
>        # Run on each node:
This would need something like `"Run on each node with root permissions"`

2021-07-16 01:43 UTC, aanm commented
@Stijn98s can you rebase the PR? :pray:

2021-09-15 09:58 UTC, aanm approved these changes

2021-09-15 10:13 UTC, merged