fix the order of blocks for bgp config mount and resources fixes #16272
cilium/cilium pull request #16273
Opened 2021-05-21 20:29 UTC by rkage

Signed-off-by: Nick M <4718+rkage@users.noreply.github.com>

Fixes: #16272

```release-note
Re-order helm template blocks to address rendering error when using bgp.enabled and operator.resources
```

2021-05-22 05:38 UTC, christarazi requested changes
Thanks for the PR! 

Could you rework the commit title to be something like, `install: Fix ordering of operator resources` and then move the "fixes #16272" into a new line inside the commit msg body? 

Also, in general the release note should be written so that a reader can understand the impact. For example, in this case it would be `Fix bug with the Helm chart where a user couldn't enable BGP and set the Operator resources`.

2021-05-22 20:56 UTC, christarazi commented
Seems like there have been some merge commits made in order to rebase on master. Could you simply rebase your change on the latest master, without the need to merge branches into each other?

2021-05-24 18:21 UTC, christarazi approved these changes
Thanks! :rocket:

2021-05-24 18:22 UTC, christarazi commented
test-net-next

2021-05-25 06:37 UTC, kkourt approved these changes

2021-06-01 16:58 UTC, nathanjsweet approved these changes

2021-06-02 19:13 UTC, merged