k8s, node: Restore router IPs (`cilium host`) from K8s resource
cilium/cilium pull request #16307
Opened 2021-05-25 19:48 UTC by christarazi

Previously, after a node reboot, Cilium would allocate a new router IP
and append it slice of node IPs. Since the node IPs have already been
synced to the K8s resource, meaning there are already IPs present (from
the previous Cilium instance), the router IP is appended to the slice.
In other parts of Cilium, it is assumed that the router IP is the first
node IP (first element of the slice). Since the new router IP has been
appended to the end, it is no longer where it is expected, aka no longer
the first element. This causes a mismatch of which router IP is to be
used. There should only ever be one router IP (one IPv4 or one IPv6).

In case of a node reboot, the router IPs cannot be restored because they
are wiped away due to the Cilium state dir being mounted as a tmpfs.
This commit fixes this to restore the router IPs from the K8s resource
(Node or CiliumNode) if they are present in the annotations. This
prevents the possibility of having more than one router IP, as described
above.

Signed-off-by: Chris Tarazi <chris@isovalent.com>

2021-05-25 20:09 UTC, nathanjsweet reviewed
I can't think of anything important offhand, but I guess there is the possibility that some kind of fast restart with a swapped NIC in a cloud provider could turn this into a race condition. However, that's a very edge case.

2021-05-26 07:18 UTC, brb reviewed
What's going to happen if podCIDR will change? Will it still try to restore potentially obsolete router IP?

2021-05-26 17:37 UTC, christarazi commented
> What's going to happen if podCIDR will change? Will it still try to restore potentially obsolete router IP?

@brb Do we support pod CIDRs changing anyway?

Regardless of that, I'm thinking we need to determine the priority of the router IPs that we restore. I'm assuming that the local filesystem is the most up-to-date source of truth. An approach would be to load the router IPs from the K8s resource like this PR already does, then read the filesystem state. If the state contains a router IP as well, then compare it against the one from the K8s resource. If there's a mismatch, then we should warn loudly and we will probably want to switch over to it anyway. 

With a system like the above in-place, then we are not actually changing the behavior of Cilium by much. Only the case where the router IP doesn't exist on the filesystem, but does exist in the K8s resource, which occurs on a node reboot.

2021-05-26 19:19 UTC, christarazi commented
User confirmed that this fixes their issue: https://github.com/cilium/cilium/issues/16279#issuecomment-849035211

2021-05-26 19:31 UTC, christarazi commented
test-me-please

2021-05-27 18:51 UTC, christarazi commented
test-me-please

2021-05-28 22:45 UTC, aanm requested changes
>> What's going to happen if podCIDR will change? Will it still try to restore potentially obsolete router IP?
>
> @brb Do we support pod CIDRs changing anyway?

Well, it's not up to Cilium as it will simply receive the podCIDR from Kubernetes.

There is at least one case where this patch might cause issues.

1. Stop kubelet
2. Delete node with `kubectl delete node <node-name>`
3. Restart kubelet
4. Kubernetes will assign a new podCIDR to that node
5. Cilium will wrongly restore an IP address that does not belong to the podCIDR.

2021-05-28 22:45 UTC, aanm commented on pkg/k8s/init.go
> +	if option.Config.EnableHostIPRestore {
nit: negate this to do an early return

2021-06-01 20:23 UTC, christarazi commented
Synced with @aanm offline. The above feedback turned out to be more relevant for issue https://github.com/cilium/cilium/issues/6469, which we should tackle at another time. However, we also realized that we should validate the IP chosen for restoration to check whether it actually belongs to the pod CIDR of the node. If it does not, then we will discard it and not restore it.

2021-06-01 21:01 UTC, christarazi commented
test-me-please

2021-06-01 21:46 UTC, aanm approved these changes

2021-06-01 21:59 UTC, michi-covalent approved these changes

2021-06-01 23:54 UTC, christarazi commented
Pushed a [small change](https://github.com/cilium/cilium/compare/c9af154fa064ed728cd179d3f37c47c70ebda076..68cae4c5f151a520ec3497ea92915e653b80bdee) that shouldn't require a re-run. CI has [passed](https://github.com/cilium/cilium/pull/16307#issuecomment-852442376).

2021-06-04 12:16 UTC, merged