node: Add WireguardPubKey to ToCiliumNode
cilium/cilium pull request #16420
Opened 2021-06-03 14:56 UTC by gandro

This ensures the WireGuard public key is preserved when converting a
`nodeTypes.Node` object to a `CiliumNode` CRD. This conversion is currently
is only used for attaching external workloads (which has no support for
WireGuard at the moment anyways), but it might be used in other places in the
future, therefore we should ensure that it propagates all information
correctly.

I discovered this while validating WireGuard support in Clustermesh.
This PR does not fix any outstanding bugs.

2021-06-03 16:29 UTC, gandro commented
test-me-please

2021-06-03 19:20 UTC, aanm requested changes
Can you add the entry:
```
/pkg/node @cilium/agent 
```

to the CODEOWNERS file? Thanks

2021-06-07 13:22 UTC, gandro commented
test-me-please

2021-06-07 14:17 UTC, aanm approved these changes

2021-06-07 15:28 UTC, gandro commented
test-me-please

2021-06-07 19:31 UTC, christarazi approved these changes

2021-06-08 12:29 UTC, merged