pkg/option: Fix default assignment of EnableWellKnownIdentities
cilium/cilium pull request #16434
Opened 2021-06-04 15:41 UTC by mauriciovasquezbernal

Fix a "typo" in the variable assignment. It wasn't causing any trouble because both `defaults.EnableEndpointRoutes` and `defaults.EnableWellKnownIdentities` are `true`.

2021-06-08 08:31 UTC, errordeveloper approved these changes
Thanks, well spotted!

2021-06-15 07:02 UTC, borkmann approved these changes

2021-06-15 07:03 UTC, borkmann commented
test-me-please

2021-06-16 22:43 UTC, aanm requested changes
Thanks for the changes, can you add the following to the commit message? Thank you
```
Fixes: 09d9e1e0e2d9 ("policy: Disable well-known identities for non-managed etcd")
```

2021-06-16 22:45 UTC, aanm commented
Marking for backport to all branches just in case we change the default of `EnableEndpointRoutes` which would end up enabling `EnableWellKnownIdentities` by accident.

2021-06-16 23:35 UTC, mauriciovasquezbernal commented
> Thanks for the changes, can you add the following to the commit message? Thank you
> 
> ```
> Fixes: 09d9e1e0e2d9 ("policy: Disable well-known identities for non-managed etcd")
> ```

I already had that on the commit message. (I'm just using a shorter commit reference but I think it doesn't matter, does it?).

2021-06-17 11:09 UTC, aanm approved these changes

2021-06-17 11:10 UTC, aanm commented
ah thanks, the PR description mislead me.

2021-06-17 11:10 UTC, merged