implement external IPAM
cilium/cilium pull request #16451
Opened 2021-06-07 04:19 UTC by answer1991

# External IPAM

External IPAM backend enable ipamd run as a sidecar container with cilium-agent. When allocate/release IP, the socket call chain like: kubelet(cni) -> cilium-agent -> ipamd.
cilium-agent use [ipam API Client](https://github.com/cilium/cilium/blob/master/api/v1/client/ipam/ipam_client.go) to allocate/release IP.

# What's Next

1. We may set cilium-agent config `--k8s-require-ipv4-pod-cidr` to be true, if we must set the Pod CIDR route to the cilium-host device. And ipamd is responsible for setting the Node annotation `io.cilium.network.ipv4-pod-cidr`.
2. Node annotation `io.cilium.network.ipv4-pod-cidr` value support multi CIDR as a string combine with ','.

2021-06-08 16:52 UTC, aanm requested changes
Hello @answer1991 thank you for your PR. I've looked at the proposed changes and code-wise they looked good. However, we would need more information about some of the use cases for this change and given the extension of this change a design document where this can be discussed. Thank you!

2021-06-08 17:13 UTC, joestringer commented
In particular I would be interested in a discussion of the contrast between this approach vs. CRD IPAM, which is intended to allow external components to help control IPAM.

Link: https://docs.cilium.io/en/latest/concepts/networking/ipam/crd/

2021-06-10 03:43 UTC, answer1991 commented
> given the extension of this change a design document where this can be discussed

Thanks @aanm . Should I post a google doc to discuss about it ?

2021-06-10 04:07 UTC, answer1991 commented
> In particular I would be interested in a discussion of the contrast between this approach vs. CRD IPAM, which is intended to allow external components to help control IPAM.

@joestringer Thanks for the reply. I know that CRD IPAM is used to extend the custom IPAM. However, I think it also has its limitations. For examples:

1. Different cloud provider must modify the [CiliumNode spec](https://github.com/cilium/cilium/blob/master/pkg/k8s/apis/cilium.io/v2/types.go#L326) to implement their function, which makes [CiliumNode spec](https://github.com/cilium/cilium/blob/master/pkg/k8s/apis/cilium.io/v2/types.go#L326) more and more complexity and obscure.
2. CRD IPAM is based on Node's Pod CIDRs, However, some CNI's IPAM is based on higher device topo's CIDRs. For example, macvlan's CIDR may based on TOR, Nodes on the same TOR are shared the same CIDR.

So, I think Cilium should define the IPAM API(already do) and cilium-agent use this IPAM API client to call an external IPAM implement daemon. Azure, AWS, Alibaba and etc should provide an IPAM daemon based on their self CRD or other any other implement we do not care, instead of modify  [CiliumNode spec](https://github.com/cilium/cilium/blob/master/pkg/k8s/apis/cilium.io/v2/types.go#L326) and do some hack.

2021-06-11 04:26 UTC, answer1991 commented
> > > given the extension of this change a design document where this can be discussed
> > 
> > 
> > Thanks @aanm . Should I post a google doc to discuss about it ?
> 
> @answer1991 yes, that would be perfect!

@aanm Is there any example docs? And shall I post the doc into the specified workspace or post to my personal docs?

2021-06-11 10:15 UTC, aanm commented
> > > > given the extension of this change a design document where this can be discussed
> > > 
> > > 
> > > Thanks @aanm . Should I post a google doc to discuss about it ?
> > 
> > 
> > @answer1991 yes, that would be perfect!
> 
> @aanm Is there any example docs? And shall I post the doc into the specified workspace or post to my personal docs?

@answer1991 something like https://docs.google.com/document/d/1DCDrgydIrLHID6k0sP1MMiOjRu5Q03nAjwpAsRVfkQc/edit?usp=sharing

2021-06-14 12:31 UTC, answer1991 commented
> @answer1991 something like https://docs.google.com/document/d/1DCDrgydIrLHID6k0sP1MMiOjRu5Q03nAjwpAsRVfkQc/edit?usp=sharing

I have no rights to visit this page, and I have request the permission. Please approve it, thanks @aanm

2021-06-14 19:22 UTC, jrajahalme commented
Converrted this to draft as design discussion is to be had before merging.

2021-06-14 19:58 UTC, joestringer commented
Just a couple of notes that might be helpful for further exploring this topic:-

> Different cloud provider must modify the CiliumNode spec to implement their functions, which makes CiliumNode spec more and more complexity and obscure.

For what it's worth, there is a benefit tradeoff here: It can be easier to debug what's going on if there's a resource that contains some intended state of the system, rather than for instance relying on the cilium-agent and IPAM agent to sufficiently log its activities. Pinpointing things like "I expect that the CiliumNode should have ____ state, and it [does/does not] include that information" can point towards either cilium-agent or cilium-operator being the source of a problem.

> CRD IPAM is based on Node's Pod CIDRs, However, some CNI's IPAM is based on higher device topo's CIDRs. For example, macvlan's CIDR may based on TOR, Nodes on the same TOR share the same CIDR.

I believe this is the case for [AWS ENI IPAM](https://docs.cilium.io/en/latest/concepts/networking/ipam/eni/) as well, it acquires individual IPs from the cloud API and populates the pool. Do you see some restriction in the current mechanism that forces node-by-node CIDRs?

2021-06-14 23:06 UTC, aanm commented
> > @answer1991 something like https://docs.google.com/document/d/1DCDrgydIrLHID6k0sP1MMiOjRu5Q03nAjwpAsRVfkQc/edit?usp=sharing
> 
> I have no rights to visit this page, and I have request the permission. Please approve it, thanks @aanm

I've contacted the original author. Ping me if you still haven't access in 2 days.

2021-08-22 18:24 UTC, closed without merging