test: Remove special case for host identity when remote-node identity is disabled
cilium/cilium pull request #16450
Opened 2021-06-06 15:57 UTC by romanspb80

The test-case "Installing fromEntities host and world policy" with disabled remote-node identity is no longer needed due to lack of any network endpoints outside of the cluster.

Fixes: #15491

Signed-off-by: Roman Ptitcyn romanspb@yahoo.com

2021-06-07 14:08 UTC, pchaigno approved these changes

2021-06-07 14:08 UTC, pchaigno commented
test-me-please

2021-06-09 17:13 UTC, romanspb80 commented
I think the tests are stuck

2021-06-09 19:44 UTC, christarazi commented
test-1.20-4.19

2021-06-09 19:44 UTC, christarazi commented
test-1.21-4.9

2021-06-14 19:18 UTC, jrajahalme approved these changes

2021-06-14 23:22 UTC, joestringer commented
Was there a discussion about this anywhere? I don't see a detailed analysis either in the issue #15491 or here in this PR.

> The test-case "Installing fromEntities host and world policy" with disabled remote-node identity is no longer needed due to lack of any network endpoints outside of the cluster.

From what I can tell, this test was about policy handling for remote nodes _in_ the cluster, where the "world" entities policy is expected to allow traffic directly from remote nodes in native mode + remote-node-identity=disabled.

Can you explain further what you mean by it is no longer needed? Do we no longer want to make such a guarantee? Or you think that this behaviour is already covered by another test in the testsuite?

2021-06-14 23:23 UTC, joestringer requested changes
Please provide a more concrete rationale before we merge this (see comment above).

2021-06-15 18:40 UTC, joestringer commented
From out-of-band discussion with @pchaigno it sounds like basically this test code being removed is either (1) not run in regular test environments or (2) not effective in evaluating whether the remote-node identity option is performing correctly, so the extra test code is unnecessary.

@romanspb80 would you mind updating the commit message to include the above detail as well? If for whatever reason we find out in future that this test code was actually useful or necessary, it could be helpful to be able to read back through the git commit logs to find these details out.

With that I think this should be OK to merge.

2021-06-15 21:08 UTC, romanspb80 commented
> @romanspb80 would you mind updating the commit message to include the above detail as well? If for whatever reason we find out in future that this test code was actually useful or necessary, it could be helpful to be able to read back through the git commit logs to find these details out.
> 
> With that I think this should be OK to merge.

OK. Done.
Thanks

2021-06-15 21:24 UTC, joestringer commented
:+1: Only change was to update the commit message, good to merge.

@romanspb80 just to let you know in future, if you configure your email / name in git using the following commands, then you can use `git commit -s` to sign off your commits, so then you can get the standard formatting of the signoff line without needing to manually type out your name / email each time:

```
git config --global user.name "FIRST_NAME LAST_NAME"
git config --global user.email "MY_NAME@example.com"
```

2021-06-15 21:24 UTC, joestringer approved these changes

2021-06-15 21:25 UTC, merged