test: Spring cleaning of K8sServicesTest
cilium/cilium pull request #16470
Opened 2021-06-08 12:09 UTC by brb

This is a preparatory work before restructuring the `K8sServices` suite.

Reviewable per commit. The last commit partly undoes the first one. This is because I wanted to make reviewing easier.

Setting backport labels to make any backports with changes in the suite easier in the future.

2021-06-08 16:20 UTC, brb commented
test-me-please

2021-06-09 14:09 UTC, brb commented
test-me-please

2021-06-09 14:38 UTC, brb commented
test-me-please

2021-06-10 10:56 UTC, brb commented
test-me-please

2021-06-11 10:01 UTC, tklauser commented
test-me-please

Failed due to Jenkins issues, see https://cilium.slack.com/archives/C7PE7V806/p1623352955165200

2021-06-14 08:39 UTC, brb commented
test-me-please

2021-06-14 08:40 UTC, brb commented
test-me-please

2021-06-14 08:52 UTC, joamaki approved these changes
Checked through the individual commits and this looks good to me.

2021-06-15 10:00 UTC, tklauser requested changes

2021-06-15 10:00 UTC, tklauser commented on test/k8sT/Services.go
> -			}
It looks like the first commit 756825ac9ecd `("test: Make Services test helpers stateless")` removes these helpers but keeps its users., leading to the build to fail on that commit. The helpers are then added again in commit  3bd10aae340d `("test: Move K8sServices test helpers to separate file")`.

I guess in order to ease bisectability it would be good if tests would build on each commit. I seem to remember we have a GH action to ensure that, but maybe it doesn't cover `test/`?

2021-06-15 10:04 UTC, tklauser commented on test/k8sT/Services.go
> -			}
This is the GH action in question: https://github.com/cilium/cilium/blob/master/.github/workflows/lint-build-commits.yaml

It looks like it only checks build of the non-test code and the datapath. Might be worth to extend it to cover `test/` as well. I think something like the following should work:

```diff
diff --git a/.github/workflows/lint-build-commits.yaml b/.github/workflows/lint-build-commits.yaml
index 2adeb889a802..cb3ca17c33c0 100644
--- a/.github/workflows/lint-build-commits.yaml
+++ b/.github/workflows/lint-build-commits.yaml
@@ -78,6 +78,26 @@ jobs:
           PR_PARENT_SHA=$(git rev-parse "${PR_FIRST_SHA}^")
           git rebase --exec "make -C bpf build_all -j $(nproc)" $PR_PARENT_SHA
 
+      - name: Check code changes
+        uses: dorny/paths-filter@78ab00f87740f82aec8ed8826eb4c3c851044126
+        id: test-tree
+        with:
+          filters: |
+            src:
+              - 'test/**'
+
+      # Runs only if code under test/ is changed.
+      - name: Check if ginkgo test suite build works for every commit
+        if: steps.test-tree.outputs.src == 'true'
+        run: |
+          PR_COMMITS_API_JSON=$(curl \
+            -H "Accept: application/vnd.github.v3+json" \
+            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            ${{ github.event.pull_request.commits_url }})
+          PR_FIRST_SHA=$(echo "$PR_COMMITS_API_JSON" | jq -r ".[0].sha")
+          PR_PARENT_SHA=$(git rev-parse "${PR_FIRST_SHA}^")
+          git rebase --exec "make -C test build -j $(nproc)" $PR_PARENT_SHA
+
       - name: Failed commit during the build
         if: ${{ failure() }}
         run: git --no-pager log --format=%B -n 1
```

2021-06-16 10:04 UTC, brb commented on test/k8sT/Services.go
> -			}
Whoa, good catch! 

I've just run `git rebase --exec "make -C test build -j $(nproc)" $PR_PARENT_SHA` - all commits seem to compile. I'd suggest to extend the linter job in a separate PR.

2021-06-16 10:05 UTC, brb commented on test/k8sT/Services.go
> -			}
Whoa, good catch! 

I've just run `git rebase --exec "make -C test build -j $(nproc)" $PR_PARENT_SHA` - all commits seem to compile. I'd suggest to extend the linter job in a separate PR.

2021-06-16 10:05 UTC, brb commented
test-me-please

2021-06-16 12:08 UTC, tklauser approved these changes
Thanks

2021-06-16 12:13 UTC, tklauser commented on test/k8sT/Services.go
> -			}
Opened #16556 to extend the commit build linter GH action.

2021-06-16 12:21 UTC, brb commented
test-1.21-4.9

2021-06-16 12:21 UTC, brb commented
test-runtime

2021-06-17 12:38 UTC, brb commented
test-net-next

2021-06-18 08:08 UTC, brb commented
net-next hit the flake from outside.

2021-06-18 08:08 UTC, brb commented
test-1.16-netnext

2021-06-21 08:01 UTC, merged

2021-06-23 13:43 UTC, brb commented
Dropping the needs 1.9 backport label, as it's complicated to backport the PR.

Let's see whether we will need many changes to v1.9 services testing code. If yes, then we can backport the PR.