test: Fix panic after 'jq' returns "null"
cilium/cilium pull request #16481
Opened 2021-06-08 19:30 UTC by jrajahalme

jq can return "null" as in:

  $ echo "{}" | jq '.status'
  null
  $

Some of our test code expects stdout to be empty in this case, which
leads to panics like:

  Stacktrace
  /home/jenkins/workspace/Cilium-PR-K8s-1.21-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:465
  Test Panicked

In this case there was no other indication of what went wrong. Tracing
the test commands and output against the test source revealed that
this is caused by 'jq' returning "null" in stdout when the test code
expects stdout to be empty if nothing is found.

This can be fixed by adding " | select (.!=null)" to the end of the jq query:

  $ echo "{}" | jq '.status | select (.!=null)'
  $

After this the test for empty stdout after the jq query functions as expected.

Fixes: 16480
Signed-off-by: Jarno Rajahalme <jarno@isovalent.com>

2021-06-08 19:31 UTC, jrajahalme commented
test-me-please

2021-06-08 20:36 UTC, pchaigno requested changes

2021-06-08 20:36 UTC, pchaigno commented on test/helpers/kubectl.go
> +	cmd := fmt.Sprintf("%s -n %s get cep %s -o json | jq '.status | select (.!=null)'", KubectlCmd, namespace, pod)
This panic was already fixed in https://github.com/cilium/cilium/pull/16443 (cf. the code added just a few lines below at line 695). The PR where it happened doesn't include the fix because it was very recently merged.

2021-06-09 19:04 UTC, jrajahalme commented
Already fixed in  #16443

2021-06-09 19:04 UTC, closed without merging