ipcache: Use cluster-name in KVStore endpoints key prefix
cilium/cilium pull request #16590
Opened 2021-06-18 09:31 UTC by jaffcheng

Currently, we use `default` as `<cluster>` in KVStore endpoints
key prefix `cilium/state/ip/v1/<cluster>/<ip>`, this should be
`cluster-name` if it is configured.

Existing agents in a cluster that have a name different than `default`
will create a new endpoint entry with key `cilium/state/ip/v1/<cluster>/<ip>`,
and the old `cilium/state/ip/v1/default/<ip>` entry will exist harmlessly
until it is finally deleted after `kvstore-lease-ttl`.

Fixes: #16378
Signed-off-by: Jaff Cheng <jaff.cheng.sh@gmail.com>

```release-note
Use cluster-name in KVStore endpoints key prefix
```

2021-06-22 17:21 UTC, jrajahalme commented
test-me-please

2021-06-23 07:32 UTC, jaffcheng commented
Looks like the migration process for kvstore key `cilium/state/ip/v1/<cluster>/<ip>` is still necessary, since old agents might write to the prefix `cilium/state/ip/v1/default` while cilium agents are rolling out. New agents who are watching `cilium/state/ip/v1` will tread these events as invalid since they are outside of the prefix `cilium/state/ip/v1/CLUSTER_NAME`, which is not expected.
https://github.com/cilium/cilium/blob/edf76fb1ef6b58d5ef90b439d54134f314ed086e/pkg/ipcache/kvstore.go#L161-L164

Marked as draft.

2021-06-30 16:57 UTC, jrajahalme commented
test-me-please

2021-07-01 04:41 UTC, jaffcheng commented
Checked some of the failed tests, some agents crashed with:
```
2021-06-30T17:42:31.683559228Z level=fatal msg="Error while creating daemon" error="invalid daemon configuration: native routing cidr must be configured with option --native-routing-cidr in combination with --enable-ipv4-masquerade --tunnel=disabled --ipam=cluster-pool --enable-ipv4=true" subsys=daemon
```
Looks like a flake, will rebase first

2021-07-01 14:43 UTC, pchaigno commented
test-me-please

2021-07-05 06:31 UTC, joamaki commented
ci-gke

2021-07-07 16:23 UTC, jrajahalme commented
@jaffcheng Can you please rebase to master to pick up CI fixes?

2021-07-07 17:58 UTC, jaffcheng commented
Rebased

2021-07-07 18:59 UTC, pchaigno commented
test-me-please

2021-07-12 12:59 UTC, jrajahalme commented
Test fail in test-1.19-5.4 is the known flake #16852

2021-07-12 13:03 UTC, jrajahalme commented
#16819 likely fixes ci-gke timeout

2021-07-12 13:09 UTC, jrajahalme commented
> Looks like the migration process for kvstore key `cilium/state/ip/v1/<cluster>/<ip>` is still necessary, since old agents might write to the prefix `cilium/state/ip/v1/default` while cilium agents are rolling out. New agents who are watching `cilium/state/ip/v1` will tread these events as invalid since they are outside of the prefix `cilium/state/ip/v1/CLUSTER_NAME`, which is not expected.

@jaffcheng Did you address this already?

2021-07-12 13:42 UTC, jaffcheng commented
> > Looks like the migration process for kvstore key `cilium/state/ip/v1/<cluster>/<ip>` is still necessary, since old agents might write to the prefix `cilium/state/ip/v1/default` while cilium agents are rolling out. New agents who are watching `cilium/state/ip/v1` will tread these events as invalid since they are outside of the prefix `cilium/state/ip/v1/CLUSTER_NAME`, which is not expected.
> 
> @jaffcheng Did you address this already?

Thanks for checking the test results! Yes, I think this is already addressed. And given that this patch changes the kvstore key, is there something else we should take a closer look at? cc @aanm

2021-07-18 01:08 UTC, aanm requested changes
I think we should avoid doing a KVStore Get when we receive a delete event from the kvstore, the one I've marked as [1]. This could be achieved with the introduction of an hidden flag, probably named as `kvstore-check-legacy-key-prefix`, I'm open to a better flag name. This flag will them be set to `true` by default in the cilium-agent binary but it would be set as `false` in new helm installations. This would mean that new clusters will not perform the KVStore Gets on deletes while existing cluster will, which still allow for an upgrade path between old nodes and new nodes.

What do you think?

2021-07-18 01:08 UTC, aanm commented on pkg/ipcache/kvstore.go
> +				}
Please add a comment in this code that it can be removed in Cilium 1.12

2021-07-18 01:08 UTC, aanm commented on pkg/ipcache/kvstore.go
> +					v, err := kvstore.Client().Get(ctx, clusterPrefixedKey)
[1]

2021-08-11 02:29 UTC, ArthurChiao commented
CC @ArthurChiao

2021-08-13 19:21 UTC, christarazi commented
Moving to draft until this is ready for review.

2022-08-31 02:16 UTC, closed without merging