Misc minor fixes
cilium/cilium pull request #1666
Opened 2017-10-03 12:39 UTC by scanf

@dborkmann I have gone through the bpf directory and tried to fix some of the __uX usage, but most of the changes ended up focusing on silencing the check output. @tgraf took care of the port related ones in c5c24504bf8e (bpf: Use __be16 consistently to indicate ports in network byteorder, 2017-08-29).

The output from sparse still seems mostly related to the macros, not sure how to fix them without breaking compilation. Do you see anything wrong or missed? Please let me know, thanks!

2017-10-03 12:44 UTC, aanm commented on bpf/bpf_lxc.c
> +		if (data + sizeof(*(data + ETH_HLEN)) + ETH_HLEN > data_end)
I think it would help to have a comment before the line so developers know what is supposed to be the `data + ETH_HLEN`

2017-10-03 12:45 UTC, tgraf requested changes

2017-10-03 12:45 UTC, tgraf commented on bpf/bpf_lxc.c
> +		if (data + sizeof(*(data + ETH_HLEN)) + ETH_HLEN > data_end)
I think we can remove this length check altogether, it looks like code that was accessing ip6 before was removed without removing this check.

2017-10-03 16:33 UTC, tgraf approved these changes

2017-10-03 19:35 UTC, tgraf commented
@scanf Is this just an ordering issue with github? I see the `bpf.sha` update commit in the middle of the series

2017-10-04 07:50 UTC, scanf commented
I think the web UI is sorting on date, which is incorrect. Because of rebasing.
One easy way to know what the last commit is independent of the UI order is to look for the CI indicator (green check mark, yellow circle, etc), which shows you the last commit on the CI. 

Squashed the commit to avoid confusion.

2017-10-04 10:34 UTC, merged