Docs: Fix maglev.hashSeed generation command
cilium/cilium pull request #16690
Opened 2021-06-29 22:28 UTC by gaffneyd4

Update one of the seed generation commands in the maglev documentation from using 12 bytes to 16 bytes, so it matches the instructions:

> The seed is a base64-encoded 16 byte-random number

2021-06-29 22:59 UTC, qmonnet reviewed
Thanks a lot for the PR!

~But I don't know if the change is correct. Looking at the history, I see that commit https://github.com/cilium/cilium/commit/4d9167fe65db7d8b20d314c9c6c68b9918c87b04 explicitly changed from 16 to 12 bytes, so the `16 byte` length may apply to the base64 output and not to the initial bytes piped into `base64`? /Cc @brb~

~In any case one of the commands is wrong (either `-c12` or `-c16`) and the text may need some clarification indeed, so thanks for working on this!~

[Edit] You edited your PR while I was writing the review, and it looks good now I think. Asking a review from Martynas to be sure, but looks good from my side, thank you!

2021-06-29 23:04 UTC, qmonnet approved these changes

2021-07-01 10:16 UTC, brb requested changes
The maglev hash seed is 16 bytes long. See:

> $ head -c12 /dev/urandom | base64 -w0 | wc -c
16

2021-07-01 10:17 UTC, brb approved these changes
Scratch my previous comment.

2021-07-01 14:03 UTC, pchaigno commented
Documentation-only change so fine to merge despite merge freeze.

2021-07-01 14:04 UTC, merged