Revert "policy: Make selectorcache callbacks lock-free"
cilium/cilium pull request #16769
Opened 2021-07-03 23:27 UTC by aanm

This reverts commit a75599da7964fb5e24c3362dfbdedf7d2f455089.
has it seems to be causing a lot of FQDN flakes through the entire CI.

Signed-off-by: André Martins <andre@cilium.io>

Fixes: https://github.com/cilium/cilium/issues/16741
Fixes: https://github.com/cilium/cilium/issues/16724
Fixes: https://github.com/cilium/cilium/issues/16722
Fixes: https://github.com/cilium/cilium/issues/16717
Fixes: https://github.com/cilium/cilium/issues/16713
Fixes: https://github.com/cilium/cilium/issues/16664
Fixes: https://github.com/cilium/cilium/issues/16659
Fixes: https://github.com/cilium/cilium/issues/16095
Fixes: https://github.com/cilium/cilium/issues/16096

2021-07-03 23:32 UTC, aanm commented
test-me-please

2021-07-04 03:01 UTC, aanm commented
Previous jenkins failures: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/967/

2021-07-04 03:01 UTC, aanm commented
test-me-please

2021-07-04 14:06 UTC, aanm commented
All Jenkins jobs were green

2021-07-04 14:06 UTC, aanm commented
test-me-please

2021-07-04 18:35 UTC, aanm commented
All Jenkins jobs were green

2021-07-04 18:35 UTC, aanm commented
test-me-please

2021-07-04 21:40 UTC, aanm commented
Previous jenkins failures: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-5.4/577/

2021-07-04 21:41 UTC, aanm commented
test-me-please

2021-07-05 00:58 UTC, aanm commented
All Jenkins jobs were green

2021-07-05 00:58 UTC, aanm commented
test-me-please

2021-07-05 04:00 UTC, aanm commented
All Jenkins jobs were green

2021-07-05 04:00 UTC, aanm commented
test-me-please

2021-07-05 08:46 UTC, nebril approved these changes

2021-07-05 08:59 UTC, pchaigno requested changes
> Fixes: #16741

That flake started happening [before](https://jenkins.cilium.io/job/cilium-master-runtime-kernel-4.9/2210/) we merged https://github.com/cilium/cilium/pull/16529, so the revert is very unlikely to fix it ;)

> Fixes: #16722
Fixes: #16664

These are not FQDN related, so what's the relation here?

> Not sure if it f-i-x-e-s: #16717

We're sure it doesn't. We know the root cause for that one.

> Fixes: #16713
Fixes: #16659
Fixes: #16724

Concerns FQDN and started failing when we merged https://github.com/cilium/cilium/pull/16529, so seems likely :+1: 

> Fixes: #16095

That one was caused by Google's anti-abuse engines and happened well before we merged https://github.com/cilium/cilium/pull/16529.

> Fixes: #16096

That one was a flow validation flake. Nothing to do with https://github.com/cilium/cilium/pull/16529.

2021-07-05 12:31 UTC, aanm commented
> > Fixes: #16741
> 
> That flake started happening [before](https://jenkins.cilium.io/job/cilium-master-runtime-kernel-4.9/2210/) we merged #16529, so the revert is very unlikely to fix it ;)

The commit from https://jenkins.cilium.io/job/cilium-master-runtime-kernel-4.9/2210/ is edf76fb1ef6b58d5ef90b439d54134f314ed086e

```
$ git ll edf76fb1ef6b58d5ef90b439d54134f314ed086e
* edf76fb1ef6b58d5ef90b439d54134f314ed086e vagrant: Bump all Vagrant box versions
* ba4acfe79bc6732abf85ed18f1dacfae61fd1444 daemon: Warn on disabling iptables
* d9eff9a7637f40b9a10221335bf1d36adc50fb5f ci: Bump cilium-cli version
* f9abe641b01c5e90a5f86533f5d88d82539180f1 ci: Enable flow validation
* 2c10568cada51702d2d2e97ad4ed49d1f8f587a0 test: re-enable K8sDatapathConfig Host firewall tests
* 31927a2e8db5c7ced889cc3618d2372ba4e999c9 bpf: fix iptables masquerading for node -> remote pod traffic
* 037a1d0c296b74c8b159cfde7a451ba409f1f547 build(deps): bump github.com/aliyun/alibaba-cloud-sdk-go
* 4e5272be1e759a33e69c7444270018452b86ecf3 docs: run GitHub action when Charts are touched to check Helm values ref
* 8b83fd3cf318e2ea0fed727ebd1f1798fcd00fb7 .github/workflows: install ginkgo for test suite build test
* 876e9db9f1c8f3b0c2e1a7f0d40e9772440720af fix: missing update verb in hubble-generate-certs
* a75599da7964fb5e24c3362dfbdedf7d2f455089 policy: Make selectorcache callbacks lock-free
```

> 
> > Fixes: #16722
> > Fixes: #16664
> 
> These are not FQDN related, so what's the relation here?

Hmm good point, although the flakes might not be entirely FQDN specific since the `notifyUsers` is not FQDN-specific, thus it might fix this as well. We can always re-open them if they show up.

> 
> > Not sure if it f-i-x-e-s: #16717
> 
> We're sure it doesn't. We know the root cause for that one.
> 
> > Fixes: #16713
> > Fixes: #16659
> > Fixes: #16724
> 
> Concerns FQDN and started failing when we merged #16529, so seems likely 
> 
> > Fixes: #16095
> 
> That one was caused by Google's anti-abuse engines and happened well before we merged #16529.
> 
> > Fixes: #16096
> 
> That one was a flow validation flake. Nothing to do with #16529.

2021-07-05 12:42 UTC, pchaigno commented
> The commit from https://jenkins.cilium.io/job/cilium-master-runtime-kernel-4.9/2210/ is edf76fb

Thanks for checking :pray: Not sure why I thought https://github.com/cilium/cilium/pull/16529 was merged on the 24th :-/

> We can always re-open them if they show up.

I'd rather go the other way around: leave open and close if we see it's not happening anymore. That way contributors are less likely to open a new issue for the same flake (which would mean we'd lose track of previous information unless someone notices the duplicate). I also don't see a benefit to closing the issue; it's not blocking anything.

2021-07-05 12:54 UTC, pchaigno approved these changes

2021-07-05 13:16 UTC, merged

2021-07-06 20:11 UTC, joestringer commented
PR #16529 was never backported to v1.8, removing the needs-backport/1.8 since you can't revert something that was never in the tree.