istio: Update to release 1.9.6
cilium/cilium pull request #16766
Opened 2021-07-02 16:30 UTC by jrajahalme

Update Cilium Istio integration to Istio release 1.9.6.

Signed-off-by: Jarno Rajahalme <jarno@isovalent.com>

```release-note
Cilium Istio integration is updated to Istio release 1.9.6.
```

2021-07-02 16:50 UTC, jrajahalme commented
test-me-please

2021-07-02 17:15 UTC, qmonnet requested changes

2021-07-02 17:15 UTC, qmonnet commented on test/k8sT/istio.go
> +		istioctlParams = // ""
Why commenting out the empty string, does it make a difference?

2021-07-02 17:15 UTC, qmonnet commented on test/k8sT/istio.go
> +		" --set values.pilot.image=docker.io/jrajahalme/istio_pilot:1.9.6" + prerelease +
Please update the note above, which tells that the lines are commented: `// Keeping these here in comments`...

2021-07-02 17:15 UTC, qmonnet commented on test/k8sT/istio.go
> +			" --set values.global.logging.level=debug"
The `// " --set values.global.mtls.auto=false"` below should be left-align on the other lines?

2021-07-02 17:15 UTC, qmonnet commented on test/k8sT/istio.go
> +			// kubeProxyReplacement": "disabled",
`// kubeProxyReplacement"`: Not sure why you removed the double-quote at the beginning?

2021-07-04 05:10 UTC, jrajahalme commented
@qmonnet Should have marked this as draft, sorry!

2021-07-06 06:44 UTC, jrajahalme commented
test-only --focus="K8sIstio"

2021-07-06 07:39 UTC, jrajahalme commented
test-only --focus="K8sIstio"

2021-07-06 08:03 UTC, jrajahalme commented
test-me-please

2021-07-06 08:04 UTC, jrajahalme commented
ci-gke

2021-07-07 13:32 UTC, jrajahalme commented
test-only --focus="K8sIstio"

2021-07-07 14:24 UTC, jrajahalme commented
test-me-please

2021-07-07 17:02 UTC, qmonnet approved these changes

2021-07-12 09:37 UTC, jrajahalme commented
test-me-please

2021-07-12 11:55 UTC, nebril approved these changes

2021-07-12 12:11 UTC, jrajahalme commented
Unrelated fails in test-1.21-4.9, Istio test succeeded also there.

2021-07-14 12:08 UTC, jrajahalme commented
Fails in test-1.21-4.9 are unrelated, Istio test succeeded.

2021-07-14 12:10 UTC, jrajahalme commented
Fail in test-gke also unrelated.

2021-07-15 12:04 UTC, merged