v1.10 backports 2021-07-05
cilium/cilium pull request #16774
Opened 2021-07-05 09:08 UTC by twpayne

* #15650 -- daemon: Add option --bpf-lb-external-clusterip (@joamaki)
 * #16721 -- Fix and add more commands in CI sysdumps (@aanm)
 * #16719 -- docs: fix code-block for bpf mount example (@aanm)
 * #16690 -- Docs: Fix maglev.hashSeed byte size documentation (@gaffneyd4)
 * #16631 -- Improve Cilium integration with managed Kubernetes providers (@aanm)
 * #16750 -- contrib/docs: rename 'cilium-actions.yml' with 'maintainers-little-helper.yaml (@aanm)
 * #16756 -- Revert "docs: add 'endpointRoutes.enabled=true' to aws-cni" (@bmcustodio)
 * #16387 -- .github: Create lint-rst.yaml (@geyslan)
 * #16691 -- bugtool: Collect BPF cgroup programs related information (@aditighag)
 * #16584 -- helm: Allow configuration of probe timers (@jonkerj)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 15650 16721 16719 16690 16631 16750 16756 16387 16691 16584; do contrib/backporting/set-labels.py $pr done 1.10; done
```

2021-07-05 09:09 UTC, bmcustodio approved these changes
My changes LGTM!

2021-07-05 09:12 UTC, joamaki approved these changes
My commit LGTM.

2021-07-05 09:13 UTC, twpayne commented
I had to resolve conflicts in the following commits:

c7a42720a46d5dff4db44f67d47f2075cf11cc94 (from c7a42720a46d5dff4db44f67d47f2075cf11cc94 in master) cc @joamaki 

3f0b281749e5dea0e1d27bce54a7a4bcad9ae9dc (from 3f0b281749e5dea0e1d27bce54a7a4bcad9ae9dc in master) cc @aanm

2021-07-05 09:16 UTC, twpayne commented
@geyslan the RST check from #16387 fails on this 1.10 branch. Note that the commit applied cleanly without conflicts. Could you investigate?

2021-07-05 09:16 UTC, twpayne commented
test-backport-1.10

2021-07-05 12:40 UTC, aanm approved these changes

2021-07-05 13:35 UTC, jonkerj commented
My change LGTM

2021-07-06 09:44 UTC, twpayne commented
test-backport-1.10

2021-07-06 13:11 UTC, twpayne commented
k8s-1.16-kernel-netnext failure looks like #12511.

k8s-1.17-kernel-4.9 failure is possibly #14598.

k8s-1.21-kernel-4.9 failure is new.

2021-07-06 14:30 UTC, twpayne commented
test-1.16-netnext

2021-07-06 14:30 UTC, twpayne commented
test-1.17-4.9

2021-07-06 14:30 UTC, twpayne commented
test-1.21-4.9

2021-07-06 15:58 UTC, aditighag approved these changes
Backport for my commit looks good! Thanks!

2021-07-07 12:35 UTC, twpayne commented
Yay! Passing tests! Marking as `ready-to-merge`.

Note to Janitors: the "RST checks / Validate RST files (pull_request)" check failure can be ignored: it was a faulty Github action included in an early version of this PR, but is no longer part of the PR.

2021-07-07 12:36 UTC, pchaigno requested changes
Commit `.github: Create lint-rst.yaml` is still present even though https://github.com/cilium/cilium/pull/16387 is not in the list of PRs being backported anymore.

2021-07-07 14:30 UTC, pchaigno approved these changes

2021-07-07 14:31 UTC, pchaigno commented
I don't think we need to rerun the end-to-end tests given they were green just before removing the commit with the broken GH workflow. I'll merge as soon as the initial tests are passing.

2021-07-08 10:24 UTC, twpayne commented
test-backport-1.10

2021-07-08 12:33 UTC, merged