docs: bandwidth manager is now disabled by default
cilium/cilium pull request #16782
Opened 2021-07-05 13:20 UTC by bmcustodio

https://github.com/cilium/cilium/pull/16380 disabled the bandwidth manager by default.

2021-07-05 14:09 UTC, borkmann approved these changes

2021-07-07 09:51 UTC, qmonnet approved these changes

2021-07-07 09:54 UTC, qmonnet commented
This PR has got positive reviews from the two owner teams, bpf and docs-structure. The documentation checks are passing. The RST checks failed, but the GitHub action is known to fail (and there's a pending PR to remove it anyway), and that failure should be ignored.

For these reasons, I'm marking as ready-to-merge.

2021-07-07 12:34 UTC, pchaigno requested changes
One question below. LGTM otherwise.

2021-07-07 12:34 UTC, pchaigno commented on Documentation/helm-values.rst
> +     - ``2``
Have these changes been included by mistake?

2021-07-07 13:59 UTC, qmonnet commented on Documentation/helm-values.rst
> +     - ``2``
No, I'm pretty sure this is intentional. They are in a separate commit (along with the spelling list update).

We've had the Helm reference for a few weeks now, and people should update it when they touch the Helm values. The CI is supposed to catch omissions, but there was a bug and a few changes to the Helm values were not reported to Documentation/helm-values.rst.

Now that the CI has been fixed, the documentation action - which will run for this PR - should complain that the Helm values are missing in the reference. This is why Bruno updated it - to fix the reference, and to have the GH action pass. The changes to the spelling wordlist in the same commit are in fact needed to account for the new words added to the Helm reference in this update.

2021-07-07 14:02 UTC, pchaigno commented on Documentation/helm-values.rst
> +     - ``2``
:+1: Ok, makes sense. That information should ideally be in the commit message though :-)

2021-07-07 14:02 UTC, pchaigno approved these changes

2021-07-07 14:02 UTC, merged