docs: improve the bandwidth manager page
cilium/cilium pull request #16783
Opened 2021-07-05 13:53 UTC by bmcustodio

Attempts to make the "Bandwidth Manager" page more user-friendly by deploying a server pod and a client pod that is guaranteed to not be colocated with the former. Also provides friendlier commands for making the `netperf` test, as well as to check the status of the bandwidth manager.

Related to this PR is https://github.com/cilium/cilium/pull/16782, but the current one needs backporting to both `v1.9` and `v.10`, whereas https://github.com/cilium/cilium/pull/16782 is only required to be backported to `v1.10`.

```release-note
docs: improve the bandwidth manager page
```

2021-07-07 22:55 UTC, joestringer approved these changes
Are the backports really already pending? Or should that be `needs-backport/xxx`? I don't see any other PRs referencing this PR, and if this PR isn't merged yet then the backporting scripts won't pick this up.

2021-07-12 07:16 UTC, borkmann requested changes
few small nits

2021-07-12 07:16 UTC, borkmann commented on Documentation/gettingstarted/bandwidth-manager.rst
> +optimize TCP and UDP workloads and efficiently rate limit individual pods
I would prefer to have Pods with capital spelling. This is also consistent elsewhere, e.g. https://cloud.google.com/kubernetes-engine/docs/concepts/pod .

2021-07-12 07:16 UTC, borkmann commented on Documentation/gettingstarted/bandwidth-manager.rst
> +        # Limits egress bandwidth to 10Mb/s.
I would clarify `10Mb/s` to `10Mbit/s`

2021-07-12 07:16 UTC, borkmann commented on Documentation/gettingstarted/bandwidth-manager.rst
> +As can be seen, egress traffic of the ``netperf-server`` pdd has been limited to 10Mbit per second.
What is pdd?

2021-07-19 23:13 UTC, joestringer commented
@bmcustodio were you planning to get back to this?

2021-07-19 23:24 UTC, joestringer commented
I've updated the labels to reflect that this PR will need backporting, since I couldn't tell if the backport process was already kicked off somewhere. If you have started backporting them, then feel free to set the labels back to `backport-pending/...`.

2021-07-21 14:25 UTC, bmcustodio commented
@joestringer sorry for the delay :| The backports were indeed not started — sorry for the mess!

2021-07-23 19:38 UTC, joestringer approved these changes
Looks like @borkmann 's review comments have been addressed. Should be good to merge now.

2021-07-23 19:38 UTC, merged