github: Increase workflow timeout
cilium/cilium pull request #16819
Opened 2021-07-07 14:39 UTC by jrajahalme

Increase conformance-gke timeout to avoid fail due to cancelled test
as in:

installation-and-connectivity
cancelled 2 hours ago in 30m 13s

[=] Test [client-egress]
....
[=] Test [echo-ingress]
Error: The operation was canceled.

Signed-off-by: Jarno Rajahalme <jarno@isovalent.com>

2021-07-07 14:40 UTC, jrajahalme commented
ci-gke

2021-07-08 01:48 UTC, aanm approved these changes
@jrajahalme do you have any idea why the connectivity tests are taking so much time? A run from 12 days ago, the connectivity test took 8 mins for the first run and ~3 minutes for the next ones.

2021-07-09 05:55 UTC, jrajahalme commented
@aanm First connectivity test taking longer is most likely due to the various prechecks before running actual tests. Prechecks wait that the deployments are available, ipcache's are coherent, and that service backends are available via DNS. On futher runs these checks would pass without delays.

2021-07-09 05:58 UTC, jrajahalme commented
ci-gke hit the same 30 minute timeout this PR should fix. Will test by enabling the `pull_request` in the workflow.

2021-07-09 06:03 UTC, jrajahalme commented
ci-gke

2021-07-09 08:52 UTC, tklauser approved these changes

2021-07-12 11:35 UTC, nebril requested changes
LGTM, but please remove `pull_request` trigger from workflow

2021-07-12 11:35 UTC, nebril commented on .github/workflows/conformance-gke.yaml
> +  pull_request: {}
Please comment out before merging

2021-07-12 13:02 UTC, jrajahalme commented on .github/workflows/conformance-gke.yaml
> +  pull_request: {}
Removed, thanks for the remainder :-)

2021-07-13 08:18 UTC, merged