v1.10 backports 2021-07-08
cilium/cilium pull request #16829
Opened 2021-07-08 13:29 UTC by pchaigno

* #16363 -- conformance tests: Use hubble-relay-ci image (@michi-covalent)
 * #16715 -- ci/conformance: Various image-related fixes (@gandro)
     - AWS-CNI workflow doesn't exist on v1.10, had to remove it.
 * #16769 -- Revert "policy: Make selectorcache callbacks lock-free" (@aanm)
 * #16767 -- test: Redeploy DNS after endpointRoutes reconfiguration (@joestringer)
 * #16804 -- contrib: Explicitly set remote for backport branches (@twpayne)
 * #16782 -- docs: account for bandwidth manager now being disabled by default (@bmcustodio)
 * #15999 -- Improve logging when cgroupfs mount fails (@johngv2)
 * #16822 -- docs: Document dns visibility limitations (@joestringer)

Skipped because the PR it fixes (which introduces the new test file) is not backported yet:

 * #16775 -- test/Bookinfo: Collect full artifact in case of failure (@pchaigno)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 16363 16715 16769 16767 16775 16804 16782 15999 16822; do contrib/backporting/set-labels.py $pr done 1.10; done
```

2021-07-08 13:31 UTC, pchaigno commented
test-backport-1.10

2021-07-08 22:07 UTC, joestringer approved these changes
:+1: There'll be a followup for #16767 but that can be handled in a subsequent backport or tacked on top.

2021-07-08 22:51 UTC, aditighag approved these changes
>Improve logging when cgroupfs mount fails #15999 -- Improve logging when cgroupfs mount fails (@johngv2)

Looks good! Thanks!

2021-07-12 08:37 UTC, gandro approved these changes
Looks good for the CI 3.0 related commits. Thanks!

2021-07-12 09:23 UTC, bmcustodio approved these changes
My commit LGTM!

2021-07-13 09:09 UTC, pchaigno commented
test-backport-1.10

2021-07-14 09:31 UTC, pchaigno commented
test-upstream-k8s

2021-07-14 11:11 UTC, pchaigno commented
test-backport-1.10

2021-07-14 22:13 UTC, aanm commented
test-backport-1.10

2021-07-14 23:00 UTC, joestringer approved these changes

2021-07-15 00:01 UTC, christarazi approved these changes

2021-07-15 01:30 UTC, aanm commented
test-1.21-4.9

2021-07-15 07:18 UTC, tklauser approved these changes

2021-07-15 08:15 UTC, qmonnet approved these changes
Reviewing for:
> #16755 -- docs(k3s): add back the flag to disable network policies (`@rio`)

The commit looks good to me

2021-07-15 09:43 UTC, jrajahalme approved these changes
Backports for all of my commits seem to be done.

2021-07-15 11:04 UTC, nbusseneau commented
- Commit from #16711 seems to be missing.
- Commit from #16830 seems to be missing.
- One commit of #16787 (f98a99de3ae4afb9f22065d08a5cf5a7be168449) seems to be missing.

Other commits LGTM.

2021-07-15 11:05 UTC, nbusseneau requested changes
- Commit from #16711 seems to be missing.
- Commit from #16830 seems to be missing.
- One commit of #16787 (f98a99de3ae4afb9f22065d08a5cf5a7be168449) seems to be missing.

Other commits LGTM.

2021-07-15 13:22 UTC, nbusseneau approved these changes
🚀

2021-07-15 13:51 UTC, aanm commented
All GH workflows were tested here https://github.com/cilium/cilium/pull/16897 the CI was green before I pushed as the only new changes pushed were GH workflow related.

2021-07-15 13:51 UTC, merged