[v1.10] install/kubernetes: re-add restartPods
cilium/cilium pull request #16858
Opened 2021-07-12 15:01 UTC by aanm

This option will be removed in Cilium 1.11 and is now deprecated in 1.10
but that does not mean that it should be removed from the 1.10 branch.
For existing clusters, users might not be able to provision a cluster
with the necessary node taints and as a backup they will have to re-use
the restartPods options.

Signed-off-by: André Martins <andre@cilium.io>

2021-07-12 15:03 UTC, aanm commented
test-backport-1.10

2021-07-13 16:40 UTC, aanm commented
test-1.21-4.9

2021-07-13 16:40 UTC, aanm commented
test-upstream-k8s

2021-07-14 02:01 UTC, aanm commented
test-1.21-4.9

2021-07-14 14:04 UTC, kkourt requested changes
Can you please add the  id  (maybe in a `fixes:` line if appropriate) of the commit that removed the code that is hereby re-added? Seems to me that the commit is: 703b38fd47da1f91a342a8546f53542d624d8b22

Also, If the exact same code is re-added, please make a note of this fact (i.e., there are no modifications in the original restartPods handling code) in the commit message.

2021-07-14 16:48 UTC, aanm commented
test-me-please

2021-07-14 16:49 UTC, kkourt approved these changes

2021-07-14 20:56 UTC, aanm commented
The CI was previously green, I just added changed proposed by Kornilios which only modified the commit message.

2021-07-14 20:56 UTC, merged