L7 Visibility Annotations (RFC)
cilium/cilium pull request #16935
Opened 2021-07-20 00:30 UTC by trvll

Translating VisibilityPolicy into PortNetwrokPolicy to enable L7 visibility for pod annotations.

Signed-off-by: Thales Paiva <thales@accuknox.com>

Fixes: #14072

2021-07-20 10:40 UTC, jrajahalme commented
@trvll Please note that no PortNetworkPolicy is needed for the visibility annotations to work. The reason why the visibility annotations do not currently work with Network Policies is *not* the lack of translation from visibility annotation to PortNetworkPolicy (which is not needed), but the missing interplay with L3/L4 allow/deny policy processing for the BPF policy map entries.

There is a work-in-progress PR that adds the missing pieces: https://github.com/cilium/cilium/pull/16258

While the solution in the linked PR is correct, it is still missing unit testing making it fragile towards future regressions. I'll be working on that shortly.

2021-07-20 10:51 UTC, jrajahalme commented
Here's the code on the cilium-envoy side making the policy exception to support Istio sidecars, this same exception also allows visibility annotations to work without PortNetworkPolicies:

https://github.com/cilium/proxy/blob/master/cilium/network_policy.cc#L555-L560

2021-07-20 10:55 UTC, jrajahalme commented
Corresponding code on the proxylib side is somewhat unfinished, maybe you try make it behave similarly to the C++ side linked above and test how it works out?

https://github.com/cilium/cilium/blob/master/proxylib/proxylib/policymap.go#L235-L245

2021-07-21 01:34 UTC, trvll commented
@jrajahalme thank you for this kind discussion. 

>@trvll Please note that no PortNetworkPolicy is needed for the visibility annotations to work. 

AFAIU for annotations a PortNetworkPolicy will be used but it is an allow-all policy since there is no policy enforced:

https://github.com/cilium/cilium/blob/eb11c1467a2c535054e5c64d644d2ea442bf1270/pkg/envoy/server.go#L1239-L1242

>EDIT: I did not consider proxylib parsers yet. It may be possible to make the proxylib network policy code behave like the Envoy side so that a missing port network policy is interpreted as an allow-all policy. For normal (non-annotation) policies we never redirect to the proxy unless a PortNetworkPolicy is successfully configured. So the only configuration where traffic is redirected without a PortNetworkPolicy is for visibility only (via the visibility annotations).

In  case of proxylib parsers, when receiving a new connection, the proxy will create a new instancy from proxylib and needs the protocol name information to do that. This information on  Envoy side is retrieved from PortNetworkPolicyRule which comes to be empty because we are using an allow-all policy. 

https://github.com/cilium/proxy/blob/e83275091139101e7ff29284ef35c56f4cd6bfc3/cilium/network_filter.cc#L124-L127

So my approach here was to create an allow-all policy that has a PortNetworkPolicyRule derived from VisibilityPolicy. This make sense to you?

2021-08-20 14:01 UTC, jrajahalme commented
@trvll Right, I forgot that proxylib parser selection requires the l7 parser name in the PortNetworkPolicyRule :-)

This PR looks good to me to fix this for the current master and is fully orthogonal with #16258. Some CI testing would be needed though. Would it be possible to augment the existing proxylib and/or Kafka tests with visibility annotations to verify this works?

Additional work will be needed to fuse the visibility annotation with an actual policy when policy is enforced, though. #16258 does this for the bpf policy map rules, but fails to address this for proxylib parsers. IMO this can be left for a follow-up PR.

2021-08-20 14:02 UTC, jrajahalme commented
test-me-please

2021-08-20 14:22 UTC, trvll commented
@jrajahalme thanks for your review. Yes! I can go through the tests right now as the proposed solution is considered satisfactory.

I also agree with the additional work statement. Thank you so much!

2021-09-02 06:50 UTC, jrajahalme commented
@trvll Do you still plan working on some test coverage? This has no test coverage as of now. At a minimum, some unit tests for the additional functionality of `getNetworkPolicy()` in `pkg/envoy/server_test.go` should be added.

2021-09-02 14:51 UTC, trvll commented
@jrajahalme yes, I'll code the tests ASAP considering your suggestion for sure. Tks.

2021-09-09 01:30 UTC, trvll commented
Hi @jrajahalme I've added a unit test for the added functionality. I used kafka as example which I think is enough to test the mechanism. Please  let me know you opinion. Tks.

2021-09-14 08:27 UTC, jrajahalme commented
test-me-please

2021-09-14 08:28 UTC, jrajahalme approved these changes
LGTM, thanks for adding the test :-)

2021-09-14 12:24 UTC, trvll commented
@jrajahalme seems that the the failing tests are not related. Should we run the tests again?

2021-09-17 19:03 UTC, nathanjsweet requested changes
nits. Otherwise, looks good. Your update should kickoff the tests again.

2021-09-17 19:03 UTC, nathanjsweet commented on pkg/envoy/server.go
> +							//Rules:    SortPortNetworkPolicyRules(rules),
Is this comment still necessary?

2021-09-17 19:03 UTC, nathanjsweet commented on pkg/envoy/server.go
> +							//Rules:    SortPortNetworkPolicyRules(rules),
ditto.

2021-09-20 08:54 UTC, trvll commented on pkg/envoy/server.go
> +							//Rules:    SortPortNetworkPolicyRules(rules),
not really. I'm going to remove it. Tks

2021-09-20 18:53 UTC, nathanjsweet commented
/test

2021-09-20 18:53 UTC, nathanjsweet approved these changes

2021-10-01 23:18 UTC, aanm commented
test-1.16-netnext

2021-10-01 23:18 UTC, aanm commented
test-1.21-4.9

2021-10-01 23:19 UTC, aanm commented
ci-awscni

2021-10-01 23:19 UTC, aanm commented
ci-aks

2021-10-01 23:19 UTC, aanm commented
ci-eks

2021-10-01 23:19 UTC, aanm commented
ci-gke

2021-10-02 13:02 UTC, aanm commented
@trvll it looks these changes is breaking CI. Can you to take a look at them?

2021-10-04 11:11 UTC, trvll commented
@aanm for sure.  I'm going to look on that. thx

2021-10-06 00:42 UTC, trvll commented
I've patched the offending code. Basically we should create the PortNetworkPolicyRule with L7Proto set only for proxylib parsers.
I added a statement to avoid this setup for HTTP and DNS annotations.

2021-11-01 12:07 UTC, jrajahalme commented
/test

2021-11-04 11:56 UTC, jrajahalme commented
All the CI fails are unrelated, labeling ready-to-merge.

2021-11-04 11:57 UTC, jrajahalme approved these changes

2021-11-04 19:42 UTC, nathanjsweet approved these changes

2021-11-04 19:42 UTC, merged