node-neigh: Wait instead of sleeping in unit tests
cilium/cilium pull request #17035
Opened 2021-08-03 00:11 UTC by aanm

We can inspect the neighLastPingByNextHop map to check
when insertNeighbor() or deleteNeighbor() was called.

Fixes: e68848b98004 ("remove ARP entries left from previous Cilium run")
Signed-off-by: André Martins <andre@cilium.io>

2021-08-03 00:12 UTC, aanm commented
test-runtime

2021-08-03 11:32 UTC, brb requested changes

2021-08-03 11:32 UTC, brb commented on pkg/datapath/linux/node_linux_test.go
> +	wait(nodev3.Identity(), nil, false)
Either you need to pass the `now` value or make the function `wait` to accept `before = nil`.

2021-08-03 11:33 UTC, brb commented
I'm wondering why all of sudden we started to hit the TestArp flakes again. Another issue: https://github.com/cilium/cilium/issues/17020.

2021-08-03 13:28 UTC, aanm commented
/mlh new-flake Cilium-PR-Runtime-4.9

2021-08-03 13:32 UTC, brb commented on pkg/datapath/linux/node_linux_test.go
> +	wait(nodev3.Identity(), &now, true)
`now` is not needed for the deletion.

2021-08-03 13:33 UTC, aanm commented
test-runtime

2021-08-03 13:34 UTC, brb approved these changes
:rocket: :moon:

2021-08-03 22:37 UTC, aanm commented
test-runtime

2021-08-04 11:41 UTC, aanm commented
test-runtime

2021-08-04 15:08 UTC, merged