netns: Fix socket leak
cilium/cilium pull request #17051
Opened 2021-08-04 16:22 UTC by brb

Close the socket if it has been successfully created.

Fixes: 0a4a393d6 ("bpf: Derive host netns cookie via SO_NETNS_COOKIE")
Reported-by: Daniel Borkmann <daniel@iogearbox.net>

2021-08-04 16:23 UTC, borkmann approved these changes

2021-08-04 16:35 UTC, gandro approved these changes

2021-08-04 22:03 UTC, aanm requested changes

2021-08-04 22:03 UTC, aanm commented on pkg/netns/cookie.go
>  	if err != nil {
This file is missing copyright header

2021-08-05 06:33 UTC, brb commented on pkg/netns/cookie.go
>  	if err != nil {
Good catch!

2021-08-05 13:21 UTC, aanm approved these changes

2021-08-05 13:21 UTC, aanm commented
test-me-please

2021-08-13 10:16 UTC, brb commented
test-me-please

2021-08-19 08:13 UTC, tklauser approved these changes

2021-08-19 08:13 UTC, tklauser commented
ConformanceEKS failed on #17139 which was fixed on master in #17140, merging.

2021-08-19 08:13 UTC, merged