Data Path Assignment by Desired CIDR
cilium/cilium pull request #17182
Opened 2021-08-18 08:50 UTC by TrevorTaoARM

There's a case that the user may want to select the desired
data path for node2node communication by its own. But now
it seems Cilium can't support that.
This feature enhancement enables the user to set the desired
outgoing interface and its data path IP(v4) address by
a designated CIDR, which may be different from the default
which currently is just the node IP.
The usage of this feature is simply done by adding a declaration
in the installation ConfigMap of Cilium, e.g, by cilium-cli:

data-path-ipv4-cidr: "xxx.xxx.xxx.xxx/yyy"

This patch here just supports overlay tunnel mode now, which would
lead the data traffic and tunnel endpoint selection to the
matched interface IP address by the specified CIDR.

I think it's easy to be extended to direct routing mode in the future
with some more work here.

Signed-off-by: TrevorTaoARM <trevor.tao@arm.com>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note

```

2021-08-23 09:44 UTC, joamaki reviewed
Few mostly stylistic comments. Still needs someone to think this through from the datapath and configuration perspective.

2021-08-23 09:44 UTC, joamaki commented on daemon/cmd/daemon_main.go
> +			log.WithField(logfields.CIDR, dataPathIPv4CIDR.IPNet.String()).Fatal("Can't detect the cidr for an actual interface IP")
```suggestion
			log.WithError(err).WithField(logfields.CIDR, dataPathIPv4CIDR.IPNet.String()).Fatal("Cannot detect the CIDR for an actual interface IP")
```

2021-08-23 09:44 UTC, joamaki commented on pkg/cidr/cidr.go
> +	//for idx := len(netIfaces) - 1; idx >= 0; idx-- {
```suggestion
```

2021-08-23 09:44 UTC, joamaki commented on pkg/cidr/cidr.go
> +				fmt.Printf("unable to parse ip address '%s' as a CIDR: %s\n", addrStr, err)
```suggestion
				log.WithError(err).Warnf("Unable to parse ip address '%s' as a CIDR", addrStr)
```

2021-08-23 09:44 UTC, joamaki commented on pkg/cidr/cidr.go
> +		//iface := &netIfaces[idx]
```suggestion
```

2021-08-23 09:44 UTC, joamaki commented on pkg/cidr/cidr.go
> +func DetectCIDRByCIDR(cidr *CIDR, version int) (*net.Interface, net.IP, *net.IPNet, error) {
Would a better name be `DetectDeviceByCIDR`?

2021-08-23 09:44 UTC, joamaki commented on daemon/cmd/daemon_main.go
> +	flags.String(option.DataPathIPv4CIDR, "", "Allows to explicitly specify the CIDR for the data path which the user desires.")
Wondering out loud:
1) Does CIDR make more sense than device name in most deployments? Or maybe having both would be useful?

2) This is also very specific to tunnelling so I think it'd make sense to use a more specific parameter, e.g. `IPv4TunnelCIDR`.

2021-08-26 10:10 UTC, errordeveloper commented on pkg/cidr/cidr.go
> +func DetectCIDRByCIDR(cidr *CIDR, version int) (*net.Interface, net.IP, *net.IPNet, error) {
I am not sure what `version` is for, right now this function is always called with `4`, perhaps it's better to just call the function `DetectDeviceByCIDRv4` and when v6 support is required here someone will need to refactor the code anyway. That would also match how IPv4 vs IPv6 is handled in other places, which you have surely noticed in some of the lines this PR touched. I personally think there might be a way to abstract things and make all functions more generic, but I'd leave that for a separate discussion :)

2021-09-06 08:10 UTC, kkourt reviewed
Thanks for the contribution!

Before discussing the code, I would like to understand what are the concrete use-cases for this feature. In other words, is this a "nice to have" or is there a specific problem that it tries to solve. Can you provide a concrete example of where this would be used? Can you also explain in the example why existing configuration approaches (e.g., defining the network interface instead of a CIDR) would not work or they would have issues?

2021-10-02 21:43 UTC, aanm commented
@TrevorTaoARM ping?

2021-10-03 07:06 UTC, TrevorTaoARM commented
> @TrevorTaoARM ping?

Yes.

2021-10-03 07:11 UTC, TrevorTaoARM commented
> Thanks for the contribution!
> 
> Before discussing the code, I would like to understand what are the concrete use-cases for this feature. In other words, is this a "nice to have" or is there a specific problem that it tries to solve. Can you provide a concrete example of where this would be used? Can you also explain in the example why existing configuration approaches (e.g., defining the network interface instead of a CIDR) would not work or they would have issues?

Yes, I think it's a natural way to choose a data path (network interface) by a specified CIDR. 
I didn't know if there's an exitsted way to choose it by a specified network interface.
Actually it would greatly facilitate our data path selection when we have multiple data paths for an internal node2node communication but only desire 1 (or more in the future).

2021-10-03 07:13 UTC, TrevorTaoARM commented
> > Thanks for the contribution!
> > Before discussing the code, I would like to understand what are the concrete use-cases for this feature. In other words, is this a "nice to have" or is there a specific problem that it tries to solve. Can you provide a concrete example of where this would be used? Can you also explain in the example why existing configuration approaches (e.g., defining the network interface instead of a CIDR) would not work or they would have issues?
> 
> Yes, I think it's a natural way to choose a data path (network interface) by a specified CIDR. I didn't know if there's an exitsted way to choose it by a specified network interface. Actually it would greatly facilitate our data path selection when we have multiple data paths for an internal node2node communication but only desire 1 (or more in the future).

Selecting the data path by NIC may not be a desired way as the NIC name may differ on different hosts(nodes), but a common CIDR can select the IP data path by a matched CIDR string with that of the NIC.

2021-10-06 08:14 UTC, kkourt commented on pkg/datapath/linux/config/config.go
> +		cDefinesMap["DATA_PATH_IPV4_CIDR"] = dataPathIPv4CIDR.String()
I don't believe this is needed, I don't see any modifications to the bpf code.

2021-10-06 08:14 UTC, kkourt commented on daemon/cmd/kube_proxy_replacement.go
> +	// dataPathIP was setted only when option.Config.Tunnel != option.TunnelDisabled which is
nit: set

2021-10-06 12:51 UTC, brb requested changes

2021-10-06 12:51 UTC, brb commented on daemon/cmd/daemon.go
> +	externalIP := node.GetDataPathIPv4Addr()
I find the name `DataPathIP*` ambiguous. Without looking into the method and related code it's difficult to imply which datapath it refers, i.e., pod2pod, node2node?

2021-10-06 12:51 UTC, brb commented on daemon/cmd/daemon_main.go
> +			log.WithField(logfields.CIDR, dataPathIPv4CIDR.IPNet.String()).Fatal("Can't detect the cidr for an actual interface IP")
The log msg is missing a context why it's needed to detect.

2021-10-09 09:01 UTC, TrevorTaoARM commented on pkg/datapath/linux/config/config.go
> +		cDefinesMap["DATA_PATH_IPV4_CIDR"] = dataPathIPv4CIDR.String()
@kkourt For your 2 questions here:

- how is the address returned by GetDataPathIPv4Addr() different from the addresses returned by GetIPv4()

I investigated the code path of GetIPv4(), which is really the ipv4RouterAddress set by SetInternalIPv4Router() which is finally defined by allocateNext() in pkg/ipam/crd.go. (The code path is given below, FYI)
All in all, I think the Cilium node internal router IP address used by pods to route its traffic.  For example, it's 10.0.0.81/32 in the following pic:
![image](https://user-images.githubusercontent.com/29970645/136651757-784c2654-8179-4301-8151-96b4d6f70fdd.png)
routerIP=d.allocateRouterIPv4()---->allocateRouterIPv4()---->allocateDatapathIPs()--->AllocateNextFamilyWithoutSyncUpstream()--->
allocateNextFamily()---->AllocateNext
                                       AllocateNextWithoutSyncUpstream

- can the desired use-case be addressed with the existing address concepts? For example, can we introduce an option such as --ipv4-node-cidr or --direct-routing-device-by-cidr that can address the use-case you mention without introducing a new concept (i.e., the one of the datapath IP)?

The data-path-ipv4-cidr here is used for selecting the node 2 node communication path. It's not expressed in device but in CIDR.  So I think it can be thought as ipv4-node-cidr or direct-routing-device-by-cidr here, but actually it not only supports direct routing but also overlay mode..

2021-10-09 09:12 UTC, TrevorTaoARM commented on daemon/cmd/daemon.go
> +	externalIP := node.GetDataPathIPv4Addr()
It's for node2node communication.

2021-10-09 09:13 UTC, TrevorTaoARM commented on daemon/cmd/daemon.go
> +	externalIP := node.GetDataPathIPv4Addr()
The log can be updated later to reflect what you concerned.

2021-10-13 08:54 UTC, TrevorTaoARM commented
> @TrevorTaoARM We are still trying to justify adding the flag to the agent which complicates quite a bit UX. We are wondering whether you have tried to solve the problem by using `--node-ip` flag in kubelet? This would set k8s Node IP which is used for tunnel endpoints.

@brb Yes, I knew the way of setting the NodeIP of the k8s, actually I had used it as a temporary solution when I need to choose a desired interface without this change. 
But this solution is a little tricky here, because it's just for the communication between k8s control plane components of each node, but not for Cilium node 2 node communication between pods.
Another shortcoming of this way is that you need to set the --node-ip flag in every node of your k8s cluster, which is very bothering for a large cluster. You need to find the actual node-ip of each node you want instead of just a CIDR.

2021-11-08 08:59 UTC, pchaigno commented
Moving to draft to remove from review & janitoring queues until the reviews are addressed or answered and the branch rebased on latest master.

2022-08-30 02:03 UTC, ldelossa commented on pkg/node/manager/manager.go
> +			if tunnelIP = n.GetNodeDataPathIPv4(); option.Config.Tunnel == option.TunnelDisabled || tunnelIP == nil {
You can optimize for the common case here:

```suggestion
			tunnelIP = nodeIP
			if dpIP = n.GetNodeDataPathIPv4(); (option.Config.Tunnel == option.TunnelDisabled) && dpIP != nil {
				log.Debugf("No data path IP manually defined, just use the nodeIP")
				tunnelIP = nodeIP
			}
			log.Debugf("tunnelIP %s", tunnelIP.String())
```

2022-10-15 02:17 UTC, closed without merging