policy: add support for kubernetes endPort
cilium/cilium pull request #17315
Opened 2021-09-05 20:11 UTC by rikatz

- [X] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [X] All code is covered by unit and/or runtime tests where feasible. - Added unit test
- [X] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [X] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [X] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Kubernetes supports endPort field since v1.21, being beta in v1.22 and enabled
by default. This commit adds basic support for parsing endPort field while
still keeps the 40 maximum ports per rule imposed by Cilium parser.

Fixes: #16622
Signed-off-by: Ricardo Pchevuzinske Katz <ricardo.katz@gmail.com>

```release-note
Added support for Kubernetes endPort field / port range
```

2021-09-09 21:47 UTC, nathanjsweet commented
You need a release note, but also you need to [add some integration tests](https://docs.cilium.io/en/v1.10/contributing/testing/) to make this viable.

2021-09-10 01:45 UTC, joestringer commented
Oh yeah, I probably should have posted here rather than on the base issue. My latest question was basically whether we think that this implementation is "good enough" for the upstream k8s use cases or not, see more detail here: https://github.com/cilium/cilium/issues/16622#issuecomment-914587235

2021-09-15 19:45 UTC, aanm approved these changes

2021-09-15 20:48 UTC, christarazi approved these changes

2021-09-15 20:48 UTC, christarazi commented on pkg/k8s/network_policy_test.go
> +
Nit: extra line

2021-09-17 17:58 UTC, rikatz commented
Sorry for the delay folks, day job duties taking me some time.

Will cycle back on this during this week/end :)

2021-09-21 14:37 UTC, nathanjsweet approved these changes

2021-09-21 18:48 UTC, joestringer requested changes
Just to make sure we engage with the discussion, I'm setting requested changes here. I think we need to decide whether we think it's useful to have a simpler implementation like this or whether we should engage with a more comprehensive solution. [link](https://github.com/cilium/cilium/issues/16622#issuecomment-914587235).

2022-07-06 19:29 UTC, rikatz commented
Hi folks,

I wont have much time to work on this anymore. If someone wants to take over this PR, please feel free, otherwise close it.

Thanks

2022-09-17 02:17 UTC, closed without merging