docs: add debug monitoring section
cilium/cilium pull request #17357
Opened 2021-09-09 23:52 UTC by ldelossa

Signed-off-by: Louis DeLosSantos <louis.delos@isovalent.com>

2021-09-10 01:24 UTC, joestringer requested changes
I'm a little bit on the fence about whether we should suggest this to users via the cheatsheet given that it modifies BPF programs & in the worst case could even break connectivity (if we somehow missed that enabling debug + all other options increases complexity against that particular kernel version)..

Couple of alternative proposals to address this:
* Move this under `Documentation/contributing/development/` -> then it's only for devs to read
* Put a `.. note::` warning that these are developer-focused instructions and you should know what you're doing if you follow them

2021-09-10 12:54 UTC, pchaigno commented
> if we somehow missed that enabling debug + all other options increases complexity against that particular kernel version

I can already explain the *somehow*: we don't cover debug mode in any test AFAIK :sweat_smile:

2021-09-10 13:04 UTC, pchaigno reviewed
That config. comes up often, thanks for adding it to the docs!

I agree with Joe regarding the location in the docs.

2021-09-10 13:04 UTC, pchaigno commented on Documentation/cheatsheet.rst
> +    cilium monitor --debug
I would remove this step here since it's already present below. No need to repeat since it's the same.

2021-09-10 13:04 UTC, pchaigno commented on Documentation/cheatsheet.rst
> +Update Cilium’s config map with the value:
Maybe more concise (less paragraphs) as:
```
The cilium monitor command is capable of providing debug output for the
datapath. Debug information can be enabled for all endpoints or at a
per-endpoint granularity.

To enable debug mode for all endpoints, update the Cilium config map as
follows and restart all cilium-agent pods.

[...]

To enable debug mode for a specific endpoint, run the following command.

[...]
```

2021-10-20 08:46 UTC, jrajahalme requested changes

2021-10-20 08:46 UTC, jrajahalme commented on Documentation/cheatsheet.rst
> +    cilium monitor --debug
In my recent experience the verbosity option `-v` is needed for any of the debug messages to be shown. Also, if I have Cilium configured with `--debug` and `--debug-verbose=datapath` the `--debug` option in `cilium monitor` does nothing. I get the debug messages with just `cilium monitor -v`.

2022-08-29 02:16 UTC, closed without merging