helm: support lookup remote CA
cilium/cilium pull request #17434
Opened 2021-09-18 04:22 UTC by dungdm93

Currently, when TLS auto method is helm but user doesn't provide CA. CA and certificates are auto (re-)generated for everytime you install/upgrade. And note that **new certificates are not compatible with old CA**.  So that can lead to downtime during rolling update or end-users need to re-import CA if they has 3rd party services/tools interact with cilium.

This PR aim to resolve above issue by re-use existing CA in k8s cluster (Certificates are still re-generated when helm upgrade as a part of renew mechanism).

2021-09-21 08:36 UTC, gandro approved these changes
Thanks, really neat trick!

I also did a few local smoke tests, seems to work nicely.

2021-09-21 12:26 UTC, kaworu approved these changes

2021-09-24 18:00 UTC, errordeveloper approved these changes

2021-09-27 09:40 UTC, kaworu commented
I'm slightly worried that, when we make a new release containing changes to the CA Secret, `helm upgrade` won't pick them up as it could re-use the CA generated by previous version. Should we have a Helm value to force CA re-generation unconditionally as a guard here?

2021-09-27 09:52 UTC, dungdm93 commented
@kaworu are you mean when CA provided by user like this?
```
--set hubble.tls.ca.cert=...
--set hubble.tls.ca.key=...
````
User provided CA always has the highest priority, next is existing CA in k8s cluster, and finally, if non of them exists, helm will generate a new one.
![Screenshot from 2021-09-27 16-51-27](https://user-images.githubusercontent.com/6848311/134886583-b74d1f1d-4ece-4053-b127-02395e76177b.png)

2021-09-27 10:41 UTC, kaworu commented
@dungdm93 let me elaborate:

Imagine I have `helm install`ed version X and at that time Helm generated automatically the CA and Secrets.

Now, Cilium version X+1 introduced a change in the CA Secrets (e.g. we added the key `foo`). With this patch, when I run `helm upgrade` the CA _will not_ be replaced, and thus my cluster will be in a state where it's running Cilium version X+1 with the incompatible version X CA Secrets.

Does that make sense?

2021-09-27 13:24 UTC, gandro commented
> @dungdm93 I did not meant when the CA is manually given on the Helm command. Let me elaborate:
> 
> Imagine I have `helm install`ed version X and at that time Helm generated automatically the CA and Secrets.
> 
> Now, Cilium version X+1 introduced a change in the CA Secrets (e.g. we added the key `foo`). With this patch, when I run `helm upgrade` the CA _will not_ be replaced, and thus my cluster will be in a state where it's running Cilium version X+1 with the incompatible version X CA Secrets.
> 
> Does that make sense?

If we do such a change in the future that should be easily detectable. We can if the existing CA has the correct keys, and if not, rewrite it (potentially without even having to re-generate the keypair)

We can of course also consider adding a Helm value `hubble.tls.ca.regenerate=true` flag, to disable the lookup if necessary.

2021-09-27 15:53 UTC, dungdm93 commented
@kaworu, @gandro Yea.....h. It's a case, but I'm not prefer adding flag to keep it as simple as possible.
I often see people add fields to certificates, not the CA. In the case people really really need to generate new CA, they can simply `kubectl delete` the old one then helm will take care the rest.
Is that solution fine with you guys?

2021-09-28 08:38 UTC, gandro commented
> @kaworu, @gandro Yea.....h. It's a case, but I'm not prefer adding flag to keep it as simple as possible.
> I often see people add fields to certificates, not the CA. In the case people really really need to generate new CA, they can simply `kubectl delete` the old one then helm will take care the rest.
> Is that solution fine with you guys?

Agreed, I don't think we need a flag now.

There might be a need for some special logic needed if we ever do some breaking changes to the CA, but I don't think this PR will limit our options in any way going forward.

2021-09-28 08:41 UTC, kaworu commented
@dungdm93 @gandro Agreed!

2021-09-28 09:15 UTC, jibi commented
/test

2021-09-28 10:10 UTC, kaworu requested changes
Test failures seems related to the patch:

```
[2021-09-28T09:52:09.712Z]         <*helpers.cmdError | 0xc0016989c0>: Unable to generate YAML (exit status 1) output: cmd: helm template --validate /home/jenkins/workspace/Cilium-PR-K8s-GKE@2/src/github.com/cilium/cilium/install/kubernetes/cilium --namespace=kube-system  --set hubble.relay.image.tag=d6b00050171eb387507d8e4780de573b96740992  --set operator.image.suffix=-ci  --set logSystemLoad=true  --set debug.enabled=true  --set ipv6.enabled=false  --set operator.image.repository=quay.io/cilium/operator  --set hubble.relay.image.repository=quay.io/cilium/hubble-relay-ci  --set ipam.operator.clusterPoolIPv6PodCIDR=fd02::/112  --set bpf.masquerade=true  --set hubble.enabled=true  --set ipam.mode=kubernetes  --set hubble.relay.image.useDigest=false  --set operator.image.tag=d6b00050171eb387507d8e4780de573b96740992  --set hubble.listenAddress=:4244  --set preflight.image.repository=quay.io/cilium/cilium-ci  --set bandwidthManager=false  --set gke.enabled=true  --set nodeinit.removeCbrBridge=true  --set nativeRoutingCIDR=10.24.0.0/14  --set bpf.preallocateMaps=false  --set ipv4.enabled=true  --set nodeinit.enabled=true  --set preflight.image.useDigest=false  --set operator.image.useDigest=false  --set k8s.requireIPv4PodCIDR=true  --set image.repository=quay.io/cilium/cilium-ci  --set pprof.enabled=true  --set loadBalancer.mode=snat  --set enableCnpStatusUpdates=true  --set image.tag=d6b00050171eb387507d8e4780de573b96740992  --set etcd.leaseTTL=30s  --set devices=  --set nodeinit.reconfigureKubelet=true  --set hostFirewall.enabled=false  --set preflight.image.tag=d6b00050171eb387507d8e4780de573b96740992  --set kubeProxyReplacement=strict  --set nodePort.enableHealthCheck=false  --set cni.binPath=/home/kubernetes/bin  --set nodeinit.restartPods=true  --set image.useDigest=false  > cilium-16a8f3992595acb3.yaml
[2021-09-28T09:52:09.712Z]     Exitcode: 1 
[2021-09-28T09:52:09.712Z]     Err: exit status 1
[2021-09-28T09:52:09.712Z]     Stdout:
[2021-09-28T09:52:09.712Z]      	 
[2021-09-28T09:52:09.712Z]     Stderr:
[2021-09-28T09:52:09.712Z]      	 Error: parse error at (cilium/templates/hubble/tls-helm/_helpers.tpl:20): function "lookup" not defined
[2021-09-28T09:52:09.712Z]     	 
[2021-09-28T09:52:09.712Z]     
[2021-09-28T09:52:09.712Z]     to be nil
```

2021-09-28 15:13 UTC, kaworu commented
> @kaworu Which version of helm using in CI?

[3.3.4 it seems](https://github.com/cilium/cilium/commit/4ae748640a5639199cbe2b40c3d2e5cf703dd312). Let me open a PR to bump to 3.7.0.

2021-10-04 13:13 UTC, kaworu commented
@dungdm93 now that #17488 has been merged, could you rebase this PR please?

2021-10-05 06:34 UTC, dungdm93 commented
@kaworu rebased. Thank you for updating Helm :smile:

2021-10-05 09:01 UTC, kaworu commented
/test

2021-12-06 13:24 UTC, nebril commented
/test

2021-12-16 08:21 UTC, kaworu commented
#
/test

2021-12-16 08:21 UTC, kaworu commented
/test

2021-12-20 16:34 UTC, kaworu commented
/test

2022-01-01 06:03 UTC, dungdm93 commented
/test

2022-01-10 12:38 UTC, gandro commented
/test

2022-01-11 07:56 UTC, kaworu approved these changes

2022-01-11 07:56 UTC, kaworu commented
/test

2022-01-13 15:08 UTC, kaworu commented
/test

2022-01-18 10:52 UTC, nebril commented
/test-gke

2022-01-20 14:13 UTC, kaworu commented
/test-1.23-net-next

2022-01-20 14:13 UTC, kaworu commented
/ci-l4lb

2022-01-20 14:13 UTC, kaworu commented
/test-1.22-4.19

2022-01-20 14:13 UTC, kaworu commented
/test-1.21-5.4

2022-01-21 08:35 UTC, kaworu commented
/test

2022-01-21 13:04 UTC, nebril approved these changes

2022-01-21 13:07 UTC, merged

2022-01-21 13:13 UTC, dungdm93 commented
Thanks you all