test/K8sverifier: Cover several datapath configurations
cilium/cilium pull request #17470
Opened 2021-09-24 17:56 UTC by pchaigno

Blocked on https://github.com/cilium/cilium/pull/17408, which is blocked by flakes.

2021-09-24 17:59 UTC, pchaigno commented
test--5.4

2021-09-24 18:00 UTC, pchaigno commented
test-5.4

2021-09-24 18:00 UTC, pchaigno commented
test-netnext

2021-09-24 18:00 UTC, pchaigno commented
test-4.19

2021-09-24 18:00 UTC, pchaigno commented
test-4.9

2021-09-24 18:04 UTC, pchaigno commented
test-netnext

2021-09-24 18:04 UTC, pchaigno commented
test-5.4

2021-09-24 18:04 UTC, pchaigno commented
test-4.19

2021-09-24 18:04 UTC, pchaigno commented
test-4.9

2021-09-24 21:46 UTC, pchaigno commented
test-netnext

2021-09-24 21:46 UTC, pchaigno commented
test-5.4

2021-09-24 21:47 UTC, pchaigno commented
test-4.9

2021-09-24 21:47 UTC, pchaigno commented
test-4.19

2021-09-27 15:25 UTC, pchaigno commented
```
[2021-09-24T21:58:04.987Z] FAIL: Failed to load BPF program bpf_lxc with datapath configuration:
[2021-09-24T21:58:04.987Z] -DSKIP_DEBUG=1 -DENABLE_IPV6=1 -DENABLE_HOST_SERVICES_TCP=1 -DENABLE_HOST_SERVICES_UDP=1 -DENABLE_HOST_REDIRECT=1 -DENABLE_ROUTING=1 -DNO_REDIRECT=1 -DPOLICY_VERDICT_NOTIFY=1 -DALLOW_ICMP_FRAG_NEEDED=1 -DENABLE_IDENTITY_MARK=1 -DMONITOR_AGGREGATION=3 -DCT_REPORT_FLAGS=0x0002 -DENABLE_HOST_FIREWALL=1 -DHAVE_LPM_TRIE_MAP_TYPE=1 -DHAVE_LRU_HASH_MAP_TYPE=1 -DENABLE_MASQUERADE=1 -DENABLE_SRC_RANGE_CHECK=1 -DENABLE_NODEPORT=1 -DENABLE_NODEPORT_ACCELERATION=1 -DENABLE_SESSION_AFFINITY=1 -DENABLE_DSR_ICMP_ERRORS=1 -DENABLE_DSR=1 -DENABLE_DSR_HYBRID=1 -DENABLE_IPV4_FRAGMENTS=1 -DENABLE_BANDWIDTH_MANAGER=1 -DENCAP_IFINDEX=1 -DTUNNEL_MODE=1 -DENABLE_EGRESS_GATEWAY=1
[2021-09-24T21:58:04.987Z] Expected command: kubectl exec -n default test-verifier -- env TC_PROGS="" XDP_PROGS="" CG_PROGS="" TC_PROGS="bpf_lxc" ./test/bpf/verifier-test.sh 
[2021-09-24T21:58:04.987Z] To succeed, but it failed:
[2021-09-24T21:58:04.987Z] Exitcode: 1 
[2021-09-24T21:58:04.987Z] Err: exit status 1
[2021-09-24T21:58:04.987Z] Stdout:
[2021-09-24T21:58:04.987Z]       => Loading bpf_lxc.c:from-container...
```

```
Failed to load BPF program bpf_lxc with datapath configuration:
-DSKIP_DEBUG=1 -DENABLE_IPV4=1 -DENABLE_HOST_SERVICES_TCP=1 -DENABLE_HOST_SERVICES_UDP=1 -DENABLE_HOST_REDIRECT=1 -DENABLE_ROUTING=1 -DNO_REDIRECT=1 -DPOLICY_VERDICT_NOTIFY=1 -DALLOW_ICMP_FRAG_NEEDED=1 -DENABLE_IDENTITY_MARK=1 -DMONITOR_AGGREGATION=3 -DCT_REPORT_FLAGS=0x0002 -DENABLE_HOST_FIREWALL=1 -DHAVE_LPM_TRIE_MAP_TYPE=1 -DHAVE_LRU_HASH_MAP_TYPE=1 -DENABLE_MASQUERADE=1 -DENABLE_SRC_RANGE_CHECK=1 -DENABLE_NODEPORT=1 -DENABLE_NODEPORT_ACCELERATION=1 -DENABLE_SESSION_AFFINITY=1 -DENABLE_DSR_ICMP_ERRORS=1 -DENABLE_DSR=1 -DENABLE_DSR_HYBRID=1 -DENABLE_IPV4_FRAGMENTS=1 -DENCAP_IFINDEX=1 -DTUNNEL_MODE=1 -DENABLE_EGRESS_GATEWAY=1
Expected command: kubectl exec -n default test-verifier -- env TC_PROGS="" XDP_PROGS="" CG_PROGS="" TC_PROGS="bpf_lxc" ./test/bpf/verifier-test.sh 
To succeed, but it failed:
Exitcode: 1 
Err: exit status 1
Stdout:
 	 => Loading bpf_lxc.c:from-container...
```

2021-10-04 17:27 UTC, pchaigno commented
/test

2021-10-13 23:10 UTC, christarazi approved these changes
:rocket:

2021-10-15 17:02 UTC, kkourt requested changes
LGTM, thanks Paul!

Just a small change I think we should do to be on the safe side if we ever change the `Makefile`.

2021-10-15 17:02 UTC, kkourt commented on test/k8sT/Verifier.go
> +				cmd := fmt.Sprintf("make -C bpf %s.o KERNEL=%s %s=%q", bpfProgram.name, getKernel(), bpfProgram.macroName, datapathConfig)
While it is currently not needed, it might be a good idea to delete the `.o` and `.ll` files before compiling, just to be in the safe side.

There is a `$(LIB)` dependency that, I think, always forces recompilation no matter if the dependencies are newer or older:
```
bpf_host.ll: bpf_host.c $(LIB)
```
Not sure what the intention is, but it seems to be that this is just a leftover.
`$(LIB)` does not exist right now, and the first commit in the Makefile introduced it as:
```
LIB := $(shell find ./lib -name '*.h')
```

If we remove it at some point, then the above `make` will not rebuild the target.

2021-10-15 19:26 UTC, pchaigno commented on test/k8sT/Verifier.go
> +				cmd := fmt.Sprintf("make -C bpf %s.o KERNEL=%s %s=%q", bpfProgram.name, getKernel(), bpfProgram.macroName, datapathConfig)
Nice catch!

2021-10-15 21:26 UTC, kkourt approved these changes
🚀

2021-10-19 08:55 UTC, merged