install: validate cilium tag being set by user
cilium/cilium pull request #17508
Opened 2021-09-30 13:02 UTC by nebril

Since we retired `latest` tag in our image repositories, we need to
validate that user explicitly sets image tags they want to deploy Cilium
from.

This change couldn't have used helm builtin `required` because of magic
image string creating functions that we are using, so instead the
validation happens inside these functions.

2021-09-30 13:22 UTC, kaworu requested changes
Removing the `tag:` lines from `values.yaml` will break our `make update-versions` target sed's magic, see https://github.com/cilium/cilium/blob/1c42ae97fca01bea9af3126400b24d5f29125e16/install/kubernetes/Makefile#L68-L83

I think we should keep `tag: ~` instead of removing it (`tag: ""` would do as well).

2021-10-01 10:26 UTC, nebril commented
@kaworu good catch! fixed

2021-10-04 07:20 UTC, kaworu commented
@nebril don't we want this for other images as well (e.g. relay)?

2021-10-19 07:03 UTC, kaworu requested changes
Can we do this for other images as well please (i.e. relay, both ui images, and clustermesh-apiserver)?

2022-09-10 02:18 UTC, closed without merging