bpf: Add extension for running sock LB on MKE-related containers
cilium/cilium pull request #17513
Opened 2021-10-01 12:50 UTC by borkmann

This adds two hidden/undocumented options to the agent which allows Cilium in
KPR=strict mode to be deployed with Mirantis Kubernetes Engine (MKE):

  --enable-mke=true
  --mke-cgroup-mount=""    (auto-detection as default, or for manual specification:)
  --mke-cgroup-mount="/sys/fs/cgroup/net_cls,net_prio"

MKE adds a number of Docker containers onto each MKE node which are otherwise
neither visible nor managed from Cilium side, example:

  docker network inspect ucp-bridge -f "{{json .Containers }}"  | jq . | grep Name
    "Name": "ucp-kv",
    "Name": "ucp-kube-controller-manager",
    "Name": "ucp-kube-apiserver",
    "Name": "ucp-swarm-manager",
    "Name": "ucp-kubelet",
    "Name": "ucp-auth-store",
    "Name": "ucp-cluster-root-ca",
    "Name": "ucp-hardware-info",
    "Name": "ucp-client-root-ca",
    "Name": "ucp-kube-scheduler",
    "Name": "ucp-proxy",
    "Name": "ucp-controller",

They [0] contain things like the kubeapi-server which then live in their own
network namespace with their own private address range of 172.16.0.0/12. The
link to the hostns is set up from MKE side and are veth pairs which are connected
to a bridge device:

  [...]
  59: br-61d49ba5e56d: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
      link/ether 02:42:b2:e4:55:ff brd ff:ff:ff:ff:ff:ff
      inet 172.19.0.1/16 brd 172.19.255.255 scope global br-61d49ba5e56d
       valid_lft forever preferred_lft forever
  61: vethd56c086@if60: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-61d49ba5e56d state UP group default
      link/ether 06:ad:07:c6:55:e8 brd ff:ff:ff:ff:ff:ff link-netnsid 4
  63: veth7db52f6@if62: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-61d49ba5e56d state UP group default
      link/ether aa:10:e2:d8:b7:6c brd ff:ff:ff:ff:ff:ff link-netnsid 5
  65: vethe23d66c@if64: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-61d49ba5e56d state UP group default
      link/ether ba:f1:e3:de:ce:a0 brd ff:ff:ff:ff:ff:ff link-netnsid 6
  [...]

This is different compared to regular K8s deployments where such components
reside in the hostns. For the socket LB which is enabled in KPR=strict deployments
this is problematic as these containers are not seen the same way as hostns and
therefore not all the translations might take place as we perform in hostns (like
accessing NodePort via loopback/local addressing, etc).

One observation in MKE environments is that cgroups-v2 is only supported with
MCR 20.10 which is not available in every deployment at this point. However, MKE
makes use of cgroup-v1 and under /sys/fs/cgroup/net_cls/ it populates both the
com.docker.ucp/ and docker/ subdirectories. One idea for a non-intrusive fix to
get KPR=strict deployments working is to tag these container's net_cls controllers
with a magic marker which we can then read out from the socket LB with the kernel
extension we added some time ago [1]. Given this relies on 'current' as task we
can query for get_cgroup_classid() to determine that this should have similar
service handling behavior as in hostns.

This has two limitations which were found to be acceptable: i) this will only work
in Kind environments with kernel fixes we upstreamed in [2], and ii) no other
application on the node can use the same net_cls tag. Running MKE on Kind is not
supported at the moment, so i) is a non-issue right now.

This approach has been tested on RHEL8, and Duffie asserted that connectivity works
as expected [when testing] manually.

  [0] https://docs.mirantis.com/mke/3.4/ref-arch/manager-nodes.html
      https://docs.mirantis.com/mke/3.4/ref-arch/worker-nodes.html
  [1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=5a52ae4e32a61ad06ef67f0b3123adbdbac4fb83
  [2] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=8520e224f547cd070c7c8f97b1fc6d58cff7ccaa
      https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=78cc316e9583067884eb8bd154301dc1e9ee945c

Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
Tested-by: Duffie Cooley <dcooley@isovalent.com>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note

```

2021-10-01 12:51 UTC, borkmann commented
test-me-please

2021-10-01 13:17 UTC, borkmann commented
test-me-please

2021-10-01 13:22 UTC, borkmann commented
test-me-please

2021-10-01 14:16 UTC, joamaki approved these changes
Looks reasonable given the constraints in this situation.

2021-10-01 15:21 UTC, borkmann commented
test-me-please

2021-10-01 15:21 UTC, borkmann commented
(rebased)

2021-10-01 15:29 UTC, michi-covalent approved these changes

2021-10-01 21:11 UTC, borkmann commented
(extended commit message to describe other approaches that have been evaluated as well just for the record)

2021-10-01 21:11 UTC, borkmann commented
test-me-please

2021-10-01 21:28 UTC, joestringer approved these changes
Thanks for the well-written explanation in the commit message. Seems like most reasonable option we have for supporting MKE today, and this code is pretty self-contained. I can't wait for some combination of socket cookies or cgroup v2 to let us solve this problem without platform-specific tricks like this.

2021-10-04 07:23 UTC, borkmann commented
/mlh new-flake Cilium-PR-K8s-1.16-net-next

2021-10-04 09:31 UTC, brb requested changes
The logic LGTM, a few nits.

Also, maybe it makes sense to extend the commit msg in order to mention the Istio usecase wrt the socket-lb bypass (that's how we discovered the issue) in the following paragraph:

> This is different compared to regular K8s deployments where such components
reside in the hostns. For the socket LB which is enabled in KPR=strict deployments
this is problematic as these containers are not seen the same way as hostns and
therefore not all the translations might take place as we perform in hostns (like
accessing NodePort via loopback/local addressing, etc).

2021-10-04 09:31 UTC, brb commented on daemon/cmd/kube_proxy_replacement.go
> +				log.Fatalf("BPF kube-proxy replacement under MKE with --%s needs kernel 5.7 or newer", option.EnableMKE)
Shouldn't we panic only when `strict == true`?

2021-10-04 09:31 UTC, brb commented on daemon/cmd/kube_proxy_replacement.go
> +func markHostExtension() {
Small comment why this function is needed for those who won't read the commit msg (also, when e.g., after refactoring `git blame` won't point to the original commit) is useful.

2021-10-04 09:31 UTC, brb commented on daemon/cmd/kube_proxy_replacement.go
> +		if option.Config.EnableMKE {
Shouldn't this be in the `if option.Config.EnableHostReachableServices {` branch above??

2021-10-04 09:31 UTC, brb commented on daemon/cmd/kube_proxy_replacement.go
> +			log.WithError(err).Fatal("Cannot retrieve mount infos")
s/Cannot retrieve mount infos/Cannot retrieve mount infos for MKE/

2021-10-04 09:31 UTC, brb commented on daemon/cmd/kube_proxy_replacement.go
> +		log.Fatal("Cannot retrieve cgroup v1 net_cls mount info")
Ditto.

2021-10-04 09:31 UTC, brb commented on daemon/cmd/kube_proxy_replacement.go
> +			log.Infof("Marking %s as MKE host extension", path)
Please use the structured logging i.e., `WithField(logfields.Path: path).Info("Marking MKE host extension"`.

2021-10-04 09:31 UTC, brb commented on daemon/cmd/kube_proxy_replacement.go
> +			f, err := os.OpenFile(path+"/net_cls.classid", os.O_RDWR, 0644)
Shall we warn if net_cls.classid is non zero?

2021-10-04 14:46 UTC, borkmann commented
test-me-please

2021-10-04 14:56 UTC, borkmann commented
test-me-please

2021-10-04 16:17 UTC, brb approved these changes

2021-10-04 19:06 UTC, borkmann commented
retest-gke

2021-10-05 06:18 UTC, borkmann commented
/mlh new-flake Cilium-PR-K8s-1.16-net-next

2021-10-05 06:19 UTC, merged