aks: fix AKS cluster creation following new taint limitations
cilium/cilium pull request #17529
Opened 2021-10-04 16:57 UTC by nbusseneau

Context: we recommend recommend users taint all nodepools with `node.cilium.io/agent-not-ready=true:NoSchedule` to prevent application pods from being managed by the default AKS CNI plugin.

To this end, the proposed workflow users should follow when installing Cilium into AKS was to replace the initial AKS node pool with a new tainted system node pool, as it is not possible to taint the initial AKS node pool, cf. Azure/AKS#1402

AKS recently pushed a change on the API side that forbids setting up custom taints on system node pools, cf. Azure/AKS#2578

It is not possible anymore for us to recommend users taint all nodepools with `node.cilium.io/agent-not-ready=true:NoSchedule` to prevent application pods from being managed by the default AKS CNI plugin.

To work around this new limitation, we propose the following workflow instead:

- Replace the initial node pool with a system node pool tainted with `CriticalAddonsOnly=true:NoSchedule`, preventing application pods from being scheduled on the system node pool.
- Create a secondary user node pool tainted with `node.cilium.io/agent-not-ready=true:NoSchedule` to prevent application pods from being scheduled on the user node pool until Cilium is ready to manage them.

2021-10-11 18:38 UTC, joestringer requested changes
Minor nit in the docs but otherwise makes sense.

I debated a little bit about the use of `.. code-block:: bash` rather than `.. code-block:: shell-session` but in this case unless we dress up the `#` lines with some extra `#`s at the beginning, I think that shell-session would interpret the comments as commands to run as root. So bash seems fine to me (also consistent with other commands in the same guide).

2021-10-11 18:38 UTC, joestringer commented on Documentation/gettingstarted/k8s-install-default.rst
> +       above, the node pools can be set up with the following commands:
The user has reached this page and is following the docs. We don't need to discuss what they are remembering or forgetting. We just need to provide them with concise instructions on what to do in order to correctly set up the cluster.

```suggestion
       Taint user node pools with ``node.cilium.io/agent-not-ready=true:NoSchedule``
       to ensure that applications pods will only be scheduled once Cilium is
       ready to manage them.

       If the AKS cluster was created following the :ref:`create_cluster` guide
       above, the node pools can be set up with the following commands:
```

2021-10-11 21:24 UTC, aanm requested changes

2021-10-11 21:24 UTC, aanm commented on .github/workflows/conformance-aks-v1.10.yaml
> +            ${{ env.cost_reduction }}
Why don't we add the user-node pool before installing cilium like it was previously done?

2021-10-11 21:24 UTC, aanm commented on .github/workflows/conformance-aks.yaml
> +          # to manage them.
Same question here.

2021-10-12 13:27 UTC, nbusseneau commented on .github/workflows/conformance-aks-v1.10.yaml
> +            ${{ env.cost_reduction }}
I wanted to mimic the EKS process of installing Cilium before spawning further nodes, but you're right that it does not really matter thanks to the taints.

2021-10-12 14:24 UTC, nbusseneau commented on Documentation/gettingstarted/k8s-install-default.rst
> +       above, the node pools can be set up with the following commands:
I have reworked the documentation after reordering AKS node pool management following André's comments, completely getting rid of this part. PTAL.

2021-10-12 14:24 UTC, nbusseneau commented on .github/workflows/conformance-aks-v1.10.yaml
> +            ${{ env.cost_reduction }}
I have reworked the PR, PTAL.

2021-10-12 14:24 UTC, nbusseneau commented on .github/workflows/conformance-aks.yaml
> +          # to manage them.
Same answer here :D

2021-10-12 14:26 UTC, nbusseneau commented
Note: please disregard spelling mistakes and `cd` in commit messages, I will fix this in next push after next round of reviews.

2021-10-12 17:33 UTC, joestringer reviewed
:+1: looking simpler which is always a win. I have some minor wording nits / suggestions to try to integrate the explanations more directly into the text. Feel free to take/leave/modify whichever you think improve on the text.

2021-10-12 17:33 UTC, joestringer commented on Documentation/gettingstarted/k8s-install-default.rst
> +       notes below for more context on the operations.
This text is under a tab inside the "Create the cluster" section. The docs are about to instruct the user exactly what they need to do to create the cluster.

What does this new sentence describe that the docs cannot describe by just instructing the user directly about what to do?

2021-10-12 17:33 UTC, joestringer commented on Documentation/gettingstarted/k8s-install-default.rst
> +          these limitations, the operations above propose to:
nit:
```suggestion
          these limitations, the operations above will:
```

2021-10-12 17:33 UTC, joestringer commented on Documentation/gettingstarted/k8s-install-default.rst
> +           # Create user node pool tainted with `node.cilium.io/agent-not-ready=true:NoSchedule`
```suggestion
           # Create user node pool tainted with `node.cilium.io/agent-not-ready=true:NoSchedule`.
           # This will be the node pool used for deploying application pods.
```

2021-10-12 17:33 UTC, joestringer commented on Documentation/gettingstarted/k8s-install-default.rst
> +       notes below for more context on the operations.
Actually, I wonder if it would make sense to front-load a little bit more of the description about what's going on up here near the start. Something like,

```suggestion
       for instructions on how to install ``az`` and prepare your account.
       
       These instructions create the cluster and configure multiple `AKS node pools <https://aka.ms/aks/nodepools>__` with specific taints in order to ensure that Cilium is correctly installed before workloads are scheduled onto any of the nodes. 
```

Note the factual tone, "this does X" / "the reason is Y" rather than instructing the user to see "below" (where?) for more context (what context? How do I know if I need to know more?).

2021-10-12 17:33 UTC, joestringer commented on Documentation/gettingstarted/k8s-install-default.rst
> +           # pools, see https://aka.ms/aks/nodepools)
nit, in general brackets and long sentences make instructions more difficult to read. I think that this is trying to communicate several points:
* Instruct the user to create the node / load balancer
* Let them know that we'll delete it later
* Let them know why we're using a specific load balancer

We can make this a bit clearer to the user by breaking up each point into its own sentence, eg:

```suggestion
           # Create AKS cluster with an initial node pool of 1 node and a standard
           # load balancer. This initial node pool is necessary for bootstrapping the 
           # cluster, but it will be deleted in later instructions. The standard load
           # balancer is required to configure multiple node pools (see https://aka.ms/aks/nodepools).
```

2021-10-12 20:44 UTC, nbusseneau commented on Documentation/gettingstarted/k8s-install-default.rst
> +       notes below for more context on the operations.
I'm not quite sure I got what you meant 😅 The "See notes below" thing is because I felt it was better to have the commands up front for folks to copy/paste mindlessly and the detailed explanations right below the commands for those that want to know why this is all needed and so complicated on AKS. It is not supposed to reference the requirements even further below, if that was what you meant.

2021-10-12 20:46 UTC, nbusseneau commented on Documentation/gettingstarted/k8s-install-default.rst
> +           # pools, see https://aka.ms/aks/nodepools)
I tried to keep the comments light since the detailed explanations are right below the commands. If we agree this is sane, I would go even lighter and skip the details rather than give more details, otherwise I would tend to say it would probably be better to go back to having very detailed comments all around and remove the notes below.

2021-10-12 20:59 UTC, joestringer commented on Documentation/gettingstarted/k8s-install-default.rst
> +       notes below for more context on the operations.
I think this is kinda the point, I didn't understand what the sentence was supposed to be pointing to or how I, as a reader, am supposed to know if it's something I'm interested in. "look somewhere for context on the operations" leaves me wondering should I be searching for the context (again, where?) or should I just ignore this random sentence and follow the instructions? And if I'm gonna ignore the sentence anyway, then it's just noise. Why are the docs telling me to look somewhere if the section is clearly trying to tell me to actually just run some commands?

Maybe an alternative suggestion that could also make it clearer would be to replace the new sentence with "Follow these instructions to ensure that Cilium is configured correctly. For more information about why these commands should be run in this way, see the note below the commands."? (or could even add a reference link to make it even more clear where the explanation is).

2021-10-12 21:00 UTC, joestringer commented on Documentation/gettingstarted/k8s-install-default.rst
> +       notes below for more context on the operations.
(but it's getting kinda bikesheddy, if you think it's clear enough already then I think it's fine to pass on this feedback).

2021-10-12 21:01 UTC, joestringer commented on Documentation/gettingstarted/k8s-install-default.rst
> +           # pools, see https://aka.ms/aks/nodepools)
:+1: yeah I think it'd be easier to try to keep the explanation together somewhere and then keep the actual instructions a bit lighter.

2021-10-12 21:09 UTC, nbusseneau commented on Documentation/gettingstarted/k8s-install-default.rst
> +       notes below for more context on the operations.
No definitely agree, I had issues finding a format that I felt was light enough for those who don't care while keeping details close enough for those who do care. If rewording the "See the notes" bit is enough, then let's do that!

2021-10-12 22:32 UTC, aanm approved these changes

2021-10-13 16:39 UTC, nbusseneau commented on Documentation/gettingstarted/k8s-install-default.rst
> +           # pools, see https://aka.ms/aks/nodepools)
Went lighter now that we recommend reading the detailed note below.

2021-10-13 16:40 UTC, nbusseneau commented on Documentation/gettingstarted/k8s-install-default.rst
> +       notes below for more context on the operations.
Reworded, PTAL.

2021-10-13 17:18 UTC, joestringer approved these changes

2021-10-13 17:23 UTC, tklauser approved these changes

2021-10-13 19:19 UTC, nbusseneau commented
All reviews are in, no need to run any additional CI as this only modifies documentation and the AKS workflow, marking as ready to merge.

2021-10-13 22:03 UTC, merged

2021-10-18 10:56 UTC, nbusseneau commented
@joamaki I added the backport label for the documentation changes. The workflows indeed are already "backported" in a sense, since they live in `master` even though they are used by the 1.10 PRs.