helm: Expose l2 neigh discovery related agent flags
cilium/cilium pull request #17526
Opened 2021-10-04 13:59 UTC by brb

This commit exposes the following flags:

- `--enable-l2-neigh-discovery` via `l2NeighDiscovery.enabled`.
- `--arping-refresh-period` via `l2NeighDiscovery.refreshPeriod`.

2021-10-04 18:09 UTC, joestringer approved these changes

2021-10-05 09:07 UTC, kaworu requested changes
Both values should be added to `install/kubernetes/cilium/values.yaml` with a leading comment starting with `--`.

Then, run `make -C install/kubernetes docs` in order to update `install/kubernetes/cilium/README.md`.

2021-10-05 18:45 UTC, nathanjsweet approved these changes

2021-10-06 07:30 UTC, kaworu approved these changes

2021-10-06 08:22 UTC, brb commented
test-1.20-4.19

2021-10-07 15:35 UTC, merged