Refactor CEBtoCEPs and CEPtoCEB maps
cilium/cilium pull request #17543
Opened 2021-10-06 00:18 UTC by krishgobinath

1) Use single lock to protect both the CEBtoCEPs and CEPtoCEB
maps.

Signed-off-by: Gobinath Krishnamoorthy <gobinathk@google.com>

2021-10-06 02:56 UTC, Weil0ng approved these changes
Change LGTM, can you please update the commit msg/PR description to elaborate what was the issue and how this fixes it?

2021-10-11 23:09 UTC, aanm requested changes
Please add the PR description in the commit message as well. Thank you

2021-10-11 23:09 UTC, aanm commented on operator/pkg/ciliumendpointbatch/ceptocebmap.go
> +	CEPNameToCEBName map[CEPName]CEBName
this field should be made private at the risk of being accessed outside this package without holding the RWMutex.

2021-10-12 00:10 UTC, krishgobinath commented on operator/pkg/ciliumendpointbatch/ceptocebmap.go
> +	CEPNameToCEBName map[CEPName]CEBName
Good point.

2021-10-12 20:10 UTC, aanm approved these changes

2021-10-12 20:11 UTC, merged