docs: clarify uses of --direct-routing-device
cilium/cilium pull request #17578
Opened 2021-10-12 10:21 UTC by kkourt

--direct-routing-device is also used for BPF fast redirect. Clarify this
in its usage doc.

Signed-off-by: Kornilios Kourtis <kornilios@gmail.com>

2021-10-12 10:24 UTC, brb requested changes

2021-10-12 10:24 UTC, brb commented on Documentation/cmdref/cilium-agent.md
> +      --direct-routing-device string                         Device name used to connect nodes in direct routing mode (used by BPF NodePort, BPF fast
You need to change the flag description in the daemon_main.go and then regenerate cilium-agent.md (`make -C Documentation cmdref`)

2021-10-12 14:34 UTC, jibi approved these changes

2021-10-12 14:44 UTC, kkourt commented on Documentation/cmdref/cilium-agent.md
> +      --direct-routing-device string                         Device name used to connect nodes in direct routing mode (used by BPF NodePort, BPF fast
Ah yes, forgot about this! Should be fixed now (although the corresponding travis test did not run).

2021-10-19 07:31 UTC, brb approved these changes

2021-10-19 09:01 UTC, merged