Process source node CiliumEndpoints in CEB watch events
cilium/cilium pull request #17571
Opened 2021-10-11 16:05 UTC by krishgobinath

Update CEPs in all cilium nodes including source node CEPs.

Found couple of issues while running CI tests against CEB feature enabled default.

1) If CEP's are updated through CEB watch events, process CEPs in all nodes. Currently, we are
skipping CEP updates in source nodes. 
Here is why we need to update on all nodes...
a) If a pod is deleted, and the corresponding CEP is removed from source node. If CEPs are updated through CEB watcher, in `OnDelete` [function](https://github.com/cilium/cilium/blob/feature/cep-scalability/pkg/k8s/watchers/cilium_endpoint_batch_subscriber.go#L136-L150) we are unable to identify the CEP is local to the node or not, in the below case `LookupPodName` returns `nil` for source node CEP, hence we are calling `cs.kWatcher.endpointDeleted`

```
    if p := cs.kWatcher.endpointManager.LookupPodName(k8sUtils.GetObjNamespaceName(c)); p != nil {
			continue
   }
```
However, in `endpointDeleted`, we were trying to [delete ipCache](https://github.com/cilium/cilium/blob/feature/cep-scalability/pkg/k8s/watchers/cilium_endpoint.go#L230-L235) but that ends up in cilium-agent crash because for source node CEP's we never upserted `ipcache` as mentioned [here](https://github.com/cilium/cilium/blob/feature/cep-scalability/pkg/k8s/watchers/cilium_endpoint.go#L178-L212) because we always skip CEP updating for source node CEPs.

2) Program QPS limit and Burst limit to default values

In our code default qps and burst limit values are zero `option.Config.K8sClientQPSLimit` and `option.Config.K8sClientBurst`, unless they are configured in cilium configmap.

If the given `qps, burst` values are zero k8s client will override with defaults values, as mentioned [here](https://github.com/cilium/cilium/blob/master/pkg/defaults/defaults.go#L359-L365). 

For workqueues, if `qps limit` is zero, then 'queue.AddRateLimited` API isn't working, it's not adding the `work item` back into queue. Hence we need to program default qps, burst  values for workqueues.

Signed-off-by: Gobinath Krishnamoorthy gobinathk@google.com

2021-10-13 16:59 UTC, Weil0ng commented on operator/pkg/ciliumendpointbatch/endpointbatch.go
> +	workQueuesBurstLimit = 100
is this too high? 100 qps for CEB updates seems like it could easily kill apiserver?

2021-10-13 17:02 UTC, krishgobinath commented on operator/pkg/ciliumendpointbatch/endpointbatch.go
> +	workQueuesBurstLimit = 100
QPS is 10, but burst is 100. These values are inline with endpoint slice implementation. Irrespective of that K8S client would cap the number of requests going into api-server.

2021-10-13 18:09 UTC, Weil0ng commented on operator/pkg/ciliumendpointbatch/endpointbatch.go
> +	workQueuesBurstLimit = 100
sgtm, another small nit is that these two default values should have more specific names, workqeuue is too general, some other component might also use workqueue and want a different QPS/Burst.

2021-10-13 22:51 UTC, aanm requested changes

2021-10-13 22:51 UTC, aanm commented on pkg/k8s/watchers/cilium_endpoint_batch_subscriber.go
>  		if p := cs.kWatcher.endpointManager.LookupPodName(k8sUtils.GetObjNamespaceName(c)); p != nil {
The comment on line 47-48 can be removed now.

2021-10-13 22:51 UTC, aanm commented on pkg/k8s/watchers/cilium_endpoint_batch_subscriber.go
>  			if p := cs.kWatcher.endpointManager.LookupPodName(k8sUtils.GetObjNamespaceName(c)); p != nil {
The comment on line 100-101 can be removed now.

2021-10-14 01:13 UTC, Weil0ng approved these changes

2021-10-14 17:50 UTC, krishgobinath commented on pkg/k8s/watchers/cilium_endpoint_batch_subscriber.go
>  		if p := cs.kWatcher.endpointManager.LookupPodName(k8sUtils.GetObjNamespaceName(c)); p != nil {
Done.

2021-10-14 17:50 UTC, krishgobinath commented on pkg/k8s/watchers/cilium_endpoint_batch_subscriber.go
>  			if p := cs.kWatcher.endpointManager.LookupPodName(k8sUtils.GetObjNamespaceName(c)); p != nil {
Done.

2021-10-15 19:38 UTC, aanm approved these changes

2021-10-15 19:38 UTC, merged