docs: fix docs following #17526
cilium/cilium pull request #17570
Opened 2021-10-11 14:50 UTC by nbusseneau

It seems we forgot to update `helm-values.rst` in #17526, yielding issues when building documentation locally with `make render-docs`:

```
Please fix the following spelling mistakes:
* Documentation/helm-reference.rst:876: (NeighDiscovery)
* Documentation/helm-reference.rst:876: (arping)
* Documentation/helm-reference.rst:877: (arping)
* Documentation/helm-reference.rst:880: (NeighDiscovery)
* Documentation/helm-reference.rst:881: (neighbour)
* Documentation/helm-values.rst:876: (NeighDiscovery)
* Documentation/helm-values.rst:876: (arping)
* Documentation/helm-values.rst:877: (arping)
* Documentation/helm-values.rst:880: (NeighDiscovery)
* Documentation/helm-values.rst:881: (neighbour)

If the words are not misspelled, run:
Documentation/update-spelling_wordlist.sh NeighDiscovery arping neighbour
```

Since we already have more occurrences of `neighbor` (US spelling) in the repo, we replace `neighbour` with `neighbor` for consistency and then fix `helm-values.rst` + spelling wordlist.

2021-10-11 16:08 UTC, qmonnet requested changes

2021-10-11 16:08 UTC, qmonnet commented on Documentation/spelling_wordlist.txt
> +neighbour
We have more occurrences of `neighbor` (US spelling) overall in the repo. Would you mind updating the description of the related option instead, to be more consistent and to avoid adding the British spelling to this list, please?

2021-10-11 16:25 UTC, nbusseneau commented on Documentation/spelling_wordlist.txt
> +neighbour
Done!

2021-10-11 16:51 UTC, qmonnet approved these changes
Thank you!

2021-10-12 06:52 UTC, kaworu approved these changes

2021-10-12 11:09 UTC, merged