policy: Add a bpf compiling option when `enable-icmp-rules` flag is set
cilium/cilium pull request #17620
Opened 2021-10-15 15:31 UTC by chez-shanpu

By this commit, bpf program is compiled with `-DENABLE_ICMP_RULE` option when `enable-icmp-rules` flag is set.

Signed-off-by: Tomoki Sugiura <tomoki.sugiura@mail.shanpu.info>

2021-10-19 17:18 UTC, joestringer requested changes
Thanks for the fix. Just one comment below, usually we we define these in the headerfiles instead of passing additional arguments directly to the compiler. Would be good to keep that consistent.

2021-10-19 17:18 UTC, joestringer commented on pkg/datapath/loader/compile.go
> +			p.Options = append(p.Options, enableICMPRuleFlag)
Usually we will define these in the headerfiles that go into the program, via `pkg/datapath/linux/config/config.go`. This means that we can also trace how the program was compiled by observing the files on the filesystem after the fact. Could you use that approach?

2021-10-20 02:05 UTC, chez-shanpu commented on pkg/datapath/loader/compile.go
> +			p.Options = append(p.Options, enableICMPRuleFlag)
Sure, I'll fix it :)

2021-10-20 16:33 UTC, joestringer approved these changes
LGTM, thanks.

2021-10-21 09:07 UTC, ti-mo approved these changes

2021-10-22 03:51 UTC, chez-shanpu commented
Okay, I would open another PR (or use existing PR #17135) when I add an e2e test for this function.

2021-10-22 06:04 UTC, merged