Speed up build image process for PRs
cilium/cilium pull request #17623
Opened 2021-10-17 19:34 UTC by aanm

Most of the PRs use the same code base. Thus, we can store Golang's
build cache on GitHub and re-use it for PR builds to speed up the
building process of the PRs code.

Since Docker buildx share the mount of type 'cache' across image builds,
the GitHub workflow to build images will populate its cache using a
'dummy' Dockerfile located in 'images/cache/Dockerfile'. This cache will
always be updated every time a build is executed in the master branch
and all PRs will reuse this cache to build their images.

The times that take each build process are:
```
Current build process     - master branch - ~ 11m3s
Build with cache hit      - master branch - ~ 9m26s (-14.63%)
Build with cache miss [1] - master branch - ~ 12m (+8.59%)

Current build process     - Pull Request  - ~ 11m1s
Cache hit PR [2]          - Pull Request  - ~ 4m17 (-61.11%)
```
[1] A cache miss will only happen if the cache is cleaned up / deleted
will only be deliberate.

[2] This was tested on a source code where there was a new line added
in the cilium-agent source code. Adding a new line meant that most of
the build cache was reused. The best case scenario are PRs that don't
change a single line of the Golang's source code, where the build
process will take less than 4m17s. The worst case scenario will be a PR
that change all of the source code for which the build time will be no
worse than 11m1s.

The reason why it takes more time on a cache hit on the master branch
than on a PR cache hit is due to the fact that the master branch will
spend the time storing the new cache where the PR will not store any
cache

Fixes https://github.com/cilium/cilium/issues/14928

2021-10-18 16:04 UTC, nbusseneau requested changes
AFAIK there is no need for the `Image CI Cache Cleaner` workflow due to GitHub Actions default behaviour: https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy

Is there any reason we need the manual cleaning on top of it? 🤔

2021-10-18 17:25 UTC, christarazi approved these changes
:rocket:

2021-10-19 10:53 UTC, twpayne approved these changes

2021-10-19 11:17 UTC, nbusseneau commented
> That is correct but the golang cache will grow forever, that's what needs to be cleaned up once in a while. The master branch will use the GH cache as well to create the new GH cache. The old GH cache will be GCed but the new GH cache will contain the old golang cache and that needs to be cleaned up.

Aaah I see. I'm not familiar with Golang's build cache, unfortunate it does not optimize/clean by itself.

2021-10-19 11:18 UTC, nbusseneau approved these changes

2021-10-19 13:07 UTC, merged

2021-11-03 22:20 UTC, aanm commented
@jrajahalme yes that is correct. Not only from forks but any PR needs to be rebased with master.