Register types related to K8s Ingress
cilium/cilium pull request #17637
Opened 2021-10-19 00:21 UTC by michi-covalent

please review commit by commit:

- 689581540b1de6d03d089bdfbd61e9c18d4f1aa1 Add types related to K8s Ingress.
- 7186ac70e4e0efeb7d989fe806564246e4456777 Generate k8s client and register ingress types.

2021-10-19 04:05 UTC, michi-covalent commented
/test

2021-10-19 10:23 UTC, aanm requested changes
Just double checking, will we use all fields of all structures? If no, might make sense to remove certain fields.

Also, it would be nice to have the code that will use these structures in this same PR instead of different PRs.

2021-10-19 10:23 UTC, aanm commented on pkg/k8s/slim/k8s/api/networking/v1/types.go
> +type IngressClassList struct {
This, similarly to `IngressClass`, `Ingress` and `IngressList`, needs to be registered in the file pkg/k8s/slim/k8s/api/networking/v1/register.go

2021-10-19 16:09 UTC, michi-covalent commented on pkg/k8s/slim/k8s/api/networking/v1/types.go
> +type IngressClassList struct {
yeah i did that in the next commit: https://github.com/cilium/cilium/blob/7186ac70e4e0efeb7d989fe806564246e4456777/pkg/k8s/slim/k8s/api/networking/v1/register.go#L35

would it be easier to review if it's a single commit?

2021-10-19 16:30 UTC, michi-covalent commented
> Just double checking, will we use all fields of all structures? If no, might make sense to remove certain fields.

i'd say yes we will use all these fields in the future.

> Also, it would be nice to have the code that will use these structures in this same PR instead of different PRs.

that's yet to be written :joy_cat: i'm trying to keep each PR to a reasonable size, it's already +6k lines although it's mostly auto-generated code...

2021-11-01 12:20 UTC, jrajahalme commented on operator/watchers/envoy_config.go
> +			// Ingress:         true,
This is a flag for *proxy ingress to pod* vs. *proxy egress from pod*. This is not to be used with k8s Ingress :-). Also, it is yet to be seen if we will ever actually need CiliumEnvoyConfig for pod ingress. So far it is completely untested and the bpf datapath support for it is also missing.

2021-12-07 00:44 UTC, michi-covalent commented
moved to https://github.com/cilium/cilium/pull/18127. closing

2021-12-07 00:44 UTC, closed without merging