daemon: add K8sCacheIsSynced() method
cilium/cilium pull request #17651
Opened 2021-10-20 13:17 UTC by jibi

This method allows to check whether the agent has fully synced its k8s
cache with the API server or not.

2021-10-20 16:36 UTC, christarazi requested changes
LGTM pending the following commit. Thanks for the PR!

2021-10-20 16:36 UTC, christarazi commented on pkg/k8s/init.go
> +
No need to introduce a canonical interface. It can be created wherever the consumer uses `K8sCacheIsSynced()`.

Example:

```go
func NewFoo(checker k8sCacheSyncChecker) *Foo {
  return &Foo{
    checker: checker,
    ...
}

type k8sCacheSyncChecker interface {
  K8sCacheIsSynced() bool
}
```

2021-10-20 17:22 UTC, jibi commented on pkg/k8s/init.go
> +
Makes sense, removed the canonical interface :+1:

2021-10-20 18:34 UTC, christarazi approved these changes

2021-10-21 00:31 UTC, aanm approved these changes

2021-10-21 00:31 UTC, merged