v1.10 backports 2021-10-20
cilium/cilium pull request #17652
Opened 2021-10-20 13:39 UTC by joamaki

* #16507 -- workflows: Fix use of paths-filter on master pushes (@pchaigno)
 * #17511 -- node: Skip ipcache for remote node IPs if IPsec is enabled (@pchaigno)
 * #17157 -- contrib/backporting: Dockerize backporting scripts (@aditighag)
 * #17470 -- test/K8sVerifier: Cover several datapath configurations (@pchaigno)
 * #17573 --  bpf: Additional tail calls for IPvX-only setups (@pchaigno)

Edit (@kkourt):
Backporting #17470 showed that #17490 also affects v1.10, so I've also pulled in the fix: #17573

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 16507 17511 17157 17470 17573; do contrib/backporting/set-labels.py $pr done 1.10; done
```
or with
```
$ make add-label branch=v1.10 issues=16507,17511,17157,17470,17573
```

2021-10-20 16:08 UTC, pchaigno requested changes
Small change required below—small in scope/time but maybe not in line changes :sweat_smile:

2021-10-20 16:08 UTC, pchaigno commented on bpf/complexity-tests/419/bpf_host.txt
> +-DSKIP_DEBUG=1 -DENABLE_IPV4=1 -DENABLE_IPV6=1 -DENABLE_HOST_SERVICES_TCP=1 -DENABLE_HOST_SERVICES_UDP=1 -DENABLE_HOST_REDIRECT=1 -DENABLE_ROUTING=1 -DNO_REDIRECT=1 -DPOLICY_VERDICT_NOTIFY=1 -DALLOW_
A couple config macros were [removed in master](https://github.com/cilium/cilium/commit/040d264ebcd7b9fb1ce60baeb2beffe1c89576c9) but are still present in v1.10, so we need to update those configurations to take those macros into account. I think simply replacing the substring `-DENABLE_NODEPORT=1 -DENABLE_NODEPORT_ACCELERATION=1 -DENABLE_SESSION_AFFINITY=1 -DENABLE_DSR_ICMP_ERRORS=1 -DENABLE_DSR=1 -DENABLE_DSR_HYBRID=1` in all `bpf/complexity-tests/` files with `-DENABLE_NODEPORT=1 -DENABLE_EXTERNAL_IP=1 -DENABLE_NODEPORT_ACCELERATION=1 -DENABLE_SESSION_AFFINITY=1 -DENABLE_DSR_ICMP_ERRORS=1 -DENABLE_DSR=1 -DENABLE_HOSTPORT=1 -DENABLE_LOADBALANCER -DENABLE_DSR_HYBRID=1` should do it. Could you make that change? :pray:

2021-10-20 16:14 UTC, aditighag approved these changes
Backport of my commit looks good. Thanks!

2021-10-20 16:45 UTC, joamaki commented on bpf/complexity-tests/419/bpf_host.txt
> +-DSKIP_DEBUG=1 -DENABLE_IPV4=1 -DENABLE_IPV6=1 -DENABLE_HOST_SERVICES_TCP=1 -DENABLE_HOST_SERVICES_UDP=1 -DENABLE_HOST_REDIRECT=1 -DENABLE_ROUTING=1 -DNO_REDIRECT=1 -DPOLICY_VERDICT_NOTIFY=1 -DALLOW_
Heading to PTO, so I'll hand this over to @kkourt who volunteered to help out :smile:

2021-10-20 16:52 UTC, pchaigno commented on bpf/complexity-tests/419/bpf_host.txt
> +-DSKIP_DEBUG=1 -DENABLE_IPV4=1 -DENABLE_IPV6=1 -DENABLE_HOST_SERVICES_TCP=1 -DENABLE_HOST_SERVICES_UDP=1 -DENABLE_HOST_REDIRECT=1 -DENABLE_ROUTING=1 -DNO_REDIRECT=1 -DPOLICY_VERDICT_NOTIFY=1 -DALLOW_
@joamaki Thanks for the heads up. Enjoy :mount_fuji: !

@kkourt It should be a simple sed command to replace :slightly_smiling_face: Happy to help if anything goes wrong of course!

2021-10-21 00:28 UTC, aanm approved these changes

2021-10-21 11:09 UTC, kkourt commented on bpf/complexity-tests/419/bpf_host.txt
> +-DSKIP_DEBUG=1 -DENABLE_IPV4=1 -DENABLE_IPV6=1 -DENABLE_HOST_SERVICES_TCP=1 -DENABLE_HOST_SERVICES_UDP=1 -DENABLE_HOST_REDIRECT=1 -DENABLE_ROUTING=1 -DNO_REDIRECT=1 -DPOLICY_VERDICT_NOTIFY=1 -DALLOW_
@pchaigno I did as suggested. Could you please have another look?

2021-10-21 13:55 UTC, pchaigno approved these changes
Thanks!

2021-10-21 13:56 UTC, pchaigno commented
/test-backport-1.10

2021-10-21 20:28 UTC, kkourt commented
@pchaigno, I guess it is  [expected](https://github.com/cilium/cilium/pull/17573#issuecomment-940972690) that the verifier test will fail on 4.19 as it does?

2021-10-22 08:32 UTC, pchaigno approved these changes
>  Seems to me that it's better to pick up the fix now rather than on the next round.

Definitely, otherwise it would break the tests.

2021-10-22 12:04 UTC, merged