k8s: move all kubernetes deployment files to a single file
cilium/cilium pull request #1766
Opened 2017-10-16 13:13 UTC by aanm

Update docs and tests with this new change

Signed-off-by: André Martins <andre@cilium.io>

2017-10-16 14:49 UTC, nebril approved these changes
LGTM

2017-10-16 15:55 UTC, ianvernon requested changes

2017-10-16 15:55 UTC, ianvernon commented on examples/kubernetes/cilium.yaml
> +    # and add the certificate in cilium-etcd-secrets on line 38.
This should refer to a comment / tag instead of a specific line number, as the line number can change if someone edits this file.

2017-10-16 15:55 UTC, ianvernon commented on examples/kubernetes/cilium.yaml
> +  # certificate has a k8s secret, see explanation on line 38.
This should refer to a comment / tag instead of a specific line number, as the line number can change if someone edits this file.

2017-10-16 15:55 UTC, ianvernon commented on examples/kubernetes/cilium.yaml
> +  - networkpolicies #FIXME remove this when we drop support for k8s NP-beta
Please create a corresponding GH issue which links to this FIXME and add GH-<issue number> on this line so we don't forget about it in the future

2017-10-16 15:55 UTC, ianvernon commented on Documentation/install.rst
>      * NOTE: before you deploy the cilium DaemonSet, make sure you change the image for cilium to be "latest" instead of "stable". Once Cilium 0.10 is released, this is not necessary.
This line can be removed.

2017-10-16 23:01 UTC, ianvernon approved these changes
Looks great! A reduction in the verbosity of our scripts + Docs while maintaining the same functionality makes me quite happy :D

2017-10-16 23:01 UTC, ianvernon commented on examples/kubernetes/cilium.yaml
> +  # "ETCD-CERT"
This is exactly what I wanted, thanks!

2017-10-17 06:30 UTC, aalemayhu approved these changes

2017-10-17 09:36 UTC, merged