Minor egress gateway fixups
cilium/cilium pull request #17663
Opened 2021-10-21 19:36 UTC by pchaigno

I was following the egress gateway implementation while implementing the SRv6 support and found a couple mistakes. This pull request fixes them. See commits for details.

I had reviewed the egress gateway pull requests, but it's interesting to see how much more you find once you start coding yourself.

2021-10-22 20:52 UTC, nathanjsweet requested changes
just nits

2021-10-22 20:52 UTC, nathanjsweet commented on pkg/k8s/apis/cilium.io/client/crds/v2alpha1/ciliumegressnatpolicies.yaml
> -    - description: The age of the identity
Why is this going away?

2021-10-22 20:52 UTC, nathanjsweet commented on pkg/k8s/apis/cilium.io/v2alpha1/types.go
> +// +kubebuilder:printcolumn:JSONPath=".metadata.creationTimestamp",name="Age",type=date
ditto.

2021-10-22 20:53 UTC, pchaigno commented on pkg/k8s/apis/cilium.io/client/crds/v2alpha1/ciliumegressnatpolicies.yaml
> -    - description: The age of the identity
This field is unspecified in most (all?) our CRDs except for CiliumIdentity. I'm guessing that's because the field is fairly self-explanatory.

2021-10-25 08:11 UTC, jibi commented on bpf/lib/maps.h
> +struct egress_info {
Shouldn't the `egress_key` and `egress_info` structs be defined in `lib/common.h`? (I see we have already a few other definitions for maps' keys and values in there)

2021-10-25 15:08 UTC, jibi approved these changes

2021-10-25 15:10 UTC, nathanjsweet approved these changes

2021-10-26 06:18 UTC, merged