ipvlan: Avoid spammy dmesg info messages
cilium/cilium pull request #17709
Opened 2021-10-26 13:26 UTC by chendotjs

Avoid spamming the kernel log with below messages when creating ipvlan slave:

[Tue Oct 26 14:20:38 2021] cilium: renamed from tmp_svwpi
[Tue Oct 26 14:20:38 2021] cilium: Caught tx_queue_len zero misconfig
[Tue Oct 26 14:20:46 2021] cilium_host: Caught tx_queue_len zero misconfig
[Tue Oct 26 14:32:11 2021] eth0: renamed from tmp6fed1
[Tue Oct 26 14:32:11 2021] eth0: Caught tx_queue_len zero misconfig

@mukeshkwm reported similar issue on veth datapath, which also applies to ipvlan datapath.

Fixes: #17703
Signed-off-by: Chen Yaqi <chendotjs@gmail.com>

2021-10-26 15:01 UTC, pchaigno approved these changes

2021-10-26 15:14 UTC, borkmann approved these changes

2021-10-26 15:17 UTC, joamaki requested changes

2021-10-26 15:17 UTC, joamaki commented on pkg/datapath/connector/ipvlan.go
> +			TxQLen:      1000,
While it probably makes no difference in the ipvlan case, I think the proper fix might be to set it `-1` instead:
https://github.com/vishvananda/netlink/blob/master/link_linux.go#L1370

2021-10-26 15:19 UTC, joamaki commented on pkg/datapath/connector/ipvlan.go
> +			TxQLen:      1000,
@borkmann what's the effect of having tx_queue_length set to a high number for ipvlan or veth? Should we change it to -1 in the veth case as well?

EDIT: Ah, net/pkt_sched.h has the default tx_queue_length set to 1000 and that's also used at least for veth, so makes no practical difference currently if it's 1000 or -1 here.

2021-10-26 15:23 UTC, joamaki approved these changes
Approving, but consider using `-1` as the constant instead of `1000` so it'll pick whatever is the kernel default.

2021-10-26 15:23 UTC, borkmann commented on pkg/datapath/connector/ipvlan.go
> +			TxQLen:      1000,
We were basically hitting this one:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/sched/sch_api.c#n1237

2021-10-26 15:25 UTC, borkmann commented on pkg/datapath/connector/ipvlan.go
> +			TxQLen:      1000,
I think the underlying issue is on kernel side to some extend in that for veth devs we don't intent to add a "real" qdisc, but rather clsact one. I'd think this spam message should be guarded behind != TC_H_INGRESS, e.g. when someone tries to attach htb and such. tx_queue_length is never used in case of clsact.

2021-11-03 16:46 UTC, pchaigno commented
/test

2021-11-05 08:40 UTC, pchaigno commented
/test-gke

2021-11-05 11:17 UTC, pchaigno commented
Reviews are in. k8s-1.16-kernel-netnext hit known flake https://github.com/cilium/cilium/issues/17661. Marking ready to merge and merging.

2021-11-05 11:18 UTC, merged