docs: Docker version requirement for external workloads
cilium/cilium pull request #17726
Opened 2021-10-28 09:04 UTC by wazir-ahmed

Related to https://github.com/cilium/cilium-cli/pull/572
    
Signed-off-by: Wazir Ahmed <wazir@accuknox.com>

2021-10-28 09:55 UTC, qmonnet requested changes

2021-10-28 09:55 UTC, qmonnet commented on Documentation/gettingstarted/external-workloads.rst
> +  installed in the system.
“Recent” is relative to the time we write the doc, not to when users read it, and even if I know it's used elsewhere in the doc I'd rather avoid it. How about:

```suggestion
* External workloads must have Docker 20.10 or newer
  installed on the system.
```

Could you also please extend this note to explain why this version is needed? It may be helpful to understand what feature is required from Docker for the use case. Just what you mention in https://github.com/cilium/cilium-cli/pull/572#issuecomment-951627991 is enough.

2021-10-28 09:59 UTC, qmonnet commented on Documentation/gettingstarted/external-workloads.rst
> +  installed in the system.
Also could you please move the note just below the requirement on the kernel version? It's a software dependency and not a configuration requirement, so there's not point for users going through the other items to make sure their cluster is correctly configured if they don't have a Docker recent enough available.

2021-10-28 10:39 UTC, wazir-ahmed commented on Documentation/gettingstarted/external-workloads.rst
> +  installed in the system.
Can I added the explanation under [Install and configure Cilium on external workloads](https://docs.cilium.io/en/latest/gettingstarted/external-workloads/#install-and-configure-cilium-on-external-workloads) as a `Note` so that it will be relevant?

2021-11-01 16:11 UTC, qmonnet commented on Documentation/gettingstarted/external-workloads.rst
> +  installed in the system.
[Apologies for the delay] I suppose you could, but I think I'd rather have the all the prerequisites (and related notes) at the same time, so we don't skip some part if we remove this constraint in the future.

I was thinking just something like:
```rst
* External workloads must have Docker 20.10 or newer
  installed on the system (this is the first version to
  support v1.41 of the Docker Engine API, which
  introduces the required ``--cgroupns`` option).
```

2021-11-01 18:10 UTC, wazir-ahmed commented on Documentation/gettingstarted/external-workloads.rst
> +  installed in the system.
I'm not sure whether we need to mention Docker Engine API version. What we care about is just  the `--cgroupns` option. How about the following? 
```
* External workloads must have Docker 20.10 or newer
  installed on the system (a version which supports
   ``--cgroupns`` CLI option).
```

2021-11-02 11:28 UTC, qmonnet commented on Documentation/gettingstarted/external-workloads.rst
> +  installed in the system.
Looks perfect, let's go for it!

2021-11-02 15:54 UTC, wazir-ahmed commented on Documentation/gettingstarted/external-workloads.rst
> +  installed in the system.
cc112b6 - Changed the text. Moved it below the kernel version requirement.

2021-11-02 15:57 UTC, aditighag approved these changes
Thanks!

2021-11-02 15:58 UTC, qmonnet approved these changes

2021-11-04 19:37 UTC, merged