Allowed to set labels to ServiceMonitors - Backport PR#17509
cilium/cilium pull request #17746
Opened 2021-11-01 09:15 UTC by canhnt

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

This PR allows Cilium Helm chart to add custom labels to ServiceMonitors: cilium-agent, cilium-operator, hubble.

This is the backport of #17509

```release-note

```

2021-11-01 09:26 UTC, gandro commented
Thanks for the backport! Reviewers, please see the following comment for some context: https://github.com/cilium/cilium/pull/17509#issuecomment-945455336

2021-11-01 09:27 UTC, gandro approved these changes

2021-11-04 21:03 UTC, nathanjsweet commented
/test-backport-1.10

2021-11-05 09:08 UTC, pchaigno requested changes
The commit description should reference the master commit. See other backported commits on branch v1.10 for examples on the format.

In general, I'd recommend using our backporting scripts as they configure all that automatically: https://docs.cilium.io/en/latest/contributing/release/backports/#creating-the-backports-branch.

2021-11-05 12:24 UTC, canhnt commented
> The commit description should reference the master commit. See other backported commits on branch v1.10 for examples on the format.
> 
> In general, I'd recommend using our backporting scripts as they configure all that automatically: https://docs.cilium.io/en/latest/contributing/release/backports/#creating-the-backports-branch.

@pchaigno : May I just update commit description following the backport template? Using backport script requires `needs-backport/1.0` label for #17509  and `backport-pending/1.10` for this PR, that I cannot add labels myself.

2021-11-05 12:33 UTC, kaworu commented
I've updated this PR title, description, and added the `backport-pending/1.10` label to https://github.com/cilium/cilium/pull/17509. @canhnt please set the commit message to:
```
Allowed to set labels to ServiceMonitors

[ upstream commit fe5628875b730a58886f41c3f4919849649151c2 ]

Signed-off-by: Canh Ngo <canhnt@gmail.com>
```

2021-11-05 12:38 UTC, canhnt commented
> I've updated this PR title, description, and added the `backport-pending/1.10` label to #17509. @canhnt please set the commit message to:
> 
> ```
> Allowed to set labels to ServiceMonitors
> 
> [ upstream commit fe5628875b730a58886f41c3f4919849649151c2 ]
> 
> Signed-off-by: Canh Ngo <canhnt@gmail.com>
> ```
> 
> and then re-request a review from @pchaigno.

@kaworu : Is commit id `fe5628875b730a58886f41c3f4919849649151c2` correct? That is https://github.com/cilium/cilium/commit/fe5628875b730a58886f41c3f4919849649151c2

It seems the `105e1ab10b560957e1d550ece789ef77ea990c15` refers to the commit in the #17746: https://github.com/cilium/cilium/commit/105e1ab10b560957e1d550ece789ef77ea990c15

2021-11-05 12:39 UTC, kaworu commented
@canhnt yes 105e1ab10b560957e1d550ece789ef77ea990c15 is the correct one, sorry for my confusion!

2021-11-05 12:39 UTC, canhnt commented
> @canhnt yes [105e1ab](https://github.com/cilium/cilium/commit/105e1ab10b560957e1d550ece789ef77ea990c15) is the correct one, sorry for my confusion!

Thank you. I updated commit message as suggested.

2021-11-05 12:40 UTC, kaworu approved these changes

2021-11-05 13:41 UTC, pchaigno approved these changes
Thanks @kaworu and @canhnt!

2021-11-05 14:44 UTC, kaworu commented
/test-backport-1.10

2021-11-05 16:31 UTC, pchaigno commented
This change is not covered by end-to-end tests and reviews are in. Marking ready to merge and merging.

2021-11-05 16:32 UTC, merged