Change all IP address that are using Oranges IP range to RFC1918 address space
cilium/cilium pull request #17741
Opened 2021-10-29 06:31 UTC by duttaANI

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #17701

2021-11-01 11:25 UTC, pchaigno commented
@duttaANI I'm happy to trigger the end-to-end tests but could you first rebase on master and sign off your commit?

2021-11-04 10:00 UTC, brb commented on daemon/cmd/policy_test.go
>  					"1.1.1.1/32",
Should we also then change the CF addrs? Those addrs are used as dummy, i.e. no actual traffic is sent, so I don't see a big problem with both.

2021-11-22 09:06 UTC, pchaigno requested changes
Please fix the commit history and we'll run the end-to-end tests. This branch's commit history currently has several merge commits which shouldn't be here and a commit authored by someone else who seems to have been picked up by mistake. The changes in this pull request should be split up into commits with changes that belong together (in some cases, that may be a single commit).

2021-11-26 18:02 UTC, duttaANI commented
> Please fix the commit history and we'll run the end-to-end tests. This branch's commit history currently has several merge commits which shouldn't be here and a commit authored by someone else who seems to have been picked up by mistake. The changes in this pull request should be split up into commits with changes that belong together (in some cases, that may be a single commit).

I have created a new draft PR [here](https://github.com/cilium/cilium/pull/18029) which contains only single commit by me .

2021-11-29 11:53 UTC, pchaigno commented
/test

2021-11-29 14:43 UTC, pchaigno commented
/test-gke

2021-11-29 14:44 UTC, pchaigno commented
/test-1.22-4.19

2021-11-29 22:19 UTC, pchaigno approved these changes

2021-11-30 08:42 UTC, rolinh approved these changes

2021-11-30 13:19 UTC, qmonnet commented
/test-1.22-4.19

2021-11-30 13:21 UTC, qmonnet approved these changes

2021-12-03 09:33 UTC, jrajahalme approved these changes

2021-12-03 09:39 UTC, pchaigno commented
I think we can merge this without waiting for all reviews. The failing k8s-1.22-kernel-4.19 test is known flake https://github.com/cilium/cilium/issues/18014. We have already received four reviews and the changes are fairly trivial. Marking ready to merge.

2021-12-03 10:28 UTC, nebril approved these changes

2021-12-03 13:26 UTC, ldelossa approved these changes

2021-12-06 01:59 UTC, merged