k8s/watchers: Add missing v1 EndpointSlice group on init
cilium/cilium pull request #17778
Opened 2021-11-04 00:18 UTC by christarazi

The K8sWatcher's InitK8sSubsystem() calls resourceGroups() which returns
a list of resources that should be waited on via WaitForCacheSync(). The
v1 version of EndpointSlice was missing from this list. This commit adds
it.

Signed-off-by: Chris Tarazi <chris@isovalent.com>

2021-11-04 00:55 UTC, joestringer approved these changes
nice catch, looks like this was introduced by one of my refactoring PRs during v1.11 development cycle. v1.10 looks fine in this regard.

Curious also how you noticed this, since CI doesn't appear to catch this condition? (at least not in a reliable way; for all I know this was causing a flake but I don't know).

2021-11-04 01:47 UTC, aanm requested changes

2021-11-04 01:47 UTC, aanm commented on pkg/k8s/watchers/watcher.go
> +	}
this needs to be made into an else statement. The agent does not listen for both versions at the same time, it's either one or the other but not both.

2021-11-04 18:59 UTC, nathanjsweet approved these changes
good on :green_apple:

2021-11-04 19:41 UTC, christarazi commented on pkg/k8s/watchers/watcher.go
> +	}
I'll convert it into an else-if because we still need to do the check

2021-11-04 19:44 UTC, christarazi commented
@joestringer My guess for why we don't see it in CI is because we probably don't disable the original `Endpoints` resource, so even if the `v1.EndpointSlice` group is missing from the wait, then we still have to wait on the former. I imagine that if Cilium ran in a cluster with the former completely disabled, then we would have seen some flakes at the startup.

I found it through regular code inspection while working on https://github.com/cilium/cilium/pull/17714.

2021-11-04 19:50 UTC, christarazi commented
/test

2021-11-04 21:47 UTC, aanm approved these changes

2021-11-05 00:14 UTC, christarazi commented
/test

2021-11-05 11:16 UTC, pchaigno commented
Reviews are in. Multicluster has the usual failure and k8s-1.21-kernel-4.19 hit known flake https://github.com/cilium/cilium/issues/13552. Marking ready to merge and merging.

2021-11-05 11:16 UTC, merged