tests: Disable K8s upstream tests that we do not support
cilium/cilium pull request #17828
Opened 2021-11-09 00:24 UTC by nathanjsweet

Tests for internalTrafficPolicy=Local and SCTP that were added
in 1.22 should be disabled as we support neither scenario

Signed-off-by: Nate Sweet <nathanjsweet@pm.me>

Please ensure your pull request adheres to the following guidelines:

Fixes: #17796

2021-11-09 00:40 UTC, aditighag requested changes

2021-11-09 00:40 UTC, aditighag commented on test/kubernetes-test.sh
>  # should enforce ingress policy allowing any port traffic to a server on a specific protocol
Please add - 
"Cilium does not support internalTrafficPolicy as Local Redirect Policy allows user to enable node-local redirection."

2021-11-09 10:46 UTC, pchaigno approved these changes
Pending Aditi's review.

2021-11-09 20:24 UTC, aditighag approved these changes

2021-11-09 20:40 UTC, pchaigno commented
test-upstream-k8s

2021-11-10 15:39 UTC, nbusseneau requested changes

2021-11-10 15:39 UTC, nbusseneau commented on test/kubernetes-test.sh
> +  --test_args="--ginkgo.focus=Net.*ol.* --e2e-verify-service-account=false --host ${KUBE_MASTER_URL} --ginkgo.skip=(should.not.allow.access.by.TCP.when.a.policy.specifies.only.SCTP)|(should.allow.egr
Suggestion:
```suggestion
  --test_args="--ginkgo.focus=Net.*ol.* --e2e-verify-service-account=false --host ${KUBE_MASTER_URL} --ginkgo.skip=(should.not.allow.access.by.TCP.when.a.policy.specifies.only.SCTP)|(should.allow.egress.access.to.server.in.CIDR.block)|(should.enforce.except.clause.while.egress.access.to.server.in.CIDR.block)|(should.ensure.an.IP.overlapping.both.IPBlock.CIDR.and.IPBlock.Except.is.allowed)|(NetworkPolicy.between.server.and.client.using.SCTP)|(should.enforce.ingress.policy.allowing.any.port.traffic.to.a.server.on.a.specific.protocol)|(should.respect.internalTrafficPolicy.Local.Pod.*to.Pod.*.Feature.ServiceInternalTrafficPolicy.)|(should.properly.isolate.pods.that.are.selected.by.a.policy.allowing.SCTP..even.if.the.plugin.doesn.t.support.SCTP..Feature.NetworkPolicy.)"
```
To cover remaining CI failures:
```
should respect internalTrafficPolicy=Local Pod (hostNetwork: true) to Pod [Feature:ServiceInternalTrafficPolicy] 
should respect internalTrafficPolicy=Local Pod (hostNetwork: true) to Pod (hostNetwork: true) [Feature:ServiceInternalTrafficPolicy] 
should respect internalTrafficPolicy=Local Pod to Pod (hostNetwork: true) [Feature:ServiceInternalTrafficPolicy] 
```

2021-11-17 16:41 UTC, nbusseneau commented
/test-upstream-k8s

2021-11-17 23:56 UTC, nbusseneau approved these changes
Upstream test passed. This PR does not need to run any additional CI and reviews are in, marking as ready to merge.

2021-11-18 10:36 UTC, merged