add context when return errors during datapath initialization
cilium/cilium pull request #18011
Opened 2021-11-25 12:22 UTC by kerthcet

Add some context information when return errors for failed device create

Signed-off-by: kerthcet <kerthcet@gmail.com>

Fixes: #17925

2021-11-25 12:22 UTC, kerthcet commented
PTAL @pchaigno

2021-11-25 16:28 UTC, qmonnet requested changes
Hi and thanks for the contribution! Checkpatch [complains](https://github.com/cilium/cilium/runs/4326206298?check_suite_focus=true#step:4:11) about the commit subject being too long, we're trying to keep them under 75 characters for better readability. Would you mind fixing it please? The change looks good to me otherwise.

Side note: this only partially addresses #17925, as the following is not covered in your PR:
> 2. The system requirements documentation should make mention of the veth kernel module.

2021-11-26 18:44 UTC, pchaigno commented
> Side note: this only partially addresses #17925, as the following is not covered in your PR:
> > The system requirements documentation should make mention of the veth kernel module.

I think it's fine to ignore that second item for now. I've created https://github.com/cilium/cilium/issues/18030 to track that and I'm planning to take care of it.

2021-11-26 18:47 UTC, pchaigno reviewed
Thanks for the pull request!

2021-11-26 18:47 UTC, pchaigno commented on pkg/datapath/loader/base.go
> +		return fmt.Errorf("failed to setup device in mode %s during datapath initialization: %w", mode, err)
```suggestion
		return fmt.Errorf("failed to setup base devices in mode %s: %w", mode, err)
```

2021-11-29 05:23 UTC, kerthcet commented on pkg/datapath/loader/base.go
> +		return fmt.Errorf("failed to setup device in mode %s during datapath initialization: %w", mode, err)
done, thanks for your advices.

2021-11-29 05:25 UTC, kerthcet commented
> Hi and thanks for the contribution! Checkpatch [complains](https://github.com/cilium/cilium/runs/4326206298?check_suite_focus=true#step:4:11) about the commit subject being too long, we're trying to keep them under 75 characters for better readability. Would you mind fixing it please? The change looks good to me otherwise.
> 
thanks for your guys' kindly advices. Hoping to contribute to cilium community continuously.

2021-11-29 11:40 UTC, pchaigno approved these changes

2021-11-29 11:59 UTC, qmonnet approved these changes
Looks good, thanks a lot!

2021-11-29 11:59 UTC, qmonnet commented
/test

2021-11-29 16:11 UTC, qmonnet commented
CI failures are flakes, documented as:
- k8s-1.21-kernel-5.4
    - https://github.com/cilium/cilium/issues/17010
- k8s-1.22-kernel-4.19
    - https://github.com/cilium/cilium/issues/18045 (new)
    - https://github.com/cilium/cilium/issues/18014

They all look unrelated to this PR.

We have the reviews from code owners so I'm merging this PR.

2021-11-29 16:11 UTC, merged