bpf mock test : Cleaning warnings in output of `make -C test/bpf/ nat…
cilium/cilium pull request #18015
Opened 2021-11-25 22:18 UTC by cdelzotti

…-test`

Fixes : #17991

Signed-off-by: Clément Delzotti <elk1ns@outlook.fr>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #17991

```release-note
"make -C test/bpf/ nat-test" generated warnings due to improper castings
```

2021-11-26 11:54 UTC, qmonnet commented
Thanks a lot! Note that we're trying to follow the kernel coding style for the C code under `bpf/`. Checkpatch [reported](https://github.com/cilium/cilium/runs/4333556306?check_suite_focus=true#step:4:5) a number of formatting issues with your changed, can you please address them?

2021-11-26 16:09 UTC, cdelzotti commented
Damn, I messed up with my ID in the last commit

2021-11-29 02:39 UTC, christarazi submitted a review, later dismissed
Thanks for the fix. Would you mind squashing the commits into one and fixing up the commit title to be like so:

```
bpf: Clean up warnings from NAT mock tests
```

2021-11-29 08:12 UTC, cdelzotti commented
Okay, I think everything went well this time^^

2021-11-29 22:04 UTC, joestringer commented
Checkpatch is complaining:

```
{[0/1] bpf: Clean up warnings from NAT mock tests}
  Running on ea101a1c85c9db0585205a622cabd4f8d639a9b6
  CHECK:PARENTHESIS_ALIGNMENT: Alignment should match open parenthesis
  #46: FILE: bpf/mock/fake_maps.h:31:
  +int fake_update_elem(hashmap_void_t *map, const void *key, const void *value, __u32 flags,
  +											size_t size)
  
  Warning: WARNING:LONG_LINE: line length of 136 exceeds 100 columns
  #89: FILE: bpf/tests/nat_test.h:133:
  +														SNAT_MAPPING_IPV4_SIZE);
  
  Warning: WARNING:LONG_LINE: line length of 107 exceeds 100 columns
  #104: FILE: bpf/tests/nat_test.h:148:
  +										bpf_compare_ipv4_ct_tuple);
  
  CHECK:PARENTHESIS_ALIGNMENT: Alignment should match open parenthesis
  #104: FILE: bpf/tests/nat_test.h:148:
  +    fake_init_map((hashmap_void_t *)&ipv4_ct_tuple_map, bpf_hash_ipv4_ct_tuple,
  +										bpf_compare_ipv4_ct_tuple);
```

In this code, we use [Linux kernel-style coding conventions](https://www.kernel.org/doc/html/latest/process/coding-style.html), which mainly in this context means using tabs with 8-char spacing, and then aligning parameters to functions with a combination of tabs+spaces such that the first character of the new line matches the indentation of the open bracket for the function.

2021-12-06 06:27 UTC, joamaki approved these changes

2021-12-06 17:24 UTC, joestringer approved these changes
This cleans up the warnings a lot, thanks!

2021-12-06 17:27 UTC, joestringer requested changes
Could you fix up your .git/config to include your full name, then update the author & sign-off to match? I see that in the PR you listed `Clément Delzotti <elk1ns@outlook.fr>` but in the commit message it's using your github name.

This should just be a matter of:
```
git config --global user.name "Clément Delzotti"
git commit --amend --reset-author --signoff
```

2021-12-06 20:36 UTC, cdelzotti commented
I rather like to use my GitHub name instead if that's okay, I modified the PR so it should be homogeneous now

2021-12-06 20:51 UTC, joestringer commented
@cdelzotti Cilium requires contributors to use their real name and certify that they have the right to submit the changes under the license, see the docs section about the [Developer's Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#developer-s-certificate-of-origin).

2021-12-07 07:33 UTC, cdelzotti commented
There you go, I changed it.

2021-12-08 02:45 UTC, joestringer approved these changes
Thanks, LGTM.

2021-12-08 02:46 UTC, joestringer commented
code is only touched by Travis runs, Travis is green. Good to go.

2021-12-08 17:49 UTC, nbusseneau commented
Thanks @cdelzotti! Merging.

2021-12-08 17:49 UTC, merged