workflows: fix build-and-push-with-qemu on v1.11
cilium/cilium pull request #18071
Opened 2021-11-30 18:06 UTC by nbusseneau

We removed the PR bits in `build-and-push-with-qemu` in 5ae34ddc6cb28cfe9a6fae3679462ea63ba0be3a, which means the job should use `${{ github.sha }}` directly.

Fixes: 8bbae9cb4323bf3dd94936e355b0c2aad96d0df8

2021-11-30 18:08 UTC, aanm approved these changes

2021-11-30 18:09 UTC, nebril approved these changes

2021-11-30 18:09 UTC, aanm requested changes
Why don't we add something similar as lines 62-69

2021-11-30 18:11 UTC, nbusseneau commented
> Why don't we add something similar as lines 62-69

The QEMU job only runs on `push` events, hence it is useless to have an intermediate step checking if we are on a `pull_request` or not and then retrieving either the SHA from the PR or the SHA from the GitHub context, thus we use the GitHub context SHA immediately.

2021-12-01 09:39 UTC, pchaigno approved these changes

2021-12-02 22:38 UTC, joestringer approved these changes

2021-12-02 22:40 UTC, merged