test: fix ensureKubectlVersion function
cilium/cilium pull request #18121
Opened 2021-12-04 01:28 UTC by aanm

In RC the minor version returned by `kubectl version --client -o json`
might contain a "+" as seen in [1]. To workaround this issue we can
compare if both versions are the same by simply checking if the
Kubernetes version being tested is a prefix of the Kubernetes version
returned by `kubectl`.

[1]
```
{
  "clientVersion": {
    "major": "1",
    "minor": "20+",
    "gitVersion": "v1.20.0-rc.0",
    "gitCommit": "3321f00ed14e07f774b84d3198ede545c1dee697",
    "gitTreeState": "clean",
    "buildDate": "2020-12-01T10:39:07Z",
    "goVersion": "go1.15.5",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```

Fixes: 75fbebbfbb5d ("test/helpers: use rc.0 as the default version of kubectl")
Signed-off-by: André Martins <andre@cilium.io>

2021-12-04 01:29 UTC, aanm commented
/test

2021-12-06 01:45 UTC, nathanjsweet approved these changes

2021-12-06 11:17 UTC, pchaigno requested changes

2021-12-06 11:17 UTC, pchaigno commented on test/helpers/kubectl.go
> +	if strings.HasPrefix(GetCurrentK8SEnv(), versionstring) {
I think the two arguments are inverted, no? It's going to run `strings.HasPrefix("1.20", "1.20+")` where the second argument is expected to be the prefix.

Also, shouldn't we instead strip the plus sign? Checking the prefix won't work if two versions are ever legitimately the prefix of one another, e.g., 1.200 and 1.20. Sure, it seems unlikely today, but if it's the same, we might as well make the helper function correct for all inputs.

2021-12-06 17:48 UTC, tklauser commented
#18133 was merged in favor of this PR after out-of-band communication with André.

2021-12-06 17:48 UTC, closed without merging