v1.10 backports 2021-12-06
cilium/cilium pull request #18146
Opened 2021-12-06 21:44 UTC by nathanjsweet

* #18031 -- ci: Restart pods when toggling KPR switch (@brb)
 * #18018 -- test/contrib: Bump CoreDNS version to 1.8.3 (@brb)
 * #18048 -- bpf: Add WireGuard to complexity and compile tests (@pchaigno)
 * #18068 -- docs: KUBECONFIG for cilium-cli with k3s (@kkourt)
 * #18006 -- test: Fix incorrect selector for netperf-service (@christarazi)
 * #18104 -- test: Extend coredns clusterrole with additional resource permissions (@aditighag)
 * #18113 -- service: Always allocate higher ID for svc/backend (@brb)
 * #18110 -- docs: fix eksctl ClusterConfig to allow copy (@aanm)
 * #18123 -- docs: fix link to signoff / certificate of origin section (@timoreimann)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 18031 18018 18048 18068 18006 18104 18113 18110 18123; do contrib/backporting/set-labels.py $pr done 1.10; done
```
or with
```
$ make add-label branch=v1.10 issues=18031,18018,18048,18068,18006,18104,18113,18110,18123
```

2021-12-06 22:59 UTC, joestringer commented
/test-backport-1.10

2021-12-06 23:26 UTC, christarazi approved these changes

2021-12-07 09:21 UTC, pchaigno requested changes
One (probably) nit below. I'm not exactly sure how K8sVerifier will react to that newline so it could be breaking.

2021-12-07 09:21 UTC, pchaigno commented on bpf/complexity-tests/netnext/bpf_lxc.txt
> +
Unnecessary newline here.

2021-12-07 17:04 UTC, nathanjsweet commented
/test-backport-1.10

2021-12-07 20:51 UTC, pchaigno approved these changes
Looks good for my PR :pray:

2021-12-07 21:13 UTC, aditighag approved these changes
Backport of my commit looks good. Thanks!

2021-12-08 13:34 UTC, brb approved these changes
My commits LGTM, thanks.

2021-12-09 02:51 UTC, aanm approved these changes

2021-12-09 16:07 UTC, nbusseneau commented
Travis hit an unspecified infra issue with the ARM build, retriggering.

2021-12-09 16:09 UTC, nbusseneau commented
AWS-CNI and EKS workflows failed due to AWS-side infrastructure transient issues, retriggering.

2021-12-09 16:09 UTC, nbusseneau commented
/test-1.16-netnext

2021-12-09 16:11 UTC, nbusseneau commented
It looks like the L4LB workflow might have hit an actual issue, see logs at https://github.com/cilium/cilium/actions/runs/1550474705/attempts/1. I'm retriggering to confirm.

2021-12-09 16:17 UTC, kkourt approved these changes

2021-12-09 17:04 UTC, nbusseneau commented
/ci-l4lb-1.10

2021-12-09 17:04 UTC, nbusseneau commented
/ci-awscni-1.10

2021-12-09 17:04 UTC, nbusseneau commented
/ci-eks-1.10

2021-12-09 23:48 UTC, joestringer commented
I ran the ci-l4lb-1.10 workflow on PR #18210 which has effectively no changes vs. the plain v1.10 branch, and it hit the same failure (#18211). We should investigate this, but given that this backport does not introduce the failure, there is no reason to believe that this is a regression introduced by these changes. 

[EKS run](https://github.com/cilium/cilium/runs/4473736147?check_suite_focus=true) hit https://github.com/cilium/cilium/issues/16938 which is now quarantined on master.

[net-next run](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/2162/testReport/junit/Suite-k8s-1/16/K8sFQDNTest_Validate_that_FQDN_policy_continues_to_work_after_being_updated/) hit an issue with the newly introduced test, investigating.

2021-12-10 00:07 UTC, merged