Fix helm chart annotations for CRDs installed by Cilium
cilium/cilium pull request #18141
Opened 2021-12-06 19:31 UTC by joestringer

- install: Use proper crd names in Chart.yaml annotations
- install: Add EgressNATPolicy to Helm charts
- install: Add CiliumEndpointSlices to Helm charts
- install: Lint for missing CRDs in charts

2021-12-06 20:40 UTC, christarazi approved these changes
Nice, thanks for fixing up.

2021-12-09 13:35 UTC, kaworu requested changes
Thanks! LGTM besides the Cilium Egress NAT Policy documentation.

2021-12-09 13:35 UTC, kaworu commented on install/kubernetes/cilium/Chart.yaml
> +        IP addressing and whether the networking is succesfully operational.
This description document Cilium Endpoint Slice but it should be about Cilium Egress NAT Policy right?

2021-12-16 23:19 UTC, joestringer commented on install/kubernetes/cilium/Chart.yaml
> +        IP addressing and whether the networking is succesfully operational.
Huh, I thought I copied this description from somewhere else in the codebase but it looks new to this PR. Thanks for pointing this out, I've written a new description and fixed this up in the relevant commit.

2021-12-17 08:45 UTC, kaworu approved these changes
Thanks @joestringer LGTM now!

2021-12-20 19:06 UTC, merged