Update aws sdk
cilium/cilium pull request #18220
Opened 2021-12-10 09:41 UTC by ese

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Update  AWS SDK go libraries to support latest EC2 instances types like m6a
 
Fixes: #18197

2021-12-10 11:20 UTC, borkmann commented
/test

2021-12-10 13:54 UTC, tklauser requested changes
@ese How did you update the dependency? It looks like there is an issue with vendoring. Could you please try the following with Go 1.17.x:

```
$ go get github.com/aws/aws-sdk-go-v2@latest
$ go get github.com/aws/aws-sdk-go-v2/config@latest
$ go get github.com/aws/aws-sdk-go-v2/feature/ec2/imds@latest
$ go get github.com/aws/aws-sdk-go-v2/service/ec2@latest
$ go mod tidy && go mod vendor
$ git commit --amend go.mod go.sum vendor/
```

2021-12-10 14:39 UTC, ese commented
Done following your path @tklauser  with `go version go1.17.5 linux/amd64`

Thanks!

2021-12-10 14:50 UTC, tklauser commented
/ci-eks

2021-12-10 14:50 UTC, tklauser approved these changes
LGTM, thanks @ese!

2021-12-13 08:48 UTC, rolinh approved these changes

2021-12-13 08:52 UTC, tklauser commented
/ci-awscni

2021-12-13 09:16 UTC, tklauser commented
Tests passed on AWS-CNI and EKS, marking as ready to merge.

2021-12-13 10:41 UTC, merged