Expose hubble-relay securityContext in Helm
cilium/cilium pull request #18242
Opened 2021-12-11 22:03 UTC by ooraini

Signed-off-by: Omar Aloraini <ooraini.dev@gmail.com>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Hubble relay pod is unprivileged and mounts the `/var/run/cilium` from the host. The container runs with SELinux type `container_t` which can only access files under `/var/run`(label `var_run_t`). This change exposes the security context for the Hubble relay pod, so the user can modify the `seLixnuOptions` and use an appropriate label.

```release-note
New config `hubble.relay.securityContext` in Helm values.
```

2021-12-13 08:24 UTC, koschos approved these changes

2021-12-13 08:33 UTC, rolinh approved these changes

2021-12-13 12:42 UTC, kaworu approved these changes
Thanks for the PR @ooraini, LGTM.

2021-12-13 12:49 UTC, kaworu requested changes
helm-docs workflow complain is legit, `hubble.relay.securityContext` probably moved between the `README.md` update and PR submission:
```
please run 'make -C install/kubernetes docs' and submit your changes
```

2021-12-14 08:13 UTC, kaworu approved these changes

2021-12-24 08:14 UTC, sayboras approved these changes
LGTM and thanks :100: 

Just curious if the similar issue can happen for hubble-ui as well :thinking:, as the security context for hubble-ui is hard coded only for user id. It's unrelated to this PR, I will send a small change to make is consistent.

```
      {{- if .Values.hubble.ui.securityContext.enabled }}
      securityContext:
        runAsUser: 1001
      {{- end }}
```

2022-01-05 19:07 UTC, pchaigno requested changes
Thanks for the pull request!

Could you please include the context from the pull request description into the commit message? We try to keep all necessary context in the git history. We should be good to merge after that.

2022-01-07 09:16 UTC, pchaigno approved these changes
Thanks!

2022-01-07 09:17 UTC, pchaigno commented
It seems Travis is failing with a legitimate error: https://app.travis-ci.com/github/cilium/cilium/jobs/554431715.

2022-01-07 14:17 UTC, qmonnet approved these changes
Looks good, thank you!

(For next time, I would recommend wrapping the commit description on 72-character long lines, so that the description is easier to read in a terminal, and for consistency with the other commits in the history.)

2022-01-07 15:39 UTC, pchaigno commented
Closing/reopening as GitHub checks seemed to be all stuck for some reason :/

2022-01-10 17:05 UTC, pchaigno commented
Smoke tests are passing and this change doesn't have additional coverage in end-to-end tests. Reviews are in. Merging.

2022-01-10 17:05 UTC, merged