Revert "pkg/endpoint: Pass endpoint alive context to regeneration tasks"
cilium/cilium pull request #18253
Opened 2021-12-13 17:28 UTC by aditighag

2021-12-15 17:26 UTC, aditighag commented
Let's merge this one. A proper fix is in the PR - https://github.com/cilium/cilium/pull/18267.

2022-01-04 09:15 UTC, jrajahalme approved these changes

2022-01-05 19:09 UTC, pchaigno requested changes
Could you include the reason for the revert in the commit message? :pray:

2022-01-06 17:56 UTC, aditighag commented
Only updated the commit message.

2022-01-06 18:28 UTC, merged