docs: Warn against Helm's `--reuse-values` in Cilium upgrades
cilium/cilium pull request #18259
Opened 2021-12-14 16:52 UTC by gandro

Using `--reuse-values` to upgrade to a new minor Cilium version is never been supported and may break the Helm template in subtle ways due to the lack of new default values. Adding this in the docs after a user on Slack reported multiple problems by using this flag, as supporting this in the chart is a rather large task and likely requires some automation and testing to ensure it remains supported.

For more details, see also https://github.com/helm/helm/issues/3957#issuecomment-384685681

2021-12-14 17:00 UTC, qmonnet requested changes
Typo in your commit log: `Using it [...] is never been supported`: `is` -> `has`.

2021-12-14 17:00 UTC, qmonnet commented on Documentation/operations/upgrade.rst
> +.. parsed-literal::
```suggestion
.. code-block:: shell-session
```
No literal to parse in this block.

2021-12-14 17:04 UTC, gandro commented on Documentation/operations/upgrade.rst
> +.. parsed-literal::
Fixed, thanks!

2021-12-14 17:28 UTC, qmonnet approved these changes
Thanks!

2021-12-15 15:25 UTC, nbusseneau approved these changes

2021-12-15 16:55 UTC, joestringer approved these changes

2021-12-15 18:44 UTC, merged