Allows to disable helm validation
cilium/cilium pull request #18297
Opened 2021-12-17 12:10 UTC by farodin91

Fixes #16552

Signed-off-by: Jan Jansen <jan.jansen@gdata.de>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

Fixes: #issue-number

```release-note

```

2021-12-17 15:16 UTC, qmonnet requested changes
Thanks! The change looks good overall. It should be noted that it disables the whole Helm validation, when there was just one check that seemed to cause an issue in the original bug report, but I think it's OK.

One thing I would like is to keep a bit more context for the change. Could you please explain why this change is required, and why `helm template` doesn't work in your commit description? It's not fun to go and search for the PRs when `git blaming` a change to find the initial motivation. I'm also wondering whether we should extend the description of the new option to tell users _why_ it might be desirable to disable the checks.

2021-12-17 15:16 UTC, qmonnet commented on install/kubernetes/cilium/values.yaml
> +# -- Allows to disable the helm validation checks
```suggestion
# -- Allows to disable the Helm validation checks
```

2021-12-17 15:16 UTC, qmonnet commented on install/kubernetes/cilium/values.yaml
> +enableHelmValidation: true
Please preserve the line break at the end of the line.

2021-12-20 09:19 UTC, gandro reviewed
Thanks! Please also run `make -C install/kubernetes` to update the Helm Chart README.

2021-12-20 15:47 UTC, gandro commented
While I'm not opposed to be able to opt-out from the validation, I would like to point out that the referenced issue is better solved by specifying the supported api-versions manually rather than disabling validation: https://github.com/cilium/cilium/issues/16552#issuecomment-998037683

2021-12-20 19:30 UTC, christarazi reviewed
Thanks for the PR. 

My opinion on is that it seems like a clunky approach to workaround when installing Helm charts. Ideally, we shouldn't need to provide an opt-out if the solution to the root issue is what @gandro suggested. @farodin91 Has that worked for you or are there more use cases for opting out of Helm validation?

2021-12-21 10:04 UTC, farodin91 commented
@gandro I'm currently playing around with ArgoCD. It seems the issue is solved with Argo CD 2.2. I'm okay with closing this PR. It could be helpful to document how to run helm template correctly.

2021-12-21 10:11 UTC, gandro commented
> @gandro I'm currently playing around with ArgoCD. It seems the issue is solved with Argo CD 2.2. I'm okay with closing this PR. It could be helpful to document how to run helm template correctly.

I see. Looking at https://github.com/argoproj/argo-cd/issues/7291 indeed seems that Argo CD has remaining bugs around `--api-versions` depending on how it is used, which might justify adding this as a workaround for now.

2021-12-21 10:54 UTC, farodin91 commented
> > @gandro I'm currently playing around with ArgoCD. It seems the issue is solved with Argo CD 2.2. I'm okay with closing this PR. It could be helpful to document how to run helm template correctly.
> 
> I see. Looking at [argoproj/argo-cd#7291](https://github.com/argoproj/argo-cd/issues/7291) indeed seems that Argo CD has remaining bugs around `--api-versions` depending on how it is used, which might justify adding this as a workaround for now.

Validation issue of the servicemonitor is solved in argo 2.2. I would add a workaround only, if there another issue. 

I've you want that cilium wants this workaround, i'll update the PR to fix all comments.

2021-12-21 11:16 UTC, gandro commented
> Validation issue of the servicemonitor is solved in argo 2.2. I would add a workaround only, if there another issue.

I'm not aware of any other issues related to validation at the moment. So yes, let's close this then. We can always re-open if we discover another issue.

@farodin91 Thanks a ton for looking into this and doing the work. Even if this will not be merged, your contribution and input was most welcome!

2021-12-21 11:16 UTC, closed without merging