pkg/monitor: consistently use logrus fields
cilium/cilium pull request #1833
Opened 2017-10-24 11:40 UTC by raybejjani

This switches a bunch of log callsites to use logrus.WIthFields. These changes are not supposed to break anything and follow the same reasoning from https://github.com/cilium/cilium/pull/1801 The goal of these changes is to make debugging via logs easier by making our usage more consistent. Ideally, field names should be used the same way throughout the code and mean the same thing.

The most important things to review are whether the field names make sense in the context they're used, and whether we should introduce new ones to pkg/logfields/logfields.go. I'm also happy to incorporate better messages into this PR :)

2017-10-24 14:49 UTC, aalemayhu requested changes
LGTM. If you want to improve the messages that could be a follow-up commit in this PR, but please add SOB. See docs for more information http://docs.cilium.io/en/stable/contributing/#developer-s-certificate-of-origin

2017-10-25 09:24 UTC, raybejjani commented
Added SOB, and I added some longer messages. Most were fine, I think.

2017-10-25 10:03 UTC, scanf commented
@raybejjani still missing, did you forgot to push? Also need to rebase with master.

2017-10-25 10:41 UTC, raybejjani commented
Yup, I did forget. It's pushed now.

2017-10-25 11:47 UTC, aalemayhu approved these changes
LGTM. Thanks for addressing comments.

2017-10-26 05:19 UTC, rlenglet commented on monitor/monitor.go
> +		log.WithField("count.listener", listeners.Len()).Info("New monitor connected.")
Remove the period at the end of the log message. It's not consistent with the other messages.

2017-10-26 07:57 UTC, merged