modify k8s-unmanaged script to only find pods where host networking i…
cilium/cilium pull request #18349
Opened 2022-01-02 22:36 UTC by thejosephstevens

…s false

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible. (no existing test to update, not clear whether it makes sense to add one here)
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

I'm running cilium on AKS where I'm unable to guarantee that system node pools are tainted with the cilium agent unready taint to ensure that cilium starts before other pods are able to come up. I used the k8s-unmanaged script as a way of identifying which pods needed to be restarted, but was surprised to find that it returned many pods that cilium won't manage (including the cilium agents theirselves), so it didn't provide a very useful list of pods as restart targets.

I found that if I excluded pods with host networking enabled, and restarted the remaining pods that were found in the diff, then the two lists converged after that and after those restarts, k8s-unmanaged.sh produced no outputs.

I think this edit makes the script's return value better align with what a user would expect it to return, but if there are any concerns about changing the behavior of the script I would be happy to just add a separate script with this new behavior and updating the docs to point to it.

Fixes: #issue-number

```release-note
Scripts: Update k8s-unmanaged script to only return pods where host networking is false
```

2022-01-03 20:27 UTC, aditighag commented on contrib/k8s/k8s-unmanaged.sh
> +ALL_PODS=$(kubectl get pods --all-namespaces -o json | jq -r '.items[] | select(.spec.hostNetwork==true | not) | .metadata | .namespace + "/" + .name')
Thanks! 🚀 

I would suggest to add a print statement below (L21) along the lines of "skipping host networked pods".

2022-01-03 20:31 UTC, aditighag requested changes
Thanks! 🚀   Could you clean up the PR title (there is an overflow text is in the commit description), maybe - "Skip host networked pods in k8s-unmanaged script"
Suggested a minor enhancement.

2022-01-03 22:53 UTC, thejosephstevens commented
Updated, @aditighag , how's that?

2022-01-03 23:56 UTC, aditighag approved these changes

2022-01-04 00:00 UTC, aditighag commented
The checkpatch script is complaining about long commit message. Can you update the commit message as well?

2022-01-05 19:03 UTC, pchaigno requested changes
Thanks for the pull request! We try to keep all the relevant context in the git history, so could you please update the commit title to `Skip host-networked pods in k8s-unmanaged script` as suggested by Aditi and include the context from the PR description into the commit message. Probably also best to squash the second commit into the first.

(Note you can do all of that from the command line with `git rebase -i upstream/master`, using actions `reword` and `fixup`.)

2022-01-11 22:04 UTC, thejosephstevens commented
Updated. Let me know if there's anything else you need!

2022-01-11 22:07 UTC, aditighag commented
>include the context from the PR description into the commit message. 

We can merge the PR once you update the commit. Thanks!

2022-01-11 22:13 UTC, thejosephstevens commented
I went ahead and popped the whole text description in there, if there's a more specific way you'd like it formatted or if there are examples you could point me to of what this should look like I'm happy to tweak or rework it

2022-01-13 15:16 UTC, pchaigno approved these changes

2022-01-13 21:15 UTC, merged