pkg/proxy: Consistently use logrus fields
cilium/cilium pull request #1835
Opened 2017-10-24 11:41 UTC by raybejjani

This switches a bunch of log callsites to use logrus.WIthFields. These changes are not supposed to break anything and follow the same reasoning from https://github.com/cilium/cilium/pull/1801 The goal of these changes is to make debugging via logs easier by making our usage more consistent. Ideally, field names should be used the same way throughout the code and mean the same thing.

The most important things to review are whether the field names make sense in the context they're used, and whether we should introduce new ones to pkg/logfields/logfields.go. I'm also happy to incorporate better messages into this PR :)

2017-10-25 08:14 UTC, tgraf approved these changes

2017-10-26 07:56 UTC, tgraf requested changes
Needs a rebase

2017-10-26 09:32 UTC, raybejjani commented
ok, @tgraf rebased and I made changes to the kafka files too. Please re-review.

@cilium/proxy Does anyone have any objections to these changes? they are mostly stylistic (but that's usually the most contentious ;) )

2017-10-26 10:20 UTC, tgraf approved these changes

2017-10-26 19:42 UTC, manalibhutiyani approved these changes
Look good to me! Thanks for taking care of Kafka as well.

2017-10-26 19:44 UTC, merged