Api logrus.WithFields fixups
cilium/cilium pull request #1836
Opened 2017-10-24 11:53 UTC by raybejjani

This switches a bunch of log callsites to use logrus.WIthFields. These changes are not supposed to break anything and follow the same reasoning from https://github.com/cilium/cilium/pull/1801 The goal of these changes is to make debugging via logs easier by making our usage more consistent. Ideally, field names should be used the same way throughout the code and mean the same thing.

The most important things to review are whether the field names make sense in the context they're used, and whether we should introduce new ones to pkg/logfields/logfields.go. I'm also happy to incorporate better messages into this PR :)
I'm not sure if the go-logging sublogger I replaced is a breaking change. I tried to retain the "cilium-policy" labelling but I'm not sure what it was for to begin with (I'm hoping it was a human readable thing, and not a strict output formatting issue).

2017-10-24 15:30 UTC, tgraf requested changes

2017-10-24 15:30 UTC, tgraf commented on pkg/policy/api/log.go
> +	// REVIEW: This is the only place we used "cilium-policy" as a logger (with go-logger). It isn't used in the parent pkg/policy :/ Do we need it?
This is a leftover, let's remove it.

2017-10-25 09:36 UTC, raybejjani commented on pkg/policy/api/log.go
> +	// REVIEW: This is the only place we used "cilium-policy" as a logger (with go-logger). It isn't used in the parent pkg/policy :/ Do we need it?
Done. Could you take another look

2017-10-25 09:50 UTC, tgraf approved these changes

2017-10-25 11:42 UTC, merged