docs: Don't rely on `assignee` filter for reviews
cilium/cilium pull request #18676
Opened 2022-01-31 14:34 UTC by pchaigno

The `review-requested:@me` filter lists pull requests that expect a review from you or from any team you belong to. To allow everyone to see only pull requests assigned specifically to them, we had to teach MLH to assign individual reviewers to the pull request and then use `assignee:@me` instead of `review-requested:@me`.

Now that GitHub has a `user-review-requested` filter, we don't need to rely on the assignee filter anymore for reviews. To view pull requests assigned specifically to you (and not just to one of the teams you belong to), you can use `user-review-request:@me`.

There is one small difference in behavior between the two filters. `assignee:@me` would display pull requests you already reviewed but gave a `Request changes` or `Comment` review. Conversely, `user-review-requested:@me` will only display pull requests you haven't reviewed yet or for which the author re-requested a review from you.

2022-01-31 14:42 UTC, qmonnet approved these changes

2022-02-03 02:49 UTC, aanm reviewed
Test - 1

2022-02-03 02:49 UTC, aanm requested changes
Test - 2

2022-02-03 02:50 UTC, aanm reviewed
Test - 3

2022-02-03 02:50 UTC, aanm approved these changes
Final test

2022-02-03 02:50 UTC, merged