reduce GC load
cilium/cilium pull request #18757
Opened 2022-02-09 18:17 UTC by florianl

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

Looping over an array to append something can put high preasure on the garbage collector and cause memory relocations. If the destination is properly allocated in advance, it reduces the work that is needed to be done by GC.

2022-02-09 18:33 UTC, michi-covalent approved these changes

2022-02-10 08:29 UTC, rolinh requested changes

2022-02-10 08:29 UTC, rolinh commented on pkg/kvstore/store/store.go
>  	}
This doesn't do what you want as you'll end up with a slice that is `2*len(s.localKeys)` large with the first half of values being the zero value of `LocalKey` after the `append` loop. What you want to do instead is to preallocate a slice of _capacity_ `len(s.localKeys)`, ie: `keys := make([]LocalKey, 0, len(s.localKeys))`.

2022-02-10 08:29 UTC, rolinh commented on pkg/option/option.go
> +	opts := make([]string, len(o.Opts))
ditto

2022-02-10 08:29 UTC, rolinh commented on pkg/option/option.go
> +	opts := make([]string, len(o.Opts))
ditto

2022-02-10 14:02 UTC, rolinh approved these changes

2022-02-10 14:56 UTC, sayboras reviewed
Thanks, just curious if there is any way to detect similar occurrence in the codebase with linter.

Goland code inspection is showing ~150+ similar but weak occurrences

![image](https://user-images.githubusercontent.com/9019229/153433653-52e76e63-d989-4da4-a0ba-2d3d917ce7a0.png)

2022-02-10 17:42 UTC, aanm approved these changes

2022-02-10 18:39 UTC, florianl commented
> Thanks, just curious if there is any way to detect similar occurrence in the codebase with linter.

Finding such cases with linter rules might be possible. In my case I was looking at a flamegraph produced by a continous profiler and looked into cases where `runtime.growslice` happens often.

2022-02-10 20:34 UTC, sayboras approved these changes

2022-02-16 19:13 UTC, florianl commented
Is there something left I can do?

2022-02-18 09:34 UTC, jibi approved these changes

2022-02-24 08:01 UTC, florianl commented
sorry for the noise. but Is there something left I can do?

2022-02-24 08:26 UTC, rolinh commented
@florianl Nope. All required reviews are in. Let's kick the CI.

2022-02-24 08:26 UTC, rolinh commented
/test

2022-02-24 13:25 UTC, florianl commented
Checked some of the failing tests. The reason of the failure seems to be the same for all. But I don't think this is related to the changes in this PR.

| Failed test | Fail reason|
|-----------|-------------|
| Cilium L4LB XDP  | The action has timed out.  |
| AWS_CNI |The action has timed out.|
| EKS |The action has timed out.|
| GKE |The action has timed out.|
| External workloads |The action has timed out.|
| Multicluster |The action has timed out.|

2022-02-28 10:21 UTC, pchaigno commented
> Checked some of the failing tests. The reason of the failure seems to be the same for all. But I don't think this is related to the changes in this PR.

Yes and no. They timed out waiting for the CI images to be ready. The images are not there because they were built more than 7 days ago and thus have been recycled in the meantime. I've restarted the builds and I'll restart the end-to-end tests once the images are ready.

2022-02-28 10:42 UTC, pchaigno commented
/test

2022-02-28 14:29 UTC, kaworu approved these changes

2022-02-28 14:30 UTC, merged