add website contributing link
cilium/cilium pull request #18940
Opened 2022-02-25 10:44 UTC by xmulligan

Signed-off-by: Bill Mulligan <billmulligan516@gmail.com>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

add a link to the website contributing section

2022-02-26 15:46 UTC, pchaigno approved these changes

2022-02-28 13:30 UTC, kaworu requested changes
Thanks for the PR @xmulligan! Blocking this PR until https://github.com/cilium/cilium.io/pull/11 is merged, but other than that LGTM.

2022-02-28 13:30 UTC, kaworu commented on CONTRIBUTING.md
> +information on how to add blogs, trainings, and other resources
nitpicking:
```suggestion
## To the cilium.io website

Please see the [cilium.io website contributing guide](https://github.com/cilium/cilium.io/blob/main/CONTRIBUTING.md) for detailed
information on how to add blog, trainings, and other resources.
```

2022-03-01 15:53 UTC, kaworu commented
Thanks @xmulligan! Please squash the two commits into one.

2022-03-02 12:57 UTC, pchaigno requested changes
We need a proper title for the commit (i.e., not `squash`). (Alex suggested to squash the commits, but the exact action probably should have been `fixup`.) The previous commit title should be okay.

2022-03-02 13:18 UTC, kaworu approved these changes

2022-03-04 18:01 UTC, aditighag approved these changes

2022-03-07 08:33 UTC, merged