pkg/maps: Fix data races around accessing nat maps
cilium/cilium pull request #18952
Opened 2022-02-26 18:34 UTC by aditighag

Commit c9810bf7b2 introduced garbage collection for orphan entries
in the nat maps that led to concurrent accesses to the map.

The nat maps accessed via ct map construct are susceptible
to data races in asynchronously running goroutines upon
agent restart when endpoints are restored -

```
2022-02-21T02:42:13.757888057Z WARNING: DATA RACE
2022-02-21T02:42:13.757895621Z Write at 0x00c00081a830 by goroutine 360:
2022-02-21T02:42:13.757912783Z   github.com/cilium/cilium/pkg/bpf.(*Map).Close()
2022-02-21T02:42:13.757920669Z       /go/src/github.com/cilium/cilium/pkg/bpf/map_linux.go:581 +0x1c4
2022-02-21T02:42:13.757927597Z   github.com/cilium/cilium/pkg/maps/ctmap.doGC4·dwrap·4()
2022-02-21T02:42:13.757934561Z       /go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:422 +0x39
2022-02-21T02:42:13.757941184Z   github.com/cilium/cilium/pkg/maps/ctmap.doGC4()
2022-02-21T02:42:13.757947352Z       /go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:482 +0x4d5
2022-02-21T02:42:13.757953881Z   github.com/cilium/cilium/pkg/maps/ctmap.doGC()
2022-02-21T02:42:13.757960362Z       /go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:517 +0x17e
2022-02-21T02:42:13.757966185Z   github.com/cilium/cilium/pkg/maps/ctmap.GC()
2022-02-21T02:42:13.757972307Z       /go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:537 +0xc6
2022-02-21T02:42:13.757978599Z   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).garbageCollectConntrack()
2022-02-21T02:42:13.757986321Z       /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:1034 +0x804
2022-02-21T02:42:13.757992160Z   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).scrubIPsInConntrackTableLocked()
2022-02-21T02:42:13.757998853Z       /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:1039 +0x173
2022-02-21T02:42:13.758004601Z   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).scrubIPsInConntrackTable()
2022-02-21T02:42:13.758010701Z       /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:1049 +0x44
2022-02-21T02:42:13.758016604Z   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).runPreCompilationSteps.func1()
2022-02-21T02:42:13.758022804Z       /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:761 +0x132

2022-02-21T02:42:13.758034551Z Previous read at 0x00c00081a830 by goroutine 100:
2022-02-21T02:42:13.758040659Z   github.com/cilium/cilium/pkg/bpf.(*Map).DumpReliablyWithCallback()
2022-02-21T02:42:13.758046461Z       /go/src/github.com/cilium/cilium/pkg/bpf/map_linux.go:756 +0x804
2022-02-21T02:42:13.758053696Z   github.com/cilium/cilium/pkg/maps/nat.(*Map).DumpReliablyWithCallback()
2022-02-21T02:42:13.758059818Z       /go/src/github.com/cilium/cilium/pkg/maps/nat/nat.go:121 +0x7b7
2022-02-21T02:42:13.758065580Z   github.com/cilium/cilium/pkg/maps/ctmap.PurgeOrphanNATEntries()
2022-02-21T02:42:13.758072272Z       /go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:612 +0x790
2022-02-21T02:42:13.758078005Z   github.com/cilium/cilium/pkg/maps/ctmap/gc.runGC()
2022-02-21T02:42:13.758084196Z       /go/src/github.com/cilium/cilium/pkg/maps/ctmap/gc/gc.go:214 +0xb0c
2022-02-21T02:42:13.758090362Z   github.com/cilium/cilium/pkg/maps/ctmap/gc.runGC()
2022-02-21T02:42:13.758096712Z       /go/src/github.com/cilium/cilium/pkg/maps/ctmap/gc/gc.go:189 +0x6a5
2022-02-21T02:42:13.758103134Z   github.com/cilium/cilium/pkg/maps/ctmap/gc.runGC()
2022-02-21T02:42:13.758109338Z       /go/src/github.com/cilium/cilium/pkg/maps/ctmap/gc/gc.go:189 +0x6a5
2022-02-21T02:42:13.758127517Z   github.com/cilium/cilium/pkg/maps/ctmap/gc.Enable.func1()
2022-02-21T02:42:13.758135513Z       /go/src/github.com/cilium/cilium/pkg/maps/ctmap/gc/gc.go:90 +0x40a
2022-02-21T02:42:13.758141621Z   github.com/cilium/cilium/pkg/maps/ctmap/gc.runGC()
2022-02-21T02:42:13.758147715Z       /go/src/github.com/cilium/cilium/pkg/maps/ctmap/gc/gc.go:189 +0x6a5
2022-02-21T02:42:13.758153712Z   github.com/cilium/cilium/pkg/maps/ctmap/gc.Enable.func1()
2022-02-21T02:42:13.758160127Z       /go/src/github.com/cilium/cilium/pkg/maps/ctmap/gc/gc.go:90 +0x40a

```

Fixes: c9810bf7b2 ("ctmap: GC orphan SNAT entries")
Fixes: https://github.com/cilium/cilium/issues/18910

Signed-off-by: Aditi Ghag <aditi@cilium.io>

2022-02-26 18:34 UTC, aditighag commented
/test

2022-02-27 00:27 UTC, aditighag commented
/test

2022-02-27 01:16 UTC, aditighag commented
/test

2022-02-27 01:35 UTC, aditighag commented
/test

2022-02-27 02:09 UTC, aditighag commented
/test

2022-02-28 04:41 UTC, YutaroHayakawa commented on pkg/maps/ctmap/ctmap.go
>  	if natMap == nil {
Need unlocking in here?

2022-02-28 04:45 UTC, YutaroHayakawa requested changes
Almost seems good. Found one missing unlocking.

2022-02-28 04:45 UTC, YutaroHayakawa commented on pkg/maps/ctmap/ctmap.go
>  	if natMap == nil {
Need unlocking in here or simply defer?

2022-02-28 05:10 UTC, aditighag commented on pkg/maps/ctmap/ctmap.go
>  	if natMap == nil {
It's unlocked at L629 below.

2022-02-28 05:17 UTC, aditighag commented
Simply moved the unlocking to a defer statement so no need to re-run the entire suite.

<img width="837" alt="Screen Shot 2022-02-27 at 9 16 43 PM" src="https://user-images.githubusercontent.com/20311845/155928077-2065f833-ed9d-4305-bf3f-f04a49c3ca8c.png">

2022-02-28 05:38 UTC, YutaroHayakawa commented on pkg/maps/ctmap/ctmap.go
>  	if natMap == nil {
Now it's resolved.

2022-02-28 07:53 UTC, YutaroHayakawa approved these changes

2022-02-28 10:16 UTC, pchaigno commented
/test

2022-02-28 10:16 UTC, pchaigno commented
/test-race

2022-02-28 15:31 UTC, aditighag commented
TIL : /test-race Thanks, Paul!

Travis has a successful run.
Sole failure in `test-net-next-race` is - https://github.com/cilium/cilium/issues/17604. I also double checked that there is no occurrence of "DATA RACE" in the sysdump. All other `test-*-race` jobs passed. Marking it as ready for merge.

2022-02-28 16:18 UTC, pchaigno commented
The one failure for Travis CI was fixed by https://github.com/cilium/cilium/pull/18953 which this pull request doesn't include. I think it's safe to ignore.

2022-02-28 18:40 UTC, aditighag commented
/test

2022-02-28 18:40 UTC, aditighag commented
/test-race

2022-02-28 19:38 UTC, aditighag commented
/test-race

2022-02-28 19:46 UTC, aditighag commented
@YutaroHayakawa I've refactored the changes a bit so that we store only the corresponding lock for a global nat lock. This avoids retrieving the lock corresponding to a map type at the consumer site where we serialize accesses to the map. PTAL.

2022-03-02 05:15 UTC, YutaroHayakawa approved these changes
LGTM 👍

2022-03-02 08:05 UTC, merged