clustermesh: Correct shared service annotation behaviour
cilium/cilium pull request #19042
Opened 2022-03-04 13:53 UTC by sayboras

### Description

The changes in previous PR #18766 was assumed shared service annotation
is for local cluster, rather than for remote cluster.

This commit is to perform the adjustment, the behavior will be as per below

clustermesh: Correct shared service annotation behaviour

The changes in previous PR #18766 was assumed shared service annotation
is for local cluster, rather than for remote cluster.

This commit is to perform the adjustment, the behavior will be as per below

| | global: true && shared: true  | global: true && shared: false |
| - | - | - |
|cluster 1 endpoints from: | local and remote | remote only |
|cluster 2 endpoints from: | local and remote | remote only |

Relates #18766

Signed-off-by: Tam Mach <tam.mach@isovalent.com>

_Thanks to Duffie for the above summary table, also to Ray for pointing out my confusion_

### Testing

Testing was done locally with 2 kind clusters with sample services mentioned
in [docs](https://docs.cilium.io/en/latest/gettingstarted/clustermesh/services/#load-balancing-with-global-services)

<details>
<summary>After provision global service</summary>

```
$ kg services rebel-base --context kind-kind-1
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
rebel-base   ClusterIP   10.96.196.167   <none>        80/TCP    118s

$ ksysex --context kind-kind-1 ds/cilium -- cilium bpf lb list                     
Defaulted container "cilium-agent" out of: cilium-agent, ebpf-mount (init), clean-cilium-state (init)
SERVICE ADDRESS     BACKEND ADDRESS
...      
10.96.196.167:80    10.244.1.38:80 (7)                        
                    10.244.1.69:80 (7)                        
                    10.244.1.147:80 (7)                       
                    10.244.1.44:80 (7)                        
                    0.0.0.0:0 (7) [ClusterIP, non-routable]  

$ kg services rebel-base --context kind-kind-2
NAME         TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
rebel-base   ClusterIP   10.96.228.46   <none>        80/TCP    2m52s

$  ksysex --context kind-kind-2 ds/cilium -- cilium bpf lb list        
Defaulted container "cilium-agent" out of: cilium-agent, ebpf-mount (init), clean-cilium-state (init)
SERVICE ADDRESS      BACKEND ADDRESS
10.96.0.1:443        172.18.0.7:6443 (3)                       
                     0.0.0.0:0 (3) [ClusterIP, non-routable]   
10.96.228.46:80      0.0.0.0:0 (7) [ClusterIP, non-routable]   
                     10.244.1.38:80 (7)                        
                     10.244.1.147:80 (7)                       
                     10.244.1.69:80 (7)                        
                     10.244.1.44:80 (7) 

$ cat temp_check.sh      
#!/usr/bin/env bash

echo 'Checking in cluster 1'
for i in $(seq 1 10); do kubectl exec -ti --context kind-kind-1 deployment/x-wing -- curl rebel-base; done

echo 'Checking in cluster 2'
for i in $(seq 1 10); do kubectl exec -ti --context kind-kind-2 deployment/x-wing -- curl rebel-base; done

$ ./temp_check.sh                                                                          
Checking in cluster 1
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
Checking in cluster 2
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}

```

</details>

<details>
<summary>Add `io.cilium/shared-service: false` annotation for service in cluster 1</summary>

```
$ k annotate service rebel-base io.cilium/shared-service="false" --context kind-kind-1 --overwrite
service/rebel-base annotated

$ ./temp_check.sh
Checking in cluster 1
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
Checking in cluster 2
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}

```

</details>

<details>
<summary>Add `io.cilium/shared-service: false` annotation for service in cluster 2</summary>

```
$ k annotate service rebel-base io.cilium/shared-service="false" --context kind-kind-2 --overwrite
service/rebel-base annotated

$ ./temp_check.sh                                                                                 
Checking in cluster 1
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
Checking in cluster 2
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}

```

</details>

<details>
<summary>Revert io.cilium/shared-service back to 'true' for 2 cluster one by one</summary>

```
$ k annotate service rebel-base io.cilium/shared-service="true" --context kind-kind-2 --overwrite
service/rebel-base annotated

$ ./temp_check.sh                                                                             
Checking in cluster 1
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
Checking in cluster 2
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
 [...]

2022-03-04 14:01 UTC, sayboras commented on pkg/k8s/service_cache.go
> -	if svcFound && svc.IncludeExternal && svc.Shared {
this is to revert back the changes in previous PR, the svc struct here is local service only.

2022-03-04 14:03 UTC, sayboras commented on pkg/k8s/service_cache.go
> +		delete(externalEndpoints.endpoints, service.Cluster)
we don't need to check if the current cluster is remote or local, as externalEndpoints should not have any local cluster endpoint anyway.

2022-03-04 14:04 UTC, sayboras commented on pkg/k8s/service_cache.go
> +	if ok && serviceReady {
remove check for shared here, as svc object here is local service, we want to publish event in case shared flag is toggled.

2022-03-15 20:54 UTC, christarazi approved these changes

2022-03-21 12:27 UTC, sayboras commented
/test

2022-03-21 21:50 UTC, sayboras commented
/test-1.22-4.19

2022-03-22 15:46 UTC, aanm requested changes

2022-03-22 15:46 UTC, aanm commented on pkg/k8s/service_cache.go
> +		delete(externalEndpoints.endpoints, service.Cluster)
please add a comment in the code stating this as well

2022-03-22 15:49 UTC, aanm commented
/test

2022-03-28 10:09 UTC, brb approved these changes

2022-03-28 12:28 UTC, qmonnet approved these changes

2022-03-29 00:10 UTC, sayboras commented
/ci-external-workloads

2022-03-29 00:41 UTC, sayboras commented
The failure for external-workloads seems related to this change, sysdump shows that kube-dns service is ready, I am checking further now.

2022-03-29 12:14 UTC, sayboras commented
/test

2022-03-29 22:49 UTC, sayboras commented
Force push to fix unit test

<details>

```diff
diff --git a/pkg/k8s/service_cache_test.go b/pkg/k8s/service_cache_test.go
index e06b914a2d..c4547d02f0 100644
--- a/pkg/k8s/service_cache_test.go
+++ b/pkg/k8s/service_cache_test.go
@@ -422,7 +422,8 @@ func (s *K8sSuite) TestServiceMerging(c *check.C) {
 				"port": {Protocol: loadbalancer.TCP, Port: 80},
 			},
 		},
-		Shared: false,
+		IncludeExternal: true,
+		Shared:          false,
 	},
 		swgSvcs,
 	)
@@ -456,7 +457,8 @@ func (s *K8sSuite) TestServiceMerging(c *check.C) {
 				"port": {Protocol: loadbalancer.TCP, Port: 80},
 			},
 		},
-		Shared: true,
+		IncludeExternal: true,
+		Shared:          true,
 	},
 		swgSvcs,
 	)
@@ -496,7 +498,8 @@ func (s *K8sSuite) TestServiceMerging(c *check.C) {
 				"port": {Protocol: loadbalancer.TCP, Port: 80},
 			},
 		},
-		Shared: true,
+		IncludeExternal: true,
+		Shared:          true,
 	},
 		swgSvcs,
 	)
@@ -553,7 +556,8 @@ func (s *K8sSuite) TestServiceMerging(c *check.C) {
 				"port": {Protocol: loadbalancer.TCP, Port: 80},
 			},
 		},
-		Shared: true,
+		IncludeExternal: true,
+		Shared:          true,
 	}
 
 	// Adding another cluster to the first service will trigger an event

```

</details>

2022-03-30 00:12 UTC, sayboras commented
/test

2022-03-30 13:06 UTC, aanm approved these changes

2022-03-30 13:46 UTC, merged

2022-03-30 13:52 UTC, sayboras commented
> to which your PR relates, was backported to 1.11. Given that this PR is marked as a bugfix, should it be backported as well?

Yes, thanks for highlighting this.

> Another note, I see that this is labelled with `requires-doc-change`. Is it still valid, and if so, are you following up on that?

Yes, I just created #19273 for tracking purpose, right now I don't know how to update docs in concise way.