api/v1: remove write-only NodeAddressingElement.AddressType property
cilium/cilium pull request #19044
Opened 2022-03-04 14:29 UTC by tklauser

This field is only ever set but never read (i.e. inside the CNI).
It is fine to make this change because the agent and CNI are always
deployed from the same Cilium version in lockstep, i.e. with matching
API. No other API clients use `NodeAddressingElement` or `NodeAddressing`
information. Because the field is never read, it shouldn't even cause
problems with CNI plugin using an older version of the API.

This also allows to drop `pkg/node.getNodeIP` and fold it into
`pkg/node.GetNodeIP`.

2022-03-04 14:35 UTC, tklauser commented
/test

2022-03-07 15:47 UTC, rolinh requested changes

2022-03-07 15:47 UTC, rolinh commented on api/v1/openapi.yaml
> -        type: string
In [the doc](https://docs.cilium.io/en/latest/api/#compatibility-guarantees), we make the following statement:
> Cilium API is stable as of version 1.0, backward compatibility will be upheld for whole lifecycle of Cilium 1.x.

My understanding is that this change breaks this promise. Could we somehow keep this but make this a no-op and mark deprecated?

2022-03-07 16:12 UTC, tklauser commented on api/v1/openapi.yaml
> -        type: string
Right, good point. I seem to remember we had ro revert other changes like this due to failures to unmarshal older versions of certain definitions.

I guess we should keep the field in the API and just no longer set it (i.e. keep this PR's changes to `pkg/node`, but leave the API untouched).

2022-03-08 10:17 UTC, tklauser commented
/test

2022-03-08 11:04 UTC, tklauser commented
/test-runtime

2022-03-08 12:42 UTC, rolinh approved these changes

2022-03-09 14:40 UTC, tklauser commented
/test

2022-03-10 11:16 UTC, tklauser commented
/test-gke

2022-03-22 10:04 UTC, jibi approved these changes

2022-03-28 10:11 UTC, qmonnet approved these changes

2022-03-28 10:12 UTC, merged