[Docs] Update docs to use enable endpoint route Azure cni
cilium/cilium pull request #19088
Opened 2022-03-08 20:09 UTC by nitishm

Added the `endpointRoute.enabled=true` value to the helm install when
running Azure CNI in chaining mode.

Signed-off-by: Nitish Malhotra <nitishm@microsoft.com>

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note

```

2022-03-08 21:53 UTC, joestringer requested changes
Thanks for figuring this out & submitting the fix. Looks good, though I don't think we necessarily need to include the explanation sentence; even that sentence by itself assumes a lot of knowledge about Cilium internals. Ideally we could just hide implementation details like this from the user, but this seems like the easiest way right now to ensure that future installations get all the right settings configured correctly.

Please also look through the PR description template and fill out / update or remove the release note. Probably the important part for the release note is that this fixes L7 policies with Azure CNI chaining.

2022-03-08 21:53 UTC, joestringer commented on Documentation/gettingstarted/cni-chaining-azure-cni.rst
> +``endpointRoutes.enabled`` enables direct routing to the Azure CNI veth pairs without requiring to route via the ``cilium_host`` interface.
nit: I don't think users will know or necessarily care about this detail - usually we would keep this information either in dedicated developer documentation or just in the commit message.
```suggestion
```

2022-03-09 10:41 UTC, qmonnet commented on Documentation/gettingstarted/cni-chaining-azure-cni.rst
> +     --set endpointRoutes.enabled=true \\
```suggestion
     --set endpointRoutes.enabled=true
```

2022-03-09 18:36 UTC, joestringer approved these changes
Changes LGTM. Please rebase + squash the patches together. It's fine to do this and then force push over the same branch.

2022-03-09 19:02 UTC, nitishm commented
@joestringer I did this with all the merged commits. Is this going to be a problem?

2022-03-09 19:17 UTC, joestringer commented
@nitishm yes, looking over the "Files changed" tab , this PR is now proposing much more modifications than the one-liner that it is intended to modify. I would suggest fetching the latest master branch then doing a `git rebase -i cilium/master` for interactive rebase (assuming `cilium` is the remote for the cilium/cilium repository). Only your own patch should show up in the editor, which you plan to base on top of the latest cilium tree.

2022-03-09 19:26 UTC, nitishm commented
@joestringer PTAL. It shows only one commit and a single file changed now.

2022-03-09 19:55 UTC, joestringer approved these changes

2022-03-10 10:30 UTC, qmonnet approved these changes
Thanks!

2022-03-10 10:36 UTC, sayboras approved these changes
LGTM :100: 

can you help to clean up the commit message as it seems to have combined message from squashed commits ?

2022-03-10 12:49 UTC, aanm approved these changes

2022-03-10 17:42 UTC, nitishm commented
> LGTM 💯
> 
> can you help to clean up the commit message as it seems to have combined message from squashed commits ?

Done

2022-03-10 18:37 UTC, merged

2022-03-10 18:37 UTC, joestringer commented
Merged, thanks!