proxy: pass connection options from agent
cilium/cilium pull request #19138
Opened 2022-03-14 17:50 UTC by jmcshane

This change allows the cilium-agent to specify key connection options to deal with connection reuse issues. The motivation for this change comes from connection issues from cilium-envoy to S3. As seen in this article https://forums.aws.amazon.com/thread.jspa?threadID=110998, S3 will reset a connection that is re-used after 100 requests. Envoy can address this by creating a new connection after that number of requests, but we need to pass that configuration from cilium-agent to cilium-envoy.

Signed-off-by: jmcshane <james.mcshane@superorbital.io>

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

Fixes: #19136

```release-note
Add proxy common http options arguments to agent
```

2022-03-16 07:27 UTC, jrajahalme commented
/test

2022-03-16 07:34 UTC, jrajahalme approved these changes
Looks good, thanks!

2022-03-22 03:00 UTC, sayboras commented
/test

2022-03-22 03:00 UTC, sayboras approved these changes
LGTM 💯

2022-03-22 15:54 UTC, aanm requested changes
Just one small nit. Thank you!

2022-03-22 15:54 UTC, aanm commented on pkg/option/config.go
> +	ProxyMaxConnectionDuration = "proxy-max-connection-duration"
`proxy-max-connection-duration` -> `proxy-max-connection-duration-seconds`

2022-03-23 15:51 UTC, jmcshane commented
> Just one small nit. Thank you!

updated, thanks!

2022-03-23 17:31 UTC, aanm approved these changes

2022-03-23 17:31 UTC, aanm commented
/test

2022-03-24 07:08 UTC, sayboras commented
/test

2022-03-24 11:29 UTC, JAORMX approved these changes

2022-03-28 21:11 UTC, joestringer commented
The checks seem to have had some trouble with images, could you please rebase against master & force-push to update the PR? We can trigger the tests again after that.

2022-03-29 12:54 UTC, jmcshane commented
@joestringer rebased

2022-03-29 13:39 UTC, sayboras commented
/test

2022-03-29 17:57 UTC, jmcshane commented
@sayboras looks like were close here, just some small issues. i rebased again one more time

2022-03-29 21:54 UTC, sayboras commented
/test

2022-03-30 05:04 UTC, sayboras commented
/test

2022-03-30 12:44 UTC, jmcshane commented
@sayboras is there a way to just re-run a single test? That k8s-1.23-kernet test has been a bit flaky it seems

2022-03-30 13:00 UTC, sayboras commented
/test-1.23-net-next

2022-03-30 13:09 UTC, sayboras commented
> is there a way to just re-run a single test? That k8s-1.23-kernet test has been a bit flaky it seems

There might be a command to focus on specific test only, but I misread your message and trigger re-run instead.

2022-03-30 15:30 UTC, ldelossa approved these changes
LGTM :+1:

2022-03-30 20:28 UTC, jmcshane commented
@sayboras would you have a minute to look at this failure with me? I could grab you on the cilium slack sometime. trying to see if there's something wrong with the PR here or if i should just keep asking you to poke the tests

2022-03-31 23:28 UTC, sayboras commented
> would you have a minute to look at this failure with me? I could grab you on the cilium slack sometime. trying to see if there's something wrong with the PR here or if i should just keep asking you to poke the tests

Sorry for late reply, sure, feel free to ping me in cilium slack.

2022-03-31 23:29 UTC, sayboras commented
/test-1.23-net-next

2022-04-01 03:13 UTC, sayboras commented
/test-1.23-net-next

2022-04-01 07:38 UTC, sayboras commented
/test

2022-04-01 14:45 UTC, merged