add enable-unsafe-external-ips
cilium/cilium pull request #19139
Opened 2022-03-14 22:52 UTC by Vilsol

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Adds unsafe external IP support.

Refers to [#14136](https://github.com/cilium/cilium/issues/14136)

2022-05-02 09:07 UTC, brb requested changes

2022-05-02 09:07 UTC, brb commented on pkg/option/config.go
> +	EnableUnsafeExternalIPs = "enable-unsafe-external-ips"
We've started prefixing the LB related options with `bpf-lb` (e.g., `--bpf-lb-algorithm`), so I suggest to do the same with this option. Maybe `--bpf-lb-unsafe-external-ips`?

2022-05-02 09:07 UTC, brb commented on pkg/datapath/linux/config/config.go
> +		if option.Config.EnableUnsafeExternalIPs {
I think this could be moved inside the if-statement above.

2022-05-02 09:07 UTC, brb commented on daemon/cmd/daemon_main.go
> +	flags.Bool(option.EnableUnsafeExternalIPs, defaults.EnableUnsafeExternalIPs, fmt.Sprintf("Enable externalIPs from pods on same host feature (requires enabling %s)", option.EnableExternalIPs))
Maybe `Enable externalIPs service access from inside host for externalIPs which are non-host IPs (requires ...)`?

2022-05-02 09:07 UTC, brb commented on bpf/bpf_sock.c
>  	if (lb4_svc_is_external_ip(svc) ||
Instead of these changes, couldn't we just protect the `if(lb4_svc_is_external_ip(svc)` with `#ifdef ENABLE_UNSAFE_EXTERNAL_IPS`?

2022-06-02 10:08 UTC, brb commented
@Vilsol Are you planning to revive the PR, or shall we close it?

2022-06-02 13:24 UTC, Vilsol commented
@brb I will revive this PR. Sorry for taking this long, just haven't had time to work on it recently, sorry.

2022-07-06 11:32 UTC, aanm commented
@Vilsol I've the PR in draft mode. Feel free to mark it back as ready once you have addressed all comments. Thank you!

2022-11-14 10:43 UTC, ti-mo commented
Helping out @github-actions here. Feel free to re-open.

2022-11-14 10:43 UTC, closed without merging