bpf: Add missing packet trace in handle_nat_fwd
cilium/cilium pull request #19158
Opened 2022-03-16 09:42 UTC by YutaroHayakawa

Please see the commit message for more details.

Fixes: #18909

```release-note
Add missing packet trace for some non-NodePort SNAT egress
```

2022-03-16 09:43 UTC, YutaroHayakawa commented
/test

2022-04-12 21:57 UTC, qmonnet requested changes

2022-04-12 21:57 UTC, qmonnet commented on bpf/lib/nodeport.h
> +	send_trace_notify(ctx, obs_point, 0, 0, 0, 0, 0, 0);
`0` for the 7th argument means `TRACE_REASON_POLICY` (a.k.a `CT_NEW`). It would be great if we had a valid reason to pass, but I'm not sure we know the status (“request” or “reply”) for the packet at this point; otherwise, please use `TRACE_REASON_UNKNOWN`.

2022-04-12 21:57 UTC, qmonnet commented on bpf/lib/nodeport.h
> +	send_trace_notify(ctx, obs_point, 0, 0, 0, 0, 0, 0);
Same comment, please use `TRACE_REASON_UNKNOWN` for the `reason` if we have no better alternative.

2022-04-25 10:27 UTC, qmonnet approved these changes
Thanks!

2022-04-28 08:24 UTC, joamaki approved these changes

2022-04-29 14:06 UTC, brb commented
/test

2022-05-06 08:42 UTC, YutaroHayakawa commented
All failing tests are hitting known flakes. Making this ready-to-merge.

ConformanceAKS: https://github.com/cilium/cilium/issues/19472
gke-stable: Hitting https://github.com/cilium/cilium/issues/19689
k8s-1.23-kernel-net-next: Hitting https://github.com/cilium/cilium/issues/17628

2022-05-06 11:49 UTC, merged