Change cilium-cleanup order
cilium/cilium pull request #19163
Opened 2022-03-16 18:07 UTC by jtaleric

Kill the hubble port forward before issuing the `cilium uninstall`

Signed-off-by: Joe Talerico <rook@isovalent.com>

2022-03-16 18:12 UTC, pchaigno approved these changes

2022-03-16 18:23 UTC, christarazi approved these changes

2022-03-16 18:24 UTC, pchaigno requested changes
Hm, actually, sorry but the commit description doesn't state *why?* I know why from our discussion, but 6 months older me won't :sweat_smile:

2022-03-16 18:36 UTC, jtaleric commented
> Hm, actually, sorry but the commit description doesn't state _why?_ I know why from our discussion, but 6 months older me won't sweat_smile

👍🏽 added to my commit message.

2022-03-16 18:39 UTC, pchaigno approved these changes
Thanks!

2022-03-16 22:43 UTC, joestringer approved these changes

2022-03-16 22:46 UTC, joestringer commented
Can someone from @cilium/ci-structure comment on whether or how we need to test these changes before merging, or add the ready-to-merge label if you're happy with it?

2022-03-16 23:23 UTC, sayboras approved these changes
:shipit:

2022-03-17 00:52 UTC, nbusseneau commented
> Can someone from @cilium/ci-structure comment on whether or how we need to test these changes before merging, or add the ready-to-merge label if you're happy with it?

Following the instructions for testing changes, documented near the top of the workflows: https://github.com/cilium/cilium/blob/1b03f0b4c9dd9f7d7b5886ca563b2c21a4e2745b/.github/workflows/conformance-aks.yaml#L11-L24

However this will require recreating the PR from a branch on the upstream repo, not from a fork 😅

Note this does not apply to the Kind workflow, which already runs on `pull_request` anyway: https://github.com/cilium/cilium/actions/runs/1994489631

I would say the risk here is negligible and it's not worth the trouble. And it passed on Kind 🎉

2022-03-17 00:53 UTC, nbusseneau approved these changes

2022-03-17 01:13 UTC, merged