bpf: fix selection of Nodeport XDP accel for IPv6
cilium/cilium pull request #19534
Opened 2022-04-22 12:29 UTC by julianwiedmann

Fix a s/ENABLE_NODEPORT/ENABLE_NODEPORT_ACCELERATION typo, so that the
XDP-based acceleration for IPv6 Nodeport only gets compiled when selected.
This matches the IPv4 path.

Only makes a difference if the XDP program gets loaded for some other
feature. Right now that would only be XDP-based CIDR filtering.

Fixes: 964c3fb9e609 ("bpf: initial datapath acceleration for nodeport in xdp")
Signed-off-by: Julian Wiedmann <jwi@isovalent.com>

```release-note
Only apply XDP acceleration for IPv6 Nodeport when enabled (with --bpf-lb-acceleration=native).
```

2022-04-22 12:45 UTC, borkmann approved these changes
Thanks a lot Julian! 🚀

2022-04-26 00:15 UTC, ldelossa approved these changes
LGTM

2022-04-26 07:55 UTC, pchaigno requested changes
Isn't this a bug? As in, in the case you describe, we will perform DNAT at the XDP hook even though we shouldn't? If it's a bug, we need a release-note and the `release-note/bug` label.

2022-04-26 18:17 UTC, julianwiedmann commented
> Isn't this a bug? As in, in the case you describe, we will perform DNAT at the XDP hook even though we shouldn't? If it's a bug, we need a release-note and the `release-note/bug` label.

Ack, adjusted accordingly.

2022-04-26 18:33 UTC, pchaigno approved these changes

2022-04-26 18:33 UTC, pchaigno commented
Thanks!

2022-04-26 20:11 UTC, borkmann commented
/test

2022-04-27 06:34 UTC, julianwiedmann commented
/test

2022-04-27 07:36 UTC, julianwiedmann commented
/test-1.23-net-next

2022-04-30 00:36 UTC, YutaroHayakawa approved these changes

2022-05-03 16:40 UTC, pchaigno commented
Reviews are in. Net-next hit known flake https://github.com/cilium/cilium/issues/18873. AKS is (was?) known to be broken. The change is small and shouldn't impact those tests specifically. Marking ready to merge.

2022-05-04 14:32 UTC, merged