operator: Add cilium node garbage collector
cilium/cilium pull request #19576
Opened 2022-04-26 12:20 UTC by sayboras

### Description

TODO

### Testing

Testing was done locally with kind cluster

<details>
<summary>Create one dummy ciliumnode and check gc </summary>

```
$ ksyslo deployment/cilium-operator --timestamps | grep kind-worker-dummy
2022-04-26T10:59:22.106774489Z level=debug msg="UpdatedStatus Node" error="<nil>" node-name=kind-worker-dummy subsys=pod-cidr
2022-04-26T10:59:23.087007602Z level=debug msg="UpdatedStatus Node" error="<nil>" node-name=kind-worker-dummy subsys=pod-cidr
2022-04-26T10:59:51.977272944Z level=info msg="Add CiliumNode to garbage collector candidates" nodeName=kind-worker-dummy subsys=watchers
2022-04-26T11:00:21.978387751Z level=info msg="Perform GC for invalid CiliumNode" nodeName=kind-worker-dummy subsys=watchers

$ kg ciliumnodes
NAME                 AGE
kind-control-plane   156m
kind-worker          156m
```

</details>

2022-04-26 21:33 UTC, christarazi requested changes
Changes look good, just a few minor comments

2022-04-26 21:33 UTC, christarazi commented on install/kubernetes/cilium/templates/cilium-operator/clusterrole.yaml
> +  # To remove node taints or perform underlying CiliumNode garbage collector
```suggestion
  # To remove node taints or perform underlying CiliumNode garbage collection
```

2022-04-26 21:33 UTC, christarazi commented on Documentation/operations/upgrade.rst
> +  can be moved out of deprecated list.
This option used to exist for kvstore GC. Now we are using it to implement K8s GC, so we should point that out.

2022-04-26 21:33 UTC, christarazi commented on operator/flags.go
> +	flags.Duration(operatorOption.NodesGCInterval, 5*time.Minute, "GC interval for nodes store in the kvstore")
We are not doing kvstore GC anymore.

2022-04-26 21:33 UTC, christarazi commented on operator/watchers/cilium_node_gc.go
> +			scopedLog.WithError(err).Error("Unable to fetch cilium node from store")
Nit: there's a mix of usages between "ciilum node" and "CiliumNode". I suggest we stick with the latter everywhere.

2022-04-27 13:35 UTC, sayboras commented on operator/flags.go
> +	flags.Duration(operatorOption.NodesGCInterval, 5*time.Minute, "GC interval for nodes store in the kvstore")
thanks :100:

2022-04-27 16:08 UTC, kaworu requested changes
Seeing that we are selectively adding RBAC permissions and passing the `nodes-gc-interval` flag through the ConfigMap, I'm assuming there is a use-case for disabling this feature. In what context users would want to disable it?

Follow-up question: how are users expected to effectively disable this feature through Helm? I think the combination of the flag being a duration, the default value, and different ways of checking it (`hasKey` in the `ConfigMap`, "emptiness" in the `ClusterRole`) might not work as expected:

```console
% helm template cilium ./install/kubernetes/cilium --namespace kube-system | grep -E "nodes-gc-interval|# To perform CiliumNode garbage collector"
  nodes-gc-interval: "5m0s"
    # To perform CiliumNode garbage collector
% helm template cilium ./install/kubernetes/cilium --namespace kube-system --set operator.nodeGCInterval=1s | grep -E "nodes-gc-interval|# To perform CiliumNode garbage collector"
  nodes-gc-interval: "1s"
    # To perform CiliumNode garbage collector
```

Here the first `grep` expression is for the flag value, second expression for RBAC. Using the default and override will correctly set the flag and add the RBAC permission, happy day™.

```console
% helm template cilium ./install/kubernetes/cilium --namespace kube-system --set operator.nodeGCInterval=null | grep -E "nodes-gc-interval|# To perform CiliumNode garbage collector"
% helm template cilium ./install/kubernetes/cilium --namespace kube-system --set operator.nodeGCInterval= | grep -E "nodes-gc-interval|# To perform CiliumNode garbage collector"
  nodes-gc-interval: ""
% helm template cilium ./install/kubernetes/cilium --namespace kube-system --set operator.nodeGCInterval=0s | grep -E "nodes-gc-interval|# To perform CiliumNode garbage collector"
  nodes-gc-interval: "0s"
    # To perform CiliumNode garbage collector
```

Settting to `null` shows nothing, meaning we don't pass the flag and we don't have the RBAC permission. The issue here is that we'll be using the non-zero CLI default (5m) and will fail because we don't have the permission.

Settting to empty will actually pass it as-is to the flag, which will fail duration parsing.

Settting to `0s` will correctly disable the feature in the ConfigMap, but won't add the RBAC permission.

2022-04-27 16:08 UTC, kaworu commented on operator/watchers/cilium_node_gc.go
> +	nodesInit(k8s.WatcherClient(), stopCh)
Admittedly I'm lacking context about how `nodesInit` uses `stopCh`, but the caller never close it and is seems like a strange pattern to me. Would it make sense to pass `ctx.Done()` here instead?

2022-04-27 17:02 UTC, christarazi approved these changes

2022-04-28 09:41 UTC, sayboras commented
Thanks for your input, indeed there are a few cases I didn't consider.

> Seeing that we are selectively adding RBAC permissions and passing the nodes-gc-interval flag through the ConfigMap, I'm assuming there is a use-case for disabling this feature. In what context users would want to disable it?

Normally, we don't want to disable this GC, it's just an option for users in case of any issue later on.

> Settting to null shows nothing, meaning we don't pass the flag and we don't have the RBAC permission. The issue here is that we'll be using the non-zero CLI default (5m) and will fail because we don't have the permission.
Settting to empty will actually pass it as-is to the flag, which will fail duration parsing.
Settting to 0s will correctly disable the feature in the ConfigMap, but won't add the RBAC permission.

Agreed on the above points, I have made below changes to rectify
- update default value in CLI to 0s i.e disabled by default, so that we don't couple with RBAC permission
- add default value in config map
- add check in RBAC to make sure that we only add permission if .Values.operator.nodeGCInterval is having some value, and it's not 0s. I don't think we need to check for correct data type (e.g. duration) in helm.

<details>

```
$ helm template cilium ./install/kubernetes/cilium --namespace kube-system --set operator.nodeGCInterval=null | grep -E "nodes-gc-interval|# To perform CiliumNode garbage collector"

$ helm template cilium ./install/kubernetes/cilium --namespace kube-system --set operator.nodeGCInterval= | grep -E "nodes-gc-interval|# To perform CiliumNode garbage collector" 
  nodes-gc-interval: "0s"
 
$ helm template cilium ./install/kubernetes/cilium --namespace kube-system --set operator.nodeGCInterval=0s | grep -E "nodes-gc-interval|# To perform CiliumNode garbage collector"
  nodes-gc-interval: "0s"
  
$ helm template cilium ./install/kubernetes/cilium --namespace kube-system --set operator.nodeGCInterval=1s | grep -E "nodes-gc-interval|# To perform CiliumNode garbage collector"
  nodes-gc-interval: "1s"
    # To perform CiliumNode garbage collector
  
```

</details>

2022-04-28 13:41 UTC, kaworu approved these changes
Thanks @sayboras, patch LGTM now although IMO it would be a tad better if the helm default reflect the cli default. Nitpicking, but here is a suggestion:
<details>
  <summary>details</summary>

```diff
diff --git a/install/kubernetes/cilium/templates/cilium-configmap.yaml b/install/kubernetes/cilium/templates/cilium-configmap.yaml
index 9dabbc381e..fc03209faf 100644
--- a/install/kubernetes/cilium/templates/cilium-configmap.yaml
+++ b/install/kubernetes/cilium/templates/cilium-configmap.yaml
@@ -109,8 +109,10 @@ data:
   cilium-endpoint-gc-interval: "{{ .Values.operator.endpointGCInterval }}"
 {{- end }}
 
-{{- if hasKey .Values.operator "nodeGCInterval" }}
-  nodes-gc-interval: "{{ .Values.operator.nodeGCInterval | default "0s" }}"
+{{- if .Values.operator.nodeGCInterval }}
+  nodes-gc-interval: {{ .Values.operator.nodeGCInterval | quote }}
+{{- else }}
+  nodes-gc-interval: 0
 {{- end }}
 
 {{- if hasKey .Values "disableEndpointCRD" }}
diff --git a/install/kubernetes/cilium/templates/cilium-operator/clusterrole.yaml b/install/kubernetes/cilium/templates/cilium-operator/clusterrole.yaml
index 8af8b9824b..d94b299d33 100644
--- a/install/kubernetes/cilium/templates/cilium-operator/clusterrole.yaml
+++ b/install/kubernetes/cilium/templates/cilium-operator/clusterrole.yaml
@@ -1,4 +1,5 @@
 {{- if and .Values.operator.enabled .Values.serviceAccounts.operator.create }}
+{{- $nodeGC := and .Values.operator.nodeGCInterval (not (regexMatch "^0(?:ns|[uµ]s|ms|s|m|h)?$" .Values.operator.nodeGCInterval)) }}
 apiVersion: rbac.authorization.k8s.io/v1
 kind: ClusterRole
 metadata:
@@ -25,7 +26,7 @@ rules:
 - apiGroups:
   - ""
   resources:
-{{- if or .Values.operator.removeNodeTaints .Values.operator.nodeGCInterval }}
+{{- if or .Values.operator.removeNodeTaints $nodeGC }}
   # To remove node taints or perform underlying CiliumNode garbage collection
   - nodes
 {{- end }}
@@ -123,12 +124,10 @@ rules:
   - get
   - list
   - watch
-{{- if .Values.operator.nodeGCInterval }}
-{{- if ne .Values.operator.nodeGCInterval "0s" }}
+{{- if $nodeGC }}
     # To perform CiliumNode garbage collector
   - delete
 {{- end }}
-{{- end }}
 - apiGroups:
   - cilium.io
   resources:
diff --git a/operator/flags.go b/operator/flags.go
index d1f11f2aa0..a3e79a2e6d 100644
--- a/operator/flags.go
+++ b/operator/flags.go
@@ -249,7 +249,7 @@ func init() {
 	flags.String(option.K8sKubeConfigPath, "", "Absolute path of the kubernetes kubeconfig file")
 	option.BindEnv(option.K8sKubeConfigPath)
 
-	flags.Duration(operatorOption.NodesGCInterval, 0*time.Second, "GC interval for CiliumNodes")
+	flags.Duration(operatorOption.NodesGCInterval, 5*time.Minute, "GC interval for CiliumNodes")
 	option.BindEnv(operatorOption.NodesGCInterval)
 
 	flags.String(operatorOption.OperatorPrometheusServeAddr, operatorOption.PrometheusServeAddr, "Address to serve Prometheus metrics")
```
</details>

With that patch we have the cli default to 5m.

`null`, empty, and `0` yield the same template:
```console
% helm template cilium ./install/kubernetes/cilium --namespace kube-system --set operator.nodeGCInterval=null | grep -E "nodes-gc-interval|# To perform CiliumNode garbage collector"
  nodes-gc-interval: 0
% helm template cilium ./install/kubernetes/cilium --namespace kube-system --set operator.nodeGCInterval= | grep -E "nodes-gc-interval|# To perform CiliumNode garbage collector"
  nodes-gc-interval: 0
% helm template cilium ./install/kubernetes/cilium --namespace kube-system --set operator.nodeGCInterval=0 | grep -E "nodes-gc-interval|# To perform CiliumNode garbage collector"
  nodes-gc-interval: 0
```

We attempt to detect a user-provided zero value, which we pass on the `ConfigMap` so that the user find may back their provided value (although they have no effect):

```console
% helm template cilium ./install/kubernetes/cilium --namespace kube-system --set operator.nodeGCInterval=0ns | grep -E "nodes-gc-interval|# To perform CiliumNode garbage collector"
  nodes-gc-interval: "0ns"
% helm template cilium ./install/kubernetes/cilium --namespace kube-system --set operator.nodeGCInterval=0us | grep -E "nodes-gc-interval|# To perform CiliumNode garbage collector"
  nodes-gc-interval: "0us"
% helm template cilium ./install/kubernetes/cilium --namespace kube-system --set operator.nodeGCInterval=0µs | grep -E "nodes-gc-interval|# To perform CiliumNode garbage collector"
  nodes-gc-interval: "0µs"
% helm template cilium ./install/kubernetes/cilium --namespace kube-system --set operator.nodeGCInterval=0ms | grep -E "nodes-gc-interval|# To perform CiliumNode garbage collector"
  nodes-gc-interval: "0ms"
% helm template cilium ./install/kubernetes/cilium --namespace kube-system --set operator.nodeGCInterval=0s | grep -E "nodes-gc-interval|# To perform CiliumNode garbage collector"
  nodes-gc-interval: "0s"
% helm template cilium ./install/kubernetes/cilium --namespace kube-system --set operator.nodeGCInterval=0m | grep -E "nodes-gc-interval|# To perform CiliumNode garbage collector"
  nodes-gc-interval: "0m"
% helm template cilium ./install/kubernetes/cilium --namespace kube-system --set operator.nodeGCInterval=0h | grep -E "nodes-gc-interval|# To perform CiliumNode garbage collector"
  nodes-gc-interval: "0h"
```

Some zero values are not correctly detected, and in that case we end up with more RBAC permission than actually needed (IMHO the trade-off is fine as convoluted zero values are not expected):
```console
% helm template cilium ./install/kubernetes/cilium --namespace kube-system --set operator.nodeGCInterval=0h0m0s | grep -E "nodes-gc-interval|# To perform CiliumNode garbage collector"
  nodes-gc-interval: "0h0m0s"
    # To perform CiliumNode garbage collector
```

Of course override and default should be passed to the `ConfigMap` and enable RBAC:
```console
% helm template cilium ./install/kubernetes/cilium --namespace kube-system --set operator.nodeGCInterval=42s | grep -E "nodes-gc-interval|# To perform CiliumNode garbage collector"
  nodes-gc-interval: "42s"
    # To perform CiliumNode garbage collector
% helm template cilium ./install/kubernetes/cilium --namespace kube-system | grep -E "nodes-gc-interval|# To perform CiliumNode garbage collector"
  nodes-gc-interval: "5m0s"
    # To perform CiliumNode garbage collector
```

2022-05-03 13:47 UTC, sayboras commented
/test

2022-05-03 16:55 UTC, qmonnet approved these changes

2022-05-04 01:19 UTC, sayboras commented
/test-1.23-net-next

2022-05-04 07:59 UTC, sayboras commented
Thanks Alex.

I noticed that this suggestion should be applied for other duration field in helm values as well. For consistency, I think we can just keep as what we have in this PR.

Raised one https://github.com/cilium/cilium/issues/19684 for future improvement.

2022-05-04 08:02 UTC, sayboras commented
All tests passed except NAT-46x64 and ci-l4lb jobs are still under waiting, there two jobs are going to merge to one, and they are not related to this change.

Mark PR ready to merge.

2022-05-04 11:34 UTC, aanm commented
waiting on https://github.com/cilium/cilium/pull/19686 to be merged

2022-05-05 02:51 UTC, sayboras commented
Force push to resolve the conflict with master, only one file is changed, the diff can be found as per below:

```diff
diff --git a/install/kubernetes/cilium/templates/cilium-operator/clusterrole.yaml b/install/kubernetes/cilium/templates/cilium-operator/clusterrole.yaml
index 531566cc4b..8af8b9824b 100644
--- a/install/kubernetes/cilium/templates/cilium-operator/clusterrole.yaml
+++ b/install/kubernetes/cilium/templates/cilium-operator/clusterrole.yaml
@@ -21,21 +21,12 @@ rules:
 {{- end }}
 {{- end }}
 {{- end }}
-{{- if or .Values.operator.removeNodeTaints .Values.operator.setNodeNetworkStatus .Values.operator.endpointGCInterval }}
-- apiGroups:
-  - ""
-  resources:
-  - nodes
-  verbs:
-  - list
-  - watch
-{{- end }}
 {{- if or .Values.operator.removeNodeTaints .Values.operator.setNodeNetworkStatus }}
 - apiGroups:
   - ""
   resources:
-{{- if .Values.operator.removeNodeTaints }}
-  # To remove node taints
+{{- if or .Values.operator.removeNodeTaints .Values.operator.nodeGCInterval }}
+  # To remove node taints or perform underlying CiliumNode garbage collection
   - nodes
 {{- end }}
 {{- if .Values.operator.setNodeNetworkStatus }}
@@ -43,6 +34,8 @@ rules:
   - nodes/status
 {{- end }}
   verbs:
+  - list
+  - watch
   - patch
 {{- end }}
 - apiGroups:
```

2022-05-05 02:59 UTC, sayboras commented
/test

2022-05-06 01:10 UTC, sayboras commented
/test-gke

2022-05-06 01:11 UTC, sayboras commented
/test-1.16-4.9

2022-05-06 01:11 UTC, sayboras commented
/test-1.22-4.19

2022-05-06 01:11 UTC, sayboras commented
/test-1.23-net-next

2022-05-06 01:11 UTC, sayboras commented
/test-1.21-5.4

2022-05-06 05:21 UTC, sayboras commented
All the tests passed now, marking this ready for merge.

2022-05-06 11:48 UTC, merged