operator: fix identity GC collection
cilium/cilium pull request #19649
Opened 2022-04-29 14:58 UTC by aanm

As the operator uses a different constructor for the GC of the
allocator, this constructor was not being initialized with the min and
max values of the identities that it should be GC. This commit adds
those options making it possible for the Operator to GC those
identities.

Fixes: 0c0f96531286 ("operator: only GC identity keys of its own cluster")
Signed-off-by: André Martins <andre@cilium.io>

Fixes https://github.com/cilium/cilium/issues/19648

2022-04-29 14:58 UTC, aanm commented
/test

2022-04-29 18:22 UTC, joestringer approved these changes

2022-04-29 18:31 UTC, aditighag requested changes
The fix seems straightforward so LGTM. But looking at the linked "Fixed" PR, we seem to have different identity allocators, and an operator is required to GC identities only from their cluster. While ideally we should have a unified way of constructing the allocators to avoid such misses, but that's probably out of the scope of your PR. But at the very least, can we add some comments to the code (how min and max are set for the different allocators)?
The linked PR is very light on details in the commit description - https://github.com/aanm/cilium/commit/0c0f96531286be0a443d2849718568b72d1b9931.

2022-04-29 20:47 UTC, aditighag approved these changes
Synced up offline with André. Looks like the linked PR that introduced this regression relied mainly on unit tests to test the fix? 😕 The unit test passes a different allocator to `RunGC`.

2022-04-29 21:03 UTC, merged

2022-04-30 01:10 UTC, christarazi commented on pkg/allocator/allocator.go
> +func NewAllocatorForGC(backend Backend, opts ...AllocatorOption) *Allocator {
I guess we can prevent this from ever happening again by making the constructors take the min and max, but maybe that's not useful anymore now. Good catch.

2022-04-30 01:11 UTC, christarazi commented on pkg/allocator/allocator.go
> +func NewAllocatorForGC(backend Backend, opts ...AllocatorOption) *Allocator {
Aditi above slightly touched on this.