Add description for some value in install/kubernetes/cilim/values.yaml
cilium/cilium pull request #19658
Opened 2022-04-30 09:36 UTC by my-git9

Signed-off-by: xin.li <xin.li@daocloud.io>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

Fixes: Add description for some values(marked TODO) in install/kubernetes/cilim/values.yaml

```release-note
NONE
```

2022-04-30 09:40 UTC, my-git9 commented
/release-note/ci

2022-04-30 09:40 UTC, my-git9 commented
/release-note ci

2022-04-30 14:53 UTC, my-git9 commented
/release-note-misc

2022-05-01 05:00 UTC, sayboras reviewed
Thanks for your PR, please find below my comments.

Also, seems like the second commit was supposed to be merged with first one.

2022-05-01 05:00 UTC, sayboras commented on install/kubernetes/cilium/values.yaml
> +# -- Enable setting identity mark for local traffic (default true).
is the default value true ?

2022-05-01 05:00 UTC, sayboras commented on install/kubernetes/cilium/values.yaml
>  # svcSourceRangeCheck:
unrelated to this PR.

This flag is not used in helm at all, can you help to add the same into configmap ? Thanks.

2022-05-01 05:00 UTC, sayboras commented on install/kubernetes/cilium/values.yaml
>  # synchronizeK8sNodes: true
same as above, this flag is not used at all in helm chart.

2022-05-01 05:48 UTC, my-git9 commented on install/kubernetes/cilium/values.yaml
>  # svcSourceRangeCheck:
There are relevant references in the configmap:
```
{{- if .Values.svcSourceRangeCheck }}
  enable-svc-source-range-check: {{ .Values.svcSourceRangeCheck | quote }}
{{- end }}```
 I think we just need to open the annotation and assign a value here.

2022-05-01 05:48 UTC, my-git9 commented on install/kubernetes/cilium/values.yaml
>  # synchronizeK8sNodes: true
Same as above, please review again, thanks

2022-05-01 05:51 UTC, sayboras commented on install/kubernetes/cilium/values.yaml
>  # svcSourceRangeCheck:
sorry about this, my helm plugin in IDE seems broken

2022-05-01 06:54 UTC, my-git9 commented
/retest

2022-05-01 09:20 UTC, sayboras commented on install/kubernetes/cilium/values.yaml
> +# -- Enable setting identity mark for local traffic (default true).
I mean the next line was having value as false, while for other fields (e.g. svcSourceRangeCheck, synchronizeK8sNodes) are uncommented with default value. 

I think it's making sense to set have helm value with default value.

2022-05-01 09:22 UTC, sayboras reviewed
LGTM with one minor comment above

Please re-run the below targets to update docs

```
make -C Documentation update-helm-values 
make -C install/kubernetes docs
```

2022-05-02 05:36 UTC, sayboras commented on install/kubernetes/cilium/values.yaml
> +# -- Enable setting identity mark for local traffic (default true).
@my-git9 curious to know what you think on the above.

2022-05-03 16:38 UTC, qmonnet requested changes
Thank you for the contribution! Please find some comments below.

Note that I would also recommend adding a bit more context in the commit description; in particular, it would be helpful to mention where the default values are coming from, so that it's easy to find from the git history in the future.

2022-05-03 16:38 UTC, qmonnet commented on install/kubernetes/cilium/values.yaml
> +# -- Enable check of service source ranges (currently, only for LoadBalancer) (default true).
I don't think it's necessary to provide the default value between parenthesis, here and elsewhere. In the current file, the default is right on the following line; in the generated documentation, it's picked up and displayed already, no need to have it a second time.

2022-05-03 16:38 UTC, qmonnet commented on install/kubernetes/cilium/values.yaml
>  # identityHeartbeatTimeout: ""
Why aren't those lines getting their default value assigned as for e.g. `identityChangeGracePeriod`, even if they're commented?

2022-05-03 16:38 UTC, qmonnet commented on install/kubernetes/cilium/values.yaml
> +# -- Enable setting identity mark for local traffic (default true).
Looks like it defaults to `true` in pkg/defaults/defaults.go.

2022-05-03 16:38 UTC, qmonnet commented on install/kubernetes/cilium/values.yaml
> +# -- Enables k8s EndpointSlice feature in Cilium if the k8s cluster supports it (default true).
```suggestion
# -- Enable Kubernetes EndpointSlice feature in Cilium if the cluster supports it (default true).
```

2022-05-04 08:47 UTC, qmonnet commented on install/kubernetes/cilium/values.yaml
> +# -- Time to wait before using new identity on endpoint identity change (default 5s).
Any particular reason for keeping the default values for commented options?

2022-05-04 10:58 UTC, qmonnet approved these changes
Thanks!

2022-05-04 10:58 UTC, qmonnet commented
/test

2022-05-04 10:59 UTC, sayboras approved these changes
LGTM :100:

2022-05-04 13:07 UTC, qmonnet commented
/test

2022-05-04 13:57 UTC, my-git9 commented
/retest

2022-05-04 13:58 UTC, my-git9 commented
/retest

2022-05-04 13:59 UTC, my-git9 commented
/test

2022-05-04 14:01 UTC, qmonnet commented
@my-git9 This is not gonna work, one needs commit access to (re-)trigger the tests.
AKS test is currently broken, so expected to fail.

2022-05-04 14:18 UTC, my-git9 commented
> @my-git9 This is not gonna work, one needs to be a member of the Cilium organisation to (re-)trigger the tests. AKS test is currently broken, so expected to fail.

OK, thanks

2022-05-05 10:26 UTC, qmonnet commented
AWS-CNI test is currently known to be broken, IPv6 smoke test as well (should be fixed by https://github.com/cilium/cilium/pull/19644/commits/953b1f9606bd9551546c5aabacd82ad323f53ac7 on master). `Cilium-PR-K8s-1.23-kernel-net-next` hits a flake. The changes are minor and I don't think there's a need to re-run these tests.

Tam and I both approved before the spelling-check change, so the reviews are in. I'm marking as ready-to-merge.

2022-05-05 10:26 UTC, qmonnet approved these changes

2022-05-05 13:27 UTC, kaworu approved these changes

2022-05-06 11:45 UTC, merged