vtep: Documents VTEP redirection and L7 policy partial incompatibility
cilium/cilium pull request #19700
Opened 2022-05-04 18:56 UTC by vincentmli

Update the VTEP redirection and L7 policy partial incompatibility
documentation, log warnings when both VTEP rediretion and L7 policy
enabled

Signed-off-by: Vincent Li <v.li@f5.com>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
doc: VTEP redirection and L7 policy partially incompatible
```

2022-05-06 19:17 UTC, Kikiodazie commented on Documentation/gettingstarted/vtep.rst
> +   This feature is in beta, and is currently partially incompatible with L7 policy.
```suggestion
   This feature is in beta, and currently, it is partially incompatible with the L7 policy.
```

2022-05-06 19:17 UTC, Kikiodazie commented on Documentation/gettingstarted/vtep.rst
> +   When pod with egress L7 policy sending request to VTEP devices, the VTEP redirection
```suggestion
   When pod with egress L7 policy sends a request to VTEP devices, the VTEP redirection
```

2022-05-09 19:41 UTC, joestringer requested changes
Couple of nits, otherwise LGTM thanks.

2022-05-09 19:41 UTC, joestringer commented on Documentation/gettingstarted/vtep.rst
> +   When pod with egress L7 policy sends a request to VTEP devices, the VTEP redirection
```suggestion
   When a pod with an egress L7 policy sends a request to VTEP devices, the VTEP redirection
```

2022-05-09 19:41 UTC, joestringer commented on daemon/cmd/datapath.go
> +					"if the endpoint has a L7 policy and send request to VTEP devices , endpoint traffic will not go through VTEP devices.", option.EnableL7Proxy)
```suggestion
			log.WithField(logfields.URL, "https://github.com/cilium/cilium/issues/19699").
				Warningf("Both VTEP redirection (%s) and L7 proxy (--%s) are enabled. This is currently not fully supported: "+
					"if the endpoint has a L7 policy and send request to VTEP devices , endpoint traffic will not go through VTEP devices.", option.EnableVTEP, option.EnableL7Proxy)
```

2022-05-09 21:23 UTC, joestringer approved these changes

2022-05-09 21:23 UTC, merged