Exclude interface's primary address from IP pool by default in Azure
cilium/cilium pull request #19743
Opened 2022-05-06 19:57 UTC by hemanthmalla

Currently `--azure-use-primary-address` defaults to true and this can lead
to connectivity issues in host networked pods unless users explicitly
disable DHCP on the interface.

See https://github.com/cilium/cilium/pull/13415 for more details on connectivity issues. 
Defaulting to false also makes the behavior consistent with ENI mode.

Signed-off-by: Hemanth Malla <hemanth.malla@datadoghq.com>

Open questions  : 
- [ ] How do i make sure this change shows up in upgrade guides ?
- [ ] What happens to existing pods using the primary IP for users upgrading from prior versions ?

2022-05-09 21:21 UTC, christarazi requested changes
Change makes sense given that it's converging with the ENI implementation.

1) Please add a note in the [upgrade guide](https://docs.cilium.io/en/latest/operations/upgrade/#upgrade-notes).
2) I'm not sure, but it sounds like users will need to restart the workload pods which have those IPs so that Cilium can assign new ones that are non-primary. I'm not sure it's worth coming up with a solution to help make this a hitless upgrade, but we can discuss this in the community meeting if you'd like.
3) Let's also bring that up in the community meeting

2022-05-25 04:41 UTC, joestringer commented
For (2), what's the consequence? is it brief disruption during upgrade or are those workloads completely impacted until the user takes action?

I'm not sure exactly how you detect this, but the upgrade guide has the preflight DaemonSet available for injecting logic if you want to e.g. identify specific workloads which will be affected and warn users upon upgrade.

Typically we will not change most options during upgrade, but instead maintain an `upgradeCompatibility` flag inside the helm charts which ensures that if the user previously had some option, they retain that option in perpetuity. On the other hand if a user deploys a fresh version of the Helm charts, then it will deploy the new option. This can also be a possible approach to avoid upgrade impact.

Re:1.12 it seems like a small enough change that as long as we have a pretty solid understanding of the upgrade impact and any potential mitigations or steps for users, then we could potentially include it.

2022-06-17 13:51 UTC, hemanthmalla commented
/test

2022-06-22 19:44 UTC, hemanthmalla commented
@christarazi / @joestringer Added support for `--bypass-ip-availability-upon-restore` in azure IPAM mode to handle upgrade impact. Also added a note in upgrade guide and added support for upgrade compatibility in helm chart. Do you mind reviewing the new changes ?

2022-06-22 21:30 UTC, christarazi approved these changes

2022-06-23 08:46 UTC, gandro approved these changes
Thanks!

2022-06-25 00:00 UTC, hemanthmalla commented
Marking this as ready to merge since the doc change is a minor paragraph addition and we have the rest of approvals.

2022-06-28 11:45 UTC, merged

2022-06-28 11:47 UTC, pchaigno commented
Oh, I merged a bit too quickly here. @hemanthmalla It seems we didn't rerun the end-to-end tests after the rebase and latest changes :grimacing: 

I'll keep an eye on CI and will revert if it breaks anything.

2022-06-28 12:58 UTC, pchaigno commented
Ah, I had not noticed the changes were that specific to AKS. We're probably good then :slightly_smiling_face: