make: fix Makefile to don't call docker pull command because error causes when using podman.
cilium/cilium pull request #19748
Opened 2022-05-08 17:19 UTC by koba1t

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

I try executing to debug command from Makefile using podman, I execute the following command:
make debug CONTAINER_ENGINE="sudo podman"

But, This command happens below errors on the terminal:

make  -C Documentation check
make[1]: Entering directory '/home/kob/git/cilium/Documentation'
# Pre-pull FROM docker images due to Buildkit sometimes failing to pull them.
grep "^FROM " Dockerfile | cut -d ' ' -f2 | xargs -n1 docker pull
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
make[1]: *** [Makefile:18: builder-image] Error 123
make[1]: Leaving directory '/home/kob/git/cilium/Documentation'
make: *** [Makefile:588: postcheck] Error 2

The cause is a Makefile calling docker pull command and causes an error when docker daemon is not running on a machine.
This patch fixes it and replaces the docker pull command with the $(CONTAINER_ENGINE) pull it supporting podman.

Signed-off-by: Yugo Kobayashi <kobdotsh@gmail.com>

```release-note

```

2022-05-09 09:49 UTC, qmonnet requested changes
Looks good, thanks! With two nitpicks:
- Can you please remove the double space which, I guess, was added by mistake?
- Can you please shorten a bit your commit object? We're trying to keep it under 75 characters so it's easier to read in the Git history, and yours is a bit over the limit.

![image](https://user-images.githubusercontent.com/17001771/167385092-2a1401d9-e906-4657-a4e9-44674e32b78c.png)

2022-05-09 09:49 UTC, qmonnet commented on Documentation/Makefile
> +	grep "^FROM " $< | cut -d ' ' -f2 |  xargs -n1 $(CONTAINER_ENGINE) pull
Why the extra space?
```suggestion
	grep "^FROM " $< | cut -d ' ' -f2 | xargs -n1 $(CONTAINER_ENGINE) pull
```

2022-05-09 10:01 UTC, koba1t commented on Documentation/Makefile
> +	grep "^FROM " $< | cut -d ' ' -f2 |  xargs -n1 $(CONTAINER_ENGINE) pull
I think it is a mistake. I'll fix it.

2022-05-09 10:12 UTC, koba1t commented
hi @qmonnet.
I fixed a long commit subject and unnecessary whitespace. 
Could you recheck it and rerun CI?

2022-05-09 10:38 UTC, qmonnet approved these changes
Looks good, thank you!

2022-05-11 18:43 UTC, joestringer approved these changes

2022-05-11 18:43 UTC, merged