Documentation: Clearer compatibility listing
cilium/cilium pull request #1989
Opened 2017-11-07 18:45 UTC by raybejjani

**Summary of changes**:
This is a start at recording all the various versions we need in order to provide specific functionality. It is intended to address #1873 but needs more data about other cases to be useful. It is incomplete and I/we need to fill in sections marked ?? at least

@tgraf aanm fixed up that particular message last week. Did you still mean to have the issue open? Is this PR too broad for this case?

@aanm Is there a listing for k8s NetworkPolicy API versions that's similar to 
https://kubernetes.io/docs/reference/workloads-18-19/ ? I couldn't find one.

Fixes: #1873 

```release-note
Documented cilium capabilities when used with various container frameworks, kvstore and kernel versions.
```

2017-11-07 19:23 UTC, aanm requested changes
>@aanm Is there a listing for k8s NetworkPolicy API versions that's similar to
>https://kubernetes.io/docs/reference/workloads-18-19/ ? I couldn't find one.

I'm not aware of any

2017-11-07 19:23 UTC, aanm commented on Documentation/compatibility.rst
> +|             | Exclusively one of:                                   |
Remove the `Exclusively one of` and add `CiliumNetworkPolicy as a CustomResourceDefinition ` on all k8s versions after 1.6

2017-11-08 04:43 UTC, tgraf requested changes

2017-11-08 04:43 UTC, tgraf commented on Documentation/compatibility.rst
> +cilium requires kernel version ?? and newer.
Requirements are covered here:
http://docs.cilium.io/en/stable/install/#system-requirements

2017-11-08 04:43 UTC, tgraf commented on Documentation/compatibility.rst
> +| etcd       | >??     | * Lock-free ID allocation             |
You can skip this, I'll add this to the docs together with the addition of the new kvstore code. This code has not been merged yet.

2017-11-09 22:05 UTC, raybejjani commented
ok, @tgraf How does this status output look? I expect we'd list TPR/CRD as well. I noticed we were printing with two different formatters/writers, so the order is now different, with IPs listed last.
@aanm Do you think this shouldn't go into `status`? perhaps `config`?

Separately, I switched to a simple k8s compatibility page.

```
vagrant@cilium-k8s-master:~/go/src/github.com/cilium/cilium$ cilium status | head
KVStore:            Ok   Etcd: https://192.168.33.11:2379 - (Leader) 3.2.7
ContainerRuntime:   Ok
Kubernetes:         Ok   OK
Kubernetes APIs:    networking.k8s.io/v1, extensions/v1beta1
Cilium:             Ok   OK
NodeMonitor:        Listening for events on 2 CPUs with 64x4096 of shared memory
```

2017-11-09 23:28 UTC, aanm commented
```
vagrant@cilium-k8s-master:~/go/src/github.com/cilium/cilium$ cilium status | head
KVStore:            Ok   Etcd: https://192.168.33.11:2379 - (Leader) 3.2.7
ContainerRuntime:   Ok
Kubernetes:         Ok   OK
Kubernetes APIs:    networking.k8s.io/v1, extensions/v1beta1  -> You need to add something
 saying this is related with kubernetes network policy because extensions/v1beta1 is too broad
 for example, the daemonsets are also under extensions/v1beta1. Also add which cilium version
 we are listening for (cilium.io/v1 or cilium.io/v2)
Cilium:             Ok   OK
NodeMonitor:        Listening for events on 2 CPUs with 64x4096 of shared memory
```

2017-11-10 17:31 UTC, raybejjani commented
Righto. This was far more involved than expected! I can break some of the fixups into separate PRs, skim the commits to see what they are.

The output now shows:
```
KVStore:            Ok   Etcd: https://192.168.33.11:2379 - (Leader) 3.2.7
ContainerRuntime:   Ok
Kubernetes:         Ok   OK
Kubernetes APIs:    ["cilium/v2::CiliumNetworkPolicy", "extensions/v1beta1::NetworkPolicy", "networking.k8s.io/v1::NetworkPolicy", "core/v1::Service", "core/v1::Endpoint", "extensions/v1beta1::Ingress", "core/v1::Node", "CustomResourceDefinition"]
Cilium:             Ok   OK
NodeMonitor:        Listening for events on 2 CPUs with 64x4096 of shared memory
```

and we add and remove things in that list to reflect the actual Informers we have running, or when we succeed/fail at using TPR/CRDs. I think those are all the API Groups but maybe there are more we use?

2017-11-14 00:48 UTC, tgraf approved these changes

2017-11-14 00:49 UTC, merged