fix aws-cni conformance test
cilium/cilium pull request #20049
Opened 2022-06-01 21:55 UTC by aanm

Commit 2d7af3a (".github: add support for cilium-cli in aws-cni
conformance tests") changed the AWS-CNI workflow to install Cilium using
the CLI instead of Helm. All of the Helm flags were passed through the
CLI using --helm-set.

However, the CLI also does it's own magic and isn't aware that we want
to install Cilium in chaining mode. Therefore, it detects EKS and
incorrectly sets IPAM mode to ENI.

As a result, Cilium attempts to setup the IP rules and routes for new
pods. It seems to fail in most cases—maybe because AWS-CNI already setup
the state—but sometimes succeeds. When it succeeds, pods end up with an
egress rule pointing to a non-existing ip route table.

This usually surfaces in the workflow runs as a DNS failure: the client
pod fails to egress to the DNS backend on a remote node. In rarer cases,
it surfaces as a failing connectivity test for some of the pods.

This commit fixes it by overwriting some of the helm flags set
automatically by Cilium-cli namely "eni.enabled=false" and
"ipam=cluster-pool".

The longer-term fix would be to support chaining mode in the CLI.

Reported-by: Paul Chaignon <paul@cilium.io>
Signed-off-by: André Martins <andre@cilium.io>

2022-06-01 22:03 UTC, christarazi approved these changes

2022-06-02 11:24 UTC, sayboras approved these changes
:shipit:

2022-06-02 13:16 UTC, pchaigno requested changes
Could we run this at least 5 times before re-enabling? Twice won't catch many flakes.

2022-06-02 13:20 UTC, pchaigno requested changes
We also need to fix the v1.11 workflow.

2022-06-02 13:20 UTC, pchaigno commented on .github/workflows/conformance-aws-cni.yaml
> +            --helm-set=ipam.mode=cluster-pool \
Can we have a comment here to explain why setting what looks like the default value is necessary?

2022-06-02 15:32 UTC, aanm commented
@pchaigno it failed [here](https://github.com/cilium/cilium/runs/6710513570?check_suite_focus=true) is this the same flake as before?

2022-06-02 21:23 UTC, pchaigno commented
> @pchaigno it failed [here](https://github.com/cilium/cilium/runs/6710513570?check_suite_focus=true) is this the same flake as before?

That's a different flake. We should file an issue for it. Not sure how frequent, but if it is frequent enough, then maybe we shouldn't reenable.

It's a very weird one: policy denied drops on egress for pod-to-pod traffic on the same node, with correct identities, and a correct policy map at the time we collect the sysdump.

2022-06-03 20:30 UTC, merged