neigh: Support multi device neighbor discovery
cilium/cilium pull request #20092
Opened 2022-06-07 02:33 UTC by ysksuzuki

Please see the commit message.

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

Fixes: #19908

2022-06-07 10:13 UTC, brb commented
@ysksuzuki Thanks for the PR! Pinging @borkmann to review too, as he recently completely reworked the neigh management.

2022-06-08 07:51 UTC, borkmann approved these changes
Great work, thanks for addressing this limitation!

Could you please also extend the documentation under ...
 - https://docs.cilium.io/en/latest/gettingstarted/kubeproxy-free/#neighbor-discovery
 ... and document the updated behavior for multi-device in detail (maybe new paragraph for it)? Are there potential limitations, I presume it currently does not work yet with the runtime device detection, right?

2022-06-08 07:51 UTC, borkmann commented
/test

2022-06-08 09:07 UTC, ysksuzuki commented
@borkmann Thank you for the review!

> Could you please also extend the documentation under

Sure, will do that.

> I presume it currently does not work yet with the runtime device detection, right?

Right, it doesn't work for now. I think neighDiscoveryLink should follow the device changes here. Will do it in a follow-up PR later.
https://github.com/cilium/cilium/blob/aa7572be0f7cfece0ebfb739716ab970c478d358/daemon/cmd/daemon.go#L1287

2022-06-09 10:15 UTC, ysksuzuki commented
@borkmann Updated the document for multi-device. Please check it.

2022-06-09 11:04 UTC, qmonnet requested changes
A few suggestions, but this looks good, thank you!

2022-06-09 11:04 UTC, qmonnet commented on Documentation/gettingstarted/kubeproxy-free.rst
> +and global scope addresses each(10.69.0.1/26 and 10.69.0.2/26). A next-hop from node1 to node2 is
```suggestion
and global scope addresses each (10.69.0.1/26 and 10.69.0.2/26). A next-hop from node1 to node2 is
```

2022-06-09 11:04 UTC, qmonnet commented on Documentation/gettingstarted/kubeproxy-free.rst
> +.. code-block:: shell-session
```suggestion
::
```

2022-06-09 11:04 UTC, qmonnet commented on Documentation/gettingstarted/kubeproxy-free.rst
> +    (On node1)
```suggestion
With, on node1:
    
    .. code-block:: shell-session
```

2022-06-10 01:35 UTC, ysksuzuki commented
@qmonnet Thank you for the review! I modified the document accordingly.

2022-06-10 09:27 UTC, qmonnet approved these changes
Thanks a lot! If you could only squash the last two commits together (docs fixes with docs update), it would be perfect :)

2022-06-10 09:37 UTC, ysksuzuki commented
> if you could only squash the last two commits together

Done!

2022-06-21 10:26 UTC, ysksuzuki commented
@borkmann @qmonnet Hello, is there anything I could do for this PR?

2022-06-21 21:31 UTC, qmonnet commented
/test

2022-06-22 00:04 UTC, ysksuzuki commented
Two tests failed. Hitting known flakes?

ConformanceAKS: https://github.com/cilium/cilium/issues/19472
Multicluster: https://github.com/cilium/cilium/issues/20186 ?

2022-06-23 00:45 UTC, sayboras commented
ConformanceAKS is disabled now due to high probability of failure. Multicluster should be fine now.

2022-06-24 10:01 UTC, brb commented
@sayboras Is it good to merge?

2022-06-24 10:03 UTC, sayboras commented
> Is it good to merge?

Yes it is, just wait for one more codeowner review for the bot to mark ready to merge.

2022-06-24 10:44 UTC, NikAleksandrov approved these changes

2022-06-24 11:07 UTC, merged