daemon: Prevent endpoint-routes and tunneling
cilium/cilium pull request #20145
Opened 2022-06-10 00:07 UTC by joestringer

Tunneling mode hasn't been fully figured out with endpoint-routes mode,
which results in various issues like applying policy twice on traffic
coming into a node or other weird problems. Prevent users from
configuring this option for now until we resolve those issues.

2022-06-10 00:10 UTC, michi-covalent approved these changes

2022-06-10 01:35 UTC, christarazi approved these changes

2022-06-10 03:56 UTC, joestringer commented
It appears that this is the default in OpenShift deployments today. Further investigation needed to resolve that before we go and disable this combination.

2022-06-10 09:21 UTC, pchaigno requested changes
As you've noticed, we have users relying on this already. I don't think there's a way around fixing the bugs it introduces.

2022-06-10 19:13 UTC, joestringer commented
What concerns me a bit is that I don't think we ever specifically decided that this combination is safe enough for users to run, so anyone who's running it out there today is liable to hit a range of weird & wonderful issues, and Cilium won't give any sort of indication that they're running a combination with known issues.

Is there a middle ground where this is an `Error()` instead of a `Fatal()`?

2022-06-10 19:14 UTC, joestringer commented
Maybe to be a bit more clear also, this is an attempt to just give users a heads up that there might be a problem in case they hit an issue, assuming that properly fixing this combination of configurations will take a bit longer. If the fixes are almost done then I'll happily discard this PR.

2022-07-07 21:57 UTC, closed without merging

2022-09-06 07:47 UTC, brb commented
> Is there a middle ground where this is an Error() instead of a Fatal()?

@joestringer Could we at least Warn users about possible consequences? Otherwise, users might be running e.g., into https://github.com/cilium/cilium/issues/16446, and such issues is not so easy to debug / obvious for users.

2022-09-06 19:15 UTC, joestringer commented
@brb I had avoided this since it's pointless warning users who have no knowledge or control over the flag, in particular OpenShift where we set this combination by default. If we change that default, then yeah adding an error/warning seems reasonable.