v1.9 backports 2022-06-13
cilium/cilium pull request #20180
Opened 2022-06-13 11:05 UTC by nebril

* #19925 -- pkg/fqdn: Fix missing delete for forward map (@christarazi)
 * #19522 -- redirectpolicy: Fix panic in service matcher LPR processing (@aditighag)

PRs skipped due conflicts:

 * #19565 -- ui: v0.9.0 images and drop envoy proxy container (@geakstr)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 19925 19522; do contrib/backporting/set-labels.py $pr done 1.9; done
```
or with
```
$ make add-label BRANCH=v1.9 ISSUES=19925,19522
```

2022-06-13 20:35 UTC, christarazi approved these changes

2022-06-13 21:41 UTC, aditighag requested changes

2022-06-13 21:41 UTC, aditighag commented on pkg/logging/logfields/logfields.go
> +	ENPName = "enpName"
This change is not part of the original PR.

2022-06-13 21:41 UTC, aditighag commented on pkg/logging/logfields/logfields.go
> +	// DirectRoutingDevice is the name of the direct routing device
This was accidentally merged in the original PR. Can you revert it in the backport?

2022-06-15 14:37 UTC, pchaigno commented on pkg/logging/logfields/logfields.go
> +	// DirectRoutingDevice is the name of the direct routing device
Why is this incorrect? Looks like it's fixing spacing. Sure, unrelated to the other changes but also very unlikely to ever cause conflicts, no?

Are you going to revert this in master or did I misunderstand? Doesn't seem worth it to me.

2022-06-15 14:43 UTC, aditighag approved these changes
LGTM Thanks!

2022-06-15 14:45 UTC, aditighag commented on pkg/logging/logfields/logfields.go
> +	// DirectRoutingDevice is the name of the direct routing device
Yeah, the spacing in the upstream code was fixed by my IDE. Agreed, we can let it be even though it's unrelated to the upstream PR changes.

2022-06-16 07:59 UTC, kkourt commented
/test-1.17-4.9

2022-06-16 08:10 UTC, kkourt commented
> Job 'Cilium-PR-Runtime-4.9' failed:

This fails on:
> 	 FAIL: proxy_test.go:381: DNSProxyTestSuite.TestRespondViaCorrectProtocol

Will try to see if I can reproduce locally.

2022-06-16 16:13 UTC, kkourt commented
/test-runtime

2022-06-17 05:42 UTC, kkourt commented
We have ACKs from authors, tests are green, marking as ready to merge.

2022-06-17 09:42 UTC, merged

2022-06-17 09:58 UTC, pchaigno commented
Should we file an issue for the new Runtime flake?