Update cli-download.rst
cilium/cilium pull request #20181
Opened 2022-06-13 15:43 UTC by nvibert

Proposed changed to docs to support M1/M2 (Apple Silicon) installation

Signed-off-by: Nico Vibert <nicolas.vibert@isovalent.com>

2022-06-13 15:52 UTC, pchaigno approved these changes

2022-06-13 15:54 UTC, qmonnet requested changes
Thanks!

Contents look good, but it seems that the indentation for the new `.. group-tab` is wrong: the new commands are included in the same tab, the ARM tab is empty.

![image](https://user-images.githubusercontent.com/17001771/173393929-73afc2cb-862a-4587-9671-ed28124b3a7d.png)

Note that you can preview the changes by clicking on the “Netlify preview” link from CI (although I think this is going to change very soon), or you can build locally with `make render-docs`.

2022-06-13 15:54 UTC, qmonnet commented on Documentation/gettingstarted/cli-download.rst
> +   .. group-tab:: macOS (Apple Silicon (ARM))
```suggestion
   .. group-tab:: macOS (Apple Silicon - ARM)
```

Nit: Easier to read than embedded parenthesis?

Alternatively, Documentation/gettingstarted/istio.rst uses `OSX` and `OSX (Apple Silicon)`.

2022-06-14 09:08 UTC, qmonnet reviewed
Looks great now, thank you! Can you please squash your commits into a single one? (No need to keep the `Co-authored-by` tag for my suggestion here, esp. because GH didn't default to my work email.)

2022-06-14 11:10 UTC, nvibert commented
![Screenshot 2022-06-14 at 10 02 49](https://user-images.githubusercontent.com/28391130/173538634-ffdb6a65-93ae-466c-bc87-b440f662c2da.png)
That looks better.

2022-06-15 10:28 UTC, qmonnet approved these changes
Renders all good this time, thanks!

2022-06-15 10:50 UTC, merged