[WIP] [DNM] dnsproxy: Stop using regex groups
cilium/cilium pull request #20214
Opened 2022-06-15 15:45 UTC by odinuge

WIP for testing:

Would be nice to get to run all the test suites to check for correctness issues before we start testing it locally. Tested it quickly on a small 25+- node k8s cluster, and everything seemed fine.

TL;DR: The code does not care (afaik.) about what group is matched, so there isn't
any reason to use groups. The regex compiler should be able to optimize the regex
way better without groups, hopefully making the actual regex prog smaller and faster.

For small regex this is probably fine, but in our case, we have 400-500-600 fqdns
in that list (as I understand it), and that crates the same amount of regex groups
that we don't need.

Worst case is the same mem and cpu usage, and no real diff in behavior.

Signed-off-by: Odin Ugedal <ougedal@palantir.com>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
TBD
```

2022-06-15 15:49 UTC, odinuge commented
ping @ungureanuvladvictor

2022-06-15 15:53 UTC, jibi commented
/test

2022-06-15 16:45 UTC, jibi commented
/test-1.23-net-next

2022-06-16 22:02 UTC, odinuge commented
Hmmm. Looks like those two jobs passed on the last commit... Strange...
/test

2022-06-20 00:00 UTC, christarazi requested changes
Thanks for the PR! Could you add some benchmarking code to the tests to see what a difference this makes?

2022-06-21 18:06 UTC, christarazi commented
Superseded by https://github.com/cilium/cilium/pull/20246

2022-06-21 18:06 UTC, closed without merging