Mark cilium pod as CriticalPod in the DaemonSet
cilium/cilium pull request #2024
Opened 2017-11-13 04:24 UTC by manalibhutiyani

We experienced the cilium pod getting evicted away due to nodefs pressure.
We should mark the pod as critical (the requirement for it is to run
in the kube-system namespace) as cilium is required for the
operating of all other pods on the node.

Fixes #1428

Signed-off-by: Manali Bhutiyani <manali@covalent.io>

```release-note
Mark cilium pod as CriticalPod in the DaemonSet
```

2017-11-13 04:27 UTC, manalibhutiyani commented
@aanm @ianvernon : I was unsure of how to handle examples/kubernetes/cilium.yaml

If you can give me pointers in the right direction, that would be great!

diff --git a/examples/kubernetes/cilium.yaml b/examples/kubernetes/cilium.yaml
index 5dc15a0f0..a3696895b 100644
--- a/examples/kubernetes/cilium.yaml
+++ b/examples/kubernetes/cilium.yaml
@@ -75,6 +75,7 @@ spec:
         k8s-app: cilium
         kubernetes.io/cluster-service: "true"
       annotations:
+        scheduler.alpha.kubernetes.io/critical-pod: ''
         scheduler.alpha.kubernetes.io/tolerations: >-
           [{"key":"dedicated","operator":"Equal","value":"master","effect":"NoSchedule"}]

2017-11-13 11:02 UTC, aanm requested changes
All of them should be something like:
```
$ git diff examples/kubernetes/cilium.yaml
diff --git a/examples/kubernetes/cilium.yaml b/examples/kubernetes/cilium.yaml
index 5dc15a0f0..665e4b090 100644
--- a/examples/kubernetes/cilium.yaml
+++ b/examples/kubernetes/cilium.yaml
@@ -75,6 +75,10 @@ spec:
         k8s-app: cilium
         kubernetes.io/cluster-service: "true"
       annotations:
+        # This annotation plus the CriticalAddonsOnly toleration makes
+        # cilium be a critical pod in the cluster, this ensures cilium
+        # gets priority scheduling.
+        scheduler.alpha.kubernetes.io/critical-pod: ''
         scheduler.alpha.kubernetes.io/tolerations: >-
           [{"key":"dedicated","operator":"Equal","value":"master","effect":"NoSchedule"}]
     spec:
@@ -194,6 +198,9 @@ spec:
       - effect: NoSchedule
         key: node.cloudprovider.kubernetes.io/uninitialized
         value: "true"
+        # Mark cilium's pod as critical for rescheduling
+      - key: CriticalAddonsOnly
+        operator: "Exists"
 ---
 kind: ClusterRole
 apiVersion: rbac.authorization.k8s.io/v1beta1
```

2017-11-13 11:29 UTC, tgraf commented
> +        # This annotation plus the CriticalAddonsOnly toleration makes
> +        # cilium be a critical pod in the cluster, this ensures cilium
> +        # gets priority scheduling.
> +        scheduler.alpha.kubernetes.io

I'm very much in favour of comments but then please describe what this actually means. What is priority scheduling? Either spell it our or a link to more information.

2017-11-13 20:44 UTC, manalibhutiyani reviewed
@tgraf : I can. add a reference to https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
if that helps?

2017-11-13 21:05 UTC, manalibhutiyani commented
@aanm : Made changes as per your review comments. Please take a look and let me know.

2017-11-14 00:40 UTC, tgraf approved these changes

2017-11-14 00:50 UTC, merged