helm: Allow configure the scrape interval for ServiceMonitor
cilium/cilium pull request #20240
Opened 2022-06-17 09:58 UTC by LawlietLi

helm: Allow configure the scrape interval for ServiceMonitor

Fixes: #19978

Signed-off-by: Li Yiheng <lyhutopi@gmail.com>

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

2022-06-17 12:37 UTC, kaworu requested changes
Thanks for the PR @LawlietLi! I have a minor nitpicking about quoting the interval values, but other than that LGTM :+1:

2022-06-17 12:37 UTC, kaworu commented on install/kubernetes/cilium/templates/cilium-agent/servicemonitor.yaml
> +    interval: {{ .Values.prometheus.serviceMonitor.interval }}
```suggestion
    interval: {{ .Values.prometheus.serviceMonitor.interval | quote }}
```

2022-06-17 12:37 UTC, kaworu commented on install/kubernetes/cilium/templates/cilium-operator/servicemonitor.yaml
> +    interval: {{ .Values.operator.prometheus.serviceMonitor.interval }}
```suggestion
    interval: {{ .Values.operator.prometheus.serviceMonitor.interval | quote }}
```

2022-06-17 12:37 UTC, kaworu commented on install/kubernetes/cilium/templates/hubble/servicemonitor.yaml
> +    interval: {{ .Values.hubble.metrics.serviceMonitor.interval }}
```suggestion
    interval: {{ .Values.hubble.metrics.serviceMonitor.interval | quote }}
```

2022-06-18 07:13 UTC, LawlietLi commented
> Thanks for the PR @LawlietLi! I have a minor nitpicking about quoting the interval values, but other than that LGTM 👍

Thanks, I've modified this.

2022-06-20 10:26 UTC, kaworu requested changes
Sorry @LawlietLi, we've recently made some changes around `values.yaml` and it is now generated from a "source" `values.yaml.tmpl` file (see [this PR](https://github.com/cilium/cilium/pull/20066) for more context). Could you please:

1. rebase your PR against the `master` branch
2. port the PR's changes to `install/kubernetes/values.yaml` to `install/kubernetes/values.yaml.tmpl`
3. run `make -C install/kubernetes`

Thank you in advance :pray:

2022-06-20 13:32 UTC, LawlietLi commented
I have rebased to master and regenerated `values.yaml`.

2022-06-20 22:56 UTC, tommyp1ckles approved these changes
lgtm, thanks!

2022-06-21 08:45 UTC, kaworu approved these changes
Thanks @LawlietLi!

2022-06-21 08:47 UTC, kaworu requested changes
[Travis-CI failure](https://app.travis-ci.com/github/cilium/cilium/jobs/574089637) is legit:

> HINT: to fix this, run 'make -C Documentation update-helm-values'

2022-06-21 10:23 UTC, kaworu reviewed
CI is passing, @LawlietLi can you squash all commits into the first one please?

2022-06-21 10:29 UTC, LawlietLi commented
OK, I will squash commits.

2022-06-21 14:12 UTC, kaworu approved these changes

2022-06-21 15:28 UTC, kaworu commented
No need for a full CI run here, marking as `ready-to-merge`.

2022-06-22 13:35 UTC, merged