daemon, option: Fix MTU when egress gateway is used
cilium/cilium pull request #20269
Opened 2022-06-21 16:44 UTC by pchaigno

When using the egress gateway in native routing mode, we setup a tunnel to send egressing traffic from pods to the gateway node. In that case, we therefore need to adjust the MTU for pod traffic to avoid dropping large packets. This pull request fixes that.

```release-note
Fix drop of large packets redirected through an egress gateway node when running in native routing mode.
```

2022-06-21 16:46 UTC, pchaigno commented
/test

2022-06-22 09:17 UTC, jibi approved these changes

2022-06-23 18:37 UTC, pchaigno commented
/test-gke

2022-06-27 06:10 UTC, julianwiedmann requested changes
Thanks! I wondered how we currently handle this :)

2022-06-27 06:10 UTC, julianwiedmann commented on pkg/option/config.go
> +// TunnelExists returns true if pod-to-pod traffic may go through a tunnel,
```suggestion
// TunnelExists returns true if inter-node traffic may go through a tunnel,
```

("pod-to-pod" doesn't apply to the EgressGW)

2022-06-28 14:16 UTC, julianwiedmann approved these changes
ta!

2022-06-28 14:25 UTC, pchaigno commented
/test

2022-07-04 21:55 UTC, pchaigno commented
Required tests are passing and we have two reviews. The change is fairly small and has already been tested by a user, so we can probably skip the CLI review. Marking ready to merge.

2022-07-05 11:24 UTC, merged