docs: Update clustermesh troubleshooting with more details
cilium/cilium pull request #20260
Opened 2022-06-21 10:28 UTC by sayboras

2022-07-11 14:55 UTC, joestringer requested changes
Looks good overall, just a couple of nits in the docs-structure given that some of the text towards the end is not shell-session output.

2022-07-11 14:55 UTC, joestringer commented on Documentation/operations/troubleshooting.rst
> +5. Run ``ip route`` or check your cloud provider router and verify that you have
Incidentally, with the fixed spacing above, these numbers should be numbered correctly with `#.`.

2022-07-11 14:55 UTC, joestringer commented on Documentation/operations/troubleshooting_clustermesh.rst
> + #. Validate that the ClusterMesh apiserver is initialized correctly
Should we suggest this " for each cluster"?

2022-07-11 14:55 UTC, joestringer commented on Documentation/operations/troubleshooting_clustermesh.rst
>         level=info msg="Initializing ClusterMesh routing" path=/var/lib/cilium/clustermesh/ subsys=daemon
:+1: would be good if we could validate the same via `cilium status` (first, in-pod but ideally from the clusterwide CLI). Maybe if this is not available, file an issue for it?

2022-07-11 14:55 UTC, joestringer commented on Documentation/operations/troubleshooting_clustermesh.rst
> +    remote cluster
Maybe end this with one `:`? Otherwise the grammar is not complete. Same with the next hunk in this patch below.

2022-07-11 14:55 UTC, joestringer commented on Documentation/operations/troubleshooting_clustermesh.rst
> +    .. code-block:: shell-session
These remaining blocks in this patch are not shell session output. Shell session highlights the `$` / `#` at start of line and colorizes the commands vs. the output. This is all just output of commands, so `::` is the best option for generic output with no special syntax highlighting.

2022-07-16 21:08 UTC, joestringer approved these changes
Some minor nits on shell formatting but otherwise LGTM, thanks.

2022-07-16 21:08 UTC, joestringer commented on Documentation/operations/troubleshooting_clustermesh.rst
> +    .. code-block:: shell-session
Maybe revert this change, this isn't shell-session output?

2022-07-16 21:08 UTC, joestringer commented on Documentation/operations/troubleshooting_clustermesh.rst
> +      point to a logical name representing the remote cluster::
Is the snippet here YAML? If yes, then we don't need to change it. If no, this is fine :+1:

2022-07-16 21:08 UTC, joestringer commented on Documentation/operations/troubleshooting_clustermesh.rst
> +           └  etcd: 1/1 connected, lease-ID=7c028201b53de660, lock lease-ID=7c028201b53de662, has-quorum=true: https://k8s-c2.mesh.cilium.io:2379 - 3.4.13 (Leader)
We aren't benefiting from the shell-session highlighting here either, given that there's no shell characters. `::` is fine to use here.

2022-07-28 08:23 UTC, sayboras commented
Mark as ready to merge after one last sanity check.

2022-07-28 14:04 UTC, merged