helm: disable the peer service by default
cilium/cilium pull request #20291
Opened 2022-06-23 13:56 UTC by rolinh

Commit 7d9c7e51f2ad122931efc885ef9fbc109af8b19c turns the peer service
into a Kubernetes service. The rationale for the change is that instead
of cross-mounting the Hubble Unix domain socket from the Cilium pod to
the Hubble Relay pod, Hubble Relay can directly query the Kubernetes
service to get information about Hubble peers. This is a security
improvement as it follows best-practices and streamlines the
installation process on platforms that strictly enforce SELinux policies
such as OpenShift.

However, this change is not minor and users have reported issues with
Hubble when upgrading from v1.11.x to v1.11.5. In order to follow the
principle of least astonishment and to avoid breaking a Hubble
deployment during a patch upgrade, this commit disables the peer service
by default such that the old behavior is retained, which shouldn't cause
any issue when upgrading. Users of platforms which need the peer service
can always explicitly enable it in v1.11.

2022-06-23 13:57 UTC, kaworu approved these changes

2022-06-23 13:58 UTC, kaworu requested changes
Actually, [CI failure](https://github.com/cilium/cilium/runs/7025019207?check_suite_focus=true) is legit:
> please run 'make -C install/kubernetes' and submit your changes

2022-06-23 15:04 UTC, gandro approved these changes

2022-06-23 15:52 UTC, kaworu approved these changes
@rolinh thanks!

2022-06-23 16:04 UTC, rolinh commented
/test

2022-06-23 18:54 UTC, nathanjsweet approved these changes

2022-06-24 10:44 UTC, rolinh commented
/test-backport-1.11

2022-06-27 10:20 UTC, merged