Add Peer Service to Cilium DS Port List
cilium/cilium pull request #20296
Opened 2022-06-23 19:18 UTC by nathanjsweet

For the sake of documenting the Peer Service port.

Signed-off-by: Nate Sweet <nathanjsweet@pm.me>

2022-06-24 05:27 UTC, sayboras commented on install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml
> +        - name: prometheus
the name port could be something else to avoid conflict with prometheus port.

2022-06-24 09:15 UTC, kaworu requested changes

2022-06-24 09:15 UTC, kaworu commented on install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml
> +          hostPort: {{ .Values.hubble.peerService.containerPort }}
[This CI failure](https://github.com/cilium/cilium/runs/7034928386?check_suite_focus=true) is legit:

> Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(DaemonSet.spec.template.spec.containers[0].ports[0]): missing required field "containerPort" in io.k8s.api.core.v1.ContainerPort

```suggestion
          containerPort: {{ .Values.hubble.peerService.targetPort }}
          hostPort: {{ .Values.hubble.peerService.targetPort }}
```

2022-06-24 16:20 UTC, nathanjsweet commented
Yikes, to the silly mistakes I made! Thanks for the reviews!

2022-06-24 20:59 UTC, tommyp1ckles approved these changes
lgtm

2022-06-26 05:08 UTC, sayboras commented
/test

2022-06-26 05:09 UTC, sayboras approved these changes
LGTM :heavy_check_mark:

2022-06-26 11:00 UTC, ldelossa approved these changes
LGTM

2022-06-26 11:01 UTC, ldelossa approved these changes

2022-06-27 08:40 UTC, kaworu approved these changes
Thanks @nathanjsweet!

2022-07-08 21:48 UTC, merged