v1.10:  helm: disable the peer service by default
cilium/cilium pull request #20290
Opened 2022-06-23 13:51 UTC by rolinh

Commit da1c1f8b3ff607844a84ec096ff9879931e5113c turns the peer service
into a Kubernetes service. The rationale for the change is that instead
of cross-mounting the Hubble Unix domain socket from the Cilium pod to
the Hubble Relay pod, Hubble Relay can directly query the Kubernetes
service to get information about Hubble peers. This is a security
improvement as it follows best-practices and streamlines the
installation process on platforms that strictly enforce SELinux policies
such as OpenShift.

However, this change is not minor and users have reported issues with
Hubble when upgrading from v1.10.x to v1.10.11. In order to follow the
principle of least astonishment and to avoid breaking a Hubble
deployment during a patch upgrade, this commit disables the peer service
by default such that the old behavior is retained, which shouldn't cause
any issue when upgrading. Users of platforms which need the peer service
can always explicitly enable it in v1.10.

2022-06-23 13:54 UTC, kaworu approved these changes

2022-06-23 14:02 UTC, kaworu requested changes
[this CI failure](https://github.com/cilium/cilium/runs/7024913126?check_suite_focus=true) should be addressed:
> please run 'make -C install/kubernetes' and submit your changes

2022-06-23 15:04 UTC, gandro approved these changes

2022-06-23 15:52 UTC, kaworu approved these changes

2022-06-23 16:04 UTC, rolinh commented
/test

2022-06-23 18:54 UTC, nathanjsweet approved these changes

2022-06-24 10:43 UTC, rolinh commented
/test-backport-1.10

2022-06-27 10:20 UTC, merged