v1.10 backports 2022-06-28
cilium/cilium pull request #20330
Opened 2022-06-28 17:30 UTC by pchaigno

* #19697 -- Unset `ImageReference` when updating Azure VMSS (@andrew-bulford-form3)
 * #19992 -- Add metric on datapath update latency due to FQDN IP updates (@rahulkjoshi)
 * #20158 -- nodediscovery: ensure we cache the nodeResource  (@odinuge)
 * #20208 -- Add a note about conflicting node CIDRs #20204 (@wokalski)
    - Trivial conflicts.
 * #20238 -- ci: provide CI images with unstripped binaries (@tklauser)
    - Couple conflicts. Not too bad but not trivial either. Needs to be checked.
 * #20289 -- docs(policy): add notes on DNS/L7 policies & Cilium agent availability (@raphink)
    - Trivial conflict on the spelling dictionnary.
 * #20325 -- jenkinsfiles: fix docker manifest inspect commands in GKE pipeline (@tklauser)
    - Trivial conflict.
 * #20314 -- Add ESP to firewall requirements in documentation for IPSec enabled C… (@Kikiodazie)
 * #20312 -- helm: Fix cluster-id arguments in clustermesh deployment (@sayboras)
    - Minor conflict.
 * #20194 -- [docs] Add training and support information to Getting Help (@lizrice)

Skipped due to conflicts:
 * #20072 -- datapath: Create sysctl `rp_filter` overwrite config on agent init (@dylandreimerink)

Not backporting due to [concerns](https://github.com/cilium/cilium/pull/19936/files#r908649338):
 * #19936 -- bug: Prevent CiliumIdentities from Being Deleted Improperly (@nathanjsweet)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 19697 19992 20158 20208 20072 20238 19936 20289 20325 20314 20312 20194; do contrib/backporting/set-labels.py $pr done 1.10; done
```

2022-06-28 17:37 UTC, nbusseneau approved these changes

2022-06-28 18:01 UTC, pchaigno commented
/test-backport-1.10

2022-06-28 18:37 UTC, nathanjsweet commented
[See this comment](https://github.com/cilium/cilium/pull/19936/files#r908819662) @pchaigno for my response to your concerns about #19936.

2022-06-28 19:09 UTC, raphink approved these changes
LGTM

2022-06-28 21:10 UTC, sayboras approved these changes
Looks good for my changes

2022-06-28 21:11 UTC, pchaigno commented
/test-backport-1.10

2022-06-29 08:29 UTC, tklauser requested changes
> * [ci: provide CI images with unstripped binaries #20238](https://github.com/cilium/cilium/pull/20238) -- ci: provide CI images with unstripped binaries (@tklauser)

There's one additional change needed so we don't overwrite `latest` images built from `master` branch, see comment inline.

>   * Trivial conflict on the spelling dictionnary.
> * [jenkinsfiles: fix docker manifest inspect commands in GKE pipeline #20325](https://github.com/cilium/cilium/pull/20325) -- jenkinsfiles: fix docker manifest inspect commands in GKE pipeline (@tklauser)

This one LGTM.

Thanks Paul!

2022-06-29 08:29 UTC, tklauser commented on .github/workflows/build-images-ci.yaml
> +            quay.io/${{ github.repository_owner }}/${{ matrix.name }}-ci:latest-unstripped
```suggestion
            quay.io/${{ github.repository_owner }}/${{ matrix.name }}-ci:v1.10-unstripped
```

2022-06-29 20:16 UTC, pchaigno commented on .github/workflows/build-images-ci.yaml
> +            quay.io/${{ github.repository_owner }}/${{ matrix.name }}-ci:latest-unstripped
Thanks! Fixed!

2022-06-29 20:17 UTC, pchaigno commented
/test-backport-1.10

2022-06-29 20:35 UTC, pchaigno commented
/test-backport-1.10

2022-06-30 07:57 UTC, tklauser approved these changes
Backport of #20238 now looks good as well. Thanks Paul!

2022-07-05 10:49 UTC, qmonnet commented
/mlh new-flake Cilium-PR-K8s-1.20-kernel-4.19

2022-07-05 10:55 UTC, qmonnet commented
/test-1.20-4.19

2022-07-05 17:06 UTC, qmonnet approved these changes
Most reviews are in, in particular all reviews for commits with non-trivial conflicts.

All tests passed.

We're good to go, thanks!

2022-07-05 17:07 UTC, merged