fix identity gc  to return correct  max/min id
cilium/cilium pull request #20361
Opened 2022-06-30 09:55 UTC by dkhachyan

Identity kvstore gc is not working with the following error:
```
Skipping this key" key=cilium/state/identities/v1/id/14142 reason="out of local cluster identity range [0,0]"
```
NewAllocatorForGC returns incorrect min/max ids.

2022-06-30 10:22 UTC, qmonnet requested changes
Thanks for your contribution!

The code change looks good to me.

Can you please:
- Add the `Signed-off-by:` tag at the end of your commit description (this is where it matters, not in the PR description)
- Add the relevant `Fixes` tag, also in your commit description:

  ```
  Fixes: 6f9fedd43cc3 ("operator: fix identity GC collection"
  ```
It would also be nice to indicate how you found this in  the description :)

2022-06-30 11:16 UTC, qmonnet requested changes
Thanks!

And sorry, more nitpicks :). Checkpatch complains that your `Signed-off` tag is not at the expected format (missing the angle brackets to recognise the email). Also please link to the commit with its SHA for the `Fixes` tag. Your commit title/description would be like this:

```
fix identity gc to return correct max/min id

Fixes: 6f9fedd43cc3 ("operator: fix identity GC collection")
Signed-off-by: Denis Khachyan <khachyanda@gmail.com>
```

2022-06-30 15:40 UTC, qmonnet approved these changes
Yes all good for me, thanks a lot!

2022-06-30 15:40 UTC, qmonnet commented
/test

2022-07-01 00:02 UTC, aanm approved these changes

2022-07-01 00:02 UTC, merged