ProcessFlow() is optional for metrics handlers
cilium/cilium pull request #20367
Opened 2022-06-30 22:59 UTC by chancez

The motivation behind this is is to support types that implement
OnDecodeFlows directly, where defining a ProcessFlow method would be
redundant.

Without this, these plugins would need to implement a no-op
ProcessFlow() method, because the logic for their metrics handlers will
live in OnDecodeFlows.

```release-note
ProcessFlow() is optional for metrics handlers
```

2022-07-01 06:54 UTC, kaworu requested changes
checkpatch CI complain seems legit
>   Warning: WARNING:REPEATED_WORD: Possible repeated word: 'is'
  The motivation behind this is is to support types that implement

2022-07-05 09:46 UTC, gandro approved these changes
The change overall looks fine to me. I do wonder if we should try to move the metrics plugin API towards `OnDecodedFlow` in general, and get rid of `ProcessFlow` completely (`ProcessFlow` predates `OnDecodedFlow`, but ultimately they do more or less the same thing).

2022-07-05 15:32 UTC, chancez commented
> The change overall looks fine to me. I do wonder if we should try to move the metrics plugin API towards `OnDecodedFlow` in general, and get rid of `ProcessFlow` completely (`ProcessFlow` predates `OnDecodedFlow`, but ultimately they do more or less the same thing).

Yeah, I think that would be ideal, but figured this approach would be easier to achieve in the short-term, and gives us time rethink how to do the metrics plugins a bit more.

2022-07-05 17:23 UTC, michi-covalent approved these changes

2022-07-08 13:27 UTC, joamaki approved these changes

2022-07-11 08:57 UTC, gandro approved these changes
Not sure why my review is pending again :thinking: Still looks good to me.

Edit: Something is wrong with GitHub. Here is the reviewer list _after_ I reviewed it:
![image](https://user-images.githubusercontent.com/50564/178227512-c5d54852-2524-4213-b039-41e7e7c19edf.png)

2022-07-13 14:12 UTC, kaworu approved these changes
Thanks @chancez, patch LGTM. Couple of remarks:

1. Any reason to use (generally) a `*Handlers` (i.e. a pointer) instead of `Handlers` (value)? Asking because `ProcessFlow` is defined on the value type, and I would prefer to be consistent.
2. `handlers.handlers` doesn't read well, but I don't have a good suggestion here.

2022-07-13 15:27 UTC, chancez commented
I think it was mostly because `NewHandlers` now returns an error and I typically use pointers when returning errors from functions and rely on Go to optimize away the pointers via escape analysis.

2022-07-29 13:17 UTC, aanm commented
/test

2022-08-02 09:17 UTC, gandro approved these changes

2022-09-02 17:05 UTC, chancez commented
Rebased and going to re-run tests.

2022-09-02 18:17 UTC, chancez commented
/test

2022-09-02 22:24 UTC, chancez commented
/mlh new-flake Cilium-PR-K8s-1.23-kernel-5.4

2022-09-05 08:42 UTC, gandro approved these changes
(I've already approved, but trying again in case GitHub finally fixed their bugs)

2022-10-25 17:25 UTC, chancez commented
/test

2022-11-29 00:27 UTC, michi-covalent approved these changes
sorry for the delay, LGTM 🚀

2022-11-29 00:40 UTC, michi-covalent approved these changes

2022-11-29 00:40 UTC, michi-covalent approved these changes

2022-11-29 08:51 UTC, kaworu commented
/test

2022-11-29 16:25 UTC, chancez commented
I probably need to rebase.

2022-11-29 20:26 UTC, chancez commented
/test

2022-11-30 17:42 UTC, chancez commented
ConformanceAKS failed on:
```
command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null [https://1.1.1.1:443](https://1.1.1.1/)" succeeded while it should have failed:
ℹ️  curl output:
 No flows recorded during action cloudflare-1111-0
```

And runtime tests are some panic that doesn't seem related:
```
	 [21:01:10]     testcase.go:144: Failed to start cilium agent: could not build arguments for function "github.com/cilium/cilium/daemon/cmd".glob..func2 (/home/vagrant/go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1627): failed to build promise.Promise[*github.com/cilium/cilium/daemon/cmd.Daemon]: could not build arguments for function "github.com/cilium/cilium/daemon/cmd".newDaemonPromise (/home/vagrant/go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1642): failed to build *agent.Controller: missing dependencies for function "github.com/cilium/cilium/pkg/bgpv1/agent".NewController (/home/vagrant/go/src/github.com/cilium/cilium/pkg/bgpv1/agent/controller.go:188): missing type: *option.DaemonConfig
	 [21:01:10] --- FAIL: TestControlPlane (0.00s)
	 [21:01:10]     --- FAIL: TestControlPlane/CNPStatusNodesGC (0.00s)
	 [21:01:10]     --- FAIL: TestControlPlane/IdentityGC (0.00s)
	 [21:01:10] panic: runtime error: invalid memory address or nil pointer dereference
	 [21:01:10] 	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	 [21:01:10] 	panic: runtime error: invalid memory address or nil pointer dereference
	 [21:01:10] [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x2a9217d]
	 [21:01:10] 
	 [21:01:10] goroutine 157 [running]:
	 [21:01:10] testing.tRunner.func1.2({0x2ea0160, 0x5743740})
	 [21:01:10] 	/usr/local/go/src/testing/testing.go:1396 +0x24e
	 [21:01:10] testing.tRunner.func1()
	 [21:01:10] 	/usr/local/go/src/testing/testing.go:1399 +0x39f
	 [21:01:10] panic({0x2ea0160, 0x5743740})
	 [21:01:10] 	/usr/local/go/src/runtime/panic.go:884 +0x212
	 [21:01:10] github.com/cilium/cilium/test/controlplane/suite.(*agentHandle).tearDown(0x0)
	 [21:01:10] 	/home/vagrant/go/src/github.com/cilium/cilium/test/controlplane/suite/agent.go:33 +0x1d
	 [21:01:10] github.com/cilium/cilium/test/controlplane/suite.(*ControlPlaneTest).StopAgent(0xc000cc3ea0)
	 [21:01:10] 	/home/vagrant/go/src/github.com/cilium/cilium/test/controlplane/suite/testcase.go:152 +0x25
	 [21:01:10] panic({0x2ea0160, 0x5743740})
	 [21:01:10] 	/usr/local/go/src/runtime/panic.go:884 +0x212
	 [21:01:10] github.com/cilium/cilium/test/controlplane/suite.(*operatorHandle).tearDown(0x0)
	 [21:01:10] 	/home/vagrant/go/src/github.com/cilium/cilium/test/controlplane/suite/operator.go:19 +0x19
	 [21:01:10] github.com/cilium/cilium/test/controlplane/suite.(*ControlPlaneTest).StopOperator(0xc000cc3ea0)
	 [21:01:10] 	/home/vagrant/go/src/github.com/cilium/cilium/test/controlplane/suite/testcase.go:190 +0x25
	 [21:01:10] runtime.Goexit()
	 [21:01:10] 	/usr/local/go/src/runtime/panic.go:522 +0x185
	 [21:01:10] testing.(*common).FailNow(0xc000d02000)
	 [21:01:10] 	/usr/local/go/src/testing/testing.go:871 +0x4c
	 [21:01:10] testing.(*common).Fatalf(0xc000d02000, {0x34cf06a?, 0x347902f?}, {0xc000d5de70?, 0xc000cad980?, 0x30?})
	 [21:01:10] 	/usr/local/go/src/testing/testing.go:955 +0x65
	 [21:01:10] github.com/cilium/cilium/test/controlplane/suite.(*ControlPlaneTest).StartAgent(0xc000cc3ea0)
	 [21:01:10] 	/home/vagrant/go/src/github.com/cilium/cilium/test/controlplane/suite/testcase.go:144 +0x1bb
	 [21:01:10] github.com/cilium/cilium/test/controlplane/identities.init.0.func1(0x0?)
	 [21:01:10] 	/home/vagrant/go/src/github.com/cilium/cilium/test/controlplane/identities/identity_gc.go:147 +0xea
	 [21:01:10] testing.tRunner(0xc000d02000, 0x3649998)
	 [21:01:10] 	/usr/local/go/src/testing/testing.go:1446 +0x10b
	 [21:01:10] created by testing.(*T).Run
	 [21:01:10] 	/usr/local/go/src/testing/testing.go:1493 +0x35f
	 [21:01:10] FAIL	github.com/cilium/cilium/test/controlplane	0.070s
	 [21:01:15] OK: 1 passed
```

2022-11-30 17:51 UTC, kaworu commented
Maybe https://github.com/cilium/cilium/pull/22352#issuecomment-1331868773 could help about the unrelated panic?

2022-11-30 20:25 UTC, chancez commented
/test

2022-12-01 22:31 UTC, merged