devenv: fix cilium opt with/without kv store
cilium/cilium pull request #20368
Opened 2022-07-01 08:50 UTC by sahid

The current algorithm was overriding options by setting CILIUM_OPT for
kv store and without.

Signed-off-by: Sahid Orentino Ferdjaoui <sahid.ferdjaoui@industrialdiscipline.com>

2022-07-01 15:40 UTC, aanm requested changes
>The current algorithm was overriding options by setting CILIUM_OPT for
kv store and without.

@sahid Thank you for the PR, however this is intentional since developers might want to quickly use one mode or the other without having to restart the development VM. To use one or the other the developer simply has to change the order of the `CILIUM_OPTS` in the `/etc/sysconfig/cilium` file.

2022-07-04 06:49 UTC, sahid commented
> > The current algorithm was overriding options by setting CILIUM_OPT for
> > kv store and without.
> 
> @sahid Thank you for the PR, however this is intentional since developers might want to quickly use one mode or the other without having to restart the development VM. To use one or the other the developer simply has to change the order of the `CILIUM_OPTS` in the `/etc/sysconfig/cilium` file.

Oh I see my mistake. Shouldn't we at least add small comment to let's developers know the usage?

2022-07-08 22:18 UTC, aanm commented
> > > The current algorithm was overriding options by setting CILIUM_OPT for
> > > kv store and without.
> > 
> > 
> > @sahid Thank you for the PR, however this is intentional since developers might want to quickly use one mode or the other without having to restart the development VM. To use one or the other the developer simply has to change the order of the `CILIUM_OPTS` in the `/etc/sysconfig/cilium` file.
> 
> Oh I see my mistake. Shouldn't we at least add small comment to let's developers know the usage?

@sahid feel free to add that comment instead of the changes proposed in this PR :)

2022-07-29 13:18 UTC, aanm approved these changes

2022-07-29 13:18 UTC, merged