docs: Add CLI installation for ServiceMesh
cilium/cilium pull request #20406
Opened 2022-07-06 09:28 UTC by sayboras

Please refer to individual commit for more details.

2022-07-06 15:21 UTC, aanm requested changes

2022-07-06 15:21 UTC, aanm commented on Documentation/gettingstarted/servicemesh/installation.rst
> +              --helm-set prometheus.enabled=true
Do we need `prometheus.enabled` here?

2022-07-06 16:56 UTC, ldelossa approved these changes

2022-07-07 14:07 UTC, aanm requested changes

2022-07-07 14:07 UTC, aanm commented on Documentation/gettingstarted/servicemesh/installation.rst
> +                --set-string extraConfig.enable-envoy-config=true
Setting `ingressController.enabled=true` already sets `enable-envoy-config=true` accordingly to https://github.com/cilium/cilium/blob/7463d9f12ba643d707f95a587ea03107ae46f0cb/install/kubernetes/cilium/templates/cilium-configmap.yaml#L210-L212

So we can remove this paragraph.

2022-07-07 14:11 UTC, sayboras commented on Documentation/gettingstarted/servicemesh/installation.rst
> +                --set-string extraConfig.enable-envoy-config=true
It's for the case that customer only wants to enable envoy config (e.g. for l7 management feature), but not the ingress controller. IIRC, the original drive is to limit RBAC clusterrole on secrets for cluster operator.

2022-07-08 22:00 UTC, aanm approved these changes

2022-07-11 09:10 UTC, merged