docs: Add troubleshooting docs for Ingress
cilium/cilium pull request #20428
Opened 2022-07-07 13:39 UTC by sayboras

This commit is to add troubleshooting steps for Ingress resources, the
similar step can be performed for CiliumClusterwideEnvoyConfig and
CiliumEnvoyConfig resources as well. I have listed down the common issue
and how to check for each request hoop, will improve along the way.

Signed-off-by: Tam Mach <tam.mach@cilium.io>

2022-07-08 09:02 UTC, qmonnet requested changes
Thanks! The documentation looks good, I've got some minor comments on the grammar.

I note this is a long addition to the troubleshooting page, maybe we should split it at some point. But this is beyond the scope of your PR.

2022-07-08 09:02 UTC, qmonnet commented on Documentation/operations/troubleshooting_servicemesh.rst
> +    documentation from your respective cloud provider.
```suggestion
 #. Validate that the Load Balancer service has either an external IP or FQDN assigned.
    If it's not available after a long time, please check the Load Balancer related
    documentation from your respective cloud provider.
```

2022-07-08 09:02 UTC, qmonnet commented on Documentation/operations/troubleshooting_servicemesh.rst
> +    originating from the Cilium Ingress controller.
```suggestion
 #. Check if there is any warning or error message while Cilium is trying to provision
    the ``CiliumEnvoyConfig`` resource. This is unlikely to happen for CEC resources
    originating from the Cilium Ingress controller.
```

2022-07-08 09:02 UTC, qmonnet commented on Documentation/operations/troubleshooting_servicemesh.rst
> +It's the best to have ``debug`` and ``debug-verbose`` enabled with below values. Kindly
```suggestion
It's best to have ``debug`` and ``debug-verbose`` enabled with below values. Kindly
```

2022-07-08 09:02 UTC, qmonnet commented on Documentation/operations/troubleshooting_servicemesh.rst
> +    the related CiliumNetworkPolicy for underlying pods.
```suggestion
    The Ingress traffic is always allowed to pass through Cilium, regardless of
    the related CiliumNetworkPolicy for underlying pods.
```

2022-07-08 09:02 UTC, qmonnet commented on Documentation/operations/troubleshooting_servicemesh.rst
> +backend service.
```suggestion
The request normally traverses from LoadBalancer service to pre-assigned port of your
node, then gets forwarded to the Cilium Envoy proxy, and finally gets proxied to the actual
backend service.
```

2022-07-08 09:02 UTC, qmonnet commented on Documentation/operations/troubleshooting_servicemesh.rst
> +    request to localhost.
```suggestion
 #. The second step could be checked by connecting with SSH to your underlying host, and sending a
    request to localhost on the relevant port:
```

2022-07-08 09:02 UTC, qmonnet commented on Documentation/operations/troubleshooting_servicemesh.rst
> +Internally, the Cilium Ingress controller will create one Load Balancer service, one CiliumEnvoyConfig
```suggestion
Internally, the Cilium Ingress controller will create one Load Balancer service, one ``CiliumEnvoyConfig``
```

2022-07-08 09:02 UTC, qmonnet commented on Documentation/operations/troubleshooting_servicemesh.rst
> +the same steps can be applied to manually configured CiliumEnvoyConfig resources as well.
```suggestion
the same steps can be applied to manually configured ``CiliumEnvoyConfig`` resources as well.
```

2022-07-08 09:02 UTC, qmonnet commented on Documentation/operations/troubleshooting_servicemesh.rst
> +    Alternatively, you can also send request directly to Envoy proxy port. For Ingress, the proxy port is randomly
```suggestion
    Alternatively, you can also send a request directly to the Envoy proxy port. For Ingress, the proxy port is randomly
```

2022-07-08 09:02 UTC, qmonnet commented on Documentation/operations/troubleshooting_servicemesh.rst
> +        $  kubectl logs -f -n kube-system ds/cilium --timestamps| egrep "envoy|proxy"
```suggestion
        $  kubectl logs -f -n kube-system ds/cilium --timestamps | egrep "envoy|proxy"
```

2022-07-08 09:02 UTC, qmonnet commented on Documentation/operations/troubleshooting_servicemesh.rst
> +    If you see the response similar to above, it means that the request is being
```suggestion
    If you see a response similar to the above, it means that the request is
```

2022-07-08 09:02 UTC, qmonnet commented on Documentation/operations/troubleshooting_servicemesh.rst
> +    correctly.
“Assuming”, and this sentence is not correct, please fix it

2022-07-08 09:02 UTC, qmonnet commented on Documentation/operations/troubleshooting_servicemesh.rst
> +    (EDS) is having name following the convention ``<namespace>/<service-name>:<port>``.
```suggestion
    Double-check whether your backend service is up and healthy. The Envoy Discovery Service
    (EDS) has a name that follows the convention ``<namespace>/<service-name>:<port>``.
```

2022-07-09 05:55 UTC, sayboras commented
Request reviews from others, who might have more insights.

2022-07-12 08:54 UTC, youssefazrak commented on Documentation/operations/troubleshooting_servicemesh.rst
> +        $ LB_IP=$(kg ingress basic-ingress -o json | jq '.status.loadBalancer.ingress[0].ip' | jq -r .)
small nit: `kg` --> `kubectl get`

2022-07-12 10:21 UTC, qmonnet approved these changes
Thanks!

2022-07-12 12:23 UTC, merged