fix subnet_id label value is empty
cilium/cilium pull request #20449
Opened 2022-07-09 04:02 UTC by wu0407

fix subnet_id label value is empty in `cilium_operator_ipam_allocation_ops` and `cilium_operator_ipam_interface_creation_ops`

Signed-off-by: xiaoqing <xiaoqingnb@gmail.com>

Please ensure your pull request adheres to the following guidelines:

- [*] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [*] All code is covered by unit and/or runtime tests where feasible.
- [ *] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ *] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #20431

```release-note

```

2022-07-12 16:32 UTC, christarazi approved these changes
Thanks for the PR! Change looks good to me. Could you update the release-note in the PR description to provide users with a impact of the change so that we can properly inform users upon upgrade?

2022-07-15 05:44 UTC, christarazi requested changes
Holding for the above to be addressed

2022-07-15 15:33 UTC, wu0407 commented
> Holding for the above to be addressed

release node is done @christarazi

2022-07-15 17:44 UTC, christarazi approved these changes

2022-07-18 05:14 UTC, wu0407 commented
sorry, I copy you commit message and push a empty commit

2022-07-29 13:36 UTC, merged