docs: fix a Links documentation style guide error
cilium/cilium pull request #20460
Opened 2022-07-11 10:40 UTC by Kikiodazie

Signed-off-by: Divine Odazie <dodazie@gmail.com>

While using the style guide, I noticed an error that set me back a few mins on the **Links** style guide as annotated in the screenshot.

in the **Prefer (but see previous item)**: code block the underscore is put in the wrong place.

![annotely_image](https://user-images.githubusercontent.com/42554056/178247636-eace6b0f-2d54-4c56-a475-02d46fa95cf7.png)

2022-07-12 11:11 UTC, qmonnet requested changes
Ah, they really _were_ examples to avoid :laughing: 

Thanks! Could you please add the following tag to your commit description to indicate what commit introduced the error?

```
Fixes: 60c5759b4b87 ("docs: add style guidelines for contributing to the documentation")
```

(Just above your `Signed-off-by`)

2022-07-12 11:51 UTC, Kikiodazie commented
> Ah, they really _were_ examples to avoid 😆
> 
> Thanks! Could you please add the following tag to your commit description to indicate what commit introduced the error?
> 
> ```
> Fixes: 60c5759b4b87 ("docs: add style guidelines for contributing to the documentation")
> ```
> 
> (Just above your `Signed-off-by`)

Anything to get a PR merged 😆😆😆. 

Will add to the commit description right away. Thanks, Quentin.

2022-07-12 11:55 UTC, Kikiodazie commented
I have implemented the requested change.

2022-07-12 12:35 UTC, qmonnet approved these changes
Thanks!

2022-07-13 17:08 UTC, aditighag approved these changes

2022-07-14 10:44 UTC, merged