WIP (DO NOT MERGE) Issue 2008 Feature Request: Add option to disable loadbalancing
cilium/cilium pull request #2048
Opened 2017-11-15 21:24 UTC by manalibhutiyani

When integrating with higher level orchestration systems, we currently
don't allow to opt out of performing load balancing operations.
We need to disable translating Kubernetes services to Cilium services,
if load-balancing is disabled.

Fixes issue #2008

Signed-off-by: Manali Bhutiyani manali@covalent.io

```release-note
Disable translating Kubernetes services to Cilium services,
if load-balancing is disabled.
```

2017-11-16 10:41 UTC, tgraf requested changes
This needs a new flag. The existing flag is for north south traffic. We don't want to enable that by default but we want to enable east-west by default.

I propose we make this very specific and name it:
`--disable-k8s-services`

2017-11-16 21:21 UTC, manalibhutiyani commented
@tgraf @aanm Made the changes as per review comments. Added a new flag `--disable-k8s-services` Please take a look.

2017-11-16 23:10 UTC, ianvernon commented
Why not add the check to `daemon/k8s_watcher.go:EnableK8sWatcher`? Within that function:

```
if !k8s.IsEnabled()  || viper.GetBool("disable-k8s-services") == true{
		return nil
}
```

2017-11-16 23:12 UTC, manalibhutiyani commented
My understanding was that in EnableK8sWatcher  we still need to execute `cache.ResourceEventHandlerFuncs{
			AddFunc:    d.addK8sServiceV1,
			UpdateFunc: d.updateK8sServiceV1,
			DeleteFunc: d.deleteK8sServiceV1,
		},`  for headless services feature.

2017-11-16 23:25 UTC, ianvernon commented
> My understanding was that in EnableK8sWatcher we still need to execute cache.ResourceEventHandlerFuncs{ AddFunc: d.addK8sServiceV1, UpdateFunc: d.updateK8sServiceV1, DeleteFunc: d.deleteK8sServiceV1, }, for headless services feature.

Given that this is the case, the flag name is not clear; it should be something like `--disable-k8s-loadbalancing` (?)

2017-11-16 23:28 UTC, ianvernon commented on daemon/k8s_watcher.go
> +	// K8s service to a cilium service.
Per our offline discussion / my other comment, given that we still want headless services to be enabled(?), this flag should be renamed and the documentation for it updated accordingly. 

To confirm, we should only disable Cilium management of Kubernetes LoadBalancing services, not headless services @tgraf @nebril ?

2017-11-16 23:28 UTC, ianvernon commented on daemon/main.go
> +		"access-log", "", "Path to access log of supported L7 requests observed")
Good catch :)

2017-11-17 00:24 UTC, tgraf commented
> My understanding was that in EnableK8sWatcher we still need to execute cache.ResourceEventHandlerFuncs{ AddFunc: d.addK8sServiceV1, UpdateFunc: d.updateK8sServiceV1, DeleteFunc: d.deleteK8sServiceV1, }, for headless services feature.

We need to parse k8s services for service based policy enforcement

2017-11-17 16:57 UTC, tgraf approved these changes

2017-11-17 16:58 UTC, tgraf commented
> Per our offline discussion / my other comment, given that we still want headless services to be enabled(?), this flag should be renamed and the documentation for it updated accordingly.
> 
> To confirm, we should only disable Cilium management of Kubernetes LoadBalancing services, not headless services @tgraf @nebril ?

I like the name `k8s-services` because loadbalancer has a different meaning in k8s. We really disable services. We only keep record so we can still enable policy enforcement based on service information. The purpose of the flag is to disable performing service datapath work.

2017-11-17 16:58 UTC, merged