Fix:Added the declaration of license to the go file
cilium/cilium pull request #20502
Opened 2022-07-13 12:30 UTC by yulng

Added the declaration of license to the go file

2022-07-13 19:12 UTC, christarazi requested changes
Thanks for the PR. Please squash all of the commits into one and please amend the final commit like so

```
git commit --amend -s
```

to properly sign it off.

Please also retitle the final commit to something like

```
test: Add missing declaration of license
```

2022-07-13 19:57 UTC, joestringer requested changes
Thanks, we missed a couple of these. Just needs a couple of things fixed up, thanks.

2022-07-13 19:57 UTC, joestringer commented on test/ginkgo-ext/junit_reporter.go
>  Junit Reference:
Given that the lines here seem to indicate that this file is copied from another project, I don't think that we should relicense or claim copyright over the lines when we are reusing the code from another project.

2022-07-13 19:57 UTC, joestringer commented on test/logger/logs.go
> +	"github.com/sirupsen/logrus"
Imports are typically set into three categories separated by whitespace: First, standard library imports, second external imports from other projects, and third imports within the codebase. As such, the linter is complaining. Please revert this hunk here.

2022-07-13 19:59 UTC, joestringer commented on test/ginkgo-ext/junit_reporter.go
>  Junit Reference:
Practically I think the thing to do would be to add MIT and the original copyright holders here.

2022-07-13 20:00 UTC, joestringer commented on test/ginkgo-ext/junit_reporter.go
>  Junit Reference:
If there are Cilium-specific changes, we can add the `Copyright Authors of Cilium` line as well.

2022-07-17 14:10 UTC, closed without merging

2022-07-17 14:11 UTC, yulng commented
later submit