bpf: Tests for session affinity and bpf-lb-sock-hostns-only
cilium/cilium pull request #20615
Opened 2022-07-21 10:05 UTC by dylandreimerink

Has tests for (https://github.com/cilium/cilium/issues/20160):
* Tests NodePort with sessionAffinity
* Checks connectivity when skipping socket lb in pod ns

Adopted from #20423

2022-07-25 13:24 UTC, julianwiedmann commented on bpf/tests/session_affinity_test.c
> +	if (!eh) return TEST_ERROR;
All these same-line `return`s make my brain hurt :).

2022-07-25 13:28 UTC, dylandreimerink commented on bpf/tests/session_affinity_test.c
> +	if (!eh) return TEST_ERROR;
Agreed, we can move the returns to the next line

2022-07-25 14:18 UTC, julianwiedmann commented
>  bpf: Add BPF unit test for bpf-lb-sock-hostns-only
> 
> Tests that the socket lb is skipped if ENABLE_SOCKET_LB_HOST_ONLY
> is set and the packet is **not** from host namespace.

2022-07-25 14:21 UTC, julianwiedmann requested changes
Looks good, ty! But please do add the `lb6_select_backend_id()` for `LB_SELECTION_FIRST`.

2022-07-25 14:21 UTC, julianwiedmann commented on bpf/lib/lb.h
> +lb4_select_backend_id(struct __ctx_buff *ctx,
Think we should also add an IPv6 variant.

2022-07-25 14:21 UTC, julianwiedmann commented on bpf/include/bpf/ctx/xdp.h
> +	 * which leads to "pointer arithmetict on pkt_end prohibited"
```suggestion
	 * which leads to "pointer arithmetic on pkt_end prohibited"
```

2022-07-28 13:21 UTC, nebril approved these changes
`test` bits LGTM

2022-07-29 09:51 UTC, julianwiedmann approved these changes
Thank you!

2022-07-29 10:30 UTC, dylandreimerink commented
/test

2022-07-29 12:50 UTC, dylandreimerink commented
Both the `k8s-1.16-kernel-4.9 (test-1.16-4.9)` and `Cilium L4LB XDP (ci-l4lb)` appear to be flakes since these same tests are failing on other branches as well, the rest of the tests are all green.

2022-07-29 12:57 UTC, merged