docs: second set of video contents added
cilium/cilium pull request #20623
Opened 2022-07-21 14:46 UTC by Kikiodazie

This PR adds the first set of video content (eCHO episodes and some talks) to the docs. 

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note

```

2022-07-28 14:04 UTC, qmonnet requested changes
Thanks! Some fixes and suggestions.

Can you please fold the spell list updates into the relevant commits?

2022-07-28 14:04 UTC, qmonnet commented on Documentation/gettingstarted/local-redirect-policy.rst
> +  Aside from this document, you can watch a video explanation of Cilium's Local Redirect Policy on `eCHO episode 39 <https://www.youtube.com/watch?v=BT_gdlhjiQc&t=176s>`__.
Missing episode title?

2022-07-28 14:04 UTC, qmonnet commented on Documentation/gettingstarted/host-firewall.rst
> +  You can also watch a video of the Cilium's host firewall in action on `eCHO Episode 40: Cilium Host Firewall <https://www.youtube.com/watch?v=GLLLcz398K0&t=288s>`__.
```suggestion
  You can also watch a video of Cilium's host firewall in action on
  `eCHO Episode 40: Cilium Host Firewall <https://www.youtube.com/watch?v=GLLLcz398K0&t=288s>`__.
```

2022-07-28 14:04 UTC, qmonnet commented on Documentation/gettingstarted/cni-chaining-aws-cni.rst
> +  To help you migrate, you can watch two Principal Engineers at Meltwater talk about `how they migrated
Repetitions of “Cilium” and “migrat*”. Could be at least “To help you with the process”.

Also “some advanced features” -> just “advanced features”? The word “some” doesn't bring anything here.

2022-07-28 14:04 UTC, qmonnet commented on Documentation/gettingstarted/bandwidth-manager.rst
> +  For more insights on Cilium's bandwidth manager, check out this `KubeCon talk on Better Bandwidth Management with eBPF <https://youtu.be/QTSS6ktK8hY>`__.
youtube.com URL, for consistency with the other additions

2022-07-28 14:04 UTC, qmonnet commented on FURTHER_READINGS.rst
> +  `Video <https://youtu.be/UcsEVnFtrLY>`__
youtube.com URLs please, for consistency with the other links below.

2022-08-01 11:40 UTC, Kikiodazie commented on Documentation/gettingstarted/local-redirect-policy.rst
> +  Aside from this document, you can watch a video explanation of Cilium's Local Redirect Policy on `eCHO episode 39 <https://www.youtube.com/watch?v=BT_gdlhjiQc&t=176s>`__.
I have made the edit. Do check it out.

2022-08-01 11:41 UTC, Kikiodazie commented on Documentation/gettingstarted/host-firewall.rst
> +  You can also watch a video of the Cilium's host firewall in action on `eCHO Episode 40: Cilium Host Firewall <https://www.youtube.com/watch?v=GLLLcz398K0&t=288s>`__.
Applied. Thank you.

2022-08-01 11:53 UTC, Kikiodazie commented on Documentation/gettingstarted/cni-chaining-aws-cni.rst
> +  To help you migrate, you can watch two Principal Engineers at Meltwater talk about `how they migrated
Made an edit. Please to check it out.

2022-08-01 11:56 UTC, Kikiodazie commented on Documentation/gettingstarted/bandwidth-manager.rst
> +  For more insights on Cilium's bandwidth manager, check out this `KubeCon talk on Better Bandwidth Management with eBPF <https://youtu.be/QTSS6ktK8hY>`__.
Made the edit. Thank you.

2022-08-01 12:07 UTC, Kikiodazie commented on FURTHER_READINGS.rst
> +  `Video <https://youtu.be/UcsEVnFtrLY>`__
Fixed all.

2022-08-01 14:54 UTC, qmonnet requested changes
Nearly all good, thanks for the changes!

Can you please fold the spell list updates into the relevant commits, as suggested in the previous review?

2022-08-01 14:54 UTC, qmonnet commented on Documentation/gettingstarted/cni-chaining-aws-cni.rst
> +  To help you with the process, you can watch two Principal Engineers at Meltwater talk about `how they migrated
trailing spaces at the end lines

2022-08-01 16:00 UTC, Kikiodazie commented on Documentation/gettingstarted/cni-chaining-aws-cni.rst
> +  To help you with the process, you can watch two Principal Engineers at Meltwater talk about `how they migrated
Fixed. Thank you.

2022-08-01 16:00 UTC, Kikiodazie commented
> Nearly all good, thanks for the changes!
> 
> Can you please fold the spell list updates into the relevant commits, as suggested in the previous review?

Ohh. So sorry I missed the spell list comment earlier. Fixed. Please do check it out.

2022-08-01 21:08 UTC, christarazi reviewed
The changes are good, thanks for the PR!

I am wondering though: do we really need 6 commits to add links to the docs? I think it makes sense to squash these altogether.

2022-08-02 08:36 UTC, qmonnet approved these changes
Looks all good, thanks a lot!

> I am wondering though: do we really need 6 commits to add links to the docs? I think it makes sense to squash these all together.

Could have been one commit, but Divine asked beforehand (to Bill, Liz and myself I think, during a GSoD sync-up) if one commit per link was fine and we agreed on that. Let's keep this for this PR at least, unless you strongly object @christarazi.

2022-08-02 17:30 UTC, joestringer approved these changes

2022-08-02 17:31 UTC, joestringer commented
Split commits is fine, it might even make it easier to rebase now that there's a conflict.

2022-08-02 20:36 UTC, christarazi commented
@qmonnet Fine with me :heavy_check_mark:

2022-08-02 20:36 UTC, christarazi approved these changes

2022-08-19 13:34 UTC, qmonnet commented
@Kikiodazie Can you please rebase this PR to address the conflicts?

2022-08-19 20:27 UTC, Kikiodazie commented
> @Kikiodazie Can you please rebase this PR to address the conflicts?

Done @qmonnet. So sorry for getting to this late. Was Away from my keyboard all day.

2022-08-20 11:32 UTC, merged

2022-08-20 19:41 UTC, borkmann commented
@Kikiodazie Thanks! Could you also add https://youtu.be/OIyPm6K4ooY to the kube-proxy free guide?

2022-08-22 00:29 UTC, Kikiodazie commented
> @Kikiodazie Thanks! Could you also add https://youtu.be/OIyPm6K4ooY to the kube-proxy free guide?

Thank you @borkmann. I have already added this video in the docs via this commit https://github.com/cilium/cilium/pull/20480/commits/a157dfebdefc97b6c9631b3abdb9a5dd5d535570, but i can also add it to the to the kube-proxy free guide. 

Please where do you think its best I add it in the kube-proxy free guide?