value for overriding the namespace in the helm chart added
cilium/cilium pull request #20828
Opened 2022-08-08 15:00 UTC by basit9958

Signed-off-by: Basit Hasan <hasanbasit13@gmail.com>

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #20511 

```release-note

```

2022-08-08 15:19 UTC, gandro requested changes
Thanks for the PR. This however does not solve the linked issue, since the value is not used by any component.

You will have to introduce a Helm helper similar to `common.names.namespace` the Bitnami charts and more importantly use it for the `namespace:` property of every Kubernetes resource we deploy in our charts. I would propose `cilium.namespace` as the name of the helper.

https://github.com/bitnami/charts/blob/ab3db922c645f313f547a227b77f2f3b06c4a7ed/bitnami/common/templates/_names.tpl#L54-L63

I personally also prefer `.Values.namespaceOverride` over `.Values.namespace`, but that's up for debate.

2022-08-22 10:35 UTC, gandro requested changes
Thanks for addressing the above feedback. Still some more changes needed.

2022-08-22 10:35 UTC, gandro commented on install/kubernetes/cilium/templates/cilium-agent/clusterrolebinding.yaml
> +  namespace: {{ cilium.namespace }}
This looks incorrect unfortunately. To use the defined template, you'll have to call include: https://helm.sh/docs/chart_template_guide/named_templates/#the-include-function

2022-09-15 10:36 UTC, pchaigno commented
Switching to draft while the review is being addressed.

2022-10-30 02:16 UTC, closed without merging