docs: Clarify identity table for reserved identities
cilium/cilium pull request #20832
Opened 2022-08-08 22:44 UTC by joestringer

Reserved identities take up the first 255 values (per `pkg/identity/numericidentity.go`), as already described in this document. Add these to the table for completeness. I didn't bother to fully explain this point for clustermesh but in practice this range (`0x00xx0001`->`0x00xx00FF`) is reserved in each cluster. These are not synchronized across all clusters.

2022-08-09 08:36 UTC, qmonnet requested changes

2022-08-09 08:36 UTC, qmonnet commented on Documentation/internals/security-identities.rst
> +   0x00000100 - 0x0000FFFF (1           to 2^16 - 1)        => cluster-local identities
```suggestion
   0x00000100 - 0x0000FFFF (2^8         to 2^16 - 1)        => cluster-local identities
```

2022-08-09 17:33 UTC, joestringer commented on Documentation/internals/security-identities.rst
> +   0x00000100 - 0x0000FFFF (1           to 2^16 - 1)        => cluster-local identities
Woops, thanks.

2022-08-10 08:54 UTC, qmonnet approved these changes
Thanks!

2022-08-10 14:47 UTC, merged