don't merge stderr into iptable stdout
cilium/cilium pull request #20895
Opened 2022-08-12 22:01 UTC by liuyuan10

runProgCombinedOutput merges stdout and stderr of iptables into a single
string and parse iptables rules out from it. But stderr is never rules but warnings/errors. For example, stderr can be "# Warning: iptables-legacy
tables present, use iptables-legacy-save to see them"

This commit changes it to use exec.Output but merge stderr into err.

Fixes: #20894

Signed-off-by: André Martins <andre@cilium.io>

```release-note
put stderr of iptables command into error instead of merging into stdout
```

2022-08-12 22:03 UTC, aanm requested changes
@liuyuan10 I think you have signed the commit with the wrong name :confused:

2022-08-12 22:20 UTC, liuyuan10 commented
thanks for catching that. I was doing copy paste with my eye covered

2022-08-16 13:11 UTC, ldelossa approved these changes
Looks good to me, you may want to use the errors package to discern the error type, see comment.

2022-08-16 13:11 UTC, ldelossa commented on pkg/command/exec/exec.go
> +		exitErr, ok := err.(*exec.ExitError)
Could this use  `errors.Is()` or `errors.As()` instead ?

2022-08-16 17:44 UTC, liuyuan10 commented on pkg/command/exec/exec.go
> +		exitErr, ok := err.(*exec.ExitError)
done. thanks for letting me know these useful helpers.

2022-08-16 23:18 UTC, nathanjsweet approved these changes

2022-08-17 06:36 UTC, NikAleksandrov approved these changes

2022-08-18 16:49 UTC, liuyuan10 commented
@aanm can we merge it?

2022-08-18 21:02 UTC, aanm approved these changes

2022-08-18 21:02 UTC, aanm commented
/test

2022-08-20 11:33 UTC, merged

2022-08-22 16:46 UTC, joestringer commented
Is this a bugfix? Should we backport at least to v1.12?

2022-08-22 17:06 UTC, liuyuan10 commented
I would prefer a backport given it's a low-risk change and indeed it helped fixing #20894 for us

2022-08-26 06:14 UTC, julianwiedmann commented
https://github.com/cilium/cilium/pull/19693 went back to `v1.10` and `v1.11`, let's unbreak those as well.