mount host /boot into cilium-agent container
cilium/cilium pull request #21113
Opened 2022-08-27 12:12 UTC by agrevtcev

mount host /boot into cilium-agent container, as it required to run `bpftool -j feature probe` during kernel feature probing

Fixes: #20981

2022-08-29 08:41 UTC, kaworu commented
Thank you for the PR @agrevtcev! Please take a look at [this comment](https://github.com/cilium/cilium/pull/21113#issuecomment-1229182339) about `Signed-off-by`. I'm also adding @aanm as reviewer since he seems to have context about the issue.

2022-08-29 12:12 UTC, gandro commented on install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml
> +        # Required to run 'bpftool -j feature probe'
Also, since this is disabled by default, can we make both added sections conditional on `{{ if .Values.bpfClockProbe }}`? Thanks!

2022-08-29 13:57 UTC, aanm requested changes

2022-08-29 13:57 UTC, aanm commented on install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml
> +        # Required to run 'bpftool -j feature probe'
@gandro what is disabled by default? I would suggest to enable mounting `/boot` by default with a helm option to disabling it if necessary.

2022-08-29 14:40 UTC, gandro commented on install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml
> +        # Required to run 'bpftool -j feature probe'
My understanding is that access to /boot is only needed if (and only if) `.Values.bpfClockProbe=true`.  That's why I would make it conditional on that.

If `.Values.bpfClockProbe` is false (which it seems to be by default on recent versions), then there is no point in mounting /boot.

2022-08-29 14:44 UTC, gandro commented on install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml
> +        # Required to run 'bpftool -j feature probe'
Oh, I just checked the source and it seems the check that requires /boot is done unconditionally (i.e. even if bpfClockProbe is false). In which case my point is moot.

2022-08-30 12:58 UTC, gandro commented on install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml
> +        # Required to run 'bpftool -j feature probe'
@aanm You requested changes. What changes are you requesting? Adding a independent Helm flag to make the boot mount conditional?

2022-08-30 14:14 UTC, aanm commented on install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml
> +        # Required to run 'bpftool -j feature probe'
> @aanm You requested changes. What changes are you requesting? Adding a independent Helm flag to make the boot mount conditional?

@gandro correct.

2022-08-30 14:15 UTC, aanm requested changes
@agrevtcev please see https://github.com/cilium/cilium/pull/21113/files#r958447909

2022-08-30 14:33 UTC, agrevtcev commented on install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml
> +        # Required to run 'bpftool -j feature probe'
@aanm are you sure it's necessary? It seems we are running initClockSourceOption() unconditionally, despite the .Values.bpfClockProbe value.
https://github.com/cilium/cilium/blob/27700b02032af349b67d97789575a1533466686a/daemon/cmd/daemon_main.go#L1413

2022-08-30 14:44 UTC, aanm commented on install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml
> +        # Required to run 'bpftool -j feature probe'
@agrevtcev yes, not everyone might want to mount `/boot` into Cilium DaemonSet even if it is read-only so it does make sense to mark it as optional. That function is running uncoditionally but we can do as a follow up to add a flag to specify that value for users that don't want to mount `/boot`

2022-08-30 15:15 UTC, gandro commented
Thanks for the updated version. Please run `make -C install/kubernetes` and `make -C Documentation helm-values.rst` to include the new value in the auto-generated docs.

2022-08-31 09:47 UTC, aanm approved these changes

2022-08-31 09:48 UTC, aanm requested changes
Changes LGTM, just please squash all commits into one. Thank you!

2022-08-31 12:03 UTC, gandro approved these changes

2022-08-31 12:13 UTC, kaworu requested changes
Thanks for the update @agrevtcev! The diff LGTM, but CI is complaining for a couple of things:

1. Please run `Documentation/update-spelling_wordlist.sh hostBoot mountHostBoot` to fix [this failure](https://github.com/cilium/cilium/runs/8112924823?check_suite_focus=true),
2. Replace the commit message's `Signed-off-by` line with `Signed-off-by: Alexey Grevtcev <alexey@grevtcev.ru>` (notice the `<` and `>` enclosing the email address) to fix [this failure](https://github.com/cilium/cilium/runs/8112921045?check_suite_focus=true),
3. Finally, rebase and squash your changes into one commit.

Thank you! :pray:

2022-08-31 15:16 UTC, kaworu commented
[Travis-CI failure](https://app.travis-ci.com/github/cilium/cilium/jobs/581432786) looks unrelated but legit:

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃   FAIL  package: github.com/cilium/cilium/pkg/k8s   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

--- FAIL: Test (3.73s)

----------------------------------------------------------------------

FAIL: rule_translate_test.go:198: K8sSuite.TestGenerateToCIDRFromEndpoint

rule_translate_test.go:249:
    c.Assert(prefixesToAllocate[0].String(), Equals, epIP1Prefix.String())
... obtained string = "10.1.1.2/32"
... expected string = "10.1.1.1/32"
```

@aanm do you have context since it's from the k8s package?

2022-08-31 15:53 UTC, aanm commented
@kaworu yes, it's this flake https://github.com/cilium/cilium/issues/21145

2022-09-01 13:53 UTC, aanm commented
/test

2022-09-01 19:23 UTC, ldelossa approved these changes

2022-09-02 07:55 UTC, kaworu approved these changes

2022-09-02 10:58 UTC, qmonnet approved these changes

2022-09-05 12:23 UTC, aanm approved these changes
Thank you!

2022-09-05 12:24 UTC, aanm commented
/test

2022-09-05 12:39 UTC, aanm commented
@agrevtcev sorry, one last thing, the CI is complaining about the commit message tittle being too long. Can you edit it by making it a paragraph please? Thank you

2022-09-07 17:10 UTC, agrevtcev commented
> 

@aanm hi! Done.

2022-09-07 20:42 UTC, aanm approved these changes
Thank you very much!

2022-09-07 20:43 UTC, aanm commented
/test

2022-09-09 15:46 UTC, aanm commented
/test-1.23-5.4

2022-09-09 15:46 UTC, aanm commented
/test-1.25-net-next

2022-09-12 10:10 UTC, aanm commented
/test

2022-09-12 22:53 UTC, aanm commented
/test

2022-09-13 21:15 UTC, aanm commented
/mlh new-flake Cilium-PR-K8s-1.25-kernel-net-next

2022-09-13 21:26 UTC, merged