v1.12 backports 2022-08-29
cilium/cilium pull request #21122
Opened 2022-08-29 20:58 UTC by glibsm

* #20780 -- datapath: avoid delete/add flap for cilium_vxlan on startup (@julianwiedmann)
 * #21003 -- pkg/endpoint: change CEP policy status message (@aanm)
 * #21006 -- add kvstore TTL flag in cilium-operator (@NikhilSharmaWe)
 * #21062 -- Do not enable health checks on Terminating backends (@zuzzas)
 * #21078 -- clustermesh-apiserver: fix key name for delete during k8s->kvstore sync (@tklauser)
 * #21008 -- helm: Add check for apparmor annotations (@sayboras)
 * #21056 -- Spring cleaning for the contributor guide (@joestringer)
 * #21052 -- docs: Update ToServices docs section (@joestringer)
 * #21086 -- pkg/nodediscovery: protect variable against concurrent access (@aanm)
 * #21087 -- pkg/endpoint: set labels for local node from k8s events (@aanm)
 * #21001 -- Highlight Non-Overlapping Functionality Between K8s and Cilium Network Policies (@nathanjsweet)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 20780 21003 21006 21062 21078 21008 21056 21052 21086 21087 21001; do contrib/backporting/set-labels.py $pr done 1.12; done
```

2022-08-29 21:05 UTC, nathanjsweet approved these changes
:+1: on my changes.

2022-08-29 21:23 UTC, glibsm commented
Checking is the following error from CI relates to any of the backported commits:
```
# github.com/cilium/cilium/operator
Error: ./flags.go:337:2: undefined: regOpts
Error: ./flags.go:339:2: undefined: Vp
```

2022-08-29 22:01 UTC, sayboras approved these changes
Looks good for my changes, thanks :+1:

2022-08-29 22:08 UTC, joestringer approved these changes
Backports of my changes look good :+1:

2022-08-30 08:10 UTC, tklauser approved these changes
> * [clustermesh-apiserver: fix key name for delete during k8s->kvstore sync #21078](https://github.com/cilium/cilium/pull/21078) -- clustermesh-apiserver: fix key name for delete during k8s->kvstore sync (@tklauser)

Looks good for the above PR.

2022-08-30 14:12 UTC, aanm approved these changes

2022-08-30 15:59 UTC, julianwiedmann approved these changes

2022-08-30 16:48 UTC, glibsm commented
Force-pushing to fix error merge in terminating backends merge:
```
/home/travis/gopath/src/github.com/cilium/cilium/pkg/service/service_test.go:549:72: undeclared name: localActiveBackends
/home/travis/gopath/src/github.com/cilium/cilium/pkg/service/service_test.go:565:72: undeclared name: localActiveBackends
/home/travis/gopath/src/github.com/cilium/cilium/pkg/service/service_test.go:574:72: undeclared name: localActiveBackends
/home/travis/gopath/src/github.com/cilium/cilium/pkg/service/service_test.go:594:72: undeclared name: localActiveBackends
/home/travis/gopath/src/github.com/cilium/cilium/pkg/service/service_test.go:519:2: localBackends declared but not used
```

2022-08-30 17:08 UTC, aditighag requested changes
>https://github.com/cilium/cilium/pull/21062 -- Do not enable health checks on Terminating backends (@zuzzas)

I've highlighted the merge conflict.

2022-08-30 17:08 UTC, aditighag commented on pkg/service/service_test.go
> +	localTerminatingBackend3 := *lb.NewBackend(0, lb.TCP, net.ParseIP("10.0.0.3"), 8080)
```suggestion
	localTerminatingBackend3 := lb.NewBackend(0, lb.TCP, net.ParseIP("10.0.0.3"), 8080)
```

2022-08-30 23:17 UTC, aditighag commented on pkg/service/service_test.go
> +	localTerminatingBackend3 := *lb.NewBackend(0, lb.TCP, net.ParseIP("10.0.0.3"), 8080)
Never mind. The upstream PR that made core changes to switch from `lb.Backend` to `*lb.Backend` wasn't backported to older branches, hence the merge conflicts.

2022-08-30 23:17 UTC, aditighag approved these changes

2022-08-31 15:15 UTC, glibsm commented
/test-backport-1.12

2022-09-02 12:44 UTC, joamaki commented
/test-backport-1.12

2022-09-05 08:32 UTC, joamaki commented
/test-backport-1.12

2022-09-05 14:22 UTC, joamaki commented
/test-gke

2022-09-05 14:22 UTC, joamaki commented
/ci-gke-1.12

2022-09-05 14:44 UTC, joamaki commented
/ci-aks-1.12

2022-09-06 07:49 UTC, joamaki commented
Some flakyness with k8s-1.2?-kernel-4.9, test-gke and ci-gke-1.12. Earlier runs passed. Merging.

2022-09-06 07:49 UTC, merged