eni: sync all nodes on operator starting
cilium/cilium pull request #21205
Opened 2022-09-05 14:29 UTC by wu0407

Set all nodes on the `nodes` field in `NewNodeManager`, that fix
`NodeManager.Resync` not resync immediately all nodes to resolves IP deficits
and metrics `cilium_operator_ipam_nodes` and
`cilium_operator_ipam_available_interfaces` not corrected.

Signed-off-by: xiaoqing <xiaoqingnb@gmail.com>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #20815

```release-note
sync all nodes on operator starting
```

2022-09-06 08:39 UTC, gandro requested changes
Thanks. If I understand the proposal correctly, this is to fix an issue with the metrics not having seen all nodes yet.

The way we typically solve this problem is by watching all nodes and waiting for the k8s client to confirm that we have seen all  (by waiting for `WaitForCacheSync`) instead of listing all nodes explicitly, which then calls `NodeManager.Resync`. We're not doing this for ENI mode at the moment, but we could absolutely add this.

https://github.com/cilium/cilium/blob/e0537f91dee911a36044c9a21fea0e875935a38e/operator/cmd/root.go#L546

https://github.com/cilium/cilium/blob/344863ac55e30f88706db06aca5af9d79db4c00a/pkg/ipam/node_manager.go#L458

`Resync` will be called once it is guaranteed that the `NodeManager` has seen every node. Why is it not possible to initialize the metrics there?

2022-09-06 13:46 UTC, wu0407 commented
> Thanks. If I understand the proposal correctly, this is to fix an issue with the metrics not having seen all nodes yet.
> 
> The way we typically solve this problem is by watching all nodes and waiting for the k8s client to confirm that we have seen all (by waiting for `WaitForCacheSync`) instead of listing all nodes explicitly, which then calls `NodeManager.Resync`. We're not doing this for ENI mode at the moment, but we could absolutely add this.
> 
> https://github.com/cilium/cilium/blob/e0537f91dee911a36044c9a21fea0e875935a38e/operator/cmd/root.go#L546
> 
> https://github.com/cilium/cilium/blob/344863ac55e30f88706db06aca5af9d79db4c00a/pkg/ipam/node_manager.go#L458
> 
> `Resync` would then be called once it is guaranteed that the `NodeManager` has seen every node. Why is it not possible to initialize the metrics there?

That  `Manager.Start` before `startSynchronizingCiliumNodes`  in eni mode, so it has no way to wait for cache synchronization.
https://github.com/cilium/cilium/blob/aed5b1816cb2937b00418e272d2946d2cf86992e/operator/cmd/root.go#L402-L415
https://github.com/cilium/cilium/blob/aed5b1816cb2937b00418e272d2946d2cf86992e/pkg/ipam/allocator/aws/aws.go#L83-L86
https://github.com/cilium/cilium/blob/aed5b1816cb2937b00418e272d2946d2cf86992e/operator/cmd/root.go#L520-L522

2022-09-06 14:20 UTC, wu0407 commented
I think change like this if use cache synced

``` go
        nm, err := alloc.Start(ctx, &ciliumNodeUpdateImplementation{}, k8sCiliumNodesCacheSynced) 
 	if err != nil { 
 		log.WithError(err).Fatalf("Unable to start %s allocator", ipamMode) 
 	}
```

``` go
go func() {
    <-k8sCiliumNodesCacheSynced
  if err := nodeManager.Start(ctx); err != nil {
		  pannic(err)
	  }
}()

	return nodeManager, nil
```

2022-09-06 21:26 UTC, christarazi requested changes
Echoing Sebastian's comment as well. Why can't we rely on the `Update()` call to the Node Manager from K8s when a new node is created to execute the code in this PR?

2022-09-06 23:58 UTC, wu0407 commented
> Echoing Sebastian's comment as well. Why can't we rely on the `Update()` call to the Node Manager from K8s when a new node is created to execute the code in this PR?

1. Because `nodeManager.Start(ctx)` is execute before  discovering an event created by a new node.  Therefore, there will be a delay in executing `Update()`.
2. If `Update()` is executed in NewManager, it may lead to repeated solution of IP shortage, and `Update()` only solves the shortage without releasing the IP when there are too many ips.

2022-09-07 05:53 UTC, wu0407 commented
@gandro @christarazi  new implement base on cache synced https://github.com/wu0407/cilium/commit/23d92e764df3260364e5009b6fe605c379378860

2022-09-07 08:31 UTC, gandro commented
I am a bit vary of delaying IPAM "just" to ensure the metrics are consistent. Why can't we start IPAM early (as we do right now), and just delay the creation of the two affected metrics until the caches are synced?

2022-09-08 03:22 UTC, wu0407 commented
> Why can't we start IPAM early (as we do right now),

Also, Reconciling the IP resource pool as early as possible, it may not be worth it.

2022-09-14 12:11 UTC, gandro commented
I don't see how the current revision is fundamentally different from the previous ones. This will block IPAM till all nodes have been received, which is not necessary for cloud-based IPAM to work and I think introduces unnecessary delays in large clusters. There is no inter-node dependency as there is e.g. with the clusterpool/podcidr allocator.

2022-09-20 09:57 UTC, wu0407 commented
> I don't see how the current revision is fundamentally different from the previous ones. This will block IPAM till all nodes have been received, which is not necessary for cloud-based IPAM to work and I think introduces unnecessary delays in large clusters. There is no inherent need for cloud-based IPAMs to rely inter-node dependency as there is e.g. with the clusterpool/podcidr allocator.
> 
> Why can we not fix the metrics issue by delaying their creation till caches are synced and leave the rest of the mechanism unaffected?
I have no idear, so close this pr.

2022-09-20 09:57 UTC, closed without merging