kvstore/allocator: fix panic on receiving invalid identity entries
cilium/cilium pull request #21213
Opened 2022-09-06 11:00 UTC by ArthurChiao

This problem is triggered when the event type is "UPDATE" AND the value
is an empty string, resulting in the `key` variable uninitialized:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1cc4362]

goroutine 1430 [running]:
github.com/cilium/cilium/pkg/allocator.(*Allocator).encodeKey(0xc00f4fab00, 0x0, 0x0, 0xc0207a5838, 0x2ac8c01)
        /go/src/github.com/cilium/cilium/pkg/allocator/allocator.go:457 +0x22
github.com/cilium/cilium/pkg/allocator.(*cache).OnModify(0xc00f4fab98, 0x333f4, 0x2f28b38, 0xc03d7b2318)
        /go/src/github.com/cilium/cilium/pkg/allocator/cache.go:144 +0x22d
github.com/cilium/cilium/pkg/kvstore/allocator.(*kvstoreBackend).ListAndWatch(0xc005029e80, 0x2f1c088, 0xc0000c8008, 0x2f1c3d0, 0xc00f4fab98, 0xc00f5aaea0)
        /go/src/github.com/cilium/cilium/pkg/kvstore/allocator/allocator.go:624 +0x2a7
github.com/cilium/cilium/pkg/allocator.(*cache).start.func1(0xc00f4fab98)
        /go/src/github.com/cilium/cilium/pkg/allocator/cache.go:198 +0x73
created by github.com/cilium/cilium/pkg/allocator.(*cache).start
        /go/src/github.com/cilium/cilium/pkg/allocator/cache.go:197 +0xee
```

"CREATE" event handlings are not suffered previously as there is nil pointer
checking in `OnAdd()` handler.

Signed-off-by: ArthurChiao <arthurchiao@hotmail.com>

2022-09-07 10:10 UTC, tklauser commented
/test

2022-09-07 14:46 UTC, tklauser requested changes
The Travis CI failure looks related:

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃   FAIL  package: github.com/cilium/cilium/pkg/identity/cache   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
--- FAIL: Test (63.79s)
                       
level=info msg="Creating etcd client" ConfigPath= KeepAliveHeartbeat=15s KeepAliveTimeout=25s RateLimit=20 subsys=kvstore
level=info msg="Connecting to etcd server..." config= endpoints="[http://127.0.0.1:4002]" subsys=kvstore
level=info msg="Initializing identity allocator" subsys=identity-cache
level=info msg="Allocating identities between range" cluster-id=0 max=393215 min=327680 subsys=identity-cache
level=info msg="Got lease ID 49ec83128512cba6 and the session TTL is 0s" subsys=kvstore
level=info msg="Got lock lease ID 49ec83128512cba8" subsys=kvstore
level=info msg="Initial etcd session established" config= endpoints="[http://127.0.0.1:4002]" subsys=kvstore
level=info msg="Successfully verified version of etcd endpoint" config= endpoints="[http://127.0.0.1:4002]" etcdEndpoint="http://127.0.0.1:4002" subsys=kvstore version=3.3.20
level=info msg="Allocated new global key" key="unspec:blah=%%//!!;unspec:id=foo;unspec:user=anna;" subsys=allocator
level=info msg="Releasing key" key="[unspec:blah=%%//!! unspec:id=foo unspec:user=anna]" subsys=allocator
level=info msg="Releasing key" key="[unspec:blah=%%//!! unspec:id=foo unspec:user=anna]" subsys=allocator
level=info msg="Released last local use of key, invoking global release" key="[unspec:blah=%%//!! unspec:id=foo unspec:user=anna]" subsys=kvstorebackend
level=info msg="Reusing existing global key" key="unspec:blah=%%//!!;unspec:id=foo;unspec:user=anna;" subsys=allocator
level=info msg="Allocated new global key" key="unspec:id=bar;unspec:user=anna;" subsys=allocator
level=info msg="Allocated new global key" key="unspec:id=bar;unspec:user=susan;" subsys=allocator
level=info msg="Releasing key" key="[unspec:blah=%%//!! unspec:id=foo unspec:user=anna]" subsys=allocator
level=info msg="Released last local use of key, invoking global release" key="[unspec:blah=%%//!! unspec:id=foo unspec:user=anna]" subsys=kvstorebackend
level=info msg="Releasing key" key="[unspec:id=bar unspec:user=anna]" subsys=allocator
level=info msg="Released last local use of key, invoking global release" key="[unspec:id=bar unspec:user=anna]" subsys=kvstorebackend
level=info msg="Releasing key" key="[unspec:id=bar unspec:user=susan]" subsys=allocator
level=info msg="Released last local use of key, invoking global release" key="[unspec:id=bar unspec:user=susan]" subsys=kvstorebackend
level=error msg="Received a key with an empty value" eventType=delete key=cilium/state/identities/v1/id/336747 subsys=kvstorebackend
level=error msg="Received a key with an empty value" eventType=delete key=cilium/state/identities/v1/id/343454 subsys=kvstorebackend
level=error msg="Received a key with an empty value" eventType=delete key=cilium/state/identities/v1/id/354727 subsys=kvstorebackend
level=error msg="Received a key with an empty value" eventType=delete key=cilium/state/identities/v1/id/385303 subsys=kvstorebackend
level=error msg="Received a key with an empty value" eventType=delete key=cilium/state/identities/v1/id/388681 subsys=kvstorebackend
----------------------------------------------------------------------
FAIL: <autogenerated>:1: IdentityAllocatorEtcdSuite.TestAllocator
allocation_test.go:323:
    c.Assert(owner.WaitUntilID(id3.ID), Not(Equals), 0)
... obtained int = 0
... expected int = 0
```

https://app.travis-ci.com/github/cilium/cilium/jobs/581944595#L775

2022-09-08 02:33 UTC, ArthurChiao commented
@tklauser thanks! Turns out `DELETE` events always have empty values, I've updated the patch and the CI passed.

2022-09-08 08:42 UTC, tklauser commented
/test

2022-09-08 10:41 UTC, tklauser commented
/test-runtime

2022-09-08 10:46 UTC, tklauser approved these changes

2022-09-08 15:30 UTC, tklauser commented
/test-1.25-net-next

2022-09-09 17:06 UTC, aanm commented
The net-next failures happening are related to https://github.com/cilium/cilium/issues/18012

2022-09-09 17:06 UTC, merged