makefile: use versioned go container when formatting after api generate.
cilium/cilium pull request #21254
Opened 2022-09-09 00:01 UTC by tommyp1ckles

Currently the Makefile generate-api target just uses whatever the user has installed. As a result, if you have mismatched goimports/branch Go versions it will write out a bunch of incorrect formatting changes.
This changes that so that it always uses the exact version of Go specified in GO_VERSION.

Signed-off-by: Tom Hadlaw <tom.hadlaw@isovalent.com>

```release-note
makefile: use versioned go container when formatting after api generate.)
```

2022-09-09 00:01 UTC, tommyp1ckles commented
/test

2022-09-10 04:48 UTC, tommyp1ckles commented
/test

2022-09-13 21:22 UTC, tommyp1ckles commented
/test-1.25-net-next

2022-09-13 22:38 UTC, aanm approved these changes

2022-09-13 22:39 UTC, aanm commented
Marked the PR to be backported to all branches to make it easier to generate the API files if we need to.

2022-09-13 22:45 UTC, aanm approved these changes

2022-09-13 22:46 UTC, aanm requested changes

2022-09-13 22:46 UTC, aanm commented on Makefile
> -	-$(QUIET) find api/v1/server/ -type f -name "*.go" -print | PATH="$(PWD)/tools:$(PATH)" xargs goimports -w
@tommyp1ckles We will need to do the same for line 342 and 359

2022-09-14 22:24 UTC, aanm approved these changes

2022-09-15 11:02 UTC, aanm commented
> @aanm This is covered by some of the lint checks, no?

Which lint checks? :thinking: the regeneration of the API files? I don't think so.

2022-09-15 11:02 UTC, pchaigno commented
/test

2022-09-16 10:11 UTC, nebril approved these changes

2022-09-16 15:06 UTC, tommyp1ckles commented
/test-1.16-4.9

2022-09-16 15:06 UTC, tommyp1ckles commented
/test-1.25-net-next

2022-09-16 21:04 UTC, tommyp1ckles commented
/test-1.25-net-next

2022-09-17 15:38 UTC, tommyp1ckles commented
Rebase should fix the L4LB failure. Not sure about the k8s-1.25 test, the K8sEgressGateway tests seem pretty flakey on the CI insights board @pchaigno

2022-09-17 21:57 UTC, tommyp1ckles commented
/test

2022-09-18 02:49 UTC, tommyp1ckles commented
/test-1.25-net-next

2022-09-19 10:00 UTC, pchaigno commented
> the K8sEgressGateway tests seem pretty flakey on the CI insights board

Could you link to the existing flake issue for those or create one if none exist? Please attach sysdump to the issue as well or we'll lose them.

2022-09-23 02:15 UTC, tommyp1ckles commented
> > the K8sEgressGateway tests seem pretty flakey on the CI insights board
> 
> Could you link to the existing flake issue for those or create one if none exist? Please attach sysdump to the issue as well or we'll lose them.

Yup:
https://github.com/cilium/cilium/issues/21293

2022-09-26 08:21 UTC, merged