properly parsed the Helm Chart values.
cilium/cilium pull request #21297
Opened 2022-09-14 10:15 UTC by slayer321

Signed-off-by: slayer321 <sachin.maurya7666@gmail.com>

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

Fixes: #21179

Used `join` in sprig to pass the list a string.

2022-09-14 11:51 UTC, gandro requested changes
Thanks for the PR, looks good overall. The values need to be space separated however.

Also, could you update the title to something a bit more descriptive for the release notes, e.g. "helm: Properly support passing subnet-tags/subnet-ids/instance-tags filters as a list"

2022-09-14 11:51 UTC, gandro commented on install/kubernetes/cilium/templates/cilium-configmap.yaml
> +  subnet-ids-filter: {{ .Values.eni.subnetIDsFilter | join "," | quote }}
```suggestion
  subnet-ids-filter: {{ .Values.eni.subnetIDsFilter | join " " | quote }}
```

2022-09-14 11:51 UTC, gandro commented on install/kubernetes/cilium/templates/cilium-configmap.yaml
> +  subnet-tags-filter: {{ .Values.eni.subnetTagsFilter |  join "," | quote }}
```suggestion
  subnet-tags-filter: {{ .Values.eni.subnetTagsFilter |  join " " | quote }}
```

2022-09-14 11:51 UTC, gandro commented on install/kubernetes/cilium/templates/cilium-configmap.yaml
> +  instance-tags-filter: {{ .Values.eni.instanceTagsFilter | join "," | quote }}
```suggestion
  instance-tags-filter: {{ .Values.eni.instanceTagsFilter | join " " | quote }}
```

2022-09-14 13:35 UTC, gandro commented
Great, thanks! One last request: Please squash all commits into one. Thank you.

2022-09-16 21:27 UTC, tommyp1ckles approved these changes

2022-09-19 09:00 UTC, gandro approved these changes

2022-09-19 09:00 UTC, gandro requested changes
@slayer321 Seems like there are some inconsisetneices, the Helm smoketest failed


```
 error: cilium/values.yaml has been modified
Make sure to apply your changes to cilium/values.yaml.tmpl and run 'make -C install/kubernetes cilium/values.yaml' to regenerate.
```

2022-09-19 18:01 UTC, slayer321 commented
What is can see is there is no changes needs to be in the [cilium/values.yaml.tmpl](https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/values.yaml.tmpl) file. Am I  missing something here ?

2022-09-20 08:37 UTC, gandro commented
> What is can see is there is no changes needs to be in the [cilium/values.yaml.tmpl](https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/values.yaml.tmpl) file. Am I missing something here ?

The `values.yaml` file is generated from the `values.yaml.tmpl` file. You will have to edit the latter fist, and then regenerate the values.yaml file using `make -C install/kubernetes cilium/values.yaml`

These are the lines you want to change:
https://github.com/cilium/cilium/blob/14c66c7bc5c6012eb6289dc0726f59dd2f16c137/install/kubernetes/cilium/values.yaml.tmpl#L593-L605

2022-09-20 09:09 UTC, gandro commented
Change looks good, please squash your commits again. Thanks!

2022-09-22 15:28 UTC, gandro approved these changes

2022-09-22 16:48 UTC, gandro commented
@slayer321 Could you squash again, please?

2022-09-26 09:41 UTC, gandro commented
Helm and docs smoketest passed. No need to run full CI on those flags, since they are not covered. Marking ready to merge.

2022-09-26 09:42 UTC, merged