monitor: fix detected races
cilium/cilium pull request #2130
Opened 2017-11-23 17:14 UTC by scanf

Fixes the following race

```
==================
WARNING: DATA RACE
Read at 0x00c42030e448 by goroutine 11:
  github.com/cilium/cilium/pkg/bpf.NewPerCpuEvents()
      /home/vagrant/go/src/github.com/cilium/cilium/pkg/bpf/perf.go:428 +0x18d
  main.(*Monitor).mainEventLoop()
      /home/vagrant/go/src/github.com/cilium/cilium/monitor/monitor.go:133 +0xb7
Previous write at 0x00c42030e448 by main goroutine:
  main.(*Monitor).Run()
      /home/vagrant/go/src/github.com/cilium/cilium/monitor/monitor.go:49 +0x52
  main.main()
      /home/vagrant/go/src/github.com/cilium/cilium/monitor/main.go:59 +0x1b0
Goroutine 11 (running) created at:
  main.(*Monitor).handleConnection()
      /home/vagrant/go/src/github.com/cilium/cilium/monitor/monitor.go:123 +0x2c2
==================
==================
WARNING: DATA RACE
Read at 0x000000dcc5c0 by goroutine 11:
  main.purgeInactiveListeners()
      /home/vagrant/go/src/github.com/cilium/cilium/monitor/monitor.go:66 +0x149
  main.(*Monitor).mainEventLoop()
      /home/vagrant/go/src/github.com/cilium/cilium/monitor/monitor.go:140 +0xd9
Previous write at 0x000000dcc5c0 by main goroutine:
  main.(*Monitor).Run()
      /home/vagrant/go/src/github.com/cilium/cilium/monitor/monitor.go:51 +0xb4
  main.main()
      /home/vagrant/go/src/github.com/cilium/cilium/monitor/main.go:59 +0x1b0
Goroutine 11 (running) created at:
  main.(*Monitor).handleConnection()
      /home/vagrant/go/src/github.com/cilium/cilium/monitor/monitor.go:123 +0x2c2
==================
==================
WARNING: DATA RACE
Read at 0x00c420010bf8 by goroutine 11:
  internal/race.ReadRange()
      /usr/local/go/src/internal/race/race.go:45 +0x42
  syscall.Write()
      /usr/local/go/src/syscall/syscall_unix.go:183 +0xaa
  internal/poll.(*FD).Write()
      /usr/local/go/src/internal/poll/fd_unix.go:218 +0x1d1
  net.(*netFD).Write()
      /usr/local/go/src/net/fd_unix.go:220 +0x65
  net.(*conn).Write()
      /usr/local/go/src/net/net.go:188 +0x87
  net.(*UnixConn).Write()
      <autogenerated>:1 +0x69
  main.purgeInactiveListeners()
      /home/vagrant/go/src/github.com/cilium/cilium/monitor/monitor.go:66 +0x181
  main.(*Monitor).mainEventLoop()
      /home/vagrant/go/src/github.com/cilium/cilium/monitor/monitor.go:140 +0xd9
Previous write at 0x00c420010bf8 by main goroutine:
  github.com/cilium/cilium/monitor/payload.(*Meta).MarshalBinary()
      /home/vagrant/go/src/github.com/cilium/cilium/monitor/payload/monitor_payload.go:47 +0x5d
  main.generateHealthCheckMsg()
      /home/vagrant/go/src/github.com/cilium/cilium/monitor/monitor.go:77 +0xa1
  main.(*Monitor).Run()
      /home/vagrant/go/src/github.com/cilium/cilium/monitor/monitor.go:51 +0x84
  main.main()
      /home/vagrant/go/src/github.com/cilium/cilium/monitor/main.go:59 +0x1b0
Goroutine 11 (running) created at:
  main.(*Monitor).handleConnection()
      /home/vagrant/go/src/github.com/cilium/cilium/monitor/monitor.go:123 +0x2c2
==================
```

Reported-by: André Martins <andre@cilium.io>
Signed-off-by: Alexander Alemayhu <alexander@alemayhu.com>

2017-11-23 17:15 UTC, scanf commented
@aanm Can you test this branch and confirm? Thanks.

2017-11-23 23:05 UTC, aanm requested changes
Also, what is the mutex on line monitor/monitor.go:L131 protecting?

It seems you're unlocking the mutex after spawn a go routine. The mutex won't have the effect you might think it has on that case.

2017-11-23 23:05 UTC, aanm commented on monitor/monitor.go
> +func setNumPages(npages int) {
Create a method for `PerfEventConfig` with a private mutex to set the `NumPages`

2017-11-23 23:05 UTC, aanm commented on monitor/monitor.go
> +	mutex.Lock() // Lock needed for eventConfig
If the lock is needed for the `eventConfig` then add a mutex for that structure.

2017-11-24 13:07 UTC, raybejjani requested changes
First, sorry, I feel I caused this set of races. Thank you for fixing it.
I would prefer that we improve the flow of the code rather than add more locking, but I don't think we can avoid a lock to protect monitorEvents unless we refactor significantly.
I think we can remove the other data races with a few steps (I left some inline comments related to this but this is the overview):
- Move the `go m.handleConnection(server)` invocation and `m := Monitor{}`  to the line just before `m.Run` (in main.go). This lets us setup all the variables we need to before we spawn goroutines and being printing stats.
- eventConfig can be passed by value to m.handleConnection (all the types are copied when we do this, so there will be no contention). This means it no longer needs to be global, or can live in main. In any case, it's only used in one place (setting up the perCpuEvents) and we can set NumPages on it directly one time, before we spawn all the goroutines.
- Set emptyMetaBuf once where it is declared. We only need one copy of it and we can reuse it just fine (and there are no writes to it after init so there is no race).

For monitorEvents, it's a lot more messy. It's accessed in `mainEventLoop` (to be created) and in `Run` (to use `dumpStat`). Worse, I just realised that the allocation we do on monitor.go:133 might shadow the global variable because of the := (so, we're never setting the global var! This would mean no statistics are printed, if true). I think we need a lock for it in the following places:
- when we set the pointer to it in mainEventLoop
- when we call dumpStats in Run
- when we call monitorEvents.Poll, CloseAll and ReadAll in mainEventLoop

I'm conflating the use of this lock a bit, as it protects assigning the pointer to the object and to using the internals. Ideally, we wouldn't need it since each time mainEventLoop starts it makes a new instance of this object (which it closes on exit). The only reason it's global is that dumpStats needs it. The easy solution is to stop the stats dumping, but those might be of use in debugging. The only ways I can think to fix this up involve bigger refactors of the code, so the lock seems like the simplest solution.

2017-11-24 13:07 UTC, raybejjani commented on monitor/monitor.go
> +	emptyMetaBuf := generateHealthCheckMsg()
We could do this one, with the global variable. Writing the slice out to clients won't consume it, and we know will be the same data send every time. This is also fine, but happens to be redundant.

2017-11-24 13:07 UTC, raybejjani commented on monitor/monitor.go
> +	setNumPages(npages)
I'd prefer to set this in main, before we call Run. This function was different before we switched it up, and it could be renamed ReportStats or something which would reflect that we aren't doing anything else.

2017-11-24 13:30 UTC, scanf commented
I wanted to go for a small fix, but I think Ray is right and we should rework the code at a later time instead. I am dropping this pull request in favor of a revert. 

Thanks.

2017-11-24 13:30 UTC, closed without merging