gradutation
cilium/cilium pull request #21336
Opened 2022-09-16 11:26 UTC by xmulligan

Cilium already has a CII best practices badge and is currently undergoing an audit so these can be removed

```release-note
Graduation documentation updated
```

2022-09-19 10:37 UTC, nebril approved these changes

2022-09-19 10:44 UTC, sayboras approved these changes
Hope this will happen real soon :100:

2022-09-20 14:00 UTC, qmonnet approved these changes

2022-09-20 14:09 UTC, qmonnet requested changes
Please make sure to use a real object for your commit, ideally prefixed with the subsystem that you're touching (for example: `docs: Update status for graduation in roadmap`). I also recommend to always have a commit description explaining the reason for the change (for example, `Badge and security audit have been/are being addressed, update status accordingly`), although we don't really enforce it for simple changes.

After that, we should be good to go.

2022-09-20 14:27 UTC, xmulligan commented
@qmonnet good point, I've updated and will do better in the future

2022-09-20 14:32 UTC, qmonnet approved these changes

2022-09-20 17:23 UTC, merged