Update the cert-manager's Certificate to fully qualify the duration
cilium/cilium pull request #21389
Opened 2022-09-21 15:38 UTC by farcaller

.spec.duration is specified as `XXhXXmXXs` and cm's webhook will rewrite the shorter values into the full ones.

Signed-off-by: Vladimir Pouzanov <farcaller@gmail.com>

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

This fully qualifies the duration field, thus removing the diff from argocd if cilium is managed via argocd/helm and cert-manager's webhook rewrites the Certificate resource.

```release-note
Update the cert-manager's Certificate to fully qualify the duration
```

2022-09-21 15:39 UTC, farcaller commented
ArgoCD's opinion on the subject:
![image](https://user-images.githubusercontent.com/693/191548922-808faac6-d960-47ef-9ccc-4c716cad83aa.png)

It can be ignored in argocd, of course, but there's no harm in fully qualifying it instead.

2022-09-21 16:11 UTC, kaworu requested changes
Hello @farcaller and thank you for the PR! No objection on my side, but we should then do this consistently (`git grep duration: install/kubernetes/` will show all instances).

2022-09-22 14:26 UTC, kaworu approved these changes
Thank you!

2022-09-23 03:07 UTC, sayboras approved these changes
thanks :100:

2022-09-23 03:07 UTC, sayboras commented
/test

2022-10-08 12:08 UTC, sayboras commented
/test-1.16-4.9

2022-10-09 00:28 UTC, merged