Fix a typo in the comment example
cilium/cilium pull request #21402
Opened 2022-09-22 12:13 UTC by farcaller

It's `log` in the [config.go](https://github.com/cilium/cilium/blob/master/pkg/option/config.go#L988)

Signed-off-by: Vladimir Pouzanov <farcaller@gmail.com>

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

Fixes a typo in the comment example: it's `log` in the [config.go](https://github.com/cilium/cilium/blob/master/pkg/option/config.go#L988)

2022-09-22 12:39 UTC, farcaller commented
Actually looking into it more, it should be separated with spaces for it to work. `cobra` is somewhat inconsistent in that regard, so I verified that on practice. Should I patch that in this same PR?

2022-09-22 14:19 UTC, kaworu requested changes
Good catch @farcaller and thank you for the PR!

> Actually looking into it more, it should be separated with spaces for it to work. cobra is somewhat inconsistent in that regard, so I verified that on practice. Should I patch that in this same PR?

That make sense to me, please see also the `required` helm message [here](https://github.com/cilium/cilium/blob/5dfebf4764f336c4f30b598f34b694b27f9d882b/install/kubernetes/cilium/templates/cilium-configmap.yaml#L667), I think it needs `s/logs/log/` and the example should be copied over to the values (possibly after fixing comma vs space).

To fix this [CI failure](https://github.com/cilium/cilium/actions/runs/3105360846/jobs/5030886841), please edit your changes to `install/kubernetes/cilium/values.yaml.tmpl` and then run `make -C install/kubernetes cilium/values.yaml` to update `install/kubernetes/cilium/values.yaml`.

Finally, pulling someone from the @cilium/api team to confirm the fixes.

2022-09-22 20:25 UTC, aanm approved these changes

2022-09-22 20:25 UTC, aanm commented
/test

2022-09-23 02:38 UTC, tommyp1ckles approved these changes

2022-09-23 07:48 UTC, kaworu approved these changes

2022-09-26 08:26 UTC, merged