cmd/bpf: Log if no policy maps found
cilium/cilium pull request #21429
Opened 2022-09-23 15:25 UTC by aditighag

2022-09-23 15:28 UTC, aanm requested changes

2022-09-23 15:28 UTC, aanm commented on cilium/cmd/bpf_policy_get.go
> +		fmt.Print("no maps found")
`Println` or `Printf` with `\n` :)

2022-09-23 15:32 UTC, aanm approved these changes

2022-09-26 08:30 UTC, gandro approved these changes

2022-09-26 08:30 UTC, merged