v1.11 backports 2022-10-03
cilium/cilium pull request #21564
Opened 2022-10-03 19:33 UTC by christarazi

* #20721 -- Improve dnsproxy ipcache handling, metrics (@joestringer)
 * #20833 -- ipcache: Fix lock leak (@joestringer)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 20721 20833; do contrib/backporting/set-labels.py $pr done 1.11; done
```

2022-10-03 19:50 UTC, joestringer commented
For this backport, we may need to also include https://github.com/cilium/cilium/pull/21565.

2022-10-03 19:56 UTC, joestringer requested changes

2022-10-03 19:56 UTC, joestringer commented on pkg/ipcache/cidr.go
> +	IPIdentityCache.Lock()
Yeah this part could trigger the bug fixed in https://github.com/cilium/cilium/pull/21565.

2022-10-10 07:12 UTC, joestringer commented
/test-backport-1.11

2022-10-10 17:09 UTC, christarazi commented
Newly backported PRs LGTM.

2022-10-10 17:54 UTC, christarazi commented
CI failed suspiciously around kube-apiserver policy enforcement. Seems to be specific to GKE somehow.

2022-10-10 22:57 UTC, joestringer commented
Is it possible that this is down to an underlying infrastructure issue?

From the `gke-stable` workflow:

Failure #1: https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/9143/testReport/junit/Suite-k8s-1/22/K8sPolicyTestExtended_Validate_toEntities_KubeAPIServer_Still_allows_connection_to_KubeAPIServer_with_a_duplicate_policy/

```
HTTP egress connectivity to pod "testds-ffrnd" to kube-apiserver "10.124.0.1"
Expected
    <string>: 
to equal
    <string>: 403
/home/jenkins/workspace/Cilium-PR-K8s-GKE@2/src/github.com/cilium/cilium/test/k8sT/Policies.go:2756
```

The message here doesn't make sense because it can't be both initiating a connection to "testds-ffrnd" and kube-apiserver on some other IP at the same time. So lets assume "to pod ..." is actually meant to say "from pod ...". But there is also no such pod in the environment. Furthermore, kube-proxy is down on one of the nodes:

```
	 kube-system         kube-proxy-gke-cilium-pr-k8s-gke-91-default-pool-6b844986-xrpf   1/1     Terminated   0          77m    10.138.15.231   gke-cilium-pr-k8s-gke-91-default-pool-6b844986-xrpf   <none>           <none>
```

What does `<string>: ` mean as output? That's not a 2xx, so not a successful operation... also not another 4xx or 5xx error code. Is this a timeout? Is it possible that the traffic was not considered as going to the kube-apiserver or the service IPs were not translated?

Failure #2: https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/9143/testReport/junit/Suite-k8s-1/22/K8sPolicyTestExtended_Validate_toEntities_KubeAPIServer_Denies_connection_to_KubeAPIServer/

This test, which follows immediately after the previous one, shows signs that the GKE cluster had nodes shut down in the middle of the test. It is plausible that this began during the previous test, hence why kube-proxy was previously down.

Failure #3: https://github.com/cilium/cilium/actions/runs/3217476092/jobs/5260494974

This one just timed out at 1h. No sign of failure.

Although it is suspicious to see failures on these tests in relation to the backports here, it's hard to gauge whether it's relevant if the underlying infrastructure is not functioning correctly.

2022-10-10 22:58 UTC, joestringer commented
/test-gke

2022-10-10 22:58 UTC, joestringer commented
/ci-gke-1.11

2022-10-10 23:04 UTC, joestringer commented
Also hit https://github.com/cilium/cilium/issues/21652

2022-10-11 01:09 UTC, joestringer approved these changes
Feels a bit weird to be approving my own changes, but the backports lgtm... I did take another fresh look through and I understand Chris took a look back over the latest ones as well.

I think this is good to merge.

2022-10-11 01:12 UTC, joestringer commented
Latest [gke-stable](https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/9153/) run failed a couple of other random tests, which is consistent with general stability of that workflow at the moment. I know that some folks have been running the first couple of fixes for a while without much trouble, so the risk is more on the latter couple of fixes. Either way those changes have been tested across 2x master + v1.12 + v1.11 backports across various jobs, including EKS conformance tests (where EKS is the most common environment to trigger the issue fixed in those latter commits), so I'm not sure we're going to get any further feedback on these changes than we have now. Worth including these in the next round of releases, so marking ready-to-merge.

2022-10-11 05:04 UTC, merged