enable cilium to retrieve k8s node node cidr
cilium/cilium pull request #216
Opened 2016-12-10 02:07 UTC by aanm

Signed-off-by: André Martins <andre@cilium.io>

2016-12-10 08:39 UTC, tgraf requested changes
Looks great. I think this should be the default as it requires no additional configuration or cluster state sync at all.

2016-12-10 08:39 UTC, tgraf commented on daemon/main.go
> +
unwanted

2016-12-10 08:39 UTC, tgraf commented on common/const.go
> +
looks like added by mistake

2016-12-15 17:49 UTC, tgraf approved these changes
One minor nit, rest looks good.

2016-12-15 17:49 UTC, tgraf commented on daemon/daemon/daemon.go
> +	if os.Getenv(common.K8sEnvNodeNameSpec) != "" {
```
if node_name := os.Getenv(..); node_name != "" {
    if err := d.useK8sNodeCIDR(node_name); err != nil {
```

2016-12-15 17:56 UTC, aanm commented on daemon/daemon/daemon.go
> +	if os.Getenv(common.K8sEnvNodeNameSpec) != "" {
Ah yes, I missed that one. Thanks

2016-12-15 19:04 UTC, merged