Sign CI images
cilium/cilium pull request #21611
Opened 2022-10-06 19:36 UTC by sandipanpanda

Implement container image signing using cosign in the build CI images workflow. Use Cosign to sign without keys by authenticating with an OIDC protocol supported by Sigstore. Leveraging image signing gives users confidence that the container images they got from the container registry was the trusted code that the maintainer built and published.

Signed-off-by: Sandipan Panda <samparksandipan@gmail.com>

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

```release-note
Sign CI images
```

2022-10-12 20:16 UTC, michi-covalent commented
ci image signing has been tested here ✅ https://github.com/cilium/cilium/pull/21669

2022-10-13 14:09 UTC, nbusseneau approved these changes
LGTM, as per the discussions already done on #21374.

2022-10-13 14:49 UTC, nbusseneau requested changes

2022-10-13 14:49 UTC, nbusseneau commented on .github/workflows/build-images-ci.yaml
> +  id-token: write
As discussed on #21374:
```suggestion
permissions:
  # To be able to access the repository with actions/checkout
  contents: read
  # Required to generate OIDC tokens for `sigstore/cosign-installer` authentication
  id-token: write
```

2022-10-18 19:24 UTC, sandipanpanda commented
Closing as testing container image signing was successful.

2022-10-28 18:41 UTC, closed without merging