Time endpoint regen after redeploying Cilium in nightly tests.
cilium/cilium pull request #2166
Opened 2017-11-29 14:02 UTC by nebril

This change adds measurement of regenerating Cilium endpoints after Cilium daemonset is deleted and recreated.

2017-11-29 14:17 UTC, nebril commented
We should not merge this until #2167 is resolved

2018-01-11 20:09 UTC, ianvernon commented
@nebril since #2167 is resolved, do you want reviews on this? If so, please add the "pending-review" tag and rebase.

2018-02-05 14:19 UTC, nebril commented
test-nightly

2018-02-07 11:31 UTC, eloycoto requested changes

2018-02-07 11:31 UTC, eloycoto commented on test/k8sT/Nightly.go
> +			ciliumPod, err = kubectl.GetCiliumPodOnNode(helpers.KubeSystemNamespace, helpers.K8s1)
ATM the nightly test are working with 4 Kubernetes nodes. Could you use the following way please?
```
ciliumPods, err := kubectl.GetCiliumPods(helpers.KubeSystemNamespace)
Expect(err).To(BeNil(), "Cannot retrieve cilium pods")
```

2018-02-07 11:31 UTC, eloycoto commented on test/k8sT/Nightly.go
> +					output := kubectl.CiliumExec(pod, "cilium endpoint list").Output().String()
I would like if you can use the following: 
```
count := 0
				for _, pod := range ciliumPods {
					status := kubectl.CiliumEndpointsStatus(pod)
					result := map[string]int{}
					for _, state := range status {
						result[state]++
					}
					count += result[desiredState]
					log.WithField("status", result).Debugf("Cilium %s endpoint status are:", pod)
				}
return count >= endpointCount
```

with this code, we can see the state per each time that runs, so it'll be helpful for debugging in the future.

2018-03-02 13:35 UTC, nebril commented
test-nightly

2018-08-23 10:47 UTC, joestringer commented
@nebril do we still need this now that https://github.com/cilium/cilium/pull/4684 is merged which exports prometheus metrics for endpoint regeneration time?

2018-09-11 08:27 UTC, closed without merging