Doc updates
cilium/cilium pull request #2173
Opened 2017-11-29 23:37 UTC by tgraf

2017-11-29 23:53 UTC, borkmann requested changes

2017-11-29 23:53 UTC, borkmann commented on README.md
> +integration points such as: network IO, application sockets, and traceptions to
`traceptions`

2017-11-29 23:53 UTC, borkmann commented on README.md
> +is integrates to common orchestration frameworks such as Kubernetes and Mesos.
`is integrates`

2017-11-29 23:53 UTC, borkmann commented on README.md
> +and flexible. To learn more about BPF, read mode in our our extensive [BPF
`our our`

2017-11-29 23:53 UTC, borkmann commented on README.md
> +   firewalls operates at Layer 3 and 4. A protocol running on a particular port
`operates`

2017-11-29 23:53 UTC, borkmann commented on README.md
> +     Currently VXLAN and Geneve are baked in but all encapsulation formats
`baked` .. maybe : `are supported natively`

2017-11-29 23:53 UTC, borkmann commented on README.md
> +   implemented using BPF using efficient hashtables allowing for almost
`using BPF using`

2017-11-29 23:53 UTC, borkmann commented on README.md
> +     the full label information of both the sender and receiving among a lot of
`among a lot of`

2017-11-29 23:53 UTC, borkmann commented on README.md
> +     process for both, running workloads and based on artbirary label
`artbirary `

2017-11-29 23:53 UTC, borkmann commented on README.md
Can we also fix the graphics in the README where we have `TC ingress` twice mistakenly?

2017-12-03 11:58 UTC, aalemayhu approved these changes
Just some minor things. Rest looks good. Thanks for fixing the dependencies section, will drop them from my branch.

In one of your commits, you are updating sphinx. Is this process documented somewhere?

2017-12-03 11:58 UTC, scanf commented on README.rst
> +`BPF and XDP Reference Guide`_.
s/read mode/read more/g

2017-12-03 11:58 UTC, scanf commented on README.rst
> +
s/artbirary/arbitrary/g

2017-12-03 11:58 UTC, scanf commented on README.rst
> +
s/4.10.x/4.14.x/g

2017-12-04 05:32 UTC, merged