bpf: remove cilium_host ip addr scope link
cilium/cilium pull request #21738
Opened 2022-10-14 11:21 UTC by liuxu623

make iptables masquerade choose cilium_host ip addr when access service external ip (backend is a pod in another node) in a pod

Fixes: #21737

2022-10-17 14:45 UTC, liuxu623 commented
@borkmann Hi, could you take a look?

2022-10-25 12:19 UTC, pchaigno requested changes
Could you explain in the commit description *why* you are making this change? Is it fixing a bug and, if so, what is the bug?

2022-10-25 12:23 UTC, liuxu623 commented
> Could you explain in the commit description _why_ you are making this change? Is it fixing a bug and, if so, what is the bug?

The bug is when access **service external ip / node port** in a pod, and backend is a pod in another node, reply package will not't through **cilium_vxlan**, it maybe drop by network device like router, you can see https://github.com/cilium/cilium/issues/21737 more details.

2022-12-02 08:46 UTC, sathieu commented
I confirm the bug and fix.

We use metallb in ARP mode, and access from a pod in the cluster to a loadbalancer IP only works from the node elected as leader for the given IP. Once the scope of `cilium_host` IP is set to global, the issue is gone.

2023-01-03 12:45 UTC, sathieu commented
This PR is not stale.

The "link" scope was added 4 years ago by https://github.com/cilium/cilium/commit/2d099f479c3a8697038014115f340b85d0bbc7ef (https://github.com/cilium/cilium/pull/1614).

@tgraf @aanm @aalemayhu Any input on this PR?

2023-01-17 11:53 UTC, pchaigno requested changes
My above review is still valid.

2023-01-23 11:59 UTC, pchaigno commented
I hit this same bug in a different context, so I resubmitted this as https://github.com/cilium/cilium/pull/23241, with a proper commit description.

2023-01-23 11:59 UTC, closed without merging