Sign Cilium container images
cilium/cilium pull request #21918
Opened 2022-10-28 20:53 UTC by sandipanpanda

Implement container image signing using cosign in build-images workflows. Leveraging image signing gives users confidence that the container images they got from the container registry were the trusted code that the maintainer built and published.

Fixes: cilium#19282

```release-note
Sign Cilium container images using cosign
```

2022-10-28 20:55 UTC, sandipanpanda commented
cc @aanm @nbusseneau @asraa

2022-10-28 21:02 UTC, sandipanpanda commented
CI run to test signing container image using cosign here: https://github.com/cilium/cilium/actions/runs/3321983746/jobs/5531352067

2022-10-28 21:07 UTC, aanm requested changes
LGTM, only one small comment

2022-10-28 21:07 UTC, aanm commented on Documentation/configuration/verify-image-signatures.rst
> +    $ COSIGN_EXPERIMENTAL=1 cosign verify --certificate-github-workflow-repository cilium/cilium --certificate-oidc-issuer https://token.actions.githubusercontent.com --certificate-github-workflow-na
`--certificate-github-workflow-ref refs/pull/[PR NUMBER]/merge` should be `--certificate-github-workflow-ref refs/tags/[RELEASE TAG]`

2022-10-29 09:32 UTC, aanm approved these changes

2022-10-31 11:10 UTC, merged