docs: restructure bpf guide
cilium/cilium pull request #21922
Opened 2022-10-30 16:08 UTC by yoyo-go

I restructured the BPF guide, but got below linter errors, I have looked up and didn't find out what's going wrong, the enumerated list has a proper indentation. 
```
Running linter...
./bpfguide/dev_tool.rst:10: (INFO/1) Enumerated list start value not ordinal-1: "3" (ordinal 3)
./bpfguide/reading.rst:10: (INFO/1) Enumerated list start value not ordinal-1: "4" (ordinal 4)
```

2022-10-31 11:15 UTC, qmonnet requested changes
Looks good, I've got some suggestions on the naming of the files (see below). The directory itself can probably just be `bpf` instead of `bpfguide`.

The CI errors were present before, but we would mask them in the script, this is what we need to adjust here now the files have moved. There's also one line to change in `CODEOWNERS`. Please add the patch below (but this is with `bpfguide/`, you probably want to adjust both lines with `bpf/` if you take my suggestion above):

```diff
diff --git a/CODEOWNERS b/CODEOWNERS
index ff22b9f66496..a8f9385ea64e 100644
--- a/CODEOWNERS
+++ b/CODEOWNERS
@@ -267,7 +267,7 @@ Makefile* @cilium/build
 /Documentation/_static/ @cilium/docs-structure
 /Documentation/api.rst @cilium/sig-agent @cilium/docs-structure
 /Documentation/beta.rst @cilium/docs-structure
-/Documentation/bpf.rst @cilium/sig-datapath @cilium/docs-structure
+/Documentation/bpfguide/ @cilium/sig-datapath @cilium/docs-structure
 /Documentation/check-build.sh @cilium/docs-structure
 /Documentation/check-cmdref.sh @cilium/docs-structure
 /Documentation/check-crd-compat-table.sh @cilium/docs-structure
diff --git a/Documentation/check-build.sh b/Documentation/check-build.sh
index bbd2923e286a..220855fb5430 100755
--- a/Documentation/check-build.sh
+++ b/Documentation/check-build.sh
@@ -101,7 +101,7 @@ run_linter() {
     CONF_PY_ROLES=$(sed -n "/^extlinks = {$/,/^}$/ s/^ *'\([^']\+\)':.*/\1/p" conf.py | tr '\n' ',')
     CONF_PY_SUBSTITUTIONS="$(sed -n 's/^\.\. |\([^|]\+\)|.*/\1/p' conf.py | tr '\n' ',')release"
     ignored_messages="("
-    ignored_messages="${ignored_messages}bpf.rst:.*: \(INFO/1\) Enumerated list start value not ordinal"
+    ignored_messages="${ignored_messages}bpfguide/.*\.rst:.*: \(INFO/1\) Enumerated list start value not ordinal"
     ignored_messages="${ignored_messages}|Hyperlink target .*is not referenced\."
     ignored_messages="${ignored_messages}|Duplicate implicit target name:"
     ignored_messages="${ignored_messages}|Malformed table\."
```

2022-10-31 11:15 UTC, qmonnet commented on Documentation/index.rst
> +   bpfguide/index
Just `bpf/index` probably, the `guide` part does not need be in the URL

2022-10-31 11:15 UTC, qmonnet commented on Documentation/bpfguide/index.rst
> +
No need to keep all these empty lines at the end of files

2022-10-31 11:15 UTC, qmonnet commented on Documentation/bpfguide/index.rst
> +   dev_tool
s/`dev_tool`/`toolchain`?

2022-10-31 11:15 UTC, qmonnet commented on Documentation/bpfguide/index.rst
> +   program_type
`program_types`, there are several ones, or even `progtypes`?

2022-10-31 11:15 UTC, qmonnet commented on Documentation/bpfguide/index.rst
> +   architect
`architect` is a person. `architecture`?

2022-10-31 11:15 UTC, qmonnet commented on Documentation/bpfguide/index.rst
> +   reading
`references`? `resources`?

2022-10-31 11:15 UTC, qmonnet commented on Documentation/bpfguide/index.rst
> +   debug_test
`debug_test` is OK, I'd use `debug_and_test` maybe to make it clear we're not debugging a test.

2022-10-31 15:41 UTC, qmonnet approved these changes
Looks good to me, thank you!

2022-11-03 10:58 UTC, borkmann approved these changes

2022-12-05 08:38 UTC, merged