hive: Unwrap provider inputs and outputs in PrintObjects
cilium/cilium pull request #21976
Opened 2022-11-02 15:46 UTC by joamaki

Previously the provider function type was shown in PrintObjects:

  🚧 pkg/node.newLocalNodeStore (local_node_store.go:71): func(node.LocalNodeStoreParams) (node.LocalNodeStore, error)

This does not unwrap the param and result structs and thus does not give enough information about the constructor. This commit fixes the issue by using dig.FillProviderInfo to pull the constructors actual inputs and outputs:

  🚧 pkg/node.newLocalNodeStore (local_node_store.go:71):
    ⮩ hive.Lifecycle, node.LocalNodeInitializer[optional]
    ⮨ node.LocalNodeStore

2022-11-14 21:42 UTC, dylandreimerink requested changes

2022-11-14 21:42 UTC, dylandreimerink commented on pkg/hive/cell/info.go
> +	maxLineLength = 120
Perhaps we should consider getting the terminal width [dynamically](https://pkg.go.dev/golang.org/x/term#GetSize) instead of hard coding a wrapping length.

2022-11-14 21:42 UTC, dylandreimerink commented on pkg/hive/cell/info.go
> +func (n *InfoNode) Condensed() *InfoNode {
Is this right? It seams strange to me to have a method with pointer receiver which modifies itself and returns itself. Perhaps this was meant to be a value receiver so it returns a copy?

In the current form we have a strange side effect where we would print differently depending on call order. Info() then Print() or Print() then Info()

2022-11-15 07:53 UTC, joamaki commented on pkg/hive/cell/info.go
> +func (n *InfoNode) Condensed() *InfoNode {
Since this was meant to be used when constructing it, I'll just remove the `Condensed()` method and just set the attribute directly.

2022-11-15 07:54 UTC, joamaki commented on pkg/hive/cell/info.go
> +	maxLineLength = 120
Agreed, will add it.

2022-11-15 09:58 UTC, dylandreimerink approved these changes
LGTM!

2022-11-15 12:13 UTC, joamaki commented
/test-runtime

2022-11-16 10:25 UTC, tklauser approved these changes

2022-11-16 10:26 UTC, tklauser commented
Looks like this branch picked up a merge conflict and needs a rebase.

2022-11-17 10:41 UTC, merged