Removed `lb_services` and `lb_backends` bpfmap dump from bugtool
cilium/cilium pull request #22011
Opened 2022-11-04 17:09 UTC by Vishal-Chdhry

Bugtool currently attempts to dump several of legacy maps which haven't existed in several versions.
This PR removes those bpfmaps

Signed-off-by: Vishal Choudhary <contactvishaltech@gmail.com>

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #21905

2022-11-04 17:10 UTC, Vishal-Chdhry commented
Hi @tommyp1ckles! Are these the only changes I have to make?

2022-11-14 13:32 UTC, joamaki approved these changes

2022-11-15 00:14 UTC, tommyp1ckles approved these changes

2022-11-21 18:20 UTC, tommyp1ckles requested changes

2022-11-21 18:20 UTC, tommyp1ckles commented on bugtool/cmd/configuration.go
> -			fmt.Sprintf("bpftool map dump pinned %s/tc/globals/cilium_lb4_backends", bpffsMountpoint),
@Vishal-Chdhry my apologies, I was mistaken, we actually can't remove the lb4_backends yet, as we still use those: https://github.com/cilium/cilium/blob/master/pkg/maps/lbmap/ipv4.go#L31.

So we just need to remove lb4_services.

2022-11-27 19:15 UTC, closed without merging