pkg/k8s: do not read k8s node annotations if they are not written
cilium/cilium pull request #22127
Opened 2022-11-12 01:15 UTC by aanm

When there is an annotation in the k8s node object, the annotation `io.cilium.network.ipv4-cilium-host` is used as the CiliumInternal IP address of the CiliumNode object in [1]. Whenever Cilium is updating any state into the CiliumNode it retrieves all IP address from k8s node, including the ones from annotations, and appends the local node's IP addresses, including the newly correct internal / router IP address, in [2]. Since this is a list, the annotation's IP address is always used first and all other Cilium agents will wrongly use it for any operation.

Fixes: 73d6cae2c906 ("install: default AnnotateK8sNode to false")
Signed-off-by: André Martins <andre@cilium.io>

```release-note
TBD
```

Fixes https://github.com/cilium/cilium/issues/21735

2022-11-12 01:16 UTC, aanm commented
/test

2022-11-12 04:29 UTC, Liz4187 approved these changes

2022-11-12 07:50 UTC, christarazi approved these changes

2022-11-14 08:14 UTC, bimmlerd commented on pkg/k8s/node.go
> +	// not annotating the node then we should use any annotation.
```suggestion
	// not annotating the node then we should not use any annotation.
```

I think that's what you mean?

2022-11-14 08:34 UTC, aanm commented
/test

2022-11-14 09:22 UTC, bimmlerd approved these changes
LGTM

2022-11-14 21:45 UTC, pchaigno requested changes
Discussed offline: this pull request doesn't fix the bug for when `annotate-k8s-node=true`.

2022-11-14 21:45 UTC, pchaigno commented on pkg/k8s/node.go
> -
*Commenting on random line, just to have a resolvable thread.*

Could you also apply the following commit to this branch to expose similar future bugs in the end-to-end tests:
```
commit 2f51308b1dd8d7e7fe8dfca49df9ae4962e7ecf1 (HEAD -> ci-fail-on-router-ip-mismatch)
Author: Paul Chaignon <paul@cilium.io>
Date:   Mon Nov 14 16:11:41 2022 +0100

    test: Fail on router IP mismatch warnings
    
    We try to restore the router IP both from the filesystem (first) and
    from Kubernetes objects (as a fallback). If the two IP addresses don't
    match, we emit a warning.
    
    There is no good reason for this to happen in CI so we should fail the
    test if that warning ever shows up. Doing so would have prevented the
    flake fixed by the previous commit.
    
    Signed-off-by: Paul Chaignon <paul@cilium.io>

diff --git a/test/helpers/cons.go b/test/helpers/cons.go
index 210c11d81d..0d27d9c605 100644
--- a/test/helpers/cons.go
+++ b/test/helpers/cons.go
@@ -229,6 +229,7 @@ const (
        removeTransientRule = "Unable to process chain CILIUM_TRANSIENT_FORWARD with ip" // from https://github.com/cilium/cilium/issues/11276
        missingIptablesWait = "Missing iptables wait arg (-w):"
        localIDRestoreFail  = "Could not restore all CIDR identities" // from https://github.com/cilium/cilium/pull/19556
+       routerIPMismatch    = "Mismatch of router IPs found during restoration"
 
        // ...and their exceptions.
        opCantBeFulfilled        = "Operation cannot be fulfilled on leases.coordination.k8s.io"        // cf. https://github.com/cilium/cilium/issues/16402
@@ -295,6 +296,7 @@ var badLogMessages = map[string][]string{
        removeTransientRule: nil,
        missingIptablesWait: nil,
        localIDRestoreFail:  nil,
+       routerIPMismatch:    nil,
        "DATA RACE":         nil,
        // Exceptions for level=error should only be added as a last resort, if the
        // error cannot be fixed in Cilium or in the test.
```

2022-11-14 21:45 UTC, pchaigno commented on pkg/k8s/node.go
> +
*Commenting on random line, just to have a resolvable thread.*

This bug caused a flake because the K8sUpdates test removed the CiliumNode objects as part of `helm delete`. Is there anything we could do so that it also cleans up the Node annotations?

2022-11-14 23:21 UTC, aanm commented
@pchaigno although it doesn't fix for the `annotate-k8s-node=true`, it does fix for the `annotate-k8s-node=false`. Regarding the case `annotate-k8s-node=true` it should be done in a different PR.

2022-11-18 15:59 UTC, aanm commented
/test

2022-11-21 11:50 UTC, pchaigno requested changes
My two comments above are still relevant I think. Other than that, looks good to me.

2022-11-22 12:24 UTC, aanm commented on pkg/k8s/node.go
> -
Done

2022-11-22 12:25 UTC, aanm commented on pkg/k8s/node.go
> +
Filled https://github.com/cilium/cilium/issues/22306

2022-11-22 12:48 UTC, aanm commented
/test

2022-11-22 17:22 UTC, pchaigno approved these changes
I've rerun my local reproduction 8 times with only the second commit and it didn't fail. Given my reproduction works with a rate 1/2, note that there's a probably of 1/256 that it doesn't fail even if it's not fixed.

The changes look good to me.

2022-11-22 21:21 UTC, merged