doc: add section to show how to customize cilium-agent metrics
cilium/cilium pull request #22178
Opened 2022-11-15 08:55 UTC by ArthurChiao

Hello there,

Just add some guides on how to customize cilium-agent metric outputs that I think are helpful but which seems to haven't been covered in the current documentation.

Signed-off-by: ArthurChiao <arthurchiao@hotmail.com>

2022-11-15 21:37 UTC, joestringer requested changes
Thanks for the suggestion! Just one minor wording nit below, could you fix that up?

2022-11-15 21:37 UTC, joestringer commented on Documentation/observability/metrics.rst
> +disable the following two metrics as they generate too much data:
```suggestion
the metric. For example, for really large clusters, users may consider to
disable the following two metrics as they generate too much data:
```

2022-11-16 01:46 UTC, ArthurChiao commented
Thanks @joestringer! Just merged, squashed and rebased against latest master.

2022-11-16 02:04 UTC, joestringer approved these changes

2022-11-16 10:28 UTC, merged