Issue #776 Cilium/Hubble
cilium/cilium pull request #22265
Opened 2022-11-18 12:50 UTC by rohithsai1904

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #776 cilium/hubble

Added filter for HTTP support
Need to add flags in hubble cli
```release-note

```

2022-11-18 15:46 UTC, kaworu requested changes
Thanks for the PR @rohithsai1904! I think the best way forward now is to add unit testing for the HTTP header filter once all the compiling issues are sorted out.

You could take inspiration from https://github.com/cilium/cilium/blob/bf3532efd47f45d505f9f1dffdda1e3b3df13662/pkg/hubble/filters/workload_test.go as it also test a key/value type of filter, although the http headers case is slightly simpler as it only appear once (vs workload filters which are doubled for source and destination).

2022-11-18 15:46 UTC, kaworu commented on api/v1/flow/flow.proto
> +    repeated HTTPHeader http_header=29;
nit:
```suggestion
    // http_header filters flows based on a list of HTTP Headers
    repeated HTTPHeader http_header = 29;
```

2022-11-18 15:46 UTC, kaworu commented on api/v1/flow/flow.pb.go
> +func (x *FlowFilter) GetDestinationPod() []string
this leads to a compilation error.

2022-11-18 15:46 UTC, kaworu commented on pkg/hubble/filters/httpheader.go
> +{
The `{` needs to be on the same line here

```suggestion
func (*HTTPHeader) OnBuildFilter(ctx context.Context, ff *flowpb.FlowFilter) ([]FilterFunc, error) {
```

2022-11-18 15:46 UTC, kaworu commented on pkg/hubble/filters/httpheader.go
> +
`httpMatchCompatibleEventFilter` is already defined in this package (see [here](https://github.com/cilium/cilium/blob/bf3532efd47f45d505f9f1dffdda1e3b3df13662/pkg/hubble/filters/http.go#L19)).


```suggestion
```

2022-11-18 15:46 UTC, kaworu commented on pkg/hubble/filters/httpheader.go
> +	}
the returned values are `(FilterFunc, error)`

```suggestion
	}, nil
```

2022-11-18 15:46 UTC, kaworu commented on pkg/hubble/filters/httpheader.go
> +	}
```suggestion
	}
	return fs, nil
```

2022-11-18 15:46 UTC, kaworu commented on pkg/hubble/filters/httpheader.go
> +		for _, w := range gethttp(ev).GetHeaders() {
`filterByHTTPHeader` is called without the `gethttp` `func` param, and I think we could do without, e.g.

```suggestion
		for _, w := range ev.GetFlow().L7.GetHttp().GetHeaders() {
```

2022-11-18 15:46 UTC, kaworu commented on pkg/hubble/filters/httpheader.go
> +type HTTPHeader struct{}
this type name must match the one used in `pkg/hubble/filters/filters.go`

```suggestion
type HTTPHeaderFilter struct{}
```

2022-11-28 08:20 UTC, kaworu commented
> Need to add unit test for http Header Filter

Thanks @rohithsai1904! Marking this PR as draft until it's ready for review with the unit tests.

2022-12-05 06:55 UTC, rohithsai1904 commented
@kaworu can you give me some specific testcases for the http header?

2022-12-05 14:27 UTC, kaworu commented
@rohithsai1904 sure, as I mentionned above, structurally

> You could take inspiration from https://github.com/cilium/cilium/blob/bf3532efd47f45d505f9f1dffdda1e3b3df13662/pkg/hubble/filters/workload_test.go as it also test a key/value type of filter, although the http headers case is slightly simpler as it only appear once (vs workload filters which are doubled for source and destination).

As for HTTP headers examples, here are some:
```
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
```

Also an interesting case specific to HTTP headers is that it's possible to have two of them with the same name, e.g.

```
Cache-control: no-cache
Cache-control: no-store
```

2022-12-06 09:42 UTC, rohithsai1904 commented
![image](https://user-images.githubusercontent.com/70425960/205875807-0feb4083-480e-44a1-83e8-914204c54ec5.png)

Stuck with this error

2022-12-06 09:46 UTC, rohithsai1904 commented
the function httpFlow is like
 
![image](https://user-images.githubusercontent.com/70425960/205876715-afab11ae-9ced-450f-85be-53b811c567dc.png)

2022-12-15 17:59 UTC, rohithsai1904 commented
@kaworu @rolinh Can you please check the PR?

2022-12-16 09:07 UTC, kaworu requested changes
Hi @rohithsai1904, I left some review comments. Please also avoid introducing blank lines and the Travis-CI error about go code formatting is [here](https://app.travis-ci.com/github/cilium/cilium/jobs/591328015#L407).

2022-12-16 09:07 UTC, kaworu commented on api/v1/flow/flow.proto
> +    repeated HTTPHeader http_header=29;
Probably make sense to move this field with the other http related ones

```suggestion
    // http_header filters flows based on HTTP Headers
    repeated HTTPHeader http_header = 29;
```

2022-12-16 09:07 UTC, kaworu commented on pkg/hubble/filters/httpheader.go
> +
```suggestion
```

2022-12-16 09:07 UTC, kaworu commented on pkg/hubble/filters/httpheader.go
> +		for _, w := range ev.GetFlow().L7.GetHttp().GetHeaders() {
sorry my mistake from a previous suggestion
```suggestion
		for _, w := range ev.GetFlow().GetL7().GetHttp().GetHeaders() {
```

2022-12-16 09:07 UTC, kaworu commented on pkg/hubble/filters/httpheader_test.go
> +								Key:   "Content_Length",
```suggestion
								Key:   "Content Length",
```

2022-12-16 09:07 UTC, kaworu commented on pkg/hubble/filters/httpheader_test.go
> +			assert.Equal(t, tt.want, fl.MatchOne(tt.args.ev))
The compilation error is here: [`fl.MatchOne` expect a `*v1.Event` parameter](https://github.com/cilium/cilium/blob/76837ead2978467e1033ee40c35d7a26beadf39d/pkg/hubble/filters/filters.go#L38) but `tt.args.ev` is a slice.

2022-12-16 21:56 UTC, rohithsai1904 commented
Hey @kaworu Can you please check with whats wrong? It could be great if u help me to merge and close issue this weekend.

2022-12-19 11:58 UTC, kaworu requested changes
Hi @rohithsai1904

1. The [Travis-CI failure](https://app.travis-ci.com/github/cilium/cilium/jobs/591464072) can be solved by running `make -C api/v1`
2. I left some suggestions, the one about the test arg struct should fix the compilation error. Then, you can run the following command to ensure that all new tests are passing and iterate from there:
    ```
   go test -v -run "TestHTTPHeaderFilter" ./pkg/hubble/filters/...
    ```
3. Optionally, it would be great to add an additional test case for multiple HTTP headers with the same name, e.g. a flow with both `Cache-control: no-cache` and `Cache-control: no-store` should match a `Cache-control: no-store` filter.
4. Finally, once the PR is passing CI and tests, please squash all commits into one and sign-off the resulting commit (see https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#developer-s-certificate-of-origin).

2022-12-19 11:58 UTC, kaworu commented on api/v1/flow/flow.proto
> +
```suggestion
```

2022-12-19 11:58 UTC, kaworu commented on api/v1/flow/flow.proto
> +
```suggestion
```

2022-12-19 11:58 UTC, kaworu commented on api/v1/flow/flow.proto
```suggestion
```

2022-12-19 11:58 UTC, kaworu commented on api/v1/flow/flow.proto
> +
```suggestion
```

2022-12-19 11:58 UTC, kaworu commented on pkg/hubble/filters/httpheader_test.go
> +			name: "header_key_and_value_empty_match",
```suggestion
			name: "header-key-and-value-empty-match",
```

2022-12-19 11:58 UTC, kaworu commented on pkg/hubble/filters/httpheader_test.go
> +		ev []*v1.Event
this is causing a compilation failure, as the declared args `ev` are `*v1.Event` now
```suggestion
		ev *v1.Event
```

2022-12-19 11:58 UTC, kaworu commented on pkg/hubble/filters/httpheader_test.go
> +			name: "header_key_match",
```suggestion
			name: "header-key-match",
```

2022-12-19 11:58 UTC, kaworu commented on pkg/hubble/filters/httpheader_test.go
> +			name: "header_value_match",
```suggestion
			name: "header-value-match",
```

2022-12-19 11:58 UTC, kaworu commented on pkg/hubble/filters/httpheader_test.go
> +			name: "header_key_and_value_match",
```suggestion
			name: "header-key-and-value-match",
```

2022-12-19 11:58 UTC, kaworu commented on pkg/hubble/filters/httpheader_test.go
> +			name: "header_key_mismatch",
```suggestion
			name: "header-key-mismatch",
```

2022-12-19 11:58 UTC, kaworu commented on pkg/hubble/filters/httpheader_test.go
> +			name: "header_value_mismatch",
```suggestion
			name: "header-value-mismatch",
```

2022-12-19 11:58 UTC, kaworu commented on pkg/hubble/filters/httpheader_test.go
> +			name: "header_key_and_value_mismatch",
```suggestion
			name: "header-key-and-value-mismatch",
```

2022-12-19 11:58 UTC, kaworu commented on pkg/hubble/filters/workload_test.go
> +
```suggestion
```

2022-12-19 11:58 UTC, kaworu commented on pkg/hubble/filters/workload_test.go
> +
```suggestion
```

2023-02-02 02:02 UTC, closed without merging