Fix: share etcd logger accross all client fix memory leak, possibly due to cluster mesh
cilium/cilium pull request #22263
Opened 2022-11-18 11:51 UTC by WingkaiHo

What type of PR is this?
/kind bug

Which issue(s) this PR fixes:
https://github.com/cilium/cilium/issues/13446

What this PR does / why we need it:
Currently cilium creates one etcd client per cluster_mesh. When cluster_mesh reconnecting etcd, it will close old client, and create a new one.  If clients aren't provided a logger they'll each create their own. These loggers can account for >= 30% cilium-agent memory.

such as in https://github.com/cilium/cilium/issues/13446
![avatar](https://user-images.githubusercontent.com/11253021/103031661-068a9880-453d-11eb-818f-cbb4b64c2ad4.png)

2022-11-19 00:40 UTC, aanm requested changes
@WingkaiHo Thank you for the PR. I believe the memory leak root cause can be fixed by this PR https://github.com/cilium/cilium/pull/14504. Feel free to rebase those changes and submit a PR with them.

2022-11-21 01:26 UTC, WingkaiHo commented
@aanm Thranks

2022-11-30 06:20 UTC, WingkaiHo commented
@aanm Thranks Only use PR https://github.com/cilium/cilium/pull/14504 still have memory leak in etcd log. 

I both use share etcd logger and PR https://github.com/cilium/cilium/pull/14504, the memory use of cluster_mesh decrease.  heap_profile 
![2022-11-30 14-17-12屏幕截图](https://user-images.githubusercontent.com/14209014/204722090-3c4176f8-0839-4df6-94f4-9efbd9b1f58d.png)

profile
[heap_profile_cilium.tar.gz](https://github.com/cilium/cilium/files/10120088/heap_profile_cilium.tar.gz)

2022-12-01 01:06 UTC, YutaroHayakawa commented on pkg/clustermesh/remote_cluster.go
> +		rc.remoteNodes.Close(context.TODO())
Can't we use `parentCtx` here?

2022-12-01 01:14 UTC, YutaroHayakawa commented on pkg/kvstore/consul.go
> +func (c *consulClient) Close(tx context.Context) {
`tx` -> `ctx`?

2022-12-01 01:15 UTC, YutaroHayakawa commented on pkg/clustermesh/remote_cluster.go
> +				rc.mutex.Lock()
`Lock` -> `Unlock`

2022-12-01 01:44 UTC, YutaroHayakawa requested changes
Thanks for your contribution @WingkaiHo! I made some comments for small things.

And please consider fixing following points.
1. We should make ab1f7fb23bac47e13f5dffca6ce3f4869fadf736 and 4c0ba13bc066609a7730968f2b68cb1469df7c73 a same commit, given the second one just moves the code added in the first one into another place.
2. Please cover the context around why we needed to unify the logger into commit message. How memory leak happens and why unifying the log resolves the issue.
3. Please cover the context around why we needed to add a new timeout value to etcd release process. What kind of the problem it is trying to resolve?
4. Please unify 7b4131d56a7cc8682632b762c012da1e9cba4195 and d31ff54135bb1d6134c38c136fb0c556716ee92e, all commits must be able to compile correctly. Otherwise, it will become hard to bisect later.
5. Please include ec4f430a89ac8bb5d9cf596e4beddaf253827f7a into the original commit (given this is a bug). Otherwise, it will become hard to bisect later.

2022-12-05 08:11 UTC, aanm requested changes

2022-12-05 08:11 UTC, aanm commented on pkg/clustermesh/clustermesh.go
> +		releaseTimeout: 5 * time.Second,
Why are we setting it to 5 seconds? Can you leave a comment on where this value came from?

2022-12-05 08:11 UTC, aanm commented on pkg/clustermesh/remote_cluster.go
> +						backend.Close(context.TODO())
Can't we use the `ctx` instead of `context.TODO()`?

2022-12-05 08:11 UTC, aanm commented on pkg/clustermesh/remote_cluster.go
> +					backend.Close(context.TODO())
Can't we use the `ctx` instead of `context.TODO()`?

2022-12-05 08:11 UTC, aanm commented on pkg/clustermesh/remote_cluster.go
> +					backend.Close(context.TODO())
Can't we use the `ctx` instead of `context.TODO()`?

2022-12-05 08:11 UTC, aanm commented on pkg/clustermesh/remote_cluster.go
> +					backend.Close(context.TODO())
Can't we use the `ctx` instead of `context.TODO()`?

2022-12-05 08:11 UTC, aanm commented on pkg/clustermesh/remote_cluster.go
> +func (rc *remoteCluster) releaseOldConnection(parentCtx context.Context) {
Can we have a good commit message in this commit (`feat(kvstore/backend): context timeout`)? It's difficult to understand why are we doing these changes here.

2022-12-05 14:25 UTC, WingkaiHo commented
I adjust commit

2022-12-05 21:19 UTC, joestringer commented
Travis-CI failed with a build failure, see the result of the failing check under the "Some checks were not successful" section below.

2022-12-08 16:13 UTC, aditighag commented
@WingkaiHo Moving the PR to draft so that reviewers are not getting pinged. Please mark it as ready for review once you've triaged, and fixed the Travis build failure.

2023-01-11 20:53 UTC, christarazi commented
@WingkaiHo Do you intend to pick up this PR?

2023-02-27 18:30 UTC, joestringer commented
Hi @WingkaiHo , do you plan on revisiting this PR? I think it is interesting to improve the memory usage of Cilium, so despite the comments it would be good to see further development on this PR.

2023-03-27 16:43 UTC, christarazi commented on pkg/kvstore/etcd.go
> +	config.Context = ctx
Doesn't the `cancel` func need to be passed or saved inside `config`, so that it can be called later? The comment on this code says that the context is cancelled when `Close()` is called, but I don't see the cancel func invoked there.

2023-03-27 16:43 UTC, christarazi commented on pkg/kvstore/etcd.go
> +	// Stop using a package scoped logger. We need to pass each etcd client a
Where is the package scoped logger? Shouldn't we remove it in favor of this one? I don't see any lines removing the existing logger.

2023-06-23 02:06 UTC, closed without merging