docs: add instructions to build the base images from external forks
cilium/cilium pull request #22304
Opened 2022-11-22 12:02 UTC by aanm

When opening a PR to update the base images from external forks, the bot does not have necessary permissions to push the changes into the fork. For those cases the developer should amend the commit locally and push the changes themselves.

Fixes: c5a778723a43 ("add auto-commit capability to build base images GH workflow")
Signed-off-by: André Martins <andre@cilium.io>

2022-11-22 12:22 UTC, jrajahalme approved these changes

2022-11-22 19:06 UTC, aditighag approved these changes
I haven't gone through the process myself recently, so I trust that the steps have been verified.

2022-11-22 23:22 UTC, joestringer requested changes
minor spelling+wording nit, but otherwise LGTM

2022-11-22 23:22 UTC, joestringer commented on Documentation/contributing/development/images.rst
> +#. If the PR was opened form a repository branch, the build will automatically
```suggestion
#. If the PR was opened from the main repository, the build will automatically
```

2022-11-23 20:19 UTC, joestringer approved these changes

2022-11-23 20:19 UTC, merged