policy: add two more fuzzers
cilium/cilium pull request #22336
Opened 2022-11-23 16:57 UTC by AdamKorcz

Signed-off-by: AdamKorcz <adam@adalogics.com>

Needs a rebase after https://github.com/cilium/cilium/pull/22038
```release-note

```

2023-01-09 16:39 UTC, nebril requested changes

2023-01-09 16:39 UTC, nebril commented on pkg/policy/fuzz_test.go
> +		policyMaps.AccumulateMapChanges(csFoo, adds, deletes, port, proto, dir, redirect, deny, nil)
Seems like this function should get more arguments.

2023-01-11 10:30 UTC, AdamKorcz commented on pkg/policy/fuzz_test.go
> +		policyMaps.AccumulateMapChanges(csFoo, adds, deletes, port, proto, dir, redirect, deny, nil)
I have updated the fuzzer.

2023-01-30 09:13 UTC, nebril approved these changes

2023-01-30 11:42 UTC, merged