fix: some tofqdn flags not being parsed
cilium/cilium pull request #22346
Opened 2022-11-24 10:33 UTC by carloscastrojumo

Flags `tofqdns-proxy-response-max-delay` and `tofqdns-idle-connection-grace-period` where not being parsed as values were not being pulled off from viper, making the default value being always applied. 

Also moved `tofqdns-proxy-response-max-delay` default value to `defaults.go`.

2022-11-28 10:36 UTC, jibi requested changes
Thanks for the fix! Could you please squash the 2 commits?

2022-11-28 13:05 UTC, carloscastrojumo commented
> Thanks for the fix! Could you please squash the 2 commits?

Thanks @jibi . Squashed.

2022-11-28 13:34 UTC, jibi approved these changes

2022-11-28 13:34 UTC, jibi commented
/test

2022-11-28 16:22 UTC, jrajahalme approved these changes

2022-11-28 16:23 UTC, merged

2022-11-30 19:17 UTC, christarazi commented
@carloscastrojumo Could you explain how these flags were not being parsed and how this fixes it? From what I could tell, the `flag.Duration` just calls down to `DurationVarP` which calls down to `VarP`. Before this PR, `DurationVar` called down to `VarP` already, so what's the difference?