workflows: enable eks ipsec tests (DON'T MERGE)
cilium/cilium pull request #22345
Opened 2022-11-24 09:44 UTC by NikAleksandrov

This commit enables EKS ipsec tests in order to try and reproduce the eks+ipsec flakes and gather new logs.

**Please do not merge.**

Closes: #16938
Signed-off-by: Nikolay Aleksandrov <nikolay@isovalent.com>

2022-11-24 10:33 UTC, NikAleksandrov commented
/ci-eks

2022-11-24 10:47 UTC, NikAleksandrov commented
/test

2022-11-24 11:30 UTC, NikAleksandrov commented
/ci-aks

2022-11-24 11:58 UTC, NikAleksandrov commented
/ci-eks

2022-11-24 12:51 UTC, NikAleksandrov commented
/ci-eks

2022-11-24 14:24 UTC, NikAleksandrov commented
/ci-eks

2022-11-24 22:28 UTC, NikAleksandrov commented
/ci-eks

2022-11-24 22:44 UTC, pchaigno commented
FYI, you can also rerun from the workflow page and it will preserve logs from previous runs. Not that it changes a lot in this case, as I'm guessing all runs are green.

2022-11-25 15:27 UTC, NikAleksandrov commented
After over 20 successful runs removing the dont-merge labels, I think we can try and re-enable these tests.

2022-11-25 15:30 UTC, nbusseneau approved these changes
You're making me very happy right now.

2022-11-25 15:31 UTC, nbusseneau commented
Do you have links to successful runs we could check?

2022-11-25 15:32 UTC, nbusseneau requested changes
Actually: do you have links to successful workflow runs? Usually we enforce providing them before approving.

2022-11-25 15:32 UTC, NikAleksandrov commented
The last few runs are here: https://github.com/cilium/cilium/actions/runs/3543967002

2022-11-25 15:33 UTC, nbusseneau commented
Thanks, but these do not have the encryption bits enabled, e.g. here from attempt 6 https://github.com/cilium/cilium/actions/runs/3543967002/jobs/5959572764 we can see the encryption steps are skipped.

2022-11-25 15:35 UTC, nbusseneau commented
Oh, I'm realizing maybe you did not know how to test changes to the workflow... Sorry, it's a bit arcane and cumbersome, so not surprised this would fly under the radar. The full explanation is documented inside the workflow, here: https://github.com/cilium/cilium/blob/fe39350a349d1a298822f61189a317a13c6997d2/.github/workflows/conformance-eks.yaml#L11-L24

2022-11-25 15:36 UTC, NikAleksandrov commented
Oooh

> Oh, I'm realizing maybe you did not know how to test changes to the workflow... Sorry, it's a bit arcane and cumbersome, so not surprised this would fly under the radar. The full explanation is documented inside the workflow, here:
> 
> https://github.com/cilium/cilium/blob/fe39350a349d1a298822f61189a317a13c6997d2/.github/workflows/conformance-eks.yaml#L11-L24
> 
> Happy to help if you need any additional help with this :)

Oooh! My bad, I didn't see that. I'll make sure to re-run them again properly. Sorry for the noise.

2022-11-25 15:37 UTC, nbusseneau commented
No problem, it happens a lot when first interacting with the GHA workflows 😅 Don't hesitate to ping me for anything.

2022-11-25 15:43 UTC, pchaigno commented
Oh, crap! I completely missed that when I checked. I'm too used to it :disappointed: So sorry for the wasted time Nikolay!

2022-11-25 15:45 UTC, NikAleksandrov commented
> Oh, crap! I completely missed that when I checked. I'm too used to it disappointed So sorry for the wasted time Nikolay!

No problem, I will re-run the tests. I've opened a new pr from the base repo here https://github.com/cilium/cilium/pull/22364

2022-11-25 15:51 UTC, closed without merging