Makefile: add target for checking if pkg/lock or sync.Mutex is used
cilium/cilium pull request #2234
Opened 2017-12-04 10:43 UTC by scanf

Makes the build fail if the lock package is not used.

Closes: #1702 (Add check to Makefile build to ensure that Cilium uses `pkg/lock` and not `sync.Mutex`)
Signed-off-by: Alexander Alemayhu <alexander@alemayhu.com>

2017-12-04 13:27 UTC, aanm approved these changes

2017-12-04 15:18 UTC, tgraf requested changes

2017-12-04 15:18 UTC, tgraf commented on Makefile
> +	@if grep -r --exclude-dir={vendor,externalversions,lock} -i --include \*.go "sync.Mutex" .; \
You want to grep for both `sync.Mutex` and `sync.RWMutex`

2017-12-05 09:53 UTC, raybejjani approved these changes
The CI failure seems to be a CLI <-> agent API parse thing, which I think we fixed on master.

2017-12-05 10:07 UTC, scanf commented
@raybejjani Will rebase and see if there are any more flakes here. Thanks for the heads up!

2017-12-05 11:02 UTC, scanf commented
The last failure looks like docker image issue will retrigger the build two more times.

```
10:53:39 ==> cilium-master-build-PR-2234-3-envoy: Unable to find image 'python:2.7.14' locally
10:54:08 ==> cilium-master-build-PR-2234-3-envoy: docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/python/manifests/2.7.14: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fpython%3Apull&service=registry.docker.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers).
``

2017-12-05 12:25 UTC, scanf commented
Last two builds invoked manually are now good.

2017-12-05 23:21 UTC, joestringer approved these changes
Looks like BPF codeowner was pulled in by prefilter.go. LGTM.

2017-12-12 22:23 UTC, aanm commented
@scanf can you rebase and add the `ready-to-merge` label?

2017-12-13 20:16 UTC, scanf commented
@aanm Done.

2017-12-19 14:05 UTC, tgraf approved these changes

2017-12-20 09:55 UTC, scanf commented
Last CI failure were aborted by Ian and look unrelated.

2017-12-22 07:26 UTC, scanf commented
Weird the last build looks like it failed because of a timeout.

https://jenkins.cilium.io/job/cilium/job/cilium/job/PR-2234/16/consoleText
```
Cancelling nested steps due to timeout
[K8s multi node Tests] Sending interrupt signal to process
[K8s multi node Tests] Sending interrupt signal to process
[K8s multi node Tests] Makefile:4: recipe for target 'k8s-multi-node-tests' failed
[K8s multi node Tests] make: *** [k8s-multi-node-tests] Error 143
[Pipeline] [K8s multi node Tests] }
[K8s multi node Tests] Failed in branch K8s multi node Tests
[Pipeline] // parallel
```

2017-12-25 07:40 UTC, merged