allow appending ReadCNIConfiguration into the default CNI plugins
cilium/cilium pull request #22358
Opened 2022-11-25 08:29 UTC by sofat1989

1. If CILIUM_CUSTOM_CNI_CONF = true, cni_install.sh will not generate the 05-cilium.conf. but cilium-agent will skip writing the ReadCNIConfiguration into WriteCNIConfigurationWhenReady, too.  We hope that cni_install.sh skips generating the file 05-cilium.conf but cilium-agent can write the ReadCNIConfiguration into WriteCNIConfigurationWhenReady ( In the previous version, cilium-agent will write the ReadCNIConfiguration when CILIUM_CUSTOM_CNI_CONF is true). here we change the logic, if opts.ReadCNIConfiguration is not empty, cilium-agent will generate the CNI conf.
```
if os.Getenv("CILIUM_CUSTOM_CNI_CONF") == "true" && opts.ReadCNIConfiguration == "" {
		return
	}
```

3. We have two our own CNI plugins, `tnet.conf yyy-istio.conf`.  They are managed by their applications. We hope cilium-agent can append ReadCNIConfiguration (the cilium CNI conf) into `tnet.conf` because it depends on tnet.conf.  

- ReadCNIConfiguration is not empty (`tnet.conflist`) ---> WriteCNIConfigurationChainingMode = false ---> write ReadCNIConfiguration directly into WriteCNIConfigurationWhenReady (`net.conflist`)
- ReadCNIConfiguration (`origin.conf`) is not empty ---> WriteCNIConfigurationChainingMode = true ---> DefaultCNIConfiguration (`tnet.conf`)  is not empty and DefaultCNIConfiguration exists --> Insert ReadCNIConfiguration (`origin.conf`)  into DefaultCNIConfiguration (`tnet.conf`) and write it into WriteCNIConfigurationWhenReady (`tnet.conflist`)  --> final files under /etc/cni/net.d: `tnet.conflist tnet.conf.cilium_bak yyy-istio.conf`
    
- ReadCNIConfiguration (`origin.conf`) is not empty ---> WriteCNIConfigurationChainingMode = true ---> DefaultCNIConfiguration is not empty but it doesn't exist ---> WriteCNIConfigurationWhenReady (`tnet.conflist`) exists --> Insert ReadCNIConfiguration (`origin.conf`)  into WriteCNIConfigurationWhenReady  (`tnet.conflist`)  (this is to silution cilium-agent restarting) --->   final files under /etc/cni/net.d: `tnet.conflist tnet.conf.cilium_bak yyy-istio.conf`
- ReadCNIConfiguration  (`origin.conf`) is not empty ---> WriteCNIConfigurationChainingMode = true ---> DefaultCNIConfiguration is empty ---> WriteCNIConfigurationWhenReady (`tnet.conflist`)doesn't exist --> Read the default CNI plugin (`tnet.conf `because it is before `yyy-istio.conf` after sorting by name ) --->  Insert ReadCNIConfiguration (`origin.conf`) into the default CNI plugin `tnet.conf ` and write it into WriteCNIConfigurationWhenReady (`tnet.conflist`) --->   final files under /etc/cni/net.d: `tnet.conflist tnet.conf.cilium_bak yyy-istio.conf`

```release-note
allow appending ReadCNIConfiguration into the default CNI plugins
```

2022-12-05 14:56 UTC, squeed commented on daemon/cmd/cni.go
> +	if os.Getenv("CILIUM_CUSTOM_CNI_CONF") == "true" && opts.ReadCNIConfiguration == "" {
Oh, good catch; this was a mistake; I'll fix it in https://github.com/cilium/cilium/pull/22035

2022-12-07 05:52 UTC, sofat1989 commented
@squeed I see that [#22035](https://github.com/cilium/cilium/pull/22035 ) is to refactor the cni management part. Could you have a look at my proposal about the appending ReadCNIConfiguration into the existing CNI plugins like the aws plugins.  We want to the same function like [mergeExistingAWSCNIConfig](https://github.com/cilium/cilium/blob/master/daemon/cmd/cni.go#L247).  But we want it is more general.

2022-12-07 18:29 UTC, pippolo84 requested changes
Thanks for your PR! :rocket: 

I've completed a first pass focusing mainly on the code structure and readability in _cni.go_. I'm planning to do a second pass later.

2022-12-07 18:29 UTC, pippolo84 commented on daemon/cmd/cni.go
> +			return fmt.Errorf("unable to read CNI configuration file %s: %s", opts.ReadCNIConfiguration, err)
We should use the `%w` verb here, since doing so will enable handling the returned error with `errors.Unwrap`, `errors.Is` and `errors.As`.

2022-12-07 18:29 UTC, pippolo84 commented on daemon/cmd/cni.go
> +		originalConfContents := make([]byte, 0)
This can be moved inside the `if opts.WriteCNIConfigurationChainingMode {` below.

Besides, since the value for this slice is taken from the functions below, you can simply declare it as: `var originalConfContents []byte`

2022-12-07 18:29 UTC, pippolo84 commented on daemon/cmd/cni.go
> +			if originalConfContents != nil && len(originalConfContents) != 0 {
`len(originalConfContents) != 0` is enough, since `len()` on a nil byte slice will give `0`.

2022-12-07 18:29 UTC, pippolo84 commented on daemon/cmd/cni.go
> +		if opts.WriteCNIConfigurationChainingMode {
AFAIU the code to manage the new `WriteCNIConfigurationChainingMode` option is placed here because we should verify that `opts.ReadCNIConfiguration != ""` first.
But doing this way, we are reading all the content of `opts.ReadCNIConfiguration` at line 173 only to discard it if `opts.WriteCNIConfigurationChainingMode == true`.

I suggest to add a helper function to properly fill `contents` and manage all the three cases:

```
func helper() ([]byte, error) {
    if opts.ReadCNIConfiguration == "" {
        return renderCNIConf(opts, confDir)
    }

    if opts.WriteCNIConfigurationChainingMode {
        // new logic here ...
        return contents, nil
    }

    // last scenario with opts.ReadCNIConfiguration != "" && opts.WriteCNIConfigurationChainingMode == false
    contents, err = os.ReadFile(opts.ReadCNIConfiguration)
    if err != nil {
        return fmt.Errorf("unable to read CNI configuration file %s: %s", opts.ReadCNIConfiguration, err)
    }
```

After calling this helper, we can apply the remaining logic in `installCNIConfFile` for:
- // commit CNI config
- // Remove the original CNI Configuration file
- and so on

2022-12-07 18:29 UTC, pippolo84 commented on daemon/cmd/cni.go
> +				return fmt.Errorf("failed to read the CNI configuration from %s: %s", opts.ReadCNIConfiguration, err.Error())
I suggest to use the %w verb for `err` and avoid calling `.Error()` on it. Same for the other occurrences of `fmt.Errorf` below

2022-12-07 18:29 UTC, pippolo84 commented on daemon/cmd/cni.go
> +	newMap := make(map[string]interface{}, 0)
Nit: there's no need to specify the initial capacity if it is 0.

2022-12-07 18:29 UTC, pippolo84 commented on daemon/cmd/cni.go
> +	var err error
`err` can be defined inside the `else` body

2022-12-07 18:29 UTC, pippolo84 commented on daemon/cmd/cni.go
> +		return plugin, err
nit: `return nil, errors.New("error reading plugin from CNI config plugin list")`

2022-12-07 18:29 UTC, pippolo84 commented on daemon/cmd/cni.go
> +		return plugins, err
nit: `return nil, errors.New("error reading plugin list from CNI config")`

2022-12-07 18:29 UTC, pippolo84 commented on daemon/cmd/cni.go
> +func getPlugins(cniConfigMap map[string]interface{}) ([]interface{}, error) {
This is used only in `getPluginsFromCNIConfigMap` and has a name that can be easily confused with `getPlugin`.
I suggest to remove the helper and move the assertion inside the calling function.

2022-12-07 18:29 UTC, pippolo84 commented on daemon/cmd/cni.go
> +	cniConfig = append(cniConfig, "\n"...)
There's no need to use a string here: `cniConfig = append(cniConfig, '\n')`

2022-12-07 18:29 UTC, pippolo84 commented on daemon/cmd/cni.go
> +	return err == nil
Since we are just testing for file existence, `return !errors.Is(err, fs.ErrNotExist)` is more specific.

2023-01-03 09:38 UTC, squeed commented on pkg/option/config.go
> +	// DefaultCNIConfiguration is an original default CNI configuration file. If
I had a bit of a think, and I think we can get away with a single string option. Something called like "CNIChainNetwork". If it's set, then:

1. Wait for a CNI network with that name to exist
2. Read that, generate the chained configuration (either from default or from read-cni-configuration)
3. Write the generated config to disk

What do you think?

2023-01-03 10:39 UTC, squeed commented
I was reading the CNI chaining code, and I think [this check](https://github.com/cilium/cilium/blob/master/plugins/cilium-cni/main.go#L407) also has to go; it requires that the _network name_ be "generic-veth", which is obviously silly.

In reality, the mere presence of a RawPrevResult is sufficient.

Can you take care of this as a part of this PR too?

2023-01-23 15:49 UTC, aanm commented
@sofat1989 do you have any update on this PR?

2023-03-28 16:54 UTC, christarazi commented
@sofat1989 Any plans to continue this PR?

2023-05-23 13:18 UTC, squeed commented
@sofat1989 I think I've taken care of this in #24956 -- I'll close this for now, and feel free to reach out otherwise.

2023-05-23 13:18 UTC, closed without merging