delete redundant type conversion
cilium/cilium pull request #22376
Opened 2022-11-26 15:16 UTC by tanberBro

Signed-off-by: tanberBro <pengfei.song@daocloud.io>

buf does not need to be forced to MAC type, redundant type conversion

2022-11-27 02:08 UTC, tanberBro commented
/cc @julianwiedmann

2022-12-01 10:06 UTC, julianwiedmann commented
Hi @tanberBro, thank you!

Can you please adjust the commit description, so it's easier to navigate later on? Something like

> 
> mac: delete redundant type conversion
> 
> buf is a []byte, and does not need to be forced to MAC type.
> 
> Signed-off-by: tanberBro <pengfei.song@daocloud.io>

2022-12-01 15:50 UTC, tanberBro commented
Adjusted
@julianwiedmann

2022-12-02 13:56 UTC, julianwiedmann requested changes
The `checkpatch` CI test asks to put a blank line between subject and body of the commit message.

2022-12-02 15:39 UTC, tanberBro commented
like this?
@julianwiedmann

2022-12-04 20:31 UTC, joestringer approved these changes

2022-12-04 20:31 UTC, merged