fix:remove ioutil for advanced golang
cilium/cilium pull request #22383
Opened 2022-11-28 07:37 UTC by yulng

Signed-off-by: yulng wei.yang@daocloud.io

Description
We should clean all io/util package according the url: https://go.dev/doc/go1.16#ioutil

2022-11-28 10:36 UTC, pippolo84 requested changes
Thanks for the PR!
Code changes are ok, but the commit message needs to be improved a bit.
What do you mean by "advanced golang"? Something like "to accomodate newer Go versions" should be clearer. Also, it would be good to report the link to the Go official doc that mention the deprecation of the ioutil package.
Finally, your "Signed-off-by" line is weird. You do not have to write it by hand, you can let git generate that with `git commit -s` after you've properly set up your name and email in git config.
Please refer to point 8 of [Cilium Contributing Guide](https://docs.cilium.io/en/v1.12/contributing/development/contributing_guide/) for more info.

2022-11-28 12:23 UTC, yulng commented
> accomodate newer Go versions

yes , accomodate newer Go versions

2022-11-28 14:36 UTC, pippolo84 commented
Sorry but using `git show` I don't see any difference from the previous commit:

```
$ git show 04911538bd
commit 04911538bdba3c5f4f441df69f623baf2b7d82e6 (HEAD -> ioutil, yulng/ioutil)
Author: yulng <wei.yang@daocloud.io>
Date:   Mon Nov 28 14:59:56 2022 +0800

    remove ioutil for advanced golang
    Signed-off-by: yulng wei.yang@daocloud.io
```

Can you please change both the commit title and message as suggested [here](https://github.com/cilium/cilium/pull/22383#pullrequestreview-1195571498)?
Also, you should remove the current `Signed-off-by` line and regenerate it with `git commit -s --amend`, so that it will be properly formatted (that is, with a blank line between the message and the `Signed-off-by` line itself).

As a reference, look at one of the commit already merged in the master branch:

```
$ git show fe39350a34
commit fe39350a349d1a298822f61189a317a13c6997d2
Author: Chance Zibolski <chance.zibolski@gmail.com>
Date:   Mon Nov 14 10:09:07 2022 -0800

    helm: Do not create Grafana dashboards by default
    
    The default in #21181 was true, but not everyone uses Grafana and this
    was already brought up in a comment in the previous PR that it can cause
    troubles with the cilium upgrade preflight manifest.
    
    Signed-off-by: Chance Zibolski <chance.zibolski@gmail.com>
```

2022-11-29 02:07 UTC, yulng commented
> Sorry but using `git show` I don't see any difference from the previous commit:
> 
> ```
> $ git show 04911538bd
> commit 04911538bdba3c5f4f441df69f623baf2b7d82e6 (HEAD -> ioutil, yulng/ioutil)
> Author: yulng <wei.yang@daocloud.io>
> Date:   Mon Nov 28 14:59:56 2022 +0800
> 
>     remove ioutil for advanced golang
>     Signed-off-by: yulng wei.yang@daocloud.io
> ```
> 
> Can you please change both the commit title and message as suggested [here](https://github.com/cilium/cilium/pull/22383#pullrequestreview-1195571498)? Also, you should remove the current `Signed-off-by` line and regenerate it with `git commit -s --amend`, so that it will be properly formatted (that is, with a blank line between the message and the `Signed-off-by` line itself).
> 
> As a reference, look at one of the commit already merged in the master branch:
> 
> ```
> $ git show fe39350a34
> commit fe39350a349d1a298822f61189a317a13c6997d2
> Author: Chance Zibolski <chance.zibolski@gmail.com>
> Date:   Mon Nov 14 10:09:07 2022 -0800
> 
>     helm: Do not create Grafana dashboards by default
>     
>     The default in #21181 was true, but not everyone uses Grafana and this
>     was already brought up in a comment in the previous PR that it can cause
>     troubles with the cilium upgrade preflight manifest.
>     
>     Signed-off-by: Chance Zibolski <chance.zibolski@gmail.com>
> ```

it's ok now😄😄

2022-11-29 10:33 UTC, yulng commented
> Thank you for updating the `Signed-off-by` line, but the commit message is still the same and needs to be fixed as suggested here:
> 
> > What do you mean by "advanced golang"? Something like "to accomodate newer Go versions" should be clearer. Also, it would be good to report the link to the Go official doc that mention the deprecation of the ioutil package.

Thanks, I updated the description, please see above
screenshot:
![image](https://user-images.githubusercontent.com/31728060/204506223-7f1461d9-9a47-4ae6-a700-46435582598b.png)

2022-11-29 11:02 UTC, pippolo84 commented
I am referring to the commit title, not the PR title. It's the commit title and the commit message that need to be fixed.
Thank you!

2022-11-30 02:41 UTC, yulng commented
> I am referring to the commit title, not the PR title. It's the commit title and the commit message that need to be fixed. Thank you!

Haha😄😄, sorry, I pushed it again

2022-11-30 18:04 UTC, pippolo84 approved these changes
LGTM, thanks! :rocket:

2022-11-30 18:04 UTC, pippolo84 commented
/test

2022-12-05 07:24 UTC, yulng commented
> /test

thank you
now it can be merged?
@pippolo84

2022-12-05 13:29 UTC, pippolo84 commented
/test-1.16-4.9

2022-12-05 13:31 UTC, pippolo84 commented
> thank you now it can be merged? @pippolo84

There's no need to modify the commit again. I retriggered some workflows, let's wait and see if the failures were just a flake.

2022-12-05 20:49 UTC, pippolo84 commented
/ci-awscni

2022-12-05 20:50 UTC, pippolo84 commented
/ci-eks

2022-12-05 20:50 UTC, pippolo84 commented
/ci-external-workloads

2022-12-06 10:57 UTC, pippolo84 commented
/test-1.24-5.4

2022-12-06 10:57 UTC, pippolo84 commented
/test-1.25-4.19

2022-12-06 10:58 UTC, pippolo84 commented
/test-1.26-net-next

2022-12-06 16:40 UTC, merged