Helm: Resources option for apiserver etcd
cilium/cilium pull request #22392
Opened 2022-11-28 14:12 UTC by shaardie

This patch adds the option to configure the resources of the init container and the container of etcd in the apiserver pods.

Signed-off-by: Sven Haardiek <sven.haardiek@uni-muenster.de>

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

This patch adds the option to configure the resources of the  init container and the container of etcd in the apiserver pods. Some clusters have a strict rules of setting those resources for scaling and quota handling and partly have policies in place not allowing containers or init containers without resources. So this makes it easier to use the Cilium Helm Chart on those clusters without patching.

```release-note
Add option to configure the resources of the init container and the container of etcd in the apiserver pods.
```

2022-11-28 15:47 UTC, kaworu requested changes
Thanks for the patch @shaardie! [This Travis-CI failure](https://app.travis-ci.com/github/cilium/cilium/jobs/589627417) is legit:

> HINT: to fix this, run 'make -C Documentation update-helm-values'

2022-11-29 09:45 UTC, shaardie commented
> Thanks for the patch @shaardie! [This Travis-CI failure](https://app.travis-ci.com/github/cilium/cilium/jobs/589627417) is legit:
> 
> > HINT: to fix this, run 'make -C Documentation update-helm-values'

Thanks for the hint. I fixed it. I thought using the Makefile in the helm `install/kubernetes/` would be sufficient.

2022-11-29 20:07 UTC, kaworu approved these changes
Thanks @shaardie patch LGTM now, pulling in someone from @cilium/sig-clustermesh to review.

2022-11-30 08:19 UTC, jrajahalme approved these changes

2022-11-30 08:20 UTC, jrajahalme commented
/test

2022-11-30 14:31 UTC, merged