ipam/crd: Fix agent fatal on router initialization
cilium/cilium pull request #22477
Opened 2022-12-01 11:53 UTC by jaffcheng

Currently, when a cilium-agent in eni/alibabacloud mode initializes router info, it might encounter the following fatal:

```
level=fatal msg="Error while creating daemon" error="failed to create router info invalid ip: " subsys=daemon
```

The gateway IP of routing info is derived from the CIDR of the subnet, the eni.Subnet.CIDR in InstanceMap is set as empty after ENI creation. In normal cases it will be filled by a later resyncTrigger after maintainIPPool. But if another goroutine (periodic resync or pool maintainer of another node) happens to sync local InstanceMap cache to k8s, cilium-agent would be informed of that ENI IP pool with empty cidr and router IP allocation would fatal due to empty gateway IP.

This patch fixes this by filling the CIDR right after ENI creation.

Signed-off-by: Jaff Cheng <jaff.cheng.sh@gmail.com>

```release-note
ipam/crd: Fix agent fatal on router initialization
```

2022-12-02 06:44 UTC, christarazi requested changes
Thanks for the PR. Could you describe under what conditions this may occur? It would be good to include that information in the release-note. 

There are also some linting errors that need to be fixed.

2022-12-05 10:34 UTC, jaffcheng commented
@christarazi  Sorry, fixed the linting errors and rebased.
>Could you describe under what conditions this may occur?

When an ENI is created, we insert that ENI with an empty CIDR into `InstanceManager`:
https://github.com/cilium/cilium/blob/8a3cefdf2ba431abda54a86a6c3e19e70fe3e589/pkg/alibabacloud/eni/node.go#L181
and then triggers `resyncTrigger` that updates the CIDR from cloud API.
Before that resync, another goroutine(periodic resync or pool maintainer of another node) might trigger a `k8sSync` and submit the ENI with the empty CIDR to ciliumnode.
https://github.com/cilium/cilium/blob/8a3cefdf2ba431abda54a86a6c3e19e70fe3e589/pkg/ipam/node_manager.go#L481

The cilium-agent might then encounter this fatal.

2022-12-06 07:50 UTC, christarazi approved these changes

2022-12-06 07:51 UTC, christarazi commented
/test

2022-12-10 12:20 UTC, merged