feat: deleted the pods that are not unmanaged by Cilium
cilium/cilium pull request #22545
Opened 2022-12-05 09:55 UTC by lvyanru8200

Set operator to remove the label of a pod that existed before the node taint

1. Delete the specified label pod according to the parameter --pod-restart-selector, default value is k8s-app=kube-dns
2. --pod-restart-selector="" Remove all pods

Fixes: #21594
Signed-off-by: yanru.lv <yanru.lv@daocloud.io>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #21594

```release-note

```

2022-12-05 23:00 UTC, joestringer requested changes
Couple of minor comments, please change these.

Also, just to let you know: you do not need to create new PRs like this each time you make changes. It should be possible to `git push --force` to override the previous PR's content on the branch. This will refresh the GitHub page and highlight the latest version of your code.

2022-12-05 23:00 UTC, joestringer commented on operator/cmd/flags.go
> +	flags.String(operatorOption.PodRestartSelector, "k8s-app=kube-dns", "Set operator to remove the label of a pod that existed before the node taint")
```suggestion
	flags.String(operatorOption.PodRestartSelector, "k8s-app=kube-dns", "cilium-operator will delete/restart any pods with these labels if the pod is not managed by Cilium. If this option is empty, then all pods may be restarted.")
```

2022-12-05 23:00 UTC, joestringer commented on operator/watchers/pod.go
> +	operatorOption "github.com/cilium/cilium/operator/option"
Please move this line down next to the other `github.com/cilium/cilium` imports.

2022-12-06 03:48 UTC, lvyanru8200 commented
cc @joestringer

2022-12-06 11:45 UTC, aanm requested changes
Just one small change, LGTM.

2022-12-06 11:47 UTC, aanm approved these changes
Oh I see that Joe already requested for the same change that I did. In that case I'm approving as long Joe's review is addressed.

2022-12-06 12:01 UTC, nebril approved these changes

2022-12-08 10:11 UTC, lvyanru8200 commented
@joestringer ping

2022-12-08 19:57 UTC, joestringer commented
Travis failed, please resolve the issue: https://app.travis-ci.com/github/cilium/cilium/jobs/590341246 .

2022-12-09 02:56 UTC, lvyanru8200 commented
/test

2022-12-09 03:02 UTC, lvyanru8200 commented
> Travis failed, please resolve the issue: https://app.travis-ci.com/github/cilium/cilium/jobs/590341246 .

How to re-trigger the Travis CI process please，I checked the logs and found no more obvious errors

2022-12-09 17:28 UTC, christarazi commented
@lvyanru8200 What's missing is that the cmdref documention has not been updated. Could you run `make -j $(nproc) && make -j $(nproc) -C Documentation/ update-cmdref` and then amend the current commit, and force push?

2022-12-12 09:13 UTC, lvyanru8200 commented
@christarazi thanks, @joestringer  cc

2022-12-13 03:05 UTC, lvyanru8200 commented
@christarazi https://github.com/cilium/cilium/actions/runs/3674055290/jobs/6211823310，Is this error a go version issue? Doesn't feel like my fault

2022-12-13 03:38 UTC, christarazi commented
No, I think this has been failing across other PRs as well.

2022-12-14 03:23 UTC, lvyanru8200 commented
@joestringer ping

2022-12-19 05:07 UTC, joestringer approved these changes

2022-12-19 05:08 UTC, joestringer commented
/test

2022-12-27 18:34 UTC, christarazi commented
@lvyanru8200 Please rebase your PR instead of introducing a merge commit, as we don't accept those in the tree.

2023-01-03 03:27 UTC, closed without merging