Revert "images/cilium-test: New test suite image"
cilium/cilium pull request #22657
Opened 2022-12-09 15:22 UTC by pchaigno

This reverts pull request https://github.com/cilium/cilium/pull/12941.

This code isn't used anywhere anymore.

cc @errordeveloper

2022-12-09 15:25 UTC, pchaigno commented
/test

2022-12-09 15:27 UTC, aanm requested changes

2022-12-09 15:27 UTC, aanm commented on .github/workflows/build-images-ci.yaml
> -  # we need to build cilium-test separately
All of this until line 438 can be deleted

2022-12-09 15:28 UTC, nebril approved these changes

2022-12-09 15:39 UTC, pchaigno commented
/test

2022-12-09 15:45 UTC, aanm requested changes

2022-12-09 15:45 UTC, aanm commented on .github/workflows/build-images-ci.yaml
>        (needs.build-and-push-with-qemu.result == 'success' || needs.build-and-push-with-qemu.result == 'skipped') }}
this `build-and-push-with-qemu` reference needs to removed

2022-12-09 18:25 UTC, pchaigno commented
/test

2022-12-09 21:50 UTC, aanm approved these changes

2022-12-10 00:00 UTC, pchaigno commented
k8s-1.16-kernel-4.9 failed with known flake https://github.com/cilium/cilium/issues/22404. That flake is unrelated to the present changes. Reviews are in. Merging.

2022-12-10 00:00 UTC, merged

2023-02-01 21:45 UTC, pchaigno commented
Marking this for backports to v1.13 as we keep getting dependency updates for that directory there.