docs-update-limitations
cilium/cilium pull request #22775
Opened 2022-12-16 13:11 UTC by raymonddejong

KPR is supported with Wireguard, but not with IPSec. This update of the docs reflects that.

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Update of the KPR limitations page as KPR is supported with Wireguard but not with IPSec.

```release-note

```

2022-12-16 13:19 UTC, brb reviewed
LGTM, thanks! I will ACK once you sign off the commit.

2022-12-16 16:18 UTC, pchaigno requested changes
Thanks for the fix!

2022-12-16 16:18 UTC, pchaigno commented on Documentation/network/kubernetes/kubeproxy-free.rst
> -    * Cilium's eBPF kube-proxy replacement currently cannot be used with :ref:`encryption-ipsec`.
The second commit needs to be squashed in the first. You can do that with:
```
git reset HEAD^
git add Documentation/network/kubernetes/kubeproxy-free.rst
git commit --amend
git push -f
```

2022-12-16 16:18 UTC, pchaigno commented on Documentation/network/kubernetes/kubeproxy-free.rst
> -    * Cilium's eBPF kube-proxy replacement currently cannot be used with :ref:`gsg_encryption`.
Could you update the title of the first commit (and of the PR) to something more descriptive? Maybe `docs: Update KPR limitations wrt WireGuard`?

2023-01-03 10:59 UTC, brb approved these changes

2023-01-03 11:00 UTC, pchaigno approved these changes

2023-01-03 13:07 UTC, pchaigno commented
The Documentation workflow passed. There are no changes to the docs structure. Merging.

2023-01-03 13:07 UTC, merged