docs: Clarify committer vote procedures
cilium/cilium pull request #22787
Opened 2022-12-19 02:05 UTC by joestringer

A couple of questions have come up recently around how to handle
communication for voting processes for committer access. Improve the
docs to make these steps more clear for subsquent nominations and votes.

2022-12-19 12:39 UTC, lizrice approved these changes

2022-12-19 13:50 UTC, sayboras approved these changes

2022-12-20 12:29 UTC, qmonnet commented on Documentation/community/governance/commit_access.rst
> +Vote results should be reported based on the vote count, ie after applying the
```suggestion
Vote results should be reported based on the vote count, i.e. after applying the
```

2022-12-20 12:29 UTC, qmonnet commented on Documentation/community/governance/commit_access.rst
> +Vote results should be reported based on the vote count, ie after applying the
```suggestion
Vote results should be reported based on the vote count, i.e. after applying the
```

2022-12-20 12:29 UTC, qmonnet commented on Documentation/community/governance/commit_access.rst
> +   *after* the nomination poll and related discussions have been deleted. There
Should we also explicitly state the motivation for deleting the poll result and related discussions?

2023-01-13 15:27 UTC, qmonnet approved these changes
Thanks for this!

2023-01-13 15:28 UTC, qmonnet requested changes
Spellchecker complains on `reposted`. Should be ready to merge after this is addressed.

2023-01-18 07:34 UTC, merged