bugtool: Dump envoy metrics for troubleshooting
cilium/cilium pull request #22797
Opened 2022-12-19 11:03 UTC by sayboras

Users might not have prometheus metrics endpoint enabled as part of existing Cilium installation. This commit is to add the capability to dump envoy metrics without the need of re-installation with additional helm flag, or updating existing cilium config map. One common use case is to check if there is any connectivity issue (e.g. 503, timeout, etc) for egress traffic.

For example, the below metrics are part of the dump, these two metrics clearly signal some configuration issues with TLS egress.

```bash
envoy_cluster_upstream_rq{envoy_response_code="503",envoy_cluster_name="egress-cluster-tls"} 100
envoy_cluster_upstream_cx_connect_fail{envoy_cluster_name="egress-cluster-tls"} 300
```

Testing was done locally by running curl command in pod manually

```bash
$ kubectl exec -n kube-system ds/cilium -- curl --unix-socket /var/run/cilium/envoy-admin.sock http:/admin/stats/prometheus > metrics_dump.txt
$ cat metrics_dump.txt | wc -l
  2753
```

Signed-off-by: Tam Mach <tam.mach@cilium.io>

2022-12-20 03:10 UTC, sayboras commented
Full CI is not required, as the changes are only limited to bugtool.

2023-01-20 04:33 UTC, sayboras commented
/test

2023-01-23 02:00 UTC, sayboras commented
/test

2023-02-02 23:02 UTC, christarazi requested changes

2023-02-02 23:02 UTC, christarazi commented on bugtool/cmd/root.go
> +				fmt.Fprintf(os.Stderr, "Unable to retrieve envoy prometheus metrics: %s\n", err)
Nit: Most files are with `-` instead of `_`.

2023-02-03 06:15 UTC, christarazi approved these changes

2023-02-03 06:42 UTC, sayboras commented
Full CI is not required, review from required team is in. Marking this ready to merge.

<details>
<summary>Sample envoy-metrics.txt from sysdump</summary>

```
# TYPE envoy_cluster_assignment_stale counter
envoy_cluster_assignment_stale{envoy_cluster_name="default/details_9080"} 0
envoy_cluster_assignment_stale{envoy_cluster_name="default/productpage_9080"} 0
envoy_cluster_assignment_stale{envoy_cluster_name="egress-cluster"} 0
envoy_cluster_assignment_stale{envoy_cluster_name="egress-cluster-tls"} 0
envoy_cluster_assignment_stale{envoy_cluster_name="envoy-admin"} 0
envoy_cluster_assignment_stale{envoy_cluster_name="ingress-cluster"} 0
envoy_cluster_assignment_stale{envoy_cluster_name="ingress-cluster-tls"} 0
envoy_cluster_assignment_stale{envoy_cluster_name="xds-grpc-cilium"} 0

# TYPE envoy_cluster_assignment_timeout_received counter
envoy_cluster_assignment_timeout_received{envoy_cluster_name="default/details_9080"} 0
envoy_cluster_assignment_timeout_received{envoy_cluster_name="default/productpage_9080"} 0
envoy_cluster_assignment_timeout_received{envoy_cluster_name="egress-cluster"} 0
envoy_cluster_assignment_timeout_received{envoy_cluster_name="egress-cluster-tls"} 0
envoy_cluster_assignment_timeout_received{envoy_cluster_name="envoy-admin"} 0
envoy_cluster_assignment_timeout_received{envoy_cluster_name="ingress-cluster"} 0
envoy_cluster_assignment_timeout_received{envoy_cluster_name="ingress-cluster-tls"} 0
envoy_cluster_assignment_timeout_received{envoy_cluster_name="xds-grpc-cilium"} 0

# TYPE envoy_cluster_bind_errors counter
envoy_cluster_bind_errors{envoy_cluster_name="default/details_9080"} 0
envoy_cluster_bind_errors{envoy_cluster_name="default/productpage_9080"} 0
envoy_cluster_bind_errors{envoy_cluster_name="egress-cluster"} 0
envoy_cluster_bind_errors{envoy_cluster_name="egress-cluster-tls"} 0
envoy_cluster_bind_errors{envoy_cluster_name="envoy-admin"} 0
envoy_cluster_bind_errors{envoy_cluster_name="ingress-cluster"} 0
envoy_cluster_bind_errors{envoy_cluster_name="ingress-cluster-tls"} 0
envoy_cluster_bind_errors{envoy_cluster_name="xds-grpc-cilium"} 0

# TYPE envoy_cluster_control_plane_rate_limit_enforced counter
envoy_cluster_control_plane_rate_limit_enforced{envoy_cluster_name="default/details_9080"} 0
envoy_cluster_control_plane_rate_limit_enforced{envoy_cluster_name="default/productpage_9080"} 0

# TYPE envoy_cluster_default_total_match_count counter
envoy_cluster_default_total_match_count{envoy_cluster_name="default/details_9080"} 0
envoy_cluster_default_total_match_count{envoy_cluster_name="default/productpage_9080"} 0
envoy_cluster_default_total_match_count{envoy_cluster_name="egress-cluster"} 0
envoy_cluster_default_total_match_count{envoy_cluster_name="egress-cluster-tls"} 0
envoy_cluster_default_total_match_count{envoy_cluster_name="envoy-admin"} 1
envoy_cluster_default_total_match_count{envoy_cluster_name="ingress-cluster"} 0
envoy_cluster_default_total_match_count{envoy_cluster_name="ingress-cluster-tls"} 0
envoy_cluster_default_total_match_count{envoy_cluster_name="xds-grpc-cilium"} 1

# TYPE envoy_cluster_http2_dropped_headers_with_underscores counter
envoy_cluster_http2_dropped_headers_with_underscores{envoy_cluster_name="xds-grpc-cilium"} 0

# TYPE envoy_cluster_http2_header_overflow counter
envoy_cluster_http2_header_overflow{envoy_cluster_name="xds-grpc-cilium"} 0

# TYPE envoy_cluster_http2_headers_cb_no_stream counter
envoy_cluster_http2_headers_cb_no_stream{envoy_cluster_name="xds-grpc-cilium"} 0

# TYPE envoy_cluster_http2_inbound_empty_frames_flood counter
envoy_cluster_http2_inbound_empty_frames_flood{envoy_cluster_name="xds-grpc-cilium"} 0

# TYPE envoy_cluster_http2_inbound_priority_frames_flood counter
envoy_cluster_http2_inbound_priority_frames_flood{envoy_cluster_name="xds-grpc-cilium"} 0

# TYPE envoy_cluster_http2_inbound_window_update_frames_flood counter
envoy_cluster_http2_inbound_window_update_frames_flood{envoy_cluster_name="xds-grpc-cilium"} 0

# TYPE envoy_cluster_http2_keepalive_timeout counter
envoy_cluster_http2_keepalive_timeout{envoy_cluster_name="xds-grpc-cilium"} 0

# TYPE envoy_cluster_http2_metadata_empty_frames counter
envoy_cluster_http2_metadata_empty_frames{envoy_cluster_name="xds-grpc-cilium"} 0

# TYPE envoy_cluster_http2_outbound_control_flood counter
envoy_cluster_http2_outbound_control_flood{envoy_cluster_name="xds-grpc-cilium"} 0

# TYPE envoy_cluster_http2_outbound_flood counter
envoy_cluster_http2_outbound_flood{envoy_cluster_name="xds-grpc-cilium"} 0

# TYPE envoy_cluster_http2_requests_rejected_with_underscores_in_headers counter
envoy_cluster_http2_requests_rejected_with_underscores_in_headers{envoy_cluster_name="xds-grpc-cilium"} 0

# TYPE envoy_cluster_http2_rx_messaging_error counter
envoy_cluster_http2_rx_messaging_error{envoy_cluster_name="xds-grpc-cilium"} 0

# TYPE envoy_cluster_http2_rx_reset counter
envoy_cluster_http2_rx_reset{envoy_cluster_name="xds-grpc-cilium"} 0

# TYPE envoy_cluster_http2_stream_refused_errors counter
envoy_cluster_http2_stream_refused_errors{envoy_cluster_name="xds-grpc-cilium"} 0

# TYPE envoy_cluster_http2_trailers counter
envoy_cluster_http2_trailers{envoy_cluster_name="xds-grpc-cilium"} 0

# TYPE envoy_cluster_http2_tx_flush_timeout counter
envoy_cluster_http2_tx_flush_timeout{envoy_cluster_name="xds-grpc-cilium"} 0

# TYPE envoy_cluster_http2_tx_reset counter
envoy_cluster_http2_tx_reset{envoy_cluster_name="xds-grpc-cilium"} 0

# TYPE envoy_cluster_init_fetch_timeout counter
envoy_cluster_init_fetch_timeout{envoy_cluster_name="default/details_9080"} 0
envoy_cluster_init_fetch_timeout{envoy_cluster_name="default/productpage_9080"} 0

# TYPE envoy_cluster_internal_upstream_rq counter
envoy_cluster_internal_upstream_rq{envoy_response_code="200",envoy_cluster_name="xds-grpc-cilium"} 3

# TYPE envoy_cluster_internal_upstream_rq_completed counter
envoy_cluster_internal_upstream_rq_completed{envoy_cluster_name="xds-grpc-cilium"} 3

# TYPE envoy_cluster_internal_upstream_rq_xx counter
envoy_cluster_internal_upstream_rq_xx{envoy_response_code_class="2",envoy_cluster_name="xds-grpc-cilium"} 3

# TYPE envoy_cluster_lb_healthy_panic counter
envoy_cluster_lb_healthy_panic{envoy_cluster_name="default/details_9080"} 0
envoy_cluster_lb_healthy_panic{envoy_cluster_name="default/productpage_9080"} 0
envoy_cluster_lb_healthy_panic{envoy_cluster_name="egress-cluster"} 0
envoy_cluster_lb_healthy_panic{envoy_cluster_name="egress-cluster-tls"} 0
envoy_cluster_lb_healthy_panic{envoy_cluster_name="envoy-admin"} 0
envoy_cluster_lb_healthy_panic{envoy_cluster_name="ingress-cluster"} 0
envoy_cluster_lb_healthy_panic{envoy_cluster_name="ingress-cluster-tls"} 0
envoy_cluster_lb_healthy_panic{envoy_cluster_name="xds-grpc-cilium"} 0

# TYPE envoy_cluster_lb_local_cluster_not_ok counter
envoy_cluster_lb_local_cluster_not_ok{envoy_cluster_name="default/details_9080"} 0
envoy_cluster_lb_local_cluster_not_ok{envoy_cluster_name="default/productpage_9080"} 0
envoy_cluster_lb_local_cluster_not_ok{envoy_cluster_name="egress-cluster"} 0
envoy_cluster_lb_local_cluster_not_ok{envoy_cluster_name="egress-cluster-tls"} 0
envoy_cluster_lb_local_cluster_not_ok{envoy_cluster_name="envoy-admin"} 0
envoy_cluster_lb_local_cluster_not_ok{envoy_cluster_name="ingress-cluster"} 0
envoy_cluster_lb_local_cluster_not_ok{envoy_cluster_name="ingress-cluster-tls"} 0
envoy_cluster_lb_local_cluster_not_ok{envoy_cluster_name="xds-grpc-cilium"} 0

# TYPE envoy_cluster_lb_recalculate_zone_structures counter
envoy_cluster_lb_recalculate_zone_structures{envoy_cluster_name="default/details_9080"} 0
envoy_cluster_lb_recalculate_zone_structures{envoy_cluster_name="default/productpage_9080"} 0
envoy_cluster_lb_recalculate_zone_structures{envoy_cluster_name="egress-cluster"} 0
envoy_cluster_lb_recalculate_zone_structures{envoy_cluster_name="egress-cluster-tls"} 0
envoy_cluster_lb_recalculate_zone_structures{envoy_cluster_name="envoy-admin"} 0
envoy_cluster_lb_recalculate_zone_structures{envoy_cluster_nam [...]

2023-02-03 22:30 UTC, merged