v1.12 backports 2023-01-06
cilium/cilium pull request #22964
Opened 2023-01-06 17:59 UTC by gentoo-root

Backporting [two fixes](https://github.com/cilium/cilium/pull/21871#issuecomment-1369471208) from my internalTrafficPolicy pull request to 1.12.

2023-01-06 20:13 UTC, christarazi commented
Could you update the PR description to match with other [backport](https://github.com/cilium/cilium/pull/22563) PRs? The automation relies on all the formatting inside in the PR description, as described in https://docs.cilium.io/en/v1.12/contributing/release/backports/#via-github-web-interface.

2023-01-06 20:39 UTC, christarazi commented
No worries :)

I see the slight dilemma now. I think it might be confusing to consider https://github.com/cilium/cilium/pull/21871 backported because the changelog will mention that the PR is now in v1.12, which is not true. That's alright for now, no need to update this PR anymore. 

Just a note for the future, typically if you have some smaller fixes in bigger PRs that deserve to be backported, we would create a separate PR so that those fixes can be backported alone, without having to do a partial backport of the large PR. It makes tracking easier.

2023-01-07 00:35 UTC, aditighag commented
/test-backport-1.12

2023-01-09 11:19 UTC, pchaigno requested changes
I don't think we can backport that second commit because it has an impact on the policies (cf. https://github.com/cilium/cilium/pull/22927).

2023-01-10 11:56 UTC, pchaigno approved these changes

2023-01-10 11:56 UTC, pchaigno commented
/test-backport-1.12

2023-01-13 14:13 UTC, ti-mo commented
/test-runtime

2023-01-13 14:51 UTC, ti-mo approved these changes

2023-01-13 16:23 UTC, merged

2023-01-16 07:24 UTC, julianwiedmann commented on pkg/k8s/init.go
> +		}
Sorry for not getting to this earlier.

Looking at the v1.12 code, I think we would have actually been fine - there `SetK8sExternalIPv6()` merely updates `addrs.ipv6ExternalAddress`, without any further side effects. But this change shouldn't cause any harm either, so no need to back it out again.