Optimization logs with entire identity object
cilium/cilium pull request #22971
Opened 2023-01-08 11:33 UTC by yulng

Printing the entire structure of the identity in the log makes the log hard to read ,so branch printing

Signed-off-by: yulng <wei.yang@daocloud.io>

2023-01-09 10:59 UTC, kaworu reviewed
Hi @yulng and thanks for the PR

> Printing the entire structure of the identity in the log makes the log hard to read ,so branch printing

As far as I can see the patch is cosmetic only and introduce no functional change. If correct then I don't understand the commit message, what is "branch printing"?

2023-01-10 06:54 UTC, yulng commented
> 

It is printed line by line, unified style, easy to view
thanks

2023-01-19 16:54 UTC, christarazi requested changes
Since this change is purely cosmetic, can you reword the commit to 

```
Make log statements easier to read

This is a cosmetic change to break up long log lines into smaller lines.
```

2023-01-20 14:50 UTC, yulng commented
> Since this change is purely cosmetic, can you reword the commit to
> 
> ```
> Make log statements easier to read
> 
> This is a cosmetic change to break up long log lines into smaller lines.
> ```
Push again and update the commit
Thanks

2023-01-23 08:34 UTC, kaworu approved these changes

2023-01-23 21:33 UTC, christarazi approved these changes

2023-01-23 21:33 UTC, christarazi commented
/test

2023-01-25 15:07 UTC, merged