metrics: Remove unused ARP ping metrics
cilium/cilium pull request #23057
Opened 2023-01-12 10:09 UTC by brb

794ce347d1e ("neigh: Rework ARP handling to let the kernel do the resolution") removed the manual arpings which made the metrics obsolete.

2023-01-12 21:15 UTC, chancez requested changes
Should probably mention this in the upgrade notes. Otherwise LGTM.

2023-01-13 08:37 UTC, brb commented
> Should probably mention this in the upgrade notes.

Good point, updated.

2023-01-13 15:14 UTC, qmonnet approved these changes
Looks good, thanks

2023-01-13 19:36 UTC, chancez approved these changes

2023-01-19 13:43 UTC, ldelossa commented
@brb should this PR skip the test suite?

2023-01-23 09:18 UTC, brb commented
> @brb should this PR skip the test suite?

@ldelossa The conformance test suite is enough to validate the change.

2023-01-23 16:32 UTC, merged