Make cilium pprof listen address configurable
cilium/cilium pull request #23094
Opened 2023-01-13 18:24 UTC by chancez

* #22768 -- Make cilium pprof listen address configurable (@chancez)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 22768 ; do contrib/backporting/set-labels.py $pr done 1.12; done
```

2023-01-20 12:40 UTC, ti-mo approved these changes
No longer TH, but I'll rubber-stamp anyway. :wink: Thanks!

2023-01-24 01:22 UTC, joestringer requested changes

2023-01-24 01:22 UTC, joestringer commented on pkg/option/config.go
> -	c.MTU = viper.GetInt(MTUName)
Was this change in the original PR? Please double-check that the backported version matches the original.

2023-01-24 01:30 UTC, joestringer commented
One more note: the referenced "upstream commit" in the commit message isn't a canonical commit in the upstream branch. Did you cherry-pick that from a local branch? Ideally that should point to the actual merged upstream commit rather than another version, since that also allows back-referencing to the original PR etc. and helps with ensuring that the correct content of the commit was backported as the one that was accepted upstream.

2023-01-24 20:54 UTC, chancez commented
@joestringer ah your right on both counts. I've corrected both of these and took another look, and adde a back porters note in the commit message as well.

2023-01-25 04:00 UTC, joestringer approved these changes

2023-01-25 04:00 UTC, merged