Ignore containers not managed by cilium
cilium/cilium pull request #231
Opened 2016-12-19 13:09 UTC by tgraf

2016-12-19 14:24 UTC, aanm requested changes
Needs a mutex for the map.

2016-12-19 14:30 UTC, tgraf commented
How are you ensuring concurrency in `updateContainer` at all? This needs more than just a mutex around the map.

2016-12-19 14:35 UTC, aanm commented
All stuff inside `updateContainer` are "concurrency-free". For example `d.setEndpointSecLabel` has a lock inside of it.

2016-12-19 14:40 UTC, tgraf commented
That's not enough. The same ID can be handled by multiple go routes which then call `setEndpointSecLabel()` on the same ID. Although the lock avoids parallelism of `setEndpointSecLabel()` itself, it does not avoid multiple calls to `setEndpointSecLabel()` which then leaves stale entries in the endpoints table.

2016-12-20 19:09 UTC, aanm requested changes

2016-12-20 19:09 UTC, aanm commented on daemon/daemon/daemon.go
> +	if _, ok := d.ignoredContainers[id]; ok {
Since the value is not a pointer you can directly do.
```go
d.ignoredContainers[id]++
```

2016-12-22 01:53 UTC, aanm approved these changes

2016-12-22 07:05 UTC, merged