.github: Pin docker buildx version to v0.9.1 (v2)
cilium/cilium pull request #23220
Opened 2023-01-20 18:57 UTC by joestringer

GitHub recently rolled out Docker buildx version v0.10.0 on their
builders, which transparently changed the MediaType of docker images to
OCI v1 and added provenance attestations.

Unfortunately, various tools we use in CI like SBOM tooling and docker
manifest inspect do not properly support some aspect of the new image
formats. This resulted in breaking CI, with some messages like this:

    level=fatal msg="generating doc: creating SPDX document: generating
    SPDX package from image ref quay.io/cilium/docker-plugin-ci:XXX:
    generating image package"

This could also lead CI to fail while waiting for image builds to
complete, because the command we use to test whether the image is
available did not support the image types.

This commit attempts to revert buildx back to v0.9.1 to prevent it from
generating the images in a format that other tooling doesn't expect.
Over time we can work on migrating to buildx v0.10, testing various
parts of our CI as we do so.

This is a quick-and-dirty hack to stabilize CI for the short term, then
we can figure out over time how to properly resolve the conflict between
these systems.

Reverts https://github.com/cilium/cilium/pull/23206

2023-01-20 18:58 UTC, michi-covalent approved these changes

2023-01-20 19:00 UTC, ldelossa approved these changes
v3's the charm ;)

2023-01-20 19:02 UTC, joestringer commented
Thanks to @chancez for pointing out why the `version` shouldn't have worked on the previous PR, originally https://github.com/cilium/cilium/pull/23206 was trying to update the `docker/build-push-action` configuration for provenance (which didn't worK). When I switched to configuring version, I thought it was the same action. However, `version` is only configured on the `docker/setup-buildx-action`. So hopefully this actually pins the version this time.

2023-01-20 19:15 UTC, chancez approved these changes
Yep looks like the right spot!

2023-01-20 19:32 UTC, aanm requested changes
Should we revert the SBOM revert PR here?

2023-01-20 19:40 UTC, joestringer commented
@aanm I was hoping to follow up on that separately once we confirmed that this is switching CI back to generating images in the older / supported format

2023-01-20 19:46 UTC, merged

2023-01-20 20:26 UTC, joestringer commented
@aanm https://github.com/cilium/cilium/pull/23221

2023-01-24 17:41 UTC, tommyp1ckles commented
@joestringer FYI, you can also work around this by doing `docker buildx imagetools inspect --raw quay.io/cilium/cilium-ci:10e55d6053762d098cce06cd97abd51afc6faf0f` (credit goes to @pippolo84)

Are we ok to backport this to v1.11, CI is broken over there as well.