Cleanup: improve metav1 package import statement
cilium/cilium pull request #23248
Opened 2023-01-23 13:17 UTC by my-git9

Improve metav1 package import statement

2023-01-23 13:46 UTC, gandro commented
Thanks for the PR! It seems there are some build failures, could you please address them:

https://github.com/cilium/cilium/actions/runs/3986769699/jobs/6835733649#step:9:134

2023-01-23 13:47 UTC, gandro requested changes

2023-01-23 13:47 UTC, gandro commented on pkg/k8s/slim/k8s/client/clientset/versioned/typed/discovery/v1beta1/endpointslice.go
> +	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
These files are auto-generated, as the header states. Please do not edit them.

2023-01-23 16:57 UTC, gandro approved these changes

2023-01-23 16:58 UTC, gandro commented
/test

2023-01-23 21:21 UTC, christarazi requested changes
Thanks for the PR. In the commit body, can you say "This commit contains no functional changes."?

2023-01-24 02:38 UTC, my-git9 commented
> Thanks for the PR. In the commit body, can you say "This commit contains no functional changes."?

Updated. Thanks ~

2023-01-24 04:55 UTC, christarazi approved these changes

2023-01-24 04:56 UTC, christarazi commented
/test

2023-01-24 23:37 UTC, my-git9 commented
/test

2023-01-25 07:14 UTC, christarazi commented
Marking ready to merge as we have approving reviews and CI has passed except for known flakes.

2023-01-25 15:06 UTC, merged