Add requirements for Raspberry Pi
cilium/cilium pull request #23337
Opened 2023-01-25 10:34 UTC by darox

Add documentation for running Cilium on a Raspberry Pi.

Signed-off-by: darox <9934402+darox@users.noreply.github.com>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note

```

2023-01-25 10:45 UTC, gentoo-root requested changes

2023-01-25 10:45 UTC, gentoo-root commented on Documentation/operations/system_requirements.rst
> +        sudo apt install linux-modules-extra-$(uname -r)
This looks specific to Raspberry Pi OS (ex Raspbian), while Raspberry Pi can run a variety of other Linux distributions, which may not need this command ([seems openSUSE doesn't need it](https://cilium.slack.com/archives/C53TG4J4R/p1674098237654269?thread_ts=1674036780.656589&cid=C53TG4J4R); I suppose, ArchLinuxARM doesn't need it either).

Another thought: as Raspberry Pi OS is based on Debian, and packages are built in a similar way, there is a chance this package might also be needed on other Debian-based distributions, not necessarily running on Raspberry Pi. Do you happen to know what specific kernel module was missing before installing this package?

2023-01-25 11:22 UTC, qmonnet requested changes

2023-01-25 11:22 UTC, qmonnet commented on Documentation/operations/system_requirements.rst
> +~~~~~~~~~~~~
Netflify preview currently breaks on this:

```suggestion
Ubuntu 22.04 on Raspberry Pi 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2023-01-25 11:23 UTC, qmonnet commented
Please, can you also consider using a real email address in the commit's `Signed-off-by:` tag? Although this doesn't happen often, we've had to reach out to some contributors in the past.

2023-01-25 13:22 UTC, darox commented
> Please, can you also consider using a real email address in the commit's `Signed-off-by:` tag? Although this doesn't happen often, we've had to reach out to some contributors in the past.

Done

2023-01-25 16:16 UTC, gentoo-root commented on Documentation/operations/system_requirements.rst
> +        sudo apt install linux-modules-extra-$(uname -r)
```suggestion
        sudo apt install linux-modules-extra-raspi
```

As far as I understand (correct me if I'm wrong), linux-modules-extra-raspi pulls in the latest version of linux-modules-extra-*, updating it automatically with kernel updates. If you just install `linux-modules-extra-$(uname -r)`, Cilium will break again after a kernel update.

(Also I checked Ubuntu for amd64, and it doesn't require linux-modules-extra for xfrm_user and xfrm_interfaces, which were [apparently missing here](https://github.com/cilium/cilium/issues/20735#issuecomment-1201744660), so the "Ubuntu 22.04 on Raspberry Pi" header looks good to me.)

2023-01-25 16:24 UTC, qmonnet approved these changes
Thanks! Looks good to me assuming Maxim's comment gets addressed

2023-01-25 17:21 UTC, gentoo-root approved these changes
Thanks!

2023-01-26 04:11 UTC, YutaroHayakawa approved these changes

2023-01-29 22:38 UTC, merged

2023-02-19 08:18 UTC, fmunteanu commented
@darox your documentation covers only Ubuntu, what about default RaspiOS?

2023-02-21 08:10 UTC, darox commented
> @darox your documentation covers only Ubuntu, what about default RaspiOS?

I expect the default OS to require the same package. However, I don't have one at hand to test it.

2023-02-21 14:08 UTC, fmunteanu commented
@darox it does not. This is a major roadblock since the kernel developers will not modify it, just to accommodate a third party app, as they describe Cilium. And they are correct. Right now RaspiOS users need to recompile the kernel, in order to accommodate the Cilium requirements, which is unrealistic for updates. I opened https://github.com/cilium/cilium/issues/23640 with Cilium.

2023-02-21 14:31 UTC, darox commented
I didnt't know that. Thank you for the clarification.

2023-02-21 14:33 UTC, fmunteanu commented
@darox not sure if you could help bring this to the attention of Cilium devs, it should be an easy fix.

2023-03-07 23:19 UTC, joestringer commented
@fmunteanu Is there some change that you could propose as a PR? It's not clear to me how Cilium interacts with the kernel flag `CONFIG_ARM64_VA_BITS_39`.

2023-03-08 19:25 UTC, fmunteanu commented
@joestringer is it possible to continue this discussion into https://github.com/cilium/cilium/issues/23640?

2023-03-08 19:40 UTC, joestringer commented
@fmunteanu ah yes, that would be better than discussing on this PR. :+1: