docs,daemon: Added discouragement warnings for MetalLB to docs and agent
cilium/cilium pull request #23393
Opened 2023-01-26 15:25 UTC by dylandreimerink

Added warnings explaining that development on the MetalLB based BGP feature has stopped. The feature will not be deprecated in 1.13, so noted that security updates and bugfixes will still be applied.

Even though we can't officially deprecate yet, we would like to highly discourage adoption of the old feature unless absolutely necessary.

Fixes: #22246

Signed-off-by: Dylan Reimerink <dylan.reimerink@isovalent.com>

```release-note
 Added discouragement warnings for MetalLB to docs and agent
```

2023-01-26 17:36 UTC, joestringer reviewed
Might be worth noting the URL so users can more easily follow up?

Otherwise LGTM thanks!

2023-01-26 17:36 UTC, joestringer commented on daemon/cmd/daemon.go
> +			"Its recommended you migrate to the BGP Control Plane feature if possible, which enjoys better support.")
.WithFields(logrus.Fields{logfields.URL, "https://github.com/cilium/cilium/issues/22246")) ?

2023-01-26 17:36 UTC, joestringer commented on Documentation/network/bgp.rst
> +  possible.
```suggestion
  possible. More details are available at :gh-issue:`22246`.
```

2023-01-27 09:55 UTC, pippolo84 approved these changes
:100:

2023-01-27 11:48 UTC, qmonnet requested changes

2023-01-27 11:48 UTC, qmonnet commented on daemon/cmd/daemon.go
> +				"Its recommended you migrate to the BGP Control Plane feature if possible, which enjoys better support.")
```suggestion
				"It is recommended to migrate to the BGP Control Plane feature if possible, which has better support.")
```
`Its` is incorrect here, the other changes are just suggestions that you can ignore if you prefer.

2023-01-27 13:03 UTC, qmonnet approved these changes
Thanks!

2023-01-27 13:04 UTC, qmonnet commented
Reading the description, you can probably remove the `release-blocker` label?

2023-01-27 13:05 UTC, dylandreimerink commented
> Reading the description, you can probably remove the release-blocker label?

I marked it as such since the original issue is also a release blocker and we would like this message to be there in the 1.13 docs. 

CC @joestringer

2023-01-27 21:45 UTC, joestringer approved these changes

2023-01-30 08:52 UTC, dylandreimerink commented
/test

2023-02-01 14:54 UTC, dylandreimerink commented
/test

2023-02-01 17:54 UTC, dylandreimerink commented
Alright, its not getting better then this I guess. All reviews are in, CI green except for 2 tests which both hit flake #22019.

Marking as ready-to-merge

2023-02-01 21:23 UTC, merged