tools: cluster-wide troubleshooting tool
cilium/cilium pull request #2348
Opened 2017-12-15 22:08 UTC by ashwinp

- The tool identifies the most commonly observed errors.
- It performs various checks (k8s, cilium) and provides hints
to fix specific issues that it has identified.
- The ModuleCheck class implements the basic notion of a check.
It is pluggable in the sense that it can be extended to change
the default on-success and on-failure actions.
- The ModuleCheckGroup class provides a grouping construct for
grouping related ModuleChecks. The ModuleChecks in a ModuleCheckGroup are
run in a serial manner. The execution of a ModuleCheckGroup
terminates on the first ModuleCheck failure. In other words, if a
ModuleCheck fails, all subsequent ModuleChecks in the group will be
skipped.
- The initial commit contains two ModuleCheckGroups. One for Kubernetes
checks, and the other for Cilium specific checks.

Signed-off-by: Ashwin Paranjpe <ashwin@covalent.io>

**Summary of changes**:

Fixes: #issue-number

```release-note

```

**How to test (optional)**:
e.g. Run `make tests`, `make runtime-tests` and/or some more specific way to
exercise the new behavior(s).
Note: [The runtime testsuite will modify the host it runs on.](http://cilium.readthedocs.io/en/latest/contributing/#testsuite)

2017-12-15 22:54 UTC, aalemayhu requested changes
LGTM, some minor things. Can you split the author file change into a separate commit? Would also git ignore the *.zip.

2017-12-15 23:08 UTC, ashwinp commented
@scanf Done. Unstaged the `AUTHOR` file changes. Updated `.gitignore`.

2017-12-18 10:23 UTC, tgraf commented
Tool looks great. We need to figure out how users should be running this, we have a couple of options:

1. Include it in the `cilium/cilium` image and provide a static binary with this tool embedded (using cpython or similar). This binary should also be released on github so non container image users can just run the plain binary.
2. Provide a separate container image which only includes this tool and starts it automatically. This could be achieved by putting this in a completely separate repo and refer to it from the docs or by including this via a special tag that is based on a separate `Dokerfile`, e.g. `cilium/cilium:cluster-debug`

@cilium/team Thoughts?

2017-12-18 19:28 UTC, ashwinp commented
@tgraf Thanks for the review. I like the idea #2 (shipping this as a separate container), but I'd like to propose that we consider separating the packaging and delivery strategy (how will the user download and run the tool) in a separate PR. For now, we can build and upload the zip file to a publicly accessible location, which the users can download and simply run using the `python clusterdebug.zip` command. I've submitted a separate PR for the docs update here: https://github.com/cilium/cilium/pull/2356. As can be seen in that PR, there is TODO, which will be fixed after we upload the zip file. Please let me know your thoughts about this. Thanks.

2017-12-19 13:03 UTC, scanf commented on clusterdebug-tool/clusterdebug/utils.py
> +    logging.addLevelName(
Why are you using the same color for both warning and error?

2017-12-19 13:29 UTC, tgraf commented
> Thanks for the review. I'd like to propose that we consider separating the packaging and delivery strategy (how will the user download and run the tool) in a separate PR. For now, we can build and upload the zip file to a publicly accessible location, which the users can download and simply run using the python clusterdebug.zip command. I've submitted a separate PR for the docs update here: #2356. As can be seen in that PR, there is TODO, which will be fixed after we upload the zip file. Please let me know your thoughts about this. Thanks.

That's fine. I want to make sure we don't just merge & forget.

2017-12-19 13:38 UTC, aalemayhu approved these changes

2017-12-19 14:12 UTC, tgraf approved these changes

2017-12-19 14:13 UTC, merged