ci: pin managed clusters' K8s version to 1.24
cilium/cilium pull request #23573
Opened 2023-02-03 14:33 UTC by nbusseneau

Cilium `master` officially supports up to K8s 1.26. However, the cloud providers do not support creating managed clusters with K8s 1.26:

- AKS: 1.24 tops (1.25 in preview).
- EKS: 1.24 tops.
- GKE: 1.25 tops.

We pin CI workflows for the stable branch to use K8s 1.24 when creating managed clustersas it is the lowest common supported version.

This version should be updated as appropriate when new K8s versions are supported by the cloud providers.

Resources:

- AKS
  - Run `az aks get-versions --location westeurope --output table`
  - https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions

- EKS
  - Run `eksctl version -o json | jq -r '.EKSServerSupportedVersions[]'` (note: this asssumes `eksctl` is up to date, as this is static info)
  - https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
  - https://eksctl.io/usage/schema/#metadata-version

- GKE
  - Run `gcloud container get-server-config --format="yaml(channels)"`
  - https://cloud.google.com/kubernetes-engine/versioning
  - https://cloud.google.com/kubernetes-engine/docs/release-schedule

[Note:

The GKE workflow was already pinned to 1.24 to fix the CI, via a77007aa44893be9894311e2546529c6e3968865 and later 1ce7f1f097731fa175a6bdee399413cc370450b5.]

2023-02-03 15:33 UTC, aanm requested changes
From https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar it looks that k8s 1.25 is already GA since December so we should probably use that one.

2023-02-03 16:26 UTC, nbusseneau commented
You're right, it's now GA, but as said in the commit description: 

> We pin CI workflows for the stable branch to use K8s 1.24 when creating managed clustersas it is the lowest common supported version.

This is also the principle that was applied for 1.13. Should we change that? I think consistency between the platforms is better, but this can be discussed.

2023-02-03 22:40 UTC, christarazi approved these changes

2023-02-06 17:53 UTC, nbusseneau commented
Links to test runs of the workflow files:

- https://github.com/cilium/cilium/actions/runs/4086016474
- https://github.com/cilium/cilium/actions/runs/4086016456
- https://github.com/cilium/cilium/actions/runs/4086016468
- https://github.com/cilium/cilium/actions/runs/4086016454
- https://github.com/cilium/cilium/actions/runs/4086016453

CI passed, removing test commit.

2023-02-20 15:36 UTC, aanm requested changes
@nbusseneau we should be _inconsistent_ so that we can have good coverage across multiple k8s versions. If we pin it to a single k8s version for all cloud providers then we don't gain that.

2023-04-04 15:50 UTC, nbusseneau commented
/test-1.26-net-next

2023-04-04 16:53 UTC, pchaigno commented
> @nbusseneau we should be _inconsistent_ so that we can have good coverage across multiple k8s versions. If we pin it to a single k8s version for all cloud providers then we don't gain that.

I'm not sure I agree. I understand the idea, but maybe here it's better to always use the latest k8s version as we do in the bpf-next CI job. That way we ensure that, for each cloud provider, we will have tested all versions at some point in the past.
If we want to cover all k8s versions we support, it sounds like a job for a dedicated workflow; we don't have enough cloud providers to support all k8s versions anyway.

2023-04-05 14:18 UTC, nbusseneau commented
/test-1.26-net-next

2023-06-02 02:03 UTC, closed without merging