pass `make -C test/ run_bpf_tests` with recent llvm
cilium/cilium pull request #23582
Opened 2023-02-05 15:15 UTC by nickolaev

I am using Ubuntu 22.04 with the default clang being 11.x. When trying to run the
bpf tests with `make -C test/ run_bpf_tests` I got into a series of bpf verifier errors.

The problem was hitting verifier "corner case" (as described in the StackOverflow discussions below), where we needed to convince the verifier we are not getting past the packet boundary. I also used the occasion to modify all `curr_off > MAX_PACKET_OFF - sizeof(whatever)` to `curr_off + sizeof(whatever) > MAX_PACKET_OFF`; I believe this is less confusing for both the verifier and the humans involved.

**Stack Overflow references used to figure out the fix**

https://stackoverflow.com/questions/70729664/need-help-in-xdp-program-failing-to-load-with-error-r7-offset-is-outside-of-the/70731589#70731589

https://stackoverflow.com/questions/67402772/bpf-verifier-rejects-when-try-to-access-sk-buff-member

```release-note
Enable running the bpf tests locally with recent llvm
```

2023-02-05 15:24 UTC, pchaigno commented
/test

2023-02-06 23:04 UTC, pchaigno commented
/test

2023-02-07 16:32 UTC, gentoo-root requested changes

2023-02-07 16:32 UTC, gentoo-root commented on bpf/tests/pktgen.h
> -			if (layer_off >= MAX_PACKET_OFF - sizeof(struct ethhdr))
> I believe this is less confusing for both the verifier and the humans involved.

I think it was written like this as a precaution to avoid an undesired overflow when adding two u16s, but it's not really needed, integer promotion will do the thing, so your change looks good.

Could you, however, make it a separate commit? It's more of a style fix, it doesn't affect the verifier corner case that you are fixing here, and I don't expect any functional change, so it's better to have it as a separate commit, it will help pinpoint potential unexpected issues.

2023-02-07 16:32 UTC, gentoo-root commented on bpf/tests/pktgen.h
> +		return 0;
I think it's useful to put a short explanation of the verifier corner case to the commit message, along with a [pointer](https://elixir.bootlin.com/linux/v5.16.1/source/kernel/bpf/verifier.c#L8435) to the Linux code.

> bpf: test: reorder stuff to make verifier happy wiht recent llvm

Typo: wiht -> with.

Do you happen to know why it's only relevant for recent LLVM? If yes, could you also add this info to the commit message?

2023-02-07 16:32 UTC, gentoo-root commented on bpf/tests/pktgen.h
> +	if (builder->cur_off + sizeof(struct ethhdr) >= MAX_PACKET_OFF)
While at it, I think, `>` should actually be enough, what do you think?

2023-02-08 20:28 UTC, nickolaev commented
OK, the underlying problem is somewhere else. We are in discussion with @dylandreimerink and to rootcause it and find a proper solution.
Closing this one now as obsolete.

2023-02-08 20:28 UTC, closed without merging