bpf, ebpf: remove GetMapType() and mock probing
cilium/cilium pull request #23634
Opened 2023-02-08 12:58 UTC by rgo3

As a follow up to #20556 and in line with cleaning up 4.9 leftovers[1] this removes GetMapType() which was only useful on 4.9 kernels. Removing GetMapType() allows removing leftover dependencies on ProbeManger.

[1] #22116

Fixes: #21214

Signed-off-by: Robin Gögge <r.goegge@isovalent.com>

2023-02-08 19:48 UTC, rgo3 commented
/test

2023-02-10 14:57 UTC, rgo3 commented
ci-multicluster hit #21655, given the changes test-1.16-4.9 is expected to fail. Removing draft status.

2023-02-16 21:15 UTC, rgo3 commented
/test

2023-02-24 17:06 UTC, gentoo-root requested changes

2023-02-24 17:06 UTC, gentoo-root commented on pkg/bpf/map_linux_test.go
> +	}()
preallocMap below also needs to be unpinned and closed (at least it was done before this commit).

2023-02-27 09:49 UTC, rgo3 commented on pkg/bpf/map_linux_test.go
> +	}()
The `preallocMap` is actually never more than a go object, that's why I removed cleaning it up.

2023-02-27 16:23 UTC, gentoo-root approved these changes

2023-02-27 16:23 UTC, gentoo-root commented on pkg/bpf/map_linux_test.go
> +	}()
Ah, OK then.

2023-02-28 08:54 UTC, rgo3 commented
/test

2023-03-01 13:47 UTC, rgo3 commented
/test

2023-03-03 11:39 UTC, julianwiedmann approved these changes

2023-03-03 13:22 UTC, merged