Implement support of annotations in hubble ui service manifest
cilium/cilium pull request #23659
Opened 2023-02-10 11:16 UTC by brnck

Signed-off-by: brnck <a.berneckas@gmail.com>

Please ensure your pull request adheres to the following guidelines:

- [X] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [X] All code is covered by unit and/or runtime tests where feasible.
- [X] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [X] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [X] Provide a title or release-note blurb suitable for the release notes.
- [X] Thanks for contributing!

We are using Cilium in EKS alongside with ALB ingress controller which requires the service to be annotated with particular information such as `alb.ingress.kubernetes.io/target-type: ip` in order to create a load balancer in the AWS. The problem is that the helm chart does not support annotating the service, therefore, we either need to manually annotate the service or use another hackish solutions 

```release-note
Implement support of annotations in hubble ui service manifest
```

2023-02-10 14:16 UTC, kaworu requested changes
Hi @brnck :wave: and thank you for the PR! Please see my comment, and also to fix the [travis-ci build](https://app.travis-ci.com/github/cilium/cilium/builds/260537315) you need to run:
```
make -C Documentation update-helm-values
```

2023-02-10 14:16 UTC, kaworu commented on install/kubernetes/cilium/values.yaml
> +      annotations: {}
Please report this change to `install/kubernetes/cilium/values.yaml.tmpl` and then run:
```
make -C install/kubernetes
```

2023-02-13 02:09 UTC, sayboras approved these changes
Apart from above point mentioned by Alex, the changes make sense and look good to me. Thanks.

2023-02-13 02:10 UTC, sayboras commented
Also, can you run the below command to update helm docs as well

```bash
make -C Documentation update-helm-values
```

2023-02-13 08:15 UTC, brnck commented
Hi, @kaworu thanks for the review! Executed both commands and committed the changes. Should be good now. 

Also, is it possible to backport this change to **1.12**?

2023-02-13 08:39 UTC, kaworu requested changes
> Hi, @kaworu thanks for the review! Executed both commands and committed the changes. Should be good now.

Thanks, the patch LGTM now, could you please sqash the three resulting commits into one?

> Also, is it possible to backport this change to 1.12?

Sure, adding the labels for v1.12 and v1.13 backport.

2023-02-13 09:16 UTC, brnck commented
@kaworu Looks like I completely messed up to branch with squash :/ I think I'll close this PR and open a new one

2023-02-13 09:18 UTC, closed without merging