build: custom-vet-check should respect make variable GO
cilium/cilium pull request #23668
Opened 2023-02-10 16:42 UTC by mhofstetter

With this change, the custom vet check respects the make variable GO which might point to a custom Go installation.

Otherwise, custom vetting fails because the default Go  installation is used.

2023-02-10 20:41 UTC, gentoo-root requested changes

2023-02-10 20:41 UTC, gentoo-root commented on contrib/scripts/custom-vet-check.sh
> +${GO} run github.com/cilium/customvet -timeafter.ignore inctimer -readall.ignore safeio ./...
```suggestion
"$GO" run github.com/cilium/customvet -timeafter.ignore inctimer -readall.ignore safeio ./...
```

* to handle the case if someone uses a crazy path with spaces.
* to prevent argument injection via $GO.

2023-02-13 09:22 UTC, nebril approved these changes

2023-02-13 15:41 UTC, gentoo-root approved these changes

2023-02-13 16:39 UTC, mhofstetter commented
/test

2023-02-14 07:34 UTC, mhofstetter commented
/test-runtime

2023-02-14 07:45 UTC, mhofstetter commented
/ci-verifier

2023-02-14 14:23 UTC, aditighag approved these changes

2023-02-15 13:45 UTC, merged