Add part on updating the Helm chart
cilium/cilium pull request #23739
Opened 2023-02-14 13:20 UTC by meyskens

This adds a part to the documentation on how to run the linting an document update for Helm chart.

Signed-off-by: Maartje Eyskens <maartje.eyskens@isovalent.com>

```release-note
Document contributor steps to update the Helm chart
```

I did this on the experience I had in #23719, am i missing something that should be added?

2023-02-14 14:16 UTC, aditighag approved these changes
Thanks! 👍 Please add the missing release note label.

2023-02-14 14:17 UTC, aditighag commented on Documentation/contributing/development/dev_setup.rst
> +Before submitting the changes the ``README.md`` file needs to be updated, this can be done using teh ``docs`` target:
```suggestion
Before submitting the changes the ``README.md`` file needs to be updated, this can be done using the ``docs`` target:
```

2023-02-14 16:21 UTC, qmonnet requested changes
Hi, and thanks!

It's nice to have the different steps covered, but to be honest I find that it's a lot of commands to run, when `make -C install/kubernetes` runs them all at once (`all: update-versions check-values-yaml docs lint`, `update-versions: update-chart cilium/values.yaml`).

I don't mind keeping the details to explain what happens, but for users who aren't interested in those, can we at least mention somewhere at the top that these are all executed as part of the default Makefile target?

Please also find some minor comments below.

2023-02-14 16:21 UTC, qmonnet commented on Documentation/contributing/development/dev_setup.rst
> +.. code-block:: shell-session
You need a blank line above your `.. code-block::` directive, or Sphinx considers it as part of the same paragraph as the line above and simply renders it as text, see [the Netlify preview](https://deploy-preview-23739--docs-cilium-io.netlify.app/contributing/development/dev_setup.html#making-changes-to-the-helm-chart).

2023-02-14 16:21 UTC, qmonnet commented on Documentation/contributing/development/dev_setup.rst
> +.. code-block:: shell-session
Same here

2023-02-14 16:21 UTC, qmonnet commented on Documentation/contributing/development/dev_setup.rst
> +Your change to the Helm chart is now ready to be PRed!
The spell checker fails to recognise `PRed`, can you please use something more standard? If you really want to keep the term, you have to add it to the list of spelling exceptions, see https://github.com/cilium/cilium/actions/runs/4174769460/jobs/7228777718

2023-02-14 16:21 UTC, qmonnet commented
One last thing, can you please squash your two commits and force-push to your branch?

2023-02-15 15:15 UTC, meyskens commented on Documentation/contributing/development/dev_setup.rst
> +.. code-block:: shell-session
fixed! first time i have seen so much reST :)

2023-02-15 15:42 UTC, qmonnet approved these changes
Looks good to me, thanks for addressing all the feedback!

The Netlify preview build failed for some (apparently unrelated) reason, I'm trying to find someone who can re-trigger it.

2023-02-15 17:25 UTC, qmonnet commented
Bill re-triggered the build (thanks!), and [the preview](https://deploy-preview-23739--docs-cilium-io.netlify.app/contributing/development/dev_setup.html#making-changes-to-the-helm-chart) looks all good now, even though Netlify didn't update the job status on this page. So we're ready to go!

2023-02-15 21:53 UTC, merged