Move ct_lookup in bpf_host.c to a separate tailcall
cilium/cilium pull request #23831
Opened 2023-02-16 21:12 UTC by gentoo-root

Move ct_lookup in bpf_host.c to a separate tailcall to reduce verifier complexity.

Fixes: #17142

2023-03-07 00:04 UTC, pchaigno commented
/test

2023-03-07 00:05 UTC, pchaigno reviewed
Changes look good to me and the commit history is nice! :rocket: 

I have a couple comments below. Most notably, I'd like to reduce the code movements in the last two commits. That will be painful during future backports and git blaming sessions.

2023-03-07 00:05 UTC, pchaigno commented on bpf/lib/host_firewall.h
> +					    CT_EGRESS, &ct_buffer->ct_state, &ct_buffer->monitor);
I don't understand why I introduced a second CT lookup on in the same BPF program with the same tuple and same direction :thinking: Do you?

We should probably optimize that in a subsequent PR

2023-03-07 00:05 UTC, pchaigno commented on bpf/lib/host_firewall.h
>  #  ifndef ENABLE_MASQUERADE
I'm not sure I understand the rationale for commit `bpf: Simplify ipv4_host_policy_egress`. It results into more code and the `ENABLE_MASQUERADE` guard is now spread into two places.

We should at least add a comment before this line to explain why there's a `ENABLE_MASQUERADE` here. It may be enough to refer to the comment in `whitelist_snated_egress_connections`.

2023-03-07 00:05 UTC, pchaigno commented on bpf/bpf_host.c
> +handle_ipv4(struct __ctx_buff *ctx, __u32 secctx,
Any reason to move this function to the bottom? If you keep it right after `resolve_srcid_ipv4`, then that's a lot less code movement and GitHub may even be able to recognize that huge portions of code didn't move. That would avoid many conflicts on backports and ease use of git blaming in the future.

2023-03-07 00:05 UTC, pchaigno commented on bpf/lib/host_firewall.h
> +	if (fill_trace) {
Is this `fill_trace` variable actually needed? It seems to be always set when we reach this point as it's set when `ret >= 0`. If it is actually needed, it may be best to move its introduction to a separate commit to explain the rationale.

2023-03-07 00:05 UTC, pchaigno commented on bpf/bpf_host.c
> +handle_ipv6(struct __ctx_buff *ctx, __u32 secctx, const bool from_host)
Same as for its IPv4 counterpart.

2023-03-07 09:34 UTC, julianwiedmann commented on bpf/bpf_host.c
> +	__u32 from_host_raw = ctx_load_meta(ctx, CB_FROM_HOST);
One thing of note here is that in current code, `from_host` is a constant. So the compiler can effectively optimize ~half of the code out. Now we need to include support for both cases ... that doesn't feel like a win, complexity-wise?

2023-03-07 12:32 UTC, gentoo-root commented on bpf/lib/host_firewall.h
> +					    CT_EGRESS, &ct_buffer->ct_state, &ct_buffer->monitor);
Well, at least we don't do both, it's either one or the other, but indeed, it looks like they can be easily squashed together.

2023-03-07 12:32 UTC, gentoo-root commented on bpf/lib/host_firewall.h
>  #  ifndef ENABLE_MASQUERADE
> the rationale

The goal is to allow ipv4_host_policy_egress_lookup to be called separately, not as part of ipv4_host_policy_egress, without putting a burden on the caller to check whitelist_snated_egress_connections. Imagine how the call to ipv4_host_policy_egress_lookup would look like if the call to whitelist_snated_egress_connections wasn't a part of it.

> ENABLE_MASQUERADE guard is now spread into two places.

It's temporary and patched up in a subsequent commit. I can probably avoid that if I introduce fill_trace right from the start.

2023-03-07 12:32 UTC, gentoo-root commented on bpf/bpf_host.c
> +handle_ipv4(struct __ctx_buff *ctx, __u32 secctx,
> Any reason to move this function to the bottom?

Yes, the functions must be declared before they are called. The call graph used to look like:

```
tail_handle_ipv4 -> handle_ipv4 -> tail_handle_ipv4_cont -> handle_ipv4_cont
```

which meant that I either had to put the definition of handle_ipv4_cont above handle_ipv4, or at least add a forward declaration (which I thought would be uglier). However, after I fixed some bug, the call graph now looks like:

```
                 /-> handle_ipv4
tail_handle_ipv4
                 \-> tail_handle_ipv4_cont -> handle_ipv4_cont
```

which essentially means I can now put handle_ipv4 before handle_ipv4_cont and make the diff readable.

2023-03-07 12:37 UTC, gentoo-root commented on bpf/lib/host_firewall.h
> +	if (fill_trace) {
Not always set: if ENABLE_MASQUERADE is defined and src_id != HOST_ID, ipv4_host_policy_egress_lookup returns CTX_ACT_OK and doesn't set any trace fields. I'll try to move it to the "bpf: Simplify ipv4_host_policy_egress" commit.

2023-03-07 12:41 UTC, gentoo-root commented on bpf/bpf_host.c
> +	__u32 from_host_raw = ctx_load_meta(ctx, CB_FROM_HOST);
That's a very valid point. I think I can fix it by using two tailcalls, just like CILIUM_CALL_IPV4_FROM_{HOST,NETDEV} already do, to keep this optimization for handle_ipv4_cont.

2023-03-11 01:01 UTC, gentoo-root commented on bpf/lib/host_firewall.h
> +					    CT_EGRESS, &ct_buffer->ct_state, &ct_buffer->monitor);
Did this cleanup in this PR, it allowed to get rid of some obscure flows, thanks for this great idea!

2023-03-11 01:03 UTC, gentoo-root commented on bpf/lib/host_firewall.h
>  #  ifndef ENABLE_MASQUERADE
That commit was dropped altogether and replaced with another one. Handling of whitelist_snated_egress_connections is much cleaner now.

2023-03-11 01:03 UTC, gentoo-root commented on bpf/bpf_host.c
> +handle_ipv4(struct __ctx_buff *ctx, __u32 secctx,
Function order restored.

2023-03-11 01:04 UTC, gentoo-root commented on bpf/lib/host_firewall.h
> +	if (fill_trace) {
fill_trace ditched from everywhere (thanks to the ct_lookup4 squash in whitelist_snated_egress_connections, that you suggested).

2023-03-15 22:33 UTC, pchaigno approved these changes

2023-03-15 22:34 UTC, pchaigno commented
/test

2023-03-15 22:35 UTC, pchaigno commented
@gentoo-root I'm guessing, given recent assignments, you may be a bit low on cycles. If that's the case, I think it's fine to address Julian's comment in a follow up. If this PR stays open too long, it's likely to accumulate conflicts :disappointed:

2023-03-16 17:49 UTC, gentoo-root commented on bpf/bpf_host.c
> +	__u32 from_host_raw = ctx_load_meta(ctx, CB_FROM_HOST);
Addressed this one in the new version.

2023-03-27 14:32 UTC, julianwiedmann requested changes
Looks great! Just a few small things below ...

There's also some typos in the commit description for `bpf: Deduplicate ct_lookup4 in ipv4_host_policy_egress` - it speaks of `ipv4_host_policy_egress_lookup()`, which doesn't exist at that point in the series.

2023-03-27 14:32 UTC, julianwiedmann commented on bpf/bpf_host.c
> +	return ret;
If the invoke_tailcall_if() expands into a tail-call, we're missing the `send_drop_notify_error()` for the `DROP_MISSED_TAIL_CALL`.

I needed to fix up something similar recently in `handle_nat_fwd()`, maybe there's some inspiration there.

2023-03-27 14:32 UTC, julianwiedmann commented on bpf/lib/host_firewall.h
> +#endif
Note that this will "conflict" with https://github.com/cilium/cilium/pull/24504.

2023-03-27 14:32 UTC, julianwiedmann commented on bpf/bpf_host.c
> +
Duplicated leftovers from conflict resolution? :thinking:

2023-03-27 14:41 UTC, gentoo-root reviewed
Thanks for reviewing it, I'll fix the remaining things.

2023-03-27 14:41 UTC, gentoo-root commented on bpf/bpf_host.c
> +
Seems so. I rebased and moved changes between patches a lot.

2023-03-27 14:41 UTC, gentoo-root commented on bpf/bpf_host.c
> +	return ret;
Ah, right, I missed that! At least the actual errors from cont are now handled properly :sweat_smile:

2023-03-28 09:22 UTC, julianwiedmann commented on bpf/lib/host_firewall.h
> +#endif
-> that PR is now merged

2023-04-24 11:38 UTC, julianwiedmann requested changes
Sorry, took way too long to review this :disappointed:. Had a closer look, please check if my comments make sense ...

2023-04-24 11:38 UTC, julianwiedmann commented on bpf/lib/host_firewall.h
> +				    int ct_ret)
nit - this could be `enum ct_status ct_ret`

2023-04-24 11:38 UTC, julianwiedmann commented on bpf/lib/host_firewall.h
> +		if (unlikely(ret < 0))
I believe this change isn't correct:
- in current code we extract a fresh CT tuple
- in new code, we re-use the previously extracted CT tuple. But that tuple has already undergone a `ct_lookup4()` with result `CT_NEW`, so its content has been flipped by `__ct_lookup4()`.

2023-04-24 11:38 UTC, julianwiedmann commented on bpf/bpf_host.c
> +
For my own education (I'll need to add a per-CPU map for some other use soon) - is there an obvious advantage to having separate IPv4/IPv6 maps? I would have instinctly gone with a single map, containing a union of the `ct_buffer4` / `ct_buffer6` structs.

2023-04-24 11:38 UTC, julianwiedmann commented on bpf/bpf_host.c
> +					   CILIUM_CALL_IPV4_CONT_FROM_HOST,
Probably just a matter of taste. But I would prefer to have the `ctx_store_meta(ctx, CB_SRC_LABEL, secctx)` here, and not hidden inside `handle_ipv4()`. It's already difficult enough to keep track of all the games we play with `CB_SRC_LABEL` ...

2023-04-24 11:38 UTC, julianwiedmann commented on bpf/bpf_host.c
> +
These are potentially executed as tail-calls, so we need to check for errors and call `send_drop_notify_error()`.

2023-04-25 17:33 UTC, gentoo-root commented on bpf/bpf_host.c
> +
send_drop_notify_error_ext is in the common code (tail_handle_ipv4_cont), just like it was for tail_handle_ipv4 before my change.

2023-04-25 17:33 UTC, gentoo-root commented on bpf/bpf_host.c
> +
I copied the same design we have in bpf_lxc.c. I don't see a real advantage over a union (type safety is equally absent when doing a lookup from a map).

2023-04-25 17:34 UTC, gentoo-root commented on bpf/lib/host_firewall.h
> +		if (unlikely(ret < 0))
>in current code we extract a fresh CT tuple

No, it's also after ct_lookup4.

This change should be equivalent to the previous code (pure refactoring).

2023-04-25 17:34 UTC, gentoo-root commented on bpf/lib/host_firewall.h
> +				    int ct_ret)
ACK.

(For some reason this enum type is not popular in the code...)

2023-04-25 17:36 UTC, gentoo-root commented on bpf/bpf_host.c
> +					   CILIUM_CALL_IPV4_CONT_FROM_HOST,
What about CB_FROM_HOST? Shall I move it out of handle_ipv4 too? If I do, it will be cumbersome to return 2 booleans in addition.

2023-04-26 06:26 UTC, julianwiedmann commented on bpf/lib/host_firewall.h
> +		if (unlikely(ret < 0))
Ah you're right of course, sorry for the noise.

2023-04-26 06:38 UTC, julianwiedmann commented on bpf/bpf_host.c
> +
Missed that, thanks!

Note that the situation has slightly changed vs current code. In current code `tail_handle_ipv4_from_{host,netdev}()` are unconditional tail-calls, so we know that they *have* to handle drop/trace notifications.

With `declare_tailcall_if()` we also need to consider that the function gets inlined, and the surrounding code then expects to handle drop/trace notifications. Not a problem for drop notifications (as they are currently implemented through a tail-call, so control will be gone after the first drop notify). But trace notifications would get duplicated.

2023-04-26 06:42 UTC, julianwiedmann commented on bpf/bpf_host.c
> +					   CILIUM_CALL_IPV4_CONT_FROM_HOST,
`CB_FROM_HOST` should probably stay in it current place - as that's where we create its input data.

I'm just very sensitive to `CB_SRC_LABEL`, burned too many times already :smile:.

2023-04-26 06:44 UTC, julianwiedmann approved these changes
Couldn't spot anything else, and you nicely shot down all my earlier concerns :sweat_smile:.

Feel free to resolve my nits in a follow-on PR if it's easier. But as this needs a rebase anyway ...

2023-04-26 12:45 UTC, gentoo-root commented on bpf/bpf_host.c
> +
>Not a problem for drop notifications (as they are currently implemented through a tail-call, so control will be gone after the first drop notify)

I'd keep it as is then, at least for now. We also have a similar pattern in bpf_lxc.

I agree it's fragile, though. If the implementation for drop notifications is changed, it will become a problem that can easily slip unnoticed. This can be solved by passing handle_ipv4_cont (instead of tail_handle_ipv4_cont_from_{host,netdev}) to invoke_tailcall_if (if we forget about the arguments for a moment), but then the compiler will complain that a static function is never used (tail_handle_ipv4_cont_from_{host,netdev} when compiled without a tailcall). We need then to add __maybe_unused  to invoke_tailcall_if_0 (will it actually remove the function from the binary?).

2023-04-26 13:09 UTC, julianwiedmann commented on bpf/bpf_host.c
> +
> I'd keep it as is then, at least for now. We also have a similar pattern in bpf_lxc.

oh yeah absolutely. I've been wanting to clean/fix some drop notification things anyway, maybe I'll tackle it along then at that point.

2023-04-26 13:46 UTC, gentoo-root commented on bpf/bpf_host.c
> +					   CILIUM_CALL_IPV4_CONT_FROM_HOST,
OK, I moved it and rebased.

(Please note that there is one more assignment to CB_SRC_LABEL in handle_ipv4 in the NAT46x64 shortcut that existed before my changes, but this should be fine, we do an unconditional tailcall right away.)

2023-04-27 09:54 UTC, pchaigno commented
/test

2023-04-27 10:08 UTC, pchaigno commented on bpf/lib/host_firewall.h
> +	    (is_defined(ENABLE_MASQUERADE) || ipcache_srcid != HOST_ID))
The comment doesn't match the condition anymore. Maybe we need to move the comment in `whitelist_snated_egress_connections` here?

2023-04-27 10:16 UTC, pchaigno approved these changes
I had a second, cursory look. One comment below, but I think it can be fixed up after the tests haven't passed (or after they are triaged) without needing to then rerun the full test suite (assuming you don't rebase in the process).

2023-04-27 10:16 UTC, pchaigno commented on bpf/lib/host_firewall.h
> +	    (is_defined(ENABLE_MASQUERADE) || ipcache_srcid != HOST_ID))
The comment doesn't match the condition anymore. Maybe we need to move the comment in `whitelist_snated_egress_connections` here? We should probably also rename `whitelist_snated_egress_connections` to something like `track_snated_egress_connections`.

2023-04-27 11:27 UTC, gentoo-root commented on bpf/lib/host_firewall.h
> +	    (is_defined(ENABLE_MASQUERADE) || ipcache_srcid != HOST_ID))
>Maybe we need to move the comment in whitelist_snated_egress_connections here?

I'll update this comment to make it more meaningful.

>We should probably also rename whitelist_snated_egress_connections to something like track_snated_egress_connections.

Why? I believe the meaning of the old name still holds. By creating a CT entry (the only thing this function does at the moment) we are whitelisting these connections from applying host policies to reply packets.

2023-04-27 17:05 UTC, pchaigno commented on bpf/lib/host_firewall.h
> +	    (is_defined(ENABLE_MASQUERADE) || ipcache_srcid != HOST_ID))
I agree, but that intent is hard to understand if the code comment is moved to where the condition is.

2023-04-27 19:58 UTC, merged

2026-05-04 21:05 UTC, pchaigno commented on bpf/lib/host_firewall.h
> +	struct ct_state ct_state_new = {};
I'm a bit confused by commit `bpf: Split ipv{4,6}_host_policy_egress` here. It says:

> Split the conntrack lookup part of the host policy egress handlers into a separate function to prepare for making it a separate tailcall.

but it seems the tail call was never introduced. Am I missing something @gentoo-root?

2026-05-05 15:41 UTC, gentoo-root commented on bpf/lib/host_firewall.h
> +	struct ct_state ct_state_new = {};
Maybe the phrasing was not the best... ipv6_host_policy_egress is split into ipv6_host_policy_egress_lookup and __ipv6_host_policy_egress. ipv6_host_policy_egress_lookup is called by the original caller of ipv6_host_policy_egress, and __ipv6_host_policy_egress continues after the tailcall. This is what's implemented in the next two commits. I don't think making ipv6_host_policy_egress_lookup an entirely separate (intermediate) tail call made sense back then, since it fit into handle_ipv6 by complexity. If it's not the case anymore, lookup is a separate function that can be made into another tailcall.