Tl/fix rpm package build
cilium/cilium pull request #2386
Opened 2017-12-21 01:42 UTC by tonylambiris

Not sure when it happened, but it looks like `cilium.spec.envsubst` used to live in the cfg directory that no longer appears to exist. This brights the spec file template back and also adds new binaries and sys-fs-bpf.mount to the `%files` directive. In addition, I added a new make target in the spec:
```
%{__make} -C daemon apply-bindata
```
This fixes an issue I was getting during my testing of this PR:
```
bindata.go: FAILED
sha1sum: WARNING: 1 computed checksum did NOT match
########################################################################

                  ERROR: bindata.go is out of date.

 This can happen for two reasons:
 1. You are using a go-bindata binary compiled with a different version
    of golang (not 1.9). If so, please up/downgrade.

 2. You have made changes to the bpf/ directory. Please run the
    following command to update the SHA in daemon/bpf.sha:

    $ make -C daemon apply-bindata
```

It looks as if this PR will also get you closer to closing out https://github.com/cilium/cilium/issues/1529

2017-12-21 13:10 UTC, tgraf commented
@tonylambiris Let us know at what point you want to have a review on this.

2018-01-04 19:43 UTC, manalibhutiyani commented
@tonylambiris : Please remove the `wip` label, when you are ready for the PR to be reviewed. Thanks!

2018-01-08 03:57 UTC, tonylambiris commented
@tgraf Sorry about that, I totally overlooked this. Should I rebase with master and push?

2018-01-08 14:36 UTC, tgraf commented
@tonylambiris Yes, please rebase against master.

2018-01-08 14:42 UTC, tgraf commented
test-me-please

2018-01-10 13:44 UTC, aalemayhu requested changes
Please add your `Signed-off-by` in the commit messages. For more info see the docs http://docs.cilium.io/en/latest/contributing/#developer-s-certificate-of-origin

2018-01-11 23:35 UTC, merged