agent: dump stack on stale probes
cilium/cilium pull request #23915
Opened 2023-02-21 15:47 UTC by squeed

Most of the time, when we see a stale probe, it's due to a deadlock. So, write a stack dump to disk (since we're probably going to be restarted soon due to a liveness probe).

To prevent any sort of excessive resource consumption, only dump stack once every 5 minutes, and always write to the same file. Also, let's make the check lock-free while we're at it.

Also, make sure we capture this file in bugtool.

2023-02-21 15:49 UTC, aanm requested changes
@squeed this is great. IIRC all files under `/var/run/cilium`, or `/run/cilium` are already part of the bugtool so there's no need to make it explicit.

2023-02-21 15:53 UTC, michi-covalent approved these changes
`:amaze:`

lgtm other than the feedback from andre 🚢

2023-02-21 16:12 UTC, squeed commented
> @squeed this is great. IIRC all files under `/var/run/cilium`, or `/run/cilium` are already part of the bugtool so there's no need to make it explicit.

@aanm only /var/run/cilium/state as far as I can tell.

2023-02-21 16:15 UTC, squeed commented
On second thought, this should be gzipped, since tmp dirs are pure memory usage. Hold please.

2023-02-21 16:30 UTC, squeed commented
OK, updated to gzip stack dump. Ready for re-review. I've confirmed that sysdumps don't have /var/run/cilium, just /var/run/cilium/state

2023-02-21 19:01 UTC, thorn3r approved these changes
:shipit: :+1:

2023-02-21 19:42 UTC, squeed commented
/test

2023-02-21 22:03 UTC, aanm commented
> > @squeed this is great. IIRC all files under `/var/run/cilium`, or `/run/cilium` are already part of the bugtool so there's no need to make it explicit.
> 
> @aanm only /var/run/cilium/state as far as I can tell.

@squeed thanks for taking a look, then why don't we store this file in `/var/run/cilium/state`? :thinking:

2023-02-22 12:55 UTC, aanm approved these changes

2023-02-22 15:36 UTC, nathanjsweet approved these changes
LGTM! Good work!

2023-02-22 16:02 UTC, squeed commented
/test

2023-02-24 11:54 UTC, sayboras approved these changes

2023-02-24 11:57 UTC, sayboras commented
test-1.16-4.19 hits https://github.com/cilium/cilium/issues/23845, which is fixed recently in master
test-runtime hits https://github.com/cilium/cilium/issues/23495

2023-02-24 11:57 UTC, merged

2023-03-06 17:00 UTC, YutaroHayakawa commented
Let me mark this as backport/author for the v1.11 and v1.12 branches. The `atomic.Int64` type is introduced in golang 1.19, and v1.11 and v1.12 are using the golang version older than that.

2023-03-06 17:01 UTC, pchaigno commented
Is it still worth backporting given it's not fixing a bug but "just" helping with troubleshooting?