Feature/modular metrics
cilium/cilium pull request #23936
Opened 2023-02-22 11:24 UTC by dylandreimerink

This PR restructures the way we work with metrics within Cilium. The goal of this PR is to address a few pain points with the current metrics system. We get three big things out of this work:
* The ability to define metrics in a modular way, close to the location where it is actually going to be used.
* The ability to define richer metadata like label descriptions, known values and their meaning etc.
* The ability to automatically generate metrics references from all defined metrics

To accomplish we did the following things:
* Created custom metric types on top of the existing Prometheus metrics, which are API compatible, but carry additional information and setting used for other features.
* Metrics are now always registered with the repository, but they can be enabled or disabled. Instead of having a centralized switch statement to determine which metrics will be enabled or disabled, the metric definitions now have a field to say if they are enabled by default or not. The main advantage here is that we are able to list all metrics even those who are disabled.
* A new cell was introduced to wire metric definitions into Hive. Metrics are always contained within a struct so this type can be used to inject the references into other cells that need to use them. The cell also makes the individual metrics available so the registry can collect all metrics defined everywhere.
* All metric definitions in `pkg/metrics/metrics.go` are not converted to a single large cell called `LegacyMetrics` and (for now) are written to the same global variables as were used before.
* The registry has been modularized and uses Hive to collect all metrics
* A tool was introduced in `tools/metricdocgen` which can collect all metrics and render the `Documentation/observability/metrics.rst` file with agent metric references generated from the metrics.

Future PRs will focus on removing app-wide dependency on global variables and start moving metric definitions next to the code that uses it, this will likely go in steps as we modularize the rest of Cillium step by step.

2023-03-24 12:33 UTC, dylandreimerink commented
/test

2023-04-05 10:48 UTC, joamaki commented
/test

2023-04-14 10:42 UTC, joamaki commented
/test

2023-04-17 23:47 UTC, zacharysarah requested changes
@dylandreimerink 👋🏻 Some edits for clarity and style, otherwise LGTM from a docs perspective.

2023-04-17 23:47 UTC, zacharysarah commented on Documentation/cmdref/cilium-agent.md
> +      --metrics strings                                         Metrics that should be enabled or disabled from the default metric list. (+metric_foo to enable metric_foo , -metric_bar to disable met
Avoid soft conditional text.
```suggestion
      --metrics strings                                         Metrics to enable or disable from the default metric list. (+metric_foo to enable metric_foo , -metric_bar to disable metric_bar)
```

2023-04-17 23:47 UTC, zacharysarah commented on Documentation/cmdref/cilium-agent_hive.md
> +      --metrics strings                        Metrics that should be enabled or disabled from the default metric list. (+metric_foo to enable metric_foo , -metric_bar to disable metric_bar)
Avoid soft conditional text.

```suggestion
      --metrics strings                        Metrics to enable or disable from the default metric list. (+metric_foo to enable metric_foo , -metric_bar to disable metric_bar)
```

2023-04-17 23:47 UTC, zacharysarah commented on Documentation/observability/metrics.rst
> +Both ``bpf_maps_virtual_memory_max_bytes`` and ``bpf_progs_virtual_memory_max_bytes`` are currently reporting the system-wide memory usage of eBPF that is directly and not directly managed by Cilium.
Avoid statements about the future. 
```suggestion
Both ``bpf_maps_virtual_memory_max_bytes`` and ``bpf_progs_virtual_memory_max_bytes`` are currently reporting the system-wide memory usage of eBPF that is directly and not directly managed by Cilium.
```

2023-04-17 23:47 UTC, zacharysarah commented on Documentation/observability/metrics.rst
> +|``outcome``  |Indicates whether the outcome of the operation was successful or not|``fail``   |                 |
Use active voice
```suggestion
|``outcome``  |Indicates whether the operation succeeded or not|``fail``   |                 |
```

2023-04-17 23:47 UTC, zacharysarah commented on Documentation/observability/metrics.rst
> +|``protocol`` |Marks the L4 protocol (TCP, ANY) for the metric.                                                     |           |                 |
Capitalize consistently. For fragments, use periods (or not) consistently
```suggestion
|``family``   |Marks which protocol family (IPv4, IPV6) the metric is related to                                   |           |                 |
+-------------+-----------------------------------------------------------------------------------------------------+-----------+-----------------+
|``name``     |Marks a unique identifier for this metric. The name should be defined once for a given type of error.|           |                 |
+-------------+-----------------------------------------------------------------------------------------------------+-----------+-----------------+
|``protocol`` |Marks the L4 protocol (TCP, ANY) for the metric                                                     |           |                 |
```

2023-04-17 23:47 UTC, zacharysarah commented on Documentation/observability/metrics.rst
> +|``status``   |The label from completed task                                                                        |           |                 |
Too fragmented
```suggestion
|``status``   |The label from the completed task                                                                        |           |                 |
```

2023-04-17 23:47 UTC, zacharysarah commented on Documentation/observability/metrics.rst
> +|``outcome``|Indicates whether the outcome of the operation was successful or not                                                                                                                     |
Use active voice
```suggestion
|``outcome``|Indicates whether the operation succeeded or not                                                                                                                     |``fail``   |                 |
```

2023-04-17 23:47 UTC, zacharysarah commented on Documentation/observability/metrics.rst
> +|``family``          |Marks which protocol family (IPv4, IPV6) the metric is related to.
Use periods (or not) consistently
```suggestion
|``family``          |Marks which protocol family (IPv4, IPV6) the metric is related to                                                                                                                       |           |                                                   |
```

2023-04-17 23:47 UTC, zacharysarah commented on Documentation/observability/metrics.rst
> +|``protocol_l7``     |The label used when working with layer 7 protocols.
Use periods (or not) consistently
```suggestion
|``protocol``        |Marks the L4 protocol (TCP, ANY) for the metric                                                                                                                                         |           |                                                   |
+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+---------------------------------------------------+
|``protocol_l7``     |The label used when working with layer 7 protocols                                                                                                                                      |           |                                                   |
```

2023-04-17 23:47 UTC, zacharysarah commented on Documentation/observability/metrics.rst
> +|``protocol_l7``|The label used when working with layer 7 protocols.|           |                 |
Use periods (or not) consistently
```suggestion
|``protocol_l7``|The label used when working with layer 7 protocols|           |                 |
```

2023-04-17 23:47 UTC, zacharysarah commented on pkg/hive/cell/metric.go
> +	container.Provide(m.provideMetrics, dig.Export(true))
Nittiest of nits, but use periods consistently, even in code comments
```suggestion
	// Provide the supplied constructor, so its return type is directly accessible by cells
	container.Provide(m.ctor, dig.Export(true)).

	// Provide the metrics provider, which will take the return value of the constructor and turn it into a
	// slice of metrics to be consumed by anyone interested in handling them.
	container.Provide(m.provideMetrics, dig.Export(true))
```

2023-04-17 23:47 UTC, zacharysarah commented on pkg/metrics/metric/metric.go
> +// prometheus metric types and add additional metadata to the definitions which can be used to generate proper metric
Capitalize product names unless they're specifically lower-cased; for example, Prometheus vs gRPC.
```suggestion
// Prometheus metric types and add additional metadata to the definitions which can be used to generate proper metric
```

2023-04-17 23:47 UTC, zacharysarah commented on pkg/metrics/metric/metric.go
> +	// This string is included with the data in the prometheus endpoint and should be brief.
Capitalize unless this is the name of a specific endpoint
```suggestion
	// This string is included with the data in the Prometheus endpoint and should be brief.
```

2023-04-17 23:47 UTC, zacharysarah commented on pkg/metrics/metric/metric.go
> +// LabelDescription, unlike traditional prometheus metric declarations contains not only the name of a label but also
Capitalize
```suggestion
// LabelDescription, unlike traditional Prometheus metric declarations contains not only the name of a label but also
```

2023-04-17 23:47 UTC, zacharysarah commented on tools/metricdoctool/metricdoctool.go
> +				// name will not be prefixed with anything.
Edits for clarity
```suggestion
				// If we do have a doc-name, then place it into its own category in the docs, but the metric
				// name will not be prefixed with anything.
```

2023-04-17 23:47 UTC, zacharysarah commented on tools/metricdoctool/metricdoctool.go
> +				// alphabetically first. This should ensure a consistent outcome
Edits for clarity, consistent periods, avoiding soft conditionals
```suggestion
				// If there are multiple descriptions for a label, pick the longest. If two are the same size, pick the
				// first in alphabetical order. This ensures a consistent outcome.
```

2023-04-18 10:57 UTC, bimmlerd approved these changes
It's pretty hard to review this, even commit by commit, as the changes are so large.

Contributing part looks ok to me, though the last commit should probably be squashed

2023-04-18 10:57 UTC, bimmlerd commented on pkg/metrics/metric/histogram.go
> +type HistogramOpts struct {
How come this doesn't embed prometheus.HistogramOpts but duplicates it instead? Applies to a few of these similar structs.

2023-04-18 10:57 UTC, bimmlerd commented on pkg/hive/example/metrics.go
> +func newExampleMetrics() exampleMetrics {
I think this deserves some comments explaining what's going on

2023-04-18 10:57 UTC, bimmlerd commented on pkg/metrics/registry.go
> +	//
nit: either document or remove comment

2023-04-18 10:57 UTC, bimmlerd commented on pkg/metrics/middleware_test.go
> +		// TODO FIX
todo: fixing test

2023-04-18 10:57 UTC, bimmlerd commented on pkg/hive/cell/metric.go
> +	"go.uber.org/dig"
is this the better place for this dep? I thought we only distringuish std&local

2023-04-19 04:13 UTC, tommyp1ckles commented on pkg/metrics/metric/counter.go
> +func (c *counter) Describe(descChan chan<- *prometheus.Desc) {
Could we have the underlying Counter type be composed with counter, that way we don't have to re implement these functions (and you can still override for Collect()).

2023-05-12 15:45 UTC, tklauser commented
There are some open review comments and this branch has picked up quite a few merge conflicts and thus needs a rebase.

I'm going to convert the PR to draft status so it doesn't show up the assigned reviewers' review queue. Please feel free to move out of draft once the above is addressed.

2023-05-26 11:01 UTC, dylandreimerink commented
Closing in favor of #25651

2023-05-26 11:01 UTC, closed without merging