Add 1.13 conformance test
cilium/cilium pull request #24033
Opened 2023-02-27 08:20 UTC by aanm

The 1.13 conformance test was added during the 1.13 release cycle with
    a27609a3eeef6f4d77d3a32e2cf0a5682fe301f8 so we should also be testing
    the v1.13 branch for regressions.
    
    Fixes: fc7ae83692b1 ("Prepare for v1.14 development cycle")

2023-03-02 14:57 UTC, nbusseneau approved these changes

2023-03-06 15:17 UTC, brb commented on .github/workflows/conformance-datapath-v1.13.yaml
> +            encryption-node: 'true'
v1.13 doesn't support node encryption.

2023-03-06 15:18 UTC, brb requested changes
Thanks. Small comment.

2023-03-06 15:49 UTC, aanm commented on .github/workflows/conformance-datapath-v1.13.yaml
> +            encryption-node: 'true'
```
diff --git a/.github/workflows/conformance-datapath-v1.13.yaml b/.github/workflows/conformance-datapath-v1.13.yaml
index ca754262a4..4933af3a9a 100644
--- a/.github/workflows/conformance-datapath-v1.13.yaml
+++ b/.github/workflows/conformance-datapath-v1.13.yaml
@@ -165,24 +165,6 @@ jobs:
             endpoint-routes: 'true'
 
           - name: '6'
-            kernel: '6.0-main'
-            kube-proxy: 'none'
-            kpr: 'strict'
-            tunnel: 'vxlan'
-            encryption: 'wireguard'
-            encryption-node: 'true'
-            lb-mode: 'snat'
-
-          - name: '7'
-            kernel: 'bpf-next-main'
-            kube-proxy: 'none'
-            kpr: 'strict'
-            tunnel: 'disabled'
-            encryption: 'wireguard'
-            encryption-node: 'true'
-            lb-mode: 'snat'
-
-          - name: '8'
             kernel: 'bpf-next-main'
             kube-proxy: 'iptables'
             kpr: 'disabled'
```

2023-03-06 15:49 UTC, aanm commented on .github/workflows/conformance-datapath-v1.13.yaml
> +            encryption-node: 'true'
@brb thanks, I've pushed new changes. Sounds good?

2023-03-06 15:52 UTC, brb commented on .github/workflows/conformance-datapath-v1.13.yaml
> +            encryption-node: 'true'
Noup :-) Keep the configuration, but just delete the `encryption-node` lines.

2023-03-06 19:29 UTC, aanm commented on .github/workflows/conformance-datapath-v1.13.yaml
> +            encryption-node: 'true'
@brb done

2023-03-07 08:44 UTC, brb approved these changes
Thanks. I assume you have tried running tests?

2023-03-07 10:58 UTC, aanm commented
Tests were successful [here](https://github.com/cilium/cilium/actions/runs/4353106838/jobs/7606730105) merging

2023-03-07 10:59 UTC, merged