Ginkgo: Added example test on Nightly using public image
cilium/cilium pull request #2413
Opened 2018-01-02 09:40 UTC by eloycoto

Hi, 

This PR adds the test to check the Kubernetes example in the nightly builds.

It reads the example (YAML), changes the values of the config map and imports the manifest. It is using the public image, instead of the local one. 

Regards.

2018-01-02 18:50 UTC, ianvernon commented
This is a great idea, as it will ensure that our example YAML is valid. Thanks for doing this! :)

2018-01-02 18:55 UTC, ianvernon requested changes
Some minor nitpicks. This is a great change as it ensures that the files used by the public work as intended.

2018-01-02 18:55 UTC, ianvernon commented on test/helpers/utils.go
> +// DecodeYAMLOrJSON reads a json or yaml file and export all documents as an
export --> exports

2018-01-02 18:55 UTC, ianvernon commented on test/helpers/utils.go
> +// array of interfaces. In case of a invalid path or invalid format it returns
a invalid path --> an invalid path

2018-01-02 18:55 UTC, ianvernon commented on test/k8sT/Nightly.go
> +	It("Check k8s Example is working correctly", func() {
k8s --> K8s

2018-01-02 18:55 UTC, ianvernon commented on test/k8sT/Nightly.go
> +	getAppPods := func() map[string]string {
Can you add a comment saying what the values of these strings represent? I.e., maps [x] to [y]

2018-01-03 11:48 UTC, tgraf approved these changes

2018-01-03 11:48 UTC, merged