Operator api server modularization
cilium/cilium pull request #24228
Opened 2023-03-07 20:34 UTC by pippolo84

Modularize the operator api server into its own independent cell.  The refactoring aims to keep the same behavior of the previous implementation. The refactored server:

- adds a custom handler for /healthz as an alias to /v1/healthz
- in case of an empty server address option, it starts two HTTP servers, one listening on "127.0.0.1:0" and the other on "[::1]:0", in case the user is running ipv4 or ipv6 only, respectively

To answer the health checks, the operator api server should always be up and running, whether the operator has been elected leader or not.
Therefore, the health handler behavior should change based on the operator instance being elected leader or not, so it is refactored to accept a function that returns the current leading status of the operator instance.

Integration style unit tests have been added for both the handlers and the server.

Fixes: https://github.com/cilium/cilium/issues/24064

2023-03-20 09:52 UTC, joamaki requested changes

2023-03-20 09:52 UTC, joamaki commented on operator/api/cell.go
> +	cell.Invoke(newServer),
This will cause the server to be instantiated twice. Use `cell.Invoke(func(Server){})` instead to force the construction.

2023-03-20 09:52 UTC, joamaki commented on operator/api/server.go
> +	healthHandler operator.GetHealthzHandler,
I would put these handlers into `params`

2023-03-20 09:52 UTC, joamaki commented on operator/cmd/root.go
> +				return IsLeader.Load()
Use just `IsLeader.Load`, no need to wrap into a closure. Also does `IsLeader` need to be exported?

2023-03-20 09:52 UTC, joamaki commented on operator/cmd/root.go
> +				EnableK8s: operatorCfg.EnableK8s,
I think it'd be preferable to this `SharedConfig` to instead check for k8s enabled status via the k8s clientset: `clientset.IsEnabled()`, rational being that it's better to have only a single source of truth. 

Hmm, or is the problem that the k8s client gets configured and we want to use `EnableK8s` to overriding? Alternative I suppose is to explicitly `Disable()` the client based on `EnableK8s` in an `Invoke`. That would also make sure that the heartbeats aren't running. Though need to be careful that the `Invoke` runs early enough before any calls to `clientset.IsEnabled()`.

... almost feels like the cleanest solution would be to make `enable-k8s` part of `client.Config`, but that would also then introduce it to `cilium-agent` and others. Still maybe not a bad idea?

2023-03-20 09:52 UTC, joamaki commented on operator/api/health.go
> +			if !cfg.EnableK8s || !clientset.IsEnabled() {
`cfg.EnableK8s` seems redundant.

2023-03-20 11:33 UTC, pippolo84 commented on operator/cmd/root.go
> +				return IsLeader.Load()
Actually no, so I'm gonna make it unexported. :+1:

2023-03-21 11:18 UTC, pippolo84 commented on operator/cmd/root.go
> +				EnableK8s: operatorCfg.EnableK8s,
I agree that the best solution is to move `enable-k8s` as part of `client.Config`.
I don't think it will be a problem to introduce it to other binaries. The [original PR](https://github.com/cilium/cilium/pull/21344) for this was mentioning that the other binaries were already working correctly. Specifically, I think the agent was behaving properly because of the `clientset.IsEnabled()` checks.
Instead the operator had some code paths that where not guarded by that, so an additional flag was added (adding a new one was easier, I suppose).

2023-03-24 17:24 UTC, nathanjsweet approved these changes
LGTM for cli, sig-k8s, api

2023-03-28 10:21 UTC, joamaki approved these changes

2023-04-04 00:38 UTC, christarazi reviewed
LGTM mostly. My comments are around commit squashing, especially to squash test commits with the implementation commits and any cmdref changes squashed into the commits that introduced them.

2023-04-04 00:38 UTC, christarazi commented on operator/api/metrics_test.go
We can squash the tests with the previous commit that provides the implementation

2023-04-04 00:38 UTC, christarazi commented on operator/api/health_test.go
Same here with test commit squashing

2023-04-04 00:38 UTC, christarazi commented on Documentation/cmdref/cilium-operator-alibabacloud_hive.md
We should squash this commit with the change that introduced it because then the commit that introduced it will technically "fail" the build because these cmdref changes are missing.

2023-04-04 09:02 UTC, pippolo84 commented
/test

2023-04-07 17:34 UTC, christarazi approved these changes
LGTM, just one non-blocking nit: I think we meant to squash "operator/api: Add api server tests" with the previous commit.

2023-04-07 20:45 UTC, pippolo84 commented
> LGTM, just one non-blocking nit: I think we meant to squash "operator/api: Add api server tests" with the previous commit.

You're right, I was missing that. Squashed :+1:

2023-04-08 09:23 UTC, pippolo84 commented
/test

2023-04-09 19:16 UTC, christarazi commented
Seems like a legit failure with the Operator

2023-04-12 13:50 UTC, pippolo84 commented
> Seems like a legit failure with the Operator

Previous revision was incorrectly trying to check for external kvstore status from the operator replica not elected leader. Fixed it with this patch:

```diff
--- a/operator/api/health.go
+++ b/operator/api/health.go
@@ -61,11 +61,9 @@ func (h *healthHandler) Handle(params operator.GetHealthzParams) middleware.Resp
                return operator.NewGetHealthzNotImplemented()
        }
 
-       if h.isOperatorLeading() {
-               if err := h.checkStatus(); err != nil {
-                       h.log.WithError(err).Warn("Health check status")
-                       return operator.NewGetHealthzInternalServerError().WithPayload(err.Error())
-               }
+       if err := h.checkStatus(); err != nil {
+               h.log.WithError(err).Warn("Health check status")
+               return operator.NewGetHealthzInternalServerError().WithPayload(err.Error())
        }
 
        return operator.NewGetHealthzOK().WithPayload("ok")
@@ -74,7 +72,12 @@ func (h *healthHandler) Handle(params operator.GetHealthzParams) middleware.Resp
 // checkStatus verifies the connection status to the kvstore and the
 // k8s apiserver and returns an error if any of them is unhealthy
 func (h *healthHandler) checkStatus() error {
-       if h.kvstoreEnabled() {
+       // We check if we are the leader here because only the leader has
+       // access to the kvstore client. Otherwise, the kvstore client check
+       // will block. It is safe for a non-leader to skip this check, as the
+       // it is the leader's responsibility to report the status of the
+       // kvstore client.
+       if h.isOperatorLeading() && h.kvstoreEnabled() {
                client := kvstore.Client()
                if client == nil {
                        return errors.New("kvstore client not configured")
```

2023-04-12 14:24 UTC, pippolo84 commented
/test-1.26-net-next

2023-04-13 08:10 UTC, merged