Service loopback
cilium/cilium pull request #243
Opened 2017-01-07 16:42 UTC by tgraf

2017-01-07 17:53 UTC, aanm reviewed
>Note: IPv4 only implementation

Does this happens with IPv6?

> FIXME: Needs a dedicated IPv4 address to ensure packets from the local host can never cause clashing tuples.

Where is this IP needed? Can you provide more info regarding this?

2017-01-07 19:29 UTC, tgraf commented
IPv6 is also affected. Changes are WIP. We can merge it separately.

Whenever a service is looped back into the same pod, the IP will be used as source. Because we are not rewriting source ports to be unique, the source IP may not be used by anyone else in the context of that host.

2017-01-08 15:26 UTC, tgraf commented
@aanm Adapted to reserve an IPv4 address out of the alloc range for service loopback use. This addresses the clash concern mentioned in the previous commit message.

I think we can merge the IPv4 part first and see if this is sufficient and performant and then add the IPv6 part as we have some experience with it.

2017-01-08 18:18 UTC, aanm requested changes

2017-01-08 18:18 UTC, aanm commented on daemon/daemon/daemon.go
> +	// Allocate IPv4 service loopback IP
Put this condition `if d.conf.IPv4Enabled`

2017-01-09 04:09 UTC, merged