ipcache: Simplify implementation with guaranteed LPM support
cilium/cilium pull request #24363
Opened 2023-03-14 14:22 UTC by dylandreimerink

Cilium v1.13 and above has a minium kernel version requirement of v4.19.57 or above (or with equal feature support). This means that we can assume that we always have full LPM map support including iterating over the map and deleting elements from the map.

This allows us to considerably simplify our IPCache logic. This commit drops all fallback code for non-LPM maps or LPM maps without delete functionality.

```release-note
Removed legacy fallbacks for LPM maps
```

2023-03-22 13:52 UTC, dylandreimerink commented
/test

2023-03-24 15:07 UTC, dylandreimerink commented
/test

2023-03-28 15:10 UTC, joamaki commented on daemon/cmd/ipcache.go
> +type IPCacheInitializer struct{}
No need to make this into a provider. Make it an invoke function instead:
```
func onStartInitIPCache(params initializerParams, ctx hive.HookContext) error {
 ....
}
func registerIPCacheInitializer(params initializerParams) {
  params.Lifecycle.Append(hive.Hook{
    OnStart: func(ctx hive.HookContext error) { return onStartInitIPCache(params, ctx) },
  })
}

// cell.Invoke(registerIPCacheInitializer)
```

or if we'd like better names in hive output:

```
func (p initializerParams) OnStart(ctx hive.HookContext) error {
   ...
}
func (p initializerParams) OnStop(hive.HookContext) error { return nil }

func registerIPCacheInitializer(params initializerParams) { 
  params.Lifecycle.Append(params)
}
```

2023-03-28 15:15 UTC, tklauser commented on pkg/datapath/prefilter/prefilter.go
> -	haveLPM := probe.HaveFullLPM()
There a a few other instances of `probe.HaveFullLPM` in `daemon/cmd`. I think these can be removed as well along with `probe.HaveFullLPM` itself.

2023-03-28 15:15 UTC, tklauser commented on pkg/datapath/prefilter/prefilter.go
> +		path = bpf.MapPath(cidrmap.MapName + "v4")
Is it safe to rename these maps without breaking connectivity on upgrade?

2023-03-28 15:16 UTC, joamaki commented on pkg/maps/cells.go
> +var Cell = cell.Module("maps", "Maps",
Could expand the title a bit to include that it's wrappers for managing Cilium's BPF maps and add some more comments about what the purpose of this grouping is and what is provided.

2023-03-28 15:16 UTC, joamaki commented on pkg/maps/ipcache/ipcache.go
> +	Delete(key *Key) error
Let's reproduce the original comments of the methods here. Might also be cleaner to move `Cell`, `MapInterface` and `NewMapInterface` into cell.go?

2023-03-28 15:52 UTC, gentoo-root requested changes

2023-03-28 15:52 UTC, gentoo-root commented on pkg/datapath/prefilter/prefilter.go
> +		fmt.Fprintf(fw, "#define CIDR4_LPM_PREFILTER\n")
I think it should be CIDR4_FILTER, same for CIDR6_FILTER below.

CIDR4_LPM_PREFILTER was removed from the code in this commit.

2023-03-28 15:52 UTC, gentoo-root commented on pkg/datapath/prefilter/prefilter.go
>  func (p *PreFilter) selectMap(ones, bits int) preFilterMapType {
`ones` is no longer used, can be removed?

2023-03-31 18:02 UTC, joestringer requested changes
Thanks for the PR! The first commit isn't related to ipcache at all, seems like it could be a separate submission.

I didn't look closely at the second commit yet, but I'm always a bit nervous about whether we are concretely changing initialization ordering and therefore may introduce a bug by factoring out some code like this. I think this is a great direction and I look forward to these changes, but I think that this is also a pretty risky change that could introduce weird and wonderful new bugs because we're not accounting for the initialization ordering and so on. I don't see any explanation about how that works or how that might change in the commit message, and I haven't had a chance to look through in detail to understand the way that Hive might be affecting this, but it would help understanding if the commit/PR messages described this.

Initial review notes below, ran out of time to look deeper.

2023-03-31 18:02 UTC, joestringer commented on bpf/bpf_xdp.c
> -} CIDR4_HMAP_NAME __section_maps_btf;
This commit message talks about ipcache, but none of the functional changes in this commit are related to ipcache. This is the prefilter map, not ipcache. I think you should fix up the commit message etc because mixing up prefilter with ipcache will just be confusing for anyone in future looking through the commits.

2023-03-31 18:02 UTC, joestringer commented on pkg/datapath/ipcache/listener.go
> +// delete the entry.
Please move this to a commit that is related to ipcache.

2023-03-31 18:02 UTC, joestringer commented on pkg/datapath/prefilter/prefilter.go
> +		path = bpf.MapPath(cidrmap.MapName + "v4")
+1 the simplest path here is to avoid changing the names of maps on the filesystem between versions.

2023-03-31 18:02 UTC, joestringer commented on bpf/bpf_xdp.c
> -} CIDR4_HMAP_NAME __section_maps_btf;
(Honestly this whole commit should just be a different PR, I don't see how it relates to the second commit at all.)

2023-03-31 18:02 UTC, joestringer commented on daemon/cmd/state.go
> -			endParallelMapMode()
Can you describe a bit about why this is safe to just remove?

I think there's a background problem that this code is trying to solve during upgrade/restart where we keep an existing valid ipcache map around, create a new one, populate both during the transition period, then over time replace the datapath for each endpoint to refer to the new ipcache map, so that eventually once all datapath objects are converted over, we can safely unpin/remove the old one. I don't know if we have testing that gives strong confidence that we don't break some sort of connectivity during upgrade / prog reload so we may need to just reason through this to explain why we think that's safe.

2023-03-31 18:02 UTC, joestringer commented on daemon/cmd/daemon.go
>  func createPrefixLengthCounter() *counter.PrefixLengthCounter {
Incidentally `createPrefixLengthCounter()` and friends is also a legacy ipcache hmap handling function, we could look at removing that too. But we can follow up on that separately if that's easier. It's logically different from creating a cell for the ipcache initialization.

2023-03-31 19:03 UTC, dylandreimerink commented
Thanks everyone for the reviews so far. The timing of this PR was a bit unfortunate since there is quite some changes to be made seeing the feedback so far, however I have been re-tasked to do some client work. I will still move forward, but it might take me a bit.

I will take all of this feedback, revise the commits, then split them up into 2 PRs as suggested. Should have done that to begin with. The second commit is what the work was initially about, but while doing so I discovered all of the now-legacy code. Removing the legacy code made the modularization step easier. It was only during the "rebase to make neat commits" stage that it separated into two loose steps that can be their own thing. Hope that explains the rational at least.

2023-04-03 08:40 UTC, ti-mo commented on daemon/cmd/datapath.go
> -func endParallelMapMode() {
This would ideally be broken out into a separate commit.

2023-04-03 08:42 UTC, ti-mo commented on daemon/cmd/state.go
> -			endParallelMapMode()
@joestringer I believe this bit was taken from https://github.com/ti-mo/cilium/commit/534160afb97d761e987158be5ba71116e5ed5818, which should have a bit more context. I suggested splitting this out into a separate commit above.

2023-04-03 08:44 UTC, ti-mo commented on pkg/bpf/map_linux.go
> +func (m *Map) Recreate() error {
Hmm, why not do a real charry-pick of https://github.com/ti-mo/cilium/commit/534160afb97d761e987158be5ba71116e5ed5818 or other needed commits from the branch? That way my rebase will be less painful, and I also get some credit. :)

2023-07-06 07:23 UTC, ti-mo commented
My changes to bpf.Map have landed, so this PR can be rebased now. Re-opening.

2023-11-08 12:41 UTC, closed without merging