datapath: DSR+UDP+IPV4, there is no need for advertising a lower MTU
cilium/cilium pull request #24383
Opened 2023-03-15 10:46 UTC by jasongwq

1. when UDP has multiple IPv4 fragments, the IPv4 option extension header is only added to the first fragment.
2. The backends receives the IPv4 option, deletes it, and passes it to the pod(Pod doesn't need to know about svc addr:port).

Fixes: #24359 

```release-note
In DSR IPv4 UDP, can choose the client decrease its MTU by 8bytes or the node's increasing its MTU by 8bytes
```

2023-03-28 15:05 UTC, NikAleksandrov requested changes
Some style and code changes requested, also please rebase to latest master and use the following format for the Fixes tag:
Fixes: <at least 12 chars of commit id> ("commit title")
And I think the commit id you're looking for is 3dfe7a7dc9a1 ("datapath: Add DSR for NodePort BPF IPv4") instead of 97bedb6. Please drop the empty new line between the Fixes tag and the sign off.

2023-03-28 15:05 UTC, NikAleksandrov commented on bpf/lib/nodeport.h
> +    }
no need for the {}

2023-03-28 15:05 UTC, NikAleksandrov commented on bpf/lib/nodeport.h
> +    __be32 sum;
please align these in a reverse xmas tree order (longest to shortest)

2023-03-28 15:05 UTC, NikAleksandrov commented on bpf/lib/nodeport.h
> +{
Please use tabs for indentation everywhere instead of spaces.

2023-03-28 15:05 UTC, NikAleksandrov commented on bpf/lib/nodeport.h
> +                    struct iphdr *ip4, struct dsr_opt_v4 *opt)
align the arguments with tabs as much as possible and use spaces after the tabs if necessary, something like:
```
static __always_inline int dsr_clear_opt4(struct __ctx_buff *ctx,
					  struct iphdr *ip4,
					  struct dsr_opt_v4 *opt)
```

2023-03-28 15:05 UTC, NikAleksandrov commented on bpf/lib/nodeport.h
> +    if (ctx_adjust_hroom(ctx, -8, BPF_ADJ_ROOM_NET,
please add a new constant with descriptive name for the -8 so it's easier to understand what is being adjusted here

2023-03-28 15:05 UTC, NikAleksandrov commented on bpf/lib/nodeport.h
> +			return dsr_clear_opt4(ctx,ip4,&opt);
please leave a space after each argument: `dsr_clear_opt4(ctx, ip4, &opt)`

2023-03-28 15:22 UTC, julianwiedmann commented on bpf/include/bpf/ctx/xdp.h
> +			break;
Note that this is a special-purpose implementation of `ctx_adjust_hroom()`, and doesn't behave as you might expect.

1. your code would currently strip off the first 8 bytes of the L2 header. I believe that's not what you want here.
2. there's an earlier `build_bug_on(len_diff <= 0)` check, so this won't even compile today.

2023-05-05 16:29 UTC, joestringer commented
Hi, the release note says:

> In DSR IPv4 UDP, can choose the client decrease its MTU by 8bytes or the node's increasing its MTU by 8bytes

I don't quite understand how the "choosing" part happens, since I don't see any configurable flags in the changes. How does the user perceive this change? Will it automatically increase MTU when higher MTU is supported by the network? Does it fix a forwarding bug in certain configurations?

2023-05-05 16:30 UTC, joestringer commented
I've converted this to draft while you rebase and address the feedback on the PR. Feel free to mark it "Ready for review" again once you've addressed this, the button is at the bottom of the page.

2023-06-20 01:56 UTC, closed without merging