docs: add note that there are two Cilium CLIs
cilium/cilium pull request #24435
Opened 2023-03-17 18:28 UTC by lizrice

The [Component Overview](https://docs.cilium.io/en/v1.13/overview/component-overview/) describes the (local agent) Cilium CLI. This PR notes that this shouldn't be confused with...the other Cilium CLI 

Please ensure your pull request adheres to the following guidelines:

- [X] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [X] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [X] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/master/USERS.md)
- [X] Thanks for contributing!

2023-03-17 20:12 UTC, joestringer approved these changes

2023-03-20 10:29 UTC, qmonnet approved these changes

2023-03-20 10:33 UTC, qmonnet requested changes
@lizrice We moved this document to `Documentation/overview/component-overview.rst` last June, please update your repository and rebase the commit.

2023-03-21 13:27 UTC, qmonnet approved these changes
Thanks!

2023-03-21 13:28 UTC, qmonnet commented
Doc change only, related workflows passed. We're good to go.

2023-03-21 17:45 UTC, merged