docs: Deprecate CNPStatusUpdates/K8sEventHandover
cilium/cilium pull request #24464
Opened 2023-03-20 12:20 UTC by marseel

CNP Node status updates are known to cause scalability-related issues. Deprecate it in preparation to remove support in a future release, to minimize the maintenance burden of this code.

```release-note
Deprecate CNP Node status updates. 
```

2023-03-22 09:43 UTC, squeed requested changes
One last request (sorry) -- can you add something in [upgrade.rst](https://github.com/cilium/cilium/blob/master/Documentation/operations/upgrade.rst) about the deprecation?

2023-05-30 15:53 UTC, aanm commented
@marseel any updates on this?

2023-05-31 11:32 UTC, qmonnet requested changes

2023-05-31 11:32 UTC, qmonnet commented on Documentation/operations/upgrade.rst
> +  options are deprecated and will be removed in v1.15.
What are they replaced with or what should users use instead? (You explain the motivation in the commit description, but I wouldn't expect users of this section to check it out.)

2023-05-31 13:35 UTC, qmonnet approved these changes
Thank you!

2023-06-01 18:21 UTC, squeed approved these changes

2023-06-05 13:22 UTC, marseel commented
/test

2023-06-05 14:53 UTC, marseel commented
/test

2023-06-06 11:31 UTC, squeed commented
I would argue this change is trivial enough as to not require a full CI run.

2023-06-06 12:46 UTC, marseel commented
> I would argue this change is trivial enough as to not require a full CI run.

Marking as ready-to-merge as all basic CI tests passed.

2023-06-06 13:28 UTC, merged