chart: generate a CA cert with certmanager for hubble tls generation
cilium/cilium pull request #24505
Opened 2023-03-21 15:16 UTC by vflaux

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/master/USERS.md)
- [x] Thanks for contributing!

When hubble tls auto method is set to certmanager with no issuer ref, generate the CA certificate using a self-signed issuer and use this CA for the hubble issuer.

Previous behavior was to generate the CA certificate using helm. It was confusing with the method set to certmanager as we could expect for all cert to be created with certmanager.
The generated secret containing the CA by helm was also missing the "tls.crt" key.

Fixes: #24500

2023-03-28 13:01 UTC, meyskens requested changes
Thanks for this! Just a few small details to note here :)

2023-03-28 13:01 UTC, meyskens commented on install/kubernetes/cilium/values.yaml
> +      issuerCertValidityDuration: 26280
This also needs to be set in the values.yaml.tmpl file for our helm chart and doc generating tool to work

2023-03-28 13:01 UTC, meyskens commented on install/kubernetes/cilium/templates/hubble/tls-certmanager/hubble-issuer.yaml
> +  isCA: true
This will generate an RSA key by default, within Cilium we are already using ECDSA.
https://github.com/cilium/cilium/blob/e63d79ba7a3f7bcae13f89de4e8a37ee29851b2a/examples/kubernetes/servicemesh/ca-issuer.yaml#L17

We might consider doing the same here

2023-03-28 13:01 UTC, meyskens commented on install/kubernetes/cilium/templates/hubble/tls-certmanager/hubble-issuer.yaml
> +  commonName: Cilium CA
We might want to add Hubble here too as Cilium uses certificates for cluster mesh, service mesh, network policy... if a user sees a certificate signed by this it helps to day that it is Cilium Hubble

2023-03-28 13:05 UTC, meyskens commented on install/kubernetes/cilium/values.yaml
> +      issuerCertValidityDuration: 26280
more info about that is at https://github.com/cilium/cilium/blob/9be3b287363bbb2c1ef3160aa5e4bb2c236574fa/Documentation/contributing/development/dev_setup.rst#making-changes-to-the-helm-chart (seems to not yet be released to our docs site)

2023-03-30 04:32 UTC, youngnick approved these changes
Looks like @meyskens' requested changes are done, LGTM now.

2023-04-06 07:04 UTC, giorio94 commented
Hey @vflaux, thanks for your contribution!

This is an heads up that we are merging #24666, which addresses #24500 in a different way. Essentially, that PR makes it mandatory to specify the issuer configuration when using cert-manager. That targets both hubble and clustermesh related configurations, and encourages the best practice of using the same CA for all components. I personally believe it also reduces the overall confusing during operations, explicitly demanding users to select which issuer type to use, since Cilium should not be concerned with the generation of the CA as much as possible. And users can just create a self-signed issuer with whatever deployment method they are using (e.g., flux2) if they are not interested in establishing a clustermesh.

Given the above, I'm closing this PR as superseded. Feel free to comment or open an issue and tag me if you feel something is still missing in this regard.

2023-04-06 07:04 UTC, closed without merging