ci: move 4.19 complexity tests to tests-datapath-verifier GHA workflow
cilium/cilium pull request #24517
Opened 2023-03-22 11:03 UTC by tklauser

It seems the verifier issues with 4.19 are resolved when running complexity tests using LVH on that version. Let's cover it in the the GitHub actions workflow instead of Ginkgo tests.

Successful run with test commit: https://github.com/cilium/cilium/actions/runs/4489169184/jobs/7894672779

2023-03-22 12:28 UTC, pchaigno commented on .github/workflows/tests-datapath-verifier.yaml
> +            ci-kernel: '419'
Did we update the 4.19-main kernel we use here? Is that what we think made the issue disappear?

2023-03-22 12:36 UTC, tklauser commented on .github/workflows/tests-datapath-verifier.yaml
> +            ci-kernel: '419'
I'm not sure how version selection exactly works of the lvh action (/cc @brb), but it seems like we build images from latest 4.19.y stable branch: https://github.com/cilium/little-vm-helper-images/blob/8b568c7421308a200daa53cb595754a7f8e091a0/_data/kernels.json#L23-L26 Current 4.19-main is running 4.19.277:

```
root@complexity-test-4:~# uname -a
Linux complexity-test-4.19 4.19.277 #1 SMP Tue Mar 14 15:39:26 UTC 2023 x86_64 GNU/Linux
```

2023-03-22 13:12 UTC, brb commented on .github/workflows/tests-datapath-verifier.yaml
> +            ci-kernel: '419'
Every merged  little-vm-helper-images PR triggers a rebuild of the LVH VM images which might bump the kernel.

2023-03-22 18:49 UTC, christarazi approved these changes

2023-03-23 05:53 UTC, brlbil approved these changes

2023-03-24 09:11 UTC, ti-mo approved these changes

2023-03-24 09:38 UTC, qmonnet approved these changes
:rocket:

2023-03-24 09:58 UTC, ti-mo commented
/test

2023-03-24 10:32 UTC, pchaigno requested changes
Sorry to be a bit of a pain, but this is highly suspicious to me. AFAIK, the complexity issue we were hitting was https://github.com/cilium/cilium/issues/17647#issuecomment-1014678098, which never got fixed on our side and was happening for more than a year.

Did it get fixed in the kernel without us knowing about it? Is there something else that fixed it very recently on our side? Or is this test actually broken again and not testing what we think?

I'll try to check if something recent on the kernel side could explain this.

2023-03-24 10:44 UTC, ti-mo commented
> Sorry to be a bit of a pain, but this is highly suspicious to me. AFAIK, the complexity issue we were hitting was [#17647 (comment)](https://github.com/cilium/cilium/issues/17647#issuecomment-1014678098), which never got fixed on our side and was happening for more than a year.
> 
> Did it get fixed in the kernel without us knowing about it? Is there something else that fixed it very recently on our side? Or is this test actually broken again and not testing what we think?
> 
> I'll try to check if something recent on the kernel side could explain this.

No problem at all, we need to know this stuff for sure. Take a look at this: https://github.com/cilium/cilium/actions/runs/4509588303/jobs/7939538892?pr=24538. This has much more detailed output and verifier stats for each tail call. It's based on the changes in this PR (adding 4.19 coverage) and loading all ELFs using Go.

I'll add a uname at the start of the test run so we know exactly what we're dealing with.

2023-03-24 12:01 UTC, nebril approved these changes

2023-03-27 08:48 UTC, bimmlerd approved these changes
CODEOWNERS change looks ok

2023-03-27 09:36 UTC, ti-mo commented
@pchaigno Does this really need to remain blocked on your investigation? Sounds like something that can be done on the side. The Go test code looks fine to me. If there are changes to be made to the feature flags, that should be done in a separate PR anyways.

2023-03-28 07:29 UTC, ti-mo commented
All tests green and https://github.com/cilium/cilium/actions/runs/4532665447/jobs/7984382192?pr=24538 (test run of https://github.com/cilium/cilium/pull/24538) shows that the largest program (`tail_handle_ipv4_cont`) of the largest bpf_lxc configuration is currently just within the 4.19 limit:

`verifier_test.go:194: tail_handle_ipv4_cont: processed 127506 insns (limit 131072), stack depth 264`

https://github.com/cilium/cilium/issues/17647 mentions a tail call split being merged close after the issue was reported. I see no reason to block this PR any further, so let's merge please.

2023-03-28 11:20 UTC, pchaigno commented
I ran a bunch of tests and it looks like it's working as expected. I don't have an explanation for why it was failing only a few weeks/months ago (no significant verifier or datapath changes were merged since then). It could just be small changes pushing us below & above the limit, though that's fairly rare with complexity issues as the complexity doesn't tend to increase/decrease linearly.

That all said, I also checked the workflow is passing and current master and it fails: https://github.com/cilium/cilium/actions/runs/4542358481/jobs/8005682276?pr=24599. That means if we were to merge, we would break CI :disappointed:

2023-03-30 04:15 UTC, ldelossa approved these changes
Approval contingent on: https://github.com/cilium/cilium/pull/24517#issuecomment-1486675725 passing.

2023-04-03 15:23 UTC, qmonnet approved these changes
Putting my docs-structure hat on, and approving again

2023-04-04 15:54 UTC, lmb commented
/test-ci-verifier

2023-04-04 16:24 UTC, lmb commented
This is :heavy_check_mark:  on 4.19 now, with only cluster aware addressing disabled: https://github.com/cilium/cilium/actions/runs/4609988154/jobs/8147889395

2023-04-04 16:37 UTC, pchaigno approved these changes
LGTM (assuming the test commit is removed of course).

2023-04-04 20:49 UTC, zacharysarah approved these changes
LGTM from a docs perspective.n 👍🏻

2023-04-04 21:26 UTC, merged