gh/workflows: Merge ci-dp 1.13 and main workflows
cilium/cilium pull request #24545
Opened 2023-03-23 13:00 UTC by brb

The only diff between two is the trigger phrases. However, nobody stops us from adding "/test-backport-1.13" to the conformance-datapath.yaml.

2023-03-23 13:31 UTC, gentoo-root requested changes

2023-03-23 13:31 UTC, gentoo-root commented on .github/workflows/conformance-datapath-v1.13.yaml
> -      - name: Run encryption tests
> The only diff between two is the trigger phrases.

Am I missing something? I see many more differences when I compare these two files. For example, this entire section is missing from the other one.

2023-03-23 13:31 UTC, gentoo-root commented on .github/workflows/conformance-datapath.yaml
> +        contains(github.event.comment.body, '/test')
Isn't it going to trigger a lot of false positives, though?

2023-03-23 13:31 UTC, gentoo-root commented on .github/workflows/conformance-datapath.yaml
>          github.event.comment.body == '/ci-datapath' ||
What about `/ci-datapath-1.13`?

2023-03-23 14:05 UTC, brb commented on .github/workflows/conformance-datapath-v1.13.yaml
> -      - name: Run encryption tests
This got moved into separate configuration sections - https://github.com/cilium/cilium/pull/24296

2023-03-23 14:06 UTC, brb commented on .github/workflows/conformance-datapath.yaml
> +        contains(github.event.comment.body, '/test')
It's just for concurrency group name.

2023-03-23 14:06 UTC, brb commented on .github/workflows/conformance-datapath.yaml
>          github.event.comment.body == '/ci-datapath' ||
No need for that one, as `/ci-datapath` can be used to trigger the workflow.

2023-03-23 14:09 UTC, gentoo-root commented on .github/workflows/conformance-datapath.yaml
> +        contains(github.event.comment.body, '/test')
The comment above says:

```
# Note: for `issue_comment` triggers, we additionally need to filter out based
# on comment content, otherwise any comment will interrupt workflow runs.
```

That means that now any comment that has `/test` inside (for example, this one) will interrupt workflow runs, won't it?

2023-03-23 14:15 UTC, gentoo-root commented on .github/workflows/conformance-datapath-v1.13.yaml
> -      - name: Run encryption tests
They moved only from conformance-datapath.yaml for some reason...

There are many other differences, this one was just an example. Some differences point to issues that are still open (e.g., #23461). This patch doesn't look like a refactoring that doesn't change the behavior.

2023-03-24 16:07 UTC, nbusseneau requested changes
I don't think we should do this: the intent behind having separate workflows for 1.13 and `master` is so that we freeze the 1.13 workflow and then any changes made on `master` are not done on 1.13 unless explicitly involved in a backport.

Putting them together could lead to a situation where changes are made on `master` and then the workflow starts not working on 1.13 because of other drift that was not backported.

2023-03-24 16:42 UTC, pchaigno commented on .github/workflows/conformance-datapath.yaml
>          github.event.comment.body == '/ci-datapath' ||
That's a bit confusing IMO. We'll have one workflow among tens that doesn't expect the `-1.13` suffix.

2023-03-27 07:58 UTC, aanm requested changes
I agree with Nicolas' point.

2023-04-26 07:05 UTC, closed without merging