Enable update-ec2-adapter-limit-via-api by default
cilium/cilium pull request #24564
Opened 2023-03-24 19:54 UTC by christarazi

This prevents reports of crashes of the Operator because the instance
type limits are not up-to-date.

Related: https://github.com/cilium/cilium/issues/18197

Signed-off-by: Chris Tarazi <chris@isovalent.com>

2023-03-24 22:23 UTC, christarazi commented
/test

2023-03-24 22:34 UTC, chancez commented
You'll want to update `eni.updateEC2AdapterLimitViaAPI` in helm values too.

2023-03-24 22:59 UTC, chancez commented
This could also require updated IAM permissions for Cilium or the node IAM role to allow `ec2:DescribeInstances`. In EKS, nodes usually have `AmazonEKSWorkerNodePolicy` which includes this permission, so it should work in most cases unless the user configured Cilium to use it's own AWS credentials separate from the node.

2023-03-25 00:06 UTC, christarazi commented
> You'll want to update `eni.updateEC2AdapterLimitViaAPI` in helm values too.

That is the value that I modified, no?

2023-03-27 15:56 UTC, chancez commented
> That is the value that I modified, no?

Github hid the diff, my bad. I confused it with the markdown files being changed.

2023-03-29 00:44 UTC, christarazi commented
/test

2023-03-29 11:02 UTC, squeed approved these changes

2023-03-29 15:25 UTC, chancez approved these changes

2023-03-31 11:12 UTC, qmonnet requested changes

2023-03-31 11:12 UTC, qmonnet commented on install/kubernetes/cilium/values.yaml
> +  updateEC2AdapterLimitViaAPI: true
Just like CI reports, this change must go to `install/kubernetes/cilium/values.yaml.tmpl` in the first place.

(Then `make -C install/kubernetes` and `make -C Documentation update-helm-values`, but I think you've covered all the changes it should bring already?)

2023-03-31 11:12 UTC, qmonnet commented on Documentation/operations/upgrade.rst
> +  false to true. This means that the Cilium Operator will fetch the most
Nit, feel free to ignore.

```suggestion
  ``false`` to ``true``. This means that the Cilium Operator will fetch the most
```

2023-03-31 11:12 UTC, qmonnet commented on Documentation/operations/upgrade.rst
> +  ``--update-ec2-adapter-limit-via-api`` to false if you want to avoid this
```suggestion
  ``--update-ec2-adapter-limit-via-api`` to ``false`` if you want to avoid this
```

2023-04-04 23:43 UTC, christarazi commented
Apologies for the noise, mis-clicked on the GH UI.

2023-04-04 23:47 UTC, christarazi commented
/test

2023-04-05 08:55 UTC, qmonnet approved these changes

2023-04-11 18:42 UTC, christarazi commented
/test

2023-04-12 14:50 UTC, nbusseneau approved these changes

2023-04-12 16:42 UTC, merged