Enable previously disabled encryption tests on GKE
cilium/cilium pull request #24603
Opened 2023-03-28 10:44 UTC by brlbil

Encryption connectivity tests were failing on new versions of GKE clusters.
Now the tests are passing and it is not clear how it is fixed.
The issue might be gone due to some changes on cilium or changes done on the cloud provider side.

Fixes: #22808

2023-03-28 13:38 UTC, brlbil commented
Tests are passing see below.

https://github.com/cilium/cilium/actions/runs/4542154957/jobs/8006809084
https://github.com/cilium/cilium/actions/runs/4542154962/jobs/8007762078
https://github.com/cilium/cilium/actions/runs/4542154978/jobs/8005216727

2023-03-28 18:31 UTC, aanm approved these changes

2023-03-28 21:14 UTC, pchaigno requested changes
I'm a bit undecided on whether reenabling this right now is a good idea.

On one hand, the longer we leave tests disabled, the more likely they are to regress. On the other, (1) we don't have a good explanation of why this may not be failing anymore, (2) it seems you only executed it once, and (3) the GKE workflow isn't really super stable at the moment (because of https://github.com/cilium/cilium/issues/22368 mostly). So I'm worried we'll just be adding to the flakiness noise of the GKE workflow is this ends up not being fixed.

Having written this down, I think I've shifted my opinion from Comment review to Request changes review :sweat_smile: Sorry.

Could we at least run this workflow ~10 times to ensure the original flake looks fixed? Or what the original issue not a flake but a complete test breakage?

2023-03-29 04:46 UTC, brlbil commented
@pchaigno It also bugs me that we do not why the issue seems to be fixed.
It certainly would not hurt if we run the tests more times.

2023-03-29 21:53 UTC, brlbil commented
@pchaigno  I have run the tests many times, and there were some errors but none of them were about encryption.
I have seen more than 10 successful tests.

2023-03-30 08:46 UTC, pchaigno approved these changes
Nice! Thanks for checking!

Let's merge then. We can always rerevert if we see it fail.

2023-04-04 07:22 UTC, merged