envoy: Bump envoy to v1.25.3
cilium/cilium pull request #24649
Opened 2023-03-30 13:00 UTC by sayboras

This is the latest envoy version, just for testing purpose.

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/master/USERS.md)
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note

```

2023-03-31 10:45 UTC, sayboras commented
/test

2023-03-31 12:47 UTC, sayboras commented
/test-1.26-net-next

2023-04-01 09:38 UTC, sayboras commented
/test

2023-04-01 12:18 UTC, sayboras commented
/test-1.26-net-next

2023-04-05 13:27 UTC, sayboras commented
/test

2023-04-06 05:02 UTC, sayboras commented
/test

2023-04-06 06:00 UTC, sayboras commented
ci-eks failure is due to https://github.com/cilium/cilium/issues/24774

```
2023-04-06T05:24:51.260101017Z level=info msg="Initializing IPAM" mode=eni subsys=cilium-operator-aws
2023-04-06T05:24:51.262287672Z level=info msg="Starting ENI allocator..." subsys=ipam-allocator-aws
2023-04-06T05:24:54.209325867Z level=warning msg="Unable to synchronize EC2 VPC list" error="operation error EC2: DescribeVpcs, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , request send failed, Post \"https://ec2.us-east-2.amazonaws.com/\": dial tcp: lookup ec2.us-east-2.amazonaws.com on 10.100.0.10:53: write udp 192.168.189.83:56692->10.100.0.10:53: write: operation not permitted" subsys=eni
2023-04-06T05:24:54.209357228Z level=fatal msg="Unable to start eni allocator" error="Initial synchronization with instances API failed" subsys=cilium-operator-aws
```

2023-04-06 16:57 UTC, jrajahalme requested changes
Better remove the stale accesslog server code block.

2023-04-06 16:57 UTC, jrajahalme commented on pkg/envoy/accesslog_server.go
>  		// Default to the deprecated HTTP log format
IMO we should just drop this block altogether. If `pblog.GetHttp()` is non-nil we already take the first `if` statement above.

2023-04-07 03:50 UTC, sayboras commented
/test

2023-04-11 15:38 UTC, sayboras commented
Rebase with master to get the recent CI fixes for ci-eks and ci-datapath.

2023-04-11 15:43 UTC, sayboras commented
/test

2023-04-11 18:03 UTC, meyskens approved these changes
LGTM

2023-04-11 18:05 UTC, jrajahalme approved these changes

2023-04-11 22:20 UTC, sayboras commented
test-1.26-net-next hits https://github.com/cilium/cilium/issues/15455, the error message is exactly same.

```
 	 error: unable to upgrade connection: Authorization error (user=kube-apiserver-kubelet-client, verb=create, resource=nodes, subresource=proxy)
```

2023-04-11 22:20 UTC, sayboras commented
/test-1.26-net-next

2023-04-12 09:48 UTC, tklauser approved these changes

2023-04-12 09:50 UTC, merged