Cli output misc
cilium/cilium pull request #2465
Opened 2018-01-08 11:57 UTC by scanf

CLI output related things. Please see individual patches.

2018-01-09 10:50 UTC, raybejjani approved these changes

2018-01-09 13:26 UTC, scanf commented
Please wait with merging this until @michi-covalent has had a chance to review. Thanks.

2018-01-10 11:59 UTC, aanm requested changes

2018-01-10 11:59 UTC, aanm commented on pkg/endpoint/policy.go
> -	e.getLogger().Debugf("TriggerPolicyUpdatesLocked: changed: %d", changed)
`%t`

2018-01-10 12:23 UTC, scanf commented on pkg/endpoint/policy.go
> -	e.getLogger().Debugf("TriggerPolicyUpdatesLocked: changed: %d", changed)
Cool, missed that.

2018-01-11 20:47 UTC, aanm approved these changes

2018-01-12 10:24 UTC, raybejjani commented
test-me-please

2018-01-16 18:22 UTC, scanf commented
test-me-please

2018-01-16 18:45 UTC, michi-covalent approved these changes

2018-01-17 22:46 UTC, ianvernon commented
test-me-please

2018-01-18 12:02 UTC, aanm commented
test-me-please

2018-01-19 04:45 UTC, ianvernon commented
test-me-please

2018-01-19 11:26 UTC, eloycoto commented
test-all-ginkgo

2018-01-19 16:33 UTC, aanm commented
test-all-ginkgo

2018-01-19 16:39 UTC, scanf commented
Superseded by #2587

2018-01-19 16:39 UTC, closed without merging