Ginkgo: Improved failed report on Kubernetes
cilium/cilium pull request #2466
Opened 2018-01-08 12:02 UTC by eloycoto

- Create Kubernetes folders with version
- Added -o wide in Kubernetes commands

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

2018-01-08 13:42 UTC, aanm requested changes

2018-01-08 13:42 UTC, aanm commented on test/helpers/utils.go
> +	testPath := fmt.Sprintf("%s%s%s/",
Try use filepath.Join

2018-01-08 16:36 UTC, ianvernon approved these changes
LGTM, but as @aanm said, please use `filepath.Join`.

2018-01-08 16:39 UTC, eloycoto commented
changes are done, and PR rebased. 

Regards

2018-01-08 16:40 UTC, ianvernon approved these changes

2018-01-08 18:51 UTC, ianvernon commented
test-me-please

2018-01-09 12:07 UTC, eloycoto commented
The problem in the failing test: 

```
19:13:05 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: ----- 10-proxy.sh: main/proxy_test: beginning proxy test
19:13:05 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: ----- 10-proxy.sh: main/proxy_test/monitor_clear: clearing monitor
19:13:05 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: ----- 10-proxy.sh: main/proxy_test: trying to reach server IPv4 at http://10.11.193.100:80/public from client (expected: 200)
19:13:05 [Runtime Tests with Envoy] ==> cilium-master-build-Cilium-Bash-Tests-9-envoy: e4e3e63a2a591d595585ebe14678542cdc779f6af8d3747df47148e4ee7a773f
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: Internal Server Error
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: ------------------------------------------------------------------------
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9:                             Test Failed
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: GET /public, unexpected return 500 != 200
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: 
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: ------------------------------------------------------------------------
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: #kernel
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: IpInReceives                    22                 0.0
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: IpInDelivers                    22                 0.0
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: IpOutRequests                   23                 0.0
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: TcpActiveOpens                  2                  0.0
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: TcpPassiveOpens                 2                  0.0
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: TcpEstabResets                  1                  0.0
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: TcpInSegs                       22                 0.0
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: TcpOutSegs                      23                 0.0
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: TcpOutRsts                      1                  0.0
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: TcpExtTCPPrequeued              1                  0.0
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: TcpExtTCPDirectCopyFromPrequeue 1216               0.0
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: TcpExtTCPHPHits                 1                  0.0
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: TcpExtTCPHPHitsToUser           1                  0.0
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: TcpExtTCPPureAcks               7                  0.0
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: TcpExtTCPHPAcks                 2                  0.0
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: TcpExtTCPAbortOnData            1                  0.0
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: TcpExtTCPOrigDataSent           11                 0.0
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: IpExtInOctets                   3967               0.0
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: IpExtOutOctets                  4600               0.0
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: IpExtInNoECTPkts                22                 0.0
19:13:06 [Runtime Tests] ==> cilium-master-build-Cilium-Bash-Tests-9: 
```

Looks like that it's a random fail no related with the new Jenkins process.

2018-01-10 08:25 UTC, eloycoto commented
test-me-please

2018-01-10 14:33 UTC, aanm approved these changes

2018-01-10 14:33 UTC, merged