bpf: inline test functions with ctx as input
cilium/cilium pull request #24662
Opened 2023-03-31 05:03 UTC by anfernee

Run ebpf test on kernel v5.11 will raise the following error:

  Validating build_packet() func#1...
  btf_vmlinux is malformed
  Arg#0 type PTR in build_packet() is not supported yet.

It's due to missing kernel patch e5069b9c "bpf: Support pointers in global func args". Inline those functions so the ebpf test can also run on v5.11 and older kernels.

Please ensure your pull request adheres to the following guidelines:

- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes. n/a

Fixes: #issue-number

```release-note

```

2023-03-31 08:58 UTC, gentoo-root requested changes
> It's due to missing kernel patch e5069b9c "bpf: Support pointers in global func args".

This patch shouldn't be needed. As its commit message says, this patch adds support for pointer types different from PTR_TO_CTX, and PTR_TO_CTX used to be supported before. The pointer in scope of your commit is PTR_TO_CTX.

I believe the real root cause of the error you see is `btf_vmlinux is malformed`. [When it happens](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/kernel/bpf/btf.c?h=v5.11#n4317), the verifier can't determine the type of the context pointer and treats `struct __ctx_buff *ctx` as PTR instead of PTR_TO_CTX.

Regarding `btf_vmlinux is malformed`, I'm not entirely sure why it happens, but a brief search hints that it might be because something was wrong with pahole or gcc during kernel compilation.

2023-03-31 17:49 UTC, anfernee commented
Thanks for the quick reply! 

> > It's due to missing kernel patch e5069b9c "bpf: Support pointers in global func args".
> 
> This patch shouldn't be needed. As its commit message says, this patch adds support for pointer types different from PTR_TO_CTX, and PTR_TO_CTX used to be supported before. The pointer in scope of your commit is PTR_TO_CTX.
> 
> I believe the real root cause of the error you see is `btf_vmlinux is malformed`. [When it happens](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/kernel/bpf/btf.c?h=v5.11#n4317), the verifier can't determine the type of the context pointer and treats `struct __ctx_buff *ctx` as PTR instead of PTR_TO_CTX.

I see! This makes sense. 

> 
> Regarding `btf_vmlinux is malformed`, I'm not entirely sure why it happens, but a brief search hints that it might be because something was wrong with pahole or gcc during kernel compilation.

I am also not sure why it happens, but inline the functions do fix the problem and make the test runnable on those kernels. Fixing Ubuntu kernel seem to the right approach, but considering it's not going to happen anytime soon. Do you think this patch can be accepted?

2023-03-31 17:55 UTC, pchaigno approved these changes
I think it's an acceptable change, but the rationale needs to be updated in the commit description as per Maxim's comment. Other than that, LGTM.

cc @dylandreimerink

2023-04-01 00:50 UTC, anfernee commented
Thanks @pchaigno  Re-worded the commit message.

2023-04-03 08:45 UTC, gentoo-root approved these changes

2023-04-03 09:23 UTC, dylandreimerink commented
> I think it's an acceptable change

Yes, agreed. Making these function always inline should also improve support for older kernels without BPF-to-BPF support (not that we are currently running the suite on those versions).

2023-04-03 11:56 UTC, merged

2023-04-03 16:12 UTC, anfernee commented
Thanks everyone!