Add go runtime scheduler latency metrics
cilium/cilium pull request #24745
Opened 2023-04-04 23:03 UTC by derailed

The Agent/Controller largely depends on various goroutines being scheduled on time to perform critical control plane tasks (i.e. like controllers, etc...)

We want to be able to detect/alert goroutine scheduling latency, specifically when CPU contention is so great that things may not be running on time.

- Added GOR scheduler latency metric to the default GO metrics collector

Signed-off-by: Fernand Galiana fernand.galiana@isovalent.com

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/master/USERS.md)
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
Expose Cilium agent go runtime scheduler latency prometheus metric `go_sched_latencies_seconds`
```

Signed-off-by: Fernand Galiana fernand.galiana@isovalent.co

2023-04-05 20:22 UTC, tommyp1ckles approved these changes

2023-04-05 20:48 UTC, christarazi requested changes
Thanks for the PR!

It looks good to me. There are a couple of things that need to be addressed

* The checkpatch job in CI is failing on a "bad sign-off". I think this can be fixed by amending your commit by doing `git commit --amend --signoff`.
* We should add a note in the upgrade guide for v1.14 that a new metric was added. You can add this inside `Documentation/operations/upgrade.rst` under the "Added Metrics" section.

2023-04-05 22:08 UTC, christarazi commented
FYI @derailed in case you didn't notice, but the sign-off is from your personal email.

2023-04-05 22:08 UTC, zacharysarah approved these changes
LGTM from a (limited) docs perspective.

2023-04-07 01:08 UTC, christarazi approved these changes

2023-04-07 05:27 UTC, tommyp1ckles commented
/test

2023-04-12 15:45 UTC, christarazi commented
/test

2023-04-12 18:39 UTC, tommyp1ckles commented
Tests look good 🙏

2023-04-12 19:20 UTC, merged