ipsec: Clean up stale XFRM policies and states
cilium/cilium pull request #24773
Opened 2023-04-05 20:08 UTC by pchaigno

Fixes: https://github.com/cilium/cilium/pull/24030.

```
Fix IPsec bug that causes connectivity issues across nodes when upgrading from a previous version of Cilium.
```

2023-04-05 20:20 UTC, pchaigno commented
/test

2023-04-06 10:52 UTC, pchaigno commented
/test

2023-04-07 12:41 UTC, pchaigno commented
/test

2023-04-10 04:35 UTC, jschwinger233 commented on pkg/datapath/linux/ipsec/ipsec_linux.go
> +		if new.Spi == s.Spi && new.Mark == s.Mark &&
`xfrmState.Mark` is of type `*XfrmMark`, so `new.Mark == s.Mark` is true only if `new.Mark == s.Mark == nil`, or they point to the same object, but the latter one can't be true, am I right?

2023-04-10 12:20 UTC, pchaigno commented on pkg/datapath/linux/ipsec/ipsec_linux.go
> +		if new.Spi == s.Spi && new.Mark == s.Mark &&
That's correct. I've changed it to check both variables against `nil`.

2023-04-10 12:21 UTC, pchaigno commented
/test

2023-04-10 16:56 UTC, michi-covalent approved these changes
lgtm for cli team files

2023-04-10 17:00 UTC, michi-covalent commented
oh i guess it already is, i see the corresponding issue has release-blocker labels: https://github.com/cilium/cilium/issues/24780

2023-04-11 03:52 UTC, jschwinger233 approved these changes

2023-04-11 17:07 UTC, YutaroHayakawa commented on pkg/datapath/linux/ipsec/ipsec_linux.go
> +	wildcardIPv6   = net.ParseIP("0::0")
Nit: This can be `::`.

2023-04-11 17:17 UTC, YutaroHayakawa commented on pkg/datapath/linux/ipsec/ipsec_linux.go
> +		log.WithError(err).Error("Cannot get XFRM states")
Don't we need return here?

2023-04-11 17:18 UTC, YutaroHayakawa commented on pkg/datapath/linux/ipsec/ipsec_linux.go
> +		log.WithError(err).Error("Cannot get XFRM policies")
Don't we need return here?

2023-04-11 17:28 UTC, YutaroHayakawa approved these changes
LGTM with non-blocking nits.

2023-04-11 17:36 UTC, asauber approved these changes
`cli` owned files (the logger) LGTM. I'll defer to others for now on the state replacement correctness.

2023-04-11 17:43 UTC, asauber requested changes

2023-04-11 17:45 UTC, asauber approved these changes

2023-04-11 17:46 UTC, pchaigno commented on pkg/datapath/linux/ipsec/ipsec_linux.go
> +		log.WithError(err).Error("Cannot get XFRM policies")
Yep, good point. I'll do that as a follow up, with a bunch of other IPsec code improvements, in the interest of merging this quickly and unblocking backports.

I've checked the source for `XfrmPolicyList` and, if there is an error, an empty slice is always return, so the subsequent for loop will just be a noop.

2023-04-11 20:59 UTC, merged