Update k8s tests and libraries to v1.27.0
cilium/cilium pull request #24837
Opened 2023-04-12 12:01 UTC by tklauser

Updating k8s libs to v1.27.0 requires updating
sigs.k8s.io/controller-runtime to an unreleased version with https://github.com/kubernetes-sigs/controller-runtime/pull/2223 in place. This in turn requires some additional adjustments to changed APIs in the controller-runtime, mainly in operator/pkg/gateway-api.

The service.kubernetes.io/topology-aware-hints annotation got deprecated with k8s 1.27 in favor of service.kubernetes.io/topology-mode (see https://github.com/kubernetes/kubernetes/pull/116522). This change keeps support for the deprecated annotation. Support for the new annotation will be added in a successive commit.

Supersedes #24553

```release-note
Add support for Kubernetes v1.27
```

2023-04-12 14:30 UTC, nbusseneau commented
/test-1.27-net-next

2023-04-12 20:20 UTC, tklauser commented
/test-upstream

2023-04-12 20:24 UTC, tklauser commented
/test-upstream-k8s

2023-04-13 16:01 UTC, tklauser commented
/test

2023-04-13 20:58 UTC, christarazi approved these changes

2023-04-17 08:55 UTC, aanm requested changes
Discussed offline

2023-04-18 01:00 UTC, zacharysarah requested changes
@tklauser 👋🏻 Some edits for clarity, otherwise LGTM from a docs perspective

2023-04-18 01:00 UTC, zacharysarah commented on vendor/github.com/golang-jwt/jwt/v4/README.md
> +1. To install the jwt package, you first need to have [Go](https://go.dev/doc/install) installed, then you can use the command below to add `jwt-go` as a dependency in your Go program.
Edits for clarity
```suggestion
1. To install the jwt package, first install [Go](https://go.dev/doc/install). Then you can use the following command to add `jwt-go` as a dependency in your Go program.
```

2023-04-18 01:00 UTC, zacharysarah commented on vendor/github.com/golang-jwt/jwt/v4/README.md
> +This library publishes all the necessary components for adding your own signing methods or key functions.  Simply implement the `SigningMethod` interface and register a factory method using `Register
Avoid "simply", "just", "easy", etc.
```suggestion
This library publishes all the necessary components for adding your own signing methods or key functions.  Implement the `SigningMethod` interface and register a factory method using `RegisterSigningMethod` or provide a `jwt.Keyfunc`.
```

2023-04-18 01:00 UTC, zacharysarah commented on vendor/github.com/golang-jwt/jwt/v4/README.md
> +A common use case would be integrating with different 3rd party signature providers, like key management services from various cloud providers or Hardware Security Modules (HSMs) or to implement addi
Edits for clarity
```suggestion
A common use case is to integrate with third party signature providers, like key management services from various cloud providers or hardware security modules (HSMs), or to implement additional standards.
```

2023-04-18 01:00 UTC, zacharysarah commented on vendor/github.com/golang-jwt/jwt/v4/README.md
> +*Disclaimer*: Unless otherwise specified, these integrations are maintained by third parties and should not be considered as a primary offer by any of the mentioned cloud providers
Use available RST callouts
```suggestion
.. note::
Unless otherwise specified, these integrations are maintained by third parties and should not be considered as a primary offer by any of the mentioned cloud providers
```

2023-04-18 01:00 UTC, zacharysarah commented on vendor/github.com/golang-jwt/jwt/v4/SECURITY.md
> +As of February 2022 (and until this document is updated), the latest version `v4` is supported.
Edited for plain language
```suggestion
As of February 2022, the latest version supported is `v4`.
```

2023-04-18 01:00 UTC, zacharysarah commented on vendor/github.com/golang-jwt/jwt/v4/SECURITY.md
> +We appreciate your help!
Edit for clarity
```suggestion
If you think you've found a vulnerability, even if you're not sure, please report it to jwt-go-security@googlegroups.com or one of the other [golang-jwt maintainers](https://github.com/orgs/golang-jwt/people). Be explicit when describing steps to reproduce the security issue. Provide code example(s).

You'll receive a response as soon as we can get back to you. If the issue is confirmed, we'll do our best to release a patch as soon as possible.

## Public Discussions

Please avoid discussing potential security vulnerabilities in public.

Finding a solution first limits a vulnerability's potential impact.

We appreciate your help!
```

2023-04-18 06:28 UTC, tklauser commented on vendor/github.com/golang-jwt/jwt/v4/README.md
> +1. To install the jwt package, you first need to have [Go](https://go.dev/doc/install) installed, then you can use the command below to add `jwt-go` as a dependency in your Go program.
@zacharysarah This change is in a 3rd party dependency package which we copy 1:1 to our code base. We'd need to make the changes upstream first and then vendor them back in. I think this is out of scope for this PR.

2023-04-18 06:28 UTC, tklauser commented on vendor/github.com/golang-jwt/jwt/v4/README.md
> +This library publishes all the necessary components for adding your own signing methods or key functions.  Simply implement the `SigningMethod` interface and register a factory method using `Register
Same here, these docs are part of a 3rd party dependency.

2023-04-18 06:28 UTC, tklauser commented on vendor/github.com/golang-jwt/jwt/v4/README.md
> +A common use case would be integrating with different 3rd party signature providers, like key management services from various cloud providers or Hardware Security Modules (HSMs) or to implement addi
Same here, these docs are part of a 3rd party dependency.

2023-04-18 06:28 UTC, tklauser commented on vendor/github.com/golang-jwt/jwt/v4/README.md
> +*Disclaimer*: Unless otherwise specified, these integrations are maintained by third parties and should not be considered as a primary offer by any of the mentioned cloud providers
Same here, these docs are part of a 3rd party dependency.

2023-04-18 06:28 UTC, tklauser commented on vendor/github.com/golang-jwt/jwt/v4/SECURITY.md
> +As of February 2022 (and until this document is updated), the latest version `v4` is supported.
Same here, these docs are part of a 3rd party dependency.

2023-04-18 06:29 UTC, tklauser commented on vendor/github.com/golang-jwt/jwt/v4/SECURITY.md
> +We appreciate your help!
Same here, these docs are part of a 3rd party dependency.

2023-04-18 06:31 UTC, tklauser commented
@zacharysarah The changes you requested are all in the 3rd party dependency package `github.com/golang-jwt/jwt/v4` which we copy 1:1 to our code base, see https://go.dev/ref/mod#vendoring for how vendoring works in Go. We'd need to make the changes in the upstream package first and then vendor them back in. I think this is out of scope for this PR. What do you think?

2023-04-18 08:40 UTC, tklauser commented
/test-1.27-net-next

2023-04-18 08:40 UTC, tklauser commented
/test-upstream-k8s

2023-04-18 09:13 UTC, aanm approved these changes

2023-04-18 10:49 UTC, tklauser commented
/test-1.27-net-next

2023-04-18 10:49 UTC, tklauser commented
/test-upstream-k8s

2023-04-18 11:45 UTC, tklauser commented
/test

2023-04-18 13:39 UTC, tklauser commented
/test-upstream-k8s

2023-04-18 20:48 UTC, zacharysarah commented
@tklauser 👋🏻 
> We'd need to make the changes in the upstream package first and then vendor them back in. I think this is out of scope for this PR. What do you think?

I agree that those changes are out of scope for this PR, but that doesn't mean I have to like it. 😅

For future PRs that import vendor content, is there a way to signal that clearly? I'd like to avoid giving unnecessary reviews.

2023-04-18 20:48 UTC, zacharysarah approved these changes

2023-04-18 21:34 UTC, tklauser commented
@zacharysarah 👋 

> @tklauser 👋🏻
> 
> > We'd need to make the changes in the upstream package first and then vendor them back in. I think this is out of scope for this PR. What do you think?
> 
> I agree that those changes are out of scope for this PR.

Sorry for taking your time to review these files 😞

> For future PRs that import vendor content, is there a way to signal that clearly? I'd like to avoid giving unnecessary reviews.

I think GitHub should hide the files under `vendor/` by default in the review view:

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/539708/232909851-131cb4a6-7784-480b-964a-e576e9edd14c.png">

Unfortunately it also hides other files which still might be of interest, e.g. in case the diff is too large. But at least this should be a good first indicator.

maybe this is something we could point out more explicitly in the contributor guide's [pull requests review process docs](https://docs.cilium.io/en/v1.13/contributing/development/contributing_guide/)?

2023-04-19 09:21 UTC, sayboras approved these changes
Thanks and looks good to me for servicemesh related files

2023-04-19 15:02 UTC, nbusseneau approved these changes

2023-04-19 15:07 UTC, merged