WIP: use cilium ubuntu image for Ginkgo runtime tests
cilium/cilium pull request #2491
Opened 2018-01-10 19:40 UTC by ianvernon

2018-01-10 19:40 UTC, ianvernon commented
test-me-please

2018-01-10 20:39 UTC, ianvernon commented
test-me-please

2018-01-10 21:46 UTC, ianvernon commented
test-me-please

2018-01-10 22:43 UTC, ianvernon commented
test-me-please

2018-01-10 23:56 UTC, ianvernon commented
test-me-please

2018-01-11 00:51 UTC, ianvernon commented
Build failed due to a deadlock detected in the agent:
```
cmd: "sudo journalctl -xe -u cilium --no-pager" exitCode: 0 
 -- Logs begin at Wed 2018-01-10 16:05:20 PST, end at Wed 2018-01-10 16:35:53 PST. --
Jan 10 16:35:50 runtime cilium-agent[5646]: goroutine 185506 lock 0xc4212f65a4
Jan 10 16:35:50 runtime cilium-agent[5646]: /home/vagrant/go/src/github.com/cilium/cilium/daemon/endpoint.go:336 main.(*Daemon).deleteEndpoint { ep.Mutex.Lock() } <<<<<
Jan 10 16:35:50 runtime cilium-agent[5646]: /home/vagrant/go/src/github.com/cilium/cilium/daemon/endpoint.go:425 main.(*Daemon).DeleteEndpoint { return d.deleteEndpoint(ep), nil }
Jan 10 16:35:50 runtime cilium-agent[5646]: /home/vagrant/go/src/github.com/cilium/cilium/pkg/workloads/containerd/watcher.go:138 containerd.processEvent { workloads.Owner().DeleteEndpoint(endpoint.NewID(endpoint.ContainerIdPrefix, m.ID)) }
Jan 10 16:35:50 runtime cilium-agent[5646]: /home/vagrant/go/src/github.com/cilium/cilium/pkg/workloads/containerd/watcher.go:125 containerd.processContainerEvents { processEvent(m) }
Jan 10 16:35:50 runtime cilium-agent[5646]: goroutine 162441 lock 0xc420adbddc
Jan 10 16:35:50 runtime cilium-agent[5646]: /home/vagrant/go/src/github.com/cilium/cilium/daemon/endpoint.go:333 main.(*Daemon).deleteEndpoint { ep.BuildMutex.Lock() } <<<<<
Jan 10 16:35:50 runtime systemd[1]: cilium.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 10 16:35:50 runtime cilium-agent[5646]: /home/vagrant/go/src/github.com/cilium/cilium/daemon/endpoint.go:425 main.(*Daemon).DeleteEndpoint { return d.deleteEndpoint(ep), nil }
Jan 10 16:35:50 runtime cilium-agent[5646]: /home/vagrant/go/src/github.com/cilium/cilium/pkg/workloads/containerd/watcher.go:138 containerd.processEvent { workloads.Owner().DeleteEndpoint(endpoint.NewID(endpoint.ContainerIdPrefix, m.ID)) }
Jan 10 16:35:50 runtime cilium-agent[5646]: /home/vagrant/go/src/github.com/cilium/cilium/pkg/workloads/containerd/watcher.go:125 containerd.processContainerEvents { processEvent(m) }
Jan 10 16:35:50 runtime cilium-agent[5646]: All current goroutines:
Jan 10 16:35:50 runtime cilium-agent[5646]: goroutine 167788 [running]:
Jan 10 16:35:50 runtime cilium-agent[5646]: github.com/cilium/cilium/vendor/github.com/sasha-s/go-deadlock.stacks(0x2b5dea0, 0xc42000e020, 0x0)
Jan 10 16:35:50 runtime cilium-agent[5646]:         /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/sasha-s/go-deadlock/stacktraces.go:101 +0xa7
Jan 10 16:35:50 runtime cilium-agent[5646]: github.com/cilium/cilium/vendor/github.com/sasha-s/go-deadlock.lock(0xc4204a7720, 0x1a8df60, 0xc420e5fbc8)
Jan 10 16:35:50 runtime cilium-agent[5646]:         /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/sasha-s/go-deadlock/deadlock.go:176 +0x6d9
Jan 10 16:35:50 runtime cilium-agent[5646]: github.com/cilium/cilium/vendor/github.com/sasha-s/go-deadlock.(*RWMutex).Lock(0xc420e5fbc8)
Jan 10 16:35:50 runtime cilium-agent[5646]:         /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/sasha-s/go-deadlock/deadlock.go:89 +0x75
Jan 10 16:35:50 runtime cilium-agent[5646]: github.com/cilium/cilium/pkg/kvstore.LockPath(0xc420059ce0, 0x6e, 0x0, 0x0, 0x0)
Jan 10 16:35:50 runtime cilium-agent[5646]:         /home/vagrant/go/src/github.com/cilium/cilium/pkg/kvstore/lock.go:87 +0x26a
Jan 10 16:35:50 runtime cilium-agent[5646]: main.(*Daemon).CreateOrUpdateIdentity(0xc4200ee480, 0xc4206bc150, 0xc420801030, 0x5, 0x0, 0x0, 0x0, 0x0)
Jan 10 16:35:50 runtime cilium-agent[5646]:         /home/vagrant/go/src/github.com/cilium/cilium/daemon/labels.go:67 +0x3b3
Jan 10 16:35:50 runtime cilium-agent[5646]: main.(*Daemon).updateEndpointIdentity(0xc4200ee480, 0xc420801030, 0x5, 0x0, 0x0, 0xc4212f6618, 0xc420611378, 0xed82cefc3cc8d401, 0xed88498d94be93c6, 0x2, ...)
Jan 10 16:35:50 runtime cilium-agent[5646]:         /home/vagrant/go/src/github.com/cilium/cilium/daemon/labels.go:144 +0x263
Jan 10 16:35:50 runtime cilium-agent[5646]: main.(*Daemon).EndpointLabelsUpdate(0xc4200ee480, 0xc4212f65a0, 0xc420b0fc80, 0xc420b0fcb0, 0xc420800e11, 0x6)
Jan 10 16:35:50 runtime cilium-agent[5646]:         /home/vagrant/go/src/github.com/cilium/cilium/daemon/endpoint.go:743 +0x479
Jan 10 16:35:50 runtime cilium-agent[5646]: github.com/cilium/cilium/pkg/workloads/containerd.handleCreateContainer(0xc4206a2a00, 0x40, 0x1)
Jan 10 16:35:50 runtime cilium-agent[5646]:         /home/vagrant/go/src/github.com/cilium/cilium/pkg/workloads/containerd/watcher.go:312 +0x8d1
Jan 10 16:35:50 runtime cilium-agent[5646]: github.com/cilium/cilium/pkg/workloads/containerd.processEvent(0xc420800cf8, 0x5, 0xc4206a2a00, 0x40, 0xc4206f83e0, 0x11, 0xc420800d10, 0x9, 0xc420800d19, 0x5, ...)
Jan 10 16:35:50 runtime cilium-agent[5646]:         /home/vagrant/go/src/github.com/cilium/cilium/pkg/workloads/containerd/watcher.go:136 +0xd0
Jan 10 16:35:50 runtime cilium-agent[5646]: github.com/cilium/cilium/pkg/workloads/containerd.processContainerEvents(0xc420bf3560)
Jan 10 16:35:50 runtime cilium-agent[5646]:         /home/vagrant/go/src/github.com/cilium/cilium/pkg/workloads/containerd/watcher.go:125 +0x350
Jan 10 16:35:50 runtime cilium-agent[5646]: created by github.com/cilium/cilium/pkg/workloads/containerd.(*watcherState).enqueueByContainerID
Jan 10 16:35:50 runtime cilium-agent[5646]:         /home/vagrant/go/src/github.com/cilium/cilium/pkg/workloads/containerd/watcher_state.go:59 +0x18a
Jan 10 16:35:50 runtime cilium-agent[5646]: goroutine 1 [semacquire, 4 minutes]:
Jan 10 16:35:50 runtime cilium-agent[5646]: sync.runtime_Semacquire(0xc42033daec)
Jan 10 16:35:50 runtime cilium-agent[5646]:         /usr/local/go/src/runtime/sema.go:56 +0x39
Jan 10 16:35:50 runtime cilium-agent[5646]: sync.(*WaitGroup).Wait(0xc42033dae0)
Jan 10 16:35:50 runtime cilium-agent[5646]:         /usr/local/go/src/sync/waitgroup.go:131 +0x72
Jan 10 16:35:50 runtime cilium-agent[5646]: github.com/cilium/cilium/api/v1/server.(*Server).Serve(0xc4202d2000, 0x1d0a5f8, 0xc4202d2000)
Jan 10 16:35:50 runtime cilium-agent[5646]:         /home/vagrant/go/src/github.com/cilium/cilium/api/v1/server/server.go:307 +0x131
Jan 10 16:35:50 runtime cilium-agent[5646]: main.runDaemon()
Jan 10 16:35:50 runtime cilium-agent[5646]:         /home/vagrant/go/src/github.com/cilium/cilium/daemon/main.go:764 +0xe72
Jan 10 16:35:50 runtime cilium-agent[5646]: main.glob..func1(0x2b49d40, 0xc4204408c0, 0x0, 0x4)
Jan 10 16:35:50 runtime cilium-agent[5646]:         /home/vagrant/go/src/github.com/cilium/cilium/daemon/main.go:123 +0x30
Jan 10 16:35:50 runtime cilium-agent[5646]: github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).execute(0x2b49d40, 0xc420010150, 0x4, 0x4, 0x2b49d40, 0xc420010150)
Jan 10 16:35:50 runtime cilium-agent[5646]:         /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:648 +0x234
Jan 10 16:35:50 runtime cilium-agent[5646]: github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2b49d40, 0xc4203c86f0, 0x191f8c0, 0xc420327880)
Jan 10 16:35:50 runtime cilium-agent[5646]:         /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:735 +0x2fe
Jan 10 16:35:50 runtime cilium-agent[5646]: github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).Execute(0x2b49d40, 0x0, 0xc4203c8200)
Jan 10 16:35:50 runtime cilium-agent[5646]:         /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:693 +0x2b
Jan 10 16:35:50 runtime cilium-agent[5646]: main.main()
Jan 10 16:35:50 runtime cilium-agent[5646]:         /home/vagrant/go/src/github.com/cilium/cilium/daemon/main.go:136 +0x13a
Jan 10 16:35:50 runtime cilium-agent[5646]: goroutine 6 [chan receive]:
Jan 10 16:35:50 runtime cilium-agent[5646]: github.com/cilium/cilium/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x2c0ffa0)
Jan 10 16:35:50 runtime cilium-agent[5646]:         /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/golang/glog/glog.go: [...]

2018-01-11 00:52 UTC, ianvernon commented
test-me-please

2018-01-11 05:08 UTC, ianvernon commented
Successful build running all Ginkgo tests: https://jenkins.cilium.io/job/Cilium-Ginkgo-Tests/46/

2018-01-11 05:13 UTC, ianvernon commented
test-me-please

2018-01-11 07:46 UTC, eloycoto requested changes
Hi, 

I do not really like the strategy of this PR TBH. I think that inherit the bad parts of the past testing framework and make things more complicated: 

1) One of the reasons of why Hashicorp made HCL language is to avoid all the monkey patching of Vagrant. Vagrantfiles should be super small and explicit, right now is a mix of some bash scripts and ruby, super hard to read :-(

2) The cilium/ubuntu-16-10 server image is a bad image; the GOPath is in a super weird location, the kernel doesn't have the headers, no Virtualbox setup. 

3) Due the problems with the Virtualbox Modules, the code needs to be shared over Rsync, and that is wrong from my POV

I think that the packer-ci-build should be updated with Bazel, and that will be more easy for all, and that server will provide us the following: 

- The base image can have any kernel version with proper Virtualbox Server. So different servers can be created in VagrantCloud with something like this: `cilium-ginkgo-4.9` `cilium-ginkgo-4.13` and each night a different kernel version can be tested. (This cover the points that have been spoken on CI2.0 meeting) 

- The base image uses the standard GOPath, and it's easy to made things on top of that. 

- We already spoke in the Cilium Meeting before Xmas to deprecate the cilium/ubuntu-16-10. 

If you need help with the packer-ci-build, I'm happy to provide help. 
Regards.

2018-01-11 16:21 UTC, aanm reviewed
Yey!

2018-01-11 16:21 UTC, aanm commented on test/Vagrantfile
> +$bootstrap = <<SCRIPT
Isn't all of this bootstrap on the `cilium/ubuntu-16.10`?

2018-01-11 16:21 UTC, aanm commented on test/runtime/kvstore.go
> +			"sudo cilium-agent --kvstore etcd --kvstore-opt etcd.address=127.0.0.1:9732")
Out of curiosity, why not `:2379`? Also, is the `--debug` flag omitted by accident? Just asking because it's set for consul (line 77)

2018-01-11 16:24 UTC, aanm commented
> 3. Due the problems with the Virtualbox Modules, the code needs to be shared over Rsync, and that is wrong from my POV

@eloycoto you can use NFS which is always synced between host and the VM

2018-01-11 16:30 UTC, tgraf commented
> I do not really like the strategy of this PR TBH. I think that inherit the bad parts of the past testing framework and make things more complicated:

@eloycoto Can you make a specific proposal on how this can be done differently?

2018-01-11 16:51 UTC, eloycoto commented
@tgraf

Firstly, use the new image, that has a proper VM setup. On that image the following changes are needed: 

- Add the scripts/envoy.sh and scripts/envoy_env.sh

Added the following lines: 
```
curl -SsL https://github.com/cilium/bpf-map/releases/download/v1.0/bpf-map -o bpf-map
chmod +x bpf-map
mv bpf-map /usr/bin

wget -nv https://github.com/bazelbuild/bazel/releases/download/#{BAZEL_VERSION}/bazel-#{BAZEL_VERSION}-installer-linux-x86_64.sh
  chmod +x bazel-#{BAZEL_VERSION}-installer-linux-x86_64.sh
  sudo -E ./bazel-#{BAZEL_VERSION}-installer-linux-x86_64.sh
  sudo -E mv /usr/local/bin/bazel /usr/bin
  rm bazel-#{BAZEL_VERSION}-installer-linux-x86_64.sh

sudo apt-get -y install socat curl jq realpath pv tmux python-sphinx python-pip yamllint
sudo pip install --upgrade pip
sudo pip install sphinx sphinxcontrib-httpdomain sphinxcontrib-openapi

```

**On the vagrantfile**:

Provision: 

All the bash scripts added on the Vagrantfile (`$build`, `$install`) goes to `test/provision/runtime_install.sh` and `test/provision/compile.sh` (Half of the code is already there) 

The ETCD install is not needed, it's already installed by default in the ginkgo base image.  

The current `provision/compile.sh` in the runtime section should change to  use ~/common/build.sh 

All the section to shared folders will be like is now, with the Virtualbox module to /vagrant/ and /src/. 

**On the test**: 

- No need to change the basepath from `/vagrant/` to `/home/vagrant/go/src/github.com/cilium/cilium/test/`
- No need to have SCPToVM and all these changes

2018-01-11 17:54 UTC, ianvernon commented
@eloycoto I will reply to your comments inline. 

Hi,

> I do not really like the strategy of this PR TBH. I think that inherit the bad parts of the past testing framework and make things more complicated:

I am happy to change the scripts for provisioning the VMs to be cleaner. This was done as a stop-gap solution to ensure that we get Envoy support into the Ginkgo build as soon as possible, as in the bash-script based framework, this is the only way with which Cilium is tested as of #2483 . Due to the amount of time it took to get Envoy / Bazel working in the build initially, I viewed this as the least-risky way of doing this. My concerns could be wrong, though. Would you be OK with creation of tasks to handle the merging / migration of the VMs themselves as a follow-up task which can be done after we get this patch merged, so we can have Envoy support as soon as possible?

> One of the reasons of why Hashicorp made HCL language is to avoid all the monkey patching of Vagrant. Vagrantfiles should be super small and explicit, right now is a mix of some bash scripts and ruby, super hard to read :-(

I concur. The Vagrantfile at the root of the repository right now is a mess. I'm open to feedback / changes with how we can change our setup. While complicated, the existing Vagrantfile at the root of the repository has functionality that is extremely useful for developers, specifically being able to easily compile and run Cilium as a systemd service alongside Kubernetes, which allows for easier compilation and testing as compared to having to build a Docker image with Cilium inside. If this can be cleaned up + provide the same functionality, I am all for it.  

> The cilium/ubuntu-16-10 server image is a bad image; the GOPath is in a super weird location, the kernel doesn't have the headers, no Virtualbox setup.

I don't see this GOPATH concern as a big issue; such a concern is subjective. I'm fine with using `packer-ubuntu-16.10` or `packer-ci-build`; the direction code moves between the two repositories isn't of big concern to me. I also do not think it is a 'bad image'. Rather it is one that can be improved to fit our needs.

> Due the problems with the Virtualbox Modules, the code needs to be shared over Rsync, and that is wrong from my POV

I'm not actually sure why we don't include guest additions in the VM for `packer-ubuntu-16.10`. @aanm do you have context regarding this? 

> I think that the packer-ci-build should be updated with Bazel, and that will be more easy for all, and that server will provide us the following:

Sure, we can make the changes here. My only concern is if we hit roadblocks due to Bazel as we did before (which might not be the case, I could just be overly cautious here). 

> The base image can have any kernel version with proper Virtualbox Server. So different servers can be created in VagrantCloud with something like this: cilium-ginkgo-4.9 cilium-ginkgo-4.13 and each night a different kernel version can be tested. (This cover the points that have been spoken on CI2.0 meeting)

Makes sense to me. 

> The base image uses the standard GOPath, and it's easy to made things on top of that.

GOPATH is arbitrary; as long as it works, we'll be OK.

> We already spoke in the Cilium Meeting before Xmas to deprecate the cilium/ubuntu-16-10.

As long as we can keep the current functionality for developers, I'm OK with this. @aanm is there anything baked into the `packer-ubuntu-16.10` image that is not built into the `packer-ci-build` image that we need for development purposes? I think that a lot of the functionality is in the `Vagrantfile` itself at the root of the repository, specifically the Kubernetes provisioning code.

> If you need help with the packer-ci-build, I'm happy to provide help.

Of course! I'm open to a variety of solutions and perspectives regarding this stuff :-)

2018-01-11 21:22 UTC, aanm commented
>I'm not actually sure why we don't include guest additions in the VM for packer-ubuntu-16.10. @aanm do you have context regarding this?

We never need it so far, that's the only reason.

2018-01-12 16:08 UTC, eloycoto commented
Hello! 


1) Happy to merge with a follow-up task. 
2)  I think that it's not a problem to migrate that. But I'm worried about `test/vagrantfile` no the root one ;-) 
3) Ok, I agree here, it's a subjective :-)
4) Ok, the thing is that you need to reboot the server. I did on the CI box. 
5) we can speak about that ;-) 
6)7) ok
8) Only for test vagrantfiles ;-)

2018-01-16 20:55 UTC, ianvernon commented
Closing as @eloycoto will work on implementing this as part of #2252 based off of the above discussion.

2018-01-16 20:55 UTC, closed without merging