bpf/nat: implement support of ICMP4 fragmentation needed at egress
cilium/cilium pull request #25054
Opened 2023-04-21 22:02 UTC by liuyuan10

PR #18414 added support for ingress ICMP "fragmentation needed" support to hande those sent by remote routers. This commit mirrors it to support such ICMP sent from endpoints.

The use case is that pod is redirecting traffic from the world into a tunnel, which has smaller MTU. It may return a ICMP "frag needed" to the remote server that requires SNAT to happen properly on both outer and inner headers.

Address IPv4 part of : #23955

```release-note
Supports IPv4 ICMP "fragmentation needed" in egress SNAT
```

2023-04-24 16:35 UTC, dylandreimerink requested changes
Thank you for this work. Seems very nice overall, just a few small things.

I do have some doubts surrounding the complexity/use-case trade off though.

2023-04-24 16:35 UTC, dylandreimerink commented on bpf/lib/nat.h
> +static __always_inline int
Nothing changed here, why is the newline needed?

2023-04-24 16:35 UTC, dylandreimerink commented on bpf/lib/nat.h
> +	__be32 sum_l4 = 0, sum;
This syntax is taxing, does `int ret, flags = BPF_F_PSEUDO_HDR;` assign `BPF_F_PSEUDO_HDR` to both `ret` and `flags` or only `flags` and does it leave `ret` uninitialized? Same goes for `sum_l4` and `sum`. Please keep to one variable declaration per line to keep this easy to read.

2023-04-24 16:35 UTC, dylandreimerink commented on bpf/lib/nat.h
> +snat_v4_icmp_rewrite_egress_embedded(struct __ctx_buff *ctx,
Can we add at least a small comment to explain what this function does and why? From calling context I can infer what it does, but that requires me to go to a call site to understand it.

2023-04-24 16:40 UTC, pchaigno commented
/test

2023-04-25 17:32 UTC, liuyuan10 commented
> I do have some doubts surrounding the complexity/use-case trade off though.

I agree this is not a common use case. But I do think it's good to support ICMP packets in SNAT (e.g. Pods may have iptables rules rejecting traffic with ICMP). With this change, it's just a few lines more to support other ICMP codes

2023-04-25 18:40 UTC, dylandreimerink commented
>> I do have some doubts surrounding the complexity/use-case trade off though.

> I agree this is not a common use case. But I do think it's good to support ICMP packets in SNAT

The "Datapath BPF Complexity" test passed on the previous iteration with room to spare in the NAT related tail calls, so I think we are good.

2023-04-27 16:50 UTC, liuyuan10 commented
@dylandreimerink what's the next step for this PR? I don't see unresolved comments

2023-04-27 16:59 UTC, dylandreimerink approved these changes
https://github.com/cilium/cilium/pull/25054/files#r1175491486 was not resolved and you had not re-requested a review, so I thought you might still have some amendments, hence the delay. Though this is such a minor thing that I think everything is good as it is. 

Next step is the setting the correct labels which I will do and to run the full test suite once more on the latest changes

2023-04-27 17:00 UTC, dylandreimerink commented
/test

2023-04-27 17:08 UTC, liuyuan10 commented
> https://github.com/cilium/cilium/pull/25054/files#r1175491486 was not resolved and you had not re-requested a review, so I thought you might still have some amendments

Sorry I didn't realize I need to re-request a review. I expect my reply addressed your comment and please mark it resolved if it's ok with you. or let me know if you have other concerns

2023-04-28 08:40 UTC, dylandreimerink commented
/mlh new-flake Cilium-PR-K8s-1.24-kernel-5.4

2023-04-28 08:41 UTC, dylandreimerink commented
/test-1.24-5.4

2023-04-28 14:42 UTC, merged