ci: fix clustermesh worfklows on stable branches
cilium/cilium pull request #25089
Opened 2023-04-24 16:12 UTC by nbusseneau

The clustermesh workflows currently fail on stable branches as they expect `.github/kind-config.yaml.tmpl` to be present, but this file is only present on `main`.

It seems the template file is the only reason we need to checkout the repository, as we do not use any other file from the repository in subsequent steps, so we fix this by removing the checkout of the current branch since we already checkout the `main` branch in a prior step.

Thus, the template file on `main` is used for all worfkows.

2023-04-24 16:39 UTC, giorio94 commented
My fault, sorry for the inconvenience. The checkout step is required to retrieve the helm chart used during installation, but it can be moved after cluster creation.

2023-04-26 12:33 UTC, viktor-kurchenko approved these changes

2023-04-26 13:01 UTC, giorio94 requested changes

2023-04-26 13:01 UTC, giorio94 commented on .github/workflows/conformance-clustermesh.yaml
> -        persist-credentials: false
We need to checkout the target branch to retrieve the helm chart for installation. But this step can be moved after cluster creation.

https://github.com/cilium/cilium/blob/a3db4b477f2aa9d03dcf365eea516d3ddd1d1664/.github/workflows/conformance-clustermesh.yaml#L264

2023-04-26 13:18 UTC, nbusseneau commented on .github/workflows/conformance-clustermesh.yaml
> -        persist-credentials: false
Ow, you're correct, I forgot about the Helm chart.

2023-04-26 15:05 UTC, giorio94 approved these changes
Thanks!

2023-04-27 11:11 UTC, merged