docs: Add platform support to docs
cilium/cilium pull request #25174
Opened 2023-04-27 20:46 UTC by joestringer

We've been distributing ARM architecture images for Cilium for almost
two years, but neglected to mention this up front in the system
requirements or the main docs page. Add this to the docs.

2023-04-27 20:53 UTC, chancez commented on Documentation/operations/system_requirements.rst
> +- ARM64
Did you mean AMD64?

2023-04-27 20:54 UTC, chancez commented on README.rst
> +Cilium images are distributed for ARM64 and AArch64 architectures.
Same as above.

2023-04-27 20:54 UTC, gentoo-root requested changes

2023-04-27 20:54 UTC, gentoo-root commented on Documentation/operations/system_requirements.rst
> +- ARM64
AMD64, I guess? ARM64 and AArch64 are the same thing.

2023-04-27 20:54 UTC, gentoo-root commented on README.rst
> +Cilium images are distributed for ARM64 and AArch64 architectures.
Same here.

2023-04-27 20:55 UTC, gentoo-root commented on Documentation/operations/system_requirements.rst
> +- ARM64
I'm too late, lol :D

2023-04-27 22:15 UTC, joestringer commented
`-ECOFFEE`, thanks for pointing those out. Fixed.

2023-04-27 22:16 UTC, gentoo-root approved these changes

2023-04-28 01:35 UTC, zacharysarah approved these changes
LGTM 👍🏻

2023-04-28 15:06 UTC, chancez approved these changes

2023-05-01 20:12 UTC, joestringer commented
[IntegrationTests job](https://github.com/cilium/cilium/actions/runs/4824916356/jobs/8595252923?pr=25174) hit https://github.com/cilium/cilium/issues/24678, re-running.

2023-05-01 20:44 UTC, merged