pr/christarazi/nodemanager ipcache diff
cilium/cilium pull request #25180
Opened 2023-04-28 00:35 UTC by christarazi

- pkg/set: Support cases where input can be nil
- node/manager: Utilize set.SliceSubsetOf in ipcache deletion

2023-04-28 00:38 UTC, christarazi commented
/test

2023-04-28 01:11 UTC, christarazi commented
/test

2023-05-11 23:40 UTC, christarazi commented
/test

2023-05-11 23:52 UTC, christarazi commented
/test

2023-05-12 11:01 UTC, pippolo84 requested changes
LGTM overall, I've just left a suggestion to improve `SliceSubsetOf`.

2023-05-12 11:01 UTC, pippolo84 commented on pkg/set/set.go
> +	}
This can be simplified as:

```
	if len(sub) == 0 {
		return true, nil
	}
	if len(main) == 0 {
		return len(sub) == 0, sub
	}
```

That's because is fine to return `true, nil` also for `sub == []string{} && main == nil`.

2023-05-12 11:01 UTC, pippolo84 commented on pkg/set/set_test.go
> +		},
Nit: maybe we can also add the following testcase

```
		{
			sub:          []string{},
			main:         nil,
			isSubset:     true,
			expectedDiff: nil,
		},
```

To "enforce" what said in the comment above in case of future changes.

2023-05-12 16:40 UTC, christarazi commented on pkg/set/set.go
> +	}
Thanks, added!

2023-05-12 16:40 UTC, christarazi commented on pkg/set/set_test.go
> +		},
Thanks, added!

2023-05-12 16:41 UTC, christarazi commented
/test

2023-05-12 17:18 UTC, pippolo84 approved these changes
LGTM :rocket:

2023-05-12 19:29 UTC, christarazi commented
Marking ready to merge as we have approving reviews and the Travis failure is due to images missing, but it's not required as the integrations test job (test the same thing AFAIK) succeeded.

2023-05-15 22:47 UTC, merged