v1.11 Backports 2023-05-03
cilium/cilium pull request #25250
Opened 2023-05-03 15:30 UTC by joamaki

* [ ] #25043 (@harsimran-pabla)
 * [ ] #25046 (@nbusseneau)
 * [ ] #24770 (@aditighag)
 * [ ] #25033 (@giorio94)
 * [ ] #25109 (@sayboras)
 * [ ] #25192 (@kaworu)
 * [ ] #25174 (@joestringer)
 * [ ] #25219 (@tommyp1ckles)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 25043 25046 24770 25033 25109 25192 25174 25219; do contrib/backporting/set-labels.py $pr done 1.11; done
```
or with
```
make add-labels BRANCH=v1.11 ISSUES=25043,25046,24770,25033,25109,25192,25174,25219
```

2023-05-03 15:32 UTC, giorio94 approved these changes
My commit looks good. Thanks!

2023-05-03 17:34 UTC, harsimran-pabla commented
BGP change https://github.com/cilium/cilium/pull/25043 is already backported in this https://github.com/cilium/cilium/pull/25139

2023-05-03 17:45 UTC, kaworu approved these changes
My commits LGTM, thanks @joamaki!

2023-05-04 15:15 UTC, sayboras approved these changes
Looks good for my commit, thanks 💯

2023-05-04 15:23 UTC, aditighag approved these changes
Looks good for my commits. Thanks!

2023-05-05 04:44 UTC, tommyp1ckles approved these changes
thanks1

2023-05-05 07:14 UTC, joamaki commented
> Looks good for my commits. Thanks!

Hey, looks like I forgot to fix up pkg/service/service_test.go. After fixing it the same way as in the v1.12 backports I get a test failure:

```
FAIL: service_test.go:833: ManagerTestSuite.TestRestoreServiceWithTerminatingBackends

service_test.go:864:
    // Backends including terminating ones have been restored
    c.Assert(len(m.svc.backendByHash), Equals, 3)
... obtained int = 2
... expected int = 3

OOPS: 0 passed, 1 FAILED
```

Enabling debug logging I get:
```
level=debug msg="Upserting service" backends="[{0  {10.0.0.1 {TCP 8080} 0} false} {0  {10.0.0.2 {TCP 8080} 0} false} {0  {10.0.0.4 {TCP 8080} 0} false}]" loadBalancerSourceRanges="[]" serviceIP="{1.1.1.1 {TCP 80} 0}" serviceName= serviceNamespace= sessionAffinity=true sessionAffinityTimeout=100 subsys=service svcHealthCheckNodePort=0 svcTrafficPolicy=Cluster svcType=NodePort
level=debug msg="Resolving service" l3n4Addr="{IP:1.1.1.1 L4Addr:{Protocol:TCP Port:80} Scope:0}" subsys=service
level=debug msg="Acquired service ID" backends="[{0  {10.0.0.1 {TCP 8080} 0} false} {0  {10.0.0.2 {TCP 8080} 0} false} {0  {10.0.0.4 {TCP 8080} 0} false}]" loadBalancerSourceRanges="[]" serviceID=1 serviceIP="{1.1.1.1 {TCP 80} 0}" serviceName= serviceNamespace= sessionAffinity=true sessionAffinityTimeout=100 subsys=service svcHealthCheckNodePort=0 svcTrafficPolicy=Cluster svcType=NodePort
level=debug msg="Deleting backends from session affinity match" backends="[]" serviceID=1 subsys=service
level=debug msg="Adding new backend" backendID=1 backends="[{0  {10.0.0.1 {TCP 8080} 0} false} {0  {10.0.0.2 {TCP 8080} 0} false} {0  {10.0.0.4 {TCP 8080} 0} false}]" l3n4Addr="{10.0.0.1 {TCP 8080} 0}" loadBalancerSourceRanges="[]" serviceID=1 serviceIP="{1.1.1.1 {TCP 80} 0}" serviceName= serviceNamespace= sessionAffinity=true sessionAffinityTimeout=100 subsys=service svcHealthCheckNodePort=0 svcTrafficPolicy=Cluster svcType=NodePort
level=debug msg="Adding new backend" backendID=2 backends="[{0  {10.0.0.1 {TCP 8080} 0} false} {0  {10.0.0.2 {TCP 8080} 0} false} {0  {10.0.0.4 {TCP 8080} 0} false}]" l3n4Addr="{10.0.0.2 {TCP 8080} 0}" loadBalancerSourceRanges="[]" serviceID=1 serviceIP="{1.1.1.1 {TCP 80} 0}" serviceName= serviceNamespace= sessionAffinity=true sessionAffinityTimeout=100 subsys=service svcHealthCheckNodePort=0 svcTrafficPolicy=Cluster svcType=NodePort
level=debug msg="Adding new backend" backendID=3 backends="[{0  {10.0.0.1 {TCP 8080} 0} false} {0  {10.0.0.2 {TCP 8080} 0} false} {0  {10.0.0.4 {TCP 8080} 0} false}]" l3n4Addr="{10.0.0.4 {TCP 8080} 0}" loadBalancerSourceRanges="[]" serviceID=1 serviceIP="{1.1.1.1 {TCP 80} 0}" serviceName= serviceNamespace= sessionAffinity=true sessionAffinityTimeout=100 subsys=service svcHealthCheckNodePort=0 svcTrafficPolicy=Cluster svcType=NodePort
level=debug msg="Adding backends to affinity match map" backends="[1 2 3]" serviceID=1 subsys=service
level=debug msg="Upserting service" backends="[{0  {10.0.0.1 {TCP 8080} 0} false} {0  {10.0.0.2 {TCP 8080} 0} false} {0  {10.0.0.4 {TCP 8080} 0} true}]" loadBalancerSourceRanges="[]" serviceIP="{1.1.1.1 {TCP 80} 0}" serviceName= serviceNamespace= sessionAffinity=true sessionAffinityTimeout=100 subsys=service svcHealthCheckNodePort=0 svcTrafficPolicy=Cluster svcType=NodePort
level=debug msg="Acquired service ID" backends="[{0  {10.0.0.1 {TCP 8080} 0} false} {0  {10.0.0.2 {TCP 8080} 0} false} {0  {10.0.0.4 {TCP 8080} 0} true}]" loadBalancerSourceRanges="[]" serviceID=1 serviceIP="{1.1.1.1 {TCP 80} 0}" serviceName= serviceNamespace= sessionAffinity=true sessionAffinityTimeout=100 subsys=service svcHealthCheckNodePort=0 svcTrafficPolicy=Cluster svcType=NodePort
level=debug msg="Deleting backends from session affinity match" backends="[]" serviceID=1 subsys=service
level=debug msg="Adding backends to affinity match map" backends="[1 2 3]" serviceID=1 subsys=service
level=warning msg="Unable to add entry to affinity match map" backendID=1 error="Backend 1 already exists in 1 affinity map" serviceID=1 subsys=service
level=warning msg="Unable to add entry to affinity match map" backendID=2 error="Backend 2 already exists in 1 affinity map" serviceID=1 subsys=service
level=warning msg="Unable to add entry to affinity match map" backendID=3 error="Backend 3 already exists in 1 affinity map" serviceID=1 subsys=service
level=debug msg="Restoring service" serviceID=1 serviceIP="1.1.1.1:80" subsys=service
level=debug msg="Restoring service" l3n4Addr="{IP:1.1.1.1 L4Addr:{Protocol:NONE Port:80} Scope:0}" subsys=service
level=info msg="Restored services from maps" failedServices=0 restoredServices=1 subsys=service
level=debug msg="Restoring backend" backendID=1 l3n4Addr="10.0.0.1:8080" subsys=service
level=debug msg="Restoring backend" backendID=2 l3n4Addr="10.0.0.2:8080" subsys=service
level=debug msg="Restoring backend" backendID=3 l3n4Addr="10.0.0.4:8080" subsys=service
level=debug msg="Leaked backend entry not restored" backendID=3 l3n4Addr="{10.0.0.4 {NONE 8080} 0}" subsys=service
level=info msg="Restored backends from maps" failedBackends=0 restoredBackends=2 skippedBackends=1 subsys=service
```

@aditighag Any idea what's going on? Are we missing something important in v1.11?

2023-05-08 14:03 UTC, aditighag requested changes
Sorry, missed the differences about service name +namespace changes.

2023-05-08 14:03 UTC, aditighag commented on pkg/service/service_test.go
> +
Can you revert these changes? Looks like there were accidentally added in the backport commit?

2023-05-08 14:03 UTC, aditighag commented on pkg/service/service_test.go
> +		Namespace: "ns1",
This should be the only difference between 1.11 and newer branches.

2023-05-10 06:57 UTC, YutaroHayakawa commented
Since this branch comes from Jussi's fork, I cannot edit commits to apply Aditi's change. I'll move this to another PR the branch owned by me.

2023-05-10 06:57 UTC, closed without merging