docs: fix typos and formatting
cilium/cilium pull request #25365
Opened 2023-05-10 17:15 UTC by peterj

fix typos and formatting in the docs.

2023-05-10 17:39 UTC, qmonnet commented
Could you please amend your commit to fix the description (you have the description of three different commits in it)? You may drop the `Co-authored-by:` tag here; if you prefer to keep it, I'd appreciate if you could use my work email (`quentin@isovalent.com`) rather than personal one that GitHub uses by default.

---

As far as I understand, GitHub is having internal issues that would explain most of the CI errors we observe.

The Netlify errors are not related to GitHub though:

```
6:16:37 PM: /opt/build/repo/Documentation/network/kubernetes/kubeproxy-free.rst:73: WARNING: Explicit markup ends without a blank line; unexpected unindent.
6:16:37 PM: /opt/build/repo/Documentation/network/kubernetes/kubeproxy-free.rst:94: WARNING: Literal block ends without a blank line; unexpected unindent.
```

Can you please look into this?

2023-05-10 17:41 UTC, qmonnet requested changes

2023-05-10 17:41 UTC, qmonnet commented on Documentation/network/kubernetes/kubeproxy-free.rst
> +by using the following commands below.
There's one indent error here, causing one of the errors in Netlify.

2023-05-10 17:41 UTC, qmonnet commented on Documentation/network/kubernetes/kubeproxy-free.rst
> +   until the Cilium replacement has been installed:
Duplicated contents. Please double-check your commit.

2023-05-10 17:41 UTC, qmonnet commented on Documentation/network/kubernetes/kubeproxy-free.rst
> +   and the kube-apiserver port number reported by ``kubeadm init`` (Kubeadm will use port ``6443`` by default).
Same here, indent error on line 94, plus duplicated contents. Please double-check.

2023-05-10 18:18 UTC, peterj commented
> Could you please amend your commit to fix the description (you have the description of three different commits in it)? You may drop the `Co-authored-by:` tag here; if you prefer to keep it, I'd appreciate if you could use my work email (`quentin@isovalent.com`) rather than personal one that GitHub uses by default.
> 
> As far as I understand, GitHub is having internal issues that would explain most of the CI errors we observe.
> 
> The Netlify errors are not related to GitHub though:
> 
> ```
> 6:16:37 PM: /opt/build/repo/Documentation/network/kubernetes/kubeproxy-free.rst:73: WARNING: Explicit markup ends without a blank line; unexpected unindent.
> 6:16:37 PM: /opt/build/repo/Documentation/network/kubernetes/kubeproxy-free.rst:94: WARNING: Literal block ends without a blank line; unexpected unindent.
> ```
> 
> Can you please look into this?

Looks like a merge gone wrong -- it should be fixed now. I think GH added the co-authored portion, modified it with the your work email.

2023-05-11 10:09 UTC, qmonnet commented on Documentation/network/kubernetes/kubeproxy-free.rst
> +.. important::
```suggestion
Next, generate the required YAML files and deploy them.

.. important::
```

You need a blank line here, or Sphinx considers your directive as part of the paragraph:

![image](https://github.com/cilium/cilium/assets/17001771/ffd0da36-38fb-473e-add3-d5ff9ff5563a)

Please make sure that the formatting changes render correctly in [the preview](https://deploy-preview-25365--docs-cilium-io.netlify.app/network/kubernetes/kubeproxy-free.html).

The rest looks better now, thanks!

2023-05-11 10:09 UTC, qmonnet commented on Documentation/network/kubernetes/kubeproxy-free.rst
> +   and the kube-apiserver port number reported by ``kubeadm init`` (Kubeadm will use port ``6443`` by default).
Nit: We might still want to better wrap these lines (or the ones from the warning above).

2023-05-11 23:23 UTC, qmonnet commented on Documentation/network/kubernetes/kubeproxy-free.rst
> +   until the Cilium replacement has been installed:
One last nit: the colon no longer makes sense here.

```suggestion
   until the Cilium replacement has been installed.
```

Please also re-wrap the warning.

2023-05-12 09:46 UTC, qmonnet approved these changes
Thanks

2023-05-16 22:05 UTC, peterj commented
@qmonnet what are the next steps for this PR? I see the branch if not up to date with main, but I am hesitant to click merge and get into the same cycle as I did with the previous PR (ie. unsigned commits, unclean commit history etc).  Is update with rebase the right option at this point?

2023-05-16 23:19 UTC, qmonnet commented
Hi, no need to rebase against `main`, unless there were a conflict (in which case I'd recommend fixing and rebasing locally before updating the branch, rather than using GitHub's button).

Here we're just missing a review from cilium/sig-k8s. @youngnick could you please take a look?

2023-05-23 15:19 UTC, youngnick approved these changes
Sorry about the delay here.

2023-05-24 08:11 UTC, qmonnet commented
Doc change only, and related tests passed. The full CI suite is not required, we're good to go

2023-05-24 12:26 UTC, merged