Draft: Modular Health Reporting
cilium/cilium pull request #25495
Opened 2023-05-17 01:38 UTC by tommyp1ckles

Draft - for discussion purposes only (for now)

2023-05-19 21:00 UTC, derailed requested changes
@tommyp1ckles Thanks for pushing this thru and for @joamaki for paving the way! 
A bit early but here are some initial thoughts. 
Feel free to consider/discard any of these.

2023-05-19 21:00 UTC, derailed commented on pkg/node/manager/cell.go
> +func newAllNodeManager(lc hive.Lifecycle, ipCache *ipcache.IPCache, healthReporter cell.StatusReporter) (NodeManager, error) {
Seems we should have a better name here ie StatusReporter->HealthReporter.

2023-05-19 21:00 UTC, derailed commented on pkg/node/manager/manager.go
> +			if acc != nil {
Are we holding the lock longer than necessary?

2023-05-19 21:00 UTC, derailed commented on daemon/cmd/status.go
> +	return "cluster-nodes-cient"
Typo?

2023-05-19 21:00 UTC, derailed commented on daemon/cmd/status_test.go
> +func (t *testHealthReporter) Stopped(string) {
I like Jussi impl here ie Down or perhaps NIY being the default ie some other state to better indicate the health module conditions ie  stopped, down or health hasn't been implemented yet? Could be easier to assert where health is missing when we traverse the graph?

2023-05-19 21:00 UTC, derailed commented on pkg/datapath/linux/node.go
> +	reconcileErrs []error
Should we just go with multierror here vs just a slice? Guessing this will become something else as we mature but for the time being, i think multierror mechanics could fit the bill?

2023-05-19 21:00 UTC, derailed commented on pkg/hive/cell/health.go
> +	StatusUnknown  Level = "Unknown"
Perhaps we should go with not implemented as unknown could indicate another state? Also distinguish down vs stopped?

2023-05-19 21:00 UTC, derailed commented on pkg/hive/cell/health.go
> +type StatusReporter interface {
As mentioned above status is a bit misleading here. Likely should go with a particular aspect of status in this case health? ie Health, HealthReporter/Provider or HealthProbe??

2023-05-19 21:00 UTC, derailed commented on pkg/hive/cell/health.go
> +		moduleStatuses: make(map[string]Status),
Perhaps modulesHealth or healthProbes as this is the graphs state of affairs?

2023-05-19 21:00 UTC, derailed commented on pkg/hive/cell/health.go
> +	p.moduleStatuses[moduleID] = Status{Update: Update{
In case of re-entry might want to check if a given module already reported health?

2023-05-19 21:00 UTC, derailed commented on pkg/hive/cell/health.go
> +func NewHealthStatus() *HealthStatus {
nit: comment

2023-05-19 21:00 UTC, derailed commented on pkg/hive/cell/health.go
> +type Status struct {
nit: comment

2023-05-19 21:00 UTC, derailed commented on pkg/hive/cell/health.go
> +type Update struct {
nit: comment

2023-05-19 21:00 UTC, derailed commented on pkg/hive/cell/health.go
> +	StatusUnknown  Level = "Unknown"
nit: comment consts

2023-05-19 21:00 UTC, derailed commented on pkg/hive/cell/health.go
> +type Level string
nit: comment

2023-05-19 21:00 UTC, derailed commented on pkg/hive/cell/health.go
> +type HealthStatus struct {
nit: comment

2023-05-19 21:00 UTC, derailed commented on pkg/hive/cell/health.go
> +func (p *HealthStatus) Processed() uint64 {
nit: comment

2023-05-19 21:00 UTC, derailed commented on pkg/hive/cell/health.go
> +func (r *reporter) Degraded(reason string) {
nit: comments

2023-05-19 21:00 UTC, derailed requested changes
@tommyp1ckles Thanks for pushing this thru and for @joamaki for paving the way! 
A bit early but here are some initial thoughts. 
Feel free to consider/discard any of these.

2023-05-26 18:07 UTC, closed without merging

2023-05-26 18:07 UTC, tommyp1ckles commented
@derailed Thanks for the feedback, I think I covered (most) of these in my latest PR.