Cover `ENABLE_L7_LB` in complexity tests
cilium/cilium pull request #25526
Opened 2023-05-18 12:00 UTC by Thearas

Fixes: https://github.com/cilium/cilium/issues/23062

2023-05-18 21:08 UTC, pchaigno commented
/ci-verifier

2023-05-18 21:09 UTC, pchaigno commented
Hi :wave: Thanks for contributing this! It looks like there's a bunch of conflicts that will need to be solved before we can merge.

2023-05-19 03:24 UTC, Thearas commented
> Hi 👋 Thanks for contributing this! It looks like there's a bunch of conflicts that will need to be solved before we can merge.

Done.

2023-05-19 09:19 UTC, pchaigno requested changes
A couple of issues from the rebase.

2023-05-19 09:19 UTC, pchaigno commented on bpf/complexity-tests/419/bpf_host.txt
> +-DSKIP_DEBUG=1 -DENABLE_IPV6=1 -DENABLE_ROUTING=1 -DPOLICY_VERDICT_NOTIFY=1 -DALLOW_ICMP_FRAG_NEEDED=1 -DENABLE_IDENTITY_MARK=1 -DMONITOR_AGGREGATION=3 -DCT_REPORT_FLAGS=0x0002 -DENABLE_HOST_FIREWALL
Why did you add new configs here instead of extending the existing ones?

2023-05-19 09:19 UTC, pchaigno commented on bpf/complexity-tests/419/bpf_overlay.txt
> +=======
That doesn't look intended.

2023-05-19 09:50 UTC, Thearas commented on bpf/complexity-tests/419/bpf_overlay.txt
> +=======
Sorry, I forgot to remove it.

2023-05-19 10:16 UTC, pchaigno approved these changes

2023-05-19 10:17 UTC, pchaigno commented
/ci-verifier

2023-06-20 11:03 UTC, ti-mo commented
@Thearas Sorry, looks like this will need another rebase. Will merge after 1.14 release.

2023-06-27 12:48 UTC, ldelossa commented
@Thearas gentle ping. If you'd like to move this PR forward please rebase.

2023-07-31 02:58 UTC, closed without merging