daemon: Separate endpoint API handlers from daemon and add tests
cilium/cilium pull request #25583
Opened 2023-05-22 13:40 UTC by joamaki

WIP, on top of https://github.com/cilium/cilium/pull/25000

2023-05-22 14:46 UTC, joamaki commented on daemon/restapi/endpoints_test.go
> +// SPDX-License-Identifier: Apache-2.0
TODO remember to rename this file as well

2023-07-10 09:44 UTC, aanm approved these changes

2023-07-10 11:11 UTC, bimmlerd approved these changes

2023-07-10 11:11 UTC, bimmlerd commented on daemon/restapi/endpoint_test.go
> +			// TODO what else to assert?
I'd vote in favour of having golden tests here; manually asserting seems more error-prone

2023-07-17 08:53 UTC, joestringer commented
/test

2023-07-17 13:12 UTC, joestringer requested changes
LGTM from the perspective of improving code cleanliness, code coverage in testing. There's a scattering of TODOs that look like they should be grappled with prior to merging. Once those are addressed, feel free to dismiss this review and go ahead with merging.

2023-11-19 01:48 UTC, closed without merging