Unify feature probing packages
cilium/cilium pull request #25627
Opened 2023-05-23 16:57 UTC by rgo3

With this PR we remove the `HaveFullLPM()` feature probe as it is no longer needed since cilium bumped its minimal supported kernel version to 4.19.

We also migrate any leftover APIs from `pkg/probe` to `pkg/datapath/linux/probes` to only have one go `pkg` for feature probing APIs.

Fixes: #25621

2023-05-24 09:26 UTC, rgo3 commented
/test

2023-05-24 12:15 UTC, ti-mo requested changes
Thanks! We can remove moar code!

2023-05-24 12:15 UTC, ti-mo commented on pkg/datapath/prefilter/prefilter.go
>  	c := preFilterConfig{
It looks like `preFilterConfig` can only ever have all its flags set to `true`, so we should probably remove it in a subsequent commit.

2023-05-24 12:15 UTC, ti-mo commented on pkg/datapath/linux/probes/probes.go
> +func HaveIPv6Support() error {
Could we add a test that expects this to succeed unconditionally?

2023-05-24 12:59 UTC, squeed approved these changes

2023-05-24 13:01 UTC, mhofstetter approved these changes

2023-05-24 13:44 UTC, ti-mo approved these changes

2023-05-25 04:20 UTC, jschwinger233 approved these changes

2023-05-25 13:30 UTC, ti-mo commented
/test

2023-05-26 06:52 UTC, ti-mo commented
/test

2023-05-26 13:26 UTC, ti-mo commented
/test-1.16-4.19

2023-05-29 11:58 UTC, merged