Add new experiments to reduce Hubble traffic
cilium/cilium pull request #25647
Opened 2023-05-24 12:54 UTC by AwesomePatrol

Part of https://github.com/cilium/cilium/issues/23111 (more info there)

```
name \ time/op    base         field_mask   endpoint_and_nodename_dedup  endpoint_and_nodename_dedup_with_field_mask
RelayGetFlows-24  20.0µs ±10%  12.7µs ± 7%                  13.7µs ± 5%                                  11.8µs ± 4%

name \ alloc/op   base         field_mask   endpoint_and_nodename_dedup  endpoint_and_nodename_dedup_with_field_mask
RelayGetFlows-24  13.1kB ± 0%  6.7kB ± 0%                   7.6kB ± 1%                                   6.1kB ± 0%

name \ allocs/op  base         field_mask   endpoint_and_nodename_dedup  endpoint_and_nodename_dedup_with_field_mask
RelayGetFlows-24  192 ± 0%     140 ± 0%                     133 ± 0%                                     121 ± 1%
```

I am not sure about `TransmitNodenameOnce` as it gives the least benefit compared to introduced complexity.
Benchmarks were refactored (they are also tests as it is easier to check the functionality there than in `TestLocalObserverServer_GetFlows`).

```release-note
Reduce Hubble observe traffic by transmitting identity once (experimental)
```

2023-06-05 10:10 UTC, kaworu requested changes
Thanks for the patch @AwesomePatrol!

> I am not sure about `TransmitNodenameOnce` as it gives the least benefit compared to introduced complexity.

Generally speaking, we try our best to avoid introducing logic into Hubble Relay itself. Specifically, mutating either the request or the response should be considered carefully, and in this instance it is not worth the performance gain in my view. cc @rolinh @gandro

See my inline comment about `TransmitEndpointOnce`.

Additionally, I'm requesting changes here because I feel the PR is missing the logic of how clients should "reconstruct full flows" when both (or either) of theses flags are given in the request (a POC patch of https://github.com/cilium/hubble would be a great example). Although I'm hesitant to introduce state tracking into the Hubble server, the server-side complexity seems reasonable. I fear that the client code might be trickier though, hence the request.

2023-06-05 10:10 UTC, kaworu commented on pkg/hubble/observer/local_observer.go
> +	}
Couple of issues here:

First, an endpoint ID can be reused at some point, which is not handled by this codepath. To that end we could [subscribe to the `endpointManager`](https://github.com/cilium/cilium/blob/2a966f4f140c47a4d90b3358de7c0ab9f2984546/pkg/endpointmanager/subscribe.go#L15-L18) (specifically `EndpointDeleted` would remove the corresponding entry in `seen`).

Secondly (unrelated to the above code), since endpoint IDs are per-node we should assume that duplicate values are possible. This, in combination with endpoint ID re-use (and potentially flowmasking `node_name`) could make it non-trivial to track from the client's perspective.

cc @joestringer

2023-06-06 07:27 UTC, AwesomePatrol commented
Sounds fair enough. Now that I read the code allocating Endpoint IDs, I understand that there are no guarantees to when it will be reused. Hubble-relay would either need to get this information in GetFlowResponses (for example as a Timestamp when ID was allocated or a notification on changes to endpoints) or it would need to fetch this data locally. In both cases I agree that it unnecessarily complicates Hubble-relay and most benefit is already part of field masking.

Thanks for the response. I will close this PR until I have better idea

2023-06-06 07:27 UTC, closed without merging

2023-06-06 07:35 UTC, AwesomePatrol commented
Maybe I was to quick to discard this PR. There two more ideas:
1. Use Identity ID - as it is correlated to labels, does it have better guarantees to avoid collisions and be consistent across the nodes?
2. Add UUIDs to Flows and send only data that changes (needs to keep a cache of active flows on client side which can be a lot, but at least it can avoid changes to Hubble-relay)

2023-06-06 08:39 UTC, kaworu commented
> Use Identity ID - as it is correlated to labels, does it have better guarantees to avoid collisions and be consistent across the nodes?

Assuming you're referring to [Cilium security identity](https://docs.cilium.io/en/stable/internals/security-identities/#security-identities), I think we'll run into a different kind of collision as distinct endpoints (e.g. `ep0`, `ep1` colocated on the same node)  can share the same security identity (`secid`) when they have the same labels. Here `secid` is not enough information disambiguate whether the endpoint was `ep0` or `ep1`.

> Add UUIDs to Flows and send only data that changes (needs to keep a cache of active flows on client side which can be a lot, but at least it can avoid changes to Hubble-relay)

This is an interesting idea! Note that [flows already have an `uuid` field](https://github.com/cilium/cilium/blob/0991c6d992a2b6f0ad6ef13f4c1df900b09cbced/api/v1/flow/flow.proto#L16-L17).

We could have a signal that a given flow should be cached to be used as base for following "diff" flows, e.g. `experimental.parent="true"` for the first flow in a TCP session, then "diff" flows would reference their parent (`experimental.parent="$parentUUID"`). Cache GC could be TTL based on the base flow time, maybe also LRU limited on the server side? Also need to think about how multiple clients requesting caching will be handled server-side. Since the Hubble server is part of the Cilium agent, we should be very careful about memory consumption.

Once cache management is solved, then we need a solution to clear fields (e.g. base flow has `traffic_direction=EGRESS` and diff flow has `traffic_direction=TRAFFIC_DIRECTION_UNKNOWN` which is the zero value) but maybe that could be done throuh a flowmask of the updated fileds (`experimental.fieldMask` would have `{paths: ["traffic_direction", …]}`).

Finally, the CPU/memory overhead should be measured, especially server side. I would be less worried about the introduced complexity as I'm expecting this facility to be easier to cover with unit tests than the patch proposed by this PR. Although most of the gain will probably come from caching the source/destination endpoints, it's generic and has huge potential going forward in my opinion.