Add workload context to hubble context labels.
cilium/cilium pull request #25667
Opened 2023-05-25 11:01 UTC by marqc

Workload context labels hubble metrics with namespace and workload name.

Please ensure your pull request adheres to the following guidelines:

- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.

As `pod-short` is deprecated and going to be removed in 1.14, current `workload-name` isn't a sufficient replacement as it misses the namespace.

```release-note
Add workload label context (hubble metrics).
```

2023-05-25 17:04 UTC, chancez requested changes
1 minor issue.

2023-05-25 17:04 UTC, chancez commented on Documentation/observability/metrics.rst
> +``workload``          Kubernetes pod's workload name and namespace in front of ``namespace/workload-name``.
Phrasing here could be improved. 

```suggestion
``workload``          Kubernetes pod's workload name and namespace in the form of ``namespace/workload-name``.
```

2023-05-25 23:03 UTC, zacharysarah approved these changes
@marqc Nits need fixing as per @chancez's review, otherwise LGTM from a docs perspective. I'm approving with the understanding that changes must be made prior to merge.

2023-05-26 06:41 UTC, marqc commented on Documentation/observability/metrics.rst
> +``workload``          Kubernetes pod's workload name and namespace in front of ``namespace/workload-name``.
done

2023-05-26 15:34 UTC, chancez approved these changes

2023-05-26 18:37 UTC, nathanjsweet approved these changes

2023-05-30 09:37 UTC, kaworu approved these changes

2023-05-30 09:37 UTC, kaworu commented
/test

2023-06-12 10:26 UTC, kaworu commented
/test

2023-06-21 01:09 UTC, zacharysarah approved these changes
LGTM

2023-06-27 13:09 UTC, ldelossa commented
@marqc please rebase this PR on main and push. Should fix any issues with our tests.

2023-06-27 17:50 UTC, ldelossa commented
/test

2023-06-30 13:32 UTC, ldelossa commented
/test

2023-06-30 14:42 UTC, ldelossa commented
@marqc 

Sorry to ask you to do this, but it appears all your PRs are having trouble triggering TravisCI. 
I tried to see if I can open a PR myself with your fork, but GH does not recognize your fork when we attempt to 'compare across forks'. 

I'm going to leave this message on your other PRs as well, but can you please close this PR and open a new one with the same changes? Hopefully this will fix these issues.

2023-07-07 09:40 UTC, squeed commented
I give up with travis :-/ -- I'm going to run the travis build manually on my laptop and see that it passes. This should merge easily.

2023-07-07 10:03 UTC, squeed commented
I manually ran travis and it worked fine. Given that this PR is so small, I think this acceptable.

2023-07-07 10:03 UTC, merged

2023-07-27 10:33 UTC, marqc commented
@squeed can we backport this to 1.14? As pod-short is removed in 1.14 this will be usable as "in-place replacement"