Add support of storing the caBundle in a secret
cilium/cilium pull request #25728
Opened 2023-05-26 21:38 UTC by farcaller

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

This allows to e.g. pull it from vault via external-secrets (as ES cannot write to a ConfigMap).

```release-note
Allow to use a Secret for the caBundle
```

2023-06-16 12:04 UTC, sayboras commented
:wave: friendly ping if you have a chance to perform the above. Also, would you mind to rebase with main branch for latest CI configuration.

2023-06-16 12:26 UTC, farcaller commented
@sayboras thanks for a ping! I got a bit distracted by my cilium setup breaking down in new and exciting ways but I'm back to this and I have a working solution that I just need to rewrite this nix into helm yamls: 😄 

```nix
{
      patchCM = object:
        let
          volumes = object.spec.template.spec.volumes;
          projected = builtins.filter (v: builtins.hasAttr "projected" v) volumes;
          nonProjected = builtins.filter (v: builtins.hasAttr "projected" v == false) volumes;
          reprojected = builtins.map
            (p: lib.recursiveUpdate p (
              let
                caSources = builtins.filter (s: (s.configMap or { name = ""; }).name == "cilium-ca") p.projected.sources;
                nonCaSources = builtins.filter (s: (s.configMap or { name = ""; }).name != "cilium-ca") p.projected.sources;
                patchedSources = builtins.map
                  (s: {
                    secret = {
                      items = [{ key = "certificate"; path = (builtins.head s.configMap.items).path; }];
                      name = "cilium-ca";
                    };
                  })
                  caSources;
              in
              {
                projected.sources = nonCaSources ++ patchedSources;
              }
            ))
            projected;
        in
        (lib.recursiveUpdate object {
          spec.template.spec.volumes = nonProjected ++ reprojected;
        });

      patchOn = cond: object:
        if (cond object) then patchCM object
        else object;

      patchCiliumDS = patchOn (object: (object.kind == "DaemonSet" && object.metadata.name == "cilium"));
      patchApiServerDeployment = patchOn (object: (object.kind == "Deployment" && object.metadata.name == "clustermesh-apiserver"));
      patchHubbleRelayDeployment = patchOn (object: (object.kind == "Deployment" && object.metadata.name == "hubble-relay"));
      patchHubbleUIDeployment = patchOn (object: (object.kind == "Deployment" && object.metadata.name == "hubble-ui"));
}
```

2023-06-16 13:50 UTC, joamaki commented
Heading on vacation so unassigned myself and picked @tommyp1ckles from sig-k8s by lottery (`sort -R sig-k8s | head -1`).

2023-06-21 22:31 UTC, joestringer commented
cc @cilium/sig-hubble I think some of you folks have spent more time with Cilium's secret management previously and could potentially help advise on the solution here.

2023-06-22 08:40 UTC, gandro commented
Also cc @giorio94 who added the CA bundle feature.

To me, the overall motivation "this allows to e.g. pull it from vault via external-secrets (as ES cannot write to a ConfigMap)." sounds very reasonable. Since we have not shipped the CA bundle feature in a release yet, I'd even say let's always make it a secret if that makes the CA bundle easier to manage (and I'm not a big fan of having a resource either be a configmap or a secret based on a Helm value).

It was also the case that before we added the CA bundle, the CA was already part of a secret, so that should also not be a problem. But I think it would be interesting to know from @giorio94 if there is a particular reason why the CA bundle is a ConfigMap, or if the intent just was that "it's a public key, so it doesn't need to be a secret".

I'm marking this as a release blocker for now, since I think this is something that we can quite easily resolve now, where it will become harder to resolve once we release the CA bundle feature.

2023-06-22 08:49 UTC, giorio94 commented
> It was also the case that before we added the CA bundle, the CA was already part of a secret, so that should also not be a problem. But I think it would be interesting to know from @giorio94 if there is a particular reason why the CA bundle is a ConfigMap, or if the intent just was that "it's a public key, so it doesn't need to be a secret".

No specific reason beside the fact that it is not a "secret" value as you mentioned, and to mimic the kubernetes behavior (specifically the `kube-root-ca.crt` ConfigMap, indeed also the default name was picket to look like that). But I don't personally have any objection to making that a secret if it simplifies the CABundle management process.

2023-06-22 09:04 UTC, gandro requested changes
Please run `make -C install/kubernetes`, it generates the `install/kubernetes/cilium/README.md` which needs to be updated if you add or change Helm values.

2023-06-22 09:04 UTC, gandro commented on install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml
> +          - {{ if .Values.tls.caBundle.useSecret }}secret{{ else }}configMap{{ end }}:
So there are multiple uses of `.Values.tls.caBundle.enabled` in our Helm charts. I think you will have to change all of them to use this pattern.

2023-06-22 09:04 UTC, gandro commented
Thanks @giorio94 for the quick response! 

I did a quick look at trust-manager, and it seems to only support ConfigMaps unfortunately https://cert-manager.io/docs/projects/trust-manager/api-reference/#bundlespectarget 

So maybe we do need to use flag that switches between ConfigMap and Secrets :disappointed: 

In that case I'll remove the release-blocker label again, since the change with `useSecret` can be done in a backwards compatible manner and I think this PR still needs a bit of iteration.

2023-06-22 09:07 UTC, giorio94 commented
> I did a quick look at trust-manager, and it seems to only support ConfigMaps unfortunately https://cert-manager.io/docs/projects/trust-manager/api-reference/#bundlespectarget

Oh right, I actually forgot to double-check it. Thanks!

2023-06-22 11:32 UTC, farcaller commented
(sorry for a sudden pull of all the people. I rebased from a shadow clone 😞 )

2023-06-22 14:59 UTC, gandro commented
Another CI failure:

```
 Validating documentation (syntax, spelling)...

Please fix the following spelling mistakes:
* Documentation/helm-values.rst:2667: (useSecret)  tls.caBundle.useSecret
* Documentation/helm-values.rst:2667: (useSecret)  tls.caBundle.useSecret

If the words are not misspelled, run:
Documentation/update-spelling_wordlist.sh useSecret 
```

2023-06-22 16:07 UTC, chancez reviewed
LGTM in terms of helm changes.

2023-06-23 06:16 UTC, sayboras commented
/test

2023-06-23 06:42 UTC, sayboras approved these changes
The changes lgtm ✅

2023-06-23 08:40 UTC, kaworu approved these changes
Thanks for the patch @farcaller!

Couple of cosmetic comments, but other than that LGTM.

2023-06-23 08:40 UTC, kaworu commented on install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml
> +          - {{ if .Values.tls.caBundle.useSecret }}secret{{ else }}configMap{{ end }}:
nitpicking:
```suggestion
          - {{ .Values.tls.caBundle.useSecret | ternary "secret" "configMap" }}:
```

2023-06-23 08:40 UTC, kaworu commented on install/kubernetes/cilium/values.yaml.tmpl
> +    # -- Use a Secret instead of a ConfigMap
nitpicking

```suggestion
    # -- Use a Secret instead of a ConfigMap.
```

2023-06-23 08:51 UTC, kaworu requested changes
Please squash all the PR's commits into one on the way!

2023-06-23 08:51 UTC, kaworu commented on install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml
> +          - {{ .Values.tls.caBundle.useSecret | ternary "secret" "configMap" }}::
I think there is an extra column here
```suggestion
          - {{ .Values.tls.caBundle.useSecret | ternary "secret" "configMap" }}:
```

2023-06-23 08:52 UTC, farcaller commented on install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml
> +          - {{ .Values.tls.caBundle.useSecret | ternary "secret" "configMap" }}::
Derp, thanks for catching it!

2023-06-23 09:11 UTC, kaworu approved these changes

2023-06-23 09:52 UTC, ti-mo commented
One more: https://github.com/cilium/cilium/actions/runs/5354804806/jobs/9712313069?pr=25728
```
-     - Use a Secret instead of a ConfigMap
+     - Use a Secret instead of a ConfigMap.
```

2023-06-23 10:59 UTC, farcaller commented
> One more

Done (thought that one was supposed to be re-generated from `make -C install/kubernetes`)

2023-06-26 09:44 UTC, gandro approved these changes

2023-06-26 09:45 UTC, gandro commented
/test

2023-06-26 14:22 UTC, ldelossa commented
All required tests passing. Merging.

2023-06-26 15:48 UTC, michi-covalent approved these changes

2023-06-26 16:49 UTC, qmonnet approved these changes
“docs” change looks good. Thanks!

2023-06-26 16:50 UTC, merged