Retire Cilium-Integrated Istio documentation
cilium/cilium pull request #25722
Opened 2023-05-26 17:03 UTC by networkop

## Summary

[Cilium documentation](https://docs.cilium.io/en/v1.13/network/istio/) refers to a custom Istio build that enables enforcement of L7 policies on an mTLS traffic encrypted by Istio. The [associated repository](https://github.com/cilium/istio) has been archived for quite some time but our documentation has not been updated which becomes a source of [confusion](https://github.com/cilium/cilium/issues/18465).

This PR includes updated documentation on the most up-to-date integration with Istio, focusing on the caveats and limitations.

2023-05-28 05:07 UTC, sayboras commented on install/kubernetes/cilium/values.yaml.tmpl
> -  # container image names
This one seems to be still required, the comment `Configure Istio proxy options` might be mis-leanding.

2023-05-31 07:08 UTC, bimmlerd approved these changes
contributing changes are trivial - I think Sarah is the main review here :)

2023-06-07 23:49 UTC, zacharysarah requested changes
@networkop Good start! 🌟 Some changes are required, otherwise LGTM from a docs perspective. Also:

![Screenshot 2023-06-07 at 4 19 41 PM](https://github.com/cilium/cilium/assets/3210446/64b074f8-7373-401d-bf80-25cd457acf55)

😻

2023-06-07 23:49 UTC, zacharysarah commented on Documentation/network/servicemesh/istio.rst
> +This document covers the following common aspects of Cilium's integration with Istio:
Use clear, plain language
```suggestion
This page helps you get started using Istio with a Cilium-enabled Kubernetes cluster.
This document covers the following common aspects of Cilium's integration with Istio:
```

2023-06-07 23:49 UTC, zacharysarah commented on Documentation/network/servicemesh/istio.rst
> +which enables socket-based load-balancing inside a Pod.
Specific is better than general, no hyphens needed
```suggestion
Disruptions can happen when you enable Cilium's ``kubeProxyReplacement`` feature  (see :ref:`kubeproxy-free` docs), 
which enables socket based load balancing inside a Pod.
```

2023-06-07 23:49 UTC, zacharysarah commented on Documentation/network/servicemesh/istio.rst
> +which enables socket-based load-balancing inside a Pod.
Good use of "you" to address the user ✨

2023-06-07 23:49 UTC, zacharysarah commented on Documentation/network/servicemesh/istio.rst
> +You can confirm the resulting setting using the following command:
Use clear, plain language, specific is better than general
```suggestion
To ensure that Cilium does not interfere with Istio, Cilium must be deployed
with the ``--config bpf-lb-sock-hostns-only=true`` cilium CLI flag or with the ``socketLB.hostNamespaceOnly`` Helm value.
You can confirm the result with the following command:
```

2023-06-07 23:49 UTC, zacharysarah commented on Documentation/network/servicemesh/istio.rst
> +When you deploy Istio there are a few things you need to be aware of:
Comma nit, use clear, plain language
```suggestion
When you deploy Istio, be aware of:
```

2023-06-07 23:49 UTC, zacharysarah commented on Documentation/network/servicemesh/istio.rst
> +* The new experimental `Ambient mesh <https://istio.io/latest/blog/2022/introducing-ambient-mesh/>`_
cap nit
```suggestion
* The new experimental `ambient mesh <https://istio.io/latest/blog/2022/introducing-ambient-mesh/>`_ 
```

2023-06-07 23:49 UTC, zacharysarah commented on Documentation/network/servicemesh/istio.rst
> +  data plane is not currently supported as it interferes with Cilium data plane.
Omit "currently"
```suggestion
  data plane is not supported, as it interferes with the Cilium data plane.
```

2023-06-07 23:49 UTC, zacharysarah commented on Documentation/network/servicemesh/istio.rst
> +  you have to configure ``mtls.mode=DISABLE`` under Istio's ``PeerAuthentication``.
Edits for clarity, no Latin abbreviations
```suggestion
  To use an HTTP-based network policy (for example, :ref:`l7_policy`), 
  you must configure ``mtls.mode=DISABLE`` under Istio's ``PeerAuthentication``.
```

2023-06-07 23:49 UTC, zacharysarah commented on Documentation/network/servicemesh/istio.rst
> +  by the API server.
Well written. ✨

2023-06-07 23:49 UTC, zacharysarah commented on Documentation/network/servicemesh/istio.rst
> +Cilium network policies, including the caveat described in the :ref:`gsg_istio_cnp` section.
Use clear, plain language
```suggestion
The following guide demonstrates the interaction between Istio's ``mTLS`` mode and 
Cilium network policies, including the caveat described in the :ref:`gsg_istio_cnp` section.
```

2023-06-07 23:49 UTC, zacharysarah commented on Documentation/network/servicemesh/istio.rst
> +* Istio's ``istioctl`` installed on the local host
Edits for clarity
```suggestion
* Istio is already installed on the local Kubernetes cluster.
* Cilium is already installed with the ``socketLB.hostNamespaceOnly`` Helm value.
* Istio's ``istioctl`` is installed on the local host.
```

2023-06-07 23:49 UTC, zacharysarah commented on Documentation/network/servicemesh/istio.rst
> +By default, Istio works in the ``PERMISSIVE`` mode, allowing both Istio-managed and sidecar-less Pods
Edits for clarity
```suggestion
By default, Istio works in ``PERMISSIVE`` mode, allowing both Istio-managed and Pods without sidecars
```

2023-06-07 23:49 UTC, zacharysarah commented on Documentation/network/servicemesh/istio.rst
> +deployed above using the following commands:
Slightly more complex language in service of a clearer meaning
```suggestion
deployed in the preceding example by entering the following commands:
```

2023-06-07 23:49 UTC, zacharysarah commented on Documentation/network/servicemesh/istio.rst
> +in the ``blue`` namespace to only clients located in ``blue`` and ``red`` namespaces.
Edit for clarity
```suggestion
in the ``blue`` namespace to clients located only in ``blue`` and ``red`` namespaces.
```

2023-06-07 23:49 UTC, zacharysarah commented on Documentation/network/servicemesh/istio.rst
> +The following command applies the L7 network policy allowing communication only with the ``/ip`` URL path:
```suggestion
You can then decide to enhance the same network policy to perform additional HTTP-based checks. 
The following command applies the L7 network policy allowing communication only with the ``/ip`` URL path:
```

2023-06-07 23:49 UTC, zacharysarah commented on Documentation/network/servicemesh/istio.rst
> +At this point, all communication with the ``blue`` namespace is broken since Cilium proxy (HTTP) interferes with
nit
```suggestion
At this point, all communication with the ``blue`` namespace is broken since the Cilium proxy (HTTP) interferes with
```

2023-06-07 23:49 UTC, zacharysarah commented on Documentation/network/servicemesh/istio.rst
> +You need to apply this policy to the same namespace where you implement the HTTP-based network policy:
```suggestion
You must apply this policy to the same namespace where you implement the HTTP-based network policy:
```

2023-06-07 23:49 UTC, zacharysarah commented on Documentation/network/servicemesh/istio.rst
> +Re-run connectivity check to confirm that communication with the ``blue`` namespaces has been restored.
nit
```suggestion
Re-run a connectivity check to confirm that communication with the ``blue`` namespaces has been restored. 
```

2023-06-07 23:49 UTC, zacharysarah commented on Documentation/network/servicemesh/istio.rst
> +
Omit line
```suggestion
```

2023-06-07 23:49 UTC, zacharysarah commented on Documentation/operations/upgrade.rst
>  * API aware policy rules are enforced in user space proxies and are currently
Grammar nits, omit "currently", yes changes are in scope for the PR even though you didn't technically touch this line
```suggestion
* API-aware policy rules are enforced in user space proxies and are
```

2023-06-07 23:49 UTC, zacharysarah commented on Documentation/operations/upgrade.rst
> +  restart which will result in a connectivity outage and connection to be reset.
Use present tense, use active voice, clarity
```suggestion
  running as part of the Cilium pod. Upgrading Cilium causes the proxy to 
  restart, which results in a connectivity outage and causes the connection to reset.
```

2023-06-07 23:49 UTC, zacharysarah requested changes
@networkop Good start! 🌟 Some changes are required, otherwise LGTM from a docs perspective. Also:

![Screenshot 2023-06-07 at 4 19 41 PM](https://github.com/cilium/cilium/assets/3210446/64b074f8-7373-401d-bf80-25cd457acf55)

😻

2023-06-07 23:51 UTC, zacharysarah commented on Documentation/network/servicemesh/istio.rst
> +You can check that Cilium is enforcing the L7 network policy by accessing a different URL path, e.g. ``/deny``:
Late review requirement: no Latin abbreviations, clarity
```suggestion
You can verify that Cilium is enforcing the L7 network policy by accessing a different URL path, for example ``/deny``:
```

2023-06-08 07:34 UTC, networkop commented
thanks @zacharysarah , all your suggestions look good to me. Accepted and added.

2023-06-13 00:12 UTC, zacharysarah approved these changes
LGTM

2023-06-14 10:13 UTC, bimmlerd requested changes
heya, looks like you've added a merge commit- not entirely sure what GH does when we then rebase-to-merge the PR, but I think people usually rebase their PR on `main` instead of merging.

2023-06-14 10:46 UTC, networkop commented
@bimmlerd does this look right now?

2023-06-15 07:31 UTC, bimmlerd approved these changes
yep lgtm now; thanks!

2023-06-20 11:52 UTC, networkop commented
thanks @ti-mo . all done.

2023-06-20 19:50 UTC, ti-mo commented
@networkop Now the title of the commit is `This PR:`. :wink: I'd suggest `Documentation: retire Cilium-integrated Istio documentation`.

2023-06-21 06:05 UTC, networkop commented
yep, sorry, first PR in a while. fixed now

2023-06-21 06:57 UTC, ti-mo commented on examples/kubernetes-istio/authn.yaml
> +    mode: DISABLE
A few of these yamls are missing trailing newlines; make sure your editor adds them! I'll push a quick fixup and merge.

2023-06-21 07:18 UTC, ti-mo commented
main currently broken due to https://github.com/cilium/cilium/pull/26389. Docs build is green, merging.

2023-06-21 07:18 UTC, merged