bpf: always inline .bss in absence of a .data section
cilium/cilium pull request #25837
Opened 2023-06-01 19:11 UTC by ti-mo

Due to an early vars == nil check in inlineGlobalData, ELFs without a .data section would not get their .bss references rewritten. This would cause verifier errors on pre-5.x kernels like 'unrecognized bpf_ld_imm64 insn', since those don't support pseudo-register load insns yet.

Delay the check and add a regression test.

```release-note
bpf: always inline .bss in absence of a .data section
```

2023-06-01 19:12 UTC, ti-mo commented
/test

2023-06-02 08:34 UTC, rgo3 approved these changes

2023-06-02 10:02 UTC, qmonnet approved these changes
Thanks!

2023-06-02 11:07 UTC, gentoo-root requested changes

2023-06-02 11:07 UTC, gentoo-root commented on pkg/bpf/collection_test.go
> +		t.Errorf("unexpected Instruction OpCode: want: %s, got: %s", want, got)
OpCode -> Dst

2023-06-05 16:36 UTC, qmonnet requested changes
The change breaks some of the unit tests, it introduces patterns such as:

```
             	150: (18) r2 = 0x0
            	152: (69) r2 = *(u16 *)(r2 +0)
            	R2 invalid mem access 'inv'
```

Observable [here](https://github.com/cilium/cilium/actions/runs/5179475666/jobs/9332408508?pr=25909) for [this test PR](https://github.com/cilium/cilium/pull/25909/files). Unit tests were skipped on your PR because it doesn't touch `bpf/` files.

2023-06-05 17:59 UTC, dylandreimerink commented
It looks like this change breaks global data which we use in the tests. For example in `bpf/tests/xdp_nodeport_lb4_nat_lb.c` we have a variable `static __be16 nat_source_port;`. It is zero initialized so it ends up in `.bss`, this change inlines it which should not happen. Giving the variables an initial value does not work, relocation entry moves to `.data` and then it also gets inlined.

I guess the tests always worked because we were hitting the edge case this PR is removing of not having any global data in `.data` so our global `.bss` variables would behave as expected.

I don't really know how to fix this one since we use global data for mocking and to confirm that mocked functions were invoked. Ideally we would mark our oddball Cilium variables in such a way that we can selectively inline them and not dynamic global variables.

2023-06-06 15:49 UTC, closed without merging