Module health node manager
cilium/cilium pull request #25912
Opened 2023-06-05 18:44 UTC by tommyp1ckles

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note

```

2023-06-05 22:20 UTC, tommyp1ckles commented
/test

2023-06-06 06:35 UTC, tommyp1ckles commented
/test

2023-06-06 15:41 UTC, ti-mo requested changes
Right off the bat I have some concerns around the pervasive use of multierr and the introduction of `pkg/errs`, so I'm flagging this early before reviewing the whole thing.

If we're going to deviate from the canonical Go error handling style, I'd like this to be discussed in the open, e.g. through a CFP, and make it part of a larger plan to convert the whole codebase. We need strong reasons for doing so, and it's not a decision we should take lightly, as it makes code look very different due to how often a function like `errs.Into` appears. It directly affects the readablilty and familiarity of the code, so personally I'd stick to the idiomatic Go style.

I think errors.Join() could be used in the majority of cases here, which is not as big of a departure as multierr or a new package.

Another observation: I'm seeing a few occurrences of `acc` (what's in a name, btw?) declared and assigned to, but never returned. IMO the pattern of declaring a separate `acc` (instead of an `err` that is `errors.Join()`ed into) is a code smell, as it splinters the source of truth. `errors.Join` doesn't really have this problem; it supports nil values and the resulting error value will remain nil if the inputs are all nil.

2023-06-06 15:41 UTC, ti-mo commented on pkg/datapath/linux/ipsec/ipsec_linux.go
> +	var acc error
This variable is never assigned to?

2023-06-06 15:41 UTC, ti-mo commented on pkg/datapath/linux/ipsec/ipsec_linux.go
> +	"go.uber.org/multierr"
Go 1.20 introduced `errors.Join()`, maybe use that instead?

2023-06-06 15:41 UTC, ti-mo commented on pkg/errs/__debug_bin
What is this file for?

2023-06-06 16:27 UTC, chancez commented on pkg/hubble/peer/handler.go
> +	return "hubble-peers"
Nit: should this be singular? Package is singular, and we refer to it as the "hubble peer service" elsewhere.

2023-06-06 17:56 UTC, tommyp1ckles commented
@ti-mo 

> Right off the bat I have some concerns around the pervasive use of multierr and the introduction of pkg/errs, so I'm flagging this early before reviewing the whole thing.

Fair enough,  the motivation for using the multierr was that errors.Join wraps the error, whereas multierr acts more like a list of errors. But the decision to use the uber multierr I think was a bit hasty.

> Perhaps the changes to errors can be isolated from the modularity work? That will make the PR more manageable to review.

Can I propose that for the purposes of this change, I use errors.Join (or if necessary a list of errors) instead of the multierr.

I agree with bringing the error handling out into an open discussion, I've been compiling my thoughts on the matter which I was planning to make into a proposal - this can be part of it as well.

2023-06-06 21:32 UTC, chancez commented on pkg/hubble/peer/handler.go
> +	return "hubble-peers"
🤔 did this change?

2023-06-07 03:31 UTC, tommyp1ckles commented
/test

2023-06-07 05:16 UTC, tommyp1ckles commented
/test

2023-06-07 06:20 UTC, tommyp1ckles commented
/test

2023-06-07 06:25 UTC, tommyp1ckles commented
@ti-mo 

Updated to use errors.Join instead of multierr. If we need something with more functionality I'll start a discussion/proposal for that.

2023-06-07 06:28 UTC, tommyp1ckles commented
I also simplified the error status handling logic, dropping the `pkg/errs` changes altogether. . I think its better we start with a simplified implementation and iterate on that. Tracking backgroundSync seems sufficient as it happens every minute and will effectively retry updates on nodes in the manager.

I changed deleteNode to just log for now. I don't think the nodeDelete is quite ready to be incorporated into the status check. I'll follow up with a better approach to this in a separate PR.

2023-06-07 16:37 UTC, closed without merging

2023-06-07 16:43 UTC, tommyp1ckles commented
Tried to close and reopen to fix issues with seeing my force-push but now I can't reopen. PR is now over at [25994](https://github.com/cilium/cilium/pull/25994)