Docs: Add basic Gateway API troubleshooting
cilium/cilium pull request #25945
Opened 2023-06-06 15:39 UTC by meyskens

This adds a very short getting started to troubleshooting Gateway API part of the documentation

```release-note
Add a troubleshooting Gateway API part of the documentation
```

2023-06-13 14:58 UTC, youngnick approved these changes
This is a great overview, thanks!

2023-06-14 07:14 UTC, zacharysarah requested changes
@meyskens 👋🏻 It's clear that a lot of enthusiasm and care went into this documentation. ✨ That said, I'm returning this PR to you because it needs more work before it's in a reviewable state for documentation. 

Specifically, you must replace every instance of "this" with a clear reference to what specifically you're referring to. It's unreasonable to expect that a reviewer, let alone a user, will correctly infer what you mean by indirect reference.

2023-06-14 07:14 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/mistakes-warning.rst
> +   If you ran into an issue which was a mistake and not yet listed here we highly appreciate a PR to add yours to the list!
"We" is unclear, specify as "the Cilium project"; "mistake" is unclear; use present tense; use clear, plain language
```suggestion
   Gateway API is a recent addition to Kubernetes, and the Cilium project has not yet received much user feedback.
   If you encounter an issue that is not yet listed in this section, consider opening a PR to add yours to the list.
```

2023-06-14 07:14 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +This part of the documentation will guide you through the different mechanics of Gateway API and how to troubleshoot them.
Use clear, plain language
```suggestion
This page guides you through the different mechanics of Gateway API and how to troubleshoot them.

Be sure to follow the Generic and Setup Verification steps from the :ref:`Troubleshooting Ingress & Service Mesh page<troubleshooting_servicemesh>`.
```

2023-06-14 07:14 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +Checking the resources
```suggestion
Checking resources
```

2023-06-14 07:14 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +    This will get you an overview for all the Gateways in the cluster. There are a few important tings to check:
Specific is better than general, use present tense, typo
```suggestion
    The preceding command returns an overview of all the Gateways in the cluster. Check the following:
```

2023-06-14 07:14 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +      * If this is missing make sure that Gateway API is enabled in the Cilium configuration.
You are overusing "this" and it isn't clear what you mean each time. For example:
> If this is missing

If what is missing, specifically?
```suggestion
    * Is the Gateway programmed? 
    
        A programmed Gateway means that Cilium saw the gateway and prepared a configuration for it.
      
      * If this is missing make sure that Gateway API is enabled in the Cilium configuration.
```

2023-06-26 09:12 UTC, youngnick commented
ping @networkop to keep an eye on this one

2023-07-17 10:06 UTC, meyskens commented
Thanks a lot for the feedback! Improved it, hope this is better :)

2023-07-17 23:19 UTC, zacharysarah requested changes
@meyskens This is greatly improved! ✨ 

I have two questions (well, the same question in two places) about what component specifically is doing the "finding" in each troubleshooting case. PTAL and update accordingly. 

I also have a question about inspecting multiple fields with values of ``Accepted`` and ``ResourceRefs``.

The rest are formatting and clarity nits. Good work!

2023-07-17 23:19 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +      * If the ``Programmed true`` indicator is missing make sure that Gateway API is enabled in the Cilium configuration.
comma nit
```suggestion
      * If the ``Programmed true`` indicator is missing, make sure that Gateway API is enabled in the Cilium configuration.
```

2023-07-17 23:19 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +      * You can check the service with ``kubectl get service``, if there is no IP there either you might be missing a LoadBalancer implementation.
Formatting, clarity, present tense
```suggestion
    * Does the gateway have an address?
    
    You can check the service with ``kubectl get service``. 
    If the gateway has an address, it means that a LoadBalancer service is assigned to the gateway.
    If no IP appears, you might be missing a LoadBalancer implementation.
  

```

2023-07-17 23:19 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +        A programmed Gateway means that Cilium saw the gateway and prepared a configuration for it.
clarity
```suggestion
        A programmed Gateway means that Cilium prepared a configuration for it.
```

2023-07-17 23:19 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +    * In case the resource type is not found, make sure that the Gateway API CRDs are installed.
Formatting and clarity, present tense

Resource type for what? Be specific.
```suggestion
    * Is the class ``cilium``? 
    
    Cilium only program Gateways with the class ``cilium``.
    
    * If the resource type is not found, make sure that the Gateway API CRDs are installed.
```

2023-07-17 23:19 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +    If you need more info to further investigate the issue you can always use ``kubectl describe gateway``
Clarity
```suggestion
    You can use ``kubectl describe gateway`` to investigate issues more thoroughly.
```

2023-07-17 23:19 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +    Per Gateway or listener you can always see two status conditions:
Clear, plain language, present tense
```suggestion
    You can see the general status of the gateway as well as the status of the configured listeners.
    
    Listener status displays the number of routes successfully attached to the listener.
    
    You can see status conditions for both gateway and listener:
```

2023-07-17 23:19 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +    If any of these are set to false you can get more information by looking at the ``Message`` and ``Reason`` fields.
Clarity
```suggestion
      * ``Accepted``: the Gateway configuration was accepted.
      * ``Programmed``: the Gateway configuration was programmed into Envoy.
      * ``ResolvedRefs``: all referenced secrets were found and have permission for use.
  
    If any of these conditions are set to false, the ``Message`` and ``Reason`` fields give more information.
```

2023-07-17 23:19 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +  The way to do check the route status is very similar to the Gateway resource. While these instructions are written for HTTPRoute, they also apply to other route types.
Address the user as "you"
```suggestion
  When the Gateway is functional, you can check the routes to verify if they are configured correctly.
  The way to check route status is similar to checking the status of a gateway resource. 
  
  While these instructions are written for HTTPRoute, they also apply to other route types.
```

2023-07-17 23:19 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +  To get further information we can again use ``kubectl describe httproute <name>``
Address the user as "you", period nit
```suggestion
  To get more information, enter ``kubectl describe httproute <name>``.
```

2023-07-17 23:19 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +  There are two status conditions that are of interest to investigate:
Clarity, address the user as "you"

There are multiple fields with "Accepted" and "ResolvedRefs". Which ones should users pay attention to?
```suggestion
  Status lists the conditions that are relevant for the specific HTTPRoute.
  Conditions are listed by parent reference to the gateway. If you linked the route to multiple gateways, multiple entries appear.
  Notice the following conditions:
```

2023-07-17 23:19 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +  * ``ResolvedRefs``: This means that the referenced services were found and are valid references.
clarity
```suggestion
  * ``Accepted``: The HTTPRoute configuration was correct and accepted.
  * ``ResolvedRefs``: The referenced services were found and are valid references.
```

2023-07-17 23:19 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +* The backend service does not exist. You can check if the backend service was found under the ``conditions`` field when doing a ``kubectl describe httproute <name>``
formatting, period nit, active voice

What's doing the finding? Is it Kubernetes via kubectl? It's better to be as specific as possible.
```suggestion
* The backend service does not exist. 

    To verify whether the backend service was found, run ``kubectl describe httproute <name>`` and inspect the ``conditions`` field:
```

2023-07-17 23:19 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +* The Gateway specified under ``parentRefs`` does not exist. You check if the gateway was found under the ``conditions`` field when doing a ``kubectl describe httproute <name>``
Formatting nit

Similar to the previous review item ☝🏻: what's doing the finding of the gateway? Kubernetes via kubectl? It's better to be as specific as possible.
```suggestion
* The gateway specified under ``parentRefs`` does not exist.

    To verify whether the gateway was found, run ``kubectl describe httproute <name>`` and inspect the ``conditions`` field:
```

2023-07-17 23:19 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +The Cilium agent will use these to supply the built in Envoy or the Envoy DaemonSet with the configuration. Envoy is where traffic will be handled.
Clarity, present tense
```suggestion
A Cilium deployment has two parts that handle Gateway API resources: the Cilium agent and the Cilium operator.

The Cilium operator watches all Gateway API resources and verifies whether the resources are valid.
If resources are valid, the operator marks them as accepted. That starts the process of translation into Cilium Envoy Configuration resources.

The Cilium agent then picks up the Cilium Envoy Configuration resources.

The Cilium agent uses the resources to supply the configuration to the built in Envoy or the Envoy DaemonSet. Envoy handles traffic.
```

2023-07-19 19:36 UTC, zacharysarah requested changes
@meyskens Some final nits, then LGTM

2023-07-19 19:36 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/mistakes-warning.rst
> +   If you encounter an issue that is not yet listed in this section, consider opening a PR to add yours to the list.
Fiddly wording nit for the sake of clarity
```suggestion
   If you encounter an issue that is not yet listed in this section, consider opening a PR to add your issue to the list.
```

2023-07-19 19:36 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +
Remove new lines

2023-07-19 19:36 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +    Cilium only program Gateways with the class ``cilium``.
s/program/programs

2023-07-19 19:36 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +    Cilium only program Gateways with the class ``cilium``.
I've opened a separate issue to talk about capitalization of API objects, in #26904.

2023-07-19 19:36 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +
Remove newline
```suggestion
```

2023-07-19 19:36 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +  will tell you it is met in a boolean. Optionally, ``Message`` will give you more information about the condition.
Present tense, new line
```suggestion
  Conditions include ``Reason``, ``Type``, ``Status`` and ``Message``. ``Type`` indicates the condition type, and ``Status`` indicates with a boolean whether the condition type is met. Optionally, ``Message`` gives you more information about the condition.
  
```

2023-07-19 19:36 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +  If any of these are set to false you can get more information by looking at the ``Message`` and ``Reason`` fields.
comma nit
```suggestion
  If any of these are set to false, you can get more information by looking at the ``Message`` and ``Reason`` fields.
```

2023-07-19 19:36 UTC, zacharysarah commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +
Remove newline
```suggestion
```

2023-07-25 20:56 UTC, zacharysarah approved these changes
Thank you @meyskens! 🎉

2023-07-26 07:53 UTC, meyskens commented
/test

2023-07-28 04:27 UTC, merged