Temporarily disable part of the conformance-kind test
cilium/cilium pull request #25983
Opened 2023-06-07 11:56 UTC by aspsk

Temporarily disable the ipsec part of the conformance-kind test, as it is currently broken on new kernels (most probably, due to the commit [1] which greatly increases complexity).

A proper fix would be to split bpf_lxc.c:from-container into more tail calls, but this is work in progress.

  [1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=354e8f1970f821d4952458f77b1ab6c3eb24d530

Please ensure your pull request adheres to the following guidelines:

```release-note
Temporarily disable part of the conformance-kind test
```

2023-06-07 13:24 UTC, brlbil requested changes

2023-06-07 13:24 UTC, brlbil commented on .github/workflows/conformance-kind.yaml
> -      - name: Install Cilium with encryption
If the intention is to disable tests temporarily, then it makes more sense to add the line below
```
if: ${{ false }}
``` 
And please add a comment if there is an issue that tracks this, or anything relevant.

2023-06-07 13:24 UTC, brlbil commented on .github/workflows/tests-smoke.yaml
> +             --set hostServices.enabled=true \
Same here is it is a temporary change then a comment would be most helpful.

2023-06-07 13:25 UTC, aspsk commented
No more tests required, as `ConformanceKind1.19` and `Smoke test` passed.

2023-06-07 13:50 UTC, brlbil approved these changes
Thanks, 👍

2023-06-08 08:38 UTC, YutaroHayakawa approved these changes
🙏

2023-06-08 14:35 UTC, merged