Calling out support for Single-Region, Multi-Region, Multi-AZ for EKS
cilium/cilium pull request #26015
Opened 2023-06-08 07:51 UTC by amitmavgupta

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note

```

2023-06-12 22:12 UTC, zacharysarah requested changes
@amitmavgupta Some small formatting changes required, otherwise LGTM.

Be sure to add a release note.

2023-06-12 22:12 UTC, zacharysarah commented on Documentation/installation/requirements-eks.rst
> +   - Cilium can also be brought up in a Single-Region, Multi-Region, Multi-AZ environment for EKS.
Edits for clarity, use active voice, address the user as "you"
```suggestion
   - To chain Cilium on top of the AWS CNI, see :ref:`chaining_aws_cni`.

   - You can also bring up Cilium in a Single-Region, Multi-Region, or Multi-AZ environment for EKS.
```

2023-06-14 01:10 UTC, christarazi reviewed
Thanks for the PR.

Could you squash all of the commits into one commit?

2023-06-14 09:59 UTC, zacharysarah requested changes

2023-06-14 09:59 UTC, zacharysarah commented on Documentation/installation/requirements-eks.rst
> +   - You can also bring up Cilium in a Single-Region, Multi-Region, or Multi-AZ environment for EKS.
No hyphens needed.
```suggestion
   To chain Cilium on top of the AWS CNI, see :ref:`chaining_aws_cni`.

   You can also bring up Cilium in a Single-Region, Multi-Region, or Multi-AZ environment for EKS.
```

2023-06-16 19:38 UTC, zacharysarah approved these changes
LGTM for docs

2023-06-17 20:42 UTC, christarazi commented
I am seeing two commits that are meant to be the same, could you please squash the two commits into one?

2023-06-20 21:27 UTC, merged