docs: Move render target to main Makefile as 'render-docs'
cilium/cilium pull request #2606
Opened 2018-01-22 22:07 UTC by jrajahalme

Building docs-container failed if built after building cilium docker
image ('make docker-image') due to the .dockerignore file produced for
building the cilium image being accidentally reused for building
docs-container. Fix this by explicitly creating a .dockerignore file
as part of the docs-container actions.

Move the 'render' target from Documentation folder to the main
Makefile as 'render-docs' and make it depend on the 'docs-container'
target.

Reorganize Documentation/Dockerfile so that any repo changes outside
of Documentation/requirements.txt will use the cached build toolchain,
making repeated 'make render-docs' commands run faster.

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

2018-01-23 10:37 UTC, aalemayhu requested changes
LGTM, but the 'Building Documentation' section needs to be updated. Could you do it in this pull request? Thanks.

2018-01-23 12:46 UTC, raybejjani commented
I don't have a string opinion but we have followed the pattern of per-thing Makefiles that the top level one `make -C` into (well, daemon does this so I've generalised). I'm not sure if leaving the `render` target in the Documentation would work with these fixups (but then invoke it with `render-docs`), or if it's then more confusing and obtuse.

2018-01-23 22:24 UTC, jrajahalme commented
@raybejjani Looking into this I see that we have most (if not all) our 'docker' machinery in the main makefile. The 'render-docs' target is actually running the 'make html' in the Documents subdiretory (in the container). So maybe we can keep it like this?

2018-01-23 22:33 UTC, jrajahalme commented
Updated the docs to match, and verified the output with ```make render-docs``` :-)

2018-01-24 11:04 UTC, raybejjani commented
Oh, I see. Fair enough.

2018-01-24 13:56 UTC, aalemayhu approved these changes

2018-01-24 14:51 UTC, tgraf commented
test-me-please

2018-01-26 13:26 UTC, tgraf commented
test-me-please

2018-01-26 15:28 UTC, merged