test/k8s: make kafka tests more reliable
cilium/cilium pull request #26121
Opened 2023-06-12 13:29 UTC by aanm

Waiting until the Kafka command succeeds will prevent any flakiness in the tests.

2023-06-12 15:43 UTC, tklauser approved these changes

2023-06-13 07:31 UTC, jrajahalme requested changes

2023-06-13 07:31 UTC, jrajahalme commented on test/k8s/kafka_policies.go
> +					errBody = kubectl.ExecKafkaPodCmd(helpers.DefaultNamespace, pod, prodHqAnnounce)
Should use `arg` in exec instead of `prodHqAnnounce`!

2023-06-13 09:07 UTC, aanm commented
/test

2023-06-13 10:31 UTC, aanm commented
/ci-ginkgo

2023-06-13 10:35 UTC, aanm commented
/ci-ginkgo

2023-06-13 11:04 UTC, aanm commented
/ci-ginkgo

2023-06-13 12:04 UTC, jrajahalme approved these changes

2023-06-13 13:50 UTC, merged