Removing ui
cilium/cilium pull request #263
Opened 2017-01-23 19:10 UTC by aanm

2017-01-23 19:11 UTC, aanm reviewed
The places where I wrote "here" are the ones where the event is triggered to show up in the web UI.

2017-01-23 19:11 UTC, aanm commented on daemon/daemon/labels.go
> -	d.AddOrUpdateUINode(secCtxLbls.ID.Uint32(), secCtxLbls.Labels.ToSlice(), secCtxLbls.RefCount())
@tgraf here

2017-01-23 19:11 UTC, aanm commented on daemon/daemon/labels.go
> -		d.DeleteUINode(dbSecCtxLbls.ID.Uint32())
@tgraf here

2017-01-23 19:11 UTC, aanm commented on daemon/daemon/labels.go
> -		d.AddOrUpdateUINode(dbSecCtxLbls.ID.Uint32(), dbSecCtxLbls.Labels.ToSlice(), dbSecCtxLbls.RefCount())
@tgraf here

2017-01-23 19:11 UTC, aanm commented on daemon/daemon/state.go
> -				d.AddOrUpdateUINode(ep.SecLabel.ID.Uint32(), ep.SecLabel.Labels.ToSlice(), ep.SecLabel.RefCount())
@tgraf here

2017-01-25 01:39 UTC, tgraf commented
> The places where I wrote "here" are the ones where the event is triggered to show up in the web UI.

We should define an interface{} which contains hooks that can later be implemented to trigger sending events to an aggerator. Initially the default implementation of the interface{} can be a no-operation.

2017-01-25 01:41 UTC, tgraf requested changes

2017-01-25 01:41 UTC, tgraf commented on plugins/cilium-docker/driver/driver.go
> +	for tries := 0; tries < 20; tries++ {
Just bump this to 5 minutes or indefinitely.

2017-01-25 01:50 UTC, aanm commented
>We should define an interface{} which contains hooks that can later be implemented to trigger sending events to an aggerator. Initially the default implementation of the interface{} can be a no-operation.

What about replacing the `here` lines with a go channel (`d.UIEvent<-Event{Type: ADD, Obj: Interface{}}`)?

2017-01-25 01:55 UTC, tgraf commented
> What about replacing the here lines with a go channel (d.UIEvent<-Event{Type: ADD, Obj: Interface{}})?

Let's not make it UI specific and call it event queue or something. This will be useful for other things besides a UI.

2017-01-25 16:28 UTC, aanm commented
>Let's not make it UI specific and call it event queue or something. This will be useful for other things besides a UI.

Check the last commit.

2017-01-25 18:06 UTC, tgraf approved these changes

2017-01-25 18:06 UTC, tgraf commented on daemon/daemon/daemon.go
> +		events:            make(chan events.Event, 10),
Is 10 enough of a buffer? Does it make sense to bump it to 512 as things like policy changes may trigger a lot of events and we would need to start waiting for the readers.

2017-01-25 18:06 UTC, tgraf commented on daemon/daemon/events.go
> +// Copyright 2016 Authors of Cilium
We can start adding -2017 for new headers.

2017-01-25 18:13 UTC, aanm commented on daemon/daemon/daemon.go
> +		events:            make(chan events.Event, 10),
I think the best option is to trigger a new go routine for each reader.
```golang
newEvent := <-...
for listener := range listeners {
   go func() {
        select {
         case listener <- newEvent:
         case <-time.After(1 * time.Second):
               log.Debug("listener foo didn't receive new event")
       }
}
```

2017-01-25 18:19 UTC, tgraf commented on daemon/daemon/daemon.go
> +		events:            make(chan events.Event, 10),
I'm not worried about listeners yet, the `listenForCiliumEvents()` itself needs to be scheduled to run to drain the 10 events before the main daemon continues running.

2017-01-25 18:23 UTC, aanm commented on daemon/daemon/daemon.go
> +		events:            make(chan events.Event, 10),
Ah I see, ok I'll change it 512.

2017-01-26 00:33 UTC, merged