docs: Update kvstore documentation with potential circular dependency.
cilium/cilium pull request #26353
Opened 2023-06-19 13:23 UTC by marseel

Current documentation does not inform about potential circular dependency between Cilium and kvstore.
This commit explains how this dependency can happen and also gives two potential ways of resolving it.

Also, bump Etcd version requirement to 3.4.0+, as previous minor releases are no longer supported.

Fixes https://github.com/cilium/cilium/issues/25632

2023-06-19 15:13 UTC, qmonnet requested changes
Of the two methods to address the circular dependency, is there one that should be preferred? Do they have particular advantages/drawbacks?

(The underlying question is: if I'm a user facing this, how do I know which of the two methods I should follow?)

2023-06-19 15:13 UTC, qmonnet commented on Documentation/installation/k8s-install-external-etcd.rst
> +================================
```suggestion
Kvstore and Cilium dependency
=============================

```

2023-06-19 15:13 UTC, qmonnet commented on Documentation/installation/k8s-install-external-etcd.rst
> + * Deploy kvstore outside of cluster or on separately managed cluster
```suggestion
 * Deploy kvstore outside of cluster or on separately managed cluster.
```

2023-06-20 08:12 UTC, marseel commented
I don't think there is any significant advantage/disadvantage between these two options.

2023-06-20 16:37 UTC, qmonnet approved these changes
OK, so let's users sort it out by themselves I guess :shrug: 

Looks all good

2023-06-20 19:48 UTC, merged