hubble: Optimize namespace tracking
cilium/cilium pull request #26547
Opened 2023-06-28 23:09 UTC by glibsm

Avoiding the use of varargs saves some allocations

Before
```
Benchmark_TrackNamespaces-12    	 5122684	       231.8 ns/op	     192 B/op	       6 allocs/op
```

After
```
Benchmark_TrackNamespaces-12    	 6114062	       187.9 ns/op	     168 B/op	       4 allocs/op
```

2023-06-30 07:19 UTC, kaworu requested changes
Thanks for the patch @glibsm!

`pkg/hubble/relay/observer/server.go` needs to be adapted accordingly.

Note that after the patch, adding a flow's src/dst namespaces is no longer "atomic" from the `namespaceManager` point of view but I don't think that's an issue.

2023-07-05 16:27 UTC, chancez commented
We should back port this to 1.14 since this functionality is new in 1.14 and that memory increase could be viewed as a performance regression.

2023-07-10 17:42 UTC, chancez approved these changes

2023-07-11 08:33 UTC, kaworu approved these changes

2023-07-11 08:33 UTC, kaworu commented
/test

2023-07-11 11:28 UTC, merged