daemon:fixed an error that the CNI configuration file could not be read
cilium/cilium pull request #26624
Opened 2023-07-04 12:10 UTC by bumblebeeK

Signed-off-by: bumblebeek <gleemanx@126.com>

Fixes: #26622
We hope fix this bug , which may cause some problems in IPAMAWS、IPAMAlibaba mode.

2023-07-04 12:11 UTC, squeed requested changes
Rather than adding a new function, can we just fix GetMTU to do the right thing?

2023-07-04 12:12 UTC, squeed commented on daemon/cmd/cni/config.go
>  	}
there is a bug here in the existing codebase; this should return 0 here as well.

2023-07-04 12:13 UTC, bumblebeeK commented
> Rather than adding a new function, can we just fix GetMTU to do the right thing?

okay

2023-07-04 12:14 UTC, bumblebeeK commented
> Rather than adding a new function, can we just fix GetMTU to do the right thing?

Do we need to change the GetMTU function signature

2023-07-04 12:18 UTC, squeed commented
> Do we need to change the GetMTU function signature ?

I don't think so. But I'm afraid I don't currently understand the bug this is trying to fix.

2023-07-04 12:37 UTC, bumblebeeK commented
> don't

https://github.com/cilium/cilium/blob/7726560faf2193a9a7bf06560aec830dcf49414a/daemon/cmd/daemon.go#L519
If not fixed, *netconf is nil in this function

2023-07-07 15:05 UTC, thorn3r commented
thanks for the PR, @bumblebeeK! I'm in the same position, I think the bug @squeed pointed out is worth fixing, but I'm not seeing how this fixes the linked issue https://github.com/cilium/cilium/issues/26622

2023-07-10 07:07 UTC, bumblebeeK commented
> 

Ok ,thx for your reply, i will do it!

2023-07-24 11:47 UTC, closed without merging