Jenkins: Fix issues with new slaves
cilium/cilium pull request #2663
Opened 2018-01-28 11:07 UTC by eloycoto

With Vagrant version 2.0.1 the `vagrant destroy -f` command exits with 1
if no servers are destroyed. Builds with the new slaves failed and it
never completes

Related to #2438 

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

**Summary of changes**:

Fixes: #issue-number

```release-note

```

**How to test (optional)**:
e.g. Run `make tests`, `make runtime-tests` and/or some more specific way to
exercise the new behavior(s).
Note: [The runtime testsuite will modify the host it runs on.](http://cilium.readthedocs.io/en/latest/contributing/#testsuite)

2018-01-28 12:00 UTC, eloycoto commented
test-me-please

2018-01-29 01:54 UTC, ianvernon approved these changes

2018-01-29 01:56 UTC, ianvernon requested changes
Looks fine, but won't the Jenkinsfile `post` section need to be updated as well? This might be overkill, but I always have erred on the side of caution to ensure that VMs are cleaned up.

2018-01-29 09:28 UTC, eloycoto commented
test-me-please

2018-01-29 10:26 UTC, eloycoto commented
test-me-please

2018-01-29 18:24 UTC, ianvernon approved these changes

2018-01-30 12:14 UTC, merged