policy: Move Listener and ParserType from L4Filter to PerSelectorPolicy
cilium/cilium pull request #26644
Opened 2023-07-05 12:49 UTC by jrajahalme

Allow different selectors use different Envoy Listeners and hence L7 parsers. This relaxes the policy import (L4Filter merge) logic by only failing out if there is an L7 parser or Listener conflict on the same cached selector.

This change is needed to allow different Envoy Listeners to be applied on traffic on the same port, depending on the destination (for an egress policy). Consequently, we must handle conflicting proxy ports on the same MapState key, originating from different selectors selecting the same remote identity. We do this by favoring the selector with most specific label match, like we already do for deny policies.

```release-note
Cilium Network policy now accepts different Envoy listeners on the same port on different policy selectors.
```

2023-07-10 20:38 UTC, jrajahalme commented
/test

2023-07-11 06:51 UTC, jrajahalme commented
/test

2023-07-11 09:08 UTC, jibi commented
/test-backport-1.13

2023-07-12 03:14 UTC, nathanjsweet requested changes
Overall looks good!

2023-07-12 03:14 UTC, nathanjsweet commented on pkg/envoy/ciliumenvoyconfig.go
> +			injectCiliumFilters := listener.GetAddress() == nil && !internalListener
Isn't the extra boolean check moot? We already know `internalListener` must be false because `listener.GetAddress()` is false.
```suggestion
			injectCiliumFilters := listener.GetAddress() == nil
```

2023-07-12 03:14 UTC, nathanjsweet commented on pkg/envoy/ciliumenvoyconfig.go
> +		if listener.GetAddress() == nil && !internalListener {
same comment as above.

2023-08-25 19:02 UTC, joestringer commented
Converted to draft while you address the feedback and rebase. Given the sheer size of the PR, it looks like this will need some close coordination with the reviewers to provide confidence around the risk/reward tradeoff for the v1.13 backport here.

2023-09-06 08:21 UTC, mhofstetter commented on pkg/policy/rule.go
> +				ctx.PolicyTrace("   Merge conflict: mismatching CiliumEnvoyConfig listeners %v/%v\n", newL7Rules.Listener, l7Rules.Listener)
nit: might be worth to put a space in between the two listener names. the names themselves can already contain slashes - which makes it quite hard to read. -> `%v / %v`

same for the error below, and maybe also the l7parser merge conflict trace on line 146

2023-10-22 01:46 UTC, closed without merging