[highscale] fqdn/policy: expand service frontends IPs to backend IPs
cilium/cilium pull request #26643
Opened 2023-07-05 12:32 UTC by squeed

For more details, see the individual commit messages.

As part of enabling egress policy for high-scale cache, we would like to enable toFQDN policy to reference kubernetes service IPs. However, this presently does not work because policy enforcement always sees the "real" destination IP, not the virtual / service IP.

So, we need to configure the policy engine to expand frontend IPs to their backend IPs without changing the DNS response. Additionally, we need to recompute FQDN policy whenever a service's backend IPs have changed.

```release-note
TODO
```

2023-07-06 08:42 UTC, squeed commented on pkg/fqdn/cache.go
> +			if frontendsWithChanges.Has(ip) {
This loop looks kind of expensive, and we need to call it on every single service update. We may wish to consider another tracking map instead.

2023-07-10 02:14 UTC, christarazi requested changes
Architecturally, I have a worry that side-loading the DNS cache with updates that are fed by the services/endpoints watcher may not scale, but we don't have any official way to measure the impact, yet at least. I am wondering whether it's worth investing in making quite drastic changes to the `toFQDNs` logic when we know it's a policy model that scales with number of unique IPs, rather than identities. Moving forward a more ideal model would be to use `toServices` with an ability to leverage service labels for use in identities so that we can switch back to a model that scales with number of unique identities (services), rather than IPs. This is how the current label-based policy model works in Cilium today. Let's table this for now though until we discuss this further.

With that said, I have a couple of concerns with the implementation as it is today. I've mostly focused on the hotpath-affecting code changes.

2023-07-10 02:14 UTC, christarazi commented on pkg/fqdn/cache.go
> +func (c *DNSCache) setVirtualIP(frontend netip.Addr, backends []netip.Addr, mergeExisting bool) bool {
Let's document that it must be called with the DNSCache mutex locked

2023-07-10 02:14 UTC, christarazi commented on pkg/k8s/watchers/watcher.go
> +					if err := waitTimeout(wg, option.Config.FQDNProxyResponseMaxDelay); err != nil {
This could delay responding to updates for services/endpoints up to `FQDNProxyResponseMaxDelay` amount of time. Given https://github.com/cilium/cilium/pull/26643/files#r1254127031, any unoptimized code in this hotpath will definitely risk hitting more timeouts of `FQDNProxyResponseMaxDelay`  (consequence is transient policy drops). This is especially concerning if there is heavy churn with services/endpoints because it requires the DNSCache lock to be taken which is in the hotpath of the DNS proxy handling DNS requests. Meaning it could also delay the DNS proxy as well. One slight mitigating circumstance is that the DNSCache object is per endpoint, which is better than a global DNSCache because that would mean global lock contention. However, if an endpoint has many connections to many different services that all experience churn, it would still be heavy lock contention on that endpoint's specific DNSCache.

2023-07-10 02:14 UTC, christarazi commented on pkg/fqdn/cache.go
> +	backendsToVips map[netip.Addr][]netip.Addr
When the TTL expires and GC runs, don't we also need to clean these maps up? I only see these maps touched from the `UpdateLBIPMapping` code path.

2023-07-10 02:14 UTC, christarazi commented on pkg/k8s/watchers/watcher.go
> +					if err := waitTimeout(wg, option.Config.FQDNProxyResponseMaxDelay); err != nil {
One idea to resolve this would be for the DNS name manager to have a queue where the code here enqueues an event to be processed without blocking, and a separate goroutine of the DNS name manager will handle processing the event.

2023-07-12 11:38 UTC, squeed commented on pkg/k8s/watchers/watcher.go
> +					if err := waitTimeout(wg, option.Config.FQDNProxyResponseMaxDelay); err != nil {
That would work but lead to policy drops between applying the changes to the load balancers and pushing out the policy map updates.

2023-07-20 13:28 UTC, squeed commented on pkg/fqdn/cache.go
> +	backendsToVips map[netip.Addr][]netip.Addr
Good question. No, these maps are just for service ip -> backend IPs (and the reverse); they're populated regardless of whether or not names reference them.

2023-09-03 01:45 UTC, closed without merging