Add 5 second timeout to Auth dialer
cilium/cilium pull request #26650
Opened 2023-07-05 15:18 UTC by meyskens

The TCP level dialer had no timeout before. This could cause some issues. This change adds a configurable timeout of default 5 seconds to the TCP dailer.

```release-note
Add a 5 second timeout to the Mutual Auth TCP handshake
```

2023-07-06 03:39 UTC, mhofstetter requested changes
thanks for this enhancement! :hourglass: :tada: 

some requested changes inline.

2023-07-06 03:39 UTC, mhofstetter commented on pkg/auth/mutual_authhandler.go
> +	mutualAuthConnectTimeout time.Duration `mapstructure:"mesh-auth-mutual-Connect-timeout"`
typo in `mesh-auth-mutual-Connect-timeout`: need to change it to a lowercase `c`

```
2 error(s) decoding:\n\n* '' has invalid keys: mesh-auth-mutual-connect-timeout\n* '' has unset fields: mesh-auth-mutual-Connect-timeout.\nHint: field 'FooBar' matches flag 'foo-bar', or use tag `mapstructure:\"flag-name\"` to match field with flag" subsys=daemon
```

2023-07-06 03:39 UTC, mhofstetter commented on pkg/auth/mutual_authhandler.go
> +	mutualAuthConnectTimeout time.Duration `mapstructure:"mesh-auth-mutual-Connect-timeout"`
And we should capitalize the field itself `mutualAuthConnectTimeout` -> `MutualAuthConnectTimeout`

2023-07-06 03:39 UTC, mhofstetter commented on pkg/auth/mutual_authhandler.go
> +	mutualAuthConnectTimeout time.Duration `mapstructure:"mesh-auth-mutual-Connect-timeout"`
shouldn't we expose this config property via Helm too?

2023-07-12 07:23 UTC, mhofstetter requested changes
helm values needs to be reflected in the docs -> `make -C Documentation update-helm-values` :rocket:

2023-07-12 07:23 UTC, mhofstetter commented on install/kubernetes/cilium/templates/cilium-configmap.yaml
> +  mesh-auth-mutual-connect-timeout: {{ .Values.authentication.mutual.connectTimeout | quote }}
Check integration test i failing due to non-updated docs.

```
index 8770ad82..a86974e0 100644
--- a/Documentation/helm-values.rst
+++ b/Documentation/helm-values.rst
@@ -48,6 +48,10 @@
      - Interval for garbage collection of auth map entries.
      - string
      - ``"5m0s"``
+   * - authentication.mutual.connectTimeout
+     - Timeout for connecting to the remote node TCP socket
+     - string
+     - ``"5s"``
    * - authentication.mutual.port
      - Port on the agent where mutual authentication handshakes between agents will be performed
      - int
make[1]: *** [Makefile:75: check] Error 1
HINT: to fix this, run 'make -C Documentation update-helm-values'
```

2023-07-12 13:49 UTC, kaworu approved these changes
Helm changes LGTM.

2023-07-12 13:49 UTC, kaworu commented on install/kubernetes/cilium/templates/cilium-configmap.yaml
> +  mesh-auth-mutual-connect-timeout: {{ .Values.authentication.mutual.connectTimeout | quote }}
nit: Consider using [`validateDuration`](https://github.com/cilium/cilium/blob/e8618e952098c9c05f2249afe80835d7d37291f7/install/kubernetes/cilium/templates/_helpers.tpl#L146-L156) For Golang duration formatted Helm values, e.g.

https://github.com/cilium/cilium/blob/e8618e952098c9c05f2249afe80835d7d37291f7/install/kubernetes/cilium/templates/cilium-configmap.yaml#L312-L316

```suggestion
  mesh-auth-mutual-connect-timeout: {{ include "validateDuration" .Values.authentication.mutual.connectTimeout | quote }}
```

2023-07-13 12:52 UTC, mhofstetter approved these changes

2023-07-13 12:52 UTC, mhofstetter commented
/test

2023-07-13 14:50 UTC, meyskens commented
/test

2023-07-17 07:03 UTC, mhofstetter commented
@meyskens looks like we need another round of `make -C Documentation update-helm-values`

2023-07-17 08:04 UTC, meyskens commented
Seems the merge un-did the cmdref this time. updating...

2023-07-17 09:31 UTC, meyskens commented
/test

2023-07-17 12:45 UTC, joamaki approved these changes

2023-07-18 16:09 UTC, merged