bpf: Suppress Key Mismatch Log for Certain Maps
cilium/cilium pull request #26656
Opened 2023-07-06 02:42 UTC by nathanjsweet

Some bpf maps do not affect any data loss or
require any action by operators when there is a
key size mismatch between bpf map versions.
When that is the case the warning log message
should be suppressed so as not to alarm
operators.

Fixes: #25224

2023-07-06 11:59 UTC, dylandreimerink requested changes

2023-07-06 11:59 UTC, dylandreimerink commented on pkg/bpf/bpf_linux.go
> +		scopedLog.Error("Could not get mapinfo for map %+v", *m)
The linter points it out already, but just to be sure, this should be an `Errorf` not an `Error` given the format option

2023-07-06 11:59 UTC, dylandreimerink commented on pkg/bpf/bpf_linux.go
> +var keySizeExceptions = []string{"cilium_policy"}
Could you add a comment to explain when maps are exempt from the key size check? so it is clear why this code exists.

2023-07-06 15:59 UTC, dylandreimerink approved these changes
:rocket:

2023-07-06 16:06 UTC, nathanjsweet commented
/test

2023-07-06 19:08 UTC, joestringer commented
I know that @ti-mo and @jrajahalme had discussed approaches to solve this in the past, so I'll CC them for their input on the long term maintainability approach here.

2023-07-10 08:47 UTC, ti-mo commented
This is a band-aid, and objCheck is going to be removed soon. Maps that tolerate data loss (typically maps that are write-only from the agent side like ipcache and policy) should use `Map.Recreate()` instead of `Map.OpenOrCreate()` to explicitly indicate this fact. Maybe this PR could take that approach instead?

I have patches floating around that do this for most maps, along with changing `OpenOrCreate()` to no longer implicitly recreate maps, but haven't had the time to polish them and put them up for review, ETA would be early August. This is part of the ongoing bpf.Map work.

2023-07-12 19:35 UTC, nathanjsweet commented
A couple of things:
1. https://github.com/cilium/cilium/issues/26793 is filed to track managing this problem more effectively/comprehensively.
2. For some reason, CI ran Jenkins jobs for this PR, even though they no longer exist. The Jenkins jobs are the only failures for this CI. Marking ready-to-merge.

2023-07-12 20:14 UTC, nathanjsweet commented
Closing. See [this issue comment](https://github.com/cilium/cilium/issues/25224#issuecomment-1633136799) for why.

2023-07-12 20:14 UTC, closed without merging