docs: update clustermesh troubleshooting guide
cilium/cilium pull request #26798
Opened 2023-07-13 07:24 UTC by giorio94

This PR modifies the clustermesh troubleshooting guide to update the outdated information, in particular about the configuration name and TLS certificates function.

Fixes: #issue-number

```release-note

```

2023-10-10 07:50 UTC, giorio94 commented
/test

2023-10-12 16:53 UTC, thorn3r approved these changes

2023-10-12 17:00 UTC, learnitall requested changes
Thank you for doing this. I have a couple of suggestions and then LGTM.

2023-10-12 17:00 UTC, learnitall commented on Documentation/operations/troubleshooting_clustermesh.rst
> +      or the ``cluster-name`` ConfigMap option).
I think we can remove the parentheticals here.

```suggestion
      the name of the remote cluster as provided by the ``--cluster-name`` argument
      or the ``cluster-name`` ConfigMap option.
```

2023-10-12 17:00 UTC, learnitall commented on Documentation/operations/troubleshooting_clustermesh.rst
> +    If any of above secrets is not configured correctly, there will be potential error message like below::
The words 'above' and 'below' give translators some trouble, can we change to 'prior' and 'following'?
```suggestion
    If any of the prior secrets is not configured correctly, there will be a potential error message like the following::
```

2023-10-12 17:00 UTC, learnitall commented on Documentation/operations/troubleshooting_clustermesh.rst
> +      Additional files may represent the certificate and private key themselves.
This sentence is a little unclear, I'm not sure what it means. I tried to add some context:

```suggestion
      Additional files may be included in the secret to provide the certificate and private key themselves.
```

2023-10-12 17:00 UTC, learnitall commented on Documentation/operations/troubleshooting_clustermesh.rst
> +      to list the files therein present.
I think `present` and `therein` are redundant. Can you pick one and remove the other?

2023-10-13 06:54 UTC, giorio94 commented
/test

2023-10-13 06:54 UTC, giorio94 commented
> Thank you for doing this. I have a couple of suggestions and then LGTM.

Suggestions applied, thanks!

2023-10-13 21:20 UTC, learnitall approved these changes
Thanks!

2023-10-16 10:32 UTC, merged