CiliumNetworkPolicy validation
cilium/cilium pull request #26794
Opened 2023-07-12 23:17 UTC by romanspb80

This patch adds validation for CiliumNetworkPolicy with CEL

Fixes: #23152

2023-07-17 12:29 UTC, kaworu requested changes
Thanks for the PR @romanspb80, please see my comment on `value.yaml`. Also pulling @cilium/sig-policy for the review.

2023-07-17 12:29 UTC, kaworu commented on install/kubernetes/cilium/values.yaml
I don't think removing `k8sClientRateLimit` was intended, also please report your changes to `install/kubernetes/cilium/values.yaml.tmpl` and then run:

```
make -C install/kubernetes cilium/values.yaml
```

to update this file.

2023-07-17 13:24 UTC, joamaki commented
Adding @christarazi and @giorio94 as extra reviewers due to https://github.com/cilium/cilium/issues/23152

2023-07-17 13:25 UTC, joamaki commented on install/kubernetes/cilium/values.yaml
`k8sClientRateLimit` was just introduced, so rebase and then regenerate `values.yaml`.

2023-07-20 07:56 UTC, giorio94 commented
Adding @gandro as extra reviewer, who has already reviewed an [earlier iteration of this PR](https://github.com/cilium/cilium/pull/26470). 
@romanspb80 Please do not open separate PRs for the same patch as it becomes difficult to follow the comments history.

2023-07-20 08:23 UTC, gandro approved these changes
In terms of Helm structure, this looks good to me.

I'll defer the review of the actual validation logic to other subteams though.

2023-07-20 08:24 UTC, gandro commented
@romanspb80 Could you rebase on main again? CI is failing due to #26883 not being part of you branch. Thanks.

2023-07-21 13:20 UTC, giorio94 requested changes
I made a try applying this validation policy, but it appears to reject even empty policies:

```
cat <<EOF | kubectl apply -f - 
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: test
spec:
  endpointSelector: {}
EOF
```

Returns: 

```
The ciliumnetworkpolicies "test" is invalid: : ValidatingAdmissionPolicy 'cilium-validate-network-policies' with binding 'cilium-validate-network-policies-binding' denied request: L7 rules can only apply to TCP (not UDP) except for egress DNS rules
```

My understanding is that an operation is rejected if the expression evaluates to false, and not when it evaluates to true.

I wonder how we could have tests to ensure that this (and other policies which we may introduce in the future) actually work as expected, and to prevent possible future regressions. 

I'd be also personally hesitant in saying that this PR fixes https://github.com/cilium/cilium/issues/23152. While being a step forward for sure, I feel that there may be other combinations of settings which would benefit from a validation, as invalid.

2023-07-21 13:20 UTC, giorio94 commented on install/kubernetes/cilium/templates/cilium-agent/validatingadmissionpolicy.yaml
I'd suggest to move these two files to a dedicated directory, renaming the files to reflect the name of the policy.

2023-07-21 13:20 UTC, giorio94 commented on install/kubernetes/cilium/templates/cilium-agent/validatingadmissionpolicybinding.yaml
When trying to apply this policy, an error is returned:

```
The ValidatingAdmissionPolicyBinding "cilium-validate-network-policies-binding" is invalid: spec.validationActions: Required value: at least one validation action is required
```

2023-07-21 15:54 UTC, aditighag requested changes
Very cool! 

>This patch adds validation for CiliumNetworkPolicy with CEL

Please spell out CEL in the description, and add an official k8s documentation link. It'll be great add a reference link to the CNP spec where the rules are specified.

Can you also add an example in the PR description showing how the validation fails an incorrect CNP?

2023-07-21 15:54 UTC, aditighag commented on install/kubernetes/cilium/templates/cilium-agent/validatingadmissionpolicy.yaml
> +                         has(x.rules.http) || has(x.rules.kafka)
Can you add a reference link to the CNP spec here so that readers know where these rules come from?

2023-07-21 15:54 UTC, aditighag commented on install/kubernetes/cilium/templates/cilium-agent/validatingadmissionpolicy.yaml
> +  name: "cilium-validate-network-policies"
```suggestion
  name: "validate-cilium-network-policies"
```

2023-07-24 19:04 UTC, nathanjsweet requested changes
Your expression is not structured to cover both `egress` and `ingress` if they are both present (and if they are both present and one of them is invalid, then this validation logic will miss the invalid object), the `toPorts` validation incorrectly assumes that `toPorts` must be present but there are other membership possibilities to consider, and it doesn't validate `endpointSelectors`.

The structure of the expression should look something like this:
```cel
has(object.spec.endpointSelectors) &&
// validate endpointSelectors
(... ) &&
 // validate ingress object
(!has(object.spec.ingress) ||
    ...
) &&
// validate egress object
(!has(object.spec.egress ||
    ...
)
```

I'm converting this PR to a draft as it needs more work.

Feel free to reach out on slack for more detailed feedback.

2023-07-24 19:04 UTC, nathanjsweet commented on install/kubernetes/cilium/templates/cilium-agent/validatingadmissionpolicy.yaml
> +          && object.spec.ingress.exists(x, has(x.toPorts)
Members of `ingress` do not need `toPorts`. My proposed change checks if `toPorts` does not exist and then proceeds to validate `toPorts` if it does.
```suggestion
          && object.spec.ingress.exists(x, !has(x.toPorts)
```

2023-07-24 19:04 UTC, nathanjsweet commented on install/kubernetes/cilium/templates/cilium-agent/validatingadmissionpolicy.yaml
> +            && x.toPorts.exists(x,
With the above changes this converts to an "or".
```suggestion
            x.toPorts.exists(x,
```

2023-09-07 01:44 UTC, closed without merging