Refactor hubble redact settings schema
cilium/cilium pull request #26989
Opened 2023-07-21 14:13 UTC by ChrsMark

TBA

cc: @ioandr

2023-07-24 12:58 UTC, pippolo84 requested changes
Left a comment about a couple of typos. Apart from that, agent related changes LGTM.
CI Failures are legit, you need to run `make -C Documentation/ update-cmdref` to regenerate the docs.
Thanks!

2023-07-24 12:58 UTC, pippolo84 commented on pkg/defaults/defaults.go
> +	// HubbleReact controls is sensitive information will be redacted from L7 flows
Couple of typos: `HubbleReact` -> `HubbleRedact` and `is` -> `if`

2023-07-24 15:24 UTC, chancez commented on daemon/cmd/daemon_main.go
> +	flags.Bool(option.HubbleRedact, defaults.HubbleRedact, "Hubble redact sensitive information from flows")
Do we even need a separate enabled option? The other options seem like they would be sufficient.

2023-07-24 15:27 UTC, chancez requested changes
Looks like the tests need updating. One question about if we need all 3 options now or if we could just have the 2 new ones.

2023-07-24 15:50 UTC, ChrsMark commented on daemon/cmd/daemon_main.go
> +	flags.Bool(option.HubbleRedact, defaults.HubbleRedact, "Hubble redact sensitive information from flows")
That's based on "this approach would provide the best flexibility for the user yet with reasonable default, all the user has to do is to set `hubble.redact.enabled=true`" from https://github.com/cilium/cilium/issues/23887#issuecomment-1632167762.

2023-07-24 15:53 UTC, chancez commented on daemon/cmd/daemon_main.go
> +	flags.Bool(option.HubbleRedact, defaults.HubbleRedact, "Hubble redact sensitive information from flows")
Ah gotcha, so the defaults for the individual options are true, but the entire feature is off by default, that makes sense to me.

2023-07-24 15:56 UTC, ChrsMark commented on daemon/cmd/daemon_main.go
> +	flags.Bool(option.HubbleRedact, defaults.HubbleRedact, "Hubble redact sensitive information from flows")
Right! Note that the defaults are still `false` in this PR, but will be fixed accordingly based on the plan I suggested at https://github.com/cilium/cilium/issues/23887#issuecomment-1646650350.

2023-07-25 20:55 UTC, zacharysarah approved these changes
LGTM

2023-07-25 21:12 UTC, chancez approved these changes
Overall LGTM.

2023-07-26 08:20 UTC, gandro approved these changes
Helm looks good to me. I'll defer the Hubble changes to Chance

2023-07-26 08:31 UTC, pippolo84 approved these changes
Thanks! :100:

2023-07-27 12:10 UTC, ChrsMark commented
@derailed @tommyp1ckles @nathanjsweet could you please review this one when you get the chance 🙏🏽 ?

2023-08-04 15:58 UTC, rolinh approved these changes

2023-08-07 16:53 UTC, ldelossa commented
/test

2023-08-07 18:23 UTC, ldelossa commented
All required tests are passing and have critical mass on review approvals. Merging.

2023-08-07 18:23 UTC, merged

2023-08-08 16:05 UTC, joestringer commented
Both of the tests that failed on this PR prior to merging had this error, which is directly related to the changes in this PR:

```
connectivity test failed: unmarshaling cilium runtime config json: json: cannot unmarshal bool into Go struct field DaemonConfig.HubbleRedact of type []string
```

2023-08-08 17:19 UTC, ldelossa commented
@ChrsMark as explained here: https://github.com/cilium/cilium/pull/27352#issuecomment-1670007214

this pr was merged prematurely. Can you please open a subsequent PR with any suggested fixes mentioned in this one

2023-08-08 19:23 UTC, ChrsMark commented
Hey @ldelossa , sure I will have a look soon.
In the meantime, I wonder why we hit these compatability issues,  since https://github.com/cilium/cilium/pull/25844 should only be landed in `main` by now based on the discussions happened at https://github.com/cilium/cilium/issues/23887#issuecomment-1645784815 and the respective revert from `v1.14`.
Any pointer here would be appreciated :).

2023-08-08 20:07 UTC, joestringer commented
@ChrsMark Ah, I didn't recognize that this is only changing code in the main branch. The reason for the incompatibility is https://github.com/cilium/cilium-cli/issues/1896 . It looks like maybe the cilium/cilium-cli repo pulled in vendor code from cilium/cilium main after https://github.com/cilium/cilium/pull/25844, so the type it internally uses is incompatible with the type that was changed in this PR.

2023-08-16 12:39 UTC, ChrsMark commented
Hey @joestringer! So what is the best way to move this one forward? 

Given that the "breaking" change only applies on `main` would that make sense to make it now and then cilium-cli can pull an updated version of the dependency? 

Otherwise we can just rename `HubbleRedact` to `HubbleRedactEnabled` in this current patch but this would be a bit overkill just to tackle a non actual breaking change.

2023-08-16 23:18 UTC, joestringer commented
We're in a bit of a pickle because Cilium CLI is incorrectly relying on internal Cilium structures. Either we need to solve https://github.com/cilium/cilium-cli/issues/1896, or maybe use a different name for the field in `DaemonConfig` and open a fresh PR for these changes. We might even be able to also delete the current `HubbleRedact` field. However, those changes would need to be merged into main and then pulled into cilium-cli as a dependency before cilium/cilium main could have a different field called `HubbleRedact` inside `DaemonConfig`.

cc @cilium/cilium-cli-maintainers

2023-08-16 23:48 UTC, michi-covalent commented
yeah we still don't have a good answer for https://github.com/cilium/cilium-cli/issues/1896#issuecomment-1671605371.

in the meantime if we pick up the latest cilium code from main branch in cilium-cli, this error `connectivity test failed: unmarshaling cilium runtime config json: json: cannot unmarshal bool into Go struct field DaemonConfig.HubbleRedact of type []string` will go away right?

2023-08-16 23:53 UTC, michi-covalent commented
... so more concretely what i'm suggesting as a short term fix is:

- revert this revert: https://github.com/cilium/cilium/pull/27352
- and then immediately pick up cilium from the latest main branch in cilium-cli repo 💭

2023-08-17 01:26 UTC, joestringer commented
@michi-covalent We can't run CI properly and confirm that this PR doesn't break _other_ CI jobs without resolving this problem. Hence I suggest we just use a different field name so that the PR can pass the full CI and go through review *before* we merge it.

2023-08-17 01:28 UTC, joestringer commented
> in the meantime if we pick up the latest cilium code from main branch in cilium-cli, this error connectivity test failed: unmarshaling cilium runtime config json: json: cannot unmarshal bool into Go struct field DaemonConfig.HubbleRedact of type []string will go away right?

No, the problem is that the flag was first introduced with a bool type, then this PR changes it to a string. Now that this PR is reverted, it is back to a bool type. Cilium-CLI is still incorrectly deserializing that option as a bool, so updating Cilium-CLI will not fix that problem.

2023-08-17 02:17 UTC, michi-covalent commented
ok yeah using a different field name would work for sure if we are ok with changing the field name 👍