Small documentation fixups
cilium/cilium pull request #26999
Opened 2023-07-21 19:12 UTC by aanm

2023-07-21 19:49 UTC, zacharysarah requested changes, later dismissed
@aanm Nice. ✨ This review includes changes to text you haven't touched, but it's a chance to make small but meaningful improvements in a related PR.

2023-07-21 19:49 UTC, zacharysarah commented on Documentation/network/servicemesh/mutual-authentication/installation.rst
> +        Note this requires the Cilium CLI Helm mode (version 0.15 or later).
Use active voice, specific is better than general, punctuation nits

I'm not attached to "its" re:SPIRE server, feel free to replace with another article like "an"
```suggestion
        You can enable mutual authentication and its associated SPIRE server with the following command.
        This command requires the Cilium CLI Helm mode version 0.15 or later.
```

2023-07-21 19:49 UTC, zacharysarah commented on Documentation/network/servicemesh/mutual-authentication/installation.rst
> +        Next you can check the status of the Cilium agent and operator:
Good use of "you" to address the user, but we can trim it here
```suggestion
        Next, check the status of the Cilium agent and operator:
```

2023-07-24 09:31 UTC, meyskens approved these changes
For technical part of sig-servicemesh LGTM

2023-07-24 12:11 UTC, aanm commented
/test

2023-07-24 14:38 UTC, merged