enhancement(policy, aws): Construct CIDR rules for referenced AWS security groups by querying associated network interfaces
cilium/cilium pull request #27071
Opened 2023-07-26 03:39 UTC by spacepants

👋 Hello!

In the current implementation, Cilium can enforce policies based on AWS metadata by cross-walking referenced security group IDs or names to the IP addresses of EC2 instances associated with matching security groups. This PR extends this functionality to any VPC-enabled service, e.g. RDS, ElastiCache, VPC endpoints, etc. by querying the underlying network interfaces directly.

```release-note
Extend AWS metadata-based policy enforcement to work with any VPC-enabled service.
```

First time contributor. Please let me know if this need anything else. Thanks!

2023-07-26 18:59 UTC, christarazi reviewed
Thanks for the PR!

Could you split up the PR into separate commits where the refactoring is separate from the new additions? This will make it easier to review. For example, the newly defined function could be part of a separate prior commit and then the next could use the commit.

2023-07-26 18:59 UTC, christarazi commented on pkg/policy/groups/aws/aws.go
> +			Name:   aws.String(fmt.Sprintf("%s:%s", policyEC2Labelskey, labelKey)),
```suggestion
			Name:   aws.String(policyEC2Labelskey +":"+ labelKey),
```

2023-07-26 22:35 UTC, zacharysarah requested changes
@spacepants Welcome to the project and thanks for the contribution. Some nits to fix, otherwise LGTM. 

Be sure to check out the [documentation style guide](https://docs.cilium.io/en/stable/contributing/docs/docsstyle/).

2023-07-26 22:35 UTC, zacharysarah commented on Documentation/security/aws.rst
> +with some experience running Kubernetes.
Edits for clarity
```suggestion
based on AWS metadata. It provides a detailed walk-through of running a single-node
Cilium environment on your machine. It is designed to take 15-30 minutes
for users with some experience running Kubernetes.
```

2023-07-26 22:35 UTC, zacharysarah commented on Documentation/security/aws.rst
> +cluster to the destination network interfaces in that security group.
Use clear, plain language, formatting
```suggestion
In this example, the destination EC2 elastic network interfaces are attached to
EC2 instances that are members of a single AWS security group ('sg-0f2146100a88d03c3').
Pods with label ``class=xwing`` should only be able to make connections outside the
cluster to the destination network interfaces in that security group.
```

2023-07-26 22:35 UTC, zacharysarah commented on Documentation/security/aws.rst
> +that is in the security group with ID ``sg-0f2146100a88d03c3``.
Edits for clarity
```suggestion
This policy allows traffic from pod *xwing* to any AWS elastic network interface
in the security group with ID ``sg-0f2146100a88d03c3``.
```

2023-07-26 22:35 UTC, zacharysarah commented on Documentation/security/aws.rst
> +IPs will be updated periodically.
Use present tense
```suggestion
IPs is updated periodically.
```

2023-07-26 22:35 UTC, zacharysarah commented on pkg/policy/groups/aws/aws.go
> +	// If the group has a security group filter, add the ips from the network interfaces
Caps nit
```suggestion
	// If the group has a security group filter, add the IPs from the network interfaces
```

2023-07-26 22:35 UTC, zacharysarah commented on pkg/policy/groups/aws/aws.go
> +// getNetworkInterfaceIpsFromFilter returns the ips from the network interfaces for
Caps nit
```suggestion
// getNetworkInterfaceIpsFromFilter returns the IPs from the network interfaces for
```

2023-07-26 22:35 UTC, zacharysarah commented on pkg/policy/groups/aws/aws.go
> +// extractIPs returns the private and associated public ips from the given reservations
Caps nit
```suggestion
// extractIPs returns the private and associated public IPs from the given reservations
```

2023-07-30 18:05 UTC, spacepants commented
Rebased into separate logical commits as requested and updated based on feedback. Thank you!

2023-07-31 23:16 UTC, christarazi commented
Thanks!

CI is reporting a couple of things:

1. Commit title is too long

```
  Error: ERROR:CUSTOM: Please avoid long commit subjects (max: 75, found: 79)
```

2. Go linter errors 

```
  pkg/policy/groups/aws/aws.go:117: File is not `gofmt`-ed with `-s` (gofmt)
  			Name:   aws.String(policyEC2Labelskey +":"+ labelKey),
```

2023-07-31 23:23 UTC, spacepants commented
Thanks, updated!

2023-07-31 23:25 UTC, christarazi commented
/test

2023-08-01 22:10 UTC, zacharysarah approved these changes
LGTM for docs

2023-08-02 06:41 UTC, christarazi commented
/test

2023-08-02 06:41 UTC, christarazi approved these changes

2023-08-02 08:36 UTC, merged