bgpv1: Add `bgp/routes` API endpoint and `cilium bgp routes` CLI
cilium/cilium pull request #27182
Opened 2023-08-01 09:43 UTC by rastislavs

Adds a new `bgp/routes` API endpoint and the `cilium bgp routes` CLI implementation that can be used for retrieval of available/advertised routes from BGP Control Plane's RIBs.

**Example usage:**

Available `ipv4 unicast` routes:
```
$ cilium bgp routes available ipv4 unicast
VRouter   Prefix              NextHop   Age   Attrs
65001     10.0.0.0/24         0.0.0.0   21s   [{Origin: i} {Nexthop: 0.0.0.0}]   
65001     192.168.10.176/32   0.0.0.0   21s   [{Origin: i} {Nexthop: 0.0.0.0}]   
```

`ipv4 unicast` routes advertised to the neighbor `172.0.0.1`:
```
$ cilium bgp routes advertised ipv4 unicast neighbor 172.0.0.1
VRouter   Prefix              NextHop     Age      Attrs
65001     10.0.0.0/24         172.0.0.2   20m33s   [{Origin: i} 65001 {Nexthop: 172.0.0.2}]   
65001     192.168.10.176/32   172.0.0.2   20m33s   [{Origin: i} 65001 {Nexthop: 172.0.0.2}]
```

Available ipv4 unicast routes in virtual router with ASN `65001`:
```
$ cilium bgp routes available ipv4 unicast vrouter 65001
VRouter   Prefix              NextHop   Age     Attrs
65001     10.0.0.0/24         0.0.0.0   24m7s   [{Origin: i} {Nexthop: 0.0.0.0}]   
65001     192.168.10.176/32   0.0.0.0   24m7s   [{Origin: i} {Nexthop: 0.0.0.0}]   
```

2023-08-01 12:55 UTC, rastislavs commented
/test

2023-08-02 00:03 UTC, zacharysarah requested changes
@rastislavs One small wording nit, otherwise LGTM for docs

2023-08-02 00:03 UTC, zacharysarah commented on Documentation/configuration/api-restrictions-table.rst
> +                      specified parameters
Use active voice.
```suggestion
GetBGPRoutes          Retrieves routes from BGP Control Plane RIB filtered by
                     parameters you specify
```

2023-08-02 08:57 UTC, dylandreimerink approved these changes
Changes look good to me. It might be useful to add this command to the [bugtool output](https://github.com/cilium/cilium/blob/main/bugtool/cmd/configuration.go#L373) so the info is available in sysdumps.

2023-08-02 22:19 UTC, rastislavs commented on Documentation/configuration/api-restrictions-table.rst
> +                      specified parameters
done

2023-08-02 22:23 UTC, rastislavs commented
@dylandreimerink 
> It might be useful to add this command to the [bugtool output](https://github.com/cilium/cilium/blob/main/bugtool/cmd/configuration.go#L373) so the info is available in sysdumps.

Added into bugtool (as well as the previously existing "cilium bgp peers" command). Realized that we need to properly handle cases when BGP Control Plane is not enabled, so fixed that in https://github.com/cilium/cilium/pull/27182/commits/697c2bc1d7c626e9782749f89dfbf182c793503a .

2023-08-03 10:03 UTC, dylandreimerink approved these changes

2023-08-08 18:47 UTC, zacharysarah approved these changes
LGTM for docs

2023-08-09 19:07 UTC, harsimran-pabla reviewed
Few comments, overall looks good. There are few follow ups, maybe tasks can be created for them
- Extend this to cilium-cli
- Paging of the result, as it can be very large (order of 10k).
- Some optimization for later ( getting result concurrently from various vrouters - gobgp instances )

2023-08-09 19:07 UTC, harsimran-pabla commented on cilium/cmd/bgp_route_get.go
> +			fmt.Fprintf(w, "%s\t", path.PathAttributes)
nit: We should probably limit how long this attr field can get. For complete attributes, users could just json output. For stdout, we should be careful as this can be very long and will make output pretty difficult to read.

2023-08-09 19:07 UTC, harsimran-pabla commented on pkg/bgpv1/manager/manager.go
> +	if params.RouterAsn != nil {
m.Servers is a map, we should be able to do direct lookup for ASN.

2023-08-09 19:07 UTC, harsimran-pabla commented on pkg/bgpv1/manager/manager_test.go
> +			for _, cidr := range tt.expectedPrefixes {
can we simplify this by require.Contains

2023-08-10 09:48 UTC, rastislavs commented on pkg/bgpv1/manager/manager_test.go
> +			for _, cidr := range tt.expectedPrefixes {
actually simplified even more with `EqualValues`

2023-08-10 11:23 UTC, rastislavs commented on cilium/cmd/bgp_route_get.go
> +			fmt.Fprintf(w, "%s\t", path.PathAttributes)
I have included that in the follow-up issue (https://github.com/cilium/cilium/issues/27420). As the PathAttributes are base64-encoded in the yaml/json output, there is no other way to show them ATM.

For now, IMO it is still the better option to overflow a line potentially, than not be able to show them. Anyway, for standard Cilium use-cases (service / PodCIDR announcements etc.) this is very unlikely to be longer than one line.

2023-08-10 11:26 UTC, rastislavs commented
@harsimran-pabla 
> There are few follow ups, maybe tasks can be created for them

I have created an overarching follow-up task with potential enhancements: https://github.com/cilium/cilium/issues/27420

2023-08-10 11:27 UTC, rastislavs commented
/test

2023-08-10 12:47 UTC, harsimran-pabla approved these changes
Thank you!! LGTM

2023-08-10 15:53 UTC, nathanjsweet requested changes
A couple of nits for API and CLI.

2023-08-10 15:53 UTC, nathanjsweet commented on api/v1/openapi.yaml
> +      description: Retrieves routes from BGP Control Plane RIB filtered by parameters you specify
nit: Punctuation; no need for first person pronoun. 
```suggestion
      description: Retrieves routes from BGP Control Plane RIB, filtered by specified parameters.
```

2023-08-10 16:37 UTC, rastislavs commented on api/v1/openapi.yaml
> +      description: Retrieves routes from BGP Control Plane RIB filtered by parameters you specify
Hah funny, that is what it was originally, but was reworded by @zacharysarah as part of docs review: https://github.com/cilium/cilium/pull/27182#discussion_r1281254748

I guess the challenge here is that docs are auto-generated from the API description, and the wording that works for docs does not work that well for API :)

2023-08-10 16:38 UTC, nathanjsweet commented on api/v1/openapi.yaml
> +      description: Retrieves routes from BGP Control Plane RIB filtered by parameters you specify
Funny! Okay. Pay attention to her over me. She's our docs expert.

2023-08-10 16:38 UTC, nathanjsweet approved these changes
Approve for API and CLI

2023-08-10 16:39 UTC, merged

2023-08-31 16:50 UTC, joestringer commented
We may want to mark this `release-note/major` as an improvement to the visibility and day 2 operations for BGP support in Cilium.

2023-09-04 06:46 UTC, rastislavs commented
@joestringer 
> We may want to mark this `release-note/major` as an improvement to the visibility and day 2 operations for BGP support in Cilium.

makes sense, marked as `release-note/major`