gateway-api: Filter routes based on Section Name and port
cilium/cilium pull request #27309
Opened 2023-08-07 05:06 UTC by sayboras

### Description

Please refer to individual commit for more details.

2023-08-07 05:43 UTC, sayboras commented
/test

2023-08-07 09:00 UTC, aanm requested changes

2023-08-07 09:00 UTC, aanm commented on operator/pkg/model/translation/gateway-api/translator.go
> +			Name:      shorten(ciliumGatewayPrefix + resource.Name),
We need to think about name collisions before shortening this name. Discussed offline, we could some hash to help out in here.

2023-08-09 13:12 UTC, sayboras commented on operator/pkg/model/translation/gateway-api/translator.go
> +			Name:      shorten(ciliumGatewayPrefix + resource.Name),
thanks :100:

2023-08-09 13:41 UTC, sayboras commented
/test

2023-08-15 08:44 UTC, aanm approved these changes

2023-08-15 11:43 UTC, mhofstetter approved these changes

2023-08-15 11:45 UTC, sayboras commented
Reviews from required teams are in, merging this in.

2023-08-15 11:45 UTC, merged