ci-upgrade: Add e2e upgrade tests
cilium/cilium pull request #27322
Opened 2023-08-07 17:36 UTC by brb

2023-08-07 17:42 UTC, brb commented
/ci-e2e-upgrade

2023-08-09 10:05 UTC, brb commented
/ci-e2e-upgrade

2023-08-09 12:50 UTC, brb commented
/ci-e2e-upgrade

2023-08-09 14:18 UTC, brb commented
/ci-e2e-upgrade

2023-08-10 08:20 UTC, brb commented
/ci-e2e

2023-08-10 09:39 UTC, brb commented
/ci-e2e-upgrade

2023-08-11 06:50 UTC, brb commented
/ci-e2e-upgrade

2023-08-31 13:40 UTC, brb commented
/ci-e2e-upgrade

2023-08-31 16:18 UTC, brlbil requested changes

2023-08-31 16:18 UTC, brlbil commented on .github/workflows/tests-e2e-upgrade.yaml
> +    steps:
With recent PR #27391 we now add names to every Jobs and Steps
New PR #27839  adds linting for this not merged yet

\+ name: Commit Status Star

2023-08-31 16:18 UTC, brlbil commented on .github/workflows/tests-e2e-upgrade.yaml
> +    needs: setup-and-test
Same here
\+ name: Commit Status Final

2023-09-01 08:20 UTC, brb commented
/test

2023-09-01 10:46 UTC, brlbil approved these changes
LGTM

2023-09-01 13:32 UTC, aanm requested changes
Also, wouldn't it make more sense to add this as a step of the existing conformance-e2e.yaml?

2023-09-01 13:32 UTC, aanm commented on .github/workflows/tests-e2e-upgrade.yaml
> +            kernel: '4.19-20230420.212204'
```suggestion
            # renovate: datasource=docker depName=quay.io/lvh-images/kind
            kernel: '4.19-20230810.091425'
```

2023-09-01 13:32 UTC, aanm commented on .github/workflows/tests-e2e-upgrade.yaml
> +            kernel: '5.4-20230420.212204'
```suggestion
            # renovate: datasource=docker depName=quay.io/lvh-images/kind
            kernel: '5.4-20230810.091425'
```

2023-09-01 13:32 UTC, aanm commented on .github/workflows/tests-e2e-upgrade.yaml
> +            kernel: '5.10-20230420.212204'
```suggestion
            # renovate: datasource=docker depName=quay.io/lvh-images/kind
            kernel: '5.10-20230810.091425'
```

2023-09-01 13:32 UTC, aanm commented on .github/workflows/tests-e2e-upgrade.yaml
> +            kernel: '5.10-20230420.212204'
```suggestion
            # renovate: datasource=docker depName=quay.io/lvh-images/kind
            kernel: '5.10-20230810.091425'
```

2023-09-01 13:32 UTC, aanm commented on .github/workflows/tests-e2e-upgrade.yaml
> +            kernel: '5.15-20230420.212204'
```suggestion
            # renovate: datasource=docker depName=quay.io/lvh-images/kind
            kernel: '5.15-20230810.091425'
```

2023-09-01 13:32 UTC, aanm commented on .github/workflows/tests-e2e-upgrade.yaml
> +            kernel: '6.0-20230420.212204'
```suggestion
            # renovate: datasource=docker depName=quay.io/lvh-images/kind
            kernel: '6.0-20230810.091425'
```

2023-09-01 13:32 UTC, aanm commented on .github/workflows/tests-e2e-upgrade.yaml
> +            kernel: 'bpf-next-20230420.212204'
```suggestion
            # renovate: datasource=docker depName=quay.io/lvh-images/kind
            kernel: 'bpf-next-20230810.091425'
```

2023-09-01 13:32 UTC, aanm commented on .github/workflows/tests-e2e-upgrade.yaml
> +            kernel: 'bpf-next-20230420.212204'
```suggestion
            # renovate: datasource=docker depName=quay.io/lvh-images/kind
            kernel: 'bpf-next-20230810.091425'
```

2023-09-01 13:32 UTC, aanm commented on .github/workflows/tests-e2e-upgrade.yaml
> +            kernel: '5.10-20230420.212204'
```suggestion
            # renovate: datasource=docker depName=quay.io/lvh-images/kind
            kernel: '5.10-20230810.091425'
```

2023-09-01 13:32 UTC, aanm commented on .github/workflows/tests-e2e-upgrade.yaml
> +            kernel: '5.15-20230420.212204'
```suggestion
            # renovate: datasource=docker depName=quay.io/lvh-images/kind
            kernel: '5.15-20230810.091425'
```

2023-09-01 13:48 UTC, brb commented
> Also, wouldn't it make more sense to add this as a step of the existing conformance-e2e.yaml?

@aanm This would prolong the ci-e2e exec time, which is currently ~15min.

2023-09-01 13:51 UTC, aanm requested changes
Why do we have `(${{ matrix.name }})` in all step names? Can we remove them?

2023-09-01 13:57 UTC, aanm commented
> > Also, wouldn't it make more sense to add this as a step of the existing conformance-e2e.yaml?
> 
> @aanm This would prolong the ci-e2e exec time, which is currently ~15min.

but from what I can see the ci-e2e-upgrade is duplicating the same test done in the conformance-e2e. Maybe we should drop conformance-e2e because one of the steps done in the ci-e2e-upgrade has the same coverage as the conformance-e2e? What I mean is that the step ["Test Cilium after upgrade"](https://github.com/cilium/cilium/actions/runs/6047140499/job/16411576256#step:17:1) in `ci-upgrade` is doing the same thing as ["Run tests"](https://github.com/cilium/cilium/actions/runs/6047139929/job/16410019204#step:13:1) in `ci-e2e`

2023-09-01 14:00 UTC, brb commented
> Maybe we should drop conformance-e2e because one of the steps done in the ci-e2e-upgrade has the same coverage as the conformance-e2e?

@aanm Unfortunately noup, as that step which is run by ci-e2e-upgrade might be influenced by a previous installation of a stable release.

> Why do we have (${{ matrix.name }}) in all step names? Can we remove them?

Can we distinguish in the dashboard which configuration failed w/o it?

2023-09-01 14:09 UTC, brb commented
/ci-e2e-upgrade

2023-09-07 14:12 UTC, aanm approved these changes
For future reference. Before marking this tests as required we should make sure this is done https://github.com/cilium/cilium-cli/issues/1735#issuecomment-1710229091

2023-09-08 00:18 UTC, youngnick commented
/test

2023-09-08 13:49 UTC, brb commented
Let's wait with merging until https://github.com/cilium/cilium-cli/pull/1952 has been released.

2023-09-11 14:20 UTC, brb commented
/ci-e2e-upgrade

2023-09-13 05:26 UTC, brb commented
/ci-e2e-upgrade

2023-10-28 01:44 UTC, closed without merging

2024-03-13 15:09 UTC, thorn3r commented
cleanup: removing from GH projects and `needs-backport` labels