Don't retry one shot jobs during hive shutdown
cilium/cilium pull request #27395
Opened 2023-08-09 15:19 UTC by giorio94

Stop retrying to execute the function of a one shot job as soon as the job context is canceled, as the hive is already shutting down at that point. Indeed, the expectation is that the function exits immediately when the context expires, and it is most likely to return an error in that condition. Retrying would only delay the hive shutdown (also due to the additional backoff delay between consecutive attempts).

2023-08-09 15:20 UTC, giorio94 commented
/test

2023-08-09 16:54 UTC, giorio94 commented
Converting back to draft while investigating test failures.

2023-08-09 17:36 UTC, giorio94 commented
/test

2023-08-10 07:02 UTC, giorio94 commented
conformance-ginkgo hit https://github.com/cilium/cilium/issues/13071. Restarting the affected matrix entry.

2023-08-10 16:54 UTC, rgo3 requested changes

2023-08-10 16:54 UTC, rgo3 commented on pkg/hive/job/job.go
> +	cancel()
```suggestion
	defer cancel()
```

2023-08-10 17:03 UTC, giorio94 commented on pkg/hive/job/job.go
> +	cancel()
Good catch, thanks!

2023-08-10 17:04 UTC, rgo3 approved these changes

2023-08-10 17:26 UTC, rgo3 commented
Not really sure, deferring the question to @dylandreimerink or @joamaki :grimacing:

2023-08-11 17:16 UTC, merged