v1.12 Backports 2023-08-09
cilium/cilium pull request #27394
Opened 2023-08-09 15:10 UTC by joamaki

* [ ] #27193 (@nbusseneau)
 * [ ] #27184 (@pchaigno)
 * [ ] #27250 (@qmonnet)
 * [ ] #27168 (@learnitall)
 * [ ] #27312 (@julianwiedmann)
 * [ ] #27230 (@brb)
 * [ ] #27365 (@mhofstetter)

PRs skipped due to conflicts:

 * #27346 (@qmonnet)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 27193 27184 27250 27168 27312 27230 27365; do contrib/backporting/set-labels.py $pr done 1.12; done
```
or with
```
make add-labels BRANCH=v1.12 ISSUES=27193,27184,27250,27168,27312,27230,27365
```

2023-08-09 15:16 UTC, mhofstetter approved these changes

2023-08-09 15:18 UTC, qmonnet approved these changes

2023-08-09 16:15 UTC, nbusseneau requested changes
Thanks, made some comments below, if this is too annoying to fix don't hesitate to let me know and I can handle the backport manually :)

2023-08-09 16:15 UTC, nbusseneau commented on .github/workflows/build-images-base.yaml
> +
I think this should not be here 😁

2023-08-09 16:15 UTC, nbusseneau commented on .github/workflows/conformance-ingress.yaml
> +
You can drop this commit altogether, as https://github.com/cilium/cilium/commit/fd2240b8e3edd697277de1da22d6822270d403ee was never backported to v1.12.

2023-08-09 16:15 UTC, julianwiedmann approved these changes
looks good, thank you!

2023-08-09 16:16 UTC, nbusseneau requested changes
Sorry for some reason my 2 additional comments below stayed in draft.

2023-08-09 16:16 UTC, nbusseneau commented on .github/workflows/build-images-base.yaml
> +
Likewise here, since https://github.com/cilium/cilium/commit/fd2240b8e3edd697277de1da22d6822270d403ee was not backported to v1.12 we should not include this.

2023-08-09 16:16 UTC, nbusseneau commented on .github/workflows/build-images-ci.yaml
> +
Ditto.

2023-08-10 06:42 UTC, brb approved these changes
Thanks!

2023-08-10 12:36 UTC, joamaki commented on .github/workflows/build-images-base.yaml
> +
Thanks for double-checking. Had the hunch that this was going wrong.
Probably best if you'd do it manually. Thanks!

2023-08-10 12:39 UTC, joamaki commented
@nbusseneau I've dropped #27193 from this PR and marked it back to backport-needed. Could you take a look at manually backporting it? Thanks!

2023-08-10 13:06 UTC, ldelossa approved these changes

2023-08-10 14:39 UTC, learnitall approved these changes
Thanks!

2023-08-11 07:25 UTC, nebril commented
/test-backport-1.12

2023-08-15 08:00 UTC, YutaroHayakawa commented
ConformanceAKS is hitting this: https://github.com/cilium/cilium/issues/27443

2023-08-15 08:04 UTC, YutaroHayakawa commented
Paul's check is remaining, but he's off now, and since it's a document-only change, so safe to go forward.

2023-08-16 12:17 UTC, nbusseneau approved these changes

2023-08-17 07:53 UTC, ti-mo approved these changes

2023-08-17 07:53 UTC, merged