Replace use of `strict` to true in helm kubeProxyReplacement in helm chart
cilium/cilium pull request #27433
Opened 2023-08-10 16:11 UTC by xtineskim

- when using the `waitForKubeProxy` flag in helm installation, passing the `--set kubeProxyReplacement=true` during a helm installation of cilium causes an installation error. Replacing the use of `strict` to `true` as strict is deprecated 

Fixes: #27060 

```release-note

```

2023-08-16 09:56 UTC, ti-mo commented
/test

2023-08-16 14:14 UTC, kaworu approved these changes

2023-08-17 07:41 UTC, joamaki approved these changes

2023-08-24 04:36 UTC, joestringer commented
@xtineskim in general in Cilium we try to retain linear git history, so I've clicked the "rebase" button at the bottom to put this change on top of the tip of `main` and avoid the "merge" commits from earlier. I'll kick off CI and then this should likely be good to merge. Thanks for the submission!

2023-08-24 04:37 UTC, joestringer commented
/test

2023-08-24 04:58 UTC, joestringer commented
Runtime job hit https://github.com/cilium/cilium/issues/26617 : https://github.com/cilium/cilium/actions/runs/5959529285/job/16165429974

2023-08-24 06:25 UTC, borkmann commented
> * when using the `waitForKubeProxy` flag in helm installation, passing the `--set kubeProxyReplacement=true` during a helm installation of cilium causes an installation error. Replacing the use of `strict` to `true` as strict is deprecated

Cc @brb should this be either "true" or "strict"? Meaning, if people still use the "strict" it should not fail either, no?

2023-08-24 17:01 UTC, joestringer commented
@xtineskim not sure if there was a conflict or something, but just a heads up that your PRs will almost _always_ be "out of date" compared to the `main` branch. If there's no conflict, then there's usually no reason to rebase. Every time you rebase, we'll need to re-trigger CI.

2023-08-24 17:01 UTC, joestringer commented
/test

2023-08-24 18:32 UTC, joestringer requested changes
Relating to @borkmann's observation above:

https://github.com/cilium/cilium/blob/6217d01630eb26734f956ac0b801587e05822c13/install/kubernetes/cilium/templates/cilium-configmap.yaml#L66-L69

In the current version, this setting can be set to true, false, disabled, partial or strict. It seems to me like as long as the above helm validation allows "strict", then this check should also cope with that version of the setting.

Either we need to make this an AND statement for not equal to "strict" or "true" so that the daemonset only waits for kube-proxy when kube proxy replacement is disabled, OR we need to change the lines at the top of this message to disallow the "strict" / "partial" / "disabled" settings.

2023-08-24 19:00 UTC, xtineskim commented
good catch, and thanks for the feedback. No super strong opinions - I think I'd prefer allowing strict and true (not sure if there is a hard timeline for removing the use of strict/partial)?

2023-08-24 19:39 UTC, joestringer commented
(CI passed)

2023-08-25 17:35 UTC, xtineskim commented
changed to allow for "strict" or "true"
For enabling w/ "true", users have to run with `--set-string` vs enabling w/ "strict", which just uses `--set`

2023-08-25 17:46 UTC, joestringer commented on install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml
> +      {{- if and .Values.waitForKubeProxy (or (ne $kubeProxyReplacement "strict") (ne $kubeProxyReplacement "true"))  }}
Let's say the user configured wait for kubepraxy and kubeproxyreplacement=strict. That will boil down into:

`and true (or (false) (true))`, so the result will be to wait for kube-proxy even though kube-proxy is disabled.

I think that the inner `or` needs to be an `and`...?

```suggestion
      {{- if and .Values.waitForKubeProxy (and (ne $kubeProxyReplacement "strict") (ne $kubeProxyReplacement "true"))  }}
```

2023-08-25 17:58 UTC, joestringer approved these changes

2023-08-25 17:58 UTC, joestringer commented
/test

2023-08-28 08:30 UTC, brb approved these changes
Thanks!

2023-09-12 09:14 UTC, julianwiedmann commented
/test

2023-09-12 11:08 UTC, merged