Delay port release
cilium/cilium pull request #2747
Opened 2018-02-07 22:13 UTC by tgraf

2018-02-07 22:14 UTC, tgraf commented
test-me-please

2018-02-07 22:37 UTC, ianvernon requested changes

2018-02-07 22:37 UTC, ianvernon commented on pkg/proxy/proxy.go
> +			Debugf("Delayed release of proxy port 5d", toPort)
5d --> %d

2018-02-07 22:38 UTC, tgraf commented on pkg/proxy/proxy.go
> +			Debugf("Delayed release of proxy port 5d", toPort)
fixed

2018-02-07 22:39 UTC, tgraf commented
test-me-please

2018-02-07 22:46 UTC, ianvernon approved these changes

2018-02-07 23:37 UTC, merged

2018-02-08 08:01 UTC, eloycoto commented on pkg/proxy/proxy.go
> +		time.Sleep(portReleaseDelay)
Minor nitpick, here I would use `time.After` instead of the sleep.