Refactor watchstore/watchsync metrics
cilium/cilium pull request #27485
Opened 2023-08-14 09:42 UTC by marseel

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note

```

2023-08-17 11:25 UTC, marseel commented
/test

2023-08-17 14:10 UTC, marseel commented
/test

2023-08-18 17:24 UTC, chancez approved these changes

2023-08-21 07:29 UTC, giorio94 requested changes
Changes overall make sense to me.

I've left inline a few comments and nits. Could you please also extend the commit message with a bit of description about the rationale behind the changes?

2023-08-21 07:29 UTC, giorio94 commented on clustermesh-apiserver/main.go
> +	Factory        store.WatchSyncStoreFactory
Nit. I'd personally rename this to `StoreFactory` (or something similar), as just plain `Factory` would likely conflict in the future. The same also applies to the other occurrences.

2023-08-21 07:29 UTC, giorio94 commented on pkg/clustermesh/cell.go
> +	store.Cell,
I wouldn't register the store cell here, as this is a dependency of the clustermesh cell, and not something that the clustermesh cell provides (a cell can only be registered once in the entire hive). To me, it seems more an infrastructural cell that should be registered in `daemon/cmd/cells.go`. The same also applies to the kvstoremesh cell.

2023-08-21 07:29 UTC, giorio94 commented on pkg/clustermesh/clustermesh_test.go
> +	).Populate()
I'd personally replace this (and the other occurrences) with a method that simply returns a new factory. Constructing a complete hive is pretty verbose, and IMO also a bit confusing for tests.

2023-08-21 07:29 UTC, giorio94 commented on pkg/kvstore/store/watchstore.go
> +	}
Is the if statement necessary? AFAIU syncMetric should never be nil.

2023-08-21 11:57 UTC, giorio94 approved these changes
/lgtm

2023-08-21 13:16 UTC, marseel commented
/test

2023-08-21 23:08 UTC, christarazi approved these changes
LGTM from my codeowners

2023-08-23 09:55 UTC, marseel commented
rebased onto main branch

2023-08-24 10:03 UTC, marseel commented
/test

2023-08-24 12:19 UTC, marseel commented
Removing Casey as he is OOO

2023-08-28 09:19 UTC, marseel commented
/test

2023-08-28 09:55 UTC, jrajahalme approved these changes
LGTM

2023-08-29 07:54 UTC, ti-mo approved these changes

2023-08-29 07:56 UTC, merged