Enhancement:Update generic-veth chaining docs with chainingTarget instructions
cilium/cilium pull request #27579
Opened 2023-08-18 01:18 UTC by jspaleta

### Documentation Enhancement
Update generic-veth chaining docs with chainingTarget instructions appropriate for multi-node kind cluster using new Helm option available as of v1.14.0.

2023-08-19 00:37 UTC, zacharysarah requested changes
@jspaleta Thanks for the updates. Some changes for clearer wording, otherwise LGTM for docs.

2023-08-19 00:37 UTC, zacharysarah commented on Documentation/installation/cni-chaining-generic-veth.rst
> +Option 1: Use a cluster-wide custom CNI configuration to define your chaining configuration
Keep headings tight, avoid overuse of "configuration"
```suggestion
Use a cluster-wide custom CNI to define your chaining configuration
```

2023-08-19 00:37 UTC, zacharysarah commented on Documentation/installation/cni-chaining-generic-veth.rst
> +This option is appropriate when you need a common CNI configuration on all nodes.
Use active voice
```suggestion
Use this option when you need a common CNI configuration on all nodes.
```

2023-08-19 00:37 UTC, zacharysarah commented on Documentation/installation/cni-chaining-generic-veth.rst
> +Similarly ``enableIPv4Masquerade=false`` instructs Cilium to not to set IPV4Masquerading, leaving that to other CNI plugins to manage.
Use clear, plain language, use active voice
```suggestion
The ``routingMode=native`` flag instructs Cilium not to manage network routing, assuming you will use the other CNI plugins.
Similarly, ``enableIPv4Masquerade=false`` instructs Cilium to not to set IPV4Masquerading, leaving the task to other CNI plugins to manage.
```

2023-08-19 00:37 UTC, zacharysarah commented on Documentation/installation/cni-chaining-generic-veth.rst
> +Option 2: Extend existing named CNI configuration
Keep headings tight
```suggestion
Extend existing named CNI configuration
```

2023-08-19 00:37 UTC, zacharysarah commented on Documentation/installation/cni-chaining-generic-veth.rst
> +This option is appropriate when the existing CNI configuration for your cluster has node specific values
Use active voice
```suggestion
Use this option when the existing CNI configuration for your cluster has node specific values
```

2023-08-19 00:37 UTC, zacharysarah commented on Documentation/installation/cni-chaining-generic-veth.rst
> +and a single cluster-wide CNI configuration can't be used. Review the named CNI configurations by manually
Use active voice
```suggestion
and you can't use a single cluster-wide CNI configuration. Review the named CNI configurations by manually
```

2023-08-19 00:37 UTC, zacharysarah commented on Documentation/installation/cni-chaining-generic-veth.rst
> +examining the CNI configurations on each node. For example a Kind cluster will typically have a CNI configuration named "kindnet".
Use present tense, comma nit
```suggestion
examining the CNI configurations on each node. For example, a Kind cluster typically has a CNI configuration named "kindnet".
```

2023-08-19 00:37 UTC, zacharysarah commented on Documentation/installation/cni-chaining-generic-veth.rst
> +to the end of its plugin chain. For example in a Kind cluster you use  ``--set cni.chainingTarget=kindnet``
Use active voice, comma nit
```suggestion
Replace ``<CNI-name>`` with the name of the CNI configuration you want to extend by appending the Cilium CNI plugin
to the end of its plugin chain. For example, in a Kind cluster you use  ``--set cni.chainingTarget=kindnet``
```

2023-08-29 23:03 UTC, jspaleta commented
working on cleaning this up now, just a few minutes

2023-09-01 21:51 UTC, zacharysarah approved these changes

2023-10-16 01:45 UTC, closed without merging