proxy: Ignore visibility annotation if proxy is disabled
cilium/cilium pull request #27597
Opened 2023-08-20 13:02 UTC by sayboras

### Description

This is to avoid the below error if proxy is disabled as part of
installation, but the visibility annotation is added to pods later.

```console
2023-08-11T12:42:41.390575371Z goroutine 1522 [running]:
2023-08-11T12:42:41.390581994Z github.com/cilium/cilium/pkg/proxy.(*Proxy).CreateOrUpdateRedirect(0x0, {0x3ae74b8, 0xc000650280}, {0x3aeb440?, 0xc0016e4560?}, {0xc0010ba1b0, 0x12}, {0x3afd260, 0xc000982000}, 0xc001c9c980)
2023-08-11T12:42:41.390589198Z  github.com/cilium/cilium/pkg/proxy/proxy.go:459 +0xb7
2023-08-11T12:42:41.390596081Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).addVisibilityRedirects(0xc000982000, 0x1, 0xc001874ba0?, 0xc001c9c980?)
2023-08-11T12:42:41.390602613Z  github.com/cilium/cilium/pkg/endpoint/bpf.go:343 +0x443
2023-08-11T12:42:41.390614345Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).addNewRedirects(0xc000982000, 0xc001874870?)
2023-08-11T12:42:41.390651325Z  github.com/cilium/cilium/pkg/endpoint/bpf.go:424 +0x3c5
2023-08-11T12:42:41.390658068Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).runPreCompilationSteps(0xc000982000, 0xc000e31800, 0x0)
2023-08-11T12:42:41.390663999Z  github.com/cilium/cilium/pkg/endpoint/bpf.go:802 +0x4fe
2023-08-11T12:42:41.390669690Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0xc000982000, 0xc000e31800)
2023-08-11T12:42:41.390675451Z  github.com/cilium/cilium/pkg/endpoint/bpf.go:542 +0x1a5
2023-08-11T12:42:41.390681112Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc000982000, 0xc000e31800)
2023-08-11T12:42:41.390686893Z  github.com/cilium/cilium/pkg/endpoint/policy.go:467 +0x9c6
2023-08-11T12:42:41.390692564Z github.com/cilium/cilium/pkg/endpoint.(*EndpointRegenerationEvent).Handle(0xc000131b50, 0x0?)
2023-08-11T12:42:41.390698385Z  github.com/cilium/cilium/pkg/endpoint/events.go:53 +0x325
2023-08-11T12:42:41.390704045Z github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run.func1()
2023-08-11T12:42:41.390709716Z  github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:245 +0x142
```
    
Fixes: #27594

### Testing

Testing was done locally with l7Proxy=false, and then annotate a pod with visibility annotation

```console
$ k annotate pod client-77bf9989dc-984xp policy.cilium.io/proxy-visibility="<Egress/80/TCP/HTTP>" --overwrite
pod/client-77bf9989dc-984xp annotate
$ ksyslo ds/cilium --timestamps | zgrep "ignoring L7 proxy visibility policy as L7 proxy is disabled"
2023-08-20T13:02:08.241508927Z level=warning msg="ignoring L7 proxy visibility policy as L7 proxy is disabled" ciliumEndpointName=default/client-77bf9989dc-984xp containerID=1ea0a77f5d containerInterface=eth0 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=759 identity=831 ipv4=10.244.0.19 ipv6= k8sPodName=default/client-77bf9989dc-984xp subsys=endpoint
```

2023-08-21 09:33 UTC, sayboras commented
/test

2023-08-21 10:42 UTC, sayboras commented
/test

2023-08-21 11:32 UTC, kaworu approved these changes

2023-08-21 13:04 UTC, youngnick approved these changes

2023-08-21 22:44 UTC, zacharysarah requested changes
@sayboras Small changes for clarity and consistency, otherwise LGTM for docs.

2023-08-21 22:44 UTC, zacharysarah commented on Documentation/observability/visibility.rst
> +    This feature requires L7 Proxy support to be enabled. If not, the visibility annotation will be ignored.
Use present tense, use active voice
```suggestion
    This feature requires enabling L7 Proxy support. Without it, the visibility annotation is ignored.
```

2023-08-22 04:34 UTC, sayboras commented on Documentation/observability/visibility.rst
> +    This feature requires L7 Proxy support to be enabled. If not, the visibility annotation will be ignored.
Thanks for your input :+1:

2023-08-22 04:35 UTC, sayboras commented
/test

2023-08-22 21:51 UTC, zacharysarah approved these changes

2023-08-23 12:45 UTC, jrajahalme approved these changes

2023-08-23 12:45 UTC, merged