Add documentation of Hubble Exporter
cilium/cilium pull request #27610
Opened 2023-08-21 12:22 UTC by AwesomePatrol

Fixes #26970

```release-note
Add documentation of Hubble exporter - an option to save Hubble flows to a file
```

2023-08-21 22:41 UTC, zacharysarah requested changes
@AwesomePatrol Thanks for adding this page. There are some clarity issues to fix, as well as some questions about how we can be more specific.

2023-08-21 22:41 UTC, zacharysarah commented on Documentation/index.rst
> +   observability/hubble-exporter
This looks like it's in the right place. ✅

2023-08-21 22:41 UTC, zacharysarah commented on Documentation/observability/hubble-exporter.rst
> +rotation, size limits, filters and field masks.
Use clear, plain language, comma nit, specific is better than general
```suggestion
**Hubble Exporter** is a feature of ``cilium-agent`` that lets you write
Hubble flows to a file for later consumption as logs. Hubble Exporter supports file
rotation, size limits, filters, and field masks.
```

2023-08-21 22:41 UTC, zacharysarah commented on Documentation/observability/hubble-exporter.rst
> +``hubble-export-file-path`` is set.
Use clear plain language, use active voice
```suggestion
Configure **Hubble Exporter** with Config Map. The feature has a default name of
``cilium-config``. Hubble Exporter is disabled until you set a file path value for
``hubble-export-file-path``.
```

2023-08-21 22:41 UTC, zacharysarah commented on Documentation/observability/hubble-exporter.rst
> +Verify that change was applied (it can take a few minutes before first flow is
Grammar nit. I don't love the passive voice here, but I think it's the best choice.
```suggestion
Verify that the change was applied (it can take a few minutes before the first flow is
```

2023-08-21 22:41 UTC, zacharysarah commented on Documentation/observability/hubble-exporter.rst
> +Configure your logging solution to consume logs from the specified location.
Specific is better than general
```suggestion
Configure your logging solution to consume logs from your Hubble export file path.
```

2023-08-21 22:41 UTC, zacharysarah commented on Documentation/observability/hubble-exporter.rst
> +Other configuration options:
Clarity
```suggestion
Other configuration options include:
```

2023-08-21 22:41 UTC, zacharysarah commented on Documentation/observability/hubble-exporter.rst
> +  Compress rotated Hubble export files.
I'd rather see these pairs on single lines.

Is `hubble-export-file-compress` a Boolean? What values does it accept?
```suggestion
- ``hubble-export-file-max-size-mb``: size in MB at which to rotate the Hubble export file. (default 10)

- ``hubble-export-file-max-backups``: number of rotated Hubble export files to keep. (default 5)

- ``hubble-export-file-compress``: compress rotated Hubble export files.
```

2023-08-21 22:41 UTC, zacharysarah commented on Documentation/observability/hubble-exporter.rst
> +Configuration options impacting performance of **Hubble exporter**:
Clarity
```suggestion
Configuration options impacting performance of **Hubble exporter** include:
```

2023-08-21 22:41 UTC, zacharysarah commented on Documentation/observability/hubble-exporter.rst
> +  Specify list of fields to use for field mask in Hubble exporter.
Again, these pairs work better as single lines.
```suggestion
- ``hubble-export-allowlist``: specify an allowlist as JSON encoded FlowFilters to Hubble exporter.

- ``hubble-export-denylist``: specify a denylist as JSON encoded FlowFilters to Hubble exporter.

- ``hubble-export-fieldmask``: specify a list of fields to use for field masking in Hubble exporter.
```

2023-08-21 22:41 UTC, zacharysarah commented on Documentation/observability/hubble-exporter.rst
> +You can use ``hubble`` CLI to generated required filters (see `Specifying Raw
Good use of active voice and referring to the user as "you" 👍🏻

2023-08-21 22:41 UTC, zacharysarah commented on Documentation/observability/hubble-exporter.rst
> +For example to filter flows with verdict ``DENIED`` or ``ERROR`` run:
Comma nits
```suggestion
For example, to filter flows with verdict ``DENIED`` or ``ERROR``, run:
```

2023-08-21 22:41 UTC, zacharysarah commented on Documentation/observability/hubble-exporter.rst
> +and paste the output to ``hubble-export-allowlist`` in ``cilium-config``
Grammar nit
```suggestion
Then paste the output to ``hubble-export-allowlist`` in ``cilium-config``
```

2023-08-21 22:41 UTC, zacharysarah commented on Documentation/observability/hubble-exporter.rst
> +``kube-system`` namespace:
Clarity, active voice, consistency with previous example
```suggestion
You can do the same to selectively filter data. For example, to filter all flows in the
``kube-system`` namespace, run:
```

2023-08-21 22:41 UTC, zacharysarah commented on Documentation/observability/hubble-exporter.rst
> +and paste the output to ``hubble-export-denylist`` in ``cilium-config`` Config
Grammar nit
```suggestion
Then paste the output to ``hubble-export-denylist`` in ``cilium-config`` Config
```

2023-08-21 22:41 UTC, zacharysarah commented on Documentation/observability/hubble-exporter.rst
> +Currently, field masks can't be generated with ``hubble``. It is a list of field names from `flow proto`_ definition.
Avoid references to the future or present as an ambiguous state. Specific is better than general: what does "it" refer to?
```suggestion
Field masks can't be generated with ``hubble``. It is a list of field names from the `flow proto`_ definition.
```

2023-08-21 22:41 UTC, zacharysarah commented on Documentation/observability/hubble-exporter.rst
> + - Keep most of the information with notable exception of pod labels:
Grammar and clarity
```suggestion
 - To keep all information except pod labels:
```

2023-08-21 22:41 UTC, zacharysarah commented on Documentation/observability/hubble-exporter.rst
> + - Keep only timestamp, verdict, ports, IP addresses, node name, pod name and namespace:
Grammar
```suggestion
 - To keep only timestamp, verdict, ports, IP addresses, node name, pod name, and namespace:
```

2023-08-21 22:41 UTC, zacharysarah commented on Documentation/observability/hubble-exporter.rst
> +Complete example:
```suggestion
The following is a complete example of configuring Hubble Exporter.
```

2023-08-21 22:41 UTC, zacharysarah commented on Documentation/observability/hubble-exporter.rst
> +Examples:
Grammar
```suggestion
Examples include:
```

2023-08-21 22:41 UTC, zacharysarah commented on Documentation/spelling_wordlist.txt
> +allowlist
I'm surprised that `allowlist` and `denylist` weren't already in the word list. 😲

2023-08-22 21:50 UTC, zacharysarah approved these changes

2023-08-22 22:05 UTC, aditighag approved these changes
Amazing docs PR 👏 
The policy related filters look good to me for my codeowners. Requesting a review from @cilium/sig-hubble /cc @chancez  as I'm not familiar with some of the extended filters like field mask and so on.

2023-08-22 22:05 UTC, aditighag commented on Documentation/observability/hubble-exporter.rst
> +    $ hubble observe --not --namespace kube-system --print-raw-filters
Nice! TIL about `--not` option

2023-08-22 22:08 UTC, aditighag commented
@AwesomePatrol FYI -- I added the missing release note label, see - https://docs.cilium.io/en/v1.13/contributing/development/contributing_guide/#submitting-a-pull-request.

2023-08-22 22:39 UTC, chancez approved these changes

2023-08-23 03:37 UTC, joestringer commented
/test

2023-08-23 03:50 UTC, michi-covalent approved these changes
🥰

2023-08-23 06:17 UTC, merged