Enable prometheus metrics for cilium-operator and clustermesh's Etcd by default
cilium/cilium pull request #27653
Opened 2023-08-23 11:46 UTC by marseel

Enable prometheus metrics for cilium-operator and clustermesh's Etcd by default.

Related: https://github.com/cilium/cilium-cli/pull/1927

```release-note
Cilium-operator and clustermesh's kvstore metrics are now enabled by default in Helm.
```

2023-08-23 13:47 UTC, kaworu requested changes

2023-08-23 13:47 UTC, kaworu commented on install/kubernetes/cilium/values.yaml
Please report the changes to `install/kubernetes/cilium/values.yaml.tmpl` and then run

```
make -C install/kubernetes cilium/values.yaml
```

2023-08-23 21:17 UTC, zacharysarah approved these changes
LGTM

2023-08-24 05:27 UTC, tommyp1ckles approved these changes
nice, having these on by default makes a lot of sense

2023-08-24 10:02 UTC, marseel commented on install/kubernetes/cilium/values.yaml
Thanks, done.

2023-08-24 13:17 UTC, kaworu approved these changes

2023-08-28 20:42 UTC, aditighag commented on Documentation/observability/metrics.rst
> +use ``operator.prometheus.enabled=true`` (enabled by default).
Should this sentence now be flipped if the default is `true`? It's enabled by default, use ... = false to turn it off.

2023-09-28 14:31 UTC, marseel commented
/test

2023-09-29 18:46 UTC, merged