docs: rephrasing the hubble intro doc
cilium/cilium pull request #27712
Opened 2023-08-25 18:42 UTC by vipul-21

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Rephrasing the doc to make sure to avoid duplication

Fixes: #14587

2023-08-25 18:43 UTC, vipul-21 commented
@joestringer can you take a look at this when you have time.

2023-08-25 20:28 UTC, joestringer commented
@vipul-21 I don't review all PRs, GitHub has assigned CODEOWNERS for the relevant areas to review. As @cilium/tophat for the week I'll trigger CI for you :+1:

2023-08-25 20:29 UTC, joestringer commented
/test

2023-08-28 12:48 UTC, lambdanis requested changes
Thanks @vipul-21, I left a few suggestions. Could you also put reasoning for the change in the commit message? Based on the linked issue, I understand the change is done to reduce duplication between the two paragraphs.

2023-08-28 12:48 UTC, lambdanis commented on Documentation/gettingstarted/hubble_intro.rst
> +cilium agent runs. This confines the network insights to the traffic observed by the local
```suggestion
Cilium agent runs. This confines the network insights to the traffic observed by the local
```

2023-08-28 12:48 UTC, lambdanis commented on Documentation/gettingstarted/hubble_intro.rst
> +Cilium agent. Hubble CLI(``hubble``) can be used to query the Hubble API provided via a local
```suggestion
Cilium agent. Hubble CLI (``hubble``) can be used to query the Hubble API provided via a local
```

2023-08-28 12:48 UTC, lambdanis commented on Documentation/gettingstarted/hubble_intro.rst
> +directing the Hubble CLI(``hubble``) to the Hubble Relay service or via Hubble UI.
```suggestion
directing Hubble CLI (``hubble``) to the Hubble Relay service or via Hubble UI. 
```

2023-08-28 12:48 UTC, lambdanis commented on Documentation/gettingstarted/hubble_intro.rst
> +Unix Domain Socket. (The Hubble CLI binary is installed by default on Cilium agent pods.)
```suggestion
Unix Domain Socket. The Hubble CLI binary is installed by default on Cilium agent pods.
```
Is there a good reason for using parentheses?

2023-08-28 18:57 UTC, chancez approved these changes

2023-08-28 18:57 UTC, chancez requested changes
Can you squash your commits together?

2023-08-28 19:19 UTC, chancez approved these changes
Thanks!

2023-08-28 20:19 UTC, lambdanis approved these changes

2023-09-12 08:57 UTC, merged