Add prerelease-testing issue template
cilium/cilium pull request #27766
Opened 2023-08-29 07:38 UTC by jspaleta

This PR adds a new prerelease-testing issue template, meant to be used for the prerelease-testing initiative to track testing contributions, including successful tests.

Note this template references a new issue label `kind/prerelease-testing`

2023-08-29 09:15 UTC, bimmlerd requested changes, later dismissed
typo, lgtm otherwise

2023-08-29 09:15 UTC, bimmlerd commented on .github/ISSUE_TEMPLATE/prerelease-testing.yaml
> +name: Prerelease Tessting
```suggestion
name: Prerelease Testing
```

2023-08-29 18:09 UTC, joestringer approved these changes
Minor nits around spelling & capitalization, otherwise LGTM. Looking forward to see how this improves testing of Cilium prerelease snapshots!

2023-08-29 18:09 UTC, joestringer commented on .github/ISSUE_TEMPLATE/prerelease-testing.yaml
> +        - Regresion Testing
```suggestion
        - Regression Testing
```

2023-08-29 18:09 UTC, joestringer commented on .github/ISSUE_TEMPLATE/prerelease-testing.yaml
> +        4. resulting in error...
```suggestion
        3. Tested this feature...
        4. Resulting in error...
```

2023-08-29 18:09 UTC, joestringer commented on .github/ISSUE_TEMPLATE/prerelease-testing.yaml
> +        6. see error...
```suggestion
        6. See error... 
```

2023-08-29 18:09 UTC, joestringer commented on .github/ISSUE_TEMPLATE/prerelease-testing.yaml
> +        - "Unknown: Something went wrong, but not sure what"
```suggestion
        - "Success: Test completed without issue"
        - "Incomplete: Ran out of time" 
        - "Failure: Reproducible bug encountered/filed"
        - "Unknown: Something went wrong, but not sure what"
```

2023-08-29 20:56 UTC, joestringer commented
LGTM, could you squash the commits together?

2023-08-29 22:50 UTC, jspaleta commented
I squash now

2023-08-29 23:02 UTC, jspaleta commented
commits squashed

2023-08-30 00:51 UTC, joestringer approved these changes

2023-08-30 00:51 UTC, joestringer commented
Thanks Jef, merging.

2023-08-30 00:51 UTC, merged