Pr/tp/l7 metrics improvements
cilium/cilium pull request #27863
Opened 2023-08-31 22:53 UTC by tommyp1ckles

2023-09-01 05:50 UTC, tommyp1ckles commented
/test

2023-09-01 22:05 UTC, learnitall approved these changes
Little formatting suggestion, otherwise LGTM.

2023-09-01 22:05 UTC, learnitall commented on Documentation/operations/upgrade.rst
> +* ``cilium_policy_l7_total`` now has label proxy_type to distinguish between fqdn and envoy proxy requests.
```suggestion
* ``cilium_policy_l7_total`` now has label ``proxy_type`` to distinguish between FQDN and Envoy proxy requests.
```

2023-09-04 08:57 UTC, gandro approved these changes
My code owners look good to me!

2023-09-06 14:39 UTC, derailed requested changes
@tommyp1ckles LG! just a few minor nits. 
Thinking we might be better off passing parallel types around vs strings to help readability...

2023-09-06 14:39 UTC, derailed commented on pkg/endpoint/endpoint.go
> +type ProxyType string
Are we using this anywhere?

2023-09-06 14:39 UTC, derailed commented on pkg/endpoint/endpoint.go
> +func (e *Endpoint) UpdateProxyStatistics(proxyType string, l4Protocol string, port uint16, ingress, request bool, verdict accesslog.FlowVerdict) {
nit: Depending on resp from above prefer proxyType, l4Proto string

2023-09-06 14:39 UTC, derailed commented on pkg/proxy/endpoint/endpoint.go
> +	UpdateProxyStatistics(proxyType string, l4Protocol string, port uint16, ingress, request bool, verdict accesslog.FlowVerdict)
nit: signature update from above

2023-09-06 14:39 UTC, derailed commented on pkg/proxy/endpoint/test/updater_mock.go
> +func (m *ProxyUpdaterMock) UpdateProxyStatistics(proxyType string, l4Protocol string, port uint16, ingress, request bool,
nit: signature update from above

2023-09-07 05:08 UTC, tommyp1ckles commented on pkg/endpoint/endpoint.go
> +type ProxyType string
nope, will clean up

2023-09-07 05:17 UTC, tommyp1ckles commented
/test

2023-09-07 05:35 UTC, tommyp1ckles commented
/test

2023-09-11 08:25 UTC, jrajahalme approved these changes

2023-09-11 18:46 UTC, derailed approved these changes
@tommyp1ckles Thanks for the updates!

2023-09-11 22:21 UTC, tommyp1ckles commented
/test

2023-09-12 19:38 UTC, tommyp1ckles commented
/test

2023-09-13 05:36 UTC, merged

2023-12-06 23:34 UTC, christarazi commented
Nominating for backport as it aids with debugging.