external-workloads: do not automatically infer ClusterID/Name
cilium/cilium pull request #27886
Opened 2023-09-01 14:26 UTC by giorio94

Currently, when the Cilium agent running on a VM joins an existing cluster, it automatically infers the corresponding ClusterID and ClusterName. Yet, this introduces a dependency order, because all consumers of that field need to be initialized after the connection to the remote cluster, which is especially problematic as more components get converted to cells. Additionally, this may also lead to possible user confusion, as the corresponding parameter is reported as not initialized in the logs.

Hence, let's require these parameters to be explicitly set, reporting a failure in case they don't match those automatically discovered.

```release-note
Don't automatically infer ClusterID and ClusterName for external workloads.
```

2023-09-04 08:56 UTC, gandro reviewed
Thanks! Does this need to be documented in the upgrade notes as a breaking change or is this not a configuration we expect users to have?

2023-09-18 12:47 UTC, giorio94 commented
> Does this need to be documented in the upgrade notes as a breaking change or is this not a configuration we expect users to have?

External workloads are marked as a beta feature, but I agree that it makes sense to call this out as a breaking change. I've updated the upgrade notes to document it.

2023-09-18 12:47 UTC, giorio94 commented
/test

2023-09-18 15:40 UTC, gandro approved these changes

2023-09-19 07:57 UTC, giorio94 commented
/test

2023-09-25 11:24 UTC, zacharysarah requested changes
@giorio94 Thanks for your patience. This is well-written and needs only some small tweaks for approval.

2023-09-25 11:24 UTC, zacharysarah commented on Documentation/operations/upgrade.rst
> +  explicitly specified as parameters (if different from the default values).
Small edits for clarity
```suggestion
  running on :ref:`external workloads <external_workloads>`. If the cluster name
  and ID are different from the default values, you must specify them 
  as parameters.
```

2023-09-25 12:31 UTC, giorio94 commented
> @giorio94 Thanks for your patience. This is well-written and needs only some small tweaks for approval.

Thanks @zacharysarah for the feedback, I've applied your suggestion.

2023-09-25 12:31 UTC, giorio94 commented
/test

2023-09-25 13:37 UTC, zacharysarah approved these changes
LGTM

2023-09-25 16:08 UTC, merged