spawn sync_endpoint_header_file goroutine out of createEndpoint func
cilium/cilium pull request #27915
Opened 2023-09-04 09:18 UTC by sofat1989

Fixes: #27371

```release-note
bug fix: sync_endpoint_header_file goroutines leaked if creating endpoints is failed because of invalidDataError
```

2023-09-13 16:47 UTC, christarazi requested changes
Thanks for the PR!

The fix makes sense, but I think just moving the init of the DNS trigger after this [line](https://github.com/cilium/cilium/blob/7530fd701ab15258d57e3731ea91bbd4a1fcf795/pkg/endpointmanager/manager.go#L618).

2023-09-14 00:37 UTC, tommyp1ckles commented on daemon/cmd/endpoint.go
> +	ep.InitDNSHistoryTrigger()
If adding to the endpointmanager fails, should we still start this trigger?

2023-09-26 07:58 UTC, lmb commented
I’ve marked this PR as draft while you work through the feedback in the PR above. When you’re ready to continue with review & testing of the PR, please click “Ready for Review” at the bottom of the page.

2023-09-27 21:54 UTC, aanm commented
Hi @sofat1989 do you have an update on this issue?

2023-11-11 01:44 UTC, closed without merging

2024-03-13 10:02 UTC, sayboras commented
@sofat1989 friendly ping, not sure if you have any update or this is no longer the issue. Thanks.