v1.13 Backports 2023-09-04
cilium/cilium pull request #27925
Opened 2023-09-04 14:22 UTC by jibi

* [ ] #27656 (@pchaigno)
 * [ ] #27572 (@bimmlerd)
 * [ ] #27171 (@joestringer)
 * [ ] #27818 (@mhofstetter)
 * [ ] #27416 (@brb)
 * [ ] #27814 (@haiyuewa)
 * [ ] #27359 (@brb)
 * [ ] #27738 (@brb)
 * [ ] #27706 (@tklauser)
 * [ ] #27170 (@joestringer)
 * [ ] #27911 (@brb)
 * [ ] #27798 (@ti-mo)

PRs skipped due to conflicts:

 * #27831 (@tklauser)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 27656 27572 27171 27818 27416 27814 27359 27738 27706 27170 27911 27798; do contrib/backporting/set-labels.py $pr done 1.13; done
```
or with
```
make add-labels BRANCH=v1.13 ISSUES=27656,27572,27171,27818,27416,27814,27359,27738,27706,27170,27911,27798
```

2023-09-04 14:58 UTC, mhofstetter approved these changes

2023-09-04 15:41 UTC, jibi commented
> cilium-agent is failing in ci-e2e:
> 
> > 2023-09-04T14:33:42.564306864Z level=fatal msg="failed to start: daemon creation failed: failed to finalise LB initialization: Cannot retrieve eth1 link: Link not found" subsys=daemon
> 
> It's because https://github.com/cilium/cilium/blob/v1.13/contrib/scripts/kind.sh#L37 doesn't have `secondary-network` option which was introduced by #26338. Let's backport that PR to v1.13.

:+1: 

> Another thing is that CLI is at v0.15.3 :-(

should I tick renovate to bump v1.13 as well?

2023-09-04 15:46 UTC, brb commented
> should I tick renovate to bump v1.13 as well?

Yes, please.

2023-09-05 08:52 UTC, jibi commented
> > should I tick renovate to bump v1.13 as well?
> 
> Yes, please.

synced offline, dropped https://github.com/cilium/cilium/pull/27738 while we understand how to sort the cilium CLI situation

2023-09-05 08:52 UTC, jibi commented
/test-backport-1.13

2023-09-05 08:54 UTC, tklauser approved these changes
My change looks good, thanks.

> * [Fix propagation of namespace labels to CEP labels #27831](https://github.com/cilium/cilium/pull/27831) (@tklauser)
>   
>   * skipped as v1.13 has not been switched to resource[T] for CEP

~Will backport myself to v1.13 and v1.12.~ Not applicable, will remove corresponding backport labels.

2023-09-05 09:15 UTC, bimmlerd approved these changes
#27572 LGTM, thanks!

2023-09-05 10:44 UTC, qmonnet approved these changes
* https://github.com/cilium/cilium/pull/27798

Looks good and I tested the same commit locally to make sure it addresses the bug on 1.13 as well. Thanks for dealing with the conflict!

2023-09-05 12:21 UTC, jibi commented
/test-1.21-4.19

2023-09-05 14:21 UTC, jibi commented
/test-1.16-4.19

2023-09-05 14:21 UTC, jibi commented
/test-1.18-4.19

2023-09-05 14:21 UTC, jibi commented
/test-1.23-4.19

2023-09-05 14:22 UTC, jibi commented
/test-1.24-4.19

2023-09-05 14:22 UTC, jibi commented
/test-1.22-4.19

2023-09-05 15:33 UTC, pchaigno approved these changes
My PR looks good. Thanks!

2023-09-06 08:07 UTC, brb approved these changes
Thanks!

2023-09-06 16:40 UTC, joestringer approved these changes
:ship:

2023-09-06 16:42 UTC, joestringer commented on .github/actions/cilium-config/action.yml
> +    default: true
Does this line make sense? v1.13 doesn't have mTLS auth.

2023-09-06 16:53 UTC, jibi commented on .github/actions/cilium-config/action.yml
> +    default: true
I'll remove it :+1:

2023-09-06 21:03 UTC, qmonnet requested changes
Apologies, I just realised, regarding https://github.com/cilium/cilium/pull/27798: it depends on https://github.com/cilium/cilium/pull/27602, which was not marked for backports on 1.13 (I labelled it now). Is it possible to add it to this PR, please?

2023-09-07 06:46 UTC, jibi commented
> Apologies, I just realised, regarding #27798: it depends on #27602, which was not marked for backports on 1.13 (I labelled it now). Is it possible to add it to this PR, please?

@qmonnet there are a few conflicts and I see @julianwiedmann is already taking care of the v1.14 backport, so I'll let him handle also v1.13 (and drop #27798 for now)

2023-09-07 06:50 UTC, jibi commented
/test-backport-1.13

2023-09-07 09:10 UTC, qmonnet approved these changes

2023-09-07 09:34 UTC, jibi commented
/test-1.24-4.19

2023-09-07 10:24 UTC, youngnick approved these changes

2023-09-07 13:23 UTC, merged