v1.12 Backports 2023-09-04
cilium/cilium pull request #27934
Opened 2023-09-05 06:59 UTC by jibi

* [ ] #27656 (@pchaigno)
 * [ ] #27572 (@bimmlerd)
 * [ ] #27814 (@haiyuewa)
 * [ ] #27359 (@brb)
 * [ ] #27706 (@tklauser)
 * [ ] #27798 (@ti-mo)

PRs skipped due to conflicts:

 * #27831 (@tklauser)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 27656 27572 27814 27359 27706 27798; do contrib/backporting/set-labels.py $pr done 1.12; done
```
or with
```
make add-labels BRANCH=v1.12 ISSUES=27656,27572,27814,27359,27706,27798
```

2023-09-05 07:03 UTC, haiyuewa requested changes

2023-09-05 07:03 UTC, haiyuewa commented on Documentation/gettingstarted/servicemesh/grpc.rst
> +    $ curl -o demo.proto https://raw.githubusercontent.com/GoogleCloudPlatform/microservices-demo/main/pb/demo.proto
"main/pb" --> "main/protos"

2023-09-05 07:03 UTC, haiyuewa commented on Documentation/gettingstarted/servicemesh/tls-termination.rst
> +            $ curl -o demo.proto https://raw.githubusercontent.com/GoogleCloudPlatform/microservices-demo/main/pb/demo.proto
"main/pb" --> "main/protos"

2023-09-05 07:08 UTC, haiyuewa requested changes

2023-09-05 07:08 UTC, haiyuewa commented on Documentation/gettingstarted/servicemesh/grpc.rst
> +    $ curl -o demo.proto https://raw.githubusercontent.com/GoogleCloudPlatform/microservices-demo/main/proto/demo.proto
miss the "s", should be "main/protos"  : - )

2023-09-05 07:08 UTC, haiyuewa commented on Documentation/gettingstarted/servicemesh/tls-termination.rst
> +            $ curl -o demo.proto https://raw.githubusercontent.com/GoogleCloudPlatform/microservices-demo/main/proto/demo.proto
miss the "s", should be "main/protos"  : - )

2023-09-05 08:58 UTC, tklauser approved these changes
My change looks good, thanks.

> * [Fix propagation of namespace labels to CEP labels #27831](https://github.com/cilium/cilium/pull/27831) (@tklauser)

Not applicable for v1.12, I've removed the `need-backport/1.12` label.

2023-09-05 09:13 UTC, bimmlerd approved these changes
#27572 LGTM, thanks!

2023-09-05 10:41 UTC, qmonnet requested changes
- https://github.com/cilium/cilium/pull/27798

`lb4_extract_tuple()` does not exist on v1.12, making the commit broken. I'm currently looking at the 1.12 backport for this PR.

2023-09-05 11:45 UTC, jibi commented
> * [bpf: lxc: support Pod->Service->Pod hairpinning with endpoint routes #27798](https://github.com/cilium/cilium/pull/27798)
> 
> 
> `lb4_extract_tuple()` does not exist on v1.12, making the commit broken. I'm currently looking at the 1.12 backport for this PR.

ack, I'll drop the backport for now then :+1:

2023-09-05 12:10 UTC, jibi commented
/test-backport-1.12

2023-09-05 12:12 UTC, jibi commented
/test-backport-1.12

2023-09-05 13:10 UTC, haiyuewa approved these changes

2023-09-05 13:47 UTC, qmonnet approved these changes

2023-09-05 14:26 UTC, jibi commented
/test-runtime

2023-09-05 14:27 UTC, jibi commented
/test-1.23-4.19

2023-09-05 15:31 UTC, jibi commented
/test-1.17-4.9

2023-09-05 15:31 UTC, jibi commented
/test-1.21-4.9

2023-09-05 19:13 UTC, jibi commented
/test-1.17-4.9

2023-09-06 08:07 UTC, brb approved these changes
Thanks!

2023-09-06 18:17 UTC, joestringer approved these changes
Ack for @cilium/github-sec

2023-09-07 10:25 UTC, youngnick approved these changes

2023-09-07 10:29 UTC, merged