CFP: cilium ingress should have an option to set the number of trusted loadbalancer hops
cilium/cilium pull request #27952
Opened 2023-09-05 14:36 UTC by chaunceyjiang

1. Add a new global config item that sets the number of trusted hops for external load balancers for Ingress (or Gateway API) config. Default to 0, which produces the current behavior.
2. Plumb that value to the relevant Envoy configs so that it takes effect for all ingress listeners. (As opposed to Layer 7 policy enforcement listeners)

Fixes: #24292

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Fixes: #issue-number

```release-note
cilium ingress should have an option to set the number of trusted loadbalancer hops
```

2023-09-07 05:52 UTC, youngnick requested changes
Thanks for this PR @chaunceyjiang, the changes look good, but could you add some tests in `envoy_http_connection_manager_test.go` and `envoy_listener_test.go`? Just basic ones that ensure that the default is set correctly, and setting a separate value is also correct?

2023-09-07 08:20 UTC, chaunceyjiang commented
>  could you add some tests in envoy_http_connection_manager_test.go and envoy_listener_test.go? Just basic ones that ensure that the default is set correctly, and setting a separate value is also correct?

Hi @youngnick  Done.  PATL.  Thanks~

2023-09-11 12:52 UTC, meyskens commented
Assigned @youngnick here for sig-servicemesh as my work cycles on this area are currently limited

2023-09-11 13:03 UTC, chaunceyjiang commented
@meyskens Thanks~

2023-09-12 05:57 UTC, youngnick approved these changes

2023-09-13 09:17 UTC, chaunceyjiang commented
Hi @youngnick, could you help me with triggering E2E testing?

2023-09-13 15:34 UTC, chaunceyjiang commented
Hi, @joamaki Ready for review , Please take a look. Thanks~

2023-09-13 23:42 UTC, youngnick commented
/test

2023-09-14 08:13 UTC, chaunceyjiang commented
```
📋 Test Report
❌ 2/45 tests failed (2/288 actions), 10 tests skipped, 1 scenarios skipped:
Test [no-policies]:
  ❌ no-policies/pod-to-service/curl-2: cilium-test/client2-646b88fb9b-fms7m (10.0.1.220) -> cilium-test/echo-other-node (echo-other-node:8080)
Test [allow-all-except-world]:
  ❌ allow-all-except-world/pod-to-service/curl-2: cilium-test/client2-646b88fb9b-fms7m (10.0.1.220) -> cilium-test/echo-other-node (echo-other-node:8080)
Error: Process completed with exit code 1.

```

It seems GitHub is having troubles.

2023-09-18 14:22 UTC, chaunceyjiang commented
> /test ci-ipsec-upgrade

Thanks~ @youngnick It seems like this action has no effect.


<img width="421" alt="image" src="https://github.com/cilium/cilium/assets/17962021/b3f8913d-9221-456a-bd14-b6c70e2d102c">

2023-09-21 03:06 UTC, chaunceyjiang commented
Friendly ping @youngnick , Can you help me re-trigger the GitHub action again?

2023-09-26 08:31 UTC, lmb commented
I've triggered a run for you. Since the check is not marked as required we can merge without it being green. What's still missing is review from @joamaki

2023-10-04 10:53 UTC, joamaki approved these changes

2023-10-04 10:53 UTC, merged