Adds jobLabel helm options to serviceMonitor of cilium-agent, cilium-operator, and hubble components
cilium/cilium pull request #28125
Opened 2023-09-12 18:22 UTC by rbankston

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Adds optional configurable jobLabel to cilium-agent, cilium-operator, and hubble serviceMonitors
Defaults to disabled and without existence does not alter the helm template.

```release-note
Adds optional configurable jobLabel to cilium-agent, cilium-operator, and hubble serviceMonitors
```

2023-09-14 14:26 UTC, kaworu requested changes
Hi @rbankston, thanks for opening this PR!

Please add the jobLabel values to `install/kubernetes/cilium/values.yaml.tmpl` along with a doc comment above them, and then run `make -C install/kubernetes cilium/values.yaml && make -C Documentation update-helm-values`.

2023-09-18 07:11 UTC, rbankston commented
Hello @kaworu Thank you for that information. I've done those steps and squashed to a single commit.

2023-09-25 12:52 UTC, kaworu requested changes
Thanks for the update @rbankston

1. [Check patch is complaining](https://github.com/cilium/cilium/actions/runs/6219372438/job/16966716668?pr=28125) about the commit's long title, can you rephrase it under 75 characters? e.g. `helm: add jobLabel to cilium-{agent,operator} and hubble serviceMonitor`
2. Please run `make -C install/kubernetes` to make [Helm Check](https://github.com/cilium/cilium/actions/runs/6219372449/job/16966717974?pr=28125) happy
3. Please run `make -C Documentation update-helm-values` to make [Travis-CI](https://app.travis-ci.com/github/cilium/cilium/builds/265993840) happy
4. Finally, rebase on top of `main` and squash everything into a single commit :pray:

2023-09-25 12:52 UTC, kaworu commented on install/kubernetes/cilium/templates/cilium-agent/servicemonitor.yaml
> +  jobLabel: {{ .Values.prometheus.serviceMonitor.jobLabel }}
nit:
```suggestion
  jobLabel: {{ .Values.prometheus.serviceMonitor.jobLabel | quote }}
```

2023-09-25 12:52 UTC, kaworu commented on install/kubernetes/cilium/templates/cilium-operator/servicemonitor.yaml
> +  jobLabel: {{ .Values.operator.prometheus.serviceMonitor.jobLabel }}
ditto
```suggestion
  jobLabel: {{ .Values.operator.prometheus.serviceMonitor.jobLabel | quote }}
```

2023-09-25 12:52 UTC, kaworu commented on install/kubernetes/cilium/templates/hubble/servicemonitor.yaml
> +  jobLabel: {{ .Values.prometheus.serviceMonitor.jobLabel }}
ditto
```suggestion
  jobLabel: {{ .Values.prometheus.serviceMonitor.jobLabel | quote }}
```

2023-09-28 12:56 UTC, lambdanis requested changes
The helm change looks good, but some paperwork needs fixing as indicated by the CI failures.

https://github.com/cilium/cilium/actions/runs/6330260806/job/17216481041?pr=28125
```
  Warning: WARNING:BAD_SIGN_OFF: Duplicate signature
  #21: 
  Signed-off-by: Ralph Bankston <ralph.bankston@isovalent.com>

  "[PATCH] Adds jobLabel helm options to serviceMonitor of cilium-agent," has style problems, please review.

  Error: ERROR:CUSTOM: Please avoid long commit subjects (max: 75, found: 100)
  ```
There are two problems with the commit message:
* The body, including the signature, is duplicated
* The subject is too long

https://github.com/cilium/cilium/actions/runs/6330260793/job/17216485087?pr=28125
```
helm-values.rst:1452: : Spell check: jobLabel: jobLabel to add for ServiceMonitor hubble.
helm-values.rst:2384: : Spell check: jobLabel: jobLabel to add for ServiceMonitor cilium-operator.
helm-values.rst:2604: : Spell check: jobLabel: jobLabel to add for ServiceMonitor cilium-agent.
helm-values.rst:1452: : Spell check: jobLabel: jobLabel to add for ServiceMonitor hubble.
helm-values.rst:2384: : Spell check: jobLabel: jobLabel to add for ServiceMonitor cilium-operator.
helm-values.rst:2604: : Spell check: jobLabel: jobLabel to add for ServiceMonitor cilium-agent.

Please fix the following documentation warnings:
WARNING: Found 6 misspelled words
```
`jobLabel` needs to be added to `Documentation/spelling_wordlist.txt`.

2023-09-29 01:39 UTC, sayboras commented
Removed myself from reviewer list, as there is no more vendor change in this PR.

2023-09-30 03:56 UTC, tommyp1ckles approved these changes

2023-09-30 04:08 UTC, tommyp1ckles commented
@rbankston seems like a previous push caused a bunch of reviewers to be added (I assumed I had been asked to review for sig-k8s, which looks fine for me).

I think we just need the sig-k8s and sig-docs approval for these changes.

2023-10-04 08:55 UTC, lambdanis commented
/test

2023-10-04 08:55 UTC, lambdanis approved these changes
looks good

2023-10-04 14:52 UTC, kaworu requested changes
One question, other than that Helm changes LGTM.

2023-10-04 14:52 UTC, kaworu commented on install/kubernetes/cilium/templates/hubble/servicemonitor.yaml
> +  jobLabel: {{ .Values.prometheus.serviceMonitor.jobLabel | quote }}
did you meant
```suggestion
  jobLabel: {{ .Values.hubble.metrics.serviceMonitor.jobLabel | quote }}
```
instead?

2023-10-04 16:03 UTC, rbankston commented on install/kubernetes/cilium/templates/hubble/servicemonitor.yaml
> +  jobLabel: {{ .Values.prometheus.serviceMonitor.jobLabel | quote }}
I did and you should see it fixed and correct

2023-10-04 16:10 UTC, kaworu approved these changes

2023-10-06 07:01 UTC, joamaki approved these changes

2023-10-06 07:01 UTC, joamaki commented
/test

2023-10-06 12:56 UTC, merged