test/k8sT: skip default deny egress tests for kubernetes 1.7
cilium/cilium pull request #2817
Opened 2018-02-14 17:14 UTC by aanm

Since kubernetes 1.7 doesn't support default deny for ingress in 1.7 we
need to skip the test for that version.

Signed-off-by: André Martins <andre@cilium.io>

2018-02-14 17:15 UTC, aanm commented
test-nightly

2018-02-14 17:15 UTC, aanm commented
test-nightly

2018-02-14 22:06 UTC, aanm commented
test-me-please

2018-02-15 07:54 UTC, eloycoto requested changes

2018-02-15 07:54 UTC, eloycoto commented on test/k8sT/Policies.go
> +				Skip("K8s 1.7 doesn't offer a default deny for egress")
Could you do a return instead of `Skip`? If you do `Skip` the result in the JUnit will be "test skiped" and it's not real, part of the test runs.

2018-02-15 07:54 UTC, eloycoto commented on test/k8sT/Policies.go
> +				Skip("K8s 1.7 doesn't offer a default deny for egress")
return + log.Info please :-)

2018-02-15 12:05 UTC, aanm commented
test-nightly

2018-02-15 12:05 UTC, aanm commented
test-me-please

2018-02-15 12:06 UTC, aanm commented on test/k8sT/Policies.go
> +				Skip("K8s 1.7 doesn't offer a default deny for egress")
Done

2018-02-16 07:22 UTC, eloycoto commented
Hi @aanm this can be merged. Thanks for the work

2018-02-16 10:43 UTC, merged