endpointmanager: fix bpf policy pressure getting stuck.
cilium/cilium pull request #28185
Opened 2023-09-16 04:01 UTC by tommyp1ckles

Currently the policy map pressure metric only updates the map pressure metric when a new pressure value that is higher than the current one is set. This means that the metric can only ever go up, so when maps are shrunk (ex. such as after doing an cilium fqdn cache clean) the metric never goes down.

This changes the behavior of the metric to maintain a map of map pressure values. When the trigger is invoked, it iterates all values and finds the max - updating the map_pressure gauge for policymaps to the max value. Endpoints that are shut down have their values removed.

2023-09-18 08:59 UTC, christarazi requested changes
Thanks for the fix! Just one comment.

2023-09-18 08:59 UTC, christarazi commented on pkg/endpoint/endpoint.go
> +func (e *Endpoint) CloseMetrics() {
Where is this called?

2023-09-25 03:29 UTC, tommyp1ckles commented
/test

2023-09-25 14:04 UTC, tommyp1ckles commented
/test

2023-09-26 03:43 UTC, tommyp1ckles commented
/test

2023-09-28 00:32 UTC, christarazi approved these changes

2023-09-28 00:32 UTC, christarazi commented on pkg/endpointmanager/policymap_pressure.go
> +	"golang.org/x/exp/maps"
Nit: This 3rd party import should be in the section before the Cilium imports

2023-10-30 17:55 UTC, christarazi commented
Let's get this PR over the finish line @tommyp1ckles, it's basically there. Just some Go linter errors to fix up.

2023-10-31 04:31 UTC, tommyp1ckles commented
@christarazi woops yeah forgot about this one, let me get it ready

2023-10-31 04:40 UTC, tommyp1ckles commented
/test

2023-10-31 06:11 UTC, tommyp1ckles commented
/test

2023-11-01 06:44 UTC, merged