Docs: Updates L2 Announce for LB Class Support
cilium/cilium pull request #28252
Opened 2023-09-22 15:43 UTC by danehans

Updates L2 announcer docs for [load balancer class](https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class) support.

Fixes: #28236

2023-09-22 16:58 UTC, dylandreimerink approved these changes

2023-09-27 20:37 UTC, learnitall requested changes
One small nit on formatting, but otherwise LGTM.

2023-09-27 20:37 UTC, learnitall commented on Documentation/network/l2-announcements.rst
> +unspecified or set to "io.cilium/l2-announcer" to be selected by a policy for announcement.
```suggestion
unspecified or set to ``io.cilium/l2-announcer`` to be selected by a policy for announcement.
```

2023-09-27 20:43 UTC, danehans commented on Documentation/network/l2-announcements.rst
> +unspecified or set to "io.cilium/l2-announcer" to be selected by a policy for announcement.
Commit 77d0747 resolves this comment.

2023-09-28 20:42 UTC, learnitall approved these changes

2023-10-06 20:53 UTC, danehans commented
@dylandreimerink @learnitall do you have any suggetions for getting this PR merged?

2023-10-09 14:47 UTC, learnitall commented
Hey @danehans I'll mark this `ready-to-merge` so it'll get picked up.

Docs-only change, full test suite is not required and all other tests are green. Marking ready to merge.

2023-10-10 08:34 UTC, merged