BPF Host Routing: do not skip fib lookups
cilium/cilium pull request #28264
Opened 2023-09-25 15:47 UTC by aspsk

See the commit message.

Fixes: #27343

```release-note
Do not skip FIB lookup when running in BPF Host Routing when Endpoint Routes enabled
```

2023-09-25 15:48 UTC, aspsk commented
This patch removes the `ENABLE_SKIP_FIB` completely. Won't it be useful to have a flag to enable it for setups when only one interface is present? (cc: @julianwiedmann)

2023-09-25 15:50 UTC, aspsk commented
/test

2023-09-25 16:27 UTC, aspsk commented
/test

2023-09-26 12:13 UTC, lmb approved these changes
config change seems fine to me. No idea whether ENABLE_SKIP_FIB is great or not, but I'm all for reducing the number of code paths we have. Unless we have a strong indication that it's hurtful I'd say go for it!

2023-09-26 13:34 UTC, julianwiedmann commented
Ripping out `ENABLE_SKIP_FIB` completely feels like a *very* big hammer. And for instance also impacts unrelated areas like N/S LB forwarding to remote backends.

Is there no way to only exclude `ENABLE_SKIP_FIB` for the regressing config? Or even teach the problematic FIB lookup path (in bpf_lxc) to ignore `ENABLE_SKIP_FIB` ?

2023-09-26 14:44 UTC, aspsk commented
> Is there no way to only exclude `ENABLE_SKIP_FIB` for the regressing config?

The config can be described as follows: `no tunnel & there are interfaces not controlled by cilium`, so I am not sure how to automate this decision. We currently experience this only on EKS, as far as we know, but this is, of course, applicable to any config as defined above.

So, does this work if we only undef `ENABLE_SKIP_FIB` for lxc, and leave it as is for other callers?

2023-09-27 11:06 UTC, aspsk commented
> So, does this work if we only undef `ENABLE_SKIP_FIB` for lxc, and leave it as is for other callers?

For this specific case I can do a check like this (and only apply to lxc, not host so that nodeport is not affected):
```
option.Config.IPAM == ipamOption.IPAMENI
```
Then if we have more cases like this, we can add an option or extend the check. WDYT @julianwiedmann

2023-09-27 16:27 UTC, aspsk commented
I've posted a new version which only disables this on EKS. Tested that this actually works.

2023-09-28 06:53 UTC, aspsk commented
/test

2023-09-28 14:01 UTC, lmb requested changes

2023-09-28 14:01 UTC, lmb commented on pkg/datapath/linux/config/config.go
> +func enforceFibLookup(e datapath.EndpointConfiguration) bool {
Could you put this on the type of `option.Config` instead? Then we wouldn't add another dependency on the global variable.

2023-09-29 09:20 UTC, borkmann commented
Would this situation be prevented if we had proper device detection at runtime, so that Cilium considers multiple devices when they get automatically added on EKS and therefore it needs to turn it off automatically when number grows from 1 to 2+? Cc @joamaki

2023-09-29 11:05 UTC, joamaki commented
> Would this situation be prevented if we had proper device detection at runtime, so that Cilium considers multiple devices when they get automatically added on EKS and therefore it needs to turn it off automatically when number grows from 1 to 2+? Cc @joamaki

Yep, I'd expect with runtime device detection enabled we wouldn't need this workaround (as then we'd reload if we get more devices at runtime). @bimmlerd and I are working on enabling it by default for v1.15. I would still go ahead with this fix (and backport it) and then remove it once it's no longer needed.

2023-09-29 11:20 UTC, bimmlerd commented
@aspsk this doesn't look like a backport to v1.14. Did you mean to add the `needs-backport/v1.14` label instead of `backport/v1.14`?

2023-09-29 11:48 UTC, aspsk commented
> Yep, I'd expect with runtime device detection enabled we wouldn't need this workaround

Yes, enabling the runtime device detection is the right way to do this, but the original report was that "this configuration worked, but not anymore" where the runtime detection is off.

Should we only apply this patch to `.14` and enable runtime detection in `.15` an later?

2023-09-29 13:05 UTC, borkmann commented
> > Yep, I'd expect with runtime device detection enabled we wouldn't need this workaround
> 
> Yes, enabling the runtime device detection is the right way to do this, but the original report was that "this configuration worked, but not anymore" where the runtime detection is off.
> 
> Should we only apply this patch to `.14` and enable runtime detection in `.15` an later?

I think that could be an option as long as we have a release blocker label to ensure the dev detection lands in time.

2023-10-03 09:27 UTC, julianwiedmann commented
> > So, does this work if we only undef `ENABLE_SKIP_FIB` for lxc, and leave it as is for other callers?
> 
> For this specific case I can do a check like this (and only apply to lxc, not host so that nodeport is not affected):
> 
> ```
> option.Config.IPAM == ipamOption.IPAMENI
> ```
> 
> Then if we have more cases like this, we can add an option or extend the check. WDYT @julianwiedmann

Sorry, was mostly afk last week.

Yep, that looks good on first glance :+1:. But instead of `ipamOption.IPAMENI`, shouldn't we check for `option.Config.EnableEndpointRoutes`  ?

2023-10-04 08:35 UTC, julianwiedmann approved these changes
Looks good, thank you! But could you please update the commit msg & release notes? :pray: 

@margamanterola maybe you want to confirm that this fixes the issue from https://github.com/cilium/cilium/issues/27343 ?

2023-10-04 15:53 UTC, margamanterola commented
For the release note, it should cover the symptoms/effects rather than the implementation. Is "Route packets to the correct interface when using BPF Host Routing on EKS" a good description of the outcome of this change?

I've destroyed the environment that I was using to test this, but I'll spin it up again and test this PR there.

2023-10-04 16:34 UTC, lmb approved these changes
Thanks :)

2023-10-05 17:35 UTC, derailed commented on pkg/option/config.go
> +	// since v1.14.0-snapshot.2. We will remove this hack later, once we
Wondering if we get tag these somehow so we can `grep out` the debt in the future?

2023-10-05 17:55 UTC, derailed approved these changes
@aspsk Nice work!

2023-11-07 08:26 UTC, sylr commented
Can this be merged ?

2023-11-07 10:48 UTC, aspsk commented
/test

2023-11-08 12:33 UTC, aspsk commented
/test

2023-11-10 09:38 UTC, merged