bgpv1: set R-bit in graceful restart
cilium/cilium pull request #28293
Opened 2023-09-26 15:58 UTC by ArsenyBelorukov

Set R-bit in graceful restart negotiation to not withdraw routes by Receiving Speaker Details is in https://www.rfc-editor.org/rfc/rfc4724.html#section-4.1

Fixes: #28168

```release-note
BGPv1: Set R-bit in graceful restart capability negotiation.
```

2023-09-27 13:55 UTC, harsimran-pabla approved these changes

2023-10-02 09:41 UTC, lmb commented
/test

2023-10-02 19:28 UTC, danehans commented
/ci-clustermesh

2023-10-02 19:36 UTC, danehans commented
/lgtm

As a side note, It's probably a good idea to add a UT for `getPeerConfig()` in a separate issue/PR so we have coverage here. @harsimran-pabla if you agree, I can create the issue to track.

2023-10-02 19:43 UTC, harsimran-pabla commented
@danehans  yes please feel free to do it. 

getPeerConfig is getting quite large and it would be good to set a baseline in unit test.

2023-10-02 22:09 UTC, danehans commented
xref: https://github.com/cilium/cilium/issues/28363

2023-10-05 08:58 UTC, YutaroHayakawa approved these changes
LGTM

2023-10-06 01:00 UTC, YutaroHayakawa requested changes
@ArsenyBelorukov The change looks good. Please fix the issue of Check Patch workflow (Signed-off-by is missing). You should commit the change with `git commit -s` option. You can fix your current commit and force push it.

2023-10-20 21:54 UTC, joestringer commented
It looks like the author and signoff emails for the commit are slightly off, but I think it's fair to assume that these represent aliases for the same person.

2023-10-20 21:54 UTC, merged

2024-02-20 13:21 UTC, julianwiedmann commented
Backport landed via https://github.com/cilium/cilium/pull/30793.