datapath/loader: attach xdp progs with bpf_link
cilium/cilium pull request #28308
Opened 2023-09-27 14:32 UTC by rgo3

datapath/loader: Fix bug in obsolete xdp removal:
```
This commit fixes a bug where cilium expects certain netlink flags to be
set to specific values regarding the mode a xdp program was attached
while those flags get translated into a differenct struct field. It also
adds a respective regression test.
```

datapath/loader: attach xdp progs with bpf_link:
```
This extends the loader to utilize bpf_link to attach XDP programs if
supported by the kernel. To avoid connectivity issues when upgrading the
new code will not upgrade to using bpf_link if previous cilium versions
attached XDP programs via netlink. This is akin to the behaviour and
upgrade logic of the cgroup attachements for bpf_sock.
```

Fixes: #27630

2023-09-27 14:39 UTC, rgo3 commented
/test

2023-09-28 11:10 UTC, rgo3 commented
/test

2023-10-04 17:37 UTC, rgo3 commented
/test

2023-10-10 10:28 UTC, rgo3 commented
/test

2023-10-10 10:29 UTC, rgo3 commented
After the offline code walk with @ti-mo and @lmb last week I'll move this into ready for review.

I've left 2 TODO's open intentionally to be discussed during review, most important probably being the decision around the bpffs linkpath we choose to store pins.

I think that there is a possibility to backport this entire PR (the fix to `maybeUnloadObsoleteXDPPrograms` and the new xdp link code) as that would solve the removing links and their respective bpffs pins when downgrading. If we don't want to backport all of it we should discuss what needs to be backported instead.

2023-10-20 18:28 UTC, asauber requested changes
Reviewed for Config and CLI. Didn't review the attach/detach logic.

2023-10-20 18:28 UTC, asauber commented on pkg/datapath/loader/netlink_test.go
> +	// TODO(rgo3): remove or fix test
Given the tests added in this PR, my vote would be to remove this.

2023-10-20 18:28 UTC, asauber commented on pkg/datapath/loader/xdp.go
> +	return filepath.Join(bpf.CiliumPath(), "loader", "links/xdp") // TODO(rgo3): not sure if we want that exact path, also relevant for cilium cleanup command
For now, these strings should at least be `const`s

2023-10-20 18:28 UTC, asauber commented on cilium/cmd/cleanup.go
> +		err = os.Remove(filepath.Join(bpf.CiliumPath(), "loader", "links/xdp", link.Attrs().Name))
Declared `const`s can be used here rather than string literals.

2023-11-06 22:14 UTC, asauber approved these changes

2023-11-09 13:02 UTC, ti-mo commented
@cilium/tophat Sorry for the noise, you got pinged because pkg/socketlb didn't have a codeowner. I assigned one now.

2023-11-09 14:50 UTC, bimmlerd approved these changes
CODEOWNERS change LGTM

2023-11-09 15:34 UTC, ti-mo approved these changes

2023-11-09 18:56 UTC, squeed approved these changes

2023-11-10 10:39 UTC, dylandreimerink approved these changes
LGTM!

2023-11-10 13:15 UTC, merged

2024-04-02 05:58 UTC, julianwiedmann commented
> The first two commits (prog removal and xdp bpf_link cleanup) will be submitted as a separate PR for backporting to 1.14 and 1.13 so these versions can handle downgrades from bpf_link-enabled Cilium agents.

@rgo3 If I see things correctly, this happened with https://github.com/cilium/cilium/pull/29105 and https://github.com/cilium/cilium/pull/29104. So the `needs-backport` for those two releases is actually complete?

2024-04-02 06:06 UTC, rgo3 commented
Yes, we forgot to update the labels unfortunately :disappointed: