ipsec: New Prometheus metrics for XFRM configs
cilium/cilium pull request #28400
Opened 2023-10-04 10:57 UTC by pchaigno

2023-10-04 11:21 UTC, pchaigno commented
/test

2023-10-04 11:29 UTC, zacharysarah approved these changes
@pchaigno Good work.

2023-10-05 10:08 UTC, ti-mo requested changes

2023-10-05 10:08 UTC, ti-mo commented on pkg/common/ipsec/utils_test.go
Why add new tests using `checkmate`? We should make these `testing.T` instead.

2023-10-06 08:46 UTC, pchaigno commented on pkg/common/ipsec/utils_test.go
Because I didn't know about the switch.

2023-10-06 08:47 UTC, pchaigno commented
/test

2023-10-06 11:20 UTC, pchaigno commented
/test

2023-10-06 13:47 UTC, ti-mo approved these changes

2023-10-06 14:53 UTC, gentoo-root approved these changes
Looks good to me.

2023-10-06 14:53 UTC, gentoo-root commented on pkg/common/ipsec/utils_test.go
> +		Mark: &netlink.XfrmMark{
Nit: looks like it could be part of the first commit.

2023-10-06 14:56 UTC, pchaigno commented on pkg/common/ipsec/utils_test.go
> +		Mark: &netlink.XfrmMark{
It's not needed until this third commit, which is why I didn't include it in the first. If we were to revert the third and fourth commit later, I'd want this to be removed as well.

2023-10-06 15:10 UTC, gentoo-root commented on pkg/common/ipsec/utils_test.go
> +		Mark: &netlink.XfrmMark{
> If we were to revert the third and fourth commits later,

There would remain an unused parameter which could be misleading.

2023-10-06 16:28 UTC, pchaigno commented on pkg/common/ipsec/utils_test.go
> +		Mark: &netlink.XfrmMark{
Yep, exactly.

2023-10-06 16:34 UTC, pchaigno commented
/test

2023-10-09 08:55 UTC, pchaigno commented
/test

2023-10-17 09:43 UTC, pchaigno commented
@squeed Note we don't receive notifications when labels are changed. Might be worth leaving a comment in that case :slightly_smiling_face:

2023-10-17 14:52 UTC, nathanjsweet approved these changes

2023-10-17 21:20 UTC, joestringer commented
Why was the `ready-to-merge` label manually set when this is a metrics PR and the @cilium/metrics codeowner hasn't approved the PR?

2023-10-18 09:14 UTC, pchaigno commented
@joestringer Because the author is tired of tracking down reviewers.

2023-10-18 14:47 UTC, chancez approved these changes
It seems like these should be separate metrics rather than one metric with a bunch of different labels, but this seems to be the already established pattern for these metrics, so I'm not going to block on that, but I would encourage considering an approach using separate metrics. 

Reasoning: usually you use labels for different dimensions of a given metric, and you can aggregate over the dimensions in a meaningful way. Given that each of these labels represents different "statistics", you can't really meaningfully aggregate them, which is why I suggest that they are broken apart into separate metrics instead.

Again, non-blocking because your following existing conventions, but it might be good to create a follow up to revisit these xfrm metrics as a whole.

2023-10-19 05:55 UTC, tommyp1ckles approved these changes
Changes look good, sorry for the delay - was on PTO.

2023-10-19 05:55 UTC, tommyp1ckles commented on pkg/datapath/linux/ipsec/xfrm_collector.go
> +		log.WithError(err).Error("Error while getting XFRM states")
nit: would it better to return the error here and log at the collect level with some context of what the outcome of this error is.

2023-10-19 05:55 UTC, tommyp1ckles commented on pkg/datapath/linux/ipsec/xfrm_collector.go
> +		log.WithError(err).Error("Error while getting XFRM policies")
Same question here, would be nice to know that this only affect metrics

2023-10-19 10:42 UTC, pchaigno commented
> Reasoning: usually you use labels for different dimensions of a given metric, and you can aggregate over the dimensions in a meaningful way.

Makes sense. I've split the metrics for XFRM states and policies.

2023-10-19 10:43 UTC, pchaigno commented
/test

2023-10-19 21:19 UTC, merged