Update docs theme
cilium/cilium pull request #28403
Opened 2023-10-04 17:24 UTC by raphink

Signed-off-by: Raphaël Pinson <raphael@isovalent.com>

2023-10-04 17:35 UTC, qmonnet approved these changes

2023-10-04 17:36 UTC, qmonnet commented
Netlify says:
![image](https://github.com/cilium/cilium/assets/17001771/e7bc2781-0b20-49bb-9227-cee97657de81)

2023-10-04 17:38 UTC, qmonnet requested changes
I forgot that the branch had to be opened in the Cilium repo to have the automated update with the new `docs-builder` image in the PR. I'll update manually tomorrow.

2023-10-05 08:27 UTC, qmonnet commented
/test

2023-10-05 08:29 UTC, qmonnet approved these changes

2023-10-05 12:32 UTC, brlbil approved these changes

2023-10-06 10:29 UTC, merged