Fix agent dashboard ConfigMap
cilium/cilium pull request #28542
Opened 2023-10-11 19:02 UTC by bakito

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

This PR fixes the rendering of the cilium agent dashboard ConfigMap if enabled.
```
sashboards:
  enabled: true
```

```release-note

Fix Helm Chart Agent Dashboard ConfigMap rendering
```

2023-10-13 10:41 UTC, squeed approved these changes

2023-10-13 10:41 UTC, squeed commented
Good catch :-)

2023-10-13 10:42 UTC, squeed commented
Can you please write a more descriptive release-node entry? Then we can merge this.

2023-10-13 10:45 UTC, squeed requested changes
Two requests:
- Please write a more descriptive release-note. Include a short summary of what went wrong
- Add a "Fixes: (commit id") line in the commit message, pointing to the commit that introduced the bug. This makes it easier to "follow the chain". Thanks!

2023-10-15 05:56 UTC, bakito commented
> Two requests:
> 
> * Please write a more descriptive release-note. Include a short summary of what went wrong
> * Add a "Fixes: (commit id") line in the commit message, pointing to the commit that introduced the bug. This makes it easier to "follow the chain". Thanks!

@squeed I changed it. Is it OK like this?

2023-10-23 11:31 UTC, squeed commented
@bakito Sorry, I wasn't specific enough -- the "fixes: xxxx" should be in the commit message (i.e. not the first line). Then GitHub automatically parses it and we can follow bugs up the chain. Fix that and we can merge this :-)

2023-10-23 12:02 UTC, bakito commented
> @bakito Sorry, I wasn't specific enough -- the "fixes: xxxx" should be in the commit message (i.e. not the first line). Then GitHub automatically parses it and we can follow bugs up the chain. Fix that and we can merge this :-)

@squeed sorry for that, I didn't know this feature.

2023-10-23 12:25 UTC, squeed approved these changes

2023-10-31 09:07 UTC, aanm commented
/test

2023-10-31 10:18 UTC, merged