docs: Updating Azure CNI chaining as Legacy approach
cilium/cilium pull request #28571
Opened 2023-10-12 18:38 UTC by vipul-21

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

This PR depends on the doc PR: https://github.com/cilium/cilium/pull/27199
Fixes: https://github.com/cilium/cilium/issues/27289

2023-10-16 19:48 UTC, tamilmani1989 approved these changes

2023-10-17 22:09 UTC, vipul-21 commented
Depends on this PR changes: https://github.com/cilium/cilium/pull/28286

2023-10-18 06:20 UTC, tommyp1ckles approved these changes

2023-10-18 06:20 UTC, tommyp1ckles commented on Documentation/installation/cni-chaining-azure-cni.rst
> +   in a chaining configuration which is the legacy way of running Azure CNI with
nit: seems like this could be two sentences ... i.e. in chaining configuration.  This is the legacy way...

2023-10-18 09:11 UTC, qmonnet requested changes

2023-10-18 09:11 UTC, qmonnet commented on Documentation/installation/cni-chaining-azure-cni.rst
> +   The best way to run cilium on AKS is through :ref:`aks_install` or `Azure CNI Powered by Cilium <https://aka.ms/aks/cilium-dataplane>`_.
Nit: please wrap the line.

```suggestion
   The best way to run cilium on AKS is through :ref:`aks_install` or
   `Azure CNI Powered by Cilium <https://aka.ms/aks/cilium-dataplane>`__.
```

2023-10-18 09:11 UTC, qmonnet commented on Documentation/installation/cni-chaining-azure-cni.rst
> +   cilium as Azure IPAM is legacy, more info :ref:`ipam_azure`.
```suggestion
   cilium as Azure IPAM is legacy, for more information see :ref:`ipam_azure`.
```

2023-10-24 08:40 UTC, nbusseneau commented
I am switching PRs related to #27289 to draft so that I have a chance to review them cohesively since they're all out at the same time and are all supposed to work together.

2024-01-10 10:01 UTC, dylandreimerink commented
@vipul-21 CI seems to have had a bad day last time checking the PR, I suggest doing a rebase against main to re-trigger the CI so that the PR might proceed.

2024-01-10 17:53 UTC, qmonnet approved these changes

2024-01-17 21:18 UTC, vipul-21 commented
Can we merge this PR ? @tommyp1ckles @qmonnet

2024-01-18 09:46 UTC, qmonnet commented
/test

2024-01-18 09:51 UTC, qmonnet commented
> Can we merge this PR ?

The PR is still waiting for a review from Nicolas, who wanted to take a look, but I understand he's out for some time. The change is small enough that I think we're good to go without his ACK, though.

One question before we merge, I see the following:

> This PR depends on the doc PR: https://github.com/cilium/cilium/pull/27199

What's the status on that?

2024-01-23 11:19 UTC, squeed commented
I see that #27199, listed as a dependency, has been closed instead of merged. Does this PR still rely on that? If I can merge this.

2024-01-23 18:16 UTC, vipul-21 commented
@squeed Removed the dependency as this PR can be merged now. Thanks !

2024-01-25 14:37 UTC, merged