checkpatch: Fix on mac, arm64
cilium/cilium pull request #28586
Opened 2023-10-13 09:28 UTC by jrajahalme

Bump checkpatch to a multiarch image, remove user:group mapping on macOS to allow it to run properly.

Add a top level make target for convenience.

Docker desktop on macOS maps user id:gruop on file operations transparently, so that container can run as "root" without having root privileges on the host. This causes two problems when user and group are mapped to be the same in the container as they are in the host:

1. git does not work:

	fatal: detected dubious ownership in repository at '/workspace'
	To add an exception for this directory, call:

		git config --global --add safe.directory /workspace

2. checkpatch.pl can not be run:

	/checkpatch/checkpatch.sh: line 282: /checkpatch/checkpatch.pl: Permission denied

Both of these problems are resolved, if the '--user' parameter is omitted on macOS.

2023-10-13 09:35 UTC, jrajahalme commented
Oh well, now this image has the same permissions error on Linux:
```
/checkpatch/checkpatch.sh: line 160: /checkpatch/checkpatch.pl: Permission denied
```
Will try to omit the user also on Linux to see it it helps...

2023-10-13 11:05 UTC, gentoo-root requested changes

2023-10-13 11:05 UTC, gentoo-root commented on Makefile
> +	$(MAKE) -C bpf checkpatch
Could you make this change in a separate commit? If the patch gets reverted due to some bug, we'd want to keep this change, it's good on its own.

2023-10-13 11:05 UTC, gentoo-root commented on bpf/Makefile.bpf
> +CONTAINER_USER=
Yes, this should work on macOS. Docker for mac will map file permissions so that the files owned by the host user become owned by root in the container, and checkpatch also runs as root.

However, if [this comment](https://github.com/docker/for-mac/issues/2657#issuecomment-371210749) is still true, it's still unclear why it doesn't work with a non-root container user, since docker is supposed to map file permissions in this case as well. Do you have any com.docker.owner xattrs on your files by any chance? They could override the default behavior.

I'm asking because I'm looking for a way to avoid handling macOS and Linux differently. If it's a dead end, though, your approach looks valid to me.

2023-10-13 11:05 UTC, gentoo-root commented on bpf/Makefile.bpf
> +CHECKPATCH_IMAGE = quay.io/cilium/cilium-checkpatch:a8f73eced11c29d8c5003ba75071fb9ff91251e4@sha256:9fba31c924b0e675ee45dada3788ded045cd63c979fae3cddcb08636ed2e00da
> The old image is retained on non-macOS as it introduces the problem (2
below) when run as non-root user.

The problem is because checkpatch.pl has 744 permissions in the new image while it had 755 in the old one. I think we should better fix it in the image itself (make it 755 again) and upgrade on both Linux and macOS.

2023-11-01 09:00 UTC, jrajahalme commented on bpf/Makefile.bpf
> +CONTAINER_USER=
No xattrs, as verified by:

```
% xattr -l -r .
./.DS_Store: com.apple.FinderInfo:         @
```

My Docker Desktop uses Virtualization framework/VirtioFS file sharing, which I believe is the new default.

[This issue](https://github.com/docker/for-mac/issues/6243) on VirtioFS may be related.

2023-12-16 01:45 UTC, closed without merging