doc: Update Azure Ipam to Legacy
cilium/cilium pull request #28685
Opened 2023-10-18 18:01 UTC by tamilmani1989

Update Azure Ipam to Legacy and add recommended ways to install cilium on AKS

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #27289 

```release-note

```

2023-10-18 21:18 UTC, qmonnet requested changes
Looks good beside one minor suggestion

2023-10-18 21:18 UTC, qmonnet commented on Documentation/network/concepts/ipam/azure.rst
> +   While still maintained for now, Azure IPAM is considered legacy. The recommended way to install cilium on AKS is
Nit - There are two ways

```suggestion
   While still maintained for now, Azure IPAM is considered legacy.
   The recommended ways to install cilium on AKS are 
```

2023-10-19 06:11 UTC, tommyp1ckles approved these changes

2023-10-20 09:14 UTC, qmonnet reviewed
Thanks for the change, can you please squash the two commits together and drop the `Co-authored-by:` tag (or use my work email instead of personal one that GitHub autofilled)?

2023-10-24 08:40 UTC, nbusseneau commented
I am switching PRs related to #27289 to draft so that I have a chance to review them cohesively since they're all out at the same time and are all supposed to work together.

2023-12-04 20:42 UTC, joestringer commented
This PR seems to already be superseded by https://github.com/cilium/cilium/pull/28910 , should we close this one?

2023-12-12 23:12 UTC, tamilmani1989 commented
closing as similar PR exists https://github.com/cilium/cilium/pull/28910

2023-12-12 23:12 UTC, closed without merging