Add runtime test for multiple `--type` in `cilium monitor`
cilium/cilium pull request #2871
Opened 2018-02-19 15:12 UTC by nebril

Had this test in a superseded PR, salvaged it so we check if this option actually work.

2018-02-19 15:13 UTC, nebril commented
test-me-please

2018-02-19 16:34 UTC, ianvernon approved these changes

2018-02-19 17:47 UTC, eloycoto requested changes

2018-02-19 17:47 UTC, eloycoto commented on test/runtime/monitor.go
> +		By(fmt.Sprintf("all types together"))
I would remove `fmt.Sprintf` here

2018-02-19 17:47 UTC, eloycoto commented on test/runtime/monitor.go
> +		vm.SampleContainersActions(helpers.Delete, helpers.CiliumDockerNetwork)
You don't need to do this here. In fact is a bad practice, all the cleanups should happen after `vm.ReportFailed`

2018-02-20 09:46 UTC, nebril commented
test-me-please

2018-02-20 10:04 UTC, nebril commented
@eloycoto thanks, fixed

2018-02-20 14:32 UTC, eloycoto commented
test-me-please

2018-02-20 14:33 UTC, eloycoto approved these changes

2018-02-21 06:48 UTC, merged