Modularize scale-test
cilium/cilium pull request #28760
Opened 2023-10-24 14:04 UTC by marseel

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note

```

2023-10-26 12:36 UTC, marseel commented
Successful run: https://github.com/cilium/cilium/actions/runs/6627684165/job/18003120946

2023-10-27 14:35 UTC, learnitall requested changes
After looking through this, I think it might be a good idea if we just make one large action that can be consumed, rather than splitting out each step into its own action. For instance, if we were to add another workflow that runs a different scale test, we would essentially copy and paste the node-throughput test and just edit the CL2 config and number of nodes. I'm not sure what the use case would be for consuming the smaller actions on their own. WDYT?

Besides that, I have a couple of small nits.

2023-10-27 14:35 UTC, learnitall commented on .github/actions/scale-tests/create-cluster/action.yaml
> +    - name: Check if we should build the Cilium CLI from source
I think the name for this step is incorrect?

2023-10-27 14:35 UTC, learnitall commented on .github/actions/scale-tests/export-results/action.yaml
> +    - name: Delete cluster
I think the name for this step is incorrect here too.

2023-10-27 14:35 UTC, learnitall commented on .github/actions/scale-tests/install-kops/action.yaml
> +    - name: Delete cluster
This step name seems off also.

2023-10-27 14:35 UTC, learnitall commented on .github/actions/scale-tests/validate-cluster/action.yaml
> +description: "Workflow that wait for cluster to be in a ready state"
```suggestion
description: "Workflow that waits for cluster to be in a ready state"
```

2023-10-27 14:35 UTC, learnitall commented on .github/workflows/scale-test-gce.yaml
> +  cluster_name: ${{ github.run_id }}-${{ github.run_attempt }}.k8s.local
Can you switch these two lines? I think the `cluster_name` should be directly underneath the comment about k8s.local.

2023-10-27 14:35 UTC, learnitall commented on .github/actions/scale-tests/validate-cluster/action.yaml
> +          --wait 20m \
Nit: this timeout value is hard coded, but a user could specify a longer timeout when consuming the workflow through the GHA option `timeout-minutes`.

2023-10-27 14:35 UTC, learnitall commented on .github/workflows/scale-test-gce.yaml
> +name: Node throughput test
Maybe it would make sense to also rename the file?

2023-11-20 12:09 UTC, closed without merging