gateway-api: Bump the version to v1.0.0
cilium/cilium pull request #28836
Opened 2023-10-27 14:13 UTC by sayboras

### Description

Please refer to individual commit for more details. This is to prepare for v1.0.0 next week.

2023-10-27 14:14 UTC, sayboras commented
/ci-gateway-api

2023-10-28 09:37 UTC, sayboras commented
/test

2023-11-01 10:29 UTC, sayboras commented
/test

2023-11-01 10:31 UTC, sayboras commented
/test

2023-11-01 11:27 UTC, sayboras commented
/ci-gateway-api

2023-11-01 11:59 UTC, sayboras commented
/test

2023-11-01 13:10 UTC, rolinh approved these changes
Vendor changes lgtm

2023-11-01 23:01 UTC, learnitall requested changes
I found one typo, and I think there needs to be one more change in Documentation/network/servicemesh/gateway-api/gateway-api.rst` on line 53? 

```
More examples can be found in the `upstream repository <https://github.com/kubernetes-sigs/gateway-api/tree/v0.8.1/examples/standard>`_.
```

Otherwise LGTM!

2023-11-01 23:01 UTC, learnitall commented on Documentation/operations/upgrade.rst
> +* If you are using Gateway API, please make sure that that new v1 CRDs are installed.
I think there's a duplicate `that` here.

```suggestion
* If you are using Gateway API, please make sure that new v1 CRDs are installed.
```

2023-11-02 10:39 UTC, meyskens approved these changes
Technical changes look good :)

2023-11-02 13:54 UTC, brlbil approved these changes
CI changes lgtm.

2023-11-03 05:13 UTC, sayboras commented on Documentation/operations/upgrade.rst
> +* If you are using Gateway API, please make sure that that new v1 CRDs are installed.
thanks a lot :+1:

2023-11-03 05:17 UTC, sayboras commented
/test

2023-11-03 05:20 UTC, sayboras commented
/test

2023-11-03 07:29 UTC, sayboras commented
/test

2023-11-03 09:55 UTC, sayboras commented
/test

2023-11-03 20:48 UTC, learnitall approved these changes
Thanks!

2023-11-03 23:25 UTC, merged