hubble: Add Support for filtering on HTTP headers
cilium/cilium pull request #28851
Opened 2023-10-28 15:07 UTC by ChrsMark

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: https://github.com/cilium/hubble/issues/776

```release-note
hubble: Add Support for filtering on HTTP headers
```

2023-10-30 11:59 UTC, gandro approved these changes
Looks good to me, thanks!

2023-10-30 12:00 UTC, gandro commented
/test

2023-10-30 15:42 UTC, lambdanis requested changes
Thank you for tackling this @ChrsMark. The error msg needs to be updated, but otherwise looks good to me.

2023-10-30 15:42 UTC, lambdanis commented on pkg/hubble/filters/http.go
> +			return nil, fmt.Errorf("invalid http method filter: %v", err)
```suggestion
			return nil, fmt.Errorf("invalid http header filter: %v", err)
```

2023-10-30 16:07 UTC, ChrsMark commented on pkg/hubble/filters/http.go
> +			return nil, fmt.Errorf("invalid http method filter: %v", err)
Ah good catch, thanks :)!

2023-10-30 16:17 UTC, lambdanis approved these changes
lgtm

2023-10-30 16:18 UTC, lambdanis commented
/test

2023-11-02 11:55 UTC, ChrsMark commented
Hey @lambdanis @gandro ! Anything else missing here?

2023-11-02 13:06 UTC, gandro commented
Required pipeline [ci-runtime](https://github.com/cilium/cilium/actions/runs/6695681611/job/18256929520) seems to have timed out. I'm going to restart it.

2023-11-08 11:04 UTC, squeed commented
@ChrsMark the failing job has has its timeout bumped. I'm rebasing your PR and hopefully it all passes :-)

2023-11-08 11:57 UTC, gandro commented
/test

2023-11-10 09:37 UTC, merged