The cilium-operator pod is scheduled to another node
cilium/cilium pull request #28856
Opened 2023-10-29 14:06 UTC by jignyasamishra

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

I recreated the particular issue on my local machine and replicated the above problem. For `cilium-operator` the tolerations field was set to `- operator: Exists` for which reason the pods were scheduling again and again into tainted system. I think changing `tolerations` field  for `cilium-operator` will fix the issue.

Fixes: #28549

```release-note

```

2023-10-30 14:16 UTC, squeed requested changes
Two changes needed:
- Can you please edit `values.yaml.tmpl` instead? Then, do a `make -C install/kubernetes` to propagate your changes
- The operator does need some tolerations, so that it can be scheduled in early-stage clusters. Can you please add, for a start, tolerations for `node.cilium.io/agent-not-ready`, `{{.Values.agentNotReadyTaintKey}}`, and `node.kubernetes.io/not-ready`

2023-10-31 13:08 UTC, jignyasamishra commented
> Two changes needed:
> 
> * Can you please edit `values.yaml.tmpl` instead? Then, do a `make -C install/kubernetes` to propagate your changes
> * The operator does need some tolerations, so that it can be scheduled in early-stage clusters. Can you please add, for a start, tolerations for `node.cilium.io/agent-not-ready`, `{{.Values.agentNotReadyTaintKey}}`, and `node.kubernetes.io/not-ready`

Thank you so much for your review!! I am working on it.

2023-11-02 17:49 UTC, jignyasamishra commented
> * The operator does need some tolerations, so that it can be scheduled in early-stage clusters. Can you please add, for a start, tolerations for `node.cilium.io/agent-not-ready`, `{{.Values.agentNotReadyTaintKey}}`, and `node.kubernetes.io/not-ready`

@squeed in my approach I think in [/install/kubernetes/cilium/values.yaml.tmpl](https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml.tmpl)                                                                        
adding tolerations for  `node.kubernetes.io/not-ready`

``` tolerations:
  - key: node.kubernetes.io/not-ready
    effect: NoSchedule   
    operator: Exists
```  
and for `node.cilium.io/agent-not-ready` 
```
tolerations:
  - key: node.cilium.io/agent-not-ready
    effect: NoSchedule   
    operator: Exists     
```
and for `agentNotReadyTaintKey: "node.cilium.io/agent-not-ready"` I am not sure how to go about it as `agentNotReadyTaintKey` prevents any cillium operations to be performed on any tainted nodes and adding the above tolerations for `node.cilium.io/agent-not-ready` will give it some tolerations. Can you guide me on this issue. Thank you

2023-11-08 11:02 UTC, squeed commented
@jignyasamishra basically, the problem is that the operator's set of tolerations is over-broad. So, we need to give it a decent set of default tolerations, but allow users to override those defaults.

Helm makes these sorts of changes possible, but it does take a bit of doing. So, you need to make two changes:

1: in `values.yaml.tmpl`: make the "default" value invalid
```yaml
operator:
  #-- Tolerations for cilium-operator.
  # @default a reasonable set of tolerations to allow for running on the control plane
  tolerations: ~ 
```

Then, in `cilium-operator/deployment.yaml`:

```yaml
tolerations:
{{- if (not (kindIs "invalid" .Values.operator.tolerations )) }}
  {{- toYaml . | trim | nindent 8 }}
{{- else }}
  - key: "node-role.kubernetes.io/control-plane"
    operator: Exists
  - key: node.kubernetes.io/not-ready
    operator: Exists
  {{- with (coalesce .Values.agentNotReadyTaintKey "node.cilium.io/agent-not-ready" }}
  - key: {{ . }}
    operator: Exists
  {{- end }}
```

Something like that. Make sense?

2023-11-09 11:07 UTC, aanm commented
> @jignyasamishra basically, the problem is that the operator's set of tolerations is over-broad. So, we need to give it a decent set of default tolerations, but allow users to override those defaults.
> 
> Helm makes these sorts of changes possible, but it does take a bit of doing. So, you need to make two changes:
> 
> 1: in `values.yaml.tmpl`: make the "default" value invalid
> 
> ```yaml
> operator:
>   #-- Tolerations for cilium-operator.
>   # @default a reasonable set of tolerations to allow for running on the control plane
>   tolerations: ~ 
> ```
> 
> Then, in `cilium-operator/deployment.yaml`:
> 
> ```yaml
> tolerations:
> {{- if (not (kindIs "invalid" .Values.operator.tolerations )) }}
>   {{- toYaml . | trim | nindent 8 }}
> {{- else }}
>   - key: "node-role.kubernetes.io/control-plane"
>     operator: Exists
>   - key: "node-role.kubernetes.io/master" #deprecated
>     operator: Exists
>   - key: node.kubernetes.io/not-ready
>     operator: Exists
>   {{- with (coalesce .Values.agentNotReadyTaintKey "node.cilium.io/agent-not-ready" }}
>   - key: {{ . }}
>     operator: Exists
>   {{- end }}
> ```
> 
> Something like that. Make sense?

@squeed why is this a bug that Cilium has to fix? The default tolerations are "- Exists". Users can still override those in case the feel appropriated. I'm only saying this because it's easier to know what tolerations are and that you need to modify them than not knowing what they are and not understanding why Cilium operator is not being scheduled to a particular node because of taints. This is the primarily reason why we only have "Exists" as the default toleration.

2023-11-10 11:57 UTC, squeed commented
@aanm in this case, adding a reasonable set of tolerations can be an advantage, since the operator is a Deployment. In other words, if there is a maintenance issue on one of the control-plane nodes, it will be rescheduled. This is not relevant for DaemonSets since they shouldn't be de-scheduled anyways.

It really stinks to have the operator not running because the node has gone missing. The node will be tainted accordingly, but the operator never rescheduled.

Whatever we do, we should basically match the tolerations in https://github.com/cilium/cilium/pull/28947, since they are the same.

2023-11-14 14:22 UTC, aanm commented
> @aanm in this case, adding a reasonable set of tolerations can be an advantage, since the operator is a Deployment. In other words, if there is a maintenance issue on one of the control-plane nodes, it will be rescheduled. This is not relevant for DaemonSets since they shouldn't be de-scheduled anyways.

@squeed I understand your point but at the same time this does not happen on environments where you are trying out Cilium for the first time. My point is that if you know that your control-plane nodes are being maintained then you will also know how to change the tolerations of an existing deployment.

First-time users will not know this and if they are running on an environment that has some node taints that is not tolerated by Cilium Operator they will not be able to try out Cilium.

The helm chart should provide some sane defaults that allows users to run on 99% of their environments. If their environment is special then they should change the helm values accordingly.

> It really stinks to have the operator not running because the node has gone missing. The node will be tainted accordingly, but the operator never rescheduled.
> 
> Whatever we do, we should basically match the tolerations in #28947, since they are the same.

2023-11-28 13:24 UTC, squeed commented
> The helm chart should provide some sane defaults that allows users to run on 99% of their environments. If their environment is special then they should change the helm values accordingly.

Agreed; that's why I propose it provide a reasonable set of tolerations. Tolerating all possible taints goes counter to general expectations, especially for something that isn't part of an individual node's networking.

2024-01-19 01:47 UTC, closed without merging

2024-06-18 19:07 UTC, MatthiasWinzeler commented
@squeed can I pick this up again? I just ran into this because a node couldn't be drained because of the cilium-operator being rescheduled right away. I'll happily add a set of sane default tolerations.