Ginkgo: Fix cilium state on RuntimeValidatedConntrackTest
cilium/cilium pull request #2888
Opened 2018-02-20 14:28 UTC by eloycoto

On Build 688 on recovery the policy was in place, so it fails after
restart.

The main issue was the leftover policy on the test that run just before.
This ensure that the status are the same after finished the test

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/688

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/runtime/chaos.go:66
Expected
    <string>: "...     Disabl..."
to equal               |
    <string>: "...     Enable..."
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/runtime/chaos.go:88

level=info msg="Cilium status is true" testName=RuntimeValidatedChaos
STEP: original: ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])   IPv6                 IPv4           STATUS
           ENFORCEMENT        ENFORCEMENT
15009      Enabled            Disabled          3749       container:id.server           f00d::a0f:0:0:3aa1   10.15.222.0    ready
63264      Disabled           Disabled          6263       container:id.client           f00d::a0f:0:0:f720   10.15.154.57   ready

STEP: new: ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])   IPv6                 IPv4           STATUS
           ENFORCEMENT        ENFORCEMENT
15009      Disabled           Disabled          3749       container:id.server           f00d::a0f:0:0:3aa1   10.15.222.0    ready
63264      Disabled           Disabled          6263       container:id.client           f00d::a0f:0:0:f720   10.15.154.57   ready
```

2018-02-20 14:30 UTC, aanm commented on test/runtime/connectivity.go
> +		res.ExpectSuccess("Cannot set policyEnforcemet to default")
Why are 2 Before/AfterEach in this file?

2018-02-20 15:15 UTC, eloycoto commented on test/runtime/connectivity.go
> +		res.ExpectSuccess("Cannot set policyEnforcemet to default")
There are two different TestCases.

2018-02-20 15:43 UTC, eloycoto commented
test-me-please

2018-02-20 18:01 UTC, ianvernon commented on test/runtime/connectivity.go
> +		res.ExpectSuccess("Cannot set policyEnforcemet to default")
Typo - policy enforcement

2018-02-21 02:59 UTC, aanm approved these changes

2018-02-21 06:58 UTC, tgraf requested changes
needs a rebase

2018-02-21 08:29 UTC, eloycoto commented
test-me-please

2018-02-21 18:11 UTC, ianvernon commented
Merging to avoid this blocking merges / wasting time, I'll go ahead and merge the typo fix separately.

2018-02-21 18:11 UTC, merged