helm & ingress/l7-lb: fix hive config properties of type stringslice
cilium/cilium pull request #28922
Opened 2023-11-01 09:21 UTC by mhofstetter

Hive config flags of type `StringSlice` are no longer split by space. Instead, they are split by comma. This leads to issues for config values that have been lately migrated to a Hive cell and didn't change this in the Helm files.

Therefore, this commit changes the affected config values to pass them as a comma-separated string.

* `ingressController.ingressLBAnnotationPrefixes` -> `ingress-lb-annotation-prefixies`
* `loadBalancer.l7.ports` -> `loadbalancer-l7-ports`

Fixes: #28794, #28794

Thanks @giorio94 for catching this!

2023-11-01 09:35 UTC, gandro approved these changes
Helm change itself looks good to me. Do we have a longer term plan (i.e. restoring compatibility or have a linter) to address this, since I'm afraid this will not be the last time we'll miss such a change.

I'm also a bit worried that we break ConfigMap compatibility here. In the past, we've tried to keep the ConfigMap format backwards-compatible as much as possible.

2023-11-01 15:53 UTC, christarazi approved these changes

2023-11-01 15:56 UTC, christarazi commented
@mhofstetter In addition to Sebastian's comment about breaking compatibility, does this need to be backported? Does it need to be mentioned in the upgrade guide so that users can migrate? Or was this code never shipped in a previous release?

2023-11-02 07:55 UTC, mhofstetter commented
> @mhofstetter In addition to Sebastian's comment about breaking compatibility, does this need to be backported? Does it need to be mentioned in the upgrade guide so that users can migrate? Or was this code never shipped in a previous release?

The fix in the Helm Chart itself doesn't need to be backported, because the configs have been changed (migrated to hive configs) in PRs targeting v1.15 (https://github.com/cilium/cilium/pull/28794, https://github.com/cilium/cilium/pull/28835).

But we might need a note in the upgrade guide for users who set this flag in current releases manually (space separated).

2023-11-02 08:03 UTC, giorio94 approved these changes
Thanks!

2023-11-02 09:57 UTC, mhofstetter commented
Let's wait a bit on the decision on whether or not we want to change helm values or whether we want to cell.Config parsing to match what we did earlier with config map StringSlice.

/cc @joamaki

2023-11-09 07:39 UTC, mhofstetter commented
added mention in the upgrade guide

2023-11-09 07:40 UTC, mhofstetter commented
rebased to `main` & resolved conflicts

2023-11-09 16:49 UTC, qmonnet approved these changes

2023-12-06 18:44 UTC, joestringer requested changes
I don't think this is a good idea. How many of these metrics are we going to make incompatible during 1.15 upgrade? I think we need a comprehensive solution. See https://github.com/cilium/cilium/issues/29210 .

2023-12-06 18:45 UTC, closed without merging