bpf: use eth_store_proto()
cilium/cilium pull request #28938
Opened 2023-11-02 04:23 UTC by julianwiedmann

Clean up some open-coded occurences to improve readability. While at it also polish the helper a tiny bit.

For the users in nat_46x64.h also use the existing `protocol` variable to keep ctx_change_proto() and eth_store_proto() in sync.

2023-11-02 04:50 UTC, julianwiedmann commented
/test

2023-11-02 16:24 UTC, gentoo-root requested changes

2023-11-02 16:24 UTC, gentoo-root commented on bpf/lib/nat_46x64.h
> -	    ctx_store_bytes(ctx, nh_off - 2, &protocol, 2, 0) < 0)
Shouldn't it continue using `nh_off - 2` to support an [inner L2 header](https://github.com/cilium/cilium/blob/f8c96d65632ec2ea521768f67457a00dae40646c/bpf/bpf_xdp.c#L177)?

2023-11-03 04:08 UTC, julianwiedmann commented on bpf/lib/nat_46x64.h
> -	    ctx_store_bytes(ctx, nh_off - 2, &protocol, 2, 0) < 0)
ugh, good catch.

I don't think it's a practical concern at the moment - all the NAT46x64 configs should require SNAT dispatch-mode (with DSR, the backends would need to perform the NAT46x64 reverse operation. But we don't have any code for that). While the XDP-passthrough feature is currently limited to DSR (also see https://github.com/cilium/cilium/pull/28959 :)).

But it's still a nasty footgun ... let me think about this for a second. I have a hard time believing that the current 4-to-6 rewrite logic would actually produce something sensible for such an inner packet.

2023-12-18 01:46 UTC, closed without merging