controller: Ensure same uuid during Manager.RemoveController
cilium/cilium pull request #2895
Opened 2018-02-21 15:56 UTC by raybejjani

**Summary of changes**:
Managers would remove any controller with the same name (which is the
key in the contoller map in the manager). We now check that the uuid
matches the entry being removed, in case we have a race between an
UpdateController and a RemoveController.

**How to test (optional)**:
none

2018-02-21 15:57 UTC, raybejjani commented
test-me-please

2018-02-21 16:15 UTC, raybejjani commented
sorry. My laptop wasn't compiling so I tried to do it online... clearly I need to think about this a little more

2018-02-21 21:36 UTC, raybejjani commented
test-me-please

2018-02-22 15:36 UTC, raybejjani commented
test-me-please

2018-02-22 18:29 UTC, ianvernon approved these changes

2018-02-22 19:36 UTC, tgraf approved these changes

2018-02-22 19:38 UTC, aanm requested changes
This is only a blocker for me but I need to discuss something with @raybejjani first. please don't merge it

2018-02-23 00:52 UTC, jrajahalme approved these changes

2018-02-23 09:00 UTC, raybejjani commented
Indeed. This PR is useful on it's own (but breaks aanm's PR) but doesn't solve aanm's real problem: how to stop a controller running. We're running through some possibilities but none are very clean or elegant :(

2018-07-02 16:46 UTC, closed without merging