Modularise mtu discovery
cilium/cilium pull request #28964
Opened 2023-11-03 09:45 UTC by bimmlerd

This series is a preparation for loader modularisation, by pulling a little bit of IPsec key setup and MTU into hive, so that the future loader cell can consume it.

2023-11-15 14:33 UTC, bimmlerd commented
/test

2023-11-17 10:13 UTC, bimmlerd commented
/test

2023-11-17 15:23 UTC, bimmlerd commented
/test

2023-11-22 15:16 UTC, bimmlerd commented
/test

2023-11-23 08:56 UTC, brb approved these changes
:+1: WireGuard changes.

2023-11-23 09:08 UTC, bimmlerd commented
> 👍 WireGuard changes.

CODEOWNERs took that as WG, IPsec and DP in general, though :grin: 

Going to pull in @pchaigno for IPsec in that case, I'm under the impression he has patches he wants to get in which may conflict.

2023-11-23 16:26 UTC, rgo3 approved these changes

2023-11-24 13:01 UTC, pchaigno requested changes
Thanks for the ping David!

The second commit seems the most likely to conflict with other ongoing IPsec work. Could we split it into smaller, easier-to-handle commits? Or alternatively, skip it if that seems easier (IIUC, it's not needed by the third commit)?

2023-11-24 13:01 UTC, pchaigno commented on daemon/cmd/daemon.go
>  	}
> MTU depends on knowing the IPsec key size (though, notably, it seemingly assumes the size doesn't change)

That's a bug. Since https://github.com/cilium/cilium/pull/19814, we allow users to change the IPsec secret without restarting the agent. If they change the authentication key size at that time, then we may end up with an incorrect MTU.

At the very least, we'd need an error message and a mention in the documentation. Do you want to take care of that or should I ask for someone to be assigned?

2023-11-24 13:01 UTC, pchaigno commented on pkg/datapath/linux/ipsec/ipsec_linux.go
> +	}))
Could we split this second commit into several to ease conflict resolution during rebase and backporting of other IPsec work?

In particular, it currently seems to mix code movements, function prototype changes/renaming, health reporting, and misc. other changes. I'd like to see the large code movement eliminated or moved to its own commit with only that. It's what is most likely to conflict and will be much easier to confidently resolve if we can just reapply the same movement without needing to watch out for 2 other types of changes.

2023-11-29 10:21 UTC, bimmlerd commented on daemon/cmd/daemon.go
>  	}
It is. I don't have enough context to deal with this myself, though we are laying the ground-work for this kind of reactivity in the agent with the runtime device work at the moment. If you could ask for someone, that'd be appreciated.

2023-11-29 10:21 UTC, bimmlerd commented on pkg/datapath/linux/ipsec/ipsec_linux.go
> +	}))
I've split the second commit in a few smaller commits, PTAL.

2023-11-29 10:42 UTC, pchaigno commented on daemon/cmd/daemon.go
>  	}
Will do. Thanks for reporting it!

2023-11-29 10:42 UTC, pchaigno approved these changes
Perfect! Thanks a lot David :pray:

2023-11-29 12:00 UTC, bimmlerd commented
/test

2023-11-29 12:23 UTC, bimmlerd commented
/ci-runtime

2023-11-29 13:53 UTC, bimmlerd commented
/ci-external-workloads

2023-11-30 13:14 UTC, joamaki approved these changes

2023-11-30 13:21 UTC, merged