v1.14 Backports 2023-11-08
cilium/cilium pull request #29064
Opened 2023-11-08 22:11 UTC by aanm

* [ ] #28810 (@aanm)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 28810
```

2023-11-08 22:12 UTC, aanm commented
/test-backport-1.14

2023-11-08 22:22 UTC, aanm commented
/test-backport-1.14

2023-11-08 22:54 UTC, aanm commented
/test-backport-1.14

2023-11-09 09:25 UTC, squeed approved these changes

2023-11-09 09:27 UTC, giorio94 requested changes
One comment inline, which I missed during my previous review (and that might be worth addressing).

2023-11-09 09:27 UTC, giorio94 commented on pkg/allocator/allocator.go
> +	key, err = a.backend.AllocateIDIfLocked(ctx, id, key, lock)
Sorry, I missed this during my last review. When `AllocateIDIfLocked` returns an error, the current implementation also returns a nil key. Which means that the error message below will be incorrect.

2023-11-09 09:44 UTC, aanm commented
/test-backport-1.14

2023-11-09 09:45 UTC, giorio94 approved these changes

2023-11-09 11:27 UTC, merged