docs: clarify Mellanox NICs that support XDP acceleration
cilium/cilium pull request #29091
Opened 2023-11-09 18:04 UTC by jshr-w

Please ensure your pull request adheres to the following guidelines:

- [X] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [X] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [X] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [X] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Through testing with AKS, I determined that networking with XDP acceleration does not work correctly with the Mellanox ConnectX-3 NIC on Azure. This has also been cross-referenced as a known issue in the NVidia [documentation](https://docs.nvidia.com/networking/display/mlnxofedv494170/known+issues) (ref: 1550266). This PR updates to documentation to be clearer about this.

Fixes: #29065

2023-11-14 05:25 UTC, qmonnet requested changes
Thanks! Please find some comments inline below.

2023-11-14 05:25 UTC, qmonnet commented on Documentation/network/kubernetes/kubeproxy-free.rst
> +XDP acceleration can only be enabled on NICs ConnectX-4 Lx and onwards.
The commit title, “clarify NIC versions for XDP acceleration”, does not correspond to this change: this is not a clarification but a correction. Can you please adjust the commit title? Would you have a source to link (ideally in the commit log) for the ConnectX-3 incompatibility?

2023-11-14 05:25 UTC, qmonnet commented on Documentation/network/kubernetes/kubeproxy-free.rst
> +     --set loadBalancer.mode=snat \\
Please motivate the change in the commit description.

2023-11-14 05:29 UTC, qmonnet commented on Documentation/network/kubernetes/kubeproxy-free.rst
> +XDP acceleration can only be enabled on NICs ConnectX-4 Lx and onwards.
For the source, I see that you investigated the topic in https://github.com/cilium/cilium/issues/29065. Linking to the Mellanox doc with its known issue and/or https://github.com/cilium/cilium/issues/29065 in the commit log would be good.

2023-11-15 20:20 UTC, jshr-w commented
@qmonnet Thanks for the feedback! I've made the requested changes.

2023-11-16 16:31 UTC, qmonnet approved these changes
Thank you!

2023-11-16 16:32 UTC, qmonnet commented
/test

2023-11-17 17:43 UTC, julianwiedmann commented
Reviews are in, CI is green.

2023-11-17 17:43 UTC, merged