metrics: fix issue where logging err/warn metric is never updated.
cilium/cilium pull request #29201
Opened 2023-11-15 18:26 UTC by tommyp1ckles

Because legacy metrics are now initialized in Hive, the logging hook was being set to the NoOpCounterVec instance.

This moves initializing the errors/warnings metric out of the NewLegacyMetrics function and provides a manual way to init metrics that must be initialized prior to Hive.

2023-12-05 16:30 UTC, chancez approved these changes
Looks reasonable. Might be worth using a gauge for the metric, since it's never going to be changed after initialization, but that's orthogonal to this PR>

2023-12-06 15:43 UTC, pippolo84 requested changes
Thanks for this! Minus the double invoke, LGTM.

2023-12-06 15:43 UTC, pippolo84 commented on pkg/metrics/cell.go
> +	cell.Invoke(func(_ *Registry) {
Now that we have this Invoke here, we can remove the one at line 11.

2023-12-06 23:42 UTC, tommyp1ckles commented on pkg/metrics/cell.go
> +	cell.Invoke(func(_ *Registry) {
ah yup thanks

2023-12-07 01:43 UTC, tommyp1ckles commented
/test

2023-12-07 05:54 UTC, tommyp1ckles commented
/test

2023-12-07 09:20 UTC, pippolo84 approved these changes
LGTM :100:

2023-12-07 17:41 UTC, tommyp1ckles commented
/test

2023-12-07 21:55 UTC, merged