Improved BGP docs on MD5
cilium/cilium pull request #29375
Opened 2023-11-25 12:35 UTC by nvibert

```release-note
Minor documentation fixes and improvements for the BGP MD5 feature
```

2023-11-27 01:23 UTC, YutaroHayakawa approved these changes
LGTM, thanks!

2023-11-27 10:33 UTC, qmonnet requested changes
Thanks! Looks good overall, with some suggestions on the phrasing.

2023-11-27 10:33 UTC, qmonnet commented on Documentation/network/bgp-control-plane.rst
> +::
```suggestion
If a ``CiliumBGPPeeringPolicy`` is deployed with an ``authSecretRef`` that Cilium cannot find, the BGP session will use an empty password and the agent will log an error such as in the following example::
```

Not sure we need to specify the error itself, it's probably enough to mention there will be an error (the error message is descriptive enough that people should be able to match it with the case you describe), but I'm not opposed to it if you prefer to keep it like this.

2023-11-28 12:11 UTC, nvibert commented on Documentation/network/bgp-control-plane.rst
> +::
Thanks @qmonnet - I think folks sometimes forget to look into the agent's log so I think it's worth reminding them and showing them the type of logs that can be on display.

2023-11-28 12:13 UTC, qmonnet approved these changes
Thanks! Please squash the two commits together.

2023-11-28 15:07 UTC, rastislavs approved these changes
Thanks!

2023-11-30 17:45 UTC, mhofstetter commented
/test

2023-11-30 17:50 UTC, mhofstetter commented
Adding `ready-to-merge`: all approvals are in and docs change only (`/tests` didn't skipped `ci-ipsec-e2e` properly)

2023-12-01 03:59 UTC, merged