gh/workflows: Bump CLI to v0.15.15
cilium/cilium pull request #29435
Opened 2023-11-28 10:20 UTC by brb

2023-11-28 10:20 UTC, brb commented
/test

2023-11-28 10:44 UTC, brb commented
Blocked by https://github.com/cilium/cilium-cli/pull/2129.

2023-11-29 06:33 UTC, brb commented
/test

2023-11-29 06:35 UTC, brb commented
/ci-e2e-upgrade

2023-11-29 07:45 UTC, brlbil approved these changes

2023-11-29 07:49 UTC, brb commented
/ci-e2e-upgrade

2023-11-29 20:17 UTC, aanm requested changes

2023-11-29 20:17 UTC, aanm commented on .github/workflows/tests-e2e-upgrade.yaml
>    # renovate: datasource=github-releases depName=cilium/cilium-cli
I think we need to remove this line as well

2023-11-30 11:02 UTC, aanm approved these changes

2023-12-01 13:46 UTC, merged