Pr/learnitall/make initialize private
cilium/cilium pull request #29495
Opened 2023-11-29 22:04 UTC by learnitall

Please ensure your pull request adheres to the following guidelines:

- [X] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [X] All code is covered by unit and/or runtime tests where feasible.
- [X] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [X] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [X] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [X] Provide a title or release-note blurb suitable for the release notes.
- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [X] Thanks for contributing!

This PR renames the function `logging.InitializeDefaultLogger` to `logging.initializeDefaultLogger` in order to make it private to the logging module. This function should only be used to initialize the `logging.DefaultLogger` variable, and should not be used by users as a parent logger. This is because the logger returned by `logging.InitializeDefaultLogger` will always use the hard-coded default logging settings, while `logging.DefaultLogger` is adjusted based on the user configuration.

The changes in `pkg/endpoint/log.go` remove the use of `logging.InitializeDefaultLogger` while also fixing #29215.

Fixes: #29215

```release-note
Make `logging.InitializeDefaultLogger` private
```

2023-11-29 22:22 UTC, tklauser commented
/test

2023-11-30 19:01 UTC, tklauser requested changes
CI failures in `Test/EndpointSuite/TestEndpointLogFormat` look related.

2023-11-30 22:55 UTC, tklauser commented
/test

2023-12-01 10:23 UTC, tklauser commented
/test

2023-12-01 12:49 UTC, tklauser approved these changes

2023-12-01 13:59 UTC, merged

2023-12-05 11:02 UTC, tklauser commented
According to https://github.com/cilium/cilium/pull/29544#issuecomment-1838668847 it seems that https://github.com/cilium/cilium/issues/29215 also occurs on v1.13 (and presumably also v1.14). I've added the corresponding labels but I assume that they'll need manual backports.

2023-12-05 14:59 UTC, learnitall commented
Sounds good @tklauser, I'll keep a look out.

2023-12-05 16:44 UTC, nbusseneau commented
@learnitall Indeed this will need manual backports, as the changes depend on changes made in #26327 and #23971 which were not backported. I will skip this PR in the current round of backports and added the `backport/author` label.

2023-12-07 14:41 UTC, antonipp commented
Hi, FYI I opened a backport PR for 1.13 since this bug affects us in that version: https://github.com/cilium/cilium/pull/29700