Docs: Adds Webhook Limitation to EKS Install Doc
cilium/cilium pull request #29497
Opened 2023-11-29 23:29 UTC by danehans

For EKS installs that use overlay mode, webhook servers must be exposed outside the cluster to be reachable from the managed control plane.

Fixes #29454

2023-11-30 16:03 UTC, lambdanis requested changes
Looks good, but I suggested one clarification.

Also requested a check from @cilium/aws

2023-11-30 16:03 UTC, ghost commented on Documentation/installation/k8s-install-helm.rst
> +               in a separate VPC from worker nodes. This can achieved by using host networking
```suggestion
               must be reachable from the EKS control plane running in a separate VPC from worker nodes. This can achieved by using host networking
```
My understanding is that webhooks must be reachable by the control plane, but not anything else outside of the cluster, so I suggest to clarify it.

2023-11-30 16:24 UTC, ghost approved these changes
Thanks for the update, lgtm

2023-11-30 16:25 UTC, ungureanuvladvictor requested changes

2023-11-30 16:25 UTC, ungureanuvladvictor commented on Documentation/installation/k8s-install-helm.rst
> +            2. `Admission webhooks <https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks>`_
I'd reword this to be more like: "The EKS API Server is unable to route packets to the overlay network. This implies that any webhook which needs to be accessed must be host networked or ...".

The end message I think we should convey is the following:
- there are multiple types of webhooks (e.g., validation, auditing) which are impacted by this
- the EKS API Server is not part of the overlay network -> is unable to communicate with that network

2023-11-30 19:33 UTC, ungureanuvladvictor approved these changes
LGTM

2023-11-30 19:39 UTC, ungureanuvladvictor commented
/test

2023-11-30 23:14 UTC, christarazi approved these changes

2023-12-01 22:58 UTC, danehans commented
Travis CI build failed due to:

```
Unable to find image 'quay.io/cilium/helm-toolbox:v1.0.1@sha256:a1483fc036b15c290326ba7ed36b8f0b714e185913b72a6074c04225d74e034c' locally
docker: Error response from daemon: Get https://quay.io/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers).
```

2023-12-04 20:57 UTC, merged

2023-12-04 21:00 UTC, joestringer commented on Documentation/installation/k8s-install-helm.rst
> +            2. The EKS API Server is unable to route packets to the overlay network. This
Minor nit while looking through afterwards, I think that unordered lists would be more appropriate here and would help to break up the flow of the document vs. the ordered list below. I don't think that there is any specific meaning to the order of these caveats, they're each unique points that the user may consider.