updated docs to reflect Envoy as a DS option
cilium/cilium pull request #29518
Opened 2023-11-30 17:41 UTC by nvibert

```release-note
updated docs to reflect Envoy as a DS option
```

2023-11-30 18:03 UTC, learnitall requested changes
Good catch! Thanks! Couple questions for you.

2023-11-30 18:03 UTC, learnitall commented on Documentation/security/policy/language.rst
> +.. note:: Layer 7 policies will proxy traffic through a node-local :ref:`envoy` instance
Two suggestions here:

1. Do you mind rephrasing this sentence to remove the parenthesis? Parenthesis are great for extra, non-essential pieces of information or side comments, and I don't think they fit here.
2. Can we keep the comment that L7 traffic targeted by policies depends on the availability of the Cilium agent pod in the case that Envoy is embedded in the agent?

2023-12-04 18:30 UTC, nvibert commented on Documentation/security/policy/language.rst
> +.. note:: Layer 7 policies will proxy traffic through a node-local :ref:`envoy` instance
Thanks for the feedback @learnitall - should be fixed now

2023-12-04 21:18 UTC, learnitall requested changes
One small grammar nit and then LGTM. Thanks!

2023-12-04 21:18 UTC, learnitall commented on Documentation/security/policy/language.rst
> +          When Envoy is embedded in the agent pod, Layer 7 traffic target by policies
```suggestion
          When Envoy is embedded in the agent pod, Layer 7 traffic targeted by policies
```

2023-12-05 22:54 UTC, learnitall approved these changes

2023-12-08 14:18 UTC, nathanjsweet approved these changes

2024-01-08 07:56 UTC, mhofstetter commented
/test

2024-01-08 09:51 UTC, mhofstetter commented
/test

2024-01-08 10:40 UTC, mhofstetter commented
MLH seems to be sleeping :( manually marking as `ready-to-merge`.

2024-01-09 09:53 UTC, merged