helm: fix prometheus.metrics not correctly configuring metrics.
cilium/cilium pull request #29564
Opened 2023-12-02 01:06 UTC by tommyp1ckles

The prometheus.metrics field in helm input values takes an array object, and in the cilium-config ConfigMap creates config such as:

```
metrics: +metric1 +metric2 -metric
```

This is then parsed by a StringSlice flag in pkg/metrics/registry.go.

StringSlice is supposed to be a comma-seperated value, however the configmap value is a whitespace seperated.

This changes the helm template to do a join creating a comma seperated array.

Suggested-by: Michi Mutsuzaki <michi@isovalent.com>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note

```

2023-12-04 03:51 UTC, youngnick approved these changes

2023-12-04 09:33 UTC, gandro requested changes
Thanks! CI is failing due to some Helm related artifacts not being regenerated, PTAL:
https://github.com/cilium/cilium/actions/runs/7067025265/job/19239843027?pr=29564

2023-12-04 09:33 UTC, gandro commented on install/kubernetes/cilium/values.yaml
> -  # The list is expected to be separated by a space. (+metric_foo to enable
Please also update the values.yaml.tmpl

2023-12-06 18:45 UTC, joestringer requested changes
We need a consistent solution to this problem. https://github.com/cilium/cilium/issues/29210

2023-12-21 04:34 UTC, closed without merging