daemon: add BackendSlot to Service6Key.String and Service4Key.String
cilium/cilium pull request #29581
Opened 2023-12-04 03:40 UTC by xyz-li

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Fixes: #29580

```release-note
Fix overlapping keys in agent-side service BPF map cache used for retries. In rare cases this bug may have caused retrying of a failed BPF map update for a services entry to be skipped leading to a missing entry. This may have, for example, adversely affected recovering from a full BPF service map after excess services were removed.
```

2023-12-04 11:45 UTC, aanm commented
/test

2023-12-05 11:40 UTC, ti-mo commented
@xyz-li What is the effect of removing the service entry? Given there are no backends to respond, is this a problem?

2023-12-05 11:54 UTC, xyz-li commented
> @xyz-li What is the effect of removing the service entry? Given there are no backends to respond, is this a problem?

Deleting the service entry will not affect the data-path. But it is very confusing when using cilium cli.

2023-12-08 08:07 UTC, aanm commented
/test

2023-12-12 20:37 UTC, joestringer commented
I think it might actually be useful to keep the service frontend in the datapath, so that when the LB decision is made, the datapath can emit drop notifications with `DROP_NO_SERVICE` ("Service backend not found").

2023-12-15 08:40 UTC, joamaki requested changes
This does not look right at all. It's effectively undoing the delete for the obsolete backends, so we'll have entries in the service map that aren't used by the BPF datapath since `slot > len(backends)` of the master service. Unless I'm missing something, to me it seems like this is just effectively leaving garbage entries in the service map and bloating it.

Looking at the code, the agent-side cache should still have the master service in there as it's not deleted even when there's 0 backends.

Could you validate the cache against the actual BPF map (`cilium-dbg bpf lb list`) and see if there's any difference? I'm wondering if there's a bug causing the cache to not be in sync.

At least on my kind environment everything looks OK:
```
root@kind-control-plane:/home/cilium# cilium-dbg map get cilium_lb4_services_v2
Key                 Value                State   Error
10.96.142.154:80    0 1 (9) [0x0 0x0]    sync    
root@kind-control-plane:/home/cilium# cilium-dbg bpf lb list
SERVICE ADDRESS     BACKEND ADDRESS (REVNAT_ID) (SLOT)
10.96.0.10:53       10.244.0.140:53 (1) (1)                                      
                    10.244.0.190:53 (1) (2)                                      
                    0.0.0.0:0 (1) (0) [ClusterIP, non-routable]                  
10.96.230.157:443   172.19.0.3:4244 (8) (1)                                      
                    0.0.0.0:0 (8) (0) [ClusterIP, InternalLocal, non-routable]   
10.96.0.1:443       0.0.0.0:0 (4) (0) [ClusterIP, non-routable]                  
                    172.19.0.3:6443 (4) (1)                                      
10.96.0.10:9153     10.244.0.190:9153 (2) (2)                                    
                    0.0.0.0:0 (2) (0) [ClusterIP, non-routable]                  
                    10.244.0.140:9153 (2) (1)                                    
10.96.142.154:80    0.0.0.0:0 (9) (0) [ClusterIP, non-routable]                  
                    10.244.1.21:9376 (9) (1) 
```

2023-12-17 02:35 UTC, xyz-li commented
1. kubectl  get svc
```
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP   36d
nginx        ClusterIP   10.96.158.224   <none>        80/TCP    12d
``` 
2. cilium map get cilium_lb4_services_v2
```
10.96.114.15:443   0 1 (8) [0x0 0x10]   sync
10.96.0.10:53      0 2 (2) [0x0 0x0]    sync
10.96.0.1:443      0 1 (3) [0x0 0x0]    sync
10.96.158.224:80   0 2 (4) [0x0 0x0]    sync // 10.96.158.224 is here now.
10.96.0.10:9153    0 2 (1) [0x0 0x0]    sync
```
3. kubectl  scale deploy nginx --replicas=1 # now service has one endpoint
4. kubectl describe svc nginx
```
Name:              nginx
Namespace:         default
Labels:            app=nginx
Annotations:       <none>
Selector:          app=nginx
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.96.158.224
IPs:               10.96.158.224
Port:              80-80  80/TCP
TargetPort:        80/TCP
Endpoints:         10.0.0.249:80
Session Affinity:  None
Events:            <none>
```
5. cilium map get cilium_lb4_services_v2
```
Key                Value                State   Error
10.96.114.15:443   0 1 (8) [0x0 0x10]   sync
10.96.0.10:53      0 2 (2) [0x0 0x0]    sync
10.96.0.1:443      0 1 (3) [0x0 0x0]    sync
10.96.0.10:9153    0 2 (1) [0x0 0x0]    sync
```
When scale down some workload,  the endpoint will be deleted. At Last the func `deleteCacheEntry` is delete. 
https://github.com/cilium/cilium/blob/main/pkg/maps/lbmap/ipv4.go#L250-L257

2023-12-18 08:57 UTC, joamaki commented
> 1. kubectl  get svc
> 
> 
> ```
> NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
> kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP   36d
> nginx        ClusterIP   10.96.158.224   <none>        80/TCP    12d
> ```
> 
>     2. cilium map get cilium_lb4_services_v2
> 
> 
> ```
> 10.96.114.15:443   0 1 (8) [0x0 0x10]   sync
> 10.96.0.10:53      0 2 (2) [0x0 0x0]    sync
> 10.96.0.1:443      0 1 (3) [0x0 0x0]    sync
> 10.96.158.224:80   0 2 (4) [0x0 0x0]    sync // 10.96.158.224 is here now.
> 10.96.0.10:9153    0 2 (1) [0x0 0x0]    sync
> ```
> 
>     3. kubectl  scale deploy nginx --replicas=1 # now service has one endpoint
> 
>     4. kubectl describe svc nginx
> 
> 
> ```
> Name:              nginx
> Namespace:         default
> Labels:            app=nginx
> Annotations:       <none>
> Selector:          app=nginx
> Type:              ClusterIP
> IP Family Policy:  SingleStack
> IP Families:       IPv4
> IP:                10.96.158.224
> IPs:               10.96.158.224
> Port:              80-80  80/TCP
> TargetPort:        80/TCP
> Endpoints:         10.0.0.249:80
> Session Affinity:  None
> Events:            <none>
> ```
> 
>     5. cilium map get cilium_lb4_services_v2  # the item in cache not exists.
> 
> 
> ```
> Key                Value                State   Error
> 10.96.114.15:443   0 1 (8) [0x0 0x10]   sync
> 10.96.0.10:53      0 2 (2) [0x0 0x0]    sync
> 10.96.0.1:443      0 1 (3) [0x0 0x0]    sync
> 10.96.0.10:9153    0 2 (1) [0x0 0x0]    sync
> ```
> 
>     6. cilium bpf lb list
> 
> 
> ```
> SERVICE ADDRESS    BACKEND ADDRESS (REVNAT_ID) (SLOT)
> 10.96.0.10:9153    0.0.0.0:0 (1) (0) [ClusterIP, non-routable]
>                    10.0.0.39:9153 (1) (1)
>                    10.0.1.179:9153 (1) (2)
> 10.96.0.10:53      10.0.0.39:53 (2) (1)
>                    0.0.0.0:0 (2) (0) [ClusterIP, non-routable]
>                    10.0.1.179:53 (2) (2)
> 10.96.114.15:443   0.0.0.0:0 (8) (0) [ClusterIP, InternalLocal, non-routable]
>                    10.11.0.11:4244 (8) (1)
> 10.96.0.1:443      0.0.0.0:0 (3) (0) [ClusterIP, non-routable]
>                    10.11.0.11:6443 (3) (1)
> 10.96.158.224:80   10.0.0.249:80 (4) (1)     # 10.96.158.224 exists 
>                    0.0.0.0:0 (4) (0) [ClusterIP, non-routable]
> ```
> 
> After **_scale_** down my nginx workload, one endpoint will be deleted. At last the func `deleteCacheEntry` is called.
> 
> https://github.com/cilium/cilium/blob/fa0037638534635471c8e45583d78f87ad78b3e1/pkg/bpf/map_linux.go#L883-L890
> 
> And then the `String` function.
> 
> https://github.com/cilium/cilium/blob/fa0037638534635471c8e45583d78f87ad78b3e1/pkg/maps/lbmap/ipv4.go#L250-L257

Ah the `String` function is incorrect! It's not taking into account the `BackendSlot` which causes multiple service entries to have the same key, hence we delete the "master" service when we're deleting the "backend slot" entries. What's worse here is that the "cache" is used to retry failed operations in `resolveErrors` and thus we may fail to retry some BPF updates since we've overwritten the entry in the cache.

A short term fix to this issue is to make sure `Service4Key.String()` fully reflects the `Service4Key` value, e.g. by having say `(N)` at the end where `N` is the `BackendSlot`. Could you try this and verify if that results in the correct behavior?

2023-12-18 11:23 UTC, xyz-li commented
1. kubectl  scale deploy nginx --replicas=4 
2. cilium map get cilium_lb4_services_v2 |grep 224
```
10.96.158.224:80 (0)   0 3 (4) [0x0 0x0]    sync
10.96.158.224:80 (1)   36 0 (4) [0x0 0x0]   sync
10.96.158.224:80 (2)   38 0 (4) [0x0 0x0]   sync
10.96.158.224:80 (3)   39 0 (4) [0x0 0x0]   sync
```
3.  kubectl  scale deploy nginx --replicas=2
4. cilium map get cilium_lb4_services_v2 |grep 224
```
10.96.158.224:80 (1)   36 0 (4) [0x0 0x0]   sync
10.96.158.224:80 (2)   38 0 (4) [0x0 0x0]   sync
10.96.158.224:80 (0)   0 2 (4) [0x0 0x0]    sync
```
5.  kubectl  scale deploy nginx --replicas=5
6. cilium map get cilium_lb4_services_v2 |grep 224
```
10.96.158.224:80 (1)   36 0 (4) [0x0 0x0]   sync
10.96.158.224:80 (2)   38 0 (4) [0x0 0x0]   sync
10.96.158.224:80 (3)   41 0 (4) [0x0 0x0]   sync
10.96.158.224:80 (4)   42 0 (4) [0x0 0x0]   sync
10.96.158.224:80 (0)   0 5 (4) [0x0 0x0]    sync
10.96.158.224:80 (5)   43 0 (4) [0x0 0x0]   sync
```
7. cilium bpf lb list
```
SERVICE ADDRESS        BACKEND ADDRESS (REVNAT_ID) (SLOT)
10.96.0.10:9153 (1)    10.0.0.39:9153 (1) (1)
10.96.114.15:443 (0)   0.0.0.0:0 (8) (0) [ClusterIP, InternalLocal, non-routable]
10.96.0.10:9153 (2)    10.0.1.179:9153 (1) (2)
10.96.0.10:53 (0)      0.0.0.0:0 (2) (0) [ClusterIP, non-routable]
10.96.0.1:443 (1)      10.11.0.11:6443 (3) (1)
10.96.0.10:53 (2)      10.0.1.179:53 (2) (2)
10.96.158.224:80 (1)   10.0.0.54:80 (4) (1)
10.96.158.224:80 (5)   10.0.0.199:80 (4) (5)
10.96.0.1:443 (0)      0.0.0.0:0 (3) (0) [ClusterIP, non-routable]
10.96.158.224:80 (0)   0.0.0.0:0 (4) (0) [ClusterIP, non-routable]
10.96.114.15:443 (1)   10.11.0.11:4244 (8) (1)
10.96.0.10:53 (1)      10.0.0.39:53 (2) (1)
10.96.158.224:80 (3)   10.0.0.176:80 (4) (3)
10.96.158.224:80 (2)   10.0.0.25:80 (4) (2)
10.96.158.224:80 (4)   10.0.0.232:80 (4) (4)
10.96.0.10:9153 (0)    0.0.0.0:0 (1) (0) [ClusterIP, non-routable]
```

The service will not be deleted. But the output is not very intuitive.

2023-12-18 11:47 UTC, xyz-li commented
This is the change.
```
func (k *Service4Key) String() string {
	kHost := k.ToHost().(*Service4Key)
	addr := net.JoinHostPort(kHost.Address.String(), fmt.Sprintf("%d", kHost.Port))
	addr = fmt.Sprintf("%s (%d)", addr, kHost.BackendSlot)
	if kHost.Scope == loadbalancer.ScopeInternal {
		addr += "/i"
	}
	return addr
}
```

2023-12-22 08:51 UTC, joamaki commented
What's unintuitive? The output now matches with the bpf map dump as it always should have. I suppose we could be more informative than just `(1)`, e.g. `(slot: 1)`, and avoid repeating the slot twice in `bpf lb list`.

2023-12-25 03:23 UTC, xyz-li commented
> What's unintuitive? The output now matches with the bpf map dump as it always should have. I suppose we could be more informative than just `(1)`, e.g. `(slot: 1)`, and avoid repeating the slot twice in `bpf lb list`.

Got it.

2023-12-29 14:31 UTC, asauber approved these changes
The current version looks correct, if we want to group entries for a service by Service-IP-without-slot. 

Could you provide an example of the `bpf lb list` output with this change?

2024-01-02 02:11 UTC, xyz-li commented
1. cilium bpf lb list
```
SERVICE ADDRESS        BACKEND ADDRESS (REVNAT_ID) (SLOT)
0.0.0.0:50814          0.0.0.0:0 (15) (0) [NodePort, non-routable]
                       10.0.1.126:8012 (15) (1)
10.96.114.15:47873     0.0.0.0:0 (8) (0) [ClusterIP, InternalLocal, non-routable]
                       10.11.0.11:4244 (8) (1)
10.96.0.10:13568       10.0.1.220:53 (2) (1)
                       0.0.0.0:0 (2) (0) [ClusterIP, non-routable]
                       10.0.0.155:53 (2) (2)
10.11.0.11:50814       0.0.0.0:0 (16) (0) [NodePort]
                       10.0.1.126:8012 (16) (1)
10.96.0.1:47873        0.0.0.0:0 (3) (0) [ClusterIP, non-routable]
                       10.11.0.11:6443 (3) (1)
10.96.158.224:20480    10.0.0.75:80 (4) (3)
                       10.0.1.211:80 (4) (2)
                       10.0.1.156:80 (4) (1)
                       0.0.0.0:0 (4) (0) [ClusterIP, non-routable]
10.96.254.239:19487    10.0.1.126:8012 (13) (1)
                       0.0.0.0:0 (13) (0) [ClusterIP, non-routable]
10.11.0.50:50814       10.0.1.126:8012 (14) (1)
                       0.0.0.0:0 (14) (0) [NodePort]
0.0.0.0:49535          0.0.0.0:0 (12) (0) [NodePort, non-routable]
                       10.0.1.7:5432 (12) (1)
10.96.106.136:14357    10.0.1.7:5432 (9) (1)
                       0.0.0.0:0 (9) (0) [ClusterIP, non-routable]
10.11.0.11:49535       0.0.0.0:0 (10) (0) [NodePort]
                       10.0.1.7:5432 (10) (1)
10.11.0.50:49535       0.0.0.0:0 (11) (0) [NodePort]
                       10.0.1.7:5432 (11) (1)
10.96.0.10:49443       0.0.0.0:0 (1) (0) [ClusterIP, non-routable]
                       10.0.1.220:9153 (1) (1)
                       10.0.0.155:9153 (1) (2)
```
2. cilium map get cilium_lb4_services_v2
```
Key                      Value                 State   Error
10.96.158.224:80 (1)     50 0 (4) [0x0 0x0]    sync
10.11.0.11:32705 (0)     0 1 (10) [0x42 0x0]   sync
0.0.0.0:32705 (0)        0 1 (12) [0x2 0x0]    sync
0.0.0.0:32454 (0)        0 1 (15) [0x2 0x0]    sync
0.0.0.0:32705 (1)        68 0 (12) [0x0 0x0]   sync
10.96.158.224:80 (3)     52 0 (4) [0x0 0x0]    sync
10.11.0.50:32705 (0)     0 1 (11) [0x42 0x0]   sync
10.96.114.15:443 (1)     88 0 (8) [0x0 0x0]    sync
10.96.254.239:8012 (1)   87 0 (13) [0x0 0x0]   sync
10.11.0.50:32454 (1)     87 0 (14) [0x0 0x0]   sync
10.96.0.1:443 (0)        0 1 (3) [0x0 0x0]     sync
10.11.0.11:32454 (1)     87 0 (16) [0x0 0x0]   sync
10.96.0.10:9153 (1)      60 0 (1) [0x0 0x0]    sync
10.96.158.224:80 (0)     0 3 (4) [0x0 0x0]     sync
10.96.106.136:5432 (1)   68 0 (9) [0x0 0x0]    sync
10.96.114.15:443 (0)     0 1 (8) [0x0 0x10]    sync
10.96.0.10:9153 (2)      63 0 (1) [0x0 0x0]    sync
10.96.0.10:9153 (0)      0 2 (1) [0x0 0x0]     sync
10.11.0.11:32454 (0)     0 1 (16) [0x42 0x0]   sync
0.0.0.0:32454 (1)        87 0 (15) [0x0 0x0]   sync
10.96.158.224:80 (2)     51 0 (4) [0x0 0x0]    sync
10.11.0.11:32705 (1)     68 0 (10) [0x0 0x0]   sync
10.96.0.10:53 (2)        62 0 (2) [0x0 0x0]    sync
10.96.0.10:53 (0)        0 2 (2) [0x0 0x0]     sync
10.96.254.239:8012 (0)   0 1 (13) [0x0 0x0]    sync
10.96.0.1:443 (1)        1 0 (3) [0x0 0x0]     sync
10.96.106.136:5432 (0)   0 1 (9) [0x0 0x0]     sync
10.11.0.50:32454 (0)     0 1 (14) [0x42 0x0]   sync
10.11.0.50:32705 (1)     68 0 (11) [0x0 0x0]   sync
10.96.0.10:53 (1)        61 0 (2) [0x0 0x0]    sync
```
@asauber

2024-01-08 08:32 UTC, joamaki approved these changes

2024-01-23 10:21 UTC, squeed commented
/test

2024-01-27 10:35 UTC, xyz-li commented
/test

2024-01-27 13:17 UTC, xyz-li commented
> What's unintuitive? The output now matches with the bpf map dump as it always should have. I suppose we could be more informative than just `(1)`, e.g. `(slot: 1)`, and avoid repeating the slot twice in `bpf lb list`.

Now the output of  the command `cilium bpf lb list -ojson` is this.
```
{
  "10.11.0.11:32705 (0)": [
    "0.0.0.0:0 (2) (0) [NodePort]"
  ],
  "10.11.0.11:32705 (1)": [
    "10.0.0.244:5432 (2) (1)"
  ]
}
```
So a lot of tests can not pass.
Shall we add a command option like "--merged", translate the output like this 
```
{
  "10.11.0.28:32705": [
    "0.0.0.0:0 (10) (0) [NodePort]",
    "10.0.0.244:5432 (10) (1)"
  ]
}
```.
Or, I just change the unit-tests.

2024-01-31 20:25 UTC, christarazi approved these changes
ci-structure changes LGTM

2024-02-19 07:13 UTC, xyz-li commented
/test

2024-02-19 09:26 UTC, joamaki commented
> > What's unintuitive? The output now matches with the bpf map dump as it always should have. I suppose we could be more informative than just `(1)`, e.g. `(slot: 1)`, and avoid repeating the slot twice in `bpf lb list`.
> 
> Now the output of the command `cilium bpf lb list -ojson` is this.
> 
> ```
> {
>   "10.11.0.11:32705 (0)": [
>     "0.0.0.0:0 (2) (0) [NodePort]"
>   ],
>   "10.11.0.11:32705 (1)": [
>     "10.0.0.244:5432 (2) (1)"
>   ]
> }
> ```
> 
> So a lot of tests can not pass. Shall we add a command option like "--merged", translate the output like this
> 
> ```
> {
>   "10.11.0.28:32705": [
>     "0.0.0.0:0 (10) (0) [NodePort]",
>     "10.0.0.244:5432 (10) (1)"
>   ]
> }
> ```.
> Or, I just change the unit-tests.
> ```

Let's change the tests as this is the correct output.

2024-02-19 13:45 UTC, xyz-li commented
/test

2024-02-20 16:16 UTC, joamaki approved these changes

2024-02-20 16:16 UTC, joamaki commented
/test

2024-02-21 06:02 UTC, xyz-li commented
/test

2024-02-26 18:38 UTC, joestringer requested changes, later dismissed
The PR title and release note don't seem to match the latest version of this PR. Could you please update these to reflect the impact of this PR, and perhaps consider putting a description of the change into the PR description?

2024-02-29 16:41 UTC, joestringer commented
/test

2024-02-29 22:02 UTC, christarazi commented
@xyz-li Could you write a user-facing release note that describes the impact of the fix? For example,

```
Fix bug where <symptom/problem> ...
```

2024-02-29 22:12 UTC, joestringer commented
@christarazi I think it's not a fix per se, it's just improving the introspection into certain datastructures when using the in-Pod CLI.

2024-02-29 22:13 UTC, joestringer commented
@christarazi @xyz-li I updated the release-note, hopefully that's more accurate.

2024-03-01 05:54 UTC, joamaki commented
@joestringer this fixes a bug as WithCache() uses String() as the key. It fixes the overlapping keys that could have caused a failed BPF map update to never be retried.

2024-03-01 17:56 UTC, joestringer commented
@joamaki I didn't realize it had user-facing impact. If a user hit this issue, what would they experience? How might they know whether this fix addresses the problem they are facing? Whatever the answer to this question is what we would expect the release note in the PR description to be.

2024-03-04 02:38 UTC, xyz-li commented
@joestringer How about not changing the output on the client side?

2024-03-14 23:29 UTC, joestringer commented
How about this?

> Fix bug where a Service would be removed from the datapath if the backends are scaled down to zero.

2024-03-15 02:44 UTC, xyz-li commented
> @xyz-li I don't understand how that relates to my feedback, sorry. All I'm asking is that we describe the change clearly in the user-facing changelogs so that users can understand what bug this fixes and whether they are likely to be affected so they know to upgrade. The release note is derived from the `` ```release-note ... ``` `` field at the bottom of the PR description.
> 
> If you think we should revisit what the client-side output looks like, then I'd suggest describing the alternatives and then others in the PR can provide feedback about which format is best. Without seeing the output, I don't have a strong opinion about this.

How about this commit.
https://github.com/cilium/cilium/pull/31408

2024-04-02 00:11 UTC, joestringer commented
/test

2024-04-03 01:19 UTC, merged