proxy: opt-out from SNAT for L7 + Tunnel for some scenarios
cilium/cilium pull request #29594
Opened 2023-12-04 11:39 UTC by jschwinger233

Currently the L7 proxy performs SNAT for traffic when tunnel routing is enabled, even for cluster-internal traffic. This prevents cilium_host from detecting pod-level traffic, and we thus can't apply features.

Modify SupportsOriginalSourceAddr(), so that the proxy doesn't SNAT such traffic when some conditions are met.

```release-note
proxy: opt-out from SNAT for L7 + Tunnel for some scenarios
```

2023-12-04 11:39 UTC, jschwinger233 commented
/test

2023-12-12 04:32 UTC, jschwinger233 commented
/test

2023-12-13 11:17 UTC, jschwinger233 commented
/test

2023-12-13 16:27 UTC, julianwiedmann requested changes
One cosmetic update below, otherwise looks good :)

2023-12-13 16:27 UTC, julianwiedmann commented on pkg/datapath/iptables/iptables.go
>  			"-m", "comment", "--comment", "cilium: ACCEPT for proxy return traffic",
Just a cosmetic update:

```suggestion
			"-m", "comment", "--comment", "cilium: ACCEPT for proxy traffic",
```

there's also a comment on top that needs `s/proxy return/proxy`.

Same for for IPv6 below :).

2023-12-13 16:45 UTC, jschwinger233 commented
/test

2023-12-13 17:32 UTC, julianwiedmann approved these changes
ty!

2023-12-14 09:13 UTC, jrajahalme approved these changes
The comment above the change should be updated to describe why original source addressing needs to be used with IPsec.

2023-12-14 09:16 UTC, jrajahalme commented
Comment on the PR description/commit message: While it may look like it, there is no SNAT involved with the L7 proxy. The forwarded connection is merely a new one originating from the host networking namespace.

2023-12-14 12:54 UTC, merged