examples: update guestbook example with new image registry
cilium/cilium pull request #29603
Opened 2023-12-04 13:28 UTC by mhofstetter

The GCP Kubernetes Engine Samples migrated their image registry from Google Container Registry to Google Artifact Registry. Hence, the image gb-frontend from the guestbook example is no longer available.

Therefore, this commit changes the example to use the new registry.

Issue: https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/issues/209
Guestbook PR: https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/pull/194

Relevant backport to v1.12 where this image is used in CI: https://github.com/cilium/cilium/pull/29600

2023-12-04 13:41 UTC, mhofstetter commented
/test

2023-12-04 13:57 UTC, aanm approved these changes

2023-12-04 14:56 UTC, ghost requested changes

2023-12-04 14:56 UTC, ghost commented on examples/misc/guestbook/5-guestbook-controller.json
> +                    "image":"us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5",
Apart from changing the registry, the image is downgraded from v6 to v5. I assume it wasn't intentional?

2023-12-04 15:00 UTC, mhofstetter commented on examples/misc/guestbook/5-guestbook-controller.json
> +                    "image":"us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5",
Unfortunately, `v5` is the latest release on that registry. without having the possibility to pull `v6` from the old registry it's hard to compare them :( My assumption is that the change isn't relevant for our usage.

On Cilium v1.12 the guestbook is also used in an automated test. This is no longer the case on newer stable branches where it's only used as an example. 

Let's wait how the test will work out onv1.12 with the v5 image: https://github.com/cilium/cilium/pull/29600

2023-12-04 16:03 UTC, ghost commented on examples/misc/guestbook/5-guestbook-controller.json
> +                    "image":"us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5",
Ah, that's surprising, but fair enough.

2023-12-04 16:04 UTC, lambdanis approved these changes

2023-12-05 08:17 UTC, mhofstetter commented
Updated guestbook example with leader/follower naming

2023-12-05 12:31 UTC, merged