1.15 proxy ingress fine tune
cilium/cilium pull request #29626
Opened 2023-12-05 11:25 UTC by julianwiedmann

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note

```

2023-12-05 11:26 UTC, julianwiedmann commented
/test

2023-12-06 02:31 UTC, jschwinger233 approved these changes

2023-12-06 08:09 UTC, jschwinger233 requested changes
Hang on a moment, let me confirm some details.

2023-12-06 09:28 UTC, jschwinger233 approved these changes
No concerns for ingress, thanks!

2023-12-06 09:56 UTC, jschwinger233 commented on pkg/proxy/routes.go
> +		Mask:     linux_defaults.MagicMarkProxyNoIDMask,
MagicMarkProxyNoIDMask int = 0xFFFFFEFF, this patch is also trying to route egress packets while original one touches ingress only. Maybe make it clear in PR title and commit message?

2023-12-06 10:36 UTC, julianwiedmann commented on pkg/proxy/routes.go
> +		Mask:     linux_defaults.MagicMarkProxyNoIDMask,
yes, that's a bug I think. Let me fix that up quickly ...

2023-12-06 10:52 UTC, julianwiedmann commented
/test

2023-12-06 11:07 UTC, julianwiedmann commented
/test

2023-12-06 11:10 UTC, jschwinger233 approved these changes
:+1:

2023-12-06 11:10 UTC, julianwiedmann commented on pkg/proxy/routes.go
> +		Mask:     linux_defaults.MagicMarkProxyNoIDMask,
thank you Gray!

2024-01-30 01:44 UTC, closed without merging