optimize kind setup
cilium/cilium pull request #29758
Opened 2023-12-09 16:21 UTC by weizhoublue

the kind.sh is used to set up a kind cluster for test, strengthen it with following points:

1. enable specify the path of kubeconfig generated by kind, or else, with the default path '~/.kube/config',  it may overwrite the kubeconfig of other kind cluster

2. add a new option  [--optimize-sysctl], which could fix a typical issue to make sure the kind cluster succeed to run even if the resource is short
issue: https://github.com/kubernetes-sigs/kind/issues/2744
issue: https://github.com/kubernetes-sigs/kind/issues/2586
if the related sysctl's values is too low, either  the kind cluster maybe fail to set up, or the pod maybe fail to run

2023-12-09 16:30 UTC, weizhoublue commented
/test

2023-12-10 03:55 UTC, weizhoublue commented
/test

2023-12-11 10:19 UTC, bimmlerd requested changes
thanks for the contribution! I like it, one minor change and then it'll LGTM

2023-12-11 10:19 UTC, bimmlerd commented on contrib/scripts/kind.sh
> +        echo "WARNING: skip optimizing sysctl on a non-linux host"
hm, given this has to be explicitly requested, I'd lean towards making this a fatal error.

2023-12-11 13:17 UTC, weizhoublue commented on contrib/scripts/kind.sh
> +        echo "WARNING: skip optimizing sysctl on a non-linux host"
If running on macBook laptop where there is no sysctl values named max_user_watches and max_user_instances, so do you prefer like following, all right ?

```
if [ "${optimize_sysctl}" = true ]; then
     if [ "$(uname 2>/dev/null)" == "Linux" ] ; then
         .....
     else
         echo "ERROR: does not support to optimize sysctl on a non-linux host"
         exit
     fi
fi
```

2023-12-11 13:33 UTC, bimmlerd commented on contrib/scripts/kind.sh
> +        echo "WARNING: skip optimizing sysctl on a non-linux host"
Yeah that's what I would suggest :+1: 
maybe `does not support optimizing sysctl on non-linux hosts` :100:

2023-12-12 02:18 UTC, weizhoublue commented
/test

2023-12-12 13:32 UTC, weizhoublue commented
the failed CI case seems to have no business with the PR

2023-12-12 14:23 UTC, ldelossa commented
This failure is unrelated. 

@bimmlerd will need to re-review, we can skip the test requirements for this pull request as it does not touch Cilium code.

2023-12-12 14:35 UTC, bimmlerd approved these changes
yep, LGTM- cheers

2024-01-11 15:21 UTC, merged