daemon: Fail init if requirements for BPF masquerade are not met
cilium/cilium pull request #29778
Opened 2023-12-11 09:40 UTC by pippolo84

In case the requirements for BPF masquerade are not met, fail the daemon initialization instead of silently fall back to iptables based masquerading.

This is needed because the iptables cell does not support runtime configuration changes.

Fixes: [a6a2b73f4f ("iptables: Add a cell for iptables config manager")](https://github.com/cilium/cilium/issues/29663)

2023-12-11 09:40 UTC, pippolo84 commented
/test

2023-12-11 10:55 UTC, giorio94 requested changes
Thanks! 

There's another occurrence which also sets `EnableBPFMasquerade` to false a few lines below. It may not be affected (as in that case `MasqueradingEnabled()` is false), but it is likely worth to also address that one, so that the value is effectively never mutated.

2023-12-11 14:49 UTC, learnitall approved these changes
Upgrade notes look good!

2023-12-13 11:29 UTC, pippolo84 commented
> Thanks!
> 
> There's another occurrence which also sets `EnableBPFMasquerade` to false a few lines below. It may not be affected (as in that case `MasqueradingEnabled()` is false), but it is likely worth to also address that one, so that the value is effectively never mutated.

Fixed, PTAL :pray:

2023-12-13 11:33 UTC, giorio94 approved these changes
Thanks!

2023-12-15 15:43 UTC, thorn3r approved these changes

2023-12-16 00:32 UTC, joestringer commented
I think that this is probably the right approach to make this behaviour more explicit and clear to the user. At the same time, I'm not sure whether we could backport this to any released version given that users could be currently relying on the fallback behaviour and they don't expect to see their cluster break upon upgrade to a .5 or .6 patch release based on an opinionated flag parsing behaviour like this. I'd be _open_ to backport this into v1.15 if y'all strongly advocate for it, or otherwise we could defer to v1.16 if there's no specific rush.

2023-12-18 07:50 UTC, giorio94 commented
> I'm not sure whether we could backport this to any released version given that users could be currently relying on the fallback behaviour and they don't expect to see their cluster break upon upgrade to a .5 or .6 patch release

Totally agree with this.

> I'd be open to backport this into v1.15 if y'all strongly advocate for it

IMHO we need to backport to v1.15 to fix https://github.com/cilium/cilium/issues/29663.

2023-12-18 09:04 UTC, pippolo84 commented
> I'd be _open_ to backport this into v1.15 if y'all strongly advocate for it, or otherwise we could defer to v1.16 if there's no specific rush.

I think it is sufficient to backport this to v1.15 only, as the primary intent of the PR was to fix https://github.com/cilium/cilium/issues/29663 after iptables modularization (as Marco already pointed out).

2023-12-20 15:37 UTC, pippolo84 commented
/test

2023-12-20 17:04 UTC, pippolo84 commented
ci-ginkgo failure tracked [here](https://github.com/cilium/cilium/issues/30011), rerunning

2023-12-21 16:04 UTC, pippolo84 commented
/test

2024-01-05 19:33 UTC, christarazi approved these changes

2024-01-09 23:07 UTC, nathanjsweet approved these changes

2024-01-09 23:14 UTC, merged