ToServices rules work for all external services
cilium/cilium pull request #2979
Opened 2018-03-01 13:53 UTC by nebril

The assumption about a service being external is switched from it being
headless, to it not having a selector.

fixes #2951

2018-03-01 14:21 UTC, nebril commented
test-me-please

2018-03-01 19:38 UTC, tgraf requested changes

2018-03-01 19:38 UTC, tgraf commented on test/k8sT/manifests/headless_service.yaml
> -  clusterIP: None
This change makes no sense to me

2018-03-01 22:59 UTC, eloycoto commented
test-me-please

2018-03-02 11:29 UTC, nebril commented
test-me-please

2018-03-02 12:57 UTC, nebril commented on test/k8sT/manifests/headless_service.yaml
> -  clusterIP: None
I will need to rename all manifests, since these services will no longer be headless.

2018-03-02 12:57 UTC, nebril commented
test-me-please

2018-03-06 11:09 UTC, nebril commented
test-me-please

2018-03-12 09:34 UTC, nebril commented
test-me-please

2018-03-13 10:59 UTC, nebril commented
test-me-please

2018-03-13 15:26 UTC, nebril commented
test-me-please

2018-03-14 11:30 UTC, aanm commented
test-me-please

2018-03-14 11:30 UTC, aanm approved these changes

2018-03-14 13:18 UTC, nebril commented
test-me-please

2018-03-14 14:33 UTC, tgraf approved these changes
👍

2018-03-14 15:07 UTC, nebril commented
Seems like Kafka tests are failing, will rebase and run ginkgo tests after it's resolved.

2018-03-14 15:13 UTC, tgraf commented
> Seems like Kafka tests are failing, will rebase and run ginkgo tests after it's resolved.

I will increase the sleep time and see if it becomes more reliable. @manalibhutiyani is working on improving the test reliability.

2018-03-15 09:57 UTC, nebril commented
test-me-please

2018-03-15 11:32 UTC, nebril commented
test-me-please

2018-03-15 15:37 UTC, nebril commented
test-me-please

2018-03-16 11:51 UTC, nebril commented
test-me-please

2018-03-16 13:08 UTC, nebril commented
test-me-please

2018-03-17 02:32 UTC, tgraf approved these changes

2018-03-17 02:32 UTC, merged