.github: Don't update LVH images on stable branches
cilium/cilium pull request #29835
Opened 2023-12-12 23:38 UTC by joestringer

The v1.14 workflows have obtained tweaks to avoid renovate from updating
the dependencies. Rather than editing each workflow on each stable
branch, configure the renovate config to avoid updating those
dependencies on the stable branches.

2023-12-13 07:28 UTC, viktor-kurchenko approved these changes
LGTM.

2023-12-13 07:39 UTC, julianwiedmann commented
Note that we *are* updating LVH images for the various LTS kernels. Just not the `bpf-next` builds.

2023-12-13 08:47 UTC, aanm requested changes
What Julian said.

We do want to update LVH images on stable branches for the stable kernels but not for the net-next.

However, right now [this](https://github.com/cilium/cilium/blob/v1.14/.github/workflows/tests-ipsec-upgrade.yaml#L101) net-next is likely not "-next" anymore but "stable" at this point, so what benefits are we getting by not upgrading it? /cc @brb

2023-12-13 10:32 UTC, brb commented
> what benefits are we getting

Stability. It happened quite a few times that upgrading bpf-next image was causing us problems due to kernel issues. IMO we don't want to spend time investigating those.

2023-12-13 17:01 UTC, joestringer commented
Ack, so this proposal doesn't make sense as-is.

Maybe we can put the bpf-next update into a separate renovate group and ensure that the update group only targets the `main` branch. This would mean that we don't have to remember how to modify the workflows every time we create a branch.

I'll mark this as draft for now and revisit the approach to ensure it follows the intended update process for these images.

2024-01-10 00:02 UTC, joestringer commented
I've reworked the changes to just split the bpf-next LVH image updates from the regular LTS image updates. Regular images will be bumped on all branches, whereas bpf-next will only be bumped on main. PTAL.

2024-01-16 10:48 UTC, aanm approved these changes
Great change

2024-01-16 10:49 UTC, merged