datapath: Enable N/S LB for overlapping pod CIDR
cilium/cilium pull request #29923
Opened 2023-12-15 14:10 UTC by aspsk

See the commit description.

```release-note
Enable N/S LB for overlapping pod CIDR
```

2023-12-15 16:21 UTC, brb approved these changes

2023-12-18 07:08 UTC, julianwiedmann requested changes
Few comments below, before I forget them ...

2023-12-18 07:08 UTC, julianwiedmann commented on bpf/tests/tc_nodeport_lb4_nat_lb.c
> +
We probably just missed to include `config_replacement.h` here (or didn't need it until now?)

2023-12-18 07:08 UTC, julianwiedmann commented on bpf/lib/nodeport.h
> +						src_identity,
Two blocking concerns here.

1. how do we preserve backwards compatibility for existing network policies?
2. we mustn't pass CIDR identities to other nodes, they have node-local scope. See https://github.com/cilium/cilium/pull/28441 :).

2023-12-18 07:08 UTC, julianwiedmann commented on bpf/lib/nodeport.h
> +	__u32 src_identity = ctx_load_meta(ctx, CB_SRC_LABEL) ?: WORLD_IPV4_ID;
I think we should do this selection in `nodeport_lb4()` already. Also note that we currently use `WORLD_IPV4_ID` when [creating](https://github.com/cilium/cilium/blob/fa0037638534635471c8e45583d78f87ad78b3e1/bpf/lib/nodeport.h#L2917) the nodeport CT entry, should probably stay in sync (even though I have no clue what it's used for ...).

2023-12-20 13:17 UTC, brb commented on bpf/lib/nodeport.h
> +						src_identity,
Do we have a helper function to check whether sec id is a CIDR one?

2023-12-21 09:49 UTC, julianwiedmann commented on bpf/lib/nodeport.h
> +						src_identity,
> Do we have a helper function to check whether sec id is a CIDR one?

I suspect it's this:
https://github.com/cilium/cilium/blob/0bf036effa18390c96c188be00e19cdd923050e4/bpf/lib/identity.h#L142-L143

2024-01-24 09:29 UTC, jibi commented
superseeded by https://github.com/cilium/cilium/pull/30348

2024-01-24 09:29 UTC, closed without merging