Add OpenSSF Scorecard badge to Cilium README
cilium/cilium pull request #29933
Opened 2023-12-17 15:54 UTC by sandipanpanda

OpenSSF Scorecard assesses open source projects for security risks through a series of automated checks.  It performs a series of checks and scores the overall security posture on a scale from 1-10. Adding the OpenSSF Scorecard badge to the README would increase transparency on the overall security posture of the project as recommended in Cilium security audit, 2022. This would also increase the [CLOMonitor score](https://clomonitor.io/projects/cncf/cilium) of Cilium.

Fixes: #23287 #21760

2023-12-22 21:05 UTC, lambdanis approved these changes
Looks good to me, thanks.

Tagging @cilium/security just FYI, unless you have objections.

2023-12-22 21:05 UTC, lambdanis commented
/test

2023-12-26 16:51 UTC, ferozsalam requested changes
Hi, thanks for the contribution!

I have some reservations about the changes proposed by this PR, due to some inconsistencies that I see in the results identified by the scorecard and the actual security posture of the project.

In particular, for the following checks, I don't think the scorecard accurately captures the state of the project:
- `Branch-Protection`: the scorecard is reporting `githubv4.Query: Resource not accessible by integration`, which sounds like an error rather than a deficiency with Cilium's configuration. Is some further setup required to to configure this check correctly, and if so, how does this need to be done?
- `Signed-Releases`: Again, the reason for a negative score here is `internal error: could not get release name`. Cilium's GitHub releases are signed with the committer's signature, so this doesn't represent the project's posture correctly as is. What configuration is required to make this work correctly?
- `Dangerous-Workflow`: Cilium's Security Team has evaluated the workflows in question for security issues and have not been able to find a viable route to exploitation here. Are you able to identify an attack path to compromise Cilium builds using these workflows?
- `Pinned-Dependencies`: The scorecard seems to incorrectly identify a large number of container images in Dockerfiles as not pinned by digest, when they are.

There are some other issues flagged that I would have to do some digging to thoroughly understand, but I think resolving the issues with the checks above would be a good start.

I noticed in https://github.com/cilium/cilium/pull/22371/files you made some changes to the `.clomonitor.yml` to exclude some checks from the CLOMonitor Report - some of those exclusions look very similar to the checks I have mentioned above. Would it be possible to do the same here?

2024-01-10 21:54 UTC, spencerschrock commented
> I have some reservations about the changes proposed by this PR, due to some inconsistencies that I see in the results identified by the scorecard and the actual security posture of the project.

Hi all, one of the OpenSSF Scorecard maintainers here. Most of these are problems are bugs or limitations on our side. The ones that actually result in runtime errors should have our inconclusive result score of `-1`, although this is simply skipped while calculating the score. But the Pinned-Dependency false positives are negatively affecting the score.

> * `Branch-Protection`: the scorecard is reporting `githubv4.Query: Resource not accessible by integration`, which sounds like an error rather than a deficiency with Cilium's configuration. Is some further setup required to to configure this check correctly, and if so, how does this need to be done?

Correct, it's more of an implementation detail. GitHub App installations (which is what we use to scan repos) struggle with detecting the [old way of protecting branches](https://docs.github.com/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule). We are able to detect GitHub's [new repository rules](https://github.blog/2023-07-24-github-repository-rules-are-now-generally-available/) better. 

> Signed-Releases

More of a misalignment/bug on our side, currently we look for release artifacts beyond the source code archives. There's some discussion of this https://github.com/ossf/scorecard/issues/2763, and it's something we can handle better.

> Dangerous-Workflow

The construct is correctly identified as dangerous in my opinion. Even if an implementation may be safe, it's easy for changes to miss the disclaimer:
```
# Warning: since this is a privileged workflow, subsequent workflow job
# steps must take care not to execute untrusted code.
``` 

> Pinned-Dependencies: The scorecard seems to incorrectly identify a large number of container images in Dockerfiles as not pinned by digest, when they are.

I talked about this a little bit in November, https://github.com/ossf/scorecard/issues/3684, but it fell off my radar.

2024-02-07 13:58 UTC, ti-mo commented
@ferozsalam I've added the discussion label so this doesn't accidentally get merged. I can't tell what's actionable here. Please consider taking the discussion elsewhere and close this out if this can't be resolved in the short term.

2024-04-07 01:46 UTC, closed without merging