Optimize make update-authors
cilium/cilium pull request #29936
Opened 2023-12-17 23:51 UTC by 20RitikSingh

Previously, running make update-authors took about 3.5 minutes to run. Now, it runs in seconds.

Fixes: #29882

2023-12-18 09:22 UTC, bimmlerd requested changes
Thank you for your contribution! I think this looks very promising, it's certainly a lot faster!

Unfortunately, as far as I can tell, we're missing a few .mailmap entries for your command to result in the same output. 

For example, `git shortlog` will output only one line for `Alexandre Perrin`, but since there isn't an entry for Alex in the `.mailmap`, he shows up twice in the `git log` output (due to having commits with `alex@kaworu.ch` and `alex@isovalent.com`). I found Alex' example by running your command and diffing against the existing AUTHORS file.

I think one approach would be to try to fix up the mailmap so that it contains entries for the people who will be duplicated otherwise.

2023-12-18 09:22 UTC, bimmlerd commented on contrib/scripts/extract_authors.sh
> +	git log --use-mailmap --format="%<|(40)%aN%aE" | sort -f | uniq
I think we can `sort -fu` instead of `sort -f | uniq`.

2023-12-18 09:22 UTC, bimmlerd commented on contrib/scripts/extract_authors.sh
> -			-e '/vagrant/d')
This seems to have removed the vagrant entry, we should keep that behaviour.

2024-01-10 10:24 UTC, dylandreimerink commented
Ping @20RitikSingh, perhaps this slipped due to the holidays, the ball is in your court. Would be great if you could update your PR.

2024-02-07 13:55 UTC, ti-mo commented
@20RitikSingh please take a look at the review feedback, otherwise we'll be closing this.

2024-02-07 14:15 UTC, ti-mo commented
Closing this in favor of https://github.com/cilium/cilium/pull/30309.

2024-02-07 14:15 UTC, closed without merging