v1.14: nodediscovery: Fix bug where CiliumInternalIP was flapping
cilium/cilium pull request #29972
Opened 2023-12-18 22:11 UTC by pchaigno

Manual backport of https://github.com/cilium/cilium/pull/29964. See commits for conflict notes.

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 29964; do contrib/backporting/set-labels.py $pr done 1.14; done
```

2023-12-18 22:11 UTC, pchaigno commented
/test-backport-1.14

2023-12-19 09:03 UTC, gandro approved these changes
Looks good to me in terms of backported logic, thanks for taking care of this. I have not tested this branch yet however, might be worth doing before we merge.

2023-12-19 09:03 UTC, gandro commented on pkg/nodediscovery/nodediscovery.go
> +				return !n.LocalConfig.EnableIPv4 || n.localNode.GetCiliumInternalIP(false) != nil
So on v1.14 and older the behavior here is slightly different than on v1.15+: `n.localNode` is not the source of truth, rather it is populated via `n.fillLocalNode` (which is not always called before this function).

However, looking at the fact that we're still using `n.localNode.IPAddresses` to populate `nodeResource.Spec.Addresses` I think this is still correct. The important thing is that both pieces of code populate using the same source.

2023-12-19 09:06 UTC, gandro commented
/test-backport-1.14

2023-12-19 09:09 UTC, gandro requested changes
I was too quick to approve. I noticed in the v1.13 review that wee need to remove the `nodeResource.Spec.Addresses = []ciliumv2.NodeAddress{}` initialization on line 411.

2023-12-19 10:01 UTC, pchaigno commented
/test-backport-1.14

2023-12-19 11:05 UTC, julianwiedmann approved these changes

2023-12-19 11:22 UTC, gandro approved these changes

2023-12-19 11:26 UTC, merged