lbipam: allow cross namespace IP sharing
cilium/cilium pull request #30055
Opened 2023-12-25 22:51 UTC by rissson

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Follow-up of #28806 to allow sharing an IP across namespaces.

The previous changes to allow sharing an IP between several services forbid to do so across namespaces because a service is a namespaced resource and doing so could cause security issues.

However, for non-tenanted clusters needing to really reduce IP usage, it still makes sense to allow users to share IPs across namespaces.

This change thus re-introduces that ability by having the user specify an annotation on both services, thus granting sharing.

cc. @usiegl00 @dylandreimerink that implemented/reviewed the initial change allowing sharing.

2023-12-26 01:58 UTC, usiegl00 approved these changes
Thanks!

2024-01-02 13:32 UTC, lambdanis approved these changes
docs ok

2024-01-02 14:09 UTC, dylandreimerink requested changes
Thank you for the contribution! I got one request through, could you please add a test case for this feature?

2024-01-02 14:10 UTC, dylandreimerink commented
I was thinking, how long until someone comes along who wants to share its IPs, but only with specific other namespaces, not just all namespaces in general? (I am thinking not very long)

How hard would it be to change `io.cilium/lb-ipam-sharing-cross-namespace` from a boolean to a list of namespaces with the option of specifying `*` to allow all? 

Would be neat if we could do this right from the start so save us the pain of migrating the accepted values later on. WDYT?

2024-01-02 14:27 UTC, rissson commented
> How hard would it be to change `io.cilium/lb-ipam-sharing-cross-namespace` from a boolean to a list of namespaces with the option of specifying `*` to allow all?

From what I gather, the namespace check only compares two services at a time, so it should easy to check that both services' namespaces are in the annotation on both namespaces.

> Would be neat if we could do this right from the start so save us the pain of migrating the accepted values later on. WDYT?

I agree yes, I'll look into implementing this, along with tests.

2024-01-02 16:37 UTC, dylandreimerink approved these changes
:heart: :rocket:

2024-01-03 12:38 UTC, lambdanis approved these changes
docs still ok

2024-01-03 12:39 UTC, lambdanis commented
/test

2024-01-10 14:59 UTC, dylandreimerink commented
CI is all green except for Gink-go conformance which is hitting flake #30101. Marking ready-to-merge

2024-01-10 14:59 UTC, merged