Increase ServiceMap limit to Uint32
cilium/cilium pull request #30053
Opened 2023-12-25 13:00 UTC by yilmaz-burak

This PR handles the change of uint16 service related variables to uint32, to increase the size of bpf max_entries parameter. This will help with expanding the limit of services that can be created. 

Fixes: #27763 

```release-note
Incerase service map size to uint32 from uint16
```

2024-01-07 14:25 UTC, yilmaz-burak commented
Hey, @tklauser , @ysksuzuki , @aspsk 

Sorry for pinging again, but is is possible for you to review this PR? Or maybe can you permit the workflows to run so that we now everything works as expected? This PR solves an important painpoint for the issue mentioned in the description.
Thanks in advance!

2024-01-08 14:27 UTC, aspsk requested changes
Please also add proper commit descriptions and squash fixes into logical changes.

2024-01-08 14:27 UTC, aspsk commented on bpf/lib/common.h
>  	__u32 src_sec_id; /* Used from userspace proxies, do not change offset! */
How do you address this in your PR?

2024-01-08 14:27 UTC, aspsk commented on bpf/lib/common.h
> -	__u16 rev_nat_index;
How do you address upgrades/downgrades given that map structure changes?

2024-01-30 12:51 UTC, tklauser commented
@yilmaz-burak there are some unresolved review comments. Are you planning to address those? I'm moving this PR to draft status until they are resolved so the PR doesn't show up in people's review queues. Please feel free to move the PR out of draft once the review comments are addressed. Thank you!

2024-04-10 01:44 UTC, closed without merging