Test: Updated default kubernetes version to 1.9
cilium/cilium pull request #3009
Opened 2018-03-05 11:52 UTC by eloycoto

Updated default kubernetes version to 1.9 in test
Added kubernetes 1.8 in test-missed-kubernetes

Fix #2948

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

2018-03-05 11:55 UTC, aanm approved these changes

2018-03-05 14:52 UTC, ianvernon approved these changes

2018-03-05 14:56 UTC, eloycoto commented
test-me-please

2018-03-06 07:39 UTC, eloycoto commented
test-me-please

2018-03-06 15:42 UTC, eloycoto commented
test-me-please

2018-03-06 17:40 UTC, ianvernon requested changes

2018-03-06 17:40 UTC, ianvernon commented on ginkgo.Jenkinsfile
> +            sh 'cd ${TESTDIR}/test/; K8S_VERSION=1.9 vagrant destroy -f || true'
These commands need to be before `cleanWs()`

2018-03-07 07:30 UTC, eloycoto commented
test-me-please

2018-03-07 12:46 UTC, eloycoto commented
test-me-please

2018-03-07 15:48 UTC, eloycoto commented
test-me-please

2018-03-07 17:30 UTC, ianvernon approved these changes

2018-03-07 17:31 UTC, merged