[v1.13] pkg/allocator: Improve 'Key allocation attempt failed' handling for CRD mode
cilium/cilium pull request #30120
Opened 2024-01-05 16:35 UTC by antonipp

Cilium 1.13 / Go 1.19 backport for https://github.com/cilium/cilium/pull/28810 and https://github.com/cilium/cilium/pull/29076

There were some conflicts mainly due to https://github.com/cilium/cilium/pull/23064 which isn't present in 1.13 and the usage of Go 1.19 in 1.13:
- I ignored changes from https://github.com/cilium/cilium/pull/23064: I left the `GlobalIdentity` struct where it is and left value receivers. The only side-effect of not moving `GlobalIdentity` to a separate package caused a cyclical import which I solved by moving `MetadataKeyBackendKey` to `pkg/k8s/identitybackend/identity.go`
- I had to replace the [usage](https://github.com/aanm/cilium/blob/48a1c96cc78647d5d9b69aabc9fd651958588d54/pkg/identity/key/global_identity.go#L60) of `maps.Clone()` with some simple code [here](https://github.com/DataDog/cilium/blob/059ff026b223b17c63ace061530e6f4c527f6394/pkg/identity/cache/allocator.go#L77-L81) (I basically copied it from the `maps` package implementation [here](https://github.com/golang/go/blob/a96487613e2703d1eb7e12c51647e36973df9fd0/src/maps/maps.go#L64-L66)). 
For more context, the `maps` package was added in Go 1.21 and the experimental version of the package which was [used](https://github.com/cilium/cilium/pull/29064/files#diff-9d6a5929a578543ea48537e3b4a054268c4d6041f30b39957dc686fc4c92d293R9) in the 1.14 backport (with Go 1.20) can't be leveraged in Go 1.19 either because `any` was [not a comparable type](https://go.dev/blog/comparable) before 1.20.

2024-01-05 16:35 UTC, antonipp commented
/test-backport-1.13

2024-01-08 10:35 UTC, antonipp commented
/test-backport-1.13

2024-01-17 16:41 UTC, antonipp commented
/test-backport-1.13

2024-01-22 14:52 UTC, antonipp commented
@gentoo-root Looks like test failures are known flaky issues? (https://github.com/cilium/cilium/issues/22749) 
Could we re-launch them?

2024-01-23 11:36 UTC, squeed commented
Requesting @aanm's review, as they are the author of the original PR.

2024-02-02 15:55 UTC, aanm requested changes
It's missing https://github.com/cilium/cilium/pull/29076

2024-02-05 09:55 UTC, antonipp commented
Thank you @aanm, just added this PR as well.

2024-02-05 16:07 UTC, aanm approved these changes

2024-02-05 16:07 UTC, aanm commented
/test-backport-1.13

2024-02-07 00:46 UTC, julianwiedmann approved these changes

2024-02-07 00:47 UTC, merged