Ldelossa/srv6 monitor logging
cilium/cilium pull request #30154
Opened 2024-01-09 13:50 UTC by ldelossa

This PR renames "egress_policies.h" to "srv6.h" since only SRv6 related logic was left in this file.
Moving forward "srv6.h" will be the canonical file for SRv6 related datapath functionality. 

This PR also adds "srv6-encap" and "srv6-decap" monitor events, explaining to a debugger that SRv6 encap/decap successfully occurred and the subsequent packet is heading to the stack. 
This will cut down the time it takes to debug whether the SRv6 datapath processed an SRv6 VPN related packet. 

```release-note
Rename egress_policies.h to srv6.h and add SRv6 related trace reasons. 
```

2024-01-09 14:33 UTC, ldelossa commented
/test

2024-01-09 21:33 UTC, gentoo-root approved these changes

2024-01-10 02:44 UTC, YutaroHayakawa requested changes
Changes looks good to me, but in addition to this, can't we contain the information about the SID on the header we decapsulated? So that we can answer to the question like "is SID X correctly decapsulated?". Looks like trace_notify6 can take an "orig＿ipv6". Can't we use it to store SID?

2024-01-10 02:45 UTC, YutaroHayakawa commented
Also, let me pull-in Hubble team as we touched to the trace_reason.

2024-01-10 15:36 UTC, ldelossa commented
> Changes looks good to me, but in addition to this, can't we contain the information about the SID on the header we decapsulated? So that we can answer to the question like "is SID X correctly decapsulated?". Looks like send_trace_notify6 can take an "orig_addr". Can't we use it to store SID?

@YutaroHayakawa I avoided doing this because we'd need to validate the skb_buff and pull out the ipv6 header when the tail call started, and then log it before we work on the sk_buff directly in `srv6_decapsulation` function. If we log the source before we perform the decap, that could be confusing since we may not successfully perform the decap.

2024-01-12 12:02 UTC, YutaroHayakawa commented
Alright, then, for the moment, let's go with this.

2024-01-12 12:02 UTC, YutaroHayakawa approved these changes

2024-01-12 12:58 UTC, ldelossa commented
@YutaroHayakawa sounds good Yutaro. 

We could also add a raw cilium_dbg statement to dump the SID before we encap, therefore it doesn't 'suggest' anything in a follow up?

2024-01-15 16:53 UTC, ldelossa commented
Marking 'do-not-merge' until Alex has a chance to review. Talked with him and there maybe an implication to this in the Hubble code's ability to perform conn tracking observability.

2024-01-16 16:01 UTC, kaworu commented
@gandro could you please take a look at the patch, especially the Hubble related commit :pray:

2024-01-17 13:34 UTC, gandro approved these changes

2024-01-17 13:52 UTC, kaworu approved these changes

2024-01-17 14:22 UTC, ldelossa commented
/test

2024-01-22 14:26 UTC, merged