Introducing `staticcheck` linter to detect duplicate package imports in Go code.
cilium/cilium pull request #30215
Opened 2024-01-11 16:44 UTC by nickolaev

This PR fixes all the duplicate go imports found by running:
```
staticcheck -checks ST1019 -f stylish ./...
```

Then it adds this action in `lint-go.yaml` to be executed alongside other linters on the PR requests.

This is a re-spin of the original (abandoned) https://github.com/cilium/cilium/pull/28062 by @Archisman-Mridha

Fixes: #27676

2024-01-12 08:36 UTC, dylandreimerink approved these changes

2024-01-12 11:17 UTC, YutaroHayakawa approved these changes

2024-01-12 11:40 UTC, brlbil requested changes

2024-01-12 11:40 UTC, brlbil commented on .github/workflows/lint-go.yaml
> +    name: Lint Source Code using golangci
Two nits, it would be a more consistent name if we change this to `Lint Source Code Golangci`

2024-01-12 11:40 UTC, brlbil commented on .github/workflows/lint-go.yaml
> +    name: Lint source code using staticcheck (to detect duplicate package imports)
and change the name here to `Lint Source Code staticcheck`
these names appear in dashboards so we do not want to bloat them if possible.

Thanks

2024-01-12 12:07 UTC, brlbil approved these changes

2024-01-12 19:42 UTC, nathanjsweet approved these changes
:pray:

2024-01-12 20:22 UTC, rolinh approved these changes

2024-01-15 08:48 UTC, pippolo84 approved these changes
Thanks! :100:

2024-01-15 09:26 UTC, kaworu reviewed
Hubble patch LGTM, however I have a golangci-lint / staticcheck GHA question (see below).

2024-01-15 09:26 UTC, kaworu commented on .github/workflows/lint-go.yaml
staticcheck is part of golangci-lint and [is enabled in our configuration](https://github.com/cilium/cilium/blob/7318ce2d0d89a91227e3f313adebce892f3c388e/.golangci.yaml#L112), do we know why the duplicated imports fixed by this PR were not found by the `golangci` GHA job?

2024-01-15 13:21 UTC, mhofstetter commented on .github/workflows/lint-go.yaml
[duplicated imports](https://staticcheck.dev/docs/checks/#ST1019) is a stylecheck within Staticcheck.

Currently, only staticchecks are enabled in golangci-lint.

It should be enough to enable "stylecheck".

2024-01-15 15:24 UTC, nickolaev commented on .github/workflows/lint-go.yaml
Good point. Adapted the PR to use golangci-lint instead.

2024-01-15 18:23 UTC, mhofstetter approved these changes
LGTM. thanks for switching to golangci-lint. :tada:

2024-01-16 03:36 UTC, tommyp1ckles approved these changes

2024-01-16 10:27 UTC, kaworu approved these changes
Thank you!

2024-01-16 10:28 UTC, kaworu commented
/test

2024-01-19 13:12 UTC, nickolaev commented
/test

2024-01-31 10:37 UTC, mhofstetter commented
/test

2024-01-31 15:46 UTC, merged