nodeipam: actually register the nodeipam cell into the operator
cilium/cilium pull request #30250
Opened 2024-01-15 12:43 UTC by MrFreezeex

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Actually register the nodeipam cell as it was missed in the original PR #30038 
Also add some docs to enable the feature at the helm level since it is disabled by default.

```release-note
Fix nodeipam cell not registered
```

2024-01-15 14:20 UTC, qmonnet requested changes
Other than small minor nits (see below), the PR looks good, thanks a lot!

2024-01-15 14:20 UTC, qmonnet commented on Documentation/network/node-ipam.rst
> +To install Cilium with the node ipam, run
```suggestion
To install Cilium with the node IPAM, run:
```

2024-01-15 14:20 UTC, qmonnet commented on Documentation/network/node-ipam.rst
> +To enable the node ipam on an existing installation, run
```suggestion
To enable the node IPAM on an existing installation, run:
```

2024-01-15 14:24 UTC, qmonnet commented
This probably calls for backports? Fabio, what do you think?

2024-01-15 14:31 UTC, MrFreezeex commented
> This probably calls for backports? Fabio, what do you think?

FYI It's a new feature merged last week (https://github.com/cilium/cilium/pull/30038), so a backport of this particular PR shouldn't be necessary but if you want the feature the "whole feature" to be backported I'm happy to do it as well.

2024-01-16 09:10 UTC, pippolo84 approved these changes
LGTM :100:

2024-01-16 09:14 UTC, pippolo84 commented
> This probably calls for backports? Fabio, what do you think?

I think we don't need it, https://github.com/cilium/cilium/pull/30038 is not part of v1.15 or any other stable branch.

2024-01-18 10:12 UTC, qmonnet approved these changes
Thanks!

2024-01-18 10:12 UTC, qmonnet commented
/test

2024-01-30 12:01 UTC, merged