GSG: Added GPRC examples on ginkgo testing
cilium/cilium pull request #3028
Opened 2018-03-06 15:31 UTC by eloycoto

2018-03-06 17:32 UTC, ianvernon requested changes

2018-03-06 17:32 UTC, ianvernon commented on test/k8sT/Nightly.go
> +	Context("Guetting started guides", func() {
Typo: Guetting --> Getting

2018-03-06 17:32 UTC, ianvernon commented on test/k8sT/Nightly.go
> +				"../examples/kubernetes-grpc/cc-door-app.yaml")
Avoid hardcoding of common paths and put them into variables.

2018-03-07 07:29 UTC, eloycoto commented
test-me-please

2018-03-07 15:19 UTC, ianvernon approved these changes

2018-03-07 15:46 UTC, ianvernon commented
test-nightly

2018-03-08 16:03 UTC, eloycoto commented
@ianvernon this test worked but failed due other problems in nightly. I think that can be merged.

2018-03-08 16:16 UTC, merged