Docs: Adds IPv6 Tunneling Caveat to Networking Concepts
cilium/cilium pull request #30364
Opened 2024-01-22 19:28 UTC by danehans

Previously, the network concepts doc did not state an IPv4 networking requirement. Therefore, users are safe to assume that tunnel mode is supported for IPv6-only networks.

This PR adds the IPv4 network support to the list of tunnel mode requirements.

Fixes #30360

2024-01-22 19:29 UTC, danehans commented
cc @squeed

2024-01-23 12:01 UTC, qmonnet requested changes
Thanks! One nit below

2024-01-23 12:01 UTC, qmonnet commented on Documentation/network/concepts/routing.rst
> +* The underlying network must support IPv4. See `issue 17240 <https://github.com/cilium/cilium/issues/17240>`_
Nit: We've got a dedicated rST role to format GH issue references consistently, can you please use it?:

```suggestion
* The underlying network must support IPv4. See :gh-issue:`17240`
```

2024-01-24 10:53 UTC, qmonnet commented
Thanks! Any chance you can squash the two commits, please?

2024-01-25 10:09 UTC, qmonnet approved these changes
Perfect, thank you!

2024-01-25 10:09 UTC, qmonnet commented
/test

2024-01-25 10:17 UTC, merged