Update Example: kafka-sw-gen-traffic.sh
cilium/cilium pull request #30462
Opened 2024-01-26 13:12 UTC by saintdle

Fixed `kubectl exec` synax

Error's recieved when running this in lab environment before changes :
```sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Error from server (BadRequest): container ./kafka-consume.sh --topic deathstar-plans --from-beginning --max-messages 1 is not valid for pod empire-backup-74b865868c-wv5r4
```

After changes

```sh
root@server:~# #!/usr/bin/env bash

HQ_POD=$(kubectl get pods -l app=empire-hq -o jsonpath='{.items[0].metadata.name}')
OUTPOST_8888_POD=$(kubectl get pods -l outpostid=8888 -o jsonpath='{.items[0].metadata.name}')
OUTPOST_9999_POD=$(kubectl get pods -l outpostid=9999 -o jsonpath='{.items[0].metadata.name}')
BACKUP_POD=$(kubectl get pods -l app=empire-backup -o jsonpath='{.items[0].metadata.name}')

# generate traffic

echo "producing messages"
kubectl exec "$HQ_POD" -- sh -c 'echo "Happy 40th Birthday to General Tagge" | ./kafka-produce.sh --topic empire-announce'
kubectl exec "$HQ_POD" -- sh -c 'echo "deathstar plans v3" | ./kafka-produce.sh --topic deathstar-plans'

echo "consuming messages"

kubectl exec "$OUTPOST_9999_POD" -- sh -c './kafka-consume.sh --topic empire-announce --from-beginning --max-messages 1'
kubectl exec "$OUTPOST_8888_POD" -- sh -c './kafka-consume.sh --topic empire-announce --from-beginning --max-messages 1'
kubectl exec "$BACKUP_POD" -- sh -c './kafka-consume.sh --topic deathstar-plans --from-beginning --max-messages 1'
producing messages
>>>>consuming messages
Happy 40th Birthday to General Tagge
Processed a total of 1 messages
Happy 40th Birthday to General Tagge
Processed a total of 1 messages
deathstar plans v3
Processed a total of 1 messages
root@server:~# 
```

2024-01-29 09:46 UTC, qmonnet requested changes
Good catch, thank you!

Would you please consider using a valid email address for your `Signed-off-by:`? Although rare, we've had to reach out to contributors in the past and the email in the logs is our best chance in that case.

2024-01-30 13:19 UTC, saintdle commented
> Good catch, thank you!
> 
> Would you please consider using a valid email address for your `Signed-off-by:`? Although rare, we've had to reach out to contributors in the past and the email in the logs is our best chance in that case.

Hi, I'm using the [github privacy feature](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address) to mask my email address, but still provide a verified commit. I don't wish to expose my email. Thank you.

2024-02-22 09:29 UTC, ti-mo commented
@saintdle There's a typo in the commit message: https://github.com/cilium/cilium/actions/runs/7668529100/job/20900493448?pr=30462

2024-02-22 09:41 UTC, saintdle commented
> @saintdle There's a typo in the commit message: https://github.com/cilium/cilium/actions/runs/7668529100/job/20900493448?pr=30462

fixed

2024-02-22 15:20 UTC, saintdle commented
> @saintdle There's a typo in the commit message: https://github.com/cilium/cilium/actions/runs/7668529100/job/20900493448?pr=30462

Fixed, and rebased on main due to age of PR

2024-02-26 09:15 UTC, qmonnet reviewed
> Hi, I'm using the [github privacy feature](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address) to mask my email address, but still provide a verified commit. I don't wish to expose my email. Thank you.

Which also prevent Cilium Committers from reaching out to you if they ever need to :confused:.

Can you get rid of the merge commit, please?

2024-03-04 14:36 UTC, qmonnet approved these changes

2024-03-04 17:32 UTC, merged