helm: Allow configuration of Envoy --base-id for Envoy DaemonSet
cilium/cilium pull request #30466
Opened 2024-01-26 14:36 UTC by cpu601

This PR allows manual configuration of Envoy `--base-id` via Helm for the Cilium Envoy DaemonSet.

Currently, Envoy `--base-id` is hard coded to use `0` for the Cilium Envoy DaemonSet which can lead to Envoy startup issues if another Envoy based solution on the same node uses the same `--base-id`.

Having the `--base-id` user configurable allows to solve such issues easily.

This fixes e.g. kubermatic/kubermatic#12922

2024-01-29 06:12 UTC, sayboras approved these changes
The changes is looking good with current codebase. 

I am not sure why we need to set optional field base id currently though, probably for hot restart feature in the near future :thinking:

2024-01-29 09:27 UTC, gandro approved these changes
Helm-wise looks good to me. Please note that you also need to update the Helm values in the Documentation folder by running `make -C Documentation update-helm-values`

2024-01-29 09:28 UTC, gandro requested changes

2024-01-29 09:28 UTC, gandro commented on install/kubernetes/cilium/values.yaml
> +  baseID: 0
Oh, I missed this. Please apply these changes to the `values.yaml.tmpl` and then run `make -C install/kubernetes`. This file here is auto-generated.

2024-01-29 10:09 UTC, gandro commented
Thank you! Please also make sure to squash your commits into one

2024-01-29 15:06 UTC, joamaki approved these changes

2024-01-29 15:11 UTC, gandro approved these changes

2024-01-31 10:12 UTC, sayboras commented
Can you merge 2 commits into one ?

2024-02-01 11:16 UTC, merged