fix aws specific PostStart is appended to daemonset when not chainingMode=aws-cni
cilium/cilium pull request #30497
Opened 2024-01-29 08:32 UTC by chaunceyjiang

Fixes: #30223

```release-note
fix aws specific PostStart is appended to daemonset when not chainingMode=aws-cni
```

2024-01-29 10:26 UTC, chaunceyjiang commented
/test

2024-01-29 10:59 UTC, squeed commented
I'm not sure this is right; chained mode is distinct from ENI mode. In chained mode, AWS is responsible for networking and we should not clean up firewall rules. Only in ENI mode do we want to "take over" the node's networking.

2024-01-29 11:16 UTC, chaunceyjiang commented
I'm not sure if I understand correctly, but in one of my local virtual machines, executing `iptables-save | grep -E -c 'AWS-SNAT-CHAIN|AWS-CONNMARK-CHAIN'` always returns `0`.


So always execute
```
    echo 'Deleting iptables rules created by the AWS CNI VPC plugin'
    iptables-save | grep -E -v 'AWS-SNAT-CHAIN|AWS-CONNMARK-CHAIN' | iptables-restore
```

Judging from the content of the `echo`, this does not meet expectations.

2024-02-05 13:53 UTC, squeed commented
> I'm not sure if I understand correctly, but in one of my local virtual machines, executing `iptables-save | grep -E -c 'AWS-SNAT-CHAIN|AWS-CONNMARK-CHAIN'` always returns `0`.

Right, the issue is when we are on AWS, using Cilium, but chained with aws-bpc-cni. In that case,  aws-vpc-cni is responsible for networking and Cilium is responsible for security and visibility. Which means we **must not** delete any iptables rules created by AWS, or else we risk breaking routing.

2024-02-12 14:45 UTC, joamaki approved these changes

2024-02-13 12:46 UTC, squeed requested changes
This isn't the right fix; the poststart does not interoperate correctly with aws-cni in chained mode. If there is a problem where poststart should be executed, we need to preserve AWS-created iptables rules in the case where `cni.chainingMode == aws-cni`

2024-02-26 21:17 UTC, christarazi commented
@chaunceyjiang What problem is this causing specifically? It's hard to tell what are the effects from the original issue.

cc @nberlee

2024-04-11 01:45 UTC, closed without merging