Bump grpc_health_probe
cilium/cilium pull request #30643
Opened 2024-02-06 11:27 UTC by ferozsalam

Contains updated deps that clear up some CVEs.

2024-02-06 12:19 UTC, sayboras commented
/test

2024-02-06 12:58 UTC, sayboras approved these changes
Looks legit, I came across similar update in envoy repo.

2024-02-06 13:43 UTC, rolinh approved these changes

2024-02-06 20:18 UTC, chancez approved these changes

2024-02-06 20:19 UTC, chancez requested changes
Should the renovate comment be updated as well? Also, why has renovate tried to update this if there's been multiple releases since it's been added?

2024-02-06 20:19 UTC, chancez commented on images/hubble-relay/download-grpc-health-probe.sh
>  # renovate: datasource=github-release-attachments depName=grpc-ecosystem/grpc-health-probe digestVersion=v0.4.21
Should we be updating digestVersion?

2024-02-07 07:05 UTC, ferozsalam commented
> Should the renovate comment be updated as well? Also, why has renovate tried to update this if there's been multiple releases since it's been added?

I've updated the Renovate comment and pinged @glrf yesterday to review the Renovate behaviour so that we don't have to do this manually in the future – I am also not sure why Renovate isn't picking the updates up automatically.

2024-02-07 07:57 UTC, glrf commented
I think the reason why renovate wasn't picking it up was because I forgot to add a file match here: https://github.com/cilium/cilium/blob/main/.github/renovate.json5#L499-L501 (sorry about that :sweat_smile: )

2024-02-07 13:20 UTC, aanm approved these changes

2024-02-07 17:28 UTC, chancez approved these changes

2024-02-08 05:44 UTC, ferozsalam commented
/test

2024-02-11 03:07 UTC, merged