kernel_version_parsing: updating the parseKernelVersion() function to…
cilium/cilium pull request #30699
Opened 2024-02-10 10:25 UTC by MeherRushi

… handle single and double digit kernel versions

Previously, Cilium expects the kernel version to always have 3 digits. However, the kernel is perfectly allowed to have only 2 or even only 1 digit for the version number.
https://github.com/torvalds/linux/blob/35a4474b5c3dd4315f72bd53e87b97f128d9bb3d/Makefile#L367

For Kernel Version :
Linux 6.7-amd64
The error message is as follows:
level=fatal msg="kernel version: NOT OK" error="Invalid character(s) found in minor number \"7-amd64\ \x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x 00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x0 0\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\"" subsys=linux-datapath

This patch updates the parseKernelVersion() to handle single as well double digit kernel versions along with the standard kernel versioning.

Fixes: #30630

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

### Description of change
The issue #30630 address that kernel versions of single and double digit are not being parsed by cilium. I have updated the parseKernelVersion() to handle this case.

Previously the assumption was that kernel version will be something as:
	4.9.17-040917-generic

I have updated it based on the following:

	We are assuming the kernel version will be one of the following:
	4.9.17-040917-generic or 4.9-040917-generic or 4-generic

	So as observered the kernel value is N.N.N-m or N.N-m or N-m
	There for we use regular expresions to extract the patch number
	from the last element of the verStrs array and append "0" to 
	the verStrs array in case the until its lenght is 3 as in all
	cases we want to return from this function : Major.Minor.PatchNumber
	
@lmb @tklauser Please do review the change in code. If it is correct, I also plan on adding test cases for the same

Fixes: #30630 

```release-note
Updated Kernel parsing to handle single and double digit kernel version as well
```

2024-02-14 11:30 UTC, lmb requested changes
Could you add some tests please?

2024-02-14 11:30 UTC, lmb commented on pkg/version/version_unix.go
> +	// So as observered the kernel value is N.N.N-m or N.N-m or N-m
Is `N-m` really a thing? Seems like all kernels are `6.0` etc.

2024-02-14 11:30 UTC, lmb commented on pkg/version/version_unix.go
> +		verStrs[len(verStrs) - 1] = patch
Doesn't this mean that `4.9-1` is treated the same as `4.9.1`?

2024-02-15 06:48 UTC, MeherRushi commented
I'll look into the changes requested and update it soon, I'll also add test cases for the same.

2024-02-16 14:00 UTC, lmb requested changes

2024-02-16 14:00 UTC, lmb commented on pkg/version/version_unix_test.go
> +		{"6-generic", mustHaveVersion("6.0.0")},
Like I mentioned, I don't think this is a valid kernel version. Why should we accept it?

2024-02-18 00:51 UTC, optix2000 commented on pkg/version/version_unix_test.go
> +		{"6-generic", mustHaveVersion("6.0.0")},
While no one uses it in practice, `6-generic` is a valid kernel version and can be generated by the stock Linux kernel Makefile.

2024-02-21 09:49 UTC, lmb approved these changes

2024-02-21 09:49 UTC, lmb commented
@danehans PTAL

2024-02-21 09:55 UTC, tklauser requested changes
Looks like you need to run `gofmt` on the change:

```
Unformatted Go source code:
./pkg/version/version_unix.go
diff ./pkg/version/version_unix.go.orig ./pkg/version/version_unix.go
--- ./pkg/version/version_unix.go.orig
+++ ./pkg/version/version_unix.go
@@ -28,18 +28,18 @@
 
 	// So as observered the kernel value is N.N.N-m or N.N-m or N-m
 	// There for we use regular expresions to extract the patch number
-	// from the last element of the verStrs array and append "0" to 
+	// from the last element of the verStrs array and append "0" to
 	// the verStrs array in case the until its lenght is 3 as in all
 	// cases we want to return from this function : Major.Minor.PatchNumber
 
-	patch := regexp.MustCompilePOSIX(`^[0-9]+`).FindString(verStrs[len(verStrs) - 1])
+	patch := regexp.MustCompilePOSIX(`^[0-9]+`).FindString(verStrs[len(verStrs)-1])
 	if patch == "" {
-		verStrs[len(verStrs) - 1] = "0"
+		verStrs[len(verStrs)-1] = "0"
 	} else {
-		verStrs[len(verStrs) - 1] = patch
-	}
-
-	for len(verStrs) <= 3{
+		verStrs[len(verStrs)-1] = patch
+	}
+
+	for len(verStrs) <= 3 {
 		verStrs = append(verStrs, "0")
 	}
 
make: *** [Makefile:479: precheck] Error 1
make: *** Waiting for unfinished jobs....
```

2024-02-22 12:23 UTC, MeherRushi commented
hank you for pointing it out @tklauser .
I'll do the necessary soon

2024-02-23 06:37 UTC, MeherRushi commented
Hey @tklauser,
I have formatted the code using `gofmt`
Please do take a look when possible

2024-02-23 09:42 UTC, tklauser commented
/test

2024-02-23 09:42 UTC, tklauser approved these changes
Thanks

2024-02-23 09:54 UTC, tklauser commented
@MeherRushi It seems there are still some issue reported by golangci-lint: https://github.com/cilium/cilium/actions/runs/8015579723/job/21900979066?pr=30699 Could you please fix these as well?

2024-02-23 09:56 UTC, MeherRushi commented
Yes, I'll look into it

2024-02-23 09:59 UTC, MeherRushi commented
> @MeherRushi It seems there are still some issues reported by golangci-lint: https://github.com/cilium/cilium/actions/runs/8015579723/job/21900979066?pr=30699 Could you please fix these as well?

yes will look into it
Sorry for the issues caused
will do the necessary in a while

2024-02-23 16:12 UTC, danehans commented
@MeherRushi the linter CI job is failing due to:
```
  Error: pkg/version/version_unix.go:29:11: `observered` is a misspelling of `observed` (misspell)
  	// So as observered the kernel value is N.N.N-m or N.N-m or N-m
  	         ^
  Error: pkg/version/version_unix.go:30:30: `expresions` is a misspelling of `expression` (misspell)
  	// There for we use regular expresions to extract the patch number
  	                            ^
  Error: pkg/version/version_unix.go:32:45: `lenght` is a misspelling of `length` (misspell)
  	// the verStrs array in case the until its lenght is 3 as in all
```

The `lint` Make target can be used to avoid this issue in the future. See the [testing docs](https://docs.cilium.io/en/latest/contributing/testing) for additional details.

2024-02-23 16:38 UTC, danehans commented on pkg/version/version_unix.go
> +	}
If `verStrs` == 3, e.g. `4.9.17`, appending a `0` will cause the version to be `4.9.17.0`. I believe the logic should be:

```
	for len(verStrs) < 3 {
		verStrs = append(verStrs, "0")
	}
```
I suggest adding a test case for this section of code.

2024-02-23 16:38 UTC, danehans commented on pkg/version/version_unix.go
> +	if len(verStrs) < 1 {
Should logic be included to check if `verStrs` exceeds the expected maximum length?

2024-02-24 05:54 UTC, MeherRushi commented
@danehans I have made the requested changes. Please have a look once

2024-02-27 17:59 UTC, danehans approved these changes

2024-02-29 16:20 UTC, danehans commented
/test

2024-03-05 12:42 UTC, tklauser commented
/test

2024-03-05 14:17 UTC, merged

2024-03-06 17:56 UTC, MeherRushi commented
Thanks for the guidance and help @tklauser @lmb @danehans @optix2000