docs: Add reference to BGP Control Plane from Multi-Pool IPAM page
cilium/cilium pull request #30748
Opened 2024-02-13 21:27 UTC by rastislavs

As announcing Multi-Pool PodCIDRs is already supported by the BGP Control Plane, remove the outdated limitation from the Multi-Pool IPAM page and add the necessary reference to the BGP docs.

2024-02-13 21:41 UTC, rastislavs commented
/test

2024-02-14 11:00 UTC, lambdanis requested changes
Commented on a few details in the docs.

2024-02-14 11:00 UTC, lambdanis commented on Documentation/network/concepts/ipam/multi-pool.rst
> +-----------------------------
```suggestion
-----------------------------

```
Can you add an empty line following the header?

2024-02-14 11:00 UTC, lambdanis commented on Documentation/network/concepts/ipam/multi-pool.rst
> +the ``auto-direct-node-routes`` Helm option can be used to enable automatic routing
`auto-direct-node-routes` looks like an agent flag not a Helm value. Could you either refer to it as an agent flag or mention the Helm value here?

2024-02-14 11:00 UTC, lambdanis commented on Documentation/network/concepts/ipam/multi-pool.rst
>   .. _ipam_crd_multi_pool_limitations:
This line should be after "Routing to Allocated PodCIDRs" section I believe.

2024-02-14 12:06 UTC, rastislavs commented on Documentation/network/concepts/ipam/multi-pool.rst
> +the ``auto-direct-node-routes`` Helm option can be used to enable automatic routing
Ah good catch, thanks! Fixed (as well as the other comments).

2024-02-14 16:16 UTC, lambdanis approved these changes
looks good

2024-02-16 08:09 UTC, harsimran-pabla approved these changes

2024-02-21 17:49 UTC, tklauser approved these changes

2024-02-21 17:50 UTC, tklauser commented
/test

2024-02-21 17:57 UTC, merged