Bump kubernetes minimal version supported to 1.6
cilium/cilium pull request #3102
Opened 2018-03-10 14:15 UTC by aanm

**Summary of changes**:
- Deprecate k8s 1.6 support
- Change documentation to minimal requirements to k8s >= 1.7
- Remove all TPR / cilium.io v1 code
- Remove all TPR / cilium.io v1 tests
- Remove jenkins configurations to test against k8s 1.6

First set of changes that address https://github.com/cilium/cilium/issues/3060

```release-note
Bump kubernetes minimal version supported to 1.6
```

2018-03-10 14:18 UTC, aanm commented
test-me-please

2018-03-10 14:18 UTC, aanm commented
test-missed-k8s

2018-03-10 14:19 UTC, aanm commented
test-nightly

2018-03-10 21:55 UTC, aanm commented
test-missed-k8s

2018-03-10 21:55 UTC, aanm commented
test-me-please

2018-03-10 21:55 UTC, aanm commented
test-nightly

2018-03-11 00:51 UTC, aanm commented
test-missed-k8s

2018-03-11 11:59 UTC, aanm commented
All tests have passed. The `Cilium-Ginkgo-Test-k8s` shows they have failed but under Details we can see they all have passed

2018-03-11 22:29 UTC, ianvernon commented on Documentation/contributing.rst
>  By default, the Vagrant VMs are provisioned with Kubernetes 1.7. To run with any other
We need to update these docs as well as we support 1.8 by default, now. This is outside the scope of this ticket, though.

2018-03-11 22:30 UTC, ianvernon commented on Documentation/contributing.rst
>  By default, the Vagrant VMs are provisioned with Kubernetes 1.7. To run with any other
Filed https://github.com/cilium/cilium/issues/3105

2018-03-11 22:35 UTC, ianvernon requested changes
One small nitpick. Thanks for taking care of this!

2018-03-11 22:35 UTC, ianvernon commented on Documentation/kubernetes/compatibility.rst
> + 1.7           * `extensions/v1beta1`_    `CustomResourceDefinition`
Collapse all three versions together since they all use the same "k8s NetworkPolicy API" and "CiliumNetworkPolciy".

2018-03-12 21:59 UTC, aanm commented
test-me-please

2018-03-13 13:51 UTC, aanm commented
test-me-please

2018-03-13 14:23 UTC, eloycoto approved these changes

2018-03-13 14:54 UTC, tgraf approved these changes

2018-03-13 14:54 UTC, merged