cilium, bpf: pkts/byte count conversion for ct
cilium/cilium pull request #31087
Opened 2024-03-01 10:11 UTC by borkmann

Misc prepwork for IPIP termination.

2024-03-01 10:11 UTC, borkmann commented
/test

2024-03-01 16:07 UTC, gentoo-root requested changes

2024-03-01 16:07 UTC, gentoo-root commented on bpf/lib/conntrack.h
> -		/* FIXME: This is slow, per-cpu counters? */
Is https://github.com/cilium/cilium/pull/27527 the final word about this issue? I.e. do we not plan to use percpu maps for these counters, since we already made them disabled by default?

2024-03-01 16:07 UTC, gentoo-root commented on bpf/tests/inter_cluster_snat_clusterip_backend_lxc.c
> -	if (entry->rx_packets != 2)
The tests become less robust with this change, but I struggle to see how we can improve that (i.e. inject more intermediate checks).

2024-03-01 16:07 UTC, gentoo-root commented on bpf/lib/common.h
> +		struct {
Why not ditch the anonymous struct and union altogether?

2024-03-01 16:07 UTC, gentoo-root commented on pkg/maps/ctmap/types.go
>  		sb.WriteString("DSR ")
Should write "DSRInternal".

2024-03-01 16:07 UTC, gentoo-root commented on pkg/maps/ctmap/types.go
>  func (c *CtEntry) isDsrEntry() bool {
I guess it makes sense to rename the function to `isDsrInternalEntry` as well.

2024-03-01 16:07 UTC, gentoo-root commented on bpf/lib/common.h
> +	      dsr_internal:1,   /* DSR is k8s service related, cluster internal */
Is it safe to move the flags of struct ct_state? This struct is passed through a tail call, it will be racy on upgrades, unless we take some measures to replace all BPF programs atomically (I think we don't).

2024-03-01 16:22 UTC, borkmann commented on bpf/lib/conntrack.h
> -		/* FIXME: This is slow, per-cpu counters? */
Good question, given they are not exposed anywhere in Cilium, disabled by default + enabling would mean datapath regen and Hubble doesn't make use of them either, I think per-CPU is for now out of the picture.

2024-03-01 16:31 UTC, borkmann commented on bpf/lib/common.h
> +		struct {
Yeap good point, I'm later on adding elements, but not for this commit so yeah looks nicer.

2024-03-01 16:39 UTC, borkmann commented on bpf/lib/common.h
> +	      dsr_internal:1,   /* DSR is k8s service related, cluster internal */
Hm, excellent point! I undid this now.

2024-03-01 17:02 UTC, gentoo-root approved these changes

2024-03-01 19:21 UTC, christarazi commented on test/k8s/service_helpers.go
> +	// TODO
TODO?

2024-03-01 19:21 UTC, christarazi commented on test/k8s/service_helpers.go
> +	// TODO
TODO?

2024-03-01 19:53 UTC, borkmann commented on test/k8s/service_helpers.go
> +	// TODO
Sry, I just pushed this locally, not fully through yet with implementing Maxim's feedback and addressing the two TODOs.

2024-03-01 23:47 UTC, borkmann commented
/test

2024-03-04 10:40 UTC, borkmann commented
/test

2024-03-04 19:40 UTC, christarazi approved these changes

2024-03-04 19:43 UTC, merged