doc,bgpv1: Add some failure scenarios
cilium/cilium pull request #31249
Opened 2024-03-08 10:46 UTC by YutaroHayakawa

Add following new failure scenarios:

1. Peering Link Down
2. Cilium Operator Down
3. Service Losing All Backends

```release-note
doc,bgpv1: Add some failure scenarios
```

2024-03-08 12:25 UTC, rastislavs requested changes
Nice write-up, just some minor corrections.

2024-03-08 12:25 UTC, rastislavs commented on Documentation/network/bgp-control-plane-operation.rst
> +However, the minimal possible value is ``holdTimeSeconds=3`` and
```suggestion
However, the minimal possible values are ``holdTimeSeconds=3`` and
```

2024-03-08 12:25 UTC, rastislavs commented on Documentation/network/bgp-control-plane-operation.rst
> +``keepAliveTimeSeconds=1``. The general approach to make it much faster is to
```suggestion
``keepAliveTimeSeconds=1``. The general approach to make failure detection faster is to
```

2024-03-08 12:25 UTC, rastislavs commented on Documentation/network/bgp-control-plane-operation.rst
> +withdraw of the PodCIDR and Service VIP routes will be stopped as well.
```suggestion
IP allocation by LB-IPAM are stopped. Therefore, the advertisement of new
and withdrawal of old PodCIDR and Service VIP routes will be stopped as well.
```

2024-03-08 12:25 UTC, rastislavs commented on Documentation/network/bgp-control-plane-operation.rst
> +usual.
Maybe we  should mention here that running more than 1 operator replicas may help to mitigate this?

2024-03-08 12:25 UTC, rastislavs commented on Documentation/network/bgp-control-plane-operation.rst
> +Control Plane behaves differently depending on the Service's
```suggestion
If all service backends are gone due to an outage or a configuration mistake, BGP
Control Plane behaves differently depending on the Service's
```

2024-03-08 12:25 UTC, rastislavs commented on Documentation/network/bgp-control-plane-operation.rst
> +``Cluster``, the Service's VIP kept advertised from all nodes selected by the
```suggestion
``Cluster``, the Service's VIP remains advertised from all nodes selected by the
```

2024-03-11 14:37 UTC, ghost approved these changes
Docs structure looks good.

Can this change be backported to previous minor versions?

2024-03-12 08:30 UTC, rastislavs approved these changes
LGTM, thanks!

2024-03-12 09:39 UTC, YutaroHayakawa commented
/test

2024-03-12 09:47 UTC, merged