v1.14 Backports 2024-03-12
cilium/cilium pull request #31335
Opened 2024-03-12 08:46 UTC by jibi

* [x] #30988 (@tommyp1ckles)
 * [x] #31014 (@tommyp1ckles)
 * [x] #31159 (@pchaigno)
 * [x] #31182 (@aanm)
 * [x] #31196 (@aanm)
 * [x] #31060 (@sayboras)
 * [x] #31179 (@YutaroHayakawa)
 * [x] #31218 (@YutaroHayakawa)
 * [x] #31015 (@learnitall)

PRs skipped due to conflicts:

 * #30686 (@cjvirtucio87)
 * #31292 (@chaunceyjiang)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30988 31014 31159 31182 31196 31060 31179 31218 31015
```

2024-03-12 09:35 UTC, jibi commented
/test-backport-1.14

2024-03-12 09:49 UTC, aanm requested changes

2024-03-12 09:49 UTC, aanm commented on CODEOWNERS
> +/.vscode @cilium/contributing
This is not part of my commit :eyes:

2024-03-12 09:51 UTC, jibi commented on CODEOWNERS
> +/.vscode @cilium/contributing
fixed

2024-03-12 10:09 UTC, sayboras commented
>  * #30686 (@cjvirtucio87)
> * #31292 (@chaunceyjiang)

Noted and thanks, I will take care of these two backports for 1.14.

2024-03-12 10:10 UTC, sayboras approved these changes
Thanks and looks good for my commit.

2024-03-12 10:38 UTC, jibi commented
/test-backport-1.14

2024-03-12 19:48 UTC, aanm approved these changes

2024-03-12 22:40 UTC, pchaigno approved these changes
My PR looks good. Thanks!

2024-03-13 07:28 UTC, YutaroHayakawa approved these changes
Thanks!

2024-03-13 14:45 UTC, learnitall approved these changes
Thank you!

2024-03-14 21:59 UTC, tommyp1ckles approved these changes

2024-03-15 10:29 UTC, dylandreimerink approved these changes

2024-03-16 12:49 UTC, merged