bgpv1: Add the documentation for using serviceAdvertisements
cilium/cilium pull request #31331
Opened 2024-03-12 02:30 UTC by chaunceyjiang

```release-note
Add the documentation for using `serviceAdvertisements`
```

2024-03-13 14:44 UTC, YutaroHayakawa requested changes
Thanks for working on this! Few comments.

2024-03-13 14:44 UTC, YutaroHayakawa commented on Documentation/network/bgp-control-plane.rst
> +This allows users to directly access th e Service from outside the cluster.
```suggestion
This allows users to directly access the Service from outside the cluster.
```

2024-03-13 14:44 UTC, YutaroHayakawa commented on Documentation/network/bgp-control-plane.rst
>  outside the cluster. When your upstream router supports Equal Cost Multi Path
We have a similar phrase above. Maybe we should consolidate?

```
This allows the BGP peers to reach the Service directly from
outside the cluster.
```

2024-03-13 14:44 UTC, YutaroHayakawa commented on Documentation/network/bgp-control-plane.rst
> +see the :ref:`External Access To ClusterIP Services <external_access_to_clusterip_services>` section.
```suggestion
If you wish to use this together with KubeProxyReplacement <reference here>, please make sure the ExternalIP support is enabled.
```

Sorry, actually the `external access to clusterip services` were not required for ExternalIP.

2024-03-13 14:44 UTC, YutaroHayakawa commented on Documentation/network/bgp-control-plane.rst
> +see the :ref:`External Access To ClusterIP Services <external_access_to_clusterip_services>` section.
```suggestion
If you wish to use this together with KubeProxyReplacement <reference here>, specific BPF parameters need to be enabled. See :ref:`External Access To ClusterIP Services <external_access_to_clusterip_services>` section for how to enable it.
```

2024-03-15 12:05 UTC, qmonnet approved these changes
Looks good, thank you

2024-03-15 13:16 UTC, harsimran-pabla approved these changes
Thanks for adding the docs 🙏

2024-03-18 05:54 UTC, YutaroHayakawa approved these changes
Thanks!

2024-03-18 10:46 UTC, merged