Add "node-map-max" to allow configuring nodemap size.
cilium/cilium pull request #31407
Opened 2024-03-15 01:55 UTC by tommyp1ckles

Using the node-map-max flag, one can now override the default 16k node map size.
This may be needed for large clusters, where the number of distinct node IPs in the cluster exceeds the standard size.

In helm, this will allow overriding the size using `bpf.nodeMapMax: <size>`

2024-03-15 01:56 UTC, tommyp1ckles commented
/test

2024-03-15 04:32 UTC, tommyp1ckles commented
/test

2024-03-15 05:01 UTC, tommyp1ckles commented
/test

2024-03-15 11:07 UTC, pchaigno reviewed
I think we need documentation in https://docs.cilium.io/en/latest/network/ebpf/maps/#ebpf-maps. A few generated files are also missing but the CI already highlighted it.

2024-03-15 11:07 UTC, pchaigno commented on pkg/maps/nodemap/cell.go
> +	fs.Uint32("node-map-max", defaultConfig.NodeMapMax,
It looks like all other sibling flags are prepended with `bpf-` (cf. https://docs.cilium.io/en/latest/network/ebpf/maps/#ebpf-maps). Do we want to do the same here?

2024-03-15 11:09 UTC, pchaigno commented
I'd be in favor of backporting to at least the latest OSS release given without this some users may hit error logs that can't be avoided in any other way.

2024-03-15 14:34 UTC, rgo3 approved these changes

2024-03-15 16:08 UTC, tommyp1ckles commented
/test

2024-03-18 10:05 UTC, gandro approved these changes

2024-03-18 10:06 UTC, gandro commented
The Helm workflow is failing due to some files not being regenerated (e.g. the values.yaml file), but otherwise this looks good to me.

Make sure to run

```
make -C install/kubernetes
make -C Documentation update-helm-values
```

2024-03-18 18:14 UTC, christarazi approved these changes

2024-03-19 11:02 UTC, joamaki approved these changes

2024-03-19 11:53 UTC, gandro commented
/test

2024-03-20 22:00 UTC, pchaigno requested changes
These flags are documented in https://docs.cilium.io/en/latest/network/ebpf/maps/#ebpf-maps, which will need to be updated.

2024-03-21 02:35 UTC, tommyp1ckles commented
/test

2024-03-21 06:49 UTC, pchaigno approved these changes

2024-03-21 09:55 UTC, qmonnet approved these changes
Thanks!

2024-03-21 09:58 UTC, qmonnet reviewed
The documentation workflow complains, please update the command reference:

```console
$ make -C Documentation update-cmdref
```

2024-03-22 00:09 UTC, tommyp1ckles commented
/test

2024-03-22 17:07 UTC, tommyp1ckles commented
/test

2024-03-22 18:26 UTC, tommyp1ckles commented
/test

2024-03-25 15:58 UTC, squeed approved these changes

2024-03-25 17:35 UTC, tommyp1ckles commented
/test

2024-03-25 17:36 UTC, tommyp1ckles commented
Looks like quay was done for ci images.

2024-03-26 03:51 UTC, tommyp1ckles commented
/test

2024-03-26 05:50 UTC, merged

2024-04-10 15:51 UTC, nbusseneau commented
@tommyp1ckles This PR depends on changes around the `pkg/datapath` modularization which were introduced during v1.15 development cycle and not backported to v1.14, I've marked the PR as `backport/author` for now so you can decide on what to do :)

2025-01-27 14:26 UTC, giorio94 commented
👋 @tommyp1ckles  Are you still planning on backporting this to v1.14?

2025-02-08 11:44 UTC, julianwiedmann commented
The v1.14 branch is EOL, removing the backport label.