k8s: wait for expected CRD version
cilium/cilium pull request #31416
Opened 2024-03-15 11:32 UTC by giorio94

Currently, Cilium agents explicitly wait for all expected CRDs to be present before proceeding with the subsequent steps. However, no check is performed on the version, which can be problematic on upgrade, as new agents may start before the Cilium operator managed to update the CRDs in case the schema changed. In turn, causing the first operations to act against the old schema, potentially dropping the content of new fields. Let's prevent this issue by explicitly ensuring that the version of the detected CRDs match at least the expected one, and continue waiting otherwise. This gives the operator time to perform the update.

```release-note
Additionally wait for CRDs to match expected version on agents startup.
```

2024-03-15 11:32 UTC, giorio94 commented
/test

2024-03-15 11:41 UTC, pippolo84 approved these changes
LGTM, just left a minot nit inline. Thanks! :100:

2024-03-15 11:41 UTC, pippolo84 commented on pkg/k8s/synced/crd.go
> +		if vsn.GE(semver.MustParse(k8sconst.CustomResourceDefinitionSchemaVersion)) {
Nit: maybe better to compute `semver.MustParse(k8sconst.CustomResourceDefinitionSchemaVersion)` once at import time and save it in a package level variable?

2024-03-15 11:56 UTC, marseel requested changes
I don't think we can make such change without better understanding all possible failure-cases. Imagine the following case:
- New version is deployed with new CRD 
- All agents are Ready
- We perform the rollback, the operator updates CRD back to old verison
- During rollback of agent, two of the new agents restart for whatever reason
- They won't become ready, because they are awaiting new version of CRD
- rollback of cilium-agent will not proceeded as wewill  have `maxUnavailable : 2` forever

I might be wrong about exact semantics of maxUnavailable etc, but my point is that it's very non-obvious change.

2024-03-15 13:09 UTC, giorio94 commented
> I don't think we can make such change without better understanding all possible failure-cases

Agreed, as it can potentially have unintended consequences. I'd still prefer a loud failure compared to subtle race conditions due to agents operating against an unexpected CRD version though.

> Imagine the following case

AFAIU, that case shouldn't be problematic, because the agents stuck due to the incorrect CRD version would be the ones corresponding to the old DaemonSet revision, while the ones associated with the new revision would be able to become ready, allowing the daemonset controller to further proceed with the rollout.

2024-03-18 10:25 UTC, giorio94 commented
> This makes me think of a case when let's say that cilium-operator does not come back up for whatever reason with new CRDs version and old revision agents crash/restart -> it updates them to the new revision. That would result in all agents being in NotReady state waiting for new CRD to come up waiting for new CRD from cilium-operator, while right now in most of the cases they can still ~normally operate even with version skew.

I agree that there could be potentially problematic corner cases if multiple components fail at the same time. That said, I personally think that as long as they are rare enough, we shouldn't worry that much, as it is highly probably that there would be serious issues regardless in that case.

> I honestly lean towards the opinion that agents should always be able to work with two consecutive versions of CRD due to the quite normal eventual consistency nature of Kubernetes (and also the fact we don't use regular CRD versions and operator is registering CRDs). If for example, some field of CRD is missing because of an incorrect version, it should be the resource-owner responsibility to update that field once the version supports it - this is still not ideal in case if CRD schema is never updated, but at least it ensures that rollbacks should be smooth and new field dependency is not "strict".

I agree that agents need to be able to work correctly with both versions during upgrade. That said, I personally think that making sure that the CRD version matches the expected one would simplify this, as avoiding the need of custom logic to realize that the CRD got updated, and that a new field needs to written again.

2024-03-18 20:58 UTC, asauber reviewed
It seems like there is a possibility that if the number of unhealthy pods due to this rollback+restart situation exceeded maxUnavailable, that the rollback would proceed by bringing up additional pods of the older (would-init) version, making the concern an non-issue. However, this possible happy path might be limited by a low value for maxSurge.

Is this something that we want to test out interactively?

An alternative to expecting a specific CRD version is using ConversionWebhooks, however as we know, expecting a CNI init to depend on webhooks is essentially a non-starter.

2024-03-19 08:16 UTC, giorio94 commented
> It seems like there is a possibility that if the number of unhealthy pods due to this rollback+restart situation exceeded maxUnavailable, that the rollback would proceed by bringing up additional pods of the older (would-init) version, making the concern an non-issue. However, this possible happy path might be limited by a low value for maxSurge.

Hmm, it seems that surge limits are ignored if a pod is already unavailable:

```
If the old pod becomes unavailable for any reason
(Ready transitions to false, is evicted, or is drained) an updated pod is
immediatedly created on that node without considering surge limits.
```


> An alternative to expecting a specific CRD version is using ConversionWebhooks, however as we know, expecting a CNI init to depend on webhooks is essentially a non-starter.

Yep. And it wouldn't even have helped in this case, as the issue was that the new agents tried to write a newly added field before the CRD was applied, as that's performed by the operator on startup.

2024-03-25 12:19 UTC, joamaki approved these changes

2024-03-28 09:09 UTC, giorio94 commented
Converting back to draft for the moment, while further investigating the possible implications of this change.

2024-05-12 01:48 UTC, closed without merging