docs: Suggest using operator logs for troubleshooting
cilium/cilium pull request #31500
Opened 2024-03-19 13:48 UTC by simonfelding

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

I had accidentally missed a CRD when installing the gateway. This causes it to mysteriously not work, but there is very nice information in the log file. I think looking in it should be encouraged.

2024-03-20 16:19 UTC, learnitall requested changes
Thank you! Great idea. I left a couple of wording suggestions for you.

2024-03-20 16:19 UTC, learnitall commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +#. Check the Cilium Operator log for information
Wording and grammar suggestion, to make the header more to the point:

```suggestion
#. Check Cilium Operator logs
```

2024-03-20 16:19 UTC, learnitall commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +  The Cilium Operator log may contain further debugging information. For example, if you did not install the required Custom Resource Definitions, you will see an error like this:
This could be formatted to remove the use of "you", which is a common style practice in our docs:

```suggestion
  The Cilium Operator logs may contain further debugging information. For example, if the required Custom Resource Definitions (CRDs) are not installed, an error will be logged:
```

2024-03-20 16:19 UTC, learnitall commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +The Cilium agent uses the resources to supply the configuration to the built in Envoy or the Envoy DaemonSet. Envoy handles traffic.
I think a newline was modified here? Do you mind adjusting the commit so the only changes are the ones you made above?

2024-03-25 16:23 UTC, simonfelding commented on Documentation/network/servicemesh/gateway-api/troubleshooting.rst
> +The Cilium agent uses the resources to supply the configuration to the built in Envoy or the Envoy DaemonSet. Envoy handles traffic.
yep, done

2024-03-25 16:25 UTC, simonfelding commented
@learnitall Thanks! I implemented your suggestions and amended my original commit to not add a newline at the end of the document.

2024-03-25 21:34 UTC, learnitall approved these changes
Looks great! Thank you!

2024-03-27 22:35 UTC, youngnick approved these changes

2024-04-02 09:51 UTC, julianwiedmann commented
/test

2024-04-02 10:04 UTC, merged