RFC: Cilium Network Policy v3
cilium/cilium pull request #3164
Opened 2018-03-16 04:41 UTC by aanm

**Summary of changes**:

Policy v3 implementation

Fixes: #3005 

```release-note
New Cilium Network Policy v3
```

There's lack of documentation since it's WIP. Please suggest better fields names for the Network Policy attributes if needed.

There's a translator from v2 to v3. It's only missing some unit tests.

IMO the new policy output is extremely verbose but it is way less misleading since it is more descriptive of what are the rule intentions. 

```
---
endpointSelector:
  matchLabels:
    any:foo: bar
ingress:
- fromEndpoint:
    endpointSelector:
      matchLabels:
        any:allow: all-ports
- fromEndpoint:
    endpointSelector:
      matchLabels:
        any:restrict: port-111
    toPorts:
    - ports:
      - port: '111'
        protocol: TCP
- fromIPs:
    cidrRule:
      cidr: 1.1.1.1/32
      except:
      - 1.1.1.1/31
    toPorts:
    - ports:
      - port: '111'
        protocol: TCP
egress:
- toService:
    service:
      k8sServiceSelector:
        selectorSelector:
          matchLabels:
            send-to: all-ports
- toService:
    service:
      k8sServiceSelector:
        selectorSelector:
          matchLabels:
            send-to: port-8080
    toServicePorts:
    - ports:
      - port: '8080'
        protocol: TCP
      - port: '80'
        protocol: TCP
      rules:
        http:
        - path: "/foo"
          method: GET
```

Fundamental missing pieces:
 - Change the internal code to accept the new v3
 - Tests?

2018-03-19 21:21 UTC, tgraf commented
Overall looks good. I would keep the first level like this:

```
type IngressRule struct {
	FromEndpoints *Endpoint `json:"fromEndpoints,omitempty"`
	FromRequires *Endpoint `json:"fromRequires,omitempty"`
	FromCIDR *CIDRMeta `json:"fromCIDR,omitempty"`
	FromEntities *EntityRule `json:"fromEntities,omitempty"`
}
```

- I would stick to `fromCIDR` and not mix in IPs. I would also stick to `fromRequires`, it reads better to me.

```
type CIDRMeta struct {
 	CIDR    *CIDRRule `json:"cidrRule,omitempty"`
	ToPorts PortRules `json:"toPorts,omitempty"`

}
```

Do we need the additional nesting? Could we  instead keep it flat?

```
type CIDR struct {
	// CIDR is a CIDR prefix / IP Block.
	//
	CIDR []string `json:"cidr"`

	// ExceptCIDRs is a list of IP blocks which the endpoint subject to the rule
	// is not allowed to initiate connections to. These CIDR prefixes should be
	// contained within CIDR. These exceptions are only applied to the CIDR in
	// this CIDRRule, and do not apply to any other CIDR prefixes in any other
	// CIDRRules.
	//
	// +optional
	ExceptCIDRs []CIDR `json:"except,omitempty"`

	ToPorts PortRules `json:"toPorts,omitempty"`
```

2018-03-19 21:58 UTC, aanm commented
@tgraf the code in this PR is not updated. output that generated the yaml in the first comment is
```
type IngressRule struct {
	FromEndpoint []Endpoint `json:"fromEndpoints,omitempty"`
	FromRequire []EndpointRequire `json:"fromRequires,omitempty"`
	FromIPs []CIDRMeta `json:"fromCIDRs,omitempty"`
	FromEntity []EntityRule `json:"fromEntities,omitempty"`
}
```

I only call it `fromIPs` because of the nesting in `CIDRMeta`. I completely forgot that we could flat the `CIDRMeta`.

```
type CIDRMeta struct {
	CIDR CIDR `json:"cidr"`
	ExceptCIDRs []CIDR `json:"except,omitempty"`
	Generated bool `json:"-"`
	ToPorts PortRules `json:"toPorts,omitempty"`
}
```

>I would stick to fromCIDR and not mix in IPs. I would also stick to `fromRequires`, it reads better to me.

what did you meant by this?

2018-03-19 22:09 UTC, tgraf commented
> what did you meant by this?

I just don't like `fromIPs` and suggest to stick to `fromCIDR`

I suggest we update the struct definitions and put them into the initial PR description and find consensus there and then update the code.

2018-03-19 22:12 UTC, aanm commented
@tgraf But you said `fromRequires` where that came from?

2018-03-20 12:25 UTC, tgraf commented
```
ingress:
- fromEndpoints:
    endpointSelector:
      matchLabels:
        any:svc: foo
    toPorts:
      anyOf:
      - port: '111'
        protocol: TCP

- fromEndpoints:
    endpointSelector:
      matchLabels:
        any:svc: bar
    toPorts:
      anyOf:
      - port: '111'
        protocol: TCP
      - port: '112'
        protocol: TCP
      rules:
        http:
        - path: "/"
          method: GET
          headers:
          - foo=bar
          
- fromCIDRs:
    anyOf:
    - 1.1.1.1/31
    - 2.2.2.2/31
    except:
    - 1.1.1.1/32
    toPorts:
      anyOf:
      - port: '9090'
        protocol: TCP

egress:         
- toEntities:
  anyOf:
  - world
  - host
  toPorts:
    anyOf:
    - port: '8080'
      protocol: TCP

- toRequires:
  anyOf:
  - endpointSelector:
      matchLabels:
        any:team: b
  - endpointSelector:
      matchLabels:
        any:team: c

- toRequires:
  anyOf:
  - endpointSelector:
      matchLabels:
        any:team: c
  - endpointSelector:
      matchLabels:
        any:team: d

- toServices:
    k8sServiceSelector:
      serviceSelector:
        matchLabels:
          svc-name: backup
    toPorts:
      anyOf:
      - port: '8080'
        protocol: TCP
```

2018-03-20 23:32 UTC, ianvernon commented
Looks great to me overall. The devil is in the details though. IMO we need to come up with a substantial test matrix to ensure that this performs how we want it to.

2018-03-21 15:44 UTC, tgraf requested changes
Given we are moving to cnp.cilium.io, we could start counting at v1 if we wanted to. I would be a cleaner but probably requires major surgery in the PR.

2018-03-21 15:44 UTC, tgraf commented on cilium/cmd/policy.go
> +	"github.com/cilium/cilium/pkg/policy/api/v2"
Title of first commit has a typo

2018-03-21 15:44 UTC, tgraf commented on pkg/policy/api/v3/rule.go
> +type EndpointRequire struct {
Rename to `IdentityRequirement`

2018-03-21 15:44 UTC, tgraf commented on pkg/policy/api/v3/selector.go
> +type IdentitySelector struct {
Change to `LabelSelector` if possible without major surgery

2018-03-21 15:44 UTC, tgraf commented on pkg/policy/api/v3/v2tov3.go
> +	if v3Rule.Ingress != nil {
1. v2
2. move for loop into branch

2018-03-21 15:44 UTC, tgraf commented on pkg/policy/api/v3/v2tov3.go
> +	if v3Rule.Egress != nil {
1. v2
2. move for loop into branch

2018-03-21 15:44 UTC, tgraf commented on pkg/policy/api/v3/v2tov3.go
> +
kill line

2018-03-21 15:44 UTC, tgraf commented on pkg/policy/api/v3/v2tov3.go
> +	for i, v := range v2IR.ToPorts {
Move into branch

2018-03-21 15:44 UTC, tgraf commented on pkg/policy/api/v3/v2tov3.go
> +func V2RulesTov3Rules(v2Rules *v2.Rules) *Rules {
Add comment that v2 must have been sanitized

2018-03-21 15:44 UTC, tgraf commented on pkg/policy/api/v3/v2tov3.go
> +
empty line

2018-03-21 15:44 UTC, tgraf commented on pkg/policy/api/v3/v2tov3.go
> +
empty line

2018-03-21 15:44 UTC, tgraf commented on pkg/policy/api/v3/v2tov3.go
> +	for i, v := range v2CR.ExceptCIDRs {
move into branch

2018-03-21 15:44 UTC, tgraf commented on pkg/policy/api/v3/v2tov3.go
> +		apiKeyInt:     v3KafkaRole,
Remove translation of private fields

2018-03-21 15:44 UTC, tgraf commented on daemon/k8s_watcher.go
> +		v3Rules := v3.V2RulesTov3Rules(&rules)
Needs to sanitise the rule again after convertion

2018-03-21 15:44 UTC, tgraf commented on daemon/k8s_watcher.go
> +	v3Rules := v3.V2RulesTov3Rules(&rules)
Sanitise rules again

2018-03-21 15:44 UTC, tgraf commented on daemon/k8s_watcher.go
>  	rules, err := cnp.Parse()
Check error before translation

2018-03-21 15:44 UTC, tgraf commented on daemon/k8s_watcher.go
> +					return errors.New("v2.CiliumNetworkPolicy does not exist in local cache")
v2 -> v3

2018-03-21 15:44 UTC, tgraf commented on daemon/k8s_watcher.go
> +					return fmt.Errorf("unable to find v2.CiliumNetworkPolicy in local cache: %s", err2)
v2 -> v3

2018-03-21 15:44 UTC, tgraf commented on pkg/k8s/network_policy.go
> +								IdentitySelector: *identitySelector,
Add comment to add L4 wildcard here (Thomas)

2018-03-21 15:44 UTC, tgraf commented on pkg/k8s/network_policy.go
> +							FromCIDRs: ipBlockToCIDRRule(rule.IPBlock),
Add comment to add L4 wildcard here (Thomas)

2018-03-21 15:44 UTC, tgraf commented on pkg/k8s/network_policy.go
> +					IdentitySelector: all,
Add comment to add L4 wildcard here (Thomas)

2018-03-21 15:44 UTC, tgraf commented on pkg/k8s/network_policy.go
> +		l4Ports := parsePorts(iRule.Ports)
This can return `nil` if empty list or a `DeepCopy()` so we can call it from all places that need to fill `ToPorts`

2018-03-21 15:44 UTC, tgraf commented on pkg/k8s/network_policy.go
> +		if len(iRule.Ports) == 0 && len(iRule.From) == 0 {
Thomas will fix logic in v2, Andre to readjust after merging v2 fix

2018-03-21 15:44 UTC, tgraf commented on pkg/k8s/network_policy.go
> +		ingresses = []v3.IngressRule{
No comment necessary

2018-03-21 15:44 UTC, tgraf commented on pkg/k8s/network_policy.go
> +		egresses = []v3.EgressRule{
No comment necessary again

2018-03-21 15:44 UTC, tgraf commented on pkg/policy/rule.go
> +				cnt, err := mergeL4(ctx, "Ingress", &ingressRule.FromIdentities.IdentitySelector,
Consider not passing a pointer in

2018-03-21 15:44 UTC, tgraf commented on pkg/policy/rule.go
> +			// FIXME FIXME FIXME why no toEndpoints Selector?
Known, Ian is working on it

2018-03-21 15:44 UTC, tgraf commented on pkg/policy/rule.go
> +	if ctx.From != nil && fromEndpoints != nil {
remove `fromEndpoints != nil`

2018-03-21 15:44 UTC, tgraf commented on pkg/policy/rule.go
> +		if fromEndpoints.Matches(ctx.From) {
```
if !fromEndpoints.Matches(ctx.From) {
   ctx.PolicyTrace("      Labels %s not found", ctx.From)
   return 0, nil
}
```

2018-03-21 15:44 UTC, tgraf commented on pkg/policy/rule.go
> +				if r.FromIdentities.ToPorts != nil {
Move this logic into a `IsWildcard()` function which returns true if `ToPorts` is nil or `ToPorts` slice is empty.

Add FIXME that this doe snot respect protocol yet

2018-03-21 15:44 UTC, tgraf commented on pkg/policy/rule.go
>  	}
Add FIXME here to respect CIDR in the future

2018-03-21 15:44 UTC, tgraf commented on pkg/policy/rule.go
>  			state.matchedRules++
Add the L4 restriction code from identities above  here as well

2018-03-21 15:44 UTC, tgraf commented on pkg/policy/rule.go
> +			if r.ToIdentities.ToPorts != nil {
Same here

2018-03-21 15:44 UTC, tgraf commented on pkg/policy/rule.go
>  			state.matchedRules++
Same here

2018-03-21 16:43 UTC, ianvernon commented
I didn't want to nitpick the initial review as it was an RFC for the actual spec in-and-of-itself because I figured it was subject to change. Is this ready for full-blown review?

2018-03-21 21:27 UTC, aanm commented on pkg/policy/rule.go
>  			state.matchedRules++
I can't, the `fromEntities` is not coming from the `v3.Rule`, is coming from the `policy.Rule`. I added a FIXME

2018-03-22 01:07 UTC, aanm commented
test-me-please

2018-03-22 01:07 UTC, aanm commented
test-missed-k8s

2018-03-22 01:07 UTC, aanm commented
test-nightly

2018-03-22 10:31 UTC, aanm commented
test-me-please

2018-03-22 11:31 UTC, aanm commented
test-me-please

2018-03-22 11:51 UTC, aanm commented
test-me-please

2018-03-22 12:08 UTC, aanm commented
test-me-please

2018-03-22 13:39 UTC, nebril reviewed
ToServices bits look OK, one rename suggestion and several random nitpicks.

2018-03-22 13:39 UTC, nebril commented on pkg/policy/api/v3/rule.go
> +	ToServices *ServiceRule `json:"toServices,omitempty"`
This is no longer a slice, should this be renamed ToService? It can still match multiple services via selector, so I am not sure about it.

2018-03-22 13:39 UTC, nebril commented on pkg/policy/api/v3/rule_validation.go
> +	l3Members := map[string]bool{
Should e.ToRequires also be sanitized here?

2018-03-22 13:39 UTC, nebril commented on pkg/policy/api/v3/rule_validation.go
> +	//_, ipnet, err := net.ParseCIDR(strCIDR)
Please remove commented out code

2018-03-22 13:39 UTC, nebril commented on pkg/policy/api/v3/rules.go
> +type Rules []*Rule
Does this type require separate file? I am OK with that, just asking what's the reason for that.

2018-03-22 13:39 UTC, nebril commented on pkg/policy/api/v3/v2tov3.go
> +// The given v2Rules needs to be sanitized and the returned v3 Rule is alread
s/alread/already

2018-03-22 16:12 UTC, tgraf requested changes

2018-03-22 16:12 UTC, tgraf commented on pkg/k8s/network_policy.go
> +		if len(iRule.From) == 0 {
Could do else branch here

2018-03-22 16:12 UTC, tgraf commented on pkg/k8s/network_policy.go
>  		}
Could do else branch with below branch

2018-03-22 16:12 UTC, tgraf commented on pkg/policy/repository_test.go
>  	ctx.Logging = logging.NewLogBackend(buffer, "", 0)
Add a `c.Log(buffer)` here so we have the trace output

2018-03-22 16:12 UTC, tgraf commented on pkg/policy/repository_test.go
> +	// FIXME FIXME FIXME FIXME FIXME FIXME FIXME
After that, remove this.

2018-03-22 16:12 UTC, tgraf commented on pkg/policy/rule.go
>  		// No need for error checking, as v3.CIDRRule.Sanitize() already does.
Remove this comment

2018-03-22 16:12 UTC, tgraf commented on pkg/policy/rule.go
> +			ip := net.ParseIP(string(c))
Add comment here that we are trying to parse `"x"` instead of `"x/y"`

2018-03-22 16:12 UTC, tgraf commented on pkg/policy/rule.go
>  	for _, entitySelector := range r.fromEntities {
This should be using `FromEntities` of the ingress rule.

2018-03-22 16:12 UTC, tgraf commented on pkg/policy/rule.go
>  	for _, entitySelector := range r.fromEntities {
Sanitisation should happen in `api/v3`

2018-03-22 16:12 UTC, tgraf commented on pkg/policy/rule.go
>  	}
Sorry, we need to remove this again.

2018-03-22 16:12 UTC, tgraf commented on pkg/policy/rule.go
>  	for _, entitySelector := range r.toEntities {
Same applies here

2018-03-22 16:12 UTC, tgraf commented on pkg/policy/rule.go
> +	// FIXME respect CIDR in the future
Remove again

2018-03-22 16:12 UTC, tgraf commented on pkg/policy/rule_test.go
> +		Port: 3000, Protocol: v3.ProtoTCP, U8Proto: 6, FromEndpoints: []v3.IdentitySelector{},
Extend `IsWildcard()` to check for `nil`

2018-03-22 18:08 UTC, aanm commented
/test-me-please

2018-03-22 18:49 UTC, ianvernon requested changes
Changes are mainly documentation related. While they are nitpicky, I think they are necessary to address because this is our publicly facing API and this should be as polished as possible.

I'm going to have to come back and review other parts separately because I found the sheer size of this PR difficult to consume.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule.go
> +	// unique, multiple rules can have overlapping or identical labels.
unique;

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule.go
> +	// Description is a free form string, it can be used by the creator of
free-form string. It can be used by...

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule.go
> +	// the rule to store human readable explanation of the purpose of this
... to store a human-readable explanation...

2018-03-22 18:49 UTC, ianvernon commented on pkg/logging/logfields/logfields.go
> +	// IdentitySelector is a selector for Endpoints
Fix this naming? It is confusing.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/decision.go
> +// Decision is a reachability policy decision
... policy-reachability decision.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/decision.go
> +	// Undecided means that we have not come to a decision yet
I don't like the use of 'we' in public APIs. 
"... specifies that whether policy allows or denies traffic is not able to be determined." ?

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/decision.go
> +	// Denied means that reachability is denied
denied.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/decision.go
> +	// Allowed means that reachability is allowed
allowed.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/decision.go
> +// String returns the decision in human readable format
human-readable format.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/decision.go
> +// UnmarshalJSON parses a JSON formatted buffer and returns a decision
" ... attempts to unmarshal the contents of b into a Decision". 

Also, this does not return a decision, it returns an error.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/decision.go
> +// MarshalJSON returns the decision as JSON formatted buffer
as a JSON-formatted buffer.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/doc.go
> +// Package api defines the API of the Cilium network policy interface
Fix this documentation

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/http.go
> +// optional, if all fields are empty or missing, the rule does not have any
... optional; if all fields ...

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +// optional, if all fields are empty or missing, the rule will match all
... optional; if all fields...

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +	// necessary to perform certain higher level Kafka operations such as "produce"
higher-level

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +	// to perform the specified higher level operation.
higher-level

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +	// This field is incompatible with the APIKey field, either APIKey or Role
... field; either ...

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +	// request, e.g. "produce", "fetch", "createtopic", "deletetopic", et al
et al --> et al.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +	// This is a user supplied identifier for the client application. The
user-supplied

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +	// want to monitor not just the requests per second overall, but the
per-second

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +	// characters as per recent Kafka spec and allowed characters are
spec. Allowed characters...

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +	// reasons we are using 255
255.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +	// via the
via the ... ?

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +	// be expanded as per the value of Role
... Role.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +	// apiVersionInt is the integer representation of APIVersion
APIVersion.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +// request
request.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +// any topic
topic.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +// KafkaAPIKeyMap is the map of all allowed kafka API keys
kafka --> Kafka

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +// KafkaReverseApiKeyMap is the map of all allowed kafka API keys
kafka --> Kafka

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +// be expanded as per the value of Role
... Role.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +// KafkaMaxTopicLen is the maximum character len of a topic.
len --> length.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +// Older Kafka versions had longer topic lengths of 255, in Kafka 0.10 version
... of 255; in Kafka...

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +// using 255
255.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +// in kafka topic name.
kafka --> Kafka.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +// it is allowed else false
returns if it is allowed.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +// any API version is allowed
allowed.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/kafka.go
> +// MapRoleToAPIKey maps the Role to the low level set of APIKeys for that role
... low-level ... for that role.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule.go
> +// labels contained in the endpointSelector
endpointSelector.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule.go
> +type IngressRule struct {
Documentation?

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule.go
> +type EgressRule struct {
Documentation?

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule.go
> +type IdentityRule struct {
Documentation?

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule.go
> +// K8sServiceNamespace is an abstraction for the k8s service + namespace types.
k8s --> Kubernetes

I do not think we should not be using abbreviations in publicly-facing documentation.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule.go
> +	ServiceName string `json:"serviceName,omitempty"`
Documentation?

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule.go
> +	// K8sServiceSelector selects services by k8s labels and namespace
Kubernetes labels and namespace.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule.go
> +	// K8sService selects service by name and namespace pair
... pair.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule.go
> +// PortProtocol specifies an L4 port with an optional transport protocol
protocol.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule.go
> +	// Rules is a list of additional port level rules which must be met in
port-level

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule.go
> +// L7Rules is a union of port level rule types. Mixing of different port
port-level

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule.go
> +// If none are specified, then no additional port level rules are applied.
port-level

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule.go
> +// ServiceSelector is a label selector for k8s services
k8s --> Kubernetes

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule.go
> +// Entities specifies the class of receiver/sender endpoints that do not have individual identities.
Fix documentation.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule.go
> +	// EntityWorld is an entity that represents traffic external to endpoint's cluster
cluster.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule.go
> +	// EntityHost is an entity that represents traffic within endpoint host
within an endpoint's host.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule.go
> +	// EntityAll is an entity that represents all traffic
all traffic.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule.go
> +// EntitySelectorMapping maps special entity names that come in policies to selectors
to selectors.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule.go
> +// CIDRMatchAll is a []CIDR that matches everything
everything.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule.go
> +// L4Proto is a layer 4 protocol name
name.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule_validation.go
> +	l3Members := map[string]bool{
Add a comment specifying what exactly this represents, specifically that we do not support combinations of any of the contents of `L3Members` together.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/rule_validation.go
> +// Sanitize sanitizes Kafka rules
... rules.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/selector.go
> +// Hash return hash of the internal json structure that represents the identity selector
... returns the hash ... selector.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/selector.go
> +// NewWildcardIdentitySelector returns a selector that matches on all identities
identities.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/selector.go
> +// where it the given srcPrefix will be encoded in the label's keys.
... where the given...

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/utils.go
> +// Exists returns true if the HTTP rule already exists in the list of rules
list of rules.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/utils.go
> +// Equal returns true if both HTTP rules are equal
are equal.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/utils.go
> +// Exists returns true if the HTTP rule already exists in the list of rules
in the list of rules.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/utils.go
> +// Validate returns an error if the layer 4 protocol is not valid
valid.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/utils.go
> +// NumRules returns the total number of L7Rules configured in this PortRule
PortRule.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/utils.go
> +// ParseL4Proto parses a string as layer 4 protocol
protocol.

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/v2tov3.go
> +// V2RulesTov3RulesSanitized translates the given v2Rules to the respective v3
"to their respective v3 counterparts"

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/v2tov3.go
> +// All given v2Rules needs to be sanitized and the returned v3 Rules needs to
needs --> need

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/v2tov3.go
> +func v2ESTov3ES(v2ES *v2.EndpointSelector) *IdentitySelector {
I'm not a big fan of these abbreviated function names. I prefer verbosity in this case (ES --> EndpointSelector).

2018-03-22 18:49 UTC, ianvernon commented on pkg/policy/api/v3/v2tov3_test.go
> +	// TODO: Add test cases.
I'm not for merging this before we add extensive testing to be sure we translate rules effectively.

2018-03-22 18:49 UTC, ianvernon commented on pkg/k8s/apis/cnp.cilium.io/register.go
> +	// GroupName is the group name of the cilium network policy
cilium network policy --> CiliumNetworkPolicy.

2018-03-22 18:49 UTC, ianvernon commented on pkg/k8s/apis/cnp.cilium.io/utils/utils.go
> +	// subsysK8s is the value for logfields.LogSubsys
logfields.LogSubsys.

2018-03-22 19:12 UTC, aanm commented
/test-me-please

2018-03-22 19:20 UTC, tgraf commented
test-me-please

2018-03-22 19:45 UTC, aanm commented
test-me-please

2018-03-22 19:51 UTC, aanm commented
test-me-please

2018-03-22 20:12 UTC, aanm commented
@ianvernon all of the descriptions were copy-paste from the v2. We can address those in a later PR. I'll add the CRD validation as well the missing field descriptions in this PR. Although the unit tests do not exist in `pkg/policy/v3` they are being covered by the unit tests in `pkg/policy` where some of the more complicated existing v2 rules are translated into v3 and them the unit tests are executed.

2018-03-22 20:30 UTC, aanm commented
test-me-please

2018-03-22 21:50 UTC, aanm commented
test-me-please

2018-03-22 22:58 UTC, aanm commented
test-me-please

2018-03-23 00:21 UTC, aanm commented
test-me-please

2018-03-23 00:38 UTC, aanm commented
test-me-please

2018-03-23 01:11 UTC, aanm commented
test-me-please

2018-03-23 01:52 UTC, aanm commented
test-me-please

2018-03-23 01:52 UTC, aanm commented
test-nightly

2018-03-23 01:52 UTC, aanm commented
test-missed-k8s

2018-03-23 10:54 UTC, aanm commented
test-me-please

2018-03-23 20:26 UTC, aanm commented
test-me-please

2018-03-23 22:17 UTC, aanm commented
test-me-please

2018-03-24 00:33 UTC, aanm commented
test-me-please

2018-03-24 11:34 UTC, aanm commented
test-me-please

2018-03-24 12:14 UTC, aanm commented
test-me-please

2018-03-25 18:49 UTC, aanm commented
test-me-please

2018-03-25 19:32 UTC, aanm commented
test-me-please

2018-03-25 21:14 UTC, aanm commented
test-nightly

2018-03-25 21:14 UTC, aanm commented
test-missed-k8s

2018-03-26 05:16 UTC, manalibhutiyani commented
@aanm Could you rebase to include the Kafka CI fixes?

2018-03-26 07:06 UTC, aanm commented
test-me-please

2018-03-26 07:06 UTC, aanm commented
test-missed-k8s

2018-03-26 09:15 UTC, aanm commented
test-me-please

2018-03-26 09:15 UTC, aanm commented
test-missed-k8s

2018-03-26 11:16 UTC, aanm commented
test-missed-k8s

2018-03-27 00:38 UTC, joestringer commented
When I was testing over the weekend, one of my primary concerns was that the v2->v3 conversion was resulting in a CIDR allow-all when the v2 policy was "allow L4". There's no support for CIDR-dependent L4 currently.
                                                                                
```                                                                             
$ cilium endpoint get 173 | jq '.[0].policy."cidr-policy"'                      
{                                                                               
  "egress": [],                                                                 
  "ingress": [                                                                  
    {                                                                           
      "derived-from-rules": [                                                   
        []                                                                      
      ],                                                                        
      "rule": "0.0.0.0/0"                                                       
    },                                                                          
    {                                                                           
      "derived-from-rules": [                                                   
        []                                                                      
      ],                                                                        
      "rule": "::/0"                                                            
    }                                                                           
  ]                                                                             
}                                                                               
``` 

Did we come to a solution to this?

2018-03-27 15:26 UTC, aanm commented
test-me-please

2018-03-27 15:26 UTC, aanm commented
test-me-please

2018-03-27 15:36 UTC, aanm commented
test-me-please

2018-03-27 23:34 UTC, aanm commented
test-me-please

2018-03-27 23:34 UTC, aanm commented
test-missed-k8s

2018-03-27 23:34 UTC, aanm commented
test-nightly

2018-03-28 00:23 UTC, aanm commented
test-me-please

2018-03-28 01:57 UTC, aanm commented
test-me-please

2018-03-28 01:57 UTC, aanm commented
test-nightly

2018-03-28 01:58 UTC, aanm commented
test-missed-k8s

2018-03-28 15:56 UTC, tgraf approved these changes

2018-03-28 17:53 UTC, aanm commented
test-me-please

2018-03-28 19:28 UTC, aanm commented
test-me-please

2018-03-28 19:41 UTC, aanm commented
test-me-please

2018-03-28 20:21 UTC, aanm commented
test-me-please

2018-03-28 21:17 UTC, ianvernon approved these changes

2018-03-28 21:39 UTC, aanm commented
test-me-please

2018-03-28 21:44 UTC, aanm commented
test-me-please

2018-03-28 23:40 UTC, aanm commented
test-me-please

2018-03-29 10:29 UTC, aanm commented
test-me-please

2018-03-29 13:06 UTC, aanm commented
test-me-please

2018-03-29 14:40 UTC, aanm commented
test-me-please

2018-03-29 15:06 UTC, aanm commented
test-me-please

2018-03-29 15:30 UTC, aanm commented
test-me-please

2018-03-29 16:51 UTC, aanm commented
test-me-please

2018-03-29 17:10 UTC, aanm commented
test-me-please

2018-03-29 18:26 UTC, aanm commented
test-me-please

2018-03-29 19:25 UTC, aanm commented
test-me-please

2018-03-29 19:52 UTC, aanm commented
test-me-please

2018-08-23 00:37 UTC, closed without merging