Misc BGP Control Plane documents
cilium/cilium pull request #31670
Opened 2024-03-29 08:39 UTC by YutaroHayakawa

Some small document changes.

```release-note
Misc BGP Control Plane documents
```

2024-04-02 07:35 UTC, rastislavs approved these changes
LGTM with some small wording nits

2024-04-02 07:35 UTC, rastislavs commented on Documentation/network/bgp-control-plane-operation.rst
> +You can check the BGP Control Plane logs from the Cilium agent logs. The logs
```suggestion
BGP Control Plane logs can be found in the Cilium agent logs. The logs
```

2024-04-02 07:35 UTC, rastislavs commented on Documentation/network/bgp-control-plane-operation.rst
> +following:
```suggestion
are tagged with ``subsys=bgp-control-plane``. You can use this tag to filter
the logs as in the following example:
```

2024-04-02 17:22 UTC, ghost requested changes
Requesting small changes, but looks good overall!

2024-04-02 17:22 UTC, lambdanis commented on Documentation/network/bgp-control-plane-operation.rst
> +.. code-block:: bash
```suggestion
.. code-block:: shell-session
```
See https://docs.cilium.io/en/stable/contributing/docs/docsstyle/#code-blocks (last point)

2024-04-02 17:22 UTC, ghost commented on Documentation/network/bgp-control-plane-operation.rst
> +  (``restartTimeSeconds``) and cause the BGP peer to withdraw routes.
Can you refactor it as a regular paragraph instead of a bullet point? This single bullet point looks a bit out of context here.

2024-04-02 17:28 UTC, lambdanis commented
Are these improvements relevant for Cilium v1.15 or older? (i.e.: should this PR get backported?)

2024-04-05 00:50 UTC, YutaroHayakawa commented
> Are these improvements relevant for Cilium v1.15 or older? (i.e.: should this PR get backported?)


I'd backport the latest document at once to v1.15 instead of backporting individual PRs.

2024-04-05 12:27 UTC, lambdanis approved these changes

2024-04-08 07:49 UTC, YutaroHayakawa commented
/test

2024-04-08 07:57 UTC, merged