ingress: control request timeout via annotation
cilium/cilium pull request #31693
Opened 2024-04-01 00:26 UTC by a5r0n

2024-04-02 14:13 UTC, a5r0n commented
@youngnick @mhofstetter can you guys please have a look? 🙏🏻

2024-04-05 03:12 UTC, youngnick commented
Thanks for this PR, @a5r0n, it's a great PR that has tests and is reasonably complete. So there are no code issues, and it _could_ make it in.

However, I think we may need to take a more holistic look at Envoy timeouts - there are a lot of timeouts, and what they mean is not always clear. For example, if we add request timeout, should we add any of the other timeouts as well?

For this reason, I think we'll need to take some time to consider here. This isn't great timing though because myself and @mhofstetter are both going to be on leave for the next couple of weeks. Sorry about the delay, but we'll have to check back in with you once we're back.

2024-04-05 05:12 UTC, a5r0n commented
@youngnick 
The main reason for this PR is to take another approach for #31514.
this PR is simply matching the behaviour and options of `Gateway API` in `Ingress` objects. 
so as long the currently envoy settings works for GatewayAPI, any further discussion about envoy-side of things are not directly connected...

https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.HTTPRouteTimeouts
https://github.com/cilium/cilium/blob/77cafec711d62033a2c15771f4f52d67496eca09/operator/pkg/model/ingestion/gateway.go#L275

2024-04-29 10:47 UTC, saintdle commented
> Ping @youngnick and @mhofstetter

I believe they are still out currently, you might need to wait just a little longer for another review :)

2024-05-02 09:11 UTC, aanm commented
/test

2024-05-02 11:39 UTC, a5r0n commented
@aanm i fixed the formatting errors & rebase.

2024-05-02 15:19 UTC, aanm commented
/test

2024-05-03 06:00 UTC, youngnick requested changes
Thanks for your work on this PR @a5r0n. I can see that you'll need to ensure that your all your commits are signed for this to be able to move forward.

In terms of functionality, I want to be clear that the only timeouts that we'll accept as annotation to Ingress objects are ones that we've already implemented in Gateway API. This means this timeout, and possibly one other.

Envoy currently has about _twenty_ timeouts, we will not be exposing all of those as annotations, that's way too many.

Just want to be clear for anyone reading this in the future that this PR isn't a precedent.

However, in this PR, you're making two changes:
- adding an annotation to change the request timeout
- setting the request timeout to 60 seconds by default.

The second one is actually a _much_ bigger change than it might seem, so I've recommended that we back it out, which will need some further changes.

There's also a few other things, but they're not huge, just more testing and error checking. This is looking pretty good.

2024-05-03 06:00 UTC, youngnick commented on operator/pkg/ingress/annotations/annotations.go
> +
In here, `val` also needs to be checked for valid formatting.

Per the Envoy [protobuf docs](https://protobuf.dev/reference/protobuf/google.protobuf/#duration), this is a number followed by an "s" to represent the number of seconds. (You're using this format later, but we need to ensure that "1y" or "2d5h1s" don't work.)

Please also add tests in `annotations_test.go` to ensure that only valid values will be accepted.

As part of this, you'll also need to change the function signature to return an error so we can check for the invalid case. GetAnnotationSecureNodePort and GetAnnotationHostListenerPort are good examples here, both in this file and at the calling location.

2024-05-03 06:00 UTC, youngnick commented on operator/pkg/ingress/cell.go
> +		IngressDefaultRequestTimeout: "60s",
This will set the default for _all_ Ingress objects to 60s, which may be a breaking change.

I think that this needs to be left set at the empty string, so that existing installs will not be changed.

The settings we want here is:
- existing installs: no timeout change
- if you specify the `ingress-default-request-timeout` flag, the timeout will be defaulted to what you set
- if you specify the annotation on an Ingress, that will always override all other settings for that Ingress, including if you set the default request timeout using the flag.

This means that the timeout handling will need to handle an empty string for a timeout, which means "don't send any config and use Envoy's defaults".

2024-05-03 06:00 UTC, youngnick commented on operator/pkg/model/ingestion/ingress.go
> +
This needs to be in a
```go
if defaultRequestTimeout != "" {
```
block, so that in the case that it's unset in the annotation _and_ the flag, nothing happens.

There also needs to be tests to ensure that's how everything works.

2024-05-03 06:00 UTC, youngnick commented on operator/pkg/ingress/cell.go
> +	flags.String("ingress-default-request-timeout", r.IngressDefaultRequestTimeout, "Default request timeout for Ingress.")
This flag also needs to be checked for correct formatting somewhere in `registerReconciler`, with a formatting error meaning that the operator will fail to start. It should log an error as well. see lines like line 103 for an example.

2024-05-03 06:00 UTC, youngnick commented on operator/pkg/model/ingestion/ingress.go
> +	requestTimeout, _ := time.ParseDuration(defaultRequestTimeout)
Just in case, if this `ParseDuration` call fails, we should log an error message that we are ignoring it, and not take any action using the timeout as a result.

This should also be tested as part of the ingestion tests, that an invalid value will be ignored.

2024-05-03 06:00 UTC, youngnick commented on operator/pkg/model/ingestion/ingress_test.go
> +				Timeout: model.Timeout{
If the annotation is invalid, the value should either be:
- the value of the default flag, if set
- no Timeout otherwise.

This will need one extra test.

2024-05-03 09:44 UTC, a5r0n commented on operator/pkg/ingress/annotations/annotations.go
> +
The annotation value can be any Go duration value, as the actual conversion occurs downstream within the `timeoutMutation` function.
`model.Timeout` takes go time.Duartion value, so even `2d5h` can be valid annotation value..

2024-05-03 12:37 UTC, a5r0n commented on operator/pkg/ingress/cell.go
> +	flags.String("ingress-default-request-timeout", r.IngressDefaultRequestTimeout, "Default request timeout for Ingress.")
fixed using flags.Duration for this

2024-05-03 12:42 UTC, a5r0n commented
@youngnick let me know what you think on this changes.
Thanks!

2024-05-06 07:37 UTC, youngnick commented on operator/pkg/ingress/annotations/annotations.go
> +
Oh, I didn't read that part closely enough, thanks! That's fine then, thanks for changing everything to use Durations properly.

2024-05-06 07:42 UTC, youngnick approved these changes
Okay, thanks for those changes, this LGTM. Nice work on this one!

2024-05-06 07:59 UTC, mhofstetter requested changes
@a5r0n please squash the commits into one and give it a meaningful description. Then we can kick off the checks and get this merged.

Thanks!

2024-05-06 08:49 UTC, a5r0n commented
@mhofstetter done!

2024-05-06 09:06 UTC, mhofstetter commented
> @mhofstetter done!

Thanks! I kicked off the tests. 

In the meantime it would be great if you could update the PR description to at least include a quick resume of the new feature with the names of the new Operator flag and Ingress annotation. Currently it still reads like some work in progress :)

You can relate to https://github.com/cilium/cilium/pull/31514 with `Related to: #31514` at the end of the description

2024-05-06 09:56 UTC, mhofstetter approved these changes
LGTM - thanks for the changes and the contribution!

2024-05-07 02:05 UTC, merged