v1.14 Backports 2024-04-02
cilium/cilium pull request #31724
Opened 2024-04-02 12:17 UTC by joamaki

* [x] #29300 (@learnitall)
 * [x] #31488 (@bimmlerd)
 * [x] #31478 (@julianwiedmann)
 * [x] #31594 (@qmonnet)
 * [x] #31635 (@pchaigno)
 * [x] #31622 (@gandro)
 * [x] #31627 (@pchaigno)
 * [x] #31104 (@tamilmani1989)
 * [x] #31641 (@tklauser)
 * [x] #31652 (@qmonnet)

PRs skipped due to conflicts:

 * #31407 (@tommyp1ckles)
 * #31328 (@nathanjsweet)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 29300 31488 31478 31594 31635 31622 31627 31104 31641 31652
```

2024-04-02 12:18 UTC, joamaki commented
@bimmlerd @tklauser same type of conflicts as with v1.13 here.

2024-04-02 12:19 UTC, joamaki commented
@tommyp1ckles skipped the node-map-max as the HeaderWriter wasn't modularized. Could you take a look at doing a manual backport for it?

@nathanjsweet skipped as proxyPolicy struct didn't exist. Could you take a look at whether we need to backport more commits or if there's another way to do it?

2024-04-02 12:41 UTC, bimmlerd approved these changes

2024-04-02 13:31 UTC, joamaki commented
/test-backport-1.14

2024-04-03 13:50 UTC, qmonnet approved these changes
Thanks!

2024-04-03 13:58 UTC, tklauser approved these changes
Looks good for my changes, thanks.

2024-04-03 17:20 UTC, learnitall approved these changes
Thanks!

2024-04-03 20:50 UTC, pchaigno requested changes
There's the same issue as for v1.13: https://github.com/cilium/cilium/pull/31627 wasn't backported because the file moved. The code to edit can be found in `.github/workflows/conformance-ipsec-e2e.yaml`.

2024-04-04 12:05 UTC, pchaigno commented on .github/workflows/conformance-ipsec-e2e.yaml
> +              echo "Waiting until key rotation completes (seeing $keys_in_use keys, expected $exp_nb_keys)"
Same here regarding `starts` -> `completes`.

2024-04-04 12:26 UTC, joamaki commented on .github/workflows/conformance-ipsec-e2e.yaml
> +              echo "Waiting until key rotation completes (seeing $keys_in_use keys, expected $exp_nb_keys)"
Fixed here as well.

2024-04-04 12:28 UTC, pchaigno approved these changes
All good for my PRs. Thanks!

2024-04-04 12:35 UTC, julianwiedmann approved these changes
@tklauser maybe you could have a look at Sebastian's PR as well? :pray:

2024-04-04 13:08 UTC, tklauser approved these changes
> @tklauser maybe you could have a look at Sebastian's PR as well? 🙏

Sure. Backport of #31622 looks good to me, thanks!

2024-04-04 14:48 UTC, joamaki commented
/test-backport-1.14

2024-04-04 16:18 UTC, merged