Loader reconciliation preparatory changes
cilium/cilium pull request #31773
Opened 2024-04-04 11:37 UTC by dylandreimerink

We are slowly moving towards a loader that is resilient and reconciles whenever device changes are detected. Currently we have datapath logic to detect device changes, this needs to be reported up all the way to the Daemon which then pushes Reinitilization requests all the way down to the loader. This PR contains a number of preparatory changes that will make it easier for a followup PR to make the datapath / loader reconcile without going through the daemon, based on the devices table.

This PR removes the `BaseProgramOwner` which was one big layer violation. All dependencies the loader needs are now passed via Hive. Only the actual Reinitialize calling still exists, which will be replaced by device based reconciliation in a followup.

2024-04-05 15:59 UTC, dylandreimerink commented
/test

2024-04-09 09:22 UTC, dylandreimerink commented
/test

2024-04-09 14:11 UTC, joamaki commented on pkg/datapath/types/orchistrator.go
File name typo

2024-04-10 08:57 UTC, dylandreimerink commented
/test

2024-04-10 13:19 UTC, lmb requested changes
Loader changes look good to me.

2024-04-10 13:19 UTC, lmb commented on pkg/datapath/types/loader.go
> +type CompilationLock interface {
Can you document why this is a separate type please? I imagine it has something to do with the fact that it's taken from all over the place. Future me would also very much be interested to know at which point we could get rid of this.

2024-04-16 14:00 UTC, dylandreimerink commented
/test

2024-04-17 12:41 UTC, lmb approved these changes

2024-04-23 11:11 UTC, tklauser approved these changes
Looks good for @cilium/ci-structure (re-adding review requests for the other code owners which I didn't cover).

2024-04-23 13:44 UTC, gentoo-root approved these changes
Great cleanup of dependencies!

2024-04-23 13:44 UTC, gentoo-root commented on pkg/datapath/types/loader.go
> +// CompilationLock is a interface over a mutex, it is used by both the loader, deamon
Nit: deamon -> daemon.

2024-04-23 13:44 UTC, gentoo-root commented on daemon/cmd/config.go
Nit: typo in the commit message: "orchistrator".

2024-04-23 13:44 UTC, gentoo-root commented on pkg/proxy/cell.go
> -	Datapath    datapath.Datapath
Nit: typo "Manger".

2024-04-23 20:19 UTC, tommyp1ckles approved these changes

2024-04-24 14:49 UTC, jrajahalme approved these changes
LGTM for the proxy files.

2024-04-25 08:45 UTC, ti-mo commented
A few unresolved conversations that should be addressed before merging. Looks like `ci-e2e-upgrade` is not required at the moment, but there's one connection interruption during upgrade. Could it be related?

2024-04-25 11:22 UTC, dylandreimerink commented
/test

2024-04-29 10:15 UTC, dylandreimerink commented
/test

2024-04-29 12:45 UTC, merged