fqdn: Fix Restore Check Logic
cilium/cilium pull request #31784
Opened 2024-04-05 01:07 UTC by nathanjsweet

Sometimes restored IPRules do not have the
default "nil" populating their IP maps, but 
instead have an empty map structure.
We need to check for this restore possibility.

```release-note
fqdn: Fix minor restore bug that causes false negative checks against a restored DNS IP map.
```

2024-04-05 07:57 UTC, pippolo84 requested changes
Just out of curiosity, what's the path that leads to an empty map instead of a nil one?

2024-04-05 07:57 UTC, pippolo84 commented on pkg/fqdn/dnsproxy/proxy.go
> +		if _, exists := ipRule.IPs[destIP]; exists || ipRule.IPs == nil || len(ipRule.IPs) == 0 {
`len(ipRule.IPs) == 0` will cover both cases (map is `nil` and map is `empty`).

2024-04-05 15:57 UTC, nathanjsweet commented
/test

2024-04-05 16:12 UTC, pippolo84 approved these changes
LGTM :100:

2024-04-05 18:49 UTC, nathanjsweet commented
> Just out of curiosity, what's the path that leads to an empty map instead of a nil one?

This is using the library for another project. Given that the restore objects can be marshalled in and out of various data formats (like JSON, for example)  this is good code hygiene.

2024-04-05 20:27 UTC, merged

2024-05-03 13:12 UTC, julianwiedmann commented
Backported with https://github.com/cilium/cilium/pull/31872, https://github.com/cilium/cilium/pull/31871, https://github.com/cilium/cilium/pull/31870