labels: Add controller-uuid into default ignore list
cilium/cilium pull request #31964
Opened 2024-04-15 15:34 UTC by sayboras

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note

```

2024-04-15 22:55 UTC, sayboras commented
/test

2024-04-16 11:49 UTC, lambdanis approved these changes
docs good

2024-04-16 13:00 UTC, aanm requested changes
I think there's some confusion in the code and documentation has they both mention `uid` and `uuid`. I think it should be either one or the other but not both.

2024-04-17 03:22 UTC, sayboras commented
/test

2024-04-17 03:37 UTC, sayboras commented
> I think there's some confusion in the code and documentation has they both mention `uid` and `uuid`. I think it should be either one or the other but not both.

Good catch, thanks.

2024-04-17 03:37 UTC, sayboras commented
/test

2024-04-17 12:25 UTC, squeed approved these changes

2024-04-18 10:33 UTC, aanm requested changes

2024-04-18 10:33 UTC, aanm commented on pkg/labelsfilter/filter.go
> +		"!" + regexp.QuoteMeta(k8sConst.BatchJobControllerUID),          // ignore batch.kubernetes.io/controller-uuid
```suggestion
		"!" + regexp.QuoteMeta(k8sConst.BatchJobControllerUID),          // ignore batch.kubernetes.io/controller-uid
```

2024-04-18 10:33 UTC, aanm commented
there's no need to backport this patch to older releases. I've marked it to be backported to v1.15 only

2024-04-18 10:52 UTC, sayboras commented
/test

2024-04-18 11:08 UTC, aanm approved these changes

2024-04-18 12:15 UTC, merged