Docs: improve Flatcar section
cilium/cilium pull request #31986
Opened 2024-04-16 09:47 UTC by darox

This commit makes it more clear, that
Flatcar only faces issues on AWS EKS ENI
mode.

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

This commit makes it more clear, that Flatcar only faces issues on AWS EKS ENI mode.

2024-04-16 09:51 UTC, gandro approved these changes
Thanks!

2024-04-16 09:55 UTC, aspsk approved these changes

2024-04-16 09:56 UTC, qmonnet requested changes

2024-04-16 09:56 UTC, qmonnet commented on Documentation/operations/system_requirements.rst
> +them as unmanaged.
We still need to introduce the coming configuration snippet:

```suggestion
them as unmanaged. To do so, add the following configuration options to ``/etc/systemd/network/01-no-dhcp.network``::

    [Match]
    Name=eth[1-9]*
    [Network]
    DHCP=no
    [Link]
    Unmanaged=yes

Then run:
```

Then the systemctl commands

2024-04-16 15:35 UTC, qmonnet requested changes
Sorry for the confusion, I didn't mean to accept my suggestion “as-is”: I copied the block that was coming below, because I couldn't create a suggestion on that block in the GitHub interface. But the block is not duplicated:

![image](https://github.com/cilium/cilium/assets/17001771/4a9739ac-bd34-4de9-86e2-c3cdc021c9b2)

Please fix (and wrap the last line of the paragraph).

2024-04-16 15:45 UTC, darox commented
> Sorry for the confusion, I didn't mean to accept my suggestion “as-is”: I copied the block that was coming below, because I couldn't create a suggestion on that block in the GitHub interface. But the block is not duplicated:
> 
> ![image](https://private-user-images.githubusercontent.com/17001771/322908197-4a9739ac-bd34-4de9-86e2-c3cdc021c9b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODI2MDUsIm5iZiI6MTcxMzI4MjMwNSwicGF0aCI6Ii8xNzAwMTc3MS8zMjI5MDgxOTctNGE5NzM5YWMtYmQzNC00ZGU5LTg2ZTItYzNjZGMwMjFjOWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE1NDUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5OGQ3YzlmZWZhZjU5N2NjODQ4ZmRmMGNiOGRiNWI0MDNiMTY3NjY2NjQ0NDhjZDMzYTU3YjcyMWQ5OGIyYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iV_uN1iWtuNE7j4ZFEkkZrEOc1LMzZQKLn2r3m2VoxA)
> 
> Please fix (and wrap the last line of the paragraph).

I'm sorry for the mess I did. Should be fine now.

2024-04-16 16:05 UTC, qmonnet approved these changes

2024-04-16 16:05 UTC, qmonnet commented
Thanks!

2024-04-16 17:51 UTC, joestringer commented
/test

2024-04-17 07:21 UTC, lambdanis approved these changes

2024-04-17 13:17 UTC, merged