Fix invalid PromQL query in the Cilium Metrics Grafana dashboard
cilium/cilium pull request #32017
Opened 2024-04-17 03:11 UTC by mikemykhaylov

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

The existing query for the Policies per Node chart in the Cilium Metrics dashboard in the `monitoring-example.yaml` contained invalid PromQL. Additionally, the correct value to be filtered on is "failure", not "fail".

<img width="1272" alt="Screenshot 2024-04-16 at 20 02 06" src="https://github.com/cilium/cilium/assets/32168861/06535f2a-c174-4e5b-847e-496091dc8091">

2024-04-22 15:25 UTC, joamaki approved these changes

2024-04-22 15:26 UTC, joamaki requested changes
Looks good, but please remove the merge commit.

2024-04-22 15:34 UTC, mikemykhaylov commented
Should be good now

2024-05-02 09:20 UTC, aanm commented
/test

2024-05-07 08:01 UTC, joamaki approved these changes

2024-05-07 08:01 UTC, joamaki commented
/test

2024-05-13 10:36 UTC, julianwiedmann commented
/test

2024-05-13 12:18 UTC, julianwiedmann commented
Added backport labels, sounds like this is essentially a docs bug.

2024-05-13 12:25 UTC, merged