Fix helm chart incompatible types for comparison
cilium/cilium pull request #32025
Opened 2024-04-17 11:30 UTC by lou-lan

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Fixes: #32024

```release-note
Fix helm chart incompatible types for comparison
```

2024-04-17 11:42 UTC, gandro approved these changes
Thanks!

2024-04-17 11:45 UTC, gandro requested changes
Actually, I believe `(ne (quote $kubeProxyReplacement) "strict")` will now always be false. Would `toString` work instead of `quote`?

2024-04-17 12:29 UTC, gandro approved these changes

2024-04-17 12:29 UTC, gandro commented
/test

2024-04-22 09:18 UTC, aanm approved these changes

2024-04-22 09:26 UTC, merged