[debug] Always include debug symbols in the agent debug image
cilium/cilium pull request #32032
Opened 2024-04-17 16:08 UTC by EricMountain

Currently, the Cilium upstream CI is capable of building stripped binary images and unstripped binary images. Release builds only deliver stripped images. It’s not possible to recover/obtain the symbols for stripped images.

Also, given the current Docker files share the NOSTRIP value across `debug` and `release` targets. So it’s not possible to build both and use the debug symbols of the `debug` images to interpret the `release` binaries (the binaries are built twice, so the symbols don’t match).

This prohibits performing profiling of `release` images with post-processing to associate the symbols for instance. It also means that in order to live-debug for instance, one needs to go and build the `debug` images before deploying them.

With this change it becomes possible to deliver `debug` and `release` images with symbols:

- If the build is invoked with `NOSTRIP=0`, then the `release` image has stripped binaries and the `debug` image has stripped binaries + debug symbol files in `/usr/lib/debug`.
- If the build is invoked with `NOSTRIP=1`, then the `release` image has non-stripped binaries and the `debug` image has non-stripped binaries + debug symbol files in `/usr/lib/debug`.

This ensures the Cilium Agent `debug` image always has symbols available, so e.g. Delve works, regardless of the NOSTRIP setting at build. It also means we can deploy the `release` image, but use the symbols found in the corresponding `debug` image to perform post-processing of profiles for instance. It also makes it trivial to deploy the `debug` image in place of the `release` image in order to perform live debugging using the exact same builds.

If folks agree with the value of this, it could be extended to other components such as the Operator, however this change is scoped to the Agent.

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

```release-note

Always include symbols in the Agent debug image.
```

2024-04-30 12:32 UTC, nebril commented on images/cilium/Dockerfile
> +         if [ "$NOSTRIP" != "1" ] ; then objcopy --strip-all ${0} && (cd $(dirname ${0}) && objcopy --add-gnu-debuglink=${filename}.debug ${filename}) ; fi && \
Why do we need to strip binaries here and not rely on `NOSTRIP` argument given to `make` on line 50 and 57?

Would it be enough to leave `NOSTRIP` as-is on lines 50 and 57 and not strip binary here, just extract debug symbols?

2024-05-02 09:21 UTC, aanm commented
/test

2024-05-17 12:18 UTC, nebril requested changes
Changing my review to Request changes. Please re-request review after you address feedback.

2024-05-24 09:23 UTC, EricMountain commented on images/cilium/Dockerfile
> +         if [ "$NOSTRIP" != "1" ] ; then objcopy --strip-all ${0} && (cd $(dirname ${0}) && objcopy --add-gnu-debuglink=${filename}.debug ${filename}) ; fi && \
If we allow `NOSTRIP=0` to be passed to `make`, we end up with binaries that contain no symbols (they were stripped), so we have nothing to extract.

The change of logic here is expressly so that we are able to extract and preserve symbols regardless of whether the final binaries will contain symbols or not. We need `make` to always produce binaries with symbols for this to work.

2024-05-24 13:36 UTC, nebril approved these changes
LGTM, thanks for the change!

2024-05-24 13:36 UTC, nebril commented on images/cilium/Dockerfile
> +         if [ "$NOSTRIP" != "1" ] ; then objcopy --strip-all ${0} && (cd $(dirname ${0}) && objcopy --add-gnu-debuglink=${filename}.debug ${filename}) ; fi && \
This makes sense. Thanks for explaining!

2024-05-30 19:23 UTC, joestringer commented
/test

2024-05-31 10:30 UTC, merged