Doc: Added new step on release
cilium/cilium pull request #3213
Opened 2018-03-20 15:47 UTC by eloycoto

- Added a new step in the release process.
- Added v0.13 branch in the Jenkins configuration to build once per day.

Fixes #3168

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

2018-03-20 16:48 UTC, ianvernon requested changes

2018-03-20 16:48 UTC, ianvernon commented on Documentation/contributing.rst
> +    `Jenkins <https://jenkins.cilium.io/view/all/job/cilium/>`__ to be tested on
Link is incorrect; it points to the Bash tests.

2018-03-20 16:48 UTC, ianvernon commented on Documentation/contributing.rst
> +    `Jenkins <https://jenkins.cilium.io/view/all/job/cilium/>`__ to be tested on
Would be helpful to point to the nightly job that runs for the release branch, as well as the job that runs for each commit.

2018-03-21 18:29 UTC, ianvernon approved these changes

2018-03-23 08:37 UTC, eloycoto commented
test-me-please

2018-03-23 11:49 UTC, merged