daemon: Deprecate EnableRuntimeDeviceDetection
cilium/cilium pull request #32153
Opened 2024-04-24 08:36 UTC by joamaki

Mark the EnableRuntimeDeviceDetection flag deprecated and remove the check for it in device reloader to make runtime reconfiguration the default and only mode of operation.

```release-note
Runtime device detection and subsequent datapath reconfiguration is now the default and only mode of operation.
The enableRuntimeDeviceDetection option is now a no-op and will be removed in v1.17.
```

2024-04-24 12:18 UTC, joamaki commented
/test

2024-04-25 09:01 UTC, bimmlerd commented
/test

2024-04-25 09:03 UTC, bimmlerd approved these changes

2024-04-29 16:39 UTC, joamaki commented
/test

2024-05-01 08:44 UTC, joamaki commented
/test

2024-05-02 18:16 UTC, christarazi approved these changes

2024-05-03 12:12 UTC, squeed requested changes
This should be documented in `Documentation/operations/upgrade.rst` too. Then this looks good to go.

2024-05-07 13:46 UTC, joamaki commented
> This should be documented in `Documentation/operations/upgrade.rst` too. Then this looks good to go.

Ah yes, better not postpone this! Documented the change there.

2024-05-07 13:56 UTC, squeed approved these changes

2024-05-07 15:29 UTC, dylandreimerink approved these changes

2024-05-08 08:04 UTC, joamaki commented
/test

2024-05-08 08:41 UTC, qmonnet approved these changes

2024-05-08 11:46 UTC, merged