[v1.15] Author backport of #31646
cilium/cilium pull request #32178
Opened 2024-04-25 07:56 UTC by mhofstetter

Currently, the translation from Ingress controller & Gateway API resources into the corresponding `CiliumEnvoyConfig` creates two Envoy listeners for TLS passthrough (Ingress annotation or GW-API `TLSRoute`) and HTTP(S) related functionality.

- TLS Passthrough implemented with Envoy [TCPProxy](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/tcp_proxy_filter) network filter
- HTTP(S) implemented with Envoy [HCM](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/http_conn_man#config-http-conn-man) network filter

This works fine for Gateway API and Dedicated Ingresses where the two use-cases are never combined into the same `CiliumEnvoyConfig` - but leads to problems with Shared Ingresses.

Problem 1: Listener name clash

The two listeners have the same name listener - hence only one of them ends up in the configuration (in most of the cases the TLS Passthrough one which appears later in the configuration).

Problem 2: TPROXY redirection to different listeners with same frontend service port

After solving the name clash, there's still an issue with TLS Passthrough and HTTPS using the same "frontend" port 443 (or the corresponding NodePort) on the Ingress Service that is handled by different Envoy listeners. The current implementation (based on TPROXY) is not able to conditionally (HTTPS or TLS Passthrough) forward traffic to one of these two Listeners.

Therefore, this PR merges the two functionalities within the same Envoy listener by using different filterchains and filterchain-matches based on the servernames (SNI).

Fixes: https://github.com/cilium/cilium/issues/31242

Backport of #31646 (HostNetwork support isn't available on v1.15, other smaller conflicts due to refactorings not being backported) 

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 31646
```

2024-04-25 08:10 UTC, mhofstetter commented
/test-backport-1.15

2024-04-25 09:46 UTC, ti-mo requested changes
@mhofstetter Are there upstream commits that mirror the ones here? These should be included in the commit messages.

2024-04-25 10:08 UTC, mhofstetter commented
> @mhofstetter Are there upstream commits that mirror the ones here? These should be included in the commit messages.

@ti-mo done - thanks (note to myself: start using the backporter tool :memo: )

2024-04-25 10:08 UTC, mhofstetter commented
/test-backport-1.15

2024-04-25 10:18 UTC, ti-mo approved these changes

2024-04-26 03:01 UTC, sayboras approved these changes
Thanks and looks good to me :heavy_check_mark:

2024-04-26 03:01 UTC, merged