Add auto labeler for hubble-cli
cilium/cilium pull request #32343
Opened 2024-05-03 14:26 UTC by aanm

2024-05-03 14:28 UTC, aanm commented
/test

2024-05-03 15:52 UTC, michi-covalent approved these changes
fascinating

2024-05-03 16:09 UTC, brlbil requested changes

2024-05-03 16:09 UTC, brlbil commented on .github/workflows/auto-labeler.yaml
> +    - id: label-the-PR
Step missing name, validation is complaining about it https://github.com/cilium/cilium/actions/runs/8940546996/job/24558885412?pr=32343

2024-05-03 18:28 UTC, aanm commented
/test

2024-05-03 18:55 UTC, brlbil approved these changes

2024-05-04 00:35 UTC, chancez approved these changes

2024-05-07 00:15 UTC, joestringer approved these changes

2024-05-07 00:23 UTC, merged

2024-05-07 18:57 UTC, joestringer commented
```
The configuration file (path: .github/labeler.yml) was not found locally, fetching via the api
Warning: The config file was not found at .github/labeler.yml. Make sure it exists and that this action has the correct access rights.
Error: HttpError: Not Found
Error: Not Found
```

`labeler.yml`, not `labeler.yaml`. PR #32406 should fix it.