Add a `--masquerade-exclusion-cidrs` setting
cilium/cilium pull request #32351
Opened 2024-05-03 21:20 UTC by alvaroaleman

This change adds a new `--masquerade-exclusion-cidrs` setting in order to allow an arbitrary set of CIDRs to be configured to not get masqueraded. This is primarily to deal with
https://github.com/cilium/cilium/issues/20554 by allowing to configure Cilium to exclude all RFC 1918 ranges from masquerading.

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
A new --masquerade-exclusion-cidrs setting was added to allow configuring an arbitrary set of CIDRs to not get masqueraded
```

2024-05-07 07:49 UTC, squeed commented on daemon/cmd/daemon_main.go
> +	option.BindEnv(vp, option.MasqueradeExclusionCIDRs)
I know naming debates are tedious :-/

The Kubernetes terminology for this is nonMasqueradeCIDRs // `--non-masquerade-cidrs`. Should we just mimic that?

2024-05-07 07:50 UTC, squeed commented on pkg/datapath/iptables/iptables.go
> +						"!", "-d", strings.Join(snatDstExclusionCIDRs, ","),
I have been using iptables my entire professional life and I didn't realize you could comma-separate multiple cidrs :exploding_head:

2024-05-07 07:53 UTC, squeed commented
Nice and clean, like it. One naming question otherwise looks good to me.

2024-05-07 17:30 UTC, derailed approved these changes
@alvaroaleman Thank you for this update. Nice work Alvaro!

2024-05-07 21:18 UTC, alvaroaleman commented
I don't think the comma-separating works with negated matches. I am out this week, let me experiment with this a bit more next week and come back

2024-05-14 09:46 UTC, jibi requested changes
I think we are missing the equivalent logic for bpf based masquerading.

One possible approach could be based on populating an LPM map with these excluded CIDRs, and then check in `snat_v4_masquerade` that the destination IP doesn't match this map.

Moreover `remoteSNATDstAddrExclusionCIDR` is used to install both ipv4 and ipv6 rules. We should properly handle the 2 different cases.

2024-05-14 09:46 UTC, jibi commented on pkg/datapath/iptables/iptables.go
> +func (m *Manager) remoteSNATDstAddrExclusionCIDR(nativeRoutingCIDR, allocCIDR string) []string {
nit:
```suggestion
func (m *Manager) remoteSNATDstAddrExclusionCIDRs(nativeRoutingCIDR, allocCIDR string) []string {
```

2024-05-14 09:46 UTC, jibi commented on pkg/datapath/iptables/iptables.go
> +		return []string{nativeRoutingCIDR}
I don't think we should ignore the `nativeRoutingCIDR` or `allocCIDR` CIDRs when `SnatDstExclusionCIDRs` is set (but rather just concat the 2)

2024-05-14 22:06 UTC, alvaroaleman commented
This doesn't quite solve the problem as packages would still leave through the wrong interface, just not without nating so closing this. Sorry for the time spend on reviewing.

2024-05-14 22:06 UTC, closed without merging