policy: Add Port Range Support for Policies
cilium/cilium pull request #32389
Opened 2024-05-06 19:08 UTC by nathanjsweet

See commits.

Fixes: #16622

```release-note
policy: Add support for port ranges in network policies.
```

2024-05-06 20:58 UTC, chancez approved these changes
Updates to Hubble parser tests LGTM.

2024-05-07 03:14 UTC, nathanjsweet commented
/test

2024-05-07 07:07 UTC, mhofstetter approved these changes
nice!

`cli` and `envoy` looks good to me :+1: 

PS: The relevant `cilium/proxy` PRs that added support for port ranges are https://github.com/cilium/proxy/pull/99 & https://github.com/cilium/proxy/pull/373

2024-05-07 07:07 UTC, mhofstetter commented on pkg/envoy/xds_server.go
> +		// Envoy will reject a policy if any overlaps exist.
it seems that Cilium Proxy (Envoy) now has support for overlapping port ranges: https://github.com/cilium/proxy/pull/373 ?

-> maybe adapt the comment accordingly?

2024-05-07 17:53 UTC, joestringer commented
:wave: Just looking from a high level meta approach, the PR is pretty big, coming into around 3.5K lines changed overall. Would it make sense to break this PR down into smaller chunks? As a reviewer I usually prefer that PRs are under 1K lines just to be able to keep things straight in my head, but I also undersand that several of the building blocks here only make sense in context of the broader context of the whole PR here. At a glance at least the bitlpm refactoring could be proposed+merged separately. That would hopefully have no functional impact and would trim ~500 lines or so from the rest to be reviewed in this PR.

2024-05-08 17:39 UTC, learnitall requested changes
I think that the changes to the PortProtocol API object need to be reflected in `./Documentation/security/policy/language.rst`. Can you take a look?

2024-05-08 20:41 UTC, nathanjsweet commented
Going off of @joestringer recommendation, I will break this PR up. Here is the first part:
https://github.com/cilium/cilium/pull/32430

2024-05-09 01:45 UTC, nathanjsweet commented
I'm turning this into a draft for the time being. This does not mean this PR is stalled; it is simply broken up. Part 1 is open for review. I'll open up part 2 as soon as part 1 is merged.

2024-05-21 17:55 UTC, tamilmani1989 commented on pkg/policy/portrange_test.go
> +		{
What's the behavior if endport > 65535 but start is valid. can we also add a test for port range something like 50000-70000?

2024-05-21 19:05 UTC, nathanjsweet commented on pkg/policy/portrange_test.go
> +		{
The underlying type is a uint16 so it is not possible for the value to be greater than 65535. The 2nd part of this PR ([the first part is merged](https://github.com/cilium/cilium/pull/32430)) will validate that the API cannot send an EndPort larger than that to the policy engine.

2024-05-31 18:56 UTC, closed without merging