v1.13 Backports 2024-05-24
cilium/cilium pull request #32696
Opened 2024-05-24 06:48 UTC by YutaroHayakawa

* [ ] #32084 (@pchaigno) :warning: resolved conflicts
 * [ ] #32328 (@joestringer)
 * [ ] #32464 (@darox) :warning: resolved conflicts
 * [ ] #32553 (@michi-covalent) :warning: resolved conflicts
 * [ ] #32564 (@jibi) :warning: resolved conflicts
 * [ ] #32548 (@squeed)
 * [ ] #32570 (@mhofstetter)
 * [ ] #32600 (@mhofstetter) :warning: resolved conflicts
 * [ ] #32302 (@marseel) :warning: resolved conflicts
 * [ ] #32629 (@antonipp) :warning: resolved conflicts

PRs skipped due to conflicts:

 * #32307 (@ferozsalam)
 * #32450 (@jschwinger233)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 32084 32328 32464 32553 32564 32548 32570 32600 32302 32629
```

2024-05-24 06:51 UTC, mhofstetter approved these changes

2024-05-24 08:13 UTC, lmb approved these changes

2024-05-24 09:23 UTC, pchaigno requested changes
It looks like you backported my PR twice, with the second backport being empty.

2024-05-24 09:24 UTC, rolinh commented on api/v1/Makefile
> +CILIUM_BUILDER_IMAGE=quay.io/cilium/cilium-builder:fcf294a0475e9d8b1c8245b97a7e991c20c6ea40
This looks wrong :thinking:

2024-05-24 14:38 UTC, jibi approved these changes

2024-05-24 15:30 UTC, joestringer approved these changes

2024-05-24 15:31 UTC, michi-covalent approved these changes

2024-05-25 01:32 UTC, YutaroHayakawa commented on api/v1/Makefile
> +CILIUM_BUILDER_IMAGE=quay.io/cilium/cilium-builder:fcf294a0475e9d8b1c8245b97a7e991c20c6ea40
Yep, should be fixed now.

2024-05-25 01:39 UTC, YutaroHayakawa commented
> It looks like you backported my PR twice, with the second backport being empty.

Looks like I messed it up when I redo the process once. Fixed now.

2024-05-25 03:51 UTC, YutaroHayakawa commented
/test-backport-1.13

2024-05-27 06:03 UTC, YutaroHayakawa commented
Rebasing to pull-in bfbb9be3ed5f21ee8c4a9452c139d22578894aef.

2024-05-27 08:00 UTC, marseel approved these changes

2024-05-27 08:11 UTC, darox approved these changes
my change looks good

2024-05-27 08:53 UTC, pchaigno approved these changes
Thanks!

2024-05-27 10:24 UTC, squeed approved these changes

2024-05-27 11:49 UTC, YutaroHayakawa commented
/test-1.17-4.19

2024-05-27 11:49 UTC, YutaroHayakawa commented
/test-1.19-4.19

2024-05-27 11:49 UTC, YutaroHayakawa commented
/test-1.25-4.19

2024-05-27 12:34 UTC, rolinh approved these changes

2024-05-28 01:06 UTC, YutaroHayakawa commented
/test-1.17-4.19

2024-05-28 03:14 UTC, merged