enforce device detection v1.16
cilium/cilium pull request #32730
Opened 2024-05-27 11:18 UTC by kvaps

- Introduce --enforce-device-detection option
- Helm chart: enforceDeviceDetection option
- Add tests for EnforceDeviceDetection option

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note

```

2024-05-28 17:20 UTC, ldelossa approved these changes
Overall these changes look OK to me. 

The same set of checks over devices is performed, eliminating the possibility of 'over-selecting'.

2024-05-28 19:41 UTC, joestringer commented
Could you speak a bit about why we need three options for configuring devices? I would have expected one of two:

(a) Auto-detection. Cilium tries its best to select devices, and Cilium is responsible for picking the devices.
(b) Case (a) didn't work for some reason (bug?), so the user wants to override the set of devices. In this case Cilium is clearly *not* responsible for picking the devices.

Case (c) Both Cilium and the user specify devices seems like it confuses who is responsible for this logic, and it's yet another complicated flag in an already complicated set of flags for the agent. Can't we just fix (a) or (b) to better cover your use case?

2024-05-29 06:48 UTC, kvaps commented
@joestringer sure, I can explain. The reason is that we're not end user, we're adopting Cilium together with [kube-ovn](https://github.com/kubeovn/kube-ovn) in [Cozystack](https://github.com/aenix.io/cozystack) a free platform for running managed services. We need kube-ovn as it provides extensive network fabric for running VirtualMachines using KubeVirt.

End users might have various hardware configurations with various interfaces, eg. some of them using bonding and vlan interfaces, some of them are not, so devices must be auto-detected.

But to make this working `ovn0` device should also added to this set. 

The reason I'm insist for adding an extra option and not extend autodetection rules, is that I don't want to break exiting installations. Eg. OpenShift project also uses OVN but different implementation [ovn-kubernetes](https://github.com/ovn-org/ovn-kubernetes). Some other users might want to run Kubernetes with Cilium  on hypervisors with OVN unrelated to the Kubernetes. Eg, Mirantis uses Kubernetes to provision OpenStack platform.

2024-05-29 11:04 UTC, nebril approved these changes
k8s LGTM

2024-05-29 11:26 UTC, joamaki commented
The use-case and the ability to configure this makes sense to me. Though I think we need to consider how to expose this to users. I find `--enforce-device-detection` to be misleading, especially as we had earlier this notion of whether or not to detect any devices at all, so I think it'd be better not to use that wording.

What we essentially want to accomplish here is filter based on contents of  `--devices`, but also apply the normal device filtering/detection logic. My suggestion would be to flip this around and have an option e.g. "--force-devices" (maybe someone can think of a better name) that is set to true by default and has the meaning that "--devices" are chosen without the additional filtering.

Or we could also have a separate option "--device-filter", but that's likely more confusing, both to users and in terms of implementation.

2024-05-29 11:34 UTC, kvaps commented
Original idea was to call it `--enforce-devices-detection`, I renamed it into singular form after `--enable-runtime-deivce-detection`

2024-05-31 10:42 UTC, aanm requested changes
Why doesn't `devices: "en+ ovn0"` work for your use case?

2024-05-31 12:02 UTC, kvaps commented
@aanm I answered here https://github.com/cilium/cilium/pull/32730#issuecomment-2136661151

We provide a platform, which simplifies configuration for users to run VMs and managed services in Kubernetes. Cilium and kube-ovn is used there. The same as you, we want to support device autodetection which would work in various environments. I'll list some of them:


multiple interfaces:
```
eth0 eth1
```

vlan:
```
eth0
  \
  eth0.100
```

bonding with vlan
```
eth0  eth1
 \   /
 bond0
   \
   bond0.1000
```
two bonds:
```
eth0  eth1 eth2  eth3
 \   /        \   /
 bond0        bond1
```

Autodetection works well in all the cases, but we always need to append `ovn0` device to it

2024-05-31 14:32 UTC, asauber commented
The word "enforce" to me usually implies a security option or functionality restriction. I think a better name would be `--force-device-detection`.

2024-05-31 14:46 UTC, asauber approved these changes
The concept makes sense to me. There are cases where as a user you only know a subset of the device names that you want Cilium to use.

2024-05-31 14:46 UTC, asauber commented on pkg/datapath/linux/devices_controller.go
> +	flags.Bool(option.EnforceDeviceDetection, false, "Enforces the auto-detection of devices, even if specific devices are explicitly listed")
```suggestion
	flags.Bool(option.ForceDeviceDetection, false, "Forces the auto-detection of devices, even if specific devices are explicitly listed")
```

2024-06-01 06:38 UTC, kvaps commented on pkg/datapath/linux/devices_controller.go
> +	flags.Bool(option.EnforceDeviceDetection, false, "Enforces the auto-detection of devices, even if specific devices are explicitly listed")
PR rebased!

2024-06-04 04:21 UTC, joestringer commented
I pondered a little about alternative configurations for this, such as adding flags to tweak the autodetection logic. Currently all bridge and OVS type devices are ignored, but we could loosen that to make it more dynamic. However, I think that in the end the current proposal is just as powerful and probably a bit simpler to configure. So it probably makes sense to go ahead with the current proposal :+1:

2024-06-04 04:21 UTC, joestringer commented
/test

2024-06-04 05:40 UTC, joamaki approved these changes

2024-06-04 10:59 UTC, aanm approved these changes

2024-06-04 18:27 UTC, kvaps commented
/test-runtime

2024-06-04 18:29 UTC, kvaps commented
@joestringer It seems that some tests have failed due to unrelated reasons. Can we rerun them somehow?

2024-06-04 19:56 UTC, joestringer commented
The [failure in ci-runtime](https://github.com/cilium/cilium/actions/runs/9361183964/job/25782047708#step:17:362) is in a related area:

```
--- FAIL: TestDevicesController_DeviceDetection (0.01s)
361
    logger.go:257: time=2024-06-04T11:12:55.923Z level=INFO source=/host/vendor/github.com/cilium/hive/hive.go:337 msg=Starting
362
    logger.go:257: time=2024-06-04T11:12:55.923Z level=INFO source=/host/pkg/datapath/linux/devices_controller.go:522 msg="Devices changed" module=devices-controller devices="[dummy0 dummy1 eth0]"
363
    logger.go:257: time=2024-06-04T11:12:55.924Z level=INFO source=/host/vendor/github.com/cilium/hive/hive.go:341 msg=Started duration=785.306µs
364
    logger.go:257: time=2024-06-04T11:12:55.924Z level=INFO source=/host/vendor/github.com/cilium/hive/hive.go:353 msg=Stopping
365
    logger.go:257: time=2024-06-04T11:12:55.924Z level=INFO source=/host/pkg/hive/health/provider.go:62 msg="health.job-module-status-metrics (rev=2)" module=health
366
    logger.go:257: time=2024-06-04T11:12:55.924Z level=INFO source=/host/vendor/github.com/cilium/hive/hive.go:337 msg=Starting
367
    logger.go:257: time=2024-06-04T11:12:55.924Z level=INFO source=/host/vendor/github.com/cilium/hive/hive.go:341 msg=Started duration=16.391µs
368
    logger.go:257: time=2024-06-04T11:12:55.925Z level=INFO source=/host/pkg/datapath/linux/devices_controller.go:522 msg="Devices changed" module=devices-controller devices="[eth0 dummy0 dummy1]"
369
    devices_controller_test.go:473: 
370
        	Error Trace:	/host/pkg/datapath/linux/devices_controller_test.go:473
371
        	            				/host/pkg/netns/netns_linux.go:171
372
        	            				/host/vendor/golang.org/x/sync/errgroup/errgroup.go:78
373
        	            				/root/sdk/go1.22.3/src/runtime/asm_amd64.s:1695
374
        	Error:      	Should be true
375
        	Test:       	TestDevicesController_DeviceDetection
```

If the failure is introduced by this PR, then it will reoccur if we re-run the tests. I can try that.

2024-06-04 19:56 UTC, joestringer commented
/ci-runtime

2024-06-04 22:30 UTC, kvaps commented
Yeah, my bad, sorry, I will fix the test

2024-06-04 23:57 UTC, kvaps commented
@joestringer thank you for pointing this out.
Test is fixed, I requested to join cilium as member
https://github.com/cilium/community/pull/125

2024-06-05 00:24 UTC, joestringer commented
/test

2024-06-05 07:32 UTC, aanm commented
/test

2024-06-05 09:19 UTC, kvaps commented
/test

2024-06-05 12:32 UTC, kvaps commented
/test ci-ipsec-upgrade ci-ipsec-upgrade ci-ipsec-e2e ci-ingress

2024-06-05 12:36 UTC, kvaps commented
/test

2024-06-05 14:55 UTC, kvaps commented
/test ci-e2e

2024-06-05 14:56 UTC, kvaps commented
/test-ci-e2e

2024-06-05 14:57 UTC, kvaps commented
/ci-e2e

2024-06-05 14:57 UTC, kvaps commented
/ci-ginkgo

2024-06-05 14:57 UTC, kvaps commented
/ci-ingress

2024-06-05 17:08 UTC, kvaps commented
/ci-ginkgo

2024-06-05 17:49 UTC, kvaps commented
@aanm @joestringer all tests have passed 🎉

2024-06-05 19:08 UTC, merged

2024-06-07 09:26 UTC, brb commented
@kvaps Thanks for the PR. Do you mind to update the documentation too (` Documentation/network/kubernetes/kubeproxy-free.rst`)?