BGPv1 - Import None
cilium/cilium pull request #33035
Opened 2024-06-11 01:17 UTC by dswaffordcw

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

# BGPv1 - Reject all inbound BGP advertisements

# Overview

Cilium's BGPv1 Control Plane accepts all BGP Paths advertised to it.  However, these paths do not program the datapath. 
 This PR modifies Cilium's BGPv1 implementation to reject all inbound BGP advertisements.

The desire for this change is:
1) To reduce confusion by administrators of a Cilium installation.  When viewing `cilium bgp routes`, the current output, which shows all received BGP paths, gives the impression that these paths/routes are being used for routing by the CNI (programmed into the dataplane).  For Cilium, this is not true and they are simply ignored.
2) To move a potential failure point in Cilium's BGP stack.  In the BGPv1 implementation, a [GoBGP](https://github.com/osrg/gobgp) server is instantiated by Cilium's directly in Go.  It does not run as an external process.  If GoBGP experiences a memory leak or panic, it has the potential to disrupt Cilium as well.  One point of failure that I've seen in the past is when using GoBGP in environments containing millions of BGP paths.  While it's an unlikely use case for a CNI, the potential exists that one could try to pass full Internet tables into their CNI.  As these are unused, it would be ideal to drop them.

# Description
TODO...

# Testing

## Manual Testing

## Unit Tests

Fixes: #32826

```release-note
BGPv1 - Reject all inbound BGP advertisements
```

2024-06-11 02:53 UTC, dswaffordcw commented
@harsimran-pabla
I am seeing something that looks off in my testing.  I thought this was just about ready, aside from one test.  But, one aspect looks like it may be a regression.  I'm not sure.

With the BGP development environment (containerlab via `make kind-bgp-v4`), on `main` and recently rebased against upstream I see:
```
$  cilium bgp routes
(Defaulting to `available ipv4 unicast` routes, please see help for more options)

Node                              VRouter   Prefix           NextHop    Age   Attrs
bgp-cplane-dev-v4-control-plane   65001     100.64.12.1/32   10.0.1.1   6s    [{Origin: i} {AsPath: 65000 65002} {Nexthop: 10.0.1.1} {Communities: 65002:100} {LargeCommunity: [ 65002:100:1]}]
bgp-cplane-dev-v4-worker          65002     100.64.12.1/32   0.0.0.0    14s   [{Origin: i} {Nexthop: 0.0.0.0}]
```

This is taken before announcing any routes toward Cilium from the FRR container.  It was configured w/ the `bgpp.yaml` below.  On this PR, I see only:
```
$  cilium bgp routes
(Defaulting to vailable ipv4 unicastroutes, please see help for more options)

Node                       VRouter   Prefix           NextHop   Age     Attrs
bgp-cplane-dev-v4-worker   65002     100.64.12.1/32   0.0.0.0   21m5s   [{Origin: i} {Nexthop: 0.0.0.0}]

```

The route that was previously announced by `bgp-cplane-dev-v4-control-plane` no longer exists.

I *think* each instance of Cilium is announcing its own paths directly to it's configured peer(s).  It looks to me though that the instance of `bgp-cplane-dev-v4-worker ` is peered with `bgp-cplane-dev-v4-control-plane` internally and is also announcing the same path to it.  With my PR, that internal announcement is not being accepted.  Does it need to be?

```
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: control-plane
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: bgp-cplane-dev-v4-control-plane
  virtualRouters:
  - localASN: 65001
    neighbors:
    - peerASN: 65000
      peerAddress: 10.0.1.1/32
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: worker
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: bgp-cplane-dev-v4-worker
  virtualRouters:
  - localASN: 65002
    #exportPodCIDR: true
    serviceSelector:
      #matchLabels:
      #  name: hello-node
      matchExpressions:
       - { key: app, operator: In, values: [hello-node, hello-node2, hello-node3] }
    serviceAdvertisements:
      - LoadBalancerIP # <-- default
      #- ClusterIP      # <-- options
      #- ExternalIP     # <-- options
    neighbors:
    - peerASN: 65000
      peerAddress: 10.0.2.1/32
      #holdTimeSeconds: 180
      #keepAliveTimeSeconds: 60
      #eBGPMultihopTTL: 1
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 60
      advertisedPathAttributes:
      - selectorType: CiliumLoadBalancerIPPool
        selector:
          matchLabels:
            environment: mgmt
        communities:
          standard:
          - 65002:100
          large:
          - 65002:100:1
          #wellknown:
          #- no-export
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "mgmt"
  labels:
    environment: mgmt
spec:
  blocks:
    - cidr: "100.64.8.0/22"
  cidrs:
    - cidr: "100.64.12.0/22"
```

2024-06-11 03:17 UTC, dswaffordcw commented
@harsimran-pabla Replying to my last comment, I think the missing route is actually the original from `bgp-cplane-dev-v4-worker` being re-advertised by the FRR container back toward Cilium's `bgp-cplane-dev-v4-control-plane` instance.   I'll do more testing tomorrow to confirm.

2024-06-11 13:57 UTC, rastislavs commented
Hi @dswaffordcw , thanks a lot for this PR, I think it makes a lot of sense to filter inbound advertisements while we don't need them. 

However, instead of doing that per neighbor, I think it would be better to just change the default import policy to reject the routes - see [GoBGP Policy docs - 4.1 Attach policy to global rib](https://github.com/osrg/gobgp/blob/master/docs/sources/policy.md#4-attaching-policy) - the equivalent of:
```
default-import-policy = "reject-route"
```

This way we can save some processing on the number of policies in case of many neighbors, and future-wise, we can still enable import per-neighbor if we need to implement such a feature.

You will probably need to add a Policy Assignment in the import direction like here: https://github.com/cilium/cilium/blob/main/pkg/bgpv1/gobgp/server.go#L186

2024-06-11 17:16 UTC, dswaffordcw commented
> Hi @dswaffordcw , thanks a lot for this PR, I think it makes a lot of sense to filter inbound advertisements while we don't need them.
> 
> However, instead of doing that per neighbor, I think it would be better to just change the default import policy to reject the routes - see [GoBGP Policy docs - 4.1 Attach policy to global rib](https://github.com/osrg/gobgp/blob/master/docs/sources/policy.md#4-attaching-policy) - the equivalent of:
> 
> ```
> default-import-policy = "reject-route"
> ```
> 
> This way we can save some processing on the number of policies in case of many neighbors, and future-wise, we can still enable import per-neighbor if we need to implement such a feature.
> 
> You will probably need to add a Policy Assignment in the import direction like here: https://github.com/cilium/cilium/blob/main/pkg/bgpv1/gobgp/server.go#L186

Thanks @rastislavs!  That's a good suggestion.  I'll update the PR and let you know when it's ready to look over again.

2024-06-12 00:02 UTC, dswaffordcw commented
@rastislavs I fought through this all day and am at a wall.  I've figured out how to configure the global policy but GoBGP is not handling it as expected.

Could you look through this and let me know your thoughts?

In https://github.com/cilium/cilium/pull/33035/commits/8714116f8d16df121cacfb8ac85704618ad3c15c, I believe that is the correct way to configure the global policies.  However, it is silently ignored.  I found another report last December of the same in https://github.com/osrg/gobgp/issues/1768#issuecomment-1839399167.  I logged a new issue under https://github.com/osrg/gobgp/issues/2814.

Then, I walked through GoBGP's configuration file parsing code.  It configures the default in a different way (see https://github.com/osrg/gobgp/blob/master/pkg/config/config.go#L45).  I did that in https://github.com/cilium/cilium/pull/33035/commits/f028b2bf5e63e0227fb748ce2c491d2497e84200 using `SetPolicyAssignment()` but that too is not working correctly.  With that commit in place, I see the following:

```
$  cilium bgp peers
Node                              Local AS   Peer AS   Peer Address   Session State   Uptime   Family         Received   Advertised
bgp-cplane-dev-v4-control-plane   65001      65000     10.0.1.1       established     9m12s    ipv4/unicast   0          0
                                                                                               ipv6/unicast   0          0
bgp-cplane-dev-v4-worker          65002      65000     10.0.2.1       established     9m14s    ipv4/unicast   0          1
                                                                                               ipv6/unicast   0          1

00x0 dswafford@dswafford-2 2024/06/11 17:00:49
☸︎ kind-bgp-cplane-dev-v4:
> cilium-fork on  GH32826-import-none [$]
$  cilium bgp routes
(Defaulting to `available ipv4 unicast` routes, please see help for more options)

Node   VRouter   Prefix   NextHop   Age   Attrs

```

And on the FRR instance, no paths/routes:

```
router0# show ip bgp sum

IPv4 Unicast Summary (VRF default):
BGP router identifier 10.0.0.1, local AS number 65000 vrf-id 0
BGP table version 0
RIB entries 0, using 0 bytes of memory
Peers 2, using 1434 KiB of memory
Peer groups 1, using 64 bytes of memory

Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
10.0.1.2        4      65001        21        21        0    0    0 00:09:35            0        0 N/A
10.0.2.2        4      65002        23        22        0    0    0 00:09:37            0        0 N/A

Total number of neighbors 2
router0# show ip bgp
No BGP prefixes displayed, 0 exist
```

2024-06-12 09:57 UTC, rastislavs commented
Hi @dswaffordcw,

> I fought through this all day

Sorry to hear that, but I can understand it - GoBGP can be a bit tricky, you almost always need to look into source code to understand the details.

> I did that in https://github.com/cilium/cilium/commit/f028b2bf5e63e0227fb748ce2c491d2497e84200 using SetPolicyAssignment()

Yeah, that is what I suggested in my first comment. That is the correct way to do it.

> but that too is not working correctly

So I looked into the source code :) and it seems that GoBGP applies policies also on locally installed routes, see:

`AddPath` calls `addPathList`: https://github.com/osrg/gobgp/blob/master/pkg/server/server.go#L2269
`addPathList` calls `propagateUpdate`: https://github.com/osrg/gobgp/blob/master/pkg/server/server.go#L2242
`propagateUpdate` calls `ApplyPolicy`: https://github.com/osrg/gobgp/blob/master/pkg/server/server.go#L1224

The solution is to add an import policy that allows local routes. Something like this seems to be working for me:

```diff
diff --git a/pkg/bgpv1/gobgp/server.go b/pkg/bgpv1/gobgp/server.go
index ab8a2ba52b..45088080da 100644
--- a/pkg/bgpv1/gobgp/server.go
+++ b/pkg/bgpv1/gobgp/server.go
@@ -74,7 +74,7 @@ func NewGoBGPServer(ctx context.Context, log *logrus.Entry, params types.ServerP
 		SubSys:    "bgp-control-plane",
 	})

-	s := server.NewBgpServer(server.LoggerOption(logger))
+	s := server.NewBgpServer(server.LoggerOption(logger), server.GrpcListenAddress("0.0.0.0:50051"))
 	go s.Serve()

 	startReq := &gobgp.StartBgpRequest{
@@ -95,11 +95,40 @@ func NewGoBGPServer(ctx context.Context, log *logrus.Entry, params types.ServerP
 		return nil, fmt.Errorf("failed starting BGP server: %w", err)
 	}

+	allowLocalPolicy := &gobgp.Policy{
+		Name: "allow-local",
+		Statements: []*gobgp.Statement{
+			{
+				Conditions: &gobgp.Conditions{
+					RouteType: gobgp.Conditions_ROUTE_TYPE_LOCAL,
+				},
+				Actions: &gobgp.Actions{
+					RouteAction: gobgp.RouteAction_ACCEPT,
+				},
+			},
+		},
+	}
+	err := s.AddPolicy(ctx, &gobgp.AddPolicyRequest{Policy: allowLocalPolicy})
+	if err != nil {
+		return nil, fmt.Errorf("failed to add %s policy: %w", allowLocalPolicy.Name, err)
+	}
+	err = s.SetPolicyAssignment(ctx, &gobgp.SetPolicyAssignmentRequest{
+		Assignment: &gobgp.PolicyAssignment{
+			Name:          globalPolicyAssignmentName,
+			Direction:     gobgp.PolicyDirection_IMPORT,
+			DefaultAction: gobgp.RouteAction_REJECT,
+			Policies:      []*gobgp.Policy{allowLocalPolicy},
+		},
+	})
+	if err != nil {
+		return nil, fmt.Errorf("failed configuring BGP server's global import policy: %w", err)
+	}
+
 	// will log out any peer changes.
 	watchRequest := &gobgp.WatchEventRequest{
 		Peer: &gobgp.WatchEventRequest_Peer{},
 	}
-	err := s.WatchEvent(ctx, watchRequest, func(r *gobgp.WatchEventResponse) {
+	err = s.WatchEvent(ctx, watchRequest, func(r *gobgp.WatchEventResponse) {
 		if p := r.GetPeer(); p != nil && p.Type == gobgp.WatchEventResponse_PeerEvent_STATE {
 			logger.l.Debug(p)
 		}
```

Note that I temporarily configured `GrpcListenAddress` on the server so that I can debug this with `gobgp` CLI, it might be helpful for you as well - e.g. this is the result of running the above code:

```
$ gobgp --host 172.18.0.2 global policy
Import policy:
    Default: REJECT
    Name allow-local:
        StatementName allow-local_stmt0:
          Conditions:
            Route Type: local
          Actions:
             accept
```

2024-06-12 20:43 UTC, dswaffordcw commented
Thanks @rastislavs!  That worked!

One follow-up Q, I'd like to include an update the `cilium-dbg` and `cilium` CLIs to distinguish between "Received" and "Accepted" route counts when looking at `cilium bgp peers`.  I thought this change would do it, but it too didn't work :-D!  Thoughts on where I should look next?

```
$  git diff
diff --git a/cilium-dbg/cmd/bgp_peer_get.go b/cilium-dbg/cmd/bgp_peer_get.go
index b40978ee3f..5168d06326 100644
--- a/cilium-dbg/cmd/bgp_peer_get.go
+++ b/cilium-dbg/cmd/bgp_peer_get.go
@@ -54,7 +54,7 @@ func printSummary(peers []*models.BgpPeer) {
                return peers[i].LocalAsn < peers[j].LocalAsn || peers[i].PeerAddress < peers[j].PeerAddress
        })

-       fmt.Fprintln(w, "Local AS\tPeer AS\tPeer Address\tSession\tUptime\tFamily\tReceived\tAdvertised")
+       fmt.Fprintln(w, "Local AS\tPeer AS\tPeer Address\tSession\tUptime\tFamily\tReceived\tAccepted\tAdvertised")
        for _, peer := range peers {
                fmt.Fprintf(w, "%d\t", peer.LocalAsn)
                fmt.Fprintf(w, "%d\t", peer.PeerAsn)
@@ -72,6 +72,7 @@ func printSummary(peers []*models.BgpPeer) {
                        // AFI and SAFI are concatenated for brevity
                        fmt.Fprintf(w, "%s/%s\t", afisafi.Afi, afisafi.Safi)
                        fmt.Fprintf(w, "%d\t", afisafi.Received)
+                       fmt.Fprintf(w, "%d\t", afisafi.Accepted)
                        fmt.Fprintf(w, "%d\t", afisafi.Advertised)
                        fmt.Fprintf(w, "\n")
                }
```

After building and copying that into one of the cilium containers, I saw:
```
root@bgp-cplane-dev-v4-control-plane:/home/cilium# /tmp/cilium-dbg-david bgp peers
Local AS   Peer AS   Peer Address   Session       Uptime     Family         Received   Accepted   Advertised
65001      65000     10.0.1.1:179   established   1h51m22s   ipv4/unicast   10         10         0
                                                             ipv6/unicast   0          0          0
root@bgp-cplane-dev-v4-control-plane:/home/cilium# /tmp/cilium-dbg-david bgp routes
(Defaulting to `available ipv4 unicast` routes, please see help for more options)

VRouter   Prefix   NextHop   Age   Attrs
root@bgp-cplane-dev-v4-control-plane:/home/cilium# /tmp/cilium-dbg-david bgp route-policies
VRouter   Policy Name   Type     Match Peers   Match Prefixes (Min..Max Len)   RIB Action   Path Actions
65001     allow-local   import                                                 accept
```

I was expecting to see 0 for "Accepted".  It looks like the response that comes back through the API's `client.Bgp.GetBgpPeers()` is unaware of the global policies and their effect.

2024-06-13 07:10 UTC, rastislavs commented
@dswaffordcw 
> I'd like to include an update the cilium-dbg and cilium CLIs to distinguish between "Received" and "Accepted" route counts when looking at cilium bgp peers. I thought this change would do it, but it too didn't work 

Interesting, in my setup your proposed CLI change seems to be working fine - it matches the output of `gobgp neighbor`:

```
gobgp --host 172.18.0.2 neighbor
Peer         AS  Up/Down State       |#Received  Accepted
172.0.0.1 65000 00:02:05 Establ      |        2         1
```

```
cilium-dbg bgp peers
Local AS   Peer AS   Peer Address    Session       Uptime   Family         Received   Accepted   Advertised
65001      65000     172.0.0.1:179   established   2m32s    ipv4/unicast   2          1          1
                                                            ipv6/unicast   0          0          0
```

Could you check what `gobgp neighbor` returns in your case?

2024-06-13 22:34 UTC, dswaffordcw commented
Hey @rastislavs

They match for me as well.   With adding the global policy to reject all routes, I was expected to see "Accepted: 0".  Though, technically this is correct.  The per-neighbor policies accepted the routes and they are being rejected later on.

I am not seeing a way to extract the fact that "Neighbor X's routes were later rejected by the global import policy".  Do you think this is worth pursuing further?  One idea for now, is that we add the "Accepted" column but statically set the value to 0.  My desire is to eliminate confusion -- by making it clear that Cilium does nothing with received routes.


```
root@bgp-cplane-dev-v4-control-plane:/home/cilium# /tmp/gobgp neigh
Peer        AS  Up/Down State       |#Received  Accepted
10.0.1.1 65000 00:20:25 Establ      |        6         6

root@bgp-cplane-dev-v4-control-plane:/home/cilium# /tmp/gobgp global rib
Network not in table
root@bgp-cplane-dev-v4-control-plane:/home/cilium#

root@bgp-cplane-dev-v4-control-plane:/home/cilium# /tmp/gobgp global rib summary
Table afi:AFI_IP  safi:SAFI_UNICAST
Destination: 0, Path: 0
root@bgp-cplane-dev-v4-control-plane:/home/cilium#
```

```
root@bgp-cplane-dev-v4-control-plane:/home/cilium# cilium-dbg bgp peers
Local AS   Peer AS   Peer Address   Session       Uptime   Family         Received   Accepted   Advertised
65001      65000     10.0.1.1:179   established   21m16s   ipv4/unicast   6          6          0
                                                           ipv6/unicast   0          0          0

root@bgp-cplane-dev-v4-control-plane:/home/cilium# cilium-dbg bgp routes
(Defaulting to `available ipv4 unicast` routes, please see help for more options)

VRouter   Prefix   NextHop   Age   Attrs
```

2024-06-14 08:56 UTC, rastislavs commented
Hi @dswaffordcw 

> They match for me as well. With adding the global policy to reject all routes, I was expected to see "Accepted: 0". Though, technically this is correct. The per-neighbor policies accepted the routes and they are being rejected later on.

Right, it seems the "Accepted" stats for a peer are sourced from adj-rib-in state: https://github.com/osrg/gobgp/blob/master/pkg/server/server.go#L3092
which is before the import policies are applied. 

I checked how FRR displays "accepted" stats for BGP peers, if you filter-out incoming routes via a route-map, and it also shows the routes that do not get into route table in the "accepted" counter in the "sh bgp neighbors" output - so at least it is consistent.

>  Do you think this is worth pursuing further? One idea for now, is that we add the "Accepted" column but statically set the value to 0.

I would not do this - I think we should be consistent with gobgp stats, but more importantly, it will become an issue once we actually start importing routes. I think for now the best option probably is to keep just the Received and Advertised columns.

2024-06-14 08:59 UTC, rastislavs commented on pkg/bgpv1/gobgp/server.go
> +	if err := s.AddPolicy(ctx, &gobgp.AddPolicyRequest{Policy: allowLocalPolicy}); err != nil {
Could you add a comment on why this policy & policy assignment are needed ad what they do?

2024-06-14 09:00 UTC, rastislavs commented on pkg/bgpv1/gobgp/server.go
> +	globalAllowLocalPolicyName = "allow-local"
could you add an comment here?

2024-06-14 09:03 UTC, rastislavs commented
@dswaffordcw please note that this change now affects BGPv2 as well, could you please test with BGPv2 enabled, and update the title & release note accordingly?

2024-06-15 00:21 UTC, dswaffordcw commented
@rastislavs Testing for BGPv2 --

Using only a BGPv2 configuration, I see the same result as with BGPv1.  I advertised 10 BGP paths from an FRR instance toward Cilium and all were rejected.  Cilium continued to announce a path toward FRR and FRR accepted it.

I'll update the PR's description to include this as well.

Here's  the `bgpp.yaml` I used:
```
$  cat bgppv2.yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: bgp-cplane-dev-v4-control-plane
  bgpInstances:
  - name: "control-plane"
    localASN: 65001
    peers:
    - name: "frr"
      peerASN: 65000
      peerAddress: 10.0.1.1
      peerConfigRef:
        name: "cilium-cp-frr-peer"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: "cilium-cp-frr-peer"
spec:
  transport:
    localPort: 179
    peerPort: 179
  #timers:
  #  connectRetryTimeSeconds: 12
  #  holdTimeSeconds: 9
  #  keepAliveTimeSeconds: 3
  #authSecretRef: bgp-auth-secret
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: "bgp-advertisements"
  labels:
    advertise: "bgp"
spec:
  advertisements:
    #- advertisementType: "LoadBalancerIP"
    - advertisementType: "PodCIDR"
      #serviceSelector:
      #matchLabels:
      #  name: hello-node
      #  matchExpressions:
      #  - { key: app, operator: In, values: [hello-node, hello-node2, hello-node3] }
      attributes:
        communities:
          standard: [ "65001:100" ]
        localPreference: 99
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "mgmt"
  labels:
    environment: mgmt
spec:
  blocks:
    - cidr: "100.64.8.0/22"
  cidrs:
    - cidr: "100.64.12.0/22"
  #serviceSelector:
  #  matchExpressions:
  #    - {key: app, operator: In, values: [hello-node]}
---
```

```

2024-06-15 01:55 UTC, dswaffordcw commented
@rastislavs This is ready for review.

Thanks for all of your help!

2024-06-17 08:30 UTC, rastislavs commented on cilium-dbg/cmd/bgp_peer_get.go
> +	fmt.Fprintln(w, "Local AS\tPeer AS\tPeer Address\tSession\tUptime\tFamily\tReceived\tAccepted\tAdvertised")
I would propose to rather not expose `Accepted` counter at this point. It has very minor information benefit - and may actually confuse users.

2024-06-17 08:32 UTC, rastislavs requested changes
I would propose to not change the CLI output at his point, otherwise LGTM!

2024-06-17 17:05 UTC, dswaffordcw commented
> I would propose to not change the CLI output at his point, otherwise LGTM!

@rastislavs ACK.  I reverted those changes.  Thanks for the thorough review!

2024-06-17 19:06 UTC, asauber approved these changes
dropping an approval since the files owned by my team no longer appear here

2024-06-18 10:00 UTC, rastislavs commented
/test

2024-06-18 10:03 UTC, rastislavs approved these changes
LGTM now, thanks a lot for your work!

2024-06-20 08:46 UTC, merged