Test: Fix assert message on kafka tests
cilium/cilium pull request #3311
Opened 2018-03-26 09:46 UTC by eloycoto

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

2018-03-26 09:46 UTC, eloycoto commented
test-me-please

2018-03-26 10:41 UTC, tgraf requested changes

2018-03-26 10:41 UTC, tgraf commented on test/runtime/kafka.go
> +		Expect(err).Should(BeNil(), "Cannot get policy enforcement summary")
I'm not sure what that means. What command does it run?

2018-03-26 10:41 UTC, tgraf commented on test/runtime/kafka.go
> +			"Kafka container does not have any policy enforcement, and it should")
`"Check number of endpoints with policy enforcement enabled"`

The kafka context is clear from the test context.

2018-03-26 10:41 UTC, tgraf commented on test/runtime/kafka.go
> +			"Number of endpoints without Policy Enforcement mismatch")
`"Check number of endpoints with policy enforcement enabled"`

2018-03-26 15:52 UTC, eloycoto commented
test-me-please

2018-03-26 17:44 UTC, ianvernon commented on test/runtime/kafka.go
> +			"Check number of endpoints without policy enforcement")
without policy enforcement enabled

2018-03-27 00:11 UTC, joestringer commented on test/runtime/kafka.go
> +			"Check number of endpoints without policy enforcement")
perhaps, 'with policy enforcement disabled'? reading double-negatives is always more difficult.

2018-03-27 03:21 UTC, manalibhutiyani commented
Looks fine. Please change the wording as per the review comments.

2018-03-27 03:21 UTC, manalibhutiyani approved these changes

2018-03-27 09:20 UTC, eloycoto commented
test-me-please

2018-03-27 19:11 UTC, ianvernon approved these changes

2018-03-27 19:43 UTC, merged