ci: fix ces migration test trigger and conn-disrupt usage
cilium/cilium pull request #33147
Opened 2024-06-13 22:29 UTC by jshr-w

PR #32930 introduced a change to the conn-disrupt test that caused this migration test to fail. This PR updates the test to work with the updated test format. The inconsistency was not caught because of the path filters used in the test, so the path filters have been updated to exclude only Documentation/ and test/.

Fixes: #32268

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

```release-note

```

2024-06-14 06:43 UTC, giorio94 requested changes
Thanks, overall changes look good to me. Just a missing check to be added.

2024-06-14 06:43 UTC, giorio94 commented on .github/workflows/tests-ces-migrate.yaml
> +    needs: check_changes
You should also add `if: ${{ needs.check_changes.outputs.tested == 'true' }}`

2024-06-14 18:24 UTC, giorio94 approved these changes
Thanks!

2024-06-15 08:01 UTC, aanm approved these changes

2024-06-15 08:58 UTC, aanm commented
/test

2024-06-15 09:07 UTC, merged