daemon: Check that DaemonConfig is not changed after being published
cilium/cilium pull request #33166
Opened 2024-06-15 09:19 UTC by jrajahalme

Add sha256 sum to config and validate no change in immutable parts after DaemonConfig is resolved.

This has been carved out from #32981 to focus reviews.

2024-06-16 11:23 UTC, jrajahalme commented
/test

2024-06-17 19:08 UTC, asauber requested changes

2024-06-17 19:08 UTC, asauber commented on pkg/option/config.go
> +	c.shaSum = c.checksum()
There is potential for a race here, the hash should be taken after the file is successfully written.

2024-06-17 19:08 UTC, asauber commented on pkg/option/config.go
> +		opts := cmp.FilterPath(func(p cmp.Path) bool {
Can we include a comment here that the purpose of this filter is to discover the exported field names during the comparison?

2024-06-17 19:08 UTC, asauber commented on pkg/option/config.go
> +			cmpopts.IgnoreTypes(&OptionLibrary{}))
Why is it safe to ignore these fields?

2024-06-18 08:44 UTC, lmb reviewed
Can you update the PR description to include what the problem you're solving is? Right now there is very little context.

2024-06-23 05:23 UTC, jrajahalme commented
This got fixed and merged as part of #32981

2024-06-23 05:24 UTC, jrajahalme commented
This got fixed and merged as part of https://github.com/cilium/cilium/pull/32981

2024-06-23 05:24 UTC, closed without merging