helm: Cleanup default values for old Cilium versions
cilium/cilium pull request #33388
Opened 2024-06-25 14:13 UTC by sayboras

2024-06-25 14:42 UTC, sayboras commented
/test

2024-06-26 09:42 UTC, sayboras commented
/test

2024-06-26 13:38 UTC, aanm requested changes
Doesn't this mean that if someone uses `--upgradeCompatibility 1.8` and updates to, let's say 1.16, that the `$defaultBpfMasquerade` will change from `true` to `false`?

2024-06-27 13:20 UTC, squeed approved these changes

2024-06-28 03:52 UTC, tommyp1ckles approved these changes
nice cleanup 😄

2024-07-01 16:07 UTC, sayboras commented
> Doesn't this mean that if someone uses --upgradeCompatibility 1.8 and updates to, let's say 1.16, that the $defaultBpfMasquerade will change from true to false?

Yes, I assume that at one point, users must upgrade the values of upgradeCompatibility to be at least the minimum supported versions (e.g. v1.13). IMO upgradeCompatibility is mainly for transition period between **supported** versions.

2024-07-02 07:51 UTC, aanm commented
> > Doesn't this mean that if someone uses --upgradeCompatibility 1.8 and updates to, let's say 1.16, that the $defaultBpfMasquerade will change from true to false?
> 
> Yes, I assume that at one point, users must upgrade the values of upgradeCompatibility to be at least the minimum supported versions (e.g. v1.13). IMO upgradeCompatibility is mainly for transition period between **supported** versions.

I think the purpose of it is to let users keep their defaults since they installed Cilium. pinging @joestringer to see if he remembers.

2024-07-04 11:21 UTC, marseel commented
> I think the purpose of it is to let users keep their defaults since they installed Cilium. pinging [Joe Stringer](https://github.com/joestringer) to see if he remembers.

This is exactly the reason for upgradeCompatibility AFAIK. 
On the other hand, it seems it might be already broken, example for KPR:
```
{{- $defaultKubeProxyReplacement = "probe" -}}
```
...
```
{{- $kubeProxyReplacement := (coalesce $stringValueKPR $defaultKubeProxyReplacement) -}}
{{- if and (ne $kubeProxyReplacement "true") (ne $kubeProxyReplacement "false") }}
  {{ fail "kubeProxyReplacement must be explicitly set to a valid value (true or false) to continue." }}
{{- end }}

```

I remember in the past, users also asked if keeping upgradeCompatibility set to the old version might affect the cluster by not having some "new" improvements. 

With KPR example in mind, I'm pretty sure we are not testing it and it's already broken. So I would establish when and how we should be using that from now on (or if we need it at all). 

If we plan to remove `upgradeCompatibility` altogether, we should also update docs and get rid of it during upgrade in https://docs.cilium.io/en/stable/operations/upgrade/#step-2-use-helm-to-upgrade-your-cilium-deployment

If we plan to repurpose it, we could have some reasonable guidelines when to use it. I would say, only keep the default if changing it causes disruption in the cluster and maybe only for bool/number values, but not for enums like KPR. 
Another example of a reasonable use case for upgradeCompatibility is to enforce additional validation: https://github.com/cilium/cilium/blob/95886de65f7cb746e08bb585a8435fc8d3affcbc/install/kubernetes/cilium/templates/validate.yaml#L94-L108

2024-07-08 17:13 UTC, joestringer requested changes
We can't just change the settings for older users without informing them. I like the idea of cleaning this up, but this needs to be done with crystal clear guidance for users based on the versions they're running and how they can change their settings without disrupting upgrade.

Additionally we should ensure on a case-by-case basis for each setting that we aren't going to break anything for users by changing these settings.

2024-07-08 17:18 UTC, joestringer commented
> If we plan to remove upgradeCompatibility altogether, we should also update docs and get rid of it during upgrade in https://docs.cilium.io/en/stable/operations/upgrade/#step-2-use-helm-to-upgrade-your-cilium-deployment

I strongly encourage a CFP for any such proposal. For this upcoming v1.16 release we continue to see value in having one set of default configurations for users that are upgrading, while providing a different set of default configurations for new users (Envoy DS changes). We should debate whether we want that, and if we do want that, then do we continue to do that via `upgradeCompatibility` or is there an alternative proposal to achieve this.

2024-08-22 01:53 UTC, closed without merging