ci-e2e: Set up node local DNS in conformance-e2e
cilium/cilium pull request #33768
Opened 2024-07-12 14:38 UTC by ysksuzuki

This PR introduces node local DNS with LRP in conformance-e2e following the LRP document.

https://docs.cilium.io/en/stable/network/kubernetes/local-redirect-policy/#node-local-dns-cache

2024-07-12 15:12 UTC, ysksuzuki commented
/test

2024-07-12 15:43 UTC, ysksuzuki commented
/test

2024-07-12 15:59 UTC, ysksuzuki commented
/test

2024-07-13 13:16 UTC, ysksuzuki commented
/test

2024-07-13 14:33 UTC, ysksuzuki commented
/test

2024-07-14 19:05 UTC, ysksuzuki commented
/test

2024-08-08 09:13 UTC, ysksuzuki commented
/test

2024-08-08 09:46 UTC, ysksuzuki commented on .github/workflows/conformance-e2e.yaml
> +          sed -i "s/__PILLAR__UPSTREAM__SERVERS__/1.1.1.1/g;" untrusted/examples/kubernetes-local-redirect/node-local-dns.yaml
https://github.com/cilium/cilium/blob/d2f71bc4ec220c6f27e790ff8e426a2aa52099ea/contrib/scripts/kind.sh#L250-L254

2024-08-08 13:37 UTC, ysksuzuki commented
/test

2024-08-08 14:02 UTC, ysksuzuki commented
/test

2024-08-09 08:44 UTC, tklauser approved these changes

2024-08-09 10:25 UTC, aanm approved these changes

2024-08-09 13:39 UTC, learnitall requested changes
Would you mind moving the `kustomization.yaml` and copying the `node-local-dns.yaml` and `node-local-dns-lrp.yaml` manifests into a new directory at `.github/actions/node-local-dns`? The examples directory has a different review process than CI related files. If someone reviewing a change to the manifests in the `examples/kubernetes-local-redirect` doesn't know it's being used by a CI workflow, an accident might occur where a change causes the workflow to break.

2024-08-09 16:29 UTC, ysksuzuki commented
@learnitall `local-redirect-policy-with-node-dns` test checks if the node local DNS with LRP using the manifests in `examples/kubernetes-local-redirect` is working as expected. (described [here](https://docs.cilium.io/en/stable/network/kubernetes/local-redirect-policy/#node-local-dns-cache)) So CI should fail If someone changes the manifests in the `examples/kubernetes-local-redirect` and break it.

2024-08-09 19:36 UTC, learnitall commented
Ack, ok that makes sense @ysksuzuki. Thank you for clarifying. I brought it up mainly because it feels like a bit of a "code smell" to have stuff for CI in `examples`, but that's probably a larger repo structure question that can be dug into at a later time.

2024-08-09 19:36 UTC, learnitall approved these changes

2024-08-09 19:44 UTC, merged