gha: don't fail if all cloud provider matrix entries are filtered out
cilium/cilium pull request #33819
Opened 2024-07-15 14:18 UTC by giorio94

Cloud provider related E2E workflows have been recently updated to automatically filter out the matrix entries if the corresponding k8s is EOL [1,2,3]. However, if that happen, the corresponding workflow currently fails due to both the empty matrix and the impossibility of subsequently merging the artifacts. Let's fix this by checking if the resulting  matrix is empty, and explicitly skipping the subsequent tasks in that case.

\[1]: dbcdd7dbe2e9 ("ci: Filter supported versions of AKS")
\[2]: 720927534b26 ("ci: Filter supported versions of EKS")
\[3]: dd947b3a3830 ("ci: Filter supported versions of GKE.")

2024-07-15 14:18 UTC, giorio94 commented
/test

2024-07-15 14:30 UTC, giorio94 commented
/ci-gke

2024-07-15 14:35 UTC, giorio94 commented
/test

2024-07-15 14:39 UTC, giorio94 commented
/test

2024-07-16 07:19 UTC, giorio94 commented
Additionally tested in https://github.com/cilium/cilium/pull/33816, it correctly skipped GKE-based workflows:
* https://github.com/cilium/cilium/actions/runs/9941380688
* https://github.com/cilium/cilium/actions/runs/9943012668

2024-07-16 17:41 UTC, viktor-kurchenko approved these changes
Thanks!

2024-07-16 23:16 UTC, tommyp1ckles approved these changes

2024-07-17 08:15 UTC, marseel requested changes
I'm not sure about it, there was no clear decision made IMHO: https://cilium.slack.com/archives/C7PE7V806/p1715292201887399
how about we talk about it during cilium dev meeting today?

2024-07-17 16:56 UTC, joestringer approved these changes
I'm fine with this.

The danger is if we accidentally introduce a new change in future which leads this workflow to pass on `main` while not running against any versions, then we might not notice. If we're worried about this, we could even make a simple addition to the workflow to do something like `if branch == main && matrix.empty { fail() }`

On the other hand, for the oldest maintained branch (v1.13 now), we're likely to see this come up from time to time. We could take action every time this comes up, but it's an expected scenario on that version given the target k8s versions at the time it was released and the support lifecycles from k8s providers. Even if we make the steps super clear when this happens (eg try to bump k8s version to the next one, or fall back to deleting the workflow), I'm not sure the value is that useful. For instance right now we're almost at v1.16 release so we'll stop releasing v1.13 versions anyway. It might gain maybe an extra month or so of testing coverage?

2024-07-18 10:15 UTC, giorio94 commented
/ci-gke

2024-07-18 10:25 UTC, giorio94 commented
/ci-gke

2024-07-18 10:33 UTC, giorio94 commented
Marking back ready for review, based on Joe's comment above.

I've additionally extended the commit status reporting to output the "Skipped" description when all matrix entries are skipped, and to explicitly fail in that case if the workflow is triggered on schedule (which only happens for the default branch, as scheduled runs on stable branches are triggered via workflow_dispatch), as additional sanity checks to detect possible breakages in the future.

![image](https://github.com/user-attachments/assets/80b89fee-1fc5-4a56-814b-1409319f22a5)

2024-07-18 10:35 UTC, giorio94 commented
/test

2024-07-18 10:48 UTC, marseel approved these changes
Thanks!

2024-07-18 13:02 UTC, merged