document helm value = hubble.dropEventEmitter.enabled
cilium/cilium pull request #33873
Opened 2024-07-17 16:34 UTC by saintdle

Documenting helm value `hubble.dropEventEmitter.enabled`

2024-07-19 20:37 UTC, joestringer requested changes, later dismissed
Hi @saintdle , thanks for the contribution.

This file is auto-generated from `install/kubernetes/cilium/values.yaml.tmpl`. If you want this to be documented, then the `enabled` field under `dropEventEmitter` in that file needs a comment line above it starting with `#`. After adding the description, you can use the following commands to update all the relevant other files:

```
make -C install/kubernetes
make -C Documentation update-helm-values
```

Additionally, sphinx has a spellchecker that doesn't understand how to interpret configurations like `dropEventEmitter`, so we work around the spellchecker by adding the config option to the dictionary like this:

```
./Documentation/update-spelling_wordlist.sh dropEventEmitter 
```

2024-07-22 11:11 UTC, saintdle commented
Thanks for the info, it seems like I'm running into some errors running those commands on macos, I'll try again on a linux machine soon, 

I did check the original helm template and it seems like that line is uncommented, so unsure as to why it's not picked up. 

https://github.com/saintdle/cilium/blob/3a5ec5e5d0c271ff4c4e058df0397b38ebe645a1/install/kubernetes/cilium/values.yaml.tmpl#L1759

2024-07-22 17:35 UTC, joestringer commented
> I did check the original helm template and it seems like that line is uncommented, so unsure as to why it's not picked up.

I think it's because there's no comment directly above the configuration item.

2024-08-12 07:01 UTC, youngnick commented
@saintdle Is this one still ongoing? Is there anything else you need here?

2024-08-14 14:39 UTC, saintdle commented
> @saintdle Is this one still ongoing? Is there anything else you need here?

Just relooked at this and I believe I've done it correctly now as per Joe's comment. 

As I am using MacOS I found the first command provided `make -C install/kubernetes` fails:

```shell
❯ make -C install/kubernetes
: cilium/Chart.yaml
grep -lR -e 'version:' -e 'appVersion:' /Users/dean/Documents/GitHub/cilium/install/kubernetes/cilium/ \
                | xargs -L 1 sed -i -e 's/''\([vV]ersion:\) ''[0-9]\+\.[0-9]\+\.[0-9]\+.*''/\1 '1.17.0-dev'/g'
sed -i 's;icon:.*;icon: https://cdn.jsdelivr.net/gh/cilium/cilium@main/Documentation/images/logo-solo.svg;' "/Users/dean/Documents/GitHub/cilium/install/kubernetes/cilium/Chart.yaml"
sed: 1: "/Users/dean/Documents/G ...": extra characters at the end of d command
make: *** [update-chart] Error 1
```

I found the fix is replacing line 46-50 with the below, not sure if there is a way to have this so using the make file works for both linux and macos easily?:

```shell
update-chart: $(ROOT_DIR)/VERSION
	$(ECHO_GEN)cilium/Chart.yaml
	$(QUIET)grep -lR -e 'version:' -e 'appVersion:' $(CILIUM_CHARTS)/ \
		| xargs -L 1 $(SED) -i '' -e 's/'$(CILIUM_CHART_REGEX)'/\1 '$(VERSION)'/g'
	$(QUIET)$(SED) -i '' 's;icon:.*;icon: $(LOGO_BASE_URL)/cilium@main/$(LOGO_PATH);' $(CHART_FILE)
```

2024-08-14 16:02 UTC, joestringer commented
I would guess that some of the steps outlined here could help to convert the sed expression into something cross-platform: https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux .

2024-08-14 17:02 UTC, saintdle commented
I could look at that as a separate issue :)

2024-08-15 13:18 UTC, saintdle commented
tried to squash the commits and add the sign off by, but keep hitting an issue. Unsure how to resolve.

2024-08-15 14:03 UTC, aanm commented
/test

2024-08-15 14:03 UTC, aanm approved these changes

2024-08-15 15:07 UTC, gandro approved these changes
Thank you!

2024-08-15 15:08 UTC, gandro commented
/ci-eks

2024-08-15 16:31 UTC, learnitall approved these changes
Thanks!

2024-08-15 16:34 UTC, learnitall commented
It looks like the workflow is failing because the sign-off has a typo:

```
<22192242+saintdle@users.noreply.github.com
```

It's missing the `>` character at the end. @saintdle did you add the sign-off manually?

2024-08-15 16:34 UTC, learnitall commented
/test

2024-08-15 20:40 UTC, saintdle commented
> It looks like the workflow is failing because the sign-off has a typo:
> 
> 
> 
> ```
> 
> <22192242+saintdle@users.noreply.github.com
> 
> ```
> 
> 
> 
> It's missing the `>` character at the end. @saintdle did you add the sign-off manually?

Yep

2024-08-16 02:07 UTC, tommyp1ckles approved these changes

2024-08-20 18:27 UTC, joestringer reviewed
Changes LGTM but the sign-off needs to be fixed. Will mark as draft until that is addressed. Once you've fixed that up, please click "Ready for Review" and we can retrigger tests and merge this.

2024-08-21 10:42 UTC, saintdle commented
> Changes LGTM but the sign-off needs to be fixed. Will mark as draft until that is addressed. Once you've fixed that up, please click "Ready for Review" and we can retrigger tests and merge this.

Hi, clicked ready for review as finally fixed the commit message, it wanted the sign off piece on a separate line, which is automatic when you use `git commit -s`. 

But now it's pulled through a missing other changes to files from main it seems? But I didn't hit rebase etc. Can you help me work through fixing that bit?

2024-08-21 15:28 UTC, joestringer commented
The easiest way is probably to walk back to an earlier copy and then rebase that and address the feedback afresh. If all of the latest changes have been merged into the patch, then it is likely to be tedious work to untangle that. 

Scanning up through the PR I see this: 
![image](https://github.com/user-attachments/assets/270dd2dd-0e5d-4dc6-b662-0b16db6376cf)

I would suggest going back to https://github.com/cilium/cilium/commit/73333666fa4e802f6eb51deedcceab9ef6782de9 and then rebase onto the latest `main` branch with `git rebase`, then amend the commit with the recent changes that you made.

2024-08-21 16:40 UTC, saintdle commented
> The easiest way is probably to walk back to an earlier copy and then rebase that and address the feedback afresh. If all of the latest changes have been merged into the patch, then it is likely to be tedious work to untangle that.
> 
> Scanning up through the PR I see this: ![image](https://private-user-images.githubusercontent.com/1243336/359980278-270dd2dd-0e5d-4dc6-b662-0b16db6376cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNTg2OTcsIm5iZiI6MTcyNDI1ODM5NywicGF0aCI6Ii8xMjQzMzM2LzM1OTk4MDI3OC0yNzBkZDJkZC0wZTVkLTRkYzYtYjY2Mi0wYjE2ZGI2Mzc2Y2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjFUMTYzOTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGY5NmU2Zjc2NTRiZDgzZmQxMjg2NWU0NTQ0NjcyMzMzMzdkNjU4NDljZDU2Zjk0YzY2MDMwOGU5M2Q0YzJlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MznjT-FVYBbOZIsyjmBfNP9xfQnniQKV0mLFibjYO3Y)
> 
> I would suggest going back to [7333366](https://github.com/cilium/cilium/commit/73333666fa4e802f6eb51deedcceab9ef6782de9) and then rebase onto the latest `main` branch with `git rebase`, then amend the commit with the recent changes that you made.

Thanks, will do that tomorrow, and moved back to draft, so that I can fix this up :)

2024-08-28 14:07 UTC, saintdle commented
> The easiest way is probably to walk back to an earlier copy and then rebase that and address the feedback afresh. If all of the latest changes have been merged into the patch, then it is likely to be tedious work to untangle that.
> 
> Scanning up through the PR I see this: ![image](https://private-user-images.githubusercontent.com/1243336/359980278-270dd2dd-0e5d-4dc6-b662-0b16db6376cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NTQyMzIsIm5iZiI6MTcyNDg1MzkzMiwicGF0aCI6Ii8xMjQzMzM2LzM1OTk4MDI3OC0yNzBkZDJkZC0wZTVkLTRkYzYtYjY2Mi0wYjE2ZGI2Mzc2Y2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMTQwNTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjliZTAzM2ZmNDk5MGQwYmZmZjBkMDAzNDM2NjhmMGVjZWJlNjdjMDY5NWE4MDRkMTc4NWUxNzQ0ZjEyNzZiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pOaXeH_xQ45_mc3xbDXjnZ9VvlyOt7ShKOP3WnJ0CJU)
> 
> I would suggest going back to [7333366](https://github.com/cilium/cilium/commit/73333666fa4e802f6eb51deedcceab9ef6782de9) and then rebase onto the latest `main` branch with `git rebase`, then amend the commit with the recent changes that you made.

It seems like I've fixed some of it, but not all of it, unfortunately, and I still have conflicts with two files. I'd really like to understand what I'm doing wrong here so I can fix it.

2024-09-09 15:40 UTC, joestringer commented on .nvim/nvim-dap.lua
> -}
It looks like this patch has a bunch of changes merged in that are unrelated to the change you're trying to make (probably you amended the commits to combine a merge commit plus your intended changes at some point). 

If you check out https://github.com/cilium/cilium/commit/73333666fa4e802f6eb51deedcceab9ef6782de9 and fix that one up for any feedback plus do a git rebase, these changes should go away. You can then force push your new copy of the branch over the top of the version in your repository that this PR is being opened from.

2024-10-25 01:59 UTC, closed without merging