pkg/endpointmanager: don't hold lock while iterating over subscribers
cilium/cilium pull request #33896
Opened 2024-07-18 20:14 UTC by aanm

Holding the lock while iterating over the subscribers is causing a potential deadlock with pkg/auth. Since pkg/auth is a subscriber of the endpoint manager, it will lock an internal mutex and then perform a GetEndpoints which will also perform a RLock to the endpointsmanager's Mutex. This itself is not an issue. However, on a separate go routine the pkg/auth will perform a lock on its internal mutex and then will do a GetEndpoints, causing inconsistent locking between these two cases which can cause a deadlock in the agent.

2024-07-18 20:14 UTC, aanm commented
/test

2024-07-19 09:38 UTC, joamaki commented
The mgr.mutex is used to also sequence the endpoint manager actions. If we don't hold the lock the callbacks may happen in arbitrary order, e.g. we could in principle get an "EndpointDeleted" before we get "EndpointCreated":
1. AddEndpoint is called. The subscribers is cloned and mutex released. Execution yielded before subscribers called.
2. RemoveEndpoint is called and subscribers called with EndpointDeleted.
3. (1) resumes and calls EndpointCreated.

I'm not sure if this is a problem as it depends on whether e.g. AddEndpoint is called in parallel or not, but it's worth thinking through these scenarios before doing this change.

2024-07-24 19:19 UTC, jrajahalme commented
I don's see the locking inconsistency in the PR/commit description, these look the same to me:

- it will lock an internal mutex and then perform a GetEndpoints which will also perform a RLock to the endpointsmanager's Mutex 
- a separate go routine the pkg/auth will perform a lock on its internal mutex and then will do a GetEndpoints

2024-07-24 19:22 UTC, jrajahalme commented
Also, the other goroutine's call to `GetEndpoints` could easily be changed to take the internal mutex after calling `GetEndpoints` if that could get around the inconsistency:
```
diff --git a/pkg/auth/authmap_gc.go b/pkg/auth/authmap_gc.go
index e175ad5763..312459232b 100644
--- a/pkg/auth/authmap_gc.go
+++ b/pkg/auth/authmap_gc.go
@@ -401,9 +401,11 @@ func (r *authMapGarbageCollector) cleanupExpiredEntries(_ context.Context) error
 // Endpoints
 
 func (r *authMapGarbageCollector) subscribeToEndpointEvents(endpointManager endpointmanager.EndpointManager) {
+	localEPs := endpointManager.GetEndpoints()
+
 	r.endpointsCacheMutex.Lock()
 	r.endpointsCache = map[uint16]*endpoint.Endpoint{}
-	for _, ep := range endpointManager.GetEndpoints() {
+	for _, ep := range localEPs {
 		r.endpointsCache[ep.GetID16()] = ep
 	}
 	r.endpointsCacheSynced = true
```

2024-08-01 07:52 UTC, jrajahalme requested changes
Please consider the comments above.

2024-08-14 09:04 UTC, aanm commented
/test

2024-08-23 14:17 UTC, jrajahalme approved these changes

2024-08-23 14:25 UTC, merged