docs:Updated bpf documentation files
cilium/cilium pull request #33969
Opened 2024-07-23 11:51 UTC by AdityaK60

Grammatically updated the documentations of bpf.

Signed-off-by: Aditya Kumar <aditya.kumar60@infosys.com>

2024-07-23 12:08 UTC, qmonnet approved these changes
Thanks! Please find a few remaining nits.

2024-07-23 12:08 UTC, qmonnet commented on Documentation/bpf/toolchain.rst
> +  like XDP BPF programs. Netronome's nfp supported NICs offer both
Missing comma before “like”?

2024-07-23 12:08 UTC, qmonnet commented on Documentation/bpf/toolchain.rst
> +  the single BPF program, and is therefore significantly
“a single BPF program” maybe?

2024-07-23 12:08 UTC, qmonnet commented on Documentation/bpf/toolchain.rst
> +however, a few differences when using ``clang --target=bpf`` versus
“There are however,” still sounds strange to me. With another comma maybe: “There are, however,” or even “However/Nonetheless, there are ...”.

2024-07-23 12:08 UTC, qmonnet requested changes
(I meant to request changes)

2024-07-23 12:12 UTC, AdityaK60 commented on Documentation/bpf/toolchain.rst
> +  like XDP BPF programs. Netronome's nfp supported NICs offer both
Ok

2024-07-24 09:32 UTC, qmonnet requested changes
Looks better, thanks! One missing space to fix, see below.

Could you also squash your commits together into a single commit, please?

2024-07-24 09:32 UTC, qmonnet commented on Documentation/bpf/toolchain.rst
> +Generally, LLVM IR generation is architecture independent.However, there are
Missing space.

```suggestion
Generally, LLVM IR generation is architecture independent. However, there are 
```

2024-07-24 09:36 UTC, AdityaK60 commented
> Could you also squash your commits together into a single commit, please?

How can I do that? Haven't done it before can you please suggest?

2024-07-24 10:03 UTC, qmonnet commented
> How can I do that? Haven't done it before can you please suggest?

Sure! The way I usually do this is in console, with interactive rebases in Git:

1. `git rebase -i main update_bpf_docs` (See the `--interactive` option in `man git rebase` for details)
2. This will open your default `$EDITOR` and show you a list of commits, where you can interactively decide what to do with each commits (available commands are described in the comments below the list):
   
   ![image](https://github.com/user-attachments/assets/796de6f9-e28f-4607-b596-6382f81cf5b2)

3. Change the actions for the second and third commits to `squash` (or just `s`) if you want to keep each commit title/description, or `fixup` (or just `f`) to discard it. Here we're OK with just the title and description of the first commit, so we can use `f`:

   ![image](https://github.com/user-attachments/assets/9884e1f5-86aa-49a1-81a6-1a7fddef0316)

4. Save the file and exit the editor. Git will apply the changes, and in this case squash the three commits together. Check with `git show`.

5. Force-push your changes: `git push -f AdityaK60 update_bpf_docs` or whatever's the name of your remote repository in your local Git setup.

2024-07-24 13:46 UTC, qmonnet approved these changes
Looks all good, thank you!

2024-07-24 13:46 UTC, qmonnet commented
/test

2024-07-24 14:02 UTC, merged