External L4B support
cilium/cilium pull request #34064
Opened 2024-07-29 13:36 UTC by YakhontovYaroslav

This PR consists of changes made by @borkmann in https://github.com/cilium/cilium/pull/31163, adapted to current master and unlocks use case described [here](https://github.com/cilium/cilium/issues/33611).

This is resulting traffic flow, once this change gets merged
<img width="833" alt="image" src="https://github.com/user-attachments/assets/899bcb95-3a37-4039-b53f-80594e5fbfd3">

2024-07-29 14:49 UTC, lmb approved these changes
Loader changes LGTM.

2024-07-30 09:17 UTC, joamaki requested changes
The commit history needs to be cleaned up (there should be no merge commits) and a proper descriptive commit message is needed. It seems like the helm changes are missing as well. And it probably would make sense to document this in https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#dsr-mode?

2024-07-30 09:17 UTC, joamaki commented on pkg/option/config.go
> +	EnableExternalDSR bool
Should there be an helm value for this or how would this be configured?

2024-08-08 22:52 UTC, tommyp1ckles commented
Thanks for the change 😃 

CLI changes look good to me, just waiting on the commit history.  For more information regarding what @joamaki was saying you can take a look at [this section of the docs](https://docs.cilium.io/en/latest/contributing/development/contributing_guide/#submitting-a-pull-request).

2024-08-30 08:37 UTC, joestringer commented
Marking this PR as draft while the feedback is addressed. Once you think this is ready for further review, you can click the "Ready for Review" button at the bottom of the page. Thank you for your contributions.

2024-10-15 01:59 UTC, closed without merging