Default allow K8s Network Policy tests
cilium/cilium pull request #3409
Opened 2018-03-30 09:57 UTC by nebril

2018-03-30 09:57 UTC, nebril commented
test-me-please

2018-03-30 10:28 UTC, nebril commented
test-me-please

2018-03-30 11:04 UTC, eloycoto commented
I've just spoke with @nebril and we'll wait to merge this PR until https://github.com/cilium/cilium/pull/3379 is merged

2018-03-30 14:45 UTC, nebril commented
test-me-please

2018-03-30 14:48 UTC, eloycoto approved these changes
Minor nitpick around Curfail ;-)

2018-03-30 14:48 UTC, eloycoto commented on test/k8sT/Policies.go
> +				helpers.CurlFail(fmt.Sprintf("http://%s/public", clusterIP)))
could you change to `elpers.CurlFail("http://%s/public", clusterIP))`?

+ the other ones added ;-)

2018-03-30 14:56 UTC, nebril commented
test-me-please

2018-03-30 15:51 UTC, manalibhutiyani approved these changes
looks good. please find comments inline

2018-03-30 15:51 UTC, manalibhutiyani commented on test/k8sT/Policies.go
> +		It("Allows traffic with k8s default-allowingress policy", func() {
Nit: default-allowingress -> default-allow ingress

2018-03-30 15:51 UTC, manalibhutiyani commented on test/k8sT/Policies.go
> +			epsWithEgress := 0
Can we not use this instead:

```
endpoints, err := kubectl.CiliumEndpointsListByLabel(ciliumPod, podFilter)
policyStatus := endpoints.GetPolicyStatus()
Expect(policyStatus[models.EndpointPolicyEnabledEgress]).Should(Equal(4))
```

2018-03-30 16:07 UTC, nebril commented on test/k8sT/Policies.go
> +			epsWithEgress := 0
I think we can, thanks!

2018-03-30 16:08 UTC, nebril commented
test-me-please

2018-03-30 17:16 UTC, nebril commented
test-me-please

2018-03-30 19:06 UTC, nebril commented
test-me-please

2018-03-31 08:29 UTC, nebril commented
test-me-please

2018-03-31 11:54 UTC, nebril commented
test-me-please

2018-04-03 10:37 UTC, nebril commented
test-me-please

2018-04-03 13:17 UTC, nebril commented
test-me-please

2018-04-04 14:21 UTC, aanm requested changes

2018-04-04 14:21 UTC, aanm commented on test/k8sT/Policies.go
> +			res.ExpectSuccess("Ingress connectivity should be allowed by policy")
If this should be allowed, shouldn't the `CurlFail` be `Curl` in the previous line?

2018-04-04 14:21 UTC, aanm commented on test/k8sT/Policies.go
> +			res.ExpectSuccess("Ingress connectivity should be allowed by policy")
Same here

2018-04-04 14:21 UTC, aanm commented on test/k8sT/Policies.go
> +				res.ExpectSuccess("Egress connectivity should be allowed for pod %q", pod)
Same here

2018-04-04 14:21 UTC, aanm commented on test/k8sT/manifests/1.7/knp-default-allow-ingress.yaml
> +apiVersion: networking.k8s.io/v1
You can remove this file. In 1.7, `policyTypes` is ignored by kube-apiserver

2018-04-06 13:08 UTC, nebril commented on test/k8sT/Policies.go
> +			res.ExpectSuccess("Ingress connectivity should be allowed by policy")
Good point.

2018-04-06 13:25 UTC, nebril commented
test-me-please

2018-07-07 18:42 UTC, ianvernon commented
@nebril can you please close this since https://github.com/cilium/cilium/pull/4133 took care of default allow?

2018-07-09 06:39 UTC, eloycoto requested changes

2018-07-09 06:39 UTC, eloycoto commented on test/k8sT/Policies.go
> +			eps := kubectl.CiliumEndpointPolicyVersion(ciliumPod)
Please delete this one, with the use of CiliumPolicyAction should be ok.

2018-07-09 06:39 UTC, eloycoto commented on test/k8sT/Policies.go
> +			defer func() {
Please don't use defer in the functions, the cleanup should happens on AfterEach.

2018-07-09 06:39 UTC, eloycoto commented on test/k8sT/Policies.go
> +			err = helpers.WaitUntilEndpointUpdates(ciliumPod, eps, 4, kubectl)
These lines should be removed, CiliumPolicyAction take care of that.

2018-07-09 06:39 UTC, eloycoto commented on test/k8sT/Policies.go
> +			eps := kubectl.CiliumEndpointPolicyVersion(ciliumPod)
Please remove this lines, as the other test.

2018-07-09 06:39 UTC, eloycoto commented on test/k8sT/Policies.go
> +			defer func() {
Please remove teh policy on AfterEach.

2018-07-09 16:56 UTC, closed without merging