ipsec: Document a new cause of XfrmInStateProtoError
cilium/cilium pull request #34221
Opened 2024-08-07 08:40 UTC by jschwinger233

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note

```

2024-08-07 12:07 UTC, jschwinger233 commented
/test

2024-08-09 13:42 UTC, learnitall requested changes
Thanks! Just one small nit but otherwise LGTM.

2024-08-09 13:42 UTC, learnitall commented on Documentation/security/network/encryption-ipsec.rst
> +   performing a new key rotation, properly.
```suggestion
   from the anti-reply oseq on the destination node. This can be fixed by
   properly performing a new key rotation.
```

2024-08-09 13:54 UTC, rgo3 approved these changes

2024-08-16 08:56 UTC, jschwinger233 commented on Documentation/security/network/encryption-ipsec.rst
> +   performing a new key rotation, properly.
Just fixed, thank you!

2024-08-16 08:56 UTC, jschwinger233 commented
/test

2024-08-20 16:36 UTC, learnitall approved these changes
Thanks!

2024-08-20 19:28 UTC, merged