egw: escape vlan interface names in sysctl rpfilter path
cilium/cilium pull request #34220
Opened 2024-08-07 07:58 UTC by henry-spanka

This PR escapes "." meta character in sysctl path. VLAN interface names contain a "." (dot) which is interpreted by sysctl as new directory.

Fixes: #34217

2024-08-13 20:17 UTC, liyihuang commented
Any update on this PR? I ran into the same issue in my test environment and trying to see when this can be merged and backpacked to 1.15

2024-08-14 06:52 UTC, henry-spanka commented
I fixed checks in tests and renamed second egress interface. Is this sufficient?

2024-08-15 13:59 UTC, julianwiedmann commented
/test

2024-08-16 07:05 UTC, julianwiedmann commented
@henry-spanka just checking - did you test your patch locally? The [CI fail](https://github.com/cilium/cilium/actions/runs/10404992978/job/28814824223#step:17:358) for the test you added indicates to me that it's not working as expected, since the sysctl gets rejected [here](https://github.com/cilium/cilium/blob/fc9f58248b3ee5828c6ab305ab303cc736d14e81/pkg/datapath/linux/sysctl/sysctl.go#L283).

But with the test you added, you should be able to iterate more quickly now :)

2024-08-16 07:25 UTC, ysksuzuki commented
I think we need to fix the sysctl package to be able to handle the case where the link name contains dots. Looks like we can't let the sysctl package to process  a path such as `/proc/sys/net/ipv4/conf/cilium_egw2.100` currently
https://github.com/cilium/cilium/blob/4219e5c3292612b7ecd221d39a683de1996ce71a/pkg/datapath/linux/sysctl/sysctl.go#L279

2024-08-16 07:33 UTC, henry-spanka commented
Sort of. I'll take a look later and make sure tests pass ...

2024-08-20 07:24 UTC, dylandreimerink requested changes
I suggest we fix this in the sysctl package by creating new versions of the existing functions which take a `[]string` instead of a `string` as `Name`. The sysctl can then join the slice without having to reserve any symbols as separator. This will allow for dots in the individual sections.

We should then also look over the rest of the codebase to see where we use interface names, its likely a lot of places, and start using the new functions there as well. (We should make an issue to track this, doesn't have to happen in this PR)

2024-08-20 07:24 UTC, dylandreimerink commented on pkg/egressgateway/manager.go
> +				Name:      fmt.Sprintf("net.ipv4.conf.%s.rp_filter", strings.ReplaceAll(ifaceName, ".", "/")),
This doesn't actually fix the issue, when the sysctl package converts the remaining dots you end up with the same result.

2024-08-23 08:20 UTC, dylandreimerink commented
I made https://github.com/cilium/cilium/pull/34527 which fixes the root cause as described, including for all other callsites.

2024-08-30 09:04 UTC, joestringer commented
@henry-spanka do you think you could take a look at #34527 and review or test it out to see if it addresses the same issue you're observing?

2024-08-30 09:06 UTC, joestringer commented
> We should then also look over the rest of the codebase to see where we use interface names, its likely a lot of places, and start using the new functions there as well. (We should make an issue to track this, doesn't have to happen in this PR)

@dylandreimerink do you think you're likely to have more context about how to find those? I would welcome @henry-spanka to file the issue if they have the context, but as a first-time contributor that might be difficult.

2024-08-30 11:09 UTC, dylandreimerink commented
> @dylandreimerink do you think you're likely to have more context about how to find those?

For https://github.com/cilium/cilium/pull/34527 I used the find all references functionality of gopls/vscode to find all usages, its a bit of work but doable.

2024-09-13 15:28 UTC, julianwiedmann commented
https://github.com/cilium/cilium/pull/34527 resolved this for `v1.16` and `main`, while https://github.com/cilium/cilium/pull/34830 will bring the toleration for errors when setting RP filter into `v1.15`.

So I think the issue is addressed - I'll flip this PR to draft state so it falls off my review queue. @henry-spanka Please close the PR if you agree, thank you for bringing this problem up! :)

2024-09-16 06:06 UTC, closed without merging

2024-09-16 06:07 UTC, henry-spanka commented
Yes looks good. Thank you very much.