Remove deprecated grpc option from pkg/kvstore/etcd_debug.go
cilium/cilium pull request #34269
Opened 2024-08-09 09:22 UTC by davchos

Remove deprecated grpc option from pkg/kvstore/etcd_debug.go

  Related:#32274

  Signed-off-by: David CHOSROVA <dchosrova@gmail.com>

2024-08-19 14:42 UTC, giorio94 requested changes
Thanks @davchos for the PR.

Unfortunately, removing that option alone modifies the behavior of the troubleshooting tool. For context, the goal of this specific snippet is to determine whether it is possible to correctly connect to the configured etcd instance, and report an error otherwise. Currently, the check is performed in two steps, first to assert that it is actually possible to establish the connection, and then to verify that it is possible to retrieve a given key (as a basic authorization check). Removing the `WithBlock` option leads the first check to succeed even if the connection cannot be established (with the subsequent error being possibly confusing), as well as causes the `DialTimeout` to no longer be effective (hence falling back to the global timeout, which is 5 seconds by default). 

To preserve a similar behavior as the current one with minimal code changes, I'd suggest to:
* Check upon `cl.Get` failure whether `cl.ActiveConnection().GetState() == connectivity.TransientFailure`, and in that case output the `Failed to establish connection` error message, rather than `Failed to retrieve key from etcd`.
* Create a dedicated subcontext with a 1 second timeout for the `cl.Get` operation, so that it terminates early in case of failures;
* Drop the `DialTimeout` setting, as no longer effective;

2024-08-19 17:07 UTC, davchos commented
> Thanks @davchos for the PR.
> 
> Unfortunately, removing that option alone modifies the behavior of the troubleshooting tool. For context, the goal of this specific snippet is to determine whether it is possible to correctly connect to the configured etcd instance, and report an error otherwise. Currently, the check is performed in two steps, first to assert that it is actually possible to establish the connection, and then to verify that it is possible to retrieve a given key (as a basic authorization check). Removing the `WithBlock` option leads the first check to succeed even if the connection cannot be established (with the subsequent error being possibly confusing), as well as causes the `DialTimeout` to no longer be effective (hence falling back to the global timeout, which is 5 seconds by default).
> 
> To preserve a similar behavior as the current one with minimal code changes, I'd suggest to:
> 
> * Check upon `cl.Get` failure whether `cl.ActiveConnection().GetState() == connectivity.TransientFailure`, and in that case output the `Failed to establish connection` error message, rather than `Failed to retrieve key from etcd`.
> * Create a dedicated subcontext with a 1 second timeout for the `cl.Get` operation, so that it terminates early in case of failures;
> * Drop the `DialTimeout` setting, as no longer effective;

Hi @giorio94 ,

Thanks for the feedback and explanation, I make the changes.

David

2024-08-21 08:04 UTC, giorio94 reviewed
Thanks, just a couple of final nits inline. 
Could you please also squash the two commits into one?

2024-08-21 08:04 UTC, giorio94 commented on pkg/kvstore/etcd_debug.go
> +		iiw.Println("❌ failed to create gRPC client: %s", err)
```suggestion
		iiw.Println("❌ Failed to create etcd client: %s", err)
```

2024-08-21 08:04 UTC, giorio94 commented on pkg/kvstore/etcd_debug.go
>  	// It doesn't really matter whether the heartbeat key exists or not.
Could you please update the comment to mention the fact that `client.New` does not block on connection failure, and hence we need to check the connection state to determine the type of failure?

2024-08-21 14:15 UTC, giorio94 reviewed
Thanks, the patch looks good to me. Last thing before running the tests and approving, could you please generalize the commit message to describe the actual change, rather than the review modifications?

2024-08-21 15:13 UTC, davchos commented
> Thanks, the patch looks good to me. Last thing before running the tests and approving, could you please generalize the commit message to describe the actual change, rather than the review modifications?

Thanks for walking me through that change, I appreciate.

2024-08-21 17:37 UTC, giorio94 approved these changes
Thanks!

(You'll need to rebase onto main to make CI happy)

2024-08-21 18:25 UTC, giorio94 commented
/test

2024-08-22 08:41 UTC, merged