pr/christarazi/k8s 1.31
cilium/cilium pull request #34463
Opened 2024-08-20 06:32 UTC by christarazi

- **go.mod: Bump controller-tools to v0.16.1**
- **docs: Update kindest/node instructions for K8s upgrade**
- **k8s: Add support for 1.31.0**

2024-08-20 06:39 UTC, christarazi commented
/test

2024-08-20 15:51 UTC, learnitall approved these changes
Docs changes look good, thanks!

2024-08-21 03:25 UTC, julianwiedmann approved these changes

2024-08-21 07:57 UTC, viktor-kurchenko approved these changes

2024-08-21 08:03 UTC, marseel approved these changes

2024-08-21 08:10 UTC, tklauser approved these changes
The ["Build commits" workflow failure](https://github.com/cilium/cilium/actions/runs/10466497702/job/28983469640?pr=34463) looks legitimate. Probably the commits need to be reordered/squashed?

Otherwise LGTM, thanks!

2024-08-21 09:11 UTC, squeed approved these changes

2024-08-23 02:18 UTC, christarazi commented
CI should be fixed now. There was a breaking change in the K8s code generation dependencies that was tricky to nail down. See first commit msg for more details.

2024-08-23 03:02 UTC, christarazi commented
/test

2024-08-23 21:05 UTC, christarazi commented
Still seeing some CI failures, investigating. For now I'll put it into draft.

2024-08-30 06:02 UTC, sayboras commented
Ingress and Gateway API failures will be fixed after the below PRs are merged

https://github.com/cilium/cilium/pull/34575
https://github.com/cilium/cilium/pull/34576

2024-09-02 12:10 UTC, aanm requested changes

2024-09-02 12:10 UTC, aanm commented on .github/actions/ginkgo/main-k8s-versions.yaml
> +    kube-image: "quay.io/cilium/kindest-node:v1.31.0-rc.1@sha256:892dad427fa73e80ff16e26e287fae4d45aeaf8055206936e42f82b1dfedf2a4"
`quay.io/cilium/kindest-node:v1.31.0@sha256:7e3cb518db362bee6a507dd5c9aa288a979ee8899be88231cdd4e9ca4079ac30`

2024-09-02 12:31 UTC, sayboras commented
> Ingress and Gateway API failures will be fixed after the below PRs are merged
> 
> #34575 #34576

I have rebased with main branch, also fix the conflict with main (due to my changes) and force pushed.

2024-09-02 12:31 UTC, sayboras commented
/test

2024-09-06 20:51 UTC, christarazi commented
/test

2024-09-08 10:10 UTC, sayboras commented
/test

2024-09-08 12:11 UTC, sayboras commented
Force pushed to fix the related CI failures + rebase with main branch. 

All CI jobs seem green now, marking this ready for review if you don't mind.

2024-09-08 12:25 UTC, sayboras approved these changes

2024-09-09 08:28 UTC, aanm approved these changes

2024-09-09 08:39 UTC, sayboras commented
/test

2024-09-09 09:51 UTC, merged

2024-09-09 11:51 UTC, julianwiedmann commented
Given that this touches CI - should it have been tested from a cilium/cilium branch, instead of a forked repo?

2024-09-09 12:09 UTC, mhofstetter commented
> Given that this touches CI - should it have been tested from a cilium/cilium branch, instead of a forked repo?

Probably yes. It seems as `/ci-ginkgo` fails for k8s v1.27 after removing the mapping k8s v1.27 to kind image

```
Error: cannot pull image quay.io/lvh-images/kind:: invalid reference format
```

Trying to fix it over here: https://github.com/cilium/cilium/pull/34773

2024-09-09 17:11 UTC, christarazi commented
> Given that this touches CI - should it have been tested from a cilium/cilium branch, instead of a forked repo?

Hm, that's something I didn't think about. I'll update the docs to explicitly mention this detail so we can avoid this situation on the next K8s bump.