support network programming latency SLI.
cilium/cilium pull request #34492
Opened 2024-08-21 13:50 UTC by weiwei02

support network programming latency SLI.

Kubernetes network programming latency is defined as the time it took to program the network - from the time the service or pod has changed to the time the change was propagated and the proper kube-proxy/cilium rules were synced. Exported for each endpoints object that were part of the rules sync.
[network_programming_latency](https://github.com/kubernetes/community/blob/master/sig-scalability/slos/network_programming_latency.md)

Fixes: #34147

```release-note
support network programming latency SLI.
```

2024-08-22 10:25 UTC, nebril requested changes
Thanks for the PR! I left several comments, I think the biggest issue is about validity of latency in `service_cache`, LMK if that sounds right to you.

2024-08-22 10:25 UTC, nebril commented on pkg/k8s/endpoints_tracker.go
> +func (tracker *EndpointsChangeTracker) EndpointUpdate(serviceID ServiceID, annotations map[string]string, remove bool) (start time.Time) {
Could we split this function into `EndpointUpdate` and `EndpointRemove`? As far as I understand we don't set the `remove` arg programmatically anywhere, so this would make these functions a bit more readable.

2024-08-22 10:25 UTC, nebril commented on pkg/k8s/endpoints_tracker.go
> +type EndpointsChangeTracker struct {
I might be alone here, but Endpoint is a very loaded term in Cilium and usually refers to Cilium Endpoints. Can we change naming here to `ServiceEndpoints` or `K8sEndpoints`, which this actually refers to?

2024-08-22 10:25 UTC, nebril commented on pkg/k8s/endpoints_tracker.go
> +		scopedLog.WithField("value", annotations[core_v1.EndpointsLastChangeTriggerTime]).
How often do we expect errors here and what can we do to mitigate them?

Can we add an action that cluster operator can take to mitigate this error?

AFAIU if we end up with a broken time annotation, the logs will just be peppered with errors, right?

2024-08-22 10:25 UTC, nebril commented on pkg/k8s/endpoints_tracker.go
> +	scopedLog := tracker.log.WithField(logfields.EndpointID, serviceID.String())
`logfields.EndpointID` is usually reserved to Cilium Endpoint numerical ID, you can use `logfields.ServiceName` and `logfields.ServiceNamespace` with values from `serviceID.Name(space)`.

2024-08-22 10:25 UTC, nebril commented on Documentation/observability/metrics.rst
> +``k8s_network_programming_duration_seconds``                                                  Enabled    Duration in seconds of network programming
Nitpick: Can we word this as "Duration of network programming in seconds"?

2024-08-22 10:25 UTC, nebril commented on pkg/k8s/service_cache.go
> +			EndpointLastChangeTriggerTime: triggerTime,
Based on the comment next to the metric, I am not sure if this is the correct place to measure the time from.
```
	// KubernetesNetworkProgrammingLatency is defined as the time it took to program the network - from the time
	// the service or pod has changed to the time the change was propagated and the proper kube-proxy/cilium
	// rules were synced.
```

There is bound to be some time between K8s object change and the time this event gets propagated to Cilium.

I think the correct way to get this data is to implement using `ManagedFields` in slim Service objects that we use which is currently unimplemented: https://github.com/cilium/cilium/blob/main/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L1300 and use `Time` field from these to figure out when object was last changed.

2024-08-22 16:18 UTC, derailed requested changes
@weiwei02 Thank you for this PR! Looks good.
I think it might be best to guard this feature via an option so folks can opt in/out.

2024-08-22 16:18 UTC, derailed commented on pkg/k8s/endpoints_tracker.go
> +		delete(tracker.lastChangeTriggerTime, serviceID)
if remove is set we are done here. Best to just return

2024-08-22 16:18 UTC, derailed commented on pkg/k8s/endpoints_tracker.go
> +	return
empty return is not needed

2024-08-22 16:18 UTC, derailed commented on pkg/k8s/endpoints_tracker_test.go
> +	tracker := NewEndpointsChangeTracker()
nit: Might be best to use table testing to highlight the various test cases.

2024-08-26 07:07 UTC, weiwei02 commented
> @weiwei02 Thank you for this PR! Looks good. I think it might be best to guard this feature via an option so folks can opt in/out.

Okay, thank you for your suggestion. I will try to add an option to this indicator to control the switch.

2024-08-31 13:31 UTC, joestringer commented
Thanks for contributing, this looks like a useful extension.

This seems to express a very generic "network programming" metric but in fact it is only related to services. Given that Cilium handles many aspects of networking, the name of the metric should probably be scoped to services if the metric is only intended to capture service behaviour.

Could you also expand the "SLI" acronym at least once so that readers unfamiliar with the acronym can get a sense for what the acronym means?

Please avoid "merge" commits in favour of rebasing on top of the upstream `main` branch; we aim to keep a clean list of commits on top of main without branches/merging, as this eases bisection.

I've updated the release note description in the PR description to something that I think users should be able to understand when reading through release notes for the upcoming version which will include this functionality, please double-check I got that right.

2024-09-03 09:42 UTC, nebril commented on pkg/k8s/service_cache.go
> +			EndpointLastChangeTriggerTime: triggerTime,
@weiwei02 can you tell me how you resolved this?

2024-09-03 09:43 UTC, nebril commented on pkg/k8s/endpoints_tracker.go
> +		scopedLog.WithField("value", annotations[core_v1.EndpointsLastChangeTriggerTime]).
@weiwei02 I think the logs are still lacking in terms of providing means to mitigate the problem.

2024-09-03 09:43 UTC, nebril requested changes
Thanks for updating the PR! There are still 2 more comments that I feel didn't get fully resolved.

2024-09-06 17:40 UTC, joestringer requested changes

2024-09-06 17:40 UTC, joestringer commented on pkg/metrics/metrics.go
> +			ConfigName: Namespace + "_" + SubsystemK8s + "_network_programming_duration_seconds",
Let's at least ensure that the metric is named accurately - this is not currently tracking network programming latency, it is very specific to services.

2024-09-06 17:40 UTC, joestringer commented
I'll mark the PR as draft while the feedback is addressed. When it's ready again, please use the "Ready for Review" button at the bottom of the page to bring it back to the attention of reviewers.

2024-10-21 02:00 UTC, closed without merging

2024-12-17 18:39 UTC, jpayne3506 commented
Going to pick this up.