Test: Simplified Kafka K8S test
cilium/cilium pull request #3456
Opened 2018-04-02 11:29 UTC by eloycoto

- Add a livenessProbe in kafka manifest, wait until kafka is ready.
- Make test code clear
- Add CepGet in kubectl.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

2018-04-02 11:31 UTC, eloycoto commented
test-me-please

2018-04-02 13:13 UTC, eloycoto commented
test-me-please

2018-04-02 17:38 UTC, manalibhutiyani requested changes
I think the fact that this is a multi-node setup is not taken into account. Please correct me if I am wrong. Also, the comment explaining the multinode setup helps people to understand the code better when reading it for the first time. Could you put that back.

2018-04-02 17:38 UTC, manalibhutiyani commented on test/k8sT/KafkaPolicies.go
> -		ciliumPod1, _ := kubectl.WaitCiliumEndpointReady(podFilter, helpers.K8s1)
@eloy: This is a multimode setup, with 

 ```
Kafka multinode setup:
 
 			K8s1:
 				1. empire-backup
 				2. empire-hq
 				3. kafka-broker : ingress policy only
 
 			K8s2:
 			   1. zook
 			   2. empire-outpost-8888
 			   3. empire-outpost-9999
```
 	

You are only testing for k8s2 nodes and have removed the logic for making sure all pods are up on k8s1

2018-04-02 17:38 UTC, manalibhutiyani commented on test/k8sT/KafkaPolicies.go
> -		/*
Why was this comment removed? This helps to understand the Kafka multimode setup. Could you please put it back?

2018-04-02 17:38 UTC, manalibhutiyani commented on test/k8sT/KafkaPolicies.go
> -		Expect(policyStatus1[models.EndpointPolicyEnabledIngress]).Should(Equal(1))
Why are we not testing the `EndpointPolicyEnabled` status anymore?

2018-04-02 17:38 UTC, manalibhutiyani commented on test/k8sT/KafkaPolicies.go
> +		ciliumPod, err = kubectl.GetCiliumPodOnNode(helpers.KubeSystemNamespace, helpers.K8s2)
Should we not be doing this for k8s1 ? This is a multinode setup?

2018-04-02 17:48 UTC, manalibhutiyani commented on test/k8sT/manifests/kafka-sw-app.yaml
>        nodeSelector:
I think we want to truly randomize it we need to remove the constaints on `nodeSelector:` of all the app pods

2018-05-01 13:13 UTC, eloycoto commented
test-me-please

2018-05-01 13:25 UTC, eloycoto commented
Hi @manalibhutiyani 

Before you review again, let me explain a few things:

*Delete the nodeselector in manifest*

This is due that we want to schedule pods randomly, and we don't want to have
one pod in each node, with this method all pods are always scheduled in a
random way, so we are sure that different scenarios work,example:

```
vagrant@k8s1:~$ kubectl get pods -o wide -l zgroup=kafkaTestApp
NAME                                   READY     STATUS    RESTARTS   AGE       IP            NODE
empire-backup-67674d68db-rl4jf         1/1       Running   0          58s       10.10.1.238   k8s2
empire-hq-bc4bfbcc6-2v759              1/1       Running   0          58s       10.10.0.4     k8s1
empire-outpost-8888-9b8665f48-4rnpl    1/1       Running   0          58s       10.10.1.147   k8s2
empire-outpost-9999-5d98d9d668-lm2nw   1/1       Running   0          58s       10.10.1.159   k8s2
kafka-broker-7db77df494-wn25m          1/1       Running   1          58s       10.10.1.158   k8s1
zookeeper-9c79c7448-hnd7g              1/1       Running   0          58s       10.10.1.187   k8s2
```

Plus, this is super useful if you want to run the test with only one node instead of two.

*Deleting ciliumPod endpoint list*

As you see we don't check the endpoints status using
`kubectl.CiliumEndpointsListByLabel` and count the output. I added a new method
`kubectl.CepGet` that uses the *Cilium endpoint kubernetes resource* and we can
retrieve that info using `kubectl`. On the other hand, instead of checking how
many endpoints has the policy enabled/disabled, we check that each pod has the
correct value.

*Added a new healthcheck on kafka manifest*

In this case wait until pod is running that Kafka is listening, this helps to
avoid weird race conditions where Pod is `ready` state but kafka is not
listening yet. With this check Kubernetes take care of that.


The PR tried to make things easier, this work will be replicated to
`K8st/Policies.go` and `K8st/Services.go` when this PR get merged, so if you
can review asap I'll be grateful.

Thanks
Eloy

2018-05-01 16:28 UTC, manalibhutiyani requested changes

2018-05-01 16:28 UTC, manalibhutiyani commented on test/helpers/kubectl.go
> +		log.Debug("cep is not presnet")
nit `presnet` -> `present`

2018-05-01 16:28 UTC, manalibhutiyani commented on test/k8sT/KafkaPolicies.go
> +		Expect(err).Should(BeNil(), "EmpireHQApp cannot announce HQ")
`EmpireHQApp cannot announce HQ` does not convey what Kafka message failed.
Please change this to 
`Failed to produce to empire-hq on topic empire-announce`

2018-05-01 16:28 UTC, manalibhutiyani commented on test/k8sT/KafkaPolicies.go
> +		Expect(err).Should(BeNil(), "OutpostApp cannot announce Outpost")
Ditto. this does not convey what Kafka message and topic failed on which action. Please change the message back to `Failed to consume from outpost on topic empire-announce`

2018-05-01 16:28 UTC, manalibhutiyani commented on test/k8sT/KafkaPolicies.go
> +		Expect(err).Should(BeNil(), "EmpireHqApp cannot produce messages")
Ditto:
`EmpireHqApp cannot produce messages` does not convey on which topic. Please change back to
`Failed to produce to empire-hq on topic deathstar-plans`

2018-05-01 16:28 UTC, manalibhutiyani commented on test/k8sT/KafkaPolicies.go
> +		Expect(err).Should(BeNil(), "OutpostApp cannot produce messages")
Ditto. `OutpostApp cannot produce messages` does not convey the topic. Please change back to `Failed to consume from outpost on topic deathstar-plans`

2018-05-01 16:28 UTC, manalibhutiyani commented on test/k8sT/KafkaPolicies.go
> +		Expect(err).Should(BeNil(), "BackupApp cannot not announce")
`BackupApp cannot not announce` ---> `Failed to produce to backup on topic empire-announce`
This specifies exactly what action on what topic failed for the particular apps.

2018-05-01 16:28 UTC, manalibhutiyani commented on test/k8sT/KafkaPolicies.go
> +		Expect(err).Should(BeNil(), "OutpostApp cannot not annouce")
`OutpostApp cannot not annouce` does not make a lot of sense to me.
Maybe change to `Failed to produce to outpost on topic empire-announce`

2018-05-02 06:17 UTC, eloycoto commented
@manalibhutiyani Sorry, I added the assert messages at that time, and you updated them meanwhile and in the merge I keep the wrong lines. 

This PR should ok now. Sorry!

2018-05-02 06:17 UTC, eloycoto commented
test-me-please

2018-05-02 16:49 UTC, manalibhutiyani approved these changes

2018-05-04 16:01 UTC, ianvernon approved these changes

2018-05-04 16:02 UTC, merged