endpoint: Delete the dirty data of old endpoint when create new endpoint
cilium/cilium pull request #34595
Opened 2024-08-28 02:28 UTC by orange30

1, the CNI deletion and delelteendpoint is  asynchronous.
2, when the CNI deletion is completed, then for example we are update the cilium-agent pod or the pod is rebooted for internal bug, the data of the old endpoint will be a dirty data.  
3, For this case, I think we should delete it automatically like this patch。
4，Is there any negative impact? I think the uniqueness of the assigned ip is the first principle for and ipamd binary, so it should almost impossible to happen; so for this case, we just need to record it in log of warning.

2024-08-28 03:59 UTC, orange30 commented
@tgraf
https://github.com/cilium/cilium/commit/022f196da22c5bbc81a574fbf60c2b85e437c9ce

2024-09-17 16:11 UTC, ldelossa commented on daemon/cmd/endpoint.go
> +			// return invalidDataError(ep, fmt.Errorf("IP %s is already in use", id))
Stale comment?

2024-09-19 05:35 UTC, orange30 commented on daemon/cmd/endpoint.go
> +			// return invalidDataError(ep, fmt.Errorf("IP %s is already in use", id))
The comment has been deleted.

2024-09-19 17:58 UTC, joestringer requested changes
Hi, thanks for the PR.

This sounds like either a bug somewhere else, or something that can be resolved with retries in the CNI. If the Cilium agent thinks that this Endpoint is still valid, then the container runtime -> CNI should be reliably forwarding the "delete" event before attempting to create a fresh endpoint with the same IP. This feels dangerous, that it could unintentionally end up affecting an actual live Endpoint with unexpected behaviour.

Do you have a way to reliably reproduce this behaviour? Such a test case would be invaluable to coming up with the right solution to this problem.

2024-09-19 18:00 UTC, joestringer commented
> 2, when the CNI deletion is completed, then for example we are update the cilium-agent pod or the pod is rebooted for internal bug, the data of the old endpoint will be a dirty data.

When this step completes, the endpoint should already be deleted. If that's not happening, then that's a bug in the CNI delete handling. I don't think it's the right solution to try to resolve a bug there by changing the CNI creation behavior.

2024-09-20 11:33 UTC, orange30 commented
> > 2, when the CNI deletion is completed, then for example we are update the cilium-agent pod or the pod is rebooted for internal bug, the data of the old endpoint will be a dirty data.
> 
> When this step completes, the endpoint should already be deleted. If that's not happening, then that's a bug in the CNI delete handling. I don't think it's the right solution to try to resolve a bug there by changing the CNI creation behavior.

https://github.com/containerd/containerd/issues/5438

2024-09-20 11:41 UTC, orange30 commented
> > 2, when the CNI deletion is completed, then for example we are update the cilium-agent pod or the pod is rebooted for internal bug, the data of the old endpoint will be a dirty data.
> 
> When this step completes, the endpoint should already be deleted. If that's not happening, then that's a bug in the CNI delete handling. I don't think it's the right solution to try to resolve a bug there by changing the CNI creation behavior.

Our problem scenario is that sometimes containerd donot call cmdDel Correctly, so the endpoint become dirty data.
https://github.com/containerd/containerd/issues/5438
《CRI fails to invoke CNI plugin to teardown network when RunPodSandbox times out》

So if we use cilium with some old version of contained, it is possible to get some dirty endpoint, and then  if the new pod using the same ip will failed.  @joestringer

2024-09-20 17:58 UTC, joestringer commented
If the bug is in containerd and fixed three years ago, then the solution is to upgrade containerd. Cilium doesn't accept patches to work around such bugs.

2024-09-20 17:58 UTC, closed without merging