route: Add DeleteV4 helper function
cilium/cilium pull request #34600
Opened 2024-08-28 12:20 UTC by pippolo84

Add DeleteV4 to delete an IPv4 route. Differently from Delete, DeleteV4 does not discard Priority, Local, Type, MTU and Scope fields when sending the deletion request via netlink.

2024-08-28 12:20 UTC, pippolo84 commented
/test

2024-08-28 13:56 UTC, pippolo84 commented
/test

2024-08-29 07:38 UTC, jibi approved these changes

2024-08-29 08:46 UTC, pippolo84 commented
/test

2024-08-30 08:06 UTC, closed without merging

2024-08-30 08:07 UTC, joestringer requested changes
The code looks fine to me, but we would expect the user of this code to be added to refer to this function as well, otherwise we get a lot of potentially stale code in the tree.