docs: Extend Hubble Performance Tuning Documentation
cilium/cilium pull request #34665
Opened 2024-09-03 12:14 UTC by glrf

Please ensure your pull request adheres to the following guidelines:

- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.

This change restructures the Hubble performance tuning guide and adds sections on the Hubble event queue and the monitor aggregation interval.

2024-09-04 04:39 UTC, ysksuzuki approved these changes

2024-09-04 08:59 UTC, qmonnet requested changes
A couple of tiny nits/typos, but looks good otherwise, thanks!

2024-09-04 08:59 UTC, qmonnet commented on Documentation/operations/performance/tuning.rst
> +length to 128k, further increasing the event queue size unlikely to help.
```suggestion
length to 128k, further increasing the event queue size is unlikely to help.
```

2024-09-04 08:59 UTC, qmonnet commented on Documentation/operations/performance/tuning.rst
> +usage. Depending on your traffic pattern, increasing the queue size by ``10'000`` may
```suggestion
usage. Depending on your traffic pattern, increasing the queue size by ``10,000`` may
```

2024-09-04 08:59 UTC, qmonnet commented on Documentation/operations/performance/tuning.rst
> +You can also choose to stop exposing event types in which you
No need for the additional blank line

```suggestion
You can also choose to stop exposing event types in which you
```

2024-09-04 09:41 UTC, qmonnet approved these changes
Thanks!

2024-09-04 09:41 UTC, qmonnet commented
/test

2024-09-04 10:24 UTC, merged

2024-09-25 10:06 UTC, mkilchhofer commented on Documentation/operations/performance/tuning.rst
> +             --set bpf.events.monitorInterval="10s"
"bpf.**events**.monitorInterval"
and
"bpf.**events**.monitorInterval"
seems not existing. Is it a regression? I think the key `events` is obsolete and the interval can be controlled directly via `bpf.monitorInterval`: https://github.com/search?q=repo%3Acilium%2Fcilium%20%22bpf.monitorInterval%22&type=code