ipsec: Remove deprecated upgrade code
cilium/cilium pull request #34709
Opened 2024-09-05 13:43 UTC by pchaigno

```release-note
Remove support for the insecure, deprecated global IPsec key. Per-tunnel IPsec keys will now be used regardless of the IPsec secret format.
```

2024-09-05 14:10 UTC, pchaigno commented
/test

2024-09-05 16:20 UTC, pchaigno commented
/test

2024-09-05 18:19 UTC, pchaigno commented
/ci-clustermesh

2024-09-06 08:09 UTC, pchaigno commented
/test

2024-09-06 10:09 UTC, aanm requested changes, later dismissed

2024-09-06 10:09 UTC, aanm commented on .github/actions/ipsec-key-rotate/action.yaml
> +  nb-nodes:
```suggestion
  number-nodes:
```

2024-09-06 10:09 UTC, aanm commented on .github/workflows/conformance-eks.yaml
> +          nb-nodes: 3
```suggestion
          number-nodes: 3
```

2024-09-06 12:01 UTC, julianwiedmann reviewed
Just one question, the change looks good!

2024-09-06 12:01 UTC, julianwiedmann commented on .github/workflows/conformance-ipsec-e2e.yaml
> +            --from-literal=keys="3+ ${key}"
Can't we just phase out the `+` symbol instead (except in downgrade tests) ?

And have some unit tests to confirm that `parseSPI()` still has toleration for both styles of secret string.

2024-09-06 12:45 UTC, qmonnet approved these changes
Looks good from my side. Nice clean-up!

2024-09-09 13:55 UTC, thorn3r approved these changes
LGTM for Clustermesh changes

2024-09-10 08:46 UTC, tklauser approved these changes

2024-10-10 07:06 UTC, julianwiedmann commented on .github/workflows/tests-clustermesh-upgrade.yaml
> +          SECRET="3+ rfc4106(gcm(aes)) $(openssl rand -hex 20) 128"
fyi, I switched this over in https://github.com/cilium/cilium/pull/35295.

2024-11-11 19:20 UTC, pchaigno commented on .github/workflows/conformance-ipsec-e2e.yaml
> +            --from-literal=keys="3+ ${key}"
> Can't we just phase out the `+` symbol instead (except in downgrade tests) ?

I'm trying to match what users will be running in production for the short and medium term. Given we're not asking to remove the `+`, I'd expect all of them to have it.

2024-11-11 19:21 UTC, pchaigno commented
/test

2024-11-12 09:34 UTC, pchaigno commented
/test

2024-11-12 10:11 UTC, pchaigno commented
/test

2024-11-12 11:05 UTC, pchaigno commented
/test

2024-11-12 15:10 UTC, rgo3 approved these changes

2024-11-12 16:41 UTC, borkmann approved these changes

2024-11-12 16:50 UTC, merged