helm: Don't set both tag and digest on image spec
cilium/cilium pull request #34891
Opened 2024-09-16 09:19 UTC by BenoitKnecht

Images specified with both a tag and a digest (e.g. `quay.io/cilium/cilium:v1.16.1@sha256:abc...`) are ambiguous, because it's not well defined what should happen if the tag and the digest don't point to the same image version. Different container engines may handle that case differently, or not handle it as all [1].

Therefore, this commit ensures that if `useDigest` is true, the generated image spec doesn't include a tag.

[1]: https://github.com/cri-o/cri-o/issues/8603

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

2024-09-16 10:11 UTC, gandro requested changes
Thank you for the PR! I think however we have to reject this proposal.

If tag and digest mismatch, there is clearly something wrong. So I think the [behavior of Docker/Moby](https://github.com/moby/moby/releases/tag/v20.10.20) is the one we want: The image pull is rejected, since there was a mistake somewhere (e.g. the tag was tampered with) and the image should not be deployed. It is unfortunate that CRIO no longer seems to support this.

Omitting the tag and just using the digest is also not a great UX. Currently, it's very easy to check what kind of image version is deployed by running a `kubectl describe` - and tools like Cilium CLI even show you the image that for that reason. Showing an opaque digest makes makes it so users have to run `cilium version` within the pod directly, or lookup the digest in a registry. 

Having said that, if it is currently not possible to _only_ provide a digest, I'm open to adding that option in our Helm charts, in particular if it improves CRIO compatiblity.

But I strongly feel that our current default of rendering both the tag and the digest brings the best of both worlds:

1. Clear indication to the user what image version they are running (thanks to the tag)
2. Clear indication to the user that the tag they are running has not been modified (thanks to the digest)

2024-09-16 10:36 UTC, gandro commented
> So I think the [behavior of Docker/Moby](https://github.com/moby/moby/releases/tag/v20.10.20) is the one we want

Turns out, I misread that bit. It only checks the image name, not the the tag. Which is not really what we want unfortunately

2024-09-16 11:33 UTC, BenoitKnecht commented
The problem is that currently, if you upgrade from CRI-O 1.30 to 1.31, images with both a tag and a digest are _rejected_ (container creation will fail with `Docker references with both a tag and digest are currently not supported`). It might get fixed with https://github.com/cri-o/cri-o/pull/8605, but given the ambiguity, there's no guarantee that container engines will all handle this case the same way, and in the worst case scenario you'll end up with containers that won't even start.

As you noted above, the intent was probably to get the image based on the tag, and then verify that it matches the digest, but that's not what happens; when the digest is specified, the tag is ignored.

I understand that the digest alone makes it hard to see at a glance which version is running, but if the tag is ignored, displaying it could be very misleading. If someone mistakenly uses the digest for 1.16.1, but specifies the `v1.15.8` tag, the UX would prominently show that version, when in reality `v1.16.1` is running.

2024-09-16 11:52 UTC, gandro commented
> I understand that the digest alone makes it hard to see at a glance which version is running, but if the tag is ignored, displaying it could be very misleading. If someone mistakenly uses the digest for 1.16.1, but specifies the v1.15.8 tag, the UX would prominently show that version, when in reality v1.16.1 is running.

I agree that it is suboptimal, but this requires some misconfiguration to occur. The default that we ship with our Helm charts is somewhat guaranteed to always match (since the tags and digests are updated automatically and not manually), so by default I think it's safe to assume that the `tag@digest` references we ship by default (which are also the ones used by a majority of users) are correct. In this default cases, I really think the better UX of having both trumps over compatibility with (hopefully) a single CRIO version that regressed to not parse it anymore.

However, as I've said, I'm also open to adding e.g. an `useTags: false` option make sure our Helm charts can be deployed only by digest if that is the user preference. I you'd like to submit such a change, I'd ACK it. By default however, I strongly feel we should keep the system as is.

For the problem at hand with CRIO v1.31, have you tried setting an emtpy `image.tag` or use `image.override` as workarounds?

2024-09-16 14:27 UTC, BenoitKnecht commented
> For the problem at hand with CRIO v1.31, have you tried setting an emtpy image.tag or use image.override as workarounds?

Setting an empty tag doesn't work, you get `quay.io/cilium/cilium:@sha256:abc...` in that case. But that's probably an easy fix, make the image spec valid when the tag is empty, and that would be an easier workaround than having to explicitly override every image (which is cumbersome to maintain whenever there's an update).

2024-09-16 14:56 UTC, gandro commented
I see, thanks for checking! Yeah I think we can either fix the empty tag case, or have a `useTags` flag similar to `useDigest` that will make sure tags are omitted

2024-09-17 13:47 UTC, BenoitKnecht commented
@gandro Is this more in line with what you had in mind?

My only issue with it is that you'd have to set an empty tag for each image, rather than having a convenient global flag that would express "my container engine doesn't support both a tag and a digest in image specs, so only use the digest everywhere;" but I don't think Helm supports global variables in templates, so I guess that's wouldn't be easy to do.

2024-09-17 14:05 UTC, gandro approved these changes
I think this is a good compromise!

2024-09-17 14:06 UTC, gandro commented
> My only issue with it is that you'd have to set an empty tag for each image, rather than having a convenient global flag that would express "my container engine doesn't support both a tag and a digest in image specs, so only use the digest everywhere;"

Yeah this is a bit unfortunate :(

2024-09-17 14:06 UTC, gandro commented
/test

2024-09-18 03:40 UTC, tommyp1ckles approved these changes

2024-09-18 08:22 UTC, merged