cilium-cli: Define CLI_MAIN_DIR Make variable
cilium/cilium pull request #34910
Opened 2024-09-16 22:06 UTC by michi-covalent

Define CLI_MAIN_DIR Make variable to make it easier to override.

2024-09-16 22:09 UTC, michi-covalent commented
/test

2024-09-17 07:16 UTC, aanm requested changes

2024-09-17 07:16 UTC, aanm commented on cilium-cli/Makefile
> +CLI_MAIN_DIR:=./cmd/cilium
shouldn't this be `CLI_MAIN_DIR?=./cmd/cilium` if we plan to override it while having a default?

2024-09-17 14:15 UTC, michi-covalent commented
/test

2024-09-19 16:19 UTC, michi-covalent commented
@aanm ping! 🙏

2024-09-20 09:15 UTC, aanm approved these changes

2024-09-20 14:51 UTC, aanm commented
@kkourt test

2024-09-20 14:55 UTC, kkourt approved these changes

2024-09-20 18:10 UTC, asauber approved these changes

2024-09-20 18:19 UTC, merged