ci: fix build-images-ci to not die in forks
cilium/cilium pull request #34948
Opened 2024-09-18 15:38 UTC by jsoref

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Forks will not necessarily have vars.GH_RUNNER_EXTRA_POWER. The best outcome is to not run a job when the var is not set.

Fixes: #34947

2024-09-18 16:20 UTC, joestringer commented
The change here seems fine, but I think it's worth noting that currently if someone wants to run the automated CI testing for Cilium, it's typically done on a PR towards this repository. Running the CI on forks is not something that the community has yet tried to support. I can see from https://github.com/check-spelling-sandbox/cilium/pull/1 that there are various workflows failing for different reasons. How far are you interested to take this, do you plan to make all the workflows pass or skip on a fork?

This might be a step towards supporting that development workflow, but it's also worth noting that many of the other workflows rely on the images that are built from this workflow, and they won't be able to pass if this step is skipped. Linters should be able to run without this workflow, but the smoke tests and end-to-end tests will time out if this step is skipped.

Also curious if you have been able to test out this change on your own fork to validate the fix?

2024-09-18 17:08 UTC, jsoref commented
It works, tested here: https://github.com/jsoref/cilium/actions/runs/10926879711/job/30331778002?pr=1

2024-09-18 17:09 UTC, jsoref commented
An alternate approach would be to have the workflow push to ghcr and have the workflows rely on ghcr instead.

2024-09-18 18:12 UTC, jsoref commented
To answer the question about how far: my goal is for nothing to give me a ❌. As long as the project is willing to work with me.

2024-09-26 10:20 UTC, aanm requested changes

2024-09-26 10:20 UTC, aanm commented on .github/workflows/build-images-ci.yaml
>      runs-on: ${{ vars.GH_RUNNER_EXTRA_POWER }}
```suggestion
    runs-on: ${{ vars.GH_RUNNER_EXTRA_POWER || 'ubuntu-latest' }}
```

2024-10-11 10:20 UTC, aanm commented
This issue has been fixed. Thank you.

2024-10-11 10:20 UTC, closed without merging