feat: cli to display ipcache by labels
cilium/cilium pull request #35275
Opened 2024-10-07 13:09 UTC by vasu-dasari

Added new CLI to display ipcache entries by cidr and labels.

Display IP Cache information
```
Usage:
cilium-dbg ip get ( <cidr> |-l <identity labels> ) [flags]

Flags: -h, --help help for get
-l, --labels strings list of labels
-o, --output string json| yaml| jsonpath='{}'
-v, --verbose Print all fields of ipcache
```
Fixes: #34632
Signed-off-by: Vasu Dasari <vasudasari@google.com>

```release-note
introducing a new CLI option to display ipcache information by labels or cidr
```

2024-10-07 13:13 UTC, vasu-dasari commented
CLI display from my testing:
Help text:
```
root@gke-vasudasari-cilium-1-default-pool-4a9bc11f-kzys:/home/cilium# cilium-dbg ip get -h
Display IP Cache information

Usage:
  cilium-dbg ip get ( <cidr> |-l <identity labels> ) [flags]

Flags:
  -h, --help             help for get
  -l, --labels strings   list of labels
  -o, --output string    json| yaml| jsonpath='{}'
  -v, --verbose          Print all fields of ipcache

Global Flags:
      --config string   Config file (default is $HOME/.cilium.yaml)
  -D, --debug           Enable debug messages
  -H, --host string     URI to server-side API
```
Query by CIDR:
```
root@gke-vasudasari-cilium-1-default-pool-4a9bc11f-kzys:/home/cilium# cilium-dbg ip get 10.168.0.12/32
IP               IDENTITY        SOURCE
10.168.0.12/32   reserved:host
```
```
root@gke-vasudasari-cilium-1-default-pool-4a9bc11f-kzys:/home/cilium# cilium-dbg ip get -l k8s:io.kubernetes.pod.namespace=default
===========================
Labels:
    k8s:io.kubernetes.pod.namespace=default
===========================
IP                HOST          IDENTITY   POD                           NAMESPACE
10.80.0.2/32      10.168.0.13   76103      rebel-base-55756c47d5-kzdsr   default
10.80.0.99/32     10.168.0.13   74181      x-wing-6bb767fcb8-757wc       default
10.80.3.4/32      10.168.0.12   74181      x-wing-6bb767fcb8-4jwsk       default
10.80.3.203/32    10.168.0.12   76103      rebel-base-55756c47d5-gjhm5   default
10.100.1.23/32    10.168.0.16   183733     rebel-base-55756c47d5-f4rv6   default
10.100.1.54/32    10.168.0.16   157998     x-wing-6bb767fcb8-2whv5       default
10.100.3.140/32   10.168.0.15   157998     x-wing-6bb767fcb8-947rj       default
10.100.3.206/32   10.168.0.15   183733     rebel-base-55756c47d5-sf8c5   default
```

2024-10-09 19:29 UTC, nathanjsweet commented
@vasu-dasari Please sign-off your first commit and remove the last empty commit. Thanks :slightly_smiling_face: !

2024-10-18 15:49 UTC, nathanjsweet approved these changes

2024-10-18 15:51 UTC, nathanjsweet commented
@vasu-dasari Pinging you on getting this merged. Please [sign-off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) your first commit and remove the empty last commit from your PR. Thanks! :slightly_smiling_face:

2024-10-22 08:00 UTC, doniacld commented on cilium-dbg/cmd/ip_get.go
> +	ipApi "github.com/cilium/cilium/api/v1/client/policy"
nit: can you remove the capital in the alias for `ipapi` (cf https://go.dev/blog/package-names)

2024-10-22 08:01 UTC, doniacld requested changes
One nit otherwise lgtm!

2024-10-30 14:35 UTC, derailed commented
@vasu-dasari Could you take another look when you get a chance? Thank you!

2024-11-03 22:01 UTC, vasu-dasari reviewed
Added `Signed-off-by` to my commit. And addressed comment from @doniacld

2024-11-03 22:01 UTC, vasu-dasari commented on cilium-dbg/cmd/ip_get.go
> +	ipApi "github.com/cilium/cilium/api/v1/client/policy"
Yes. Made the changes as suggested. Thanks for reviewing.

2024-11-04 10:32 UTC, aanm commented
/test

2024-11-04 15:44 UTC, doniacld approved these changes
LGTM! Thanks for the change

2024-11-05 10:50 UTC, jrajahalme approved these changes

2024-11-05 11:35 UTC, merged