cilium-dbg: Add "bpf ipcache delete/update"
cilium/cilium pull request #35454
Opened 2024-10-21 11:10 UTC by jschwinger233

https://github.com/cilium/cilium/pull/35231 will use two new ipcache cmd to temporarily delete ipcache entries for strict mode encryption test.

Suggested-by: Timo Beckers <timo@isovalent.com>

2024-10-21 11:30 UTC, jschwinger233 commented
/test

2024-10-22 03:48 UTC, jschwinger233 commented
/test

2024-10-22 09:57 UTC, YutaroHayakawa approved these changes

2024-10-22 09:59 UTC, squeed commented on cilium-dbg/cmd/bpf_ipcache_update.go
> +	Short: "Update an entry for an ip",
suggestion: in most cases, this should be called a prefix, not an IP, as the ipcache accepts arbitrary length prefixes.

2024-10-22 10:02 UTC, squeed commented on cilium-dbg/cmd/bpf_ipcache_update.go
> +		key := ipcache.NewKey(ipnet.IP, ipnet.Mask, 0)
Cluster-id should be a parameter as well, if we're going to allow arbitrary low-level access.

2024-10-22 10:03 UTC, squeed commented on cilium-dbg/cmd/bpf_ipcache_update.go
> +		}
Should reject ipv6 tunnel endpoints here.

2024-10-22 10:03 UTC, squeed commented on cilium-dbg/cmd/bpf_ipcache_delete.go
> +			Usagef(cmd, "No ip provided. "+usage)
nit: prefix, not ip

2024-10-22 10:04 UTC, squeed commented on cilium-dbg/cmd/bpf_ipcache_delete.go
> +		ip := net.ParseIP(arg)
`ParsePrefix()`, not `ParseIP()`

2024-10-22 10:05 UTC, squeed requested changes
Basic idea is fine, just some cleanups.

Do we need to add any warnings that this is a very low-level tool? Or is it sufficiently hidden that nobody will find it (and break their cluster)?

2024-10-23 08:21 UTC, jschwinger233 commented
/test

2024-10-23 12:57 UTC, squeed approved these changes

2024-10-23 13:07 UTC, merged