renovate: Fix image updates for IPsec workflows
cilium/cilium pull request #35555
Opened 2024-10-25 18:04 UTC by pchaigno

The matrix configs for the two IPsec workflows were moved from the workflow themselves to a dedicated file in commit 06cfdb4b107b ("workflows: Generate IPsec matrix from config file").

We thus need to update the Renovate configuration such that it will know to look in the new, dedicated file with the configs and kernel versions.

Fixes: https://github.com/cilium/cilium/pull/35323.

2024-10-25 18:08 UTC, pchaigno commented
/test

2024-10-29 10:46 UTC, tklauser requested changes
The change likely also needs to adjust the `fileMatch` stanza [here](https://github.com/cilium/cilium/blob/d8f1fae086e86ecc6debb872bf6bc0f78d25652f/.github/renovate.json5#L793-L798) for the file to be matched by the regex manager.

2024-10-29 11:13 UTC, pchaigno commented
Thanks!

> The change likely also needs to adjust the `fileMatch` stanza [here](https://github.com/cilium/cilium/blob/d8f1fae086e86ecc6debb872bf6bc0f78d25652f/.github/renovate.json5#L793-L798) for the file to be matched by the regex manager.

Do you mean [this one](https://github.com/cilium/cilium/blob/d8f1fae086e86ecc6debb872bf6bc0f78d25652f/.github/renovate.json5#L719)? The one you pointed to already didn't match the IPsec workflows.

2024-10-29 12:14 UTC, tklauser commented
> Thanks!
> 
> > The change likely also needs to adjust the `fileMatch` stanza [here](https://github.com/cilium/cilium/blob/d8f1fae086e86ecc6debb872bf6bc0f78d25652f/.github/renovate.json5#L793-L798) for the file to be matched by the regex manager.
> 
> Do you mean [this one](https://github.com/cilium/cilium/blob/d8f1fae086e86ecc6debb872bf6bc0f78d25652f/.github/renovate.json5#L719)? The one you pointed to already didn't match the IPsec workflows.

Ah yes, that's the one I meant to link.

2024-10-29 12:41 UTC, pchaigno commented
/test

2024-10-29 12:50 UTC, tklauser approved these changes

2024-10-29 12:52 UTC, tklauser commented on .github/renovate.json5
>          "^\\.github/actions/ginkgo/[^/]+\\.ya?ml$"
Missing comma at EOL here.

2024-10-29 12:53 UTC, pchaigno commented on .github/renovate.json5
>          "^\\.github/actions/ginkgo/[^/]+\\.ya?ml$"
:facepalm:

2024-10-29 12:54 UTC, pchaigno commented on .github/renovate.json5
>          "^\\.github/actions/ginkgo/[^/]+\\.ya?ml$"
Fixed. Thanks!

2024-11-04 09:18 UTC, brlbil approved these changes

2024-11-04 09:27 UTC, merged