helm: Add certgen.generateCA value
cilium/cilium pull request #35602
Opened 2024-10-29 08:17 UTC by sderoe

Allow creation of secrets without CA creation.

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

2024-10-29 09:12 UTC, giorio94 requested changes
Thanks! The patch looks good to me. Could you please also extend it to the Hubble certificates generation (see comment inline)?

2024-10-29 09:12 UTC, giorio94 commented on install/kubernetes/cilium/templates/clustermesh-apiserver/tls-cronjob/_job-spec.tpl
> +            - "--ca-generate={{ .Values.certgen.generateCA }}"
The same change shall be applied to `install/kubernetes/cilium/templates/hubble/tls-cronjob/_job-spec.tpl` as well.

2024-10-29 11:12 UTC, sderoe commented
@giorio94 Thank you. I have updated the hubble template as well

2024-10-29 11:26 UTC, giorio94 approved these changes
Thanks!

2024-10-29 13:12 UTC, gandro approved these changes

2024-10-29 13:13 UTC, gandro commented
Not sure why the Helm smoke test is failing. I don't see any error message. Could you run `make -C install/kubernetes` locally and commit any differences if there are any?

2024-10-30 00:39 UTC, sderoe commented
@gandro There was a diff so I have committed it. Helm check is waiting to run

2024-10-30 09:11 UTC, gandro commented
Seems like there are still some issues. Checkpatch says that the Sign-Off line is inconsistent:

> Error: ERROR:NO_AUTHOR_SIGN_OFF: Missing Signed-off-by: line by nominal patch author 'john-r-swyftx <john.roche@swyftx.com.au>'

And it seems the documentation needs some regeneration as well:

> HINT: to fix this, run 'make -C Documentation update-helm-values'

2024-10-30 09:11 UTC, sderoe commented
Just ran `make -C Documentation update-helm-values` as well

2024-10-30 09:14 UTC, sderoe commented
Updated the email as well. Didn't realise it was tested v account email

2024-10-30 09:41 UTC, gandro commented
/test

2024-10-30 12:11 UTC, merged