bpf: tests: de-dup IPv4 header validation
cilium/cilium pull request #35688
Opened 2024-11-01 08:35 UTC by julianwiedmann

Clean up a lot of boilerplate code. Consistently validate the header checksum against the actual header content, replacing the current approach of comparing it against a stored golden value.

2024-11-01 08:36 UTC, julianwiedmann commented
(I'd want to add similar helpers for other header types, but let's start small)

2024-11-01 10:13 UTC, julianwiedmann commented
/test

2024-11-06 19:06 UTC, gentoo-root requested changes

2024-11-06 19:06 UTC, gentoo-root commented on bpf/tests/skip_tunnel_nodeport_masq.c
> +		assert(!pktcheck__validate_ipv4(l3, IPPROTO_TCP,
IMO, the new assertions are far less informative than the old error messages that tell exactly what field is wrong and what is the likely reason. Passing multiple unlabeled parameters is also more prone to errors.

Replacing hardcoded checksums is a good idea (we are not testing csum_diff itself here), but I'm not in favor of putting more checks into the same function.

2024-11-06 19:06 UTC, gentoo-root commented on bpf/tests/pktcheck.h
> +	/* Skip csum validation if options are present */
Do we have tests with IP options? If yes, I'd rather support additional packet lengths, than have the checksum value untested in those cases. If not, I'd rather return a failure if the IP header length is unexpected, so that we don't miss the checksum validation when we start using/testing options.

2024-11-07 15:01 UTC, julianwiedmann commented on bpf/tests/skip_tunnel_nodeport_masq.c
> +		assert(!pktcheck__validate_ipv4(l3, IPPROTO_TCP,
>IMO, the new assertions are far less informative than the old error messages that tell exactly what field is wrong and what is the likely reason. 

yeah I would have loved to preserve the textual output, but that didn't seem possible in the current framework. But would be a nice add-on. For debugging, it's easy enough to quickly copy&paste the different checks into the broken test, and add output as needed.

>Replacing hardcoded checksums is a good idea (we are not testing csum_diff itself here), but I'm not in favor of putting more checks into the same function.

Hmm not sure I understand what the "more checks into the same function" refers to.

2024-11-07 15:04 UTC, julianwiedmann commented on bpf/tests/pktcheck.h
> +	/* Skip csum validation if options are present */
There's some tests with IP options, I didn't touch them (so they just use the hard-coded csum check).

We can easily explore adding support for IP options later on, but I wouldn't want to block on that. So I'll go with your suggestion of returning an error for now :+1:.

2024-11-29 15:44 UTC, gentoo-root commented on bpf/tests/skip_tunnel_nodeport_masq.c
> +		assert(!pktcheck__validate_ipv4(l3, IPPROTO_TCP,
> yeah I would have loved to preserve the textual output, but that didn't seem possible in the current framework.

Could you elaborate? I thought these messages from `test_fatal(...)` were printed. Has it changed?

> Hmm not sure I understand what the "more checks into the same function" refers to.

I mean the `pktcheck__validate_ipv4` function, which now contains checks for protocol, saddr, daddr and checksum, reducing code repetition, but also sacrificing the error messages.

2024-11-29 15:44 UTC, gentoo-root commented on bpf/tests/pktcheck.h
> +	/* Skip csum validation if options are present */
>I'll go with your suggestion of returning an error for now

ACK.

2024-12-04 11:50 UTC, viktor-kurchenko commented on bpf/tests/skip_tunnel_nodeport_masq.c
> +		assert(!pktcheck__validate_ipv4(l3, IPPROTO_TCP,
Can we use `test_fatal` function inside of `pktcheck__validate_ipv4` with generic messages?
E.g.:
```
test_fatal("src addr was changed [expected: %s, actual: %s]", saddr, ip4->saddr);
```

2024-12-04 11:54 UTC, gentoo-root commented on bpf/tests/skip_tunnel_nodeport_masq.c
> +		assert(!pktcheck__validate_ipv4(l3, IPPROTO_TCP,
That's an option too. If it includes the expected and actual values, it would be even more informative than, e.g., "src IP changed", but in some cases still less informative the old messages (like "src IP was not SNAT'ed").

2024-12-04 15:22 UTC, viktor-kurchenko commented on bpf/tests/skip_tunnel_nodeport_masq.c
> +		assert(!pktcheck__validate_ipv4(l3, IPPROTO_TCP,
Yeah, but that's the price for code reduction ))
Otherwise, a new function might have too many input arguments.

2025-03-17 02:05 UTC, closed without merging