policy/api: don't write zero enableDefaultDeny field
cilium/cilium pull request #35804
Opened 2024-11-06 10:46 UTC by squeed

Before this change, marshalling policy to a struct caused the line `... "enableDefaultDeny":{}, ...` to be written to json-marshalled network policy. This later caused problems when using cilium-cli with cluster versions that do not support the `enableDefaultDeny` field.

This can be replaced with a `omitzero` modifier on the json struct tag once go1.24 is released. Until then, we can work around this with a simple pointer instead.

2024-11-06 11:01 UTC, squeed commented
/test

2024-11-06 14:53 UTC, michi-covalent approved these changes

2024-11-11 08:11 UTC, aanm commented
/test

2024-11-11 15:37 UTC, squeed commented
/test

2024-11-13 19:59 UTC, learnitall approved these changes

2024-11-13 20:59 UTC, squeed commented
/test

2024-11-19 16:23 UTC, tklauser requested changes
The failing https://github.com/cilium/cilium/actions/runs/11825695933/job/33196483218#step:18:960 f02-agent-fqdn e2e test seems to be legitimate, it's persistent across re-runs.

I think we need to additionally protect access to the `EnableDefaultDeny` field with `r.EnableDefaultDeny != nil` checks now that it is a (potentially `nil`) pointer.

2024-11-20 15:14 UTC, squeed commented
EnableDefaultDeny isn't a pointer, so it can't be nil. That's what got us in to this mess in the first place :-/.

The CI failure is actually #35985, I just need to rebase.

2024-11-20 15:15 UTC, squeed commented
/test

2024-11-20 15:54 UTC, squeed commented
> Now I´m confused. Isn't this the other way around that it wasn't a pointer before and couldn't be nil and was thus always written?

Right, this doesn't change the policy type, just the stub type we use for JSON marshalling. We never actually dereference the pointer.

2024-11-20 15:56 UTC, tklauser commented
> > Now I´m confused. Isn't this the other way around that it wasn't a pointer before and couldn't be nil and was thus always written?
> 
> Right, this doesn't change the policy type, just the stub type we use for JSON marshalling. We never actually dereference the pointer.

Ah, stub type was what confused me. Thanks for clarifying.

2024-11-20 15:57 UTC, tklauser approved these changes

2024-11-20 17:33 UTC, merged