fix typo: subomains -> subdomains
cilium/cilium pull request #35875
Opened 2024-11-09 10:58 UTC by AaronDewes

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

This fixes a typo in a comment.

Fixes: #issue-number

```release-note

```

2024-11-10 12:52 UTC, xmulligan commented
Thanks for the fixes, can you squash your commits and add sign off to it?

2024-11-14 13:48 UTC, doniacld approved these changes

2024-11-25 16:40 UTC, derailed commented
@AaronDewes Thank you for these updates! It looks like this PR needs a bit more TLC. Could you take another look?

2024-11-25 16:53 UTC, AaronDewes commented
Sorry, I missed the previous comments. I'll get back to this pr in about 30 mins.

2024-11-26 20:57 UTC, learnitall requested changes
Can you please remove the changes which were made in the vendor directory for the `go-toml` package? Those changes would need to be made in `go-toml`'s repository, we can't change them here.

2025-01-17 01:56 UTC, closed without merging