Adjustment of Variable Naming to Remove Hyphens (node1_IP, node2_IP and node3_IP)
cilium/cilium pull request #35923
Opened 2024-11-12 14:06 UTC by yilas

In bash, hyphens are not permitted in variable names, as they can cause syntax errors. To avoid this issue, variable names have been updated to use underscores (_) instead of hyphens. This change ensures compatibility with bash syntax and avoids potential errors during script execution.

Please ensure your pull request adheres to the following guidelines:

- [X] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [X] All code is covered by unit and/or runtime tests where feasible.
- [X] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [X] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [X] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [X] Thanks for contributing!

Fixes: #35922

2024-11-12 15:25 UTC, qmonnet requested changes
Thanks! Please fix the missing bracket (see below). You also have a typo in your commit log (`corrects` -> `correct`).

2024-11-12 15:25 UTC, qmonnet commented on Documentation/installation/k0s.rst
> +   k0sctl init --k0s -n "myk0scluster" -u "k0s" -i "~/.ssh/id_rsa" -C "1" "$ node1_IP}" "${node2_IP}" "${node3_IP}" > k0s-myk0scluster-config.yaml
```suggestion
   k0sctl init --k0s -n "myk0scluster" -u "k0s" -i "~/.ssh/id_rsa" -C "1" "${node1_IP}" "${node2_IP}" "${node3_IP}" > k0s-myk0scluster-config.yaml
```

2024-11-12 15:35 UTC, yilas reviewed
Env var node1_IP, node2_IP and node3_IP were not correct

2024-11-12 15:54 UTC, qmonnet commented
Thank you! Can you please squash the two commits together and force-push?

2024-11-12 18:02 UTC, yilas commented
> Thank you! Can you please squash the two commits together and force-push?

Thank you ! Commits have been squashed and force-pushed as requested.

2024-11-12 18:06 UTC, qmonnet commented
Thanks, change looks good. Can I just ask again to change your commit title? You're not removing _underscore_ (you're adding them! :slightly_smiling_face:) but dashes. Can you also please make the commit title fit under 80 characters? The checkpatch CI job will complain otherwise.

2024-11-12 18:16 UTC, yilas commented
Oops, sorry... Where was my head ? I just made the change...

2024-11-13 10:59 UTC, qmonnet approved these changes
Thanks a lot!

2024-11-13 10:59 UTC, qmonnet commented
/test

2024-11-13 11:16 UTC, merged