DOC: Update cilium contributing docs:
cilium/cilium pull request #3611
Opened 2018-04-10 15:03 UTC by eloycoto

- Added documentation for JustAfterEach, AfterFailed and example flow of
execution.
- Extend documentation related to sshConfig
- Added documenation how to run ginkgo using delve.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

2018-04-10 16:29 UTC, ianvernon requested changes

2018-04-10 16:29 UTC, ianvernon commented on Documentation/contributing.rst
> +some assertions, for a group of test, after the test finished without
to perform some assertions for a group of tests.

2018-04-10 16:29 UTC, ianvernon commented on Documentation/contributing.rst
> +duplicating some the code. For example, for each test a new a dead lock check
A good example of using a global ``JustAfterEach`` function is for deadlock detection, which checks the Cilium logs for deadlocks that may have occurred in the duration of the tests.

2018-04-10 16:29 UTC, ianvernon commented on Documentation/contributing.rst
> +This method will run before all ``AfterEach`` and after ``JustAfterEach`` this
and after ``JustAfterEach``. This function is...

2018-04-10 16:29 UTC, ianvernon commented on Documentation/contributing.rst
> +function is only called when the test failed. The main reason of this code is to
This construct is used to gather logs, the status of Cilium, etc, which provide data for analysis when tests fail.

2018-04-10 16:29 UTC, ianvernon commented on Documentation/contributing.rst
> +Global execution
Global execution is a bit vague. Maybe something like `Example Test Layout`? I'm open to suggestions here.

2018-04-10 16:29 UTC, ianvernon commented on Documentation/contributing.rst
> +Here is an example of the complete test case flow and when these methods will run:
Here is an example layout of how a test may be written with the aforementioned constructs:

2018-04-10 16:29 UTC, ianvernon commented on Documentation/contributing.rst
> +	BeforeAll(A)
Indent things below `Describe` to show they are contained within the `Describe`.

2018-04-10 16:29 UTC, ianvernon commented on Documentation/contributing.rst
> +	TEST1
For consistency, call these `TESTA1`, `TESTA2`, etc.

2018-04-10 16:29 UTC, ianvernon commented on Documentation/contributing.rst
> +Running test on other vms
Running Tests in Other VMs

2018-04-10 16:29 UTC, ianvernon commented on Documentation/contributing.rst
> +If you want to run test in a different VM, you can use ``--cilium.SSHConfig``
... use the ...

2018-04-10 16:29 UTC, ianvernon commented on Documentation/contributing.rst
> +option to connect over ssh to another server. Cilium source code should be
to provide the SSH configuration of the endpoint on which tests will be ran.

2018-04-10 16:29 UTC, ianvernon commented on Documentation/contributing.rst
> +option to connect over ssh to another server. Cilium source code should be
The tests presume the following on the remote instance: 
* Cilium source code is located in the directory ``/home/vagrant/go/src/github.com/cilium/cilium/``.
* Cilium is installed and running.

2018-04-10 16:29 UTC, ianvernon commented on Documentation/contributing.rst
> +- k8s{1..2}-${K8S_VERSION}: to run Kubernetes test. It needs a Kubernetes installation
Kubernetes tests. These instances must have Kubernetes installed and running as a prerequisite for running tests.

2018-04-10 16:29 UTC, ianvernon commented on Documentation/contributing.rst
> +- runtime: To run runtime test.
test --> tests

2018-04-11 17:52 UTC, ianvernon requested changes

2018-04-11 17:52 UTC, ianvernon commented on Documentation/contributing.rst
> +The ssh connection need to be defined as a ``ssh-config`` file and need to have
need --> needs

2018-04-11 17:52 UTC, ianvernon commented on Documentation/contributing.rst
> +- k8s{1..2}-${K8S_VERSION}: to run Kubernetes tests. Kubernetes tests. These
> to run Kubernetes tests. Kubernetes tests.

remove " Kubernetes tests" . Please be more careful with proofreading your changes.

2018-04-11 17:52 UTC, ianvernon commented on Documentation/contributing.rst
> +        BeforeAll(A)
Indentation doesn't look consistent with things under `Describe` vs. those in `Context` on GitHub.

2018-04-11 17:52 UTC, ianvernon commented on Documentation/contributing.rst
> +    BeforeAll
Indent things under `Describe`.

2018-04-12 06:54 UTC, eloycoto commented
test-me-please

2018-04-13 16:51 UTC, ianvernon approved these changes

2018-04-13 16:52 UTC, merged