examples/k8s: change image to point to 1.0
cilium/cilium pull request #3613
Opened 2018-04-10 17:08 UTC by aanm

Signed-off-by: André Martins <andre@cilium.io>

This will point the 1.0 branch to the 1.0 docker image

2018-04-10 17:10 UTC, aanm commented
test-me-please

2018-04-10 20:05 UTC, tgraf requested changes

2018-04-10 20:05 UTC, tgraf commented on examples/kubernetes/1.10/cilium-ds.yaml
> +      - image: cilium/cilium:1.0
Shouldn't this be `v1.0`?

2018-04-10 20:14 UTC, aanm commented on examples/kubernetes/1.10/cilium-ds.yaml
> +      - image: cilium/cilium:1.0
you're right, fixed!

2018-04-10 20:14 UTC, aanm commented
test-me-please

2018-04-11 00:09 UTC, aanm commented
test-me-please

2018-04-11 00:14 UTC, aanm commented
test-missed-k8s

2018-04-11 09:03 UTC, aanm commented
test-me-please

2018-04-11 09:03 UTC, aanm commented
test-missed-k8s

2018-04-11 22:56 UTC, tgraf approved these changes

2018-04-11 22:56 UTC, merged