feat: Standalone dns proxy - Cilium agent grpc server
cilium/cilium pull request #36213
Opened 2024-11-27 18:27 UTC by vipul-21

Note: This PR is includes changes from this PR: https://github.com/cilium/cilium/pull/36121
The PR adds the cilium agent grpc server to send the policy rules to SDP.
- The grpc server starts running on a default port if `l7proxy` and `enable-standalone-dns-proxy` is true
- Cilium agent sends the data to SDP(standalone dns proxy) during endpoint regeneration specifically after the policy cache is updated. There is lock mechanism in the `policyCache` as well as the `FqdnDataServer` to make sure that the updates are a snapshot of the current policy state.(and in serialized manner)
- `SubscribeToDNSPolicies` is called by the client(SDP) on start and cilium agent sents it the current policy rules it has. Otherwise, it stores the stream and write the rules on the same stream for the client to receive.
- `UpdatesMappings` is used by the client to send the data(DNS Response mappings) to cilium agent.
 
Fixes: https://github.com/cilium/cilium/issues/30984
CFP: https://github.com/cilium/design-cfps/pull/54
```

2024-11-28 08:11 UTC, tklauser commented
Including David in reviewers per [his request](https://github.com/cilium/design-cfps/pull/54#pullrequestreview-2453715689).

2024-12-17 10:47 UTC, tklauser commented
The specifics of the design are still being discussed in https://github.com/cilium/design-cfps/pull/54. I'm marking this PR as draft, so it doesn't show up in reviewer's queues. Please feel free to mark as ready for review once the discussion on the CfP has converged and the PR updated accordingly.

2025-01-22 09:37 UTC, vipul-21 commented
Commenting to make sure the PR is not closed.

2025-03-03 13:28 UTC, marseel commented on daemon/cmd/daemon_main.go
> +	flags.Bool(option.EnableEmbeddedDNSProxy, true, "Enables embedded DNS proxy.")
What would be the use-case for this flag? 
The reason why I am asking is that I don't see helm specific option to use it, but I also wonder from user-point of view if it will be ever used?

2025-03-03 20:31 UTC, vipul-21 commented on daemon/cmd/daemon_main.go
> +	flags.Bool(option.EnableEmbeddedDNSProxy, true, "Enables embedded DNS proxy.")
Inbuilt(embedded) dns proxy and standalone dns proxy can running together, listening on the same port using the Linux `SO_REUSEPORT`. Since the load balancing of the dns request is controlled via linux kernel, we won't know if standalone dns proxy is serving the dns requests or not. This flag is used to make sure that the embedded dns proxy is disabled and all the dns requests can be served by standalone dns proxy. This way we can test that standalone dns proxy works as intended with cilium agent. (Also to benchmark performance of standalone dns proxy with embedded dns proxy)

I added the helm value for it already: https://github.com/cilium/cilium/pull/37836/files#diff-b9a59a825d08e17ba73f27f4d3eb3d0b5852c44ed80705c3003d51617237d1a6R1055

2025-03-04 10:28 UTC, marseel commented on daemon/cmd/daemon_main.go
> +	flags.Bool(option.EnableEmbeddedDNSProxy, true, "Enables embedded DNS proxy.")
> This flag is used to make sure that the embedded dns proxy is disabled and all the dns requests can be served by standalone dns proxy. This way we can test that standalone dns proxy works as intended with cilium agent. 

If it's just for testing, I would probably not have helm value and also mark this flag as hidden as we don't expect users to ever use it, right?

2025-03-05 15:56 UTC, vipul-21 commented on daemon/cmd/daemon_main.go
> +	flags.Bool(option.EnableEmbeddedDNSProxy, true, "Enables embedded DNS proxy.")
Yes, as of now I don't expect users to use it. I added the helm value so that it can be easily used in the CI to test the standalone dns proxy. If we mark this hidden, we will need to deploy a cilium config map with this value right OR there is others way we can pass the hidden value ? Does CI currently creates config map specific to features ?

2025-03-05 16:00 UTC, marseel commented on daemon/cmd/daemon_main.go
> +	flags.Bool(option.EnableEmbeddedDNSProxy, true, "Enables embedded DNS proxy.")
You can do that like this: https://github.com/cilium/cilium/blob/e8ee0f077067d44cdf15a3a7d7d4a22235b7d2eb/.github/workflows/scale-test-egw.yaml#L174
`enable-stale-cilium-endpoint-cleanup` is hidden option https://github.com/cilium/cilium/blob/b2b20b084acf57b4bfe427f3ba2531401c4fbc96/pkg/endpointcleanup/cell.go#L33

2025-03-19 18:39 UTC, vipul-21 commented on daemon/cmd/daemon_main.go
> +	flags.Bool(option.EnableEmbeddedDNSProxy, true, "Enables embedded DNS proxy.")
@marseel  Thank you for the review. Updated it.
I have updated the full PR as well(as that was the one which was getting the review). Here is the relevant commit w.r.t this PR: https://github.com/cilium/cilium/pull/37836/commits/baaef362c312f85718b977243f6f125d3d864701. Let me know if this looks good to you.

2025-03-20 09:42 UTC, marseel approved these changes
Thanks, my codeowners look good.

2025-03-20 20:28 UTC, tklauser commented on daemon/cmd/daemon_main.go
> +	flags.Int(option.ToFqdnsServerPort, 40045, "Global port on which the grpc server for standalone dns proxy should listen. Default is 40045.")
nit: no need to mention the default, this will be automatically added to the generated usage based on the second argument. Also, let's properly capitalize abbreviations while at it:

```suggestion
	flags.Int(option.ToFqdnsServerPort, 40045, "Global port on which the gRPC server for standalone DNS proxy should listen")
```

2025-03-20 23:00 UTC, vipul-21 commented on daemon/cmd/daemon_main.go
> +	flags.Int(option.ToFqdnsServerPort, 40045, "Global port on which the grpc server for standalone dns proxy should listen. Default is 40045.")
Updated it !

2025-03-20 23:01 UTC, vipul-21 commented
/test

2025-03-21 12:52 UTC, vipul-21 commented
/test

2025-03-21 14:30 UTC, vipul-21 commented
/test

2025-03-21 15:18 UTC, vipul-21 commented
/test

2025-03-21 20:10 UTC, vipul-21 commented
/test

2025-03-24 10:21 UTC, bimmlerd requested changes
I've spent some more time reviewing, but I haven't had time to read everything in detail. Let's get the things I've questioned fixed and then I'll take another look.

2025-03-24 10:21 UTC, bimmlerd commented on pkg/option/config.go
> +	ToFqdnsServerPort int
nit: consistent capitalisation with above please - `ToFQDNsServerPort`

2025-03-24 10:21 UTC, bimmlerd commented on pkg/fqdn/service/service.go
> +func (s *FQDNDataServer) StreamPolicyState(stream standalonednsproxy.FQDNData_StreamPolicyStateServer) error {
Is the expectation here that there's zero or one SDPs connecting to the agent or can there be multiple?

2025-03-24 10:21 UTC, bimmlerd commented on pkg/fqdn/service/service.go
> +func (s *FQDNDataServer) ReceiveDNSpolicesACK(stream standalonednsproxy.FQDNData_StreamPolicyStateServer) error {
nit: can be private? Also, maybe `receiveDNSPolicyACKs`?

2025-03-24 10:21 UTC, bimmlerd commented on pkg/fqdn/service/service.go
> +		case <-s.ctx.Done():
Is this necessary? Wouldn't it make sense to have stopping the server cancel all stream contexts, and relying on that mechanism instead of checking for the server context everywhere?

2025-03-24 10:21 UTC, bimmlerd commented on pkg/fqdn/service/service.go
> +	log  = logging.DefaultLogger.WithField(logfields.LogSubsys, "fqdn/server")
As I believe I've pointed out elsewhere- there's a big push to remove logrus happing at the moment, so please use `slog`.

2025-03-24 10:21 UTC, bimmlerd commented on pkg/fqdn/service/service.go
> +		default:
nit: can end the switch statement here and have the code be less indented.

2025-03-24 10:21 UTC, bimmlerd commented on pkg/fqdn/service/service.go
> +	streams lock.Map[standalonednsproxy.FQDNData_StreamPolicyStateServer, context.CancelFunc]
Keeping this state server-scoped seems unnecessary - the cancel function (like the server) is request-scoped, so we can just pass it to child functions of the request handler?

2025-03-24 10:21 UTC, bimmlerd commented on pkg/fqdn/service/service.go
> +	go func() {
If we pass around the cancel func instead of storing it on the server, we can avoid this. If you don't want to change that, I think this doesn't have to be a goroutine - it can just be a `defer` since the handler has the same lifecycle as the stream anyway.

2025-03-24 10:21 UTC, bimmlerd commented on pkg/fqdn/service/service.go
> +		byteIps = append(byteIps, []byte(ip.String()))
I'm confused by this. Why are we converting IPs (which are inherently a byte slice) to string to then convert that string to bytes?

2025-03-24 10:21 UTC, bimmlerd commented on pkg/fqdn/service/service.go
> +	standalonednsproxy "github.com/cilium/cilium/api/v1/standalone-dns-proxy"
nit: I think `pb` is a commonly used import alias for protobuf definitions.

I'm suprised that the Go imports linter lets this ordering through, I thought this should be part of the general `cilium/cilium` block.

2025-03-24 10:21 UTC, bimmlerd commented on pkg/fqdn/service/service.go
> +	closer := func() {
what's the point of this being a function pointer? The underlying grpc server is server-scoped - that's one of the bits of state I'd have expected in the server struct.

2025-03-24 10:21 UTC, bimmlerd commented on pkg/fqdn/service/service.go
> +	if err := grpcServer.Serve(lis); err != nil {
Isn't `Serve` blocking? As in, if it returns the server is already dead and it hence makes no sense to setup the `closer` func synchronously after?

2025-03-24 23:06 UTC, vipul-21 commented on pkg/fqdn/service/service.go
> +func (s *FQDNDataServer) StreamPolicyState(stream standalonednsproxy.FQDNData_StreamPolicyStateServer) error {
There can be multiple.
In case of SDP restart, there can be brief moment where the old SDP is shutting down and new is coming up. At that moment, there can be two SDP connected to cilium agent.

2025-03-24 23:11 UTC, vipul-21 commented on pkg/fqdn/service/service.go
> +		case <-s.ctx.Done():
Yeah make sense. Just kept in at one place that handles the closing of the server and cleaning the streams.

2025-03-24 23:12 UTC, vipul-21 commented on pkg/fqdn/service/service.go
> +	log  = logging.DefaultLogger.WithField(logfields.LogSubsys, "fqdn/server")
Updated to use `slog`

2025-03-24 23:15 UTC, vipul-21 commented on pkg/fqdn/service/service.go
> +	streams lock.Map[standalonednsproxy.FQDNData_StreamPolicyStateServer, context.CancelFunc]
If we don't keep the state, then we have to pass it to every request handler. For closing the server, we need to cancel each stream. I would want to keep the state as it if that;s okay ?

2025-03-24 23:15 UTC, vipul-21 commented on pkg/fqdn/service/service.go
> +	go func() {
Agreed. Also since we removed the context listening of the server I removed the listener from the bottom as well as it was redundant.

2025-03-24 23:15 UTC, vipul-21 commented on pkg/fqdn/service/service.go
> +		byteIps = append(byteIps, []byte(ip.String()))
Okay wasn't aware of that. I changed it so it does not convert it to string as IPs are stored as byte slice.

2025-03-24 23:16 UTC, vipul-21 commented on pkg/fqdn/service/service.go
> +	standalonednsproxy "github.com/cilium/cilium/api/v1/standalone-dns-proxy"
Updated it it to use `pb`

2025-03-24 23:16 UTC, vipul-21 commented on pkg/fqdn/service/service.go
> +	closer := func() {
The idea behind storing the function pointer is provide a way to shut down server from other parts of the code.

2025-03-24 23:17 UTC, vipul-21 commented on pkg/fqdn/service/service.go
> +	if err := grpcServer.Serve(lis); err != nil {
Yup changed it. The `closer` is setup to stop the server from outside.(if needed)

2025-03-24 23:19 UTC, vipul-21 commented on pkg/fqdn/service/service.go
> +		default:
Updated it.

2025-03-24 23:39 UTC, vipul-21 commented
/test

2025-03-26 15:56 UTC, vipul-21 commented
@bimmlerd Thanks for the review! I addressed your comments.
Friendly ping for re-review. Thanks!

2025-03-31 22:28 UTC, vipul-21 commented
@bimmlerd Friend ping for re-review ! Thanks !

2025-04-01 23:24 UTC, vipul-21 commented
Converting this to draft until we merge the basic grpc server PR: https://github.com/cilium/cilium/pull/38669
cc: @gandro  @bimmlerd

2025-05-16 02:09 UTC, closed without merging