bgp: remove metallb-bgp documentation
cilium/cilium pull request #36306
Opened 2024-12-02 18:38 UTC by harsimran-pabla

Removing metallb-bgp integration documentation as well as adding notes to upgrade to 1.17 document with references to removal of metallb-bgp.

Related to: https://github.com/cilium/cilium/pull/36191

2024-12-02 20:56 UTC, harsimran-pabla commented
/test

2024-12-03 00:00 UTC, joestringer approved these changes
:tada:

2024-12-03 07:42 UTC, rastislavs approved these changes

2024-12-03 19:01 UTC, learnitall requested changes
Couple of small typos and grammar suggestions, but LGTM! Thank you!

2024-12-03 19:01 UTC, learnitall commented on Documentation/operations/upgrade.rst
> +  control plane for BGP advertisements.
```suggestion
* The deprecated ``metallb-bgp`` flags ``bgp-config-path``, ``bgp-announce-lb-ip``
  and ``bgp-announce-pod-cidr`` have been removed. Users are now required to use Cilium BGP
  control plane for BGP advertisements.
```

2024-12-03 19:01 UTC, learnitall commented on Documentation/operations/upgrade.rst
> +  ``bgp.announce.loadbalancerIP`` has been removed. Users are required to use Cilium BGP
```suggestion
  ``bgp.announce.loadbalancerIP`` have been removed. Users are now required to use Cilium BGP
```

2024-12-04 15:39 UTC, harsimran-pabla commented
Thanks @learnitall, PR updated with requested changes.

2024-12-04 17:04 UTC, learnitall approved these changes
Thank you! :rocket:

2024-12-04 20:43 UTC, joestringer commented
/test

2024-12-04 20:52 UTC, merged