bandwidth: support ingress QoS using eBPF token bucket
cilium/cilium pull request #36351
Opened 2024-12-04 07:56 UTC by l1b0k

This commit adds ingress bandwidth rate limiting support using an eBPF token bucket implementation. This complements the existing egress bandwidth management and allows for bidirectional traffic shaping of Cilium endpoints. The QoS works on native device, same as EDT does, so traffic in the same node, will not work.

Key changes:
- Implements a token bucket rate limiter in eBPF (bpf/lib/tb.h)
- Adds a new BPF map (cilium_ingress_throttle) to store per-endpoint rate limits
- Extends the bandwidth manager to handle ingress bandwidth annotations
- Updates the CLI to display both ingress and egress bandwidth limits

Limitations:
- For native routing, BPF Routing is required

Fixes: #15636

```release-note
bandwidth: support ingress QoS using eBPF token bucket
```

2024-12-18 09:34 UTC, jrajahalme commented
/test

2025-01-13 16:37 UTC, derailed commented
@l1b0k Looks like we have some conflicts. Could you take a peek? Thank you!

2025-01-17 08:03 UTC, borkmann commented on bpf/lib/tb.h
> +} INGRESS_THROTTLE_MAP __section_maps_btf;
Nice work! Just thinking out loud, do you think we could merge the two bwm maps? e.g. from the id key we use one bit to denote whether the type is ingress or egress?

Could you also add another commit extending/updating the bmw doc?

2025-01-22 15:49 UTC, l1b0k commented on bpf/lib/tb.h
> +} INGRESS_THROTTLE_MAP __section_maps_btf;
I have extended `edt_id` and `edt_info`, making adjustments to simplify the code. I plan to submit another PR to update the documentation.

2025-01-22 17:09 UTC, borkmann commented on bpf/bpf_overlay.c
> +			return ret;
Looks great! Small nit: Could we move this directly into ipv{4,6}_local_delivery()?

2025-01-22 17:13 UTC, borkmann commented on bpf/lib/common.h
> +	__u8        pad[7];
tiny nit: whitespace got messed up, should be tab

2025-01-22 17:13 UTC, borkmann commented on bpf/lib/common.h
> +    __u32		prio;
ditto

2025-01-22 17:16 UTC, borkmann approved these changes
modulo small nits, LGTM, thanks!

2025-01-22 17:19 UTC, borkmann commented on bpf/lib/tb.h
> +} INGRESS_THROTTLE_MAP __section_maps_btf;
Btw, CI has some build error: 
```
CGO_ENABLED=0 go build -mod=vendor -ldflags '-X "github.com/cilium/cilium/pkg/version.ciliumVersion=1.18.0-dev f22163e86c 2025-01-22T23:19:34+08:00" -s -w -X "github.com/cilium/cilium/pkg/envoy.requiredEnvoyVersionSHA=585ba14700a2c729f024d9f0b2c694bc83a908a2" ' -tags=osusergo  -o cilium-docker
# github.com/cilium/cilium/pkg/datapath/linux/bandwidth
Error: ../pkg/datapath/linux/bandwidth/bandwidth.go:95:68: cannot use hostEpID (variable of type uint16) as bwmap.EdtIDKey value in argument to bwmap.EdtIDIndex.Query
Error: ../pkg/datapath/linux/bandwidth/bandwidth.go:99:31: not enough arguments in call to bwmap.NewEdt
	have (uint16, number, number)
	want (uint16, uint8, uint64, uint32)
Error: ../pkg/datapath/linux/bandwidth/bandwidth.go:104:39: not enough arguments in call to bwmap.NewEdt
	have (uint16, uint64, uint32)
	want (uint16, uint8, uint64, uint32)
Error: ../pkg/datapath/linux/bandwidth/bandwidth.go:113:70: cannot use epID (variable of type uint16) as bwmap.EdtIDKey value in argument to bwmap.EdtIDIndex.Query
make[1]: *** [Makefile:22: cilium-agent] Error 1
make[1]: Leaving directory '/go/src/github.com/cilium/cilium/daemon'
make: *** [Makefile:81: daemon] Error 2
make: *** Waiting for unfinished jobs....
```

2025-01-23 07:19 UTC, borkmann commented
/test

2025-01-24 20:32 UTC, nathanjsweet approved these changes
Looks good for K8s, CLI, and API.

2025-01-25 06:24 UTC, l1b0k commented
I have updated the PR;  BPF section needed to initialize the struct edt_id.

2025-01-28 05:36 UTC, youngnick approved these changes
k8s related changes are minor and LGTM

2025-01-29 23:14 UTC, hemanthmalla commented
@l1b0k IIUC, this only implements ingress rate limiting and not QoS to prioritize traffic to certain pods ? 
If so, can we update the PR title to reflect that ?

2025-01-30 09:47 UTC, tklauser commented
/test

2025-01-30 12:54 UTC, jrajahalme requested changes
I'd rather not double the bpf map key size, when that is not necessary.

2025-01-30 12:54 UTC, jrajahalme commented on bpf/lib/common.h
> +	__u8		pad[7];
Given that the `id` field is always(?) set to a 32-bit value, it would be better redefine this as:
```
struct edt_id {
	__u32		id;
	__u8		direction;
	__u8		pad[3];
};
```
This would also keep the size of `edt_id` intact. This is nice since many map implementations may have optimized hashing of 32 or 64-bit keys (not sure if applies to bpf maps, though).

Corresponding change would need to be done on Go `type EdtId` as well.

Looks like in userspace the `id` is only 16 bits, for all this would fit into a 32-bit key in kernel as well.

2025-01-31 13:23 UTC, l1b0k commented on bpf/lib/common.h
> +	__u8		pad[7];
Good call, I've made that change.

2025-02-01 15:03 UTC, jrajahalme commented
/test

2025-02-01 15:03 UTC, jrajahalme approved these changes

2025-02-13 13:58 UTC, qmonnet commented
/test

2025-02-13 14:12 UTC, qmonnet requested changes
Looks good thank you, just one comment on the file name.

2025-02-13 14:12 UTC, qmonnet commented on bpf/lib/edt.h
> +	struct edt_id aggregate = {0};
Style nit: Most other locations do `= {}` rather than `= {0}`

2025-02-13 14:12 UTC, qmonnet commented on bpf/lib/tb.h
Would you consider renaming this file to make the name more explicit, please? `token_bucket.h` is not _that_ long and would make it easier to understand what it's about.

2025-02-13 16:11 UTC, l1b0k commented on bpf/lib/tb.h
sure

2025-02-13 21:26 UTC, qmonnet commented
/test

2025-02-13 21:27 UTC, qmonnet approved these changes
Looks good, thank you!

2025-02-13 22:35 UTC, hemanthmalla approved these changes
LGTM. Thank you.

2025-02-14 10:56 UTC, merged

2025-03-06 13:18 UTC, julianwiedmann commented
:wave: how is this new major feature tested?

2025-03-10 09:07 UTC, l1b0k commented
for now manual testing locally, it can be included in e2e if necessary.