chore: quarantine high-scale IPcache
cilium/cilium pull request #36376
Opened 2024-12-04 17:02 UTC by Artyop

Quarantine waiting for https://github.com/cilium/cilium/pull/36373 before deleting the test  
More on https://isovalent.slack.com/archives/C06KAGZBNRW/p1733326137735609

Fixes: [#36323](https://github.com/cilium/cilium/issues/36323)

```release-note
Quarantine of high-scale IPcache
```

2024-12-04 17:13 UTC, pchaigno requested changes

2024-12-04 17:13 UTC, pchaigno commented on test/k8s/datapath_configuration.go
> +	// More on https://isovalent.slack.com/archives/C06KAGZBNRW/p1733326137735609
That's a private Slack link. Maybe TL;DR here instead?

2024-12-04 17:26 UTC, Artyop commented on test/k8s/datapath_configuration.go
> +	// More on https://isovalent.slack.com/archives/C06KAGZBNRW/p1733326137735609
removed the slack link

2024-12-04 17:26 UTC, pchaigno approved these changes

2024-12-04 17:27 UTC, pchaigno commented
/test

2024-12-05 09:20 UTC, Artyop commented
/test

2024-12-05 10:16 UTC, merged