Docs: review GRPC GSG
cilium/cilium pull request #3644
Opened 2018-04-11 08:47 UTC by eloycoto

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

2018-04-11 11:03 UTC, aanm requested changes

2018-04-11 11:03 UTC, aanm commented on Documentation/gettingstarted/grpc.rst
>  The next step is to install Cilium into your Kubernetes cluster.  Cilium installation
@eloycoto remove this whole `Step 1` section and replace it with 
```
.. include:: cilium_install.rst
```

2018-04-11 15:43 UTC, ianvernon requested changes
Minor nitpicks / grammatical corrections.

2018-04-11 15:43 UTC, ianvernon commented on Documentation/gettingstarted/grpc.rst
> +It is important for this demo that ``kube-dns`` is working correctly, to know the
is working correctly. To know the status...

2018-04-11 15:43 UTC, ianvernon commented on Documentation/gettingstarted/grpc.rst
> +Where at least one pod should be Availabe.
Available --> available.

2018-04-11 15:43 UTC, ianvernon commented on Documentation/gettingstarted/grpc.rst
> +policies was Star Wars-themed we decided to do the same for gRPC. While the
... Star Wars-themed, we decided...

2018-04-11 15:43 UTC, ianvernon commented on Documentation/gettingstarted/grpc.rst
> +well. Its this mismatch between the course granularity of traditional firewalls and
Its --> It is

2018-04-12 06:49 UTC, eloycoto commented
test-me-please

2018-04-13 18:06 UTC, ianvernon approved these changes

2018-04-16 08:48 UTC, merged