masquerade: type change reverted
cilium/cilium pull request #36504
Opened 2024-12-11 07:51 UTC by viktor-kurchenko

MasqueradeInterfaces type reverted to string slice.

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note

```

2024-12-11 07:59 UTC, viktor-kurchenko commented
/test

2024-12-11 14:07 UTC, Artyop approved these changes

2024-12-11 17:16 UTC, joestringer requested changes
Could you also update the flag declaration back to `StringSlice` in `daemon/cmd/daemon_main.go`?

2024-12-11 18:16 UTC, derailed approved these changes

2024-12-11 18:20 UTC, joestringer commented
I went back and forth a bit on the release note for this, but in general PRs should have only one release note  and since this is fixing a regression in v1.17.0-pre.3 I figure that `release-note/bug` is probably the most appropriate.

2024-12-11 19:28 UTC, viktor-kurchenko commented
> Could you also update the flag declaration back to `StringSlice` in `daemon/cmd/daemon_main.go`?

Oh, thank you very much! Done.

2024-12-11 19:32 UTC, viktor-kurchenko commented
/test

2024-12-11 19:41 UTC, viktor-kurchenko commented
/test

2024-12-11 20:10 UTC, joestringer approved these changes

2024-12-12 10:59 UTC, merged

2025-01-27 11:09 UTC, giorio94 commented
Additionally marking for backport to v1.15, as https://github.com/cilium/cilium/pull/36103 got marked as well.

2025-01-27 20:04 UTC, joestringer commented
I agree that if we are backporting #36103 then this should also be backported. I don't understand why we are nominating #36103 however because it's outside the regular backport criteria: https://docs.cilium.io/en/stable/contributing/release/backports/#backport-criteria . CC @nbusseneau Users should be upgrading to the latest stable release if they want all the latest bugfixes. We really should be only backporting critical changes or security fixes to the older releases at this stage, as every change comes with a degree of risk that we break something else in the older releases. The less churn we have on older branches, the less burden we take on as an open source community due to the work of backporting and potentially then also subsequently fixing broken backports on older releases. This translates into more time we can spend making the current stable or next feature release better.