datapath: Add eni parent interface to short-cut the FIB lookup
cilium/cilium pull request #36563
Opened 2024-12-13 02:01 UTC by l1b0k

Introduce THIS_INTERFACE_PARENT_IFINDEX for container endpoints to enable direct packet redirection using bpf_redirect_neigh(). This optimization eliminates the overhead of BPF FIB lookup operations in the datapath.

Flow up #36310

2024-12-13 11:08 UTC, julianwiedmann requested changes
Please limit the optimization to `CT_REPLY` results, so that it matches what we do in the corresponding redirect logic at the `to-netdev` level: https://github.com/cilium/cilium/blob/60f639c555a8ffb56ba1830b35bd1737c7030e28/bpf/lib/nodeport_egress.h#L329

2024-12-14 08:19 UTC, l1b0k commented
Wondering why need to limit to `CT_REPLY` . All packages should route out through it's own eni as the datapath described https://docs.cilium.io/en/stable/network/concepts/routing/. 
 #35298 shows the replay package  gets routed to eth0 of the host (expected for traffic to a world IP),  how does this happen ?

2025-01-13 16:32 UTC, derailed commented
@julianwiedmann Do you have an update on @l1b0k question? Thank you!

2025-02-14 15:39 UTC, julianwiedmann requested changes
Thank you! Some comments inline. Besides that - have you already looked at how to test these changes?

2025-02-14 15:39 UTC, julianwiedmann commented on bpf/bpf_lxc.c
> +		if (oif > 0 && ct_is_reply4(get_ct_map4(tuple), tuple)) {
```suggestion
		if (oif > 0 && ct_status == CT_REPLY) {
```

2025-02-14 15:39 UTC, julianwiedmann commented on bpf/bpf_lxc.c
> -		ret = fib_redirect_v4(ctx, ETH_HLEN, ip4, false, false, ext_err, &oif);
Curious, have you looked at what changes are needed to re-use `fib_redirect_v4()` here? I'd be optimistic that it's possible.

2025-03-03 07:56 UTC, l1b0k commented
> Thank you! Some comments inline. Besides that - have you already looked at how to test these changes?

It might not be straightforward to test directly; however, E2E tests may already cover the data plane connectivity.

2025-03-24 04:18 UTC, joestringer commented
> E2E tests may already cover the data plane connectivity.

I'm a little confused by the statement; do they test it or not?

2025-04-17 10:43 UTC, l1b0k commented
Correct if i'm wrong, Kubernetes Network E2E tests have cover data plane connectivity. And fib_test already have the redirect test.

2025-04-21 21:49 UTC, joestringer commented
Can you point specifically to where the relevant configuration is configured and how the specific test validates the logic?

2025-08-16 02:11 UTC, closed without merging