Pr/add feature metric docs
cilium/cilium pull request #36579
Opened 2024-12-13 11:46 UTC by aanm

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note

```

2024-12-13 13:32 UTC, aanm commented
/test

2024-12-13 15:52 UTC, qmonnet requested changes
This is not only a doc change. Would you mind providing a brief description and motivation for the feature-helm-generator and related CI steps that you introduce in your commit title+description, please?

2024-12-13 15:52 UTC, qmonnet commented on Documentation/observability/metrics.rst
> +  Metrics in this group monitor datapath configurations, such as internet
```suggestion
  Metrics in this group monitor datapath configurations, such as Internet
```

2024-12-13 15:52 UTC, qmonnet commented on Documentation/observability/metrics.rst
> +All metrics follows the format ``cilium_operator_feature`` + group name + metric name.
```suggestion
All metrics follow the format ``cilium_operator_feature`` + group name + metric name.
```

2024-12-13 15:52 UTC, qmonnet commented on Documentation/observability/metrics.rst
> +   For metrics of type "counter," the operator has processed the associated object
```suggestion
   For metrics of type "counter", the operator has processed the associated object
```

2024-12-16 10:05 UTC, qmonnet approved these changes
Thank you!

2024-12-16 13:58 UTC, viktor-kurchenko approved these changes

2024-12-17 07:49 UTC, aanm commented
/test

2024-12-17 09:08 UTC, aanm commented
/test

2024-12-17 15:02 UTC, doniacld approved these changes

2024-12-17 16:13 UTC, merged