tailcall split
cilium/cilium pull request #36591
Opened 2024-12-13 15:01 UTC by viktor-kurchenko

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note

```

2024-12-13 15:55 UTC, viktor-kurchenko commented
/test

2024-12-13 17:06 UTC, viktor-kurchenko commented
/test

2024-12-14 07:51 UTC, viktor-kurchenko commented
/test

2024-12-15 11:41 UTC, viktor-kurchenko commented
/test

2024-12-16 08:59 UTC, viktor-kurchenko commented
/test

2024-12-17 10:55 UTC, viktor-kurchenko commented
/test

2024-12-17 12:10 UTC, viktor-kurchenko commented
/test

2024-12-17 12:10 UTC, viktor-kurchenko commented
/test

2024-12-17 13:45 UTC, viktor-kurchenko commented
/test

2024-12-18 10:50 UTC, viktor-kurchenko commented
/test

2024-12-26 20:24 UTC, viktor-kurchenko commented
/ci-verifier

2024-12-26 20:32 UTC, viktor-kurchenko commented
/test

2025-01-06 08:25 UTC, julianwiedmann requested changes
> The PR extracts `do_netdev` function call into tailcalls to simplify **complexity** of `cil_from_netdev` and `cil_from_host` programs.

Note that your numbers show the difference in program **size** (number of instructions). But given that we [require](https://github.com/cilium/cilium/blob/e702d9e27390a7c8c2d55fefba04b9938905e224/pkg/datapath/linux/requirements.go#L49) `HaveLargeInstructionLimit`, that's really not a concern anymore. So you'd need to look at the `processed ... insns` output in the verifier tests, to understand the change in program **complexity**.

Ideally we'd be able to point at the problematic [datapath config](https://github.com/cilium/cilium/tree/main/bpf/complexity-tests) which demonstrates the high complexity. Or add a new config to that effect.

2025-01-06 10:40 UTC, viktor-kurchenko commented
> Note that your numbers show the difference in program **size** (number of instructions). But given that we [require](https://github.com/cilium/cilium/blob/e702d9e27390a7c8c2d55fefba04b9938905e224/pkg/datapath/linux/requirements.go#L49) `HaveLargeInstructionLimit`, that's really not a concern anymore. So you'd need to look at the `processed ... insns` output in the verifier tests, to understand the change in program **complexity**.

@julianwiedmann looks like I'm missing something but I was looking at the `processed ... insns` output, e.g. for `5.10-20241107.001101`:
```
    verifier_test.go:263: cil_from_host: processed 49 insns (limit 1000000) max_states_per_insn 0 total_states 2 peak_states 2 mark_read 2 (48 unverified insns)
```

Is it incorrect?

2025-01-06 10:48 UTC, julianwiedmann commented
> looks like I'm missing something but I was looking at the `processed ... insns` output

Then I don't understand what problem we're addressing here - in the numbers you quoted, there's nothing that would point at close-to-the-limit program complexity?

2025-01-06 10:53 UTC, viktor-kurchenko commented
> Then I don't understand what problem we're addressing here - in the numbers you quoted, there's nothing that would point at close-to-the-limit program complexity?

Yeah, so does it mean that we can simply close [the issue](https://github.com/cilium/cilium/issues/35292)?

2025-01-06 11:02 UTC, julianwiedmann commented
> Yeah, so does it mean that we can simply close [the issue](https://github.com/cilium/cilium/issues/35292)?

Ack - if we don't have a datapath configuration that demonstrates the high program complexity, I don't think we should make any change.

> Maybe complexity was high before your refactoring: #35463 ?

That would have only helped `to-netdev` though.

2025-01-06 11:05 UTC, closed without merging