golint: use consistent receiver names
cilium/cilium pull request #366
Opened 2017-03-20 18:01 UTC by scanf

Fixes all of the warnings with the following pattern

... receiver name x should be consistent with previous receiver name y for Z (golint)

Related-to: #153 (Resolve golint warnings)

2017-03-20 18:01 UTC, aanm commented
This pull request is now managed with CodeReviewHub. <a href='https://github.com/cilium/cilium/pull/366'>Refresh</a>.<a href='#crh-update-none'></a>

2017-03-20 20:58 UTC, aanm requested changes

2017-03-20 20:58 UTC, aanm commented on pkg/labels/labels.go
>  // SHA256Sum calculates lbls' internal SHA256Sum. For a particular set of labels is
Can you change the function comment as well? ("lbls" -> "receiver's Labels `l`")

2017-03-20 20:58 UTC, aanm commented on pkg/maps/lbmap/ipv6.go
>  func (k *RevNat6Value) GetValuePtr() unsafe.Pointer { return unsafe.Pointer(k) }
I think this one should be `v` instead of `k`, no? (And the following ones would be kept as `v`)

2017-03-20 20:58 UTC, aanm commented on pkg/maps/policymap/policymap.go
> +func (p *PolicyMap) AllowConsumer(id uint32) error {
Why `PolicyEntry` is `pe` but `PolicyMap` is not `pm`?

2017-03-20 20:58 UTC, aanm commented on pkg/policy/identity.go
> -func (s *Identity) AssociateEndpoint(id string) {
`s`-> `id` and `id` -> `epID`

2017-03-20 20:58 UTC, aanm commented on pkg/policy/identity.go
> +func (id *Identity) DisassociateEndpoint(id2 string) bool {
`s`-> `id` and `id` -> `epID`

2017-03-20 20:59 UTC, aanm commented
What are the golint errors? Is because the receiver's variable doesn't start with the same letter as the struct's name?

2017-03-20 21:05 UTC, tgraf commented
> What are the golint errors? Is because the receiver's variable doesn't start with the same letter as the struct's name?

I think the error states that if you have multiple functions for the same struct they should all share the same variable name in the func prototype.

2017-03-20 21:47 UTC, scanf commented on pkg/labels/labels.go
>  // SHA256Sum calculates lbls' internal SHA256Sum. For a particular set of labels is
:+1:

2017-03-20 21:56 UTC, scanf commented on pkg/maps/lbmap/ipv6.go
>  func (k *RevNat6Value) GetValuePtr() unsafe.Pointer { return unsafe.Pointer(k) }
:+1:

2017-03-20 21:57 UTC, aalemayhu commented on pkg/maps/policymap/policymap.go
> +func (p *PolicyMap) AllowConsumer(id uint32) error {
IIRC, there was a mix and I tried to pick whatever was previously used in the file.

2017-03-20 21:59 UTC, scanf commented on pkg/policy/identity.go
> -func (s *Identity) AssociateEndpoint(id string) {
:+1:

2017-03-20 22:07 UTC, scanf commented
@aanm TBH, I don't know how golint works so not sure why it reports _712 warning but only 85 issues across 343 files_. The numbers are straight from https://goreportcard.com/report/github.com/cilium/cilium

From the golang wiki there is a section called **Receiver Names**
>The name of a method's receiver should be a reflection of its identity; often a one or two letter abbreviation of its type suffices (such as "c" or "cl" for "Client"). Don't use generic names such as "me", "this" or "self", identifiers typical of object-oriented languages that place more emphasis on methods as opposed to functions. The name need not be as descriptive as that of a method argument, as its role is obvious and serves no documentary purpose. It can be very short as it will appear on almost every line of every method of the type; familiarity admits brevity. Be consistent, too: if you call the receiver "c" in one method, don't call it "cl" in another.

https://github.com/golang/go/wiki/CodeReviewComments#receiver-names

2017-03-21 00:45 UTC, aanm requested changes

2017-03-21 00:45 UTC, aanm commented on pkg/maps/policymap/policymap.go
> +func (p *PolicyMap) AllowConsumer(id uint32) error {
Can you change it to `pm`? Just to be consistent with the `PolicyEntry` -> `pe`

2017-03-21 06:15 UTC, scanf commented
:+1:<a href='#crh-update-none'></a>

2017-03-21 06:15 UTC, scanf commented on pkg/policy/identity.go
> +func (id *Identity) DisassociateEndpoint(id2 string) bool {
:+1:<a href='#crh-update-none'></a>

2017-03-21 06:15 UTC, scanf commented on pkg/maps/policymap/policymap.go
> +func (p *PolicyMap) AllowConsumer(id uint32) error {
:+1:<a href='#crh-update-complete'></a>

2017-03-21 14:50 UTC, aanm approved these changes
Awesome work, thank you!

2017-03-21 14:50 UTC, merged