clustermesh: Add hidden flag --allow-buggy-clustermesh
cilium/cilium pull request #36602
Opened 2024-12-13 21:58 UTC by joestringer

This hidden flag can allow existing users who are using a high
clustermesh ID in ENI environments to continue using it at their own
risk. Recently we added a check to startup to detect this potentially
problematic configuration and warn users, however it's now no longer
possible to run Cilium in the risky configuration. This puts users in a
tough spot of whether to run an outdated release or manually patch out
this newly introduced guardrail.

In the long term we should be able to lift the restriction around
usage of clustermesh ID in the datapath, but for now we should try to
encourage users not to configure Cilium this way while still ultimately
leaving the decision up to them about how to manage their environments.

Related: #35349
Related: #36309

2024-12-13 22:00 UTC, joestringer commented
@giorio94 I had pushed for the solution in #35349 because I figured it's better that by default users can't configure Cilium in this risky configuration. However, perhaps users are not running policies and won't observe the worst effects of this configuration. In issue https://github.com/cilium/cilium/issues/36309 for instance the user wants to continue to run in that configuration despite the risks. While I don't think we should encourage it, it seems like they've been able to run like that previously without hiccups. The idea for this PR is to create a hidden flag that advanced users can opt into if they know what they're doing and accept the risks. At least this means they're not locked into an older release of Cilium, potentially missing out on other fixes like security updates etc. Do you think this is a reasonable middle ground?

2024-12-16 17:20 UTC, giorio94 requested changes
> The idea for this PR is to create a hidden flag that advanced users can opt into if they know what they're doing and accept the risks. At least this means they're not locked into an older release of Cilium, potentially missing out on other fixes like security updates etc. Do you think this is a reasonable middle ground?

Sounds reasonable to me, with the caveat that connectivity is probably completely broken in this configuration as soon as network policies are used. I've left a couple of comments inline, mostly about the flag naming.

One extra note is that the same validation is also [performed via helm](https://github.com/cilium/cilium/blob/pr%2Fjoe%2Fallow-broken-clustermesh/install/kubernetes/cilium/templates/validate.yaml#L151-L155), and should be probably relaxed as well:

2024-12-16 17:20 UTC, giorio94 commented on pkg/clustermesh/cell.go
> +	flags.Bool("allow-buggy-clustermesh", false,
Hmm, I'd suggest changing the flag name to `allow-buggy-identities`, `allow-buggy-netpols`, or something like that. My feeling with the current wording is that it implies that the problem is clustermesh-specific, but it actually affects the traffic in the local cluster if the given cluster IDs are configured, regardless of whether clustermesh is used or not.

2024-12-16 17:20 UTC, giorio94 commented on pkg/clustermesh/cell.go
> +type ClustermeshConfig struct {
Nit. The struct handling the `cluster-id/cluster-name` flags is defined in `pkg/clustermesh/types/option.go`. I'd suggesting moving this one there as well (although I reckon it may need to be a separate struct given that the other is used by multiple components). The name seems to imply again that this is clustermesh-specific, which is not.

2024-12-16 17:20 UTC, giorio94 commented on pkg/clustermesh/cell.go
> +	cell.Config(defaultConfig),
The ClusterInfo config is registered [here](https://github.com/cilium/cilium/blob/pr%2Fjoe%2Fallow-broken-clustermesh/daemon/cmd/cells.go#L261), so I'd probably move this one there as well for consistency.

2024-12-16 17:20 UTC, giorio94 commented on pkg/clustermesh/cell.go
> +	cell.Invoke(func(info types.ClusterInfo, dcfg *option.DaemonConfig, cnimgr cni.CNIConfigManager, cfg Configuration) error {
Nit. It would be better to depend on the `ClustermeshConfig` (however it'll be called), rather than the full `Configuration` object.

2024-12-19 16:17 UTC, joestringer commented on pkg/clustermesh/cell.go
> +	flags.Bool("allow-buggy-clustermesh", false,
Yeah the naming of this flag is not ideal, I'll need to think about it. In some sense the `buggy` aspect helps to scare users but I don't like associating that word with a feature. Maybe the more generic term is `--allow-unsafe-policy-skb-usage` or something. The thing I am not sure about though is that if the mitigation for the user is to modify the clustermesh IDs for their environment, then it seems like it should use clustermesh in the name. I appreciate though that it's only a problem with the combination of clustermesh and policy.

2024-12-19 16:18 UTC, joestringer commented
Thanks for the feedback @giorio94 . I'll park this for now due to lack of cycles, but I agree this could do with a few improvements.

2024-12-19 16:52 UTC, giorio94 commented on pkg/clustermesh/cell.go
> +	flags.Bool("allow-buggy-clustermesh", false,
> The thing I am not sure about though is that if the mitigation for the user is to modify the clustermesh IDs for their environment, then it seems like it should use clustermesh in the name. I appreciate though that it's only a problem with the combination of clustermesh and policy.

You can actually set a ClusterID different from zero even if you are not using clustermesh at all. I guess that my main point here is that having clustermesh in the term implies that it affects cross-cluster traffic only, while this issue is actually about the netpol enforcement inside the local cluster (and possibly cross-cluster, by extension).

2025-01-15 00:38 UTC, joestringer commented on pkg/clustermesh/cell.go
> +	cell.Config(defaultConfig),
I ended up declaring a new `Quirks` module specifically to combine the new flag and the logic to detect/handle this scenario. That way the quirks module can be included in the Hive from the top-level as you suggest. It's not otherwise obvious to me when we should make config part of the module itself vs. at the top level; for instance the two lines directly above this are specifying default config for this module.

I did however end up modifying where you linked in order to only include this quirks logic in the cilium-agent and not in the other binaries that consume clustermesh.

2025-01-15 00:40 UTC, joestringer commented on pkg/clustermesh/cell.go
> +	cell.Invoke(func(info types.ClusterInfo, dcfg *option.DaemonConfig, cnimgr cni.CNIConfigManager, cfg Configuration) error {
The `Configuration` object here is to pull a logger from somewhere. I couldn't find a better handle for a logger. If you have an alternative suggestion then I'd be open to feedback, otherwise I'll keep that parameter just for the logger.

2025-01-15 01:47 UTC, joestringer commented
/test

2025-01-15 01:48 UTC, joestringer commented
/test

2025-01-15 14:44 UTC, giorio94 approved these changes
Thanks!

2025-01-15 14:44 UTC, giorio94 commented on pkg/clustermesh/cell.go
> +	cell.Invoke(func(info types.ClusterInfo, dcfg *option.DaemonConfig, cnimgr cni.CNIConfigManager, cfg Configuration, quirks types.QuirksConfig) error {
```suggestion
	cell.Invoke(func(logger logrus.FieldLogger, info types.ClusterInfo, dcfg *option.DaemonConfig, cnimgr cni.CNIConfigManager, quirks types.QuirksConfig) error {
```

Nit. I'd suggest depending explicitly on the logger, rather than on the broader cfg object.

2025-01-15 15:27 UTC, joestringer commented on pkg/clustermesh/cell.go
> +	cell.Invoke(func(info types.ClusterInfo, dcfg *option.DaemonConfig, cnimgr cni.CNIConfigManager, cfg Configuration, quirks types.QuirksConfig) error {
How do we make sure the Logger is the right one, for example including the right subsystem etc? Do we need to declare a specific clustermesh logger type and provide it from the same Cell?

2025-01-15 15:44 UTC, giorio94 commented on pkg/clustermesh/cell.go
> +	cell.Invoke(func(info types.ClusterInfo, dcfg *option.DaemonConfig, cnimgr cni.CNIConfigManager, cfg Configuration, quirks types.QuirksConfig) error {
That's automatically taken care of by hive, which always provides a logger (either logrus or slog) scoped for the module that requested it. The logger part of the `Configuration` structure is also already retrieved that way, without any further customization.

2025-01-15 15:46 UTC, joestringer commented on pkg/clustermesh/cell.go
> +	cell.Invoke(func(info types.ClusterInfo, dcfg *option.DaemonConfig, cnimgr cni.CNIConfigManager, cfg Configuration, quirks types.QuirksConfig) error {
It looks like Hive/Cell magically populates this. Incremental patch, will push soon:

```
diff --git a/pkg/clustermesh/cell.go b/pkg/clustermesh/cell.go
index 9cc5ba6591f2..d3f2c7cd2ffe 100644
--- a/pkg/clustermesh/cell.go
+++ b/pkg/clustermesh/cell.go
@@ -5,6 +5,7 @@ package clustermesh
 
 import (
        "github.com/cilium/hive/cell"
+       "github.com/sirupsen/logrus"
 
        "github.com/cilium/cilium/daemon/cmd/cni"
        "github.com/cilium/cilium/pkg/clustermesh/common"
@@ -40,10 +41,10 @@ var Cell = cell.Module(
        metrics.Metric(common.MetricsProvider(subsystem)),
 
        cell.Config(types.DefaultQuirks),
-       cell.Invoke(func(info types.ClusterInfo, dcfg *option.DaemonConfig, cnimgr cni.CNIConfigManager, cfg Configuration, quirks types.QuirksConfig) error {
+       cell.Invoke(func(info types.ClusterInfo, dcfg *option.DaemonConfig, cnimgr cni.CNIConfigManager, log logrus.FieldLogger, quirks types.QuirksConfig) error {
                err := info.ValidateBuggyClusterID(dcfg.IPAM, cnimgr.GetChainingMode())
                if err != nil && quirks.AllowUnsafePolicySKBUsage {
-                       cfg.Logger.WithError(err).Error("Detected clustermesh ID configuration that may cause connection impact")
+                       log.WithError(err).Error("Detected clustermesh ID configuration that may cause connection impact")
                        return nil
                }
                return err
```

2025-01-15 15:49 UTC, joestringer commented
/test

2025-01-15 16:09 UTC, gandro approved these changes

2025-01-15 19:13 UTC, joestringer commented
/test

2025-01-15 22:18 UTC, merged