bpf: nat: remove NAT_MIN_EGRESS
cilium/cilium pull request #36631
Opened 2024-12-16 13:24 UTC by gyutaeb

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

It is no longer correct to check the `NAT_MIN_EGRESS` condition. This is because `target->from_local_endpoint` is now being checked. In the case of `!target->from_local_endpoint`, source NAT is not required, and performing source NAT can result in incorrect source NAT, leading to connection failures as described in #36572.

Fixes: #36572

2024-12-18 06:45 UTC, julianwiedmann requested changes
>It is no longer correct to check the NAT_MIN_EGRESS condition. This is because target->from_local_endpoint is now being checked. In the case of !target->from_local_endpoint, source NAT is not required,

I don't follow. Can you please elaborate *much* more on the suggested change. **Why** is source NAT not required in the case you're describing? Also please add this in-depth explanation to the patch description, not just the PR.

2024-12-23 13:23 UTC, gyutaeb commented
@julianwiedmann @gentoo-root Thank you for review! When using iptables masquerade instead of bpf masquerade, SNAT is not required. I plan to enhance the `cDefinesMap` and explanation of suggested change. I will re-request after that.

2025-01-03 04:05 UTC, gyutaeb commented
@julianwiedmann @gentoo-root @ti-mo Thank you for your patience. The previous changes had some ambiguities. To clarify the bug and the fix, I added `cDefinesMap["ENABLE_IPTABLES_MASQUERADE_IPV4"]` and `cDefinesMap["ENABLE_IPTABLES_MASQUERADE_IPV6"]` to explicitly handle SNAT accordingly. Additionally, I provided a clear and detailed explanation of the #36572 and the commit description.
The issue is that when using iptables masquerade, the source address is already nat-ed by iptables. So, we should skip SNAT when using iptables masquerade. If we don't skip SNAT, the source address is nat-ed twice. It also unnecessarily occupies entry in the `SNAT_MAPPING` map. And if it exceeds `SNAT_COLLISION_RETRIES`, it leads to connection failures due to `DROP_NAT_NO_MAPPING`.
This patch ensures that SNAT is skipped when using iptables masquerade. It prevents duplicate SNAT, avoids unnecessary use of the `SNAT_MAPING` map, and mitigates connection failures caused by packet drops. Additionally, by eliminating the complexity caused by duplicate SNAT, it reduces troubleshooting time and clarifies the masquerade process.
The new define was named based on the code reference below.
https://github.com/cilium/cilium/blob/5a4fdc967a51146c15b65e5401ecb5d7decdd8d2/pkg/option/config.go#L2416-L2426

2025-01-06 07:11 UTC, gyutaeb commented
*Update Branch(Rebase)

2025-01-08 06:51 UTC, julianwiedmann requested changes
I don't see how this can be correct for the case of using BPF Nodeport without BPF masquerade. Please elaborate a lot more.

We're **intentionally* tracking connections in the SNAT engine for this case, and applying SNAT as needed to avoid conflicts between [LB-to-remote-backend connections](https://github.com/cilium/cilium/blob/d2c4e0f7baa6080bd78b4ae454e1c21de88e61ab/bpf/lib/nodeport.h#L2453) and [host-originating / iptables-masqueraded connections](https://github.com/cilium/cilium/blob/d2c4e0f7baa6080bd78b4ae454e1c21de88e61ab/bpf/lib/nodeport_egress.h#L347).

2025-01-09 16:32 UTC, gyutaeb commented
> I don't see how this can be correct for the case of using BPF Nodeport without BPF masquerade. Please elaborate a lot more.
> 
> We're **intentionally** tracking connections in the SNAT engine for this case, and applying SNAT as needed to avoid conflicts between [LB-to-remote-backend connections](https://github.com/cilium/cilium/blob/d2c4e0f7baa6080bd78b4ae454e1c21de88e61ab/bpf/lib/nodeport.h#L2453) and [host-originating / iptables-masqueraded connections](https://github.com/cilium/cilium/blob/d2c4e0f7baa6080bd78b4ae454e1c21de88e61ab/bpf/lib/nodeport_egress.h#L347).

@julianwiedmann Thank you for your detailed explanation. I agree with your opinion, After reviewing the case you explained, I realized that skipping SNAT in iptables-masquerade cannot prevent the conflict with LB-to-remote-backend.
```
flow1: pod -> node:nodeport(32000) >>>> SNAT engine >>>> node:natedPort(34000) -> remote-backend
flow2: host -> external >>>> iptables-masquerade >>>> host:natedPort(34000) -> external
```
I hadn't considered that scenario, so thank you for pointing it out. This PR should not be merged. To elaborate, during my attempts to reproduce this issue, I observed a rare case where the SNAT engine performed SNAT on an egress packet, but the reverse NAT for the response packet failed. This occurred when the `--bpf-nat-global-max` limit was reached. I tried skipping SNAT in order to resolve this issue, but it's clear now that skipping SNAT is not the right approach. Instead, I will focus on analyzing why reverse NAT occasionally fails. If you have encountered or received reports about a similar issue, I'd greatly appreciate it if you could share them.
In summary, this PR should not be merged. I will focus on the reverse NAT issue and submit a new PR with an appropriate fix.

2025-01-09 16:52 UTC, julianwiedmann commented
> In summary, this PR should not be merged. I will focus on the reverse NAT issue and submit a new PR with an appropriate fix.

Thank you for the feedback! Looking forward to what you come up with :).

I'll flip this PR to `draft` then for now.

2025-01-16 06:11 UTC, gyutaeb commented
> I observed a rare case where the SNAT engine performed SNAT on an egress packet, but the reverse NAT for the response packet failed.

@julianwiedmann Hello, I'd like to share the root cause of the issue that caused REV NAT to fail, as mentioned earlier. This issue was mitigated by #35304, which introduced the idea of recreating evicted reverse entries during NAT using the otuple. I think this is a fantastic approach!
While #35304 has significantly reduced the issue, there are still rare cases where the reverse entry is evicted when `snat_v4_rev_nat_handle_mapping()` attempts to find it.
To address this, I'd like to propose an alternative: if `snat_v4_rev_nat_handle_mapping()` cannot find the reverse entry, it could attempt to recreate it using the original entry(assuming the original entry has not been deleted). What are your thoughts on this approach?

2025-01-17 07:56 UTC, julianwiedmann commented
> > I observed a rare case where the SNAT engine performed SNAT on an egress packet, but the reverse NAT for the response packet failed.
> 
> @julianwiedmann Hello, I'd like to share the root cause of the issue that caused REV NAT to fail, as mentioned earlier. This issue was mitigated by #35304, which introduced the idea of recreating evicted reverse entries during NAT, using the otuple. I think this is a fantastic approach! While #35304 has significantly reduced the issue, there are still rare cases where the reverse entry is evicted when `snat_v4_rev_nat_handle_mapping()` attempts to find it. To address this, I'd like to propose an alternative: if `snat_v4_rev_nat_handle_mapping()` cannot find the reverse entry, it could attempt to recreate it using the original entry(assuming the original entry has not been deleted). What are your thoughts on this approach?

Sorry, I don't think I'll have the cycles to co-design a solution for the problem you encountered. But maybe you can connect with @sugangli and discuss this in more detail - hack up a minimal reproducer that demonstrates the problem etc?

2025-01-17 17:46 UTC, sugangli commented
Hi @gyutaeb,  

IIUC,  retrieving the original entry from the rev nat path could be a bit tricky. Could you give an example on how it could be done? Feel free to tag me in the new PR once you are ready.

2025-01-19 09:58 UTC, gyutaeb commented
Hi, @sugangli 
I will reach out to you once the code is ready. I'm excited to collaborate with you. Currently, I am working on a PR related to #31213, and it will take a few more weeks to complete. Thank you for your support!

2025-05-07 02:09 UTC, closed without merging