v1.14 Backports 2024-12-16
cilium/cilium pull request #36639
Opened 2024-12-16 15:46 UTC by pippolo84

* [ ] #36549 (@verysonglaa) :warning: resolved conflicts

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 36549
```

2024-12-16 15:55 UTC, michi-covalent approved these changes

2024-12-16 15:55 UTC, gandro requested changes

2024-12-16 15:55 UTC, gandro commented on Documentation/security/policy/language.rst
> +<<<<<<< HEAD
Unresolved merge conflict

2024-12-16 16:10 UTC, pippolo84 commented on Documentation/security/policy/language.rst
> +<<<<<<< HEAD
Fixed, thanks!

2024-12-16 16:18 UTC, gandro approved these changes

2024-12-17 18:27 UTC, pippolo84 commented
/test-backport-1.14

2024-12-19 10:01 UTC, merged