doc: Update metrics documentation & list exported metrics
cilium/cilium pull request #3665
Opened 2018-04-11 18:55 UTC by raybejjani

We export a small list of metrics and now list them in the docs. This
change also includes some text fixups and a bad link to the prometheus
configuration.

Relates to: https://github.com/cilium/cilium/issues/3597

2018-04-11 18:55 UTC, raybejjani commented
test-me-please

2018-04-11 19:48 UTC, borkmann commented
test-me-please

2018-04-11 23:05 UTC, tgraf requested changes

2018-04-11 23:05 UTC, tgraf commented on Documentation/configuration/metrics.rst
> +Your Cilium spec will need these labels:
Annotations?

2018-04-12 00:09 UTC, ianvernon requested changes
Small nits.

2018-04-12 00:09 UTC, ianvernon commented on Documentation/configuration/metrics.rst
> +Cilium as a kubernetes pod
kubernetes --> Kubernetes

2018-04-12 00:09 UTC, ianvernon commented on Documentation/configuration/metrics.rst
> +Prometheus will contact the kubernetes API server for these lists and must have
kubernetes --> Kubernetes

2018-04-12 00:09 UTC, ianvernon commented on Documentation/configuration/metrics.rst
> +annotation, and tag the resulting metrics series. In the kubernetes case
kubernetes --> Kubernetes

2018-04-12 00:09 UTC, ianvernon commented on Documentation/configuration/metrics.rst
> +- discover the metrics url path from the label ``prometheus.io/path`` or use the default of ``/metrics`` when it isn't present
url --> URL

2018-04-12 09:32 UTC, raybejjani commented
test-me-please

2018-04-12 21:44 UTC, tgraf approved these changes

2018-04-12 21:55 UTC, merged