SNAT metrics
cilium/cilium pull request #36730
Opened 2024-12-19 12:51 UTC by gentoo-root

Collect a histogram of the number of attempts taken before a successful
(or an unsuccessful) port allocation for SNAT occurs. These data will be
useful for troubleshooting and for evaluating SNAT port allocation
algorithms. For example, collecting these statistics at various ratios
of allocated ports will show the distribution of how quickly the
algorithm can find an unused port (and whether at all).

New cilium-dbg commands are added:

`cilium-dbg bpf nat retries list` - to print the histogram.
`cilium-dbg bpf nat retries flush` - to reset the counters to zero.

Fixes: #35621

```release-note
Collect a histogram and show the distribution of the number of attempts needed to allocate a port for SNAT.
```

2025-01-06 15:53 UTC, derailed reviewed
@gentoo-root Nice work! Could be off base here so please disregard if not applicable...

2025-01-06 15:53 UTC, derailed commented on cilium-dbg/cmd/bpf_nat_retries_list.go
> +		if len(args) == 0 {
nit: Better to exit early if extra invalid args are detected

2025-01-06 15:53 UTC, derailed commented on cilium-dbg/cmd/bpf_nat_retries_list.go
> +	entries := make([]nat.RetriesMapRecord, 0)
nit: move where it's actually used. Also nil slice would suffice.

2025-01-06 15:53 UTC, derailed commented on pkg/bpf/map_linux.go
> +type MapPerCPUValue interface {
nit: docs

2025-01-06 15:53 UTC, derailed commented on pkg/bpf/map_linux.go
> +type DumpPerCPUCallback func(key MapKey, values any)
nit: docs

2025-01-06 15:53 UTC, derailed commented on pkg/bpf/map_linux.go
> +func (m *Map) DumpPerCPUWithCallback(cb DumpPerCPUCallback) error {
nit: docs

2025-01-06 15:53 UTC, derailed commented on pkg/bpf/map_linux.go
> +	if err := m.Open(); err != nil {
Not sure of implications here but the map is open and never closed and the path is not checked? 
It looks like the call site also manages existence/open/close on the map?
Do we want to assume call site is responsible for these checks if existence is required?
Would it be best to let this method handle it instead and perhaps DumpPerCPUWithCBIfExists?

2025-01-06 15:53 UTC, derailed commented on pkg/maps/nat/nat.go
> +func RetriesMaps(ipv4, ipv6, nodeport bool) (ipv4RetriesMap, ipv6RetriesMap RetriesMap) {
nit: docs

2025-01-07 09:36 UTC, borkmann approved these changes
apart from comments from Fernand, this lgtm! Maybe also add a commit adding `cilium-dbg bpf nat retries list` to the sysdump?

2025-01-07 14:11 UTC, gentoo-root commented on cilium-dbg/cmd/bpf_nat_retries_list.go
> +		if len(args) == 0 {
Inspired by [this](https://github.com/cilium/cilium/blob/181ed5a73517ba9e3ca0c64063202049d6f32321/cilium-dbg/cmd/bpf_nat_list.go#L28-L52), but I agree with you.

2025-01-07 14:11 UTC, gentoo-root commented on cilium-dbg/cmd/bpf_nat_retries_list.go
> +	entries := make([]nat.RetriesMapRecord, 0)
ACK (inspired by [this](https://github.com/cilium/cilium/blob/181ed5a73517ba9e3ca0c64063202049d6f32321/cilium-dbg/cmd/bpf_nat_list.go#L62))

2025-01-07 14:11 UTC, gentoo-root commented on pkg/bpf/map_linux.go
> +	if err := m.Open(); err != nil {
> the map is open and never closed

It's similar to other methods ([DumpWithCallback](https://github.com/cilium/cilium/blob/181ed5a73517ba9e3ca0c64063202049d6f32321/pkg/bpf/map_linux.go#L614), [Lookup](https://github.com/cilium/cilium/blob/181ed5a73517ba9e3ca0c64063202049d6f32321/pkg/bpf/map_linux.go#L1028)). The map is opened on demand on the first access, and it's the responsibility of the caller to close it. It's the pattern that is widely used across the codebase, and changing it would require rewriting of a lot of things. I'm following the existing pattern. E.g., like in `bpf nat list`: [link](https://github.com/cilium/cilium/blob/181ed5a73517ba9e3ca0c64063202049d6f32321/cilium-dbg/cmd/bpf_nat_list.go#L68-L89). I do it in a similar fashion in `bpf nat retries list`: [link](https://github.com/cilium/cilium/pull/36730/files/0b36a35aa4b7b661ee6070e4e13bbba3cbf293be#diff-8c02757c3e3dd9daf80a1155d6e8947d7167dace77e8526253a827a41d713278R48).

> It looks like the call site also manages existence/open/close on the map?
Do we want to assume call site is responsible for these checks if existence is required?

Basically, yes, and it's an assumption that we make in the existing code, I'm not adding anything new here.

2025-01-07 14:11 UTC, gentoo-root commented on pkg/bpf/map_linux.go
> +type MapPerCPUValue interface {
ACK.

2025-01-07 14:11 UTC, gentoo-root commented on pkg/bpf/map_linux.go
> +type DumpPerCPUCallback func(key MapKey, values any)
ACK.

2025-01-07 14:11 UTC, gentoo-root commented on pkg/bpf/map_linux.go
> +func (m *Map) DumpPerCPUWithCallback(cb DumpPerCPUCallback) error {
ACK.

2025-01-07 14:11 UTC, gentoo-root commented on pkg/maps/nat/nat.go
> +func RetriesMaps(ipv4, ipv6, nodeport bool) (ipv4RetriesMap, ipv6RetriesMap RetriesMap) {
ACK.

2025-01-13 16:18 UTC, derailed reviewed
@gentoo-root Thanks for the updates!

2025-01-13 16:18 UTC, derailed commented on pkg/bpf/map_linux.go
> +type MapPerCPUValue interface {
Exported calls docs should always start with the item name i.e MapPerCPUValue.

2025-01-13 16:18 UTC, derailed commented on pkg/bpf/map_linux.go
> +type DumpPerCPUCallback func(key MapKey, values any)
Same as above ^

2025-01-13 16:18 UTC, derailed commented on pkg/bpf/map_linux.go
> +	if err := m.Open(); err != nil {
@gentoo-root Thank you for the clarification! Are there implications in opening the map twice? The current pattern seems off as the call site opens the resource and is responsible to close it but the underlying call re-open the resource and assumes the call site is responsible for closing it?? 
This might be ok on a short lived call but it seems to be an anti-pattern.

2025-01-15 16:21 UTC, tommyp1ckles requested changes

2025-01-15 16:21 UTC, tommyp1ckles commented on pkg/bpf/map_linux.go
> +	err := i.Err()
nit: can just be `return i.Err()`

2025-01-15 16:21 UTC, tommyp1ckles commented on pkg/maps/nat/nat.go
> +	DumpPerCPUWithCallback(bpf.DumpPerCPUCallback) error
minor/non-blocking: There's a bit of overlap with the `NatMap` interface, we could probably simplify using interface composition.

```go
type commonMap interface {
	Open() error
	Close() error
	Path() (string, error)
	DumpEntries() (string, error)  
}

type NatMap interface {
        commonMap
        DumpWithCallback(bpf.DumpCallback) error
}

type RetriesMap interface {
        commonMap
        DumpPerCPUWithCallback(bpf.DumpPerCPUCallback) error
        ClearAll() error
}
```

2025-01-15 16:21 UTC, tommyp1ckles commented on cilium-dbg/cmd/bpf_nat_retries_list.go
> +func dumpRetries(m nat.RetriesMap) {
Question: Is there any plan to provide this as a prometheus metric, this would map well to proms histogram type.

2025-01-15 16:22 UTC, tommyp1ckles approved these changes
Just a few small points (should've added them as Comment not Require-Changes). Otherwise no blocking issues for me.

2025-01-15 16:34 UTC, tommyp1ckles requested changes

2025-01-15 16:34 UTC, tommyp1ckles commented on pkg/maps/nat/nat.go
> +func (k *RetriesValue) NewSlice() any     { return &RetriesValues{} }
Actually, one question, shouldn't this return a pointer to a slice type?

2025-01-21 18:25 UTC, rgo3 requested changes
Should we add unit tests for the newly added `DumpPerCPUWithCallback` and `ClearAll` functions in the `bpf` package?

2025-01-21 18:25 UTC, rgo3 commented on pkg/bpf/map_linux.go
> +
```suggestion

	// Validate map type early
	if !m.hasPerCPUValue() {
		return fmt.Errorf("map %s is not a per-CPU map", m.name)
	}

    // do type assertion once, avoid repetitive type assertions below in the loop
    // also bails out early if value type doesn't satisfy the MapPerCPUValue interface
	perCPUValue, ok := m.value.(MapPerCPUValue)
	if !ok {
		return fmt.Errorf("map %s value type does not implement MapPerCPUValue", m.name)
	}
```

2025-01-22 14:44 UTC, gentoo-root commented on pkg/bpf/map_linux.go
> +	if err := m.Open(); err != nil {
> Are there implications in opening the map twice?

Open() is idempotent, the second call will be a no-op: https://github.com/cilium/cilium/blob/a9b6d692f62e56bff501ea9565fbb4bd91bab68a/pkg/bpf/map_linux.go#L547-L549

> it seems to be an anti-pattern

I tend to agree with you. If the open-close lifecycle is managed externally, the methods should fail when the map was not opened. If the methods try to fall back and open it, I see a bunch of problems: the caller doesn't know whether it needs to close it now (i.e. whether it was opened now or before), the method might use a wrong way of opening the map (there are Open, OpenMap, OpenOrCreate).

However, for some reason we have it in a lot of methods (DumpWithCallback, DumpReliablyWithCallback, Lookup, Update, delete, DeleteAll, resolveErrors), so it might be problematic to just get rid of it, because some other code might rely on this behavior. I also don't know the reason why we have it there in the first place. So, I'd rather keep the existing (anti-)pattern in this PR, and we can experiment with removing it in a follow-up (feel free to try it, as you are the one who spotted it).

2025-01-22 17:16 UTC, gentoo-root commented on pkg/maps/nat/nat.go
> +func (k *RetriesValue) NewSlice() any     { return &RetriesValues{} }
You mean, instead of `any`? It's an interface method, and the caller needs a slice of structs, not a slice of interfaces. As the struct type can be anything that implements MapValue, and generic methods are not supported in Go, I had to erase the type. If you know a better way (without making [Map](https://github.com/cilium/cilium/blob/663c450daa6c6c80e9722637b5fa7390a64b9799/pkg/bpf/map_linux.go#L65) a generic struct and rewriting all code in the project), please tell me, I would be happy to change it into something better.

2025-01-22 17:18 UTC, gentoo-root commented on cilium-dbg/cmd/bpf_nat_retries_list.go
> +func dumpRetries(m nat.RetriesMap) {
That's a good idea, and I guess it would be useful to expose it in prometheus. I'll check if it can be done here or as a follow-up. If you have an example of something similar, could you send me a pointer?

2025-01-22 17:22 UTC, gentoo-root commented on pkg/bpf/map_linux.go
> +
Thanks! Makes sense to me, I'll add it.

2025-01-22 19:07 UTC, tommyp1ckles commented on pkg/maps/nat/nat.go
> +func (k *RetriesValue) NewSlice() any     { return &RetriesValues{} }
Oh I misread, didn't realize RetriesValues was actually an alias for a slice type.

looks good

2025-01-22 19:07 UTC, tommyp1ckles approved these changes

2025-01-24 09:52 UTC, rgo3 requested changes
Made some suggestions to avoid changing the `Update` API to facilitate the unit tests.

2025-01-24 09:52 UTC, rgo3 commented on pkg/bpf/map_linux.go
> +	if m.hasPerCPUValue() {
Not sure if we should make changes to the Update API just to facilitate a test.
Instead of using the Update API in the test, we can try to write a setup function that accesses the underlying `ebpf.Map` directly (I'll make a comment with my idea at the appropriate place in the code) inserting per-CPU values like in this test: https://github.com/cilium/ebpf/blob/f224bff41d4d89fca11ddac24453f6dacffb6f89/map_test.go#L2327. Once the map is setup check if Dump and Clear work as expected?

2025-01-24 09:52 UTC, rgo3 commented on pkg/bpf/map_linux_test.go
> +	err := testMap.Update(key1, value1)
Would `testMap.m.Put(...)` work here?

2025-01-24 15:27 UTC, gentoo-root commented on pkg/bpf/map_linux.go
> +	if m.hasPerCPUValue() {
> write a setup function that accesses the underlying ebpf.Map directly

Good idea, thanks. Implemented.

2025-01-24 17:50 UTC, rgo3 approved these changes
LGTM, thanks!

2025-01-24 17:50 UTC, rgo3 commented on pkg/bpf/map_linux_test.go
> +	func() {
Is there a benefit to wrapping this into an anonymous function?

2025-01-24 18:04 UTC, gentoo-root commented on pkg/bpf/map_linux_test.go
> +	func() {
It's for `defer testMap.lock.Unlock()` to trigger after all Update()s, but not later. As far as I know, it defers until the return from the function, so a regular `{ block of code }` wouldn't suffice.

2025-01-28 17:30 UTC, derailed commented on pkg/bpf/map_linux.go
> +	if err := m.Open(); err != nil {
@gentoo-root Thanks for the clarifications! I think at the very least we should add docs to that effect on all the public APIs to ensure the call site is aware and does the right thing with that resource. 
And perhaps a TODO might be appropriate here so we can revisit for a code debt pass

2025-01-28 17:31 UTC, derailed approved these changes
@gentoo-root Tx for the updates!

2025-01-28 19:12 UTC, merged

2025-02-17 07:06 UTC, julianwiedmann commented on bpf/node_config.h
> +
Looks like this change tripped over a weird issue in BPF program compilation during downgrade:
https://github.com/cilium/cilium/issues/37602

2025-02-17 10:03 UTC, gentoo-root commented on bpf/node_config.h
> +
The issue description says it happened on one node only, where node_config.h wasn't regenerated for some reason. Sounds like the general bug is with node_config.h generation, not directly caused by moving this #define.