Update azure go sdk
cilium/cilium pull request #36751
Opened 2024-12-21 02:02 UTC by HadrienPatte

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Related to issue #32274

```release-note
Update Azure go SDK
```
---

Migrate from older version of Azure SDKs of management libraries for Go language (package name starting with `services/**/mgmt/**`, also known as track1) to the latest version of Azure SDKs for Go (SDK package name starting with `sdk/resourcemanager/**/arm**`, also known as track2).

The older Golang libraries that do not conform to Azure SDK guidelines have been deprecated since 30 September 2023.

This PR follows microsoft's [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md#long-running-operations).

# Summary of changes

## By path

### `go.mod`/`go.sum`
* Removed dependency on depreciated `github.com/Azure/azure-sdk-for-go` module as well as related `github.com/Azure/go-autorest` libraries
* Added new `github.com/Azure/azure-sdk-for-go/sdk/xxx` modules

### `pkg/azure/api/api.go`
Bulk of the changes are here, this file has been significantly rewritten, see summary of changes by symbol bellow for details.

### `vendor`
Automated changes resulting from running `go mod tidy`/`go mod vendor` following the `go.mod` updates described above

## By symbol
* `constructAuthorizer`:
  * Has been replaced with `newTokenCredential`, and the underlying implementation has switched from using the `github.com/Azure/go-autorest/autorest` libraries to the `github.com/Azure/azure-sdk-for-go/sdk/azidentity` ones. The logic remains the same: if a managed identity ID is provided, then use it to get credentials, otherwise rely on environment variable and file-based credentials.
* `NewClient`:
  * Part of its logic has been split out in a helper function `newClientOptions` which handles the cloud type detection that was previously done with `azure.EnvironmentFromName` and also sets the custom cilium user agent for all azure API calls via a custom `net/http` client.
  * The rest of this function remains mostly unchanged, the four azure API clients are still created and initialized here, but with the newer `NewXXXClient` functions from their respective new `arm` packages.
* `describeNetworkInterfaces`: renamed to `listAllNetworkInterfaces` for naming consistency
* `vmNetworkInterfaces`: updated to use the new [pager-based](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md#pagination) syntax.
* `vmssNetworkInterfaces`:
  * Listing of the virtual machines scale sets has been split out in a helper `listVirtualMachineScaleSets` function.
  * Listing of the interfaces of a single virtual machine scale set has been split out in a helper `listVirtualMachineScaleSetNetworkInterfaces` function.
* `listVirtualMachineScaleSets`: new helper function split from `vmssNetworkInterfaces`, uses the new [pager-based](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md#pagination) syntax.
* `listVirtualMachineScaleSetNetworkInterfaces`: new helper function split from `vmssNetworkInterfaces`, uses the new [pager-based](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md#pagination) syntax.
* `parseInterface`: minor changes related to changes in the structs from the new azure libraries
* `describeVpcs`:
  * Renamed to `listAllVPCs` for naming consistency
  * Updated to use the new [pager-based](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md#pagination) syntax.
  * Note: I noticed that this function was previously setup to list all VPCs and not just the ones in the client's resource groups, whereas all other azure API calls in are always scoped to a resource group. I preserved this setup with the updated azure SDK libraries.
* `parseSubnet`: minor changes related to changes in the structs from the new azure libraries
* `AssignPrivateIpAddressesVMSS`:
  * Minor changes related to changes in the structs from the new azure libraries
  * Updated to use the new [poller-based](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md#long-running-operations) syntax.
* `AssignPrivateIpAddressesVM`:
  * Minor changes related to changes in the structs from the new azure libraries
  * Updated to use the new [poller-based](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md#long-running-operations) syntax.

## Additional notes

Also introduces anonymous functions with defered calls for azure API call duration measurement. See the current code:
```go
sinceStart = spanstat.Start()
future, err := c.vmss.Update(ctx, c.resourceGroup, vmssName, instanceID, result)
defer c.metricsAPI.ObserveAPICall(VirtualMachineScaleSetVMsUpdate, deriveStatus(err), sinceStart.Seconds())
...
return xxx
```
And go's `defer` documentation:
> The deferred call's arguments are evaluated immediately, but the function call is not executed until the surrounding function returns.

This means that with the above snippet, `ObserveAPICall` is correctly defered to only run once the function gets to a `return` statement, but its `sinceStart.Seconds()` argument gets evaluated at the same tiime `ObserveAPICall gets registered to be defered, instead of when it actually runs.

With the following updated code:
```go
sinceStart = spanstat.Start()
poller, err := c.virtualMachineScaleSetVMs.BeginUpdate(ctx, c.resourceGroup, vmssName, instanceID, result.VirtualMachineScaleSetVM, nil)
defer func() {
	c.metricsAPI.ObserveAPICall(virtualMachineScaleSetVMsUpdate, deriveStatus(err), sinceStart.Seconds())
}()
...
return ...
```
Now it's the whole anonymous `func() {...}` function that is registered to be defered, and that function has no arguments that would be evaluated right away. As it is fully wrapped in the anonymous function, `sinceStart.Seconds()` is only evaluated when the anonymous function runs  after having been defered.

As a result of this fix, the value of the `cilium_operator_azure_api_duration_seconds` metric will see an increase.

2024-12-21 02:49 UTC, ovidiutirla approved these changes

2024-12-21 02:49 UTC, ovidiutirla commented
/test

2025-01-07 22:15 UTC, tommyp1ckles requested changes

2025-01-07 22:15 UTC, tommyp1ckles commented on pkg/azure/api/api.go
> +			if virtualMachineScaleSet.Name == nil {
What are the circumstances when this could be nil?

2025-01-07 22:15 UTC, tommyp1ckles commented on pkg/azure/api/api.go
> +			if errors.As(err, &respErr) && respErr.StatusCode == http.StatusNotFound {
Bit confused by this snippet (before and after the change). Won't `respErr` just always be nil here, causing errors.As(err, &respErr) to just always be false?

2025-01-08 12:48 UTC, HadrienPatte commented on pkg/azure/api/api.go
> +			if errors.As(err, &respErr) && respErr.StatusCode == http.StatusNotFound {
I don't think so, this looks consistent with [this example snippet](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore#example-ResponseError): when `err` is not nil, we use [errors.As](https://pkg.go.dev/errors#As) to cast it to `respErr` which is a `*azcore.ResponseError`. If that cast is successful, then `errors.As(...)` returns `true` and `respErr` is no longer a nil pointer.
> As finds the first error in err's tree that matches target, and if one is found, sets target to that error value and returns true. Otherwise, it returns false.

As for `errors.As(...) && respErr.xxx`, errors.As is evaluated first, so by the time `respErr.StatusCode` is evaluated, `respErr` is no longer nil (see [this example snippet](https://go.dev/play/p/d0zeybzVGcq))

2025-01-08 12:48 UTC, HadrienPatte commented on pkg/azure/api/api.go
> +			if virtualMachineScaleSet.Name == nil {
I am not sure, this pattern is one that was already present before and has been here since the introduction of azure IPAM in #10089 and I just preserved it as is.

The same pattern is in other similar functions ([here](https://github.com/cilium/cilium/blob/0959a41eea2d40ed30209a6bfebeadd1679aff56/pkg/azure/api/api.go#L203-L205), [there](https://github.com/cilium/cilium/blob/0959a41eea2d40ed30209a6bfebeadd1679aff56/pkg/azure/api/api.go#L255-L257), [there](https://github.com/cilium/cilium/blob/0959a41eea2d40ed30209a6bfebeadd1679aff56/pkg/azure/api/api.go#L292-L294) and [there](https://github.com/cilium/cilium/blob/0959a41eea2d40ed30209a6bfebeadd1679aff56/pkg/azure/api/api.go#L457-L459)). I don't mind removing those `nil` checks if you think they are not necessary and the azure API will never return a response that has an object with a `nil` name

2025-01-08 22:43 UTC, tommyp1ckles commented
/test

2025-01-08 22:44 UTC, tommyp1ckles approved these changes

2025-01-09 01:26 UTC, merged