Test: Gather core dumps in test if are present.
cilium/cilium pull request #3683
Opened 2018-04-12 08:01 UTC by eloycoto

If cilium dies by a core dump the core is not saved on Jenkins artifact.
With this change the core will be created and saved in the test folder
to further analysis.

Fix #3399
Needs to wait until: PR #3354
This unblocks PR #3355

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

**Summary of changes**:

Fixes: #issue-number

```release-note

```

**How to test (optional)**:
e.g. Run `make tests`, `make runtime-tests` and/or some more specific way to
exercise the new behavior(s).
Note: [The runtime testsuite will modify the host it runs on.](http://cilium.readthedocs.io/en/latest/contributing/#testsuite)

2018-04-12 12:52 UTC, borkmann approved these changes

2018-04-13 18:07 UTC, ianvernon commented
Can you elaborate as to why this PR is blocked by PR #3354 ? The two do not seem related to me.

2018-04-13 18:07 UTC, ianvernon commented
test-me-please

2018-04-13 18:09 UTC, ianvernon requested changes
Looks fine at face-value. However, I do have some concerns. Specifically, what is the size of these core dumps? If these core dumps are large, will it affect stability of Jenkins w.r.t. available disk space? I'd prefer if this PR is closed and this is added as a commit in #3355 so that all of this logic is coupled together so that we can see if we can fail the build if a segmentation fault is detected, and then test whether the core-garhtering logic functions correctly.

2018-04-16 07:51 UTC, eloycoto commented
@ianvernon 

1) Core dumps size, don't worry, actually Jenkins has plenty of space, disks were added a few months back. 
2) Ok.

2018-04-16 08:52 UTC, eloycoto commented
Cherry pick the changes on 3355 PR.

2018-04-16 08:52 UTC, closed without merging