daemon: Use per-subsystem async status collection
cilium/cilium pull request #3690
Opened 2018-04-12 14:31 UTC by raybejjani

This is an extension of https://github.com/cilium/cilium/pull/3607 I had hoped to redo it in far fewer lines. It feels far too verbose for what it does so I'm not terribly pleased with it :/

The async code before this change was effective but it has two problems:
- When a deadlock occurs, `cilium status` cannot detect this because we keep returning the most recent status object
- Any subsystem that is slow or doesn't update will block others from being updated.

This change splits out each subsystem into a separate controller to collect the status while the API handler simply marshals the data into the final status object. It also does the final checkups to populate the global status, which now include a staleness check. Not all these subsystems take locks but some make status requests to other things (like docker, I think) so it seemed safest to treat all of them as a slow path. 

**How to test (optional)**:
all tests pass

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cilium/cilium/3690)

2018-04-12 14:32 UTC, raybejjani commented
test-me-please

2018-04-12 23:29 UTC, aanm requested changes

2018-04-12 23:29 UTC, aanm commented on daemon/status.go
>  	collectStatusInterval = 5 * time.Second
Isn't 5 seconds a little aggressive?

2018-04-12 23:29 UTC, aanm commented on daemon/status.go
> +func (h *getHealthz) Handle(params GetHealthzParams) middleware.Responder {
Shouldn't this be somewhere else? I had the feeling the "Handles" were all in a single file

2018-04-12 23:29 UTC, aanm commented on daemon/status.go
> +	l7ProxyStatusTS time.Time
What does `TS` mean?

2018-04-12 23:29 UTC, aanm commented on daemon/status.go
> +			"global-locks":      dss.lockStatusTS,
Maybe use constants instead?

2018-04-12 23:29 UTC, aanm commented on daemon/status.go
> +	staleTimeout = 1 * collectStatusInterval
Maybe `2 * collectStatusInterval`?

2018-04-12 23:29 UTC, aanm commented on daemon/status.go
> +			if newDelay := now.Sub(ts); newDelay > maxDelay {
What does this do exactly?

2018-04-12 23:29 UTC, aanm commented on daemon/status.go
> +func (dss *daemonStatus) startStatusCollector(d *Daemon) {
You are passing the `daemon` only because of the `IPAM`? Don't he have every single component in packages?  :disappointed:

2018-04-13 12:53 UTC, raybejjani commented on daemon/status.go
>  	collectStatusInterval = 5 * time.Second
I left it as it was before. It is aggressive because some subsystems call out to something else (the `getK8sStatus` and `containerd.Status()`). On the other hand status lookups ideally aren't that costly, since they are reads.
In any case, what value would make sense? We previously felt ok setting the k8s liveness prove to 10s but at least there one could turn it off if something went wrong. This is more hardcoded :/ Still, 5s or 10s doesn't solve the issue where each node is hitting the k8s api server every so many seconds but I'm not sure what value would make that less troubling.
This value controls the resolution of the status data. If we set it too long we risk being blind to failures. In the most trivial case we are always `collectStatusInterval` behind from the real status when requesting `/healthz`. There likely isn't a perfect number since it's a compromise between real-timeness and not overloading shared resources.

2018-04-13 12:53 UTC, raybejjani commented on daemon/status.go
> +	staleTimeout = 1 * collectStatusInterval
I actually started with this at `3*` and it was called `deadlockTimeout`. I couldn't pick a number that made sense so I picked the `1*` and hoped a reviewer would have some input ;) I had thought we held a bpf build lock somewhere but I can't find it. I switched to `2*` but it might be better to set an explicit time instead? (like 30s or 1 minute).

2018-04-13 12:53 UTC, raybejjani commented on daemon/status.go
> +func (h *getHealthz) Handle(params GetHealthzParams) middleware.Responder {
I think it's a mix :/ some are near the thing they represent: https://github.com/cilium/cilium/blob/master/daemon/ipam.go#L39

It was here before so Ieft it. I don't particularly care one way or the other so you get to decide :)

2018-04-13 12:53 UTC, raybejjani commented on daemon/status.go
> +	l7ProxyStatusTS time.Time
timestamp
I'll reorder these fields to be all the status fields in one group and all the timestamps in another. I can then have a comment explaining how they are used and updated.

2018-04-13 12:53 UTC, raybejjani commented on daemon/status.go
> +func (dss *daemonStatus) startStatusCollector(d *Daemon) {
and `getK8sStatus` but yeah, not too many things need it. This method was originally on the `Daemon` class but it didn't make sense anymore since these controllers were inside this daemonStatus type (and the locks). I could, of course, not have the new type at all and leave everything in the main `Daemon` but this scheme allows us to make `dss` a global object more easily later.

Do you have a preference? We seem to be in the middle of packages as global singletons vs objects as global singletons (I have a preference but the project has not decided yet, it seems).

2018-04-13 12:53 UTC, raybejjani commented on daemon/status.go
> +			"global-locks":      dss.lockStatusTS,
for the key names? or for the whole map?

2018-04-13 12:53 UTC, raybejjani commented on daemon/status.go
> +			if newDelay := now.Sub(ts); newDelay > maxDelay {
for all the timestamps of the last update of the status, is any timestamp older than staleThreshold. If it is, add it to the list and calculate how long ago it was updated (`newDelay`). If it's larger than `maxDelay` it becomes the new `maxDelay`.
I realise now that it would be better to simply return the oldest timestamp from here and we can print it directly. I switched to that and the code is more clear (I hope).

2018-04-13 12:54 UTC, raybejjani commented
test-me-please

2018-04-13 18:31 UTC, ianvernon approved these changes

2018-04-17 15:34 UTC, aanm commented on daemon/status.go
> +			"global-locks":      dss.lockStatusTS,
for the key names

2018-04-17 15:34 UTC, aanm commented on daemon/status.go
> +	staleTimeout = 1 * collectStatusInterval
Discussed offline. best option would be one timeout per collector. I'm fine with 30s or 1 minute

2018-04-17 15:41 UTC, aanm commented on daemon/status.go
> +			if newDelay := now.Sub(ts); newDelay > maxDelay {
`What does this do exactly?` a.k.a. `Please add documentation in the code :-)` for this part

2018-05-29 13:27 UTC, raybejjani commented
test-me-please

2018-05-29 13:57 UTC, raybejjani commented
I'm closing this in favour of https://github.com/cilium/cilium/pull/4273 It is too big for what it does, I think, and I couldn't find a good way to simplify it without more annoying complexity.

2018-05-29 13:57 UTC, closed without merging