daemon: Regenerate endpoint in PATCH handler also when endpoint is in waiting-for-identity state
cilium/cilium pull request #3706
Opened 2018-04-12 23:07 UTC by jrajahalme

commit 41c08396ce ("daemon: Only regenerate in PATCH from valid
state") intended to limit endpoint regeneration calls from the API
PATCH endpoint handler to valid endpoint states, but inadvertently
limited the allowed states only to waiting-to-regenerate, while the
endpoint should also be built while in the waiting-for-identity state.

The symptom was that endpoints created via docker never built the
initial drop-all bpf program while waiting for identity.

This commit allows endpoint regeneration via the PATCH endpoint API
also when the endpoint is in wairing-for-identity state.

CI testing for this is done by #3625

Fixes: #3705
Fixes: 41c08396ce ("daemon: Only regenerate in PATCH from valid state")
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

2018-04-12 23:09 UTC, jrajahalme commented
test-me-please

2018-04-12 23:10 UTC, joestringer approved these changes

2018-04-12 23:22 UTC, manalibhutiyani requested changes

2018-04-12 23:22 UTC, manalibhutiyani commented on daemon/endpoint.go
> +		if err := ep.RegenerateWait(h.d, "Waiting on endpoint regeneration while handling API PATCH"); err != nil {
Should we have a separate log for `endpoint.StateWaitingToRegenerate` versus `endpoint.StateWaitingForIdentity`

```
Switch state {
    case endpoint.StateWaitingToRegenerate:
    logMesg = "Waiting on endpoint regeneration because identity is known while handling API PATCH"

    case endpoint.StateWaitingForIdentity:
    logMesg = "Waiting on endpoint regeneration because of DROP_ALL policy at endpoint creation"
}
if err := ep.RegenerateWait(h.d, logMesg); err != nil {
```

I think maintaining this difference is important for correctly identifying endpoint state /logs in the future.?

2018-04-12 23:55 UTC, jrajahalme commented on daemon/endpoint.go
> +		if err := ep.RegenerateWait(h.d, "Waiting on endpoint regeneration while handling API PATCH"); err != nil {
Changed as requested, but avoided using DROP_ALL due to these strings being visible via cilium API (not just logs). Used "initial program" instead.

2018-04-12 23:57 UTC, manalibhutiyani commented on daemon/endpoint.go
> +		if err := ep.RegenerateWait(h.d, "Waiting on endpoint regeneration while handling API PATCH"); err != nil {
Thanks!

2018-04-12 23:58 UTC, jrajahalme commented
test-me-please

2018-04-12 23:58 UTC, manalibhutiyani approved these changes

2018-04-12 23:59 UTC, manalibhutiyani commented
test-missed-k8s

2018-04-13 01:45 UTC, manalibhutiyani commented
Star Wars demo test failed:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/100/execution/node/43/log/

```
00:17:49 K8sValidatedDemosTest
00:17:49 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:280
00:17:49   Tests Star Wars Demo [It]
00:17:49   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:312
00:17:49 
00:17:49   unable to curl deathstar.default.svc.cluster.local/v1: 000command terminated with exit code 6
00:17:49   command terminated with exit code 6
00:17:49   
00:17:49   Expected
00:17:49       <string>: 000command terminated with exit code 6
00:17:49       command terminated with exit code 6
00:17:49       
00:17:49   to contain substring
00:17:49       <string>: 200
```
Raised : https://github.com/cilium/cilium/issues/3710


Also:

```
00:24:52 • Failure in Spec Setup (BeforeEach) [30.270 seconds]
00:24:52 K8sValidatedUpdates
00:24:52 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:280
00:24:52   Updating Cilium stable to master [BeforeEach]
00:24:52   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:312
00:24:52 
00:24:52   cannot apply cilium example daemonset
00:24:52   Expected
00:24:52       <bool>: false
00:24:52   to be true
00:24:52 
00:24:52   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/helpers/utils.go:192
00:24:52 ------------------------------
00:24:52 SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
00:24:52 
00:24:52 Summarizing 1 Failure:
00:24:52 
00:24:52 [Fail] K8sValidatedUpdates [BeforeEach] Updating Cilium stable to master 
00:24:52 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/helpers/utils.go:192
00:24:52 
```
Updated the GH issue #3692

2018-04-13 01:45 UTC, manalibhutiyani commented
test-me-please

2018-04-13 01:46 UTC, manalibhutiyani commented
test-missed-k8s

2018-04-13 04:09 UTC, tgraf approved these changes

2018-04-13 04:09 UTC, merged