examples/minikube: Allow container to mount bpffs itself
cilium/cilium pull request #3768
Opened 2018-04-17 09:58 UTC by mrostecki

Containers with the SYS_ADMIN capability are able to create mounts
(even for bpffs) and mounting it from host is not needed. The
requirement of mounting bppfs on host is invalid in case of
Minikube, because Minikube VMs don't mount bpffs.

Signed-off-by: Michal Rostecki <mrostecki@suse.com>

**Summary of changes**:

Fixes: #3717

```release-note

```

**How to test (optional)**:
Run the modified `cilium-ds.yaml` file on Minikube, then `demo.yaml` and `l3_l4_l7_policy.xaml`, after that check whether you got rid of errors like that (which occur every time you run the demo on Minikube without changes from this PR!):

```
level=error msg="bpf: Unable to update in tunnel endpoint map" error="Unable to get object /sys/fs/bpf/tc/globals/tunnel_endpoint_map: no such file or directory" ipAddr=172.16.xxx.xxx/23
```

2018-04-17 10:09 UTC, mrostecki commented
test-me-please

2018-04-17 14:37 UTC, aanm requested changes
@mrostecki It seems this file is deprecated as we no longer reference it in our documentation.

2018-04-17 18:52 UTC, tgraf commented
@mrostecki If we want to do this then we should add it to `examples/kubernetes` directly. This shouldn't be minikube specific, correct?

2018-04-18 08:11 UTC, mrostecki commented
I've just reaized that BPF mounts on host are needed for persistency after Cilium pod restarts. I will submit an another, proper fix for the issue today.

2018-04-18 08:11 UTC, closed without merging