systemd: Enable core dumps.
cilium/cilium pull request #3849
Opened 2018-04-20 23:31 UTC by jrajahalme

Enable core dumps both in dev VM and CI VMs, and update `cilium.service` to not limit cores.

This does not change CI test behavior, but enables collecting cores manually from local CI runs.

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

2018-04-20 23:33 UTC, jrajahalme commented
This overlaps with #3355, but was still very useful for local debugging without changing CI behavior.

2018-04-23 07:23 UTC, eloycoto requested changes

2018-04-23 07:23 UTC, eloycoto commented on test/provision/runtime_install.sh
> +sudo systemctl disable apport.service
Could you update the VM to version 52 and you don't need to add these ones. 

https://app.vagrantup.com/cilium/boxes/ubuntu/versions/52

2018-04-23 18:21 UTC, jrajahalme commented
test-me-please

2018-04-23 18:22 UTC, jrajahalme commented
Updated to use the newer box (52) as requested.

2018-04-23 19:18 UTC, eloycoto commented
LGTM

2018-04-23 19:55 UTC, jrajahalme commented
test-me-please

2018-04-24 01:58 UTC, ianvernon commented
While approval was not given, merging since @eloycoto said LGTM, which equates to an approval.

2018-04-24 01:58 UTC, merged