kvstore: Introduce shared store type
cilium/cilium pull request #4124
Opened 2018-05-16 11:59 UTC by tgraf

Package store implements a shared store backed by a kvstore or similar with
the following properties:

* A single type is used to represent all keys
* Any number of collaborators can join the store. Typically a collaborator
  is an individual Cilium agent running on each node.
* All collaborators can own and contribute keys to the store. Each key is
  owned by exactly one collaborator. It is the responsibility of each
  collaborator to pick a key name which is guaranteed to be unique.
* All collaborate desire to see all keys within the scope of a store. The
  scope of the store is defined by a common key prefix. For this purpose,
  each collaborator maintains a local cache of all keys in the store by
  subscribing to change events.

This implementation will be used by the upcoming kvstore based node discovery

Signed-off-by: Thomas Graf <thomas@cilium.io>

2018-05-16 11:59 UTC, tgraf commented
test-me-please

2018-05-16 13:18 UTC, tgraf commented
test-me-please

2018-05-16 15:57 UTC, tgraf commented
test-me-please

2018-05-16 18:19 UTC, ianvernon requested changes
First round of comments.

2018-05-16 18:19 UTC, ianvernon commented on pkg/kvstore/store/store.go
> +	log = logrus.WithField(logfields.LogSubsys, "shared-store")
this should be `logging.DefaultLogger.WithField...` where logging is `pkg/logging`

2018-05-16 18:19 UTC, ianvernon commented on pkg/kvstore/store/store.go
> +// DeleteLocalKey removes a key from bein synchronized with the kvstore
bein --> being

2018-05-16 18:19 UTC, ianvernon commented on pkg/kvstore/store/store.go
> +	delete(s.localKeys, name)
if you `delete(s.localKeys, name)` and then check `_, ok := s.localKeys[name]`, won't `ok` always be `false`?

2018-05-16 18:19 UTC, ianvernon commented on pkg/kvstore/store/store.go
> +			logger.Infof("Received key update via kvstore [value %s]", event.Value)
Based on past experience, you may not have the value of the event when the event is `kvstore.EventTypeDelete`, so the log message might look strange.

2018-05-16 18:19 UTC, ianvernon commented on pkg/kvstore/store/store.go
> +	if key == nil {
why not:

``` key, ok := s.sharedKeys[name]
if !ok { ... }
```

?

2018-05-16 18:19 UTC, ianvernon commented on pkg/kvstore/store/store.go
> +		if s.localKeys[name] != nil {
Same here, why not use the `key, ok` convention?

2018-05-16 18:19 UTC, ianvernon commented on pkg/kvstore/store/store.go
> +	if existingKey == nil {
And here.

2018-05-16 22:47 UTC, tgraf commented
test-me-please

2018-05-17 11:00 UTC, aanm commented on pkg/kvstore/store/store.go
> +			logger.Infof("Received key update via kvstore [value %s]", event.Value)
The `event.Value` is a slice of byes so `event.Value` should be cast into a string

2018-05-17 11:00 UTC, aanm commented on pkg/kvstore/store/store.go
> +					logger.WithError(err).Warningf("Unable to unmarshal store value: %s", event.Value)
The `event.Value` is a slice of byes so `event.Value` should be cast into a string

2018-05-17 22:12 UTC, tgraf commented
test-me-please

2018-05-18 09:44 UTC, tgraf commented
test-me-please

2018-05-18 09:59 UTC, aanm approved these changes

2018-05-19 08:43 UTC, tgraf commented
test-me-please

2018-05-20 08:34 UTC, merged