Add containerd integration
cilium/cilium pull request #4184
Opened 2018-05-18 18:18 UTC by aanm

**Summary of changes**:

Add containerd integration

Note to reviewers: the first 5 commits belong to PR #4128

2018-05-18 18:19 UTC, aanm commented
test-me-please

2018-05-22 15:23 UTC, raybejjani requested changes
+1 Nothing terribly big, but I'm not sure about the intention with the CLI option. It's like we want to support multiple runtimes, but we only store one internally. It might be better to avoid that until we're sure we'll add more (it's non-breaking to make the CLI option take multiple from taking only one)

2018-05-22 15:23 UTC, raybejjani commented on daemon/state.go
> +			} else if !workloads.IsRunning(ep) {
Should this say `docker.IsRunning`? I don't see where we moved this, and the file it was in seems to still be in the docker package. (I'm looking at this per-commit so maybe it's fixed later)

2018-05-22 15:23 UTC, raybejjani commented on daemon/state.go
> +			} else if !workloads.IsRunning(ep) {
ah, I see it in `pkg/workloads: add containerd integration`

2018-05-22 15:23 UTC, raybejjani commented on pkg/workloads/runtimes.go
> +	workloadIDsList(ctx context.Context) ([]string, error)
I didn't realise you could have private functions on an interface. Do they only work if the implementor is part of this package too?

2018-05-22 15:23 UTC, raybejjani commented on pkg/workloads/client.go
> +func Client() WorkloadRuntime {
Are we expecting to support multiple clients in the future? Why not expose defaultClient directly? It might also be worth dropping the `default` since the only way to get it is with `Client()` since it's set via initClient (and not `init()`).

2018-05-22 15:23 UTC, raybejjani commented on pkg/workloads/config.go
> +	var err error
It would be good to comment that this err is the one written in the once below, and that it is returned at the end of this outer function. I was really confused for a while.

2018-05-22 15:23 UTC, raybejjani commented on pkg/workloads/containerd.go
> +			c.processEvent(m)
When we added the per-container handlers it was because we couldn't spend too long handling an event (at least, I think that was why). Will that cause an issue here? We also couldn't just `go c.processEvent` because that would be out of order (this doesn't have that issue, but if we would have it again if we needed to return sooner)

2018-05-22 15:23 UTC, raybejjani commented on pkg/workloads/containerd.go
> +			c.processEvent(m)
Oh, I see, we have a buffered channel... that should be enough

2018-05-22 15:23 UTC, raybejjani commented on pkg/workloads/client.go
> +func Client() WorkloadRuntime {
Hmm, we also allow a list of strings and parse that all the way to `Setup`... but I guess we're only allowing `auto` or nothing? so this is intended to be a single runtime

2018-05-22 15:23 UTC, raybejjani commented on Documentation/cmdref/cilium-agent.md
> +      --container-runtime stringSlice     Sets the container runtime(s) used by Cilium { containerd | docker | none | auto } ( "auto" the uses the container runtime found in the order: "docker", "con
Probably drop the plural here. I was really confused because I thought we could run more than one, but the code seems to only allow for one `Client()`

2018-05-22 15:23 UTC, raybejjani commented on pkg/option/config.go
> +	Workloads       []string   // List of Workloads set by the user to used by cilium.
unless we know we'll be supporting multiple soon (which I hope we do) this is actually the mode, since we only store one `Client()`, no?

2018-05-24 18:38 UTC, aanm commented
test-me-please

2018-05-24 21:27 UTC, aanm commented
test-me-please

2018-05-24 22:50 UTC, aanm commented
test-me-please

2018-05-25 19:29 UTC, aanm commented
test-me-please

2018-05-28 13:06 UTC, aanm commented on pkg/workloads/runtimes.go
> +	workloadIDsList(ctx context.Context) ([]string, error)
Yes

2018-05-28 13:11 UTC, aanm commented
>+1 Nothing terribly big, but I'm not sure about the intention with the CLI option. It's like we want to support multiple runtimes, but we only store one internally. It might be better to avoid that until we're sure we'll add more (it's non-breaking to make the CLI option take multiple from taking only one)

@raybejjani I've noticed that your comments were most related with the one vs multiple clients. The flag was always intended to support multiple runtimes at the same time, and it will be. Since I don't want to break backwards compatibility I'll keep it as such, if the user uses "auto" it will automatically detect which container runtime is running.

I'll add a new PR later on to have multiple container runtimes running and every time the daemon calls `pkg/workloads.Client()`. there will be a call for all the runtimes connected. Does that makes sense?

2018-05-29 09:11 UTC, raybejjani approved these changes
Oops, I didn't realise the CLI parameter was already a slice. You are correct in not wanting to change that. How does it work, though? will it use the last value in the slice? or just do all of them and lose the earlier ones (and how would "auto" interact with the other two). Anyway, it's doesn't need to be part of this PR since nothing has changed in that behaviour from before. ship it.

2018-05-29 09:11 UTC, raybejjani commented on Documentation/cmdref/cilium-agent.md
> +      --container-runtime stringSlice     Sets the container runtime(s) used by Cilium { containerd | docker | none | auto } ( "auto" the uses the container runtime found in the order: "docker", "con
Ah, I just noticed`"auto" the uses the container runtime found in the order: "docker", "containerd"` has an extra `the` in there.

2018-05-29 11:56 UTC, tgraf approved these changes

2018-05-29 11:56 UTC, merged