Elasticsearch Getting Started Guide
cilium/cilium pull request #4186
Opened 2018-05-18 20:03 UTC by ackerman80

Signed-off-by: Arvind Soni <arvindsoni@gmail.com>

2018-05-18 20:03 UTC, ackerman80 commented
test-docs-please

2018-05-18 20:04 UTC, ackerman80 commented
test-me-please

2018-05-21 16:34 UTC, ackerman80 commented
Tested on K8s 1.8, 1.9, 1.10. Partial test on 1.7 that the app yaml works correctly

2018-05-21 18:37 UTC, aanm requested changes

2018-05-21 18:37 UTC, aanm commented on Documentation/gettingstarted/elasticsearch.rst
> +   :scale: 30 %
Is 40% to big?

2018-05-21 18:37 UTC, aanm commented on Documentation/gettingstarted/elasticsearch.rst
> +    role "elasticsearch" created
The output  was different for me, specially the "deployment"
```
    serviceaccount "elasticsearch" created
    service "elasticsearch" created
    replicationcontroller "es" created
    role.rbac.authorization.k8s.io "elasticsearch" created
    rolebinding.rbac.authorization.k8s.io "elasticsearch" created
    pod "sidious" created
    pod "vader" created
```

2018-05-21 18:37 UTC, aanm commented on Documentation/gettingstarted/elasticsearch.rst
> +A fundamental security concern for Elasticsearch service is *which client services should be allowed to access what content and perform what actions*. This is an access control problem at the API-lay
`which client....` is in italic, you meant italic or bold?

2018-05-21 18:37 UTC, aanm commented on Documentation/gettingstarted/elasticsearch.rst
> +    created :  {'_index': 'sidious', '_type': 'tome', '_id': '1', '_version': 1, 'result': 'created', '_shards': {'total': 2, 'successful': 1, 'failed': 0}, 'created': True}
Output was different, I got 2 created messages
```
Creating/Updating Books
created :  {'_index': 'sidious', '_type': 'tome', '_id': '1', '_version': 1, 'result': 'created', '_shards': {'total': 2, 'successful': 1, 'failed': 0}, 'created': True}
created :  {'_index': 'sidious', '_type': 'tome', '_id': '2', '_version': 1, 'result': 'created', '_shards': {'total': 2, 'successful': 1, 'failed': 0}, 'created': True}
```

2018-05-21 18:37 UTC, aanm commented on Documentation/gettingstarted/elasticsearch.rst
> +    Got 2 Hits:
Output is different:
```
Searching for Books by Darth Sidious
Got 2 Hits:
{'_index': 'sidious', '_type': 'tome', '_id': '2', '_score': 1.0, '_source': {'author': 'sidious', 'title': 'Force is Same for Dark Side and Jedi'}}
{'_index': 'sidious', '_type': 'tome', '_id': '1', '_score': 1.0, '_source': {'author': 'sidious', 'title': 'Why Convert a Jedi!'}}
Get Book 1 by Darth Sidious
{'author': 'sidious', 'title': 'Why Convert a Jedi!'}
```

2018-05-21 18:37 UTC, aanm commented on Documentation/gettingstarted/elasticsearch.rst
> +Sidious has access to perform ``GET`` and ``PUT`` as expected. But see what happens when Vader has both ``GET`` and ``PUT`` access. Vader can completely modify the books! (Note the change in book tit
I would change it to `Vader can, and did completely modified the books! (Note the change in book titles from 'Convert Jedi to Dark Side: 101' to "Why convert a Jedi!")`

2018-05-21 18:37 UTC, aanm commented on examples/kubernetes-es/es-sw-policy.yaml
> +- egress:
Do we need the egress policy for this example?

2018-05-21 18:48 UTC, aanm submitted a review, later dismissed

2018-05-21 18:48 UTC, aanm commented on Documentation/gettingstarted/elasticsearch.rst
> +In this example, the policy rules are defined for inbound traffic (i.e., "ingress") connections to the *elasticsearch* service. Note that endpoints selected as backend pods for the service are define
instead of

>``k8s: component: elasticsearch``

should be

> ``'k8s:component': elasticsearch``

2018-05-21 21:06 UTC, aanm approved these changes

2018-05-21 21:06 UTC, aanm commented
test-docs-please

2018-05-21 23:52 UTC, merged