Split debuginfo into separate files
cilium/cilium pull request #4252
Opened 2018-05-25 12:12 UTC by stevenceuppens

@joestringer  Fixes: #3799

I added a flag "--file-per-command" which generates a single file for each command,
and restructured the code to make it more readable

Single file:
```
$ cilium debuginfo -f debug.md
Warning, some of the BPF commands might fail when run as not root
Markdown output at debug.md
```
Multiple files:
```
$ cilium debuginfo -f debug.md --file-per-command
Warning, some of the BPF commands might fail when run as not root
Markdown output at debug-cilium-status.md
Markdown output at debug-cilium-endpoint-list.md
Markdown output at debug-cilium-service-list.md
Markdown output at debug-cilium-policy.md
Markdown output at debug-cilium-memory-map.md
Markdown output at debug-cilium-version.md
Markdown output at debug-kernel-version.md
Markdown output at debug-cilium-environment-keys.md
```
With multiple files, i insert the command name between the file-name and file-extension

2018-05-28 10:17 UTC, tgraf commented
test-me-please

2018-05-28 11:13 UTC, raybejjani requested changes
A few small things but this is excellent  :) Thank you!

2018-05-28 11:13 UTC, raybejjani commented on cilium/cmd/debuginfo.go
> +	{
Are these blocks purely for scoping? I didn't realise Go allows for that (I've done it in C). In any case, since we aren't declaring any new variables, and the special case is bounded with an if I'd prefer to avoid this style. It would be the only place in the codebase to have it.

2018-05-28 11:13 UTC, raybejjani commented on cilium/cmd/debuginfo.go
> +type addSection = func(*tabwriter.Writer, *models.DebugInfo)
Is there a reason to have this type alias? we only use it one place (the sections map) and it doesn't make the enforcement any more effective. Were you expecting to pass it somewhere as a parameter type?
It was a little confusing to see the map at the top use this type, but not see the type itself. While it makes sense to have it near these functions, I feel that putting it near the map makes the map easier to understand, while these functions are a little more self-explanatory.

2018-05-28 11:13 UTC, raybejjani commented on cilium/cmd/debuginfo.go
> +	if len(suffix) > 0 {
This could be inverted to become an early return on `len(suffix) == 0`. Purely a style thing, however, so it isn't important.

2018-05-28 11:13 UTC, raybejjani commented on cilium/cmd/debuginfo.go
> +func writeToOutput(buf bytes.Buffer, suffix string) {
It would be nice to make `file` and `html` parameters here but that might be out of scope of this PR (even better would be to make this switch part of startup and just pass an `io.Writer`  down the callstack but that's even more out of scope).

Alternatively, could you document the dependence on the global variables?

2018-05-28 11:14 UTC, raybejjani commented
test-me-please

2018-05-28 12:25 UTC, stevenceuppens commented on cilium/cmd/debuginfo.go
> +	{
@raybejjani i add those sometimes in my code to improve readability of sections, i removed them

2018-05-28 12:26 UTC, stevenceuppens commented on cilium/cmd/debuginfo.go
> +type addSection = func(*tabwriter.Writer, *models.DebugInfo)
Moved the type definition to the top, i use the typedef to store all the generator functions in the map, do you have a better approach/proposal?

2018-05-28 12:26 UTC, stevenceuppens commented on cilium/cmd/debuginfo.go
> +	if len(suffix) > 0 {
updated

2018-05-28 12:26 UTC, stevenceuppens commented on cilium/cmd/debuginfo.go
> +func writeToOutput(buf bytes.Buffer, suffix string) {
i reworked it, so that writeToOutput does not use global vars.
Do you more like this approach?

2018-05-29 07:01 UTC, stevenceuppens commented
@raybejjani can you review again

2018-05-29 07:39 UTC, tgraf commented
test-me-please

2018-05-29 09:30 UTC, raybejjani commented on cilium/cmd/debuginfo.go
> +	STDOUT outputType = 0 + iota
I think `iota` resets to 0 in each const block. Is the `0` just to make it clear we're starting at 0?

2018-05-29 09:30 UTC, raybejjani commented on cilium/cmd/debuginfo.go
> +	{
Thanks. Ultimately, I was worried that this one instance of this style would be more confusing because it isn't used anywhere else.

2018-05-29 09:31 UTC, raybejjani commented on cilium/cmd/debuginfo.go
> +type addSection = func(*tabwriter.Writer, *models.DebugInfo)
Oh, I just meant that we could declare the map with the function type directly: `var sections = map[string]func(*tabwriter.Writer, *models.DebugInfo) {`. The counterargument to what I said is that it's harder to read than one line. Placing the type just above is solves that problem and keeps it simple, so what you did is perfect.

2018-05-29 09:31 UTC, raybejjani commented on cilium/cmd/debuginfo.go
> +func writeToOutput(buf bytes.Buffer, suffix string) {
Yes! Thank you!

2018-05-29 09:32 UTC, raybejjani approved these changes
thanks for making the changes :)

2018-05-29 09:33 UTC, merged