RFC: Istio e2e testing
cilium/cilium pull request #4266
Opened 2018-05-28 17:58 UTC by eloycoto

Hi,

This is an RFC pull request to automate the work in Istio e2e testing. The
current is an example of how to run Istio testing on top of Cilium.

I think that the following topics need to be tested:
- [ ] Configure a request routing with a single and multiple pods.
- [ ] Traffic Shifting with different pods (Httpd1, Httpd2)
- [ ] Request timeouts
- [ ] Mirroring
- [ ] Egress traffic.
- [ ] Rate limits
- [ ] TLS.

I find quite difficult to test these scenarios with the current `demo.yaml`, on
the other hand, I think that using Bookinfo application is not a good idea
either.

My proposal is to write a small HTTPd service, where we can get the number of
requests processed, the hostname of destination pod, where we can have
timeouts, etc.. That allows us to validate that the rate-limits works, the
traffic shifting with a real numbers, tcp timeouts, etc..  The httpd service
that I propose is something like this:

```go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"time"
)

var request = 0

func SimpleHandler(w http.ResponseWriter, r *http.Request) {
	request++
	hostname, _ := os.Hostname()

	var result = map[string]string{
		"request":  fmt.Sprintf("%d", request),
		"hostname": hostname,
	}
	b, err := json.Marshal(result)
	if err != nil {
		fmt.Fprintf(w, "Error: %s", err)
		w.WriteHeader(http.StatusInternalServerError)
		return
	}
	fmt.Fprintf(w, "%s", b) 
        return
}

func ResetHandler(w http.ResponseWriter, r *http.Request) {
	request = 0
	return
}

func TimeoutHandler(w http.ResponseWriter, r *http.Request) {
	time.Sleep(10 * time.Second)
	return
}

func main() {
	http.HandleFunc("/", SimpleHandler)
	http.HandleFunc("/reset", ResetHandler)
	http.HandleFunc("/timeout", TimeoutHandler)

	err := http.ListenAndServe(":9090", nil)
	if err != nil {
		log.Fatal("ListenAndServe: ", err)
	}
}
```

With the following service, we can use good asserts that bookinfo do not allow
at all and test will be simpler.

The test from my POV will be:

- It("Request routing all to HTTPD1") #validate the requests number and hostname.
- It("Traffic shaping 50% to httpd[1|2]") # where requests output are in use.
- It("Test timeout requests works on httpd1") # use timeout/ target.
- It("Rate limit number of requests")

If you want to use Bookinfo manifest I'm happy with that, but I think that it's
not the right application to run these e2e.

Waiting for your feedback.

PS: The way of how Cillium is installed will change as soon the #4219 is
merged.

2018-05-29 12:58 UTC, aanm commented
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/k8sT/Istio.go, line 35 at r2](https://reviewable.io/reviews/cilium/cilium/4266#-LDfwFQI047EbiISdnyb:-LDfwFQI047EbiISdnyc:b8u5d7p) ([raw file](https://github.com/cilium/cilium/blob/22ced51813bd06d187ca2f93aa95a8ffa5c2d6e1/test/k8sT/Istio.go#L35)):*
> ```Go
> 		microscopeCancel func() error
> 		ciliumPodK8s1    string
> 		ciliumFilter     string = "-l k8s-app=cilium"
> ```

Can we have this as a constant somewhere? I've been seen this string multiple times.

---

*[test/k8sT/manifests/demo_big.yaml, line 1 at r2](https://reviewable.io/reviews/cilium/cilium/4266#-LDfxcXH6xnrbkReYqw9:-LDfxcXH6xnrbkReYqwA:b-6h9kb8) ([raw file](https://github.com/cilium/cilium/blob/22ced51813bd06d187ca2f93aa95a8ffa5c2d6e1/test/k8sT/manifests/demo_big.yaml#L1)):*
> ```YAML
> ---
> ```

Please use a proper name file, it's really vague.

---

*[test/k8sT/manifests/istio-auth.yaml, line 1 at r2](https://reviewable.io/reviews/cilium/cilium/4266#-LDfxwJSBtZwP6B7ZiJq:-LDfxwJSBtZwP6B7ZiJr:blzztat) ([raw file](https://github.com/cilium/cilium/blob/22ced51813bd06d187ca2f93aa95a8ffa5c2d6e1/test/k8sT/manifests/istio-auth.yaml#L1)):*
> ```YAML
> apiVersion: v1
> ```

Where did this file came from? It would be useful to know if we need to upgrade it afterwards.

---

*[test/provision/k8s_install.sh, line 153 at r2](https://reviewable.io/reviews/cilium/cilium/4266#-LDfyNVYBlp-an-pdJpr:-LDfyNVYBlp-an-pdJps:b-lwwqps) ([raw file](https://github.com/cilium/cilium/blob/22ced51813bd06d187ca2f93aa95a8ffa5c2d6e1/test/provision/k8s_install.sh#L153)):*
> ```Shell
> 
> sudo mkdir -p /etc/certs
> sudo chmod 777 /etc/certs
> ```

why `777` and not `755`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cilium/cilium/4266)*
<!-- Sent from Reviewable.io -->

2018-06-12 22:38 UTC, ianvernon commented
@eloycoto what is the timeline for review on this? Also, please rebase as there is a merge conflict.

2018-06-12 22:39 UTC, ianvernon commented
> I find quite difficult to test these scenarios with the current demo.yaml, on
the other hand, I think that using Bookinfo application is not a good idea
either.

Please provide reasoning here. Why do you think that it is difficult to test these scenarios with the current `demo.yaml`, and why is the use of Bookinfo "not a good idea"?

2018-06-12 22:41 UTC, ianvernon commented on test/k8sT/Istio.go
> +// Copyright 2017 Authors of Cilium
The commit message for this is way too brief. In the final version, please be sure to detail what the test framework does, including topology of the setup, tests that have been added along with brief descriptions of what they do, etc.

2018-06-12 22:48 UTC, ianvernon requested changes

2018-06-12 22:48 UTC, ianvernon commented on test/k8sT/Istio.go
> +// Copyright 2017 Authors of Cilium
Copyright 2018

2018-06-12 22:48 UTC, ianvernon commented on test/k8sT/Istio.go
> +var _ = Describe("K8sValidatedIstioTest", func() {
Why are we using `K8sValidated` for `Istio`? Wouldn't it be better to have a separate suite for Istio?

2018-06-12 22:48 UTC, ianvernon commented on test/k8sT/Istio.go
> +var _ = Describe("K8sValidatedIstioTest", func() {
If you're going to use the same string on line 49, set a constant and use this in the `Describe` and in line 49 as well.

2018-06-12 22:48 UTC, ianvernon commented on test/k8sT/Istio.go
> +		_ = kubectl.Exec(fmt.Sprintf(
Why does Cilium need to be deleted here? Add comments to indicate why this is occurring.

2018-06-12 22:48 UTC, ianvernon commented on test/k8sT/Istio.go
> +		Expect(err).Should(BeNil(), "Cannot get cilium pod on k8s1")
Use `helpers.K8s1` instead of hardcoded string.

2018-06-12 22:48 UTC, ianvernon commented on test/k8sT/Istio.go
> +	kubeInject := func(fileName string, command string) *helpers.CmdRes {
Sync up with @rlenglet about how to install Istio; it may be much simpler since we use Helm in the Istio GSG now.

2018-06-12 22:48 UTC, ianvernon commented on test/k8sT/Istio.go
> +		kubectl.ExecWithSudo("rm -rf /ust/local/istio")
Typo in path. Please be more careful with typos.

2018-06-12 22:48 UTC, ianvernon commented on test/k8sT/Istio.go
> +	Context("With Basic Application", func() {
What is a 'Basic Application' and a 'Basic Connectivity Test'? I understand that the description of a Context / It is brief in nature, but this provides no added value to indicate what is actually being tested here. A brief comment would be helpful indicating what exactly is being tested here, or better yet, indicate what type of datapath traffic is being tested, etc.

2018-06-12 22:48 UTC, ianvernon commented on test/k8sT/Istio.go
> +			res.ExpectSuccess("cannot install demo: %s", res.CombineOutput())
install?

2018-06-13 14:28 UTC, eloycoto commented
Please, review my first comment, this PR is a RFC.

2018-06-20 12:44 UTC, closed without merging