Test: Policy namespaces fixes
cilium/cilium pull request #4304
Opened 2018-05-31 14:02 UTC by eloycoto

- Move `Tests the same Policy in the different namespaces` into a new   
 context "Namespaces Policies"                                           
 - `Tests the same Policy in the different namespaces"                   
     - Moved to the namespace context.                                   
     - Use custom demo application instead of pods.                      
     - Move to `kubectl exec` instead of API pod creation that was       
     difficult to debug.                                                 

Related to #4292

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

2018-05-31 14:02 UTC, eloycoto commented
test-me-please

2018-05-31 15:38 UTC, eloycoto commented
test-me-please

2018-05-31 19:01 UTC, ianvernon requested changes
Please address my comments. In the future, when adding tests to the CI, I would like to have the following to make it easier to be reviewed:]

* Describe the test topology in the commit. 
* Describe how policy is being enforced: what exactly is the test covering w.r.t. policy enforcement?
* Is there positive/negative testing being done w.r.t. the policy?

It would be even better if these comments were added inline to make the code more readable. I want to have this approach for policy-related tests.

EDIT: one additional comment I have is that the PR title is vague. What exactly is being fixed? It seems to be more of a refactoring to me. While this didn't impact my ability to review, it would be helpful in the future to have titles that are more evocative of what the PR is doing than the generic "fixes".

2018-05-31 19:01 UTC, ianvernon commented on test/k8sT/Policies.go
> +			res.ExpectSuccess("unable to apply manifest %s")
there is no corresponding string to `%s`

2018-05-31 19:01 UTC, ianvernon commented on test/k8sT/Policies.go
> +			res.ExpectSuccess("unable to apply manifest %s")
there is no corresponding string to `%s`

2018-05-31 19:01 UTC, ianvernon commented on test/k8sT/Policies.go
> +			Expect(err).Should(BeNil(), "cannot get CiliumPod")
"cannot get CiliumPod on node %s", helpers.K8s1

2018-05-31 19:01 UTC, ianvernon commented on test/k8sT/Policies.go
> +			Expect(err).To(BeNil(), "testapp pods are not ready after timeout")
Since we wait for testapp pods to be ready in separate namespaces, include the namespace in the error message.

2018-05-31 19:01 UTC, ianvernon commented on test/k8sT/Policies.go
> +			Expect(err).To(BeNil(), "testapp pods are not ready after timeout")
Since we wait for testapp pods to be ready in separate namespaces, include the namespace in the error message.

2018-05-31 19:01 UTC, ianvernon commented on test/k8sT/Policies.go
> +		It("Tests the same Policy in the different namespaces", func() {
same policy in different namespaces

2018-05-31 19:01 UTC, ianvernon commented on test/k8sT/Policies.go
> +			By("Applying Policy in %q namespace", namespace)
include which policy you are applying in `By`

2018-05-31 19:01 UTC, ianvernon commented on test/k8sT/Policies.go
> +			Expect(err).Should(BeNil(), "L3 Policy cannot be applied in %q namespace", namespace)
This error message duplicates the one on line 814 - differentiate the two for easier debugging.

2018-05-31 19:01 UTC, ianvernon commented on test/k8sT/Policies.go
> +			By("Testing %q namespace", namespace)
Testing what in the namespace? Make this more specific.

2018-05-31 19:01 UTC, ianvernon commented on test/k8sT/Policies.go
> +			By("Testing default namespace")
Testing what in the namespace? Make this more specific.

2018-05-31 19:01 UTC, ianvernon commented on test/k8sT/Policies.go
> +		It("Network Policy namespace selector", func() {
This is not clear enough. What is this testing? Make the string reflect what this tests overall.

2018-05-31 19:01 UTC, ianvernon commented on test/k8sT/Policies.go
> +				res.ExpectFail("%q can curl to service and it should not. NS policy should be applied", appPods[pod])
NS policy should be applied --> policy restricts communication across namespaces (or something more specific).

2018-05-31 19:01 UTC, ianvernon commented on test/k8sT/Policies.go
> +			By("Delete policy in %q namespace", namespace)
Nit - specify which policy is being deleted

2018-05-31 19:01 UTC, ianvernon commented on test/k8sT/Policies.go
> +			namespace   = "second"
Rename this to "secondNamespace"

2018-05-31 19:01 UTC, ianvernon commented on test/k8sT/Policies.go
> +			clusterIPNS string
Rename this variable to be something like "app1SecondNSClusterIP" - the variable name in its current form is not evocative of what it actually represents, and makes the test hard to follow.

2018-05-31 19:01 UTC, ianvernon commented on test/k8sT/Policies.go
> +			policy           = fmt.Sprintf("%s -n %s", l3Policy, namespace)
Rename this variable. "policy" is quite vague. Please try to make the variable more expressive of what type of policy it represents.

2018-05-31 19:01 UTC, ianvernon commented on test/k8sT/Policies.go
> +			l3Policy         = helpers.ManifestGet("l3_l4_policy.yaml")
This variable is called l3Policy, yet the file is l3l4Policy; rename accordingly.

2018-05-31 19:01 UTC, ianvernon commented on test/helpers/kubectl.go
> -// ApplyNetworkPolicyUsingAPI applies a Kubernetes network policy using the API
<3

2018-06-01 07:16 UTC, eloycoto commented
test-me-please

2018-06-01 09:40 UTC, eloycoto commented
test-me-please

2018-06-01 12:25 UTC, eloycoto commented
test-me-please

2018-06-01 17:06 UTC, ianvernon requested changes
@eloycoto a few comments from my last review, and my requests for more in-depth descriptions of the test topology have not been addressed. 
Please do the following:

* Describe the test topology in the commit.
* Describe how policy is being enforced: what exactly is the test covering w.r.t. policy enforcement?
* Is there positive/negative testing being done w.r.t. the policy? Provide evidence of this in the PR description.

It would be even better if these comments were added inline to make the code more readable. I want to have this approach for policy-related tests so that when people look at the tests they can easily understand what is going on. See `test/runtime/Policies.go:It(L3-Dependent L7 Egress)` for this. 

I realize that I have not asked for this before this PR, but I think this will make our tests much more approachable. Let me know what you think about this.

2018-06-01 17:06 UTC, ianvernon commented on test/k8sT/Policies.go
> +				"testapp pods are not ready after timeout in namespace", helpers.DefaultNamespace)
There is no `%s` corresponding to `helpers.DefaultNamespace`

2018-06-01 17:06 UTC, ianvernon commented on test/k8sT/Policies.go
> +			By("Testing connectivity on %q namespace", namespace)
Nit: on --> in

2018-06-01 17:06 UTC, ianvernon commented on test/k8sT/Policies.go
> +			namespace         = "second"
This variable still has not been renamed despite my prior request to do so. Please address my prior comment.

2018-06-04 07:32 UTC, eloycoto commented
@ianvernon all should be ok. 

Regards

2018-06-04 08:05 UTC, eloycoto commented
test-me-please

2018-06-04 17:11 UTC, ianvernon approved these changes
LGTM, apart from one small, non-blocking typo fix needed. Does not need a request for review from me again.

2018-06-04 17:11 UTC, ianvernon commented on test/k8sT/Policies.go
> +				res.ExpectFail("%q can curl to service, policiy is not blocking"+
policiy --> policy

2018-06-05 06:03 UTC, eloycoto commented
test-me-please

2018-06-05 08:55 UTC, merged