Initial support for transparent proxy injection
cilium/cilium pull request #431
Opened 2017-03-23 18:55 UTC by tgraf

2017-03-23 18:55 UTC, aanm commented
This pull request is now managed with CodeReviewHub. <a href='https://github.com/cilium/cilium/pull/431'>Refresh</a>.<a href='#crh-update-none'></a>

2017-03-23 20:11 UTC, aanm requested changes
We only support IPv4 Proxy? Did I miss the `proxy6key` and `proxy6value`?

2017-03-23 20:11 UTC, aanm commented on daemon/main.go
> +	flags.String("access-log", "", "File to store access log in")
maybe a filepath instead of a single name?

2017-03-23 20:11 UTC, aanm commented on pkg/endpoint/policy.go
> +// Must be called with endpointsMU held
`AllowConsumer must be called with endpointsMU held`

2017-03-23 20:11 UTC, aanm commented on pkg/endpoint/policy.go
> +func (e *Endpoint) AllowConsumer(owner Owner, id policy.NumericIdentity) {
Since it must be called with `endpointsMU` held, can we set this func as private?

2017-03-23 20:11 UTC, aanm commented on pkg/endpoint/policy.go
> +	} else {
Will golint complain about the `} else {`?

Also, you can invert the if condition no?
```
if e.Opts.IsEnabled(OptionConntrack) {
    e.Consumable.AllowConsumer(cache, id)
}
e.Consumable.AllowConsumerAndReverse(cache, id)
```

2017-03-23 20:11 UTC, aanm commented on pkg/endpoint/policy.go
> +		return 0, fmt.Errorf("Can't redirect, proxy disabled")
`Can't` -> `can't`

2017-03-23 20:11 UTC, aanm commented on pkg/endpoint/policy.go
> +	id := fmt.Sprintf("%d:%s:%d", e.ID, l4.Protocol, l4.Port)
Should we have an independent function that deals with the id creation?

2017-03-23 20:11 UTC, aanm commented on pkg/endpoint/policy.go
> +	id := fmt.Sprintf("%d:%s:%d", e.ID, l4.Protocol, l4.Port)
Should we have an independent function that deals with the id creation?

2017-03-23 20:11 UTC, aanm commented on pkg/labels/labels.go
>  	AddLabelsOp     LabelOpType = "AddLabelsOp"
All of this `consts` are unused.

2017-03-23 20:11 UTC, aanm commented on pkg/policy/rule.go
> +	// Must return the consumable decision of this rule if the rule
I don't get it, is this for the `Resolve` function? The `Resolve` doesn't return a consumable decision.

2017-03-23 20:11 UTC, aanm commented on pkg/policy/rule_l4.go
> +	Redirect     string    `json:"redirect,omitempty"`
I'm lost, can you add some comments for the `Redirect` and the `RedirectPort`?

2017-03-23 20:11 UTC, aanm commented on pkg/proxy/proxy.go
> +	rangeMin       uint16
What's `rangeMin` and `rangeMax`? (I think I know) Do we support something like `[1-20, 25, 90-3000]`?

2017-03-23 20:11 UTC, aanm commented on pkg/proxy/proxy.go
> +		return nil, fmt.Errorf("Invalid remote address")
On returned errors, return sentences starting with small case.
Are you hiding the `err` on purpose?

2017-03-23 20:11 UTC, aanm commented on pkg/proxy/proxy.go
> +	newUrl := fmt.Sprintf("http://%s:%d%s", val.OrigDAddr.IP().String(), val.OrigDPort, req.URL)
what about IPv6 brackets? Use `net.JoinHostPort(val.OrigDAddr.IP(), strconv.Itoa(int(val.OrigDPort)))`

2017-03-23 20:11 UTC, aanm commented on pkg/proxy/proxy.go
> +	if colon := strings.LastIndex(ip, ":"); colon != -1 {
Are you accounting for IPv6?

2017-03-23 20:11 UTC, aanm commented on pkg/proxy/proxy.go
> +
At first sigh it seems that you can use  `defer p.mutex.Unlock()`, am I wrong?

2017-03-23 20:11 UTC, aanm commented on pkg/proxy/proxy.go
> +	return p.redirects[id]
If you return this and the caller changes the `Redirect` it would be outside the mutex, can you return a copy instead?

2017-03-23 20:11 UTC, aanm commented on pkg/proxy/proxymap.go
> +	return fmt.Sprintf("%s:%d (%d) => %d", k.SAddr.IP().String(), k.SPort, k.Nexthdr, k.DPort)
Use the `net.JoinHostPort()` as well?

2017-03-23 20:11 UTC, aanm commented on pkg/proxy/proxymap.go
> +	return fmt.Sprintf("%s:%d", v.OrigDAddr.IP().String(), v.OrigDPort)
Use the `net.JoinHostPort()` as well?

2017-03-23 20:23 UTC, tgraf commented on daemon/main.go
> +	flags.String("access-log", "", "File to store access log in")
You mean a path to a directory? I would assume that people using this would use a log rotator.

2017-03-23 20:23 UTC, tgraf commented on pkg/endpoint/policy.go
> +// Must be called with endpointsMU held
Fixed

2017-03-23 20:24 UTC, tgraf commented on pkg/endpoint/policy.go
> +func (e *Endpoint) AllowConsumer(owner Owner, id policy.NumericIdentity) {
fixed

2017-03-23 20:24 UTC, tgraf commented on pkg/endpoint/policy.go
> +	} else {
We are not runing from AllowConsumer call so I assume as-is is fine?

2017-03-23 20:25 UTC, tgraf commented on pkg/endpoint/policy.go
> +		return 0, fmt.Errorf("Can't redirect, proxy disabled")
fixed

2017-03-23 20:36 UTC, tgraf commented on pkg/endpoint/policy.go
> +	id := fmt.Sprintf("%d:%s:%d", e.ID, l4.Protocol, l4.Port)
fixed

2017-03-23 20:40 UTC, tgraf commented on pkg/endpoint/policy.go
> +	id := fmt.Sprintf("%d:%s:%d", e.ID, l4.Protocol, l4.Port)
fixed

2017-03-23 20:41 UTC, tgraf commented on pkg/labels/labels.go
>  	AddLabelsOp     LabelOpType = "AddLabelsOp"
fixed

2017-03-23 20:45 UTC, tgraf commented on pkg/policy/rule_l4.go
> +	Redirect     string    `json:"redirect,omitempty"`
fixed

2017-03-23 20:46 UTC, tgraf commented on pkg/policy/rule.go
> +	// Must return the consumable decision of this rule if the rule
Incorrect comment, fixed

2017-03-23 20:51 UTC, tgraf commented on pkg/proxy/proxy.go
> +	rangeMin       uint16
documented

2017-03-23 20:52 UTC, tgraf commented on pkg/proxy/proxy.go
> +	rangeMin       uint16
This is only the proxy port allocation which should be invisible to the user. It does not have any impact the ports we are redirecting from.

2017-03-23 20:52 UTC, tgraf commented on pkg/proxy/proxy.go
> +		return nil, fmt.Errorf("Invalid remote address")
Not on purpose, fixed

2017-03-23 20:54 UTC, tgraf commented on pkg/proxy/proxy.go
> +	if colon := strings.LastIndex(ip, ":"); colon != -1 {
This only works with IPv4 for now

2017-03-23 20:54 UTC, tgraf commented on pkg/proxy/proxy.go
> +	if colon := strings.LastIndex(ip, ":"); colon != -1 {
Fixed to use `SplitHostPort`

2017-03-23 20:57 UTC, tgraf commented on pkg/proxy/proxy.go
> +	return p.redirects[id]
This function was unused. I've just removed it

2017-03-23 20:58 UTC, tgraf commented on pkg/proxy/proxy.go
> +
Needs to unlock before starting the HTTP server

2017-03-23 20:58 UTC, tgraf commented on pkg/proxy/proxymap.go
> +	return fmt.Sprintf("%s:%d (%d) => %d", k.SAddr.IP().String(), k.SPort, k.Nexthdr, k.DPort)
fixed

2017-03-23 21:02 UTC, tgraf commented on pkg/proxy/proxymap.go
> +	return fmt.Sprintf("%s:%d", v.OrigDAddr.IP().String(), v.OrigDPort)
fixed

2017-03-24 17:10 UTC, aanm requested changes

2017-03-24 17:10 UTC, aanm commented on daemon/main.go
> +	flags.String("access-log", "", "File to store access log in")
No, a file path for to write the logs in it? Let me ask you a different question, where the `access-log` will be created? How can I access it?

2017-03-24 17:10 UTC, aanm commented on examples/demo/sw_demo.sh
> +desc_rate "The Jedi have forseen this situation and manipulated the"
foreseen

2017-03-24 17:10 UTC, aanm commented on examples/demo/sw_demo.sh
> +desc_rate "which is aware of its weaknessses."
weaknesses

2017-03-24 17:10 UTC, aanm commented on pkg/policy/rule_l4.go
> +	// Redirect port is the L7 proxy port to redirect to (optional)
`RedirectPort is a` (otherwise golint will complain)

2017-03-24 17:10 UTC, aanm commented on pkg/proxy/proxy.go
> +	newUrl := fmt.Sprintf("http://%s%s", val.HostPort(), req.URL)
The end result will be `172.0.0.1:8080cilium/clium`, isn't there a missing `/` (`"http://%s/%s"`)?

2017-03-24 17:10 UTC, aanm commented on pkg/proxy/proxy.go
> +	go func() {
You can just do `go redir.server.ListenAndServe()`

2017-03-24 17:10 UTC, aanm commented on pkg/proxy/proxymap.go
> +	return fmt.Sprintf("%s:%d", v.OrigDAddr.IP().String(), v.OrigDPort)
Where?

2017-03-24 17:31 UTC, tgraf commented on examples/demo/sw_demo.sh
> +desc_rate "which is aware of its weaknessses."
fixed

2017-03-24 17:32 UTC, tgraf commented on examples/demo/sw_demo.sh
> +desc_rate "The Jedi have forseen this situation and manipulated the"
fixed

2017-03-24 17:32 UTC, tgraf commented on pkg/policy/rule_l4.go
> +	// Redirect port is the L7 proxy port to redirect to (optional)
fixed

2017-03-24 17:33 UTC, tgraf commented on pkg/proxy/proxy.go
> +	newUrl := fmt.Sprintf("http://%s%s", val.HostPort(), req.URL)
I think we want to use `path` here
https://play.golang.org/p/F7DQfo6c8P

2017-03-24 17:33 UTC, tgraf commented on pkg/proxy/proxy.go
> +	go func() {
fixed

2017-03-24 17:38 UTC, tgraf commented on pkg/proxy/proxymap.go
> +	return fmt.Sprintf("%s:%d", v.OrigDAddr.IP().String(), v.OrigDPort)
I looked at this again and this is guaranteed to always be IPv4 so what is the point of using `JoinHostPort()`? It only required to convert the port to a string first.

2017-03-24 17:39 UTC, tgraf commented on daemon/main.go
> +	flags.String("access-log", "", "File to store access log in")
if lf := viper.GetString("access-log"); lf != "" {
                          if logFile, err = os.Create(lf); err != nil {

the value given is the path to the file. I'll change the wording of the usage string, that seems to be confusing.

2017-03-24 18:08 UTC, aanm commented on pkg/proxy/proxy.go
> +	newUrl := fmt.Sprintf("http://%s%s", val.HostPort(), req.URL)
Yep, sounds perfect

2017-03-24 18:08 UTC, aanm commented on pkg/proxy/proxymap.go
> +	return fmt.Sprintf("%s:%d", v.OrigDAddr.IP().String(), v.OrigDPort)
Ah, you're right, sounds good.

2017-03-24 18:28 UTC, mchalla commented
If traffic is between two nodes where do we install the proxy ?

2017-03-24 21:00 UTC, mchalla commented
Couple of comments inline. Rest of the bpf side changes look good to me.

2017-03-24 21:01 UTC, mchalla commented on bpf/lib/lxc.h
> +		return DROP_CT_CREATE_FAILED;
Does this need to be updated for every packet ?

2017-03-24 21:01 UTC, mchalla commented on bpf/bpf_lxc.c
> +		return redirect(HOST_IFINDEX, 0);
do we have to do skb_change_type(skb, 0) here ?

2017-03-24 21:34 UTC, borkmann commented on bpf/bpf_lxc.c
> +		return redirect(HOST_IFINDEX, 0);
Shouldn't the `redirect(HOST_IFINDEX, 0)` be a redirect to ingress and not egress when we send the pkt up the stack to the socket?

Could we add lib/host_port.h and place that as a new function there along with ipv4_redirect_to_host_port() itself?
Also ipv4_redirect_to_host_port() may be better named as ipv4_rewrite_to_host_port() as it better says what the function does (rewriting content)?

2017-03-24 21:39 UTC, borkmann commented on bpf/bpf_lxc.c
> +
PR says `Limited to IPv4 for now.`? But in any case, same as with the IPv4 case, would be great to refactor this into a separate function f.e. in lib/host_port.h or such.

2017-03-24 22:47 UTC, tgraf commented
> If traffic is between two nodes where do we install the proxy ?

The proxy runs either just before or after a payload. If the proxy is after, we currently lose the security context.

2017-03-24 23:15 UTC, tgraf commented on bpf/bpf_lxc.c
> +
The kernel side is mostly done but the proxymap is IPv4 only at this point. Aggreed on refactoring.

2017-03-25 00:52 UTC, aanm approved these changes

2017-03-25 00:56 UTC, merged