Correctly restore router IPs from cilium_host interface
cilium/cilium pull request #4327
Opened 2018-06-01 13:50 UTC by tgraf

Fixes restore from node_config.h. Requires this functionality to be disabled
for unit tests as random state can be found in development environments.

Signed-off-by: Thomas Graf <thomas@cilium.io>

2018-06-01 13:50 UTC, tgraf commented
test-me-please

2018-06-01 14:34 UTC, aanm approved these changes

2018-06-01 16:36 UTC, ianvernon requested changes
I dislike the mixture of flags that have "true" indicating disabling functionality, and other flags that have "true" indicating enabling of functionality; can you change this to "RestoreHostIP" and then flip the logic accordingly for consistency across the configuration flags? This isn't blocking because the logic seems to be correct, but I think having consistency is important w.r.t. configuration.

2018-06-02 10:29 UTC, tgraf commented
> I dislike the mixture of flags that have "true" indicating disabling functionality, and other flags that have "true" indicating enabling of functionality; can you change this to "RestoreHostIP" and then flip the logic accordingly for consistency across the configuration flags? This isn't blocking because the logic seems to be correct, but I think having consistency is important w.r.t. configuration.

I don't care too much in general but there is one property that is lost. Disable flags can make the default code flow very obvious. Of course this is fragile as defaults can change, but:

```
+       if !option.Config.DisableHostIPRestore {
+               // Read the previous cilium host IPs from node_config.h for backward
+               // compatibility
+               ipv4GW, ipv6Router := getCiliumHostIPs()
```

Makes it very clear that the code will run unless explicitly disabled

Whereas:
```
+       if option.Config.EnableHostIPRestore {
+               // Read the previous cilium host IPs from node_config.h for backward
+               // compatibility
+               ipv4GW, ipv6Router := getCiliumHostIPs()
```

Is more likely to be read: Restore the host IP if explicitly enabled. I would even choke a bit when reading this code to see that a backwards compatibility function is conditional and eventually not the default.

These things are very subjective though. I've changed it to a non disable flag and moved the default definition into the defaults package.

2018-06-02 10:31 UTC, tgraf commented
test-me-please

2018-06-02 20:04 UTC, merged