golint: reduce comment warnings
cilium/cilium pull request #435
Opened 2017-03-23 21:00 UTC by scanf

Fixes all the warnings with the following pattern

  ... comment on exported function xYZ should be of the form "xYZ ..."

Related-to: #153 (Resolve golint warnings)

Please let me know if anything should be reworded, thanks.

2017-03-23 21:00 UTC, aanm commented
This pull request is now managed with CodeReviewHub. <a href='https://github.com/cilium/cilium/pull/435'>Refresh</a>.<a href='#crh-update-none'></a>

2017-03-23 21:48 UTC, aanm requested changes
Needs minor changes, looks great

2017-03-23 21:48 UTC, aanm commented on common/addressing/ip.go
> +// NewCiliumIPv6 returns a IPv6 address or nil.
The previous sentence was regarding the requirements of `address` so you can change to:
```
NewCiliumIPv6 returns a CiliumIPv6 if the given `address` is:
- An IPv6 address
```

2017-03-23 21:48 UTC, aanm commented on common/ipam/ipam.go
>  	LibnetworkIPAMType IPAMType = "libnetwork"
On a follow up commit you can remove this
```
type IPAMType string

const (
	// CNIIPAMType
	CNIIPAMType IPAMType = "cni-host-local"
	// LibnetworkIPAMType
	LibnetworkIPAMType IPAMType = "libnetwork"
)
```
and replace this
```
	ipamConf := &ipam.IPAMConfig{
		IPAMConfig: hb.IPAMConfig{
			Name:    string(ipam.CNIIPAMType),
```
with this
```
	ipamConf := &ipam.IPAMConfig{
		IPAMConfig: hb.IPAMConfig{
			Name:    "cilium-local-IPAM",
```

2017-03-23 21:48 UTC, aanm commented on common/ipam/ipam.go
> +// ByMask sort an array of routes by mask, narrow first.
`// ByMask is used to sort an array of routes by mask, narrow first.`

2017-03-23 21:48 UTC, aanm commented on common/plugins/ipam.go
> +// ByMask sort an array of routes by mask, narrow first.
// ByMask sort an array of routes by mask, narrow first.

2017-03-23 21:48 UTC, aanm commented on common/types/ipv4.go
> +// IPv4 binary representation for encoding in binary structs.
IPv4 is the...

2017-03-23 21:48 UTC, aanm commented on common/types/ipv6.go
> +// IPv6 binary representation for encoding in binary structs.
IPv6 is...

2017-03-23 21:48 UTC, aanm commented on common/types/loadbalancer.go
> +// AddService adds service to list of loadbalancers and returns true if created.
adds **a** service...

2017-03-23 21:48 UTC, aanm commented on common/types/namespace_annotation.go
> +	// DefaultDeny deny all ingress traffic to pods in this namespace. Ingress means
// DefaultDeny denies

2017-03-23 21:48 UTC, aanm commented on common/types/namespace_annotation.go
> +// NamespaceSpec standard namespace object, modified to include a new
is the standard...

2017-03-23 21:48 UTC, aanm commented on common/types/namespace_annotation.go
> +// NamespaceIngressPolicy the configuration for ingress to pods within this
is the configuration

2017-03-23 21:48 UTC, aanm commented on common/types/namespace_annotation.go
> +// namespace.  For now, this only supports specifying an isolation policy.
`namespace.  F` 2 spaces between `.` and `F`

2017-03-23 21:48 UTC, aanm commented on pkg/bpf/perf.go
> +// PerfEventHeader matching 'struct perf_event_header in <linux/perf_event.h>.
`matches 'struct`
or
`must match 'struct`

2017-03-23 21:48 UTC, aanm commented on pkg/bpf/perf.go
> +// PerfEventSample matching 'struct perf_event_sample in kernel sources.
`matches 'struct`
or
`must match 'struct`

2017-03-23 21:48 UTC, aanm commented on pkg/bpf/perf.go
> +// PerfEventLost matching 'struct perf_event_lost in kernel sources.
`matches 'struct`
or
`must match 'struct`

2017-03-23 21:48 UTC, aanm commented on pkg/client/client.go
> +// NewDefaultClient create client with default parameters connecting to UNIX domain socket.
creates a client

2017-03-23 21:48 UTC, aanm commented on pkg/client/client.go
> +// NewClient creates a client.
"a client for the given \`host\`"

2017-03-23 21:48 UTC, aanm commented on pkg/client/config.go
> +// ConfigGet returns daemon configuration.
returns a

2017-03-23 21:48 UTC, aanm commented on pkg/client/identity.go
> +// IdentityGet returns security identity.
returns a

2017-03-23 21:48 UTC, aanm commented on pkg/client/ipam.go
> +// IPAMAllocate allocate IP address out of address family specific pool.
allocates an

2017-03-23 21:48 UTC, aanm commented on pkg/client/ipam.go
> +// IPAMAllocateIP try to allocate a particular IP address.
`try to` -> `tries to`

2017-03-23 21:48 UTC, aanm commented on pkg/client/ipam.go
> +// IPAMReleaseIP release a IP address back to the pool.
releases a

2017-03-23 21:48 UTC, aanm commented on pkg/client/policy.go
> +// PolicyPut modifies a node in the policy tree.
// PolicyPut inserts the `policyJSON` into the given `path`.

2017-03-23 21:48 UTC, aanm commented on pkg/client/service.go
> +// GetServices returns list of all services.
`returns a`

2017-03-23 21:48 UTC, aanm commented on pkg/client/service.go
> +// GetServiceID returns service by ID.
returns a

2017-03-23 21:48 UTC, aanm commented on pkg/client/service.go
> +// PutServiceID creates or updates service. Returns true if service was created.
updates a service

2017-03-23 21:48 UTC, aanm commented on pkg/client/service.go
> +// DeleteServiceID deletes service by ID.
deletes a service

2017-03-23 21:48 UTC, aanm commented on pkg/endpoint/endpoint.go
> +// PolicyMapPath returns path to policy map of endpoint.
// PolicyMapPath returns the path

2017-03-23 21:48 UTC, aanm commented on pkg/endpoint/endpoint.go
> +// Ct6MapPath returns path to IPv6 connection tracking map of endpoint.
returns the

2017-03-23 21:48 UTC, aanm commented on pkg/endpoint/endpoint.go
> +// Ct4MapPath returns path to IPv4 connection tracking map of endpoint.
returns the

2017-03-23 21:48 UTC, aanm commented on pkg/endpoint/owner.go
> +// Owner this interface defines the requirements for anybody owning policies.
`Owner is the interface`

2017-03-23 21:48 UTC, aanm commented on pkg/endpoint/policy.go
> +// Regenerate force regeneration of endpoint programs & policy.
`forces the regeneration`

2017-03-23 21:48 UTC, aanm commented on pkg/endpoint/policy.go
> +// TriggerPolicyUpdates called to indicate that a policy change is likely to
// TriggerPolicyUpdates indicates that a policy...

2017-03-23 21:48 UTC, aanm commented on pkg/labels/labels.go
> +// DeleteMarked deletes the labels which have the DeletionMark set and returns true if any.
and returns true if any was of them was deleted.

2017-03-23 21:48 UTC, aanm commented on pkg/maps/lbmap/lbmap.go
> +	// MaxSeq used by daemon for generating bpf define LB_RR_MAX_SEQ.
is used

2017-03-23 21:48 UTC, aanm commented on pkg/maps/lbmap/lbmap.go
> +// ServiceKey interface describing protocol independent key for services map.
is the interface

2017-03-23 21:48 UTC, aanm commented on pkg/maps/lbmap/lbmap.go
> +// ServiceValue interface describing protocol independent value for services map.
is the interface

2017-03-23 21:48 UTC, aanm commented on pkg/policy/consumer.go
> +// Consumer a entity that consumes a Consumable.
`is the entity`

2017-03-23 21:48 UTC, aanm commented on pkg/policy/consumer.go
> +// Consumable a entity that is being consumed by a Consumable.
`is the entity`

2017-03-23 21:48 UTC, aanm commented on pkg/policy/identity.go
> +	// MinimalNumericIdentity all IDs lesser than this value are reserved.
`MinimalNumericIdentity represents the minimal numeric identity not used for reserved purposes.`

2017-03-23 21:48 UTC, aanm commented on pkg/policy/identity.go
> +// Uint32 normalize ID for use in BPF program.
normalizes the ID

2017-03-23 21:48 UTC, aanm commented on pkg/policy/identity.go
> +// AssociateEndpoint associate endpoint with identity.
associates the endpoint with identity.

2017-03-23 21:48 UTC, aanm commented on pkg/policy/identity.go
> +// DisassociateEndpoint disassociate endpoint with identity and return true if successful.
`disassociates the endpoint`

2017-03-23 21:48 UTC, aanm commented on pkg/policy/policy.go
> +// Privilege available privileges for policy nodes to define.
// Privilege represents the privileges available to define for a policy node

2017-03-23 21:48 UTC, aanm commented on pkg/policy/rule_consumers.go
> +// RuleConsumers allow the following consumers.
// RuleConsumers allows the

2017-03-23 22:28 UTC, scanf commented on common/plugins/ipam.go
> +// ByMask sort an array of routes by mask, narrow first.
Don't see any difference in your comment with the actual diff here. What am I missing?

2017-03-23 22:46 UTC, scanf commented on pkg/labels/labels.go
> +// DeleteMarked deletes the labels which have the DeletionMark set and returns true if any.
how about `and returns true if any of them were deleted` instead?

2017-03-23 22:49 UTC, aanm commented on common/plugins/ipam.go
> +// ByMask sort an array of routes by mask, narrow first.
Sorry, I meant `// ByMask is used to sort an array of routes by mask, narrow first.`

2017-03-23 22:50 UTC, aanm commented on pkg/labels/labels.go
> +// DeleteMarked deletes the labels which have the DeletionMark set and returns true if any.
yep, absolutely

2017-03-23 23:02 UTC, scanf commented on pkg/client/client.go
> +// NewClient creates a client.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:02 UTC, scanf commented on pkg/endpoint/policy.go
> +// Regenerate force regeneration of endpoint programs & policy.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:02 UTC, scanf commented on pkg/labels/labels.go
> +// DeleteMarked deletes the labels which have the DeletionMark set and returns true if any.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:02 UTC, scanf commented on common/plugins/ipam.go
> +// ByMask sort an array of routes by mask, narrow first.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:02 UTC, scanf commented on pkg/policy/identity.go
> +// AssociateEndpoint associate endpoint with identity.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:02 UTC, scanf commented on common/types/ipv6.go
> +// IPv6 binary representation for encoding in binary structs.
:+1:<a href='#crh-update-complete'></a>

2017-03-23 23:07 UTC, scanf commented on pkg/policy/identity.go
> +// AssociateEndpoint associate endpoint with identity.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:07 UTC, scanf commented on pkg/client/client.go
> +// NewClient creates a client.
:+1:<a href='#crh-update-complete'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/maps/lbmap/lbmap.go
> +// ServiceKey interface describing protocol independent key for services map.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on common/types/namespace_annotation.go
> +// namespace.  For now, this only supports specifying an isolation policy.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on common/types/namespace_annotation.go
> +// NamespaceIngressPolicy the configuration for ingress to pods within this
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/endpoint/endpoint.go
> +// Ct6MapPath returns path to IPv6 connection tracking map of endpoint.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/client/service.go
> +// DeleteServiceID deletes service by ID.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/client/policy.go
> +// PolicyPut modifies a node in the policy tree.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/policy/identity.go
> +// Uint32 normalize ID for use in BPF program.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/policy/identity.go
> +// DisassociateEndpoint disassociate endpoint with identity and return true if successful.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/client/ipam.go
> +// IPAMAllocateIP try to allocate a particular IP address.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/client/service.go
> +// GetServiceID returns service by ID.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/bpf/perf.go
> +// PerfEventHeader matching 'struct perf_event_header in <linux/perf_event.h>.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/policy/consumer.go
> +// Consumer a entity that consumes a Consumable.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/bpf/perf.go
> +// PerfEventLost matching 'struct perf_event_lost in kernel sources.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/client/client.go
> +// NewDefaultClient create client with default parameters connecting to UNIX domain socket.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on common/ipam/ipam.go
>  	LibnetworkIPAMType IPAMType = "libnetwork"
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/maps/lbmap/lbmap.go
> +// ServiceValue interface describing protocol independent value for services map.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/policy/rule_consumers.go
> +// RuleConsumers allow the following consumers.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/endpoint/endpoint.go
> +// PolicyMapPath returns path to policy map of endpoint.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/client/service.go
> +// GetServices returns list of all services.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/policy/consumer.go
> +// Consumable a entity that is being consumed by a Consumable.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on common/ipam/ipam.go
> +// ByMask sort an array of routes by mask, narrow first.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/client/service.go
> +// PutServiceID creates or updates service. Returns true if service was created.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/endpoint/owner.go
> +// Owner this interface defines the requirements for anybody owning policies.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on common/types/namespace_annotation.go
> +// NamespaceSpec standard namespace object, modified to include a new
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/endpoint/policy.go
> +// TriggerPolicyUpdates called to indicate that a policy change is likely to
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/policy/identity.go
> +	// MinimalNumericIdentity all IDs lesser than this value are reserved.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/client/ipam.go
> +// IPAMAllocate allocate IP address out of address family specific pool.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/endpoint/endpoint.go
> +// Ct4MapPath returns path to IPv4 connection tracking map of endpoint.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on common/addressing/ip.go
> +// NewCiliumIPv6 returns a IPv6 address or nil.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/policy/policy.go
> +// Privilege available privileges for policy nodes to define.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/bpf/perf.go
> +// PerfEventSample matching 'struct perf_event_sample in kernel sources.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on common/types/ipv4.go
> +// IPv4 binary representation for encoding in binary structs.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/maps/lbmap/lbmap.go
> +	// MaxSeq used by daemon for generating bpf define LB_RR_MAX_SEQ.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on pkg/client/ipam.go
> +// IPAMReleaseIP release a IP address back to the pool.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on common/types/loadbalancer.go
> +// AddService adds service to list of loadbalancers and returns true if created.
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:09 UTC, scanf commented on common/types/namespace_annotation.go
> +	// DefaultDeny deny all ingress traffic to pods in this namespace. Ingress means
:+1:<a href='#crh-update-none'></a>

2017-03-23 23:14 UTC, aalemayhu commented
@aanm thanks for your extensive review.

Sorry for the noise, was just trying to mark the check boxes as completed but Github did not like it.

```
Internal Server Error

The server has either erred or is incapable of performing the requested operation.

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~github-review/1.398884974638749925/pages/pull.py", line 150, in post
    wait_for = self.markAsCompleted(code_review)
  File "/base/data/home/apps/s~github-review/1.398884974638749925/pages/pull.py", line 78, in markAsCompleted
    self.pull.create_review_comment(add, commit, path, position)
  File "/base/data/home/apps/s~github-review/1.398884974638749925/github/PullRequest.py", line 351, in create_review_comment
    input=post_parameters
  File "/base/data/home/apps/s~github-review/1.398884974638749925/github/Requester.py", line 168, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/base/data/home/apps/s~github-review/1.398884974638749925/github/Requester.py", line 176, in __check
    raise self.__createException(status, output)
GithubException: 403 {u'documentation_url': u'https://developer.github.com/v3#abuse-rate-limits', u'message': u'You have triggered an abuse detection mechanism and have been temporarily blocked from content creation. Please retry your request again later.'}
```

2017-03-24 03:38 UTC, tgraf approved these changes

2017-03-24 04:04 UTC, aanm approved these changes

2017-03-24 04:05 UTC, merged