Test: Refactor CiliumEndpointWait
cilium/cilium pull request #4355
Opened 2018-06-04 15:16 UTC by eloycoto

Refactor CiliumEndpointWait to CiliumEndpointWaitReady and avoid to use
CiliumPod per each call. Use of separate functions has been inefficient
now that we have CEP resource, the idea is to avoid the use of
CiliumPodk8s1 and CiliumPodk8s2 in the test.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

2018-06-04 15:17 UTC, eloycoto commented
test-me-please

2018-06-04 16:42 UTC, eloycoto commented
test-me-please

2018-06-04 16:47 UTC, ianvernon requested changes
Great change overall, as I think waiting for endpoints on all nodes to be ready is a good step to not have to make the helpers dependent upon the # of nodes provisioned in the tests themselves.

2018-06-04 16:47 UTC, ianvernon commented on test/helpers/kubectl.go
> +// pod are ready. Returns an error if cannot get the cilium pods, or the
"pods pod are ready" --> "pod are ready"
"Returns an error if the Cilium pods cannot be retrieved via Kubernetes, or endpoints are not ready after a specified timeout"

2018-06-04 16:47 UTC, ianvernon commented on test/helpers/kubectl.go
> +				kub.logger.WithError(err).Errorf("cannot get endpoints state on pod '%s'", pod)
endpoints state --> endpoint states

2018-06-04 16:47 UTC, ianvernon commented on test/helpers/kubectl.go
> +				if len(vals) != 2 {
Add a comment in the code which explains what the desired output looks like (i.e., add an example).

2018-06-04 16:54 UTC, eloycoto commented
test-me-please

2018-06-04 17:48 UTC, ianvernon approved these changes

2018-06-04 17:48 UTC, ianvernon commented
test-me-please

2018-06-05 06:04 UTC, eloycoto commented
Namespace flake, fixed on https://github.com/cilium/cilium/pull/4304
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3800/testReport/

2018-06-05 06:04 UTC, eloycoto commented
test-me-please

2018-06-05 07:57 UTC, eloycoto commented
test-me-please

2018-06-05 08:57 UTC, eloycoto commented
test-me-please

2018-06-05 13:02 UTC, merged