pkg/endpoint: Keep BPF object files if compilation is skipped.
cilium/cilium pull request #4372
Opened 2018-06-05 15:48 UTC by aanm

Since we optmized the BPF compilation by skipping it if the lxc_header.h
was not different, we still need to keep the object files from the
previous successful build.

Fixes: a5d98cc5eb01 ("endpoint: Skip BPF compilation if headerfile is unchanged")
Signed-off-by: André Martins <andre@cilium.io>

2018-06-05 15:49 UTC, aanm commented
Oh, actually it doesn't need to be backported since this was only introduced in `1.1`, :confetti_ball:

2018-06-05 15:49 UTC, aanm commented
test-me-please

2018-06-05 15:59 UTC, ianvernon requested changes

2018-06-05 15:59 UTC, ianvernon commented on common/utils.go
> +func MoveNewFilesTo(oldDir, newDir string) error {
Please add tests for this.

2018-06-05 15:59 UTC, ianvernon commented on pkg/endpoint/policy.go
> +			log.WithError(err).Debugf("Unable to copy old bpf object "+
Warning instead of Debug?

2018-06-05 16:25 UTC, aanm commented on common/utils.go
> +func MoveNewFilesTo(oldDir, newDir string) error {
Done

2018-06-05 16:25 UTC, aanm commented on pkg/endpoint/policy.go
> +			log.WithError(err).Debugf("Unable to copy old bpf object "+
The user can't do anything if it is a warning so let's keep it as a debug. The object files are only kept for debug purposes.

2018-06-05 16:26 UTC, aanm commented
test-me-please

2018-06-06 00:00 UTC, ianvernon commented on pkg/endpoint/policy.go
> +			log.WithError(err).Debugf("Unable to copy old bpf object "+
Makes sense.

2018-06-06 00:00 UTC, ianvernon approved these changes

2018-06-06 00:00 UTC, merged

2018-06-06 09:38 UTC, raybejjani commented
Wouldn't it have been more correct to not move the _next (and make a _stale) directory in this case? To make it seem like nothing changed, we added more logic, instead of just not doing the thing right above it.
I doubt it matters, but are we sure that the .h file is actually the same? One reason to do what we did here is to retain a newer lcx_config.h file with a newer copy of the serialised endpoint so we can restore it correctly. I don't know if we include the comments in the hash.