V1.0 backports 18 06 06
cilium/cilium pull request #4410
Opened 2018-06-07 17:45 UTC by jrfastab

**Summary of changes**:

**Backports targeting branch v1.0 for eventual release v1.4.**
PR: 4365 -- daemon: Delete old ID mapping when updating the IP for a reserved ID
PR: 4340 -- Add k8s label source in GetPolicyLabels
PR: 4306 -- identity: Resolve unknown identity to label reserved:unknown
PR: 4294 -- identity: Ignore nil identity when generating IdentityCache
PR: 4250 -- Add "docker info" output to bugtool
PR: 4247 -- init.sh: Use 'ip route replace' instead of 'ip route add'
PR: 4240 -- pkg/endpoint: include node headerfile hash
PR: 4239 -- policy: always regenerate if policy forcibly computed
PR: 4239 -- policy: always regenerate if policy forcibly computed
PR: 4230 -- cilium status: fix --brief to print less when cilium isn't running
PR: 4218 -- test: download exact k8s version of k8s upstream e2e
PR: 4214 -- bpf: Only create veth pair if it does not already exist.
PR: 4205 -- test: update k8s versions to 1.7.15, 1.8.13, 1.9.8, 1.10.3 and 1.11.0-beta.0

**PRs that were not backported despite tags in 'PR' list. I believe these are needed in v1.1 _not_ v1.0:**
PR: 4167 -- ipcache: Create copies of NPHDS cache resources when updating
PR: 3968 -- docs: Update Istio GSG to Istio 0.8.0 pre-release

**This PR was reverted and we are waiting for the revised PR to be accepted:**
PR: 3786 -- pkg/bpf: Use the other directory when /sys/fs/bpf is not BPFFS

2018-06-07 17:46 UTC, jrfastab commented
@ianvernon: Please review carefully `PR: 4240 -- pkg/endpoint: include node headerfile hash` required numerous merge conflict resolution. Note I also pulled in this dependency, `PR: 4240 -- pkg/endpoint: include node headerfile hash`

2018-06-07 17:50 UTC, jrfastab commented
@aanm with regards to commit,

```
commit 7baa81ab1aedd1c426e6b3b4ee8d0f78850f6c70
Author: André Martins <andre@cilium.io>
Date:   Wed May 23 12:39:16 2018 +0200

    test: download exact k8s version of k8s upstream e2e
```
the file `./test/kubernetes-test.sh` was not part of the v1.0 branch. I've added it here, let me know if its more appropriate to drop the file.

2018-06-07 20:49 UTC, tgraf commented
test-me-please

2018-06-07 23:16 UTC, tgraf commented
test-me-please

2018-06-08 01:02 UTC, ianvernon commented on pkg/endpoint/bpf.go
> +	nodeConfigPath := "./globals/node_config.h"
I just realized that this has to be changed to be an absolute path - you will need to pass `Owner` to this function and then call `owner.GetStateDir()` to get `nodeConfigPath` to be at the correct path. Sorry about that :(

2018-06-08 01:04 UTC, ianvernon commented on pkg/endpoint/bpf.go
> +	nodeConfigPath := "./globals/node_config.h"
Actually, if https://github.com/cilium/cilium/pull/4410/commits/f7e4adf68ec0718962a8f4c3fb0782fe2c739ff3 was a backport as well to 1.0 (i.e., we are not hashing the headerfiles in 1.0), then we do not need to backport this commit either to 1.0, only 1.1. I believe you can revert these two commits. The hashing of the headerfile was an optimization, and this commit  ( https://github.com/cilium/cilium/pull/4410/commits/58a38a5523df35a8aa09a72a6de2350b07cffa0d ) is a fix for that commit which you also had to backport. cc: @rlenglet to confirm I am correct. Sorry about all of the confusion.

2018-06-08 01:05 UTC, ianvernon requested changes
Please see my comments inline about backporting the headerfile changes. I think the fix I made needs to be backported to the 1.1 branch, not 1.0.

2018-06-08 02:03 UTC, jrfastab commented
test-me-please

2018-06-08 04:21 UTC, jrfastab commented
test-me-please

2018-06-08 04:37 UTC, ianvernon approved these changes
Thanks for fixing so quickly, and my apologies again for leading you astray with the headerfile commits!

2018-06-08 05:27 UTC, jrfastab commented
@ianvernon hmm got a test failure (or maybe just a flake) with the changes, I'm going to try and get a good build with those two popped off first. May add them back after I get a good build.

2018-06-08 06:26 UTC, jrfastab commented
test-me-please

2018-06-08 16:20 UTC, aanm approved these changes

2018-06-08 16:23 UTC, jrfastab commented
test-me-please

2018-06-08 19:03 UTC, jrfastab commented
test-me-please

2018-06-08 20:36 UTC, jrfastab commented
test-me-please

2018-06-08 22:17 UTC, merged