Test: CiliumEndpointsWaitReady ensure policy is latest
cilium/cilium pull request #4530
Opened 2018-06-15 12:52 UTC by eloycoto

To avoid weird collisions ensure that the endpoints on Wait until Ready
are all in the latest policy revision.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

2018-06-15 12:53 UTC, eloycoto commented
test-me-please

2018-06-18 09:57 UTC, tgraf commented
Why is this necessary? Can you provide an example of a weird collision?

2018-06-18 10:14 UTC, eloycoto commented
Hi, 

The main reason for this change is to make sure that all endpoints are in `ready` state and in the latest `policy`. Is to make sure that each time that WaitUntilReady no policy is pending to be applied but the status is ready. 

I saw a few weird logs last week with the upgrade test, so the change in this function is to make sure that the logging/triage is easy. 

Regards

2018-06-18 15:23 UTC, tgraf commented
> The main reason for this change is to make sure that all endpoints are in ready state and in the latest policy. Is to make sure that each time that WaitUntilReady no policy is pending to be applied but the status is ready.
> 
> I saw a few weird logs last week with the upgrade test, so the change in this function is to make sure that the logging/triage is easy.

OK, thanks for the explanation. Thinking about this some more. What seems possible here is that while the restore functionality ensures that we re-generate the endpoints, it may do so with incomplete policy view as k8s is still pushing policy events down. This means that the endpoint restore function will regenerate with incomplete whitelists.

If that is correct, then what you propose here is not a real fix either as the "latest" policy revision may not reflect the actual latest k8s policies as imported before the restart.

In order to improve this, we may have to retrieve all NP and CNP in a blocking matter before restoring any endpoints to guarantee that all endpoints being restored have at least the same privileges as before the restart after the first regeneration.

2018-06-19 00:07 UTC, tgraf requested changes
I think this check will be incomplete. As discussed in the weekly meeting. We should fetch the policy completely before attempting to regenerate any endpoints or serve the API.

2018-06-20 12:45 UTC, closed without merging