Test: Refactor health test
cilium/cilium pull request #4661
Opened 2018-06-27 09:57 UTC by eloycoto

On `healthTest` the use of `jq` command didn't show the full json output,
and it was hard to know the status. Move the execution to use
`cmdRes.Filter` so the health data will be dumped into `test-output.log`

The current output/log that we have is the following:

```
/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
Expected
    <string>: "Connection timed out"

to contain substring
    <string>: null
/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/k8sT/Health.go:109
```

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

The output of the jsonpath: 

```
vagrant@k8s1:~$ kubectl -n kube-system exec -ti cilium-lpqg4 -- cilium-health status -o jsonpath='{.nodes[1].endpoint.http.status}'
Connection timed out
vagrant@k8s1:~$ kubectl -n kube-system exec -ti cilium-lpqg4 -- cilium-health status -o jsonpath='{.nodes[1].host.primary-address.icmp.status}'
Connection timed out
vagrant@k8s1:~$
```

2018-06-27 09:57 UTC, eloycoto commented
test-me-please

2018-06-27 15:44 UTC, ianvernon approved these changes

2018-06-28 07:02 UTC, tgraf requested changes

2018-06-28 07:02 UTC, tgraf commented on test/k8sT/Health.go
> +			healthCmd := fmt.Sprintf("cilium-health status -o json")
Sprintf is unnecessary

2018-06-28 08:33 UTC, eloycoto commented
test-me-please

2018-06-28 08:33 UTC, eloycoto commented on test/k8sT/Health.go
> +			healthCmd := fmt.Sprintf("cilium-health status -o json")
fixed.

2018-06-28 09:36 UTC, tgraf approved these changes

2018-06-28 20:31 UTC, merged