Test: Upgrade test, delete kube-dns pods before install.
cilium/cilium pull request #4675
Opened 2018-06-28 12:29 UTC by eloycoto

Delete Kube-dns pods before cilium 1.0 is installed. This is because if
not cilium 1.0 try to restore pods from 1.1 and maybe it fails.

Related #4329

2018-06-28 12:38 UTC, aanm approved these changes

2018-06-28 12:38 UTC, aanm commented
test-me-please

2018-06-29 06:36 UTC, eloycoto commented
@aanm it does not matter if the kube-dns is deleted before the install: 

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/432/testReport/junit/k8s-1/8/K8sValidatedUpdates_Updating_Cilium_stable_to_master/
[f0c5341e_K8sValidatedUpdates_Updating_Cilium_stable_to_master(6).zip](https://github.com/cilium/cilium/files/2148010/f0c5341e_K8sValidatedUpdates_Updating_Cilium_stable_to_master.6.zip)

```
Stacktrace

/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
DNS entry is not ready after timeout
Expected
    <*errors.errorString | 0xc4202aa3a0>: {
        s: "Timeout reached: DNS \"app1-service.default.svc.cluster.local\" is not ready after timeout",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/src/github.com/cilium/cilium/test/k8sT/Updates.go:122

Standard Output

STEP: Checking that installed image is "cilium/cilium:v1.0.0"
STEP: Installing kube-dns
STEP: Creating some endpoints and L7 policy
=== Test Finished at 2018-06-28T14:29:44Z====
===================== TEST FAILED =====================
cmd: kubectl get pods -o wide --all-namespaces
NAMESPACE     NAME                               READY     STATUS    RESTARTS   AGE       IP              NODE
default       app1-7796cc66f4-qm72s              1/1       Running   0          8m        10.10.0.32      k8s1
default       app1-7796cc66f4-rdkvz              1/1       Running   0          8m        10.10.0.59      k8s1
default       app2-7dbb458fcc-qgrgn              1/1       Running   0          8m        10.10.0.66      k8s1
default       app3-787bfc6d9f-26qv4              1/1       Running   0          8m        10.10.0.142     k8s1
kube-system   cilium-8kd5l                       1/1       Running   0          9m        192.168.36.12   k8s2
kube-system   cilium-fcsxh                       1/1       Running   0          9m        192.168.36.11   k8s1
kube-system   etcd-k8s1                          1/1       Running   0          44m       192.168.36.11   k8s1
kube-system   kube-apiserver-k8s1                1/1       Running   0          43m       192.168.36.11   k8s1
kube-system   kube-controller-manager-k8s1       1/1       Running   0          43m       192.168.36.11   k8s1
kube-system   kube-dns-6f4c8dbcd4-2fw62          3/3       Running   0          8m        10.10.1.66      k8s2
kube-system   kube-proxy-44b72                   1/1       Running   0          37m       192.168.36.12   k8s2
kube-system   kube-proxy-fqxsx                   1/1       Running   0          44m       192.168.36.11   k8s1
kube-system   kube-scheduler-k8s1                1/1       Running   0          43m       192.168.36.11   k8s1
prometheus    prometheus-core-5c9fbf5cc6-xdxg2   1/1       Running   0          37m       10.10.0.134     k8s1

cmd: kubectl exec -n kube-system cilium-8kd5l -- cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                   IPv6                   IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                     
173        Disabled           Disabled          55437      k8s:io.kubernetes.pod.namespace=kube-system   f00d::a0a:100:0:ad     10.10.1.66    ready   
                                                           k8s:k8s-app=kube-dns                                                                       
29898      Disabled           Disabled          56968      reserved:health                               f00d::a0a:100:0:74ca   10.10.1.172   ready   

cmd: kubectl exec -n kube-system cilium-fcsxh -- cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                  IPv6                 IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                  
173        Disabled           Disabled          63759      k8s:id=app2                                  f00d::a0a:0:0:ad     10.10.0.66    ready   
                                                           k8s:io.kubernetes.pod.namespace=default                                                 
                                                           k8s:zgroup=testapp                                                                      
13949      Enabled            Disabled          59960      k8s:id=app1                                  f00d::a0a:0:0:367d   10.10.0.32    ready   
                                                           k8s:io.kubernetes.pod.namespace=default                                                 
                                                           k8s:zgroup=testapp                                                                      
27131      Disabled           Disabled          53004      k8s:app=prometheus                           f00d::a0a:0:0:69fb   10.10.0.134   ready   
                                                           k8s:component=core                                                                      
                                                           k8s:io.kubernetes.pod.namespace=prometheus                                              
29381      Enabled            Disabled          59960      k8s:id=app1                                  f00d::a0a:0:0:72c5   10.10.0.59    ready   
                                                           k8s:io.kubernetes.pod.namespace=default                                                 
                                                           k8s:zgroup=testapp                                                                      
29898      Disabled           Disabled          56968      reserved:health                              f00d::a0a:0:0:74ca   10.10.0.172   ready   
48896      Disabled           Disabled          64198      k8s:id=app3                                  f00d::a0a:0:0:bf00   10.10.0.142   ready   
                                                           k8s:io.kubernetes.pod.namespace=default                                                 
                                                           k8s:zgroup=testapp                                                                      

===================== Existing AfterFailed =====================
```

The DNS status: 

#### BPF Endpoint List 173

```
IP ADDRESS             LOCAL ENDPOINT INFO                                                                                     
10.10.1.66             id=173   ifindex=95  mac=00:00:00:00:9E:FB nodemac=C3:3F:00:00:86:FF seclabel=0xd88d portMaps=(empty)   
10.10.1.44             (localhost)                                                                                             
f00d::a0a:100:0:ad     id=173   ifindex=95  mac=00:00:00:00:9E:FB nodemac=C3:3F:00:00:86:FF seclabel=0xd88d portMaps=(empty)   
f00d::a0a:100:0:8ad6   (localhost)                                                                                             
fd04::12               (localhost)                                                                                             
10.10.1.172            id=29898 ifindex=93  mac=00:00:00:00:BE:51 nodemac=1B:44:00:00:86:5E seclabel=0xde88 portMaps=(empty)   
192.168.36.12          (localhost)                                                                                             
f00d::a0a:100:0:74ca   id=29898 ifindex=93  mac=00:00:00:00:BE:51 nodemac=1B:44:00:00:86:5E seclabel=0xde88 portMaps=(empty)   

```


#### BPF Policy Get 173

```
DIRECTION   LABELS (source:key[=value])   PORT/PROTO   BYTES   PACKETS   
Ingress     reserved:host                 ANY          0       0         

```


#### BPF CT List 173

```
Error: Unable to open /sys/fs/bpf/tc/globals/cilium_ct6_173: Unable to get object /sys/fs/bpf/tc/globals/cilium_ct6_173: no such file or directory

```


# [...]

2018-06-29 13:26 UTC, aanm commented
@eloycoto debugging that problem will depend on https://github.com/cilium/cilium/pull/4686

2018-07-02 15:10 UTC, eloycoto commented
test-me-please

2018-07-03 12:58 UTC, eloycoto commented
test-me-please

2018-07-03 14:18 UTC, eloycoto commented
test-me-please

2018-07-03 19:40 UTC, eloycoto commented
test-me-please

2018-07-04 06:30 UTC, eloycoto commented
test-me-please

2018-07-04 15:38 UTC, eloycoto commented
Review the output, there is communication from APP2 to the DNS: 

```
k8s2: <- overlay flow 0x9e9ae694 identity 0->0 state new ifindex cilium_vxlan: 10.10.0.66:45244 -> 10.10.1.72:53 udp
k8s2: -> endpoint 17318 flow 0x9e9ae694 identity 23964->13306 state new ifindex lxc3571f: 10.10.0.66:45244 -> 10.10.1.72:53 udp
k8s2: <- overlay flow 0x9e9ae694 identity 0->0 state new ifindex cilium_vxlan: 10.10.0.66:45244 -> 10.10.1.72:53 udp
k8s2: -> endpoint 17318 flow 0x9e9ae694 identity 23964->13306 state established ifindex lxc3571f: 10.10.0.66:45244 -> 10.10.1.72:53 udp
k8s2: <- endpoint 17318 flow 0x9e9ae694 identity 13306->0 state new ifindex 0: 10.10.1.72:53 -> 10.10.0.66:45244 udp
k8s2: -> overlay flow 0x9e9ae694 identity 13306->0 state new ifindex cilium_vxlan: 10.10.1.72:53 -> 10.10.0.66:45244 udp
k8s2: <- endpoint 17318 flow 0x9e9ae694 identity 13306->0 state new ifindex 0: 10.10.1.72:53 -> 10.10.0.66:45244 udp
k8s2: -> overlay flow 0x9e9ae694 identity 13306->0 state new ifindex cilium_vxlan: 10.10.1.72:53 -> 10.10.0.66:45244 udp
```

Core-dns does not have any good DNS log, so I'll wait until microscope has timestamps to be able to debug this one.

2018-07-04 20:45 UTC, aanm commented
@eloycoto can we enable debug logs in coredns?

Can we merge this as this seems to be hit by a flake? I'm going to trigger a new missed-k8s to make sure it's a flake

2018-07-04 20:45 UTC, aanm commented
test-missed-k8s

2018-07-05 15:11 UTC, eloycoto commented
test-me-please

2018-07-05 16:54 UTC, eloycoto commented
test-me-please

2018-07-06 07:41 UTC, eloycoto commented
test-me-please

2018-07-06 12:11 UTC, eloycoto commented
test-missed-k8s

2018-07-06 12:53 UTC, aanm requested changes

2018-07-06 12:53 UTC, aanm commented on test/provision/manifest/coredns_deployment.yaml
> +apiVersion: extensions/v1beta1
Can you add a header here specifying where we got this file from?

2018-07-06 14:32 UTC, eloycoto commented
test-me-please

2018-07-06 14:37 UTC, eloycoto commented
test-me-please

2018-07-06 20:03 UTC, aanm approved these changes

2018-07-06 20:03 UTC, merged