pkg/endpoint: check when policy proxy revision is set
cilium/cilium pull request #4743
Opened 2018-07-04 21:00 UTC by aanm

In WaitForPolicyRevision, the channel would only be closed when the
PolicyRevision was at the given revision. With this change we will also
take into account the proxy revision number only when the endpoint has a
proxy configured, otherwise it will only consider the policy revision.

Signed-off-by: André Martins <andre@cilium.io>

```release-note
In Kubernetes, set Cilium Endpoint Status policy enforcement as true when the L4 and L7 policy desired is configured in the proxy.
```

2018-07-04 21:00 UTC, aanm commented
test-me-please

2018-07-04 21:15 UTC, ianvernon submitted a review, later dismissed

2018-07-04 21:15 UTC, ianvernon commented on pkg/endpoint/endpoint.go
> +		e.DesiredL4Policy.Ingress.HasRedirect() &&
Shouldn't this be `e.DesiredL4Policy != nil && ( e.DesiredL4Policy.Ingress.HasRedirect() || e.DesiredL4Policy.Egress.HasRedirect() )` ?

2018-07-04 21:15 UTC, ianvernon commented on pkg/endpoint/endpoint.go
> +		e.DesiredL4Policy.Ingress.HasRedirect() &&
You could also call `e.DesiredL4Policy.HasRedirect()` directly.

2018-07-04 21:15 UTC, ianvernon commented on pkg/endpoint/endpoint.go
> +			if (!e.HasProxy() || e.proxyPolicyRevision >= ps.wantedRev) && e.policyRevision >= ps.wantedRev {
Please add a code comment explaining what this is doing.

2018-07-05 10:17 UTC, aanm commented
test-me-please

2018-07-05 10:20 UTC, aanm commented
I need someone from @cilium/proxy to verify the `proxyPolicyRevision` is incremented when the policy is received by the proxy **and** if the `proxyPolicyRevision` is also incremented when all of the L4-L7 policy is removed from the proxy. For both kafka and envoy.

2018-07-05 17:03 UTC, rlenglet requested changes

2018-07-05 17:03 UTC, rlenglet commented on pkg/endpoint/endpoint.go
> +func (e *Endpoint) setProxyPolicyRevision(rev uint64) {
Comment that e.Mutex must be held.

2018-07-05 17:03 UTC, rlenglet commented on pkg/endpoint/endpoint.go
> +	for ps := range e.policyRevisionSignals {
Please factorize this loop into another method.

2018-07-05 17:03 UTC, rlenglet commented on pkg/endpoint/endpoint.go
> +	return e.DesiredL4Policy.HasRedirect() || e.RealizedL4Policy.HasRedirect()
That's not reliable. In the sidecar HTTP proxy mode, we have no redirects. See `Endpoint.addNewRedirectsFromMap` in `pkg/endpoint/bpf.go`.

In the sidecar HTTP proxy mode, you need to check whether there are L7 rules in the policy. See how it's done in `XDSServer.UpdateNetworkPolicy` in `pkg/envoy/server.go`: https://github.com/cilium/cilium/blob/master/pkg/envoy/server.go#L557-L593.
Feel free to factorize that code somewhere else.

2018-07-05 17:15 UTC, rlenglet commented
> the proxyPolicyRevision is incremented when the policy is received by the proxy

That's true for Envoy, false for Kafka.

> [...] the proxyPolicyRevision is also incremented when all of the L4-L7 policy is removed from the proxy

I believe that's the case for Envoy, but that should be confirmed by testing.
That's not the case for Kafka.

2018-07-19 00:06 UTC, tgraf commented
@aanm @rlenglet What is blocking this?

2018-07-19 00:09 UTC, rlenglet commented
- Need to modify the Kafka proxy to increment the proxy policy revision.
- Need to modify the approach to determine whether traffic is redirected to a proxy, to work with the sidecar case.
- Need to test, at least manually.

2018-08-25 09:31 UTC, closed without merging

2018-09-01 16:47 UTC, jrfastab commented
Closed with unmerged commits, remove tags because there is nothing to backport.