prepare for release v1.0.5
cilium/cilium pull request #4884
Opened 2018-07-18 18:21 UTC by ianvernon

Signed-off-by: Ian Vernon <ian@cilium.io>

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cilium/cilium/4884)

2018-07-18 18:21 UTC, ianvernon commented
test-me-please

2018-07-18 18:22 UTC, ianvernon commented
test-missed-k8s

2018-07-18 18:57 UTC, ianvernon commented
K8s tests failed:
```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 137: expecting '}', found '' @ line 137, column 1.
1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:150)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:120)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:132)
	at org.codehaus.groovy.control.SourceUnit.addError(SourceUnit.java:350)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.transformCSTIntoAST(AntlrParserPlugin.java:144)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.parseCST(AntlrParserPlugin.java:110)
	at org.codehaus.groovy.control.SourceUnit.parse(SourceUnit.java:234)
	at org.codehaus.groovy.control.CompilationUnit$1.call(CompilationUnit.java:168)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:943)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:605)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:131)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:125)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:560)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:521)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:329)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
```

cc: @eloycoto @aanm

2018-07-18 19:52 UTC, ianvernon commented
K8s Jenkinsfile is broken because of the following:

```
           environment {
                FAILFAST=setIfPR("true", "false")
           ## there should be a '}' here
            options {
                timeout(time: 120, unit: 'MINUTES')
            }
            step
```

2018-07-18 20:07 UTC, aanm commented
@ianvernon probably this commit needs to be backported? https://github.com/cilium/cilium/commit/78499dec6a235d19031d891ab461c9175a38c387 cc @eloycoto

2018-07-19 10:52 UTC, eloycoto commented
I don't think so, the master ginkgo Jenkinsfile is ok: 

```
breo.acalustra.com ➜  cilium git:(v1.0) ✗ git rev-parse HEAD
4f02eec5112d721c1afc60367c8e8125d6d11cd1
breo.acalustra.com ➜  cilium git:(v1.0) ✗ curl -X POST -F "jenkinsfile=<ginkgo.Jenkinsfile" http://jenkins.cilium.io:8080/pipeline-model-converter/validate

Jenkinsfile successfully validated.
breo.acalustra.com ➜  cilium git:(v1.0) ✗
```

Any other change?

2018-07-19 10:52 UTC, eloycoto commented
test-me-please

2018-07-19 16:31 UTC, ianvernon commented
@aanm @eloycoto should this block the release of v1.0.5 ? The normal CI tests work just fine, so I think we can go ahead and release since this bug is only in the Jenkinsfile, not in Cilium itself.

2018-07-19 18:21 UTC, aanm commented
@ianvernon yes we should block as this is a release. The fix for your issue is here. https://github.com/cilium/cilium/pull/4907 as soon the tests start the PR can be merged since the issue is only related with the jenkinsfile itself

2018-07-27 00:33 UTC, ianvernon commented
test-me-please

2018-07-27 00:33 UTC, ianvernon commented
test-missed-k8s

2018-07-27 02:26 UTC, aanm requested changes

2018-07-27 02:26 UTC, aanm commented on examples/kubernetes/1.9/cilium.yaml
> -      priorityClassName: system-node-critical
wow, what's is happening here?

2018-07-27 02:29 UTC, aanm commented on examples/kubernetes/1.9/cilium.yaml
> -      priorityClassName: system-node-critical
You probably did `make` in `examples/kubernetes`. Can you fix it on a commit and then re-create the files again?

2018-07-27 03:37 UTC, ianvernon commented on examples/kubernetes/1.9/cilium.yaml
> -      priorityClassName: system-node-critical
This is part of the release notes (step 6) - http://docs.cilium.io/en/v1.1/contributing/#generic-release-process

2018-07-27 03:37 UTC, ianvernon commented on examples/kubernetes/1.9/cilium.yaml
> -      priorityClassName: system-node-critical
This is odd though, how did this happen? Is there something I can backport here?

2018-07-27 03:42 UTC, ianvernon commented on examples/kubernetes/1.9/cilium.yaml
> -      priorityClassName: system-node-critical
Manually fixed in latest upload.

2018-07-27 03:43 UTC, ianvernon commented
test-me-please

2018-07-27 03:43 UTC, ianvernon commented
test-missed-k8s

2018-07-27 06:07 UTC, aanm approved these changes

2018-07-27 06:07 UTC, merged