Test: Wait for Pods ensure that no deleted pods
cilium/cilium pull request #4902
Opened 2018-07-19 15:05 UTC by eloycoto

Have seen that pods are not ready because some pods are waiting to be
deleted and finally pods are not ready at all. Added a new checker to
validate that pods should not be deleted.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

2018-07-19 15:06 UTC, eloycoto commented
test-me-please

2018-07-19 22:14 UTC, ianvernon commented
@eloycoto can you provide an example of the behavior you are purportedly fixing? I'm having a hard time figuring out exactly what you are fixing here.

2018-07-19 22:17 UTC, ianvernon requested changes

2018-07-19 22:17 UTC, ianvernon commented on test/helpers/kubectl.go
> +		return fmt.Errorf("There is some pods with filter %s that are mark to delete", filter)
there are some pods ... that are marked to be deleted

2018-07-19 22:17 UTC, ianvernon commented on test/helpers/kubectl.go
>  		var jsonPath = "{.items[*].status.containerStatuses[*].ready}"
Instead of returning an error, why not just only take pods that do not have a deletion timestamp?

2018-07-19 22:17 UTC, ianvernon commented on test/helpers/kubectl.go
> +		fmt.Sprintf("could not get pods on filter %s", filter),
error is a bit cryptic, what about "timed out waiting for pods with filter %s to be ready"?

2018-07-20 07:50 UTC, eloycoto commented
test-me-please

2018-07-20 07:55 UTC, eloycoto commented
Hi Ian,

Related to the return error if any pod is mark as deleted. The issue here is
that if you apply the a manifest that it's going to install the same pods that
are scheduled to be deleted, Kubernetes does not install at all, so the test
fails and you don't know why.

This does not use to happens, mainly because all Test groups use to have a
WaitTerminate helper on the AfterEach, but with this change I want to make sure
that do not happen in any case, and if it happens know the reason.

2018-07-22 04:08 UTC, eloycoto commented
test-me-please

2018-07-23 18:46 UTC, ianvernon approved these changes

2018-07-24 05:39 UTC, merged