golint: fix warnings for pkg/events/events.go
cilium/cilium pull request #497
Opened 2017-03-31 13:16 UTC by scanf

Fixes the following warnings

pkg/events/events.go:22:2: exported const IdentityAdd should have comment (or a comment on this block) or be unexported
pkg/events/events.go:27:6: exported type EventType should have comment or be unexported
pkg/events/events.go:29:6: exported type Event should have comment or be unexported
pkg/events/events.go:35:1: exported function NewEvent should have comment or be unexported

Related-to: #153 (Resolve golint warnings)

2017-03-31 13:16 UTC, aanm commented
This pull request is now managed with CodeReviewHub. <a href='https://github.com/cilium/cilium/pull/497'>Refresh</a>.<a href='#crh-update-none'></a>

2017-03-31 13:18 UTC, tgraf requested changes

2017-03-31 13:18 UTC, tgraf commented on pkg/events/events.go
> +        // IdentityAdd the identity creation event.
Can you work with @aanm to make this a bit more descriptive?

2017-03-31 13:24 UTC, scanf commented on pkg/events/events.go
> +        // IdentityAdd the identity creation event.
Will wait for feedback from @aanm  and reword later.

Thanks.

2017-04-06 10:45 UTC, scanf commented
FYI, Andrew has kindly provided me some feedback and I have started incorporating them. Being in a different timezone and wanting to attend netdev. This might be delayed a little bit.

Thanks.

2017-04-08 12:19 UTC, scanf commented
Please let me know if anything more should be reworded, thanks.

2017-04-08 19:54 UTC, tgraf approved these changes

2017-04-08 19:54 UTC, merged