Test: extend validate on errors on Runtime
cilium/cilium pull request #5086
Opened 2018-08-03 07:30 UTC by eloycoto

Currently the runtime test does not have the full validation of logs
messages as Kubernetes test. This adds al the methods for fail and
checks.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

2018-08-03 07:30 UTC, eloycoto commented
test-me-please

2018-08-03 17:18 UTC, ianvernon requested changes
Looks fine, mainly nitpicks.

2018-08-03 17:18 UTC, ianvernon commented on test/helpers/cilium.go
>  	"github.com/cilium/cilium/test/config"
Please proofread your commit messages. "al" --> "all"

2018-08-03 17:18 UTC, ianvernon commented on test/helpers/cilium.go
> +			fmt.Sprintf("%s/cilium_test.log", testPath),
Make "cilium_test.log" a string variable / constant and reuse it.

2018-08-06 14:55 UTC, eloycoto commented on test/helpers/cilium.go
>  	"github.com/cilium/cilium/test/config"
done

2018-08-06 14:56 UTC, eloycoto commented
test-me-please

2018-08-07 14:28 UTC, tgraf approved these changes

2018-08-07 14:28 UTC, merged