prometheus example edit
cilium/cilium pull request #5124
Opened 2018-08-08 01:16 UTC by techcet

Signed-off-by: Cynthia Thomas <cynthia@covalent.io>

**Summary of changes**:
Prometheus example provided in recent blog was missing the creation of monitoring namespace. Team opted to modify the prometheus yaml to use the same namespace for both Prometheus and Grafana deployments in the Prometheus blog.

2018-08-08 20:55 UTC, ianvernon commented
test-me-please

2018-08-08 20:55 UTC, ianvernon commented
test-docs-please

2018-08-08 21:04 UTC, ianvernon commented
Tests failed due to #5137 . Given that the CI utilizes this YAML, I wanted to make sure this didn't break anything on the CI (it shouldn't, but you never know). Once #5137 is merged, I will run tests again.

2018-08-09 13:45 UTC, aanm requested changes
@techcet the blogpost is not pointing to this file, it's pointing to `examples/kubernetes/addons/prometheus/prometheus.yaml`

Please discard the changes for this file. I've made a PR #5155 to remove this file, `examples/kubernetes/cilium.yaml` and `examples/kubernetes/rbac.yaml` to avoid future confusion.

Also, this PR will need to be backported to 1.1 as the blogpost is pointing to that version.

2018-08-10 18:19 UTC, ianvernon commented
@aanm if `examples/kubernetes/prometheus.yaml` is being removed, then how are we going to backport the changes? Should these changes be made against the branches v1.1 and v1.2 directly?

2018-08-10 20:37 UTC, aanm commented
@ianvernon I don't understand your question. What should be backported is the changes eventually made by @techcet in `examples/kubernetes/addons/prometheus/prometheus.yaml`. This PR should not touch `examples/kubernetes/prometheus.yaml`

2018-08-10 20:38 UTC, aanm commented
@ianvernon I don't understand your question. What should be backported is the changes eventually made by @techcet in `examples/kubernetes/addons/prometheus/prometheus.yaml`. This PR should not touch `examples/kubernetes/prometheus.yaml`

2018-08-10 20:45 UTC, ianvernon commented
@aanm that clarifies things, thanks!

2018-08-23 00:35 UTC, closed without merging