CEP: Added custom columns on list
cilium/cilium pull request #5161
Opened 2018-08-10 06:32 UTC by eloycoto

On CEP the default list is not enough for a quick view and it does not
provide a lot of information to the users.

Kubernetes 1.11 added a new option to have custom list on the Custom
Resources definition, so the list provides to the users more
information.

This commit change the CEP list output to the following:

- Kubernetes 1.11
```
vagrant@k8s1:~$ kubectl get cep --all-namespaces
NAMESPACE     NAME                      ENDPOINT ID   IDENTITY ID  POLICY ENFORCEMENT   ENDPOINT STATE   IPV4          IPV6
default       app1-5d79fbc474-fkvxq     24637         37263        none                 ready            10.10.0.54    f00d::a0a:0:0:603d
default       app1-5d79fbc474-n4g2f     17467         37263        none                 ready            10.10.0.247   f00d::a0a:0:0:443b
default       app2-56fbc4b964-gwp6j     9386          22676        none                 ready            10.10.0.39    f00d::a0a:0:0:24aa
default       app3-5d9895d6ff-cwj2q     46066         11397        none                 ready            10.10.0.3     f00d::a0a:0:0:b3f2
kube-system   coredns-b9476b976-zkp9x   54975         30138        none                 ready            10.10.0.220   f00d::a0a:0:0:d6bf
```

- Kubernetes 1.7
```
vagrant@k8s1:~$ kubectl get pods
NAME                    READY     STATUS    RESTARTS   AGE
app1-1879020049-2sb9c   1/1       Running   0          1m
app1-1879020049-vb1z9   1/1       Running   0          1m
app2-2809035625-htqm4   1/1       Running   0          1m
app3-753781860-f1wj9    1/1       Running   0          1m
vagrant@k8s1:~$ kubectl get nodes
NAME      STATUS    AGE       VERSION
k8s1      Ready     12m       v1.7.15
vagrant@k8s1:~$ kubectl get cep
NAME                    KIND
app1-1879020049-2sb9c   CiliumEndpoint.v2.cilium.io
app1-1879020049-vb1z9   CiliumEndpoint.v2.cilium.io
app2-2809035625-htqm4   CiliumEndpoint.v2.cilium.io
app3-753781860-f1wj9    CiliumEndpoint.v2.cilium.io
```

Related to #3334

This PR works, but if https://github.com/cilium/cilium/pull/5100 is merged, this PR need to be updated. 

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

2018-08-10 06:32 UTC, eloycoto commented
test-me-please

2018-08-10 08:07 UTC, aanm requested changes
Bump the `CustomResourceDefinitionSchemaVersion` to `1.10`

2018-08-10 08:42 UTC, raybejjani commented
This is the excellentest thing! :) :) :)

2018-08-10 12:09 UTC, eloycoto commented
test-me-please

2018-08-10 12:29 UTC, aanm approved these changes

2018-08-10 15:20 UTC, eloycoto commented
timeout: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5581/flowGraphTable/

2018-08-10 15:20 UTC, eloycoto commented
test-me-please

2018-08-10 18:40 UTC, eloycoto commented
test-upstream-k8s

2018-08-10 20:16 UTC, ianvernon approved these changes

2018-08-12 13:40 UTC, eloycoto commented
test-upstream-k8s

2018-08-13 07:55 UTC, merged