Ignore k8s node updates
cilium/cilium pull request #5170
Opened 2018-08-10 16:12 UTC by aanm

```release-note
Ignore unnecessary Kubernetes node updates
```

2018-08-10 16:13 UTC, aanm commented
test-me-please

2018-08-10 16:20 UTC, raybejjani approved these changes

2018-08-10 18:03 UTC, ianvernon requested changes

2018-08-10 18:03 UTC, ianvernon commented on pkg/node/node.go
> +	if n == nil {
Please add unit tests for this.

2018-08-10 20:31 UTC, aanm commented
test-me-please

2018-08-10 20:31 UTC, aanm commented on pkg/node/node.go
> +	if n == nil {
Done

2018-08-11 02:16 UTC, ianvernon approved these changes

2018-08-11 08:33 UTC, tgraf approved these changes

2018-08-11 08:33 UTC, merged