policy: Handle empty L7Rules in ToPorts
cilium/cilium pull request #5216
Opened 2018-08-15 20:41 UTC by rlenglet

Consistently respect the API spec in handling an empty `L7Rules`
like a `nil` `L7Rules`.  Fix the merging and wildcarding of rules with
empty `L7Rules`.

Signed-off-by: Romain Lenglet <romain@covalent.io>

2018-08-15 20:42 UTC, rlenglet commented
test-me-please

2018-08-15 21:47 UTC, ianvernon approved these changes

2018-08-15 21:48 UTC, ianvernon commented on pkg/policy/api/l4.go
> +func (rules *L7Rules) Len() int {
Unit test these functions please. Do the existing policy resolution unit tests cover these cases? If not, please add such a test.

2018-08-16 01:22 UTC, tgraf requested changes
How is this not breaking the API? There can be existing policies out there that will all of a sudden become more permissive.

2018-08-16 03:23 UTC, rlenglet commented
Yes, this is changing the behavior of the API.

The current behavior is as follows.
This rule alone:
```
                        {
                            "fromEndpoints": [
                                {
                                    "matchLabels": {
                                        "k8s:app": "loader",
                                    }
                                }
                            ],
                            "toPorts": [
                                {
                                    "ports": [
                                        {
                                            "port": "9092",
                                            "protocol": "TCP"
                                        }
                                    ],
                                    "rules": {}
                                }
                            ]
                        },
```
is semantically identical to the same rule with no `rules`, i.e. an L3/L4 rule:
```
                        {
                            "fromEndpoints": [
                                {
                                    "matchLabels": {
                                        "k8s:app": "foo",
                                    }
                                }
                            ],
                            "toPorts": [
                                {
                                    "ports": [
                                        {
                                            "port": "9092",
                                            "protocol": "TCP"
                                        }
                                    ]
                                }
                            ]
                        },
```
But whenever another L7 rule has the same L4 port, any rule with an empty `rules` gets ignored.
I.e. those 2 rules:
```
                        {
                            "fromEndpoints": [
                                {
                                    "matchLabels": {
                                        "k8s:app": "bar",
                                    }
                                }
                            ],
                            "toPorts": [
                                {
                                    "ports": [
                                        {
                                            "port": "9092",
                                            "protocol": "TCP"
                                        }
                                    ],
                                    "rules": {
                                        "kafka": [
                                            {
                                                "role": "produce",
                                            }
                                        ]
                                    }
                                }
                            ]
                        },
                        {
                            "fromEndpoints": [
                                {
                                    "matchLabels": {
                                        "k8s:app": "foo",
                                    }
                                }
                            ],
                            "toPorts": [
                                {
                                    "ports": [
                                        {
                                            "port": "9092",
                                            "protocol": "TCP"
                                        }
                                    ],
                                    "rules": {}
                                }
                            ]
                        },
```
are semantically equivalent to the first rule only, and the rule with the empty `rules` is ignored:
```
                        {
                            "fromEndpoints": [
                                {
                                    "matchLabels": {
                                        "k8s:app": "bar",
                                    }
                                }
                            ],
                            "toPorts": [
                                {
                                    "ports": [
                                        {
                                            "port": "9092",
                                            "protocol": "TCP"
                                        }
                                    ],
                                    "rules": {
                                        "kafka": [
                                            {
                                                "role": "produce",
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
```

@tgraf, did you mean that you want to preserve that behavior?
If so, this needs to be documented, since the API spec specifies a different behavior.
How would you suggest I word this in the docs?

2018-08-16 03:25 UTC, rlenglet commented
Alternatively, a simpler change would be to reject any rule with empty `rules` field. That would only require changing the validation and a bit of the API spec. That would be less surprising than the current behavior.
@tgraf what is your preference?

2018-08-16 08:39 UTC, tgraf commented
I assume you had a typo in your example as the `"fromEndpoints:` was using different labels.

I think I'm fine with the change after fully understanding it. Let me double check my understanding. Your change will cause the following:

```
                            "toPorts": [
                                {
                                    "ports": [
                                        {
                                            "port": "9092",
                                            "protocol": "TCP"
                                        }
                                    ],
                                    "rules": {}
                                }
```

to be handled identically to:

```
                            "toPorts": [
                                {
                                    "ports": [
                                        {
                                            "port": "9092",
                                            "protocol": "TCP"
                                        }
                                    ]
                                }
```

while the following will still have the old behavior:

```
                            "toPorts": [
                                {
                                    "ports": [
                                        {
                                            "port": "9092",
                                            "protocol": "TCP"
                                        }
                                    ],
                                    "rules": {
                                        "kafka": []
                                    }
                                }
```

2018-08-16 08:50 UTC, rlenglet commented
Good point. My fix was breaking the old behavior with an empty Kafka list. I will fix that by changing the implementation of `IsEmpty` to:
```
func (rules *L7Rules) IsEmpty() bool {
	return rules == nil || (rules.HTTP == nil && rules.Kafka == nil)
}
```

2018-08-16 08:51 UTC, tgraf commented
test-me-please

2018-08-16 08:59 UTC, rlenglet commented
Fixed `L7Rules.IsEmpty` to keep the semantics with empty non-nil HTTP or Kafka rule lists.

2018-08-16 08:59 UTC, rlenglet commented
test-me-please

2018-08-16 09:21 UTC, tgraf approved these changes

2018-08-16 11:30 UTC, merged