Tl/add ninja build to BuildRequires
cilium/cilium pull request #5220
Opened 2018-08-16 01:44 UTC by tonylambiris

**Summary of changes**:
Add the `ninja-build` package to cilium.spec.envsubst (required for recent builds, verified on RHEL and Arch Linux)
Fix-up the VERSION variable.
Generate a RELEASE variable (previously hard-coded to 0).

Here is the current package information after building:
```
➜  rpm -qip output/cilium-1.2.90-0.git54ce03f.fc28.x86_64.rpm | head -3
Name        : cilium
Version     : 1.2.90
Release     : 0.git54ce03f.fc28
```

Here is the updated package information from this PR:
```
➜  rpm -qip output/cilium-1.2.0.rc3-1340.git562985b.fc28.x86_64.rpm | head -3 
Name        : cilium
Version     : 1.2.0.rc3
Release     : 1340.git562985b.fc28
```

**How to test (optional)**:
```bash
$ cd contrib/packaging/rpm && make
```

2018-08-16 15:30 UTC, ianvernon commented
Thank you for the contributions @tonylambiris ! Can you please remove the "Merge" commit from your branch by rebasing, as well as sign off each commit per the [contributing documentation](http://docs.cilium.io/en/v1.1/contributing/#developer-s-certificate-of-origin) ?

2018-08-17 09:50 UTC, joestringer requested changes
Looks good to me, just needs rebase/squash and signoff per @ianvernon 's comments.

Thanks!

2018-08-17 11:20 UTC, tonylambiris commented
@ianvernon @joestringer Hey guys, did I do this correctly? Haven't done much in the way of squashing and rebasing commits.

2018-08-17 14:02 UTC, joestringer commented
@tonylambiris Hey, I think it didn't quite work.

There's a guide on how to rebase here:
https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history

I usually do something similar to the section about "Interactive Rebase" and "Squash the commits together".

Then, to sign off, assuming you agree with the [Contributing guidelines](http://docs.cilium.io/en/v1.1/contributing/#developer-s-certificate-of-origin), you can do a `git commit --amend -s` and save the commit message.

2018-08-17 18:12 UTC, aanm commented on contrib/packaging/rpm/Makefile
> +VERSION := $(shell git tag -l --sort=-v:refname | sed 's/v\([^-]*-g\)/r\1/;s/-/./g' | head -1)
This should be available from `./VERSION`. Did we change anything that broke it?

2018-08-17 18:14 UTC, aanm commented
@tonylambiris try `git rebase -i ^HEAD~8` and replace `pick` with `squash` or `s` if you want to squash commits together or simply remove the lines for the commits that you want to make them disappear.

The do `git fetch origin master` and `git rebase origin/master`

2018-08-21 20:07 UTC, tonylambiris commented
@aanm did that work properly? if not im at a loss because I had rebased and squashed. running `git rebase -i` currently shows:
```noop

# Rebase 562985b8c..562985b8c onto 562985b8c (1 command)
```

let me know, i'll just redo the pull request. what exactly was the original issue anyway here (so I can avoid it in the future).

thanks.

2018-08-21 22:03 UTC, aanm commented
@tonylambiris are you on cilium slack? I can help you quickly in there

2018-08-23 00:27 UTC, tgraf commented
@tonylambiris `git rebase -i master`, replace pick with squash except for first line, `git commit --amend -s` to sign the commit, `git push -f`

2018-08-24 08:52 UTC, raybejjani commented
If we prefer saving tonylambiris the hassle, perhaps an admin can click the "Squash and merge" button? I think that will work correctly in this case (I'm not sure, though).

2018-08-27 18:25 UTC, joestringer commented
> If we prefer saving tonylambiris the hassle, perhaps an admin can click the "Squash and merge" button? I think that will work correctly in this case (I'm not sure, though).

This might just work, but we still need sign-off from @tonylambiris.

2018-08-29 18:28 UTC, tonylambiris commented
Is it copisetic if I close this PR in favor of a new one, all refreshly rebased and such? Caught a one offs I need to add (ie: requirement of llvm installed due to llc and/or lld needed for pre-flight checks).

Thanks!

2018-08-29 20:49 UTC, tgraf commented
> Is it copisetic if I close this PR in favor of a new one, all refreshly rebased and such? Caught a one offs I need to add (ie: requirement of llvm installed due to llc and/or lld needed for pre-flight checks).
> 
> Thanks!

Sure, go ahead

2018-09-07 20:05 UTC, tonylambiris commented
I'll get back to this shortly, thanks everyone for their input! 👍

2018-09-07 20:05 UTC, closed without merging