Test: Refactor some helpers to parallel
cilium/cilium pull request #5261
Opened 2018-08-20 14:26 UTC by eloycoto

Hi, 

Moved two functions to parallel to speed a little bit the tests. The functions are: 

- CiliumPolicyAction
- CiliumEndpointReady

Regards

2018-08-20 14:26 UTC, eloycoto commented
test-me-please

2018-08-20 15:11 UTC, eloycoto commented
For the track, 

Comparing the following builds: 

Master: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/3735/execution/node/98/log/?consoleFull
Current build: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5756/execution/node/93/log/

**Data:**

Before: 
```
13:07:36 • [SLOW TEST:171.301 seconds]
13:07:36 K8sPolicyTest
13:07:36 /home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
13:07:36   GuestBook Examples
13:07:36   /home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
13:07:36     checks policy example
13:07:36     /home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
```
After: 
```
15:03:12 • [SLOW TEST:110.683 seconds]
15:03:12 K8sPolicyTest
15:03:12 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
15:03:12   GuestBook Examples
15:03:12   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
15:03:12     checks policy example
15:03:12     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
```

Before:
```
13:02:24 • [SLOW TEST:83.688 seconds]
13:02:24 K8sPolicyTest
13:02:24 /home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
13:02:24   Basic Test
13:02:24   /home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
13:02:24     Allows traffic with k8s default-allow ingress policy
13:02:24     /home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
```

After:
```
14:57:39 • [SLOW TEST:73.618 seconds]
14:57:39 K8sPolicyTest
14:57:39 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
14:57:39   Basic Test
14:57:39   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
14:57:39     Denies traffic with cnp default-deny egress policy
14:57:39     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
```

2018-08-20 21:12 UTC, aanm requested changes

2018-08-20 21:12 UTC, aanm commented on test/helpers/kubectl.go
> +		for _, pod := range ciliumPods {
wg.Add(len(ciliumPods))

2018-08-20 21:12 UTC, aanm commented on test/helpers/kubectl.go
> +		for _, v := range pods {
wg.Add(len(pods))

2018-08-20 21:59 UTC, eloycoto commented
test-me-please

2018-08-21 08:19 UTC, eloycoto commented
test-me-please

2018-08-21 09:13 UTC, aanm approved these changes

2018-08-21 11:37 UTC, merged