Fix xDS completion timeout handling
cilium/cilium pull request #5326
Opened 2018-08-24 00:09 UTC by rlenglet

Ignore completion timeouts on xDS resource upsert and delete.

Fix `plugins/cilium-cni/Makefile` to re-enable quiet builds (`make V=0`).

Fixes: https://github.com/cilium/cilium/issues/5317
Fixes: https://github.com/cilium/cilium/pull/5233
Fixes: 2b3650dac24e2c635ee6408440c5f9734f9de03f
Signed-off-by: Romain Lenglet <romain@covalent.io>

2018-08-24 00:14 UTC, rlenglet commented
test-me-please

2018-08-24 01:27 UTC, rlenglet commented
test-me-please

2018-08-24 02:04 UTC, ianvernon approved these changes

2018-08-24 04:52 UTC, rlenglet commented
The CI build took a very long time and eventually timed out:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5857/
There are also several k8s test failures.
An interesting point is that every test run has a warning about a non-negligible number of `Goroutine took lock for more than` warnings:
```
02:19:34 ⚠️  Number of "Goroutine took lock for more than" in logs: 13
```

2018-08-24 05:29 UTC, rlenglet commented
test-me-please

2018-08-24 05:55 UTC, rlenglet commented
test-me-please

2018-08-24 08:02 UTC, tgraf requested changes
What change is actually fixing the bug? I see changes to increase the probability but nothing that would explain and resolve the 55 second timeout?

There is no `BPF compilation completed` log file message so we did not actually compile any programs.

2018-08-24 08:02 UTC, tgraf commented on pkg/envoy/xds/ack.go
> +	// Always upsert the resource, even if the completion's context was
Does this mean we have Envoy rules configured for a particular endpoint even if the endpoint ends up not going to that policy revision? That seems very serious.

Shouldn't we have a change queue and revert the change if it got canceled?

How does this fix 5317?

2018-08-24 08:02 UTC, tgraf commented on plugins/cilium-cni/Makefile
> +	 $(QUIET)CGO_ENABLED=0 go build $(GOBUILD) -o $(TARGET) ./cilium-cni.go
Why are you replacing $(GO) with go? If it is needed, it needs a comment why we are not using $(GO). Also, how is this related to this PR? We are likely to backport this PR and this commit will cause an unnecessary merge conflict.

2018-08-24 13:06 UTC, ianvernon commented on plugins/cilium-cni/Makefile
> +	 $(QUIET)CGO_ENABLED=0 go build $(GOBUILD) -o $(TARGET) ./cilium-cni.go
Related: https://github.com/cilium/cilium/pull/5331/commits/8531e41eb853e7dbf5f00074f28577058f4ad0e7

2018-08-24 16:49 UTC, rlenglet commented
Got a green build:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5860/

2018-08-24 16:50 UTC, rlenglet commented
> What change is actually fixing the bug? I see changes to increase the probability but nothing that would explain and resolve the 55 second timeout?

Commit https://github.com/cilium/cilium/pull/5326/commits/683dadbd089d5f54416b554ed570b39edc1920e1 removes one endpoint lock/unlock after BPF compilation. That will reduce the regeneration time overall.

2018-08-24 16:53 UTC, rlenglet commented on pkg/envoy/xds/ack.go
> +	// Always upsert the resource, even if the completion's context was
One of the points in https://github.com/cilium/cilium/issues/5317 is that if we tried to add a redirect after the context was cancelled, we ended up with an inconsistent state: no listener was added into the xDS cache, but the listener was recorded in the endpoint as part of the realized redirects. This commit fixes that: now the xDS cache and the endpoint state are consistent, whether we add listeners or not.

2018-08-24 16:54 UTC, tgraf commented
Do you seriously think that endpoint lock caused a wait of 55 seconds?

I see no real fix in this PR.

On Fri, 24 Aug 2018, 18:50 Romain Lenglet, <notifications@github.com> wrote:

> What change is actually fixing the bug? I see changes to increase the
> probability but nothing that would explain and resolve the 55 second
> timeout?
>
> Commit 683dadb
> <https://github.com/cilium/cilium/commit/683dadbd089d5f54416b554ed570b39edc1920e1>
> removes one endpoint lock/unlock after BPF compilation. That will reduce
> the regeneration time overall.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/cilium/cilium/pull/5326#issuecomment-415817198>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABWiuQI9pHsfJz2b-isxft6Y-3ReqwUqks5uUC7rgaJpZM4WKi0u>
> .
>

2018-08-24 17:01 UTC, rlenglet commented on pkg/envoy/xds/ack.go
> +	// Always upsert the resource, even if the completion's context was
> Shouldn't we have a change queue and revert the change if it got canceled?

Correct. We currently don't revert changes to the Envoy resources if the endpoint's regeneration failed.

2018-08-24 17:02 UTC, rlenglet commented on plugins/cilium-cni/Makefile
> +	 $(QUIET)CGO_ENABLED=0 go build $(GOBUILD) -o $(TARGET) ./cilium-cni.go
@ianvernon Cool, I can remove my commit then.

2018-08-24 17:08 UTC, rlenglet commented
> Do you seriously think that endpoint lock caused a wait of 55 seconds?
> I see no real fix in this PR.

As I commented in https://github.com/cilium/cilium/issues/5317#issuecomment-415597530, this PR is fixing the xDS cache consistency issue in the presence of context timeout.

Commit https://github.com/cilium/cilium/commit/683dadbd089d5f54416b554ed570b39edc1920e1 is an attempt to reduce the regeneration time overall. I tried that because I hit a build where the tests took more than 2 hours: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5857/

@tgraf I can remove that commit from this PR if you find it confusing.

2018-08-24 17:11 UTC, rlenglet commented
test-me-please

2018-08-24 18:03 UTC, tgraf commented
@rlenglet OK, that makes more sense. How does adding it to `pendingCompletions` guarantee that it will be configured in Envoy? Is it guaranteed to never fail after that point? I see several other cases where we see if the context was canceled, e.g. `HandleResourceVersionAck`

This issue is very serious as we seem to never be able to recover from it.

2018-08-24 18:14 UTC, rlenglet commented
> @rlenglet OK, that makes more sense. How does adding it to pendingCompletions guarantee that it will be configured in Envoy? Is it guaranteed to never fail after that point? I see several other cases where we see if the context was canceled, e.g. HandleResourceVersionAck

We are only sure that Envoy has configured it when we receive an ACK from Envoy for the updates to the xDS cache. That why we do this call to `WaitForProxyCompletions`.

Adding the resource update into `pendingCompletions` only means that we can wait for an ACK on it, and that we'll be able to clean it up later when its context is cancelled.

The problem we had was that in the `Endpoint`'s state we recorded that the listener had been upserted into the xDS cache, when it actually wasn't in the case of an early context timeout. With this PR, the list of listeners in the `Endpoint` corresponds to what is in the xDS cache.

2018-08-24 18:24 UTC, tgraf commented
> The problem we had was that in the Endpoint's state we recorded that the listener had been upserted into the xDS cache, when it actually wasn't in the case of an early context timeout. With this PR, the list of listeners in the Endpoint corresponds to what is in the xDS cache.

If I understand this correctly then even after this change, the context can still be canceled after `addNewRedirects()` and we won't wait for the ACK so we don't know whether Envoy has a listener configured. I still don't understand what change guarantees this to work now. It seems that we make it less likely to break but it can still break. What am I missing?

2018-08-25 09:32 UTC, tgraf approved these changes

2018-08-25 09:33 UTC, tgraf commented
This does not completely address #5317 but we agree that this is a step in the right direction.

2018-08-25 09:33 UTC, merged