Test: Update Vagrant image to 107.
cilium/cilium pull request #5381
Opened 2018-08-27 14:23 UTC by eloycoto

Include the following PR:

https://github.com/cilium/packer-ci-build/pull/84
https://github.com/cilium/packer-ci-build/pull/82

Fix #5059

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cilium/cilium/5381)

2018-08-27 14:23 UTC, eloycoto commented
test-me-please

2018-08-27 14:25 UTC, aanm requested changes

2018-08-27 14:25 UTC, aanm commented on Vagrantfile
> -        config.vm.box_version = "106"
There's no need to change this one as we didn't change anything relevant for developers.

2018-08-27 14:35 UTC, eloycoto commented on Vagrantfile
> -        config.vm.box_version = "106"
There is a fix on `./cahe/.gobuild` so it's needed for developers, that make the build faster + don't show errors.

2018-08-27 14:54 UTC, aanm approved these changes

2018-08-28 07:39 UTC, eloycoto commented
test-me-please

2018-08-28 10:18 UTC, merged