Metrics: Add Controllers metrics
cilium/cilium pull request #5434
Opened 2018-08-30 16:21 UTC by eloycoto

Added two new metrics related to controllers:

- controllers_runs_total which provide the number of runs labeled by
success or not.
- controllers_runs_duration_seconds which provide the number of seconds
that a controller took labeled by the status.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cilium/cilium/5434)

2018-08-30 16:55 UTC, ianvernon approved these changes

2018-08-30 17:00 UTC, vadorovsky approved these changes

2018-08-30 19:07 UTC, raybejjani requested changes
There are some controllers that block in their DoFunc, so I'm not sure how the histogram will look. It should be ok, and somewhat clear on the histogram itself, but the percentiles may not be usable.
Have you tried it out? Did it look ok?

Otherwise approved!

2018-08-30 22:24 UTC, joestringer reviewed
Likewise, I'm curious regarding Ray's question. I don't know how this might look with controllers that block a long time.

2018-08-31 10:46 UTC, eloycoto commented
Hi, 

About long controllers, the way that I see that:

1) The histogram creates the values per `less than` so each time that a controller takes more than a second we'll see that. 

```
cilium_controllers_runs_duration_seconds_bucket{status="success",le="0.005"} 2575 
cilium_controllers_runs_duration_seconds_bucket{status="success",le="0.01"} 2645  
cilium_controllers_runs_duration_seconds_bucket{status="success",le="0.025"} 2800 
cilium_controllers_runs_duration_seconds_bucket{status="success",le="0.05"} 2856  
cilium_controllers_runs_duration_seconds_bucket{status="success",le="0.1"} 2880   
cilium_controllers_runs_duration_seconds_bucket{status="success",le="0.25"} 2880  
cilium_controllers_runs_duration_seconds_bucket{status="success",le="0.5"} 2880   
cilium_controllers_runs_duration_seconds_bucket{status="success",le="1"} 2880
cilium_controllers_runs_duration_seconds_bucket{status="success",le="2.5"} 2881   
cilium_controllers_runs_duration_seconds_bucket{status="success",le="5"} 2881
cilium_controllers_runs_duration_seconds_bucket{status="success",le="10"} 2881
cilium_controllers_runs_duration_seconds_bucket{status="success",le="+Inf"} 2881  
cilium_controllers_runs_duration_seconds_sum{status="success"} 8.773957286000007  
cilium_controllers_runs_duration_seconds_count{status="success"} 2881
cilium_controllers_runs_total{status="success"} 2881
```

I do not think that we have successful controllers that take more than 10 seconds, but if we have, maybe if something that we should check.

2) Having this data we can use 95th percentitle using [histogram_quantile](https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile()), so the 95th percentile should be in less that a second, or I understand so.

2018-08-31 13:18 UTC, joestringer approved these changes

2018-08-31 13:49 UTC, eloycoto commented
test-me-please

2018-09-01 16:50 UTC, tgraf commented
How are these metrics useful if we can't tell what controller it is?

2018-09-03 06:35 UTC, eloycoto commented
>How are these metrics useful if we can't tell what controller it is?

The issue with the controllers is the same as the endpoint, it's easy to get hundred of controllers because there are using the id or pointer in the name: 

```
vagrant@runtime:~$ cilium status --all-controllers  -o json | jq '.controllers|length'
510
```

So, my idea is:

- Know how many controllers are failing/success
- Know the time that the controller took if is working or it's failing. 

You can't do a fine grained debug in there, but at least you'll know when controllers are failing or not. 

Regards

2018-09-03 10:15 UTC, raybejjani commented
We could add a new field to UpdateController called `category` or `type` (or something) and use that as a label. We have many controller instances but only 31 places we call `UpdateController`, so perhaps "only" 31 types. That might still be too many for a label, though, especially because we are likely to add more controllers.
A similar alternative is to split name into `type` and `id` fields but internally they are combined as the controller name. The `id` here is freeform but could be empty or be the id we usually use.

2018-09-17 21:04 UTC, tgraf approved these changes

2018-09-18 07:22 UTC, eloycoto commented
test-me-please

2018-09-18 09:10 UTC, merged