doc: add initial BPF and XDP documentation
cilium/cilium pull request #546
Opened 2017-04-14 01:13 UTC by borkmann

We're currently lacking a guide on this, therefore add a start of it
that we can further extend over time.

Rendered version from wip branch:

  http://cilium.readthedocs.io/en/doc-bpf-wip/

Signed-off-by: Daniel Borkmann <daniel@cilium.io>

2017-04-14 11:51 UTC, aalemayhu approved these changes
Other than the minor nitpick this looks very good and was fun to read :taco:

2017-04-14 11:51 UTC, scanf commented on Documentation/bpf.rst
> +kernel before program execution.
s/into an/into a/ ?

2017-04-14 11:51 UTC, scanf commented on Documentation/bpf.rst
> +  data, packet data, etc.
s/can could/and could/

2017-04-14 11:51 UTC, scanf commented on Documentation/bpf.rst
> +   static inline functions or macros / definitions.
s/resuse/reuse/

2017-04-14 11:51 UTC, scanf commented on Documentation/bpf.rst
> +   and ``egress``. The toy example code demonstrates that both can share a map
s/to contain to/to contain/ ?

2017-04-14 11:51 UTC, scanf commented on Documentation/bpf.rst
> +  limitation. This also works accross tail calls, since it has the same guarantees
s/temporariy/temporary/ ?

2017-04-14 11:51 UTC, scanf commented on Documentation/bpf.rst
> +  dumping additional attributes.
s/view through/view/ ? The extra `through` adds nothing extra IMO, but either way is fine.

2017-04-14 11:51 UTC, scanf commented on Documentation/bpf.rst
s/instace/instance/ ?

2017-04-14 22:04 UTC, tgraf requested changes

2017-04-14 22:04 UTC, tgraf commented on Documentation/bpf.rst
> +BPF and XDP Guide
Maybe rename this to "BPF and XDP Reference Guide" to make it a bit clearer that this is deep dive material for developers and not required for users.

2017-04-14 22:04 UTC, tgraf commented on Documentation/bpf.rst
> +for Cilium users to read, since Cilium abstracts eBPF internals away entirely.**
Let's move this and make it the first paragraph. You can use:

``
.. note:: This purely serves as a ...
``

prefix so it will appear as a note widget so it stands out a bit more.

2017-04-14 22:04 UTC, tgraf commented on Documentation/bpf.rst
> +The older cBPF architecture is not covered by this document, since Cilium does
I would drop the 'since Cilium' part

2017-04-14 22:04 UTC, tgraf commented on Documentation/bpf.rst
> +key / value stores, helper functions to interact with the kernel, tail calls for
helper functions to interact with and leverage kernel functionaly

2017-04-14 22:04 UTC, tgraf commented on Documentation/bpf.rst
> +  traffic interruptions.
Let's add that any program state can be maintained throughout updates via bpf maps.

2017-04-14 22:04 UTC, tgraf commented on Documentation/bpf.rst
> +  infrastructure and tooling (e.g., iproute2) as well as the safety guarantees that
Would be great to add an (e.g. ...) with a couple of examples of used kernel infrastructure.

2017-04-14 22:04 UTC, tgraf commented on Documentation/bpf.rst
> +  terminate, etc. XDP programs, for example, reuse the existing in-kernel drivers
Maybe move XDP down until you have properly introduced it. The XDP concept is completely unknown to the reader at this point.

2017-04-14 22:04 UTC, tgraf commented on Documentation/bpf.rst
> +the execution of the program once a packet is received.
Add a second example for kprobe attachment.

2017-04-14 22:04 UTC, tgraf commented on Documentation/bpf.rst
> +either spill them to the eBPF stack or move them to callee saved registers if these
Add a sentence to explains spilling.

2017-04-14 22:57 UTC, borkmann commented on Documentation/bpf.rst
> +  data, packet data, etc.
Fixed

2017-04-14 22:57 UTC, borkmann commented on Documentation/bpf.rst
> +   static inline functions or macros / definitions.
Fixed

2017-04-14 22:57 UTC, borkmann commented on Documentation/bpf.rst
> +   and ``egress``. The toy example code demonstrates that both can share a map
Fixed

2017-04-14 22:57 UTC, borkmann commented on Documentation/bpf.rst
> +  limitation. This also works accross tail calls, since it has the same guarantees
Fixed

2017-04-14 22:58 UTC, borkmann commented on Documentation/bpf.rst
> +  dumping additional attributes.
Wrote it as `view with`.

2017-04-14 22:58 UTC, borkmann commented on Documentation/bpf.rst
Fixed

2017-04-14 22:58 UTC, borkmann commented on Documentation/bpf.rst
> +BPF and XDP Guide
Fixed

2017-04-14 22:58 UTC, borkmann commented on Documentation/bpf.rst
> +for Cilium users to read, since Cilium abstracts eBPF internals away entirely.**
Fixed

2017-04-14 22:59 UTC, borkmann commented on Documentation/bpf.rst
> +either spill them to the eBPF stack or move them to callee saved registers if these
Fixed

2017-04-14 23:13 UTC, borkmann commented on Documentation/bpf.rst
> +The older cBPF architecture is not covered by this document, since Cilium does
Fixed

2017-04-14 23:13 UTC, borkmann commented on Documentation/bpf.rst
> +key / value stores, helper functions to interact with the kernel, tail calls for
Fixed

2017-04-14 23:19 UTC, borkmann commented on Documentation/bpf.rst
> +  traffic interruptions.
Fixed

2017-04-14 23:20 UTC, borkmann commented on Documentation/bpf.rst
> +kernel before program execution.
I think it's probably fine as is, but I'll double check to make sure.

2017-04-14 23:26 UTC, borkmann commented on Documentation/bpf.rst
> +  infrastructure and tooling (e.g., iproute2) as well as the safety guarantees that
Fixed

2017-04-14 23:35 UTC, borkmann commented on Documentation/bpf.rst
> +the execution of the program once a packet is received.
Fixed

2017-04-15 00:06 UTC, borkmann commented on Documentation/bpf.rst
> +  terminate, etc. XDP programs, for example, reuse the existing in-kernel drivers
Given it's kind of used throughout the doc (also in the more generic LLVM / iproute2 section), I tried to introduce XDP and tc terms at the very beginning now, but we could later on also still rearrange this a bit if we think a strict separation seems better.

2017-04-15 07:33 UTC, tgraf approved these changes

2017-04-15 07:33 UTC, tgraf commented
I'll provide more feedback directly as a PR but this is in great shape to go in already.

2017-04-15 08:56 UTC, merged

2017-04-15 08:57 UTC, borkmann commented
Perfect, thanks. I'll continue working on the remaining bits.

2017-04-15 15:00 UTC, borkmann commented on Documentation/bpf.rst
> +kernel before program execution.
(`an eBPF representation` is the correct form)