Updated step to modify kube-dns deployment for fixed identity
cilium/cilium pull request #5518
Opened 2018-09-11 06:22 UTC by ackerman80

Updated step to modify kube-dns deployment for fixed identity
Updated to included dependencies for cert generation scripts

Signed-off-by: Arvind Soni <arvindsoni@gmail.com>

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cilium/cilium/5518)

2018-09-11 06:22 UTC, ackerman80 commented
/test-docs-please

2018-09-11 15:12 UTC, ianvernon commented
test-docs-please

2018-09-11 15:13 UTC, ianvernon commented
@ackerman80 if you add a preceding `/` before the test trigger phrase, it will not work.

2018-09-11 15:13 UTC, ianvernon approved these changes

2018-09-11 15:47 UTC, aanm requested changes
This might require more steps. Blocking before merging

2018-09-11 17:23 UTC, ackerman80 commented
@aanm agreed. let me know your edits and I will update the docs along with testing them. Particularly unsure why we were getting multiple dns replica-sets today.

2018-09-13 12:35 UTC, aanm commented
@ackerman80 this will work:
for coredns
```
kubectl patch -n kube-system deployment/coredns --type merge -p '{"spec":{"template":{"metadata":{"labels":{"io.cilium.fixed-identity":"kube-dns"}}}}}'
```
for kube-dns
```
kubectl patch -n kube-system deployment/kube-dns --type merge -p '{"spec":{"template":{"metadata":{"labels":{"io.cilium.fixed-identity":"kube-dns"}}}}}'
```
you can also mention that by, default kubernetes keeps the old replicaset but it will not be running. If the deployment is deleted all replicasets are clean up and they are not left in the users's cluster.

For example the `coredns-5976949f76` is the one with the patch, `coredns-687db6485c` is the one without the patch.
```
$ kubectl get rs --all-namespaces
NAMESPACE     NAME                 DESIRED   CURRENT   READY     AGE
kube-system   coredns-5976949f76   1         1         1         1m
kube-system   coredns-687db6485c   0         0         0         1m
```

2018-09-13 19:13 UTC, ackerman80 commented
test-docs-please

2018-09-13 19:27 UTC, aanm approved these changes

2018-09-13 23:33 UTC, ianvernon submitted a review, later dismissed

2018-09-13 23:33 UTC, ianvernon commented on Documentation/kubernetes/install/eks.rst
> +   security policies before etcd is up. (Note: By default, kubernetes keeps the old replicaset
kubernetes --> Kubernetes

replicaset --> ReplicaSet (maybe surround in \`\`)?

2018-09-13 23:33 UTC, ianvernon commented on Documentation/kubernetes/install/eks.rst
> +   but those sets are not running. When the deployment is deleted all replicasets will be cleaned up
replicaset --> ReplicaSets

2018-09-13 23:33 UTC, ianvernon commented on Documentation/kubernetes/install/eks.rst
> +   This step allows Cilium to bring up kube-dns networking and enforce
you surround kube-dns with \`\` above, but not here. Do so for consistency.

2018-09-14 16:02 UTC, ackerman80 commented
test-docs-please

2018-09-14 17:17 UTC, ianvernon approved these changes

2018-09-14 17:17 UTC, merged