Test: Fail if a lock took more than 10 seconds.
cilium/cilium pull request #5534
Opened 2018-09-12 08:02 UTC by eloycoto

Deadlock detection has a lot of improvements in the last release, at the
moment we only count the number of locks that took more than 0.1 second,
but we don't fail if any lock take more than X.

This PR add a initial checker to check that the lock does not take more
than 10 seconds (related with issue #5532) and in the future we can fail
when it took more than a second.

At the moment, in Nightly the number is a bit high:

```
⚠️  Number of "Goroutine took lock for more than" in logs: 269
```

The reason to have 10 seconds and not 1 seconds is to start to fail
gradually and make the improvements step by step.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

2018-09-12 08:02 UTC, eloycoto commented
test-me-please

2018-09-12 20:09 UTC, ianvernon approved these changes

2018-09-13 10:11 UTC, aanm requested changes
This will make PRs to fail, although I agree it's a good idea we should merge this next week when the feature freeze window is closed. Otherwise this will probably make some PRs fail and we will have to trigger again causing a huge queue of unnecessary builds because of this.

2018-09-13 10:15 UTC, eloycoto commented
Hi @aanm 

As we spoke, this is a **safe-check** after the test has been passed, if a build fails because of this can be merged because all test work and we're going to address all the locks that are >10seconds.

Also, tested on Nightly, and in that given issue all the locks are under 0.8seconds, so IMHO this should be merged asap, and next week we should decrease it to >1 second.

2018-09-13 10:21 UTC, aanm commented
@eloycoto won't this make the `Cilium-Ginkgo-Tests` to have a red cross?

2018-09-13 22:37 UTC, tgraf commented
I like the PR but I think we should merge it after the compilation locks have been removed.

2018-09-18 18:03 UTC, ianvernon commented
Removing `ready-to-merge` label since we want to do this only after compilation locks are removed.

2018-11-21 20:27 UTC, ianvernon commented
@eloycoto this is quite a stale issue. I'm moving it to `wip` state.

2019-01-24 15:53 UTC, closed without merging