1.2 backports 18-09-12
cilium/cilium pull request #5541
Opened 2018-09-12 18:24 UTC by ianvernon

Backported PRs:

* #5319 (had some minor conflicts, @eloycoto please review)
* #5503
* #5513
   * I only backported commit 2c0385365cd930aba91590d3f8b36b010d3cfbeb, but not 724334bb037c93f3716602c3cdde149350b59af8 because 724334bb037c93f3716602c3cdde149350b59af8 fixed an issue in master that was not present in v1.2.
* #5515 - required fixing merge conflicts, but I was the author of the PR so I am confident in it working correctly.
* #5538 - required fixing merge conflicts. @aanm and @joestringer please review carefully.

*Not* backported PRs:

* #5445
    * Tons of merge conflicts. I do not think this needs to be backported because it fixes functionality that wasn't even added in the v1.2 branch. Replied on that PR with requested justification for need to backport.

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cilium/cilium/5541)

2018-09-12 18:25 UTC, ianvernon commented
test-me-please

2018-09-12 18:25 UTC, ianvernon commented
test-docs-please

2018-09-12 18:27 UTC, ianvernon commented
test-missed-k8s

2018-09-12 18:59 UTC, ianvernon commented
Build failed due to a rogue import:
```
18:55:12 test/helpers/node.go:24:2: imported and not used: "time"
```

Fixing...

2018-09-12 19:14 UTC, ianvernon commented
test-me-please

2018-09-12 19:14 UTC, ianvernon commented
test-docs-please

2018-09-12 19:14 UTC, ianvernon commented
test-missed-k8s

2018-09-13 15:19 UTC, ianvernon commented
Hit gofmt issues... will fix up and try again.

2018-09-13 15:21 UTC, ianvernon commented
test-me-please

2018-09-13 15:41 UTC, ianvernon commented
test-me-please

2018-09-13 17:00 UTC, joestringer commented on pkg/maps/ctmap/entry.go
> +type CtEntry struct {
This patch backport would be much simpler if the `Slave` field is just added to the existing CtEntry structure instead. Then the backport commit would also match line-for-line the commit being backported.

2018-09-13 17:02 UTC, joestringer requested changes
I'm inclined to request a simplification of the backport for #5538 , we shouldn't be refactoring the CtEntry in the backport. 

If you feel strongly about the current approach, feel free to dismiss this request for changes.

2018-09-13 18:32 UTC, ianvernon commented
> I'm inclined to request a simplification of the backport for #5538 , we shouldn't be refactoring the CtEntry in the backport.

@joestringer sure, not a problem. I'm all for smallest-possible deltas in backports :)

2018-09-13 18:44 UTC, ianvernon commented
@joestringer followed your recommendations.

2018-09-13 18:44 UTC, ianvernon commented
test-me-please

2018-09-13 20:07 UTC, ianvernon commented
Forgot to update `bpf.sha`, fixed and re-running tests.

2018-09-13 20:07 UTC, ianvernon commented
test-me-please

2018-09-13 21:05 UTC, joestringer approved these changes

2018-09-14 01:12 UTC, tgraf approved these changes

2018-09-14 01:12 UTC, merged