Metrics: Add Kubernetes events metrics
cilium/cilium pull request #5621
Opened 2018-09-19 14:10 UTC by eloycoto

Cilium has a watcher that read some events from Kubernetes to be able to
setup correctly the services, policies, pods, endpoints, etc..

This commit adds the support to show the number of Kubernetes events
received that are used by cilium, labelled by the result and the action
that it performs (delete, update, create)

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

Disclaimer: 
1) This pr change a lot of k8s_watcher functions return, the main logic is the same, I think that I did not change anything related to that. I also keep  the `return nil` in all the `ResourceEventHandlerFactory` I can change if you want to return err, but I'm not sure if is desired. 
2) The CNP apply will create two events each time, first the create event and after that an update event with the node status.

2018-09-19 14:18 UTC, eloycoto commented
test-me-please

2018-09-19 15:12 UTC, eloycoto commented
test-me-please

2018-09-19 16:21 UTC, ianvernon commented on daemon/k8s_watcher.go
> +	return policyImportErr
`policyImportErr` can be nil, but there are other errors that can occur within `cnpNodeStatusController`, which we would be hiding from the metric - I'm not sure what the best way of going about in ensuring that we capture all of these possible error states is, though.

2018-09-19 16:21 UTC, ianvernon commented on pkg/metrics/metrics.go
> +	// LabelAction is the label that need to be used for label metrics by actions
This documentation is self-referential, and as a result, isn't very useful. Provide an example of an action in the documentation here.

2018-09-19 21:02 UTC, tgraf requested changes

2018-09-19 21:02 UTC, tgraf commented on daemon/k8s_watcher.go
> +	metricKNP      = "kubernetesNetworkPolicy"
Let's use the standard names so just name this "NetworkPolicy". I would also capitalize all names so they match the k8s naming.

2018-09-19 21:02 UTC, tgraf commented on daemon/k8s_watcher.go
> +						return err
You are changing behavior here. nil was returned before.

2018-09-19 21:02 UTC, tgraf commented on daemon/k8s_watcher.go
> +	return policyImportErr
Those errors are reported via the controller metric

2018-09-19 21:02 UTC, tgraf commented on daemon/k8s_watcher.go
> +		return nil
👍

2018-09-20 07:20 UTC, eloycoto commented
test-me-please

2018-09-20 09:03 UTC, tgraf requested changes

2018-09-20 09:03 UTC, tgraf commented on daemon/k8s_watcher.go
> +	metricKNP      = "KubernetesNetworkPolicy"
This is still wrong. We should use the real name which is `NetworkPolicy` and not `KubernetesNetworkPolicy`.

2018-09-20 14:30 UTC, eloycoto commented
test-me-please

2018-09-20 14:47 UTC, tgraf approved these changes

2018-09-21 17:46 UTC, rlenglet submitted a review, later dismissed

2018-09-21 17:46 UTC, rlenglet commented on daemon/k8s_watcher.go
> -				return
This changes the flow of control. The point of this `if` is to not trigger a policy update below.
```
return nil
```

2018-09-21 17:46 UTC, rlenglet commented on daemon/k8s_watcher.go
> +		return fmt.Errorf("Unable to update some endpoints with new namespace labels")
`Errorf` -> `Error`

2018-09-21 17:46 UTC, rlenglet commented on daemon/k8s_watcher.go
> +		return fmt.Errorf("Unable to update some endpoints with new namespace labels")
`Unable` -> `unable`

2018-09-24 06:42 UTC, eloycoto commented
test-me-please

2018-09-24 07:08 UTC, eloycoto commented
test-me-please

2018-09-24 13:34 UTC, eloycoto commented
test-me-please

2018-09-24 16:12 UTC, rlenglet approved these changes

2018-09-24 18:34 UTC, aanm approved these changes

2018-09-25 06:44 UTC, eloycoto commented
test-me-please

2018-09-25 08:36 UTC, tgraf commented
test-me-please

2018-09-25 08:54 UTC, eloycoto commented
test-me-please

2018-09-25 11:15 UTC, merged