Documentation: some rewording and nitpicks
cilium/cilium pull request #563
Opened 2017-04-17 16:20 UTC by scanf

These are just suggestions that sound better to me. Let me know if I should reword more or drop any. Please see individual patches for more detail.

Thanks.

2017-04-17 16:34 UTC, aanm requested changes

2017-04-17 16:34 UTC, aanm commented on Documentation/intro.rst
> +microservices environments and traditional Linux network security approaches
`traditional Linux...` is repeated

2017-04-17 16:34 UTC, aanm commented on Documentation/gettingstarted.rst
> -Open a terminal and navigate into the top of the cilium source directory.
The visual of a console font helps me to see what are the commands I need to run without reading the whole paragraph. I like better the way it look.

2017-04-17 16:34 UTC, aanm commented on Documentation/gettingstarted.rst
> -    $
The `$` signals the user won't see anymore messages besides those 3.

2017-04-17 17:35 UTC, scanf commented on Documentation/intro.rst
> +microservices environments and traditional Linux network security approaches
Should be fixed but please verify.

2017-04-17 17:35 UTC, scanf commented on Documentation/gettingstarted.rst
> -Open a terminal and navigate into the top of the cilium source directory.
Reverted changes.

2017-04-17 17:36 UTC, scanf commented on Documentation/gettingstarted.rst
> -    $
ah, reverted.

2017-04-18 02:49 UTC, aanm submitted a review, later dismissed

2017-04-18 02:49 UTC, aanm commented on Documentation/intro.rst
> +rules that  need to be updated with a continuously growing frequency. Protocol
`that  need`
2 spaces between `that` and `need`

2017-04-18 06:11 UTC, scanf commented on Documentation/intro.rst
> +rules that  need to be updated with a continuously growing frequency. Protocol
Fixed.

2017-04-18 12:03 UTC, tgraf approved these changes

2017-04-18 12:03 UTC, merged