Update dns pod label modification
cilium/cilium pull request #5634
Opened 2018-09-19 22:01 UTC by techcet

Update command to edit kube-dns labelled pods.

2018-09-19 22:29 UTC, ianvernon commented
@techcet please sign off on your commit, c.f. [the Developer's Certificate of Origin](http://docs.cilium.io/en/v1.2/contributing/#developer-s-certificate-of-origin)

2018-09-19 22:30 UTC, ianvernon requested changes

2018-09-19 22:30 UTC, ianvernon commented on examples/kubernetes/addons/etcd-operator/README.md
> +# if using kube-dns
Add three backticks around each `kubectl patch` command, e.g. \`\`\` <command> \`\`\`

2018-09-21 09:18 UTC, aanm approved these changes

2018-09-26 16:27 UTC, techcet commented on examples/kubernetes/addons/etcd-operator/README.md
> +# if using kube-dns
Done

2018-09-26 17:51 UTC, techcet commented
@ianvernon I suspect I may have made edits directly on the GH webpage, and missed the sign-off that I usually do with my normal workflow. How does it look now?

2018-09-26 17:52 UTC, ianvernon approved these changes

2018-09-26 17:53 UTC, ianvernon commented
@techcet LGTM, merging. No need to run CI since this is just a README change.

2018-09-26 17:53 UTC, merged

2018-09-28 01:33 UTC, techcet commented
Request to backport for 1.2.3 (Ubuntu 18.04 blog references this README).