k8s: create Missing Function for K8sService
cilium/cilium pull request #5644
Opened 2018-09-20 14:51 UTC by aanm

With this commit, Cilium will no longer send unnecessary AddFunc events
and running useless operations for services that have non-relevant
changes.

Signed-off-by: André Martins <andre@cilium.io>

Read per commit basis.

```release-note
Stop triggering unnecessary loadbalancer setups for every Kubernetes service watch event.
```

Depends on https://github.com/cilium/cilium/pull/5642

2018-09-20 15:03 UTC, tgraf requested changes

2018-09-20 15:03 UTC, tgraf commented on daemon/k8s_watcher.go
> +		fmt.Printf("Me me nil? %+v\n", k8sSvc)
Leftover

2018-09-20 17:37 UTC, aanm commented
@nebril can you take a look? I just want to make sure I don't miss anything since the headless services also affect the policy, and you are more familiarized with that code.

2018-09-20 20:47 UTC, tgraf approved these changes

2018-09-21 23:21 UTC, aanm commented
test-me-please

2018-09-22 07:12 UTC, tgraf commented
test-missed-k8s

2018-09-22 15:10 UTC, tgraf commented
test-missed-k8s

2018-09-24 09:37 UTC, tgraf commented
Changed release not level. We'll point this out as one big major item.

2018-09-24 09:38 UTC, merged