policy: fixed LookupLocked bug
cilium/cilium pull request #565
Opened 2017-04-17 19:22 UTC by aanm

This commit gives consistency to the LookupLocked function since
searching `io.cilium` returned `io` as parent and `cilium` as node. The
same principle should be applied if some searches `io` and `io` doesn't
exist, thus if LookupLocked should return `root` as parent and `io`,
if found, as node.

Signed-off-by: André Martins <andre@cilium.io>

2017-04-17 19:23 UTC, aanm commented
The `LookupLocked` doesn't exist in `0.8` but there's a similar function, should we backport to that function as well?

2017-04-17 20:03 UTC, tgraf requested changes

2017-04-17 20:03 UTC, tgraf commented on pkg/policy/utils.go
> +	return strings.TrimLeft(path, cut)
This does not do what you think it does. It trims a cutset, not a prefix.

2017-04-17 20:34 UTC, aanm commented on pkg/policy/utils.go
> +	return strings.TrimLeft(path, cut)
Fixed!

2017-04-17 23:38 UTC, tgraf commented
I'm fine with the changes. Please describe the exact new behaviour in the documentation of the function though.

2017-04-18 02:33 UTC, aanm commented
Looks good?

2017-04-18 11:55 UTC, tgraf approved these changes

2017-04-18 11:55 UTC, merged