Metrics: Add subroutines metrics
cilium/cilium pull request #5673
Opened 2018-09-24 15:27 UTC by eloycoto

When cilium starts it creates a few new process in background that are
used for multiple things.

With this change, all this subroutines (envoy, health, monitor) will
trigger a new metric when starts. The idea behind is to know if a
process is restarting a lot.

Sample data:

```
->cilium metrics list | grep subro
cilium_subroutine_start_total                       scope="cilium-envoy"                                    1.000000
cilium_subroutine_start_total                       scope="cilium-health"                                   1.000000
cilium_subroutine_start_total                       scope="cilium-node-monitor"                             1.000000
->
```

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

2018-09-24 17:14 UTC, eloycoto commented
test-me-please

2018-09-24 17:37 UTC, joestringer requested changes
Thanks for the PR, I made some minor suggestions.

`subroutine` is a bit misleading to me; that has a specific meaning historically which is more to do with routines/functions and I believe that in this case `subprocess` is more accurate.

2018-09-24 17:37 UTC, joestringer commented on pkg/metrics/metrics.go
> +		Help:      "Number of times that a subroutine has started by Cilium labeled by scope",
`Number of times that Cilium has started a subprocess, labeled by scope`.

2018-09-24 18:42 UTC, aanm requested changes

2018-09-24 18:42 UTC, aanm commented on Documentation/configuration/metrics.rst
> +* ``subroutine_start_total``: Number of times that a subroutine has started by
Subroutine might give the impression that is a go routine, I would use "child processes" or "sub-processes"?

2018-09-24 22:14 UTC, joestringer commented on pkg/metrics/metrics.go
> +	}, []string{LabelScope})
Should it be `scope` or `subsystem`?

I was thinking of scope as similar to a programming language scope:

```
scope1 {
  scope2 {
    (part of scope1 and scope 2)
  }
  (part of only scope1)
}
```

2018-09-25 07:03 UTC, eloycoto commented
test-me-please

2018-09-25 08:45 UTC, tgraf approved these changes

2018-09-25 08:46 UTC, merged