proxylib: Make xDS node-id configurable.
cilium/cilium pull request #5704
Opened 2018-09-26 20:21 UTC by jrajahalme

Cilium needs to distinguish between ACKs from the NPDS clients
connecting from Envoy and proxylib. It also needs to separate between
NPDS clients connecting from the host proxy vs. sidecars. To
facilitate this the node-id used by the proxylib's NPDS client needs
to be configurable.

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

2018-09-26 20:57 UTC, jrajahalme commented
test-me-please

2018-09-26 22:56 UTC, rlenglet requested changes
LGTM after you address the style and formatting issues. Thanks!

2018-09-26 22:56 UTC, rlenglet commented on proxylib/proxylib.go
> +	var accessLogPath, xdsPath, nodeId string
+1

2018-09-26 22:56 UTC, rlenglet commented on proxylib/proxylib/instance.go
> +func OpenInstance(nodeId string, xdsPath string, newPolicyClient func(path, nodeId string, updater PolicyUpdater) PolicyClient,
+1

2018-09-26 22:56 UTC, rlenglet commented on proxylib/proxylib/instance.go
> +
go-fmt to remove the extra spaces.

2018-09-26 22:56 UTC, rlenglet approved these changes

2018-09-26 22:58 UTC, rlenglet commented
Your CI build failure is only due to the formatting issues:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/6751/execution/node/92/log/?consoleFull
```
00:07:54.019     runtime: Unformatted Go source code:
00:07:54.019     runtime: ./proxylib/proxylib/instance.go
00:07:54.019     runtime: diff -u ./proxylib/proxylib/instance.go.orig ./proxylib/proxylib/instance.go
00:07:54.019     runtime: --- ./proxylib/proxylib/instance.go.orig	2018-09-26 21:05:19.994441281 +0000
00:07:54.019     runtime: +++ ./proxylib/proxylib/instance.go	2018-09-26 21:05:19.994441281 +0000
00:07:54.019     runtime: @@ -66,7 +66,7 @@
00:07:54.019     runtime:  	accessLogPath string, newAccessLogger func(accessLogPath string) AccessLogger) uint64 {
00:07:54.019     runtime:  	mutex.Lock()
00:07:54.019     runtime:  	defer mutex.Unlock()
00:07:54.019     runtime: -	
00:07:54.019     runtime: +
00:07:54.019     runtime:  	// Check if have an instance with these params already
00:07:54.019     runtime:  	for id, old := range instances {
00:07:54.019     runtime:  		if (nodeId == "" || old.nodeId == nodeId) && old.xdsPath == xdsPath && old.accessLogPath == accessLogPath {
00:07:54.019     runtime: Makefile:231: recipe for target 'precheck' failed
00:07:54.019     runtime: make: *** [precheck] Error 1
```

2018-09-26 23:32 UTC, jrajahalme commented on proxylib/proxylib/instance.go
> +func OpenInstance(nodeId string, xdsPath string, newPolicyClient func(path, nodeId string, updater PolicyUpdater) PolicyClient,
changed.

2018-09-26 23:33 UTC, jrajahalme commented on proxylib/proxylib.go
> +	var accessLogPath, xdsPath, nodeId string
ditto.

2018-09-26 23:36 UTC, jrajahalme commented
test-me-please

2018-09-27 07:57 UTC, tgraf approved these changes

2018-09-27 07:57 UTC, merged