agent: Fix temporary corruption of BPF endpoint map on restart
cilium/cilium pull request #5706
Opened 2018-09-26 21:27 UTC by jrfastab

Backports

#5663 (note on backport: resolved conflicts by hand)

---
[ upstream commit 4ecf111c35f047f490f5cc8858d23c15e342541f ]

Due to deleting and repopulating the BPF endpoint map on startup. Cilium agent
restarts would introduce a race window of a couple of seconds [0] in which
local endpoints would not be reachable. This would result in packet drops or
depending on the routing path, a routing loop which eventually leads to a drop
followed by a ICMP TTL exceeded.

[0] The race window for host IPs was in the microseconds range. The race
window for endpoints depended on the number of local endpoints and etcd
latency as the endpoint would reappear as it was regenerated on restore.

Fixes: #5651

Signed-off-by: Thomas Graf <thomas@cilium.io>
Signed-off-by: John Fastabend <john.fastabend@gmail.com>

2018-09-26 21:27 UTC, jrfastab commented
test-me-please

2018-09-27 07:56 UTC, tgraf requested changes
Please pull in https://github.com/cilium/cilium/pull/5708 that was just merged as it fixes the commit being backported here.

2018-09-27 15:17 UTC, jrfastab commented
test-me-please

2018-09-27 16:25 UTC, jrfastab commented
test-me-please

2018-09-27 16:28 UTC, tgraf approved these changes

2018-09-27 17:11 UTC, jrfastab commented
tests added in commit, https://github.com/cilium/cilium/pull/5708/commits/299c8fa6bbb9c2e23318a0a4921917a7eb0d50a3 do not appear to be in v1.0 or at very list are missing some other piece. Rerun tests without them for now.

2018-09-27 17:11 UTC, jrfastab commented
test-me-please

2018-09-27 18:00 UTC, jrfastab commented
test-me-please

2018-09-27 18:34 UTC, jrfastab commented
test-me-please

2018-09-27 19:43 UTC, jrfastab commented
test-me-please

2018-09-27 20:29 UTC, jrfastab commented
test-me-please

2018-09-27 23:47 UTC, jrfastab commented
test-me-please

2018-09-28 02:27 UTC, jrfastab commented
test-me-please

2018-09-28 04:05 UTC, jrfastab commented
test-me-please

2018-09-28 08:16 UTC, eloycoto approved these changes

2018-09-28 08:16 UTC, merged