make: Clean go cache before running go vet
cilium/cilium pull request #5736
Opened 2018-10-01 07:26 UTC by mrostecki

Sometimes `go vet` checks become unrelialable when old Cilium's
code is cached. To ensure that `go vet` will always check fresh
code, cache should be cleaned.

Fixes #5670

Signed-off-by: Michal Rostecki <mrostecki@suse.de>

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cilium/cilium/5736)

2018-10-01 07:28 UTC, mrostecki commented
test-me-please

2018-10-01 15:43 UTC, ianvernon approved these changes

2018-10-01 15:46 UTC, tgraf commented
@mrostecki What does this mean in terms of added build time?

2018-10-01 18:23 UTC, ianvernon commented
@tgraf does make a good point - would be good to compare the amount of time it takes to build Cilium with and without this change to see if there is a significant change in build time, as we do not want to increase CI build-time unless we have to. However, there is a correctness aspect to this, in that we don't want to commit code that fails `go vet` :/

2018-10-01 21:13 UTC, mrostecki commented
When I'm just running `go clean ...` once after a build, it takes no more than 2 seconds.

But forloop with `time` seems to provide worse results. For now I did a small check locally.

```
 mrostecki   go-vet-clean-cache  …  github.com  cilium  cilium  time for i in {1..20}; do make precheck &>/dev/null; done

real	2m26.897s
user	2m38.965s
sys	0m18.280s
 mrostecki   go-vet-clean-cache  …  github.com  cilium  cilium  git checkout master 
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
 mrostecki   master  …  github.com  cilium  cilium  time for i in {1..20}; do make precheck &>/dev/null; done

real	1m13.562s
user	1m27.408s
sys	0m10.754s
```

But maybe I should compare it on CI by submitting some other PR which will print `time` output on Jenkins. I will do it tomorrow.

2018-10-01 21:15 UTC, mrostecki commented
test-me-please

2018-10-01 21:19 UTC, mrostecki commented
Ah, and I added yet another `go vet` fix, I didn't rebase with master when I submitted this PR at the first time.

2018-10-01 21:44 UTC, tgraf commented
The diff doesn't seem that big for 20 runs so I'm fine with it.

2018-10-01 21:47 UTC, ianvernon approved these changes

2018-10-01 21:52 UTC, jrajahalme commented
I'd expect the CI to start with empty caches, so the impact should be negligible there. It's more interesting to see the impact on a `make` in a dev VM:
- `time make` without cleaning: 41 secs
- `time make` after `go clean ...`: 53 secs

2018-10-01 21:52 UTC, jrajahalme approved these changes

2018-10-01 21:54 UTC, jrajahalme requested changes
Why is `endpoint.go` changed here?

2018-10-01 21:54 UTC, ianvernon commented
@jrajahalme to make `go vet` succeed

2018-10-01 21:56 UTC, jrajahalme approved these changes

2018-10-01 21:57 UTC, jrajahalme commented
So we had code in master that did not pass go vet? Nice :-)

2018-10-01 22:02 UTC, jrajahalme commented
@ianvernon I'm building with the `govet` target change without applying any changes to `pkg/endpoint`. See no vet errors, wonder why?

@tgraf build time with the clearing the cache before `go vet`: 105 seconds, a full minute more than before this change.

2018-10-01 22:15 UTC, tgraf commented
> build time with the clearing the cache before `go vet`: 105 seconds, a full minute more than before this change

In the vagrant box with NFS?

2018-10-01 23:40 UTC, jrajahalme commented
@tgraf Yes.

2018-10-02 09:19 UTC, aanm requested changes
Running **without** govet, **without** ineffassign and **without** check-fmt.sh
```
$ make clean
$ time SKIP_DOCS=true CILIUM_DISABLE_ENVOY_BUILD=1 make
Build finished.

real    0m29.459s
user    0m29.491s
sys     0m4.672s
$
$ # 2nd compilation
$ time SKIP_DOCS=true CILIUM_DISABLE_ENVOY_BUILD=1 make
Build finished.

real    0m2.898s
user    0m2.875s
sys     0m0.845s
```
Running with master
```
$ make clean
$ time SKIP_DOCS=true CILIUM_DISABLE_ENVOY_BUILD=1 make
Build finished.

real    0m32.068s
user    0m34.203s
sys     0m4.769s
$
$ # 2nd compilation
$ time SKIP_DOCS=true CILIUM_DISABLE_ENVOY_BUILD=1 make
Build finished.

real    0m6.204s
user    0m6.882s
sys     0m1.138s
```
Running with this PR (`$(GO) clean -cache github.com/cilium/cilium/...`)
```
$ make clean
$ time SKIP_DOCS=true CILIUM_DISABLE_ENVOY_BUILD=1 make
Build finished.

real    1m0.026s
user    2m7.812s
sys     0m15.368s
$
$ # 2nd compilation
$ time SKIP_DOCS=true CILIUM_DISABLE_ENVOY_BUILD=1 make
Build finished.

real    0m44.635s
user    1m50.391s
sys     0m13.391s
```

2018-10-02 09:19 UTC, aanm commented on Makefile
> +	$(GO) clean -cache github.com/cilium/cilium/...
This will cause the builds to be slow.

2018-10-02 10:52 UTC, tgraf commented
Can we enable it for the CI only?

2018-10-02 15:44 UTC, jrajahalme commented
CI build failed to an agent-crash related to endpoint locking during restoration: https://github.com/cilium/cilium/issues/5757

2018-10-02 15:51 UTC, jrajahalme commented
IMO we should understand why this would be needed in the first place. E.g., what are the conditions for the issue to arise? Is it potentially related to go version change while caches were not cleaned? That is, why should caching make a difference given that the go compiler and the tools in particular do not change?

Given the above and the hit this causes on (iterative) compilation times, I second @tgraf in enabling this for the CI only (where we are not rebuilding anyway).

2018-10-02 15:51 UTC, jrajahalme commented
test-me-please

2018-10-02 15:52 UTC, jrajahalme commented
Building again to see if the crash repeats. If yes, then it may be due to the code changes in this PR.

2018-10-03 16:00 UTC, ianvernon commented
I suspect the endpoint mutex changes broke something here. Moving back to wip.

2018-10-05 10:24 UTC, vadorovsky commented
@jrajahalme Caching is not related to Go version differences. `go vet` just tends to be not reproducible without cleaning cache.

But I totally understand concerns about build time. Enabling this on CI only sounds good. I will just move cache clean to the separate `make` target which is going to be used by CI.

And of course I will take a look at endpoint mutex problem

2018-10-25 13:20 UTC, closed without merging