pkg/node: delete tunnel routes when remote nodes are removed
cilium/cilium pull request #5752
Opened 2018-10-01 23:45 UTC by ianvernon

Fixes: #5421

Signed-off by: Ian Vernon <ian@cilium.io>

2018-10-01 23:45 UTC, ianvernon commented
test-me-please

2018-10-02 09:04 UTC, aanm approved these changes

2018-10-02 10:05 UTC, raybejjani approved these changes

2018-10-02 10:05 UTC, raybejjani commented on pkg/node/manager.go
> +			deleteIPRoute(n)
Should the routes be removed before the tunnel? I'm not sure which which leads to which.

2018-10-02 10:11 UTC, raybejjani submitted a review, later dismissed
on chatting with @tgraf, apparently this deleteIPRoute won't do what we intend. In particular (and he'll have to explain this better), `deleteIPRoute` is for direct routing and we'd need to remove the route for the node's CIDR block (I think, I probably understood it incorrectly).

2018-10-02 10:44 UTC, tgraf requested changes

2018-10-02 10:44 UTC, tgraf commented on pkg/node/manager.go
> +			deleteIPRoute(n)
deleteIPRoute is currently tailored to direct routing rules. We have to reverse `replaceNodeRoute()`

2018-10-02 20:34 UTC, ianvernon commented
test-me-please

2018-10-02 20:35 UTC, ianvernon commented
From what I could grok from looking at the code, we just need to call `deleteIPRoute` with the node's IPv4 and IPv6 CIDRs. I did the following locally:

```
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ ip route show | grep cilium_host
10.0.0.0/16 via 10.0.0.1 dev cilium_host src 10.0.0.1 
10.0.0.1 dev cilium_host scope link 
10.1.0.0/16 via 10.0.0.1 dev cilium_host src 10.0.0.1 
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ kubectl get nodes 
NAME      STATUS    ROLES     AGE       VERSION
k8s1      Ready     <none>    2h        v1.11.3
k8s2      Ready     <none>    1h        v1.11.3
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ kubectl delete node k8s2
node "k8s2" deleted
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ kubectl get nodes 
NAME      STATUS    ROLES     AGE       VERSION
k8s1      Ready     <none>    2h        v1.11.3
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ ip route show | grep cilium_host
10.0.0.0/16 via 10.0.0.1 dev cilium_host src 10.0.0.1 
10.0.0.1 dev cilium_host scope link 
```

Is this what is expected?

2018-10-02 20:38 UTC, tgraf commented
> Is this what is expected?

Yes, this is what is being expected. So it seems to work by accident. The function was definitely not intended to delete arbitrary node routes. Looking at the exact implementation, it does in fact work reliably.

2018-10-02 20:38 UTC, tgraf approved these changes

2018-10-02 22:51 UTC, merged