daemon / kvstore: add kvstore flag for daemon CLI
cilium/cilium pull request #584
Opened 2017-04-19 23:25 UTC by ianvernon

daemon: add kvstore flag for cilium-daemon CLI and allowed types of kvstores in kvstore pkg
kvstore: add kvstore type and officially supported kvstore types

Signed-off by: Ian Vernon <ian@covalent.io>

Fixes: #387

2017-04-20 12:25 UTC, tgraf requested changes

2017-04-20 12:25 UTC, tgraf commented on daemon/daemon.go
> +			log.Warningf("Invalid configuration for consul provided; using local storage.")
I think we should error out in this case with a message such as "Please specify the address to a consul instance with the --consul option" as the user explicitly asked for a consul kvstore.

2017-04-20 12:25 UTC, tgraf commented on daemon/main.go
> +		log.Warningf("unsupported key-value store provided; using local storage for key-value store")
I think we should handle "no option" specified differently from an unknown kvstore type specified. Unknown should error out. No option should default to local storage without a warning of an unknown kvstore type

2017-04-20 12:25 UTC, tgraf commented on pkg/kvstore/kvstore.go
> +)
👍

2017-04-21 21:43 UTC, aanm requested changes
Just small nits

2017-04-21 21:43 UTC, aanm commented on daemon/daemon.go
> +			return nil, fmt.Errorf("Invalid configuration for consul provided; please specify the address to a consul instance with the --consul option")
On returned errors, start the sentences with small case.

2017-04-21 21:43 UTC, aanm commented on daemon/main.go
> +		return
No need for `return` here, `log.Fatalf` exits the program:
```
// Fatalf is equivalent to l.Critical followed by a call to os.Exit(1).
func (l *Logger) Fatalf(format string, args ...interface{}) {
	l.log(CRITICAL, format, args...)
	os.Exit(1)
}
```

2017-04-21 21:43 UTC, aanm commented on daemon/main.go
> +		log.Fatalf("unsupported key-value store \"%s\" provided", kvStore)
Upper case instead of small. Also, go has `%q` to quote strings (only strings!)

2017-04-21 21:43 UTC, aanm commented on daemon/daemon.go
> +		return nil, fmt.Errorf("Invalid key-value store type provided; please use one of the following: %s, %s, %s", kvstore.Consul, kvstore.Etcd, kvstore.Local)
I was wondering if we should check for this in `daemon/main.go:initEnv()`

2017-04-24 22:24 UTC, ianvernon commented on daemon/daemon.go
> +		return nil, fmt.Errorf("Invalid key-value store type provided; please use one of the following: %s, %s, %s", kvstore.Consul, kvstore.Etcd, kvstore.Local)
Is initEnv where all validation of passed in parameters to the daemon should be done?

2017-04-24 22:30 UTC, tgraf commented on daemon/daemon.go
> +		return nil, fmt.Errorf("Invalid key-value store type provided; please use one of the following: %s, %s, %s", kvstore.Consul, kvstore.Etcd, kvstore.Local)
We typically added all validations to `initEnv()` and start running stuff in `runDaemon()`

2017-04-24 22:55 UTC, ianvernon commented on daemon/daemon.go
> +		return nil, fmt.Errorf("Invalid key-value store type provided; please use one of the following: %s, %s, %s", kvstore.Consul, kvstore.Etcd, kvstore.Local)
OK, thanks! I'll take care of that.

2017-04-25 00:21 UTC, ianvernon commented on daemon/daemon.go
> +			return nil, fmt.Errorf("Invalid configuration for consul provided; please specify the address to a consul instance with the --consul option")
fixed

2017-04-25 00:21 UTC, ianvernon commented on daemon/daemon.go
> +		return nil, fmt.Errorf("Invalid key-value store type provided; please use one of the following: %s, %s, %s", kvstore.Consul, kvstore.Etcd, kvstore.Local)
Moved validation to initEnv in latest upload.

2017-04-25 00:21 UTC, ianvernon commented on daemon/main.go
> +		log.Fatalf("unsupported key-value store \"%s\" provided", kvStore)
Done.

2017-04-25 00:22 UTC, ianvernon commented on daemon/main.go
> +		log.Warningf("unsupported key-value store provided; using local storage for key-value store")
Done.

2017-04-25 00:22 UTC, ianvernon commented on daemon/daemon.go
> +			log.Warningf("Invalid configuration for consul provided; using local storage.")
Done.

2017-04-25 00:47 UTC, aanm requested changes

2017-04-25 00:47 UTC, aanm commented on daemon/config.go
> +		log.Infof("using consul as key-value store")
Why not a `log.Infof("using etcd as key-value store")` for `etcd`? :(

2017-04-25 00:47 UTC, aanm commented on daemon/daemon.go
> +			return nil, fmt.Errorf("invalid configuration for etcd provided; please specify an etcd configuration path with --etcd-config-path and an etcd agent address with --etcd")
The error should be: "invalid configuration for etcd provided; please specify an etcd configuration path with --etcd-config-path ~and~ **or** an etcd agent address with --etcd"

2017-04-25 08:38 UTC, tgraf approved these changes

2017-04-25 09:04 UTC, aanm approved these changes

2017-04-25 09:14 UTC, merged