test: install Cilium before creating any pods in upgrade test
cilium/cilium pull request #5850
Opened 2018-10-10 12:46 UTC by aanm

As Cilium is installed with with the clean state it can delete the
connectivity endpoints recently created before deploying Cilium causing
the test to fail.

Signed-off-by: André Martins <andre@cilium.io>

2018-10-10 12:47 UTC, aanm commented
test-me-please

2018-10-10 12:54 UTC, eloycoto requested changes

2018-10-10 12:54 UTC, eloycoto commented on test/k8sT/Updates.go
>  		By("Cilium %q is installed and running", oldVersion)
Quick one, with that changes that line should be in the top, 140 no? After ExpectCiliumReady I think.

I'm refering to this line: 
```
By("Cilium %q is installed and running", oldVersion)
```

2018-10-10 13:22 UTC, aanm commented on test/k8sT/Updates.go
>  		By("Cilium %q is installed and running", oldVersion)
You know, when I looked at this line before pushing the branch it seemed to "close" to the line 147 I read the `"Cilium %q is installed and running"` and it seemed that was in the right place. 

Fixed

2018-10-10 13:24 UTC, aanm commented
test-me-please

2018-10-10 13:24 UTC, eloycoto approved these changes

2018-10-10 15:02 UTC, ianvernon approved these changes

2018-10-10 18:02 UTC, aanm commented
test-me-please

2018-10-10 20:33 UTC, aanm commented
test-me-please

2018-10-11 07:28 UTC, eloycoto approved these changes

2018-10-11 07:28 UTC, merged