move prefilter code to pkg/datapath
cilium/cilium pull request #5894
Opened 2018-10-15 22:07 UTC by ianvernon

This code was in `pkg/policy` but is used for configuring the datapath
directly, and does not tie into the policy repository. Refactor it into
`pkg/datapath` accordingly.

Fixes: #5865

Signed-off by: Ian Vernon <ian@cilium.io>

2018-10-15 22:08 UTC, ianvernon commented
test-me-please

2018-10-16 15:31 UTC, aanm requested changes

2018-10-16 15:31 UTC, aanm commented on pkg/datapath/prefilter/prefilter.go
>  // See the License for the specific language governing permissions and
Change copyright header date

2018-10-16 15:33 UTC, ianvernon commented on pkg/datapath/prefilter/prefilter.go
>  // See the License for the specific language governing permissions and
Done.

2018-10-16 15:33 UTC, ianvernon commented
Prior build was green, and I only changed the copyright header. The file is correctly formatted:

```
$ go fmt pkg/datapath/prefilter/prefilter.go
Ians-MBP:cilium ianvernon$
```

IMO this can be merged without running the CI again provided there are no other comments.

2018-10-16 17:05 UTC, aanm commented
test-me-please

2018-10-16 17:05 UTC, aanm approved these changes

2018-10-16 17:21 UTC, joestringer approved these changes
:shipit:

2018-10-16 17:39 UTC, merged