fqdn: Make Rule UUIDs random instead of depending on the labels.
cilium/cilium pull request #5897
Opened 2018-10-15 23:01 UTC by jrajahalme

Rules may not have any labels and many rules may share the same
labels. Therefore a rule can't be uniquely identified by it's labels.

Generate a random rule UUID for each rule with "toFQDNs" so that we
can identify the same rule when needed for an update.

Unit tests are updated to not assume a stable UUID for a given set of
labels. Tests are also modified to make sure each rule has a unique
UUID regardless of it's labels, and that UUID is generated also if the
rule has no labels.

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

2018-10-15 23:02 UTC, jrajahalme commented
test-me-please

2018-10-16 15:43 UTC, raybejjani requested changes
I'm sorry you had to look through the tests! they're quite obtuse. Thank you!
The UUIDs started as random, a long time ago, but I replaced them because we needed a consistent UUID when we replaced rules (i.e. on insert into the agent). If we change the toFQDNs list in an existing rule and `kubectl apply` the replace doesn't correctly remove names to be polled etc. but, more critically, we never replace the older rule data in `poller.allRules` because the new rule receives a new random UUID.

I prefer the random UUID, and this should sort this one case out:
```
diff --git a/daemon/policy.go b/daemon/policy.go
index a18ea4a6a..e76d5040f 100644
--- a/daemon/policy.go
+++ b/daemon/policy.go
@@ -211,6 +211,7 @@ func (d *Daemon) PolicyAdd(rules policyAPI.Rules, opts *AddOptions) (uint64, err
                        for _, r := range rules {
                                tmp := d.policy.SearchRLocked(r.Labels)
                                if len(tmp) > 0 {
+                                       d.dnsPoller.StopPollForDNSName(tmp)
                                        d.policy.DeleteByLabelsLocked(r.Labels)
                                }
                        }
@@ -218,6 +219,7 @@ func (d *Daemon) PolicyAdd(rules policyAPI.Rules, opts *AddOptions) (uint64, err
                if len(opts.ReplaceWithLabels) > 0 {
                        tmp := d.policy.SearchRLocked(opts.ReplaceWithLabels)
                        if len(tmp) > 0 {
+                               d.dnsPoller.StopPollForDNSName(tmp)
                                d.policy.DeleteByLabelsLocked(opts.ReplaceWithLabels)
                        }
                }
```

Unrelated to this PR, there is a race between the DNSPoller controller (`LookupUpdateDNS`) updating `poller.allRules` and adding new ones. I don't think that's happening here, and I've been meaning to replace allRules with a lookup into the policy repository, but in case you saw this behaviour this might be the reason.

Feel free to merge with the change above or some variant. I'm requesting changes to stop tgraf from optimistically merging this ;)

2018-10-16 15:52 UTC, jrajahalme commented
@raybejjani AFAIK we never add new rules for FQDN, but augment existing ones. Those rules have the original labels derived from k8s namespace and CRD name and will be deleted when the CNP CRD is replaced or deleted. Are you saying that rule removal from the policy repository is not enough to clean out the state hold in the poller for the removed rule?

2018-10-16 15:56 UTC, jrajahalme commented
@raybejjani OK, I see PolicyDelete() has the equivalent of what you suggested above, will add those.

2018-10-16 16:07 UTC, jrajahalme commented
test-me-please

2018-10-16 16:08 UTC, jrajahalme commented
Added `StopPollForDNSName()` calls for the replaced rules to clean up DNS poller state & rebased.

2018-10-16 16:40 UTC, raybejjani approved these changes
@jrajahalme exactly so. I've discussed adding hooks of some sort into the policy repo to catch the add/delete events. This would then simplify some of this logic with respect to both toFQDNs and toServices (we could reuse the part of the rule translator stuff in the k8s package).

2018-10-16 17:58 UTC, merged

2018-10-29 11:47 UTC, raybejjani commented
1.2 backport was in https://github.com/cilium/cilium/pull/6035