pkg/bpf: generate ASM output if debug enabled
cilium/cilium pull request #599
Opened 2017-04-24 23:49 UTC by ianvernon

pkg/endpoint: add GetDebug to Owner interface
daemon: regenerate bindata to account for changes in pkg/bpf/join_ep.sh

Add GetDebug to Owner interface, implement in daemon, and utilize this method to determine whether debug mode is enabled to pass in as a parameter to join_ep.sh to generate ASM when BPF is generated.

Signed-off by: Ian Vernon <ian@covalent.io>

2017-04-24 23:53 UTC, tgraf requested changes

2017-04-24 23:53 UTC, tgraf commented on daemon/daemon.go
> +func (d *Daemon) GetDebug() bool {
I would pay more attention to hound if they'd use a puppy as a logo but we should add a comment to the function nevertheless.

2017-04-25 00:25 UTC, ianvernon commented on daemon/daemon.go
> +func (d *Daemon) GetDebug() bool {
Will do - I'll only add reviewers after I placate the hound in the future :)

2017-04-25 01:05 UTC, aanm requested changes
@tgraf should we also generate ASM output of `bpf_netdev`, `bpf_lb` and `bpf_overlay`?

2017-04-25 01:05 UTC, aanm commented on daemon/daemon.go
> +func (d *Daemon) GetDebug() bool {
Why not `DebugEnabled()`? In consistency with the `DryModeEnabled()` and `TracingEnabled()`

2017-04-25 01:12 UTC, ianvernon commented on daemon/daemon.go
> +func (d *Daemon) GetDebug() bool {
Fixed in latest upload.

2017-04-25 08:36 UTC, tgraf commented
> @tgraf should we also generate ASM output of bpf_netdev, bpf_lb and bpf_overlay?

I think this is fine to get started. There is no code generation for these static programs so one can always invoke clang manually to generate it.

2017-04-25 08:36 UTC, tgraf approved these changes

2017-04-25 09:05 UTC, aanm approved these changes

2017-04-25 09:14 UTC, merged