daemon: change policyAdd message type from Info to Debug
cilium/cilium pull request #6019
Opened 2018-10-23 11:11 UTC by aanm

Also, change the way we print the rules by also printing all fields
names of the policy being imported.

Fixes: b0aeb2888ac6 ("policy/api: add String function for Rules type")
Signed-off-by: André Martins <andre@cilium.io>

2018-10-23 11:11 UTC, aanm commented
test-me-please

2018-10-23 14:06 UTC, tgraf commented
The info message was quite useful in the past. What is the motivation to turn it into a Debug?

2018-10-23 14:19 UTC, aanm commented
@tgraf it's extremely verbose when importing a rule that contains a DNS rule as the DNS poller is calling policyAdd every 5 seconds.

2018-10-23 14:25 UTC, tgraf commented
@aanm Even if the poller is returning a constant list of IPs? Is it the random ordering or constantly changing subset of IPs that makes it verbose?

2018-10-23 15:25 UTC, ianvernon commented
Being able to see what rules we are adding to the repository is crucial to know, even at Info level. Do we have any change detection logic here that we could leverage? I.e., only log when rules are changed at Info level?

2018-10-23 23:44 UTC, aanm commented
> hat makes it verbose?

@raybejjani would be better suitable to answer that question than me

2018-10-24 17:52 UTC, joestringer commented
As mentioned in the SIG-Policy meeting, there should be a "generated" flag for DNS-generated CIDR policy insertions which may provide an intermediate fix for the verbosity issue.

2018-10-25 17:18 UTC, aanm commented
test-me-please

2018-10-25 18:58 UTC, ianvernon approved these changes

2018-10-28 14:40 UTC, tgraf requested changes

2018-10-28 14:40 UTC, tgraf commented on daemon/policy.go
> +	// was generated by cilium-agent, e.g. dns pooler.
poller

2018-10-29 10:17 UTC, aanm commented
test-me-please

2018-10-29 17:22 UTC, tgraf approved these changes

2018-10-29 17:36 UTC, merged