Test: Enable a custom tmp folder for etcd certs.
cilium/cilium pull request #6049
Opened 2018-10-25 11:19 UTC by eloycoto

Due Jenkins is executing actions in parallel, the etcd certs can't be in
the same folder and need to be in a temporal folder to avoid collusions
between parallel jobs.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

2018-10-25 11:19 UTC, eloycoto commented
test-me-please

2018-10-25 13:38 UTC, eloycoto commented
test-me-please

2018-10-25 16:18 UTC, eloycoto commented
test-me-please

2018-10-26 07:18 UTC, eloycoto commented
test-me-please

2018-10-26 07:35 UTC, aanm requested changes

2018-10-26 07:35 UTC, aanm commented on examples/kubernetes/addons/etcd-operator/tls/certs/gen-cert.sh
> +cfssl gencert -initca ${dir}/ca-csr.json | cfssljson -bare ca
put quotes between all `"${dir}/..."`

2018-10-31 11:43 UTC, eloycoto commented
close due https://github.com/cilium/cilium/pull/6062 will fix this one.

2018-10-31 11:43 UTC, closed without merging