Jenkinsfile: boot VMs in separate shell
cilium/cilium pull request #6130
Opened 2018-10-31 20:58 UTC by ianvernon

This decouples testing from provisioning.

Signed-off by: Ian Vernon <ian@cilium.io>

2018-10-31 20:58 UTC, ianvernon commented
test-me-please

2018-10-31 20:59 UTC, ianvernon commented
test-me-please

2018-10-31 22:22 UTC, ianvernon commented
Monitor tests failed: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7773/

2018-10-31 22:24 UTC, ianvernon commented
test-me-please

2018-11-01 09:10 UTC, eloycoto commented
test-me-please

2018-11-01 14:20 UTC, ianvernon commented
Monitor tests keep failing. There must be some behavior that is skipped when `--cilium.provision=false` is set in the CI. I'll work on fixing this up locally.

2018-11-01 23:27 UTC, ianvernon commented
test-me-please

2018-11-02 00:41 UTC, ianvernon commented
test-me-please

2018-11-02 04:12 UTC, ianvernon commented
test-me-please

2018-11-02 08:45 UTC, aanm approved these changes

2018-11-02 08:56 UTC, eloycoto requested changes
Minor thing, It'll be great if we can validate that 
Nightly test are working with these changes too ;-)

2018-11-02 08:56 UTC, eloycoto commented on test/test_suite_test.go
> +	logger := log.WithFields(logrus.Fields{"testName": "BeforeSuite"})
Update the testName to BeforeAll

2018-11-02 08:56 UTC, eloycoto commented on test/test_suite_test.go
> +	if err != nil {
Quick one, the lines from 172 to 176 should be removed no?
https://github.com/cilium/cilium/blob/205b1ca5f44efae964c4fca561f615c3b739d5ae/test/test_suite_test.go#L155-L176

2018-11-02 14:54 UTC, ianvernon commented
test-me-please

2018-11-02 14:55 UTC, ianvernon commented
test-nightly

2018-11-02 15:04 UTC, eloycoto approved these changes

2018-11-02 15:05 UTC, eloycoto commented
Nightly is working, happy to merge without finish ;-)

2018-11-02 16:07 UTC, merged