Remove envoy proxy, add llvm to Requires
cilium/cilium pull request #6159
Opened 2018-11-02 19:34 UTC by tonylambiris

Remove deprecated envoy proxy from build
Add llvm to requirements for runtime compilation (requiring llc executable)

2018-11-02 20:04 UTC, aanm commented
Thanks @tonylambiris , will cilium-envoy still be created in the .rpm?

2018-11-02 20:10 UTC, tonylambiris commented
@aanm No, sorry I was under the impression that moved out. Let me amend the PR. :+1:

2018-11-02 20:14 UTC, tonylambiris commented
@aanm According to the Makefile in envoy:
```ifdef PKG_BUILD

all:
	echo "cilium-envoy has been moved to github.com/cilium/proxy"

install:
	echo "cilium-envoy must be installed separately"

else```

What course of action should be taken (I define PKG_BUILD=1 in the spec file).

Thanks!

2018-11-02 20:18 UTC, aanm commented
@jrajahalme ^^^^

2018-11-02 20:37 UTC, jrajahalme commented
AFAIK `PKG_BUILD=1` is used for docker container builds, in which case we now pull in the `cilium-envoy` binary from an image created from `github.com/cilium/proxy called cilium/cilium-envoy:<CILIUM_ENVOY_SHA>`, where the <CILIUM_ENVOY_SHA> identifies the Git commit from which the binary was built.

I'm not really familiar with rpm packaging, but the end result should be that the binaries from the cilium/cilium-envoy image (now only `/usr/bin/cilium-envoy`) should be included wherever the cilium binaries are installed.

After #6158 is merged the exact dependency (image name with the tag) will be in the main Dockerfile. When running make, the tag is extracted to variable CILIUM_ENVOY_SHA.

2018-11-02 20:38 UTC, ianvernon approved these changes

2018-11-02 20:39 UTC, jrajahalme requested changes
cilium-envoy binary must be extracted from the image like in `envoy/Makefile` for the case of PKG_BUILD not being defined.

2018-11-02 20:49 UTC, tonylambiris commented
@jrajahalme I keep running into the following:
```
docker create -ti --name cilium-envoy cilium/cilium-envoy:fd3866831d8f85e27120f34d98133343fc9c4e0e bash
Unable to find image 'cilium/cilium-envoy:fd3866831d8f85e27120f34d98133343fc9c4e0e' locally
fd3866831d8f85e27120f34d98133343fc9c4e0e: Pulling from cilium/cilium-envoy
b1a35b3e83dc: Already exists 
Digest: sha256:3f08adb47b708790bf51af1a9ad7336761366f4eff4c9fec4c1f04376f330b19
Status: Downloaded newer image for cilium/cilium-envoy:fd3866831d8f85e27120f34d98133343fc9c4e0e
Error response from daemon: Conflict. The container name "/cilium-envoy" is already in use by container "cb554dd9fc3b10af3e22b488b08ccd5e41eb0c9a51aafbaed77d60b5a2f2ab99". You have to remove (or rename) that container to be able to reuse that name.
make: *** [Makefile:32: install] Error 1
```

Any suggestions?

2018-11-02 20:57 UTC, tonylambiris commented
@jrajahalme Nevermind, I think I figured out a workaround (just got it working for the Arch Linux package I maintain):
```
	export PKG_BUILD=1

	make DESTDIR="${pkgdir}" install

	unset PKG_BUILD
	make -C envoy BINDIR="${pkgdir}/usr/bin/" -i install
```

```
➜ pacman -Ql cilium-git | ag envoy
cilium-git /usr/bin/cilium-envoy
```

2018-11-02 22:04 UTC, tonylambiris commented
@aanm @jrajahalme Updated the Makefile to write-out cilium-envoy binary before creating the tarball.

Since the cilium rpm is built in a docker container and not all docker daemons are setup to allow container-in-container support I felt this was the best option.

```
➜ make &>/dev/null; echo $?
make &> /dev/null  12.13s user 1.34s system 14% cpu 1:32.31 total
0

➜ rpm -qlp output/cilium-1.3.0rc5-191.git31a2dc2.fc28.x86_64.rpm| grep envoy
/usr/bin/cilium-envoy
```

2018-11-05 06:13 UTC, tgraf commented
test-me-please

2018-11-05 23:22 UTC, jrajahalme approved these changes
Looks OK to me, but then I know very little of rpm packaging.

2018-11-06 00:02 UTC, merged

2018-11-06 00:02 UTC, tgraf commented
Thanks @tonylambiris!