k8s: CEP controller retries k8s version checks
cilium/cilium pull request #6207
Opened 2018-11-08 19:58 UTC by raybejjani

When requests for the k8s version are flaky, newly created CEP
controllers will not create the controller and never try again. The
check is now repeated in the controller until it succeeds, and the
result cached.

Fixes https://github.com/cilium/cilium/issues/6186

2018-11-08 19:58 UTC, raybejjani commented
test-me-please

2018-11-08 20:38 UTC, aanm requested changes

2018-11-08 20:38 UTC, aanm commented on pkg/k8s/cep.go
> +							"found":    ciliumEPControllerLimit,
The found/ expected are swapped.

2018-11-08 20:53 UTC, raybejjani commented on pkg/k8s/cep.go
> +							"found":    ciliumEPControllerLimit,
ah, so they are

2018-11-08 20:53 UTC, raybejjani commented
test-me-please

2018-11-09 09:11 UTC, raybejjani commented
test-me-please

2018-11-09 09:19 UTC, raybejjani commented
test-me-please

2018-11-09 14:04 UTC, aanm approved these changes

2018-11-09 15:45 UTC, raybejjani commented
test-me-please

2018-11-12 12:25 UTC, tgraf approved these changes

2018-11-12 12:26 UTC, tgraf commented
test-me-please

2018-11-12 17:59 UTC, raybejjani commented
test-me-please

2018-11-12 20:07 UTC, raybejjani commented
test-me-please

2018-11-12 21:20 UTC, ianvernon commented
Tests failed - related to CEP: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8020/

2018-11-12 21:20 UTC, ianvernon commented
test-me-please

2018-11-12 23:37 UTC, merged