Test: Fix CIDR/L4 flakes
cilium/cilium pull request #6241
Opened 2018-11-14 12:23 UTC by eloycoto

Due the connectivity test to CloudFlare, time to time this test was not
reliable at all due internet connectivity issues. With this change if
the connection is failing more than one time will fail.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

Fixes: #5745

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cilium/cilium/6241)

2018-11-14 12:33 UTC, eloycoto commented
test-me-please

2018-11-14 14:04 UTC, eloycoto commented
test-me-please

2018-11-14 17:17 UTC, ianvernon reviewed
LGTM apart from `ExpectWithOffset` changes as I commented.

2018-11-14 17:17 UTC, ianvernon commented on test/runtime/Policies.go
> +			ExpectWithOffset(1, err).Should(BeNil(),
Change all `ExpectWithOffset` in this diff to `Expect`.

2018-11-14 18:24 UTC, aanm requested changes

2018-11-14 18:24 UTC, aanm commented on test/runtime/Policies.go
> +			proto := "https"
why is this variable here? What does it do?

2018-11-15 07:51 UTC, eloycoto commented on test/runtime/Policies.go
> +			proto := "https"
Because is used in a lot of curl fails and the test policy is restricted to port 443. 

Regards

2018-11-15 07:51 UTC, eloycoto commented
test-me-please

2018-11-15 10:01 UTC, eloycoto commented
test-me-please

2018-11-15 15:44 UTC, ianvernon approved these changes
LGTM!

2018-11-15 16:59 UTC, ianvernon commented
@eloycoto does this fix any of the issues in the CI Project? If so can you mark them as having been fixed by this PR?

2018-11-15 17:02 UTC, eloycoto commented
@ianvernon is already in the commit message ;-)

2018-11-15 17:04 UTC, ianvernon commented
@eloycoto thanks! I added it in the PR description as well.

2018-11-16 15:14 UTC, ianvernon commented on test/runtime/Policies.go
> +			proto := "https"
@aanm can you PTAL at @eloycoto 's comment?

2018-11-16 15:23 UTC, aanm commented on test/runtime/Policies.go
> +			proto := "https"
But why does it need to be a variable and not use `https` directly?

2018-11-16 15:26 UTC, eloycoto commented on test/runtime/Policies.go
> +			proto := "https"
@aanm because it is used four times in the test, and it's the way that the test was before.

2018-11-16 15:58 UTC, aanm approved these changes

2018-11-16 16:55 UTC, merged