policy: add RulesSelect field to SearchContext
cilium/cilium pull request #6274
Opened 2018-11-21 17:11 UTC by ianvernon

RulesSelect specifies whether or not to check whether a rule which is
being analyzed against its SearchContext has already been determined to select
the labels in the `To` or `From` fields within the SearchContext. This is used
to avoid using `EndpointSelector.Matches()` while analyzing rules if possible,
since said function is costly in terms of performance. Currently, this flag
is always false, so no functional change is intended here. In the future, the
list of rules that will be analyzed when generating policy for an endpoint will
only be the list of rules that select the endpoint.

Signed-off by: Ian Vernon <ian@cilium.io>

2018-11-21 17:11 UTC, ianvernon commented
test-me-please

2018-11-22 10:36 UTC, nebril approved these changes

2018-11-23 11:14 UTC, aanm requested changes
@ianvernon This is such a small PR I don't think it makes sense to merge it until there's is some usage of the `RulesSelect`. I would like to see what logic it would be applied to set the boolean values set in `RulesSelect` to understand the consequences of it.

2018-11-26 19:51 UTC, ianvernon commented
test-me-please

2018-11-26 19:53 UTC, ianvernon commented
@aanm the intention of this PR is to be small / show that there is no breakage when this functionality is added. There is no change in existing behavior because the field is never set to 'True' anywhere in the code base. To get to the point where it will be used is quite involved. I was planning on getting this done over time in a series of PRs to make it easier to merge. I'm not sure how to achieve that goal and to do what you request.

The description illustrates why this will be useful in the future, and it passed tests. I think we should be able to merge code that isn't used yet and doesn't break anything, as this promotes small, easy to review PRs.

2018-11-26 20:22 UTC, aanm commented
@ianvernon make this commit part of the first set of changes that will make use of this field. There's no design doc that points the need for this field. The main reason I'm arguing about this is because I've concerns if that field is wrongly set it will create tremendous bugs which will also be difficult to track it down.

2018-11-26 20:23 UTC, ianvernon commented
Travis build hit the proxy unit test problem, relaunching the build on Travis.

2018-11-26 21:28 UTC, ianvernon commented
CI failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8200/testReport/junit/k8s-1/12/K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies/

Kafka pods were not ready. Appears unrelated... trying again.

2018-11-26 21:28 UTC, ianvernon commented
test-me-please

2018-11-29 22:10 UTC, ianvernon commented
@aanm closing this PR and will fold these commits into the PR which consumes them.

2018-11-29 22:10 UTC, closed without merging