pkg/sockops: use native go API for mount
cilium/cilium pull request #6283
Opened 2018-11-22 16:10 UTC by nirmoy

Replace exec.Command(mount) with syscall.Mount

Signed-off-by: Nirmoy Das <ndas@suse.de>

2018-11-22 16:42 UTC, vadorovsky approved these changes
One minor comment, but LGTM overall. We should check more more often whether Cilium is not overusing `exec`.

2018-11-22 16:42 UTC, mrostecki commented on pkg/sockops/sockops.go
> +	if err := syscall.Mount(cgroupRoot, cgroupRoot, "cgroup2", 0, ""); err != nil {
Please use `mountinfo.FilesystemTypeCgroup2` const (https://github.com/cilium/cilium/blob/master/pkg/mountinfo/mountinfo.go#L29)

2018-11-22 17:10 UTC, mrostecki commented
test-me-please

2018-11-23 08:36 UTC, mrostecki commented
test-me-please

2018-11-23 10:56 UTC, aanm requested changes

2018-11-23 10:56 UTC, aanm commented on pkg/sockops/sockops.go
> +	if err := syscall.Mount(cgroupRoot, cgroupRoot, mountinfo.FilesystemTypeCgroup2, 0, ""); err != nil {
@nirmoy should this be `syscall.Mount("none"`...?

2018-11-23 11:16 UTC, aanm approved these changes

2018-11-23 17:17 UTC, nirmoy commented
test-me-please

2018-11-23 17:17 UTC, vadorovsky approved these changes

2018-11-26 09:09 UTC, mrostecki commented
test-me-please

2018-11-26 09:35 UTC, aanm commented
test-me-please

2018-11-26 14:30 UTC, merged

2018-11-26 14:30 UTC, tgraf commented
Nice!