Runtime/FQDN new tests
cilium/cilium pull request #6289
Opened 2018-11-23 14:33 UTC by eloycoto

New FQDN test based on a local bind9 container that uses three new containers in a different network to be able to continue the work over different DNS types without hit external DNS.

2018-11-23 15:42 UTC, aanm requested changes

2018-11-23 15:42 UTC, aanm commented on test/runtime/fqdn.go
> +		bindContainerImage = "eloycoto/docker-bind"
add this to the cilium dockerhub, specify a version and write the repository where this is installed. `docker.io/...`

2018-11-26 16:35 UTC, eloycoto commented
test-me-please

2018-11-26 18:49 UTC, aanm reviewed
I'll defer the test code to @raybejjani

2018-11-27 09:51 UTC, raybejjani approved these changes

2018-11-27 10:09 UTC, merged