test: add k8s 1.13 to testing framework
cilium/cilium pull request #6297
Opened 2018-11-27 11:00 UTC by aanm

2018-11-27 11:00 UTC, aanm commented
test-missed-k8s

2018-11-27 16:38 UTC, aanm commented
test-missed-k8s

2018-11-27 17:13 UTC, aanm commented
test-missed-k8s

2018-11-27 20:35 UTC, aanm commented
k8s 1.11 failed https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1328/execution/node/98/log/

2018-11-27 20:39 UTC, aanm commented
test-me-please

2018-11-27 20:39 UTC, aanm commented
test-docs-please

2018-11-27 22:48 UTC, aanm commented
test-me-please

2018-11-28 10:53 UTC, eloycoto requested changes

2018-11-28 10:53 UTC, eloycoto commented on test/provision/k8s_install.sh
> +        sudo ln -sf $COREDNS_DEPLOYMENT $DNS_DEPLOYMENT
I think that we should be consistent here, if we run a different version of coredns for 1.12 we also need to run the right version for 1.13. I strongly disagree with this one (We should also use the latest), but if you can add the coredns version for 1.13 will be great.

2018-11-28 11:13 UTC, aanm commented on test/provision/k8s_install.sh
> +        sudo ln -sf $COREDNS_DEPLOYMENT $DNS_DEPLOYMENT
ups I almost forgot. coredns for 1.13 added.

2018-11-28 11:13 UTC, aanm commented
test-me-please

2018-11-28 13:18 UTC, aanm commented
k8s 1.10 failed with known flake

2018-11-28 13:18 UTC, aanm commented
test-missed-k8s

2018-11-28 14:15 UTC, eloycoto requested changes

2018-11-28 14:15 UTC, eloycoto commented on test/provision/manifest/1.13/coredns_deployment.yaml
> +# https://raw.githubusercontent.com/kubernetes/kubernetes/release-1.12/cluster/addons/dns/coredns/coredns.yaml.base
Typo here, is 1.13

2018-11-28 18:15 UTC, aanm commented
test-me-please

2018-11-28 18:23 UTC, eloycoto approved these changes

2018-11-29 21:54 UTC, aanm commented
test-me-please

2018-11-30 02:12 UTC, ianvernon commented
Checkout from git failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8309/execution/node/7/log/

2018-11-30 02:12 UTC, ianvernon commented
test-me-please

2018-11-30 02:14 UTC, ianvernon commented
Travis unit tests hit the following issue: 
https://github.com/cilium/cilium/issues/6337

```
level=info msg="Starting to watch allocation changes" kvstoreErr="<nil>" kvstoreStatus="Consul: 172.17.0.3:8300" prefix=test-prefixzdRNAGVhuOFr/id subsys=allocator
allocator_test.go:102:
    c.Assert(id, Equals, idpool.ID(0))
... obtained idpool.ID = 0x1 ("1")
... expected idpool.ID = 0x0 ("0")

START: allocator_test.go:67: AllocatorConsulSuite.TearDownTest
PASS: allocator_test.go:67: AllocatorConsulSuite.TearDownTest	0.006s

FAIL: <autogenerated>:1: AllocatorConsulSuite.TestSelectID

OOPS: 11 passed, 1 FAILED
--- FAIL: Test (28.27s)
FAIL
coverage: 14.5% of statements in ./...
FAIL	github.com/cilium/cilium/pkg/kvstore/allocator	28.347s
make: *** [unit-tests] Error 1
travis_time:end:1253d968:start=1543528581515949791,finish=1543528880499027772,duration=298983077981
[0K[31;1mThe command "./.travis/build.sh" exited with 2.[0m
```

2018-11-30 08:59 UTC, aanm commented
test-me-please

2018-11-30 11:37 UTC, aanm commented
test-missed-k8s

2018-11-30 13:22 UTC, aanm commented
test-missed-k8s

2018-11-30 15:21 UTC, aanm commented
test-missed-k8s

2018-11-30 16:59 UTC, ianvernon commented on test/provision/k8s_install.sh
> +        KUBEADM_SLAVE_OPTIONS="--discovery-token-unsafe-skip-ca-verification --ignore-preflight-errors=cri,SystemVerification"
Not blocking, just out of curiosity - what is the need to ignore this error?

2018-11-30 16:59 UTC, ianvernon approved these changes

2018-11-30 17:00 UTC, ianvernon commented
@aanm looks great overall. Would you find value in documentation for how to update the K8s versions tested in CI so that others can do this in the future as well? I'd be happy to help.

2018-11-30 17:23 UTC, aanm commented
test-me-please

2018-11-30 18:34 UTC, jrajahalme approved these changes
Janitorially looks ok apart from one typo, can't comment on all the k8s yaml detail, though.

2018-11-30 18:34 UTC, jrajahalme commented on Documentation/install/upgrade.rst
> +  .. group-tab:: K8s 1.12
Should be `1.13`

2018-11-30 19:37 UTC, aanm commented on Documentation/install/upgrade.rst
> +  .. group-tab:: K8s 1.12
Correct

2018-11-30 19:39 UTC, aanm commented
The tests were all 7/7 green I just made the changes in the documentation pointed out by @jrajahalme

2018-11-30 19:39 UTC, aanm commented
test-docs-please

2018-11-30 19:43 UTC, merged