[FQDN] Delete lookups after last rule was deleted
cilium/cilium pull request #6300
Opened 2018-11-27 15:47 UTC by nebril

If there are two toFQDN rules for the same endpoint with the same
pattern, after deleting first one all lookups would be deleted from
RegexpMap. This change adds counter to RegexpMap lookup mapping.

2018-11-27 15:47 UTC, nebril commented
test-me-please

2018-11-27 16:09 UTC, vadorovsky approved these changes

2018-11-27 16:09 UTC, mrostecki commented on pkg/fqdn/regexpmap/regexp_map.go
> +	m.lookups[reStr][lookupValue] = m.lookups[reStr][lookupValue] + 1
```
m.lookups[reStr][lookupValue]++
```

2018-11-28 11:31 UTC, raybejjani requested changes
This is fantastic! Thanks for fixing it!
Could you add a test in regexpmap for the refcount as well? It'll be a copy of the one in dnsproxy but the regexpmap is used in a few other places too.

2018-11-29 13:21 UTC, nebril commented
@raybejjani done

2018-11-29 13:21 UTC, nebril commented
test-me-please

2018-11-29 15:16 UTC, tgraf approved these changes

2018-11-29 15:19 UTC, raybejjani approved these changes

2018-11-29 15:20 UTC, merged