FQDNS- New test and fixes
cilium/cilium pull request #6327
Opened 2018-11-29 16:54 UTC by eloycoto

Hi, 

Two commits here: 

- Roundrobin: The test didn't apply the policy correctly and no enforce at all. 
- New CNAME follow test, to validate that the CNAME entries are working correctly.

2018-11-29 16:54 UTC, eloycoto commented
test-me-please

2018-11-29 16:59 UTC, raybejjani requested changes

2018-11-29 16:59 UTC, raybejjani commented on test/runtime/fqdn.go
> +		res.ExpectSuccess("Container %q cannot access to %q when should work", helpers.App1, target)
`helpers.App2`, no? for both the comment and the exec? unless you wanted the policy to apply to app1

2018-11-29 16:59 UTC, raybejjani commented on test/runtime/fqdn.go
> +				"Endpoint %q do not have policy applied", container)
"does not have a policy applied"

2018-11-29 17:22 UTC, eloycoto commented
test-me-please

2018-11-29 17:27 UTC, raybejjani approved these changes

2018-11-30 02:23 UTC, ianvernon requested changes
One small fix needed.

2018-11-30 02:23 UTC, ianvernon commented on test/runtime/fqdn.go
> +		endpoints, err := vm.GetEndpointsIds()
`endpoints` is never used again after this. Why not do the assertion for each value of `ep` in the for loop below?

2018-11-30 02:23 UTC, ianvernon commented on test/runtime/fqdn.go
> +			Expect(ep.Status.Policy.Realized.PolicyEnabled).To(
This will panic if the endpoints are nil.

2018-11-30 07:20 UTC, eloycoto commented on test/runtime/fqdn.go
> +		endpoints, err := vm.GetEndpointsIds()
I'm not sure If I understand this one, endpoints is a map with containerName:epID and it's used in the loop.

2018-11-30 07:21 UTC, eloycoto commented on test/runtime/fqdn.go
> +			Expect(ep.Status.Policy.Realized.PolicyEnabled).To(
Nice one, checking the key just before of this one :-) Thanks

2018-11-30 07:21 UTC, eloycoto commented
test-me-please

2018-11-30 13:39 UTC, aanm approved these changes

2018-11-30 14:34 UTC, eloycoto commented
test-me-please

2018-11-30 14:35 UTC, merged