vendor: update miekg/dns to v1.1.0
cilium/cilium pull request #6339
Opened 2018-11-30 13:30 UTC by aanm

Signed-off-by: André Martins <andre@cilium.io>

2018-11-30 13:31 UTC, aanm commented
test-me-please

2018-11-30 13:32 UTC, raybejjani approved these changes

2018-11-30 15:04 UTC, aanm commented
test-me-please

2018-11-30 16:21 UTC, ianvernon approved these changes

2018-11-30 18:48 UTC, jrajahalme requested changes
Please provide a short motivation for the change in the commit message.

Also, there is one change that seems unrelated.

2018-11-30 18:48 UTC, jrajahalme commented on Gopkg.toml
> +[[override]]
Is this change related to the miekg/dns version change? Why?

2018-11-30 20:21 UTC, aanm commented
test-me-please

2018-11-30 20:22 UTC, aanm commented
@jrajahalme let me know if the changes are good now.

2018-12-01 18:14 UTC, tgraf approved these changes

2018-12-01 18:15 UTC, merged