Test: On fail retrieve all the logs
cilium/cilium pull request #6557
Opened 2019-01-07 10:50 UTC by eloycoto

Due the latest fail on CI I observed that the reportFailed information
was not retrieved correctly due a early return due no Cilium Pods.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

2019-01-07 10:50 UTC, eloycoto commented
test-me-please

2019-01-07 13:57 UTC, eloycoto commented
test-me-please

2019-01-07 15:53 UTC, eloycoto commented
test-me-please

2019-01-07 18:09 UTC, eloycoto commented
test-me-please

2019-01-08 08:14 UTC, eloycoto commented
test-me-please

2019-01-08 09:14 UTC, eloycoto commented
test-me-please

2019-01-08 15:37 UTC, eloycoto commented
test-me-please

2019-01-08 23:29 UTC, tgraf approved these changes

2019-01-08 23:29 UTC, tgraf commented on test/helpers/kubectl.go
>  			status := strings.Split(data, "::")
Should this use `strings.SplitN()` instead?

2019-01-09 16:52 UTC, eloycoto commented
test-me-please

2019-01-09 18:38 UTC, ianvernon requested changes

2019-01-09 18:38 UTC, ianvernon commented on test/helpers/kubectl.go
> +			continue
Log the error? Otherwise the failure is silent.

2019-01-09 18:38 UTC, ianvernon commented on test/helpers/kubectl.go
> +			if len(status) != 2 {
Why is this necessary? Add a comment - there is no context here explaining why this check is necessary.

2019-01-10 07:41 UTC, eloycoto commented
test-me-please

2019-01-14 22:34 UTC, ianvernon approved these changes

2019-01-14 22:34 UTC, merged