daemon: Add /discover/fqdn/{id} API
cilium/cilium pull request #6652
Opened 2019-01-15 16:21 UTC by raybejjani

_This is WIP while I clean things up, but feedback on the API itself it welcome!_

    daemon: Add /discover/fqdn/{id} API

    Introspecting the internal caches used to populate DNS data is useful
    when debugging FQDN policy behaviour and to simply audit what an
    endpoint has done.
    The API returns the entries for each endpoint, instead of using the
    shared global cache. This exposes more per-endpoint history, because the
    global cache only uses the most recent entry from any endpoint. Results
    can be filtered by DNS name, following the policy matchPattern spec, and
    by CIDR range.

```
$ curl -s --unix-socket /var/run/cilium/cilium.sock http://localhost/v1/discovery/fqdn?matchpattern=*.*oogle.com. | jq .
[
  {
    "endpoint-id": 2395,
    "expiration-time": "2019-01-15T16:27:40.395Z",
    "fqdn": "www.google.com.",
    "ips": [
      "74.125.206.105",
      "74.125.206.103",
      "74.125.206.106",
      "74.125.206.147",
      "74.125.206.104",
      "74.125.206.99"
    ],
    "lookup-time": "2019-01-15T15:27:40.395Z",
    "ttl": 3600
  },
  {
    "endpoint-id": 2395,
    "expiration-time": "2019-01-15T16:24:27.835Z",
    "fqdn": "www.google.com.",
    "ips": [
      "2a00:1450:400c:c04::6a"
    ],
    "lookup-time": "2019-01-15T15:24:27.835Z",
    "ttl": 3600
  },
...
 }
]
```

The PR also includes some refactors that might be better left out:
- split out FQDN code into daemon/fqdn.go
- matchpattern.Validate returns the internal regex it compiles
- DNSCache exposes the internal objects via a Dump function

2019-01-15 16:21 UTC, raybejjani commented
test-me-please

2019-01-16 21:51 UTC, tgraf requested changes
Looks great overall. The matching may be relatively slow so we have to make sure that the API does not get abused

2019-01-16 21:51 UTC, tgraf commented on api/v1/openapi.yaml
> +  "/tofqdns":
I would call this `/fqdncache` or `/fqdn/cache`

2019-01-17 12:33 UTC, raybejjani commented
@tgraf do you mean the nested iterations will be slow? or something else?

2019-01-17 12:34 UTC, raybejjani commented
test-me-please

2019-01-17 12:45 UTC, raybejjani commented
test-me-please

2019-01-17 15:30 UTC, tgraf approved these changes

2019-01-17 15:30 UTC, merged