Enable Cilium policy enforcement on top of flannel
cilium/cilium pull request #6653
Opened 2019-01-15 16:27 UTC by aanm

This PR deprecates https://github.com/cilium/cilium/pull/6267 as it got rebased against master. All changes suggested in #6267 were made, as best effort as possible, into this PR.

Some notes:

- The first commit is also in the PR https://github.com/cilium/cilium/pull/6248
- Best if reviewed per commit
- Suggestions to rename `policy-enforcement-interface` are more than welcome
~~- Runtime tests will to be added once the CI is adapted to install Flannel. This adaptation will likely be done in a different PR.~~

Missing parts:

- create k8s job, or something else, to add / remove bpf programs for running contains as the cilium-agent is not able to read from other namespaces once it's running inside a container. that's why some parts related with creating an endpoint based on its PID code are commented.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cilium/cilium/6653)

2019-01-15 18:56 UTC, aanm commented
test-me-please

2019-01-15 23:00 UTC, aanm commented
test-me-please

2019-01-16 07:03 UTC, aanm commented
test-me-please

2019-01-16 09:11 UTC, aanm commented
test-me-please

2019-01-16 09:46 UTC, aanm commented
test-me-please

2019-01-16 10:11 UTC, aanm commented
test-me-please

2019-01-16 12:01 UTC, aanm commented
test-me-please

2019-01-16 17:05 UTC, aanm commented
test-me-please

2019-01-16 18:47 UTC, aanm commented
test-me-please

2019-01-16 21:51 UTC, aanm commented
test-me-please

2019-01-17 09:56 UTC, aanm commented
test-me-please

2019-01-17 10:52 UTC, aanm commented
test-me-please

2019-01-17 13:00 UTC, aanm commented
test-me-please

2019-01-17 13:48 UTC, aanm commented
test-me-please

2019-01-17 14:50 UTC, aanm commented
test-me-please

2019-01-17 15:43 UTC, aanm commented
green: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9108/

2019-01-17 15:43 UTC, aanm commented
test-me-please

2019-01-17 22:23 UTC, ianvernon requested changes
Great work! Most comments are requests for clarification.

2019-01-17 22:23 UTC, ianvernon commented on api/v1/openapi.yaml
> +      pid:
The commit message doesn't match up with the commit's content. SHouldn't the commit say "Will allow to create an endpoint based on the process ID of its container"? Or are container ID / PID interchangeable here?

2019-01-17 22:23 UTC, ianvernon commented on pkg/workloads/runtimes.go
> +	// GetAllInfraContainersPID returns a list of workload IDs running in the
instead of "a list of workload IDs", this should specify what the mapping is - a mapping of the ID of the container to its PID.

2019-01-17 22:23 UTC, ianvernon commented on daemon/daemon_main.go
> +// ifaceName is not found, then it will wait forever until the device is
I think there should be some ceiling for how long we wait; what is the motivation for waiting infinitely?

2019-01-17 22:23 UTC, ianvernon commented on daemon/daemon_main.go
> +	// there is also a script waiting for the interface to be created.
Which script?

2019-01-17 22:23 UTC, ianvernon commented on daemon/endpoint.go
> +	_, ip6, err := ipam.AllocateNext("ipv6")
Is Flannel IPv4 only? Why is it safe to allocate an IPv6 address without checking? Document this behavior if Flannel doesn't do IPv6 with a comment here.

2019-01-17 22:23 UTC, ianvernon commented on daemon/health.go
> +		// controlled by Cilium.
Add a log message at Info level indicating that we are skipping `cilium-health` bootstrap / management due to running alongside Flannel.

2019-01-17 22:23 UTC, ianvernon commented on daemon/daemon_main.go
> +		// d.attachExistingInfraContainers()
Why is this commented out? Please provide some context, or a TODO with a corresponding GitHub issue filed for follow-up.

2019-01-17 22:23 UTC, ianvernon commented on pkg/endpoint/connector/add.go
> +	// _, ip6, err := ipam.AllocateNext("ipv6")
Similar to above, please provide context as to why this is commented out, along with a corresponding TODO with a GitHub issue link.

2019-01-17 22:23 UTC, ianvernon commented on pkg/endpoint/connector/add.go
> +func DeriveEndpointFrom(hostDevice, containerID string, pid int) (*models.EndpointChangeRequest, error) {
Update copyright at top of file.

2019-01-17 22:23 UTC, ianvernon commented on plugins/cilium-cni/cilium-cni.go
> +	if len(n.NetConf.RawPrevResult) != 0 {
What is the significance of the value being nonzero? Is this for chaining? Add comments indicating what's going on here for maintainability.

2019-01-17 22:23 UTC, ianvernon commented on daemon/cleanup.go
> +					ep.DeleteBPFProgramLocked()
This is being called without the endpoint mutex being acquired - if this is intended, document why.

2019-01-17 22:23 UTC, ianvernon commented on daemon/endpoint.go
> +		ep.DeleteBPFProgramLocked()
The endpoint lock is not acquired here - is this intentional?

2019-01-17 22:23 UTC, ianvernon commented on plugins/cilium-cni/04-flannel-cilium-cni.conflist
> +         "hairpinMode": true,
This may be because I am not an expert on this stuff, but please document why these options are needed for code-maintenance purposes.

2019-01-17 22:23 UTC, ianvernon commented on plugins/cilium-cni/04-flannel-cilium-cni.conflist
> +{
Is there a specific order this file needs to be in the CNI conf directory? Or does it just have to be before `x-cilium.conf`?

2019-01-17 22:23 UTC, ianvernon commented on plugins/cilium-cni/cni-install.sh
> +	until ip link show "${CILIUM_FLANNEL_MASTER_DEVICE}" &>/dev/null ; do
Is it necessary that this loops infinitely?

2019-01-17 22:23 UTC, ianvernon commented on plugins/cilium-cni/cni-install.sh
> +	CNI_CONF_NAME=${CNI_CONF_NAME:-04-flannel-cilium-cni.conflist}
Document in the corresponding file that this script (`cni-install.sh`) is dependent upon this name, e.g., in `04-flannel-cilium-cni.conflist` that `plugins/cilium-cni/cni-install.sh is dependent upon the name of this file being 04-flannel-cilium-cni.conflist`.

2019-01-17 22:23 UTC, ianvernon commented on examples/kubernetes/addons/flannel/README.md
> +If you have your cluster already set up with Flannel will not need to install
"Flannel, you will not..."

2019-01-17 22:23 UTC, ianvernon commented on examples/kubernetes/addons/flannel/README.md
> +Cilium might not come up immediately on all nodes, since flannel only sets up
flannel --> Flannel

2019-01-17 22:23 UTC, ianvernon commented on examples/kubernetes/addons/flannel/README.md
> +Once you have change the configuration map accordingly, you can deploy Cilium.
changed

2019-01-17 22:23 UTC, ianvernon commented on examples/kubernetes/addons/flannel/README.md
> +Wait all pods to be in ready state before preceding to the next step.
Wait for

2019-01-17 22:23 UTC, ianvernon commented on test/helpers/kubectl.go
> +		fmt.Sprintf("timed out waiting for pods of daemon set with filter %q to be scheduled", filter),
Nit: these pods don't necessarily have to be part of a daemon set - could just say 'waiting for pods with filter %q to be scheduled'

2019-01-17 22:23 UTC, ianvernon commented on test/helpers/kubectl.go
> +		case CIIntegrationFlannel:
Why are we ignoring the cilium preflight check in the flannel case? Document why this is being done, same goes for the health preflight check for code maintenance purposes.

2019-01-17 22:23 UTC, ianvernon commented on test/k8sT/Updates.go
> +			return
use `Skip` here.

2019-01-17 22:23 UTC, ianvernon commented on test/helpers/kubectl.go
> +func (kub *Kubectl) WaitForPodsRunning(namespace, filter string, minPodsScheduled int, timeout time.Duration) error {
This filter is hardcoded to be `-l k8s-app=cilium` and isn't actually used.

2019-01-17 22:23 UTC, ianvernon commented on test/k8sT/assertionHelpers.go
> +		vm.Apply(helpers.GetFilePath("../examples/kubernetes/addons/flannel/flannel.yaml"))
Add a `By` indicating that Flannel is being installed.

2019-01-17 22:23 UTC, ianvernon commented on test/k8sT/manifests/cilium-ds-patch.yaml
>          - "--debug=$(CILIUM_DEBUG)"
Is this being removed because vxlan is the default?

2019-01-17 22:23 UTC, ianvernon commented on test/provision/k8s_install.sh
> +    export KUBEADM_POD_NETWORK="10.244.0.0"
Can you elaborate on why this is necessary?

2019-01-17 22:23 UTC, ianvernon commented on test/k8sT/Updates.go
> +		Skip(fmt.Sprintf(
Will we be able to add upgrade / downgrade tests for Flannel support in Cilium v1.5? If so file a GH Issue and link it here so we don't miss that testing gap for v1.5.

2019-01-17 22:23 UTC, ianvernon commented on daemon/daemon_main.go
> +	if k8s.IsEnabled() {
What is the need for this change? Please explain why this is necessary in the commit message. I am wary of changing orders of operations upon daemon bootstrap.

2019-01-17 22:50 UTC, aanm commented
The previous build was green (https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9112/) , running without the label to see if something broke with the new changes.

2019-01-17 22:51 UTC, aanm commented
test-me-please

2019-01-18 01:03 UTC, tgraf commented
Merging this. I think @ianvernon's comment can be addressed in a follow-up PR. Rebasing this PR has become a nightmare and we don't want to hold off all other merging.

2019-01-18 01:03 UTC, merged