kubernetes: Mark cilium-etcd-secret secret required
cilium/cilium pull request #6718
Opened 2019-01-22 17:45 UTC by tgraf

With the etcd-operator becoming the standard, marking the cilium-etcd-secrets as optional is inefficient as it requires a Cilium pod restart to mount the secret after it has been created.

Instaead, mark the secret as required an provide a new `cilium-external-etcd.yaml` which contains an empty secret. For users upgrading, document the requirement to create an empty secret before the upgrade.

2019-01-22 20:22 UTC, tgraf commented
test-me-please

2019-01-22 20:44 UTC, aanm requested changes
Why don't we make the creation of the dummy secret part of the upgrade guide? Regardless if the user is running secrets or not they will either *not* be overwritten or created.

```
kubectl create -f \ |SCM_WEB|\/examples/kubernetes/1.11/etcd-secrets.yaml
Error from server (AlreadyExists): error when creating "examples/kubernetes/1.13/secret.yaml": secrets "cilium-etcd-secrets" already exists
kubectl apply -f ./cilium-ds.yaml
...
```

2019-01-22 20:44 UTC, aanm commented on Documentation/install/upgrade.rst
> +   ``cilium-etcd-secretes`` to access etcd using TLS, no action is required. If
`s/cilium-etcd-secretes/cilium-etcd-secrets/`

2019-01-22 20:44 UTC, aanm commented on Documentation/install/upgrade.rst
> +   ``cilium-etcd-secrets`` like this:
Write an example how can the user know if it has secrets installed or not

2019-01-22 21:07 UTC, tgraf commented
> Why don't we make the creation of the dummy secret part of the upgrade guide? Regardless if the user is running secrets or not they will either _not_ be overwritten or created.

Good point, added

2019-01-22 21:24 UTC, aanm commented
> > Why don't we make the creation of the dummy secret part of the upgrade guide? Regardless if the user is running secrets or not they will either _not_ be overwritten or created.
> 
> Good point, added

@tgraf no, it's a bad point, if we do this regardless of the user Cilium will have the wrong secret mounted and etcd client will fail to connect as well

2019-01-22 21:28 UTC, tgraf commented
> no, it's a bad point, if we do this regardless of the user Cilium will have the wrong secret mounted and etcd client will fail to connect as well

How so? Please explain

2019-01-22 21:45 UTC, aanm commented
scratch that, I thought the `create -f dummy secret.yaml` would also be done for new users, which would make cilium to crash eventually.

2019-01-23 00:02 UTC, tgraf commented
test-me-please

2019-01-23 02:10 UTC, tgraf commented
test-me-please

2019-01-23 21:10 UTC, tgraf commented
test-me-please

2019-01-23 21:24 UTC, ianvernon approved these changes

2019-01-23 22:45 UTC, aanm reviewed
@tgraf New thoughts around this

1) by marking the secret as mandatory this will make `cilium-etcd-operator` impossible to work without `hostNetwork: true`.
2) It seems `cilium-etcd-operator` didn't start in [1] due the fact the node is marked as nonschedulable or even that kubelet can not create the `cilium-etcd-operator` as `cilium` is not initialized and `cilium` will not be initialized because `cilium-etcd-operator` did not create the secret.

[1] https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9272/execution/node/83/log/

2019-01-23 23:09 UTC, tgraf commented
> 1. by marking the secret as mandatory this will make `cilium-etcd-operator` impossible to work without `hostNetwork: true`.

Correct

> 2\. It seems `cilium-etcd-operator` didn't start in [1] due the fact the node is marked as nonschedulable or even that kubelet can not create the `cilium-etcd-operator` as `cilium` is not initialized and `cilium` will not be initialized because `cilium-etcd-operator` did not create the secret.

Yes, I've come to the same conclusion while digging into the failures.

2019-01-23 23:37 UTC, tgraf commented
The `cilium-etcd-operator` already has tolerations so it should come up even on a tainted node

2019-01-23 23:38 UTC, tgraf commented
Hit #6727

2019-01-23 23:38 UTC, tgraf commented
test-me-please

2019-01-24 05:05 UTC, tgraf commented
Hit #6727 again

2019-01-24 05:05 UTC, tgraf commented
test-me-please

2019-01-24 20:30 UTC, tgraf commented
test-me-please

2019-01-25 02:54 UTC, tgraf commented
test-me-please

2019-02-05 21:08 UTC, tgraf commented
@aanm verified that this is not required

2019-02-05 21:08 UTC, closed without merging