v1.4 backports 19-01-23
cilium/cilium pull request #6739
Opened 2019-01-24 05:33 UTC by jrfastab

2019-01-24 05:55 UTC, jrfastab commented
test-me-please

2019-01-24 08:27 UTC, aanm requested changes

2019-01-24 08:27 UTC, aanm commented on examples/kubernetes/templates/v1/cilium-ds.yaml.sed
>          imagePullPolicy: IfNotPresent
When you get those conflicts, ignore all `examples/kubernetes/1.*`, fix the conflicts on this file and generate all files again `CILIUM_VERSION=v1.4.0-rc4 make -C examples/kubernetes clean all`. This needs to be done in this commit ("
examples/kubernetes: add options for policy enforcement mode") as the imagePullPolicy should be IfNotPresent

2019-01-24 08:32 UTC, aanm commented
@jrfastab it seems something is missing

```
07:14:06 
07:14:06 # github.com/cilium/cilium/test/helpers
07:14:06 helpers/kubectl.go:624:25: cannot use timeout (type time.Duration) as type int64 in field value
07:14:06 
07:14:06 Ginkgo ran 1 suite in 5.099465508s
07:14:06 Test Suite Failed
```

My changes need 92f83a5fb927ca6bc5a0360eea9286faded5c5d0 or tell me and I'll modify commit ("test: add flannel integration in the CI")

2019-01-24 14:42 UTC, jrfastab commented
Marking https://github.com/cilium/cilium/pull/6576 as 'needs-backport-v1.4' and pulling in for commit https://github.com/cilium/cilium/commit/92f83a5fb927ca6bc5a0360eea9286faded5c5d0 per @aanm comment above.

2019-01-24 15:12 UTC, jrfastab commented
test-me-please

2019-01-24 17:17 UTC, joestringer approved these changes

2019-01-24 17:17 UTC, joestringer commented on test/helpers/kubectl.go
> +		defer cancel()
I think these lines were actually introduced in another commit, but this matches master so LGTM

(Found the commit later, it actually belongs to `helpers: Limit ep gathering to 5m for all cilium pods`)

2019-01-24 19:12 UTC, ianvernon approved these changes
Approving for api / docs.

2019-01-24 19:13 UTC, ianvernon commented
test-missed-k8s

2019-01-24 19:13 UTC, ianvernon commented
test-docs-please

2019-01-24 22:29 UTC, jrfastab commented
test-me-please

2019-01-24 23:39 UTC, jrfastab commented
test-me-please

2019-01-24 23:55 UTC, jrfastab commented
test-me-please

2019-01-25 01:55 UTC, ianvernon commented
test-missed-k8s

2019-01-25 01:55 UTC, ianvernon commented
test-docs-please

2019-01-25 02:27 UTC, jrfastab commented
test-missed-k8s

2019-01-25 04:07 UTC, ianvernon commented
K8s tests failed: ```02:53:43 Cannot contact jenkins-fixed-1: java.lang.InterruptedException```

Link: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1560

I think this can be merged.

2019-01-25 04:24 UTC, ianvernon commented
test-missed-k8s

2019-01-25 05:45 UTC, tgraf commented
Only failure was known flake that will be fixed in next batch

2019-01-25 05:46 UTC, merged