CLI for clearing FQDN proxy cache
cilium/cilium pull request #6745
Opened 2019-01-24 13:55 UTC by nebril

depends on #6692

2019-01-24 13:55 UTC, nebril commented
test-me-please

2019-01-24 17:14 UTC, vadorovsky approved these changes

2019-01-24 18:33 UTC, aanm commented
@nebril there's something odd with the commits in this PR, I almost though this was a backport PR

2019-01-25 05:42 UTC, tgraf requested changes

2019-01-25 05:42 UTC, tgraf commented on cilium/cmd/fqdn-proxy-cleanup.go
> +	Use:   "fqdn-clean-cache",
Please define this as multiple levels of subcommands: `cilium fqdn cache clean` We may want to list the cache as well

2019-01-25 12:41 UTC, nebril commented
Rebased and fixed, thanks for reviews.

2019-01-25 12:43 UTC, eloycoto approved these changes

2019-01-25 21:07 UTC, ianvernon approved these changes

2019-01-25 21:07 UTC, ianvernon commented
Approving based on only the last commit, since the rest is rebased on top of #6692 .

2019-01-25 22:58 UTC, tgraf approved these changes

2019-01-26 09:30 UTC, aanm approved these changes

2019-01-28 11:45 UTC, nebril commented
test-me-please

2019-01-28 13:35 UTC, merged