fqdn: Introduce upper cap of IPs per FQDN name per endpoint
cilium/cilium pull request #6788
Opened 2019-01-26 00:18 UTC by tgraf

The minimal TTL for DNS entries in the cache is deliberately long with 1 week
per default. This is done to accommodate long-lived, persistent connections.
On the other end of the spectrum are workloads which perform short-lived
connections in repetition to FQDNs which are backed by a large number of IP
addresses (e.g. AWS S3). Such workloads can grow the number of IPs mapping to
an FQDN quickly. In order to limit the number of IP addresses that map a
particular FQDN, each FQDN per endpoint has a max capacity of IPs that are
being maintained (default: 50). Once the capacity is exceeded, the oldest
entries are automatically expired from the cache. This capacity can be changed
using the `--tofqdn-max-ip-per-hostname` option.

2019-01-26 00:29 UTC, tgraf commented
test-me-please

2019-01-26 09:43 UTC, aanm commented on pkg/option/config.go
> +	ToFQDNsMaxIPsPerHost = "tofqdn-max-ip-per-hostname"
to be consistent: `s/tofqdn/tofqdns`

2019-01-28 16:29 UTC, raybejjani requested changes
My only change is fixup the tofqdns CLI option, since that is annoying to fix later. Everything else is discussion.

Two important things to note about this change:
- We maintain two caches: one in the endpoint and one global one. The one in the endpoint is used to restore the state, and has no direct impact on the number of CIDR identities when we include this change. The global one is the one we want to apply this limit to. If we make this a constructor parameter we can tune them separately. The reason I want the endpoint cache to have no limit is that when restoring from all the endpoint caches (on cache delete or startup) we need the entire history keep the behaviour consistent. I'm not sure anyone will notice, however.
2- This change might violate a specific assumption in the cache. Because of the way expiration worked, if 2 IPs were provided by DNS lookup A, they would expire together. Now, it's possible to evict only some of those IPs. I don't think any bugs will show up, since we already handle IPs coming from different DNS lookups. It will make the DNS CLI list IPs that aren't actually in use (since we partially expired only some IPs in the entry).
A related issue to this, one that was addressed in the Delete API, is that when you delete an IP, that IP may come from a different DNS lookup as well. That lookup wasn't used because lookup A had a later expiration, but with the eviction lookup B might be expected to provide this IP. This might happen when different endpoints lookup the same name. This would mean we need to rebuild the cache from all endpoints when we evict, which is more difficult (and that we need to evict the same DNS lookup in the global cache and the endpoint specific cache).

2019-01-28 16:29 UTC, raybejjani commented on pkg/option/config.go
> +	ToFQDNsMaxIPsPerHost = "tofqdn-max-ip-per-hostname"
I second aanm :p

2019-01-28 16:29 UTC, raybejjani commented on pkg/fqdn/cache.go
> +	if overLimit := len(entries) - option.Config.ToFQDNsMaxIPsPerHost; overLimit > 0 {
It's not the end of the world, but would you be ok making this a constructor parameter on the cache object. Mainly to avoid including more packages, but it is also relevant when managing the per-endpoint cache (used in state restore) and the global cache (used to actually populate policies, and so the CIDR identities).

2019-01-28 16:29 UTC, raybejjani commented on pkg/fqdn/cache.go
> +				if oldestEntry == nil || entry.LookupTime.Before(oldestEntry.LookupTime) {
This might actually be better comparing the expiration times. I'm not sure, though, it very much depends on the use-case (e.g. the earliest lookup is also likely the one most likely not used, but if a specific DNS response had a long TTL for a reason, we are circumventing it a bit).

2019-01-28 16:29 UTC, raybejjani commented on pkg/fqdn/cache.go
> +		for i := 0; i < overLimit; i++ {
This isn't a blocking comment.
To avoid the repeated iterations, we can make a list during the iteration above. Sort it by LookupTime, and evict the first overLimit entries in the slice. In most cases this won't be an issue, since we add 1 IP at a time so this loop will run just once.

2019-01-28 17:18 UTC, raybejjani commented
For those following at home:
I chatted briefly with tgraf (but we ran out of time). The goal here is to allow for both expected usage modes: 
1- endpoints that have long-lasting connections to a toFQDNs name
2- endpoints that make many connections to a toFQDNs name

2 such endpoints shouldn't break each other, and that is why the PR had applied the limit to all instances of the cache. If we did want to feed this eviction we'll need a way to wire the evictions in the per-endpoint caches to the shared cache. Not trivial but we'll figure something out.

2019-01-28 19:13 UTC, tgraf commented
@raybejjani Can we keep track of the endpoints that are sourcing a particular FQDN in the cache and simply have a GC that enforces the cap periodically?

2019-01-30 03:19 UTC, tgraf commented
Discussed with @raybejjani offline. @raybejjani has a better way of achieving this with a garbage collector. Closing this PR.

2019-01-30 03:19 UTC, closed without merging