pkg/bpf/ctmap: refactor to utilize pkg/bpf/map
cilium/cilium pull request #679
Opened 2017-05-09 22:10 UTC by ianvernon

Refactor pkg/bpf/ctmap to utilize pkg/bpf/map implementation.
Add GetNextKey wrapper in pkg/bpf/map.go.

Signed-off by: Ian Vernon <ian@covalent.io>

Fixes: 357

2017-05-09 22:11 UTC, ianvernon commented
I would like to only have one map refactoring per issue - 357 says it is for all maps, but would be better / more modular if we have multiple tickets.

2017-05-10 06:24 UTC, aanm requested changes

2017-05-10 06:24 UTC, aanm commented on cilium/cmd/bpf_ct_list.go
> +	"github.com/cilium/cilium/pkg/bpf"
This should be grouped with the remaining `github.com/cilium/cilium` imports

2017-05-10 06:24 UTC, aanm commented on cilium/cmd/bpf_ct_list.go
> +			dumpCtProto(ctmap.MapName6Global, "")
Why the `dumpCtProto` from `else` take the `args[0]` but this one doesn't take the `"global"` string?

2017-05-10 06:24 UTC, aanm commented on cilium/cmd/bpf_ct_list.go
>  		Fatalf("Error while dumping BPF Map: %s\n", err)
You can remove the `\n` here as well

2017-05-10 06:24 UTC, aanm commented on daemon/ct.go
> +		file = bpf.MapPath(mapType)
Won't this overwrite the variable written on line 49?

2017-05-10 06:24 UTC, aanm commented on pkg/bpf/map.go
> +		if err := m.Open(); err != nil {
you can replace this with by simply having `return m.Open()`

2017-05-10 06:24 UTC, aanm commented on pkg/bpf/map.go
> +	if m.fd == 0 {
Why not use the `m.openIfNotOpened()`?

2017-05-10 06:24 UTC, aanm commented on pkg/maps/ctmap/ctmap.go
> +type ServiceKey interface {
Why the name `ServiceKey`? Is this related to the notion of virtual IPs for the LB that we have?

2017-05-10 06:24 UTC, aanm commented on pkg/maps/ctmap/ctmap.go
> +	"github.com/op/go-logging"
should be:
```
	"bytes"
	"fmt"
	"unsafe"

	"github.com/cilium/cilium/common"
	"github.com/cilium/cilium/pkg/bpf"

	"github.com/op/go-logging"
```

2017-05-10 06:24 UTC, aanm commented on pkg/maps/ctmap/ctmap.go
>  	CtTypeIPv4Global
All these 4 const are unused

2017-05-10 06:24 UTC, aanm commented on pkg/maps/ctmap/ctmap.go
> +// doGC removes key and its corresponding value from Map m if key has a lifetime less than interval. It sets nextKey's address to be the key after key in map m.
Small nit, can you write this in 80 columns?

2017-05-10 06:24 UTC, aanm commented on pkg/maps/ctmap/ctmap.go
> +	// GetNextKey errors out if we have reached the last entry in the map. This signifies that the entire map has been traversed and that garbage collection is done.
Small nit, can you write this in 80 columns?

2017-05-10 06:24 UTC, aanm commented on pkg/maps/ctmap/ctmap.go
> +// GC runs garbage collection for map m with name mapName with interval interval. It returns how many items were deleted from m.
Small nit, can you write this in 80 columns?

2017-05-10 06:24 UTC, aanm commented on pkg/maps/ctmap/ctmap.go
> +		m.Delete(nextKey)
`err = m.Delete(nextKey)`

2017-05-10 06:24 UTC, aanm commented on pkg/maps/ctmap/ctmap.go
> +		m.Update(nextKey, entry)
No debug message here? :-)
```
if err != nil {
			log.Debugf("error during Update: %s", err)
		}
```

2017-05-10 06:24 UTC, aanm commented on pkg/maps/ctmap/ipv4.go
> +	"bytes"
```
	"bytes"
	"fmt"
	"net"
	"unsafe"

	"github.com/cilium/cilium/common"
	"github.com/cilium/cilium/common/types"
	"github.com/cilium/cilium/pkg/bpf"
	"github.com/cilium/cilium/pkg/u8proto"
```

2017-05-10 06:24 UTC, aanm commented on pkg/maps/ctmap/ipv4.go
> +	Service4Map = bpf.NewMap(MapName4+"_services",
@tgraf I'm lost, do we have a services map for CT?

2017-05-10 06:24 UTC, aanm commented on pkg/maps/ctmap/ipv4.go
> +	Service4GlobalMap = bpf.NewMap(MapName4Global+"services",
The name of `Service4Map` is `MapName4+"_services"` this one doesn't have an underscore, on purpose?

2017-05-10 06:24 UTC, aanm commented on pkg/maps/ctmap/ipv4.go
> +func NewCtKey4(addr net.IP, sport uint16, dport uint16, nexthdr u8proto.U8proto, flags uint8) *CtKey4 {
Seems this function is unused

2017-05-10 06:24 UTC, aanm commented on pkg/maps/ctmap/ipv4.go
> +// Dump writes the contents of key to buffer and returns true if the value for next header in the key is nonzero.
80 columns

2017-05-10 06:24 UTC, aanm commented on pkg/maps/ctmap/ipv4.go
> +func (k CtKey4) Map() *bpf.Map { return Service4Map }
@tgraf I'm not entirely sure that we should be returning something like this, if this is a local map, why are they being pointed to the same name?

2017-05-10 06:24 UTC, aanm commented on pkg/maps/ctmap/ipv6.go
> +func (key CtKey6) Dump(buffer *bytes.Buffer) bool {
@ianvernon He wants you to have `(k CtKey6)` instead of `(key CtKey6)`

2017-05-10 13:40 UTC, tgraf commented on pkg/maps/ctmap/ipv4.go
> +	Service4Map = bpf.NewMap(MapName4+"_services",
Hehe, no. I think this is just an oversight and can be removed.

2017-05-10 13:46 UTC, tgraf commented on pkg/maps/ctmap/ctmap.go
> +type ServiceKey interface {
This should be renamed to `CtKey` which is the interface for the common functions of `CtKey4` and `CtKey6`

2017-05-10 13:47 UTC, tgraf commented on pkg/maps/ctmap/ipv4.go
> +	Service4GlobalMap = bpf.NewMap(MapName4Global+"services",
I think that's jus a leftover from basing this of lbmap and can be removed.

2017-05-10 13:48 UTC, tgraf commented on pkg/maps/ctmap/ipv4.go
> +func (k CtKey4) Map() *bpf.Map { return Service4Map }
lbmap uses `Map()` to hide name for IPv4 and IPv6 specific map names for services map. The difference is that lbmaps are always global, just per address family whereas ctmap is per endpoint unless global.

I think all of the `Map()` usage can be removed and what remains is the address family specific `Convert()`.

2017-05-10 13:49 UTC, tgraf commented
Great work! This exactly the direction that I meant when I opened the issue. Agreed with handling one map at a time. Let's iron out the details here and use it as the new prime example of how to abstract BPF maps.

2017-05-10 17:00 UTC, ianvernon commented on cilium/cmd/bpf_ct_list.go
> +			dumpCtProto(ctmap.MapName6Global, "")
cramp.MapName6Global is assigned the following value: MapName6Global = MapName6 + "global" so there is no need to use args[0] here.

2017-05-10 17:41 UTC, ianvernon commented on daemon/ct.go
> +		file = bpf.MapPath(mapType)
Line 49 is no longer needed - I'll remove it in the next upload.

2017-05-10 17:43 UTC, ianvernon commented on pkg/bpf/map.go
> +		if err := m.Open(); err != nil {
You're right - I don't think we really need this function anymore. I'll refactor accordingly.

2017-05-10 17:46 UTC, ianvernon commented on pkg/bpf/map.go
> +	if m.fd == 0 {
I'm replacing calls to openIfNotOpened with ```if err := m.Open(); err != nil {
			return err
		}``` in the next upload

2017-05-10 17:55 UTC, ianvernon commented on pkg/maps/ctmap/ipv4.go
> +	Service4Map = bpf.NewMap(MapName4+"_services",
OK, I'll remove these maps.

2017-05-10 17:57 UTC, ianvernon commented on pkg/maps/ctmap/ipv4.go
> +func (k CtKey4) Map() *bpf.Map { return Service4Map }
Ah, that makes sense. Thanks for clarifying; I will remove this.

2017-05-10 23:03 UTC, tgraf commented on cilium/cmd/bpf_ct_list.go
> +			dumpCtProto(ctmap.MapName6Global, "")
I'm fine with this. Less dynamic calculation.

2017-05-10 23:21 UTC, tgraf requested changes

2017-05-10 23:21 UTC, tgraf commented on cilium/cmd/bpf_ct_list.go
> +	out, err := ctmap.ToString(m, mapType)
👍

2017-05-10 23:21 UTC, tgraf commented on pkg/maps/ctmap/ctmap.go
> +func DumpToSlice(m *bpf.Map, mapType string) ([]CtEntryDump, error) {
Can this be made private?

2017-05-10 23:21 UTC, tgraf commented on pkg/maps/ctmap/ctmap.go
> +			log.Debugf("error during Delete: %s", err)
👍

2017-05-12 07:10 UTC, tgraf approved these changes

2017-05-12 20:47 UTC, aanm requested changes
Small nits, overall looks good

2017-05-12 20:47 UTC, aanm commented on pkg/bpf/map.go
> +	err := GetNextKey(m.fd, key.GetKeyPtr(), nextKey.GetKeyPtr())
can be `return GetNextKey(m.fd, key.GetKeyPtr(), nextKey.GetKeyPtr())`

2017-05-12 20:47 UTC, aanm commented on pkg/maps/ctmap/ipv4.go
> +// Convert converts CtKey4 fields between host bye order and map byte order.
s/fields/ports

2017-05-12 20:47 UTC, aanm commented on pkg/maps/ctmap/ipv4.go
> +// order.
s/fields/ports

2017-05-12 20:47 UTC, aanm commented on pkg/maps/ctmap/ipv6.go
> +// Convert converts CtKey6 fields between host bye order and map byte order.
s/fields/ports

2017-05-12 20:47 UTC, aanm commented on pkg/maps/ctmap/ipv6.go
> +// Convert converts CtKey6Global fields between host bye order and map byte order.
s/fields/ports

2017-05-12 22:10 UTC, aanm approved these changes

2017-05-12 22:10 UTC, merged