Docs/GSG: Fix some paths on etcd keys
cilium/cilium pull request #6885
Opened 2019-02-01 14:51 UTC by eloycoto

Fix path issues on etcd config.
Added operator to the list.

Fix https://github.com/cilium/cilium/issues/6876

2019-02-01 14:51 UTC, eloycoto commented
test-docs-please

2019-02-01 22:37 UTC, tgraf requested changes

2019-02-01 22:37 UTC, tgraf commented on Documentation/gettingstarted/k8s-install-external-etcd.rst
> +Verify that a cilium pods were started on each of your worker nodes
remove the "a" in "Verify that a cilium pod"

2019-02-04 13:42 UTC, eloycoto commented
test-docs-please

2019-02-04 19:15 UTC, tgraf approved these changes

2019-02-04 19:15 UTC, merged