FQDN proxy keep dnscache sync
cilium/cilium pull request #6981
Opened 2019-02-07 23:09 UTC by tgraf

[Submiting on behalf of @eloycoto]

Two commits:

* The first one added a new functions in endpoint.
* The second one fixes the issue with FQDN restart.

Addressed remaining comments
Supersedes #6974

2019-02-07 23:09 UTC, tgraf commented
test-me-please

2019-02-07 23:19 UTC, ianvernon requested changes

2019-02-07 23:19 UTC, ianvernon commented on pkg/endpoint/endpoint.go
> +	defer owner.GetCompilationLock().RUnlock()
remove this line

2019-02-07 23:19 UTC, ianvernon commented on pkg/endpoint/endpoint.go
> +	owner.GetCompilationLock().RLock()
Shouldn't we hold the Endpoint `BuildMutex` too?

2019-02-07 23:21 UTC, raybejjani approved these changes
We might have a race between builds that hold the compile lock and DNS updates (this would be new because we now have 2 async writers of this file but before it was always serialised via the queue). Is it possible for this to happen:
- a build is queued
- a dns update happens, this writes do disk
- the build uses an old serialisation of the endpoint and overwrites the newer DNS data

I think the answer is no, and all other order-of-operations seem safe.

2019-02-07 23:22 UTC, tgraf commented on pkg/endpoint/endpoint.go
> +	owner.GetCompilationLock().RLock()
Good point, I meant to lock the BuildMutex, not the CompilationLock

2019-02-07 23:27 UTC, tgraf commented
@raybejjani The following could happen:

1. build is queued
2. DNS update happens, trigger is invoked
3. trigger is run, uses latest endpoint data
4. build is executed, uses latest endpoint data as endpoint pointer is passed in

So yes, the race can happen in terms of a DNS update preempting the build execution but I don't thikn we have stale data anywhere as we pass around the endpoint pointer. Does this match your understanding?

2019-02-07 23:30 UTC, raybejjani commented
@tgraf yes, that is exactly what I think will happen. Should be totally fine :)

2019-02-07 23:30 UTC, ianvernon approved these changes

2019-02-08 00:08 UTC, raybejjani commented
test-me-please

2019-02-08 00:56 UTC, joestringer requested changes
Looks good, except the unconditional lock.

2019-02-08 00:56 UTC, joestringer commented on pkg/endpoint/endpoint.go
> +	e.UnconditionalLock()
Can we unconditionally lock here? Sure we looked up the endpoint but could it also disappear?

2019-02-08 00:56 UTC, joestringer commented on pkg/endpoint/bpf.go
> +func (e *Endpoint) writeHeaderfile(prefix string) error {
nit: Removing owner is not part of the fix. I think I'll need it again soon for the templating stuff too, but I can always rebase and reinstate it.

2019-02-08 01:13 UTC, tgraf commented
test-me-please

2019-02-08 01:19 UTC, joestringer approved these changes

2019-02-08 01:42 UTC, tgraf commented
`runtime.RuntimeFQDNPolicies Roundrobin DNS` failed

2019-02-08 01:42 UTC, tgraf commented
test-me-please

2019-02-08 03:43 UTC, ianvernon commented
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9694/testReport/junit/(root)/runtime/RuntimeFQDNPolicies_Roundrobin_DNS/

Round robin DNS test failed again :/

2019-02-08 03:43 UTC, ianvernon commented
test-me-please

2019-02-08 04:45 UTC, merged