FQDN: Add metrics for Garbage collector cleanup.
cilium/cilium pull request #6985
Opened 2019-02-08 08:17 UTC by eloycoto

This commit add the option to get the number of names that has been
cleaned on a GC job.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

Please ensure your pull request adheres to the following guidelines:

2019-02-08 08:17 UTC, eloycoto commented
test-me-please

2019-02-08 08:19 UTC, eloycoto commented
test-me-please

2019-02-08 08:51 UTC, eloycoto commented
test-me-please

2019-02-08 15:08 UTC, aanm requested changes

2019-02-08 15:08 UTC, aanm commented on Documentation/configuration/metrics.rst
> +* ``fqdn_garbage_collector"``: Number of FQDN that has been cleaned on FQDN
remove the `"`

2019-02-08 16:01 UTC, eloycoto commented
test-me-please

2019-02-08 16:01 UTC, eloycoto commented on Documentation/configuration/metrics.rst
> +* ``fqdn_garbage_collector"``: Number of FQDN that has been cleaned on FQDN
@aanm done.

2019-02-08 16:46 UTC, aanm approved these changes

2019-02-08 17:41 UTC, joestringer requested changes

2019-02-08 17:41 UTC, joestringer commented on pkg/metrics/metrics.go
> +		Name: "fqdn_garbage_collector",
I'm not sure that the name of this metric effectively communicates the meaning of the metric, one shouldn't need to read the help text to understand. There's conventions documented here which I think would be useful to follow: https://prometheus.io/docs/practices/naming/ . Ideally we'd have a bit of framework that adds to all the metrics and runs `promtool check metrics` against all of them, but for the moment I guess we run it locally.

Here's my naming suggestion, but I'm open to other suggestion too:

`fqdn_gc_deletions_total`

This communicates the area (fqdn), subarea (gc ie garbage collector, we've used this before for conntrack), type of operation (deletion) and unit (_total_ is the standard way to count integer units).

2019-02-12 07:19 UTC, eloycoto commented
test-me-please

2019-02-12 10:41 UTC, nebril approved these changes
Small nitpick in doc, looks good otherwise

2019-02-12 10:41 UTC, nebril commented on Documentation/configuration/metrics.rst
> +* ``fqdn_garbage_collector``: Number of FQDN that has been cleaned on FQDN
`s/Number of FQDN/Number of FQDNs`

2019-02-12 13:39 UTC, eloycoto commented
test-me-please

2019-02-12 17:06 UTC, joestringer requested changes
Just one last thing.

2019-02-12 17:06 UTC, joestringer commented on Documentation/configuration/metrics.rst
> +* ``fqdn_garbage_collector``: Number of FQDNs that has been cleaned on FQDN
Metric name needs updating in docs.

2019-02-13 01:53 UTC, tgraf requested changes

2019-02-13 01:53 UTC, tgraf commented on pkg/metrics/metrics.go
> +		Help: "Number of FQDNs that has been cleaned on FQDN Garbage collector job",
`... that have been cleaned...`

2019-02-13 17:38 UTC, eloycoto commented
test-me-please

2019-02-14 18:57 UTC, ianvernon commented
Boot VMs stage timed out in last build: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9856/execution/node/58/log/

Unrelated to these changes, triggering again.

2019-02-14 18:57 UTC, ianvernon commented
test-me-please

2019-02-14 18:59 UTC, ianvernon approved these changes

2019-02-15 01:06 UTC, joestringer approved these changes

2019-02-15 07:48 UTC, eloycoto commented
test-me-please

2019-02-15 18:09 UTC, ianvernon commented
@eloycoto needs rebase.

2019-02-16 16:06 UTC, tgraf approved these changes

2019-02-18 11:16 UTC, eloycoto commented
test-me-please

2019-02-18 21:09 UTC, ianvernon commented
CI tests actually passed, Coveralls failed due to issues unrelated to this PR:

```
Bad response status from coveralls: 422
{"message":"Couldn't find a repository matching this job.","error":true}
travis_time:end:0a504200:start=1550488802945838263,finish=1550489219221850859,duration=416276012596
[0K[31;1mThe command "./.travis/build.sh" exited with 1.[0m
```

2019-02-18 21:10 UTC, merged