Simplified creation of k8s secrets for IPSec integration
cilium/cilium pull request #7048
Opened 2019-02-12 20:55 UTC by aanm

read per commit message

2019-02-12 20:55 UTC, aanm commented
test-me-please

2019-02-13 03:49 UTC, jrfastab commented
test-missed-k8s

2019-02-13 03:50 UTC, jrfastab commented
test-missed-k8s

2019-02-13 03:51 UTC, jrfastab commented
test-me-please

2019-02-13 10:45 UTC, aanm commented
test-missed-k8s

2019-02-13 17:46 UTC, jrfastab commented
hit FQDN failure it seems unlikely that this could cause any issues there so lets retry.

2019-02-13 17:47 UTC, jrfastab commented
test-missed-k8s

2019-02-13 20:53 UTC, ianvernon approved these changes
LGTM for docs.

2019-02-13 21:51 UTC, tgraf requested changes

2019-02-13 21:51 UTC, tgraf commented on pkg/datapath/linux/node.go
> +		log.WithError(err).Error("Unable to replace node ip sec in-route")
I don't understand this error message.

```Unable to replace IPsec node outgoing route```

2019-02-13 21:51 UTC, tgraf commented on pkg/datapath/linux/node.go
> +		log.WithError(err).Error("Unable to replace node ip sec in-route")
Same here

2019-02-13 21:51 UTC, tgraf commented on pkg/datapath/linux/ipsec/ipsec_linux.go
> +		// As we have released the v1.4.0 docs telling the users to write the
Move this into the function where the prefix is removed

2019-02-14 12:27 UTC, aanm commented
test-me-please

2019-02-14 14:15 UTC, jrfastab approved these changes

2019-02-14 15:12 UTC, aanm commented
hit https://github.com/cilium/cilium/issues/6786 in the CI, merging as it was the only test failure and it's a known issue.

2019-02-14 15:12 UTC, merged