Backport PR-7054
cilium/cilium pull request #7073
Opened 2019-02-14 09:26 UTC by eloycoto

Due the pkg/datapath/maps does not exists on 1.3 branch, I need to
manually backport this PR.

Commits backported:

19767816a9a8573bce1860d774c3ad7bdb1348b2
3adbd7f5e95f4c5e18eaf29aff454a4146017fd2

PR #7054 

@joestringer please review. 

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

2019-02-14 09:26 UTC, eloycoto commented
test-me-please

2019-02-14 19:13 UTC, ianvernon requested changes

2019-02-14 19:13 UTC, ianvernon commented on daemon/daemon.go
> +		policymap.MapName,
nit - `policymap.MapName` is duplicated here.

2019-02-15 01:10 UTC, joestringer reviewed
Looks fine other than Ian's comment above.

2019-02-15 07:35 UTC, eloycoto commented
test-me-please

2019-02-15 18:07 UTC, ianvernon commented
Build failure: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9912/

`JoinEP` found in logs.

Should be unrelated - trying again.

2019-02-15 18:07 UTC, ianvernon commented
test-me-please

2019-02-15 18:27 UTC, ianvernon approved these changes

2019-02-15 18:27 UTC, ianvernon commented
test-missed-k8s

2019-02-15 18:27 UTC, ianvernon commented
test-docs-please

2019-02-15 21:01 UTC, ianvernon commented
Doc test failed due to failure to check out from version control:  https://jenkins.cilium.io/job/Cilium-PR-Doc-Tests/917/flowGraphTable/

2019-02-15 21:01 UTC, ianvernon commented
test-docs-please

2019-02-15 21:01 UTC, ianvernon commented
So did K8s tests, sigh: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1679/flowGraphTable/

2019-02-15 21:01 UTC, ianvernon commented
test-missed-k8s

2019-02-18 11:27 UTC, eloycoto commented
Issues on getting cilium ready, does not looks related: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1681/testReport/junit/k8s-1/8/K8sChaosTest_Connectivity_demo_application_Endpoint_can_still_connect_while_Cilium_is_not_running/

2019-02-18 11:28 UTC, eloycoto commented
test-missed-k8s

2019-02-18 15:39 UTC, tgraf approved these changes

2019-02-18 15:40 UTC, merged