policy: Add missinng import error metric calls
cilium/cilium pull request #7161
Opened 2019-02-20 15:31 UTC by mrostecki

After this change, policy import error metric is increased after every
logged error in the whole pkg/policy package in functions/methods which
are called when policies are imported.

Fixes #7022

Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>

2019-02-20 15:32 UTC, mrostecki commented
test-me-please

2019-02-20 15:33 UTC, mrostecki commented
test-me-please

2019-02-20 21:09 UTC, joestringer requested changes
Looking at these error handling cases, I don't understand why we don't always return errors to the caller for handling. If we *are* triggering these bad conditions during policy import and they're not otherwise triggered then we should be incrementing the metrics.

I have a few comments below. In particular the `allows...` are not policy import.

2019-02-20 21:09 UTC, joestringer commented on pkg/policy/groups/actions.go
> +			metrics.PolicyImportErrors.Inc()
In this case, the error is returned to the caller so I think it should already be measured?

Oh, but sometimes the caller ignores the error and in general it tends to be handled by controllers. Hmm, I see. In that case it's probably more consistent to keep this here so at least this entire function guarantees that the error is incremented in bad conditions.

2019-02-20 21:09 UTC, joestringer commented on pkg/policy/repository.go
> +		metrics.PolicyImportErrors.Inc()
This should not be policy import time, this is evaluating the policy.

2019-02-20 21:09 UTC, joestringer commented on pkg/policy/repository.go
> +		metrics.PolicyImportErrors.Inc()
Same here, this is not importing the policy but applying the policy.

2019-02-21 13:28 UTC, mrostecki commented on pkg/policy/groups/actions.go
> +			metrics.PolicyImportErrors.Inc()
Yes, I think we should keep it here. Otherwise we would need to have logic for detecting specific errors in `UpdateController` method of Manager.

2019-02-21 13:34 UTC, mrostecki commented
test-me-please

2019-02-21 18:42 UTC, ianvernon commented on pkg/policy/api/selector.go
> +		metrics.PolicyImportErrors.Inc()
We should ideally never hit errors here and should resolve this at import time - I filed  https://github.com/cilium/cilium/issues/7176 to account for that. Having the metric here in the meantime is good.

2019-02-21 18:46 UTC, ianvernon requested changes

2019-02-21 18:46 UTC, ianvernon commented on pkg/policy/groups/actions.go
> +			metrics.PolicyImportErrors.Inc()
I don't think this one is necessary here because updating status doesn't affect whether there was an error importing the policy itself.

2019-02-21 18:46 UTC, ianvernon commented on pkg/policy/groups/actions.go
> +		metrics.PolicyImportErrors.Inc()
Same here.

2019-02-22 10:18 UTC, aanm approved these changes

2019-02-22 11:48 UTC, mrostecki commented
@ianvernon Thanks, PTAL!

2019-02-22 11:49 UTC, mrostecki commented
test-me-please

2019-02-22 23:26 UTC, joestringer approved these changes

2019-02-26 16:55 UTC, merged