Pr/backport/v1.3 2019 02 19
cilium/cilium pull request #7165
Opened 2019-02-20 18:41 UTC by raybejjani

Backported

 * PR: 7144 -- Wait for for k8s objects until are synced and processed before initializing cilium daemon (@aanm) -- https://github.com/cilium/cilium/pull/7144
@aanm This had a minor conflict. I think I did it correctly.

 * PR: 7139 -- policy: Fix ipcache synchronization on startup (@tgraf) -- https://github.com/cilium/cilium/pull/7139
@tgraf This had a conflict and I think I put the code back in the right place, but I haven't verified anything beyond that it compiles.

 * PR: 7103 -- Change endpoint policy status map to regular map (@nebril) -- https://github.com/cilium/cilium/pull/7103

 * PR: 7076 -- docs: Add note about triggering builds with net-next (@brb) -- https://github.com/cilium/cilium/pull/7076

Skipped
--------
 * PR: 7147 -- .travis: as coverall is not working we will disable it (@aanm) -- https://github.com/cilium/cilium/pull/7147
@aanm this file doesn't exist in 1.3 and I couldn't find another one

2019-02-20 18:41 UTC, raybejjani commented
test-me-please

2019-02-20 18:46 UTC, raybejjani commented
test-docs-please

2019-02-20 20:05 UTC, ianvernon commented
test-missed-k8s

2019-02-20 20:09 UTC, ianvernon approved these changes

2019-02-20 20:09 UTC, ianvernon requested changes
Reverting approval, as CI failure looks suspicious.

2019-02-21 14:06 UTC, raybejjani commented
@tgraf I pulled out * PR: 7139 -- policy: Fix ipcache synchronization on startup (@tgraf) -- #7139. From what I can tell the code is the same as master but the ipcache map is already open on startup. I can look further but you probably have a better idea.

2019-02-21 14:07 UTC, raybejjani commented
test-docs-please

2019-02-21 14:07 UTC, raybejjani commented
test-me-please

2019-02-21 15:35 UTC, raybejjani commented
test-missed-k8s

2019-02-21 18:11 UTC, ianvernon approved these changes

2019-02-21 18:12 UTC, merged

2019-02-25 22:29 UTC, joestringer commented
This also backported #7159....