agent: Remove deprecated --auto-ipv6-node-routes option
cilium/cilium pull request #7199
Opened 2019-02-22 23:16 UTC by tgraf

Fixes: #4082

2019-02-22 23:44 UTC, tgraf commented
test-me-please

2019-02-25 09:31 UTC, aanm requested changes
Please add in the documentation that the option was removed.

2019-02-25 22:09 UTC, joestringer approved these changes

2019-02-26 08:56 UTC, tgraf commented
test-docs-please

2019-02-26 09:27 UTC, merged