daemon: Remove old health EP state dirs in restore
cilium/cilium pull request #7249
Opened 2019-03-01 00:05 UTC by joestringer

In the restore logic, when attempting to restore endpoints, if there are
old health endpoint state files left on the filesystem, clean them up as
these endpoints will not be restored, and otherwise they will just hang
around forever.

This is likely to mostly affect non-containerised environments, probably
with the biggest impact being in developer VMs where devs often restart
cilium. Marking for backport because I think it's safe, but it's not pressing.
Happy to drop the backport labels if people feel strongly otherwise.

2019-03-01 00:06 UTC, joestringer commented
test-me-please

2019-03-01 09:26 UTC, brb submitted a review, later dismissed

2019-03-01 09:26 UTC, brb commented on daemon/state.go
> +			healthStateDir := filepath.Join(option.Config.StateDir, ep.StringID())
Maybe we can use `ep.StateDirectoryPath()` here?

2019-03-01 17:38 UTC, joestringer commented
test-me-please

2019-03-04 08:49 UTC, tgraf requested changes

2019-03-04 08:49 UTC, tgraf commented on daemon/state.go
> +				}).Infof("Cannot clean up old health state directory")
Please change this from info to warning

2019-03-04 08:50 UTC, tgraf commented
` k8s-1.13.K8sFQDNTest Restart Cilium validate that FQDN is still working` failed

2019-03-04 17:16 UTC, joestringer commented
test-me-please

2019-03-04 19:37 UTC, ianvernon approved these changes

2019-03-04 19:46 UTC, brb approved these changes

2019-03-04 19:48 UTC, merged

2019-03-11 18:33 UTC, joestringer commented
v1.3 used a slightly different approach in `daemon/state.go` which collected a list of endpoints to clean up the state of, then clear them out. That logic is equivalent to the logic proposed in this PR, so v1.3 is not affected. Removed backport tag.