test: Do not install Vbox Guest Additions
cilium/cilium pull request #7255
Opened 2019-03-01 13:57 UTC by brb

Currently, Virtualbox Guest Additions are installed to a test VM
image when it gets build by packer-ci. However, when we start a VM
on a Virtualbox which version does not match with the version
of the additions (i.e. != 5.2.0), either Vagrant or Vagrant's plugin
`vbguest` re-installs the additions which includes `mount.vboxsf`.

The latter is not compatible with the custom vboxsf version we use
in ubuntu-next and makes the following command to fail:

    mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

Removing the `mount.vboxsf` fixes the problem. However, I couldn't
find an easy way to remove the binary before Vagrant starts
syncing shared folders, thus I chose not to install the additions.

2019-03-01 13:58 UTC, brb commented
test-me-please

2019-03-01 15:05 UTC, nebril commented
I wonder if this won't make the local development harder? Are we using guestadditions to sync Cilium code to ginkgo vms?

2019-03-01 15:16 UTC, eloycoto commented
I'm not 100% agree with this, VBOX 6 will be used in the near future, and I would not add this complexity in the code, I would like to keep the Vagrantfile as simple and declarative as possible.

2019-03-01 15:53 UTC, brb commented
> I wonder if this won't make the local development harder?

The additions are installed when we build a VM image on packer-ci. My PR is for preventing Vagrant to re-install them when it detects that versions do not match. At least on my machine with Virtualbox 6.0.4 I haven't hit any problem due to different versions.

> I'm not 100% agree with this

Would you agree, if I make disabling of the check optional while we are still using Virtualbox 5.2? The option could go away after we have upgraded to Virtualbox 6.0.

2019-03-01 16:02 UTC, brb commented
TIL: Vagrant supports a global configuration (`~/.vagrant.d/Vagrantfile`), so I can put those settings locally.

However, I'm afraid that someone will trip over the mount problem and waste time debugging it. Maybe updating the contributing docs is enough?

2019-03-04 08:47 UTC, tgraf requested changes

2019-03-04 08:47 UTC, tgraf commented on test/Vagrantfile
> +    $CHECK_GUEST_ADDITIONS = false
Please add a comment that says that the guest additions are already installed in the box image and include a link to the packer ci scripts for clear reference.

2019-03-05 19:07 UTC, ianvernon approved these changes

2019-03-05 22:43 UTC, aanm approved these changes

2019-03-08 21:09 UTC, closed without merging