Test: Make a By message on connection test.
cilium/cilium pull request #7267
Opened 2019-03-03 20:44 UTC by eloycoto

Make a By message to make sure to know where the test is failing.

Try to debug issues:
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/6100/execution/node/90/log/?consoleFull

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

2019-03-03 20:44 UTC, eloycoto commented
test-me-please

2019-03-04 08:45 UTC, tgraf requested changes

2019-03-04 08:45 UTC, tgraf commented on test/k8sT/Updates.go
> -			err = kubectl.CiliumEndpointWaitReady()
Please state  in the commit message why removing this is needed.

2019-03-04 10:15 UTC, eloycoto commented
test-me-please

2019-03-04 10:42 UTC, tgraf approved these changes

2019-03-04 14:00 UTC, eloycoto commented
FQDN issue: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/10382/testReport/junit/(root)/runtime/RuntimeFQDNPolicies_Implements_matchPattern_____/

2019-03-04 14:00 UTC, eloycoto commented
test-me-please

2019-03-04 16:37 UTC, ianvernon approved these changes

2019-03-04 16:37 UTC, merged