Use official k8s watcher to watch for k8s events
cilium/cilium pull request #7301
Opened 2019-03-05 21:32 UTC by aanm

Long story short: don't reinvent the wheel. Read per commit. Last commit can be seen as a bug fix, I can create a backport commit for that bug fix if anyone wants it.

Fixes: #6252

2019-03-05 21:49 UTC, joestringer reviewed
Janitors are requested for review here, but it looks like the agent/k8s teams could provide much better input. Acknowledging the PR but not reviewing at this stage.

2019-03-05 21:51 UTC, aanm commented
test-me-please

2019-03-05 22:03 UTC, aanm commented
test-me-please

2019-03-06 00:21 UTC, ianvernon approved these changes

2019-03-06 08:26 UTC, aanm commented
test-me-please

2019-03-06 10:34 UTC, tgraf requested changes

2019-03-06 10:34 UTC, tgraf commented on daemon/k8s_watcher.go
> +	serKNPs := serializer.NewFunctionQueue(1024)
Let's make the 1024 configurable via an option.

2019-03-06 10:34 UTC, tgraf commented on pkg/k8s/factory_functions_test.go
> -func (s *K8sSuite) Test_missingK8sNetworkPolicyV1(c *C) {
I assume this should be folded into the previous commit?

2019-03-06 10:34 UTC, tgraf commented on daemon/k8s_watcher.go
> +								return
I think we need to cover this with a metric somehow to understand how much we are ignoring. Ideally we bump a metric for each event received here and have a label type = { invalid | equal | valid }

I have some ideas here. Happy to work on this after we merge this PR.

2019-03-06 12:06 UTC, aanm commented
test-me-please

2019-03-06 13:29 UTC, tgraf approved these changes

2019-03-06 13:40 UTC, merged