CMD: Use tabwritter on fqdn cache list.
cilium/cilium pull request #7318
Opened 2019-03-06 09:45 UTC by eloycoto

Fix #7300

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

2019-03-06 09:45 UTC, eloycoto commented
test-me-please

2019-03-06 14:36 UTC, nebril requested changes

2019-03-06 14:36 UTC, nebril commented on cilium/cmd/fqdn.go
> +		fmt.Fprintf(w, "%d\t%s\t%d\t%s\t%s\n",
Can you add a trailing `\t` before the newline? This way, the last column will also be alligned.

2019-03-06 14:36 UTC, nebril commented on cilium/cmd/fqdn.go
> +	fmt.Fprintln(w, "Endpoint\tFQDN\tTTL\tExpirationTime\tIPs")
Can you add a trailing `\t` here? https://play.golang.org/p/e2w1hO5EeJI

2019-03-06 15:15 UTC, eloycoto commented
test-me-please

2019-03-06 15:17 UTC, eloycoto commented
test-me-please

2019-03-06 17:45 UTC, ianvernon approved these changes

2019-03-06 17:47 UTC, ianvernon commented
RuntimeFQDNPolicies CNAME follow test failed; https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/10539/testReport/junit/(root)/runtime/RuntimeFQDNPolicies_CNAME_follow/

2019-03-06 17:47 UTC, ianvernon commented
test-me-please

2019-03-06 23:46 UTC, joestringer approved these changes

2019-03-07 00:48 UTC, joestringer commented
Hit #7105, but this is a CLI change. Clearly unrelated, will merge.

2019-03-07 00:48 UTC, merged