Abort identity allocation when endpoint creation is aborted
cilium/cilium pull request #7322
Opened 2019-03-06 13:46 UTC by tgraf

In #7128 it was observed that:
 * kvstore operations can continue to block even when etcd connectivity is given. This is due to lack of quorum
 * The identity allocation will thus be attempted aggressively. The operation will retry many times. Each of the attempts can then block on the local or distributed lock for a long time.
 * In the meantime, the endpoint creation will time out due to the API caller giving up.
 * The identity allocation is not aborted in this case so all remaining attempts will be executed which will continue to add contention to the lock. In particular if the local lock has been acquired already.

Resolution:
Abort identity allocation based on context provided from API caller.

2019-03-06 13:55 UTC, aanm requested changes

2019-03-06 13:55 UTC, aanm commented on pkg/endpoint/endpoint.go
In this exact line the context might already be canceled, this means 2 things:

1) the identity allocated needs to be released
2) the `releaseNewlyAllocatedIdentity` function, which uses an already canceled context will never be executed as the context was canceled.

2019-03-06 14:05 UTC, tgraf commented on pkg/endpoint/endpoint.go
Yes. Maybe just pass a new context with a one minute timeout?

2019-03-06 14:06 UTC, tgraf commented on pkg/endpoint/endpoint.go
The same is true for the `Release()` further down.

2019-03-06 14:10 UTC, tgraf commented on pkg/endpoint/endpoint.go
@aanm Fixed, have a look.

2019-03-06 14:45 UTC, aanm approved these changes

2019-03-06 15:18 UTC, tgraf commented
test-me-please

2019-03-06 16:24 UTC, jrfastab approved these changes

2019-03-06 17:34 UTC, ianvernon approved these changes

2019-03-06 17:34 UTC, ianvernon commented
@tgraf needs rebase

2019-03-07 00:03 UTC, tgraf commented
test-me-please

2019-03-07 02:46 UTC, jrfastab commented
test-me-please

2019-03-07 04:27 UTC, merged