k8s: add hidden option to use JSONPatch to update CNP and CEP status
cilium/cilium pull request #7351
Opened 2019-03-08 13:18 UTC by aanm

As this option can be used in certain k8s version we should make
optional as JSON Patch might work for some k8s versions. By default,
this flag will have no effect for k8s versions >= 1.13.

Signed-off-by: André Martins <andre@cilium.dev>

2019-03-08 13:46 UTC, tgraf requested changes

2019-03-08 13:46 UTC, tgraf commented on pkg/option/config.go
> +	K8sUseJSONPatch = "k8s-use-json-patch"
Rename this to `k8s-force-json-path` so it's clear that's in not an opt-in but a force flag.

2019-03-08 14:27 UTC, aanm commented
test-me-please

2019-03-08 14:32 UTC, tgraf approved these changes

2019-03-08 15:38 UTC, tgraf commented
@aanm Do you need to have this merged into master right now? I assume you primarily need this for the scale testing. It will be much simpler to rebase this on top of #7349 than the other way around.

2019-03-11 13:26 UTC, aanm commented
test-me-please

2019-03-11 14:51 UTC, merged