fix: enable auto-compaction of etcd by default
cilium/cilium pull request #7399
Opened 2019-03-14 10:08 UTC by moshloop

Enable auto-compaction of etcd to prevent mvcc: database space exceeded errors

```release-note
cilium-etcd-operator: enable auto-compaction by default
```

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cilium/cilium/7399)

2019-03-14 10:23 UTC, aanm requested changes
@moshloop thanks for the change. Can you provide a reason why `1` is a good compaction retention?

2019-03-14 11:37 UTC, moshloop commented
I am not sure if it is necessary to retain any versions and 1 (or 1h) seems to be a common value

2019-03-14 15:18 UTC, aanm commented
> I am not sure if it is necessary to retain any versions and 1 (or 1h) seems to be a common value

Ah ok. That makes more sense. We have been testing with "25000", not hours but based on the revision number. Would that sound sane to you as well?

2019-03-14 17:35 UTC, moshloop commented
Calico uses a [1h](https://github.com/projectcalico/calico/blob/master/master/getting-started/kubernetes/installation/hosted/etcd.yaml#L58) window.  Seeing as etcd is going to run a compaction job periodically anyway and I don't think there really is a use case to go back in time (as I understand etcd is used more as a cache as it's populated on creation anyway) it is probably safer to have predictable compaction rather than risk storage being exceeded.

2019-03-14 19:26 UTC, aanm commented
> Calico uses a [1h](https://github.com/projectcalico/calico/blob/master/master/getting-started/kubernetes/installation/hosted/etcd.yaml#L58) window. Seeing as etcd is going to run a compaction job periodically anyway and I don't think there really is a use case to go back in time (as I understand etcd is used more as a cache as it's populated on creation anyway) it is probably safer to have predictable compaction rather than risk storage being exceeded.

@moshloop agreed. Can you then change the file in `examples/kubernetes/templates/v1/cilium-etcd-operator.yaml.sed` by adding this?
```
        - name: CILIUM_ETCD_META_ETCD_AUTO_COMPACTION_MODE
          value: "revision"
        - name: CILIUM_ETCD_META_ETCD_AUTO_COMPACTION_RETENTION
          value: "25000"
```

The file that you changed is auto generated so you will need to run `CILIUM_VERSION=latest make -C examples/kubernetes clean all` and commit all files modified

2019-03-15 06:55 UTC, moshloop commented
Would a revision based compaction strategy still not potentially lead to out of space if there is lots of churn, but not all on the same key?

2019-03-15 13:08 UTC, aanm commented
> Would a revision based compaction strategy still not potentially lead to out of space if there is lots of churn, but not all on the same key?

@moshloop Can you elaborate? If I understand the etcd behavior correctly is that having the compaction on a time basis can have more probability to run out of space since in between that time period lots of things can happen.

2019-03-15 13:23 UTC, moshloop commented
My bad - I was under the mistaken impression that revisions are per key, and not global in which case I agree revision based compaction is more predictable

2019-03-15 13:25 UTC, aanm approved these changes

2019-03-15 13:25 UTC, aanm commented on examples/kubernetes/README.rst
> +To make a change to a template and all versions of Kubernetes run: :code:`CILIUM_VERSION=latest make -C examples/kubernetes clean all`
Thanks for adding this!

2019-03-15 13:25 UTC, aanm commented
test-me-please

2019-03-15 15:14 UTC, nebril approved these changes

2019-03-16 08:43 UTC, aanm commented
test-me-please

2019-03-16 11:42 UTC, merged