make selective regeneration of endpoints configurable
cilium/cilium pull request #7467
Opened 2019-03-21 22:59 UTC by ianvernon

Provide an option to end-users of Cilium to always regenerate all endpoints upon
policy changes instead of selectively regenerating endpoints based on the
content of the policy change. The option is called
"enable-selective-regeneration", and is hidden by default.
This option can be enabled in case the selective regeneration logic becomes
overwhelmed and blocks the policy API. This is not expected; this is a 
fallback, just in case :) 

Signed-off by: Ian Vernon <ian@cilium.io>

2019-03-21 23:00 UTC, ianvernon commented
test-me-please

2019-03-22 00:36 UTC, ianvernon commented
test-me-please

2019-03-22 10:37 UTC, aanm approved these changes

2019-03-22 15:52 UTC, tgraf requested changes
You want to set `SelectiveRegeneration: true` on `pkg/option.config.go:863` as well to make sure it is enabled for unit tests

2019-03-22 16:32 UTC, ianvernon commented
@tgraf nice catch, fixed in latest upload

2019-03-22 16:32 UTC, ianvernon commented
test-me-please

2019-03-22 17:52 UTC, vadorovsky approved these changes

2019-03-22 17:55 UTC, tgraf approved these changes

2019-03-22 17:55 UTC, merged