FQDN: Do not lock twice the endpoint Manager.
cilium/cilium pull request #7508
Opened 2019-03-26 15:19 UTC by eloycoto

In DNS proxy all the information about the endpoint is already gathered
from the endpoint manager in the ServeDNS function, this function called
a few times to NotifyDNSMsg, and this function also lock the endpoint
manager to retrieve endpoint.

This commit send the endpointID and the endpointAddress in the callback,
so the number of locks in the EndpointManager decreases and make the
dns-proxy a bit faster. Also the lookups are using the endpointManager
map instead of the IP, so are a bit faster.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

2019-03-26 15:19 UTC, eloycoto commented
test-me-please

2019-03-26 16:04 UTC, eloycoto commented
test-me-please

2019-03-26 18:57 UTC, ianvernon commented
I might be missing something, but it appears as if the same number of `endpointmanager` lookups are performed here?

2019-03-26 21:46 UTC, aanm requested changes

2019-03-26 21:46 UTC, aanm commented on pkg/fqdn/dnsproxy/proxy.go
> +	EpAddr string
Why isn't this a `net.IP`?

2019-03-26 21:46 UTC, aanm commented on pkg/fqdn/dnsproxy/proxy.go
> +	EpID   int64
s/int64/uint64

2019-03-27 09:16 UTC, eloycoto commented
test-me-please

2019-03-27 13:48 UTC, raybejjani requested changes
@eloycoto Sorry, I wasn't clear in what I was proposing. I was expecting that we could remove LookupEndpointByID from ServeDNS completely. We would keep a pointer to the endpoint inside DNSProxy that we update in `DNSProxy.UpdateAllowed`. The idea was to avoid locking during `ServeDNS`, so this might also mean caching some non-changing data on the endpoint (like its IPs) but `Endpoint.ID` might be enough for all the logs we use.

EDIT: We chatted offline. eloycoto pointed out that keeping a copy of the endpoint in the proxy would likely have more raciness than just doing a single lookup in endpoint manager. We can do that and ditch the EpContext type, though, since the Endpoint.ID field is available on the endpoint objects.
Separately, there seems to be a nil-dereference in some logging code when an endpoint can't be found that we'll also fix.

2019-03-27 15:17 UTC, eloycoto commented
test-me-please

2019-03-28 11:50 UTC, raybejjani approved these changes
Apart from one debug message, LGTM

2019-03-28 11:50 UTC, raybejjani commented on pkg/fqdn/dnsproxy/proxy.go
> -	scopedLog.Debug("Handling DNS query from endpoint")
Could you leave this debug line in? It's useful when diagnosing whether the proxy is being slow to begin handling packets or something else is slow in NotifyOnDNSMsg.

2019-03-29 08:18 UTC, eloycoto commented
test-me-please

2019-03-29 09:50 UTC, eloycoto commented
test-me-please

2019-03-29 17:18 UTC, merged