k8s: add useragent
cilium/cilium pull request #7791
Opened 2019-04-19 09:47 UTC by pyaillet

Signed-off-by: Pierre-Yves Aillet <pyaillet@gmail.com>

This PR adds a UserAgent in k8s requests.
The format of the useragent is `Cilium 0.13.90 a722bdb 2018-01-09T22:32:37+01:00 go version go1.9 linux/amd64` for example

Fixes: #7634

```release-note
Add `Cilium <VERSION>` as k8s useragent
```

2019-04-19 15:56 UTC, ianvernon commented
test-me-please

2019-04-19 19:56 UTC, ianvernon commented
Both CI runs hit #7615 : 

* https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1923/
* https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11748/

2019-04-19 20:01 UTC, ianvernon commented
Going to wait for @aanm to check to ensure this is what he wants since he filed the initial issue.

2019-04-23 12:15 UTC, aanm approved these changes

2019-04-23 12:16 UTC, aanm requested changes

2019-04-23 12:16 UTC, aanm commented on pkg/k8s/client.go
> +	userAgent := fmt.Sprintf("Cilium %s", version.Version)
The user agent also needs to be added to the configuration returned on line 51 and 55

2019-04-23 12:17 UTC, aanm commented
@pyaillet thanks for the change, please take a look at my change requests

2019-04-23 13:16 UTC, nebril commented
test-me-please

2019-04-23 13:16 UTC, nebril approved these changes

2019-04-23 13:24 UTC, vadorovsky approved these changes
Looks good, thanks for your contribution!

2019-04-23 13:25 UTC, aanm approved these changes

2019-04-24 20:48 UTC, ianvernon commented
test-me-please

2019-04-24 20:48 UTC, ianvernon commented
test-missed-k8s

2019-04-25 19:11 UTC, nirmoy commented
test-me-please

2019-04-26 14:15 UTC, ianvernon commented
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11882/

```
20:01:09  K8sChaosTest Restart with long lived connections 
20:01:09    TCP connection is not dropped when cilium restarts
20:01:09    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:410
20:01:11  STEP: Deleting all cilium pods
20:01:11  STEP: Waiting cilium pods to terminate
20:02:04  STEP: Waiting for cilium pods to be ready
20:05:56  === Test Finished at 2019-04-25T20:05:56Z====
20:26:04  ===================== TEST FAILED =====================
20:28:19  cmd: kubectl get pods -o wide --all-namespaces
20:28:19  Exitcode: 0 
20:28:19  Stdout:
20:28:19   	 NAMESPACE     NAME                                    READY     STATUS             RESTARTS   AGE       IP              NODE
20:28:19  	 default       netperf-client                          1/1       Running            0          27m       10.10.0.173     k8s1
20:28:19  	 kube-system   cilium-6pqfx                            0/1       NodeLost           0          26m       192.168.36.12   k8s2
20:28:19  	 kube-system   cilium-etcd-749wglg64p                  1/1       Unknown            0          43m       10.10.1.74      k8s2
20:28:19  	 kube-system   cilium-etcd-bslw9kzqz2                  1/1       Unknown            0          43m       10.10.1.181     k8s2
20:28:19  	 kube-system   cilium-etcd-j4xsjdvpcm                  1/1       Running            0          43m       10.10.0.7       k8s1
20:28:19  	 kube-system   cilium-etcd-operator-77d4ddf8c6-n47fb   1/1       Unknown            0          34m       192.168.36.12   k8s2
20:28:19  	 kube-system   cilium-etcd-operator-77d4ddf8c6-rrnfp   0/1       CrashLoopBackOff   6          21m       192.168.36.11   k8s1
20:28:19  	 kube-system   cilium-kbrlq                            1/1       Running            6          26m       192.168.36.11   k8s1
20:28:19  	 kube-system   cilium-operator-5fb956fc65-2wjx2        0/1       CrashLoopBackOff   9          21m       10.10.0.230     k8s1
20:28:19  	 kube-system   etcd-k8s1                               1/1       Running            0          55m       192.168.36.11   k8s1
20:28:19  	 kube-system   etcd-operator-65476dd78f-whfg5          1/1       Unknown            0          34m       10.10.1.127     k8s2
20:28:19  	 kube-system   kube-apiserver-k8s1                     1/1       Running            0          54m       192.168.36.11   k8s1
20:28:19  	 kube-system   kube-controller-manager-k8s1            1/1       Running            0          54m       192.168.36.11   k8s1
20:28:19  	 kube-system   kube-dns-f4d788bb7-5xdb4                3/3       Running            0          21m       10.10.0.183     k8s1
20:28:19  	 kube-system   kube-dns-f4d788bb7-fzx4z                3/3       Unknown            0          34m       10.10.1.173     k8s2
20:28:19  	 kube-system   kube-proxy-pg7s6                        1/1       NodeLost           0          45m       192.168.36.12   k8s2
20:28:19  	 kube-system   kube-proxy-x8kj9                        1/1       Running            0          55m       192.168.36.11   k8s1
20:28:19  	 kube-system   kube-scheduler-k8s1                     1/1       Running            0          55m       192.168.36.11   k8s1
20:28:19  	 
20:28:19  Stderr:
20:28:19   	 
20:28:19  
20:30:20  cmd: kubectl exec -n kube-system cilium-6pqfx -- cilium service list
20:30:20  Exitcode: 1 
20:30:20  Stdout:
20:30:20   	 
20:30:20  Stderr:
20:30:20   	 Error from server: error dialing backend: dial tcp 192.168.36.12:10250: getsockopt: connection timed out
20:30:20  	 
20:30:20  
20:32:36  cmd: kubectl exec -n kube-system cilium-6pqfx -- cilium endpoint list
20:32:36  Exitcode: 1 
20:32:36  Stdout:
20:32:36   	 
20:32:36  Stderr:
20:32:36   	 Error from server: error dialing backend: dial tcp 192.168.36.12:10250: getsockopt: connection timed out
20:32:36  	 
20:32:36  
20:32:36  cmd: kubectl exec -n kube-system cilium-kbrlq -- cilium service list
20:32:36  Exitcode: 1 
20:32:36  Stdout:
20:32:36   	 
20:32:36  Stderr:
20:32:36   	 error: unable to upgrade connection: container not found ("cilium-agent")
20:32:36  	 
20:32:36  
20:32:36  cmd: kubectl exec -n kube-system cilium-kbrlq -- cilium endpoint list
20:32:36  Exitcode: 1 
20:32:36  Stdout:
20:32:36   	 
20:32:36  Stderr:
20:32:36   	 error: unable to upgrade connection: container not found ("cilium-agent")
20:32:36  	 
20:32:36  
20:45:54  Sending interrupt signal to process
20:46:03  cleaning up VMs started for k8s tests
20:46:03  
```

Haven't ever seen this! Looks like the VM got into a bad state in the testing infra.

2019-04-26 14:15 UTC, ianvernon commented
test-me-please

2019-04-30 10:39 UTC, aanm commented
test-upstream-k8s

2019-04-30 10:39 UTC, aanm commented
test-k8s-upstream

2019-05-01 14:11 UTC, tgraf commented
test-me-please

2019-05-01 15:37 UTC, tgraf commented
Great work @pyaillet

2019-05-01 15:37 UTC, merged