Docs: minor fixes to AWS EKS and AWS Metadata filtering GSGs
cilium/cilium pull request #7856
Opened 2019-04-26 06:25 UTC by danwent

Minor changes based on recent testing of AWS metadata filtering using an EKS cluster.

2019-04-26 15:22 UTC, danwent commented
test-me-please

2019-04-26 15:41 UTC, ianvernon commented
test-docs-please

2019-04-27 16:14 UTC, ianvernon commented
test-docs-please

2019-04-29 13:30 UTC, nebril requested changes
LGTM overall, two comments inline

2019-04-29 13:30 UTC, nebril commented on Documentation/gettingstarted/aws.rst
> +To do this, identify and delete the existing cilium-operator pod, which will
s/which will/which will be

2019-04-29 13:30 UTC, nebril commented on Documentation/gettingstarted/aws.rst
> +'k8s-worker' security group.    Cilium filtering will then ensure that the only pods allowed
Will multiple spaces before "Cilium" render? If yes, I think they should be deleted.

2019-04-29 20:56 UTC, danwent commented
Thanks @nebril , made the changes you suggested, and added sign-off.   Thanks!

2019-04-30 10:32 UTC, aanm commented
test-docs-please

2019-05-06 16:52 UTC, danwent commented
@nebril  , can you please take a look and confirm that your comments have been addressed?   thanks!

2019-05-07 08:55 UTC, tgraf approved these changes

2019-05-07 08:55 UTC, merged