kvstore: Wait for kvstore to reach quorum
cilium/cilium pull request #7938
Opened 2019-05-07 11:23 UTC by tgraf

So far, the channel returned by the Connected() function of the kvstore client
was closed when the kvstore could be connected to. This did not guarantee that
the kvstore actually had quorum and operations could still block and timeout
afterwards. Wait for a distributed lock to be acquired to identify the moment
quorum has been reached.

Also indicate the quorum status in the kvstore status of `cilium status` for
etcd.

```
KVStore:                Ok   etcd: 1/1 connected, has-quorum=true: https://192.168.33.11:2379 - 3.3.11 (Leader)
```

2019-05-07 11:34 UTC, aanm requested changes

2019-05-07 11:34 UTC, aanm commented on pkg/kvstore/etcd.go
> +				if success {
what happens if `success` is false? `out` will never be closed.

2019-05-07 12:01 UTC, tgraf commented
test-me-please

2019-05-08 10:13 UTC, aanm approved these changes

2019-05-08 10:17 UTC, merged