test: replace guestbook test docker image
cilium/cilium pull request #7955
Opened 2019-05-08 13:24 UTC by aanm

The image docker.io/kubernetes/guestbook:v2 no longer exists so we need
to update the guestbook test to make usage of the new guestbook test
version.

Signed-off-by: André Martins <andre@cilium.io>

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cilium/cilium/7955)

2019-05-08 14:29 UTC, aanm commented
> @aanm Why does this need backports into all branches?

@tgraf the CI test will fail if the image is not in the local cache.

2019-05-08 16:17 UTC, aanm commented
test-missed-k8s

2019-05-08 16:19 UTC, aanm commented
test-missed-k8s

2019-05-08 17:57 UTC, ianvernon requested changes

2019-05-08 17:57 UTC, ianvernon commented on test/k8sT/manifests/guestbook_deployment.json
> +                "app": "guestbook",
The selector in the policy in `guestbook-policy-web.yaml` should change as well to reflect the change in labels.

2019-05-08 18:13 UTC, aanm commented
test-me-please

2019-05-09 10:54 UTC, aanm commented
test-missed-k8s

2019-05-09 20:20 UTC, ianvernon approved these changes

2019-05-09 20:20 UTC, merged