docs: give better troubleshooting for conntrack-gc-interval
cilium/cilium pull request #7961
Opened 2019-05-08 16:59 UTC by aanm

In case the default values of `conntrack-gc-interval` are not good
enought for the end users we should prepare them how to solve the issue.

Signed-off-by: André Martins <andre@cilium.io>

2019-05-08 16:59 UTC, aanm commented
test-docs-please

2019-05-08 17:00 UTC, joestringer approved these changes
Looks good, though I expected this to show up as a new section under the troubleshooting docs rather than upgrade.

2019-05-08 17:01 UTC, aanm commented
> Looks good, though I expected this to show up as a new section under the troubleshooting docs rather than upgrade.

Me too, but I think it's better to give a heads up during these upgrade instructions.

2019-05-08 17:01 UTC, brb commented on Documentation/install/upgrade.rst
> +   value ``bpf-ct-global-any-max`` should be increased. Setting both of these
You probably want to mention the TCP CT here too?

2019-05-08 17:44 UTC, ianvernon requested changes

2019-05-08 17:44 UTC, ianvernon commented on Documentation/install/upgrade.rst
> +   ``--conntrack-gc-interval`` to an interval lower than the default or the
it's advised to set up --> it is recommended to set 

lower than the default or the -->lower than the default. Alternatively, the value for ``bpf-ct-global-any-max`` can be increased.

2019-05-08 18:12 UTC, aanm commented
test-docs-please

2019-05-08 20:02 UTC, joestringer commented
> Me too, but I think it's better to give a heads up during these upgrade instructions.

Why not both? :)

2019-05-09 07:32 UTC, brb requested changes

2019-05-09 07:32 UTC, brb commented on Documentation/install/upgrade.rst
> +   shows ``xx drop (CT: Map insertion failed)`` t is recommended to set
s/t is/it is/

2019-05-09 09:34 UTC, aanm commented
> > Me too, but I think it's better to give a heads up during these upgrade instructions.
> 
> Why not both? :)
> 
> (Well, I guess soon enough people will stop using <4.11 kernels so it won't be a problem..)

@joestringer done

2019-05-09 09:35 UTC, aanm commented
test-docs-please

2019-05-09 09:37 UTC, brb approved these changes
LGTM!

2019-05-09 21:10 UTC, ianvernon approved these changes

2019-05-09 21:13 UTC, joestringer approved these changes

2019-05-09 21:14 UTC, merged