Add initial go.mod file
cilium/cilium pull request #7987
Opened 2019-05-11 01:29 UTC by James203

- workaround for projects that depend on Cilium and need
to use go mod.

Signed-off-by: ashwinp <ashwin@covalent.io>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](http://docs.cilium.io/en/stable/contributing/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue. 
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](http://docs.cilium.io/en/stable/contributing/#dev-coo).
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note

```

2019-05-13 11:04 UTC, aanm commented
@James203 I'll take care of this. The `go.mod` does not match the dependencies that we have in `Gopkg.toml`.

2019-05-13 14:32 UTC, vadorovsky requested changes

2019-05-13 14:32 UTC, mrostecki commented on go.mod
> +	k8s.io/api v0.0.0-20190111032252-67edc246be36
Versions of k8s libraries still look weird. I remeber some discussions in k8s community about prividing go.mod-compatible versioning. Maybe you just need to update all k8s deps to the newest versions or commits?

2019-07-29 13:29 UTC, aanm commented
superseed by #8719

2019-07-29 13:29 UTC, closed without merging