daemon: add option to skip CRD creation
cilium/cilium pull request #7989
Opened 2019-05-12 08:38 UTC by charlyx

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](http://docs.cilium.io/en/stable/contributing/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue. 
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](http://docs.cilium.io/en/stable/contributing/#dev-coo).
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Hi 👋 

First of all, thanks for your work!
We've added a new option called `--skip-crd-creation` that skips automatic CRD creation and let users create it themselves.
We've also added an example of such a creation to help them make it.

Fixes: #7434

Signed-off-by: Pierre-Yves AILLET <pyaillet@gmail.com>
Signed-off-by: Charles-Henri GUERIN <charleshenri.guerin@icloud.com>

```release-note

```

2019-05-12 10:56 UTC, aanm requested changes
Thank you for the changes, they look great

I would put the `examples/crds` files in the `examples/kubernetes/addons/crds` directory.

2019-05-12 10:56 UTC, aanm commented on daemon/daemon_main.go
> +	flags.Bool(option.SkipCRDCreation, false, "skip CRD creation")
`s/skip CRD creation/Skip Kubernetes Custom Resource Definitions creations`

2019-05-12 10:56 UTC, aanm commented on examples/crds/ciliumnetworkpolicies.yaml
> +                Valid operators are In, NotIn, Exists and DoesNotE
It's missing a new line

2019-05-12 10:56 UTC, aanm commented on examples/crds/ciliumendpoints.yaml
> +    storage: true
It's missing a new line

2019-05-13 15:40 UTC, aanm requested changes

2019-05-13 15:40 UTC, aanm commented on Documentation/cmdref/cilium-agent.md
> +      --skip-crd-creation                          skip CRD creation
you will need to generate this doc again `make -C Documentation cmdref`

2019-05-14 09:27 UTC, aanm commented
test-me-please

2019-05-14 16:23 UTC, tgraf approved these changes
I'm fine with the location for now. Maybe we should consider moving all installation yamls to `install/` to make it clearer what are examples and what are installation artifacts.

2019-05-14 16:24 UTC, tgraf commented
@charlyx Please rebase against master. @aanm will do a final review.

2019-05-15 20:17 UTC, charlyx commented
@tgraf @aanm the branch has been rebased against master 👌

2019-05-15 21:39 UTC, tgraf commented
test-me-please

2019-05-15 22:27 UTC, aanm approved these changes

2019-05-16 20:23 UTC, merged

2019-05-16 20:23 UTC, tgraf commented
Thanks @charlyx!