[CI] Don't overwrite minRequired in WaitforNPods
cilium/cilium pull request #8002
Opened 2019-05-14 09:11 UTC by nebril

If `minRequired` was set to 0, it was overwritten on the first pass of
`body` function (since it's in this function's closure) and if some pods
were being deleted during the test startup time, it could cause
`minRequired` to be higher than possible with test pods number.

Fixes: #7995

2019-05-14 09:11 UTC, nebril commented
test-me-please

2019-05-14 09:19 UTC, brb reviewed
Maybe I'm missing something, but isn't the intention of `minRequired=0` is to determine the count during the first run? If yes, then this PR defeats its intention.

2019-05-14 09:20 UTC, raybejjani requested changes
LGTM except for a comment change

2019-05-14 09:20 UTC, raybejjani commented on test/helpers/kubectl.go
> +		var required int
Could you update the function comment above?

2019-05-14 09:26 UTC, nebril commented
@brb the first couple of runs can contain leftover pods being deleted from previous tests. This causes `minRequired` to be set to higher pod count than the test can provide.

2019-05-14 09:29 UTC, nebril commented
test-me-please

2019-05-14 09:32 UTC, nebril commented
test-me-please

2019-05-14 09:39 UTC, raybejjani approved these changes

2019-05-14 09:39 UTC, nebril commented
test-me-please

2019-05-14 09:45 UTC, raybejjani commented
@brb One reason I'm preferring this PR over https://github.com/cilium/cilium/pull/7993/files is that it eventually accounts for deleted/deleting pods but also handles new pods showing up. It's not clear to me that this way of determining the pod count is correct to begin with. Ian's suggestion in https://github.com/cilium/cilium/pull/7993/files#r283611833 is probably the correct way to go, with variants for deployments, replicasets and (maybe) even parsing a pod manifest directly (although, really, we should just not be so lazy and put numbers in).

2019-05-14 09:59 UTC, aanm approved these changes

2019-05-14 10:56 UTC, tgraf commented
I think it's fine to merge this right now but I agree that we should follow @ianvernon's approach as described in https://github.com/cilium/cilium/pull/7993/files#r283611833

2019-05-14 10:56 UTC, merged

2019-06-05 14:21 UTC, aanm commented
marking this as backported needed since it is happening in 1.4