test: add v1.15.0-beta.0 to the CI
cilium/cilium pull request #8050
Opened 2019-05-16 09:44 UTC by aanm

Signed-off-by: André Martins <andre@cilium.io>

2019-05-16 09:44 UTC, aanm commented
test-missed-k8s

2019-05-16 15:49 UTC, aanm commented
test-me-please

2019-05-16 21:08 UTC, aanm commented
test-me-please

2019-05-16 23:41 UTC, ianvernon approved these changes

2019-05-16 23:41 UTC, ianvernon commented
@aanm why does this need backporting?

2019-05-17 09:36 UTC, aanm commented
> @aanm why does this need backporting?

We decided that we need to support new releases of k8s versions on already cilium releases.

2019-05-17 10:12 UTC, nebril requested changes
Overall looks good, but it will run 1.15 tests in parallel to 1.13 tests in the same directory which can lead to cross polution between tests.

2019-05-17 10:12 UTC, nebril commented on ginkgo-kubernetes-all.Jenkinsfile
> +        stage('Boot VMs 1.{13,15}'){
Can you put provisioning vms and running tests in parallel stages with separate directories (same way as for 1.11 and 1.12 above)?

2019-05-17 10:22 UTC, nebril approved these changes

2019-05-17 10:22 UTC, merged

2019-05-17 10:23 UTC, nebril commented on ginkgo-kubernetes-all.Jenkinsfile
> +        stage('Boot VMs 1.{13,15}'){
My bad, I thought my PR got merged before.