ipam: improve blacklisting mechanism in IPAM
cilium/cilium pull request #8139
Opened 2019-05-28 18:25 UTC by fristonio

* Move blacklist from an IP string hashmap to IP hashmap + IPNet list
combination
* Fixes #8120

Signed-off-by: Deepesh Pathak <deepshpathak@gmail.com>

2019-05-28 20:19 UTC, fristonio commented
@tgraf can you take a look at this?

2019-05-28 21:22 UTC, tgraf requested changes
Looks great. Only a minor date update needed.

2019-05-28 21:22 UTC, tgraf commented on pkg/ipam/blacklist.go
> +// Copyright 2016-2017 Authors of Cilium
Update date

2019-05-29 08:55 UTC, tgraf commented
test-me-please

2019-05-29 11:02 UTC, tgraf approved these changes

2019-05-29 11:03 UTC, merged

2019-05-29 11:03 UTC, tgraf commented
Awesome work!