docs: Update upgrade instructions for v1.5 -> v1.4 -> v1.5 case
cilium/cilium pull request #8158
Opened 2019-05-29 14:46 UTC by brb

Currently, we do not maintain the svc-v2 BPF maps in `v1.4`, so if a user downgraded from `v1.5` to `v1.4`, then did some updates to `Services`, those changes won't be reflected in the v2 maps. When the user upgrades to `v1.5`, the `daemon/loadbalancer.go:restoreServices()` function won't apply the changes to the v2 maps from the legacy maps, neither `daemon/loadbalancer.go:syncLBMapsWithK8s()` will, as both functions don't do a "deep" comparison of the maps.

Therefore, for such upgrade case, we require the users to run the `cilium-rm-svc-v2` DaemonSet introduced in this PR (a copy-paste from `cilium-pre-flight-check.yaml`) which will remove the v2 maps before doing the upgrade to v1.5.

In addition, this PR adds a note about losing the v2 maps content if user enables and then disables the `--enable-legacy-services` option.

2019-05-29 14:53 UTC, brb commented
test-docs-please

2019-05-29 17:26 UTC, aanm requested changes
discussed offline the changes needed

2019-05-29 19:54 UTC, brb commented
test-docs-please

2019-05-29 19:58 UTC, brb commented
@aanm PTAL.

The templating part got a bit more complex, but at the same time users won't need to run two different preflight DaemonSets (however, I'd rather have users running two different DS instead of this complexity). See https://github.com/cilium/cilium/tree/pr/brb/preflight-rm-svc-v2-backup for difference.

2019-05-30 08:19 UTC, tgraf approved these changes

2019-05-30 09:27 UTC, aanm approved these changes

2019-05-30 09:29 UTC, merged