ctmap: Fix conntrack map filtering
cilium/cilium pull request #8182
Opened 2019-05-31 09:56 UTC by tgraf

The type was incorrect causing all filters to be ignored. Add a warning
statement to catch future mismatches.

Fixes: eacec0bffcf ("pkg/maps: create CtKeyGlobal structures")

2019-05-31 09:59 UTC, aanm approved these changes

2019-05-31 10:00 UTC, aanm requested changes
@tgraf what about *tuple.TupleKey4 a couple lines bellow?

2019-05-31 10:05 UTC, tgraf commented
> what about *tuple.TupleKey4 a couple lines bellow?

I don't know you, you tell me. I'm not seeing unknown type warnings and it fixes at least the GC run. There may be more problems.

2019-05-31 12:34 UTC, aanm commented
@tgraf you are not seeing them because it should only affect local conntracking not global

2019-06-03 13:30 UTC, tgraf commented
test-me-please

2019-06-03 15:41 UTC, tgraf commented
test-me-please

2019-06-03 15:41 UTC, aanm approved these changes

2019-06-03 16:41 UTC, brb approved these changes

2019-06-03 17:50 UTC, merged