cni: Add cniVersion in cni config file
cilium/cilium pull request #8184
Opened 2019-05-31 19:26 UTC by nirmoy

crio(1.14.2) fails to delete network if cniVersion is
missing in the config file.
Error message:
```
level=error msg="Error deleting network: failed to convert major version
part "": strconv.Atoi: parsing "": invalid syntax"
level=error msg="Error while removing pod from CNI network "cilium":
failed to convert major version part "": strconv.
```

2019-05-31 19:30 UTC, nirmoy commented
cni tries to retrieve Cached result on delete pod which require cni version check.

https://github.com/containernetworking/cni/blob/d11ef1fb4e9ab1d261cd734d5063fd241cdd7d3c/libcni/api.go#L332

2019-06-01 12:57 UTC, tgraf requested changes
Please apply the same change to the CNI configuration files as written via `plugins/cilium-cni/cni-instasll.sh`

2019-06-03 07:57 UTC, nirmoy commented
@tgraf Added `ciniVersion` on aws-cni and portmap as well

2019-06-03 09:18 UTC, mrostecki commented
test-me-please

2019-06-03 09:18 UTC, vadorovsky approved these changes

2019-06-03 11:59 UTC, tgraf approved these changes

2019-06-03 11:59 UTC, merged