test/k8sT: disabling direct routing tests
cilium/cilium pull request #8207
Opened 2019-06-04 16:38 UTC by aanm

The test is currently broken which is affecting the CI runs. Should be
disabled once the issue was tracked down.

Signed-off-by: André Martins <andre@cilium.io>

2019-06-04 16:38 UTC, aanm commented
test-me-please

2019-06-04 17:04 UTC, jrfastab commented
Interesting, does this resolve the issue even though we still run the direct routing test with encryption? Those two tests do almost the same thing just one has encryption enabled and so it separates the routing table a bit with route rules.

2019-06-04 17:12 UTC, aanm commented
> Interesting, does this ~resolve the issue~ get around the failure even though we still run the direct routing test with encryption? Those two tests do almost the same thing just one has encryption enabled and so it separates the routing table a bit with route rules.

I thought the same thing when I was disabling the test. Let's see how it goes.

2019-06-05 07:55 UTC, tgraf commented
@aanm This may be fixed by https://github.com/cilium/cilium/pull/8214

2019-06-05 11:39 UTC, raybejjani approved these changes

2019-06-05 22:49 UTC, ianvernon commented
What is the nature of the brokenness of the CI with this test? If the CI was getting stuck, is it possible that there is a legitimate issue that may be unmasked after having merged #8223 , which helps with the CI getting stuck?

2019-06-06 08:05 UTC, tgraf commented
> What is the nature of the brokenness of the CI with this test? If the CI was getting stuck, is it possible that there is a legitimate issue that may be unmasked after having merged #8223 , which helps with the CI getting stuck?

I think it's a route that we install/uninstall that causes SSH to the VM to break.

2019-06-13 16:48 UTC, ianvernon requested changes
We have not observed this issue in master for some time - I don't think disabling the test is the way to go here. Additional ways to ensure that commands do not get stuck have been added to the CI to ensure that we do not block upon SSH session creation getting stuck.

2019-06-14 08:41 UTC, closed without merging