test: try to dial to remote host upon each SSH connection
cilium/cilium pull request #8259
Opened 2019-06-07 22:25 UTC by ianvernon

Given that the golang SSH library provides no timeouts for establishing a new session with an existing client, to get around this, try to dial to the same remote host upon each time we create a new session. Given that we don't want to leak clients / connections, close this new connection if the connection was successful. 

This is added to try to avoid the CI getting completely stuck when SSH connectivity is lost to VMs, which has been occurring during the direct node routes CI test. 

Signed-off by: Ian Vernon <ian@cilium.io>

2019-06-07 22:25 UTC, ianvernon commented
test-me-please

2019-06-08 05:10 UTC, ianvernon commented
test-me-please

2019-06-10 19:35 UTC, eloycoto requested changes

2019-06-10 19:35 UTC, eloycoto commented on test/helpers/ssh_command.go
> +			fmt.Sprintf("%s:%d", client.Host, client.Port),
https://golang.org/pkg/net/#JoinHostPort better no? it'll cover an IPv6 case. ;-)

2019-06-11 18:28 UTC, closed without merging