agent: Allow writing CNI configuration when ready
cilium/cilium pull request #8316
Opened 2019-06-17 10:46 UTC by tgraf

This can be used to generate the CNI configuration in a location outside of the
cni-conf-dir and then copy the CNI configuration into the config directory once
the agent is up. This avoids the node being marked ready before the agent is
ready to schedule pods.

2019-06-17 12:23 UTC, tgraf commented
test-me-please

2019-06-17 14:48 UTC, nebril requested changes

2019-06-17 14:48 UTC, nebril commented on daemon/daemon_main.go
> +	flags.String(option.WriteCNIConfigurationWhenReady, "", "Write the CNI configuration to path when agent is ready")
Can we add an information for user that `ReadCNIConfiguration` also needs to be defined for this to work?

2019-06-17 14:48 UTC, nebril commented on daemon/daemon_main.go
> +	if option.Config.WriteCNIConfigurationWhenReady != "" {
I think we should check if `option.Config.ReadCNIConfiguration` is not empty here and let user know with a distinct error message that it should be fixed.

2019-06-17 18:15 UTC, ianvernon commented on daemon/daemon_main.go
> +	if option.Config.WriteCNIConfigurationWhenReady != "" {
This is already done by the check in `DaemonConfig.Validate()` below - we check if both are set and return an error if so. The call to `Validate()` for said configuration is done before we hit this code, so we'd never hit this point if only one option is set.

2019-06-17 18:15 UTC, ianvernon approved these changes

2019-06-18 10:45 UTC, tgraf commented on daemon/daemon_main.go
> +	flags.String(option.WriteCNIConfigurationWhenReady, "", "Write the CNI configuration to path when agent is ready")
Added.

2019-06-18 11:45 UTC, merged