Small improvements in dev VM scripts and setup
cilium/cilium pull request #8403
Opened 2019-06-27 18:24 UTC by aanm

read per commit basis

2019-06-27 20:17 UTC, aanm commented
test-me-please

2019-07-01 13:55 UTC, aanm commented
test-me-please

2019-07-01 19:06 UTC, ianvernon requested changes

2019-07-01 19:06 UTC, ianvernon commented on Vagrantfile
> +    config.vm.box_check_update = false
I disagree with this being the default behavior - by getting the latest and greatest by default, we get improvements / newer VM versions, etc. I'd prefer if you wrap this with an environment variable, `CHECK_UPDATES=false` where by default, it is `true`.

2019-07-02 09:47 UTC, aanm commented
test-me-please

2019-07-02 14:21 UTC, ianvernon approved these changes

2019-07-02 14:21 UTC, merged