Dockerfile: Add init-container.sh to cilium image
cilium/cilium pull request #8489
Opened 2019-07-08 16:09 UTC by nirmoy

This will allows us to make use of same cilium
image instead of cilium-init image for clean-cilium-state
init container

Todo after this PR is gets merged:
1 Recreate cilium image
2 create a another PR to change `__CILIUM_INIT_VERSION__` to `__CILIUM_ERSION__` in `examples/kubernetes/templates/v1`

2019-07-08 16:11 UTC, aanm requested changes

2019-07-08 16:11 UTC, aanm commented on contrib/packaging/docker/Dockerfile.runtime
> -#
This should not have been removed :/

2019-07-09 09:20 UTC, nirmoy commented on contrib/packaging/docker/Dockerfile.runtime
> -#
@aanm :man_facepalming:

2019-07-09 10:07 UTC, nirmoy commented
test-me-please

2019-07-09 10:09 UTC, aanm approved these changes

2019-07-09 10:10 UTC, aanm commented
@nirmoy you can as well change the k8s descriptors to point to this image instead

2019-07-09 20:39 UTC, ianvernon approved these changes

2019-07-10 20:20 UTC, joestringer approved these changes

2019-07-10 21:24 UTC, merged