Take all labels
cilium/cilium pull request #849
Opened 2017-05-29 20:55 UTC by tgraf

2017-05-29 22:08 UTC, aanm requested changes

2017-05-29 22:08 UTC, aanm commented on daemon/docker_watcher.go
> -
We still need to store the `io.kubernetes.pod.namespace` here.

2017-05-29 22:08 UTC, aanm commented on pkg/labels/filter.go
>  			},
Also ignore `k8s.io/kubernetes/pkg/apis/extensions/DefaultDeploymentUniqueLabelKey` or `"pod-template-hash"`

2017-05-30 01:47 UTC, tgraf commented on daemon/docker_watcher.go
> -
Fixed

2017-05-30 03:45 UTC, aanm approved these changes

2017-05-30 03:45 UTC, aanm commented
For future reference:
```
$ cilium endpoint list
ENDPOINT   POLICY        IDENTITY   LABELS (source:key[=value])                   IPv6                     IPv4            STATUS   
           ENFORCEMENT                                                                                                              
173        Enabled       258        k8s:io.kubernetes.pod.namespace=default       fd02::c0a8:210b:0:ad     10.11.42.252    ready    
                                    k8s:k8s-app.guestbook=redis                                                                     
                                    k8s:role=slave                                                                                  
13949      Enabled       259        k8s:io.kubernetes.pod.namespace=default       fd02::c0a8:210b:0:367d   10.11.193.100   ready    
                                    k8s:k8s-app.guestbook=web                                                                       
38939      Enabled       257        k8s:io.kubernetes.pod.namespace=default       fd02::c0a8:210b:0:981b   10.11.148.173   ready    
                                    k8s:k8s-app.guestbook=redis                                                                     
                                    k8s:role=master                                                                                 
56326      Disabled      256        k8s:io.kubernetes.pod.namespace=kube-system   fd02::c0a8:210b:0:dc06   10.11.250.189   ready    
                                    k8s:k8s-app=kube-dns
```

2017-05-30 11:23 UTC, merged