eni: Add trigger metrics
cilium/cilium pull request #8521
Opened 2019-07-11 07:47 UTC by tgraf

2019-07-11 07:48 UTC, tgraf commented
test-me-please

2019-07-11 08:35 UTC, aanm requested changes

2019-07-11 08:35 UTC, aanm commented on pkg/metrics/metrics.go
> +				Name:      "policy_update__call_duration_seconds",
s/`policy_update__call_duration_seconds`/`policy_update_call_duration_seconds`/

2019-07-11 12:11 UTC, tgraf commented
test-me-please

2019-07-11 15:49 UTC, ianvernon approved these changes
Nothing blocking, just some suggestions to reduce hardcoding in metrics string fields. This can be merged.

2019-07-11 15:49 UTC, ianvernon commented on pkg/metrics/metrics.go
> +				Help:      "Total number of policy update trigger invocations labelled by reason",
Nit (non-blocking): labelled --> labeled

2019-07-11 15:49 UTC, ianvernon commented on pkg/metrics/metrics.go
> +				Subsystem: "triggers",
Make "triggers" a const string.

2019-07-11 15:49 UTC, ianvernon commented on pkg/metrics/metrics.go
> +		case Namespace + "_triggers_policy_update_call_duration_seconds":
Could make "triggers" a const string, then the name of each metric a const string and be able to use them in the case statements + the "Subsystem" and "Name" fields for each trigger to reduce duplicate hardcoded strings.

2019-07-11 23:44 UTC, joestringer approved these changes
Metrics LGTM

2019-07-12 06:31 UTC, tgraf commented
test-me-please

2019-07-12 08:59 UTC, merged