pkg/{kvstore,node}: delay node delete event in kvstore
cilium/cilium pull request #8544
Opened 2019-07-12 09:59 UTC by aanm

Instead of checking if the node is still present in the observer, we
should check if the node is still present in the store instead. Checking
if the node is still available in the observer is irrelevant as the node
will never be deleted since the check for its existence in the store
will always be true.

Intead, delay the propagation of the deletion event to the observer in
the store itself.

Fixes: 3137ad5eee6c ("node: Delay handling of node delete events received via kvstore")
Signed-off-by: André Martins <andre@cilium.io>

```release-note
Remove leftover nodes from cilium node list
```

2019-07-12 10:00 UTC, aanm commented
test-me-please

2019-07-12 16:48 UTC, aanm commented
test-me-please

2019-07-12 21:22 UTC, ianvernon approved these changes
Great find!

2019-07-14 04:44 UTC, aanm commented
test-me-please

2019-07-14 12:50 UTC, aanm commented
test-me-please

2019-07-15 23:06 UTC, aanm commented
test-me-please

2019-07-16 03:58 UTC, tgraf requested changes

2019-07-16 03:58 UTC, tgraf commented on pkg/kvstore/store/store_test.go
> +	"github.com/cilium/cilium/pkg/defaults"
oooohhh

2019-07-16 03:59 UTC, aanm commented
test-me-please

2019-07-16 04:12 UTC, tgraf approved these changes

2019-07-16 13:19 UTC, merged