migrate test which checks too many ports in rule to unit test from Ginkgo
cilium/cilium pull request #8593
Opened 2019-07-17 00:26 UTC by ianvernon

This is unit-testable; remove it from the Ginkgo framework, as unit tests should be created instead of Ginkgo tests if they can test specific functionality.

Signed-off by: Ian Vernon <ian@cilium.io>

2019-07-17 00:27 UTC, ianvernon commented
test-me-please

2019-07-17 16:20 UTC, vadorovsky approved these changes

2019-07-17 16:38 UTC, aanm requested changes

2019-07-17 16:38 UTC, aanm commented on pkg/policy/api/rule_validation_test.go
> +						// Max is 40 ports
Isn't it cleaner to have a for loop instead of having 40 lines of code?

2019-07-17 18:03 UTC, ianvernon commented
test-me-please

2019-07-18 23:34 UTC, raybejjani approved these changes

2019-07-18 23:35 UTC, nebril approved these changes

2019-07-18 23:52 UTC, merged