[CI] Add timeout to ginkgo calls
cilium/cilium pull request #8631
Opened 2019-07-22 14:59 UTC by nebril

Add timeout to make ginkgo exit instead of being interrupted by Jenkins.
Should help with builds being marked as aborted instead of failed.

2019-07-22 15:00 UTC, nebril commented
test-me-please

2019-07-22 15:31 UTC, ianvernon requested changes

2019-07-22 15:31 UTC, ianvernon commented on ginkgo.Jenkinsfile
> +                        sh 'cd ${TESTDIR}; ginkgo --timeout=108m --focus=" Runtime*" -v --failFast=${FAILFAST} -- -cilium.provision=false'
Please make these values configurable as environment variables instead of hardcoding.

2019-07-23 12:42 UTC, nebril commented
test-me-please

2019-07-23 13:18 UTC, nebril commented
@ianvernon addressed your comment

2019-07-23 16:09 UTC, ianvernon approved these changes

2019-07-23 16:09 UTC, merged