daemon: update policy enforcement w/ no endpoints
cilium/cilium pull request #870
Opened 2017-05-31 06:05 UTC by ianvernon

fixed bug in the daemon where if no endpoints were added, the policy
enforcement flag for the daemon was not updated if a policy was added.
fixes bug in the daemon where if the configuration flag for the boolean
option for policy enforcement was updated, the value of PolicyEnabled
within the daemon was not updated.
added tests to test policy enforcement flag when endpoints are not
added, as well as ping tests to ensure that policy enforcement
configuration updates are reflected in the networking configuration of
endpoints.

Signed-off by: Ian Vernon <ian@covalent.io>

2017-05-31 07:03 UTC, aalemayhu requested changes
@ianvernon please consider breaking your commit message into several paragraphs or using bullet points. It's very hard to read the way it's written.

2017-05-31 17:34 UTC, aalemayhu approved these changes

2017-06-01 16:48 UTC, aanm requested changes

2017-06-01 16:48 UTC, aanm commented on daemon/policy.go
> +	} else if d.conf.EnablePolicy == endpoint.DefaultEnforcement && d.conf.IsK8sEnabled() && e != nil {
Not sure if intencional or not, but be aware the `e != nil` is only checked if k8s mode is enabled.

2017-06-01 16:48 UTC, aanm commented on tests/15-policy-config.sh
> +	ping_success foo bar
This should commented?

2017-06-02 00:33 UTC, tgraf commented on daemon/policy.go
> +	} else if d.conf.EnablePolicy == endpoint.DefaultEnforcement && d.conf.IsK8sEnabled() && e != nil {
Discussed this with Ian face to face as well. We agreed to split `UpdatePolicyEnforement` into two functions. One which takes care of endpoint specific policy enablement and one to update the global policy setting on policy changes in general.

2017-06-05 00:56 UTC, tgraf requested changes

2017-06-05 00:56 UTC, tgraf commented on daemon/policy.go
> -	} else if d.conf.EnablePolicy == endpoint.DefaultEnforcement && d.conf.IsK8sEnabled() {
Discussed this with Ian face to face as well. We agreed to split UpdatePolicyEnforement into two functions. One which takes care of endpoint specific policy enablement and one to update the global policy setting on policy changes in general.

2017-06-06 21:44 UTC, aanm approved these changes

2017-06-06 21:44 UTC, aanm commented
@tgraf OK to merge?

2017-06-08 21:06 UTC, tgraf approved these changes

2017-06-08 21:06 UTC, merged