endpoint: remove duplicate closing of maps from endpoint deletion logic
cilium/cilium pull request #8745
Opened 2019-07-31 22:31 UTC by ianvernon

`daemon.deleteEndpointQuiet` already calls  which cleans up the BPF ConfigMap
and PolicyMap for the endpoint, so no need to do it again in `LeaveLocked`.

Signed-off by: Ian Vernon <ian@cilium.io>

2019-07-31 22:31 UTC, ianvernon commented
test-me-please

2019-08-06 18:42 UTC, aanm requested changes
Can you provide more context where the maps are being closed in the daemon side? I couldn't find any line that does it.

2019-08-12 16:07 UTC, ianvernon commented
test-me-please

2019-08-12 16:10 UTC, ianvernon commented
@aanm updated the commit message, `DeleteMapsLocked` is the function which is responsible:

https://github.com/cilium/cilium/blob/4d0f8518671b23ea8265cb15d62634ed4c31f995/pkg/endpoint/bpf.go#L763-L771

2019-08-12 18:28 UTC, ianvernon commented
Build failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14247/

Jenkins was unable to contact GitHub.

2019-08-12 18:29 UTC, ianvernon commented
test-me-please

2019-08-13 05:50 UTC, aanm requested changes
@ianvernon it is not the same logic. The one under `pkg/endpoint/endpoint.go` is closing the map, and its FDs. The one that you have point it out is simply doing a `os.Remove`

2019-09-27 06:34 UTC, closed without merging