Monitor: omiting panic when no events Fix #757
cilium/cilium pull request #883
Opened 2017-06-01 19:46 UTC by eloycoto

Hey! 

My first PR :-) 

This fix issue #757. The new output will be like this: 
```
ubuntu-zesty ➜  cilium git:(757) ✗ ./cilium/cilium monitor
Error: Unable to get BPF events (Unable to get object: /sys/fs/bpf/tc/globals/cilium_events)
```

Regards

2017-06-01 20:11 UTC, tgraf commented on pkg/bpf/bpf.go
> +		return 0, fmt.Errorf("Unable to get object: %s", pathname)
I think we want to print both path and error:
`return 0, fmt.Errorf("Unable to get object %s: %s", pathname, err)`

2017-06-01 20:11 UTC, tgraf requested changes

2017-06-01 20:11 UTC, tgraf commented on cilium/cmd/monitor.go
> +		os.Exit(1)
👍

2017-06-02 06:06 UTC, eloycoto commented
Changes done ;-)

2017-06-02 13:07 UTC, tgraf approved these changes

2017-06-02 13:07 UTC, merged