Connection readiness of k8s client gets ns
cilium/cilium pull request #8855
Opened 2019-08-09 13:52 UTC by nebril

kube-system is always in the cluster, getting it indicates that
connection to apiserver is ready.

2019-08-09 13:53 UTC, nebril commented
test-me-please

2019-08-09 15:27 UTC, vadorovsky approved these changes

2019-08-09 21:03 UTC, tgraf requested changes
Please also remove the "componentstatus" from the ClusterRole so we have less expansive RBAC requirements.

2019-08-13 13:33 UTC, nebril commented
test-me-please

2019-08-13 14:15 UTC, nebril commented
test-me-please

2019-08-13 15:04 UTC, nebril commented
test-me-please

2019-08-13 17:26 UTC, nebril commented
test-me-please

2019-08-14 13:40 UTC, nebril commented
test-me-please

2019-08-14 15:49 UTC, ianvernon commented
test-me-please

2019-08-14 15:49 UTC, ianvernon commented
test-missed-k8s

2019-08-14 16:02 UTC, aanm approved these changes

2019-08-16 17:38 UTC, ianvernon commented
test-me-please

2019-08-19 16:07 UTC, nebril commented
test-me-please

2019-08-19 16:08 UTC, ianvernon commented
Build failure:

Appears related to this change: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14439/

```
019-08-16T18:52:36.224298288Z level=error msg="Unable to contact k8s api-server" error="namespaces \"kube-system\" is forbidden: User \"system:serviceaccount:kube-system:cilium-operator\" cannot get resource \"namespaces\" in API group \"\" in the namespace \"kube-system\"" ipAddr="https://10.96.0.1:443" subsys=k8s
2019-08-16T18:52:36.224312617Z level=fatal msg="Unable to connect to Kubernetes apiserver" error="unable to create k8s client: unable to create k8s client: namespaces \"kube-system\" is forbidden: User \"system:serviceaccount:kube-system:cilium-operator\" cannot get resource \"namespaces\" in API group \"\" in the namespace \"kube-system\"" subsys=cilium-operator
```

2019-08-19 16:26 UTC, nebril commented
test-me-please

2019-08-20 10:44 UTC, nebril commented
test-me-please

2019-08-20 15:08 UTC, nebril commented
test-me-please

2019-08-20 17:29 UTC, nebril commented
test-me-please

2019-08-20 21:22 UTC, tgraf approved these changes

2019-08-20 21:23 UTC, merged

2019-08-26 06:39 UTC, vsxen commented on pkg/k8s/client.go
> -	_, err := c.CoreV1().ComponentStatuses().Get("controller-manager", metav1.GetOptions{})
cilium was crashloopbackoff .
```
level=error msg="Unable to contact k8s api-server" error="componentstatuses \"controller-manager\" is forbidden: User \"system:serviceaccount:kube-system:cilium\" cannot get resource \"componentstatuses\" in API group \"\" at the cluster scope" ipAddr="https://10.96.0.1:443" subsys=k8s
level=fatal msg="Unable to initialize Kubernetes subsystem" error="unable to create k8s client: unable to create k8s client: componentstatuses \"controller-manager\" is forbidden: User \"system:serviceaccount:kube-system:cilium\" cannot get resource \"componentstatuses\" in API group \"\" at the cluster scope" subsys=daemon
```
with this docker image
`cilium/cilium                                                                  v1.6.0              7bd190b404f4        6 days ago          710MB`

you should change this yaml file URL 

https://cilium.readthedocs.io/en/v1.6/gettingstarted/minikube/#install-cilium

2019-08-26 12:02 UTC, brb commented on pkg/k8s/client.go
> -	_, err := c.CoreV1().ComponentStatuses().Get("controller-manager", metav1.GetOptions{})
@vsxen Thanks for reporting. This should be fixed after https://github.com/cilium/cilium/pull/9038 has been merged.