daemon: sleep 2 seconds before fatal
cilium/cilium pull request #8857
Opened 2019-08-09 14:31 UTC by aanm

If the user specifies a flag that does not exist to cilium-agent it can
make Cilium to present the following error to the user:
```
PostStartHookError: command '/cni-install.sh' exited with 126:
```

This is misleading and the reason for it to happen is because
cni-install.sh was not completed by the time `cilium-agent` process
exited. For this reason, before printing the helper message and / or
fatal, Cilium will be delayed 2 seconds so it gives enough time for
`cni-install.sh` to complete and the user will see a different type of
error in the pod status message.

Signed-off-by: Ray Bejjani <ray@isovalent.com>
Signed-off-by: André Martins <andre@cilium.io>

Fixes https://github.com/cilium/cilium/issues/7983

2019-08-09 15:17 UTC, aanm commented
test-me-please

2019-08-09 15:21 UTC, vadorovsky requested changes
Maybe instead of assuming that `cni-install.sh` executes in less that two seconds, we should just look explicitly for files installed by that script - `/etc/cni.d/10-cilium.conf` and `/opt/cni/bin/cilium-cni`?

2019-08-09 15:23 UTC, mrostecki commented
^ Doing so would also be a solution for the issue #1252

2019-08-09 16:31 UTC, aanm commented
@mrostecki the `10-cilium.conf` is optional and `/opt/cni/bin/cilium-cni` is created before the script is complete. Also it doesn't work if those files are already installed (i.e. user upgrading from an old cilium installation to a new one)

2019-08-09 18:32 UTC, ianvernon commented
Would doing `touch cni-complete` in some directory that we manage be enough to signify that `cni-install.sh` has completed? Then we could do use `fsnotify` to wait for this file to exist, or timeout after some time.

2019-08-12 06:37 UTC, tgraf approved these changes

2019-08-12 06:44 UTC, tgraf commented
I'm fine with the currently proposed patch but I'm also fine with what @ianvernon is proposing. It's slightly more complicated but doesn't depend on the arbitrary timeout.

2019-08-12 16:10 UTC, merged