Document CNI chaining modes
cilium/cilium pull request #8874
Opened 2019-08-12 12:07 UTC by tgraf

2019-08-12 12:10 UTC, tgraf commented
test-me-please

2019-08-12 12:10 UTC, tgraf commented
test-docs-please

2019-08-12 15:20 UTC, ianvernon requested changes
A few nits.

2019-08-12 15:20 UTC, ianvernon commented on Documentation/gettingstarted/cni-chaining-calico.rst
> +Calico:
Nit: add a link to Calico here.

2019-08-12 15:20 UTC, ianvernon commented on Documentation/gettingstarted/cni-chaining-generic-veth.rst
> +that is using a veth device model which is the vast majority of plugins.
Change to "...veth device model. The majority of CNI plugins use such a model."

2019-08-12 15:20 UTC, ianvernon commented on Documentation/gettingstarted/cni-chaining-generic-veth.rst
> +Writing such a plugin is trivial, contact us on Slack for more details.
"...is trivial. Contact us on Slack for more details."

Perhaps add a link to the Slack as well.

2019-08-13 09:37 UTC, tgraf commented
test-docs-please

2019-08-13 11:23 UTC, merged