Enable IP forwarding on daemon start
cilium/cilium pull request #8954
Opened 2019-08-19 17:03 UTC by mrostecki

This PR enables IP forwarding on the daemon start to prevent Cilium failures due to disabled forwarding.

Fixes: #8476

```release-note
Enable IP forwarding on daemon start
```

2019-08-19 17:04 UTC, mrostecki commented
test-me-please

2019-08-19 18:09 UTC, mrostecki commented
test-me-please

2019-08-20 07:26 UTC, brb commented
Hey @mrostecki, is it ready for a review?

2019-08-20 07:31 UTC, mrostecki commented
@brb yes

2019-08-20 09:07 UTC, brb requested changes
Nice! Couple of nits.

2019-08-20 09:07 UTC, brb commented on daemon/daemon_main.go
> +	if err := initSysctlParams(); err != nil {
Could we make this compile for our OS X friends?

2019-08-20 09:07 UTC, brb commented on pkg/sysctl/sysctl_linux.go
> +	if err := ioutil.WriteFile(fPath, value, 0644); err != nil {
Nits:

- I'd replace `value` param type to `string`.
- Instead of `ioutil.WriteFile() I'd use `io.WriteString()`.

2019-08-20 09:07 UTC, brb commented on daemon/sysctl_linux.go
> +func initSysctlParams() error {
Maybe `s/initSysctlParams/enableIPForwarding`?

2019-08-21 11:35 UTC, mrostecki commented
test-me-please

2019-08-21 11:35 UTC, mrostecki commented
@brb Thanks for review! All comments addressed.

2019-08-21 14:33 UTC, mrostecki commented
test-me-please

2019-08-21 20:14 UTC, mrostecki commented
test-me-please

2019-08-22 08:48 UTC, brb approved these changes
Thanks!

2019-08-22 08:48 UTC, merged

2019-08-22 08:54 UTC, brb commented
BTW, @mrostecki could you refactor other instances of `sysctl -w` in the go code (just grep for `WriteSysConfig`) to use your library?

2019-08-22 10:31 UTC, mrostecki commented
@brb Yes, I will do it, great idea!