Makefile: add test target for applying changes
cilium/cilium pull request #899
Opened 2017-06-03 01:52 UTC by scanf

retyping all of these commands is very tedious.

Signed-off-by: Alexander Alemayhu <alexander@alemayhu.com>

2017-06-03 01:54 UTC, aanm requested changes

2017-06-03 01:54 UTC, aanm commented on Makefile
> +	sudo systemctl stop cilium
You need to stop and start `cilium-docker` as well.

2017-06-05 23:29 UTC, tgraf commented on Makefile
> +tt:
I'm fine with this but let's give this a better name. `make tt` is not very descriptive.

2017-06-06 06:31 UTC, scanf commented on Makefile
> +tt:
Was hoping to keep it short, how about one of these?

`make reload`
`make change`
`make apply`

2017-06-06 13:59 UTC, tgraf commented on Makefile
> +tt:
I'm happy with `make reload`. You can always have an alias for you locally if you like `make tt`

2017-06-06 14:30 UTC, tgraf approved these changes

2017-06-06 15:14 UTC, aanm approved these changes

2017-06-06 15:14 UTC, merged