docs: Update direct routing policy limitations
cilium/cilium pull request #9015
Opened 2019-08-22 22:56 UTC by joestringer

2019-08-22 22:56 UTC, joestringer commented
test-me-please

2019-08-22 22:56 UTC, joestringer commented
test-docs-please

2019-08-22 22:57 UTC, joestringer commented
test-docs-please

2019-08-22 22:58 UTC, ianvernon requested changes

2019-08-22 22:58 UTC, ianvernon commented on Documentation/concepts/networking.rst
> +          L7 policies is currently beta. Iplease provide feedback and file a
Iplease --> Please

2019-08-22 23:08 UTC, joestringer commented
test-docs-please

2019-08-23 14:00 UTC, tgraf approved these changes

2019-08-23 14:01 UTC, merged

2019-08-26 09:40 UTC, brb commented
@joestringer Setting `need-backport/1.5`, as this would reduce some confusion for v1.5 users: https://cilium.slack.com/archives/C53TG4J4R/p1566477425192100?thread_ts=1566438387.191500&cid=C53TG4J4R (via #9035).