Revert "Remove componentstatus from rbac"
cilium/cilium pull request #9038
Opened 2019-08-26 10:12 UTC by brb

This reverts commit 0fb23b57e6fe1d6abe544024f1e248c96ab87d7b.

[1] changed the way we probe a connection to k8s api-server. The probe no longer requires the RBAC for `componentstatuses`, and therefore the relevant RBAC got removed from the v1.6 helm templates.

Unfortunately, we haven't released v1.6.1 yet, which will include the changed probing. Therefore, any user using the templates from the v1.6 branch won't be able to start cilium-agent due to the missing RBAC permissions.

We can remove the RBAC once we have release v1.6.1.

2019-08-26 10:13 UTC, brb commented
never-tell-me-the-odds

2019-08-26 10:14 UTC, tgraf requested changes

2019-08-26 10:14 UTC, tgraf commented on install/kubernetes/quick-install.yaml
> -  - namespaces
You want to keep the namespaces

2019-08-26 12:00 UTC, brb commented on install/kubernetes/quick-install.yaml
> -  - namespaces
Oops, fixed.

2019-08-26 12:00 UTC, brb commented
never-tell-me-the-odds

2019-08-26 12:39 UTC, tgraf approved these changes

2019-08-26 13:55 UTC, nebril commented
test-upstream-k8s

2019-08-26 15:46 UTC, brb commented
CI failed:
```
Suite-k8s-1.10.K8sDatapathConfig Transparent encryption DirectRouting Check connectivity with transparent encryption and direct routing

/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.10-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:347
Test suite timed out after 1h48m0s
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.10-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:536
```

2019-08-26 15:46 UTC, brb commented
never-tell-me-the-odds

2019-08-26 17:47 UTC, jrajahalme approved these changes
While the description says `This reverts commit 0fb23b5`, it does not revert the addition of `namespaces` resource. Is this intentional?

2019-08-26 19:29 UTC, brb commented
@jrajahalme This is required by the current probing mechanism: https://github.com/cilium/cilium/pull/8855/commits/2fa2e8cf4548f0c84b3f50c7f7f0f8d6f7efcb36.

2019-08-27 07:48 UTC, brb commented
k8s upstream tests have failed:
```
[2019-08-26T16:06:06.222Z] 2019/08/26 16:05:54 e2e.go:158: Updating kubetest binary...
[2019-08-26T16:06:06.222Z] go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
[2019-08-26T16:06:06.222Z] 	ignoring go.mod;
[2019-08-26T16:06:06.222Z] 	see 'go help modules'
[2019-08-26T16:08:33.987Z] # k8s.io/client-go/transport
[2019-08-26T16:08:33.987Z] ../../../k8s.io/client-go/transport/round_trippers.go:70:11: cannot convert klog.V(9) (type klog.Verbose) to type bool
[2019-08-26T16:08:33.987Z] ../../../k8s.io/client-go/transport/round_trippers.go:72:11: cannot convert klog.V(8) (type klog.Verbose) to type bool
[2019-08-26T16:08:33.987Z] ../../../k8s.io/client-go/transport/round_trippers.go:74:11: cannot convert klog.V(7) (type klog.Verbose) to type bool
[2019-08-26T16:08:33.987Z] ../../../k8s.io/client-go/transport/round_trippers.go:76:11: cannot convert klog.V(6) (type klog.Verbose) to type bool
[2019-08-26T16:08:33.987Z] 2019/08/26 16:08:19 e2e.go:77: err: go get -u k8s.io/test-infra/kubetest: exit status 2
[2019-08-26T16:08:33.987Z] exit status 1
```

2019-08-27 09:38 UTC, merged