test: Wait for at least one Istio POD to get ready
cilium/cilium pull request #9049
Opened 2019-08-26 22:37 UTC by jrajahalme

WaitforPods() succeeds if there are no PODs matching the given filter
("-l istio" in this case). Wait for at least one Istio POD to get
Running before waiting for all of them to get Ready.

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cilium/cilium/9049)

2019-08-27 20:09 UTC, vadorovsky approved these changes

2019-08-28 14:16 UTC, mrostecki commented
Anyone from @cilium/ci can review?

2019-08-28 14:29 UTC, ianvernon requested changes

2019-08-28 14:29 UTC, ianvernon commented on test/k8sT/istio.go
> -	waitIstioReady := func() {
Please keep this function as is in terms of running it within the `It` itself - see 425e6b455f8f0c663c36cba3acc3bcbdfdbb8f52

2019-08-28 17:03 UTC, jrajahalme commented on test/k8sT/istio.go
> -	waitIstioReady := func() {
Will do. Will also add a comment explaining why this is a separate function.

2019-08-28 18:14 UTC, ianvernon approved these changes
Thanks for adding the comment to clarify why the wait for readiness is in a separate function!

2019-08-28 20:15 UTC, merged