docs: Update source branch in kube-proxy-free guide
cilium/cilium pull request #9055
Opened 2019-08-27 14:46 UTC by brb

Switch to v1.6, because:

1. https://github.com/cilium/cilium/pull/8995 got backported to the v1.6.
2. The templates from the master branch cannot be used with the v1.6.0 image due to removed RBAC for `componentstatuses`.

Once v1.6.1 is released, we can just include `k8s-install-download-release.rst`.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cilium/cilium/9055)

2019-08-27 14:46 UTC, brb commented
test-me-please

2019-08-27 14:48 UTC, brb commented
test-docs-please

2019-08-27 15:57 UTC, joestringer requested changes
This is generated for all of the other guides based on readthedocs version, is there any reason we can't generate the version correctly in this guide too?

What I mean, is that `k8s-install-download-release.rst` will generate the correct version, so for latest docs it generates master and when backported, for v1.6 branch docs it will generate the v1.6 paths. Isn't that what we want?

2019-08-29 10:26 UTC, brb commented
@joestringer The intention of this PR is to lock the version for those who access the latest guide ( http://docs.cilium.io/en/latest/gettingstarted/kubeproxy-free/), as the master template is broken for v1.6 users due to the missing RBAC. I would unlock the version once the RBAC issue has been resolved (after the v1.6.1 release).

2019-08-29 15:58 UTC, joestringer reviewed
:shipit:

2019-08-29 15:58 UTC, joestringer approved these changes

2019-08-29 16:05 UTC, merged