clustermesh: Improve troubleshooting ability
cilium/cilium pull request #9081
Opened 2019-08-29 19:10 UTC by tgraf

2019-08-29 19:10 UTC, tgraf commented
test-me-please

2019-08-29 19:10 UTC, tgraf commented
test-docs-please

2019-08-29 19:40 UTC, ianvernon requested changes
Small nits. Great work!

2019-08-29 19:40 UTC, ianvernon commented on Documentation/gettingstarted/clustermesh.rst
> +    healthy as well as it is responsible to synchronize state from the local
responsible for synchronizing

2019-08-29 19:40 UTC, ianvernon commented on Documentation/gettingstarted/clustermesh.rst
> +      cache.  it will list the Kubernetes services and endpoints of the local
Provide an example of the output here.

2019-08-29 20:30 UTC, joestringer approved these changes
Some minor nits, but this is really helpful.

2019-08-29 20:30 UTC, joestringer commented on Documentation/gettingstarted/clustermesh.rst
> +    are healthy and ready. Is is important that the ``cilium-operator`` is
```suggestion
    are healthy and ready. It is important that the ``cilium-operator`` is
```

2019-08-29 20:30 UTC, joestringer commented on Documentation/gettingstarted/clustermesh.rst
> + #. Validate that the ClusterMesh subsystem is initialized by looking for a log
```suggestion
 #. Validate that the ClusterMesh subsystem is initialized by looking for a ``cilium-agent`` log
```

2019-08-29 20:30 UTC, joestringer commented on Documentation/gettingstarted/clustermesh.rst
> +    configuration`` along with the remote cluster name must be logged.
```suggestion
    configuration`` along with the remote cluster name must be logged in the ``cilium-agent`` logs.
```

2019-08-29 20:30 UTC, joestringer commented on Documentation/gettingstarted/clustermesh.rst
> +    You will see a log message like this for each remote cluster:
```suggestion
    You will see a log message like this in ``cilium-agent`` logs for each remote cluster:
```

2019-08-29 20:30 UTC, joestringer commented on Documentation/gettingstarted/clustermesh.rst
> +	 The kvstore will only contain nodes of the **local cluster**. It will
nit: The tabbing seems a bit weird to me in github interface. As long as the indentation looks right then that's fine.

2019-08-30 09:05 UTC, tgraf commented
test-docs-please

2019-08-30 10:17 UTC, merged