Docs: tofqdns-pre-cache is optional in preflight templates
cilium/cilium pull request #9107
Opened 2019-09-02 12:54 UTC by raybejjani

The fqdns precache is an opt-in feature but we had configured the
preflight pod to always produce it. This sometimes causes errors when
the a user has not opted into generating this file but still ran the
preflight manifest, possibly one pre-dating the feature.
It is now a more explicit option in the helm templates, making it more
clear what is happening.

2019-09-02 12:54 UTC, raybejjani commented
test-me-please

2019-09-02 12:54 UTC, raybejjani commented
test-docs-please

2019-09-02 15:01 UTC, raybejjani commented
test-docs-please

2019-09-03 15:17 UTC, ianvernon requested changes

2019-09-03 15:17 UTC, ianvernon commented on install/kubernetes/cilium/charts/preflight/templates/daemonset.yaml
> +              - /tmp/read-tofqdns-precachey
/tmp/read-tofqdns-precachy --> /tmp/ready-tofqdns-precache

2019-09-03 15:17 UTC, ianvernon commented on install/kubernetes/cilium/charts/preflight/templates/daemonset.yaml
> +              - /tmp/read-tofqdns-precachey
Same here.

2019-09-03 15:17 UTC, ianvernon commented
@raybejjani IMO we should backport this - what do you think?

2019-09-10 00:16 UTC, aanm approved these changes
LGTM beside what Ian already requested

2019-09-28 14:16 UTC, tgraf commented
@raybejjani The change looks good, let's address @ianvernon's comments so we can merge it.

2019-11-06 10:42 UTC, raybejjani commented
test-me-please

2019-11-06 10:43 UTC, raybejjani commented
Once this passes tests it is mergeable (finally).
It backports cleanly to 1.6, so I'll mark it for backport as well.

2019-11-06 14:00 UTC, merged