endpoint: do not export additional fields
cilium/cilium pull request #9170
Opened 2019-09-09 17:31 UTC by ianvernon

The following fields are now hidden:

* Container ID
* Docker Endpoint ID
* Docker Network ID
* Container Name

2019-09-09 17:31 UTC, ianvernon commented
test-me-please

2019-09-10 00:48 UTC, aanm reviewed
Small nit

2019-09-10 00:48 UTC, aanm commented on pkg/workloads/docker.go
> +				if v.EndpointID == ep.GetDockerEndpointID() {
to avoid doing multiple rlocks, get the dockerendpointID before the for loop

2019-09-11 11:23 UTC, joestringer approved these changes
Looks good to me.

2019-09-11 16:55 UTC, vadorovsky requested changes
One nit, but overall looks good

2019-09-11 16:55 UTC, mrostecki commented on pkg/logging/logfields/logfields.go
> +	// containerID is the container identifier
That comment seems to be relevant - probably your `sed` command touched the file which should not be touched ;)

2019-09-11 17:07 UTC, ianvernon commented
test-me-please

2019-09-11 22:27 UTC, ianvernon commented
Istio pods never got ready: 	

```
istio-system   istio-cleanup-secrets-1.2.5-66bwp         0/1       Completed   0          4m        10.10.1.185     k8s2      <none>
	 istio-system   istio-galley-7fcdcc57f9-whs2j             1/1       Running     0          4m        10.10.1.154     k8s2      <none>
	 istio-system   istio-ingressgateway-597fd5bd96-pg445     0/1       Running     0          4m        10.10.1.15      k8s2      <none>
	 istio-system   istio-init-crd-10-726hh                   0/1       Completed   0          4m        10.10.1.103     k8s2      <none>
	 istio-system   istio-init-crd-11-x95zg                   0/1       Completed   0          4m        10.10.1.21      k8s2      <none>
	 istio-system   istio-init-crd-12-jctdf                   0/1       Completed   0          4m        10.10.1.96      k8s2      <none>
```

2019-09-11 22:27 UTC, ianvernon commented
test-me-please

2019-09-12 13:15 UTC, aanm approved these changes

2019-09-12 15:26 UTC, merged