k8s: Allow `_` in CNP CRD toFQDNs validation
cilium/cilium pull request #9179
Opened 2019-09-11 11:55 UTC by raybejjani

We allowed `_` in f00f857 but did not
update the CRD validation to match. This changes the CRD validation to
match the internal matchpattern validation. The regex is quite different
because the older CRD validator enforced valid domain names but `_`
violates this. Since we aren't enforcing domain names the overall
pattern can be collapsed down.

fixes f00f857

2019-09-11 11:56 UTC, raybejjani commented
test-me-please

2019-09-11 13:20 UTC, aanm requested changes
Can you also update `./examples/crds/ciliumnetworkpolicies.yaml`?

All of this will be automagically done in the future

2019-10-21 17:49 UTC, ianvernon commented
@raybejjani ping - is this still needed? I recall we wanted this for a user who needed underscores.

2019-11-06 11:36 UTC, raybejjani commented
@aanm I think I updated the file in all the spots where toFQDNs would show up. Hopefully it's complete!

2019-11-06 11:37 UTC, raybejjani commented
test-me-please

2019-11-06 14:02 UTC, aanm approved these changes

2019-11-08 11:03 UTC, aanm approved these changes

2019-11-08 11:04 UTC, aanm commented
@raybejjani do we need to backport this to v1.5 and v1.6 since it's fixing a commit that was backported?

2019-11-08 18:33 UTC, ianvernon commented
Upstream K8s tests failed:

```
06:38:12  Running pods 0
06:38:13  Running pods 0
06:38:13  Sending interrupt signal to process
06:38:14  Connection to 127.0.0.1 closed by remote host.
06:38:14  script returned exit code 255
```

2019-11-08 18:33 UTC, ianvernon commented
test-upstream-k8s

2019-11-08 18:35 UTC, ianvernon approved these changes

2019-11-11 10:48 UTC, merged

2019-11-11 16:27 UTC, raybejjani commented
@aanm I'm not sure. It should backport cleanly (and maybe we want that? so that the CRD version is updated?) but it's also not a critical bug. You have to be using `_` in your DNS and we've only had 1 report so far.
I'm fine either way.