daemon: check error from `d.init()`
cilium/cilium pull request #9182
Opened 2019-09-11 20:56 UTC by ianvernon

Commit a4f50323a7e0b437611d9567dfaa8f6d1a4a516b shuffled code around such that
the `err` variable from `d.init()` was masked by the invocation of
`monitoragent.NewAgent()`. As such, if `d.init()` failed, we would never know
that it had because its returned error was overwritten to `nil` if
`monitoragent.NewAgent()` subsequently succeed.

Fixes: a4f50323a7e0b437611d9567dfaa8f6d1a4a516b

Signed-off by: Ian Vernon <ian@cilium.io>

2019-09-11 20:56 UTC, ianvernon commented
test-me-please

2019-09-11 22:07 UTC, ianvernon commented
test-me-please

2019-09-12 20:18 UTC, aanm approved these changes
Nice catch :scream:

2019-09-12 20:19 UTC, aanm requested changes
Wait, no. the err on line 493 is still valid on line 502.

2019-09-12 20:20 UTC, aanm commented on daemon/daemon.go
>  		monitorAgent, err := monitoragent.NewAgent(context.TODO(), defaults.MonitorBufferPages)
`err` is a new variable. It shadows `493` but the `err` in 493 is still valid in `502`

2019-09-12 20:51 UTC, ianvernon commented on daemon/daemon.go
>  		monitorAgent, err := monitoragent.NewAgent(context.TODO(), defaults.MonitorBufferPages)
Wow, TIL, you're right! To those reading this, check out the following: https://play.golang.org/p/Q-HzFMwhTAy

But, this is still a bug, in that we do not check whether base programs successfully compiled or not (checking the error returned from `d.init()`) before starting the monitorAgent, which was part of why the code to start the monitor agent was moved to this location. I'll update the commit to reflect this.

2019-09-12 20:56 UTC, ianvernon commented on daemon/daemon.go
>  		monitorAgent, err := monitoragent.NewAgent(context.TODO(), defaults.MonitorBufferPages)
See the new commit message.

2019-09-16 10:13 UTC, brb approved these changes
Nice catch!

2019-09-16 10:15 UTC, aanm approved these changes

2019-09-16 14:30 UTC, merged