daemon: do not remove created directory in `TearDownTest`
cilium/cilium pull request #9183
Opened 2019-09-11 22:07 UTC by ianvernon

The directory is created in `TestMain`, which runs once, while `TearDownTest`
runs after every test. This means that the directory is deleted after the first
test in the Daemon test suite is ran, which is not correct. Instead, defer the
deletion of this directory after `TestMain` has exited.

Signed-off by: Ian Vernon <ian@cilium.io>

2019-09-12 13:12 UTC, aanm requested changes

2019-09-12 13:12 UTC, aanm commented on daemon/daemon_test.go
> +	defer os.RemoveAll(tempRunDir)
But AFAIK, TestMain doesn't block until the tests are run.

2019-09-12 13:12 UTC, aanm commented on daemon/daemon_test.go
> -		os.RemoveAll(option.Config.RunDir)
Shouldn't the `TearUpTest` create a new `option.Config.RunDir` as well as leaving this change untouched?

2019-09-12 15:40 UTC, ianvernon commented on daemon/daemon_test.go
> +	defer os.RemoveAll(tempRunDir)
I don't understand what you mean here :/ are you saying that this won't run because we run `ox.Exit(m.Run()`?

2019-09-12 15:42 UTC, ianvernon commented on daemon/daemon_test.go
> -		os.RemoveAll(option.Config.RunDir)
I'll look into seeing whether the logic can be put into `SetUpTest`. I definitely think that we should not have the `ds.d != nil` check, though, and just unconditionally try to remove the existing `option/config/RunDir`, as we create the directories regardless of if the Daemon is nil or not.

2019-09-12 16:16 UTC, ianvernon commented on daemon/daemon_test.go
> +	defer os.RemoveAll(tempRunDir)
Code has changed, PTAL

2019-09-12 16:16 UTC, ianvernon commented on daemon/daemon_test.go
> -		os.RemoveAll(option.Config.RunDir)
Refactored the configuration setup to be ran before each test. I had to make a change to ensure that metrics registration was only done once per run of the tests within `option.Config.Populate()`.

2019-09-12 20:21 UTC, aanm commented on pkg/option/config.go
> +	// Only run this once so we can call this function multiple times in unit
`TestMain` was added for this reason :) cc @jrajahalme

2019-09-12 20:37 UTC, ianvernon commented on pkg/option/config.go
> +	// Only run this once so we can call this function multiple times in unit
I can do the following in `TestMain` and revert the changes to `pkg/option/config.go`:

```
option.Config.Populate()	 	
option.Config.IdentityAllocationMode = option.IdentityAllocationModeKVstore
```

Would this alleviate your concerns? What is blocking here?

2019-09-12 21:27 UTC, jrajahalme requested changes

2019-09-12 21:27 UTC, jrajahalme commented on pkg/option/config.go
> +	// Only run this once so we can call this function multiple times in unit
I'd prefer keeping the TestMain() for the calls that must be done only once.

2019-09-12 21:27 UTC, jrajahalme commented on daemon/daemon_test.go
> +	os.RemoveAll(option.Config.RunDir)
Is this done also when the test fails? It would be nice to have the temp files around when a test fails.

2019-09-12 21:44 UTC, ianvernon commented on daemon/daemon_test.go
> +	os.RemoveAll(option.Config.RunDir)
Done, PTAL

2019-09-12 21:47 UTC, jrajahalme approved these changes

2019-09-12 22:03 UTC, ianvernon commented on pkg/option/config.go
> +	// Only run this once so we can call this function multiple times in unit
Got approval from Jarno, PTAL

2019-09-16 10:09 UTC, brb approved these changes

2019-09-16 14:29 UTC, ianvernon commented
@aanm can you PTAL again? I want to make sure you are OK with how I addressed the feedback. This is blocking a few other PRs I would like to get merged.

2019-09-17 14:50 UTC, aanm approved these changes

2019-09-17 15:02 UTC, merged