daemon: create globals directory when other directories are created
cilium/cilium pull request #9184
Opened 2019-09-11 22:19 UTC by ianvernon

This reduces the creation of directories from being spread across different
parts of the code base.

Signed-off by: Ian Vernon <ian@cilium.io>

2019-09-11 23:05 UTC, ianvernon commented
test-me-please

2019-09-12 13:10 UTC, aanm requested changes

2019-09-12 13:10 UTC, aanm commented on daemon/daemon.go
> +
Seems unrelated.

2019-09-12 13:10 UTC, aanm commented on daemon/daemon.go
>  	if err := os.Chdir(option.Config.StateDir); err != nil {
Shouldn't this be moved as well?

2019-09-12 13:10 UTC, aanm commented on daemon/daemon_main.go
> +
I would suggest to have a dedicated function for directories stuff

2019-09-12 13:10 UTC, aanm commented on daemon/daemon_test.go
> +	defer os.RemoveAll(tempRunDir)
was `option.Config.RunDir` set with `tempRunDir`?

2019-09-12 13:10 UTC, aanm commented on daemon/daemon_test.go
> -		os.RemoveAll(option.Config.RunDir)
Won't this leave leftover files from the tests?

2019-09-18 15:09 UTC, ianvernon commented
test-me-please

2019-09-19 01:32 UTC, ianvernon commented
test-me-please

2019-09-19 16:30 UTC, ianvernon commented
test-me-please

2019-10-01 20:11 UTC, ianvernon commented
test-me-please

2019-10-30 22:33 UTC, closed without merging