CMD - service list command refactoring Fix #744
cilium/cilium pull request #934
Opened 2017-06-08 06:37 UTC by eloycoto

Hello! 

A few changes here: 

- [x] Added text/tabwriter
- [x] Changed the sort with the new options added in Golang 1.8. 
- [x] Added header labels

Around the compact format for backend address, I tried a different ways, but I didn't get any better option, if you have any suggestion I'm happy to change it. 

Current output: 
```
➜  cilium git:(744) ✗ ./cilium service list
ID   Frontend       Backend
2    0.0.0.0:90     1 => 192.168.100.1:80
                    2 => 192.168.100.2:80
                    3 => 192.168.100.4:80
3    0.0.0.0:8080   1 => 192.168.99.1:80
                    2 => 192.168.99.2:80
```

Regards.

2017-06-08 06:45 UTC, aalemayhu requested changes
Other than the import, looks good.

2017-06-08 06:45 UTC, scanf commented on cilium/cmd/service_list.go
>  )
This import needs to be further up. Cilium and go imports should be split.

2017-06-08 06:52 UTC, scanf commented
So the build is failing because the go version in the CI is `go1.7.4`.
@aanm shouldn't the VM be running at least `go1.8.1` by now?

```
[Runtime Tests] ==> cilium-master: cilium/cmd/service_list.go:90: undefined: sort.Slice
[Runtime Tests] ==> cilium-master: Makefile:43: recipe for target 'tests-consul' failed
[Runtime Tests] ==> cilium-master: make: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium'
[Runtime Tests] ==> cilium-master: make: *** [tests-consul] Error 1
```

2017-06-08 06:59 UTC, eloycoto commented on cilium/cmd/service_list.go
>  )
Sorry! It is now changed.

2017-06-08 14:03 UTC, aanm approved these changes

2017-06-08 14:04 UTC, aanm commented
> @aanm shouldn't the VM be running at least go1.8.1 by now?

@tgraf was the new image pushed to atlas?

2017-06-08 16:34 UTC, tgraf commented
> @tgraf was the new image pushed to atlas?

It's currently building on my mac. I've updated the scripts a bit as well: https://github.com/cilium/packer-ubuntu-16.10/pull/4

2017-06-08 17:09 UTC, aalemayhu approved these changes

2017-06-10 12:28 UTC, tgraf commented
> It's currently building on my mac. I've updated the scripts a bit as well: cilium/packer-ubuntu-16.10#4

New vagrant box is uploaded and updated on Jenkins slaves. Please `rebase master --ignore-date` and `push -f` to trigger a new Jenkins run.

2017-06-10 15:15 UTC, eloycoto commented
Hey, 

I updated the branch from master. Looks like that there is a problem with the labels. Not sure if something related to this branch. 

Do I need to do anything here?

Best regards

2017-06-10 17:38 UTC, tgraf commented
> Do I need to do anything here?

No, this seems to be an issue with upgrading to 1.8.3, we're tracking this in #955

2017-06-10 19:53 UTC, eloycoto commented
Hello!

Ok, I'll keep an eye on that issue. I forgot to check the tests suite and 06-lb.sh is affected. I changed a few lines, and I use the REST API instead of use the cilium list, not sure if It is correct, if you're not happy with that I'll change to the original behaviour ;-)

2017-06-11 00:55 UTC, tgraf commented
> Ok, I'll keep an eye on that issue. I forgot to check the tests suite and 06-lb.sh is affected. I changed a few lines, and I use the REST API instead of use the cilium list, not sure if It is correct, if you're not happy with that I'll change to the original behaviour ;-)

The CI is back, you can push again after you've fixed the issues of this PR.

2017-06-12 09:44 UTC, eloycoto commented
All looks good now, I think that is good to merge ;-)

2017-06-12 10:12 UTC, merged