daemon: Fix race condition when syncing services with k8s
cilium/cilium pull request #9341
Opened 2019-10-04 11:56 UTC by brb

Previously, the `sync-lb-maps-with-k8s-services` controller did the following:

1. Fetched a list of services from `pkg/k8s.k8sServiceCache`.
2. Iterated over `pkg/service.Service` cache and removed those which couldn't be found in the former list.

As no lock was held during the (1) and (2) steps, any service added to `service.Service` after the (1) step was removed.

Fix this race condition by setting the `noUpdateAfterRestore` flag for each service during `RestoreServices()` (happens before the controller is scheduled) and unset it in `UpsertService()`; in `SyncWithK8sFinished()` remove those services which still has the flag being set.

The fix is based on an assumption that during the k8s service cache sync period `UpsertService()` is going to be called for each alive service.

Not backporting to v1.5 and v1.6, as the fix heavily relies on the recent LB refactoring.

```release-minor
Fix race condition when syncing Kubernetes services after cilium-agent restart which could resulted in failures to establish connections to some services.
```

Fix: #9333.

2019-10-04 11:56 UTC, brb commented
test-me-please

2019-10-07 15:05 UTC, aanm reviewed
Discuss offline, there's still a small race in the `service_cache.go` Events channel

2019-10-09 14:25 UTC, brb commented
test-me-please

2019-10-11 07:14 UTC, brb commented
test-me-please

2019-10-21 12:26 UTC, brb commented
test-me-please

2019-10-21 15:07 UTC, brb commented
@aanm PTAL.

2019-10-21 17:56 UTC, ianvernon approved these changes

2019-10-22 07:06 UTC, brb commented
test-me-please

2019-10-22 10:27 UTC, brb commented
test-me-please

2019-10-22 12:40 UTC, brb commented
The CI hit unrelated the NodePort BPF flake.

2019-10-22 15:10 UTC, aanm requested changes
1) Consider renaming the field `noUpdateAfterRestore` to `restoredFromDatapath`
2) Add a small comment when the field `noUpdateAfterRestore` is being assigned with a value. Describing why is that value being. For example "Setting `noUpdateAfterRestore` with false here because we have received the update from k8s events"

2019-10-23 09:30 UTC, brb commented
test-me-please

2019-10-23 17:20 UTC, aanm approved these changes

2019-10-23 17:20 UTC, merged