[WIP] Operator:  try to fix disconnects on operator restarts when using ipsec
cilium/cilium pull request #9343
Opened 2019-10-04 13:32 UTC by lbernail

We noticed that on container restarts established TCP connections were disconnected (under load).
After some investigation we noticed these events on the agent for all nodes:
- `Received key update via kvstore` with invalid `EncryptionKey:0`
- a few minutes later `Received key update via kvstore` with valid `EncryptionKey:x`

After looking into the code, it seems that on operator restart the node Informer will add all nodes to the kvstore based on the k8s-node resource which does not have the EncryptionKey info and will set it to 0. Watches on the agents will then update the ipsec configuration and create the issue. After a while, the agents update their kvstore resource to the the good value and traffic can flow again (I haven't checked but I assume there is a reconcile loop in the agents).

This PR removes the Add and Update handlers for the k8s-node resources (but keep the Delete handler to handle node deletion).

We've tested it and the following works:
- operator restart doesn't trigger wrong kvstore update
- adding a new node works (the agent create the kvstore and the ciliumnode resources)
- deleting a node works (the operator removes the kvstore and ciliumnode resources)

This PR is marked as WIP because we don't know the operator well enough to be sure that we are not missing something (of course if it's approved I'll clean the PR to simply remove the code instead of commenting).

cc @tgraf / @jrfastab

2019-10-07 10:05 UTC, aanm requested changes
Thanks for the explanation in the PR description.

We can't simply remove this code because it's synchronizing the k8s nodes into the kvstore. The option `--enable-k8s-event-handover` highly depends on this.

Before we get the nodes from k8s we list and start watching them from the kvstore here:

https://github.com/cilium/cilium/blob/3aacf41d784ef39c67efbf0c700be051077c5613/operator/k8s_node.go#L59-L65

That function will list all nodes present in the kvstore and it only returns once the operation 'list' is complete.

The problem however is in line 77 [1] where we blindly update the node:

[1]
https://github.com/cilium/cilium/blob/3aacf41d784ef39c67efbf0c700be051077c5613/operator/k8s_node.go#L74-L82

We should compare the node received from k8s with the node that we have received from the kvstore and only update it if different. There are 2 ways we can assure this:

1) We perform a comparison similar to the one being performed in [2] where we will ignore the `EncryptionKey` difference and only push into the kvstore when the node is considered different:

2) We add the `EncryptionKey` into k8s annotations, I thought we were already doing that. cc @jrfastab 

[2]
https://github.com/cilium/cilium/blob/3aacf41d784ef39c67efbf0c700be051077c5613/operator/k8s_node.go#L85-L87

2019-10-07 13:03 UTC, lbernail commented
@aanm Thanks for the detailed explanation. I was assuming node creation in the kvstore was done by the agents (in our case node are created ok with the removed code but it may be related to our setup).

I'm not clear where the source of truth should be for the different node properties (node annotation? ciliumnode cr? kvstore?).

Option 1 (testing for equalv1Node) seems very easy to do and I can definitely give a try (I can also work on option 2 but I'm not sure where to do that exactly)

2019-10-07 18:06 UTC, jrfastab commented
It looks to me though even with above change you will still do some Upsert() logic with incorrect keys. For example the health agents just below this will no longer be encrypted?
```
        for _, address := range []net.IP{n.IPv4HealthIP, n.IPv6HealthIP} {
                if address == nil {
                        continue
                }
                isOwning := ipcache.IPIdentityCache.Upsert(address.String(), n.GetNodeIP(false), n.EncryptionKey, nil, ipcache.Identity{
                        ID:     identity.ReservedIdentityHealth,
                        Source: n.Source,
                })
                if !isOwning {
                        dpUpdate = false
                }
        }
```

2019-10-07 18:09 UTC, jrfastab commented
I had expected that the parse node update logic from ./daemon/k8s_watcher.go would have the correct encrypt key included in the message,
```
func ParseCiliumNode(n *ciliumv2.CiliumNode) (node Node) {
        node = Node{
                Name:          n.Name,
                EncryptionKey: uint8(n.Spec.Encryption.Key),
                Cluster:       option.Config.ClusterName,
                ClusterID:     option.Config.ClusterID,
                Source:        source.CustomResource,
        }
```
Apparently this is not happening.

2019-10-21 14:11 UTC, lbernail commented
@aanm / @jrfastab 
If you have an idea of what we should implement I can start working on it this week
It's not really urgent for us because we've been running the workaround from this PR without any issue for ~2 weeks, but I'd rather we rely on a clean fix (and a real Cilium release)

2019-10-22 17:02 UTC, jrfastab commented
@lbernail I think I have a fix for this will try to push later today, but would you be up for testing as I can't actually reproduce this.

2019-10-22 17:54 UTC, lbernail commented
@jrfastab Yes of course I can test the fix as soon as you have one

I did not see it until we tested with a real world cassandra cluster under load because the consequence of the problem is the loss of packets during a short amount of time but it shows a lot when you look at the aggregate cassandra throughput

2019-11-14 16:08 UTC, jrfastab commented
proposed fix here, https://github.com/cilium/cilium/pull/9612

2019-11-29 14:27 UTC, aanm commented
@lbernail was this fixed by #9612 ?

2019-12-12 16:02 UTC, jrajahalme commented
@ibernail please close this if not needed now that #9612 has merged.

2020-02-18 23:26 UTC, aanm commented
> @ibernail please close this if not needed now that #9612 has merged.

ping @lbernail ?

2020-04-20 15:40 UTC, closed without merging