Use config option for security identity swap cool-down period
cilium/cilium pull request #9349
Opened 2019-10-04 20:16 UTC by ungureanuvladvictor

Swapped the `time.Sleep` in the security identity swap to use the config option instead of the hardcoded default.

```release-note
Use config option for security identity swap cool-down period
```

2019-10-05 16:14 UTC, joestringer approved these changes

2019-10-07 09:47 UTC, aanm requested changes
@ungureanuvladvictor the commit is missing a sign-off

2019-10-07 16:20 UTC, ungureanuvladvictor commented
@aanm added the sign-off.

2019-10-07 16:32 UTC, aanm approved these changes

2019-10-07 16:32 UTC, aanm commented
test-me-please

2019-10-07 20:06 UTC, merged