[CI] Node affinity based on labels not hostname
cilium/cilium pull request #9365
Opened 2019-10-08 12:27 UTC by nebril

This change allows node affinity-depending tests use custom labels
instead of kubernetes.io/hostname.

2019-10-08 12:27 UTC, nebril commented
test-me-please

2019-10-08 13:05 UTC, nebril commented
test-me-please

2019-10-08 14:21 UTC, raybejjani approved these changes

2019-10-08 14:41 UTC, nebril commented
test-missed-k8s

2019-10-08 17:28 UTC, ianvernon reviewed
This looks good, but it looks like some breakage was introduced into the CI. I will review once the tests pass.

2019-10-09 10:40 UTC, aanm requested changes

2019-10-09 10:40 UTC, aanm commented on test/k8sT/manifests/guestbook_deployment.yaml
> -        kubernetes.io/hostname: k8s1
You have missed line 122 of this file

2019-10-09 12:30 UTC, nebril commented
test-me-please

2019-10-09 12:30 UTC, nebril commented
test-missed-k8s

2019-10-09 13:20 UTC, aanm approved these changes

2019-10-18 12:42 UTC, nebril commented
test-missed-k8s

2019-10-21 12:09 UTC, nebril commented
test-missed-k8s

2019-10-21 12:09 UTC, nebril commented
test-me-please

2019-10-21 22:54 UTC, ianvernon approved these changes

2019-10-21 22:54 UTC, merged