install: Add `system:nodes` Group to cilium ClusterRoleBinding
cilium/cilium pull request #9388
Opened 2019-10-10 10:18 UTC by jaffcheng

Create a cilium cluster via cilium.yaml generated by helm template,
agent fails because User system:nodes:NODE_NAME cannot get desired k8s
resource, this fixes the issue.

Signed-off-by: Jaff Cheng <jaff.cheng.sh@gmail.com>

2019-10-10 10:35 UTC, aanm requested changes
@jaffcheng can you provide more logs regarding the issue you were seeing and steps to replicate the problem? Thank you

2019-10-10 11:41 UTC, jaffcheng commented
Hi @aanm , I have a pre-built **v1.13.2** kubernetes all in one cluster, following cilium 1.6.2 installation guide, I downloaded and decompressed https://github.com/cilium/cilium/archive/1.6.2.tar.gz .

After executing
```
helm template cilium \
  --namespace kube-system \
  --set global.etcd.enabled=true \
  --set global.etcd.endpoints[0]=http://xxx:2379 \
  --set global.etcd.endpoints[1]=http://xxx:2379 \
  > cilium.yaml

kubectl create -f cilium.yaml
```
cilium-agent started and tried to contanct apiserver, but failed with error:
```
level=info msg="Establishing connection to apiserver" host="https://192.168.160.130:6443" subsys=k8s
level=error msg="Unable to contact k8s api-server" error="namespaces \"kube-system\" is forbidden: User \"system:node:dev\" cannot get resource \"namespaces\" in API group \"\" in the namespace \"kube-system\"" ipAddr="https://192.168.160.130:6443" subsys=k8s
level=fatal msg="Unable to initialize Kubernetes subsystem" error="unable to create k8s client: unable to create k8s client: namespaces \"kube-system\" is forbidden: User \"system:node:dev\" cannot get resource \"namespaces\" in API group \"\" in the namespace \"kube-system\"" subsys=daemon
```

After applying the changes, the errors are gone.
It seems these lines exist in cilium v1.5 example yaml file, not sure why they are removed in v1.6:
https://github.com/cilium/cilium/blob/v1.5/examples/kubernetes/1.15/cilium-external-etcd.yaml#L621

2019-10-12 10:10 UTC, jaffcheng commented
Thanks @aanm , using cilium service account should be the right approach. Maybe we could add the configmap to examples or mention that in the docs for users running without kube-proxy?

2019-10-12 10:11 UTC, jaffcheng commented
Closing this.

2019-10-12 10:11 UTC, closed without merging