[WIP] Vagrant concurrent build fix
cilium/cilium pull request #941
Opened 2017-06-08 21:00 UTC by ianvernon

2017-06-08 21:45 UTC, ianvernon commented
I did multiple things to try to fix the issue @aanm observed in #931:

1. Cleaned up old VMs that were running on the Jenkins instances that were lying around for a few months.
2. Cleaned up the state of Vagrant after deleting the VMs from 1 using `vagrant global-status --prune`.
3. Added the changes in the commit above.

I was not able to reproduce the issue found in #931 locally by concurrently running multiple instances of the VMs used in the build (one for runtime-tests / k8s tests) at the same time by cloning the cilium repository to two locations on my local setup. Based on my prior experience with VirtualBox / Vagrant however, it is a good idea to use different intnets for parallel builds.

2017-06-08 22:01 UTC, aanm commented on tests/k8s/Vagrantfile
> +$node_ip = "192.168.33.15"
Can multiple VMs from multiple tests share the same IP?

2017-06-08 22:02 UTC, ianvernon commented on tests/k8s/Vagrantfile
> +$node_ip = "192.168.33.15"
yes, because in each build they are in separate vbox__intnet's.

2017-06-12 13:19 UTC, tgraf requested changes
Looks good, needs squash & rebase.

2017-06-12 16:29 UTC, aanm approved these changes

2017-06-12 17:38 UTC, tgraf approved these changes

2017-06-12 17:39 UTC, merged