docs: Improve external etcd documentation wording
cilium/cilium pull request #9415
Opened 2019-10-14 22:35 UTC by mpeiffer

Changes to be committed:
	modified:   k8s-install-external-etcd.rst
	modified:   requirements_intro.rst

Previously, having an available external etcd was not listed under the requirements section in the external etcd documentation. This was addressed by listing "Key-Value store etcd >= 3.1.0 or consul >= 0.6.4" under the requirements section. In addition, the section title "Configure the external etcd" referred to the configuration of Cilium and not an external etcd, thus the title was changed to "Configure Cilium" for clarity.

Fixes: #9401

Signed-off-by: Melissa Peiffer mbp83@nau.edu

2019-10-14 23:57 UTC, joestringer requested changes
Hi, thanks for the contribution!

As a matter of policy, all commits should be signed off (`git commit -s`): http://docs.cilium.io/en/latest/contributing/contributing/#developer-s-certificate-of-origin

I also commented on the changes below, minor adjustmentments needed.

2019-10-14 23:57 UTC, joestringer commented on Documentation/gettingstarted/requirements_intro.rst
> +* Key-Value store etcd >= 3.1.0 or consul >= 0.6.4
While this improves the docs for the "External etcd" guide, this also now reports such a requirement for the "etcd operator" guide (http://docs.cilium.io/en/latest/gettingstarted/k8s-install-etcd-operator/) which actually requires neither `etcd` nor `consul` to be installed, as that guide will configure `etcd` as part of the guide.

Also, this text is only referred to from etcd guides so the Consul mention is not necessary. That option is already documented here: http://docs.cilium.io/en/latest/install/system_requirements/#summary

```
$ git grep requirements_intro Documentation/
Documentation/gettingstarted/k8s-install-etcd-operator.rst:.. include:: requirements_intro.rst
Documentation/gettingstarted/k8s-install-external-etcd.rst:.. include:: requirements_intro.rst
```

2019-10-14 23:57 UTC, joestringer commented
test-docs-please

2019-10-18 10:44 UTC, aanm commented
test-docs-please

2019-10-18 16:19 UTC, joestringer reviewed
Looks good, could you just rebase and squash the commits together?

https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history

2019-10-22 09:09 UTC, aanm commented
ping @mpeiffer

2019-10-22 17:39 UTC, mpeiffer commented
Hello, I apologize for the wait. I will rebase and squash my commits together later today.

2019-10-22 21:26 UTC, mpeiffer commented
I'm not really sure what I did but I will revert these changes and fix all of this as soon as possible.

2019-10-22 22:38 UTC, closed without merging