endpoint: Do not fail to regenerate endpoint when running w/o L7 proxy
cilium/cilium pull request #9481
Opened 2019-10-23 09:15 UTC by brb

It is expected that in some deployments the L7 proxy will be disabled. Currently, it can be disabled when `--install-iptables-rules=false` is set which can happen when e.g.  running in the ipvlan mode or
w/o netfilter/iptables.

To play nicely with such deployments, do not fail the endpoint regeneration when the L7 proxy is disabled.

2019-10-23 09:15 UTC, brb commented
test-me-please

2019-10-23 13:44 UTC, brb commented
test-me-please

2019-10-23 18:19 UTC, ianvernon commented
I don't think this is a complete enough fix. We should disable L7 policy being allowed to be imported via Cilium in this case as well. Otherwise we will tell users they are realizing policy which actually isn't being realized. It's not clear at first that disabling iptables rules would disable the proxy, which in turn disables an entire layer of policy enforcement.

2019-10-24 13:33 UTC, aanm approved these changes

2019-10-24 16:28 UTC, ianvernon commented
> I agree that it's very unclear. What if I introduce --enable-l7-proxy (default "true"), and log a fatal message when --enable-l7-proxy=true and --install-iptables-rules=false?

Works for me.

> AFAIK, the policy import happens async, so in the best case we could just log an error? I'd like to keep such change out of the scope of this PR.

Please log a warning if there are L7 rules in the policy and we have the proxy disabled.

2019-10-24 16:29 UTC, ianvernon requested changes
Commented out of band of the review.

2019-10-28 10:04 UTC, brb commented
test-me-please

2019-10-28 20:51 UTC, joestringer approved these changes
The changes that are here are simple and straightforward.

I understand from the community meeting that there is a desire to also reject CNPs that configure L7 rules (and perhaps also FQDN rules) in this PR as well.

2019-10-29 10:35 UTC, brb commented
test-me-please

2019-10-29 10:43 UTC, brb commented
PTAL. Created a separate issue with the `release-blocker` priority to track warning/rejecting CNPs with L7 rules and `--enable-l7-proxy=false`: https://github.com/cilium/cilium/issues/9518.

2019-10-29 14:13 UTC, aanm commented on install/kubernetes/cilium/charts/config/templates/configmap.yaml
> +
remove new line?

2019-10-30 04:23 UTC, ianvernon approved these changes

2019-10-31 07:24 UTC, brb commented
test-me-please

2019-10-31 11:12 UTC, aanm commented
test-me-please

2019-10-31 13:35 UTC, aanm commented
test-me-please

2019-10-31 17:59 UTC, aanm commented
test-me-please

2019-10-31 19:25 UTC, aanm commented
test-me-please

2019-11-01 22:06 UTC, joestringer approved these changes
Minor nit.

2019-11-01 22:06 UTC, joestringer commented on daemon/daemon.go
> +		log.Info("L7 proxies is disabled")
nit:
```suggestion
		log.Info("L7 proxies are disabled")
```

2019-11-04 12:42 UTC, aanm commented
test-me-please

2019-11-04 17:20 UTC, merged