Add unit tests for health server
cilium/cilium pull request #9491
Opened 2019-10-24 03:54 UTC by joestringer

Do a little refactoring and write some basic sanity unit tests for the health server.

2019-10-30 03:13 UTC, joestringer commented
test-me-please

2019-10-30 03:21 UTC, joestringer commented
test-me-please

2019-11-01 18:32 UTC, joestringer commented
test-me-please

2019-11-01 19:55 UTC, joestringer commented
test-me-please

2019-11-04 10:19 UTC, gandro approved these changes
Nice!

2019-11-04 11:44 UTC, aanm requested changes

2019-11-04 11:44 UTC, aanm commented on pkg/ip/addr.go
> +// Copyright 2019 Authors of Cilium
This should not be required or at least the full file. See [1]

2019-11-04 11:44 UTC, aanm commented on pkg/health/server/prober_test.go
> +		sort.Sort(ip.AddrsByMask(slice))
[1]
```golang
	sort.Slice(slice, func(i, j int) bool {
		iLength := len(slice[i].IP)
		jLength := len(slice[j].IP)
		if iLength == jLength {
			return bytes.Compare(slice[i].IP, slice[j].IP) < 0
		}
		return iLength < jLength
	})
```

2019-11-04 17:31 UTC, joestringer commented
test-me-please

2019-11-04 21:10 UTC, aanm approved these changes

2019-11-04 21:16 UTC, merged