Add enable-local-node-route option
cilium/cilium pull request #9505
Opened 2019-10-26 01:17 UTC by jraby

Controls adding the route which points to the allocation prefix of the
local node. The option can be used to avoid adding the route when an
external process is managing the routes.

This basically plumbs `nodediscovery.enableLocalNodeRoute()` out to the CLI options.

It is a first step in being able to use cilium in generic-veth mode with the bridge cni plugin (and kube-router in CNI mode), since the `cni0` interface created by `bridge` already holds the route for the node's podCIDR (allocation prefix), in this case cilium shouldn't go about overriding that route.

Fixes: #9503

2019-10-28 12:58 UTC, aanm approved these changes

2019-10-28 12:58 UTC, aanm commented
test-me-please

2019-10-28 14:25 UTC, tgraf requested changes
@jraby You'll need to run `make -C Documentation cmdref` to update the Documentation with the new option.

2019-10-28 16:13 UTC, ianvernon commented
test-me-please

2019-10-28 16:15 UTC, ianvernon commented on Documentation/cmdref/cilium-agent.md
> +      --enable-local-node-route                               Enable installation of the route which points the allocation prefix of the local node (default true)
@jraby please sign off on this commit

2019-10-28 17:02 UTC, jraby commented on Documentation/cmdref/cilium-agent.md
> +      --enable-local-node-route                               Enable installation of the route which points the allocation prefix of the local node (default true)
(squashed the commit into previous one)

2019-10-28 17:03 UTC, ianvernon commented
test-me-please

2019-10-28 20:48 UTC, joestringer approved these changes

2019-10-29 08:59 UTC, tgraf approved these changes

2019-10-29 08:59 UTC, merged