Cilium daemonset gets deleted every 40s on AKS.
cilium/cilium pull request #9519
Opened 2019-10-29 12:21 UTC by mlushpenko

This patch deletes depreceted label that triggers AKS to delete cilium daemonset and breaks cluster networking.

Similar issue: https://github.com/kubernetes/kubernetes/issues/51376
The main issue looks to be this one: addon manager reads all deployments from api server with annotation cluster-service:true -> deletes all that do not exist as files

Fixes: #9464

Signed-off-by: Maksym Lushpenko <maksym.lushpenko@hal24k.com>

```release-note
Fix cilium daemonset deletion on AKS
```

2019-10-29 13:03 UTC, borkmann commented
test-me-please

2019-10-29 13:04 UTC, tgraf requested changes
Change looks great. Thanks for digging in. Please run `make` in the `install/kubernetes` directory to regenerate the `quick-install.yaml` as well.

2019-10-29 13:18 UTC, mlushpenko commented
@tgraf done, thanks

2019-10-29 13:45 UTC, tgraf approved these changes

2019-10-29 13:46 UTC, tgraf requested changes
Sorry, one more small change needed. Remove the `priorityClassName: system-node-critical` from the generated `quick-install.yaml` Older k8s versions don't support it.

2019-10-29 14:12 UTC, mlushpenko commented
@tgraf updated

2019-10-29 14:15 UTC, tgraf approved these changes

2019-10-29 14:15 UTC, tgraf commented
test-me-please

2019-10-29 19:22 UTC, tgraf commented
The problem is that the upgrade tests perform `kubectl apply` as a user would. The selector is immutable. Not sure yet how to solve this properly.

2019-10-29 21:42 UTC, mlushpenko commented
Ouch, this is a nasty case. Looks like for upgrades, you'll have to delete the deployment. Wondering if `--force=true` would override it but probably not. Maybe you could add some script that greps on output and deletes a resource if it gets `immutable` output although that's a hack :) 

Would it be ok to accept such merge requests and add some sort of breaking change in release notes? As I understand, due to `cilium-node-init`, pods should be running even without `cilium` agent temporarily, so perhaps it's not too bad to delete it for the upgrade? Or maybe I got it wrong

2019-10-29 22:23 UTC, ianvernon commented
Is there a way to delete the label via the CLI? Perhaps we could add that to our upgrade tests as well as our upgrade docs.

2019-10-30 13:40 UTC, aanm commented
> Ouch, this is a nasty case. Looks like for upgrades, you'll have to delete the deployment. Wondering if `--force=true` would override it but probably not. Maybe you could add some script that greps on output and deletes a resource if it gets `immutable` output although that's a hack :)
> 
> Would it be ok to accept such merge requests and add some sort of breaking change in release notes? As I understand, due to `cilium-node-init`, pods should be running even without `cilium` agent temporarily, so perhaps it's not too bad to delete it for the upgrade? Or maybe I got it wrong

I've try it locally, `--force=true` does indeed the trick. The issue might be that a DaemonSet upgrade won't happen, what will happen is a deletion of a DaemonSet and a creation of a new DaemonSet which might be problematic since the users, when doing an upgrade, won't be able to safely "stop" an ongoing upgrade if things go sideways.

Perhaps the best solution would be to document in the upgrade notes that before doing the upgrade they would need to remove the labels manually from the running DaemonSet, by doing `kubectl get ds -n kube-system cilium > cilium-ds.yaml` opening the file, removing the labels and then `kubectl apply -f ./cilium-ds.yaml --force`. This would be less intrusive as it would make cilium pods to restart. Only after this step is made that users could then perform the upgrade for the new DaemonSet.

2019-11-04 18:48 UTC, tgraf commented
@mlushpenko We discussed this on the developer call today. We decided that we will change the CI to use `--force` in the upgrade test. After that change is in, this PR can be rebased on top of master and it should succeed. We'll also update the upgrade instructions accordingly.

2019-11-04 19:00 UTC, mlushpenko commented
Thanks, @tgraf, please ping me via `@` when rebase is needed.

2019-11-04 19:03 UTC, mlushpenko commented
We are unfortunately switching to Calico for now. Had too many problems with cilium and AKS combo and time is ticking.  The latest issue was exactly as described [here]( https://cilium.io/blog/2018/2/6/cilium-troubleshooting-cluster-health-monitor/#hands-on-troubleshooting-an-iptables-issue) but we didn't have an idea how to troubleshoot further (and not much time either)

2019-11-06 09:13 UTC, tgraf commented
@mlushpenko The CI has been adjusted to use `--force`. You can rebase the PR so we can we re-run the CI and see if the upgrade procedure will work if we document use of `--force` to apply the DaemonSet.

2019-11-06 14:14 UTC, aanm commented
test-me-please

2019-11-06 14:15 UTC, aanm commented
test-me-please

2019-11-07 12:47 UTC, aanm commented
test-me-please

2019-11-07 21:49 UTC, aanm commented
@mlushpenko can you please rebase against master again? Thanks!

2019-11-07 22:18 UTC, mlushpenko commented
@aanm good?

2019-11-08 08:34 UTC, aanm commented
test-me-please

2019-11-08 11:12 UTC, nebril commented
test-me-please

2019-11-08 14:59 UTC, nebril commented
test-me-please

2019-11-08 15:10 UTC, nebril commented
test-missed-k8s

2019-11-14 09:19 UTC, nebril commented
after https://github.com/cilium/cilium/pull/9605 is merged, please rebase, that should fix the underlying issue.

2019-11-14 10:26 UTC, aanm commented
test-me-please

2019-11-14 13:14 UTC, aanm commented
test-missed-k8s

2019-11-14 16:07 UTC, jrfastab commented
proposed fix here, https://github.com/cilium/cilium/pull/9612

2019-11-18 11:19 UTC, nebril commented
@mlushpenko please rebase again, CI issue should be resolved now.

2019-11-18 13:20 UTC, mlushpenko commented
@nebril fingers crossed this is the last time. Didn't expect so much interaction for a few lines of code :)

2019-11-18 13:23 UTC, aanm commented
test-me-please

2019-11-18 17:03 UTC, merged