Added chart value for etcd-operator cluster domain
cilium/cilium pull request #9526
Opened 2019-10-30 16:33 UTC by dsexton

This adds a Helm value for customizing the `CILIUM_ETCD_OPERATOR_CLUSTER_DOMAIN` value

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cilium/cilium/9526)

2019-10-31 09:21 UTC, aanm requested changes
changes look good, please generate the `quick-install.yaml` file.

`cd install/kubernetes && make clean all`

If `priorityClassName: system-node-critical` is added into the file please remove it manually. Thanks

Marked for backport since it might be useful for existing users to change it in 1.6

2019-11-01 16:52 UTC, dsexton commented
@aanm since this change is using the existing value it will not cause a change, however something else did change:

```
@ install/kubernetes/quick-install.yaml:384 @ spec:
            exec:
              command:
              - "/cni-install.sh"
              - "--enable-debug=true"
              - "--enable-debug=false"
          preStop:
            exec:
```

2019-11-01 17:12 UTC, aanm approved these changes

2019-11-01 17:12 UTC, aanm commented
@dsexton ah you are right, thanks for letting us know. I'll push a fix to fix that. In the meanwhile, can you sign-off your commit? Thanks!

2019-11-02 16:01 UTC, dsexton commented
@aanm unsure what you mean by sign-off, but this PR is ready for review/merge if that is what you mean.

2019-11-02 18:36 UTC, aanm commented
@dsexton As a matter of policy, all commits should be signed off (`git commit -s`): https://docs.cilium.io/en/v1.6/contributing/contributing/#developer-s-certificate-of-origin

2019-11-05 22:58 UTC, dsexton commented
@aanm done

2019-11-06 08:44 UTC, aanm approved these changes
Thanks @dsexton !

2019-11-06 08:45 UTC, aanm commented
test-me-please

2019-11-06 14:13 UTC, aanm commented
test-me-please

2019-11-06 17:35 UTC, merged