pkg/k8s: fix toServices policy update when service endpoints are modified
cilium/cilium pull request #9535
Opened 2019-10-31 16:59 UTC by aanm

When a toServices policy was used, Cilium wouldn't update the policy
toCIDR whenever the endpoints selected by that service changed. This
could make Cilium block traffic for new endpoints added, and allowing
traffic for endpoints deleted for the service selected by the toServices
rule.

Signed-off-by: André Martins <andre@cilium.io>

Fixes: https://github.com/cilium/cilium/issues/9525

Marking for backport for 1.5 and 1.6 since it affects policy enforcement.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cilium/cilium/9535)

2019-10-31 16:59 UTC, aanm commented
test-me-please

2019-10-31 17:05 UTC, aanm commented
test-me-please

2019-10-31 17:15 UTC, aanm commented
test-me-please

2019-11-04 12:27 UTC, raybejjani requested changes
I think this PR fixes the issue, but the original commit that added this (a270d52ef158371fa2be06db53df39866af0080c) was trying to avoid regenerating too often. There is a trigger to rate-limit the regenerations but from what I can tell the minimum interval (`option.Config.PolicyTriggerInterval`) is never set. Are we going to see unneeded regenerations as suggested in the original PR?

2019-11-04 16:38 UTC, aanm commented
> I think this PR fixes the issue, but the original commit that added this ([a270d52](https://github.com/cilium/cilium/commit/a270d52ef158371fa2be06db53df39866af0080c)) was trying to avoid regenerating too often. There is a trigger to rate-limit the regenerations but from what I can tell the minimum interval (`option.Config.PolicyTriggerInterval`) is never set. Are we going to see unneeded regenerations as suggested in the original PR?

@raybejjani The interval is being set here https://github.com/cilium/cilium/blob/c47bd8d0e042fa7455da378d30de0b11f81104c8/daemon/daemon.go#L373-L382

That is a good concern, the original commit was created before we stopped doing a resync from kubernetes. Since we are no longer doing a resync every 5 minutes we don't need this code anymore.

2019-11-04 17:01 UTC, raybejjani approved these changes
Works for me.

2019-11-05 09:18 UTC, merged