vendor: fix stack corruption from retrieving veth peer index
cilium/cilium pull request #9570
Opened 2019-11-06 16:31 UTC by borkmann

Manual backport till https://github.com/vishvananda/netlink/pull/498 got merged.

2019-11-06 16:31 UTC, borkmann commented
never-tell-me-the-odds

2019-11-06 20:26 UTC, borkmann commented
```Still waiting to schedule task
Waiting for next available executor on ‘baremetal’
Running on jenkins-node-3 in /home/jenkins/workspace/Cilium-PR-Doc-Tests
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
using credential ciliumbot
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/cilium/cilium
 > git init /home/jenkins/workspace/Cilium-PR-Doc-Tests # timeout=10
Fetching upstream changes from https://github.com/cilium/cilium
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress https://github.com/cilium/cilium +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=20
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/cilium/cilium +refs/heads/*:refs/remotes/origin/* --depth=1" returned status code 128:
stdout: 
stderr: fatal: unable to access 'https://github.com/cilium/cilium/': Could not resolve host: github.com

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2042)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1761)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$400(CliGitAPIImpl.java:72)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:442)```

2019-11-06 20:27 UTC, borkmann commented
never-tell-me-the-odds

2019-11-06 20:31 UTC, borkmann commented
CI issue: ``` > git fetch --tags --progress https://github.com/cilium/cilium +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=20
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/cilium/cilium +refs/heads/*:refs/remotes/origin/* --depth=1" returned status code 128:
stdout: 
stderr: fatal: unable to access 'https://github.com/cilium/cilium/': Could not resolve host: github.com

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2042)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1761)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$400(CliGitAPIImpl.java:72)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:442)```

2019-11-06 22:21 UTC, borkmann commented
never-tell-me-the-odds

2019-11-07 07:36 UTC, borkmann commented
test-missed-k8s

2019-11-07 07:36 UTC, borkmann commented
test-upstream-k8s

2019-11-07 09:13 UTC, aanm requested changes
we can't change the vendor manually.

2019-11-08 11:17 UTC, borkmann commented
Discussed offline & pinged netlink folks, so hopefully we could still rebase today.

2019-11-11 10:32 UTC, borkmann commented
Given the slow pace, I've temporary forked  vishvananda/netlink into cilium/netlink with the fixes applied. Will use that as dep in a new PR. Closing this one.

2019-11-11 10:32 UTC, closed without merging