HostToContainer propagation for /sys/fs/bpf
cilium/cilium pull request #9575
Opened 2019-11-07 16:37 UTC by jraby

By default, mount events from the host namespace are not propagated to a container  after a volume has been mounted into it.
Thus, the initContainer of the agent can never notice changes to /sys/fs/bpf (it cannot detect if the path became a mountpoint)

With mountPropagation: HostToContainer, the mount events are propagated to the container,
allowing the init container to correctly detect changes on /sys/fs/bpf, if it is mounted on the host while the script is blocked waiting for it to be mounted.

In other words, this makes wait-bpf-mount work as advertised.

Signed-off by: Jean Raby <jean@raby.sh>

2019-11-07 18:40 UTC, tgraf approved these changes
Great fix

2019-11-07 18:40 UTC, tgraf commented
test-me-please

2019-11-07 21:44 UTC, aanm approved these changes

2019-11-08 11:11 UTC, aanm commented
test-me-please

2019-11-08 13:46 UTC, aanm requested changes

2019-11-08 13:46 UTC, aanm commented on install/kubernetes/cilium/charts/agent/templates/daemonset.yaml
> +{{- /* Required for wait-bpf-mount to work */ -}}
please replace the `*/ -}}` with `*/}}`

2019-11-08 16:57 UTC, jraby commented
Should be in better shape now, I wrote this in github without testing anything :)

Not sure why `enable-debug` was toggled to false or where `      priorityClassName: system-node-critical` comes from, maybe the file had not been regenerated after previous changes?

2019-11-08 20:28 UTC, aanm commented
> Should be in better shape now, I wrote this in github without testing anything :)
> 
> Not sure why `enable-debug` was toggled to false or where ` priorityClassName: system-node-critical` comes from, maybe the file had not been regenerated after previous changes?

Yes, they haven't. The `priorityClassName: system-node-critical` needs to be removed manually for now. Sorry

2019-11-11 10:51 UTC, aanm commented
test-me-please

2019-11-11 23:32 UTC, joestringer commented
So `priorityClassName: system-node-critical` still needs to be removed from the PR? Also would be good to squash the commits into one.

2019-11-12 02:21 UTC, jraby commented
Should be in better shape now.

2019-11-12 03:11 UTC, joestringer approved these changes

2019-11-12 03:11 UTC, joestringer commented
test-me-please

2019-11-12 08:46 UTC, aanm approved these changes

2019-11-12 08:46 UTC, merged