vendor: point vishvananda/netlink back to upstream
cilium/cilium pull request #9606
Opened 2019-11-13 19:33 UTC by borkmann

Given PR https://github.com/vishvananda/netlink/pull/498 has been
merged officially, move the repo back to upstream. Final follow-up
to 515654b58beb ("vendor: fix stack corruption from retrieving
veth peer index"). Re-performed same update as in 515654b58beb.

Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

2019-11-13 19:35 UTC, borkmann commented
test-me-please

2019-11-13 22:16 UTC, aanm requested changes
from master branch, please apply:
```patch
diff --git a/go.mod b/go.mod
index 4d2dc94e8..267428368 100644
--- a/go.mod
+++ b/go.mod
@@ -497,7 +497,7 @@ replace (
        github.com/ugorji/go => github.com/ugorji/go v1.1.4
        github.com/urfave/cli => github.com/urfave/cli v1.20.0
        github.com/urfave/negroni => github.com/urfave/negroni v1.0.0
-       github.com/vishvananda/netlink => github.com/cilium/netlink v1.0.1-0.20191111102915-47ae870a10ed
+       github.com/vishvananda/netlink => github.com/vishvananda/netlink v1.0.1-0.20191113183427-d71301a47b60
        github.com/vishvananda/netns => github.com/vishvananda/netns v0.0.0-20190625233234-7109fa855b0f
        github.com/vmware/govmomi => github.com/vmware/govmomi v0.20.1
        github.com/xiang90/probing => github.com/xiang90/probing v0.0.0-20190116061207-43a291ad63a2
```
and then run:
`./contrib/go-mod/update-vendor.sh`

2019-11-13 22:38 UTC, borkmann commented
test-me-please

2019-11-13 22:40 UTC, borkmann commented
> from master branch, please apply:
> 
> ```diff
> diff --git a/go.mod b/go.mod
> index 4d2dc94e8..267428368 100644
> --- a/go.mod
> +++ b/go.mod
> @@ -497,7 +497,7 @@ replace (
>         github.com/ugorji/go => github.com/ugorji/go v1.1.4
>         github.com/urfave/cli => github.com/urfave/cli v1.20.0
>         github.com/urfave/negroni => github.com/urfave/negroni v1.0.0
> -       github.com/vishvananda/netlink => github.com/cilium/netlink v1.0.1-0.20191111102915-47ae870a10ed
> +       github.com/vishvananda/netlink => github.com/vishvananda/netlink v1.0.1-0.20191113183427-d71301a47b60
>         github.com/vishvananda/netns => github.com/vishvananda/netns v0.0.0-20190625233234-7109fa855b0f
>         github.com/vmware/govmomi => github.com/vmware/govmomi v0.20.1
>         github.com/xiang90/probing => github.com/xiang90/probing v0.0.0-20190116061207-43a291ad63a2
> ```
> 
> and then run:
> `./contrib/go-mod/update-vendor.sh`

This was exactly what I did. Are you asking as I need to rebase, or why `./contrib/go-mod/update-vendor.sh` is pulling in all these direct dependencies? I don't know yet.. maybe golang version related?

2019-11-13 23:59 UTC, borkmann commented
test-me-please

2019-11-14 00:03 UTC, aanm approved these changes

2019-11-14 07:26 UTC, merged