Fixes kafka-v1.yaml file for compatibility
cilium/cilium pull request #9607
Opened 2019-11-13 23:43 UTC by swami-dvr

Fixes:  Compatibility issue seen in the kafka-v1.yaml file while trying to test the Getting Started with Istio guide.
Based on the Kubernetes description for using StatefulSet  "You must set the .spec.selector field of a StatefulSet to match the labels of its .spec.template.metadata.labels. Prior to Kubernetes 1.8, the .spec.selector field was defaulted when omitted. In 1.8 and later versions, failing to specify a matching Pod Selector will result in a validation error during StatefulSet creation."

Fixes: #9603
Signed-off-by:  Swaminathan Vasudevan <svasudevan@suse.com>

2019-11-13 23:50 UTC, joestringer requested changes
Looks good, just one nit: The signoff line should appear in the commit message for each patch (in this case just the one). I think you should be able to fix this up with a simple `git commit --amend -s`.

2019-11-13 23:57 UTC, swami-dvr commented
> Looks good, just one nit: The signoff line should appear in the commit message for each patch (in this case just the one). I think you should be able to fix this up with a simple `git commit --amend -s`.

Not sure what you meant. I only see one signedoff message. Can you clarify.

2019-11-14 00:14 UTC, joestringer commented
@swami-dvr The actual commit does not have the sign-off:

https://github.com/cilium/cilium/pull/9607/commits/c680b4ce21a59f70a223083c61379ebd0bce80c2

2019-11-14 00:35 UTC, swami-dvr commented
> @swami-dvr The actual commit does not have the sign-off:
> 
> [c680b4c](https://github.com/cilium/cilium/commit/c680b4ce21a59f70a223083c61379ebd0bce80c2)

That's odd, in my view I am seeing the signoff may be I might have a newer version then the one that I pushed. Let me see what went wrong.
![ciliumpr](https://user-images.githubusercontent.com/7094327/68816544-a59f4a00-0633-11ea-8418-d22d5a7412ec.jpg)

2019-11-14 01:45 UTC, ianvernon commented
@swami-dvr your commit message itself needs to have the sign-off, not the PR description. See your commit message here: https://github.com/cilium/cilium/pull/9607/commits/c680b4ce21a59f70a223083c61379ebd0bce80c2

2019-11-14 22:44 UTC, soumynathan commented
Use https://github.com/cilium/cilium/pull/9615 instead of this pull request.

2019-11-14 22:56 UTC, joestringer commented
Closing, the other PR was merged.

2019-11-14 22:56 UTC, closed without merging