Deprecate/Delete support for monitor v1.0 socket
cilium/cilium pull request #9650
Opened 2019-11-22 20:37 UTC by soumynathan

The monitor v1.0 socket protocol has not been used since Cilium
v1.2, which is well past support so we should be able to remove
all code associated with monitor v1.0 socket handling as per
the recomendation.

Fixes: #8955

Signed-off-by: Swaminathan Vasudevan <svasudevan@suse.com>

2019-11-22 21:14 UTC, mrostecki commented
test-me-please

2019-11-22 21:14 UTC, vadorovsky approved these changes

2019-11-22 21:56 UTC, joestringer approved these changes
LGTM.

FYI you don't need to open a whole new PR, you should be able to just do a `git push --force <branch>` to replace the code on the branch on github. We can take this one though, just letting you know for the future.

2019-11-25 14:49 UTC, aanm requested changes
All good from a code side perspective. Can you add some documentation notes in `Documentaion/install/upgrade.rst` that support for monitor 1.0 was removed?

2019-11-25 19:54 UTC, soumynathan commented
> All good from a code side perspective. Can you add some documentation notes in `Documentaion/install/upgrade.rst` that support for monitor 1.0 was removed?

Sure will add an note in the documentation.

2019-11-25 23:12 UTC, joestringer commented
test-me-please

2019-11-25 23:12 UTC, joestringer approved these changes

2019-11-25 23:12 UTC, joestringer commented
test-docs-please

2019-11-26 12:35 UTC, aanm approved these changes

2019-11-26 12:37 UTC, aanm commented
@soumynathan can you do a push --force into this branch? I accidentally created a merge commit.

2019-11-26 18:59 UTC, soumynathan commented
> @soumynathan can you do a push --force into this branch? I accidentally created a merge commit.

@aanm  I just did a force push.

2019-11-26 19:13 UTC, aanm approved these changes
Thank you!

2019-11-26 19:13 UTC, aanm commented
test-me-please

2019-11-29 02:06 UTC, tgraf commented
Great work @soumynathan

2019-11-29 02:06 UTC, merged