CI: Wait longer for monitor output in DataPathConfiguration
cilium/cilium pull request #9707
Opened 2019-12-04 17:37 UTC by raybejjani

When running on EKS, the timing seems different from the CI cluster.
Simple checks for the occurence of packets in the monitor output seem
racey and the monitor output being scanned seems truncated, as opposed
to missing the packets completely. The collection function now waits 10s
for the output. It would be better to parse the output live with a
timeout but that is a much larger refactor.

2019-12-04 17:38 UTC, raybejjani commented
test-me-please

2019-12-04 17:56 UTC, raybejjani commented
test-docs-please

2019-12-04 22:13 UTC, ianvernon approved these changes
The joys of different behavior across different environments :/

2019-12-05 09:36 UTC, aanm approved these changes
@raybejjani needs rebase

2019-12-05 10:50 UTC, joestringer reviewed
This is trying to ensure that the monitor is actually running and receiving events, right? Do you think there's some event we could guarantee will occur, which we could wait and try to read from the monitor output? This way we wouldn't have to always wait 10s regardless of the environment?

Could it be something as simple as scanning for lines like this?

```
Press Ctrl-C to quit
level=info msg="Initializing dissection cache..." subsys=monitor
```

2019-12-05 19:42 UTC, soumynathan requested changes
There is a typo in the commit message. 'racey'. 
Otherwise looks good to me.

2019-12-09 12:29 UTC, raybejjani commented
@joestringer Yup, it would be far better. In fact, it would be better still to parse the output stream for the match on the fly with a timeout. It was a bigger refactor so I avoided it.
The direct blocker is how we collect the output from commands. It isn't an `io.Reader` but a custom `Buffer` type that mutex-wraps a `bytes.Buffer`. We slurp it all up at the end of tests and search the collected bytes. From what I remember the wiring around it is a goroutine moving bytes about so it should be possible to read the buffers as they are written.

Since this wasn't a guaranteed fail, I'll mark this WIP here until the other things are running. Perhaps it was an accident of the region. I can also do the larger rebase if you (or anyone) prefers.

2020-01-21 14:39 UTC, raybejjani commented
Closing this for now. I'm not sure if we'll need to merge something like it since the flake isn't as prevalent anymore.

2020-01-21 14:39 UTC, closed without merging