Improve the 'Setting up Cluster Mesh' page.
cilium/cilium pull request #9725
Opened 2019-12-09 09:12 UTC by bmcstdio

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](http://docs.cilium.io/en/stable/contributing/contributing/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue. 
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](http://docs.cilium.io/en/stable/contributing/contributing/#dev-coo).
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

This PR updates the _Setting up Cluster Mesh_ page in order to suggest that services of type `NodePort` are also supported, following https://github.com/cilium/clustermesh-tools/pull/1.

Fixes: N/A

2019-12-09 12:34 UTC, joestringer commented
test-docs-please

2019-12-09 17:12 UTC, aanm approved these changes

2019-12-09 17:14 UTC, aanm requested changes

2019-12-09 17:14 UTC, aanm commented on Documentation/gettingstarted/clustermesh.rst
> +   This can also be done by passing `--set global.cluster.id=<id>` and
needs to be double ` between `--set global.cluster.id=<id>`

2019-12-09 17:14 UTC, aanm commented on Documentation/gettingstarted/clustermesh.rst
> +   `--set global.cluster.name=<name>` to `helm template` when installing or
needs to be double ` between `--set global.cluster.name=<name>` and `helm template`

2019-12-09 22:28 UTC, joestringer reviewed
Thanks for the contribution!

It looks like the `make test-docs` target is failing, most likely due to the areas that @aanm commented on. Otherwise LGTM. You can feel free to ignore the `maintainers-little-helper` failures below, we're working through some issues in the github actions we use.

2019-12-10 08:13 UTC, bmcstdio commented
@aanm @joestringer thank you for your reviews, I've updated the branch accordingly. :+1:

2019-12-10 09:42 UTC, aanm commented
test-docs-please

2019-12-10 13:49 UTC, joestringer approved these changes

2019-12-10 13:49 UTC, merged

2019-12-10 13:53 UTC, bmcstdio commented
@aanm @joestringer thank you for your feedback! I don't know how the publishing process for documentation works, but I believe that https://github.com/cilium/clustermesh-tools/pull/1 should be merged before this gets published. 🙂