[DO NOT MERGE] K8s tests multi node
cilium/cilium pull request #980
Opened 2017-06-14 16:13 UTC by aanm

2017-06-17 00:47 UTC, michi-covalent commented on Jenkinsfile
> +                        "K8s Tests": { sh './tests/k8s/start' }
i guess you need a comma here?

2017-06-17 00:55 UTC, aanm commented on Jenkinsfile
> +                        "K8s Tests": { sh './tests/k8s/start' }
Thanks!

2017-06-17 08:05 UTC, tgraf requested changes

2017-06-17 08:05 UTC, tgraf commented on tests/helpers.bash
> +        sleep 2s
Let's use `micro_sleep` as well.

2017-06-17 08:05 UTC, tgraf commented on tests/helpers.bash
> +        sleep 2s
`micro_sleep`

2017-06-17 08:05 UTC, tgraf commented on tests/k8s/multi-node/cluster/cilium/rbac.yaml
> +kind: ClusterRole
Can we use `examples/kubernetes/rbac.yaml` instead?

2017-06-17 08:05 UTC, tgraf commented on tests/k8s/multi-node/helpers.bash
> +    docker logs ${cilium_id}
Indentations

2017-06-17 08:05 UTC, tgraf commented on tests/k8s/multi-node/Vagrantfile
> +docker build -t cilium:build_test /home/vagrant/go/src/github.com/cilium/cilium
We already have a way to build an image and push it to a registry, can we use this instead:

`tests/k8s/Vagrantfile:`
```
$build = <<SCRIPT
docker run -d -p 5000:5000 registry
cd /home/vagrant/go/src/github.com/cilium/cilium/
docker build -t cilium:build_test /home/vagrant/go/src/github.com/cilium/cilium
export ID=$(docker images | grep "build_test" | awk '{print $3}')
docker tag $ID localhost:5000/cilium:build_test
docker push localhost:5000/cilium:build_test
SCRIPT
```

2017-06-29 17:27 UTC, aanm commented
there are some changes that needs to be done in the kubeadm itself to support IPv6, for now it's only possible to test IPv4 tests

2017-06-29 21:25 UTC, ianvernon reviewed
Comments are mostly cosmetic. Looks great for the most part - this will be a very helpful addition to our test suite!

2017-06-29 21:25 UTC, ianvernon commented on tests/k8s/multi-node/README.md
> +    kubernetes and cilium files generation. It is also in charge on setting up
in charge of setting up

2017-06-29 21:25 UTC, ianvernon commented on tests/helpers.bash
> +
These functions should ensure that the correct number of arguments are provided and error out if an unexpected amount of arguments are provided.

2017-06-29 21:25 UTC, ianvernon commented on tests/k8s/multi-node/README.md
> +    and deploy a fully kubernetes cluster with etcd running. On this file is
"On this file is possible to change a couple options, such as etcd version and k8s version among others." --> "This file has several configurable options, like the version of etcd and k8s.

2017-06-29 21:25 UTC, ianvernon commented on tests/k8s/multi-node/README.md
> +    - `deployments/` - yaml files to be managed for each runtime tests.
runtime test.

2017-06-29 21:25 UTC, ianvernon commented on tests/k8s/multi-node/README.md
> +- `run-tests.bash` - script that is in charge of running the runtime tests, to
change to "in charge of running the runtime tests, setting up of the IPv6 environment for the cluster, and running of the runtime tests in IPv6."

2017-06-29 21:25 UTC, ianvernon commented on tests/k8s/multi-node/README.md
> +When running `vagrant up` there will be 2 VMs, `cilium-k8s-master` and
Running `vagrant up` will start 2 VMs: `cilium-k8s-master` and `cilium-k8s-node-2`.

2017-06-29 21:25 UTC, ianvernon commented on tests/k8s/multi-node/README.md
> +kube-controller-manager, kube-scheduler and a kubelet instance running where all
... and a kubelet instance. All Kubernetes components are spawned by kubeadm.

2017-06-29 21:25 UTC, ianvernon commented on tests/k8s/multi-node/README.md
> +This node will have the 3 static IPs and 2 interfaces:
... will have 3 static IPs...

2017-06-29 21:25 UTC, ianvernon commented on tests/k8s/multi-node/README.md
> +`cilium-k8s-node-2` will only container a kubelet instance running.
... will only contain ...

2017-06-29 21:25 UTC, ianvernon commented on tests/k8s/multi-node/README.md
> +Kubernetes will be running in IPv4 mode by default, to run on IPv6 mode, after
... by default; to run with IPv6 mode, ...

2017-06-29 21:25 UTC, ianvernon commented on tests/k8s/multi-node/README.md
> +This will reset the kubernetes cluster to it's initial state.
Good idea adding this command to clear state!!

2017-06-29 21:25 UTC, ianvernon commented on tests/k8s/multi-node/README.md
> +option on the first command.
... without providing the `--ipv6` option to the first command.

2017-06-29 21:25 UTC, ianvernon commented on tests/k8s/multi-node/README.md
> +This command only needs to be executed in one of the nudes as kubernetes daemon
executed in one of the nodes; since Cilium is deployed as a DaemonSet, Kubernetes will deploy it on each node accordingly.

2017-06-29 21:25 UTC, ianvernon commented on tests/k8s/multi-node/README.md
> +Cilium will also be connecting to etcd and kubernetes using TLS.
...will also connect to...

2017-06-29 21:25 UTC, ianvernon commented on tests/k8s/multi-node/README.md
> +In loadbalancer mode, the `cilium-k8s-master` will run a daemon set for designed
... designed for this purpose ...

2017-06-29 21:25 UTC, ianvernon commented on tests/k8s/multi-node/Vagrantfile
> +$build_docker_image = <<SCRIPT
It would be nice to have some comments before each script section outlining what they do.

2017-06-29 21:25 UTC, ianvernon commented on tests/k8s/multi-node/Vagrantfile
> +ip r a 10.12.0.1/32 dev enp0s8
Please confirm - this will not be needed after the multi-node setup changes?

2017-06-29 21:25 UTC, ianvernon commented on tests/k8s/multi-node/cluster/cluster-manager.bash
> +esac
Easy to understand what's going on / how you are setting things up!!

2017-06-29 21:25 UTC, ianvernon commented on tests/k8s/multi-node/tests/01-guestbook-test.sh
> +# - Rewrite the test when the ingress controller is fixed.
We should have Github issues for TODO's.

2017-06-29 21:25 UTC, ianvernon commented on tests/k8s/multi-node/run-tests.bash
> +# Set up cilium-lb-ds and cilium-ds
Please create a Github issue to re-enable once they work accordingly so we don't lose track of the tests being disabled.

2017-06-29 21:25 UTC, ianvernon commented on tests/k8s/multi-node/tests/01-guestbook-test.sh
> +    # FIX ME finish this test case once we have LB up and running
Please make sure there is a GitHub issue tracking this.

2017-06-29 21:25 UTC, ianvernon commented on tests/k8s/multi-node/tests/01-guestbook-test.sh
> +if [ $? -eq 0 ]; then abort "guestbook-web policy found in cilium and they should have been cleaned" ; fi
...found in cilium; policy should have been deleted

2017-06-29 21:25 UTC, ianvernon commented on tests/k8s/multi-node/tests/01-guestbook-test.sh
> +if [ $? -eq 0 ]; then abort "guestbook-redis policy found in cilium and they should have been cleaned" ; fi
...found in cilium; policy should have been deleted

2017-06-29 21:25 UTC, ianvernon commented on tests/k8s/multi-node/tests/ipv4/ipv4.sh
> +
Please create a ticket to finish this / the ipv6 tests.

2017-06-29 21:52 UTC, tgraf approved these changes
Looks great overall! 👍 

I have some ideas for improvement but this is a great start.

2017-06-30 04:48 UTC, aanm commented on tests/k8s/multi-node/Vagrantfile
> +ip r a 10.12.0.1/32 dev enp0s8
correct

2017-06-30 04:51 UTC, aanm commented on tests/k8s/multi-node/tests/ipv4/ipv4.sh
> +
It's not unfinished, it's just a template so we can start using them if we want to create a dedicated IPv4 / IPv6 tests.

2017-06-30 05:36 UTC, merged

2017-06-30 17:46 UTC, ianvernon commented on tests/k8s/multi-node/tests/ipv4/ipv4.sh
> +
Makes sense, thanks!