tests: remove sleep calls
cilium/cilium pull request #982
Opened 2017-06-14 21:41 UTC by scanf

**Nota bene: this is just a test to see the jenkins build output**

2017-06-15 10:51 UTC, tgraf requested changes
This is awesome, see comments around requirement for a micro sleep in all the loops.

2017-06-15 10:51 UTC, tgraf commented on tests/05-cni.sh
> +	contid=$(docker run -t -d --net=none $LABELS busybox:latest)
This looks wrong. The sleep here ensures that the container keeps running, otherwise it will exit immediately.

2017-06-15 10:51 UTC, tgraf commented on tests/09-perf-gce.sh
> +    echo -n "."
This will spam the log, we need a minimal sleep here. This could be `sleep 0.5`

2017-06-15 10:51 UTC, tgraf commented on tests/09-perf-gce.sh
> -    sleep 2s
Same here

2017-06-15 10:51 UTC, tgraf commented on tests/10-proxy.sh
> +	    fi
Need a minimal sleep here as well

2017-06-15 10:51 UTC, tgraf commented on tests/k8s/k8s-gsg-test.sh
> +    fi
Needs sleep

2017-06-15 10:51 UTC, tgraf commented on tests/00-no-sleep.sh
> +    exit 1
I like this a lot.

I think we can keep this but ignore the helper.sh script and have a function `micro_sleep` which does `sleep 0.5` and we can insert this in all the loops which should relax the CPU a bit.

2017-06-15 11:16 UTC, scanf commented on tests/05-cni.sh
> +	contid=$(docker run -t -d --net=none $LABELS busybox:latest)
@tgraf Why wouldn't the container continue running when a tty is attached?

2017-06-15 11:30 UTC, tgraf commented on tests/05-cni.sh
> +	contid=$(docker run -t -d --net=none $LABELS busybox:latest)
@scanf You are right, I didn't see that you added `-t`. Looks good then.

2017-06-15 16:31 UTC, tgraf approved these changes

2017-06-15 23:50 UTC, merged

2017-06-22 04:48 UTC, ianvernon commented
Was OOO, but wanted to say thanks for this ! Getting a good library of helper functions for our tests will pay off !