daemon: remove bindata from git
cilium/cilium pull request #988
Opened 2017-06-15 09:34 UTC by scanf

2017-06-22 16:28 UTC, tgraf requested changes

2017-06-22 16:28 UTC, tgraf commented on daemon/Makefile
> +GO_BINDATA_SHA1SUM=4c07b9aaa78073a929aa67dc4bcb862de58d7522
Can you add a comment here that the value of this variable can be updated with `make -C daemon apply-bindata`?

2017-06-22 16:28 UTC, tgraf commented on daemon/Makefile
> +GO_VERSION_USED=go1.8.3
Is the expectation that we notice incompatible go versions by seeing this value changing in a patch?

2017-06-22 17:11 UTC, scanf commented on daemon/Makefile
> +GO_VERSION_USED=go1.8.3
Yes.

2017-06-22 17:11 UTC, scanf commented on daemon/Makefile
> +GO_BINDATA_SHA1SUM=4c07b9aaa78073a929aa67dc4bcb862de58d7522
Done

2017-06-23 04:34 UTC, tgraf approved these changes
Awesome! I love this.

2017-06-23 04:34 UTC, merged