Add support for HealthCheckNodePort in NodePort BPF
cilium/cilium pull request #9906
Opened 2020-01-20 15:46 UTC by gandro

This adds the `HealthCheckNodePort` field to the service manager package and related types and starts a HTTP server on that port if set. This feature is used by external loadbalancers to determine whether a certain node contains a local backend. When a service has local backends, the HTTP server on the specified port returns `HTTP 200`, otherwise it returns `503 Service Unavailable`. The implementation inside the new `service/healthserver` provides the same JSON output as `kube-proxy`.

The health check server is only enabled for a given service if it has a non-zero `HealthCheckNodePort`. This value may only be set in Kubernetes if a service has `externalTrafficPolicy=Local` and its type is `LoadBalancer`. Our current implementation is a bit more relaxed, it relies on the K8s API to enforce the constraint, since we do not know the original Kubernetes service type.

Review per commit. Ginkgo run-time tests will be added in a separate PR.

Fixes: #8699

2020-01-20 15:46 UTC, gandro commented
test-me-please

2020-01-20 16:13 UTC, gandro commented
test-me-please

2020-01-20 19:24 UTC, gandro commented
test-me-please

2020-01-20 19:25 UTC, gandro commented
test-missed-k8s

2020-01-21 08:35 UTC, gandro commented
test-missed-k8s

2020-01-21 09:53 UTC, brb requested changes
LGTM except for a few nits!

Also, would be good to have CI tests for this, and `Documentation/gettingstarted/nodeport.rst` needs update (both can be done in a follow-up).

2020-01-21 09:53 UTC, brb commented on pkg/service/healthserver/healthserver.go
> +type healthServerFactory interface {
Maybe `s/healthServerFactory/healthHTTPServerFactory/` and `s/newHealthServer/newHealthHTTPServer` to better distinguish from `ServiceHealthServer` (the user of the factory method and the interface)?

2020-01-21 09:53 UTC, brb commented on pkg/service/healthserver/healthserver.go
> +	portByServiceID     map[uint16]uint16
`s/uint16/loadbalancer.ServiceID/`?

2020-01-21 13:32 UTC, gandro commented
@brb Addressed your nits.

--

[Cilium-PR-Ginkgo-Tests-K8s](https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2745/console) failed with `The Service "istio-ingressgateway" is invalid: spec.ports[2].nodePort: Invalid value: 31390: provided port is already allocated`. It looks like the statically defined `nodePort`s in the Istio tests clashed with some randomly allocated ports (I was unable to figure out where the randomly allocated ports were used though).

I while I believe that the failure is *not* caused by this PR (because the port random allocation and rejection both comes from the API server which is not affected by the changes here), it's something we should keep in mind for the future. Adding CI tests which set static `healthCheckNodePorts` will also run into the danger of conflicting with randomly allocated node ports. Not sure if there is something that can be done about it however (except not setting static node ports, and always have them allocated randomly).

2020-01-21 13:34 UTC, gandro commented
test-me-please

2020-01-21 13:52 UTC, brb approved these changes

2020-01-21 15:10 UTC, gandro commented
test-me-please

2020-01-21 19:06 UTC, borkmann approved these changes

2020-01-21 19:07 UTC, merged

2020-02-04 12:50 UTC, gandro commented
test-me-please