Fix issue that BPF system config check fail
cilium/cilium pull request #9910
Opened 2020-01-21 05:02 UTC by Jianlin-lv

Bpftool can't open file:"/boot/config-% s"
the main reason is without mounting /boot into container,
thus bpftool skipping kernel config.

Signed-off-by: Jianlin Lv <Jianlin.Lv@arm.com>

Fixes: #9838

2020-01-21 05:08 UTC, Jianlin-lv commented
Continue to discuss the comments of https://github.com/cilium/cilium/pull/9840#issuecomment-576515682

2020-01-22 10:44 UTC, mrostecki commented
I'm wondering how the previous kernel checks worked if there was no access to /boot and IKCONFIG was disabled. I need to investigate.

2020-01-22 15:27 UTC, Jianlin-lv commented
> I'm wondering how the previous kernel checks worked if there was no access to /boot and IKCONFIG was disabled. I need to investigate.

I think the same issue existed in the previous cilium version. Cilium v1.6.4 logs as follows:
![image](https://user-images.githubusercontent.com/19404437/72907358-b4f6ee00-3d6e-11ea-98ac-0ea2e06fe1c2.png)
Related code:
https://github.com/cilium/cilium/blob/v1.6.4/bpf/run_probes.sh#L62

2020-02-18 23:33 UTC, aanm requested changes
I think this was discussed on a different PR? We can't add those mounting points to Cilium. @borkmann do you remember the GH issue that we have discussed this?

2020-03-02 12:12 UTC, rreinurm commented
Based on discussion from https://github.com/cilium/cilium/pull/9840 mounting /boot is not recommended. What can be solution for Linux distributions which have disabled IKCONFIG?

2020-03-08 02:28 UTC, iecedge commented
> Based on discussion from #9840 mounting /boot is not recommended. What can be solution for Linux distributions which have disabled IKCONFIG?
 Perhaps we can use the netlink library to detect BPF on distribution version.
I`m trying to update this patch using Netlink.

2020-03-08 02:30 UTC, Jianlin-lv commented
> Based on discussion from #9840 mounting /boot is not recommended. What can be solution for Linux distributions which have disabled IKCONFIG?

Perhaps we can use the netlink library to detect BPF on distribution version.
I`m trying to update this patch using Netlink.

2020-03-09 09:25 UTC, brb commented
The alternative solution is to have probes for each individual feature we require, and then we don't have to rely on the kernel config for that.

2020-05-06 10:26 UTC, pchaigno commented
The issue this pull request is trying to address (`Kernel config not found`) is fixed in Cilium v1.7. Since #9789, we don't rely on `/boot/config-*` or similar file to detect BPF features. Instead [we use `bpftool feature probe`](https://github.com/cilium/cilium/blob/6fc0b5b09d41dc4968290ced850da5c181847a40/pkg/datapath/linux/probes/probes.go#L140).

2020-05-06 10:26 UTC, closed without merging