bpf, sock: reduce xlation for externalTrafficPolicy=Local to host_id
cilium/cilium pull request #9930
Opened 2020-01-22 15:35 UTC by borkmann

See commit msg. /cc @brb @gandro

2020-01-22 17:45 UTC, gandro requested changes
The approach looks good to me! Since I'm still not super familiar with the logic: What happens if the connection is not translated? Is the host set up to forward the packet to the remote host or will we just drop it?

2020-01-22 17:45 UTC, gandro commented on pkg/maps/lbmap/lbmap.go
> -	ipv6 bool, svcType loadbalancer.SVCType) error {
You will need to update https://github.com/cilium/cilium/blob/c6e876c1ac568db853af21ccde5445cef9da1a5e/pkg/maps/lbmap/lbmap_mock.go#L36-L37 as well.

2020-01-22 17:54 UTC, borkmann commented
> The approach looks good to me! Since I'm still not super familiar with the logic: What happens if the connection is not translated? Is the host set up to forward the packet to the remote host or will we just drop it?

The request will go through untranslated, so depending on the service type if this is routable and we end up on the remote node (e.g. nodeport), then there won't be any backends on that node and therefore the skb will be dropped.

2020-01-23 13:16 UTC, gandro approved these changes

2020-01-23 13:22 UTC, borkmann commented
test-me-please

2020-01-23 13:53 UTC, borkmann commented
test-me-please

2020-01-23 13:55 UTC, borkmann commented
test-me-please

2020-01-23 15:21 UTC, borkmann commented
test-me-please

2020-01-23 15:26 UTC, borkmann commented
Jenkins provisioning issue:
```[Pipeline] // node
[Pipeline] End of Pipeline
Setting status of 84ae46ccc591b34690aee2d13d8e0136a17c43f4 to FAILURE with url https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/16574/ and message: 'Build finished. '
Using context: Cilium-Ginkgo-Tests
15:24:33  Terminated
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)```

2020-01-23 15:26 UTC, borkmann commented
test-me-please

2020-01-23 15:33 UTC, borkmann commented
test-me-please

2020-01-23 15:54 UTC, brb requested changes
I think you need to update this as well: https://github.com/cilium/cilium/blob/master/pkg/service/service.go#L537.

2020-01-23 20:40 UTC, borkmann commented
test-me-please

2020-01-23 21:25 UTC, borkmann commented
test-me-please

2020-01-23 23:12 UTC, merged